### ISSUE TITLE
trial 85-95 laevateinn

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#1]
**Date & Time**:  25/05/2015
**Frequency**: all time 
**FFXi Client Version**: 30150508_5
**Character Name**:rikiki
**Race**: tarutaru
**Main Job**: blm
**Sub Job**: rdm
**Area & Coordinates X:7 Y:0 Z:-67 (202)
**Party or Solo**:
**NPC Name**: AKTA
**Monster Name**:
**Steps To Reproduce The Issue**: akta do not accept laevateinn for new challenge 85-95 
when i trade nothing happen :)

**Comment by bathuka** [comment]
trading
http://img11.hostingpics.net/pics/696048Rikiki20150526151152.png
no trial
http://img11.hostingpics.net/pics/567726Rikiki20150526151209.png

**Comment by bathuka** [comment]
Excuse me teo you think for Tuesday maint will fix the trialbug ?
or i screen all kill as with previous trial :)

**Comment by TeoTwawki** [comment]
@bathuka its fixed now.

**Comment by TeoTwawki** [comment]
If further issue with same trial, can post here and I'll re-open issue if need be.
