### ISSUE TITLE
Summoners Doublet +2 Gives no Perpetuation -

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#10]
**Date & Time**: 5/26/15
**Frequency**: NA
**FFXi Client Version**: 20150508_8
**Character Name**: Tarot
**Race**: Hume
**Main Job**: Smn 92
**Sub Job**: NA
**Area & Coordinates (Type @where to get this info.)**: NA
**Party or Solo**: NA
**NPC Name**: NA
**Monster Name**: NA
**Steps To Reproduce The Issue**: Equip summoner's doublet +2, get no perpetuation cost -, should be -3

**Comment by R3P0FFXI** [comment]
Added Mod 346 +3
