### ISSUE TITLE
Item not showing on AH (Gunman gambison)

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#100]
**Date & Time**: 6/15/2015 8:55 pm
**Frequency**: always
**FFXI Client Version**:30150508_8
**Character Name**: Baucant
**Race**: Elvaan
**Main Job**: Thf
**Sub Job**: Dnc
**Area & Coordinates**: Sothern Sandy X:-9 Y:1 Z:-30 (97)
**Party or Solo**: solo
**NPC Name**: Auction House
**Monster Name**:N/A
**Steps To Reproduce The Issue**: Placed item on AH. Check sales status to confirm it's on AH but can not find it under armor > body for someone who might want to buy. I tried zoning loging off and on still can not see the item for sale on the AH.

**Comment by Baucant** [comment]
just checked a few othere Items and they fall under the same issue Oxossi facon+1, Magavan slops & Tlamiztli collar These are being sold by Dapunted

**Comment by itachioax** [comment]
is not a regular armor, btw tyranic scorpion in ifrit's cauldron drops it

**Comment by Baucant** [comment]
yeah thats where i got it from. but i don't want it and it is AH able.

**Comment by Loki79** [comment]
bazzar it.

**Comment by Loki79** [comment]
Resolving this would mean editing the bot which is currently blocking it from being auto-stocked.  If you want to farm and sell items that are blocked by the bot that's fine but you will need to bazzar them.  Closing this out.
