### ISSUE TITLE
Leathercraft 95 bugged in Piest Mantler?

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#1000]
Date & Time: 6-29-16 10am hst

FFXI Client Version (use  /ver ): 30160602_0

Character Name: Dimma

Nation: Sandy

Job(level)/Sub Job(level): 
 blu99/rdm49

NPC or Monster or item Name: 
 Dimma Craft Leathercraft Lv95.

Zone name & Coordinates (use  @where ): 
 San'doria

ffxiah.com link (for items issues only): 

Multi-boxing? (multiple clients on same connection): 
 No

I was upping leathercraft and doing Peiste skin x2 + Grass Thread to made a Peiste Mantle but, it is gonna made a Buskers Earring and Rapture earring, i think it can be a bug?

**Comment by Samikana** [comment]
@R3P0FFXI Buskers Earring and Rapture Earring have the crafting recipe of Peiste Mantle, just checked on the DB search.  Peiste Mantle also has the correct crafting recipe, though.

http://legiondark.com/db/items/15977/buskers_earring
http://legiondark.com/db/items/15978/rapture_earring

**Comment by Samikana** [comment]
Made an edit to the initial report to correct the names of crafting materials, items, and bugged items.

**Comment by R3P0FFXI** [comment]
This has been submitted to DSP and should be corrected shortly

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
