### ISSUE TITLE
Windurst Mission 2-3 Dread Dragon & Seeker fight

### ISSUE THREAD

**Issue by alannor** [LegionDark/Issues#1001]
Please help me push through this mission as per this thread:
http://legiondark.com/forums/viewtopic.php?f=69&t=1225&p=4030&hilit=windurst+mission#p4030

I have been advised that I need to be logged in when this happens. I am in GMT+8 time zone, 12 hours ahead of New York. Please let me know what times work.

**Date & Time**: 06/30/2016 12:16AM (GMT+10)

**FFXI Client Version (use `/ver`)**: 30160602_0

**Character Name**: Alannor

**Nation**: Windurst

**Job(level)/Sub Job(level)**: RDM99/BLM49

**NPC or Monster or item Name**: Dread dragon & Seeker

**Zone name & Coordinates (use `@where`)**: Waugron Shrine

**ffxiah.com link (for items issues only)**: None

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: None

**Comment by R3P0FFXI** [comment]
@alannor this is an old thread we are no longer pushing users through this mission as issues have since been resolved. If you are on a newer client you will need to wait until we complete the update to proceed.

**Comment by alannor** [comment]
I can't do the BCNM fight though

**Comment by alannor** [comment]
Can you at least tell me what the issue is and how long I have to wait?

**Comment by alannor** [comment]
Actually I remember now, 3 of us try to do BCNM 40 in Wauhgron Shrine around 2 weeks ago but couldn't get it to work and even a GM came and tested it. Is the BC actually active?

**Comment by TeoTwawki** [comment]
> If you are on a newer client you will need to wait until we complete the update to proceed.

**Comment by alannor** [comment]
can you at least advise how long? Or if I change nations and avoid Waugron Shrine BCNM it will be possible?

**Comment by alannor** [comment]
Wasn't my intention to update the client, I joined the server two weeks ago

**Comment by TeoTwawki** [comment]
Darkstar itself isn't on the latest client yet.
You are asking for something I _don't have._

update gets done when it gets done. There are fairly regular news posts about it on the forums. This happens everytime there is a client update on retail, because we can't yet control what version you get updated to it always goes from whatever you have to the very latest.
