### ISSUE TITLE
Cannot equip O.Club on PLD

### ISSUE THREAD

**Issue by piglorian** [LegionDark/Issues#1003]
**Date & Time**: 
7/3 11PM CST

**FFXI Client Version (use `/ver`)**: 
30160427_0

**Character Name**: 
Piglorian

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
PLD94/WAR47

**NPC or Monster or item Name**: 
Octave Club

**Zone name & Coordinates (use `@where`)**: 
All

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/18852/octave-club

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Tried to equip O.Club, but will not equip on PLD.  Will equip on other jobs such as BLM, MNK, and THF

**Comment by R3P0FFXI** [comment]
O. Club is a 99 club your PLD is not 99
