### ISSUE TITLE
Atma of the Sundering Slash

### ISSUE THREAD

**Issue by fencedin** [LegionDark/Issues#1004]
**Date & Time**: 7/5/16 11:13am PST

**FFXI Client Version (use `/ver`)**: ver 30160427_0

**Character Name**: Fence

**Nation**: Sandy

**Job(level)/Sub Job(level)**: DRK(99)/SAM(49)

**NPC or Monster or item Name**: Atma of the Sundering Slash

**Zone name & Coordinates (use `@where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: Atma of the Sundering Slash is supposed to give 30TP Regain but is only giving 3TP per tick. Also, it is supposed to only give the TP with 2-Handed weapons but gives it with any weapon I tired (staff/dagger/sword/club).

**Comment by TeoTwawki** [comment]
For now its going to keep working even for 1 hand weapons, till someone creates a latent trigger for 2 handers. the tp being wrong is thanks to dsp changing things again...hotfixing in live right now and will put the change into that massive update legion has coming.
