### ISSUE TITLE
Blades craft transfer

### ISSUE THREAD

**Issue by tobys1556** [LegionDark/Issues#1005]
**Date & Time**: 7/5/16  6:40pm

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Blades

**Nation**: Sandoria

**Job(level)/Sub Job(level)**:85nin/war 

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: would like my cloth craft transferred link below
http://legiondark.com/forums/viewtopic.php?f=37&t=1606

**Comment by Genesis-Legion** [comment]
@tobys1556 I've been checking every so often for you to be online to transfer your crafting but I haven't seen you, leave a message here next time you think you'll be online.

**Comment by tobys1556** [comment]
Should be on tonight around 7:00pm central time zone

**Comment by Genesis-Legion** [comment]
Player's craft has been transferred.
