### ISSUE TITLE
Persikos unattainable

### ISSUE THREAD

**Issue by fgebony** [LegionDark/Issues#1006]
**Date & Time**: 7/5/16 10:59 pm

**FFXI Client Version (use `/ver`)**: 30160427_0

**Character Name**: Pallom

**Nation**: windurst

**Job(level)/Sub Job(level)**: 70blm/35rdm

**NPC or Monster or item Name**:  Persikos (Item Id: 4274)

**Zone name & Coordinates (use `@where`)**: n/a

**ffxiah.com link (for items issues only)**:  http://www.ffxiah.com/item/4274/persikos

**Multi-boxing? (multiple clients on same connection)**:  n/a

**Steps To Reproduce / any other info**:  Item by all accounts is only available via gardening, popular item for crafting skill ups in cooking, is it possible to have AH bot supply a nominal amount since there is no other way to procure item?

**Comment by R3P0FFXI** [comment]
@fgebony I have not gotten to cooking yet no idea when i will

**Comment by fgebony** [comment]
@r3poffxi Thanks for taking a look :)
