### ISSUE TITLE
Can't complete San d'Oria Mission 2-3 "Journey Abroad" 

### ISSUE THREAD

**Issue by Radditz** [LegionDark/Issues#1007]
**Date & Time**: 
July 07, 2016

**FFXI Client Version (use `/ver`)**: 
30160602_0

**Character Name**: 
Radditude

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
79THF/39NIN

**NPC or Monster or item Name**: 
NPC: Savae E Paleade  
Item: Mythril Sand (ex)

**Zone name & Coordinates (use `@where`)**: 
X:23 Y:-16  Z:-43 (250)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/599/mythril-sand

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
I wasn't sure if this was fixed, or something is out of line, but I have no way on continuing the mission at this point as the NPC will not accept the trade. Also another character in the same area and part of the chain, Grohm, never gave me a cutscene ( http://ffxiclopedia.wikia.com/wiki/Grohm ) 

Is it possible that my FFXI version is to new? I hope I put in enough information to find the problem.

**Comment by TeoTwawki** [comment]
> 30160602_0
ID probs most likely, as the server isn't updated yet (neither is darkstar itself, and legion usually takes a few days after them)

**Comment by TeoTwawki** [comment]
I just had an awesome idea about this I have to run by atom0s...

**Comment by Radditz** [comment]
I figured as much. Is there anything I can do in the mean time to get around this, or just wait for the catch up? Thanks for the info though.

I noticed this is a reoccurring thing on the git-hub listings here, so I'm hoping that's relating to your awesome idea.

**Comment by TeoTwawki** [comment]
prolly gonna have to wait for the server update. Its possible something else is at work like a stuck variable, but we can't really know till we catch up at which point we'll just make sure everything works correct with whatever the latest client is.

**Comment by Radditz** [comment]
Sounds good, I'm looking forward to that update. Keep it up guys!

**Comment by TeoTwawki** [comment]
Update regarding that idea I mentioned: I've added a new command (`@ecv`) and atom0s is adding the version display to the sites index page for us. :smiley:

**Comment by Radditz** [comment]
Yeah I saw that on the server while playing. It's a great idea at least. It can help narrow down when people are having problems. :)

**Comment by Aelromi** [comment]
I also have the version Radditz has 30160602_0. Same thing happened to me today.
