### ISSUE TITLE
Mogsafe2 Mogrwardrobe 2 innaccesible and storage empty upon transfer

### ISSUE THREAD

**Issue by Avestaffxi** [LegionDark/Issues#1008]
**Date & Time**:  7/10/2016  8:00 PM

**FFXI Client Version (use `/ver`)**:   3.0.0 I think? Not sure how to check what version the client is 

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**:  yes

**Character Name**: Avesta

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  99 PLD

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  no  

**Steps To Reproduce / any other info**: 

Mogsafe 2 and Mogwardrobe 2 are not accessible(Just greyed out) 
And My storage which was full is now empty 0/0    

I made sure I had no items above lvl 75. Might have forgotten to throw away my gjallarhorn though.

**Comment by R3P0FFXI** [comment]
@Avestaffxi Reset your furniture to get your storage back, Mogsafe 2 does not work never has, Mogwardrobe 2 same thing
