### ISSUE TITLE
Avesta craft import + missing storage/wardrobe2/safe2

### ISSUE THREAD

**Issue by Avestaffxi** [LegionDark/Issues#1009]
**Date & Time**:  7/11/16

**FFXI Client Version (use `/ver`)**:  30160602_0

**Character Name**:  Avesta

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  99 PLD

**NPC or Monster or item Name**:  na

**Zone name & Coordinates (use `@where`)**:  na  

**ffxiah.com link (for items issues only)**:  na

**Multi-boxing? (multiple clients on same connection)**:  na

**Steps To Reproduce / any other info**: 
Craft transfer for Avesta http://legiondark.com/forums/viewtopic.php?f=37&t=1624
Also 
Mogsafe2 Mogwardrobe2 missing (Did not transfer from retail) + Storage empty after server transfer

**Comment by R3P0FFXI** [comment]
@Avestaffxi please read what migrates from retail and what does not this is not retail

**Comment by Avestaffxi** [comment]
> If you transferred form a non retail server and know for a fact that there were items in the second mog safe, please inform me what server you came from ASAP.

This is what it says on the Advisory notice. I read it before transferring from Bnet.cc and assumed it does not apply to me since Bnet is not retail. But theres also the other two containers missing/innacessible

I think overall, nearly 200 items are missing from safe2/wardrobe2/storage including a Dring :(

Sorry for the inconvenience.

**Comment by Genesis-Legion** [comment]
Player's goldsmithing transferred.

**Comment by R3P0FFXI** [comment]
@Avestaffxi Dring would not transfer over nor would any items post 75. This is all outlined on the forums in various topics.

**Comment by TeoTwawki** [comment]
> If you transferred form a non retail server and know for a fact that there were items in the second mog safe, please inform me what server you came from ASAP.

The advisory references retail because mogsafe2 isn't even legitly accessible on darkstar servers...
