### ISSUE TITLE
Cannot use Scroll of Absorb-Attri

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#101]
**Date & Time**: 6/15/15
**Frequency**: Always
**FFXI Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: Hume
**Main Job**: Drk
**Sub Job**: NA
**Area & Coordinates**: NA
**Party or Solo**: NA
**NPC Name**: NA
**Monster Name**: NA
**Steps To Reproduce The Issue**: Cannot use scroll, spell probably not coded

**Comment by Loki79** [comment]
yeah this is going to be right there with the crusade spell you opened and issue with.  Just isn't coded yet.  Will get to it at some point but wont be a priority.
