### ISSUE TITLE
Can't craft (Piece Of Guatambu Lumber)

### ISSUE THREAD

**Issue by diqoo** [LegionDark/Issues#1010]
**Date & Time**: 13/7/16 
13/7/16

**FFXI Client Version (use `/ver`)**: 
30160602_0
**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 

**Character Name**: 
daqoo

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
Thf99/dnc99

**NPC or Monster or item Name**: 
-

**Zone name & Coordinates (use `@where`)**: 
Nsandy x-173 y4 z227 (189)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/4019/gua-lumber

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
Baucant was trying to help me craft Piece Of Guatambu Lumber with 1 wind crstal, 1  Spool Of Bundling Twine, and 3  Urunday Log. It cannot be craft with this receipt. Found the receipt at legiondark item tool. Please confirm :dancer:

**Comment by R3P0FFXI** [comment]
@diqoo 

NQ: Urunday Lumber x3
HQ1:Urunday Lumber x6
HQ2:Urunday Lumber x9
HQ3:Urunday Lumber x12
Main Craft: Woodworking - (92) 
Key Item: Lumberjack

Wind Crystal
Bundling Twine
Urunday Log x3

It can only make urunday lumber so that's obviously wrong in the database

**Comment by R3P0FFXI** [comment]
This has been submitted to DSP and should be corrected shortly

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
