### ISSUE TITLE
Cannot Complete Windhurst Mission 2-3

### ISSUE THREAD

**Issue by Holygara** [LegionDark/Issues#1011]
**Date & Time**: 
July 13th 2016 3:13 PM EST

**FFXI Client Version (use `/ver`)**: 
30160602_0
**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
No

**Character Name**: 
Oujo

**Nation**: 
Windhurst

**Job(level)/Sub Job(level)**: 
Black Mage/White Mage 60/30

**NPC or Monster or item Name**: 
Kindred Crest

**Zone name & Coordinates (use `@where`)**: 
X:-69 Y:-2 Z:33

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
1. Completed all steps up to BCNM fight.  I got all required cutscenes and received the Key Item Kindred Crest.  When attempting to talk to Kasaroro to receive the key item Kindred Report she acts as if no mission was accepted by me.

**Comment by R3P0FFXI** [comment]
@Holygara Expected Client Version: 30160329_0 your version is higher then the code the server is running on when we update this issue will be fixed
