### ISSUE TITLE
Alchemy guildworker rep won't accept items

### ISSUE THREAD

**Issue by Lilneme** [LegionDark/Issues#1012]
**Date & Time**:  7/13/2016 4:12 EST

**FFXI Client Version (use `/ver`)**:  30160602_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**:  no (30160329_0)

**Character Name**:  Nemeria

**Nation**:  Windurst

**Job(level)/Sub Job(level)**:  THF73/DNC36

**NPC or Monster or item Name**: Hemewmew

**Zone name & Coordinates (use `@where`)**: Bastok Mines X:116 Y:2 Z:-10 (211)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  Yes

**Steps To Reproduce / any other info**: Will not accept current requested item (Busuto). After I try to trade her the item, she tells me "You can still receive up to 0 guild points by trading us the item before the time limit is up."

**Comment by Samikana** [comment]
What's your current crafting level?

**Comment by Samikana** [comment]
Closed because they never responded!
