### ISSUE TITLE
 R3P0FFXI here are the char crafts for transfer

### ISSUE THREAD

**Issue by Psyclosis** [LegionDark/Issues#1014]
**Date & Time**: 7/16/16 5:00 am

**FFXI Client Version (use `/ver`)**: 30160329_1

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: No (_0 expect, _1 found)

**Character Name**: Brickz

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 75 ninja / 37 war

i was told to make this post for the transfer of my char crafts the char info has been transferred already i'm submitting
![brickz_2016 07 15_1939501](https://cloud.githubusercontent.com/assets/2892271/16894216/e33d3c84-4b1d-11e6-836b-e50b0e33b2fe.png)
 a pic of the crafts hope im putting this in the right spot.

**Comment by Genesis-Legion** [comment]
Player's crafting has been updated.
