### ISSUE TITLE
Smn quest

### ISSUE THREAD

**Issue by exorial1** [LegionDark/Issues#1015]
**Server's Expected Client Version matches,  no 

Date & Time:16 July 2016 10:15
Frequency:Happened Twice
FFXI Client Version: 30160620_1
Character Name:Exorial
Race:Hume
Main Job:Blu
Support Job:Rdm
Area and Coordinates: na
Party or Solo:solo
NPC Name:na
Monster Name:na
Steps:
1.zoned into area with a weather effect, had black screen for over 5 minutes no cutscene
2.restarted game zoned to same area no cut scene although weather was still there, I have collected all other weathers to see if still worked
3.trading ruby to ??? G-6 LA thiene plat, does nothing and still can't collect missing weathers

**Comment by R3P0FFXI** [comment]
@exorial1 Server version does not match current code  30160329_0, you have update so IDs are off this will not get resolved until we pull in the new update

**Comment by exorial1** [comment]
Ok no problem thank you for the quick reply

**Comment by TeoTwawki** [comment]
@exorial1 still having problems with quest?

**Comment by R3P0FFXI** [comment]
No response closing
