### ISSUE TITLE
Promy 4-2 failed to complete CS due to crash of client

### ISSUE THREAD

**Issue by Hazed69** [LegionDark/Issues#1016]
Date & Time: July 17th 9:02am

FFXI Client Version (use  /ver ): 30160427_0

Server's Expected Client Version matches, yes/no? (use  @ecv ): no ecversion is 30160329_0

Character Name: Hazed

Nation: Bastok

Job(level)/Sub Job(level): 99thf/49dnc  (50thf/25dnc in Mission)

NPC or Monster or item Name: PM mission 4-2 fight

Zone name & Coordinates (use  @where ): Monarch Linn x:-581  Y:82 Z:1 (128)

ffxiah.com link (for items issues only): 

Multi-boxing? (multiple clients on same connection): No

Steps To Reproduce / any other info: Not attempted. Won the fight barely and CS never completed I am now inside uncapped I did crash during the Cutscene however. If I have to redo no biggie just took me a few tries.

**Comment by R3P0FFXI** [comment]
@Hazed69 Expected Client Version: 30160329_0 Wont be fixed until update is ready to go

**Comment by Hazed69** [comment]
ok ty

**Comment by TeoTwawki** [comment]
Please don't change the formatting in the template. It causes issues not just with readability but with function: for example by removing those backticks you triggered [mentions](https://help.github.com/articles/mentions-on-github-pages/) for github accounts named "[ecv](https://github.com/ecv)" and "[where](https://github.com/where)"  (many of darkstars GM commands match up with user names on github).

**Comment by TeoTwawki** [comment]
This has been a recurring problem despite my having set up the automation that places the template with formatting in the input box, so I'd consider it a favor if you'd inform anyone else that you see mention they are about to open a bug report.
