### ISSUE TITLE
Maat fight failed to complete

### ISSUE THREAD

**Issue by Spardante** [LegionDark/Issues#1017]
<img width="960" alt="capture" src="https://cloud.githubusercontent.com/assets/20506368/16903412/88f30996-4c4b-11e6-9d56-71badb415e0a.PNG">

**Date & Time**:
7-17-18  17:48:34 EST

**FFXI Client Version (use `/ver`)**:
30160629_0 

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
30160329_1

**Character Name**: 
Biggie

**Nation**: 
Sand d'Oria

**Job(level)/Sub Job(level)**: 
70 RDM

**NPC or Monster or item Name**: 
Maat BCNM

**Zone name & Coordinates (use `@where`)**: 
Waughroon Shrine (Palborough Mines I-10)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
After obtaining RDM Testimony, I went and traded it to Maat in Ru Lude Gardens.  He offered to fight, and I accepted.  It teleported me to Waughroon Shrine Burning Circle.  I traded the RDM Testimony and started the fight.  After winning the fight (see screenshot for Maat confirming defeat saying "...you've come a long way" at 17:48:34), I was teleported out of the BCNM.  However, it did not confirm the battlefield was completed.

I went back to Maat and talked to him, but he just requested 3 items: papyrus, exoray mold, and bomb coal.  I also tried trading the RDM Testimony back to him, but it just starts the quest again.  See screenshot below.

Is there a way I could at least get credit for completing the fight?  I would hate to have to try again and have it glitch again.  And RDM isn't the easiest Maat fight.

<img width="960" alt="capture" src="https://cloud.githubusercontent.com/assets/20506368/16903479/7fd1bef0-4c4d-11e6-8364-d104487b8f24.PNG">

Thank you!

**Comment by Genesis-Legion** [comment]
It's asking for those items since you didn't have to do Limit break 1 since those're optional, you should have completed limit break 5 with no problems and should be able to level up fine,

**Comment by Spardante** [comment]
Hi there. Thanks for the reply.

I understand that those items are for Limit Break 1, and as you said, I should have completed limit break 5 with no problem.

However, as you can see from the first screenshot, I did beat maat, and I am still capped at 70. It did not complete the quest or remove the cap.

This is the problem. I am worried about spending gil on food and whatnot again if its just going to glitch again.

Do you need me to send you a screenshot showing my level still capped?

**Comment by R3P0FFXI** [comment]
@Spardante glitches happen, we will not push you forward unless absolutely necessary Expected Client Version: 30160329_0 is the current version of the server I am not sure if this is a simple client version issue, 1x glitch that does occasionally happen, or something else. 60k for food is no big deal when every mob drops 1k. Trust me when I say gil is not a huge issue.

**Comment by R3P0FFXI** [comment]
@Spardante please redo the fight, looking over your log it looks like you might have typed @tele dem to soon and its possible that the win did not fully register.

**Comment by Spardante** [comment]
4 minutes is too soon?

**Comment by TeoTwawki** [comment]
The timestamp isn't what matters, what matters is if the event was still running. But don't redo the fight yet. Matter of fact, everyone just stop talking before my head asplodes.

**Comment by TeoTwawki** [comment]
meet me in game

**Comment by Spardante** [comment]
Hey, TeoTwawki.  Just got home and logging in.  I'll try looking for you

**Comment by TeoTwawki** [comment]
Handled.

**Comment by Spardante** [comment]
Just wanted to say thank you again for the help.

**Comment by TeoTwawki** [comment]
You're welcome
