### ISSUE TITLE
Connection Lost Item

### ISSUE THREAD

**Issue by akahri** [LegionDark/Issues#1018]
Date & Time: 7/17/2016 @ 11:50:00PM

FFXI Client Version (use /ver): 03160329_1

Server's Expected Client Version matches, yes/no? (use `@ecv`): No, 30160329_0

Character Name: Akahri

Nation: Sandoria

Job(level)/Sub Job(level): 99SAM/49DNC

NPC or Monster or item Name: Pole Grip

Zone name & Coordinates (use @where): North Sandoria (Mog House) X:0 Y:0 z:0 (192)

ffxiah.com link (for items issues only): http://www.ffxiah.com/item/19025/pole-grip

Multi-boxing? (multiple clients on same connection): No

Steps To Reproduce / any other info: I was ~R 14 receiving at the time i was trying to throw my Long Boomerang away.
My screen was just sitting there, i could scroll through the menu but nothing would happen. Then there was a lag spike, 
followed by my 'Pole Grip' being thrown away at 11:50PM and 'Long Boomerang' being thrown out at the same time. I could not recover the 'Pole Grip' because of this lag spike or fluctuation and i can't get another one. I was wondering if i may get it back, as the connection was up and down. I have screenshot the verifies this, thankyou.

**Comment by Genesis-Legion** [comment]
I had a spare pole grip on Genesis, so I gave it to Akahri.

**Comment by R3P0FFXI** [comment]
@akahri @Genesis-Legion We do not restore items due to a spike or loss of connection

**Comment by TeoTwawki** [comment]
@R3P0FFXI I'm willing to due one time only restores IF and only IF I can find a record of it.

@akahri *Would you like to ~~waste~~ use your* **one time only** *item restore* on this pole grip?
