### ISSUE TITLE
cop mission unable to advance 3-3

### ISSUE THREAD

**Issue by atts2002** [LegionDark/Issues#1019]
**Date & Time**: 
21/07/2016

**FFXI Client Version (use `/ver`)**: 
30160329_1
**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
30160329_0

**Character Name**: 
doradosushi

**Nation**: 
sand oria

**Job(level)/Sub Job(level)**: 
NIN/DNC99

**NPC or Monster or item Name**: 
nil not npc/monster/item 

**Zone name & Coordinates (use `@where`)**: 
sandy oria

**ffxiah.com link (for items issues only)**: 
nil

**Multi-boxing? (multiple clients on same connection)**: 
yes multi boxing
toon name
doradosushi
tunasushi
teamsushi

**Steps To Reproduce / any other info**: 
doing cop 3-3 The road forks
tuansushi and team sushi finish the NM fights etc all cut scenes and advance onto CoP 3-4 no problem
mission promathia log stated - complete with sub missions
BUT only doradosushi mission promathia stated at 3-3 which is the road forks
done all requred /npc and cut scenes but mission log still at 3-3the road forks with NO sub missions completed
back traacking to the start to do missions again for doradosushi still no change in mission log 
therefore unable to advance further on this character

**Comment by TeoTwawki** [comment]
@LegionDark/gm `@checkmission` and `@checkvar` this. The varname is `PromathiaStatus` look in the appropriate NPC scripts as you walk him through each step of mission one NPC and cs at a time. When you see a var not move when you know it should have just then, tell me.

**Comment by atts2002** [comment]
so i type down @checkmission and @checkvar ingame?

**Comment by TeoTwawki** [comment]
I'm speaking to the GM staff
https://help.github.com/articles/mentions-on-github-pages/

**Comment by atts2002** [comment]
Oh i see sorry my bad first timer :)

**Comment by TeoTwawki** [comment]
@atts2002  p.s. thats also why I surrounded my Gm commands in backticks, so I wouldn't tag users with weird github account names. We keep having ppl ping paypals official account here (`@where`).

```text
`code`
```

**Comment by atts2002** [comment]
tbh i have no idea what u just said, im not very great with computers and such
but i suspect thats a  good thing :)

**Comment by atts2002** [comment]
just checked this cop3-3 the road forks is curerently under current and complete but no sub missions under The road forks
both other toons got complete The road forks with submissions

**Comment by TeoTwawki** [comment]
> tbh i have no idea what u just said

I am saying the `@` symbol here makes github email people unless you surround it with the [backtick](https://en.wikipedia.org/w/index.php?title=Backtick) character...People don't like getting irrelevant mail just because some fan project decided to stupidly use them for in game commands.

As for your missions, there is nothing for you to do till a GM can meet up with you for step by step analysis. Your multi-boxing borked it (happens randomly) and to fix it we have to find where the progression died.

**Comment by atts2002** [comment]
ok guess i have to wait for GM then

**Comment by PikaFox** [comment]
Checkmission 6 (cop) is 28 the road forks.

Checkvar PromathiaStatus is 0

Ill start trying to go through the paths with him after im done getting the potatos cooked; ill leave the current findings here just in case and for future reference.

**Comment by TeoTwawki** [comment]
Thanks pika <3

**Comment by PikaFox** [comment]
Solved. Multi var mission oh god why so confusing.
