### ISSUE TITLE
Bard instrument Syrinx does not work

### ISSUE THREAD

**Issue by bartonkt** [LegionDark/Issues#102]
**Date & Time**: 6/14, approx 3 PM mountain time
**Frequency**: anytime instrument is used
**FFXI Client Version**: 30150508_8
**Character Name**: Cyrilla
**Race**: Elvaan
**Main Job**: Bard
**Sub Job**: red mage
**Area & Coordinates**: Gustav Tunnel, 99 exp area
**Party or Solo**: party
**NPC Name**: n/a
**Monster Name**: boulder eater
**Steps To Reproduce The Issue**: equip Syrinx, sing elegy on monster. You will see your character singing, and not using the equipped Syrinx. If you are not capped skill, you may get a singing only skillup - no wind instrument skill up. 

Workaround - I'm using horn+1 instead, which provides elegy+2, and works as intended.

**Comment by Loki79** [comment]
@R3P0FFXI  take a look at this, its more than likely the model or the item just flat out isn't fully made.  Let me know if you get stuck.  If this is broken in a non-custom SQL ill apply your fix and PR it to dsp.  Do not make any changes to non-custom files in repo.

**Comment by R3P0FFXI** [comment]
I will look at this tonight Loki

**Comment by R3P0FFXI** [comment]
This item does not have the right model ID, the ID is 65 it will be submitted to DSP for a fix may take 1-2 weeks for them to merge it into the trunk
