### ISSUE TITLE
Sarameya Strong Regen

### ISSUE THREAD

**Issue by Vladrek17** [LegionDark/Issues#1020]
**Date & Time**: 7/20/16 11:30pm

**FFXI Client Version (use `/ver`)**: 30160329_1

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: no

**Character Name**: Vladrek

**Nation**: Bastok

**Job(level)/Sub Job(level)**: Samurai (99) / Ninja (49)

**NPC or Monster or item Name**: Sarameya

**Zone name & Coordinates (use `@where`)**: Mount Zhayolm X:319 Y:-14 Z:-589 (191)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: I was not, but members in my party were at the time. 

**Steps To Reproduce / any other info**: When fighting Sarameya it had a very strong regen active that would barely allow a party of 4 damage dealers to take it below 90% health.  When less than that was present, it would barely fall below 97% before regaining full health.

**Comment by TeoTwawki** [comment]
Just so you know, this is somewhat normal from retail: particularly when it has blaze spikes up. Need to take its spikes off or you have a hopeless battle. I will be reducing its total regen however (right now, as a hotfix) because I see a mistake was made giving it more than intended during its non spikes phases.

**Comment by TeoTwawki** [comment]
before: 100/tick at spawn, +1% of max hp per tick during spikes
after: 10/tick when spikes are down, +1% of max hp per tick during spikes

until next restart he may still spawn in with high regen, but the moment his battle script kicks in it will self correct. Keep his spikes off and he'll be normal.

**Comment by Vladrek17** [comment]
thanks, we'll try him again very soon.
