### ISSUE TITLE
Smithing 101 Gefechtbrust broke?

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#1021]
Date & Time: 7-21-16 9pm hst

FFXI Client Version (use /ver ): 30160602_0

Character Name: Dimma

Nation: Sandy

Job(level)/Sub Job(level): 
 blu99/rdm49

NPC or Monster or item Name: 
 Craft Smithing Lv101.

Zone name & Coordinates (use @where ): 
 San'doria

ffxiah.com link (for items issues only):  Gefechtbrust

Multi-boxing? (multiple clients on same connection): 
 No

I was trying to make an item called Gefechtbrust but when I was in front I get a message saying that the production is not possible

**Comment by R3P0FFXI** [comment]
@Dimmabr Does not make it broken means the item currently does not exist.

**Comment by R3P0FFXI** [comment]
@Dimmabr This is an Su item it synths just fine but will not work until the Su fix is in.
