### ISSUE TITLE
Clothcrafting Skill Port

### ISSUE THREAD

**Issue by Hazed69** [LegionDark/Issues#1022]
**Date & Time**: 7/22/16 1848 Eastern Standard Time

**FFXI Client Version (use `/ver`)**: 30160427_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: no ECV is 30160329_0

**Character Name**: Hazed

**Nation**: Bastokian

**Job(level)/Sub Job(level)**: 99thf/49dnc

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: Just requesting porting of skills if not too late to do so(wasn'
t ever planning to craft but need to now)
![hazedskills](https://cloud.githubusercontent.com/assets/20501801/17073561/de649d98-503f-11e6-8845-e5adf7cb2a8e.png)

**Comment by Genesis-Legion** [comment]
Crafts transferred

**Comment by Hazed69** [comment]
tyvm
