### ISSUE TITLE
Aegis Not Being given from stage 4

### ISSUE THREAD

**Issue by Hazed69** [LegionDark/Issues#1023]
Date & Time: July 22th 11:34pm

FFXI Client Version (use /ver ): 30160427_0

Server's Expected Client Version matches, yes/no? (use @ecv ): no ecversion is 30160329_0

Character Name: Hazed

Nation: Bastok

Job(level)/Sub Job(level): 99thf/49dnc

NPC or Monster or item Name: Ancile  -->  Aegis

Zone name & Coordinates (use @where ):Carpenters Landing H-10 x:-100 Y:0 Z:-514 (20)

ffxiah.com link (for items issues only): 
http://www.ffxiah.com/item/15069/ancile  
http://www.ffxiah.com/item/15070/aegis
Multi-boxing? (multiple clients on same connection): No

Steps To Reproduce / any other info: Not attempted. Trading all 4 items Ancile Supernal Frag and 1 ronp. gold piece with necropsyche and nothing happening

![img_20160722_233812](https://cloud.githubusercontent.com/assets/20501801/17075574/b15d06e8-5065-11e6-81f7-4ba069cde8eb.png)
![img_20160722_233813](https://cloud.githubusercontent.com/assets/20501801/17075575/b64e2bf0-5065-11e6-8d89-235a0e979c4f.png)
![img_20160722_233815](https://cloud.githubusercontent.com/assets/20501801/17075576/ba12d420-5065-11e6-8645-9ad8078d2357.png)
![img_20160722_233816](https://cloud.githubusercontent.com/assets/20501801/17075577/bd8cb440-5065-11e6-8279-7ad4742e217e.png)

**Comment by TeoTwawki** [comment]
https://help.github.com/articles/mentions-on-github-pages/

You people need to stop removing the templates prefilled formatting. you are pinging github users unrelated to the project

**Comment by Hazed69** [comment]
Resolved Do not have any base relics in inventory or it will bug preventing you from completing for anyone else in future
