### ISSUE TITLE
cop mission unable to advance 5-3 Three Paths

### ISSUE THREAD

**Issue by atts2002** [LegionDark/Issues#1025]
**Date & Time**: 
23/july/2016

**FFXI Client Version (use `/ver`)**: 
30160329_1
**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
30160329_0

**Character Name**: 
doradosushi
tunasushi
teamsushi

**Nation**: 
sandy oria

**Job(level)/Sub Job(level)**: 
nin/dnc99
sam/war99
rdm/whm99
**NPC or Monster or item Name**: 
nil

**Zone name & Coordinates (use `@where`)**: 
cop misison

**ffxiah.com link (for items issues only)**: 
nil

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
open up a smimilar tickek few days ago
seem my cop mission got borked again currently stuck on 5-3 Three Paths
cpmpleted Tenzen path but mission still Current Three Paths and completed Three Paths with no submission whatever
this time all 3 toons stuck 
i back tracked on doradosushi with all toons logged off so far 
will try other 2
sorry for the trouble....

**Comment by atts2002** [comment]
sorry guys false alarm

**Comment by TeoTwawki** [comment]
Good. The last time literally all that was needed was for the character to talk to Cid again.

Just a reminder for future incidents when multiboxing is involved:
**Remember that logging off the other characters doesn't make the server fix anything, the player must log out _ALL_ accounts and relog just one _after all clients are 100% closed_, and then repeat the steps for the bugged quest/mission. Many times as we watch someone go over it step by step things magically work with zero GM intervention.**
