### ISSUE TITLE
ZM12

### ISSUE THREAD

**Issue by ronnymp** [LegionDark/Issues#1026]
**Server's Expected Client Version matches, no

Date & Time:24 July 2016 5:16 PM
Frequency:
FFXI Client Version: 30160620_1
Character Name: Miudo
Race:Galka
Main Job:war
Support Job:sam
Area and Coordinates: Quicksand caves
Party or Solo:solo
NPC Name:
Monster Name:Ancient Vessel.
Steps:
the ??? not there to pop NM ^^

**Comment by TeoTwawki** [comment]
http://legiondark.com/forums/viewtopic.php?t=1648&amp;sid=d969cf13de7fe392b526655351cd3b7d

**Comment by TeoTwawki** [comment]
Thats enough of that..

**Comment by TeoTwawki** [comment]
p.s. : look at the version number. Your client doesn't match server.
