### ISSUE TITLE
Nosferatu won't drop the dagger Terpsichore Lv.75

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#1027]
Date & Time: 25/7/16 
 3:40PM

FFXI Client Version (use  /ver ): 
 30160602_0
Server's Expected Client Version matches, yes/no? (use  @ecv ): 

Character Name: Dimma

Nation: San'doria

Job(level)/Sub Job(level): BLU99/RDM49

NPC or Monster or item Name: Nosferatu 

Zone name & Coordinates (use  @where ): Aydeewa Subterrane
 
ffxiah.com link (for items issues only): http://www.ffxiah.com/item/18969/terpsichore

Multi-boxing? (multiple clients on same connection):  no

I having tryied to get the dancer dagger Mythical weapon Terpsichore Lv75 in Aydeewa Subterrane with Nosfiratu but, don't get any sucess because it don't drop the dagger.

**Comment by R3P0FFXI** [comment]
@Dimmabr duplicate ticket https://github.com/LegionDark/Issues/issues/985
