### ISSUE TITLE
SAM AF Hand 109 + 5x Chapter 3 = RNG AF Hand 119

### ISSUE THREAD

**Issue by Xenriv** [LegionDark/Issues#1028]
**Date & Time**:  7/24/2016 11:00 AM EST

**FFXI Client Version (use `/ver`)**:  Current

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**:  yes

**Character Name**:  Xenriv

**Nation**: Bastok

**Job(level)/Sub Job(level)**:  99THF/49DNC

**NPC or Monster or item Name**:  N/A

**Zone name & Coordinates (use `@where`)**:  Upper Jeuno

**ffxiah.com link (for items issues only)**:  http://www.ffxiah.com/item/27954/wakido-kote  http://www.ffxiah.com/item/27974/orion-bracers-1

**Multi-boxing? (multiple clients on same connection)**:  No

**Steps To Reproduce / any other info**:  Traded 5x Chapter3 and Wakido Kote (SAM AF Hand 109) to NPC in upper jeuno and received Orion bracers +1 (RNG AF Hand 119).  Thanks in advance.

**Comment by R3P0FFXI** [comment]
@Genesis-Legion  please verify user has tossed incorrect item, additem correct one this is fixed in update

**Comment by Genesis-Legion** [comment]
Player was given his item.
