### ISSUE TITLE
Revealer's Tunic and RDM job Don't equip.

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#1029]
Date & Time: 26 July 2016
FFXI Client Version (use  /ver ): 30160602_0
Character Name: Dimma
Nation: San d'oria
Job(level)/Sub Job(level): RDM99/NIN49
NPC or Monster or item Name: Revealer's Tunic 
Zone name & Coordinates (use  @where ): n/a
ffxiah.com link (for items issues only): http://www.ffxiah.com/item/26885/revealers-tunic
Multi-boxing? (multiple clients on same connection): n/a
Steps To Reproduce / any other info: Tunic won't equip in RDM job.

**Comment by Genesis-Legion** [comment]
The item is Su1, which hasn't been fixed yet if I recall.

**Comment by R3P0FFXI** [comment]
@Dimmabr stop placing bug reports for things that are already reported. Look at the items and open tickets before you waste everyones time with these things.
