### ISSUE TITLE
Can not equip ammo Annihilator 75

### ISSUE THREAD

**Issue by rekcahniZe** [LegionDark/Issues#103]
Date & Time: 6/16/15
Frequency: Always
FFXI Client Version: 30150508_8
Character Name: Rekcah
Race: Hume
Main Job: Rng
Sub Job: Sam
Area & Coordinates: NA
Party or Solo: Any
NPC Name: NA
Monster Name: NA
Steps To Reproduce The Issue:

1) Equip Annihilator
2) Equip ammo (Tested Titanium, Steel, and silver bullet)

Note: Cannon Shells work
Maybe I need to drop mine and receive a new Annihilator for changes to take place

**Comment by R3P0FFXI** [comment]
This was fixed today during maint. Please retest now

**Comment by rekcahniZe** [comment]
Still same for me only cannon shells work.

**Comment by Loki79** [comment]
i will test this in game and see what could be causing it,

**Comment by Loki79** [comment]
ok this is fixed here, and in DSP now so it should never pop up again.  will require a restart to go in though.  i know you have been dealing with this bug a while now so come find me in IRC please and we will talk about moving your trial along.
