### ISSUE TITLE
item went missing

### ISSUE THREAD

**Issue by atts2002** [LegionDark/Issues#1030]
**Date & Time**: 
27 july 2016

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
no  30160329_0

**Character Name**: 
doradosushi

**Nation**: 
sany oria

**Job(level)/Sub Job(level)**: 
sam/war 99

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/19464/kannagi

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
kannagi +1 complted first stagre upgrade had the weapon for awhile been very carefrull
looking for it today to complete second upgrade got mats right now but weapon is missing

**Comment by TeoTwawki** [comment]
What date did you last for certain see the item in your inventory? If possible, also tell me what date believe you first acquired the item. I've checked today and yesterdays backups and don't see it so far, and I'd like to narrow down my search before I dig deeper.

**Comment by atts2002** [comment]
pretty sure i upgrade to first stage about 10 days ago
had the base item for about 6 weeks i believe

**Comment by TeoTwawki** [comment]
ok, found a record of you owning it now to see how you lost it..

**Comment by atts2002** [comment]
hope its not because i toss it :(

**Comment by TeoTwawki** [comment]
might you have? were you tossing out multiple items and lagged a bit?

**Comment by atts2002** [comment]
yeah i was cleaning out not long ago

**Comment by TeoTwawki** [comment]
If I find no bug here (not looking liek I will) I'm gonna handle this like retail would:
*would you like to use your **one time** item restore?*

**Comment by atts2002** [comment]
lol

**Comment by atts2002** [comment]
yes please

**Comment by atts2002** [comment]
that took me 2 weeks to farm

**Comment by TeoTwawki** [comment]
k, if your in game tonight I'll be on to see you in a few.

**Comment by atts2002** [comment]
ok tyvm

**Comment by atts2002** [comment]
i be on prollyt for the next 6hr hours with afks ion between

**Comment by TeoTwawki** [comment]
No bugs discovered in any script that touches the item, but Assai_Nybaen.lua sure is a royal mess. Functional but also fugly...Someday will have to clean him up.

Players lost item returned in game, added to "already restored something" tracking.
