### ISSUE TITLE
Eddy Necklace not equipable by PLD

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1031]
**Date & Time**: 
July 27, 2:39:21

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
30160329_0

**Character Name**: 
Tbone

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
PLD99

**NPC or Monster or item Name**: 
Eddy Necklace

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/28401/eddy-necklace

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
PLD listed as usable on the item, but it won't equip.

Useful for Holy and MAB based WSes.

**Comment by Samikana** [comment]
Jobmask should be 3719372.  I can't check because I need to get access back to the item files, can anyone check it?

**Comment by TeoTwawki** [comment]
@Samikana https://github.com/LegionDark/SQL_testbed/tree/master/sql should be fairly recent

**Comment by tb1** [comment]
Working now on pally, didn't test all jobs, but assumed to be resolved.

**Comment by TeoTwawki** [comment]
thanks for checking and closing.
