### ISSUE TITLE
Mog Sack only has 30 slots instead of 80

### ISSUE THREAD

**Issue by jyocis82** [LegionDark/Issues#1035]
**Date & Time**: 
7/28/2016 12:33 CST

**FFXI Client Version (use `/ver`)**: 
30160629_1
**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
no

**Character Name**: 

Belaal
**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
60BST/30DNC

**NPC or Monster or item Name**: 
Mog Sack

**Zone name & Coordinates (use `@where`)**: 
Moghouse port Windurst

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 

Mog Sack only has 30 slots was told it was supposed to have 80 and to put in a ticket. Thank you in Advance.

**Comment by TeoTwawki** [comment]
@R3P0FFXI need to find out wtf is going on that causes this, I am seeing a ton of characters in the database with the size wrong like this...

**Comment by R3P0FFXI** [comment]
@TeoTwawki Let me check the config files again and make sure the character is not a transfer character.

**Comment by R3P0FFXI** [comment]
@TeoTwawki from the config file

START_INVENTORY = 80; -- Starting inventory and satchel size.  Ignores values < 30.  Do not set above 80!

This says nothing about sack in the config file.

**Comment by TeoTwawki** [comment]
satchel and sack both match main inventory (they shouldn't even be separate columns in the sql table really)

**Comment by Samikana** [comment]
@TeoTwawki was this ever fixed?

**Comment by TeoTwawki** [comment]
@Samikana teh players at that time were but I left issue open pending discovery of HOW this keeps happening. R3 was supposed to check out some things for me. I'll remind him this is a thing still..
