### ISSUE TITLE
Forge Your Destiny Uncompletable

### ISSUE THREAD

**Issue by Reabs** [LegionDark/Issues#1036]
**Date & Time**: 
7/28/2016  4:40pm

**FFXI Client Version (use `/ver`)**: 
version 30160629_1

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
Expected Client Version: 30160329_0

**Character Name**: 
Reabs

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
Warrior(36)/Black Mage(15)

**NPC or Monster or item Name**: 
Jaucribaix

**Zone name & Coordinates (use `@where`)**: 
Norg x:90 y:-7 z:-7

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Level warrior to 36.  Complete samurai quest Forge Your Destiny up till the point where Jaucribaix tells you you have to wait for 72hours.  Wait 4-5 real life days.  Attempt to complete.

In the meantime between doing this I leveled whm & blm a bit neither past 30.  I also did this same quest with 3 other people and all of them were able to unlock.

Talking to Jaucribaix gives this text:  "Know the meaning of the power you hold, and only then will you find the true power within.  That be "bushido," the way of the samurai.

Talking to Aeka gives this text:  "You do not have to worry about your reward. Master Jaucribaix is a man of his word.  Time is necessary for him to complete his work.  You must be Patient.  Nothing good can be gained by rushing things.

**Comment by R3P0FFXI** [comment]
@TeoTwawki Client mismatch due to ID's?

**Comment by TeoTwawki** [comment]
Text ID NPC was trying to tell him his inventory was full.
