### ISSUE TITLE
Octave club not equipable in PLD

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#1037]
Date & Time: 
 July 28, 12:40

FFXI Client Version (use  /ver ): 30160602_0

Server's Expected Client Version matches, yes/no? (use  @ecv ):  30160602_0

Character Name: Dimma

Nation: San'doria

Job(level)/Sub Job(level):  PLD75

NPC or Monster or item Name: Octave club

ffxiah.com link (for items issues only): http://www.ffxiah.com/item/18852/octave-club

Multi-boxing? (multiple clients on same connection): 
 

Steps To Reproduce / any other info: 
 PLD listed as usable on the item, but it won't equip.

**Comment by TeoTwawki** [comment]
http://legiondark.com/forums/viewtopic.php?t=1648
