### ISSUE TITLE
Blurred Lance error crafting (Smithing guild)

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#1038]
**Date & Time**: 
16/07/29 07:40 AM

**FFXI Client Version (use `/ver`)**: 
30160602_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
30160329_0

**Character Name**: 
Dimma

**Nation**: 
San'doria

**Job(level)/Sub Job(level)**: 
PLD73/NIN36

**NPC or Monster or item Name**: 
Shabti Sabatons

**Zone name & Coordinates (use `@where`)**:
San'doria  X:-191 Y:11 Z:140 (65)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/28316/shabti-sabatons

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: I was manufacturing a Shabti Sabatons but when I used the necessary items ( Fire Crystal, Gold Ingot, Ram Leather x2, Mercury, Bismuth Sheet x3 ) I received another item called Blurred Lance. ( http://www.ffxiah.com/item/20940/blurred-lance )

**Comment by Samikana** [comment]
Just tested.  Shabti Sabaton's intended crafting recipe crafts Blurred Lance (gotten info off bg-wiki).  Shabti Sabaton currently has no actual recipes to craft it.

**Comment by R3P0FFXI** [comment]
Fixed in Maint
