### ISSUE TITLE
Paladin can't equip Octave club.

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#1039]
**Date & Time**: 
16/07/29 07:55 AM

**FFXI Client Version (use `/ver`)**: 
30160602_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
30160329_0

**Character Name**: 
Dimma

**Nation**: 
San'doria

**Job(level)/Sub Job(level)**: 
PLD73/NIN36

**NPC or Monster or item Name**: 
Octave clube

**Zone name & Coordinates (use `@where`)**:
San'doria  X:-191 Y:11 Z:140 (65)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/18852/octave-club

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Paladin is listed to use this item but when I try to team it does not work

**Comment by TeoTwawki** [comment]
5 second forum search:
http://legiondark.com/forums/viewtopic.php?f=30&t=574&p=1756&hilit=octave#p1756
http://legiondark.com/forums/viewtopic.php?f=27&t=8&p=8&hilit=octave#p8

**Comment by TeoTwawki** [comment]
## **_Working as intended ™_**
