### ISSUE TITLE
PM5-3 Louverance path

### ISSUE THREAD

**Issue by goferffxi** [LegionDark/Issues#104]
**Date & Time**  17/06/2015    06:38 GMT: 
**Frequency**: not sure
**FFXI Client Version**: 30150508_8
**Character Name**:Gofer
**Race**:Taru
**Main Job**:BLM
**Sub Job**:RDM
**Area & Coordinates**X:117 Y:-3 Z:100 (193):
**Party or Solo**:solo
**NPC Name**:Perih Veshai
**Monster Name**: N/A
**Steps To Reproduce The Issue**: Complete PM5-3 Tenzen and Ulmia. Start Louverance path. Speak to Despachire in Tav Safehold.  Head to windy to spk to NPC for cutscene. No Cutscene Given. Attempted to zone and come back. No cutscene Given.

**Comment by goferffxi** [comment]
After getting the CS from Despachire I changed zone, came back and got the CS again. After exhausting all other ideas I decided to speak to despachire AFTER the CS had finished to which he gave me a little few words but no CS. I travelled to Windurst spoke to the NPC and got the CS for this mission. in short, speak to Despachire again AFTER the CS then go to windurst to continue

**Comment by R3P0FFXI** [comment]
User received CS for mission
