### ISSUE TITLE
Will not be leaving EXP

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#1041]
**Date & Time**: 2016/1/8

**FFXI Client Version (use `/ver`)**: 30160329_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 

**Character Name**: 
Qigang

**Nation**: SAND

**Job(level)/Sub Job(level)**: BLU99/RDM49

**NPC or Monster or item Name**: no

**Zone name & Coordinates (use `@where`)**: Mordion Gaol

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 
For this problem I know, but I now ID has closed the confinement, the future will not be like this. Hope to go out. Thank you

**Comment by R3P0FFXI** [comment]
@qiganggang your account has been suspended for unattended leveling. You may contact a GM in game or in IRC in 24 hours to be released. Unattended play is unacceptable and will not be tolerated.

**Comment by qiganggang** [comment]
i need wait 1day?

**Comment by R3P0FFXI** [comment]
@qiganggang Yes your account was caught leveling unattended it is suspended for 24 hours, Whether or not it was you on the account or someone else you are responsible for your account.

**Comment by R3P0FFXI** [comment]
@LegionDark/gm Please get with user after noon EST today 8/2/2016 to pardon. @qiganggang If this happens again you will be suspended for 72 hours. @qiganggang  please login your character so we can pardon.

**Comment by qiganggang** [comment]
i login characer now plz

**Comment by qiganggang** [comment]
yes is my friend login my ID , ls friend need exping, hmmm, i dont know,

**Comment by Genesis-Legion** [comment]
Released them.

**Comment by TeoTwawki** [comment]
@qiganggang if you share your account info you are still responsible for what happens on your account. robots playing for you are not allowed.

如果您共享您的帐户信息，你仍有责任在您的帐户会发生什么。
机器人比赛是被禁止。
Automated translation. I hope that is readable.
