### ISSUE TITLE
Raider's Craft Skills 

### ISSUE THREAD

**Issue by Raider83** [LegionDark/Issues#1042]
**Date & Time**: 8/1/16 22:24

**FFXI Client Version (use `/ver`)**: 30160629_1

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: No

**Character Name**: Raider

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 99PLD/49WAR

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: N/A

![chris s crafts picture](https://cloud.githubusercontent.com/assets/20784845/17315153/5044b9d0-5837-11e6-97aa-ac95241f61df.png)

**Comment by Genesis-Legion** [comment]
Craft transferred.
