### ISSUE TITLE
so is it a wast of time playing here 

### ISSUE THREAD

**Issue by numxxviii** [LegionDark/Issues#1044]
**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 

**Character Name**: 

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:

**Comment by R3P0FFXI** [comment]
@numxxviii No its a waste of time opening a report when you remove half the template. Your issue was closed because you failed to follow simple instructions. Failing to do so = ticket closed. When you remove the template you message people not associated with this project because of the at symbol.

**Comment by TeoTwawki** [comment]
I have no sympathy for self made victims, you will not be missed.

**Comment by TeoTwawki** [comment]
Any further use of the issue tracker as means to disparage the project instead of reporting an issue will result in tracker bans.
