### ISSUE TITLE
cant upgrade empy 109 with 3 lunars and 10 titles

### ISSUE THREAD

**Issue by numxxviii** [LegionDark/Issues#1045]
**Date & Time**: 
8/3/2016 8:04pm

**FFXI Client Version (use `/ver`)**: 
 301602_0
**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
 no

**Character Name**: 
 Numxxviii

**Nation**: 

 Bastok

**Job(level)/Sub Job(level)**: 
 99Blue/Rdm 

**NPC or Monster or item Name**: 
Prishe

**Zone name & Coordinates (use `@where`)**: 
 x:539 Y:-500 Z:-589 (83)

**ffxiah.com link (for items issues only)**: 
 N/A

**Multi-boxing? (multiple clients on same connection)**:
Same 

**Steps To Reproduce / any other info**: traded all 30 items and the +2 body as I have done on the last 3 parts and now being told i need 3 lunar and 10 titles and I do have all 3 and 10 titles

**Comment by R3P0FFXI** [comment]
@numxxviii it should only be asking for 2 Lunars and 9 titles

**Comment by TeoTwawki** [comment]
@R3P0FFXI you didn't edit the text message so even though you changed the requirements it would still tell them the old message if they were missing anything.

**Comment by TeoTwawki** [comment]
I've added messages to indicate which thing is missing.

**Comment by numxxviii** [comment]
Thank you

**Comment by R3P0FFXI** [comment]
@TeoTwawki Thanks man did Not realize i missed the message

**Comment by numxxviii** [comment]
ok just trade and it is the same thing i have pic showing i have 3 lunars and +2 body armor if that helps

**Comment by TeoTwawki** [comment]
@R3P0FFXI @numxxviii code was mistakenly looking for lunars to exactly equal 2, rather than greater or equal to 2. This is fixed now.

**Comment by numxxviii** [comment]
Thank you now have blue 109 body

On Aug 5, 2016 2:00 AM, "TeoTwawki" <notifications@github.com> wrote:
>
> @R3P0FFXI @numxxviii code was mistakenly looking for lunars to exactly
equal 2, rather than greater or equal to 2. This is fixed now.
