### ISSUE TITLE
Tanners Ring Went AWOL

### ISSUE THREAD

**Issue by Hazed69** [LegionDark/Issues#1046]
**Date & Time**: 8/3/16 18:21

**FFXI Client Version (use `/ver`)**: 30160629_1

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: No

**Character Name**: Hazed

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99thf/49dnc

**NPC or Monster or item Name**: Tanner's Ring

**Zone name & Coordinates (use `@where`)**: 0 0 0 (68)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/15823/tanners-ring

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: N/A checked every storage slot 1 at a time 12 times to be sure it was here couple weeks ago and now its gone

**Comment by TeoTwawki** [comment]
When was the last time you are certain you had it? I have to be able to locate it in a backup to prove it was owned.

**Comment by TeoTwawki** [comment]
Any clue how it may have been lost? Very important.

**Comment by Hazed69** [comment]
I think my dumb ass dropped it its not important ill get a new one was just having trouble making nq item for someone I'm not sure when it got tossed by my stupidity
