### ISSUE TITLE
reforge went wrong ^^

### ISSUE THREAD

**Issue by ronnymp** [LegionDark/Issues#1047]
**Date & Time**: 8/6/2016 4PMEST

**FFXI Client Version (use `/ver`)**: 30160329_1

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**:  no , 30160329_0

**Character Name**: Miudo

**Nation**: sandy

**Job(level)/Sub Job(level)**: BLU99/49RDM

**NPC or Monster or item Name**: Assimilator's Keffiyeh+1

**Zone name & Coordinates (use `@where`)**: x:-15, y:0 , z:40 (54)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/27699/assim-keffiyeh-1

**Multi-boxing? (multiple clients on same connection)**:  yes , serjoca

**Steps To Reproduce / any other info**: 

i was with  Assimilator's keffiyeh 109 , and then i trade 5 rems chaps 4 with renik and she gave me convoker's horn +1 (SMN artifact head 119)

**Comment by R3P0FFXI** [comment]
@ronnymp Why are you working on an item that drops from Bismark when all that works on Voidwatch is Chapter 1/2 we have said numerous times these items will be fixed in Massive Update part 2.

**Comment by ronnymp** [comment]
Ok ill when i get in home , thx alot... need me to post in here when i toss the item?

**Comment by ronnymp** [comment]
and sorry about that , tough only chapter 5 was broken... my bad ><

**Comment by R3P0FFXI** [comment]
@ronnymp No Chapter 3-5 are broken, you will need to post a pic of the item being tossed

**Comment by ronnymp** [comment]
will do , thx

**Comment by ronnymp** [comment]
![img_20160806_220557](https://cloud.githubusercontent.com/assets/13970269/17459858/0f2b11bc-5c22-11e6-91ca-19fbfdc0b142.png)

**Comment by Genesis-Legion** [comment]
Player was returned his 109 piece.
