### ISSUE TITLE
denali trade for thaumas

### ISSUE THREAD

**Issue by atts2002** [LegionDark/Issues#1048]
**Date & Time**: 
7.25am
7 august 2016

**FFXI Client Version (use `/ver`)**: 
30160329_1
**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
no 30160329_0

**Character Name**: 
doradosushi

**Nation**: 
sandy o ria

**Job(level)/Sub Job(level)**: 
99nin/49war

**NPC or Monster or item Name**: 
Mrohk Sahjuuli at (I-11)
**Zone name & Coordinates (use `@where`)**: 
whitegate X:22 Y:0 Z:-88 (238) 

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/10479/thaumas-coat

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
as stated in forums
http://legiondark.com/forums/viewtopic.php?f=25&t=20&p=20&hilit=denali#p20
Nyzul 99 Gear Sets
traded denali 75 body piece along with 12 snowsteel ores and 5 gold pieces 
but no respomse from the npc

**Comment by R3P0FFXI** [comment]
@atts2002 I will have to look at the NPC script but I do not believe this has been changed so let me see what its looking for

**Comment by atts2002** [comment]
thankyou vm

**Comment by atts2002** [comment]
i was wondering if this was fix and i stumbled across something, the process of tradiing is diff to what u would do for empy armor/weaopn
first trade in 75 piece armor
listen to her terms
then trade in 75 piece allong with snowsteel ore and gold pieces
with body piece forums states 12 ores but in fact its 8
trading in 12 ores will not get you your new piece
needs to be exact
which was 75 piece 8 ores and 5 gold imp pieces
