### ISSUE TITLE
Took mission 3-2 Crystal Lake by accident+

### ISSUE THREAD

**Issue by Raider83** [LegionDark/Issues#1049]
**Date & Time**: 8/6/2016 744pm

**FFXI Client Version (use `/ver`)**: 30160629_1

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: no

**Character Name**: Raider

**Nation**: Sandy

**Job(level)/Sub Job(level)**: 99PLD/49WAR

**NPC or Monster or item Name**: Crystal Bass

**Zone name & Coordinates (use `@where`)**: x-99  y 1 z-43 (97)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/4528/crystal-bass

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**:  Not sure if can do mission for sandy 3-2 if fishing is disabled

**Comment by TeoTwawki** [comment]
Crystal Bass should be in AH, if not will add

**Comment by Raider83** [comment]
Great thanks none in there

**Comment by TeoTwawki** [comment]
was asleep "gee thanks" fcough, and you, moron that you are, closed the fucking ticket so none of the others would see it

**Comment by TeoTwawki** [comment]
I apologize, I think I just dream typed. holy crap. the sleep deprivation is really screwing with me.

**Comment by TeoTwawki** [comment]
I'm really, really sorry,

**Comment by TeoTwawki** [comment]
I just listed a bunch on AH, and we'll make sure the bot is reloading them later in the week. Again really sorry about my stupid earlier. If I'm lucky you didn't even see it.

**Comment by Raider83** [comment]
I did just now lol its ok it happens I just worked 29 hours of OT on the weekend so I am very familiar to sleep deprivation myself reading all that had me on laughing so hard though. and ty for adding them got the mission done

**Comment by TeoTwawki** [comment]
Glad you at least got a chuckle outa that

08.08.2016, 20:20, "Raider83" <notifications@github.com>:
