### ISSUE TITLE
NPC doesnt give new voidstones after day

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#105]
**Date & Time**:  6/18/15
**Frequency**: Always
**FFXI Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: NA
**Main Job**: NA
**Sub Job**: NA
**Area & Coordinates**: S Sandy, Bastok Mark, Windurst Waters
**Party or Solo**: NA
**NPC Name**: Voidwatch Officer
**Monster Name**: NA
**Steps To Reproduce The Issue**: NPC doesnt give 1 voidstone/earth day. You get initial stone and that is all. Got my stone tues, its thurs and i hanvt gotten a 2nd/3rd.

**Comment by Genesis-Legion** [comment]
Same problem, all three NPCs tell me I can only get one voidstone per day, and it's been well over 24 hours.

**Comment by Loki79** [comment]
Ok the timer has been corrected and the variables have all been zero'd out.  So you should be able to go get a stone with no issue at all.  Please let me know if you have any further problems.
