### ISSUE TITLE
Utsusemi: Ichi Spell  no longer in spell list 

### ISSUE THREAD

**Issue by Pendzich** [LegionDark/Issues#1051]
**Date & Time**: 
8/8/2016 9:07pm
**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 

**Character Name**: 
Rashtin

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
68thf/30nin

**NPC or Monster or item Name**: 
utsusemi: ichi 

**Zone name & Coordinates (use `@where`)**: 
NA

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/4946/utsusemi-ichi

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
ran quest got scroll used a couple weeks ago finally got shihei spell is not available under nin magic

**Comment by Genesis-Legion** [comment]
Player has been sorted out.
