### ISSUE TITLE
Character Issue

### ISSUE THREAD

**Issue by curelessLegion** [LegionDark/Issues#1053]
**Date & Time**:  08/09/2016 11:02pm EST

**FFXI Client Version**: 30160728_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**:  yes

**Character Name**:  Cureless

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  Job levels seem to have been rolled back.

- I am missing tons of gear.
- I have the last limit breaker complete, but no job over level 82
- All sorts of things seem to be missing, and rolled back, and gltiched.

Hoping my character can be put back to how he was. It's been a year since I logged on, before today.

**Comment by R3P0FFXI** [comment]
@curelessLegion We have done no player resets and we do not have backups going back a year as this is not a professional server. I have 30 days of backups if you have not logged into the server in the last 30 days there is nothing I can do for you.

**Comment by TeoTwawki** [comment]
I can look to see what the oldest available backup is, if we can't find where you got glitched out

**Comment by TeoTwawki** [comment]
Quick lookup shows oldest backup we have ( which is from February this year) has identical job levels to what you have now...I doubt any of your other data is any different.

**Comment by curelessLegion** [comment]
Thanks for the effort, I appreciate it.

**Comment by curelessLegion** [comment]
Just a quick thought, for piece of mind really.. Wouldn't happen to have my
transfer data I used to get this char on the server?

**Comment by TeoTwawki** [comment]
A re-import is something we can do, if that's what you want. It would totally wipe out your existing data and set you to whatever is in the export file used.

**Comment by TeoTwawki** [comment]
I see the thread on the forum: http://legiondark.com/forums/search.php?keywords=Cureless&fid%5B0%5D=37

If possible it would be better to have a new dump form the old server you played on though, as form time to time the formatting gets changed after client updates.

**Comment by curelessLegion** [comment]
I'm fine with that. Please do.

**Comment by TeoTwawki** [comment]
Ok. 

Do you want to try and get a new export file off your old server, or do you want us to reuse the old file and hope it works out? . If anything goes wrong I can still pull your current messed up character back from the void thought that might take a few days if for some reason we have to.

The importer tool expects the character we're overwriting to be lv one. The quickest way to accomplish that is delete and recreate.

**Comment by curelessLegion** [comment]
I don't even know if that server is up anymore. I haven't been playing ffxi at all since I stopped on legion.. so just use the old one, it's cool.

**Comment by curelessLegion** [comment]
Or just leave it alone.. if it's going to completely rollback to level one.

**Comment by curelessLegion** [comment]
I think I confused myself? You need me to delete and recreate, so you can import again?

**Comment by curelessLegion** [comment]
Sorry for being a tard, I have my reasons xD

Deleted, and recreated.

**Comment by TeoTwawki** [comment]
Import done check char in game

**Comment by curelessLegion** [comment]
Thank you.

**Comment by curelessLegion** [comment]
Okay so, in my infinite idiocy, this has rolled me back farther. -_-; I feel very... sheepish? 

Don't worry about pulling anything from the void, I'll just do the work to get back to where I was. I appreciate your guys time.

**Comment by curelessLegion** [comment]
On second thought.. it'd be cool to get it back, cause it did have more progress. I'm not in any rush, I don't have much time right now to play. I'll delete and recreate again.

**Comment by TeoTwawki** [comment]
don't re-delete next time, that's only for the importer..

**Comment by TeoTwawki** [comment]
You could have shot yourself in the foot: what if I had come back and said "hey I said if something goes wrong, not if you just change your mind?" you'd have been 100% screwed. Aintcha glad I'm such a nice guy?

Anyway you are restored back to as close as possible to where we started now and there's nothing left we can do. You may need to change job at the moogle before things look right  and the site profile doesn't update at the speed with which I edit the database so don't be alarmed by it still saying you are lower level.
