### ISSUE TITLE
Ashen Abissytie III losted KI after kill Aello.

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#1054]
Date & Time: 
16/08/10 07:40 AM
FFXI Client Version (use /ver): 
30160602_0
Server's Expected Client Version matches, yes/no? (use @ecv): 
30160329_0
Character Name: 
Dimma
Nation: 
San'doria
Job(level)/Sub Job(level): 
BLU99/RDM45
NPC or Monster or item Name: 
Aello 
Zone name & Coordinates (use @where):
Ru'Aun Gardens X:77 Y:-40 Z:-458 (102)
ffxiah.com link (for items issues only): 
https://www.bg-wiki.com/bg/Ashen_stratum_abyssite_III
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce / any other info: 
I was with some friends going to kill Aello in VWNM Zilart end bosses , but when I went to pop the NM it does not pop , but when I verifyquei my KI it was not her, I lost it.

**************HELP ME GET MY KI BACK**************

**Comment by R3P0FFXI** [comment]
@Dimmabr once again you failed at creating a simple ticket by editing the template so im closing this when you learn how to open tickets again please reopen

**Comment by R3P0FFXI** [comment]
@Dimmabr Also it should be noted VW Zilart also known as VW Chapter 3 IS NOT WORKING, All that is working is up to chapter 2 Jeuno sorry but as the content is closed until Massive update part 2 due to the mobs not working right GM will not assist with this ticket.
