### ISSUE TITLE
Amphiptere hide error crafting (Leathercraft guild)

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#1055]
.
Date & Time: 
16/07/29 07:40 AM
FFXI Client Version (use /ver): 
30160602_0
Server's Expected Client Version matches, yes/no? (use @ecv): 
30160329_0
Character Name: 
Dimma
Nation: 
San'doria
Job(level)/Sub Job(level): 
DNC99/THF49
NPC or Monster or item Name: 
Amphiptere Hide
Zone name & Coordinates (use @where):
Southern San'doria X:-185 Y:0 Z:12 (46)
ffxiah.com link (for items issues only): 
http://www.ffxiah.com/item/2750/amphiptere-hide
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce / any other info: I was manufacturing a Amphiptere Leather but when I used the necessary items ( Dark Crystal, Willow log, Amphiptere hide, Distilled Water ) I received another item called Raaz Leather. ( http://www.ffxiah.com/item/8708/raaz-leather )

**Comment by R3P0FFXI** [comment]
@Dimmabr once again edited the template stop editing the damn template closing ticket due to this.
