### ISSUE TITLE
Sallow Seymour doesn't play fair

### ISSUE THREAD

**Issue by Nususu** [LegionDark/Issues#1057]
**Date & Time**: 7:30pm EST

**FFXI Client Version (use `/ver`)**: 30160427_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 30160329_0

**Character Name**: Nususu

**Nation**: Bastok

**Job(level)/Sub Job(level)**: NIN99/DNC49

**NPC or Monster or item Name**: Sallow Seymour

**Zone name & Coordinates (use `@where`)**: 798, Y: 0, Z: 439

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Sallow Seymour draws you in. That's cool. But he draws you in to a location under the map so you can't run away. He then proceeds to brutalize you.

**Comment by TeoTwawki** [comment]
That bastid! There's a fix coming but I can't give an ETA for when it'll be live.

**Comment by Nususu** [comment]
Thanks @TeoTwawki !

**Comment by alannor** [comment]
Beaten couple of days ago with 4 BLUs using absolite terror/blistering roar. Stand close enough and it wont use draw in. Wiped a cpuple of times before we got it right. Fought a second time without any death. Let me know if you want to do it again, still need to take mules through it

**Comment by TeoTwawki** [comment]
Should be corrected with Today's update. If it still happens post back here and I'll raise the issue with DSP about it.
