### ISSUE TITLE
Pass Recovery 

### ISSUE THREAD

**Issue by deianm** [LegionDark/Issues#1059]
Date & Time: 8/23/2016

FFXI Client Version (use /ver): 30160629_1

Server's Expected Client Version matches, yes/no? (use @ecv): 30160329_0

Character Name: Marshmallow

Nation: Sand'Oria

Job(level)/Sub Job(level): 99WAR

NPC or Monster or item Name:

Zone name & Coordinates (use @where):

ffxiah.com link (for items issues only):

Multi-boxing? (multiple clients on same connection):

Steps To Reproduce / any other info: Account retrieval, the account was made a year ago before the e-mail system was implemented. I have the user if that's required, thanks in advance. Please IRC me or e-mail me to deian.mosolov@gmail.com
-Unisei

**Comment by TeoTwawki** [comment]
-***SLAP***-
Do not edit the template formatting!
