### ISSUE TITLE
Trail NM (King Behemoth) not recorded in @trial

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#106]
**Date & Time**: 6/18/2015 7:45pm
**Frequency**: once
**FFXI Client Version**:30150508_8
**Character Name**:Baucant
**Race**:Elvaan
**Main Job**:Thf
**Sub Job**:Dnc
**Area & Coordinates**:Behe,th's Dominio X:-228 Y:-19 Z:76 (48)
**Party or Solo**:Party
**NPC Name**:N/A
**Monster Name**:King Behemoth
**Steps To Reproduce The Issue**: 
Skeet, Crystiina and Rarag killed King Behemoth twice but only showing 1 in @trial

**Comment by R3P0FFXI** [comment]
Did the users in question have trial weapon equipped?

**Comment by Baucant** [comment]
Sorry for the long time to repond. I did have the mandau equiped. I have fount KB a few more times since this post and completed the trial without anymore trouble

**Comment by R3P0FFXI** [comment]
Per User issue is resolved
