### ISSUE TITLE
Dragoon 2hr's dont work

### ISSUE THREAD

**Issue by Alacard** [LegionDark/Issues#1060]
**Date & Time**: 
8/25/2016 6:31pm

**FFXI Client Version (use `/ver`)**: 
30160728_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
~~no~~ Admin edit: server updated, now its yes :)

**Character Name**: 
Alacardjr

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
DRG67/DNC33

**NPC or Monster or item Name**: 
N/A

**Zone name & Coordinates (use `@where`)**: 
The Boyahda Tree
X:289 Y:8 Z:23 (120)

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
N/A

**Steps To Reproduce / any other info**: 
Use Dragoon 2hr's

**Comment by TeoTwawki** [comment]
Need more information than "doesn't work". Spirit surge has been working for months.

**Comment by R3P0FFXI** [comment]
Lack of player response closing issue
