### ISSUE TITLE
PM5-3 Past Sins Bugged (final cutscene)

### ISSUE THREAD

**Issue by honeycubbinz** [LegionDark/Issues#1061]
**Date & Time**: 
8/27/2016 5:30 am

**FFXI Client Version (use `/ver`)**: 
30160602_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
no

**Character Name**: 
Brando

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
99 whm / 49 rdm

**NPC or Monster or item Name**: 
Cid

**Zone name & Coordinates (use `@where`)**: 
X:-12 Y:-10 Z:1 (201)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Chains of Promation Mission 5-3L4 completed everything and talked to Cid and no cutscene / completion of mission in mission log and other mules were able to complete. 100% positive I followed the same steps with all so I'm not sure why it won't give Brando the final cutscene of the mission.

**Comment by R3P0FFXI** [comment]
@honeycubbinz you are dualboxing, chances are this character is having issues because it did not get a step flagged. try restarting your PC and only login the character having issues and retalk to all NPC

**Comment by honeycubbinz** [comment]
@R3P0FFXI 
Tried that already. Tried again this morning still no luck. Went through every possible NPC in Past Sins quest to get a cutscene and nothing. I was at the final short cutscene from Cid in Bastok Metalworks.

**Comment by deianm** [comment]
Which path is it

**Comment by honeycubbinz** [comment]
@deianm 
Hi. I was on the Louverance path. In order, I did them: Tenzen, Ulmia, Louverance. Tried doing entire quest over again: talking to all npcs, zoning to oldton, shaft entrance cutscene, trading gold key to shaft, nothing flags. Thank you for your help.

**Comment by honeycubbinz** [comment]
Was able to get cutscene and have been able to make it through chapter 7 without any further issues. Thank you so much for your help!
