### ISSUE TITLE
Crafting 

### ISSUE THREAD

**Issue by Renothegreat** [LegionDark/Issues#1062]
**Date & Time**:  
8/28/16  5:55pm

**FFXI Client Version (use `/ver`)**: 
30160728__0
**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
yes

**Character Name**: 
Renokiribani

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
MNK99/WAR49

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Was told to make a gittracker for Crafting skills
![reno_2016 08 28_010304](https://cloud.githubusercontent.com/assets/21297502/18037031/8d9a9b12-6d48-11e6-9fae-a841d359c77b.png)

**Comment by Genesis-Legion** [comment]
Craft imported
