### ISSUE TITLE
Ghillie Dhu /checks as Very Tough instead of normal NM /check

### ISSUE THREAD

**Issue by Mizuharu** [LegionDark/Issues#1063]
**Date & Time**: 
August 29th, 2016 (08/29/2016) @01:39 PM CST

**FFXI Client Version (use `/ver`)**: 
Version 30160728_0
**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
No; @ecv = 30160329_0

**Character Name**: 
Zixum

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
Thief11/----

**NPC or Monster or item Name**: 
Ghillie Dhu

**Zone name & Coordinates (use `@where`)**: 
Konschtat Highlands | (J-10) | X: 385 Y: -8 Z:-336 (82)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
1) Locate Ghillie Dhu
2) /check

I know it's a minor issue compared so some other problems that may be in game, but thought I should report it nonetheless. :v

**Comment by TeoTwawki** [comment]
Do. Not. Remove. The Effin. Formatting.

**Comment by TeoTwawki** [comment]
FYI, this bug is just a flag in Darkstar's table. Has to be fixed on their end.
