### ISSUE TITLE
Crafting

### ISSUE THREAD

**Issue by cloudchief25** [LegionDark/Issues#1064]
**Date & Time**: 
8/29/2016

**FFXI Client Version (use `/ver`)**: 
30160728
**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
yes

**Character Name**: 
Hiei

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
99thf/49nin

**NPC or Monster or item Name**: 
n/a

**Zone name & Coordinates (use `@where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
opening for craft
![hiei_craftskills](https://cloud.githubusercontent.com/assets/21297432/18070948/a4d2769c-6e1f-11e6-869c-4f238a1d4de8.JPG)

**Comment by Samikana** [comment]
Player was not online at 11:45AM on 8/31/16.  They have 3 days to either contact me in-game or respond to this thread to set up a time to meet.  :)

**Comment by cloudchief25** [comment]
I will be on tonight

**Comment by Samikana** [comment]
Please be aware fishing nor synergy skill will be transferred.  Your crafts have been transferred.  Please re-open your bug report if you have any issues.
