### ISSUE TITLE
Transfer Crafting Skill - Jasnah 

### ISSUE THREAD

**Issue by yelsaewnor** [LegionDark/Issues#1065]
Date & Time: 
8/29/2016 8:15 eastern 

FFXI Client Version (use /ver): 
30160728_0
Server's Expected Client Version matches, yes/no? (use @ecv): 
no (30160329_0) client is working fine and this does not seem to be an issue.

Character Name: 
Jasnah

Nation: 
Windy

Job(level)/Sub Job(level): 
99thf/49dnc

NPC or Monster or item Name: 
n/a

Zone name & Coordinates (use @where): 
n/a

ffxiah.com link (for items issues only): 
n/a

Multi-boxing? (multiple clients on same connection): 
no

Steps To Reproduce / any other info: 
crafting skill for transfered character
![yel_craftskills](https://cloud.githubusercontent.com/assets/21323531/18071755/3f5ff5b2-6e26-11e6-8b0e-7f6393af0a7a.JPG)

**Comment by TeoTwawki** [comment]
**Do not remove the formatting form the template ever again.** I am sick to death of telling people to not change text that was pre-filled for them to avoid exactly what you did: caused unrelated github users to be notified of this ticket. Stupid effing DSP may use `@` for in game commands but the rest of the bloody world does not. Github uses them for **[mentions](https://help.github.com/articles/mentions-on-github-pages/)**
