### ISSUE TITLE
Crafting Skill for Transfer

### ISSUE THREAD

**Issue by yelsaewnor** [LegionDark/Issues#1066]
**Date & Time**: 
8/29/2016 8:15 eastern

**FFXI Client Version (use `/ver`)**: 
30160728_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
no (30160329_0) client is working fine and this does not seem to be an issue.

**Character Name**: 
Jasnah

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
99thf/49dnc

**NPC or Monster or item Name**: 
n/a

**Zone name & Coordinates (use `@where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
crafting skill for transfered character
![yel_craftskills](https://cloud.githubusercontent.com/assets/21323531/18075322/c1d95144-6e41-11e6-82cb-7d59638697a0.JPG)

**Comment by Samikana** [comment]
Player was not online at 11:45AM on 8/31/16.  They have 3 days to either contact me in-game or respond to this thread to set up a time to meet.  :)

**Comment by yelsaewnor** [comment]
I am available tomorrow night (9/1) from 6:30PM until 11PM eastern. If this works for you see you then, if not let me know and we can set up a different time. Thanks. :)

**Comment by Samikana** [comment]
@yelsaewnor I'll be there to give you your crafts.  :)

**Comment by Samikana** [comment]
Please be aware fishing nor synergy skill will be transferred.  Your crafts have been transferred.  Please re-open your bug report if you have any issues.
