### ISSUE TITLE
Kukulkan

### ISSUE THREAD

**Issue by Najasa** [LegionDark/Issues#1067]
Date & Time: Aug 31st, 2016 2pm-4:20 pm EST (Multiple attempts at killing nm)

FFXI Client Version (use /ver): Ver. 30160728_0

Server's Expected Client Version matches, yes/no? (use @ecv): Yes?

Character Name: Najasa

Nation: San'Doria

Job(level)/Sub Job(level): 99MNK/49DNC

NPC or Monster or item Name: Kukulkan

Zone name & Coordinates (use @where): Abbyssea-Konschtat H-4/H-5

ffxiah.com link (for items issues only):

Multi-boxing? (multiple clients on same connection): Yes Multi-Boxing, but happens to other people regardless.

Steps To Reproduce / any other info: Not sure whats is actually producing the crash, maybe when NM uses TP Move?
This is making very difficult to win with a party or even an alliance closest I got by myself was 25% 5mins into fight Multi-boxing. 7+ Attempts and every time it crashes 2-4/6 Party members. This being a pre-requisite to get a KI for EE, rare drop rate for KI, then you need to kill EE for a small chance at 2nd Lunar Abbysite. You need 2nd Lunar Abbysite from EE to even unlock 109 Reforge Gear. Since the crashes and KI Drop rate alone are rare for this Pre-requisite, I think 2nd Lunar Abbysite should be moved to another zone until this is fixed.
Spent KI poping it, can't kill cause of it. Can i get push to EE?

**Comment by TeoTwawki** [comment]
```
<!-- 
DO NOT REMOVE OR CHANGE THE PRE-FORMATTED TEXT!!!
GITHUB SEES `@MENTIONS`, NOT `@GMCOMMANDS`!!!
IF YOU STUPIDLY IGNORE THIS WARNING I WILL CLOSE YOUR ISSUE!

Issues will also be closed without being looked into if 
the following information is missing (unless its not applicable)!!!
-->
```

Right there in the template itself..

**Comment by TeoTwawki** [comment]
P.s. there is likely an issue common to multiple Pieste type mobs. No we will not be giving anyone a clear to bypass it.
