### ISSUE TITLE
COP Mission 8-3 (When Angels Fall) Battle 

### ISSUE THREAD

**Issue by honeycubbinz** [LegionDark/Issues#1068]
**Date & Time**: 9/1/2016

**FFXI Client Version (use `/ver`)**: 30160602_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: yes

**Character Name**: Brandoh

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: THF(99)/DNC(49)

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: X:419 Y:0 Z:398 (111)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: Every character got key items for access to the top floor of The Garden of Ru'Hmet. Examining the Particle Gate doesn't produce a cutscene. Tried logging every character out and logging each one back on individually and checking the gate and still no luck. I received cutscenes for both the Brand of Twilight and the Brand of Dawn so I'm not sure why this isn't flagging.

**Comment by PikaFox** [comment]
Did you visit your race towers? **Everyone** forgets either one of the two, so generally its a good idea to ask before we do anything.

**Comment by PikaFox** [comment]
Part I
The first objective is for you to climb a specific tower of The Garden of Ru'Hmet, which are located in the five outlying points of the map. Each tower corresponds to a specific race.

Each player may complete this mission by climbing any one of the five towers. However, climbing the tower corresponding to your character's race will grant you a new title, and a key item that will help you in the following mission.

http://ffxiclopedia.wikia.com/wiki/When_Angels_Fall

**Comment by honeycubbinz** [comment]
I thought I did that too but I'm not positive so I'll try that again and see if it works. I'll try to do that here in the next few days so if you want to close the ticket you can. Thank you :)

**Comment by PikaFox** [comment]
Ill just put the player reply required tag on it for now since you need to check to do that.

**Comment by R3P0FFXI** [comment]
Lack of player response closing issue
