### ISSUE TITLE
Sync drk67 to lvl57 makes ACC incorrect

### ISSUE THREAD

**Issue by Alacard** [LegionDark/Issues#1069]
Date & Time: 
8/25/2016 6:31pm

FFXI Client Version (use /ver): 
30160728_0

Server's Expected Client Version matches, yes/no? (use @ecv): 
no

Character Name: 
Alacardjr

Nation: 
San d'Oria

Job(level)/Sub Job(level): 
DRK67/DNC33 sync DRK57/DNC28

NPC or Monster or item Name: 
N/A

Zone name & Coordinates (use @where): 
The Boyahda Tree
X:340 Y:8 Z-64 (57)
ffxiah.com link (for items issues only): 
N/A

Multi-boxing? (multiple clients on same connection): 
N/A

Steps To Reproduce / any other info: 
Sync to level 57, ACC go's to hell cant hit nothing. if you eat any ACC food ACC gets worse. when you unsync

**Comment by TeoTwawki** [comment]
Please tell Darkstar https://github.com/DarkstarProject/darkstar/issues this is obliviously not a Legion Server specific issue

**Comment by TeoTwawki** [comment]
Also, you borked the template and sent messages to unrelated persons. https://help.github.com/articles/mentions-on-github-pages/
