### ISSUE TITLE
animated knuckles

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#107]
Date & Time: 6/19/2015 12:31pm CST
Frequency: once
FFXI Client Version:30150508_8
Character Name:Itachioax
Race:Hume
Main Job:Thf
Sub Job:Dnc
Area & Coordinates:Dynamis Xarcabard (H-8)
Party or Solo:solo
NPC Name: none
Monster Name:Animated knuckles
Steps To Reproduce The Issue:
iw as trying to farm this fragment for relic h2h, but animated knuckles never shows, i got check all the map and nothing, in this same run i got relic bow fragment without problem

**Comment by R3P0FFXI** [comment]
Itachioax, please make sure you popped everything required for ht eNM to show and did not just walk around 1 shotting everything. It is my experince people that have issues with the NM popping in dynamis usually do not let all the mobs or PH pop as they should

**Comment by R3P0FFXI** [comment]
Is this still an issue?

**Comment by R3P0FFXI** [comment]
Still an issue last time I will ask after this if no response by tomorrow closing ticket

**Comment by R3P0FFXI** [comment]
No response from suer in a week closing ticket
