### ISSUE TITLE
Farming Ansherikh and no drop King Hide (Extremely rare drop?)

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#1070]
**Date & Time**: 2016/04/09 8:16 AM

**FFXI Client Version (use `/ver`)**: 30160728_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 30160329_0

**Character Name**: Dimasp

**Nation**: San'doria

**Job(level)/Sub Job(level)**: THF99/DNC49

**NPC or Monster or item Name**: Ansherekh

**Zone name & Coordinates (use `@where`)**: X:-514 Y:0 Z:-62 (215)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/3232/tiger-king-hide

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: 
Last night I was there trying to drop this item but after 21 times killing the NM nothing fell , I looked you what is happening , my thf has treasure hunter 8

**Comment by R3P0FFXI** [comment]
Tiger Kings Hide	6.00%

http://legiondark.com/db/items/3232/tiger_kings_hide

working as intended

**Comment by PikaFox** [comment]
For future reference, there is an item drop tool on the main website that lists what drops where and what percent it drops at, so you dont need to open a bug report to ask if something drops. Check there first.
