### ISSUE TITLE
NO Drop Forgotten Journey 

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1071]
Date & Time: 2016/04/09 8:16 pm

FFXI Client Version (use /ver): 30160629_0

Server's Expected Client Version matches, yes/no? (use @ecv): 30160629_0

Character Name: Rukitsu

Nation: San'doria

Job(level)/Sub Job(level): THF99/DNC49

NPC or Monster or item Name: 

Zone name & Coordinates (use @where): Dynamis-qufim	    X: -83, Y: -19, Z: 177

ffxiah.com link (for items issues only): http://www.ffxiah.com/item/3496/frgtn-journey

Multi-boxing? (multiple clients on same connection): no

Steps To Reproduce / any other info: hello ,I kill all the mobs in dynamis and 0 drop 

me use TH 11 and 12 and no drop Forgotten Journey

**Comment by R3P0FFXI** [comment]
http://legiondark.com/db/items/3496/forgotten_journey

This does drop as players have it in their bazzar

**Comment by TeoTwawki** [comment]
```<!-- 
DO NOT REMOVE OR CHANGE THE PRE-FORMATTED TEXT!!!
GITHUB SEES `@MENTIONS`, NOT `@GMCOMMANDS`!!!
IF YOU STUPIDLY IGNORE THIS WARNING I WILL CLOSE YOUR ISSUE!

Issues will also be closed without being looked into if 
the following information is missing (unless its not applicable)!!!
-->
