### ISSUE TITLE
Locating Nagi (Lvl 75 NIN Mythic Wpn) in Database

### ISSUE THREAD

**Issue by Najasa** [LegionDark/Issues#1072]
**Date & Time**: 20160904 1504

**FFXI Client Version (use `/ver`)**: N/A 

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: N/A 

**Character Name**: N/A

**Nation**:  N/A

**Job(level)/Sub Job(level)**: N/A 

**NPC or Monster or item Name**: NAGI, LVL75 BASE WEAPON

**Zone name & Coordinates (use `@where`)**: ZNM TIER 3

**ffxiah.com link (for items issues only)**:  http://www.ffxiah.com/item/19003/nagi

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: Searching through the Database, the item nor monster tool gives any hints as to where this item could possibly drop from. Normally they suppose to drop from one of the Tier 3 ZNMs, but there are no records of it.

**Comment by Nususu** [comment]
#985

**Comment by PikaFox** [comment]
Iirc it was supposed to drop from Nosferatu.

http://legiondark.com/forums/viewtopic.php?f=27&t=8&p=8&hilit=nagi#p8

Nosferatu


75 Terpsichore
75 Nagi
75 Gastraphetes

Ares body
Ogiers body x2
Windbuffet belt +1

Hes missing the mythics now.

**Comment by R3P0FFXI** [comment]
@Najasa Issue resolved in Maint Yesterday
