### ISSUE TITLE
af+1 reforged  ERROR

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1073]
Date & Time: 2016/04/09 8:16 pm

FFXI Client Version (use /ver): 30160629_0

Server's Expected Client Version matches, yes/no? (use @ecv): 30160629_0

Character Name: Aurel
![img_20160904_162943](https://cloud.githubusercontent.com/assets/13084662/18233405/08c948fa-72bd-11e6-889a-8a1b73e5b7b4.png)

Nation: San'doria

Job(level)/Sub Job(level): DRK99/DNC49

NPC or Monster or item Name: Renik

Zone name & Coordinates (use @where): 

ffxiah.com link (for items issues only):
 http://www.ffxiah.com/item/28251/igno-sollerets-1 

http://www.ffxiah.com/item/28118/igno-flan-1

Multi-boxing? (multiple clients on same connection): no

Steps To Reproduce / any other info
i have trade 
http://www.ffxiah.com/item/28097/ignominy-flanchard + 5 rems chap 2 ,and i obtain pld feet af1 http://www.ffxiah.com/item/28117/rev-breeches-1
i have trade
http://www.ffxiah.com/item/28230/igno-sollerets +5 rems chap 1,and i obtain
http://www.ffxiah.com/item/28250/rev-leggings-1

**Comment by TeoTwawki** [comment]
```
<!-- 
DO NOT REMOVE OR CHANGE THE PRE-FORMATTED TEXT!!!
GITHUB SEES `@MENTIONS`, NOT `@GMCOMMANDS`!!!
IF YOU STUPIDLY IGNORE THIS WARNING I WILL CLOSE YOUR ISSUE!

Issues will also be closed without being looked into if 
the following information is missing (unless its not applicable)!!!
-->
```
https://raw.githubusercontent.com/LegionDark/Issues/master/ISSUE_TEMPLATE.md
