### ISSUE TITLE
af+1 reforged ERROR

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1074]
**Date & Time**: 2016/04/09 8:16 pm

**FFXI Client Version (use `/ver`)**: 30160629_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 30160629_0

**Character Name**: 
Aurel

**Nation**: 
sandy

**Job(level)/Sub Job(level)**: 
drk/dnc

**NPC or Monster or item Name**: 
Renik

**Zone name & Coordinates (use `@where`)**: x:-15, y:0 , z:40 (54)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/28251/igno-sollerets-1

http://www.ffxiah.com/item/28118/igno-flan-1

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: i have trade 
http://www.ffxiah.com/item/28097/ignominy-flanchard + 5 rems chap 2 ,and i obtain pld feet af1 http://www.ffxiah.com/item/28117/rev-breeches-1
i have trade
http://www.ffxiah.com/item/28230/igno-sollerets +5 rems chap 1,and i obtain
http://www.ffxiah.com/item/28250/rev-leggings-1

![img_20160904_162943](https://cloud.githubusercontent.com/assets/13084662/18234347/4348e9ca-72d8-11e6-8716-bbcc27cf9868.png)

**Comment by Samikana** [comment]
This issue will be fixed in the update.  I will give you the chapters and NQ version back, but you're going to have to wait until after the update to trade them.

**Comment by Aurelcassy** [comment]
ok ty

**Comment by R3P0FFXI** [comment]
Gave player missing items
