### ISSUE TITLE
Shabti Cuisses Not giving correct stat bonuses

### ISSUE THREAD

**Issue by Brenketsu** [LegionDark/Issues#1075]
**Date & Time**: 
02:20 06/09/2016

**FFXI Client Version (use `/ver`)**: 
30160728_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
Yes

**Character Name**: 
Tleaf

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
WAR 99

**NPC or Monster or item Name**: 
Shabti Cuisses

**Zone name & Coordinates (use `@where`)**: 
x:207 Y:10 z:76

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/28178/shabti-cuisses

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
It seems that this item is giving incorrect stat bonuses. it should give STR+27 VIT +23
AGI+11 etc. However when I equip this item I receive no stat bonuses at all, it is infact as if I have not equipt anything to that armour slot(legs)

**Comment by Samikana** [comment]
Hey there, Shabti Cuisses aren't coded.  It looks like they somehow got misplaced during our last update, as I know that I coded them.  I'm going to ask @PikaFox  to recode them when they have time.

**Comment by PikaFox** [comment]
This is why i save everything i do.

Sent an email with what i had before, should still be accurate.

**Comment by R3P0FFXI** [comment]
@Brenketsu This has been resolved and will be included in Next maint

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
