### ISSUE TITLE
Pages not working

### ISSUE THREAD

**Issue by Samikana** [LegionDark/Issues#1078]
**Date & Time**: Sept 6 2016 9:16PM

**FFXI Client Version (use `/ver`)**: 30160728_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: ya dawg

**Character Name**: Halsey

**Nation**: Bastok

**Job(level)/Sub Job(level)**: RDM/DNC

**NPC or Monster or item Name**:  all

**Zone name & Coordinates (use `@where`)**: Crawler & Valk

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: nah

**Steps To Reproduce / any other info**: Tested Crawlers pages 1 and 3, as well as Page 1 in Valkurm.  No pages give credit no matter if you're in lvl range or below it for intended levels.

**Comment by TeoTwawki** [comment]
fixed
