### ISSUE TITLE
Cannot Use Scroll of Gravity II

### ISSUE THREAD

**Issue by mabrewer** [LegionDark/Issues#1079]
**Date & Time**:  12:18 AM, 09/07/2016

**FFXI Client Version (use `/ver`)**: 30160728_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: Yes

**Character Name**: Kysia

**Nation**: Windurst

**Job(level)/Sub Job(level)**: RDM 99/WHM 49

**NPC or Monster or item Name**: Refresh

**Zone name & Coordinates (use `@where`)**: Everywhere

**ffxiah.com link (for items issues only)**: [http://www.ffxiah.com/item/4825/gravity-ii](url)

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Attempt to use the scroll (Get Error Text "Cannot Use Scroll of Gravity II on Kysia"

**Comment by TeoTwawki** [comment]
Fixed in darkstar https://github.com/DarkstarProject/darkstar/pull/3452

**Comment by R3P0FFXI** [comment]
@mabrewer this should now be resolved please let us know if it is not
