### ISSUE TITLE
CoP 8-3 Shale Tunk Skeye

### ISSUE THREAD

**Issue by Valknut4** [LegionDark/Issues#108]
**Date & Time**:  6/20/2015
**Frequency**: 3/3
**FFXI Client Version**: 1.18.15e
**Character Name**: Shale=Tunk & Skeye
**Race**: Elvaan Taru Mythra
**Main Job**: DRG/WAR BLM/WHM DRK/SAM
**Sub Job**:DRG/WAR BLM/WHM DRK/SAM
**Area & Coordinates**: 8-3 Battle ground door " Particle Gate "
**Party or Solo**: Party
**NPC Name**: Particle Gate
**Monster Name**: NA
**Steps To Reproduce The Issue**: Got both brands on 2 seperate characters got same result of battle ground CS at PArticle Gate not triggering

**Comment by R3P0FFXI** [comment]
User was dual boxing and PromathiaStatus variable was not changed to 4 after clicking the door 2x
