### ISSUE TITLE
Blade: Yu has 100% miss rate

### ISSUE THREAD

**Issue by Mizuharu** [LegionDark/Issues#1080]
**Date & Time**: 
9/7/2016; September 7th, 2016

**FFXI Client Version (use `/ver`)**: 
30160728_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
30160728_0

**Character Name**: 
Zixum

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
Ninja 80/Dancer 40

**NPC or Monster or item Name**: 
N/A

**Zone name & Coordinates (use `@where`)**: 
Anywhere

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes, but bug happens when I'm not multi-boxing.

**Steps To Reproduce / any other info**: 
1) Be Ninja with access to Blade: Yu and 1000+ TP.
2) Target anything you can engage in combat. Crabs in the tree or bees in Gustaberg; results are the same.
3) Use Blade: Yu.

![zixum_2016 09 07_193559](https://cloud.githubusercontent.com/assets/21317503/18333187/86642f7e-7532-11e6-921c-d53d168b202f.png)

**Comment by TeoTwawki** [comment]
Try it now. Seems it was misisng a script param that indicates if the ws is able to crit or not.

**Comment by Mizuharu** [comment]
It lands now! However, the TP return was 10. The other water-elemental WS, Blade: Teki, has a TP return of 46 with no Store TP+ gear on. Will get a screenshot for the two weapon skill TP returns if needed.

**Comment by TeoTwawki** [comment]
If you can prove that, you'll have to show that to Darkstar over at https://github.com/DarkstarProject/darkstar/issues/new

There is nothing script side to control the tp return of a ws (aside from artificially giving out free TP, which isn't happening in Teki' script).

Go ahead and update me here too if you happen to do that or figure out why the TP return differed.
