### ISSUE TITLE
Blue Mage Tool

### ISSUE THREAD

**Issue by piglorian** [LegionDark/Issues#1081]
**Date & Time**: 1:12 pm CST

**FFXI Client Version (use `/ver`)**:  N/A

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: N/A

**Character Name**: N/A

**Nation**: N/A

**Job(level)/Sub Job(level)**: N/A

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: In the Blue Mage Tool on the website, it is pulling incorrect data as to which mobs to kill for cretin spells if it even shows up at all.  For example: Fantod is supposed to obtained from Hippogryphs.  Now it says it can be obtained by Fenrir Prime.  I've checked several spells and they are either not on the correct mobs or they say Sorry, but the requested spell could not be loaded.  If you need more examples, please let me know.

**Comment by R3P0FFXI** [comment]
@piglorian Some Blu spells are scripted some are database in SQL, Spells that are script will never show in the tool. wont be looked at anytime soon

**Comment by TeoTwawki** [comment]
I may have accidentally dropped in the newer blu magic table during the last update which would mean all the IDs matching them up to a monster's TP attacks are off..This will be corrected shortly, as the next update is almost ready anyhow.

**Comment by R3P0FFXI** [comment]
Issue resolved in massive Update part 2

**Comment by R3P0FFXI** [comment]
Issue does not appear to be resolved

**Comment by atom0s** [comment]
This issue should be posted under the Website reports. This is a website issue.
https://github.com/LegionDark/Website

**Comment by atom0s** [comment]
This should be fixed now.
