### ISSUE TITLE
Ladycapulets Crafting skills.

### ISSUE THREAD

**Issue by Juiliet** [LegionDark/Issues#1083]
**Date & Time**: 1:00am CST

**FFXI Client Version (use `/ver`)**: 30160728_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: Yes

**Character Name**: Ladycapulet

**Nation**: Bastok

**Job(level)/Sub Job(level)**: RDM90

**NPC or Monster or item Name**: Crafting Skills

**Zone name & Coordinates (use `@where`)**: Bastok Market Moghouse

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/player/Sylph/Juiliet (Crafting skills of the transfer character)  http://legiondark.com/forums/viewtopic.php?f=37&t=1701 (Original Post)

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:

**Comment by Samikana** [comment]
When is a good time to meet you in-game?  I'm off today and tomorrow and can make something work.  :)

**Comment by Juiliet** [comment]
Today once i Figure out what I need to update the game, Been unable to sign on since it was introduced

**Comment by Juiliet** [comment]
Currently logged in.

**Comment by R3P0FFXI** [comment]
@Juiliet please reply if this has not been completed

**Comment by Juiliet** [comment]
This has not been Resolved. If it possible can we set a time for wednesday?

**Comment by R3P0FFXI** [comment]
@Juiliet please login to IRC and get with a GM to resolve this

**Comment by TeoTwawki** [comment]
@LegionDark/gm -*bump*-

**Comment by R3P0FFXI** [comment]
No response from player

**Comment by TeoTwawki** [comment]
Actually they DID. And then no either GM got with them or updated this ticket.

**Comment by Juiliet** [comment]
Bump, Reason for it was because after a update in sept I was unable to log in till now. Is it possible to have this Reviewed again now that I am able to sign on?

**Comment by Juiliet** [comment]
Thank you, Please let me know when to log her in, So that I may have this resolved

**Comment by R3P0FFXI** [comment]
@Juiliet please contact as GM on discord so that we can resolve this

**Comment by Juiliet** [comment]
Understood I will connect later tonight.

**Comment by R3P0FFXI** [comment]
Has been completed per GM chat in Discord
