### ISSUE TITLE
Tachi Fudo available MUCH earlier than intended

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1084]
**Date & Time**: 9/11/16

**FFXI Client Version (use `/ver`)**: 30160728_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: yes

**Character Name**: Tarot

**Nation**: San

**Job(level)/Sub Job(level)**: Sam 49

**NPC or Monster or item Name**: NA

**Zone name & Coordinates (use `@where`)**: NA

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 
Tachi: Fudo is usable at lower level/combat skill than intended

**Comment by PikaFox** [comment]
The drag and drop images onto github templates really didnt want to cooperate...

**Comment by PikaFox** [comment]
![tarot_2016 09 11_105922](https://cloud.githubusercontent.com/assets/12601727/18418176/836ba984-780f-11e6-9221-6c93dd36b63d.png)

![tarot_2016 09 11_105934](https://cloud.githubusercontent.com/assets/12601727/18418178/89a0cac8-780f-11e6-8208-24dc8480cb2a.png)

**Comment by TeoTwawki** [comment]
Not sure it server has to restart for it to notice, but I fixed.
