### ISSUE TITLE
Caliyoh Crafting skills

### ISSUE THREAD

**Issue by caliyoh** [LegionDark/Issues#1085]
**Date & Time**: 11:00 pm GMT

**FFXI Client Version (use `/ver`)**: 30160728_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: Yes

**Character Name**: Toki

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: SAM95

**NPC or Monster or item Name**: Crafting Skills

**Zone name & Coordinates (use `@where`)**: Sandoria North Mog House

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/player/Asura/Caliyoh (Crafting skills of the transfer character) http://legiondark.com/forums/viewtopic.php?f=37&t=1700 (Original Post with screen crafting)

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:

**Comment by Samikana** [comment]
What is a good time for you to be on?  I'm off of work today and tomorrow and can make something work.  :)

**Comment by caliyoh** [comment]
Hello
Thank you for your help. as I am gmt + 1 french I'm not on the game 
8.00am to 16.00pm GMT +1 tomorrow.
see you soon:-)

**Comment by caliyoh** [comment]
but i can log today 16h30 to 20h00 gmt+1
just tell me or i play with me other character "louve" on the server
ty


Envoyé depuis mon appareil Samsung


-------- Message d'origine --------
De : Sami <notifications@github.com>
Date : 19/09/2016 14:06 (GMT+01:00)
À : LegionDark/Issues <Issues@noreply.github.com>
Cc : caliyoh <tokiyohki@live.fr>, Author <author@noreply.github.com>
Objet : Re: [LegionDark/Issues] Caliyoh Crafting skills (#1085)


What is a good time for you to be on? I'm off of work today and tomorrow and can make something work. :)

**Comment by caliyoh** [comment]
hi again 
excuse me you think you can work on me craft skill or it s imposible??

**Comment by R3P0FFXI** [comment]
@caliyoh please respond if this has not been completed

**Comment by R3P0FFXI** [comment]
No response closing
