### ISSUE TITLE
AF+1 reforge error

### ISSUE THREAD

**Issue by T3RT1UM** [LegionDark/Issues#1086]
**Date & Time**: 9/15/2016

**FFXI Client Version (use `/ver`)**: 30160728_0

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: yes

**Character Name**: Kurare

**Nation**: Bastok

**Job(level)/Sub Job(level)**: Thief(99)/Warrior(49)

**NPC or Monster or item Name**: Renik

**Zone name & Coordinates (use `@where`)**: Upper Jeuno, X:-16 Y:0 Z:37 (238)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/28096/rev-breeches

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 

Traded item http://www.ffxiah.com/item/28096/rev-breeches + 5x REM chapter 2
and obtained http://www.ffxiah.com/item/28116/pill-culottes-1

![kurare_2016 09 15_232147](https://cloud.githubusercontent.com/assets/22230953/18575640/bcb425e8-7b9f-11e6-81bb-d5e21da1c3d1.png)

**Comment by TeoTwawki** [comment]
@LegionDark/gm the npc should be fixed now, so this player just needs the item he already got refunded or swapped out.

**Comment by T3RT1UM** [comment]
yea i need the item swapped to the right one

**Comment by T3RT1UM** [comment]
![kurare_2016 09 18_005819](https://cloud.githubusercontent.com/assets/22230953/18613214/239fd738-7d3b-11e6-8fa5-1cc9f45b3708.png)

**Comment by atom0s** [comment]
Handled in game.
