### ISSUE TITLE
wotg progression out of sync

### ISSUE THREAD

**Issue by sucidaldeathtar** [LegionDark/Issues#1087]
**Date & Time**: 
9/17/16

**FFXI Client Version (use `/ver`)**: 
30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
sucidaldeath

**Nation**: 
sandy

**Job(level)/Sub Job(level)**: 
sam99/war49

**NPC or Monster or item Name**: 
mission:  Cait sith now was back to the beginning

**Zone name & Coordinates (use `$where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
yes fine on other char

**Steps To Reproduce / any other info**: 
I went back to the past right after server up and this popped up now after server went up again I'm out of sync with my progression.

**Comment by TeoTwawki** [comment]
I don't understand your meaning of "out of sync". you aren't describing whats wrong.

**Comment by sucidaldeathtar** [comment]
I have up  to Purple, The New Black done.  but after the first server reset I'm now back at the beginning again.  After the 2nd restart I can do maws normally again but the mission is still progressing from the start again.   Be going through it and it looks like all I need to do is redo the cs but I don't know if its messing anything up by doing that.

**Comment by TeoTwawki** [comment]
do nothing for the moment. I have to check some stuff on your character in game. You might have found a darkstar bug that triggers adding back missions you already had done. I fixed similar bugs in Zilart and Chain of Promathia before..

**Comment by sucidaldeathtar** [comment]
ok I wont login on that toon ill be on sucidaldeathtwo lol

**Comment by TeoTwawki** [comment]
Player on legion fixed,
Bug on DSP fixed
https://github.com/DarkstarProject/darkstar/pull/3461
