### ISSUE TITLE
Morta spawn fixed, but now loot pool missing

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1088]
**Date & Time**: 17-9-16

**FFXI Client Version (use `/ver`)**: 30160831-1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Aurel

**Nation**: sandy

**Job(level)/Sub Job(level)**: blu/rdm

**NPC or Monster or item Name**: Morta

**Zone name & Coordinates (use `$where`)**:  X: 441.07, Y: -26.85, Z: 396.726 :	Aydeewa Subterrane

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
i have ki so NM no pop
![img_20160917_210258](https://cloud.githubusercontent.com/assets/13084662/18611750/55846faa-7d1a-11e6-8a31-c1df5624546b.png)

![img_20160917_210645](https://cloud.githubusercontent.com/assets/13084662/18611755/c262dd28-7d1a-11e6-98c0-5960b1875223.png)

**Comment by TeoTwawki** [comment]
Darkstar made a change that broke all legions rift scrips - all of them :weary: 
I'm working on fixing them.

**Comment by TeoTwawki** [comment]
Additional discoveries: you were at the wrong rift (Morta one seems to be at pos x:280 y:1 z: 396) but the IDs in the entire zone are screwed up. Even if you had been in right place though, it wouldn't have worked. We needs to fix the scripts and the IDs before it will work. :(

**Comment by TeoTwawki** [comment]
@Aurelcassy give it a try now, let me know how it goes.

**Comment by R3P0FFXI** [comment]
@TeoTwawki Morta now pops but the NPC is named Tulmult Lamp and Not Planar Rift

**Comment by Aurelcassy** [comment]
Where pop now ???? no planar in zone???

![2015_04_02_07_17_31_396](https://cloud.githubusercontent.com/assets/13084662/19313259/df4a5914-9063-11e6-972d-cad8940fbfcf.jpg)

**Comment by TeoTwawki** [comment]
@Aurelcassy are you at the wrong place again? Because R2P0FFXI saw it and it had wrong name.

**Comment by TeoTwawki** [comment]
@Aurelcassy I see what happened between him looking and you looking, sorry. It should be present where he was at now..

**Comment by Aurelcassy** [comment]
Hi ,,,now work pop of morta ,so no have drop ,,,

![captura](https://cloud.githubusercontent.com/assets/13084662/19410406/b53f1d3c-92b9-11e6-969c-3b7527d73ed3.PNG)

**Comment by TeoTwawki** [comment]
I think translation was off there, uncertain of intention

**Comment by TeoTwawki** [comment]
Drops are missing?

**Comment by Aurelcassy** [comment]
only check page 

![captura](https://cloud.githubusercontent.com/assets/13084662/19410444/9da2ce8e-92ba-11e6-9af9-8eb7224793e3.PNG)

**Comment by Aurelcassy** [comment]
Unknown is = to 0 drop in NM 

![captura](https://cloud.githubusercontent.com/assets/13084662/19410453/d95f5578-92ba-11e6-8375-b32a35f1380a.PNG)

**Comment by TeoTwawki** [comment]
Ic.

**Comment by TeoTwawki** [comment]
moving this to  #1172
