### ISSUE TITLE
Ogbunabali Spawns underground/invisible

### ISSUE THREAD

**Issue by R3P0FFXI** [LegionDark/Issues#1089]
**Date & Time**:  9/18/2016

**FFXI Client Version (use `/ver`)**:  30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: God

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: Ogbunabali

**Zone name & Coordinates (use `$where`)**: -280, 0, -119, 164

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
Spawn Ogbunabali as normal by clicking the Planar rift, VWNM (antlion) spawns underground also does not show in website.

**Comment by TeoTwawki** [comment]
need to retest after next maint. I might have fixed it but the changes don't take effect without reloading sql tables and restarting the server.

**Comment by R3P0FFXI** [comment]
@TeoTwawki I tested this today, the NM now shows on the website as it should under monster lookup, however it still spawns invisible server restarted at 6am EST today

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
