### ISSUE TITLE
voidwatch NM

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#109]
Date & Time: 20/06/2015
Frequency:
FFXI Client Version: 30150508_5
Character Name: Bathuka
Race: Elvaan
Main Job:pld
Sub Job:nin
Area & Coordinates:north gustaberg and (S)(M-8) 
Party or Solo:PARTY
NPC Name:
Sallow Seymour -- (M-8) 
spam ability (mud stream) = wipe 
http://img15.hostingpics.net/pics/145110Bathuka20150620220544.png

Noth gustaberg ( s ) Ushumgal -- (M-8) = pol crash all account 88%

after 2 night test VWNM lost 4 stone ( first test abyssite do not up T2 ) i know that is repair now

**Comment by Loki79** [comment]
spam ability (mud stream) = wipe  ~ this is working correctly.  you were just unlucky

Noth gustaberg ( s ) Ushumgal -- (M-8) = pol crash all account 88% ~ POL.exe crash also has nothing to do with the mob.
