### ISSUE TITLE
Chant du Cygne Missing from Almace

### ISSUE THREAD

**Issue by R3P0FFXI** [LegionDark/Issues#1090]
**Date & Time**: 9/18/2016

**FFXI Client Version (use `/ver`)**: NA

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: God

**Nation**: 

**Job(level)/Sub Job(level)**: 99 PLD

**NPC or Monster or item Name**: NA

**Zone name & Coordinates (use `$where`)**: NA

**ffxiah.com link (for items issues only)**: 
https://www.bg-wiki.com/bg/Chant_du_Cygne

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Equipped 99-4 Alamce, weaponskill is missing
85 PLD, RDM, or BLU via Almace, Badelaire, +1, +2, +3, or Brunello

**Comment by TeoTwawki** [comment]
Probably all the upper level Empyrean..

**Comment by tb1** [comment]
I few other people reporting this, I noticed it on my pally and rdm with almace.  Tried manual too (/ws ....) and no-go.  I'll just tell people it's being looked at and there is no ETA.

**Comment by TeoTwawki** [comment]
@tb1 its in the [known issues thread](http://legiondark.com/forums/viewtopic.php?t=1721&amp;sid=a221a9ba16aa01856e51b46760af4e60) and shouldn't take to much longer for us to have another update ready to handle said issues :)
