### ISSUE TITLE
Cannot Start Ranger Job Quest

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1091]
**Date & Time**: 9/18/16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Nyaarun

**Nation**: Win

**Job(level)/Sub Job(level)**: 38 war main

**NPC or Monster or item Name**: Perih Vashai 

**Zone name & Coordinates (use `$where`)**: Windurst Woods K-7

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 

Level 38 war, talk to NPC, no dialog, no quest flag

**Comment by TeoTwawki** [comment]
NPC name got mangled https://github.com/DarkstarProject/darkstar/commit/088aee8797fec7e34136b26284084db5f7995570?w=1

**Comment by TeoTwawki** [comment]
hot fixed on live with an alternate named till next maint fixes the name in the database
