### ISSUE TITLE
War lost ws Ruinator ,and empy ws

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1092]
**Date & Time**: 18-9-16

**FFXI Client Version (use `/ver`)**: 30160831-1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Aurel

**Nation**: sandy

**Job(level)/Sub Job(level)**: war -sam-drk -cor

**NPC or Monster or item Name**: ws empy

**Zone name & Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
War not have Ruinator ,and other job lost ws empy

**Comment by TeoTwawki** [comment]
Looking into multiple weaponskills right now. Some of this is normal as the unlockable code now works (so relic mythic etc requires the item) and some not (some ws we give out by skill because a quest to unlock it isn't implemented)

**Comment by Nususu** [comment]
On this topic, I have empy katana and even with it mainhand, cannot use Blade: Hi. If that's not new information, sorry for the redundancy.

**Comment by R3P0FFXI** [comment]
@Aurelcassy @TeoTwawki @Nususu This has been fixed and will be in the next maint pull
