### ISSUE TITLE
Crafts xferred

### ISSUE THREAD

**Issue by Devolnu** [LegionDark/Issues#1094]
**Date & Time**: 
9/19   4:26

**FFXI Client Version (use `/ver`)**: 
30160831_1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Devolnu

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
84thf/42dnc

**NPC or Monster or item Name**: 
N/A

**Zone name & Coordinates (use `$where`)**: 
Korroloka Tunnel

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/player/Phoenix/Devolnu

**Multi-boxing? (multiple clients on same connection)**: 
Elbavolnu

**Steps To Reproduce / any other info**: 
I would like to have my Crafts transferred to my character. Thank you.
http://legiondark.com/forums/viewtopic.php?f=39&t=1600

**Comment by PikaFox** [comment]
Done
