### ISSUE TITLE
Aqueduct Spider is not UP ate all.

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#1097]
**Date & Time**: 09/20/2016 (9:11AM)

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Dimma

**Nation**: Sand'Oria

**Job(level)/Sub Job(level)**: DNC99/THF49

**NPC or Monster or item Name**: Aqueduct Spider

**Zone name & Coordinates (use `$where`)**: X:-214 Y:-11 Z:60 (19)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/2198/w-spiders-web

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: The monster that who drop the (Water Spider's Web ) is not online in your position , I believe that there exists a bug.

**Comment by R3P0FFXI** [comment]
All Spiders are in database but have no position data in the database

**Comment by R3P0FFXI** [comment]
@Dimmabr reported this to DSP awaiting packet caps of the POS for the spiders

**Comment by R3P0FFXI** [comment]
Sacrarium MOB positions  https://1drv.ms/t/s!AgGsYAwvj7kajBlmKZKq8Rr5kpfW

**Comment by R3P0FFXI** [comment]
Aquiducts MOB positions http://pastebin.com/f0tahfNU

**Comment by R3P0FFXI** [comment]
Fixed for Aquiducts in maint
