### ISSUE TITLE
Unable to receive PM6-2 Cutscene

### ISSUE THREAD

**Issue by Brenketsu** [LegionDark/Issues#1098]
**Date & Time**: 
23:04 20/09/2016

**FFXI Client Version (use `/ver`)**: 
30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Nemu

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
RDM99/WHM

**NPC or Monster or item Name**: 
NA

**Zone name**: 
Ru'Lude Gardens

**Coordinates (use `$where`)**: 
X:0 Y:2 z:45

**ffxiah.com link (for items issues only)**: 
NA

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
I am trying to receive the cutscene from PM6-2 which is activated when approaching the palace.
I was 1st attempting to do this mission with two other mules which I had on auto follow. The cut scene activated as expected for the two mules Lteaf and Crysis. However it id not on Nemu. 
I took 3 obvious steps to see if it resolved the issue but so far nothing.

1. I have double checked that I have received all previous cutscenes, so this is not an issue.
2. I have tried re-zoning but to no effect
3. I tried loggout out ALL characters and re-logged with only Nemu and also re-zoning again.

**Comment by R3P0FFXI** [comment]
@Brenketsu try redoing the entire chapter 6 cutscene order. Restart your PC log in no other characters but the one you are having an issue with then test it is probably missing a flag between 6-1 and 62, there are issues with multiboxing and multiple characters receiving missions updates its a DSP thing.

**Comment by Brenketsu** [comment]
Hi R3P, I have tried this but to no avail
The guts of 6-1 is to talk to NPC: Pherimociel
And click the door of Lower Jeuno Eatery 
I have retried both of these but so far nothing.

**Comment by Brenketsu** [comment]
One thing not tried yet is the reboot. Ill give it a try soon.

**Comment by TeoTwawki** [comment]
> Brenketsu closed this a minute ago

Resolved then?

**Comment by TeoTwawki** [comment]
Thing about multi boxing is as far as the server is concerned you still are until *all* characters are logged out and then *one* logs back in, and even after that you have to repeat everything...And sometimes you can't because half of something registered and the other half didn't.

Sadly its both impossible to prevent this and not reasonable to declare multi-boxing not allowed (not to mention, unenforceable)

**Comment by Brenketsu** [comment]
Would it be possible I could also be missing tags from the previous chapter?

I have now tried the reboot and also tried to redo PM6-1 and am having the same result.

**Comment by R3P0FFXI** [comment]
@Brenketsu Yes its possible your missing something from chapter 5

**Comment by TeoTwawki** [comment]
Someone will have to get with you in game and check your variables and any KI involved to see what step you are missing the the script wants.

**Comment by Brenketsu** [comment]
Ok, I look back as far as the last BattleField. hopefully this rabbit hole doesnt go too deep :s.

**Comment by Brenketsu** [comment]
Ok, I've been back to everything as far as the Goblin Fight, nothing there so far and thats All I have done on CoP today. Would appreciate a variable check when you guys get a chance, no rush I can wait untill tomorrow if neccessary.

**Comment by PikaFox** [comment]
elseif (player:getCurrentMission(COP) == A_PLACE_TO_RETURN and player:getVar("PromathiaStatus") == 0) then
            player:startEvent(10048);

Their var was 1

1 was required to do the next part of the mission.

Apparently the CS didnt play, but the Var did change, from what i can guess.

**Comment by PikaFox** [comment]
Gunna leave player reply required until player can confirm they completed the mission successfully just incase

**Comment by Brenketsu** [comment]
Hey guys, yes everything is working as it should now. I've moved onto the next cut scenes. Thanks for taking the time to look at this for me. Sorry for any inconvenience as I know dual boxing issues can be a bit of a head ache for you guys.
