### ISSUE TITLE
Renik is charging 5000 Bayld for Rusted Coin Upgrades

### ISSUE THREAD

**Issue by Nafff** [LegionDark/Issues#1099]
**Date & Time**: 9/20/16 3:28PM PST

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Naffin

**Nation**: Sandoria Rank 6

**Job(level)/Sub Job(level)**: THF99/DNC49

**NPC or Monster or item Name**: Renik

**Zone name**: Upper Jueno

**Coordinates (use `$where`)**: X: -14 Y:0 Z:37 (190)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/26893/taeon-tabard

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Pre-update Renik did not charge Bayld to upgrade Rusted Coins gear only for upgrading AF1-3 Armor. Post update I found out when upgrading Taeon Chapeau he charged 5000 Bayld. I tried again with Taeon Tabard to make sure it was actually charging and did not have enough Bayld to upgrade. I was curious if this was intentional with the update or an error?

**Comment by PikaFox** [comment]
The AH items required for the trades are listed below. 

· Adaman --> Yorium
· Royal Squires --> Acro
· Wool Gambison --> Taeon
· Traders --> Telchine
· Errant --> Helios

The trade requires the same item from one set to get the other. For example, for Yorium head you would need

Adaman Barbuta + 5 Rusty Coins + 5,000 Bayld.

http://legiondark.com/forums/viewtopic.php?f=66&t=889&p=2727&hilit=Voidwatch+Jeuno#p2727

Intended as far as i can tell.
