### ISSUE TITLE
Summoner's Horn +2 gives no Perpetuation Cost -

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#11]
**Date & Time**: 5/26/15
**Frequency**: NA
**FFXi Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: Hume
**Main Job**: Smn 92
**Sub Job**: NA
**Area & Coordinates (Type @where to get this info.)**: NA
**Party or Solo**: NA
**NPC Name**: NA
**Monster Name**: NA
**Steps To Reproduce The Issue**: Equip Summoner's Horn +2, get no Avatar Perpetuation Cost -, should be -3

**Comment by R3P0FFXI** [comment]
Added mod 346 +3
