### ISSUE TITLE
Traded AF3 + Seals - Never received +1 item back

### ISSUE THREAD

**Issue by Skett** [LegionDark/Issues#110]
**Date & Time**: 20/06/2015 22:45
**Frequency**: Once
**FFXI Client Version**:30150508_5
**Character Name**: Skett
**Race**: Elvaan
**Main Job**: THF 99
**Sub Job**: NIN 49
**Area & Coordinates**: x:-48 Y:0 Z:-8 (240)
**Party or Solo**: Party
**NPC Name**: Moogle (AF3 Upgrade)
**Monster Name**: N/A
**Steps To Reproduce The Issue**: Trade 8 Raiders seals and NQ Raiders Feet
Says obtained Raiders Feet +1 in log but never receive item.
Tried trading everything at once before this, didnt work. Also tried zoning and sorting inventory.

Obviously would like the +1 item so I can trade it along with the jewels i have.

**Comment by Loki79** [comment]
This trial works 100% correctly.  Was scripted correctly and functions fine when tested.  I assume you must had a full inventory, even though it didn't show full.  Although it shouldn't have said you received the item......  get with GM in game for your item please.

**Comment by Loki79** [comment]
whoever gives the item please close this out.

**Comment by Thilion** [comment]
Item was given to the player.
