### ISSUE TITLE
Custom entries for npc_list and mob_spawn_points need review.

### ISSUE THREAD

**Issue by R3P0FFXI** [LegionDark/Issues#1100]
**Date & Time**:  9/20/2016

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**: 

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: Laidly_Laurence

**Zone name**: Garlaige Citadel [S] 

**Coordinates (use `$where`)**: pos -260 -0.579 -20 164

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:
**_Edited by Teo**_ 
A Planar Rift is being spawned at `-260 -0.579 379` of Garlaige Citadel [S] instead of `-260 -0.579 -20` but the worst part of this is the custom entry should not even exist, because that NPC does exist and is set to be spawned in the stock DSP npc_list table, meaning no edit to the insert statement was needed.

**Comment by TeoTwawki** [comment]
As discussed last night: Wrong.

Have editted totle and to reflect real problem.

**Comment by TeoTwawki** [comment]
Bumped button by accident.

**Comment by R3P0FFXI** [comment]
Resolved in Nextupdate branch
