### ISSUE TITLE
Maat fights buggy

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1101]
**Date & Time**: 
Sep 21, 2016
12:39 PM (GMT)

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Girlieman

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
PLD70

**NPC or Monster or item Name**: 
Maat

**Zone name**: 
Fei Yin

**Coordinates (use `$where`)**: 
It's the maat fight, you can figure it out

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Fight maat.

This might only happen the first fight (shattering stars), after you win, "Another event was called while current event was running" is spammed in the log, and a cutscene plays over and over.

This doesn't break the fight, you still get flagged as winning, you just have to wait until time runs out or maybe restart your client.

Also reported by Peashy (as THF).

**Comment by tb1** [comment]
Had to restart client, didn't get unstuck when time ran out.

**Comment by tb1** [comment]
I use enternity, peashy doesn't so I don't think it's that.

**Comment by TeoTwawki** [comment]
People on other servers have been complaining of this bug for months, first time we've seen it reported on legion. Will look into soon.

**Comment by TeoTwawki** [comment]
Should be resolved next time we get DSP updates (right about when we are ready to update client) https://github.com/DarkstarProject/darkstar/pull/3555

**Comment by TeoTwawki** [comment]
updated, open new issue if problems with maat persis
