### ISSUE TITLE
Wrong In Game Models and no additional effects for Blurred Weapons

### ISSUE THREAD

**Issue by Nususu** [LegionDark/Issues#1102]
**Date & Time**: 9/21/16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: ~~60831_1 AL~~ yes

**Character Name**: Lurtz

**Nation**: Bastok

**Job(level)/Sub Job(level)**: WAR99/SAM49

**NPC or Monster or item Name**: Blurred Cleaver

**Zone name**: N/A

**Coordinates (use `$where`)**: N/A

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/20849/blurred-cleaver

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: Blurred Cleaver does not have the correct in-game model. Additionally, it seems the additional effect:haste does not proc. I've tested two other blurred items (Kujaku and Blurred Knife). Blurred knife has the correct model, Kujaku does not.

**Comment by TeoTwawki** [comment]
That particular type of additional effect doesn't exist in darkstar yet, but I'm working on that.

**Comment by TwIzTiD2469** [comment]
Also, for the hq its supposed to hit 2x and the webpage has it listed for 1x

**Comment by Nususu** [comment]
@TeoTwawki thanks for the quick response on that one.

**Comment by PikaFox** [comment]
Blurred Cleaver mID: 744

Kujaku mID: 746

Blurred Knife mID: 459

**Comment by R3P0FFXI** [comment]
DSP has correct MID Legion had incorrect info fix in Legion next time we update these will be correct.
