### ISSUE TITLE
Mochizuki kyahan +1 not have evasion +69

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1103]
**Date & Time**: 22-9-16

**FFXI Client Version (use `/ver`)**: 30160831-1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Aurel

**Nation**: sandy

**Job(level)/Sub Job(level)**: Nin/thf

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/27353/mochi-kyahan-1

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Hi ,feet not have evasion +69

**Comment by R3P0FFXI** [comment]
Item has 2 incorrect mods which need fixing

69% Evasion
Haste/Slow From Equipment +51

**Comment by Aurelcassy** [comment]
hi ,i have a doubt ,feet Drk af2 not have evasion feet Monk,Cor,war ,blm,rdm etc ,all af1 and af2 after update are very too   ,i reforge 60 pieces have all bugg,,,af3 work evasion  fine,,,just I put this to not report all af

**Comment by R3P0FFXI** [comment]
@Aurelcassy Verified with other items mods appear correct

**Comment by Aurelcassy** [comment]
![img_20160924_125056](https://cloud.githubusercontent.com/assets/13084662/18809575/b4417e6c-8255-11e6-8c57-9c3373d16545.png)
![img_20160924_125031](https://cloud.githubusercontent.com/assets/13084662/18809578/c1251b34-8255-11e6-9c47-207e29df4dd6.png)


only is evasion in all af1 and af2 or /checkparam is bad??

**Comment by Aurelcassy** [comment]
Please check head blu af1 119 ,have 44 evasion +AG24 =453 evsion  vs head af3 119  ,have 38 evasion + AG 18 =488

![img_20160924_125858](https://cloud.githubusercontent.com/assets/13084662/18809631/677ade82-8257-11e6-9533-b4a9ae1d5523.png)
![img_20160924_125830](https://cloud.githubusercontent.com/assets/13084662/18809636/7791ba7a-8257-11e6-85fe-652ce08e3a43.png)

**Comment by Aurelcassy** [comment]
feet Cor ,please do not get angry
![img_20160924_130902](https://cloud.githubusercontent.com/assets/13084662/18809667/65735adc-8258-11e6-9949-46ba6fbf6e96.png)
![img_20160924_130844](https://cloud.githubusercontent.com/assets/13084662/18809671/7769dc20-8258-11e6-845a-fdfdc874d2b8.png)
