### ISSUE TITLE
Cross Server Chat Being a Derp

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1104]
**Date & Time**: 9/22/16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Tarot

**Nation**: San

**Job(level)/Sub Job(level)**: 99thf/49dnc

**NPC or Monster or item Name**: 

**Zone name**: Dynamis San

**Coordinates (use `$where`)**: Zone

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
Go into dynamis

Everyone outside dyna is "changing areas or offline" when trying to /tell them, LS goes quiet.

**Comment by TeoTwawki** [comment]
@LegionDark/thebosses its specific to dynamis so far. its triggered by warping out. The exit code for the battlefield doesn't fire and it just hangs there but doesn't prevent new entry nor crash the map server..Possibly effects limbus as well (same map server).

**Comment by TeoTwawki** [comment]
I think this got fixed when the exit crash was. If it happens again, new issue.
