### ISSUE TITLE
request for crafting levels import

### ISSUE THREAD

**Issue by Ryhila** [LegionDark/Issues#1105]
**Date & Time**: 9/22/2016 4:32 pm CST

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Morphious

**Nation**: Bastok

**Job(level)/Sub Job(level)**: Thief 99 / dancer 49

**NPC or Monster or item Name**:  N/A (getting crafting level imported)

**Zone name**: N/A

**Coordinates (use `$where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: N/A
![img_20160816_225427](https://cloud.githubusercontent.com/assets/8400510/18767025/8f569854-80e2-11e6-9477-ecd8b7f9414d.png)

attempting to port over my crafting levels, please and thank you, if any questions please reach out to me asap ^^ thank you and have a great day

**Comment by Genesis-Legion** [comment]
Player's crafts have been transferred.
