### ISSUE TITLE
ASHEN VW QUEST: VW Op. #115: Li'Telor Variant

### ISSUE THREAD

**Issue by SquallerSnake** [LegionDark/Issues#1107]
**Date & Time**: 02:33 PM, 23/09/2016

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Squaller

**Nation**: Bastok

**Job(level)/Sub Job(level)**: PLD 99/WAR 49

**NPC or Monster or item Name**: Kieran

**Zone name**: Norg

**Coordinates (use `$where`)**: X:0 Y:0 Z:14 (167) 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: VW Op. #115: Li'Telor Variant
I followed the instructions of the quest "VW Op. #115: Li'Telor Variant" on FFXI wiki:

1)Travel to Norg and speak to Kieran (with KeyItem:Ashen Stratum Abyssite II) for a cutscene. -->OK
2)The quest "VW Op. #115: Li'Telor Variant" is flagged at this point. --> OK
3)Defeat Cath Palug in The Sanctuary of Zi'Tah (defeated many times). --> OK
4)Defeat Modron in The Boyahda Tree (defeated many times). --> OK
5)Mimic King in Ro'Maeve (defeated once). --> OK
6)Return to Norg and speak to Kieran to receive your KeyItem: Ashen Stratum Abyssite III. -->ERROR I got Ashen Stratum Abyssite III immediately after the death of Mimic King in Ro'Maeve.
7)If I speak to Kieran there is no cutscene and this message is displayed "system message: this menu doesn't work yet". The quest VW Op. #115: Li'Telor Variant is still active and the quest "Skyward Ho, Voidwatcher!" don't start.

I think i'm in these conditions "Voidwatch Chapters 3-5 are once again open.
*This will not fix dual boxing issues with Voidwatch where players are not getting the proper flags. 
We will attempt to deal with those issues in Massive Update part 3.

Question: I need to wait MUP3 to have my active/completed quest fixed or I need the intervention of a GM to fix it?

-- I have the same problem on my mules: Thranduil and Nanatuttatana --

**Comment by TeoTwawki** [comment]
> 6)Return to Norg and speak to Kieran to receive your KeyItem: Ashen Stratum Abyssite III. -->ERROR I got Ashen Stratum Abyssite III immediately after the death of Mimic King in Ro'Maeve.

This is expected to happen repeats..checking to see if wrong quest was checked..

In the future I intend to get rid of the entire deleting of keyitem thing, and track your progress differently. The initial implementation with Loki

**Comment by TeoTwawki** [comment]
@LegionDark/gm `@setplayervar Squaller ASHEN_STRATUM_II 7` and then have him see both Kieren and Gilgemesh.

**Comment by SquallerSnake** [comment]
--Update--

1) With active quest VW Op. #115: Li'Telor Variant and Ashen T3 KI i killed the 3 T3 mobs, once i have defeated the last one i got again Ashen1.
2) I killed again all the 6 T1 mobs without any CS and I got Ashen2 once I defeated the last one.
3) I killed again all the 3 T2 mobs and when I killed the last one this time Ashen abyssite remain to Ashen2.
4) I go to speak with Kieran and this time he give me the CS, Ashen3 and the quest VW Op. #115: Li'Telor Variant closed.
5) Now on completed quest I have also "Skyward Ho, Voidwatcher!" maybe because i have already killed the T3 mobs once?

I think that my bug is solved. Right?

**Comment by TeoTwawki** [comment]
Someone was supposed to help you way before this. I'm kinda ticked off now about it. See me in game in a few min for some extra stones.

@LegionDark/gm other players still need assistance in issues that were closed prematurely. I want them handled before the usual suspects begin making whole new issues for it.

**Comment by SquallerSnake** [comment]
Thanks, I'm in Europe so our times do not coincide. Maybe i will be online on the weekend or next week.

**Comment by R3P0FFXI** [comment]
@SquallerSnake I see you on but am at work. Can you please hop in IRC so we can hammer out a time to get this resolved for you.

**Comment by R3P0FFXI** [comment]
Fixed by Teo

**Comment by PikaFox** [comment]
Voidstones added to player

**Comment by TeoTwawki** [comment]
I've now taken care of the others as well. Finally caught them online.
