### ISSUE TITLE
Sprightly Soup for expert cooking test

### ISSUE THREAD

**Issue by Oderson** [LegionDark/Issues#1109]
**Date & Time**: 09/23/16

**FFXI Client Version (use `/ver`)**:  60831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**:  Nevion

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: thf99

**NPC or Monster or item Name**: Sprightly Soup

**Zone name**:  Windurst Waters

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/5930/sprightly-soup

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: no recipe is given in legion item tool, cant make item

**Comment by R3P0FFXI** [comment]
@Oderson Cooking has not been adjusted or mapped out yet, no ETA when this will happen
