### ISSUE TITLE
Thf cannot equip the dagger Izhiikoh

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#111]
**Date & Time**: 6/21/15
**Frequency**: always
**FFXI Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: Hume
**Main Job**: Thf
**Sub Job**: NA
**Area & Coordinates**: All
**Party or Solo**: NA
**NPC Name**: NA
**Monster Name**: NA
**Steps To Reproduce The Issue**: Dagger will not equip to main or sub.

http://www.ffxiah.com/item/20636/izhiikoh

**Comment by Loki79** [comment]
ill get this taken care of for tuesday.
