### ISSUE TITLE
Keratyrannos NM no pop

### ISSUE THREAD

**Issue by atts2002** [LegionDark/Issues#1110]
**Date & Time**: 
4:36pm 24 sept australia

**FFXI Client Version (use `/ver`)**: 
30160831_1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
60831_1

**Character Name**: 
doradosushi

**Nation**: 
san d oria

**Job(level)/Sub Job(level)**: 
nin99/war49

**NPC or Monster or item Name**: 
Keratyrannos monster

**Zone name**: 
abbyssea konschat

**Coordinates (use `$where`)**: 
x-136 y:47 z:418 (43)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
NM spawn by trading a Amored dragon to the ??? at those co-ords
first 2 times pop no problem since after that NM will not pop anymore

**Comment by atts2002** [comment]
server reset works fine now

**Comment by atts2002** [comment]
ok happened again

**Comment by TeoTwawki** [comment]
undefined prcedue because soemderp never put onEventFinish in the script.

Checking to see how many other scripts are effected, then I'll fix.

**Comment by TeoTwawki** [comment]
...It seems the server also thinks the mob is "roaming" rather than not popped. Even though I don't see it on widescan.

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
