### ISSUE TITLE
Self-Target Weaponskill 

### ISSUE THREAD

**Issue by Spardante** [LegionDark/Issues#1111]
**Date & Time**: 
9/24/16, 9:40AM EST

**FFXI Client Version (use `/ver`)**: 
30160831_1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
600831_1
AL

**Character Name**: 
Biggie

**Nation**: 
Sand D'Oria

**Job(level)/Sub Job(level)**: 
99BLU/49RDM

**NPC or Monster or item Name**: 
Self-target Weaponskills (i.e. Starlight) will consistently fail to activate (although it won't fail every time).  Same problem on different Mobs.

**Zone name**: 
Arrapago Reef

**Coordinates (use `$where`)**: 
X:-62  Y:-15  Z:59 (190)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
While in Arrapago Reef, the Club Weaponskill Starlight would not work most of the time.  This is a self-targetting weaponskill, and upon activation, it would say "You cannot see Biggie", my character.  Sometimes it would work, and when it did, I could do it multiple times in a row.  But when it would show the error, I could not find a way to get it to activate.  I tried moving around, standing on flat surfaces, and still couldn't get Starlight to activate.  Moonlight also failed to activate, which I believe means the error is happening with all Self-targetting weaponskills. See screenshot for error message.

![self-target weaponskill failure](https://cloud.githubusercontent.com/assets/20506368/18808903/df9285d4-823c-11e6-9d4b-e730cc37dde4.jpg)

**Comment by TeoTwawki** [comment]
I made a report to DSP after making sure their most recent revision still does it.
