### ISSUE TITLE
Cant move items between Items and House, also after transfer do not have KI maps or portal charm.

### ISSUE THREAD

**Issue by Taruecho** [LegionDark/Issues#1112]
**Date & Time**: 09/25/2016  11:18am CST

**FFXI Client Version (use `/ver`)**: 30160831 1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: ~~60831_1~~ yes

**Character Name**: Killerboy

**Nation**: Windurst

**Job(level)/Sub Job(level)**:BLM55 

**NPC or Monster or item Name**: All, ex antivenom earring

**Zone name**: Windurst Woods

**Coordinates (use `$where`)**:  x:-98  Y:-4  z:38 (107)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes, other charaters work fine

**Steps To Reproduce / any other info**: Try to move items from House to inventory and can only move up to 4. Once I move inventory back to house. Seems like my items max is 4. This is happening in every house box it seems. Mog Safe, Locker, Satche, case and sack. Ive tried zoning, changing jobs, logging out and back in.

**Comment by Taruecho** [comment]
I not sure if its normal but after transfer also missing Portal Charm and linkshell that new charaters start with.

**Comment by TeoTwawki** [comment]
> I not sure if its normal but after transfer also missing Portal Charm and linkshell that new charaters start with.

It was only being given on char creation and never updated it after imports became a thing. I just changed it to now be given by the door itself so you imported folks can have one too 😄

**Comment by TeoTwawki** [comment]
I checked and your storage container size isn't borked, so I suspect you have an "invisible" item throwing a wrench into your inventory. Quite probably *not* the kind caused by the sort bug, but rather by items with only part of their database entries implemented somehow slipped in with your import 😦

**Comment by Taruecho** [comment]
Should I recreate xml or is there something happening on your side?  

Thanks for your quick response.

**Comment by TeoTwawki** [comment]
I'm not sure what we should be doing yet, have to look at whats in your item lists. May need to get with you in game but my rl is kind of hectic atm, just has a pipe break and basement part flooded.

Items after the 4th show they just refuse to be moved right?

**Comment by Taruecho** [comment]
I can only move 4 items into my inventory. Unable to move anything else after the forth one.  So my inventory shows 4/80 once I cant move anything else. But then 0/80 when empty.

**Comment by TeoTwawki** [comment]
after moving 4 into inventory, whats the total of items?

**Comment by TeoTwawki** [comment]
I'm seeing a a related sql error in server log, indicating my bad item hypothesis is likely right. will meet you in game as soon as I can

**Comment by TeoTwawki** [comment]
Ding dinging! we have a winner!
http://www.ffxiah.com/item/6416/behemoth-meat
Effectively doesn't exist, bugs any character that has any.
Paging @R3P0FFXI and @LegionDark/gm

**Comment by Taruecho** [comment]
Mog Sac still bugged

**Comment by TeoTwawki** [comment]
k will look in a min

**Comment by Taruecho** [comment]
Perfect

**Comment by TeoTwawki** [comment]
handled.
