### ISSUE TITLE
Crafting inport

### ISSUE THREAD

**Issue by Taruecho** [LegionDark/Issues#1114]
**Date & Time**:  09/25/16 3:45pm  cst 

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  60831_1

**Character Name**: Killerboy

**Nation**: Windurst

**Job(level)/Sub Job(level)**: BLM55

**NPC or Monster or item Name**: N/A

**Zone name**: South Sandy 

**Coordinates (use `$where`)**:138  -2  117 

**ffxiah.com link (for items issues only)**:  NA

**Multi-boxing? (multiple clients on same connection)**:  Yes.

**Steps To Reproduce / any other info**: 

![killerboy](https://cloud.githubusercontent.com/assets/22431344/18818146/62ff878c-8337-11e6-9f63-0e1dca18b711.png)

**Comment by TeoTwawki** [comment]
@LegionDark/gm someone handle this, or close it if it already has been..

**Comment by Taruecho** [comment]
Crafting all 0 still >.<;  would be great to get imported to get started leveling ^^

**Comment by TeoTwawki** [comment]
@Taruecho my apologies that you've had to wait so long.

**Comment by Heepster03** [comment]
Crafts imported.
