### ISSUE TITLE
unable to retrieve items sent wrongly from delivery box

### ISSUE THREAD

**Issue by shiromaneki** [LegionDark/Issues#1117]
**Date & Time**: 
26/09/2016 & 1600hrs

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Shirokawa

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
Thf(70)/Dnc(35)

**NPC or Monster or item Name**: 

**Zone name**: 
Jeuno

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Keeps giving backlogged error when I try to retrieve items that are sent wrongly

**Comment by TeoTwawki** [comment]
Not enough info here - what do you eman by "sent wrongly" and aslo clarify "sent from delivery". There is a send box at the NPCs and and a delivery box in your mog - 2 separate things.

**Comment by R3P0FFXI** [comment]
Lack of player response after 15 days
