### ISSUE TITLE
Client constantely crashes when loading into game after character select

### ISSUE THREAD

**Issue by MikaiTiaga** [LegionDark/Issues#1119]
**Date & Time**: 
started Sunday (9/25/2016) when i zoned in tokonshtaht it crashed and since keeps doing so 

**FFXI Client Version (use `/ver`)**: 
30160831_1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Mikaitaiga

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
Thf16

**NPC or Monster or item Name**: 
none

**Zone name**: 
Konshtat Highlands

**Coordinates (use `$where`)**: 
zoning into

**ffxiah.com link (for items issues only)**: 
no

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
n/a

**Comment by R3P0FFXI** [comment]
@MikaiTiaga Use the website to reset your character

**Comment by R3P0FFXI** [comment]
@MikaiTiaga Please reply or I will be closing this ticket

**Comment by R3P0FFXI** [comment]
@MikaiTiaga closing due to no reply

**Comment by MikaiTiaga** [comment]
it wqasnt fixed

**Comment by TeoTwawki** [comment]
Policy is after 3 days if we notice a player has not replied we close. Tickets can be reopened or new ones can be made but we have to many get abandoned to not close them after awhile.
