### ISSUE TITLE
Unable to receive Ark Pentasphere

### ISSUE THREAD

**Issue by Skett** [LegionDark/Issues#112]
**Date & Time**: 22/06/2015 14:00GMT ? Unsure, its was Full moon 90-100% though.
**Frequency**: N/A
**FFXI Client Version**: 30150508_5
**Character Name**: Skett/Chrystina/Pray
**Race**: Elvaan/Hume/Taru
**Main Job**: 99THF / 99BLM / 99WHM
**Sub Job**: 49NIN / 49RDM / 49RDM
**Area & Coordinates**: X:0 Y:-29 Z:64 (204)
**Party or Solo**: Solo
**NPC Name**: Qu'Hau Spring
**Monster Name**: N/A
**Steps To Reproduce The Issue**: Visit Spring in full moon between 00:00 and 3:00 and trade illuminink and parchment but doesnt give ark pentasphere.
The pool didnt fill with water while i was waiting and I never noticed any weather effects, tried a few times.

**Comment by R3P0FFXI** [comment]
Please verify your Client version Skett, 30150508_8 you have _5 is this a typo or correct? If correct you may want to update the client again.

**Comment by Skett** [comment]
Will update client first and try again.

Date: Mon, 22 Jun 2015 09:25:10 -0700

**Comment by Squall-Bibi** [comment]
humm just curious i have the same version 30150508_5 what the 8 ?

**Comment by Skett** [comment]
Updated to _8 and can confirm that spring still doesnt fill for us.

**Comment by Skett** [comment]
Any update on this guys? looks like will be an additem job

**Comment by Squall-Bibi** [comment]
yeah i need divine might too :)

**Comment by Baucant** [comment]
http://ffxiclopedia.wikia.com/wiki/Ark_Pentasphere
I too have been trying to get this. I have been during full moon, between 0:00 -3:00 but the weather condistions have always been cloudy therefore the fountain will not fill. I think I just have bad luck.

**Comment by R3P0FFXI** [comment]
Currently at 83% moon will check when full

**Comment by Skett** [comment]
SS - http://i.imgur.com/kQ8oDA4.jpg

**Comment by TeoTwawki** [comment]
The full moon check got removed from the script when this got merged https://github.com/DarkstarProject/darkstar/pull/1489/files#diff-02c5347ab67e8827994aae2dbcbf4f05L20 so its just checking for clear weather and game time between 00:00 and 02:00 now. Note that fog or clouds means its not "clear" weather.

**Comment by TeoTwawki** [comment]
p.s.
If it fails during clear weather... https://github.com/DarkstarProject/darkstar/issues/new <- tell them

**Comment by R3P0FFXI** [comment]
Please check this as we have now updated

**Comment by Squall-Bibi** [comment]
for this test, need to see clear weather but i never see it in a couple oh days.

**Comment by TeoTwawki** [comment]
I just made it so cloudy and foggy weather will always get removed when making the trade during the correct hours.

**Comment by Squall-Bibi** [comment]
i dont know if restart server is ok but i tested now 0:10 in game time and no work. is raining time and thunder, no see the star and moon too :)

**Comment by Squall-Bibi** [comment]
now its work omg :)

**Comment by Skett** [comment]
Now down to teo

Sent from my HTC

----- Reply message -----

**Comment by TeoTwawki** [comment]
>>  dont know if restart server is ok but i tested now 0:10 in game time and trade no work. its raining time and thunder, no see the stars and moon :)

> now its work omg :) 

Like I said, needed to be clear weather. :smiley:
