### ISSUE TITLE
3200+ shield skill

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1120]
**Date & Time**: 9/28/16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Nyaarun

**Nation**: Win

**Job(level)/Sub Job(level)**: 44 blu/22 dnc

**NPC or Monster or item Name**: 

**Zone name**: Crawler's Nest

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/17702/shotel-1
http://www.ffxiah.com/item/17701/shotel

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 

0 shield skill leveled on this char. Equip shotel. - shield skill with 0 skill grants an insane amount of skill.

**Comment by PikaFox** [comment]
![nyaarun_2016 09 28_181847](https://cloud.githubusercontent.com/assets/12601727/18934572/69d883c4-85a8-11e6-9a04-89f7533b866b.png)

**Comment by TeoTwawki** [comment]
I assigned myself but haven't got to looking where it is in dsp's core yet, but want to let you know: easy fix, and lol not clamping  when applying negative values!

**Comment by PikaFox** [comment]
If only that was my shield skill on tarot. :c

**Comment by TeoTwawki** [comment]
If its any consolation, you can't actually make use of it for anything serious thanks to how the skill system internals work and the conditions involved.

**Comment by TeoTwawki** [comment]
Should be fixed now.
