### ISSUE TITLE
Rahu will not pop in Abyssea Attohwa for Smok KI

### ISSUE THREAD

**Issue by Nafff** [LegionDark/Issues#1121]
**Date & Time**: 9/29/2016 12:29AM PST

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Naf

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 99NIN/49WAR

**NPC or Monster or item Name**: Rahu

**Zone name**: Abyssea Attohwa

**Coordinates (use `$where`)**: X:-542 Y:-12 Z:-74 (55)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Went to pop Rahu so that I could pop Smok and his ??? did not react to the pop item. I tried all other possible potential pop spots in the nearby area. I looked up his monster information on the Legiondark.com tool and found that he did not currently exist on the server. I am trying to get the KI Hollow Dragon Eye so that I can pop Smok to make my Empyrean Weapon.

**Comment by Nafff** [comment]
Another NM listed for the same area that also drops the KI is named Svarbhanu. Same POS and ??? listed on ffxiwikia : http://ffxiclopedia.wikia.com/wiki/Svarbhanu

When looking his information up on Legiontool he is listed but in Empyreal Paradox and inaccessible.

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
