### ISSUE TITLE
LS Chat Sometimes Appears Twice

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1122]
**Date & Time**: 9/29/16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Nyaarun

**Nation**: Win

**Job(level)/Sub Job(level)**: 13rng/6dnc

**NPC or Monster or item Name**: 

**Zone name**: any

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 

Not sure what causes it. Sometimes LS chat appears twice. It doesnt show you sending messages twice, just everyone else has 2 messages. It doesnt seem everyone sees it happening either.

**Comment by PikaFox** [comment]
![nyaarun_2016 09 29_164521](https://cloud.githubusercontent.com/assets/12601727/18971829/88f004fa-8664-11e6-91b2-ba75792a2c4b.png)

**Comment by TeoTwawki** [comment]
see this before, relogging usually fixes.

**Comment by TeoTwawki** [comment]
I think the bug in the dyna server and the twice daily lobby reboot can both trigger it.

**Comment by PikaFox** [comment]
When i logged back in, it seems my LS2 had somehow set itself to LS1 twice.
![nyaarun_2016 09 29_165117](https://cloud.githubusercontent.com/assets/12601727/18971956/27ad4aa8-8665-11e6-9fe0-d56e5cdfc7a8.png)

I reset them after, which is indicated by the chat, but thought it might be relevant.

**Comment by TeoTwawki** [comment]
yeah, think you found an additional dsp bug with ls2 there. The other day someone had it happening while they owned only one physical ls  in inventory, right after lobby restarted.

**Comment by PikaFox** [comment]
I think its the same bug. It happened again, and i had my LS2 as LS1 and my LS1 wasnt equipped. LS2 chat appeared twice, resetting my LS1 to LS1 fixed it.

**Comment by TeoTwawki** [comment]
If we ever figure out how to consistently make it happen on purpose, we can see about getting it fixed in DSP. Meanwhile no point in leaving this open forever with nobody I am aware of actively trying to do anything with it.
