### ISSUE TITLE
cataclysm skill unavailable

### ISSUE THREAD

**Issue by warlord1352** [LegionDark/Issues#1124]
**Date & Time**: 9/29/16, 6:47pm pst

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**: Cureslave

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99whm/49rdm

**NPC or Monster or item Name**: n/a

**Zone name**: korroloka tunnel

**Coordinates (use `$where`)**: -338.764, -5.5, 81.661

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  yes

**Steps To Reproduce / any other info**: logged/relogged, tried to unequip/reequip weapon

**Comment by R3P0FFXI** [comment]
@warlord1352 Which weapon was equipped?

**Comment by warlord1352** [comment]
Chatoyant staff....but I apologize now that i think about it, I'm sure this is the quested WS.

**Comment by TeoTwawki** [comment]
Its among the current known issues that certain was are missing. The next update fixes it.

**Comment by warlord1352** [comment]
Oh ok, Thanks.

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
