### ISSUE TITLE
Dropped rems

### ISSUE THREAD

**Issue by alannor** [LegionDark/Issues#1125]
**Date & Time**: 
Oct 1st, 22.44

**FFXI Client Version (use `/ver`)**: 
Current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Kathy

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
MNK/DNC

**NPC or Monster or item Name**: 
Rems tale 1

**Zone name**: 
Lower Delkft

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
3 Rems 1 dropped. I obtained the first 2 correctly but after casting lot on the third, instead of going to my inventory, it said I don't meet the requirements to obtain this item and was lost...

I had 69/80 inventory space, and its not a Rare item...

I have alreadt spoken to God (GM) about this and I know the official policy that dropped items are not replaced, but hope you can also understand the frustration. 

Attached screenshots
https://postimg.org/image/5nnd7snuj/
https://postimg.org/image/457d3r3lx/27e5bef9/

**Comment by TeoTwawki** [comment]
If ***any*** member of the alliance fails to pass or lot, then instead of giving the item to the highest lot as expected, it can fall to the ground like this. Its a Darkstar bug which Legion can't do anything about. Need ppl to complain about it to Darkstar if they want 2+ yr old DSP bugs caused by bad implementation to be fixed 😢

**Comment by TeoTwawki** [comment]
There is a similar bug where the item doesn't even reach the loot pool to be lotted on - we don't even *KNOW* what triggers that one.
