### ISSUE TITLE
Client constantely crashes when loading into game after character select #1119 was never fixed an admin tried everything and couldnt fix it reinstalled still happening

### ISSUE THREAD

**Issue by MikaiTiaga** [LegionDark/Issues#1126]
Date & Time: 
started Sunday (9/25/2016) when i zoned in tokonshtaht it crashed and since keeps doing so

FFXI Client Version (use /ver): 
30160831_1
Server's Expected Client Version matches, yes/no? (use $ecv): 
yes

Character Name: 
Mikaitaiga

Nation: 
Windurst

Job(level)/Sub Job(level): 
Thf16

NPC or Monster or item Name: 
none

Zone name: 
Konshtat Highlands

Coordinates (use $where): 
zoning into

ffxiah.com link (for items issues only): 
no

Multi-boxing? (multiple clients on same connection): 
no

Steps To Reproduce / any other info: 
n/a

**Comment by TeoTwawki** [comment]
The previous ticket was closed because you didn't respond for 3 days.

I just manually changed your password, logged in, logged out, and changed your password back. Nothing is wrong on the server, its your client.

**Comment by TeoTwawki** [comment]
![](https://s22.postimg.org/fkwd993u9/Mikaitaiga_2016_10_01_143132.png)

**Comment by TeoTwawki** [comment]
Reset your resolution settings in FFXI's native config. Make sure your setting in ashita/windower (whichever) are match. Check anything else that would crash your client on retail (such as desktop dimming when running things as admin).

**Comment by R3P0FFXI** [comment]
@MikaiTiaga As you can see by the pic above this is not a Legion issue but an issue with the client installed on your PC it is corrupt or improperly configured. I am closing this ticket as there is no reson for it to be open as there is nothing the staff can do to resolve this.
