### ISSUE TITLE
Emotes can cause client crashes

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1127]
**Date & Time**: 10/1/16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Nyaarun

**Nation**: Win

**Job(level)/Sub Job(level)**: NA

**NPC or Monster or item Name**: 

**Zone name**: Multiple (north san, boyhada tree etc)

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 

Using emotes (commonly /wave) can cause you or another player to crash.

**Comment by TeoTwawki** [comment]
spamming wave and not crashing. Need to discover what conditions are required to make it crash, or a report is useless

**Comment by PikaFox** [comment]
Im not entirely sure what the conditions are for it. I just know immortality was /poking people and when i /poked them back yesterday it caused me to crash.

**Comment by TeoTwawki** [comment]
Well if we get it figured out, ima be telling you to tell DSP anyway. Coz its their bug, whatever it is :/

Nothing we can do on our end.

**Comment by TeoTwawki** [comment]
But they won't give it much attention if we can't tell'em how to make it happen.
