### ISSUE TITLE
Lord of Onzozo doesn't cast any magic like he's supposed to.

### ISSUE THREAD

**Issue by TwIzTiD2469** [LegionDark/Issues#1128]
**Date & Time**: 10/02/16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Boombastic

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: THF99/DNC49

**NPC or Monster or item Name**:Lord of Onzozo 

**Zone name**: Labyrinth of Onzozo

**Coordinates (use `$where`)**: X:-42 Y:15 Z:-60 (182)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: pop him and fight him. no casting at all from him. on retail he would cast waterga3 flood and blindga, here he's casting nothing at all.

**Comment by R3P0FFXI** [comment]
@TwIzTiD2469 This has been submitted to DSP and should be in next maint

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
