### ISSUE TITLE
Juggalo Character Transfer, Crafting levels restored

### ISSUE THREAD

**Issue by ffxijuggalo** [LegionDark/Issues#1129]
**Date & Time**: 10/2/2016 4:43 PM CST

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Juggalo

**Nation**: Windurst

**Job(level)/Sub Job(level)**: 99THF

**NPC or Monster or item Name**: none

**Zone name**: Windurst Waters

**Coordinates (use `$where`)**: X:-40 Y:-5 Z:80 (64)

**ffxiah.com link (for items issues only)**: none

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Character Transfer, Crafting levels restored

![img_20160930_065737](https://cloud.githubusercontent.com/assets/22580624/19023958/1903cb8c-88c0-11e6-935b-d6343fc581b9.png)

**Comment by Genesis-Legion** [comment]
Crafts transferred
