### ISSUE TITLE
Aegis armor line mods are off

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#113]
**Date & Time**: 6/22/15
**Frequency**: Always
**FFXI Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: Hume
**Main Job**: Pld
**Sub Job**: NA
**Area & Coordinates**: All
**Party or Solo**: NA
**NPC Name**: NA
**Monster Name**: NA
**Steps To Reproduce The Issue**: Aegis 85 gives no def, and according to Thil gives no -mdt either. Also, supposedly most/all other aegis' are missing/have incorrect stats as well (notably the 75 having -64% mdt)

http://www.ffxiah.com/item/15070/aegis 75

http://www.ffxiah.com/item/16196/aegis 85

http://www.ffxiah.com/item/16198/aegis 95

http://www.ffxiah.com/item/16200/aegis 99

**Comment by R3P0FFXI** [comment]
Tarot I am not seeing anything in the database anymore for Aegis either, let me verify something with Loki this morning and if I am correct I can get this in at maint for you guys but it seems to be affecting 75/85/95/99-1 Aegis

**Comment by R3P0FFXI** [comment]
This issue is resolved, I have added the correct mods to the items fixed all Aegis 85 to 99-4

**Comment by TeoTwawki** [comment]
note: the 65% is a display issue, dsp calculates mdt as fractions of 256, so thats 64/256 mistakenly displayed as a percntage base don 64/100 when it should be base don 64/256. I'll let atom0s know.
