### ISSUE TITLE
Marksmanship WS Last Stand not available on THF

### ISSUE THREAD

**Issue by TwIzTiD2469** [LegionDark/Issues#1130]
**Date & Time**: 10/02/16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Boombastic

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: 99THF/49DNC

**NPC or Monster or item Name**: N/A

**Zone name**: Any

**Coordinates (use `$where`)**: Any

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:   https://www.bg-wiki.com/bg/Last_Stand

**Comment by TwIzTiD2469** [comment]
Still not available even after most recent patch.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/3419
Will be in next time legion updates.

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint

**Comment by TwIzTiD2469** [comment]
Still not available.
