### ISSUE TITLE
NM wont pop out when i trade pop item .

### ISSUE THREAD

**Issue by arkooqymoya** [LegionDark/Issues#1131]
**Date & Time**:2016/10/3 

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**:  arkoo

**Nation**: bastok

**Job(level)/Sub Job(level)**: 99thf/49dnc

**NPC or Monster or item Name**:  Grandgousier

**Zone name**:  Abyssea - La Theine

**Coordinates (use `$where`)**:  X:-399 Y:0 Z:-319 (74)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**:  it was normal before i trade the pop item too fast after its death last time.  now its not respone by my trading pop item.

**Comment by TeoTwawki** [comment]
bug fix on its way soon as legion has a maintenance

**Comment by alannor** [comment]
Related, so wont raise new ticket

Unable to pop Quasimodo in Abs Vunkerl either

**Comment by TeoTwawki** [comment]
With the exception of some event IDs being wrong possibly interfering (mainly KI pops) these should be working after yesterdays update. the rest is being worked on.
