### ISSUE TITLE
TP Return for AoE WSes

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1132]
**Date & Time**: 
Oct 3, 2016
5:16 AM MST

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 
Girlieman

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
PLD/DNC

**NPC or Monster or item Name**: 

**Zone name**: 
The Booby Tree

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
AoE Weapon Skill TP return is excessive with many mobs.

Using circle blade with ~5-6 mobs I get >1000 TP return, allowing me to spam WSes very fast.

Dual-Wielding joytoy & burtgang (both multi-hit weapons).

Please say this is intended because I'm having a blast clearing rooms this way.

**Comment by R3P0FFXI** [comment]
@tb1 this is probably not intended @TeoTwawki would have to verify the formula most likely this is a DSP issue

**Comment by R3P0FFXI** [comment]
@tb1 This has been addressed by Darkstar and will be in the next maintenance.

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
