### ISSUE TITLE
odin bugged

### ISSUE THREAD

**Issue by atts2002** [LegionDark/Issues#1134]
**Date & Time**: 
9:51am 4 oct 2016

**FFXI Client Version (use `/ver`)**: 
30160831_1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
608131_1

**Character Name**: 
doradosushi

**Nation**: 
san doria

**Job(level)/Sub Job(level)**: 
nin/war 99

**NPC or Monster or item Name**: 
odin

**Zone name**: 
hazhalm testing ground

**Coordinates (use `$where`)**: 
X378 Y-215 Z41 (59)

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
GM God says NM is bugged and to file report
apparentl;y not using TP correctly or soemthing
i will leave it in your hands

**Comment by R3P0FFXI** [comment]
Casts Sleepga II, Breakga, Blindga, Bindga, Blizzard IV, Blizzaga III, Blizzaga IV, Slowga, Paralyga, and Dread Spikes (can be dispelled with Finale).
Uses the following TP moves, all of which have a range of 20' or larger:
Gagnrath: Front-AoE damage and Terror
Valfodr: AoE damage and Curse + Silence
Ofnir: AoE magic damage
Yggr: Gives Odin the ability to Intimidate players
Geirrothr: AoE physical damage that acts as "10,000 Needles", dividing 10,000 points of damage among all players in range. Additional effect: bind. Used 3 times, once when Odin reaches 74%, 49%, and 24% HP. Odin precedes this attack with a message in the chat log.
A good strategy is to ensure that every non-weakened member and any pets are near Odin at this time to help spread and reduce the damage. Alternatively, the damage can be absorbed using Migawari and similar abilities.
Sanngetall: AoE full dispel that removes almost all buffs from players in range. Used 8 times, once when Odin reaches 89%, 79%, 69%, 59%, 49%, 39%, 29%, and 19% HP. Odin precedes this attack with a message in the chat log.
Reraise and Embrava will not be dispelled by Sanngetall.
At 49%, Geirrothr will be used first, followed by Sanngetall. At 9%, this ability is replaced by Zantetsuken.
Zantetsuken: An Astral Flow-like ability. Used once when Odin reaches 9% HP. This move deals instant KO to all targets within a 30' radius around him. Odin precedes this attack with 3 messages in the chat log.

**Comment by TeoTwawki** [comment]
Delete it and start over. No seriously, this is effing stupid and I'm not doing it.

**Comment by TeoTwawki** [comment]
The most *basic* of script logic is simply wrong in that mobs script.

**Comment by TeoTwawki** [comment]
Dear players: don't read into this and spread rumors in game, Odin isn't being removed. I was angrily telling R3 he can rewrite it.

**Comment by TeoTwawki** [comment]
@R3P0FFXI no, the changes I did to it are already in, its now *less* fundamentally retarded than it *was*

**Comment by TeoTwawki** [comment]
forgot to close
