### ISSUE TITLE
Kapor Log not obtainable from logging.

### ISSUE THREAD

**Issue by ghost** [LegionDark/Issues#1135]
**Date & Time**: 
10/3/2016

**FFXI Client Version (use `/ver`)**: 
30160831_1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
 yes

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99Thf/49Dnc

**NPC or Monster or item Name**: 
Kapor Log

**Zone name**: 
North Sandy

**Coordinates (use `$where`)**: 
X:-159 Y:4 Z:264 (161)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/732/kapor-log

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Unobtainable from logging.

**Comment by Jessland86** [comment]
Fixed in previous maint, but never closed.
