### ISSUE TITLE
Kapor Lumber recipe not implemented.

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1136]
**Date & Time**: 
10/3/2016

**FFXI Client Version (use `/ver`)**: 
30160831_1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
 yes

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99Thf/49Dnc

**NPC or Monster or item Name**: 
Kapor Lumber

**Zone name**: 
North Sandy

**Coordinates (use `$where`)**: 
X:-159 Y:4 Z:264 (161)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/733/kapor-lumber

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Recipe not implemented.

**Comment by R3P0FFXI** [comment]
This has been submitted to DSP and should be corrected shortly

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
