### ISSUE TITLE
Cools Craft Transfer

### ISSUE THREAD

**Issue by ragecools** [LegionDark/Issues#1138]
![craft skills](https://cloud.githubusercontent.com/assets/22609036/19063579/fe2fe6e8-89b8-11e6-8c3b-c4ecae2463c4.jpg)

**Comment by ragecools** [comment]
They adjusted my Ragecools character.
Need the craft skills on the Cools character.
Sorry if it wasnt clear

**Comment by Genesis-Legion** [comment]
Fixed, crafts transferred.
