### ISSUE TITLE
Impossible to pop Celaeno for Bastok Voidwatch Win

### ISSUE THREAD

**Issue by Nafff** [LegionDark/Issues#1139]
**Date & Time**: 10/4/2016 7:03PM PST

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Naf

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 99NIN/49WAR

**NPC or Monster or item Name**: Celaeno

**Zone name**: Dangruf Wadi

**Coordinates (use `$where`)**: X: -253 Y: 4 Z: 505 191

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
There is no pop location for Celaeno at all, I have checked the entire zone and have no way of popping him to progress onto Jueno Voidwatch. I had the same issue prior to todays update but waited until after to see if there would be a fix.

**Comment by TeoTwawki** [comment]
Fix is incoming, posting issue topic on forum

**Comment by Nafff** [comment]
Thanks a ton for the quick response Teo! Appreciated :D

**Comment by TeoTwawki** [comment]
Its a ton of rifts missing. I manually popped this one.

**Comment by Nafff** [comment]
Yeah I had noticed that, this was the only one currently causing me issues. I didn't want to bother GMs asking for a manual pop.

**Comment by R3P0FFXI** [comment]
This has been submitted to DSP and should be corrected shortly

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
