### ISSUE TITLE
Race change

### ISSUE THREAD

**Issue by Strafeous** [LegionDark/Issues#114]
Usually I wouldn't post it here, but Noob told me to submit a bug report
My in game name is Strafeous and I was just wondering how to get a race change, I was reading on the fourms that you guys have done it for others and I wasn't sure what I had to do to get one.
I xferred my character over to Legion from retail which I've been an elvaan for 10 years and I wanted to be a hume after a year of playing elvaan. 
If you need to know, Hume male, face 2, hair A. 

Tyvm.

**Comment by R3P0FFXI** [comment]
We have never done a race change for anyone. We are in the process of looking into a way for players to have such an option but nothing has been implemented yet. Currently this is not a feature we are offering but it is something we plan to offer in the future.
