### ISSUE TITLE
VW Access

### ISSUE THREAD

**Issue by Vauser12** [LegionDark/Issues#1140]
**Date & Time**: 
7:12PM PST 10/04/16

**FFXI Client Version (use `/ver`)**: 
30160831_0
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
No currently 30160831_0

**Character Name**: Vauser, Jessalyn, Lyner

**Nation**:  All Bastok

**Job(level)/Sub Job(level)**: 
SAM99/WAR49
WHM99/SCH49
BLM99/RDM49

**NPC or Monster or item Name**: 
Voidwatch Purveyor

**Zone name**: 
South San d;Oria

**Coordinates (use `$where`)**: 
K-9

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**:

**Comment by TeoTwawki** [comment]
Wrong NPC if your trying to begin. But you didn't even describe what exactly the problem was.

You want "Voidwatch **Officer**" not purveyor, and bear in mind his text is likely busted right now.
