### ISSUE TITLE
Svarbhanu won't pop for the KI to spawn Smok

### ISSUE THREAD

**Issue by Nafff** [LegionDark/Issues#1141]
Date & Time: 10/4/16 7:21 PST

FFXI Client Version (use /ver): 30160831_1

Server's Expected Client Version matches, yes/no? (use $ecv): Yes

Character Name: Naf

Nation: Sandoria

Job(level)/Sub Job(level): 99NIN/49WAR

NPC or Monster or item Name: Svarbhanu

Zone name: Abyssea Attohwa

Coordinates (use $where): X:-544 Y:-12 Z:-72 (134)

ffxiah.com link (for items issues only):

Multi-boxing? (multiple clients on same connection): No

Steps To Reproduce / any other info: Went to pop Svarbhanu so that I could pop Smok and his ??? did not react to the pop item. I tried all other possible potential pop spots in the nearby area. I looked up his monster information on the Legiondark.com tool and found that he is currently located in Empyreal Paradox. I am trying to get the KI Hollow Dragon Eye so that I can pop Smok to make my Empyrean Weapon.

**Comment by TeoTwawki** [comment]
Idiots over at DSP gave it same pool ID as Promathia, which explains why cop final battle is broken as well

**Comment by TeoTwawki** [comment]
fixing it over in their trunk..

**Comment by Nafff** [comment]
Ahh okay that makes sense! Once again thank you for the quick response time :D 

Looking forward to progressing on my Empyrean Gun when this is all fixed.

**Comment by Nafff** [comment]
So I checked this morning and saw that Svarbhanu was back to being located in Abyssea Attohwa. I just went and tried to pop him at his corresponding ??? using the Cracked Dragonscale and he did not pop. Just wanted to let you know! Thanks again for working on these issues so quickly!

**Comment by TeoTwawki** [comment]
I haven't posted here that it was fixed yet, so its not.

**Comment by Nafff** [comment]
Oh my mistake! I just assumed after checking his location.

**Comment by TeoTwawki** [comment]
The tool reads the database. It sees changes before they are in the server because the game server has to actually have things like restarts and being recompiled to see the changes.

**Comment by Nafff** [comment]
Makes total sense! Sorry for bothering you. I'll wait to see your comment here when it is all fixed. Thanks again :)

**Comment by TeoTwawki** [comment]
pretty much when this gets closed, it should be working. Unless r3 closes then its in tomorrows update because he likes making me drown in duplicate issues from confused users....

**Comment by R3P0FFXI** [comment]
Fixed in Maint
