### ISSUE TITLE
Amhuluk not targetable

### ISSUE THREAD

**Issue by Dalkiel81** [LegionDark/Issues#1142]
**Date & Time**: 

October 4, 2016 11PM GMT
**FFXI Client Version (use `/ver`)**: 
30160831_1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

60831_1 doesnt't match
**Character Name**: 
Deaomongun

**Nation**: 

Bastok
**Job(level)/Sub Job(level)**: 

99thf/49dnc
**NPC or Monster or item Name**: 
Amhuluk

**Zone name**: 
Abyssea Misareaux

**Coordinates (use `$where`)**: 
X:29 Y:-9 Z:-30 (137

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

yes
**Steps To Reproduce / any other info**: 
Popped, Amhuluk, was unable to target him.

**Comment by TeoTwawki** [comment]
@R3P0FFXI WHY THE F IS THIS BACK

**Comment by TeoTwawki** [comment]
Re-"fixed" with garbage code we shouldn't have be using.
