### ISSUE TITLE
Ashita Login Error

### ISSUE THREAD

**Issue by aimez** [LegionDark/Issues#1144]
**Date & Time**: 10/5/2016

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Godaime

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: 99 THF/DNC

**NPC or Monster or item Name**: 

**Zone name**: La Theine Plateau

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes, not at the time of error.

**Steps To Reproduce / any other info**:  After quick fix on Oct. 5th, I opened ashita and the new UI was there and went to sign in, like normal, and it prompted "Exception Occured! Opps! That's not supposed to happen!". With "Copy the below message for support:"
System.MissingMethodException: Method not found: 'Void System.Runtime.InteropServices.Marshal.StructureToPtr(Ashita.Model.AshitaInstallParams, IntPtr, Boolean)'.
   at Ashita.Classes.ManagedInjector.StructToBytes[T](T obj)
   at Ashita.Classes.AshitaInjector.<>c__DisplayClass1_0.<LaunchConfiguration>b__0()

**Comment by atom0s** [comment]
Can you jump back on Discord or IRC, I have an idea as to why this is happening for some users.

**Comment by aimez** [comment]
yes sir omw on IRC!

**Comment by atom0s** [comment]
This issue can be corrected by installing the .NET Framework 4.5.2:
https://www.microsoft.com/en-us/download/details.aspx?id=42642
