### ISSUE TITLE
Bard Maat fight

### ISSUE THREAD

**Issue by sucidaldeathtar** [LegionDark/Issues#1146]
**Date & Time**: 
10/6/2016 @ 16:11

**FFXI Client Version (use `/ver`)**: 
30160831_1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Sucidalbard

**Nation**: 
sandy

**Job(level)/Sub Job(level)**: 
70brd/35whm

**NPC or Monster or item Name**: 
Maat test fight

**Zone name**: 
Qu'Bia Arena

**Coordinates (use `$where`)**: 
Burning circle

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
I had capped sword evasion and parry skills plus sing and wind skills.  I used  protect ring, blind band and stoneskin torque.  I engaged maat and suddenly I was getting skillups for sword evasion and parry.  Also he ate through my blink and stoneskin in 1 attack round and then the next he hit me for over 120 damage with crits over 200+.  Needless to say I died.  I do have a screen shot of the battle report below.

Also when I was kicked out it spamed another even was called while current event was running till I was able to get full hp and $tele holla out
![img_20161006_162015](https://cloud.githubusercontent.com/assets/19639643/19169835/0931e14a-8be4-11e6-8728-391643edf1a9.png)

**Comment by Heepster03** [comment]
I got with him and he said that his skills weren't capped yet. They appeared to be so due to the skillup glitch that sometimes requires you to zone to fix it. That's why he was getting skillups.

**Comment by TeoTwawki** [comment]
If the event spam thing happens again, make a new issue for that
