### ISSUE TITLE
Chatoyant Quadav dropping Cheese Hoarder Gigaroon drops

### ISSUE THREAD

**Issue by Heepster03** [LegionDark/Issues#1151]
**Date & Time**: 10/8/16 @ 11:21am cst

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes 60831_1

**Character Name**: Heep

**Nation**: Bastok

**Job(level)/Sub Job(level)**: THF99/DNC37

**NPC or Monster or item Name**: Chatoyant Quadav

**Zone name**: Castle Zvahl Keep [S]

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Chatoyant Quadavs appear to have the same treasure pool as Cheese Hoarder Gigaroon from T1 ZNM.

**Comment by R3P0FFXI** [comment]
Pushed fix to DSP should be pulled down next Maint

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
