### ISSUE TITLE
Windy Mission 2-3 Stuck

### ISSUE THREAD

**Issue by Ziabatsu** [LegionDark/Issues#1152]
**Date & Time**: 
10/8/2016

**FFXI Client Version (use `/ver`)**: 
Current?

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Tes

**Character Name**: 
Flatliner

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
59/29

**NPC or Monster or item Name**: 
Patt-Pott in Metalworks won't accept Mithril Sand

**Zone name**: 
Metalworks

**Coordinates (use `$where`)**: 
I-7

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
I have followed this guide step by step. http://ffxiclopedia.wikia.com/wiki/The_Three_Kingdoms

**Comment by TeoTwawki** [comment]
> Multi-boxing? (multiple clients on same connection):

**Comment by Ziabatsu** [comment]
Version: 30160831_1

Multibox:
No. I only have 1 account.

**Comment by TeoTwawki** [comment]
Does anyone on the same internet connection also play?

**Comment by Ziabatsu** [comment]
Just me. Static IP address.

**Comment by TeoTwawki** [comment]
screenshot me you mission log real quick, and link it here (upload it anyplace you like except photobucket pls)

**Comment by Ziabatsu** [comment]
https://postimg.org/image/w5cniebdn/

https://postimg.org/image/e3tiklhcr/

https://postimg.org/image/6ccsm1d7f/

**Comment by TeoTwawki** [comment]
Yeah I only needed the "current mission" screen. 

You went to san'droia first or bastok first?

Your mission status in the database suggests you are already past this step and shouldn't even be doing anything with Mythril sand at all.

**Comment by TeoTwawki** [comment]
I'm guessing you did San d'Oria first and then went to Bastok second and followed wrong half of wiki while skipping as much in game dialog as possible (most player do, slow UI..)  There are 2 versions of the mission, depending which nation to travel to first.

If you travel to bastok first, you have to do mythril sand. If you travel to sandoria first, you have to assassinate a war chief. You don't have to do both.

**Comment by Ziabatsu** [comment]
Ah. Well, the only reason I had tried the second step is because I can't enter the Waughroon Shrine.

**Comment by Ziabatsu** [comment]
It works now, however. Didn't work for me last night when I tried it, so I just did the second half.

**Comment by TeoTwawki** [comment]
Well if it works now, good. Going to close this.

**Comment by TeoTwawki** [comment]
If you have any other concerns that need addressed, just pop in and make a new issue report, one of us will see it when we're free.
