### ISSUE TITLE
alectryon

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#1153]
**Date & Time**: 
10/08/2016 9:41

**FFXI Client Version (use `/ver`)**: 
30160831_1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
ritonami

**Nation**: 
windurst

**Job(level)/Sub Job(level)**: 
thf99/snc49

**NPC or Monster or item Name**: 
Alectryon

**Zone name**: 
tahrongi canyon (s)

**Coordinates (use `$where`)**: 
-58,4, 94 165

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
only requiring half of pop items to pop

**Comment by TeoTwawki** [comment]
> tahrongi canyon (s)

did you mean *Abyssea - Tahrongi* ?

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/3424

**Comment by ritonami** [comment]
opps yeah abyssea tahrongi

**Comment by TeoTwawki** [comment]
I figured it out pretty fast. Thanks for the report! Fix will be in soon.

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
