### ISSUE TITLE
Issues learning Blue Magic spell Rail Cannon

### ISSUE THREAD

**Issue by Enceer** [LegionDark/Issues#1154]
**Date & Time**: 10/10/2016 9:29 PM EST

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Encee

**Nation**: Sandoria 

**Job(level)/Sub Job(level)**: 99BLU/49RDM

**NPC or Monster or item Name**: Impervious Chariot/Sub-zero Gear

**Zone name**: Abyssea Uleguerand Range

**Coordinates (use `$where`)**: X:-232 Y:-177 Z:13 (233)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Having issues learning the Blue Mage spell Rail Cannon. It is not currently listed on the Blue Mage Tool on legion website but after some research both in server and on the github issues tracker I read the you could learn it off Impervious Chariot and in the last there was a fix allowing you to learn off of Sub-zero Gear. Over the last 2 days I have spent roughly 4 hours trying to learn the spell with the AF hands to increase chance to learn Blue Magic. I was wondering if this spell was still learnable from the Chariot and I'm just having bad luck? Thank you very much in advance and looking forward to your response.

**Comment by TeoTwawki** [comment]
Armed gears and Sub-Zero Gear both have it randomly given to eligible Blue Mages on death. We hope to eventually have it learn-able the old fashioned way, when we have time to fix the mob/mobskills properly.

You are just having bad luck. Really bad, since the rate is high.

**Comment by TeoTwawki** [comment]
Edit: the chariot doesn't have it.

**Comment by Enceer** [comment]
Okay thank you very much for your clarification. I was focusing mainly on the Chariot. I will try again with the gears and hope my luck improves!

**Comment by Enceer** [comment]
Hey Teo, quick question. I have been killing Sub-Zero Gears non stop since you responded to my bug report. It has been roughly 4 hours since then and I still have not gotten spell. Capped BLU magic and gloves on still. I in now way want to sound like I am complaining I am just curious if it is possible that this could be bugged in any way? Or just 7 hours of bad luck?

**Comment by TeoTwawki** [comment]
Bad luck. And non the blue learning boosts help this. Its a flat % chance to happen. Your luck has been pretty bad, the rate of these is very high.

**Comment by Enceer** [comment]
Ah that's a bummer but good to know, I'll keep at it! Hopefully my bad luck turns around. Thank you for the information again.

**Comment by TeoTwawki** [comment]
Good news, I did find a TON of other bugs, unrelated to your specific problem. So at least good came of this!

**Comment by Enceer** [comment]
Even better news I finally learned it just now!! A win win for both of us! Thanks a ton for being cooperative during my troubles and glad some good to come out of this for you too!

**Comment by TeoTwawki** [comment]
Congratulation. :smile:

**Comment by Enceer** [comment]
Thank you very much! Have a great night and thanks for all you do! Looking forward to the update/fixes coming tomorrow.
