### ISSUE TITLE
Voidwatch T4/5 have no drops

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1156]
**Date & Time**: 12-10-16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Aurel

**Nation**: sandy

**Job(level)/Sub Job(level)**: all

**NPC or Monster or item Name**: Amber Stratum Abyssite

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 
hi , the NM pop so after kill always is 0 drop ,i use KI Amber Stratum Abyssite

Having a Voidstone and this in your possession allow you to spawn:
Dimgruzub in Arrapago Reef
Brekekekex in Caedarva Mire
Yalungur in Mamook
Vanasarvik in Mount Zhayolm 

EXAMPLE
![captura](https://cloud.githubusercontent.com/assets/13084662/19312803/0ad0c278-9062-11e6-976a-7e86b2ac4d0c.PNG)

![captura](https://cloud.githubusercontent.com/assets/13084662/19312881/5df50c3e-9062-11e6-9a1c-0bbce59ed2b2.PNG)

**Comment by R3P0FFXI** [comment]
@Aurelcassy We are aware of further issues with Voidwatch mobs and will address this in time

**Comment by TeoTwawki** [comment]
@Aurelcassy I see what happened between him looking and you looking, sorry. It should be present where he was at now..

**Comment by TeoTwawki** [comment]
how the hell did I post to wrong issue

**Comment by R3P0FFXI** [comment]
@Aurelcassy this will be fixed today
