### ISSUE TITLE
WS Low dmg in abyss

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1157]
**Date & Time**: 
12-10-16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: aurel

**Nation**: sandy

**Job(level)/Sub Job(level)**: all

**NPC or Monster or item Name**: SAM-DRG-NIN-BST-MONK-RDM-BLU-COR

**Zone name**: all abyss

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: hi ,me have empy weapon for  SAM-DRG-NIN-BST-MONK-RDM-BLU-COR-DRK-so ws is very low only work Redemtion for drk and empy weapon for WAR  ,war and drk have dmg 4000 +- ,+double dmg 7000 to 9000 dmg ,war is more dmg ,,so SAM-DRG-NIN-BST-MONK-RDM-BLU-COR  WS dmg is 800 to 2000
,I have relic weapon119 an ws is Very Very low 500 to900  ,I have Mythic weapon 119 i never user  (drk) is very bad ,,,
Please
PLEASE
please can match the damage of weapons. I get bored always depend on WAR

**Comment by R3P0FFXI** [comment]
@Aurelcassy  Working as Intended
