### ISSUE TITLE
~ Planar Rifts missing ~ Pashhow M. 

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#1158]
**Date & Time**: 12/10/16, 18.00

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Thranduil

**Nation**: bastok

**Job(level)/Sub Job(level)**: blu99/rdm49

**NPC or Monster or item Name**: Murk-Veined Baneberry

**Zone name**: Pashhow Marshlands

**Coordinates (use `$where`)**: X: 551, Y: 24.5, Z: 49

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 

There are no planar rifts in the zone. 
Thank you.

**Comment by R3P0FFXI** [comment]
@simthra Issue resolved by @TeoTwawki during a server reboot
