### ISSUE TITLE
??? In Abyssea-Miseraux Doesn't Take Pop Item

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1159]
**Date & Time**: 10/13/16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Tarot

**Nation**: San

**Job(level)/Sub Job(level)**: 99 Thf/49 Dnc

**NPC or Monster or item Name**: ???

**Zone name**: Abyssea - Miseraux

**Coordinates (use `$where`)**: 207, -23, 319

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/3087/apkallu-down

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 

Trade item to ???, does not pop NM. ??? does state that the correct item needs to be traded to it, but does not accept the trade.

**Comment by TeoTwawki** [comment]
Happening because the NM is already up (seriously). Someone wiped to it and he wandered off. We don't have the modifiers set to make these depop yet.
