### ISSUE TITLE
Bard limit break 4 item

### ISSUE THREAD

**Issue by Megamoo** [LegionDark/Issues#116]
**Date & Time**: 6/23/2014
**Frequency**: 1/1
**FFXI Client Version**: 30150508_08
**Character Name**: Megastrafe
**Race**: Mithra
**Main Job**: Bard
**Sub Job**: White Mage
**Area & Coordinates**: Ru'Lude Gardens
**Party or Solo**: Solo
**NPC Name**: Maat
**Monster Name**: N/A
**Steps To Reproduce The Issue**: I finished limit break 4 on bard and received an ammo slot item

**Comment by TeoTwawki** [comment]
Were you on bard main job at the time you received the item? Maat goes by the job you are on at the time you interact with him, and will swap the for current job item if you trade it back (fail-safe in case a player was on wrong job, lets you switch the item and or augments without having to redo it all).

**Comment by Megamoo** [comment]
Yes, I was on bard. I tried trading it to Maat and he gave me the same item back. Picture of the item that I received both times. http://i.imgur.com/j7ADeGs.png http://i.imgur.com/Gn53soC.png

**Comment by TeoTwawki** [comment]
Found and fixed issue, something got removed causing it not translate the job abbreviation back into numbers. This effected rng and cor as well.
