### ISSUE TITLE
Rudra's Storm Sometimes Deals 0 Damage

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1161]
**Date & Time**: 10/13/16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Tarot

**Nation**: San

**Job(level)/Sub Job(level)**: 99 Thf 49 Dnc

**NPC or Monster or item Name**: NA

**Zone name**: NA

**Coordinates (use `$where`)**: NA

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
Use Rudra's Storm. Will sometimes deal 0 damage for no reason whatsoever. Started this update.

**Comment by Whoaitsz** [comment]
same here. i was learning how to open ticket when i saw this. as THF 73/36 fighting onions and rarabs 
WS do 0 damage. it started after maintenance. so far i notice no pattern. sometimes they all work, sometimes 3-4 in a row do zero damage.

i'm blister. city is Windurst. WS are dancing edge and evisceration.

**Comment by TeoTwawki** [comment]
This was likely at the moments I was making live adjustment to get rid of a message in the servers console log, and typo'd I fixed reloaded the file but during that 2 minute window every ws was broken. This happened several times at different points in the last few days and I had hoped I was quick enough that nobody noticed. Guess not.

**Comment by TeoTwawki** [comment]
If it happens again, open me a new issue guys.
