### ISSUE TITLE
~ Missing Planar Rifts ~ Meri.Mount. / S

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#1162]
Date & Time: 13/10/16, 22.15

FFXI Client Version (use /ver): 30160831_1

Server's Expected Client Version matches, yes/no? (use $ecv): yes

Character Name: Thranduil

Nation: bastok

Job(level)/Sub Job(level): blu99/rdm49

NPC or Monster or item Name: Lord Asag

Zone name: Meriphataud Mountains

Coordinates (use $where): X: -282, Y: 16, Z: 602

ffxiah.com link (for items issues only):

Multi-boxing? (multiple clients on same connection): yes

Steps To Reproduce / any other info:
Planar rifts are missing in this zone (also Meriphataud S).

**Comment by TeoTwawki** [comment]
Hotfixed live, will be permanent when legion gets the update I just tossed to DSP https://github.com/DarkstarProject/darkstar/pull/3451
