### ISSUE TITLE
Customized NMs that should depop after claim loss need MOBMOD_IDLE_DESPAWN to be set

### ISSUE THREAD

**Issue by TeoTwawki** [LegionDark/Issues#1163]
**Date & Time**: 
N/A

**FFXI Client Version (use `/ver`)**: 
N/A

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
N/A

**Character Name**: 
N/A

**Nation**: 
N/A

**Job(level)/Sub Job(level)**: 
N/A

**NPC or Monster or item Name**: 
N/A

**Zone name**: 
N/A

**Coordinates (use `$where`)**: 
N/A

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
N/A

**Steps To Reproduce / any other info**: 
See #1159
Also, it seems this modifier does not work if set by script. Needs to be in the SQL.

**Comment by R3P0FFXI** [comment]
@TeoTwawki these were all added to SQL a few maint ago
