### ISSUE TITLE
I Can Hear A Rainbow

### ISSUE THREAD

**Issue by warlord1352** [LegionDark/Issues#1164]
**Date & Time**: 5:21 pm pst

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Oscar, Erinyes, Cureslave

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99thf, 99war, 99whm

**NPC or Monster or item Name**: Carbuncle's Ruby?

**Zone name**: Any zone with needed weather

**Coordinates (use `$where`)**: 34.799; .74; 175.104

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Tried several times to zone into locations with weathers I need. I have been in all locations to successfully get the cutscene but have maybe only gotten 2 or so. Is there any way I can skip ahead so I can just get and unlock my smn job? I've been wanting and waiting to get this job for a long time. Like I said constantly going to different locations with weathers and "gotten" them all several time but since no CSs no continuing foward. Thanks in advance guys!

**Comment by TeoTwawki** [comment]
Will be with you in game momentarily.

**Comment by TeoTwawki** [comment]
I think a lot of people with this issue are entering zone son chocobo or are entering zones that don't count. Has to be old zones, and chocobo breaks the cs event (or DSP bug). I just checked you in game and you are missing several weathers.

**Comment by TeoTwawki** [comment]
Seems to be from the item check failing when the ruby isn't in primary inventory, and from multi boxing glitching up vars
