### ISSUE TITLE
Voltsurge Torque Missing stats

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1165]
**Date & Time**: 
13-10-16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Aurel

**Nation**: sandy

**Job(level)/Sub Job(level)**: all

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/28354/voltsurge-torque

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**:    Voltsurge Torque  not work ,0 stat not have fast cast+4

**Comment by R3P0FFXI** [comment]
@Aurelcassy this has been pushed to DSP and will come down to legion once merged
