### ISSUE TITLE
Atrophy Chapeau +1 Missing stats

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1167]
**Date & Time**: 14-10-16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: aurel

**Nation**: sandy

**Job(level)/Sub Job(level)**:RDM

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/27688/atro-chapeau-1

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 

hi , head stat is 6% of haste so have 5% ,,and have ''ZERO fast cast ''   0% fastcast

**Comment by R3P0FFXI** [comment]
@Aurelcassy This has been sent into DSP and once merged will be added to legion

**Comment by R3P0FFXI** [comment]
Issue resolved
