### ISSUE TITLE
Atrophy boots +1 Missing stats

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1168]
**Date & Time**: 14-10-16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: aurel

**Nation**: sandy

**Job(level)/Sub Job(level)**: rdm

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/28248/atrophy-boots-1

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: hi Atrophy boots +1 no have 20acc no have shied skill +13 ,haste bad

**Comment by R3P0FFXI** [comment]
@Aurelcassy this has been pushed to DSP and will come down to legion when it is merged

**Comment by Aurelcassy** [comment]
now work thanks
