### ISSUE TITLE
Atrophy Gloves +1 Missing stats

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1169]
**Date & Time**: 14 -10 -16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: aurel

**Nation**: sandy

**Job(level)/Sub Job(level)**: RDM

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/27968/atrophy-gloves-1

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Atrophy Gloves +1 no have acc +10 ,no have attcak +10 ,no have parrying +17 ,,,,Maybe all set is bugg

**Comment by R3P0FFXI** [comment]
@Aurelcassy item has been sent to DSP and will be included in legion once they merge
