### ISSUE TITLE
Zmey Gorynych spawns call for help status

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#117]
**Date & Time**: 6/24/15
**Frequency**: always
**FFXI Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: Hume
**Main Job**: NA
**Sub Job**: NA
**Area & Coordinates**: Cape Terrigan
**Party or Solo**: NA
**NPC Name**: NA
**Monster Name**: Zmey Gorynych
**Steps To Reproduce The Issue**: Mob spawns CFH status, making all drops auto 0% unless someone dies to it to fix it.

**Comment by Loki79** [comment]
Be in after maint.
