### ISSUE TITLE
Atrophy Tights +1 Missing stats

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1170]
**Date & Time**: 14-10-16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**:  aurel

**Nation**: sandy

**Job(level)/Sub Job(level)**: RDM

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/28115/atrophy-tights-1

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: Atrophy Tights +1 ,no have cure +10% ,no have skill add   

all states worked before

**Comment by R3P0FFXI** [comment]
@Aurelcassy fixes have been pushed to DSP will be merged once dsp has them
