### ISSUE TITLE
Crafting Skills for import character

### ISSUE THREAD

**Issue by Redaske** [LegionDark/Issues#1171]
**Date & Time**: 
10/15/2016  01:25am PST

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Redaske

**Nation**: 
Bastok 1

**Job(level)/Sub Job(level)**: 
99PLD/47DNC

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

http://legiondark.com/forums/viewtopic.php?f=37&t=1745&p=5873&hilit=Redaske#p5873

![img_20161015_012357](https://cloud.githubusercontent.com/assets/22852160/19408611/bc783342-9276-11e6-86be-f08deb1b6e37.png)

**Comment by TeoTwawki** [comment]
Was this a recent import character?

Also I just fixed the bug that was clipping the front digits of the version number off. 😃

**Comment by TeoTwawki** [comment]
Answered my own question, found your forum post and updated your info here. Its not missing it hasn't been applied yet, a GM will will be with you in game as soon as they are free to do so. 😄

**Comment by Redaske** [comment]
Appreciated.  lol I literally posted this and went to bed.

**Comment by Genesis-Legion** [comment]
Crafts imported.
