### ISSUE TITLE
VWNM Morta loot pool empty, probably others too

### ISSUE THREAD

**Issue by TeoTwawki** [LegionDark/Issues#1172]
**Date & Time**: 
Since at least October 14th maintenance

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yep

**Character Name**: 
N/A

**Nation**: 
N/A

**Job(level)/Sub Job(level)**: 
N/A

**NPC or Monster or item Name**: 
Morta, probably others too

**Zone name**: 
Aydeewa Subterrane, probably others too

**Coordinates (use `$where`)**: 
N/A

**ffxiah.com link (for items issues only)**: 
N/a

**Multi-boxing? (multiple clients on same connection)**: 
N/A

**Steps To Reproduce / any other info**: 
See #1088
This is a placeholder issue to try and avoid duplicate reports

**Comment by R3P0FFXI** [comment]
@TeoTwawki Duplicate https://github.com/LegionDark/Issues/issues/1156
