### ISSUE TITLE
Div-e Sepid does not spawn in Abyssea Vunkerl 

### ISSUE THREAD

**Issue by Nafff** [LegionDark/Issues#1173]
**Date & Time**: 10/15/2016 11:41 PM PST

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Naffy

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: RDM99/SCH49

**NPC or Monster or item Name**: Div-e Sepid

**Zone name**: Abyssea Vunkerl

**Coordinates (use `$where`)**: X:-530 Y:-39 Z:-481 (167)

**ffxiah.com link (for items issues only)**: http://ffxiclopedia.wikia.com/wiki/Div-e_Sepid

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Div-e Sepid doesnt seem to spawn at all in Abyssea Vunkerl. I checked his location for 15 minutes and via widescan. After looking for him in game I checked on the Legiondark monster tool and found he was not listed anywhere.

**Comment by Heepster03** [comment]
Closing due to overall Abyssea NM ticket made here: https://github.com/LegionDark/Issues/issues/1189
