### ISSUE TITLE
Crawler's Nest client crash

### ISSUE THREAD

**Issue by Sorenishii** [LegionDark/Issues#1176]
**Date & Time**: Oct. 16, 2016

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Soren

**Nation**: Bastok

**Job(level)/Sub Job(level)**: Thf 93/ Nin 46

**NPC or Monster or item Name**: Exoray

**Zone name**: Crawlers Nest

**Coordinates (use `$where`)**: x:61 Y:-28 Z:16 (190)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Kill an Exoray with a weapon skill (Viper Bite or Dancing Edge) And client will crash sometimes.

**Comment by TeoTwawki** [comment]
See #1115

We found anything stopping a mob from using a skill it was preparing can crash the client. 

Includes mob dying, stuns, sleep, terror, prettify.. And likely other situations where the mob wants to animate one thing while something we do makes a different animation go (dying has that fall down animation).

**Comment by TeoTwawki** [comment]
leaving this open, so if you have any reason to believe it can't possibly be the same as the other issue I linked any info you can provide to support that is appreciated.

**Comment by TeoTwawki** [comment]
see also:
#1002
#1115
https://github.com/DarkstarProject/darkstar/issues/3393
