### ISSUE TITLE
Croque-Mitaine

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#1177]
Date & Time: 
10/08/2016 9:41

FFXI Client Version (use /ver): 
30160831_1
Server's Expected Client Version matches, yes/no? (use $ecv): 
yes

Character Name: 
ritonami

Nation: 
windurst

Job(level)/Sub Job(level): 
thf99/dnc49

NPC or Monster or item Name: 
Croque-Mitaine

Zone name: 
pashow marshland (s)

Coordinates (use $where): 
215,24,-63 (64)

ffxiah.com link (for items issues only):

Multi-boxing? (multiple clients on same connection): 
yes

Steps To Reproduce / any other info: 
Mob is a goobue has tp moves of a peistes. fought it a couple times for aptants seems to crash my client half the time

**Comment by TeoTwawki** [comment]
My apologies this fell through the cracks.

**Comment by R3P0FFXI** [comment]
issue resolved in todays update
