### ISSUE TITLE
Halver 5-1 no dialog.

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1179]
**Date & Time**: 
10/16/2016 23:34

**FFXI Client Version (use `/ver`)**: 
61004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Thrice

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99NIN/49WAR

**NPC or Monster or item Name**: 
Halver

**Zone name**: 
Chateau d'Oraguille

**Coordinates (use `$where`)**: 
X:0 Y:0 Z:0 (121)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes/no

**Steps To Reproduce / any other info**: 
Zoned into the Chateau got initial cutscene for 5-1 (was dualboxing at the time) both toons got CS. Went to gate guard after and accepted on both toons. Zoned back to the Chateau talk to Halver, Thrice gets no dialog at all with Halver, while Pimparu was able to get the New Fei'Yin seal. logged off all toons, logged back in only trice followed all steps above again and still no dialog option with Halver.

**Comment by TeoTwawki** [comment]
@LegionDark/gm do thsi for anyone having this issue. I'm fixing it in dsp but players who already saw that cs will need these run on them:

`$addkeyitem NEW_FEIYIN_SEAL <name>`
`$setplayervar <name> MissionStatus 10`

**Comment by TeoTwawki** [comment]
Handled by a GM in game who forgot to post back here :)
