### ISSUE TITLE
Armor Storage NPC

### ISSUE THREAD

**Issue by helixhamin** [LegionDark/Issues#118]
**6/24/2014 11:35 PM PST+8**: 
**Always**:
**30150508_8**:
**Weijun**:
**Hume**:
**BLU**:
**NIN**:
**Lower Jeuno/X:22 Y:1 Z:38 (76) - Northern San d'Oria/X:-90 Y:0 Z:59 (86)**:
**Party, but both**:
**Caruvinda/Taulenne**:
**N/A**:
**Trade PLD Gallant set to NPC, npc doesn't take, doesn't give claim slip**:

It seems the armor storage NPCs are no longer accepting Gallant. I tried with WHM AF1 and the NPC accepted with no issues.

**Comment by R3P0FFXI** [comment]
This is a DSP issue, l will open a DSP ticket

**Comment by R3P0FFXI** [comment]
PLease advise if still an issue we just pulled a DSP update

**Comment by helixhamin** [comment]
I will test when I am able to get online and let you know the outcome. If it works, I will close and comment.

**Comment by helixhamin** [comment]
After testing, it is still not working. I have tested the following NPCS:
http://ffxiclopedia.wikia.com/wiki/Armor_Depository
Caruvinda	Lower Jeuno (J-6)
Tesch Garanjy	Windurst Woods (H-11)
Taulenne	Northern San d'Oria (G-8)
Sinon	Bastok Markets (H-9)
Ratonne	Tavnazian Safehold (F-8) (Main level)
Hajawaa	Aht Urhgan Whitegate (H-8)
Renadile	Southern San d'Oria (S) (L-6)

I will also post in the DSP issue.

**Comment by Loki79** [comment]
Our custon NPC gives the claim slips for free... drop the items and get again >.>  Closing this out.
