### ISSUE TITLE
Minax Bugard will not spawn when trading correct item

### ISSUE THREAD

**Issue by Nafff** [LegionDark/Issues#1180]
**Date & Time**: 10/16/2016 11:09PM PST

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Naf

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 99NIN/49WAR

**NPC or Monster or item Name**: Minax Bugard

**Zone name**: Abyssea Misareaux Coast

**Coordinates (use `$where`)**: X:508 Y:13 Z:-264 (143)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Traded Bewitching Tusk to correct ??? and Minax Bugard did not pop. Tried multiple times on different characters to be sure. Checked LegionDark monster tool and found he was not listed at all.

**Comment by Heepster03** [comment]
Closing due to overall Abyssea NM ticket made here: https://github.com/LegionDark/Issues/issues/1189
