### ISSUE TITLE
Seedspray Missing From Normal Mobs

### ISSUE THREAD

**Issue by atom0s** [LegionDark/Issues#1182]
**Date & Time**:  10/17/2016 - 3:00pm

**FFXI Client Version (use `/ver`)**:  30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Atomos

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: BLU99/---

**NPC or Monster or item Name**: Rafflesia

**Zone name**: West Sarutabaruta [S]

**Coordinates (use `$where`)**: -206, -23, 531

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No.

**Steps To Reproduce / any other info**: 

Attack Rafflesia's, they do nothing TP wise. Missing all TP moves and BLU spell move 'Seedspray.'. Appears to be missing from all past mobs that can use it.

**Comment by R3P0FFXI** [comment]
@atom0s issue resolved in todays update
