### ISSUE TITLE
Belladonna Disappears After Using Viscid Emission

### ISSUE THREAD

**Issue by atom0s** [LegionDark/Issues#1183]
**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: Belladonna 

**Zone name**: West Sarutabaruta [S]

**Coordinates (use `$where`)**: -104 -22 175 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

Fighting Belladonna, when she uses Viscid Emission her model just disappears.

**Comment by TeoTwawki** [comment]
fixed it, forgot to close issue
