### ISSUE TITLE
Lobison Use Asuran Claws In Wrong Form

### ISSUE THREAD

**Issue by atom0s** [LegionDark/Issues#1184]
**Date & Time**: Oct 17, 2016

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Atomos

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: BLU99/---

**NPC or Monster or item Name**: Lobison

**Zone name**: Jugnar Forest [S]

**Coordinates (use `$where`)**: -347 -1 215

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No.

**Steps To Reproduce / any other info**: 

Attack Lobison's for Asuran Claws. They are supposed to only use it while standing. Instead, they only use it while sitting on all 4's.

**Comment by TeoTwawki** [comment]
They should be using it in both forms actually (on darkstar at least) and one likely animates wrong to boot. I'll go look for anything that might be preventing the standing up one from firing.

**Comment by TeoTwawki** [comment]
Fixed in dsp trunk and hotfixed on server live.
