### ISSUE TITLE
BLU Question bug

### ISSUE THREAD

**Issue by viperzero8** [LegionDark/Issues#1185]
**Date & Time**: 
Oct 18th 0745

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Lenneth

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
War30/Blm1

**NPC or Monster or item Name**: 
Waoud

**Zone name**: 
Whitegate

**Coordinates (use `$where`)**: 
X:67 Y:-6 Z:-76 (74)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
"Empty Vessel" Wont give any other responce to questions other then Springserpent. Tried ALL combinations. Spent 4 hours doing so. Please advise

**Comment by TeoTwawki** [comment]
Tested working. You are wrong, and its worth noting that ffxiclopedia and bg wiki differ as to the right answers. Whichever guide you followed, try the opposite. If you were just guessing answers try one of them then the other. But this isn't bugged got 2 GMs who were abe to do this.

**Comment by atom0s** [comment]
Personally used ffxiclopedia's answers about 3-4 days ago. Worked fine for me without issue.

**Comment by Heepster03** [comment]
I just used bgwiki and it also worked fine.

**Comment by TeoTwawki** [comment]
Seems they have been edited so that both wiki's match now. Been a long time since I had to look on wiki.
