### ISSUE TITLE
~ Can't pop Iku-Torso ~

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#1186]
Date & Time: 18/10/16, 14.00

FFXI Client Version (use /ver): 30161004_1

Server's Expected Client Version matches, yes/no? (use $ecv): Yes

Character Name: thranduil

Nation: bastok

Job(level)/Sub Job(level): rdm99/whm49

NPC or Monster or item Name: Iku-Torso

Zone name: Abyssea Vunkerl

Coordinates (use $where): 241, -31, 241

ffxiah.com link (for items issues only):

Multi-boxing? (multiple clients on same connection): Yes

Steps To Reproduce / any other info: Traded Moonbeam clam ??? and Iku Torso did not pop. Checked LegionDark monster tool and found he was not listed at all.

**Comment by Heepster03** [comment]
Closing due to overall Abyssea NM ticket made here: https://github.com/LegionDark/Issues/issues/1189
