### ISSUE TITLE
~ Unable to learn SCH spells thunder/aurora/void-storm ~

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#1187]
**Date & Time**: 18/10/16, 19.00

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Nanatuttatana

**Nation**: Windurst

**Job(level)/Sub Job(level)**: SCH50/RDM25

**NPC or Monster or item Name**: 

**Zone name**: Port Windust, anywhere

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 

Tried to learn sch-storm spells by using scrolls, but no deal. Thank you.
![nanatuttatana_2016 10 18_190818](https://cloud.githubusercontent.com/assets/12772770/19488382/edc23bbc-9566-11e6-88af-d41bb742061e.png)

**Comment by TeoTwawki** [comment]
@R3P0FFXI check: 
scroll script (checks that user of said scroll is able to cast the spell), 
item_usable.sql (says scroll is a usable item and has the animation and use delay values), 
spell_list.sql (job mask that scroll script will check against) 

Missing or incorrect data in any of the 3 can cause this.

**Comment by TeoTwawki** [comment]
Cause has been found will be fixed next update.

**Comment by TeoTwawki** [comment]
Should be fixed now
