### ISSUE TITLE
Sandy 5-1 BC fight.

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1188]
**Date & Time**: 
10/18/2016 13:24

**FFXI Client Version (use `/ver`)**: 
61004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Thrice

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99NIN/49WAR

**NPC or Monster or item Name**: 
 

**Zone name**: 
Qu'Bia Arena/Chateau d'Oraguille

**Coordinates (use `$where`)**: 
X:0 Y:0 Z:0 (0)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Pimparu, Thrice, Lezeattacos, along with others from LS(Devolnu, Morphious) entered BC and cleared the battlefield, Thrice, Lez and Devolnu were k/o at the end of the fight. Lez, who is rank 6 already, was ejected from the battlefield on the winning side. Dev and Thrice were left in the battlefield with mobs that did not despawn and were given no option to homepoint or RR. Once we disconnected and reconnected it put us both on the loss side of the BS even though we both got the title of arch mage assassin. Pimparu has the key item burnt seal, Thrice has the KI of New Fei'Yin Seal still. Pimparu is able to progress to the next mission as normal, Thrice is not.

**Comment by TeoTwawki** [comment]
Anyone with the new seal KI should still be able to renter the BCNM, though having victory stolen like that sucks. Does the BCNM menu still come up for those players? I'll try and get with you all in game this afternoon.

**Comment by TeoTwawki** [comment]
I also need to know which characters were the multi box ones - who all was on same IP as who?

Multiboxing glitches battlefields, missions, variables..Its a pain. The only reason there is no rule against multiboxing anywhere except dyn is its pretty much impossible to prevent it. The only reason we catch people that break the rule about dynamis/limbus is we see the names when they trigger a related crash.

**Comment by TeoTwawki** [comment]
Could not catch you today, post back the info I asked for and a good time of day I am likely to catch you online in game

**Comment by JessLand86** [comment]
The BCNM menu still comes up on Thrice. 

I was multiboxing Thrice, Lezeattacos, and Pimparu. Devolnu and Morphious are two separate people who were helping me with the fight. Dev just happened to have the same issue with being ejected from the battlefield even though they have already completed the mission.

**Comment by JessLand86** [comment]
I'm online on Immortality or Lezeattacos for the next 10 hours perhaps.

**Comment by TeoTwawki** [comment]
Player proceeded normally in game after re-fight 😃 
**Probable cause:** multibox, or possibly multiple BCNM initiators (always make sure 1 person activates, and the rest click after gaining the status icon).
