### ISSUE TITLE
Abyssea NMs

### ISSUE THREAD

**Issue by Heepster03** [LegionDark/Issues#1189]
**Date & Time**: 10/18/2016

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Halkuras

**Nation**: Bastok

**Job(level)/Sub Job(level)**: N/A

**NPC or Monster or item Name**: See other info below for list.

**Zone name**: See other info below for list.

**Coordinates (use `$where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: 
Abyssea NMs missing / unpoppable:
- Abyssea-Konschtat
  -- Alkonost
  -- Ashtaerth the Gallvexed
  -- Bloodeye Vileberry
  -- Bombadeel
  -- Guimauve
  -- Keratyrannos
  -- Sacrophilus
  -- Siranpa-Kamuy
- Abyssea-Attohwa
  -- Gaizkin
  -- Gieremund
- Abyssea-Misareaux
  -- Abyssic Cluster
  -- Avalerion
  -- Cep-Kamuy
  -- Flame Skimmer
  -- Ironclad Severer
  -- Karkatakam
  -- Manohra
  -- Minax Bugard
  -- Nehebkau
  -- Nonno
  -- Npfundlwa
  -- Tuskertrap
- Abyssea-Vunkerl
  -- Armillaria
  -- Chhir Batti
  -- Div-e Sepid
  -- Durinn
  -- Dvalinn
  -- Gnawtooth Gary
  -- Iku-Turso
  -- Kadraeth the Hatespawn
  -- Karkadann
  -- Khalkotaur
  -- Quasimodo
  -- Rakshas
  -- Seps
  -- Xan
- Abyssea-Grauberg
  -- Ironclad Sunderer
  -- Lorelei
  -- Teugghia

**Comment by R3P0FFXI** [comment]
@TeoTwawki @Heepster03 @simthra @nafff  This is all set for Tuesday best I can do with the time I have if any still do not work well need to look into them further

**Comment by SquallerSnake** [comment]
In Abyssea-Konschtat clingy clare is not working

**Comment by R3P0FFXI** [comment]
@SquallerSnake We are aware this has been fixed and will be in the game tuesday

**Comment by R3P0FFXI** [comment]
Issue resolved in Maint Yesterday
