### ISSUE TITLE
Auctions no longer selling automatically

### ISSUE THREAD

**Issue by skidip** [LegionDark/Issues#119]
I have had the items in the attached screenshot posted to the auction house for at least 12+ hours and they have still not automatically sold to the AHBot:
![screenshot](https://cloud.githubusercontent.com/assets/13035433/8334304/238bcf02-1a65-11e5-896b-cc8ccd865236.png)
Previously, my items would sell back just fine, I never had any trouble. I noticed this started happening the other night when the server crashed. I was actually in the middle of auctioning when it crashed, so that may have something to do with it. I tried to remove these items from auction and re-post them, but they still would not sell. This happens with any items I list, and is not limited to the ones in the screenshot. Also, even though there's 7 items posted already, I'm still able to post more items which also do not sell and do not show up in my "Sales Status" list... For example, I tried to sell an Allure Ring +1 for 500k but it never sold and I cannot seem to find that auction anywhere.

**Comment by R3P0FFXI** [comment]
User needs to attach template to post

**Comment by skidip** [comment]
**Date & Time**: 6/23/15
**Frequency**: All the time
**FFXI Client Version**: 30150508_8
**Character Name**: Skidip
**Race**: Hume
**Main Job**: Beastmaster
**Sub Job**: White Mage
**Area & Coordinates**: Any
**Party or Solo**: Solo
**NPC Name**: Auction House
**Monster Name**: N/A
**Steps To Reproduce The Issue**: Log into my account and see the items aren't sold?

**Comment by R3P0FFXI** [comment]
AH bot was not running
