### ISSUE TITLE
Crafting skills cooking99 import for character

### ISSUE THREAD

**Issue by Ramilonlegiondark** [LegionDark/Issues#1190]
**Date & Time**: 
19/10/2016 21:25

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Ramilon

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
NIN99/DNC47

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

![img_20160830_140232](https://cloud.githubusercontent.com/assets/22943747/19534213/33651ef0-9643-11e6-898b-cc96a82124a5.png)

**Comment by Genesis-Legion** [comment]
Craft restored
