### ISSUE TITLE
Jailer of Temperance Not Spawning

### ISSUE THREAD

**Issue by Devolnu** [LegionDark/Issues#1191]
**Date & Time**: 10/20/2016 3:18pm central

**FFXI Client Version (use `/ver`)**:  30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**:  Devolnu

**Nation**:  Bastok

**Job(level)/Sub Job(level)**: 99Thf/49Dnc

**NPC or Monster or item Name**:  Jailer of Temperance

**Zone name**:  Grand Palace of Hu'Xzoi 

**Coordinates (use `$where`)**:   X: -426 Y: 0 Z: 687

**ffxiah.com link (for items issues only)**:  N/A

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**:  not respawning at all

**Comment by TeoTwawki** [comment]
Saw someone pop this with my own eyes a few days ago.

**Comment by atom0s** [comment]
Just tested this myself, got him to pop easily. Working fine.

**Comment by Devolnu** [comment]
According to your site it pops every 15 minutes. It isn't a lottery like
retail. So what's the timer? Or pop item?

**Comment by TeoTwawki** [comment]
Site tool is showing a time because someone set the wrong flag in the database, but the scripts are setting it to pop like retail and it *is* working.
