### ISSUE TITLE
Command to enter Legion doesnt appear to work

### ISSUE THREAD

**Issue by Oderson** [LegionDark/Issues#1193]
**Date & Time**: 
10/21/16  12:52 CST

**FFXI Client Version (use `/ver`)**:  30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  30161004_1

**Character Name**: 
Nevion, Smevion, Oderson

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
THF99

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: X:-453 Y:-7 Z:366 (219)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Have tried legionlaunch and legionhall commands, neither do anything, Having never used these commands, user error is a major possibility

**Comment by TeoTwawki** [comment]
I dunno what the intent was but the script appears to only handle 1 person and not their party/alliance...And it was the same in the old commands with the broken fee as well.

Sorry I'm dealing with a lot of bad code other put in and never came back to in a lot of diff places, and my memory isn't that code to start with.

**Comment by TeoTwawki** [comment]
\*that good

**Comment by Oderson** [comment]
Thanks again, someone just tried and said other pt members need to trade a cluster also to enter

**Comment by Heepster03** [comment]
I'm pretty sure I was always told to use the @legionhall (hallname) to enter as just a normal entrant. Granted it could be different but this was the general consensus of how to do it.

**Comment by TeoTwawki** [comment]
@Heepster03 Command original was made by back when it took a GM, and then an CA (community assistant) to run it. Then it was decided to let just anyone start it but charge a fee. Except the fee never worked (the script would stop if you didn't meet the requirements, but never removed the money/item from you..) and there was no reason to use a command when the tome could do the job with fewer issues (like 2 groups hitting the command at the same time - who gets the mobs then?).

The commands had been disabled months ago, accidentally re-enabled god knows when, then disabled. I'm really tired of trying to fix and also explain the stupid things on this server.

**Comment by sucidaldeathtar** [comment]
I was just in it and  the cost was 1 mil plus fire cluster BUT to get my other toons in I need to trade a fire cluster and if they had one mil gil on them it took it so I lost 2 mil entering and 5 fire clusters.

I did this I think a hr ago when I entered.  Died to wyrm aoeing my party down but killed turtles.

**Comment by TeoTwawki** [comment]
the trade requirements are teh same for every character, as the script is currently. as I already stated.

**Comment by PikaFox** [comment]
It wont work in its current iteration, as floors 2-5 require the trophy of the previous hall to progress. Meaning if everyone needs the items, assuming a 6 person party, youd need to clear floor 1 6 times to enter hall 2, then clear hall 1 6 more times and hall 2 5 more times to enter hall 3 etc.

I believe the legionhall command stayed to allow other players to enter, as the book only transports the original trader. legion 1 etc was the command to actually start the event iirc.

**Comment by TeoTwawki** [comment]
GDI. Its no wonder players are effing confuse dif even the GMs dunno wtf they are talking about.

**Comment by TeoTwawki** [comment]
just STOP effing POSTING
