### ISSUE TITLE
leathercrafting skill transfer

### ISSUE THREAD

**Issue by warlord1352** [LegionDark/Issues#1194]
**Date & Time**: 4:05pm pst

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Bumblebeeman

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99sam

**NPC or Monster or item Name**: 99 Leathercraft

**Zone name**: bastok mines/residential

**Coordinates (use `$where`)**: 0 0 -2

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Just got my character imported and trying to get my 100 leathercraft imported as well, since this character got imported from another private server R3P0 said only pick 1 craft. Thanks!

![bumblebeeman_2016 10 17_210040](https://cloud.githubusercontent.com/assets/15023912/19623106/e194574a-9871-11e6-8887-1f5c5a012dcd.png)

**Comment by warlord1352** [comment]
P.s. I need a linkpearl as well please and thank you.

**Comment by Genesis-Legion** [comment]
Transferred his leathercraft and given LegionDS pearl
