### ISSUE TITLE
Scroll of Kakka: Ichi not ingame

### ISSUE THREAD

**Issue by ffxijuggalo** [LegionDark/Issues#1195]
**Date & Time**: 10/23/2016

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Juggalo

**Nation**: Windurst

**Job(level)/Sub Job(level)**: thf99/dnc49

**NPC or Monster or item Name**: Kaggen

**Zone name**: Qufim Island

**Coordinates (use `$where`)**: Voidwatch Planer Rift

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Scroll of Kakka: Ichi doesn't drop from anything according to the item tool. FFXIclopedia has this spell listed as dropping from Kaggen.

**Comment by Samikana** [comment]
I love you. <3

**Comment by ffxijuggalo** [comment]
Love you too Sami lol

**Comment by JessLand86** [comment]
NPC Solby-Maholby sells these in Norg btw.

**Comment by Heepster03** [comment]
Why is this ticket still open? I just reverified that the NPC Solby-Maholby does sell Kakka: Ichi for 133k.

**Comment by TeoTwawki** [comment]
It got buried and forgotten.
