### ISSUE TITLE
No Planar Rift in Carwlers Nest.

### ISSUE THREAD

**Issue by Dalkiel81** [LegionDark/Issues#1196]
**Date & Time**:  October 24, 2016.  12:15 am

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30161004_1 yes

**Character Name**: 
Dalkiel

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99Blu/49Rdm

**NPC or Monster or item Name**: 
Mellonia

**Zone name**: 
Crawler's Next

**Coordinates (use `$where`)**: 
X:57 Y:0 Z:263 (72)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
The is no Planar Rift anywhere in Crawler's Nest.
I Checked all locations, and couldn't find any.

**Comment by TeoTwawki** [comment]
NPC ID's were wrong. Fixed now.
