### ISSUE TITLE
The Jumping Crab/Excalipoor

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#1197]
**Date & Time**: 10/24/2006

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: blu99/rdm49

**NPC or Monster or item Name**: The Jumping Crab

**Zone name**: Rolanberry fields [S]

**Coordinates (use `$where`)**: X:-736 Y:-30 Z:-370 (109)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: After beating the jumping crab both myself and Nyaarun got excalipoor in the chest, but when we took it out the item it gave us was Ibushi shinai instead.

**Comment by TeoTwawki** [comment]
This is normal. Its random which item you get Both item get used in an as yet unimplemented battlefield.
