### ISSUE TITLE
Unable to pop Ix'aern (DRK)

### ISSUE THREAD

**Issue by alannor** [LegionDark/Issues#1198]
**Date & Time**: 
2016/10/24

**FFXI Client Version (use `/ver`)**: 
current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Kathy

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
THF/DNC

**NPC or Monster or item Name**: 
Ix'aern (DRK)

**Zone name**: 
Garden of Ruhmet

**Coordinates (use `$where`)**: 
-561, 5, 238 (217)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Trade aern organ to ??? results in the messgae cannot spawn mob - are you sure it isn't already up?

In fact yoy can trade the ??? and it will say the same message, I tried a bat fang just to test

The ??? also does not move. Have tried clearning the room several times and that didnt help either.

**Comment by TeoTwawki** [comment]
#739
