### ISSUE TITLE
Chatoyant Staff Improper Perpetuation Cost (at 92 summoner)

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#12]
**Date & Time**: 5/26/15
**Frequency**: NA
**FFXi Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: Hume
**Main Job**: Smn 92
**Sub Job**: NA
**Area & Coordinates (Type @where to get this info.)**: NA
**Party or Solo**: NA
**NPC Name**: NA
**Monster Name**: NA
**Steps To Reproduce The Issue**: Equip Chatoyant Staff at 92 smn, get -5 perpetuation cost reduction instead of -3

**Comment by R3P0FFXI** [comment]
Working with DSP on this it may be an Affinity Issue this staff has multiple affinity mods on it

INSERT INTO `item_mods` VALUES (18633, 347, 2);
INSERT INTO `item_mods` VALUES (18633, 348, 2);
INSERT INTO `item_mods` VALUES (18633, 349, 2);
INSERT INTO `item_mods` VALUES (18633, 350, 2);
INSERT INTO `item_mods` VALUES (18633, 351, 2);
INSERT INTO `item_mods` VALUES (18633, 352, 2);
INSERT INTO `item_mods` VALUES (18633, 353, 2);
INSERT INTO `item_mods` VALUES (18633, 354, 2);

**Comment by R3P0FFXI** [comment]
Darkstar bug will be handled and fixed through DSP
