### ISSUE TITLE
Unable to equip Vespid Mantle on WAR

### ISSUE THREAD

**Issue by maikuru23** [LegionDark/Issues#120]
**Date & Time**: 6/26/2015  @6:39PM PST
**Frequency**:  Always
**FFXI Client Version**:  30150508_8
**Character Name**:  Maiku
**Race**:  Taru
**Main Job**:  WAR
**Sub Job**:  SAM
**Area & Coordinates**:  X:115,  Y:0, Z:-57  (151)
**Party or Solo**:  Solo
**NPC Name**:  N/A
**Monster Name**:  N/A
**Steps To Reproduce The Issue**:
1. Get Vespid Mantle
2. See mantle has WAR in jobs able to wear
3. Try to equip mantle on warrior
4. Acts like job is unable to equip mantle
5. works on other jobs I.E. RNG

**Comment by R3P0FFXI** [comment]
INSERT INTO `item_armor` VALUES (28641,'vespid_mantle',99,0,4947942,0,0,0,32768,0); 

Job mask should be 2473971

**Comment by R3P0FFXI** [comment]
Item will be temp updated in Legion but needs to be sent to DSP in shareback to fully fix
