### ISSUE TITLE
HP Crystal issue in Qufim Island

### ISSUE THREAD

**Issue by Sorenishii** [LegionDark/Issues#1202]
**Date & Time**: 10/24/2016 7:09pm pst

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Soren

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99thf/49dnc

**NPC or Monster or item Name**: Homepoint #1

**Zone name**: Qufim Island

**Coordinates (use `$where`)**: X:-211 Y:-20 Z:93 (161)

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Click the homepoint #1 crystal in Toraimarai Canal at the entrance to Full Moon Fountain, and then collect/click the Homepoint #1 crystal in Qufim island. Then when you select to teleport to the homepoint in Toraimarai canal, it takes you to the Homepoint#1 crystal in Qufim island to said Coordinates as listed above.

**Comment by TeoTwawki** [comment]
> I will be replacing the homepoint warps with something custom in the future, due to the repeated hassles the crappy implementation in DSP causes

Nothing legion can do to correct them, its craptacular in darkstar and not worth making a pull request to try and fix in darkstar, so just going to have to eventually shut them off and give a replacement feature to compensate.
