### ISSUE TITLE
Viseclaws missing in The Boyahda Tree

### ISSUE THREAD

**Issue by ffxijuggalo** [LegionDark/Issues#1203]
**Date & Time**: 10/25/2016 12:44AM

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Juggalo

**Nation**: Windurst

**Job(level)/Sub Job(level)**: thf99/dnc49

**NPC or Monster or item Name**: Viseclaw

**Zone name**: The Boyahda Tree

**Coordinates (use `$where`)**: X:-203 Y:8 Z:-276 (72)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Mourning Crawlers and Snaggletooth Peapuks are visible, but Viseclaws are not present within the same area as the other two mobs.

**Comment by ffxijuggalo** [comment]
Update: Page 8 from the grounds tome in The Boyahda Tree requirements:

```2 Viseclaws```
```2 Snaggletooth Peapuks```
```2 Mourning Crawlers```

Can't complete this GoV page with the Viseclaws missing from the area.
Would make for a great additional exp/merit location

**Comment by Jessland86** [comment]
These have been added at some point and this ticket never got closed.

![image](https://user-images.githubusercontent.com/28382433/29773439-8b5a5246-8bcb-11e7-9ffe-6210c3c40c7b.png)
