### ISSUE TITLE
Crafting Skills Import Slimshmitty

### ISSUE THREAD

**Issue by redx3** [LegionDark/Issues#1207]
**Date & Time**: 
10/29/16 10:30am

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Slimshmitty

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
Thf - subjob not unlocked yet

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
[http://legiondark.com/forums/viewtopic.php?f=37&t=1779](url)

Hope I did this right. :)

**Comment by Genesis-Legion** [comment]
Crafts imported
