### ISSUE TITLE
Supay Weskit (Item Id: 26874) Missing Magic Attack +20 Mod (not MAB).

### ISSUE THREAD

**Issue by Genesis-Legion** [LegionDark/Issues#1209]
**Date & Time**: 7:00 PM

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  Yes

**Character Name**: Genesis

**Nation**: Bastok

**Job(level)/Sub Job(level)**:  BLM99/RDM49

**NPC or Monster or item Name**: None

**Zone name**: West Ronfaure 

**Coordinates (use `$where`)**: X:-283 Y:-59 Z:364 (65)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/26874/supay-weskit

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
Checked mods on website for the weskit, noticed it was missing the Magic Damage +20 mod on it.

**Comment by Genesis-Legion** [comment]
INSERT INTO `item_mods` VALUES (26874,28,20);
should be correct, just so you don't have to do any work (the mod is missing from DSP's item_mods file, not anything custom)

**Comment by TeoTwawki** [comment]
code displays better if you wrap it in 3 backtics (optionaly can include langauge for syntax highlighting), like so:
```
\```sql
INSERT INTO item_mods VALUES (26874,28,20);
\```
```

Ignore the slashes, used them to make it display :)

```sql
INSERT INTO item_mods VALUES (26874,28,20);
```

**Comment by Genesis-Legion** [comment]
Ahh :) thanks teo

**Comment by TeoTwawki** [comment]
😄 https://github.com/DarkstarProject/darkstar/pull/3525
congrats on successful pull request

**Comment by R3P0FFXI** [comment]
Issue resolved in Maint Yesterday
