### ISSUE TITLE
Brego Gloves not abe to be paced on AH

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#121]
**Date & Time**:6/27/2015 6:57pm est 
**Frequency**: anytime I try to pace Bergo Goves on AH
**FFXI Client Version**: 30150508_8
**Character Name**:Baucant
**Race**:Elvaan
**Main Job**:Thf
**Sub Job**: Dnc
**Area & Coordinates**: attempted at multipull AH counters and useing the @ah command
**Party or Solo**:both
**NPC Name**:Auction House counter
**Monster Name**:N/A
**Steps To Reproduce The Issue**: I have attempted to place this item on AH multipul times. I get to the point where you put in the selling price but the "confirm sale" box never appers. I am also having a similar issue with a spider web that will give confirm sale but item doesn't leave my inventory.

**Comment by R3P0FFXI** [comment]
Checked Flags all looked ok

Item is labeled as 19 in ah flag, checked item armor it is listed as 64 for slot. This will have to wait for Loki to return as I am at a loss here.

**Comment by Loki79** [comment]
how many items to have up for sale?  @R3P0FFXI  give these to yourself in game and try to sell them so we get a baseline here.  The fact that its happening "One Spiderweb" and not other leads me to believe its not the items,

**Comment by Loki79** [comment]
@R3P0FFXI wow man.... was exactly wtf i said it was.  they were flagged "No Auction"
