### ISSUE TITLE
Not ganing Bayld after void watch nms killed

### ISSUE THREAD

**Issue by viperzero8** [LegionDark/Issues#1210]
<!-- 
DO NOT REMOVE OR CHANGE THE PRE-FORMATTED TEXT TO PUT @COMMANDS IN TEMPLATE!!!
GITHUB SEES `@MENTIONS`, NOT `@GMCOMMANDS`!!!
IF YOU STUPIDLY IGNORE THIS WARNING I WILL CLOSE YOUR ISSUE!11eleventytwo!

Issues will also be closed without being looked into if 
the following information is missing (unless its not applicable)!!!

I fought 5 T4 void watch NMs and gained Rems and coins but no bayld. Everyone with me in the pt gained around 3000 bayld and I still have 0

**Date & Time**: 
11/2/2016

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30161004_1

**Character Name**: 
Lenneth

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99BLU/49RDM

**NPC or Monster or item Name**: 
NA

**Zone name**: 
NA

**Coordinates (use `$where`)**: 
NA

**ffxiah.com link (for items issues only)**: 
NA

**Multi-boxing? (multiple clients on same connection)**: 
6

**Steps To Reproduce / any other info**: 
VNM

**Comment by TeoTwawki** [comment]
My psychic powers didn't tell me which NM was involved, or any other of the info that we have fields in the template for.
