### ISSUE TITLE
AH bot seems borked

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1212]
**Date & Time**: 11/6/16

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Nyaarun

**Nation**: Win

**Job(level)/Sub Job(level)**: 99rdm/49whm

**NPC or Monster or item Name**: na

**Zone name**: na

**Coordinates (use `$where`)**: na

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 
AH seems to have not stocked/bought items since around oct 30th or 31st.

**Comment by R3P0FFXI** [comment]
@PikaFox wasn't running just started it issue fixed

**Comment by atom0s** [comment]
Can you tell me on IRC where the exe for this is located so I can restart it if I ever have to again? Wasn't sure where it was so I never restarted it after the hard-boot the other morning.

**Comment by TeoTwawki** [comment]
@atom0s on the remotes machines desktop is a folder with several shortcuts in it. These start the the executable via a script which handles automatic restarts as well. Without them all the automation is gone for periodic lobby resets and restart on crash. Each shortcut is named for which executable it starts.
