### ISSUE TITLE
Blue Mage Assimilation Not Showing Up

### ISSUE THREAD

**Issue by dial8urmind** [LegionDark/Issues#1214]
Spent 5 merit points on Assimilation to raise max blue mage points.  Was capped at 55, should have raised that to 57.  However, I am still capped at 55.  Information below:

**Date & Time**:  11/6/2016  9:30PM

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**:  Eclypse

**Nation**:  Sandy

**Job(level)/Sub Job(level)**: 99BLU/49DNC

**NPC or Monster or item Name**: NA

**Zone name**: Mog House

**Coordinates (use `$where`)**:  X:0 Y:0 Z:0  (192)

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**:  No

**Steps To Reproduce / any other info**: Zoned and logged to see if max blue mage points would change.  Did not.

**Comment by R3P0FFXI** [comment]
@dial8urmind this is a DSP issue not legion, please report it to DSP

**Comment by TeoTwawki** [comment]
#298
