### ISSUE TITLE
Can't withdraw mog house inventory.

### ISSUE THREAD

**Issue by romethius** [LegionDark/Issues#1215]
**Date & Time**: 11/6/2016 10:45pm (CST)

**FFXI Client Version (use `/ver`)**: Ashita - 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**:  Zell

**Nation**: San D'Oria

**Job(level)/Sub Job(level)**: BLU99 (no sub job yet)

**NPC or Monster or item Name**: All of my mog house inventory.

**Zone name**: North San D'Oria (Mog House)

**Coordinates (use `$where`)**: x:0 Y:0 Z:-1 (184)

**ffxiah.com link (for items issues only)**: All of my mog house inventory

**Multi-boxing? (multiple clients on same connection)**:  nope

**Steps To Reproduce / any other info**: I just go into my mog house, try to open mog house, mob bag, all of them do the same thing, i can put items IN the inventory but I can't take them back out. Even when it's an item i just put in there, still unable to withdraw.

**Comment by R3P0FFXI** [comment]
@romethius Throw out your Mog Kupons, and Cipher of Koru-morus alter ego and youll be able to access your inventory this should solve your issue I am able to access your inventory, Mog Safe etc. now when I import to a test character.

**Comment by romethius** [comment]
Wonderful! Thanks very much. I'll do that when I get home from work unless you're just bored and feel like it lol if not I'll just take care of it later tonight. 

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 15, 2016 at 5:46 PM, R3P0FFXI<notifications@github.com> wrote:   
@romethius Throw out your Mog Kupons, and Cipher of Koru-morus alter ego and youll be able to access your inventory this should solve your issue I am able to access your inventory, Mog Safe etc. now when I import to a test character.

**Comment by TeoTwawki** [comment]
@R3P0FFXI He can't throw them out form his already imported character..You have to clarify if you intended him to re-export. Otherwise you need to manually nuke those from the database for him. Which is what I did for others with this issue. You look up the character ID and search for that the item ID with a `WHERE` clause for the char ID. I probably pre-saved a query for you last time..

**Comment by romethius** [comment]
So, I need to go onto my retail account, drop those items then re export the data and upload it to the forum? Or just email it to you?

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 15, 2016 at 7:15 PM, TeoTwawki<notifications@github.com> wrote:   
@R3P0FFXI He can't throw them out form his already imported character..You have to clarify if you intended him to re-export. Otherwise you need to manually nuke those from the database for him. Which is what I did for others with this issue. You look up the character ID and search for that the item ID with a WHERE clause for the char ID. I probably pre-saved a query for you last time..

**Comment by TeoTwawki** [comment]
I wouldn't. thats kind of shitty if you ever played retail again.

**Comment by romethius** [comment]
Oh uh....ok so um definitely misunderstanding what you're telling me to do lol I get there are the items you listed you said was the reason my stuff couldn't be withdrawn. Are you saykng you're going to tske care of it or do I need to do something? I'm nkt sure how to look up item IDs but I can google it when I get home. Im at work right now so my brains has several things going through it so I'm having problems understanding what you're saying

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 15, 2016 at 7:23 PM, TeoTwawki<notifications@github.com> wrote:   
I wouldn't. thats kind of shitty if you ever played retail again.

**Comment by TeoTwawki** [comment]
> Oh uh....ok so um definitely misunderstanding what you're telling me to do lol
@romethius That's because I was telling him not you, thats why I `@mentioned` him.

**Comment by R3P0FFXI** [comment]
@romethius you actually had what appeared to be a 1 off situation and thats where some of the confusion seems to stem from. Normally when this happens the item or items causing the issue do not appear in a players inventory. 

In this particular case the items that appeared to be causing the issue are showing up in your inventory. When I tested by deleting those 4 things I was able to move your carbuncles ruby etc to your mog safe sack etc and withdraw all your o bronze to your inventory from safe. 

This does not mean there are not further items causing issues but at this time it appears the 4 items I listed may have been causing what you saw initially. 

Please delete them from inventory on Legion not retail, test and let me know if further issues show up.

**Comment by romethius** [comment]
Gotcha! Will do in a few hours. 

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 15, 2016 at 8:05 PM, R3P0FFXI<notifications@github.com> wrote:   
@romethius you actually had what appeared to be a 1 off situation and thats where some of the confusion seems to stem from. Normally when this happens the item or items causing the issue do not appear in a players inventory. 

In this particular case the items that appeared to be causing the issue are showing up in your inventory. When I tested by deleting those 4 things I was able to move your carbuncles ruby etc to your mog safe sack etc and withdraw all your o bronze to your inventory from safe. 

This does not mean there are not further items causing issues but at this time it appears the 4 items I listed may have been causing what you saw initially. 

Please delete them from inventory on Legion not retail, test and let me know if further issues show up.

**Comment by R3P0FFXI** [comment]
@romethius is this still an issue we have not heard back from you

**Comment by R3P0FFXI** [comment]
No response from user closing
