### ISSUE TITLE
Lugra Cloak Doesnt Restrict Head Slot

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1216]
**Date & Time**: 11/7/16

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Nyaarun

**Nation**: Win

**Job(level)/Sub Job(level)**: 99Drk

**NPC or Monster or item Name**: na

**Zone name**: na

**Coordinates (use `$where`)**: na

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/26896/lugra-cloak

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 
Equip Headslot, It will not restrict the head slot

```
INSERT INTO `item_armor` VALUES (26896,lugra_cloak,99,119,128,46,0,0,32,4);
```
Should fix the issue, assuming i scripted it correctly (and hopefully i did that correctly)

**Comment by Heepster03** [comment]
This also happened to Vermillion cloak. I'm going to assume that it's probably all cloaks.

**Comment by R3P0FFXI** [comment]
@PikaFox Resolved
