### ISSUE TITLE
Maxwellcross Crafting Skill Transfer

### ISSUE THREAD

**Issue by DJMaxwell87** [LegionDark/Issues#1217]
**Date & Time**:  11/07/2016 9:17PM

**FFXI Client Version (use `/ver`)**:  30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  30161004_1

**Character Name**:  Maxwellcross

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  SCH99/RDM49

**NPC or Monster or item Name**: 

**Zone name**:  The Eldieme Necropolis [S]

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
![14959167_10154658142287698_914174991_o](https://cloud.githubusercontent.com/assets/23328996/20087796/8a1f5f0c-a530-11e6-85a2-9dceb73b998c.jpg)

**Comment by Heepster03** [comment]
Crafts imported.
