### ISSUE TITLE
Taisaijin being a pain in my rear end (works, breaks, works, breaks again..)

### ISSUE THREAD

**Issue by TeoTwawki** [LegionDark/Issues#1218]
**Date & Time**: 
Since pulling in DSP updates - we had him working before

**FFXI Client Version (use `/ver`)**: 
n/a

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yep

**Character Name**: 
n/a

**Nation**: 
n/a

**Job(level)/Sub Job(level)**: 
n/a

**NPC or Monster or item Name**: 
Taisaijin & Taisai

**Zone name**: 
Ranguemont Pass

**Coordinates (use `$where`)**: 
-15 7 -131

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
I've repaired this peckers spawn code 3 times now, successfully spawned it personally, killed it, watched PH respawn. Still getting reports of it or one or its placeholders going missing later. Need to retest after next maint.

**Comment by atom0s** [comment]
#thanksobama

**Comment by TeoTwawki** [comment]
Seems fixed (again)
