### ISSUE TITLE
Nation Mission Quest Issue ~Tifa

### ISSUE THREAD

**Issue by aimez** [LegionDark/Issues#1219]
**Date & Time**: 
11/9/2016 at 5:32pm

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Tifa

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
RDM99/WHM49

**NPC or Monster or item Name**: 
Ambrotien

**Zone name**: 
South San d'Oria

**Coordinates (use `$where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
 I went to go get the nation mission "Appointment to Jeuno" from the gate guard Ambrotien and due to lag on my end it per-selected the mission "The Crystal Spring" and due to no Crystal Bass in AH nor being able to fish without crashing the server i am sadly unable to to complete this mission thus I cannot move to Rank 4 in nation missions. 
Thank you for your time,
~Tifa

**Comment by TeoTwawki** [comment]
@aimez your template is all borked...


@R3P0FFXI you were supposed to make sure they were in bot last time this came up.

**Comment by aimez** [comment]
:O lol

**Comment by R3P0FFXI** [comment]
@TeoTwawki Crystal bass is in the bot ID 4528 it was probably just sold out

**Comment by TeoTwawki** [comment]
It shouldn't be sold out - almost nobody does that mission, everyone skips it.

Makes me think its being bought to be resold somewhere if thats the case.

**Comment by aimez** [comment]
aw ok ty teo :) im sry if i wasnt anytime was unsure as to wat i needed to do always better to ask n not know :) ty sir! ^^

**Comment by Genesis-Legion** [comment]
The fish finally restocked, but atm they're set to only stock one single stack, and one single which could cause issues.

**Comment by TeoTwawki** [comment]
Yeah thats not right. PAGING @R3P0FFXI AGAIN

**Comment by R3P0FFXI** [comment]
@aimez @TeoTwawki this was taken care of today with some minor AH updates
