### ISSUE TITLE
Gnawtooth Gary drop list

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#122]
**Date & Time**: 6/28/2015
**Frequency**: always
**FFXI Client Version**:30150508_8
**Character Name**:Baucant
**Race**: Elvaan
**Main Job**:THF
**Sub Job**:nin
**Area & Coordinates**:Aby ssea - Vunkerl
**Party or Solo**:both
**NPC Name**:???
**Monster Name**:Gnawtooth Gary
**Steps To Reproduce The Issue**:Drop list for Gnawtooth Gary shows only 0's

**Comment by R3P0FFXI** [comment]
INSERT INTO `mob_droplist` VALUES (9214,0,19259,223); -- Clarus Stone
INSERT INTO `mob_droplist` VALUES (9214,0,3193,356); -- Goetia Seal: Feet BLM
INSERT INTO `mob_droplist` VALUES (9214,0,3204,303); -- Caller's Seal: Feet SMN
INSERT INTO `mob_droplist` VALUES (9214,0,3207,363); -- Cirque Seal: Feet PUP
INSERT INTO `mob_droplist` VALUES (9214,0,3199,204); -- Aoidos' Seal: Feet BRD

Will be inserted for Tuesday

**Comment by R3P0FFXI** [comment]
Pushed to server will be executed during maint
