### ISSUE TITLE
~ Tamaxchi still missing ~

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#1220]
**Date & Time**: 09/11/16 13.42 GMT+1

**FFXI Client Version (use `/ver`)**:  30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**: Nanatuttatana

**Nation**: Windurst

**Job(level)/Sub Job(level)**: WHM99/RDM49

**NPC or Monster or item Name**: Tamaxchi

**Zone name**: Abyssea-Attohwa

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/21125/tamaxchi

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Tamaxchi is still missing after today maint; it used to be a Blazing Eruca drop.

**Comment by R3P0FFXI** [comment]
@simthra This is intentional this drop will be getting a new location in the future I removed it during the last weapon shift.
