### ISSUE TITLE
~ Can't close VW Op 26: Tavnazian Terrors ~

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#1221]
**Date & Time**: 11/09/16 21.28 GMT+1

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 1

**Character Name**: Thranduil

**Nation**: bastok

**Job(level)/Sub Job(level)**: blu99/rdm49

**NPC or Monster or item Name**: Owain

**Zone name**: Tavnazian Safehold

**Coordinates (use `$where`)**: -17,-25,126

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: Killed all the Hyacinth T1 mobs, then went to Owain to close the quest but it's not working.

**Comment by SquallerSnake** [comment]
Same problem for me:

Character Name: Squaller

this is the active quest:

![img_20161109_124038](https://cloud.githubusercontent.com/assets/13245127/20153919/53131238-a6c5-11e6-9fab-6d77acf48330.png)

 this is the message after talking to Owain (after the 4 kill)

![img_20161109_212547](https://cloud.githubusercontent.com/assets/13245127/20153943/71ebbf3e-a6c5-11e6-8f4d-9c7fdf9a39f4.png)

**Comment by TeoTwawki** [comment]
Owain doesn't close the quest, the final NM kill does and the next quest is immediately flagged, so one or more of your NM kills didn't register. There's an **optional** cs event at Owain after this before fighting Bismarck as the next task.

**Comment by TeoTwawki** [comment]
Additionally, A fix for Isarukitsck (he's the one you will need to re-kill) is incoming..

**Comment by TeoTwawki** [comment]
Left instructions with other GMs to get with folks in game on this, after which issue can be closed. Code was patched last night and I forgot to post back here after.

**Comment by simthra** [comment]
Fought the whole tier1 again and it worked fine; got the auto-upgrade to Hyacinth II and then moved on to amber. Thank you.

**Comment by SquallerSnake** [comment]
Same for me all fine now.
