### ISSUE TITLE
WHM Maat Glitching

### ISSUE THREAD

**Issue by Devolnu** [LegionDark/Issues#1222]
**Date & Time**: 11/9/2016

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Sweatybawls

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 70whm/35blm

**NPC or Monster or item Name**: Maat fight

**Zone name**: Balga's Dais

**Coordinates (use `$where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Stayed alive for 8+ minutes fighting maat cured alot of HP and got repose off at one point. Nothing triggered a win. Timed out then glitched watching maat kill me and event saying 18 hours left. what is going on?

**Comment by TeoTwawki** [comment]
Whats going on is you are trying to do something that likely doesn't work on DSP.

**Comment by TeoTwawki** [comment]
99% sure they don't have that win method atm.

**Comment by Devolnu** [comment]
I am curing myself just like you are supposed to so how is that wrong?

**Comment by Devolnu** [comment]
Cure method is how people are telling me they did it long ago on this
server so explain

**Comment by R3P0FFXI** [comment]
https://github.com/DarkstarProject/darkstar/issues/3530 its a DSP bug

**Comment by TeoTwawki** [comment]
There nothing anywhere in his battlefield code either in core or script different from darkstar beyond the food thing. I'm not explaining anything beyond that, deal with it.

**Comment by Fiocitrine** [comment]
> Cure method is how people are telling me they did it long ago on this
server so explain

A please would be nice ^^

**Comment by Samikana** [comment]
@TeoTwawki It may not be coded that way in DSP, but on retail, you just need to last the entire fight without dying to win.  It's definitely that way on this server as well, because I beat the maat fight on Ezra like that.

**Comment by R3P0FFXI** [comment]
@Samikana we know how it is supposed to work it is currently broken on DSP that is what we are saying, its a DSP issue there is nothing we can do for this until DSP has fixed the issue.

**Comment by TeoTwawki** [comment]
@Samikana see the above issue r3 linked above? I don't care what retail does, its not working on Darkstar.

**Comment by TeoTwawki** [comment]
I worked out a fix in darkstar, just needs them to merge it and it can be in legions next batch of dsp updates.

**Comment by TeoTwawki** [comment]
Should be resolved next time we get DSP updates (right about when we are ready to update client) https://github.com/DarkstarProject/darkstar/pull/3555

**Comment by TeoTwawki** [comment]
Its in now
