### ISSUE TITLE
Ishi crafting skill transfer

### ISSUE THREAD

**Issue by ishi124** [LegionDark/Issues#1223]
**Date & Time**: 
11/09/2016 8:41 pm

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
ishi

**Nation**: 
sandy

**Job(level)/Sub Job(level)**: 
99 blue/49 dnc

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
![ishi](https://cloud.githubusercontent.com/assets/23370115/20161805/e2817d26-a6be-11e6-86dc-9c0212ef6aac.PNG)

**Comment by Genesis-Legion** [comment]
Craft Transferred
