### ISSUE TITLE
Morta Has no drop list.

### ISSUE THREAD

**Issue by Dalkiel81** [LegionDark/Issues#1224]
**Date & Time**: 
November 9, 2016 7:30 GMT

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: 
Dalkiel

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
Blu99/rdm49

**NPC or Monster or item Name**: 
Morta

**Zone name**: 
 Aydeewa Subterrane

**Coordinates (use `$where`)**: 
X: 280, Y: 1, Z: 396 
 X: 441.07, Y: -26.85, Z: 396.726 
These are from using monster tool on website, there was 2 listings for morta

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
According to monster tool, Morta has no drops listed.. he did yesterday however.

**Comment by R3P0FFXI** [comment]
@Dalkiel81 there was an error in the SQL it has been fixed and will be pushed next maint.

**Comment by R3P0FFXI** [comment]
@Dalkiel81 Issue resolved in Maint Yesterday
