### ISSUE TITLE
cant get the Hyacynth Stratum  KI   and lost ashen III KI

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#1225]
**Date & Time**: 11/10/2016

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Qigang

**Nation**: sand

**Job(level)/Sub Job(level)**: 99war/49sam

**NPC or Monster or item Name**: 
Owain

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 

![qq 20161110161628](https://cloud.githubusercontent.com/assets/13742980/20169187/10466ca6-a761-11e6-962c-0af943a8b16d.png)

**Comment by qiganggang** [comment]
![qq 20161110190951](https://cloud.githubusercontent.com/assets/13742980/20174559/4cdd25d4-a779-11e6-9e60-741d03ccd30f.png)
lost ashen iii KI

**Comment by simthra** [comment]
How does one get to have the amber abyssite without the hyacinth one? And why Amber is listed twice: I and II ? Weird.

**Comment by qiganggang** [comment]
me up ashen II to ashen III     pop ashen III NM lost KI

**Comment by simthra** [comment]
OK; and what about amber I AND amber II ?

**Comment by TeoTwawki** [comment]
> How does one get to have the amber abyssite without the hyacinth one? And why Amber is listed twice: I and II ? Weird.

@simthra its because qiganggang has hit many bugs and in the past GMs mishandled fixing him several times over.

**Comment by TeoTwawki** [comment]
@qiganggang I'll take a look soon as I can

**Comment by qiganggang** [comment]
what time help fix?

**Comment by qiganggang** [comment]
:<

**Comment by TeoTwawki** [comment]
Have some patience, I have other things I have to deal with too

**Comment by qiganggang** [comment]
ok  i wait you

**Comment by TeoTwawki** [comment]
I've been having trouble syncing up our schedules, just want to let you know I haven't forgotten you and also that I intend to give the Ashen Stratum line the same treatment I did the Hyacinth line and will fix you up during that if I don't catch up with you in game before then - there won't be anymore losing KI or repeating tier when I finish.

**Comment by TeoTwawki** [comment]
Finally caught up with player, closing issue now. Will still be overhauling voidwatch stuff soon.
