### ISSUE TITLE
your crystal ball quest not working 

### ISSUE THREAD

**Issue by salazer** [LegionDark/Issues#1227]
**Date & Time**: 11/10/16 9:40pm est.

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Emel

**Nation**: bastok

**Job(level)/Sub Job(level)**: thf99/dnc49

**NPC or Monster or item Name**: rockwell pool,Divination Sphere

**Zone name**: Maze of Shakhrami

**Coordinates (use `$where`)**: -21,-12,180, rockwell

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: the quest call for me to trade a Ahriman Lens to rockwell  pool i trade but nothing happens i go back to speak to npc Kurou-Morou - Lower Jeuno (I-7) he say nothing about quest this time i get another lens and trade again nothing happens i have quest in current for jeuno i read i should get message i submerged lens in pool but i get nothing but there is nothing out of the ordinary here

**Comment by TeoTwawki** [comment]
You are supposed to wait a day. If retail dropped that requirement, DSP didn't get the memo.

**Comment by R3P0FFXI** [comment]
@salazer Please advise if this is still an issue

**Comment by salazer** [comment]
issue closed
