### ISSUE TITLE
Kadraeth the Hatespawn Doesn't drop KI

### ISSUE THREAD

**Issue by Dalkiel81** [LegionDark/Issues#1228]
**Date & Time**: 
November 10, 2016 11:45 pm gmt

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Dalkiel

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99MNK/49WAR

**NPC or Monster or item Name**: 
Kadraeth the Hatespawn (NM)

Pulsating soulflayer beard (key item)
**Zone name**: 
Abyssea-Vunkerl

**Coordinates (use `$where`)**: 
X: -475, Y: -40, Z: -280 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
I was tryin to farm KI's to get Atma of the Minikin Monstrosity, but this NM doesnt seem to give a KI at this time.

The KI is Pulsating soulflayer beard.

**Comment by R3P0FFXI** [comment]
@Dalkiel81 this does drop KI you just have very bad luck, I just confirmed the KI code is in the script still

**Comment by TeoTwawki** [comment]
Actually the mob has the wrong name - script and database don't match. So his script never executes so he can't drop..This is because someone got the name wrong in darkstar and someone in legion fixed it in the database but used the DSP name in script. Pushing a fix momentarily.

**Comment by TeoTwawki** [comment]
Should work now.
