### ISSUE TITLE
Dynamis - Jeuno

### ISSUE THREAD

**Issue by Strafeous** [LegionDark/Issues#123]
**Date & Time**:  6/28/15 at 4:30pm
**Frequency**: Happened once, dced, can't log back in; shows characters online
**FFXI Client Version**: Can't login, but it's the version before the latest.
**Character Name**: Strafeous, Megamoo, Megastrafe, Megameow
**Race**: Elvaan, Hume, Mithra, Mithra
**Main Job**:PLD, SAM, BRD, WHM
**Sub Job**:THF, WAR, WHM, RDM
**Area & Coordinates**: Dynamis - Jeuno after pulling an NPC
**Party or Solo**: Party
**NPC Name**: NPC
**Monster Name**: NPC
**Steps To Reproduce The Issue**: Pull an NPC in Dynamis - Jeuno

**Comment by R3P0FFXI** [comment]
Dynamis Server crashed rebooted
