### ISSUE TITLE
Wingcutter+1

### ISSUE THREAD

**Issue by Sorenishii** [LegionDark/Issues#1230]
**Date & Time**: 11/10/2016

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Soren

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99thf/49dnc

**NPC or Monster or item Name**: Isarukitsck

**Zone name**: Uleguerand Range

**Coordinates (use `$where`)**: N/A

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/21350/wingcutter-1

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Tried to equip the Wingcutter+1 that drops from Isarukitsck on my lvl 99thf but it will not equip. It does absolutely nothing, even tried to equip it through gearlock, but will not equip to thf what so ever, not sure if it will equip to a 99 nin as I do not have a 99 nin, but will not for thf.

**Comment by Heepster03** [comment]
Tested for Ninja. Same result, not equipping,

**Comment by R3P0FFXI** [comment]
@Sorenishii Issue resolved in Maint Yesterday
