### ISSUE TITLE
Can't get my abyssite or voidstone from voidwatch npc

### ISSUE THREAD

**Issue by warlord1352** [LegionDark/Issues#1231]
**Date & Time**:11/11/16 7:30pm pst

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Bumblebeeman

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99sam/war

**NPC or Monster or item Name**: Voidwatch Officer

**Zone name**:  Bastok Markets

**Coordinates (use `$where`)**: D-11

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Tried re-logging to see if that would remedy and still saying I'm not "high enough rank" or whatever.

**Comment by PikaFox** [comment]
Did you complete the first few WotG missions and completely register with a nation in the past? (im assuming you mean for your first time)

**Comment by warlord1352** [comment]
Yes I did. And sorry, I did have a screenshot of it but for some reason its not in my screeenshot folder now. Any way yes I completed everything up to mission 3.

**Comment by TeoTwawki** [comment]
Check keyitems for Adventurers certificate.
> "Voidwatch Officer: I'm sorry, but only certified adventurers may participate in Voidwatch Ops."
> "Voidwatch Officer: Serve your country well, and your rank is sure to improve."

This is the only condition under which he mentions rank at all.

**Comment by warlord1352** [comment]
uuuuuuuughhhhh.....so I have to have that. I am only rank 1 on this character soooooo....I guess that means I am doing some rank missions =/. Thanks @TeoTwawki !

**Comment by TeoTwawki** [comment]
Yep gotta get rank 3 where it will give that KI. Also have to have joined one of the 3 nations in the Shadowreign era (WotG army) and be on a job 75 or higher when talking to him. WotG stuff is coded just enough to join, but not many of the quest/mission work after that. I know San d'Oria is join-able. The other 2 should as well be but I have not personally tried them.
