### ISSUE TITLE
Itzpapalotl abby- attohwa

### ISSUE THREAD

**Issue by sucidaldeathtar** [LegionDark/Issues#1232]
**Date & Time**: 
11/12  1045am

**FFXI Client Version (use `/ver`)**: 
30161004-1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30161004-1

**Character Name**: 
Sucidaldeath and alts

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
Thf99/dnc49

**NPC or Monster or item Name**: 
Itzpapalotl

**Zone name**: 
Abbyssea-Attohwa

**Coordinates (use `$where`)**: 
x440 y19 z-208

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Fighting mob slowly with 6 clients  using drk, sam, thf, brd, rdm and blu.  Using sudden Lunge.  After 1st kill repoped him.   During fight multiple client hard lock.  No error message comes up client Freezes.  On other accounts the frozen clients dc. 

Ive repeated this twice on two different days with and without other people in zone.

Its not a normal client error something else  is going on.  Ive never seen it lock the way it did on anyone mob.

**Comment by Heepster03** [comment]
Sudden Lunge or any kind of 'stun' has a random chance to crash your client while it may stun an animation. Spamming said spells just raise the chances for a crash to occur.

**Comment by R3P0FFXI** [comment]
@sucidaldeathtar this is a duplicate issue of the Sudden Lunge error
