### ISSUE TITLE
Cant Complete Windy past 3rd Quest!

### ISSUE THREAD

**Issue by FreakNature** [LegionDark/Issues#1233]
**Date & Time**:   2:29 PM EST.

**FFXI Client Version (use `/ver`)**: Ashita v2 Latest

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: FFXI latest patch.

**Character Name**:  DethBytes

**Nation**:  Sandy (Future) Windy (past)

**Job(level)/Sub Job(level)**:  99DRK/49WAR

**NPC or Monster or item Name**: Dhea) NPC  Not signaling 3rd quest from Rotih in fort Korug (S).
Click nothing happens. Cant continue on wotg missions from any nation.

**Zone name**:  FORT KORUG (S)

**Coordinates (use `$where`)**: X:-64 Y:75 Z:2 (153)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No.

**Steps To Reproduce / any other info**: WOTG MISSIONS 1-3?

**Comment by R3P0FFXI** [comment]
@FreakNature WOTG mission arte not coded past 1-3
