### ISSUE TITLE
Shikohi Import Craft

### ISSUE THREAD

**Issue by Hirakoshi** [LegionDark/Issues#1234]
**Date & Time**: 
11/13/2016 9:09AM EST

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Shikohi

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
THF(75)/No Sub at this time

**NPC or Monster or item Name**: 
N/A

**Zone name**: 
La Theine Plateau

**Coordinates (use `$where`)**: 
X:108 Y:21 Z:-428 (54) 

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Would like to get Clothcraft transferred from my imported data.
![shikohi crafts](https://cloud.githubusercontent.com/assets/23434426/20246285/ade4fabe-a981-11e6-9b4b-6d56e25f704c.JPG)

**Comment by TeoTwawki** [comment]
@LegionDark/gm -*nudge*-

**Comment by Heepster03** [comment]
Putting a 24 hour restriction on this ticket. If no response from player than going to close this ticket.

**Comment by Heepster03** [comment]
Haven't seen player online.

**Comment by Heepster03** [comment]
@Hirakoshi please let us know what time of day and what days of the week we can catch up with you

**Comment by Hirakoshi** [comment]
I will connect tonight. Was out of town.

**Comment by Hirakoshi** [comment]
Should I contact anybody ingame when I'm online?

**Comment by Heepster03** [comment]
Crafts xferred~
