### ISSUE TITLE
Gorger Mobs in Promyvion Dem

### ISSUE THREAD

**Issue by Redaske** [LegionDark/Issues#1235]
**Date & Time**:   Numerous dates/times

**FFXI Client Version (use `/ver`)**:  Same version server is running 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  ^ 30161004_1

**Character Name**:  Redaske don't think this matters

**Nation**:  Hmmm Bastok again don't think this matters

**Job(level)/Sub Job(level)**:  99BLU/47DNC >.>

**NPC or Monster or item Name**:   Gorger

**Zone name**:  Promyvion-Dem

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Simple... fight gorger mob type and watch them NEVER use TP moves.

**Comment by R3P0FFXI** [comment]
@Redaske DSP issue temp fix will be in next update

**Comment by R3P0FFXI** [comment]
@Redaske Issue resolved in Maint Yesterday
