### ISSUE TITLE
Atkorkamuy broken.

### ISSUE THREAD

**Issue by Heepster03** [LegionDark/Issues#1237]
**Date & Time**: 0911 / 11-17-2016

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Halkuras

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99BLU/49RDM

**NPC or Monster or item Name**: Atkorkamuy

**Zone name**: Qufim

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: Atkokamuy not spawnable.

(9:07:18 AM) R3P0FFXI: mb pool ID incorrectly listed in SQL
(9:07:25 AM) R3P0FFXI: 9113 should be 2772

**Comment by TeoTwawki** [comment]
Recheck this, we've had updates.

**Comment by Heepster03** [comment]
Still broken. Can't spawn by command either.

**Comment by TeoTwawki** [comment]
😢

**Comment by R3P0FFXI** [comment]
@Heepster03 Resolved in next update

**Comment by JessLand86** [comment]
Hey you three, I'm going to assume Harvestman in  is bugged similarly to this, I just noticed there wasn't a ticket open for that one. Dunno if it was known or not.

Bhaflau Thickets
X: 398.13, Y: -10.675, Z: 179.169
ID: 16990252

**Comment by TeoTwawki** [comment]
Harvestman was working last update >.<
