### ISSUE TITLE
Friomisi Earring missing from all drops

### ISSUE THREAD

**Issue by Genesis-Nova** [LegionDark/Issues#1238]
**Date & Time**: 7:30 est

**FFXI Client Version (use `/ver`)**: 30161004_1 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30161004_1 

**Character Name**: Genesis

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BLU99/RDM49

**NPC or Monster or item Name**: Friomisi Earring. Used to drop off 
http://legiondark.com/db/monsters/17818048/Ika-Roa.

**Zone name**: Abyssea Grauberg

**Coordinates (use `$where`)**: 157 -29 -212

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/28514/friomisi-earring

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
The Friomisi Earring has been missing from this NM for a very long time. I just noticed that there wasn't a bug report for it and a lot of people are asking about it. It used to drop off Ika-Roa in Abyssea Grauberg. I'm guessing the same thing that happened to the Tamaxchi happened to this.

**Comment by Jessland86** [comment]
Taken care of in Pupdate.
