### ISSUE TITLE
Bastok 9-2 Battlefield

### ISSUE THREAD

**Issue by ghost** [LegionDark/Issues#1239]
**Date & Time**: 
11/18/2016

**FFXI Client Version (use `/ver`)**: 
30161103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
No

**Character Name**: 
Immortality

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99Blu/Rdm

**NPC or Monster or item Name**: 
Zeid?

**Zone name**: 
Throne Room

**Coordinates (use `$where`)**: 
-481 -172 -240 (2)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
After defeating Zeid final CS will not trigger for battlefield.

Zeid is also supposed to only be defeated once in this battlefield. Volker is supposed to join in at ~70% during a CS. Instead Volker joins after you kill Zeid and then you need to re-kill Zeid.

![immortality_2016 11 18_155539](https://cloud.githubusercontent.com/assets/22607214/20446855/a9a0f738-ada9-11e6-8ea3-5ecc3c4f9840.png)

**Comment by R3P0FFXI** [comment]
@JessLand86 this is a known DSP issue the 9-2 battlefields are not coded properly for any nation

**Comment by Jessland86** [comment]
If I recall correctly this was fixed in a previous maintenance. If it's still an issue please open another ticket.

**Comment by TeoTwawki** [comment]
I don't think we got the fix from dsp in till recently, but yeah its fixed.
