### ISSUE TITLE
tantra cyclas +1 not obteined

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#124]
**Date & Time**: 28/06/15 6:52pm CST
**Frequency**: once
**FFXI Client Version**:30150508_8
**Character Name**:itachioax
**Race**:hume
**Main Job**:mnk
**Sub Job**: dnc
**Area & Coordinates**:Port Jeuno
**Party or Solo**: party
**NPC Name**:Moogle (next to Joachim)
![img_20150628_184747](https://cloud.githubusercontent.com/assets/12620527/8398921/086ba722-1dc8-11e5-8aa5-285e4ce86826.png)

**Monster Name**:none
**Steps To Reproduce The Issue**:
1. i bought Tantra cycla from first moogle,
2. traded 10 tandra seal body and Tantra cyclas to the second moogle
3. got message... Obteined: Tantra cyclas +1 then i check my inventory and doesnt get anything, try to sort inventory and nothing, i took pictures.
![Uploading img_20150628_184747.png…]()
![img_20150628_184752](https://cloud.githubusercontent.com/assets/12620527/8398922/08975c64-1dc8-11e5-8df5-b608563f1b57.png)
![img_20150628_184755](https://cloud.githubusercontent.com/assets/12620527/8398923/089b31f4-1dc8-11e5-88f9-9346bf0c93cf.png)

**Comment by R3P0FFXI** [comment]
your inventory is full thats why you didnt get the item

**Comment by itachioax** [comment]
no, it wasnt

**Comment by TeoTwawki** [comment]
Actually it appears you were (I'm not just going by your screenshot) but the script fails to actually check for that so it'll just eat the trade while giving nothing, when it should be displaying the message for that. Looks like Loki never went back to changed those moogles in port.

**Comment by TeoTwawki** [comment]
A GM will get with you in game to get you fixed up, and when Loki gets back from vacation he can correct his moogles.

**Comment by R3P0FFXI** [comment]
User has been given item 11185 Tantra Cyclas +1

**Comment by itachioax** [comment]
ty so much =D

**Comment by Loki79** [comment]
Fixed remaining trials to check for available slot count.
