### ISSUE TITLE
Sailfi Belt +1 Missing stats

### ISSUE THREAD

**Issue by Dalkiel81** [LegionDark/Issues#1240]
**Date & Time**: 
November 18, 4:30 pm gmt

**FFXI Client Version (use `/ver`)**: 

30161004_1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Dalkiel

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
Mnk99/war49

**NPC or Monster or item Name**: 
Sailfi Belt +1

**Zone name**: 
N/A

**Coordinates (use `$where`)**: 
N/A

**ffxiah.com link (for items issues only)**: 
[Sailfi Belt +1](http://www.ffxiah.com/item/28428/sailfi-belt-1)

**Multi-boxing? (multiple clients on same connection)**: 
N/A

**Steps To Reproduce / any other info**: Stats are missing from Sailfi Belt +1. When you equip it, there is no added attack.

**Comment by R3P0FFXI** [comment]
@Dalkiel81 Unity Ranking: Attack+10～15 this belt is coded correctly as Unity mods do not exist in DSP
