### ISSUE TITLE
Castle Zvahl Treasure Chest

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1241]
**Date & Time**: 
11/19/2016 08:44

**FFXI Client Version (use `/ver`)**: 
1103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
No

**Character Name**: 
Immortality

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99Thf/Dnc

**NPC or Monster or item Name**: 
Treasure Chest

**Zone name**: 
Castle Zvahl Baileys

**Coordinates (use `$where`)**: 
-19 -20 69 (35)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/1038/zvahl-chest-key

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Traded Zvahl Chest Key to Treasure chest and it does not open. Click on chest and it states a Coffer key is required to open.

![immortality_2016 11 19_084316](https://cloud.githubusercontent.com/assets/22607214/20455898/fec6bf14-ae34-11e6-98b2-4d51e5a957b8.png)

**Comment by R3P0FFXI** [comment]
@JessLand86 you are on the incorrect client version you updated to current retail.

**Comment by TeoTwawki** [comment]
actual its this: https://github.com/DarkstarProject/darkstar/issues/909

**Comment by ffxijuggalo** [comment]
Hey guys, just fixed this and going to pr to dsp. Looks like it was just a typo in Bailey's treasure_chest.lua
Lol go figure.
