### ISSUE TITLE
Character Transforming when I interact with objects

### ISSUE THREAD

**Issue by hirovitality** [LegionDark/Issues#1242]
**Date & Time**: 
11/20/2016

**FFXI Client Version (use `/ver`)**: 
30161103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
no

**Character Name**: 
Hope

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
RDM(53)/DNC(26)

**NPC or Monster or item Name**: 
null

**Zone name**: 
all

**Coordinates (use `$where`)**: 
X:453 Y:-35 Z:171 (27)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
Whenever I interact with anything in the world, my character transforms into a male version, and my nameplate disappears. As well as other player's names do not show up.

**Comment by hirovitality** [comment]
I'm trying to reinstall to see if anything changes.

**Comment by R3P0FFXI** [comment]
@hirovitality did reinstalling fix your issues?

**Comment by TeoTwawki** [comment]
make new issue if you still have problems.
