### ISSUE TITLE
Please apply Cooking skill to Character

### ISSUE THREAD

**Issue by ffxiphoenix** [LegionDark/Issues#1243]
**Date & Time**: 21-11-2016

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Enko

**Nation**: Windurst

**Job(level)/Sub Job(level)**: BST 84/DNC 42

**NPC or Monster or item Name**: NA

**Zone name**: NA

**Coordinates (use `$where`)**: NA

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Please could I have my Cooking (100) applied to my Char. Screnie is in my transfer application

Many thanks

**Comment by ffxiphoenix** [comment]
My application is here btw

http://legiondark.com/forums/viewtopic.php?f=37&t=1820

**Comment by R3P0FFXI** [comment]
@LegionDark/gm can someone please get with player and arrange a time to have crafts imported

**Comment by Heepster03** [comment]
Haven't seen this player online recently.

**Comment by Heepster03** [comment]
Haven't seen player online.

**Comment by TeoTwawki** [comment]
@ffxiphoenix please let us know what time of day and what days of the week we can catch up with you

**Comment by R3P0FFXI** [comment]
@ffxiphoenix please contact one of us ASAP so we can get this resolved for you.

**Comment by Heepster03** [comment]
@ffxiphoenix I was logging on my GM character to do your xfer for you. But you logged off within like 5 minutes of asking for a GM.

**Comment by ffxiphoenix** [comment]
Apologies, as no-one answered I assumed that there were no GMs available to assist me.

**Comment by Heepster03** [comment]
I'm almost always online. I'm afk now but ill bbl

**Comment by TeoTwawki** [comment]
Ok this has gone long enough, @ffxiphoenix please set up an appointment. post some dates and times you are available. I will be closing this issue if we don't hear back from you soon, and if need be you can make a new issue. But I don't want this buried and stagnant where nobody on staff will see it.

**Comment by TeoTwawki** [comment]
@ffxiphoenix if you come back and see this and still want help, open a fresh ticket.
