### ISSUE TITLE
Successful Steal from Maat does not get the win

### ISSUE THREAD

**Issue by barnabyjoneshd** [LegionDark/Issues#1245]
**Date & Time**: 4:38 CST 11/21/2016 

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30161004_1

**Character Name**: Barnabey

**Nation**: Windurst

**Job(level)/Sub Job(level)**: THF70/DNC35

**NPC or Monster or item Name**: Maat

**Zone name**: Waughroon Shrine

**Coordinates (use `$where`)**: I did not retrieve this information.

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Successfully Steal from Maat for the level 70 THF limit break quest
![barnabey_2016 11 21_161803](https://cloud.githubusercontent.com/assets/23644609/20504520/7e7d72b4-b00d-11e6-9b56-ff3b67871f4e.png)

**Comment by TeoTwawki** [comment]
DSP broke it

**Comment by barnabyjoneshd** [comment]
oh ok, i was unaware, thank for the update. I assume I'll just find another way to beat him :)

**Comment by TeoTwawki** [comment]
or wait till gets fixed. no eta could be real soon or could take weeks (I dunno if/when I will have time to look at it, or someone on their end fixes)

thf and whm were the "easy" Maat fighst and both busted atm.

**Comment by TeoTwawki** [comment]
I worked out a fix in darkstar, just needs them to merge it and it can be in legions next batch of dsp updates.

**Comment by barnabyjoneshd** [comment]
Oh wow that was unexpected, you are the man teo, ill keep an out for that update then

**Comment by barnabyjoneshd** [comment]
Thanks for the update

**Comment by TeoTwawki** [comment]
Should be resolved next time we get DSP updates (right about when we are ready to update client) https://github.com/DarkstarProject/darkstar/pull/3555

**Comment by barnabyjoneshd** [comment]
Great, thanks for letting me know, any idea when the updates are going out?

**Comment by TeoTwawki** [comment]
dsp is on the old client itself still. no idea when it'll be ready but thats when legion will be looking to grab updates because its expected to be "soon".

**Comment by TeoTwawki** [comment]
Should work now
