### ISSUE TITLE
Water and Lightning Ore

### ISSUE THREAD

**Issue by Sorenishii** [LegionDark/Issues#1246]
**Date & Time**: 11/21/2016

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Soren

**Nation**: Bastok

**Job(level)/Sub Job(level)**: THF99/DNC49

**NPC or Monster or item Name**: Water Elemental & Lightning Elemental

**Zone name**: N/A

**Coordinates (use `$where`)**: N/A

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/1259/lightning-ore   http://www.ffxiah.com/item/1260/water-ore

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: I was farming in Sky for elemental ores. I checked the item tool, and the only mobs that drop water ore is water elementals in Jugner Foreest, and only 2 NMs in Abyssea drop lightning ore and no elementals at all drop them.

**Comment by R3P0FFXI** [comment]
@Sorenishii this is resolved in the next update
