### ISSUE TITLE
didnt get ornate fragment from animated dagger

### ISSUE THREAD

**Issue by warlord1352** [LegionDark/Issues#1247]
**Date & Time**: 9:10am pst 11/22/16

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Oscar

**Nation**: bastok

**Job(level)/Sub Job(level)**: 99thf/dnc

**NPC or Monster or item Name**: Animated Dagger

**Zone name**: Dynamis - Xarcabard

**Coordinates (use `$where`)**: 153; -24; -235 (188)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: I looked up first on ffxi wiki the guide I've been using to follow and said its 100% drop rate, then I double check on our website to check it drops it and says 100% as well. Maybe I haven't done something but I thought it would've dropped.

**Comment by PikaFox** [comment]
You need to kill the mobs required to spawn yin and yang. The fragment will not drop until you get the message saying the souls trapped in dynamis have been released or something similar.
