### ISSUE TITLE
Stuck on Airship to Kazham

### ISSUE THREAD

**Issue by mikegillis677** [LegionDark/Issues#1249]
**Date & Time**: 2016-11-22 06:55pm Central Time

**FFXI Client Version (use `/ver`)**: 30161103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30161004_1

**Character Name**: Eldil

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BLK (48) / WHM  (24)

**NPC or Monster or item Name**: 

**Zone name**: Airship (Jeuno -> Kazham)

**Coordinates (use `$where`)**: X:0 Y:1 Z:-21 (190)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: I boarded the airship to Kazham to do the Ninja and Samurai quests.  When the airship arrives in either Jeuno or Kazham, the screen fades to black, but does not load the next zone.

**Comment by R3P0FFXI** [comment]
log out fully reset your character via the website and try again @mikegillis677

**Comment by mikegillis677** [comment]
Thanks
