### ISSUE TITLE
Kutharei unaccesable Aby-Misareau gate wont open

### ISSUE THREAD

**Issue by Alizoutim** [LegionDark/Issues#125]
**Date & Time**: 6/29/2015 1:30 p.m est
**Frequency**:    Always
**FFXI Client Version**: 30150508_5
**Character Name**: Alizoutim
**Race**: TaruTaru
**Main Job**: Blu
**Sub Job**: Rdm
**Area & Coordinates**:  Kutharei : X: -146.279, Y: -31.324, Z: -316.425   
                                       Dilapidated Gate: x: 259 y:9 z:-438 (77)
**Party or Solo**: both
**NPC Name**:  Dilapidated Gate 
**Monster Name**: Kutharei
**Steps To Reproduce The Issue**:
1- Zone into Abyssea-Misareau
2- Take conflux 7 to get to G-11 for dilapidated gate
3- click on the gate  (nothing Happen)
Link for Kutharei : http://ffxiclopedia.wikia.com/wiki/Kutharei

**Comment by TeoTwawki** [comment]
@Loki79 didn't the 2 of us decide on an NPC target at the gate pos that clicking would player:setPos() them to the other side after wallhacking our way around there and seeing there was a huge gulf of empty space between the 2 sides of the gates?

**Comment by TeoTwawki** [comment]
@Loki79 if door is already targettable I just need the pos's for both sides, and the npc name so I can script. If its not targetable, we need to place the NPC ***exactly*** at the door positions (all 4) and make sure it's in a spawned state at server start in the npc list. Coulda swore we did the fetching pos's part but I don't have any notes for it.

**Comment by Loki79** [comment]
@TeoTwawki yeah i think we did...  ill look at this tonight if i have time.

**Comment by Loki79** [comment]
ok took a look at this.  the script names didnt match the npc names.  corrected.  All should be fine now
