### ISSUE TITLE
Unable to play on transferred character.

### ISSUE THREAD

**Issue by Miscbox** [LegionDark/Issues#1250]
**Date & Time**: 
1:09 am EST - 11/23/2016

**FFXI Client Version (use `/ver`)**: 
N/A 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
N/A

**Character Name**: 
Izayoi

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
75 NIN / no sub

**NPC or Monster or item Name**: 

**Zone name**: 
Unknown, probably residential area.

**Coordinates (use `$where`)**: 
N/A

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
N/A

**Steps To Reproduce / any other info**: 

Did a transfer on the night of 11/22/2016 and upon trying to login was stuck on "downloading data" until ultimately timed out. Tried to use unstuck tool to move character and attempt to log in, also tried to have a friend log in and attempt to move the character, neither of which worked. Friend was saying that a GM said it's possible that it was a corrupted transfer? Not sure, will post this in the transfer thread in question as well.

**Comment by TeoTwawki** [comment]
I have 2 questions.

If you have any other characters, how many are on this same account?

Are you able to log in any other characters on any account?

**Comment by Heepster03** [comment]
Used bring command to pull them from their MH and now they appear to be working now.
