### ISSUE TITLE
Character no longer on Character List

### ISSUE THREAD

**Issue by ragecools** [LegionDark/Issues#1251]
**Date & Time**: 11-23-2016 12:31 AM PST

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Cools

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99SAM/49WAR

**NPC or Monster or item Name**: N/A

**Zone name**: N/A

**Coordinates (use `$where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: Yes had my brothers accounts sitting inactive.

**Steps To Reproduce / any other info**: Character is completely gone from character selection screen. Happened after I timed out from the server.

**Comment by atom0s** [comment]
Log out of all characters / accounts and try again. Could just be a hiccup from dual-boxing.

**Comment by TeoTwawki** [comment]
how many chars did you have on the account?

**Comment by ragecools** [comment]
Just closed all and restarted computer still not there.

On this account there is 4.

**Comment by TeoTwawki** [comment]
ok thats why, there is supposed to be a limit of 3 per account here to avoid a bug. Earlier today I saw the limiter missing and reinstated it. I can relocate one to an alternate account for you, just need the account name to move it to.

Its our fault you were even able to place 4 on one account, and I apologize for the trouble.

**Comment by ragecools** [comment]
Ok deleted off a mule. We are all good now phew! +1:

**Comment by TeoTwawki** [comment]
oh, that works too.
