### ISSUE TITLE
VW Ashen III KI

### ISSUE THREAD

**Issue by alannor** [LegionDark/Issues#1254]
**Date & Time**: 
2016/11/26

**FFXI Client Version (use `/ver`)**: 
current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Free

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
NIN99

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Unable to upgrade Ashen III KI afyer killing the 3 VWNMs

Have tried logging off all characters and logging on just one. Still not working

**Comment by TeoTwawki** [comment]
I'll be rebuilding the entire Ashen Stratum Line like I did the Hyacinth soon. I take care of you when I get that done.

**Comment by alannor** [comment]
Thanks Teo, really appreciated

**Comment by TeoTwawki** [comment]
my apologies I got severely delayed on that project. will try to get with you in game soon.
