### ISSUE TITLE
Ogbunabali TP move "Norn Arrow" causing crashes

### ISSUE THREAD

**Issue by MusashiZetsuei** [LegionDark/Issues#1255]
**Date & Time**: 
10:07 pm est

**FFXI Client Version (use `/ver`)**: 
Current -  30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

 30161004_1
**Character Name**: 

Musashi
**Nation**: 

Bastok
**Job(level)/Sub Job(level)**: 
99sam/49dnc

**NPC or Monster or item Name**: 

Ogbunabali
**Zone name**: 

Maze of Shikrami
**Coordinates (use `$where`)**: 

Voidwatch spawn point (windy tier 2)
**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

Yes
**Steps To Reproduce / any other info**: 

The npc uses norn arrow, people start crashing. happened multiple times over the course of the fight, each time after norn arrow,. ashen, me, arkoo all dc'd during norn arrow multiple times, not all at once but each time norn arrow and game client would generate a crash error for bootloader.

**Comment by R3P0FFXI** [comment]
@MusashiZetsuei This was an incorrect entry and will be resolved in the next maint. window.

**Comment by R3P0FFXI** [comment]
Should be fixed now
