### ISSUE TITLE
Voidwatch nm Invisiable but popped Ordelles caves

### ISSUE THREAD

**Issue by sucidaldeathtar** [LegionDark/Issues#1256]
**Date & Time**: 
Nov 27 2016 5:30pm est

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30161004_1

**Character Name**: 
Sucidaltank

**Nation**: 
sandy

**Job(level)/Sub Job(level)**: 
blu99/49rdm

**NPC or Monster or item Name**: 
Krabimanjaro

**Zone name**: 
Ordelle's Caves

**Coordinates (use `$where`)**: 
X:-109 y:31 z:229 (1208)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Rift is not targetable so I spawned VW at another rift and mob is now popped invisible and not targetable.  I see the rift and mob on wide scan right where I'm at (G-8).

**Comment by Heepster03** [comment]
Not invisible. I see the NM at the rift. Having player come see if he sees it.

**Comment by Heepster03** [comment]
Closing, player at wrong rift.
