### ISSUE TITLE
Chains of Promathia - Sacrium

### ISSUE THREAD

**Issue by Miscbox** [LegionDark/Issues#1258]
**Date & Time**: 
12/1/2016  & 3:28 pm

**FFXI Client Version (use `/ver`)**: 
30161103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
No

**Character Name**: 
Izayoi

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99SAM/WAR37

**NPC or Monster or item Name**: 
Wooden Gate

**Zone name**: 
Sacrium

**Coordinates (use `$where`)**: 
N/A - Not there atm anymore.

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
Yes, I was.

**Steps To Reproduce / any other info**: 

Was doing the mission "The Secrets of Worship," received the cut-scene requesting that I get the Key item "Reliquiarium Key." Killed the ghost NM and got the key, proceeded to try and get the final cut-scene and did not, it just asked me to use the key to open the door and proceed into the room. Did this all on an alt to find out if it was myself or the mission and it completed properly. 

Might need help with a push to the next mission or something :<. Thanks!

**Comment by PikaFox** [comment]
Promathia Status is 3. Assuming im reading the script correctly, this means you still need to spawn the ghost NM and kill him. See if you can find a spawn for him that lets you spawn him and kill him.

**Comment by Miscbox** [comment]
Hey, thanks for the reply! I did actually attempt to go around and pop the ghost NM after I progressed on my alt but didn't on my main. I also actually have the key already too? I can try one more time once I get the chance and post again.

**Comment by Miscbox** [comment]
Alrighty, so I got the chance to go back and got this message: https://gyazo.com/e9fc728a2f6ce14ae2038afa2ff7221c



there are 6 drawers in all and the one that I clicked twice as shown "The drawer is jammed shut" is the one that it -should- come out of. I already have received the key and as such when I click the door, instead of getting the cut-scene to put me on the next mission, I receive: https://gyazo.com/5d3c6fc6e9ecac9c2a99c436bc32e523

I had received the prior cut-scene requesting that I obtain said key > did ghost > came back and am stuck here now: https://gyazo.com/35e594b381a4b75f7e161f2217dffdf5


Added bonus it also has shown up in the completed log: 

https://gyazo.com/4278e8f3d19f443bb48f0055c6b709f7

**Comment by TeoTwawki** [comment]
Sounds like typical bug brought on by multibox, and going to have to manually adjust player to fit requirements for the step that isn't firing.

**Comment by Miscbox** [comment]
Alrighty.

**Comment by TeoTwawki** [comment]
Pikafox, I choose you! -*whips a pokeball at players feet*-

**Comment by PikaFox** [comment]
Set PromathiaStatus to 4, player got CS. Player can reopen if issues continue.
