### ISSUE TITLE
Trying to talk to Halver after killing Shadow Lord

### ISSUE THREAD

**Issue by Arlux** [LegionDark/Issues#126]
**Date & Time**:  1:30 PM
**Frequency**: When i try to talk to Halver after defeating the Shadow Lord and receiving Shadow Fragment i am unable to speak to Halver to finish the mission
**FFXI Client Version**: ver. 30150508_8
**Character Name**: Arlux
**Race**: Hume
**Main Job**: Paladin
**Sub Job**: Warrior
**Area & Coordinates**:     Chateau d'Oraguille   x:2 y:0 z:0
**Party or Solo**: Solo and Party
**NPC Name**: Halver
**Monster Name**: None
**Steps To Reproduce The Issue**: After defeating the Shadow Lord and receiving the Shadow Fragment i am unable to speak to Halver to continue on with the mission.

**Comment by R3P0FFXI** [comment]
Halver sucks Ill look at this when im home Arlux see where your stuck

**Comment by Arlux** [comment]
So i want to leave a detail i forgot to mention. After defeating the Shadow Lord and getting his Fragment i went and talked to the Prince Trion in his room which lead to a cut scene where i ended up talking to the King. After that i went and tried to talk to Halver and have been stuck since.

 I will also add i went to Norg and received the cutscene where those guys from Jueno (Kam'lanaut and friend) released the five Crystal Warriors and tried to kill me only to be saved by Lion.

**Comment by R3P0FFXI** [comment]
Does it allow you to move on to Rank 6 Missions? If you can start ZM missions then everything may be ok.

**Comment by Arlux** [comment]
It doesn't let me start Dynamis  but i can do Zilart.

 Also when i talk to the guard he doesn't let me get anymore quests/missions. Says i have to complete my current mission to continue.

**Comment by Loki79** [comment]
@R3P0FFXI  whre you at on this?  Is it resolved?

**Comment by Arlux** [comment]
Yes it was resolved. A GM ended up talking to me in game and now i finished
that quest chain and now am Ranked 6

On Thu, Jul 16, 2015 at 7:39 PM, Keegan Carr <notifications@github.com>
wrote:

> @R3P0FFXI <https://github.com/R3P0FFXI> whre you at on this? Is it
> resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LegionDark/Issues/issues/126#issuecomment-122153563>.
>



-- 
~~Raul Flores, Jr
