### ISSUE TITLE
Legion Anniversary Event

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1260]
**Date & Time**: 
12/3/2016 02:23

**FFXI Client Version (use `/ver`)**: 
30161103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
No

**Character Name**: 
Immortality

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99 Thf/dnc

**NPC or Monster or item Name**: 
Anniversary Moogle

**Zone name**: 
Bastok Markets

**Coordinates (use `$where`)**: 
-255 -12 -71

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Anniversary Moogle is missing from Bastok Markets, verified by other players on matching version.

**Comment by TeoTwawki** [comment]
I fixed them but maint hasn't happened yet. Would have done a separate smaller maint earlier had I realized the event starts before the actual anniversary. Will be extending event and starting maintenance early as a result.

**Comment by TeoTwawki** [comment]
Maint is now done, and the moogle is back. Anniversary event will last to December 12th.
