### ISSUE TITLE
Legion Anniversary Event Buff- No effect

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1261]
**Date & Time**: 
12/3/2016 10:33 

**FFXI Client Version (use `/ver`)**: 
30161103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
No

**Character Name**: 
Immortality

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99Thf/Dnc

**NPC or Monster or item Name**: 
Anniversary Moogle

**Zone name**: 
Windurst Waters

**Coordinates (use `$where`)**: 
-50 -5 217 (90)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Moogle gave the buff of a costume (Cait Sith) and 30 minutes of flee. Flee buff does not actually give flee movement speed. Using flee on THF while the buff is active overrides the anniversary buff and actually enhanced movement speed.

**Comment by JessLand86** [comment]
Cancelling the costume did not change the movement speed either.

**Comment by TeoTwawki** [comment]
It actually does have it, but its a ridiculousness mall amount nobody would even notice.
Nobody is going to care about +5 move speed...Lets make that 50 >.>

**Comment by TeoTwawki** [comment]
p.s. costume is a separate effect the wya this was coded, I have no idea what the original intent was, not my code..

**Comment by TeoTwawki** [comment]
Hotfix'd !

**Comment by JessLand86** [comment]
Thanks Teo!

**Comment by TeoTwawki** [comment]
You are welcome, and thanks for reporting it! :)
