### ISSUE TITLE
Windurst VW T2 NM

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#1262]
**Date & Time**: 13/3/2016

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: blu99/rdm49

**NPC or Monster or item Name**: Ogbunabali

**Zone name**: Maze of Shakarami

**Coordinates (use `$where`)**: x:-285 y:0 z:-115 (211)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: spawned the nm and wiped.  When I recovered it wouldn't let me activate voidwatch, the nm was still active.  Only it is invisible and can't be targeted.  I can see the dust on the ground as it moves around.  I've checked back and it's been about 4ish hours now and its still wandering around invisible, untargetable, also unable to pop another nm.

**Comment by R3P0FFXI** [comment]
@LegionDark/gm please despawn NM this wont get fixed until we update the nextupdate branch

**Comment by Heepster03** [comment]
Despawned.
