### ISSUE TITLE
PM6-4 BCNM bugged - One To Be Feared (Airship Battle)

### ISSUE THREAD

**Issue by Spardante** [LegionDark/Issues#1263]
**Date & Time**: 
12/3/16, 5:00P M EST

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30161004_1

**Character Name**: 
Biggie, Small, Tupac, Athie

**Nation**: 
Sandoria, Bastok, Sandoria, Bastok

**Job(level)/Sub Job(level)**: 
WAR, WHM, BLU, WHM

**NPC or Monster or item Name**: 
One to be Feared BCNM

**Zone name**: 
Sealion's Den

**Coordinates (use `$where`)**: 
X:-638 Y:-231 Z:-524 (91)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Was doing PM6-4 mission Airship Battle bcnm.  After winning and beating Ultima, all characters DC'd.  After relogging on and trying fight again, I could no longer pass the Mammet part of the fight.  After all Mammets are killed, it will not teleport me back to the airship where I can move on to the next part.  I tried multiple times and it will not allow me to get passed this part.

After checking the Mission status for each character, they now show "One To Be Feared" as both Current and Completed.  I cannot complete mission and obtain the Ducal Guard Ring reward, or move onto the next CoP mission.

**Comment by Heepster03** [comment]
Alright. I went ahead and check the variables when I was told of the issue. 

The PromathiaStatus variables for the four characters are located at http://imgur.com/a/jT8xP

R3 gave the go ahead to push through as this is flagging as completion, just bugged out due to the DC.

**Comment by Heepster03** [comment]
It's done. 

All that is required is that the player zones to Lufaise Meadows to obtain the CS missed from the bug and be back on track.
