### ISSUE TITLE
Please Add woodworking craft to my char

### ISSUE THREAD

**Issue by suter1980** [LegionDark/Issues#1264]
**Date & Time**:  5/12/2016 10:35am(GMT)

**FFXI Client Version (use `/ver`)**: 30161103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  No

**Character Name**:  Suter

**Nation**:  Sandoria

**Job(level)/Sub Job(level)**: 
paladin99/dancer49

**NPC or Monster or item Name**:N/A 

**Zone name**:  N/A

**Coordinates (use `$where`)**: N/A

**ffxiah.com link (for items issues only)**:  N/A

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Please could you add my woodworking craft skill from my application.
Transfer was completed on 23rd July
![img_20160720_094554](https://cloud.githubusercontent.com/assets/19614946/20881806/04c63036-bad6-11e6-928d-6f2eda6ffdd9.png)

**Comment by R3P0FFXI** [comment]
@LegionDark/gm can someone please contact player in game and setup a time to get crafts imported

**Comment by suter1980** [comment]
have been trying to contact somebody in game to set up a time but have had no luck so last few days now.

**Comment by Heepster03** [comment]
I can work on this later when I get a moment. Sorry, have been busy with finals and such.

**Comment by suter1980** [comment]
when ever u have time is good for me thou i will be on around 7pm GMT ( in around 2hrs 30m from now)
if thats any help

**Comment by Heepster03** [comment]
Crafts xferred.
