### ISSUE TITLE
Dynamis - Buburimu boss doesn't spawn

### ISSUE THREAD

**Issue by PresidentNixon** [LegionDark/Issues#1265]
**Date & Time**: 
12/7/2016

**FFXI Client Version (use `/ver`)**: 
30161103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:
No, its 30161104_1

**Character Name**: 
Nixon

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
BLU99/NIN49

**NPC or Monster or item Name**: 
Apocalyptic Beast
http://legiondark.com/db/monsters/16941057/Apocalyptic_Beast

**Zone name**: 
Dynamis - Buburimu

**Coordinates (use `$where`)**: 
X: 100, Y: -5, Z: 39

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Boss is supposed to be up when you enter zone, it's not. Tried killing all the NMs in the zone and trading the pop item to ??? as written on wiki, that does not spawn it either.

Also unrelated to Bubu but like half the mobs in Dyna Qufim say you can't attack them when you try to engage. That zone is winnable but might as well mention it.

**Comment by TeoTwawki** [comment]
Dynamis on Darkstar is currently styled in the old form before retail changed, and is often buggy to boot. _None_ of the NMs in old-style Dynamis are trade popped. Dynamis won't be updated till enough people nag Darkstar about it or I miraculously get tons of free time to give it a complete makeover just for Legion (don't hold your breath).

**Comment by TeoTwawki** [comment]
@LegionDark/gm one of you guys go see which mobs can't be engaged that this user mentioned, and bug report to darkstar's tracker, pretty please.

**Comment by JessLand86** [comment]
We also had issues with another dyna zone (Qufim) where the boss wasn't up, We solved by everyone exiting the zone and then re-entering to reset the mobs. I can't comment on random other mobs in the zone being un-attackable since we literally just ran in killed the boss and left.

**Comment by PresidentNixon** [comment]
Re entering the zone today seems to have gotten around this. The boss and several other mobs that weren't there yesterday were up now. Mainly made ticket because I thought it was impossible to get Dyna Tavnazia access and since that's not the case it's not a big problem.

**Comment by JessLand86** [comment]
This was fixed in a previous update.
