### ISSUE TITLE
Sorcerer's Ring not working

### ISSUE THREAD

**Issue by yokhai** [LegionDark/Issues#1266]
**Date & Time**: 
12/6/16 - 11:30 PM EST

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Vinsanity

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
BLM99/RDM49

**NPC or Monster or item Name**: 
Sorcerer's Ring

**Zone name**: 
N/A

**Coordinates (use `$where`)**: 
N/A

**ffxiah.com link (for items issues only)**: 
http://ffxiclopedia.wikia.com/wiki/Sorcerer%27s_Ring

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Reduce HP to below 76%, typically "yellow" hp, and compare Elemental Magic spell damage of tier 1 spells on level 1 mobs and you will not find a change. You should see roughly 10% increase in damage delt, this does not occur.

**Comment by R3P0FFXI** [comment]
-- -------------------------------------------------------
-- Sorcerer's Ring
-- -------------------------------------------------------
INSERT INTO `item_latents` VALUES(13289, 28, 10, 2, 76); -- "Magic Atk. Bonus"+10 while HP <76% and TP <100%

@yokhai Sorc Ring Latent is in and functioning as expected
