### ISSUE TITLE
Sushi not giving ACC

### ISSUE THREAD

**Issue by yokhai** [LegionDark/Issues#1267]
**Date & Time**: 
12/6/16 - 11:30 PM EST

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Vinsanity

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
THF99/DNC49

**NPC or Monster or item Name**: 
Sole Sushi +1 / Probably all sushi

**Zone name**: 
N/A

**Coordinates (use `$where`)**: 
N/A

**ffxiah.com link (for items issues only)**: 
http://ffxiclopedia.wikia.com/wiki/Sole_Sushi_%2B1

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
None of the sushi items that I have tested have given the ACC bonus they claim by using /checkparam. Either /checkparam does not take account of the ACC bonus or the item is not working at intended. I do receive the ACC boost from the DEX the food gives me.

**Comment by R3P0FFXI** [comment]
target:addMod(MOD_FOOD_ACCP, 30);

@yokhai this is giving ACC as intended

**Comment by yokhai** [comment]
So is /checkparam not picking up that acc. And it's not just the 30% from the modded food either, the sushi itself should also give 16% which it is not. None of the sushi foods give their ACC, as checked by /checkparam

**Comment by TeoTwawki** [comment]
Currently its normal for foods ACC% bonus to not be calculated into the output display of `/checkparam` The acc applies but you aren't given the value.
