### ISSUE TITLE
ZM4 Unlit Lantern/Rancor Flame

### ISSUE THREAD

**Issue by yokhai** [LegionDark/Issues#1268]
**Date & Time**: 
12/6/16 - 11:30 PM EST

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Vinsanity

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
THF99/DNC49

**NPC or Monster or item Name**: 
Unlit Lantern / Rancor Flame

**Zone name**: 
Den of Rancor

**Coordinates (use `$where`)**: 
X:118 Y:15 Z:-317 (34)

**ffxiah.com link (for items issues only)**: 
http://ffxiclopedia.wikia.com/wiki/Unlit_Lantern
http://ffxiclopedia.wikia.com/wiki/Rancor_Flame

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Trade the Unlit Lantern item to the Altar of Rancor should result in removing the Unlit Lantern and giving you the Rancor Flame item. This does not occur, resulting in the inability to get into the Sacrificial Chamber thus not being able to complete the mission.

**Comment by TeoTwawki** [comment]
Those seem to be the wrong coordinates..? I see the script for the trade is coded.
Check positions `199 32 -280` and `-76 16 -1`

**Comment by yokhai** [comment]
I believe those are the coordinates for the Crimson and Blue Flames. The third, for the Altar of Rancor, is needed to get into the Sacrificial Chamber. I will try the Crimson and Blue to see what happens.

**Comment by TeoTwawki** [comment]
One of them is crimson, but the other one is not blue. The correct one should be where Friar Rush pops if I am remembering correctly.

**Comment by yokhai** [comment]
You are correct. I cannot read maps very well. Thanks for the quick response. Any chance you can look into my closed issue of sushi. I'm still not seeing the acc bonus from the food using /checkparam. 

Thanks again.
