### ISSUE TITLE
Unable to equip Imbodla Necklace in BLU > drop 7Wonder (ACHUKA)

### ISSUE THREAD

**Issue by Squall-Bibi** [LegionDark/Issues#127]
Date & Time: 29/06/2015 
Frequency: always
FFXI Client Version: 30150508_8
Character Name: Squall
Race: Hume
Main Job: BLU 
Sub Job: NIN
Area & Coordinates: all
Party or Solo: solo and party
NPC Name: N/A
Monster Name: N/A
Steps To Reproduce The Issue : i can click it but not equip Imbodla Necklace

**Comment by Squall-Bibi** [comment]
???

**Comment by Loki79** [comment]
Corrected Job mask locally, will fix in dsp as well.
