### ISSUE TITLE
Minervah - Tossed items by mistake - Wicce Coat + 1 / Wicce Gloves +1

### ISSUE THREAD

**Issue by adamviano** [LegionDark/Issues#1270]
**Date & Time**: 
10/12/2016 6AM

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Minervah

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
THF99/DNC49

**NPC or Monster or item Name**: 
NA

**Zone name**: 
Tavnazian Safehold

**Coordinates (use `$where`)**: 
X:0 Y:-22 Z:9 (101)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/26905/wicce-coat-1
http://www.ffxiah.com/item/27059/wicce-gloves-1

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Hello,
I was farming dynamis-buburimu and when i had enough forgotten steps, i zoned out and started sorting the excessive mats and gears i didnt want to keep.
In the process i accidentally tossed 2 pieces of gears: the wicce coat+1 (body) and the wicce gloves +1 (hands) for blm, as the following pictures show it.

![mistake](https://cloud.githubusercontent.com/assets/17102708/21072823/ef54b9a0-be9c-11e6-8770-f7ee12b978d9.PNG)

![mistake 2](https://cloud.githubusercontent.com/assets/17102708/21072867/bae6abaa-be9d-11e6-8135-381ebb16ce84.PNG)

Can i please retrieve these, as the time and effort put into this is considerable?
That would be well appreciated.
Thank you.

**Comment by R3P0FFXI** [comment]
@adamviano we allow a 1 time 1 item restoration if you would like to use your 1 time restoration please let us know which item you want but we will not restore both.

**Comment by adamviano** [comment]
Cant you do for both? that was accidental.
I was sorting out my mats and then i pressed by mistake

**Comment by R3P0FFXI** [comment]
@adamviano We allow a 1 time 1 item restoration

You dropped over 30 items between 6:00 and 6:03 this is not a server issue this is on you not paying attention. SE has the exact same policy on retail. Mistakes happen and because of that we allow 1 item to be restored during the life of your character on the server. To many people have come to us with this exact same issue this policy was enacted back in July due to multiple players claiming they dropped X/Y/Z by accident.

**Comment by adamviano** [comment]
Body

**Comment by R3P0FFXI** [comment]
Restored Wicce Coat
