### ISSUE TITLE
Goldsmith Membership drops after log out

### ISSUE THREAD

**Issue by Devrin9** [LegionDark/Issues#1271]
**Date & Time**: 
12/10/2016 3:46pm MST

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Devrin

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
30PLD/15WAR

**NPC or Monster or item Name**: 
Fatimah
Reinberta

**Zone name**: 
Bastok Markets

**Coordinates (use `$where`)**: 
X:-194 
Y:-6 
Z:-58 (182)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Accept into guild (so guild turn-ins occur)
Log in later in the day or next day and you will have to sign up for goldsmithing again (Even though your goldsmith level has not changed) 

Minor issue unless guild points are lost in the process.

**Comment by TeoTwawki** [comment]
Tested this myself and then reported to DSP https://github.com/DarkstarProject/darkstar/issues/3575

**Comment by TeoTwawki** [comment]
Its not even after logout. I was able to just repeatedly "join" back to back.

**Comment by TeoTwawki** [comment]
This should be fixed now.
