### ISSUE TITLE
"Archmage Petasos" vs "Archmage Petasos +1" : wrong design for HQ hat

### ISSUE THREAD

**Issue by adamviano** [LegionDark/Issues#1272]
**Date & Time**: 
10/12/2016 9:59PM

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Minervah

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
BLM99/DNC49

**NPC or Monster or item Name**: 
NA

**Zone name**: 
Upper Jeuno

**Coordinates (use `$where`)**: 
X: 22 Y: -1 Z: -43 (176)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/26630/arch-petasos
http://www.ffxiah.com/item/26631/arch-petasos-1

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
I went to turn the archmage petasos to an archmage petasos +1, i got a hat with the wrong design and colors.
See the pictures:

NQ hat:
![archmage nq](https://cloud.githubusercontent.com/assets/17102708/21077780/d8f00e0c-bf24-11e6-8fd3-7fdbd600ea32.PNG)

HQ hat:
![archmage hq](https://cloud.githubusercontent.com/assets/17102708/21077782/f35f668e-bf24-11e6-9ec4-d17151cd4ce4.PNG)

**Comment by Samikana** [comment]
Incorrect MID.  I'll fix it.

**Comment by R3P0FFXI** [comment]
Fix submitted to DSP

**Comment by R3P0FFXI** [comment]
@adamviano issue resolved in todays update
