### ISSUE TITLE
Malfeasance has Incorrect Crafting Ingredients

### ISSUE THREAD

**Issue by adamviano** [LegionDark/Issues#1273]
**Date & Time**: 
11/12/2016 5:49AM

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Minervah

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
THF99/WAR49

**NPC or Monster or item Name**: 
N/A

**Zone name**: 
North Sandoria

**Coordinates (use `$where`)**: 
X:183 Y:12 Z:144 (160)

**ffxiah.com link (for items issues only)**: 
https://www.bg-wiki.com/bg/Malfeasance

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Malfeasance in the database has the incorrect recipe, requiring a Scarletite Ingot instead of the **Ormulu Ingot.**

**Comment by R3P0FFXI** [comment]
@adamviano issue resolved in todays update
