### ISSUE TITLE
Jailer of Fortitude

### ISSUE THREAD

**Issue by Lavrik83** [LegionDark/Issues#1274]
**Date & Time**: 
12/11/16

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Lavrik

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
WAR99/SAM49

**NPC or Monster or item Name**: 
Jailer of Fortitude

**Zone name**: 
The Garden of Ru'Hmet

**Coordinates (use `$where`)**: 
X:-43 Y:0 Z:461 (176)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Traded 12 Ghrah M Chips to the ???, but Jailer of Fortitude is not popping.  I've tried it twice and lost both stacks of chips, to no avail.

**Comment by TeoTwawki** [comment]
Fix'd. Position wasn't being set correctly (the NPC that spawns it moves normally, but the Mob position wasn't being updated.).
