### ISSUE TITLE
Jailer Of Faith

### ISSUE THREAD

**Issue by Lavrik83** [LegionDark/Issues#1275]
**Date & Time**: 
12/11/16

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Lavrik

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
WAR99/SAM49

**NPC or Monster or item Name**: 
Jailer of Faith

**Zone name**: 
The Garden of Ru'Hmet

**Coordinates (use `$where`)**: 
X:-579 Y:0 Z:-646 (218)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
The ??? to trade HQ Euvhi Organ to, to spawn JoF, is giving a debug message stating: 
Debug: Jailer of Faith (qm3.lua)  and nothing happens when organ is traded.

**Comment by TeoTwawki** [comment]
That message has nothing to do with the trade, thats on clicking it. And its there because I was working on this NPC when you happened to click it (had you arrived a few minutes sooner, you'd have seen same issue Jailer or Fortitude had). Try your trade now.
