### ISSUE TITLE
Missing Gil

### ISSUE THREAD

**Issue by Gn3x0n** [LegionDark/Issues#1276]
** Issue: 20 million gil vanished from my possession. When I logged of earlier in the day, I had approx 58mil gil, when I logged back in it was down to 38mil. I did not make any purchases or transfer any funds between characters. Please offer assistance if able

**Date & Time**:  12/10/16, approx 7:00pm est.

**FFXI Client Version (use `/ver`)**: 30161103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  Yes.

**Character Name**: Caramon

**Nation**:  San D'oria

**Job(level)/Sub Job(level)**: Thief 37/Black mage 18

**NPC or Monster or item Name**:  N/A

**Zone name**:  Northern San D'Oria

**Coordinates (use `$where`)**: X:71, Y:0, Z:15 (153)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**:  At the time, Yes.

**Steps To Reproduce / any other info**: N/A

**Comment by atom0s** [comment]
Gil does not just vanish and there has been no restarts or rollbacks of character data. So there is no valid reason for this happening other than you spending it or forgetting your actual gil amount.
