### ISSUE TITLE
request to have salazer's leather craft restored

### ISSUE THREAD

**Issue by salazer** [LegionDark/Issues#1277]
![img_20161112_035546 2](https://cloud.githubusercontent.com/assets/20325695/21139390/a2a05acc-c100-11e6-8625-943faae82e38.png)

**Date & Time**: 12/13/2016 6:50am

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Salazer

**Nation**: Bastok

**Job(level)/Sub Job(level)**: war99/dnc49

**NPC or Monster or item Name**: leather craft level 80

**Zone name**: n/a

**Coordinates (use `$where`)**: n/a

 
**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: I've been meaning to submit this after toon was imported can you please restore salazer's leathercraft level 80 to toon thank you

**Comment by Heepster03** [comment]
I will work on this later when I have a moment and if you're online.

**Comment by Heepster03** [comment]
Crafts xferred.
