### ISSUE TITLE
Ix'Aern DRK not dropping deed of moderation

### ISSUE THREAD

**Issue by alannor** [LegionDark/Issues#1278]
**Date & Time**: 
Dec 13th 22.10 GMT+10

**FFXI Client Version (use `/ver`)**: 
Current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Snow

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
Various 99

**NPC or Monster or item Name**: 
Ix'Aern DRK

**Zone name**: 
SEA

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
YES

**Steps To Reproduce / any other info**: 
Ix'Aern DRK is not dropping deed of moderation, supposed to be 81% drop rate, killed him 4 times with TH+12 and no drops. Hardly to believe its just bad luck...

Also takes 48 Aern organ to pop? Supposed to be only 1?

Thanks

**Comment by adamviano** [comment]
@alannor 
Ix Drk works perfectly fine, and when my team and I farmed it, we had no issue with it. 
Of course it's not 100%, we also had bad lucks, but deeds are dropping as intended.
You've had some really bad luck Alannor, that's it.

**Comment by R3P0FFXI** [comment]
IX Drk is working as intended @alannor

**Comment by simthra** [comment]
I'm too on a bad streak: 0/5 on Ix'drk with TH12; au contraire mnk and drg dropped 12/12 deeds with just TH1. Shoot...

**Comment by PikaFox** [comment]
TH doesnt affect it. Its a 100% drop that is either one or the other. You cant augment 100% drop to any higher.

**Comment by simthra** [comment]
I see; it's just Ix'drk working with this "deed OR vice" thing? Real drop %s  are to be disclosed by chance?
