### ISSUE TITLE
Etherael: Bugged Mog storages.

### ISSUE THREAD

**Issue by p4r4cyt3** [LegionDark/Issues#1280]
**Date & Time**: 2016-12-15 05:25:00

**FFXI Client Version (use `/ver`)**: 30161103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: no

**Character Name**: Etherael

**Nation**: Windurst

**Job(level)/Sub Job(level)**: THF99/

**NPC or Monster or item Name**: After character import, unable to access items in Mog Satchel, Sack, Case, and Wardrobe. May also have invisible items in Mog Wardrobe 2 and normal inventory. When picking up items that drop, they get lost because the game thinks my inventory is full, even though it shows 23/80.

**Zone name**: 
N/A

**Coordinates (use `$where`)**: N/A

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: N/A

**Comment by R3P0FFXI** [comment]
@p4r4cyt3 you need to upload your import file to the server transfer section of the site before anything can be looked at

**Comment by p4r4cyt3** [comment]
My apologies. atom0s had imported the file for me. I'll get right on that.

**Comment by TeoTwawki** [comment]
Think I got him squared away, told him to open a another issue here if he has trouble
