### ISSUE TITLE
Pining Nocturn, Unable to use Scroll -> "Cannot attack this target"

### ISSUE THREAD

**Issue by Brenketsu** [LegionDark/Issues#1281]
**Date & Time**: 
14:52 22/12/2016

**FFXI Client Version (use `/ver`)**: 
30161103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30161004_1

**Character Name**: 
Tleaf

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
Bard 99

**NPC or Monster or item Name**: 
NA

**Zone name**: 
Northern Sandoria

**Coordinates (use `$where`)**: 
X:128 Y:0 Z:-1

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/5080/pining-nocturne

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Try learning Pining Nocturn via Scroll for a 95+ Bard.
I noticed my version is a little off, but a client update doesnt bring me to match which I assume is in this case normal, Please advise.

**Comment by Heepster03** [comment]
Unfortunately it's currently not implemented in DSP. No ETA on when it will be done.

**Comment by Jessland86** [comment]
Duplicate - https://github.com/LegionDark/Issues/issues/846
