### ISSUE TITLE
Apocalypse (Relic Scythe) Low Dmg / No 2x Damage Proc

### ISSUE THREAD

**Issue by Lavrik83** [LegionDark/Issues#1282]
**Date & Time**: 
12/23/16
3:26pm

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Lavrik

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
75DRK/37WAR

**NPC or Monster or item Name**: 
N/A

**Zone name**: 
Zehrun Mines

**Coordinates (use `$where`)**: 
X: 26 Y: 9 Z:-99 (129)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/18306/apocalypse

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Damage seems to be a bit low, as Vassago's Scythe (http://www.ffxiah.com/item/16788/vassagos-scythe)  was putting up higher numbers.  Also, I haven't gotten a 2x dmg proc at all since equipping it, not sure if it's working correctly or not.

**Comment by R3P0FFXI** [comment]
@Lavrik83 Working as intended
