### ISSUE TITLE
Doom effect broken

### ISSUE THREAD

**Issue by sucidaldeathtar** [LegionDark/Issues#1283]
**Date & Time**: 
Dec 24th, 2016 

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Sucidaltank

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
Blu99/rdm49

**NPC or Monster or item Name**: 
Lofty Zilant

**Zone name**: 
Legion

**Coordinates (use `$where`)**: 
x-183 y-12 z215

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes x6

**Steps To Reproduce / any other info**: 
Doom Doesn't take effect after it countdown.  I believe most of the doom type moves don't work.  I never had them work since I been playing.  Thought there was already a ticket but there wasn't it seems

Taurus type mobs that do mortal ray in abyesea don't work from what ive seen also

**Comment by R3P0FFXI** [comment]
Lofty Zilant casts Soul Douse 	local typeEffect = EFFECT_DOOM;

**Comment by TeoTwawki** [comment]
global dsp issue effecting all status effects (buffs too)
