### ISSUE TITLE
Cactrot Rapido does nothing.

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1284]
**Date & Time**: 
12/25/2016

**FFXI Client Version (use `/ver`)**: 
30161103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
no

**Character Name**: 
Immortality

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99Pld/dnc

**NPC or Monster or item Name**: 
Cactrot Rapido

**Zone name**: 
Eastern Altepa Desert

**Coordinates (use `$where`)**: 
-25 -16 60 (237)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Cactrot Rapido doesn't move, just stands there and lets you pound on him till he dies. He also can't be claimed with a Sabotender like normal. Literally stands there and does nothing.

**Comment by TeoTwawki** [comment]
Conformed and investigating..He spawns, runs a short ways then suddenly freezes solid..

**Comment by TeoTwawki** [comment]
I've worked around it by disabling all his roam logic. He'll act like a normal Sabotender till fixed properly.

**Comment by TeoTwawki** [comment]
His pathing error is a DSP prob. I don't expect a fix anytime soon.
