### ISSUE TITLE
Gurfurlur the Menacing still despawning

### ISSUE THREAD

**Issue by Dalkiel81** [LegionDark/Issues#1286]
**Date & Time**: Dec. 26 2016 2:30pm

**FFXI Client Version (use `/ver`)**: 
30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yep

**Character Name**: 
Dalkiel

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
nin99/war49

**NPC or Monster or item Name**: 
Gurfurlur the Mencing

**Zone name**: 
Halvung

**Coordinates (use `$where`)**: 
x:-47 Y:-22 Z:9 (121)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Was fighting Gurfurlur the Menacing, I died and he despawned.

**Comment by TeoTwawki** [comment]
found and fixed in dsp yesterday. when we pull in updates (just waiting on that client update to get in) it'll be fixed here

**Comment by Dalkiel81** [comment]
ok ty
