### ISSUE TITLE
Prishe doesn't accept Sylvan legs trade

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#129]
**Date & Time**: 6/30/15
**Frequency**: Always
**FFXI Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: Hume
**Main Job**: Rng
**Sub Job**: NA
**Area & Coordinates**: Abyssea Empyreal Paradox
**Party or Solo**: NA
**NPC Name**: Prishe
**Monster Name**: NA
**Steps To Reproduce The Issue**: I have access to empy reforge. Trade Prishe Sylvan Bragues +2 and 30 Itzpapalotl Scales as stated on forums, get no response and no trade.

**Comment by Loki79** [comment]
typo in script.  fixed and working correctly.
