### ISSUE TITLE
SCH Modus Veritas job ability

### ISSUE THREAD

**Issue by Devilotte** [LegionDark/Issues#1290]
**Date & Time**: 
12/30/2016 6:04PM

**FFXI Client Version (use `/ver`)**: 
30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Demresinaux

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
SCH99/BLM49

**NPC or Monster or item Name**: 

**Zone name**: 
Abyssea - Altepa

**Coordinates (use `$where`)**: 
X-751 Y-19 Z-603 (71)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Modus Veritas (SCH Job Ability) always misses

**Comment by TeoTwawki** [comment]
From the README.md:

> **If the issue you woud like to report concerns a Job Ability or Job Trait, please read [this](https://github.com/LegionDark/Issues/issues/298) first.**

**Comment by TeoTwawki** [comment]
We want to keep all trait/ability reports to a single issue. Unfortunately till now nobody even bothered to use the existing issue.

**Comment by TeoTwawki** [comment]
#298
