### ISSUE TITLE
Crafting Levels

### ISSUE THREAD

**Issue by Reho01** [LegionDark/Issues#1291]
**Date & Time**: 01/01/2017 11:08am

**FFXI Client Version (use `/ver`)**: 30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Hanzo

**Nation**: Windurst

**Job(level)/Sub Job(level)**: 99 Red Mage

**NPC or Monster or item Name**:  Crafts

**Zone name**: Buburimu Peninsula

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Would like to have my crafts applied to my character Hanzo

![crafting levels](https://cloud.githubusercontent.com/assets/24864645/21582177/19943a92-d013-11e6-966a-68eb72916072.png)

**Comment by TeoTwawki** [comment]
Do you have an uncropped version of that?

**Comment by Reho01** [comment]
Yes I do

![img_20161231_143805](https://cloud.githubusercontent.com/assets/24864645/21582210/004aa318-d014-11e6-8bf7-29330ad60e2c.png)

**Comment by TeoTwawki** [comment]
Thanks :)

A GM will be with you as soon as possible.

**Comment by Reho01** [comment]
Thank you :) Currently online

**Comment by TeoTwawki** [comment]
All set.
