### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by Reho01** [LegionDark/Issues#1292]
**Date & Time**: 1/2/2017

**FFXI Client Version (use `/ver`)**: 30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Hanzo

**Nation**: Windurst

**Job(level)/Sub Job(level)**: RDM99/THF49

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: I was looking at my character and seen my storage didn't transfer over. Sorry if it's too late but worth a post. Screenshot and list of Storage items.

[Storage.zip](https://github.com/LegionDark/Issues/files/680730/Storage.zip)

**Comment by Heepster03** [comment]
Have you placed the furnishings back into your MH to open the storage? Also want to give you a heads up that 90+% of that will not xfer. Anything of 75 is not xferred.

**Comment by R3P0FFXI** [comment]
@Reho01 anything over 75 will not transfer

**Comment by Reho01** [comment]
Yeah ip'm sorry I just did that and its there, little sleep didn't let me read stuff corredctly
