### ISSUE TITLE
Sandy mission Infiltrate Davoi picked up after completing

### ISSUE THREAD

**Issue by Karsh81** [LegionDark/Issues#1293]
**Date & Time**:  1/3/2017 7:30 PM

**FFXI Client Version (use `/ver`)**:  30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**:  Karsh

**Nation**:  Sandoria

**Job(level)/Sub Job(level)**:  WHM79/BLM39

**NPC or Monster or item Name**:  Prince Trion's Room/door guard Perfaumand

**Zone name**:  Chateau d'Oraguille

**Coordinates (use `$where`)**:  X:-38 Y:-3 Z:69 (131)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  No

**Steps To Reproduce / any other info**:  I am rank 4, I completed the Qufim island mission in Delkfutts tower. I went back to the south sandoria gate guard to get next mission and All he had available was "Infiltrate Davoi" and "The Crystal Spring".  I forgot I already completed "Infiltrate Davoi" and selected it from the list, and it made me accept the mission. There is no way to cancel the Mission SO I tried to just do it. The first step in the mission is to goto the Chateau and talk to Prince Trion, however when I try to go do this The guard at his bedroom door tells me "No entry" 

I wasn't supposed to do this mission I was supposed to do the next mission "Magicite" according to the ffxi wiki. The last mission I completed was "Appointment to Jeuno" And I received Rank 4.

**Comment by TeoTwawki** [comment]
http://ffxiclopedia.wikia.com/wiki/The_Davoi_Report
or
http://ffxiclopedia.wikia.com/wiki/Infiltrate_Davoi
?

You don't wanna know how many times someone told us one is broken when they follow the steps for the other..(its a lot).

**Comment by JessLand86** [comment]
@Check mission gives 10 for "Infiltrate Davoi"

**Comment by JessLand86** [comment]
Checkmission gives 10 which is "Infiltrate Davoi"

**Comment by TeoTwawki** [comment]
Apologies to mr. Check for the errant mentions, our game engine used that symbol for commands where github uses it for mentions before I changed it


@JessLand86 `$checkvar` their `MissionStatus` for me.

**Comment by JessLand86** [comment]
Missionstatus comes up with 6. And I'll get the hang of this eventually >.> My bad Mr. Check.

**Comment by Karsh81** [comment]
Its Infiltrate davoi, but I have already completed it. So it is not letting me redo it

**Comment by TeoTwawki** [comment]
We'll have to reset that status var.

**Comment by TeoTwawki** [comment]
@Karsh81 its not proceeding because you somehow have an invalid variable value. None of our code sets it to 6 anywhere. Your post says you weren't multi-boxed but this is common side effect of that.

Being able to repeat missions is normal. We'll fix your variable so you can continue but you'll have to finish repeating it since you flagged it.

**Comment by TeoTwawki** [comment]
> Trion: I SWEAR TO YOU I AM A MERE RARAB!

Ok since the crown prince is bonkers, I just said F it and forced the steps to completed. Prince bunny should have a cs for you now.
