### ISSUE TITLE
Cannot get Dynamis Cutscene in Xarcabard

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1294]
**Date & Time**: 
1/4/2017 12:16

**FFXI Client Version (use `/ver`)**: 
3016206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Thrice

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99nin/war

**NPC or Monster or item Name**: 
n/a

**Zone name**: 
Xarcabard

**Coordinates (use `$where`)**: 
 533 0 -274

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Zoned into Xarcabard and did not get the CS for dynamis. I've already cleared outlands dynamis, but never tried to touch city dynamis until today. Checked I do not have the KI "Vial of Shrouded Sand" Zoning to xarc does nothing as does checking the trail markings in the cities.

**Comment by Heepster03** [comment]
![image](https://cloud.githubusercontent.com/assets/8421725/21651859/ed31d6a8-d26f-11e6-858d-0f1dbdc816df.png)

**Comment by JessLand86** [comment]
I r derp~ I derp it gerd~

**Comment by Heepster03** [comment]
I setplayervar to 0 for obtaining CS as it should've been.

**Comment by TeoTwawki** [comment]
I blame dsp for letting city dyna and cop dyna write to the same crap..
