### ISSUE TITLE
Dynamis Issues Mobs Dont spawn or are Not attackable

### ISSUE THREAD

**Issue by PerfectGuik** [LegionDark/Issues#1295]
**Date & Time**:  **2017-01-05  12:41 EST**

**FFXI Client Version (use `/ver`)**:  **30161206_3**

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: **Server Ver match**

**Character Name**:  **Alizoutim**

**Nation**:  **San d'Oria**

**Job(level)/Sub Job(level)**:  **Thie99/Dancer49**

**NPC or Monster or item Name**: 

**Zone name**:  Dynamis-Valkurm dunes

**Coordinates (use `$where`)**:   everywhere

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  no multi boxing

**Steps To Reproduce / any other info**: 
- Enter Dynamis Valkurm dune
- Run everywhere
- No monster found  except 6 nightmare sabotender
-asked a GM
-replied that he dosent see anything in the zone and ask to report it

**Comment by PerfectGuik** [comment]
I went in again and everything seemed ok all the monster were there

**Comment by R3P0FFXI** [comment]
@PerfectGuik this is a known issue in Darkstar. There is no ETR to getting it fixed as most likely it requires a complete recode of Dynamis

**Comment by TeoTwawki** [comment]
Should be fixed when we catch up with DSP now
