### ISSUE TITLE
Celaeno's Cloth and Waktza Rostrum don't stack.

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1296]
**Date & Time**: 
1/6/2016 1910

**FFXI Client Version (use `/ver`)**: 
30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Immortality

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99THF/DNC

**NPC or Monster or item Name**: 
Celaeno's Cloth
Waktza Rostrum

**Zone name**: 
N/A

**Coordinates (use `$where`)**: 
N/A

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/3449/celaenos-cloth
http://www.ffxiah.com/item/4012/waktza-rostrum

**Multi-boxing? (multiple clients on same connection)**: 
yes/ N/A

**Steps To Reproduce / any other info**: 
Neither item stacks, both should stack to 12.

**Comment by R3P0FFXI** [comment]
@JessLand86 fixed in latest update

**Comment by JessLand86** [comment]
@R3P0FFXI Still don't stack after the update.

**Comment by TeoTwawki** [comment]
@JessLand86 @R3P0FFXI I checked the flags and the stack size in the SQL against what the client dat says file and can't find any reason for these not stacking proper, gonna have to tell DSP.

**Comment by TeoTwawki** [comment]
@R3P0FFXI you have trash in a custom file. That never should have ever been there.
