### ISSUE TITLE
 Khalkotaur spawn point is not close to the spawn ???

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1297]
**Date & Time**: 
1/6/2016 1910

**FFXI Client Version (use `/ver`)**: 
30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Immortality

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99THF/DNC

**NPC or Monster or item Name**: 
Khalkotaur

**Zone name**: 
Abyssea-Vunkerl

**Coordinates (use `$where`)**: 
-242 -40 -115

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Current spawn point is at -240 -39 -166 ??? is at -242 -40 -115

**Comment by TeoTwawki** [comment]
basically a crap-ton of spawnpoints for NMs are plain wrong and need changed.

**Comment by R3P0FFXI** [comment]
@JessLand86 please check and see if this is still an issue after last nights maint.

**Comment by JessLand86** [comment]
The ??? is missing now.

**Comment by Heepster03** [comment]
Addressed in https://github.com/LegionDark/Issues/issues/1364
