### ISSUE TITLE
Perfect Counter job ability doesn't work?

### ISSUE THREAD

**Issue by DjZetsubou** [LegionDark/Issues#1298]
**Date & Time**:  01/08/17

**FFXI Client Version (use `/ver`)**:  30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  Yes

**Character Name**: Zetsubou

**Nation**: Windy

**Job(level)/Sub Job(level)**:  86Mnk/43 War

**NPC or Monster or item Name**: 

**Zone name**:  Maze of Shakrami

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:  
Activated Perfect Counter, No effect on the status buff bar and no counter attack. I have tried everything, Tried activating it first then pulling a mob with chi blast and my character did not counter attack like the ability is supposed to. Also has a weird new animation that I have never seen before and takes like 3 seconds to finish.

**Comment by TeoTwawki** [comment]
From the README: 

>**If the issue you would like to report concerns a Job Ability or Job Trait, please read [this](https://github.com/LegionDark/Issues/issues/298) first.**

**Comment by TeoTwawki** [comment]
#298
