### ISSUE TITLE
Can't do anything

### ISSUE THREAD

**Issue by MokaMacaroon** [LegionDark/Issues#1299]
**Date & Time**: 8-1-17

**FFXI Client Version (use `/ver`)**: 30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30161206_3

**Character Name**: Mokamacaroon

**Nation**: Windurst

**Job(level)/Sub Job(level)**: 21RDM / 10WHM

**NPC or Monster or item Name**:  N/A

**Zone name**:  Happens in all zones

**Coordinates (use `$where`)**: x:-233 y:8 z:45 (248)

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)**: n/a

**Steps To Reproduce / any other info**: 
As said before, I was crafting while using @ah, came to craft again, but this time i couldn't and now I cant use any shops, @ah or craft...

Thanks...

**Comment by MokaMacaroon** [comment]
Ok. I've sorted it. For some reason, I had to toss the items I bought on AH while crafting. 

P.S, please don't get salty for me post in the wrong section when it isn't clear in your forums. Thank you.

**Comment by R3P0FFXI** [comment]
don't use @ commands on git it spams the actual owner of that login. ALL our commands are $ @MokaMacaroon

**Comment by TeoTwawki** [comment]
Nobody got was "salty" but having attitude over **your** mistake isn't a good idea. I wouldn't even be speaking if you hadn't made that comment, all it did was annoy. There is a link that says bug reports go here both on the ***front page*** of the website _and_ as a forum redirect. What more can we do? We're not going back to forum posts as bug reports that's for sure. If you got suggestions I'd love to ear them, but please think before you throw out terms like "salty" - we didn't do anything wrong here.
