### ISSUE TITLE
Summoner BPs do not work in Fenrir Prime fight

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#13]
**Date & Time**: 5/26/15
**Frequency**: once
**FFXi Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: Hume
**Main Job**: Smn 92 (fight capped 80)
**Sub Job**: Rdm 
**Area & Coordinates (Type @where to get this info.)**: Fenrir Prime fight BC
**Party or Solo**: Duo
**NPC Name**: NA
**Monster Name**: NA
**Steps To Reproduce The Issue**: Go into fenrir fight, try to use any BP, no animations will play, damage will not appear in log. Ward BPs seem to play animation, but have no effect whatsoever beyond just the avatar themselves.

**Comment by R3P0FFXI** [comment]
Per User Avatars will Summon

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/commit/f4b5fa008e096023a5cbe8005827f0b19b4c271c
Will be fixed on or before Tuesday Maint.
