### ISSUE TITLE
Hashishin Mintan Blu mage reforge 109lvl haste +3% not work

### ISSUE THREAD

**Issue by razielyjofiel** [LegionDark/Issues#130]
Date & Time:6/27/2015 6:57pm est 
Frequency: anytime 
FFXI Client Version: 30150508_8
Character Name:Aurel
Race:Hume
Main Job:Blu
Sub Job: Rdm
Area & Coordinates: equiped
Party or Solo:both
NPC Name:Hashishin Mintan haste
Monster Name:N/A
Steps To Reproduce The Issue:  Hello reforged body lvl 109 blu Hashishin Mintan not give the stats haste + 3 % and Blue magic spellcasting time -13% is not appreciated

**Comment by R3P0FFXI** [comment]
Correct existing mods in DSP have been added change will take effect next Maint.

**Comment by razielyjofiel** [comment]
ok thanks
