### ISSUE TITLE
Craft needed to transferred^^

### ISSUE THREAD

**Issue by ChronoTrigger01** [LegionDark/Issues#1300]
**Date & Time**: 1/8/2017 1:04 PM

**FFXI Client Version (use `/ver`)**:  

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**:  Forby

**Nation**:  Windy

**Job(level)/Sub Job(level)**:  PLD83/DNC38

**NPC or Monster or item Name**:  -

**Zone name**:  -

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:   Looking to have Leathercraft as my craft to be transferred
![img_20170104_183212](https://cloud.githubusercontent.com/assets/5108725/21752718/5a431f8c-d5a3-11e6-8fb1-e240c12190c3.png)

**Comment by Heepster03** [comment]
Leathercrafting imported, enjoy~
