### ISSUE TITLE
Goldsmithing 100 restoration

### ISSUE THREAD

**Issue by Acedffxi** [LegionDark/Issues#1301]
**Date & Time**:  1/8/17 4:50 PM CST

**FFXI Client Version (use `/ver`)**:  30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**:  Serise

**Nation**: Sandy

**Job(level)/Sub Job(level)**: PLD75/NIN37

**NPC or Monster or item Name**: N/A

**Zone name**: N/A

**Coordinates (use `$where`)**: N/A

**ffxiah.com link (for items issues only)**:  N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**:  I would like my goldsmithing 100 to be restored from my server transfer. Thanks!
![img_20170108_010718](https://cloud.githubusercontent.com/assets/17110587/21754261/7f92c138-d5c2-11e6-8e46-84c6898ed72d.png)

**Comment by Heepster03** [comment]
Goldsmithing transferred, enjoy~

**Comment by Acedffxi** [comment]
Tyvm
