### ISSUE TITLE
Wulgaru uses no TP moves

### ISSUE THREAD

**Issue by ghost** [LegionDark/Issues#1302]
**Date & Time**: 
1/8/2017 2021 

**FFXI Client Version (use `/ver`)**: 
30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99Blu/rdm

**NPC or Monster or item Name**: 
Wulgaru

**Zone name**: 
Alzadaal Undersea Ruins

**Coordinates (use `$where`)**: 
-22.265 -4.449 204.588

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Mob uses no TP moves at all during fight. This is also currently the only way to learn the blue spell Sinker Drill.

**Comment by R3P0FFXI** [comment]
@JessLand86 Blu spells need to be moved off incorrect mobs and in to the correct method DSP has for them via SQL, this is planned but no ETR.

**Comment by TeoTwawki** [comment]
@R3P0FFXI lets focus on the part where the mob has no skills before the part where the skill is a learnable blu spell

**Comment by TeoTwawki** [comment]
In fact I nominate you!

-_runs and hides_-

**Comment by Raelious** [comment]
Fixed just tested, Wulgaru uses all of its TP moves now.
