### ISSUE TITLE
~ Dynamis Xarcabard busted ? Attacking issue ~

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#1303]
**Date & Time**: 09/01/17 , 20.18 GMT+1

**FFXI Client Version (use `/ver`)**: 30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Thranduil

**Nation**: Bastok

**Job(level)/Sub Job(level)**: thf99/dnc49

**NPC or Monster or item Name**: various mobs

**Zone name**: Dynamis Xarcabard

**Coordinates (use `$where`)**: various

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 
Tried after and before  jan 8th maintenance: I was unable to attack mobs in Dyna Xarc; I've tried changing targets, and managed to kill some, but something's wrong, getting lots of "you cannot attack that target".

**Comment by TeoTwawki** [comment]
dynamis - everyplace
is all farked up.

dsp busted all of them everywhere.exit/re-enter can help _sometimes_ but its a total clusterf\*\*\*k

**Comment by R3P0FFXI** [comment]
https://github.com/LegionDark/Issues/issues/1295

**Comment by R3P0FFXI** [comment]
@simthra moving Dynamis issues to 1 topic https://github.com/LegionDark/Issues/issues/1295
