### ISSUE TITLE
Various ilvl weapons are giving duplicate skills

### ISSUE THREAD

**Issue by sucidaldeathtar** [LegionDark/Issues#1305]
**Date & Time**: 
1/11 5:31pm

**FFXI Client Version (use `/ver`)**: 
30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Sucidaldeath

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
thf99/49dnc

**NPC or Monster or item Name**: 
Twashtar

**Zone name**: 
Ordells cave

**Coordinates (use `$where`)**: 
X-60 Y-27 Z42

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/20587/twashtar

**Multi-boxing? (multiple clients on same connection)**: 
yes but only one in zone

**Steps To Reproduce / any other info**: 
Not increasing Dagger skill, and Parry skill in Combat skill menu.   Is it still giving just not showing?   Attack is showing at 830,  sanding and vajra in the 107X range.  Also showing correct skill lvls

**Comment by sucidaldeathtar** [comment]
tried main hand only no offhand

**Comment by sucidaldeathtar** [comment]
hidden stats look like there working though

**Comment by R3P0FFXI** [comment]
Darkstar inserted incorrect mods on certain ilvl weapons when they should not be this will be corrected via a darkstar update
