### ISSUE TITLE
Nexus Cape not working?

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1306]
**Date & Time**:  01/11/17 - 9:19p EST

**FFXI Client Version (use `/ver`)**: 30151227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30151227_1

**Character Name**: Meokazi

**Nation**: Bastok

**Job(level)/Sub Job(level)**: SAM75/DNC37

**NPC or Monster or item Name**: Nexus Cape

**Zone name**: Meokazi is in Nashmau and Bastok Markets trying to warp to party leader in Bhaflau Thickets

**Coordinates (use `$where`)**:  X:-13, Y:0, Z:31 (28)

**ffxiah.com link (for items issues only)**: n/a?

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Trying to use Nexus Cape and timer is up and item is ready to use, been to the area multiple times, get the error "Unable to use item"

**Comment by Raelious** [comment]
Did some further testing with it, I warped one character to Qufim Island and the cape worked fine, warped to Lufaise Meadows worked fine, tried Whitegate did not work, tried  Wajoam Woodlands did not work, tried Caedarva Mire did not work. So maybe its not working to warp to Whitegate areas?

**Comment by TeoTwawki** [comment]
The non retail zones accidentally got lost in the recent update. I just restored them.
