### ISSUE TITLE
ibar watchexp and a few other addons stopped working with client update

### ISSUE THREAD

**Issue by warlord1352** [LegionDark/Issues#1308]
**Date & Time**: 6:15 am pst

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Oscar

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99nin/49war

**NPC or Monster or item Name**: n/a

**Zone name**: everywhere

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: not as this time

**Steps To Reproduce / any other info**: tried relogging several times and nothing changes. not exactly sure if this is where I should be posting this or not, but after I updated the client a few of my addons/plugins are not working and giving weird problems. See attachment.

On a side note is there any way to "reinstall" addons/plugins?

![oscar_2017 01 12_062213](https://cloud.githubusercontent.com/assets/15023912/21893375/adaeee5a-d88f-11e6-8fa6-65bc3f625b69.png)
![oscar_2017 01 12_062247](https://cloud.githubusercontent.com/assets/15023912/21893374/adaeba8e-d88f-11e6-9dea-dc353b6d5f4a.png)

![cureslave_2017 01 11_193825](https://cloud.githubusercontent.com/assets/15023912/21893257/353d5952-d88f-11e6-9029-7975daa75a51.png)

**Comment by Heepster03** [comment]
Are you using v2 or v3? If you're using v2, you should upgrade to v3 at your earliest convenience. If you're using v3, the bug report should be posted here: http://git.ashita.atom0s.com/Ashita/Ashitav3-Release/issues

**Comment by R3P0FFXI** [comment]
@warlord1352 Not our issue

**Comment by warlord1352** [comment]
@Heepster03 That was the fix thanks heep. Didn't even know v3 was out lol.
