### ISSUE TITLE
Kumhau Not using Ability's or tp moves

### ISSUE THREAD

**Issue by sucidaldeathtar** [LegionDark/Issues#1309]
**Date & Time**: 
1/12/17

**FFXI Client Version (use `/ver`)**: 
30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Sucidaldeath

**Nation**: 
sandy

**Job(level)/Sub Job(level)**: 
99thf/dnc49

**NPC or Monster or item Name**: 
Kumhau

**Zone name**: 
Uleguerand Range 

**Coordinates (use `$where`)**: 
 X: -22, Y: -175, Z: 50 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Not doing ability's or TP moves.  Just melee damage

**Comment by Heepster03** [comment]
This appears to be working as intended now, gonna go ahead and close.
