### ISSUE TITLE
Ferdinand - Relic gun stage 4

### ISSUE THREAD

**Issue by Strafeous** [LegionDark/Issues#131]
**Date & Time**:  2:11am 7/1/2015
**Frequency**: All the time
**FFXI Client Version**:  30150619_2
**Character Name**: Strafeous
**Race**: Elvaan
**Main Job**: WAR atm, tried on RNG also
**Sub Job**: THF
**Area & Coordinates**: x:387 Y-12 Z-18
**Party or Solo**: Solo
**NPC Name**: Switchstix
**Monster Name**:
**Steps To Reproduce The Issue**: Traded the items remaining to finish Annihalator, then tried to trade 10k byne and won't take the currency with the gun. Tried to talk and trade the gun. Won't take either. Blank dialogue.

**Comment by PikaFox** [comment]
He doesnt take the final trade. It seems someone at least fixed the bug where he would eat your currency.

 Ferdinand
 Necropsyche
 Ethereal Fragment
 Metalworks: Gunpowder Room

Gunpowder room blank space takes final trade. Might need to talk to switchstix with ferdinand in inventory first.

**Comment by Strafeous** [comment]
Hrmm, I traded him the Necropsyche/fragment and held that. Would I just need to trade the gunpower room the currency?

**Comment by PikaFox** [comment]
You trade fragment, necro, and currency to the blank space in the gunpowder room. If the goblin took anything, youll need to either hope you have screenshots of it for a GM, or farm it again im assuming.

**Comment by Strafeous** [comment]
Yeaaah, gunpower room doesn't work, just blank diaglouge

**Comment by PikaFox** [comment]
I literally did this less than a week ago. Trade all the items to the blank space within the gunpowder room, not the door, not the ???, the blank space.

**Comment by Strafeous** [comment]
![This place gives me no dialogue when trading the Necropsyche, Ethereal Fragment, 10k byne](http://i.imgur.com/QGOCqKK.jpg)

**Comment by itachioax** [comment]
talk one time with the goblin at castle zhal then come back to metalworks and make trade again

**Comment by R3P0FFXI** [comment]
ID has most likely shifted this would not be a Legion bug but a DSP bug. Try what itachi suggested and let us know if it does or does not work if it does not then its a DSP issue and he ID has shifted.

**Comment by Strafeous** [comment]
Yeah, still doesn't work. 
What are my options here?

**Comment by R3P0FFXI** [comment]
well report it to DSP its a DSP issue

**Comment by R3P0FFXI** [comment]
https://github.com/DarkstarProject/darkstar/issues/1651

**Comment by R3P0FFXI** [comment]
Please advise if this is still an issue or has been resolved

**Comment by R3P0FFXI** [comment]
Per user closing issue this has been resolved
