### ISSUE TITLE
Crafts Restored

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1310]
**Date & Time**: 1/12/17

**FFXI Client Version (use `/ver`)**:  30151227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30151227_1

**Character Name**: Raelious

**Nation**: Bastok

**Job(level)/Sub Job(level)**: MNK75/WAR37

**NPC or Monster or item Name**: N/A

**Zone name**: Bastok Mines

**Coordinates (use `$where`)**: X:0, Y:0, Z:0 (192)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: 
Not to sure if its too late to have my crafts restored or not but was told to post anyway;
http://imgur.com/a/qF7qE

**Comment by Heepster03** [comment]
Clothcraft xferred.
