### ISSUE TITLE
ahbot issue

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#1311]
**Date & Time**: 1/12/2017

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: ritonami

**Nation**: windurst

**Job(level)/Sub Job(level)**: thf(99)/dnc(49)

**NPC or Monster or item Name**:archer ring

**Zone name**: ordelle's

**Coordinates (use `$where`)**: -83,-27,-98 (252)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
AH is buying archer rings back for 200k instead of the 40k its listed as

**Comment by Heepster03** [comment]
Working as intended.

**Comment by ritonami** [comment]
no complaints that its selling for more but shouldn't the ahbot > ahbot be updated to reflect 200k? otherwise wont ppl just buy them off ahbot for 40k and sell them back 200k?

**Comment by TeoTwawki** [comment]
the bot doesn't doesn't time travel back to change history so the old sales still show old prices unless someone manually edits the database to change some rows.
