### ISSUE TITLE
Glory Slash Accuracy Error

### ISSUE THREAD

**Issue by Hazed69** [LegionDark/Issues#1312]
**Date & Time**: Jan. 13th 2017 4:21pm Eastern US

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Hazed

**Nation**: N/A

**Job(level)/Sub Job(level)**: 99PLD/49WAR

**NPC or Monster or item Name**: N/A

**Zone name**: N/A

**Coordinates (use `$where`)**: N/A

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Persistent Coding Error. Glory Slash Properly hits current target but does not have AoE effect at this time.

**Comment by TeoTwawki** [comment]
Try now

**Comment by Hazed69** [comment]
ok retesting

**Comment by Hazed69** [comment]
Properly hits current target but does not have AoE effect at this time.

**Comment by TeoTwawki** [comment]
will have this cleared up next maint

**Comment by Hazed69** [comment]
no worries just informing you

**Comment by TeoTwawki** [comment]
This server *really* needs to get better at keeping its customization documented.

In game helptext will always reflect retail, and @Loki79 edited these. I thought one of the 2 was made single target and the other left AoE but I was just told he made both single target.

**Comment by Hazed69** [comment]
Ah ok well that explains why then. Atleast you found the cause.

**Comment by TeoTwawki** [comment]
These might get reworked to aoe again to avoid future confusion, don't know yet. But for now I guess this is intended.
