### ISSUE TITLE
Walahra Turban 

### ISSUE THREAD

**Issue by DirtyAE** [LegionDark/Issues#1313]
Ok so i donated the 1000 imp brinze pieces to NPC in Aht Urgan for Walahra Turban, i didnt reciace the Turban and he just wants me to keep signing the Petition, I check the NPC that could be taken in besieged and its still in town and no he never said "He was taken" i just checked! Please Assist! XD ty ty

**1/13/17 about 6am cst**: 

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Dirty**: 

**Sandy**: 

**Job(level)/Sub Job(level)**: 

**Gajaad**: 

**Art Urgan**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:

**Comment by Heepster03** [comment]
Yeah... you're going to have to redo this. Edit it to match the correct format.
