### ISSUE TITLE
Walahra Turban

### ISSUE THREAD

**Issue by DirtyAE** [LegionDark/Issues#1314]
**Date & Time**: 
1/13/17 6am cst

**FFXI Client Version (use `/ver`)**: 
Ashita v3
 
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes?

**Character Name**: 
Dirty

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
76 THF / 38NIN

**NPC or Monster or item Name**: 
Gajaad

**Zone name**: 
Art Urgan

**Coordinates (use `$where`)**: 
J-6

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/15270/walahra-turban

**Multi-boxing? (multiple clients on same connection)**: 
yes sometimes but cannot firgure out repeater lol

**Steps To Reproduce / any other info**: 
just donate 1000 imperial bronze pieces to Gajaad

**Comment by PikaFox** [comment]
Assuming it did not give you the item. Try trading one more. It gives it at 1001.

**Comment by DirtyAE** [comment]
i can try giving 1 more yes

**Comment by DirtyAE** [comment]
ok so i traded 5 more and got it~!!!! TY PIKA
