### ISSUE TITLE
Bonecrafting stuck at 100 (Khimaira horn)

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#1315]
**Date & Time**: 1/15/2017

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/rdm49

**NPC or Monster or item Name**: Khimaira Horn

**Zone name**: na

**Coordinates (use `$where`)**: na

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: The test item to take Bonecraft over 100 is Hajduk Ring, you need 2 Khimaira horn, however the only place the item tool shows it dropping is PW, which is disabled and has been for about a year now.  The Khimaira horn also isn't sold on AH, neither is the Hajduk ring, leaving bonecraft stuck at 100.

**Comment by TeoTwawki** [comment]
Moved into catch all issue. #1333

@R3P0FFXI you suck. 😛
