### ISSUE TITLE
Server transfer items missing 

### ISSUE THREAD

**Issue by Sookram** [LegionDark/Issues#1316]
**Date & Time**: 01/15/17 08:30 PM

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Esquelax

**Nation**: Bastok

**Job(level)/Sub Job(level)**: MNK 99 no sub

**NPC or Monster or item Name**: 

**Zone name**: Bastok Mines

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Did a server transfer from retail. Everything seems to work as intended except everything from my Mog Safe 2 is missing. I downloaded the tool > downloaded and installed both of the 32-bit Visuall C++ files > downloaded the latest EliteAPI.dll > logged onto my character and sat in the same zone for several minutes > opened tool as admin > ran the tool > zipped the file > created a new character with the same name on Legion server > made a post.

I did all of this today so I should have the latest tool. Only thing I see is my Mog safe 2 is empty. I

**Comment by R3P0FFXI** [comment]
@Sookram what was in your mogsafe2? was it items over 75? I can try to reimport but id advise first post  apic of whats there so we can determine if its items ignored by the tool automatically.

**Comment by Sookram** [comment]
![mogsafe2_items_1](https://cloud.githubusercontent.com/assets/4282796/21969623/9faaeeb8-db6d-11e6-96b8-ba9c27eb4362.PNG)
![mogsafe2_items_2](https://cloud.githubusercontent.com/assets/4282796/21969624/9fab9b56-db6d-11e6-9a6f-bf0396b7073c.PNG)
![mogsafe2_items_3](https://cloud.githubusercontent.com/assets/4282796/21969625/9fae0788-db6d-11e6-845e-8e8c553777d4.PNG)
![mogsafe2_items_4](https://cloud.githubusercontent.com/assets/4282796/21969626/9faece0c-db6d-11e6-93d8-8735818a2b38.PNG)

I know Vunetshelo, Fieldrazer Scythe, and Velox Harness won't transfer as they are the only items 76+.
Teo said he looked at my export file and said nothing was in there.

**Comment by R3P0FFXI** [comment]
@Sookram please reattempt export and upload the new file we can see if that works if not im not going to spend to much time on a few misc items that can be gotten in game via our ah bot

**Comment by R3P0FFXI** [comment]
@Sookram reimport completed
