### ISSUE TITLE
Abyssea La thiene NM - Ovni is avoiding me i didnt take shower for week.. ok

### ISSUE THREAD

**Issue by thekwan3** [LegionDark/Issues#1318]
**Date & Time**: 
Jan 18, 2017 10:00PM EST

**FFXI Client Version (use `/ver`)**: 
30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Extralargetaru

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
Paladin99/Warrior49

**NPC or Monster or item Name**: 
Ovni

**Zone name**: 
Abyssea - La Theine Plateau

**Coordinates (use `$where`)**: 
X:512 Y:36 Z:468

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Ovni is flying around taunting me, not coming down from the sky so i can kill him for his harp and belt. [GM]Astreaea tried to get ovni down also but it scared of him i think...so he tell me to write a report ok hi! please get him off his high horse so i can beat him up cause he make me do i'm cry inside.

**Comment by TeoTwawki** [comment]
fixed and forgot to update+close issue, my bad!
