### ISSUE TITLE
Now 2017 ...Prishe do not accept the item for reforge Arbatel bracers

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1319]
**Date & Time**: 19-01-2017

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Cassy

**Nation**: Sandy

**Job(level)/Sub Job(level)**: sch

**NPC or Monster or item Name**: Prishe

**Zone name**: AbyssParadox

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/27090/arbatel-bracers

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: Issue is closed #467 and issue #712 ....Prishe do not accept the item for reforge Arbatel bracers

**Comment by Aurelcassy** [comment]
![captura](https://cloud.githubusercontent.com/assets/13084662/22096877/be89320e-ddfc-11e6-8b4e-702f3cadb81d.PNG)

**Comment by R3P0FFXI** [comment]
@Aurelcassy you are trading the incorrect items this is working as intended
