### ISSUE TITLE
Windurst Mission 5-1 The final seal

### ISSUE THREAD

**Issue by kelvenar** [LegionDark/Issues#132]
**Date & Time**: 02.07.2015  02:15(GMT+2) 
**Frequency**: 2 times
**FFXI Client Version**: ver.30150619_2
**Character Name**: Kelvenar
**Race**: Mithra
**Main Job**: Ninja
**Sub Job**: Warrior
**Area & Coordinates**:  Burning Circle Qu'Bia Arena  x:-400 y:-199 z:496(64).
**Party or Solo**: Party
**NPC Name**: None
**Monster Name**: Archlich Taber'quoan
**Steps To Reproduce The Issue**: I tried this fight 2 times and didnt got the KI (Burnt Seal), all my other characters in my party got the KI on the first attempt.

**Comment by R3P0FFXI** [comment]
Are you Dual boxing?

**Comment by kelvenar** [comment]
Yes I did with 4 characters, my alternate chars (Tolone, Seraphina, Dominia) got the KI on the first attempt.

**Comment by R3P0FFXI** [comment]
Ok this is a dual boxing issue then, known issue where all do not get KI to advance.

**Comment by kelvenar** [comment]
I got the KI on 5-1 when i did it alone and i got the KI for all my 4 characters when i did Shadow Lord (5-2) dualboxing.

**Comment by R3P0FFXI** [comment]
Please confirm you have the KI on all our characters if so ill close the ticket

**Comment by TeoTwawki** [comment]
@kelvenar the multi boxing glitches are random, sometimes they happen, sometimes they don't. Anytime you have 2 characters on at the same time there is a small chance that a variable doesn't get set or a keyitem doesn't get obtained. Its a result of DSP's cruddy socket implementation having a hard time telling the 2 clients apart. 

The good news is dual boxing glitches are among the easiest things to fix in the event a player can't just redo a step.

**Comment by kelvenar** [comment]
Yes I have the KI on all chars thx for the work
