### ISSUE TITLE
sub-zero gears not doing any kind of tp moves

### ISSUE THREAD

**Issue by warlord1352** [LegionDark/Issues#1320]
**Date & Time**: 10:18am pst

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: oscar

**Nation**: bastok

**Job(level)/Sub Job(level)**: nin99/war49

**NPC or Monster or item Name**: Sub-zero Gear

**Zone name**: Abyssea-Uleguerand

**Coordinates (use `$where`)**:X -232 Y -176 Z -5

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Keep fighting lots of them and I have not yet seen one tp move. Been trying to learn Rail Cannon.

**Comment by Heepster03** [comment]
Rail Cannon is scripted. They do not currently do tp moves but you can still learn it. Just random.

**Comment by TeoTwawki** [comment]
Not a bug, simply never implemented, mobs were given crappy script work arounds as heep said. Eventually they will get done the right way but were busy with other things atm.
