### ISSUE TITLE
Returning player forgot username password for my Cure mule

### ISSUE THREAD

**Issue by slaggyt** [LegionDark/Issues#1321]
Date & Time:Thursday January 19

FFXI Client Version (use /ver):30161227_1

Server's Expected Client Version matches, yes/no? (use $ecv):yes

Character Name:Imalion cure mule for Lionpaw from Exigence Linkshell

Nation:
Bastok 7 Sandy 1
Job(level)/Sub Job(level):99 WHM/99BLM

NPC or Monster or item Name:

Zone name:Bastok

Coordinates (use $where):nil

ffxiah.com link (for items issues only):none

Multi-boxing? (multiple clients on same connection):will be

Steps To Reproduce / any other info:reset username and password

DO NOT REMOVE OR CHANGE THE PRE-FORMATTED TEXT TO PUT @COMMANDS IN TEMPLATE!!!
GITHUB SEES `@MENTIONS`, NOT `@GMCOMMANDS`!!!
IF YOU STUPIDLY IGNORE THIS WARNING I WILL CLOSE YOUR ISSUE!11eleventytwo!

Issues will also be closed without being looked into if 
the following information is missing (unless its not applicable)!!!
-->

**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:

**Comment by atom0s** [comment]
Handled and restored.

**Comment by TeoTwawki** [comment]
That template butchery, Seriously dude? Watch what you are doing.
