### ISSUE TITLE
Dropped item by accident please restore

### ISSUE THREAD

**Issue by alannor** [LegionDark/Issues#1322]
**Date & Time**: 
1/21/2017

**FFXI Client Version (use `/ver`)**: 
Current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Alannor

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
Various

**NPC or Monster or item Name**: 
Kogarusumaru

**Zone name**: 
Aby Lathien (maybe)

**Coordinates (use `$where`)**: 
Not sure

**ffxiah.com link (for items issues only)**: 
Kogarasumaru 95

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Hi I think I accidently dropped Kogarasumaru lv95 while I was testing out GKs last night... I understand we have one chance for an item dropped to be restored?

**Comment by TeoTwawki** [comment]
verified, found the log showing you dropped it. You are certain want to use up you once only restore on this?

**Comment by alannor** [comment]
Yeah taht wpuld be great

**Comment by TeoTwawki** [comment]
Will be in game shortly (if you won't be, leave me a message here about when is good to catch you on)

**Comment by TeoTwawki** [comment]
Used player's one time restore, item replaced
