### ISSUE TITLE
Crawler's Nest [S] Planar Rift Missing

### ISSUE THREAD

**Issue by Walkersauce** [LegionDark/Issues#1324]
**Date & Time**: 01/22/2016 @1925

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: YES

**Character Name**: Jaundice

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99BLM/49RDM

**NPC or Monster or item Name**: Planar Rift (missing)

**Zone name**: Crawler's Nest [S]

**Coordinates (use `$where`)**: X:54 Y:0 Z:259 (15)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: Gwar

**Steps To Reproduce / any other info**: Rift is missing cannot complete Tier 3 White Abbysite

**Comment by TeoTwawki** [comment]
Thanks for the report.

**Comment by TeoTwawki** [comment]
I fixed it in DSP, it'll be in Legions next Maint.

**Comment by Walkersauce** [comment]
THANKS!!!
