### ISSUE TITLE
Ildebrann drawing players into the mountain and resetting to 100%

### ISSUE THREAD

**Issue by Walkersauce** [LegionDark/Issues#1325]
**Date & Time**:  01/22/2017 @1056

/
**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  YES

**Character Name**: Jaundice

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99BLM/49RDM

**NPC or Monster or item Name**: Ildebrann

**Zone name**: Ifrit's Cauldron

**Coordinates (use `$where`)**: X:11 Y:3 Z:288 (151)

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: Gwar

**Steps To Reproduce / any other info**: Spawn VW NM and he will Draw you into the mountain and you will become stuck unable to get out. He then will climb mountain and reset to 100%. Also the 2 dragons he spawns will keep spawning over and over causing much sadness and death.

**Comment by TeoTwawki** [comment]
> github sees `@mentions`, not `@gmcommands`

The repopping is normal. They are on a timer. Working something related to this mob not in the report: He seems to never use any skills, which also means he will never land like from flight he is supposed to.

As for the issue you reported the mobs position is being moves so he's not so close to the wall, and draw in is being disabled.

**Comment by TeoTwawki** [comment]
Forgot to close after I hotfixed
