### ISSUE TITLE
one of relic weapon stage5 item is not droping 

### ISSUE THREAD

**Issue by arkooqymoya** [LegionDark/Issues#1326]
**Date & Time**: 2017/1/24

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: arkoo

**Nation**: bastok

**Job(level)/Sub Job(level)**: 99thf/49dnc

**NPC or Monster or item Name**: Animated Shield (item's name that surpose to drop  is Supernal Fragment )

**Zone name**: Dynamis - Xarcabard

**Coordinates (use `$where`)**: H-9

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/1822/supernal-fragment

**Multi-boxing? (multiple clients on same connection)**: no(its the dyna i wont multi-box atm)

**Steps To Reproduce / any other info**:      Animated Shield is droping the item"Supernal Fragment" and without this theres not possible to finish the 5th tire of the relic weapon trial,that item is 100% drop rate on the website item search tool, and other item which in need of the relic trial seems droping normally, it seems only this mob is not droping the relic weapon trial needed item.

**Comment by TeoTwawki** [comment]
If I recall correctly DSP has that set to only drop in specific conditions like old old retail did. This has come up before on the tracker for other similar drops see #1247

**Comment by TeoTwawki** [comment]
if that doesn't actually work, someone besides me has to inform dsp that everyone woudl like them get off their rears and scrap their broken dynamis system

**Comment by R3P0FFXI** [comment]
@arkooqymoya Fragment is only 100% after meeting certain conditions this is not Neo Dynamis, You need to kill all the NM first then the Fragment Mob

**Comment by JessLand86** [comment]
This is what DSP Dynamis goes by: http://www.dynamisbums.com/strategy/xar.html

`Scattered through Dynamis-Xarcabard are various animated weapons, which drop fragments used for relic weapon upgrades. Prior to defeat of all of the Demon NMs (and receipt of the "The prison of souls has set free its captive spirits!" message), these weapons are mere placeholders which drop nothing when defeated.

You **have** to get the `The prison of souls has set free its captive spirits! message for the NM's to drop anything. One shotting the eyes and not letting the NM's pop will also prevent you from getting this message as you did not kill the NM.

**Comment by Heepster03** [comment]
Did you try as suggested and it worked? With the amount of Aegis floating around, I'd say that it's working properly.

**Comment by arkooqymoya** [comment]
@R3P0FFXI i was told by others that ,and my friend did clean the mobs that supose to be cleaned,  well i didnt when i doing the test, i will go do that ,

**Comment by arkooqymoya** [comment]
@TeoTwawki thx man, i will go check those stuff and see if that working now,

**Comment by Heepster03** [comment]
I can you that this is working. I did it last week.

**Comment by arkooqymoya** [comment]
yes!my friend and i got that lastnight, now the shield progress is back on trek , thx guys!!

**Comment by PikaFox** [comment]
Closed as per ark's last comment.
