### ISSUE TITLE
Halimede will not spawn.

### ISSUE THREAD

**Issue by Thotless** [LegionDark/Issues#1327]
**Date & Time**:  1/24/2017   0600

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`: yes

**Character Name**: Thotless

**Nation**: Bastok

**Job(level)/Sub Job(level)**: WAR99/SAM49

**NPC or Monster or item Name**: Halimede

**Zone name**: Abyssea-Tahrongi

**Coordinates (use `$where`)**: X:-234 Y:15 Z:-599 (186). 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/2915/hq-cli-wing

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Tried trading High Quality Clionid Wing to the ??? at G-12 to spawn Halimede, nothing seems to happen.  It's one of the NM's needed on the path to pop Chloris.

**Comment by R3P0FFXI** [comment]
@Thotless can you test this and see if its still an issue after last nights maint

**Comment by Heepster03** [comment]
Addressed at https://github.com/LegionDark/Issues/issues/1364
