### ISSUE TITLE
Isgebind abilities/spells

### ISSUE THREAD

**Issue by Thotless** [LegionDark/Issues#1328]
**Date & Time**:  1/24/2017  0700

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Thotless

**Nation**: Bastok

**Job(level)/Sub Job(level)**: WAR99/SAM49

**NPC or Monster or item Name**: Isgebind

**Zone name**: Abyssea-Uleguerand Range

**Coordinates (use `$where`)**: X:166 Y:-116 Z:430 (3).

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Where to begin...  First off its not supposed to fly, It casts Freeze and Freeze 2 which are not supposed to be on its spell list.
Worst of all the only TP move it uses is Absolute Terror.  Its supposed to use Horrid roar, Glacial Breath, and Gregale wing as well but it doesn't.  
This means for almost all the jobs in the game you are stuck in a limbo of not being able to hit him because hes flying, or because you are frozen in terror.
Of course you may say the simple solution to this is to bring more people, but that doesn't help either because a tank wouldn't be able to hold agro because they cant do anything to gain emnity.
Yet another fight Blue mages excel at because while its flying they can just spam nukes and they can simply stun any attempt at isgebind using absolute terror.  Not to mention he also gains resistance to physical attacks throughout the fight, which is an even bigger kick in the balls to melee jobs, but not an issue for blue mage.
This isn't about blue mage balancing though so I digress

**Comment by TeoTwawki** [comment]
> First off its not supposed to fly, It casts Freeze and Freeze 2 which are not supposed to be on its spell list.

welcome to THIS IS NOT RETAIL, where things get customized. Loki tried to make this dude harder. Looks like he overachieved.

**Comment by R3P0FFXI** [comment]
@Thotless bring blm

**Comment by Thotless** [comment]
@R3P0FFXI like i was inferring above, if you were to bring a blm to nuke, the blm would pull agro and die fairly quickly because the warrior/ninja/paladin wouldn't be able to stack enmity very well if they can never hit the enemy due to him flying or you being constantly terror'd.
Maybe im wrong though?

@TeoTwawki right I understand that its not retail and that you have customized things, but its impossible for me to know your goal with balancing so I am reporting what *feels* wrong.  Its completely up to you if you agree or not.

Thanks for the responses

**Comment by TeoTwawki** [comment]
@Thotless right now is he not landing at all? Because I'm seeing that bug with other flying wyrms. Only 1 wyrm is supposed to perma fly. And like I said overdue for rebalancing, I agree with things be cray cray right now. If it were balanced right and lands when it should, it should then be possible to tank it long enough for nukers to bring it down to the ground again (there's both a timer AND a health % check involved, whichever is reached first should make it land).

**Comment by Thotless** [comment]
It does land, however while in the sky, and upon landing or very shortly after he will use a TP ability.  The issue is the only TP ability he is using is Absolute Terror.  By the time the Terror wears off, he will then be very close to either flying, using terror again, or both.

**Comment by TeoTwawki** [comment]
yeah he should be using sleet breath when flying..

**Comment by Thotless** [comment]
Even if he didn't fly at all the fact that he only uses terror would be an issue in my opinion.
There's just not enough time inbetween his abilities to do anything substantial.

**Comment by TeoTwawki** [comment]
er not sleet..whichever breath type for his model
sleet is jormy

**Comment by TeoTwawki** [comment]
yes its a prob, shouldn't bee doing that..

**Comment by Thotless** [comment]
It's by no means a high priority issue.  Hes still able to be killed it just takes like 4x as long as it should and requires like 2-3x more healing efficiency than normal.  Its just not a balanced, and a very angering battle even when overgeared for it lol.

**Comment by TeoTwawki** [comment]
Doe he never use anything else ever? I'm not seeing a reason, he's got all Jormy's moves available to him (its the same skill list!)

**Comment by Thotless** [comment]
In 4 fights with him i only ever saw him once use something else.  Dragon's Breath or something and it literally set my hp to 1, that or it perfectly did 3900~ damage and just so happened to leave me with 1 hp.  Otherwise yes, that's all he has used

**Comment by TeoTwawki** [comment]
sounds like ***extreme*** bad luck rather than busted skill list. if he can use it once he can use it more than once. Breath dmg is HP based (high his HP, harder it'll hit).

**Comment by Thotless** [comment]
lol....i don't think it was just bad luck, why don't you give it a try yourself?

**Comment by Thotless** [comment]
Like i said I did 4 attempts, each attempt was 20ish mins long, enough for him to use like 50+ abilities per fight.

**Comment by TeoTwawki** [comment]
_lol... I don't think you understand how mobskills work, why don't you learn to code yourself?_

See how that sort of response doesn't work?

**Comment by TeoTwawki** [comment]
Plain and simple: if it used it once the skill DOES work, and can be used again. there is nothing stopping it form selecting any skill it has ever selected. If the dice don't say dragon breath it doesn't dragon breath. I'll fix what I can when I can.

**Comment by R3P0FFXI** [comment]
@Thotless This is where restraint comes into play when attacking mobs. In a case like this you use 2 tanks PLD on the ground and Ninja to tank in the air because ninja can just spam the elemental wheel and /
drk for stun. Of course BLM and Blu cannot just go all out when it is in the air they need to slow dmg just enough to bring it down while the ninja keeps it in position. 

Once again these mobs are not designed to be soloed by a persons little group. You are in an area designed for an alliance to kill and do things.

**Comment by R3P0FFXI** [comment]
@Thotless issue resolved in todays update
