### ISSUE TITLE
Unable to see when KIs drop in Abyssea

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#133]
**Date & Time**:  7/2/15
**Frequency**: Always
**FFXI Client Version**: 30150619_2
**Character Name**: Tarot
**Race**: Hume
**Main Job**: Blu
**Sub Job**: Rdm
**Area & Coordinates**: Abyssea Mis
**Party or Solo**: Party
**NPC Name**: NA
**Monster Name**: Heqet and Cep-Kamuy
**Steps To Reproduce The Issue**: Issue probably due to latest update. KIs seem to not show in chat when they drop. I do not know if this is only contained to abyssea, or if it is all KIs in general, and do not know if this is a DSP issue or legion. Most likely a DSP issue if it applies to all KIs.

**Comment by Strafeous** [comment]
We've farmed about 10 abyssea bosses since the update and when you receive the KI, it comes up as "You've obtained x gil" x is usually around 1500. 
Look for that message instead of the KI message. :P

**Comment by atom0s** [comment]
Just means that the text ids are not aligned properly.

**Comment by R3P0FFXI** [comment]
This is a DSP issue needs to be fixed via PR to DSP

**Comment by Loki79** [comment]
Corrected locally, will toss in a PR to DSP soonish.
