### ISSUE TITLE
Magavan Frock Missing from Body armour AH table.

### ISSUE THREAD

**Issue by Darkara** [LegionDark/Issues#1331]
**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30161227_1

**Character Name**: Darkara

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: MNK99/DNC49

**NPC or Monster or item Name**: Magavan Frock

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/10464/magavan-frock

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Was able to list to AH. When I looked at buy menu Magavan Frock does not show in list. Asked LS, no one can see it.

**Comment by TeoTwawki** [comment]
probably has wrong AH category in the database.

**Comment by TeoTwawki** [comment]
It will auto return on expire

**Comment by R3P0FFXI** [comment]
Already corrected in DSP no custom lines in Legion
