### ISSUE TITLE
CN [S] Rift fix didn't give Abyssite Upgrade when completed

### ISSUE THREAD

**Issue by Walkersauce** [LegionDark/Issues#1332]
**Date & Time**: 01/24/2017 @2312

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  Yes

**Character Name**: Jaundice

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99BLM/49RDM

**NPC or Monster or item Name**: Nympha Eunomia, Kalos Eunomia

**Zone name**: Crawler's Nest [S]

**Coordinates (use `$where`)**: X:62 Y:0 Z:257 (103)

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: Yes, Gwar

**Steps To Reproduce / any other info**:  Last VW NM to upgrade from White Aby II to White Aby III and no upgrade was reported in chat log and not present in Key Items. Those in party who were suppose to get upgrade is Jaundice, Ashen, and Kiari.

**Comment by TeoTwawki** [comment]
From the template: 
```
GITHUB SEES `@MENTIONS`, NOT `@GMCOMMANDS`!!!
```

You tagged a username of 2312. That person now gets a notification for every comment here. 😢

**Comment by Walkersauce** [comment]
whoops, sorry work habit. I got upgrade by talking to Voidwatch officer and then taking KI to Jeuno so I guess this isn't an issue at all. Sorry!!!
