### ISSUE TITLE
Catch all issue for Non-food items that need recipes coded

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1333]
Just add a comment for any non-food craftable item that you actually cannot craft.
Please also include a link to the item on FFXIAH.
Be sure to say why you can't craft it: missing ingredient, recipe errors when attempted, etc...

**Comment by Xenriv** [comment]
Thx for the post, here are a few:

Woodworking:
=100+ test item: Vejovis wand: Kapor Lumber + Black Chocobo Feather, no **Kapor Log** available from logging/AH/Vendors. http://www.ffxiah.com/item/18884/vejovis-wand
=Rockfin tooth recipes: Balsam staff/Echidna's Bow, possibly another source of Gabbrath Horns as well, previously a 3% drop from T6 VW, not listed on item search anymore http://www.ffxiah.com/item/21202/balsam-staff http://www.ffxiah.com/item/21239/echidnas-bow  http://www.ffxiah.com/item/3977/gabbrath-horn  
= Newer recipes like Ames: http://www.ffxiah.com/item/22021/ames, Rhuthenium ingot/ore seems unavailable as well: http://www.ffxiah.com/item/9250/ruthenium-ingot

Bonecrafting: 
=100+ test item: Hajduk ring: 2x Khimaira Horn, currently only dropped from PW, unable to synth. http://www.ffxiah.com/item/11058/hajduk-ring
=Rockfin tooth recipes: Ej Necklace/Donderbuss. http://www.ffxiah.com/item/28404/ej-necklace http://www.ffxiah.com/item/21289/donderbuss
=Unsure if any of the Jinxed/Voodoo will be craftable as VW abjurations aren't available?
=Staunch Tathlum - this is a newer recipe from recent update, mats seem available but not craftable. http://www.ffxiah.com/item/22278/staunch-tathlum
= Tati earrings - http://www.ffxiah.com/item/28526/tati-earring, currently no Gabbrath Horns anymore

Leathercraft:
=Ioskeha Belt - http://www.ffxiah.com/item/26333/ioskeha-belt, Wyrm blood currently not available, unsure if it drops  http://www.ffxiah.com/item/8739/wyrm-blood , recipe isn't craftable either 
=Sweordfaetels - http://www.ffxiah.com/item/28446/sweordfaetels, Sealord Skin/Leather not available http://www.ffxiah.com/item/3548/sealord-leather
=Newer Grips/Straps - Clerisy/Elan/Irenic/Mensch http://www.ffxiah.com/item/22200/clerisy-strap http://www.ffxiah.com/item/22210/elan-strap http://www.ffxiah.com/item/22202/irenic-strap http://www.ffxiah.com/item/22208/mensch-strap

Goldsmithing
= Stikini Ring - http://www.ffxiah.com/item/26183/stikini-ring
= Ravenous Breastplate - http://www.ffxiah.com/item/26875/rav-breastplate, Sealord Leather/Skin not available
= Mache Earring - http://www.ffxiah.com/item/26080/mache-earring, Hepatization ore/Ingot not available - http://www.ffxiah.com/item/8721/hepatizon-ore

Smithing
=Basically anything with Scintilliant Ingot - Luminium ores aren't available and Desynthing Gulfurur's Helm is unrealistic given the quantity of recipes and number of players that would potentially craft this. 
=Anything with Beryllium ore/Ingot - Currently not available http://www.ffxiah.com/item/8723/beryllium-ore
=Anything with Scarletite Ingot - http://www.ffxiah.com/item/687/scarletite-ingot

Clothcraft 
= Yetshila - http://www.ffxiah.com/item/21378/yetshila, last time I tried it didn't work, possibly fixed?

Alchemy  
=Chirich Ring - http://www.ffxiah.com/item/26181/chirich-ring, Defiant Sweat http://www.ffxiah.com/item/9007/defiant-sweat and Plovid Effluvium http://www.ffxiah.com/item/9002/plovid-effluvium haven't been coded/aren't available yet.

There're more recipes but as the game shifts toward end-game content i.e. relic/mythic/empy trials, these items would certainly boost the gear for players to match their ilvl 119 wpns.

**Comment by Raelious** [comment]
Feyweald Lumber (67)-Wind Crystal, Feyweald Log

Recipe is missing from the Databse.

**Comment by Raelious** [comment]
Goldsmithing (100/111)
Yield: Chunk of Snowsteel x 1
Fire Crystal
4 x Chunk of Snowsteel Ore

Not sure if this is missing intentionally as the ores has no use outside of upgrading gear on this server, would certainly help aspiring Goldsmiths skill up some.

**Comment by Raelious** [comment]
Clothcraft (99/110)
Yield: Karakul Thread x 1
HQ 1: Gold Thread x 1
HQ 2: Wamoura Silk x 1
Lightning Crystal
1 x Al Zahbi Sash

**Comment by Raelious** [comment]
http://www.ffxiah.com/item/352/half-partition

Woodworking (83/94)

Yield: Half Partition
HQ1: Half Partition
Earth Crystal
6 x Mahogany Lumber
