### ISSUE TITLE
Kogatasumaru missing mutil hit

### ISSUE THREAD

**Issue by alannor** [LegionDark/Issues#1334]
**Date & Time**: 
27/01/2017

**FFXI Client Version (use `/ver`)**: 
current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Alannor

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
SAM

**NPC or Monster or item Name**: 
Kogarasumaru 119

**Zone name**: 
N/A

**Coordinates (use `$where`)**: 
N/A

**ffxiah.com link (for items issues only)**: 
http://legiondark.com/db/items/21017/kogarasumaru

**Multi-boxing? (multiple clients on same connection)**: 
YES

**Steps To Reproduce / any other info**: 
Kogarasumaru 119 seems to be missing occasionally attacks or thrice stat. Tried with no double triple attack equip, only GK and no double triple attack for 5mins in Aby La. The 75 version was working correctly, mutil hits (lots of multi hits) without any additional equipment.

**Comment by PikaFox** [comment]
Occ attacks twice and thrice are only given during aftermath effects in retail. We once had custom mods on mythics because the aftermath effects didnt work. DSP started trying to add aftermaths, so id guess that would be why some mythics are missing their custom stats. But in reference to your main post; working "correctly" would be only when you have an aftermath effect and even then only when used at 3000 TP.

**Comment by JessLand86** [comment]
Aftermath TP% only affects duration it would seem. https://www.bg-wiki.com/bg/Mythic_Aftermath

**Comment by alannor** [comment]
Well since aftermath doesnt work, I can assume Kogarasumaru good as dead? Or are there plans to apply some kind of interim fix?

**Comment by PikaFox** [comment]
Mythics have different effects for their different Aftermath Tiers. These Tiers are typically listed in order in the weapon item description. Weapons that have been enhanced by Trial of the Magians have more potent and longer lasting Aftermath effects.

As far as i can tell, the wiki is just set up pretty weird in explaining different tp values give different stats.
http://ffxiclopedia.wikia.com/wiki/Aftermath
ffxiclopedia is a bit more straight forward in this with their chart.

And it will be fixed when it will be fixed. We have other priorities we have been doing.
