### ISSUE TITLE
Container Transfers/Crafting Skill

### ISSUE THREAD

**Issue by DrDowo** [LegionDark/Issues#1338]
**Date & Time**: 1/28/2017 

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Dowo

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99WAR/49DNC

**NPC or Monster or item Name**: NA

**Zone name**: NA

**Coordinates (use `$where`)**: NA

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Items in Mog Sage 2 and Mog Wardrobe 2-4 are missing after server transfer process. 

In addition I would like my smithing 100 added after transfer. Thank you!

![img_20170128_000340](https://cloud.githubusercontent.com/assets/25403300/22397208/3971fb7c-e532-11e6-8931-f8db4e75a330.png)

**Comment by Heepster03** [comment]
Is it possible that its stuff that doesn't transfer? Anything over 75 is blocked.

**Comment by DrDowo** [comment]
There was some level 75+ gear but it was definitely not all. I can provide
screenshots if necessary. For instance, I know I am missing some sky gear
and kings abjuration gear.

I believe all 4 containers were at max capacity or very close to it.

Thanks for getting back to me.


On Jan 28, 2017 9:13 AM, "Randall Heep" <notifications@github.com> wrote:

Is it possible that its stuff that doesn't transfer? Anything over 75 is
blocked.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LegionDark/Issues/issues/1338#issuecomment-275853625>,
or mute the thread

**Comment by DrDowo** [comment]
Container issue solved. Just need smithing skill transferred. Thanks!

**Comment by Heepster03** [comment]
Smithing transferred, enjoy~
