### ISSUE TITLE
unable to obtain dynamis jeuno ki

### ISSUE THREAD

**Issue by puffer1221** [LegionDark/Issues#134]
Date & Time: 3/7/15, 10:36 pm gmt
Frequency: Always
FFXI Client Version: 30150619_2
Character Name: Anofreixx
Race: Hume
Main Job: Bst
Sub Job: Blm
Area & Coordinates: Dynamis Jeuno, X:0 Y:0 Z: -101 (5)
Party or Solo: Party
NPC Name: NA
Monster Name: Goblin Golem
Steps To Reproduce The Issue: Gofer and i killed the boss and received the title, but every time i touched the ??? for the ki it did nothing

**Comment by R3P0FFXI** [comment]
NPC ID Shift or Text ID shift check Permanent KI see by chance if you received Item and it just did not show

**Comment by TeoTwawki** [comment]
Or, its the wrong ??? spot you are clicking. There was an issue just liek this in dyna sandy where players kept telling me it was broken because they killed the boss to close to another ??? spot and targeted the wrong one, repeatedly, for multiple runs, till I GM warped in and moved them farther apart to show them wtf I was saying.

**Comment by puffer1221** [comment]
yeah i checked through all my kis and it wasn`t there, i also checked the other ??? in the zone just to be safe inc the one over by maats area since thats where the original ??? would pop.

**Comment by goferffxi** [comment]
Anofreixx and myself (using Gofer and Mule, Gofertwo) killed the Boss and clicked the ??? where it would normally be. The KI has not appeared in the inventory of my Mule (Gofertwo) Unable to check with Gofer as I had already completed Jeuno back in may.

**Comment by TeoTwawki** [comment]
> where it would normally be

it won't be one already up, it would spawn on the bosses death. You know what..screw all this I'm making all dyna boss just hand it out in on death. If it dies you get KI prob solved for forever, SE's ID shifts can kiss Teo's pale white rear-end.

**Comment by TeoTwawki** [comment]
There, from now on anyone in the killers alliance (or party) is automatic cleared without having to click a damn thing. And this is already live in server. The scritp will still try to spawn a ??? spot but if it doesn't at slate people who were already present don't have a problem.

**Comment by TeoTwawki** [comment]
And btw, I checked the IDs and there is no ID issue.
