### ISSUE TITLE
Abyssea-Tahrongi NM - Halimede

### ISSUE THREAD

**Issue by Xenriv** [LegionDark/Issues#1341]
**Date & Time**:  1/28/2017 7:30 PM EST

**FFXI Client Version (use `/ver`)**:  Current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Xenriv

**Nation**: Bastok

**Job(level)/Sub Job(level)**: THF/DNC

**NPC or Monster or item Name**:  Halimede

**Zone name**:  Abyssea-Tahrongi

**Coordinates (use `$where`)**: -234 -601 15

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/2915/hq-cli-wing

**Multi-boxing? (multiple clients on same connection)**:  Yes

**Steps To Reproduce / any other info**:   NM Halimede, spawned by trading a H.Q. Clinoid Wing to the ??? at G-11 in aby-tahrongi does not work. This NM is part of the Chloris pathway, used for various empyrean weapons and armor upgrades.

**Comment by R3P0FFXI** [comment]
https://github.com/LegionDark/Issues/issues/1327
