### ISSUE TITLE
Incorrect Abyssea NM Spawns (??? NPC at wrong location or missing)

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1342]
**Date & Time**: 1/29/17

**FFXI Client Version (use `/ver`)**: 
30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: 
Tarot

**Nation**: 
San

**Job(level)/Sub Job(level)**: 
99 Pld

**NPC or Monster or item Name**: 
http://ffxiclopedia.wikia.com/wiki/Chhir_Batti (Aby Vunkerl, ??? in wrong spot)
http://ffxiclopedia.wikia.com/wiki/Khalkotaur (Aby Vunkerl, missing ???)
http://ffxiclopedia.wikia.com/wiki/La_Theine_Liege (Aby la theine, missing ???)

**Zone name**: 
Aby Vunkerl

**Coordinates (use `$where`)**: 
F-6 - -359, -31, 332 (approx)

H-9 - -117, -40, -201 (approx)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
The ??? for Chhir is where Khalk should be. It accepts the Djinn Ashes, but spawns the mob where it should spawn all the way at F-6. Khalk seems to be entirely missing a spawn altogether.

**Comment by JessLand86** [comment]
https://github.com/LegionDark/Issues/issues/1297 for Khalk.

**Comment by TeoTwawki** [comment]
Could you turn this issue into a list of all the ??? points in abyssea that do not match?
Except for **Abyssea - Konschtat (Zone 15)** and **Abyssea - Altepa (Zone 218)** (Those 2 are gonna need different kind of attention..)

**Comment by TeoTwawki** [comment]
Basically the problem is the scripts have the wrong number in their names, over in DSP. Which is Legion's fault since this is where those scripts even came from. They didn't get in before ID shifting had already wrecked havok.

**Comment by PikaFox** [comment]
Updated title, added another spawn missing

**Comment by ritonami** [comment]
another aby nm is Ovni doesnt seem to land

**Comment by TeoTwawki** [comment]
ovni's problem is he needs to agro and trigger his animation sub change etc..I'll try and hotfix him sometime tonight

**Comment by Baucant** [comment]
Date & Time: 02/05/2017

FFXI Client Version (use /ver):
30161206_3

Server's Expected Client Version matches, yes/no? (use $ecv): Yes

Character Name:
Baucant, Dapunted and Jukebox

Nation:
San

Job(level)/Sub Job(level):
99 Thf , 99 Whm, 99 Brd

NPC or Monster or item Name:
http://ffxiclopedia.wikia.com/wiki/Halimede (aby-Tahrongi correct location; no response to trade)
http://ffxiclopedia.wikia.com/wiki/Vetehinen (aby-Tahrongi correct location; no response to trade)

Both mobs required to pop Chloris

Zone name:
Aby-Tahrongi

Coordinates (use $where):
X:-235 Y:15 Z:-602 (245)
X:78 Y:0 Z:-433 (86)

ffxiah.com link (for items issues only):
http://www.ffxiah.com/item/2915/hq-cli-wing
http://www.ffxiah.com/item/2916/hq-lim-pincer

Multi-boxing? (multiple clients on same connection):
Yes

Steps To Reproduce / any other info: tried trading the correct items. Tried trading the "other item". Tried zoning and logging out and in..

**Comment by TeoTwawki** [comment]
@Baucant that "no response to trade" is generally going to mean one of:

1. It is up from a previous spawn but wandered far away without depopping (NM in need of depop modifier)  

2. An identically named NPC is mistakenly at that spot (NPC's got scrambled, expecting ton of this)  

3. It is spawning the NM way off in middle of nowhere (by now there shouldn't be many if any of this left)

**Comment by JessLand86** [comment]
Treble Noctules is spawnable with Bloody Fang at 185 -20 -151
Ophanim is spawnable with Bloodshot hecteye at -195 -16- 165 
Hedetet is spawnable with Venomous Scorpion Stinger and Clump of Acidic Hummus at -279 7 126
Gancanagh is spawnable with Alkaline Humus at 74 11 -51
Chukwa is a times spawn and I verified he was up.

All the ???'s are in the correct spot and Chloris is spawnable.

**Comment by Baucant** [comment]
Treble Noctules is suppose to spawn with Bloody fang & Exorcised Skull (comes from Cannered Noz[working})
Ophanim is suppose to spawn with Bloodshot Hecteye, Shriveled Wing (comes from Halimede [not working]) & Tarnished Pincer (comes from Vetehinen [not working])

Now I'm good with the changes it is a lot less running around

**Comment by arkooqymoya** [comment]
Date & Time: 02/07/2017

FFXI Client Version (use /ver):
30161206_3

Server's Expected Client Version matches, yes/no? (use $ecv): Yes

Character Name:
cornfield, boos,chinaese 

Nation:
bastok

Job(level)/Sub Job(level):
99pld/49war

NPC or Monster or item Name:

http://ffxiclopedia.wikia.com/wiki/Apademak

Zone name:
Abyssea - Uleguerand

Coordinates (use $where):
X:-332 Y:-156 Z:346(215) theres another 2 question mark near by this popsite ,

ffxiah.com link (for items issues only):
n/a

Multi-boxing? (multiple clients on same connection):
Yes
Steps To Reproduce / any other info:  we have the KI which supose to pop the Apademak but its not coming out of the pop site, and the qustion mark is not giving the info that usually giving the ki needed infomation.

**Comment by simthra** [comment]
Also Itzpapalotl is not spawning @ X: 436, Y: 20, Z: -184

**Comment by Heepster03** [comment]
All addressed at https://github.com/LegionDark/Issues/issues/1364
