### ISSUE TITLE
Error Code: FFXI-3305

### ISSUE THREAD

**Issue by Vaneticorum** [LegionDark/Issues#1343]
**Date & Time**:  01-29-2017

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Vaneticorum and Queenwarrior

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Vanet - THF44/WAR22 and Queen - WHM38/RDM19

**NPC or Monster or item Name**: N/A

**Zone name**: Eastern Altep Desert

**Coordinates (use `$where`)**: Not sure.

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No. On Same connection

**Steps To Reproduce / any other info**: 
Both of the characters are unable to log in and are showing as Online. Attempted to log in using a different Internet connection but the characters will not disconnect. Please disconnect them both if I possible. I can also submit another ticket just for Queenwarrior if necessary.

**Comment by PikaFox** [comment]
Server didnt restart properly. Should be resolved now.
