### ISSUE TITLE
Error Code FFXI - 3305

### ISSUE THREAD

**Issue by UngreasedTeflon** [LegionDark/Issues#1344]
**Date & Time**: 01/29/17 4 PM EST

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Tef

**Nation**: Bastok

**Job(level)/Sub Job(level)**: WHM75/BLM37

**NPC or Monster or item Name**: N/A

**Zone name**: Zeruhn Mines

**Coordinates (use `$where`)**: Unsure

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Exp party, was disconnected, unable to log back in.  Character is still showing logged in.

**Comment by PikaFox** [comment]
Server didnt restart properly on crash. Is up now.
