### ISSUE TITLE
Error 3305

### ISSUE THREAD

**Issue by Wolfwood-san** [LegionDark/Issues#1345]
**Date & Time**: 
1/29/2017  5:00PM

**FFXI Client Version (use `/ver`)**: 
30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Wolfwood

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
PLD60/WAR30

**NPC or Monster or item Name**: 
N/A

**Zone name**: 
Northern San d'Oria

**Coordinates (use `$where`)**: 
Don't know.

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Outside of moghouse when disconnected, can not log back in.  Character showing logged in.

**Comment by Heepster03** [comment]
Did you close the client and give yourself 5min or so to log back in? Are you getting stuck in downloading data?

**Comment by PikaFox** [comment]
Server didnt restart properly on crash. Is up now.
