### ISSUE TITLE
Crafting Trasfer if you could assist please

### ISSUE THREAD

**Issue by Cloudlyon** [LegionDark/Issues#1347]
**Date & Time**: 
1/30/17 6:54 AM

**FFXI Client Version (use `/ver`)**: 
30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Cloudlyon

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99 Blue Mage/49 war

**NPC or Monster or item Name**: 
NA

**Zone name**: 
Aht urghan whitegate

**Coordinates (use `$where`)**: 
X-16 Y-6 Z-37 (201)

**ffxiah.com link (for items issues only)**: 
NA

**Multi-boxing? (multiple clients on same connection)**: 
NA

**Steps To Reproduce / any other info**: 
I would like my crafts imported please 

![screenshot 1](https://cloud.githubusercontent.com/assets/25431688/22422488/9c14336a-e6ba-11e6-8669-eb8e485ed87e.png)

**Comment by Cloudlyon** [comment]
Goldsmithing im so sry forgot to add that in there ; ;

**Comment by Heepster03** [comment]
Crafts xferred. Enjoy~
