### ISSUE TITLE
abyssea nms

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#1349]
**Date & Time**: 1/30/2017 7:50 pm

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: 
Ritonami

**Nation**: 
windurst

**Job(level)/Sub Job(level)**: 
thf 99/dnc

**NPC or Monster or item Name**: 
blanga,Yaguarogui, chione

**Zone name**: 
abyssea-ulegurand

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
chione doesnt spawn, and the other two, possibly more only tried these two, only require half the items to spawn them

**Comment by TeoTwawki** [comment]
@ritonami thanks we'll get them sorted out when we can, leaving note here for the other GMs. If you find anymore please comment in the other issue.

@LegionDark/gm  please add to #1342 with info I need to fix that (see my comment in that issue) then close this.

**Comment by Heepster03** [comment]
All addressed at https://github.com/LegionDark/Issues/issues/1364
