### ISSUE TITLE
Dynamis Jeuno - Unable to get win

### ISSUE THREAD

**Issue by Megamoo** [LegionDark/Issues#135]
**Date & Time**: 7/3/2015 11pm and 7/5/2015 1:30 am
**Frequency**: 2 out of 2 attempts
**FFXI Client Version**: 30150619_2
**Character Name**: Megamoo
**Race**: Hume
**Main Job**: Samurai
**Sub Job**: Warrior
**Area & Coordinates**: Dynamis - Jeuno @where X:0 Y:0 Z-100 
**Party or Solo**: Party
**NPC Name**: N/A
**Monster Name**: Goblin Golem
**Multi-boxing? (multiple clients on same connection)**: Yes, Megastrafe(BRD) and Megameow(WHM)
**Steps To Reproduce The Issue**: Beat the Megaboss in Dynamis - Jeuno two days in a row, clicked the ??? after killing it and didn't get a KI on any character. Tatako was there with us the first day and couldn't get a KI. Strafeous was in the party both days and couldn't get a KI either.

**Comment by R3P0FFXI** [comment]
KI is dropped with win when you beat the boss the KI should be given to you automatically now

**Comment by TeoTwawki** [comment]
#134
