### ISSUE TITLE
Items grayed out in "Items" inventory

### ISSUE THREAD

**Issue by ffxijuggalo** [LegionDark/Issues#1350]
**Date & Time**: 1/30/2017 10:27PM

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Juggalo

**Nation**: Windurst

**Job(level)/Sub Job(level)**: THF99/DNC49

**NPC or Monster or item Name**: Gausebit Grass / Tenshodo Invite

**Zone name**: Aht Urhgan Whitegate

**Coordinates (use `$where`)**: X:-99 Y:0 Z:-79 (0)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Screenshot included showing these items grayed out as if they're in use by something. Have tried zoning/checking items and logging off/on and checking items. Neither of these methods have worked to remedy this.

![juggalo_2017 01 30_223159](https://cloud.githubusercontent.com/assets/22580624/22452401/2018714a-e73c-11e6-8d2c-16a7dd4b3c4c.png)

**Comment by atom0s** [comment]
This appears like the items are stuck in your bazaar and your nameflags got altered to remove the bazaar flag. Try opening a bazaar and seeing if you can alter the price on anything then remove the bazaar again.

**Comment by ffxijuggalo** [comment]
Yessir, that did it. Didn't have a bazaar up but those items were indeed for sale. So i removed the prices on them and not they're accessible again.
