### ISSUE TITLE
Verdical Conflux missing in Pashhow Marshlands [S]

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1351]
**Date & Time**: 
1/31/2017 2136

**FFXI Client Version (use `/ver`)**: 
30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Astraea

**Nation**: 
n/a

**Job(level)/Sub Job(level)**: 
n/a

**NPC or Monster or item Name**: 
Verdical Conflux

**Zone name**: 
Pashhow Marshlands [S]

**Coordinates (use `$where`)**: 
342 25 -159

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
Verdical conflux is missing.

**Comment by TeoTwawki** [comment]
Hotfixed.
