### ISSUE TITLE
my white stratum abyssite ki is missing.

### ISSUE THREAD

**Issue by arkooqymoya** [LegionDark/Issues#1353]
Date & Time: 2017/2/3

FFXI Client Version (use /ver):
30161227_1

Server's Expected Client Version matches, yes/no? (use $ecv):
yes

Character Name:
arkoo arkooqymoya corn doctor maomao(its my ls people's char ,he lost this ki too)

Nation: bastok

Job(level)/Sub Job(level):
N/A

NPC or Monster or item Name: the char's white stratum abyssite

Zone name: n/a

Coordinates (use $where):n/a

ffxiah.com link (for items issues only):

Multi-boxing? (multiple clients on same connection):
yes

Steps To Reproduce / any other info:
i was helped people with voidwatch ki upgrading ,but with the process of ki upgrade my 

jeuno ki(the white stratum abyssite)was lost, i was hoping someone else would have the same 

 problem and reported it but until today, i havnt search that yet .

**Comment by TeoTwawki** [comment]
@arkooqymoya  Apologies that this sat so long

@LegionDark/gm please use `$addkeyitem` to give effected players the WHITE_STRATUM_ABYSSITE, I have introduces a hotfix until I have time to properly rework the rest of VW

**Comment by Heepster03** [comment]
So far, I've seen Maomao on and gave him the KI. Haven't seen the others yet.

**Comment by TeoTwawki** [comment]
Handled Arkoo, Arkooqymoya, Corn and Doctor. I think soem other players not listed were effected, Arkoo said he'd let us know.

**Comment by TeoTwawki** [comment]
anyone still effected will need to open a new ticket
