### ISSUE TITLE
AV drops

### ISSUE THREAD

**Issue by alannor** [LegionDark/Issues#1355]
**Date & Time**: 
13:20

**FFXI Client Version (use `/ver`)**: 
current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
YES

**Character Name**: 
Alannor

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
BLU

**NPC or Monster or item Name**: 
Absolute virtue

**Zone name**: 
Al'Taieu

**Coordinates (use `$where`)**: 
K11

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
YES

**Steps To Reproduce / any other info**: 
Killed AV 3 times 0 drops, even with 3 THFs 2TH12 one with TH13, doesnt seem like 5-7% drop rate on the rings. Even if working as intended would question why it should be so difficult. We already spend endless hours farming Ix'Aern DRK pops, (48 organs for 1 pop with 1/3 chance on deed) AV is lottery pop from JOL, usually 1/3, and if drop rate on rings are so low 0 rings for 3 kills, you have to wonder whats the point?

**Comment by TeoTwawki** [comment]
A lot of drop rates are unintentionally lower than they should be, I dunno if this is one of them but I will be checking on it while I fix some of them tonight.

**Comment by alannor** [comment]
Thanks Teo. Sorry for the rant, just felt like waste of time after spending probably 100 hours collectively for the LS farming pops only to have 0 drops.

**Comment by TeoTwawki** [comment]
its cool, and totally understandable. its got a low % chance to drop "a" ring, and then which ring it drops is an equal chance among all of them. which overall makes getting any particular ring that you actually wanted pretty rare. Combined with the fact I see no other loot on him at all, this is pretty bad, will discuss changing it with staff. I know drops are being re-organized but we shouldn't be removing and reducing rates before adding the replacement drops fully at the same time. Going to close this out and take it up with the team for adjustment in next maint.

**Comment by alannor** [comment]
Got it thanks Teo

**Comment by R3P0FFXI** [comment]
@alannor It was always intended other items would be added to AV. Sadly it is currently working as somewhat intended. As we are discussing a lot right now among staff regarding drops as well as waiting on the full results of the survey it may be a little bit before this is rectified.
