### ISSUE TITLE
the pop site's question mark of the sobek is missing.

### ISSUE THREAD

**Issue by arkooqymoya** [LegionDark/Issues#1356]
**Date & Time**: 2017/2/5 13:03

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**:arkoo  

**Nation**: bastok

**Job(level)/Sub Job(level)**: 99thf/49dnc

**NPC or Monster or item Name**: sobek

**Zone name**: Abyssea - Misareaux

**Coordinates (use `$where`)**: x:541 y:16 z:-357(75)

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: its the sobek info on wikia http://ffxiclopedia.wikia.com/wiki/Sobek
    the question mark of pop site is missing.

**Comment by JessLand86** [comment]
Found the ??? for Sobek at (I-11)

**Comment by TeoTwawki** [comment]
#1342

**Comment by Heepster03** [comment]
Addressed in https://github.com/LegionDark/Issues/issues/1364
