### ISSUE TITLE
Vial of Shrouded Sand Ki missing can't do dynamis

### ISSUE THREAD

**Issue by salazer** [LegionDark/Issues#1357]
**Date & Time**: 2/5/17 7:00 pm est

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: salazer

**Nation**: bastok

**Job(level)/Sub Job(level)**: thf99/dnc49

**NPC or Monster or item Name**: Vial of Shrouded Sand

**Zone name**: dynamis windrust

**Coordinates (use `$where`)**: windurst wall trail marking

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: tried to see if its a cut scene i missed but i'm rank 6 and i finished CoP and Roz  i've been to Xarcabard lot of time's but no city trail marking will let me in and  i can enter dream world area in dunes

**Comment by JessLand86** [comment]
Sounds like the same issue as #1294. I'll check players vars.

**Comment by JessLand86** [comment]
![astraea_2017 02 05_201148](https://cloud.githubusercontent.com/assets/22607214/22631659/62df5988-ebdf-11e6-85aa-edbe14d80245.png)

**Comment by TeoTwawki** [comment]
yep same issue with same solution

**Comment by TeoTwawki** [comment]
Player got cs.
