### ISSUE TITLE
stat boots are not workign 

### ISSUE THREAD

**Issue by zeos101** [LegionDark/Issues#1359]
**Date & Time**:  2-7-2017 5:00 AM

**FFXI Client Version (use `/ver`)**:  301612271

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  Yes

**Character Name**:  klang

**Nation**:  batok

**Job(level)/Sub Job(level)**:  thf 99/dnc 49

**NPC or Monster or item Name**:  NA

**Zone name**:  NA

**Coordinates (use `$where`)**:  NA

**ffxiah.com link (for items issues only)**:  all food and weapons

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**:  when I have a hellsteak +1 there is no atk stat boost now with my  mantodea harpe it is not giving any stat bonus to str or agi  both are to be 8+

**Comment by TeoTwawki** [comment]
Relog, nothings wrong with the food's effect script so any stat abnormalities are via your temporary character data or your gear. If after relogging unqeuip all gear and see if you still have wrong base stats

**Comment by atom0s** [comment]
Non-issue, lack of response. Closing. Repeat steps as Teo mentioned to correct your stats if they are bugging out.
