### ISSUE TITLE
San d'Oria rank9-2 mission

### ISSUE THREAD

**Issue by unknownwolf** [LegionDark/Issues#136]
Date & Time: 05/07/15
Frequency: Always
FFXI Client Version: 30150619_2
Character Name: Volks
Race: Elvaan
Main Job: Mnk
Support Job: Dnc
Area and Coordinates: Northern San d'Oria
Party or Solo: Solo
NPC Name: None
Monster Name:
Steps:
1. Beat the battlefield 9-2.
2.Zone in Northern San d'Oria did not receive cutscene
3.
<Tried to keep on to the next step of the mission and did not receive any cutscene from any step beyond northern san doria. Notice that prince trion during the second part of the battlefiel wasnt moving or doing anything. I was still able to beat it solo and receive cutscene after the battle.> 

BG Wiki link for additional information:  https://www.bg-wiki.com/bg/San_d%27Oria_Mission_9-2

**Comment by TeoTwawki** [comment]
Were you multi boxed at all / multiple players from same internet connection? Did the fight go normally with Trion Alive and helping at the end? Your variable didn't increment on BCNM win, and that script looks legit, so for it to break down had to be the multibox bug or a problem inside the BCNM battle itself causing the wrong leavecode. https://github.com/DarkstarProject/darkstar/blob/e41c17615cdbcba03023f5961b875fd93e84e1fe/scripts/zones/QuBia_Arena/bcnms/heir_to_the_light.lua#L59

**Comment by TeoTwawki** [comment]
@R3P0FFXI if not a multiboxing issue, send it to DSP because this is like the 5th person to have problems at this exact spot.

**Comment by unknownwolf** [comment]
I wasnt using another character and tried twice the battlefield and still no cutscene.

**Comment by TeoTwawki** [comment]
ok, thanks

**Comment by unknownwolf** [comment]
Maybe I should try again with the new updated version?

**Comment by TeoTwawki** [comment]
@R3P0FFXI manually bumping up his mission status so he's taken care of, once you inform DSP of their bug close this,

**Comment by TeoTwawki** [comment]
@unknownwolf you can't log into game if your on the older client right now, Legion got updated Tuesday.

**Comment by unknownwolf** [comment]
How do I inform DSP of their bugs(a bit off subject, sorry) ?

**Comment by TeoTwawki** [comment]
That message was to R3P0FFXI

**Comment by R3P0FFXI** [comment]
Unknown catch me on IRC so I can complete the mission for you

**Comment by Superman78** [comment]
I also just did this mission. I only had valentine logged in, solod the bcnm, and when zoning into North Sandy I didn't receive a cs either. I tried talking to Halver, the king, and mission gate guard with no results.

**Comment by TeoTwawki** [comment]
This is already reported to DSP now.

**Comment by TeoTwawki** [comment]
@Superman78 open a new issue for it, sorry dude I need to kill this one.

@unknownwolf I thought I already fixed you, if you still need fixed open a new issue please, and I apologize for the confusion but SOME PEOPLE have gotten idiotic about my instructions so I needed to close this one out so they didn't get even more confusion.

**Comment by TeoTwawki** [comment]
@R3P0FFXI https://github.com/DarkstarProject/darkstar/issues/1876 when AlexCA beats you to reporting something, its time to be ashamed.
