### ISSUE TITLE
Level Sync Bug

### ISSUE THREAD

**Issue by cleanermc** [LegionDark/Issues#1360]
**Date & Time**: 11.02.2017 2:00 PM

**FFXI Client Version (use `/ver`)**:  301612271

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Kacie

**Nation**: Bastok

**Job(level)/Sub Job(level)**: RDM99/BLM49

**NPC or Monster or item Name**: NA

**Zone name**: NA

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: NA

**Steps To Reproduce / any other info**:  First of you need more then 3 Partymember. Then when you in Party you need to Sync. After this 1 member of the Party has to leave (but not the Sync member) by Zoneing or Warp or Tele. After this your PT is stuck in LvL Sync and if the Sync leaves then it is still stuck.

**Comment by Jessland86** [comment]
Taken care of in today's maintainance.
