### ISSUE TITLE
Aerial Armor not working

### ISSUE THREAD

**Issue by Vaneticorum** [LegionDark/Issues#1361]
**Date & Time**:  2/11/17 & 7:24 CST

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Queenwarrior

**Nation**: Windurst

**Job(level)/Sub Job(level)**: SMN45/WHM24

**NPC or Monster or item Name**: Garuda

**Zone name**: All (Western Altepa atm)

**Coordinates (use `$where`)**: X:393 Y:0 Z:262 (44)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No / Yes

**Steps To Reproduce / any other info**: Attempting to use Garuda's BP "Aerial Armor". There is no animation and the ability does not apply to the party. Tried this in multiple zones. Probably a DSP thing. Huh?

**Comment by TeoTwawki** [comment]
Since legion has zero changes to it, yeah its a bug in their end. Someone has to go tell them. https://github.com/DarkstarProject/darkstar/issues/new

**Comment by Vaneticorum** [comment]
Reference DSP Ticket: https://github.com/DarkstarProject/darkstar/issues/3709

**Comment by Raelious** [comment]
@TeoTwawki  seems to have been fixed, just tested it the move now works and has an animation applied to it.
