### ISSUE TITLE
Missing NPC in Altar Room

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1362]
**Date & Time**: 
2/11/17 -- 16:27:50

**FFXI Client Version (use `/ver`)**: 
30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Raelious

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99THF/49DNC

**NPC or Monster or item Name**: 
Hooknox

**Zone name**: 
Altar Room

**Coordinates (use `$where`)**: 
X:-338, Y:19, Z:-93 (131)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
The NPC is missing to start the quest "A Moral Manifest?" zoned serveral times the npc doesnt show up, not sure if its implemented in DSP or not yet.

**Comment by TeoTwawki** [comment]
Those quests don't exist yet. Tons of NPCs and quests that haven't been implemented in DSP.
