### ISSUE TITLE
Aby - Vunkerl; Durinn

### ISSUE THREAD

**Issue by Acedffxi** [LegionDark/Issues#1363]
**Date & Time**: 2/12/17

**FFXI Client Version (use `/ver`)**:  30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  Yes

**Character Name**:  Freelot

**Nation**:  Sandy

**Job(level)/Sub Job(level)**:  SAM99/DNC49

**NPC or Monster or item Name**: Durinn

**Zone name**:  Abyssea - Vunkerl

**Coordinates (use `$where`)**: **Date & Time**:  2-12-17

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**:  Freelot

**Nation**:  Sandy

**Job(level)/Sub Job(level)**: SAM99/DNC49

**NPC or Monster or item Name**:  Durinn

**Zone name**:  Abyssea - Vunkerl

**Coordinates (use `$where`)**:   @ X: -571, Y: -47, Z: -570

**ffxiah.com link (for items issues only)**:  N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
When clicking Durinn's "???", it is unresponsive and you are unable to spawn him.

**Comment by Heepster03** [comment]
Addressed at https://github.com/LegionDark/Issues/issues/1364
