### ISSUE TITLE
All Known Abyssea Issues

### ISSUE THREAD

**Issue by Heepster03** [LegionDark/Issues#1364]
**Date & Time**: 2/13/17 at 2338

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: [GM] Halkuras

**Nation**: Bastok

**Job(level)/Sub Job(level)**: N/A

**NPC or Monster or item Name**: N/A

**Zone name**: N/A

**Coordinates (use `$where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: Each comment below will address each zone individually.

**Comment by Heepster03** [comment]
** Abyssea-Tahrongi **

Halimede
	- unspawnable
	
Orphanim
	- needs pop items adjusted
	
Vetehinen
	- unspawnable

**Comment by Heepster03** [comment]
** Abyssea-Attohwa **

Berstuk
	- ??? at (-404,3,-198)
	- should be at (-279,-4,-38)
	
Drekavac
	- ??? at () = unspawnable
	- should be at (-159,0,219)
	
Gaizkin
	- ??? at (-538,-6,-25)
	- should be at (-130,0,2)
	
Itzpapalotl 
	- ??? at (351,19,209)
	- should be at (439,20,-193)

Kampe
	- ??? at (-539,-12,-75)
	- should be at (-404,3,-198)
	
Kharon
	- ??? at (-130,0,2)
	- should be at (-403,-4,200)
	
Maahes
	- mob needs adjusting
	- ??? at (-279,-4,-38)
	- should be at (214,20,-94)
	
Mielikki
	- ??? at (199,20,108)
	- should be at (481,20,39)
	
Nightshade
	- ??? at (214,20,-94)
	- should be at (411,19,13)
	
Smok
	- ??? at (481,20,39)
	- should be at (-529,-5,-40)
	
Svarbhanu
	- ??? at (-159,0,219)
	- should be at (-539,-12,-75)
	
Titlacauan
	- ??? at (-546,-4,-12)
	- should be at (-389,-3,245)
	
Ulhuadshi
	- ??? at (-389,-3,245)
	- should be at (361,20,199)
	
Wherwetrice
	- ??? at (411,19,13)
	- should be at (199,20,108)

**Comment by Heepster03** [comment]
** Abyssea-Misareaux **

Funereal Apkallu
	- ??? at (180,-23,287)
	- should be at (209.-23.321)
	- need to remove the 15min respawn (it's a force pop)
	
Karkatakam
	- needs pop items adjusted
	
Nonno
	- need to remove the 1min respawn (it's a force pop)
	- mob needs adjusting
	
Sirrush
	- ??? at (428,23,-376)
	- should be at (346,15,-437)
	- mob spawn needs to be moved to (346,15,-437)
	
Sobek
	- ??? at (346,15,-437)
	- should be at (428,23,-376)
	- mob spawn needs to be moved to (428,23,-376)
	
Tuskertrap
	- unspawnable due to the popitem unobtainable (itemid 3096)

**Comment by Heepster03** [comment]
** Abyssea-Vunkerl **

Armillaria
	- named NPC instead of Armillaria
	
Chhir Batti
	- ??? at () = nonspawnable
	- should be at (-395,-31,357)
	
Durinn
	- ??? at (402,-31,405)
	- should be at (-555,-47,-565)
	
Karkadann
	- ??? at (-555,-47,-565)
	- should be at (-157,-32,118)
	
Khalkotaur
	- ??? at (-395,-31,357)
	- should be at (-239,-40,-120)
	
Rakshas
	- 17666492 (mobid)
	- should be a tiger, currently a gargouille
	
Sedna
	- ??? at () = nonspawnable
	- should be at (402,-31,405)

**Comment by Heepster03** [comment]
** Abyssea-Uleguerand **

Anemic Aloysius
	- ??? at (457,-52,125)
	- should be at (440,-51,141)
	
Apademak
	- ??? at (-614,-39,-15)
	- should be at (-332,-156,346)
	
Blanga
	- needs popitems adjusted
	- ??? at (-116,-175,4)
	- should be at (-614,-39,-15)
	
Dhorme Khimaira
	- currently nonspawnable
	- needs popitems adjusted
	
Koghatu
	- ??? at (-199,-176,155)
	- should be at (-116,-175,4)

Kur
	- needs respawn timer adjusted
	
Yaguarogui
	- needs popitems adjusted

**Comment by Heepster03** [comment]
** Abyssea-Grauberg **

Ningishzida
	- currently nonspawnable
	- needs popitems adjusted
	
Teekesselchen
	- mob spawn needs to be moved to (320,47,644)
	
Teugghia
	- currently nonspawnable (site says not implemented)

**Comment by TeoTwawki** [comment]
Thanks Heep. Now we can get these taken care of.

**Comment by Heepster03** [comment]
Finally the time has arrived, all of the above fixes are submitted to DSP.

**Comment by TeoTwawki** [comment]
Bless you for taking so much of that off my plate.

**Comment by R3P0FFXI** [comment]
issue resolved in todays update
