### ISSUE TITLE
Can read chat of an LS when I don't have 1 equipped. 

### ISSUE THREAD

**Issue by dr4luc0n** [LegionDark/Issues#1365]
**Date & Time**:  2/14/2017 @ 8:58am EST

**FFXI Client Version (use `/ver`)**:  30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  30161227_1

**Character Name**:  Dralucon

**Nation**:  Sandoria

**Job(level)/Sub Job(level)**:  57THF/28DNC

**NPC or Monster or item Name**: 

**Zone name**:  Crawler's Nest

**Coordinates (use `$where`)**:  X: 352 Y: -32 Z: -22 (119)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  Yes

**Steps To Reproduce / any other info**:  No steps to reproduce, but I don't have an LS equipped, I zoned into Crawler's Nest and then I can read the chat of a LS named "TheHighCouncil" but can't type in it because I don't have an LS equipped.

**Comment by tb1** [comment]
I had this happen to me once with BelCool, I had to relog to stop it (if I recall).  I was never able to reproduce it, and just assumed it was DSP being DSP.

**Comment by Jessland86** [comment]
I think this was resolved. I haven't seen this issue happen in quite a long time. If it happens again please open a new ticket.
