### ISSUE TITLE
NPC Leepe-Hoppe not giving me a key item

### ISSUE THREAD

**Issue by Meokazi** [LegionDark/Issues#1366]
**Date & Time**: 
6:30pm UTC

**FFXI Client Version (use `/ver`)**: 
uh...V 3.0.03

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30161227_1

**Character Name**: 
Meokazi

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
SAM99/WAR49

**NPC or Monster or item Name**: 
Leepe-Hoppe

**Zone name**: 
Windurst Waters

**Coordinates (use `$where`)**: 
X:15 Y:-9 Z:-193 (131)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Leepe-Hoppe has given me the quest to collect the 6 whispers however he is not letting me turn them in for the Moon Babble key item to fight Fenrir. He keeps complaining about being hungry.

**Comment by atom0s** [comment]
It looks like you have the quest 'Food For Thought' accepted by the same NPC. This quest takes priority over the whispers so you will need to complete it first before turning in the whispers.

**Comment by R3P0FFXI** [comment]
@Meokazi is this still an issue @LegionDark/gm

**Comment by R3P0FFXI** [comment]
No Player reply closing issue @Meokazi
