### ISSUE TITLE
$ command not displaying

### ISSUE THREAD

**Issue by piglorian** [LegionDark/Issues#1367]
**Date & Time**: 
2/14/17 7:45 CST 

**FFXI Client Version (use `/ver`)**: 
30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
No

**Character Name**: 
Piglorian and Lilpig

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
All

**NPC or Monster or item Name**: 
N/A

**Zone name**: 
All

**Coordinates (use `$where`)**: 
Can't retrieve this information

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
When attempting any $ command, it will not display the text on Piglorian, but I can type the same text on Lilpig and it will display the text.  I have checked chat filters/settings across both characters and the are the same.  EX: On Piglorian I type $trial and does not display any text.  On Lilpig, I type $trial and it says that I have no trials.

**Comment by atom0s** [comment]
Are you using Ashita or Windower? Try unloading all addons and plugins to see if they are interfering with anything as well.

**Comment by piglorian** [comment]
I am using Ashita and I get the same results when I unload everything.  It is also character based because it works on my mule on the same PC.

**Comment by piglorian** [comment]
On Piglorian, I set the chat filters back to default.  Also, I created a character on the same account and was able to see the text from $ commands, but not on my main.

**Comment by piglorian** [comment]
Is there any way someone could tell me what trials i have active and where I am on them?

**Comment by TeoTwawki** [comment]
Question. Did you try other commands besides `$trial`?

**Comment by piglorian** [comment]
I did.  Doesn't matter which command, there will be no text displayed.

**Comment by piglorian** [comment]
Also, it isn't a matter of inputting the wrong command.  I am able to use the commands and see the text on the same account with a different character and also with a character on a completely different account.

**Comment by TeoTwawki** [comment]
r3 said he was going to get in touch with you to investigate

**Comment by piglorian** [comment]
Thanks!

**Comment by TeoTwawki** [comment]
Sorry one of use should have posted that sooner lol..I just figured he'd be talking to you by now. Check forum pm's in case.

**Comment by atom0s** [comment]
Debugged this tonight, found out the issue. You have yourself blacklisted.

Type /blacklist

And then remove yourself lol.

**Comment by TeoTwawki** [comment]
I deleted you off your own blacklist. I didn't even know you could DO that...
