### ISSUE TITLE
Job abilities

### ISSUE THREAD

**Issue by goferffxi** [LegionDark/Issues#137]
**Date & Time**: 5/7/2015     21:23
**Frequency**:Always
**FFXI Client Version**: 30150629_2
**Character Name**: Gofer
**Race**: Taru
**Main Job**: WAR THF SMN
**Sub Job**:NA
**Area & Coordinates**: NA
**Party or Solo**:NA
**NPC Name**: NA
**Monster Name**:NA
**Multi-boxing? (multiple clients on same connection)**:NA
**Steps To Reproduce The Issue**:Use job abilities
WAR - Restraint
THF - Despoil, Bully, Feint
SMN - Elemental Siphon

**Comment by TeoTwawki** [comment]
Not a bug, an unimplemented feature of dsp. Their tracker is this way :point_right: https://github.com/DarkstarProject/darkstar/issues/new

As for me trying to implement things, i have a big old list already, on the archive section of the forums. Don't want multiple issues for unimplemented dsp stuff in legions tracker becoming a thing.
