### ISSUE TITLE
Missing Crafting Recipes For Jug Pets

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1370]
**Date & Time**: 2/16/17

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: 
Tarot

**Nation**: 
San

**Job(level)/Sub Job(level)**: 
99 BST

**NPC or Monster or item Name**: 
NA

**Zone name**: 
NA

**Coordinates (use `$where`)**: 
NA

**ffxiah.com link (for items issues only)**: 
Legion Links:
http://legiondark.com/db/items/17902/lucky_broth
http://legiondark.com/db/items/17903/shadowy_broth
http://legiondark.com/db/items/17881/deepbed_soil
http://legiondark.com/db/items/17904/briny_broth
http://legiondark.com/db/items/17894/vermihumus
http://legiondark.com/db/items/17893/wool_grease

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
No crafting recipe listed on item tool, assuming most are unobtainable

**Comment by JessLand86** [comment]
https://github.com/LegionDark/Issues/issues/1333
