### ISSUE TITLE
Wrong drop pool for Makara.

### ISSUE THREAD

**Issue by ghost** [LegionDark/Issues#1371]
**Date & Time**: 
2/17/2017

**FFXI Client Version (use `/ver`)**: 
30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
N/a

**Job(level)/Sub Job(level)**: 
N/a

**NPC or Monster or item Name**: 
Makara

**Zone name**: 
Toraimarai Canal

**Coordinates (use `$where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
Makara using the incorrect drop pool. 
http://legiondark.com/db/monsters/17469565/Makara

**Comment by R3P0FFXI** [comment]
@JessLand86 @atom0s issue resolved in reorg branch

**Comment by R3P0FFXI** [comment]
issue resolved in todays update
