### ISSUE TITLE
Haste 2 scroll

### ISSUE THREAD

**Issue by zeos101** [LegionDark/Issues#1372]
**Date & Time**:  02/17/17

**FFXI Client Version (use `/ver`)**:  30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  30161227_1

**Character Name**:  Wildgrass

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  WHM 99 / BLM 49

**NPC or Monster or item Name**:  NA

**Zone name**:  Tried in many different zones

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**:  http://www.ffxiah.com/item/4692/haste-ii

**Multi-boxing? (multiple clients on same connection)**:  Tried with only one client running. Have tried on 3 different computers,  Ashita 3, Ashita 2 and Windower 4.

When I try to use the scroll I get this error ( same on all 3 computers on all different boot clients )

Error ( Boot loader for final fantasy for use with private servers. has stopped working )

A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

Trouble shooting on my end

1.Tried to run as admin no help, 
2.run as rug user no help, 
3.run compatibility mode for win xp no help

**Steps To Reproduce / any other info**:

**Comment by zeos101** [comment]
UPDATE 

Found the scroll is yellow as if it could be used by my WHM I see now that its an RDM only spell 
That must be the issue

**Comment by TeoTwawki** [comment]
yeah this is normal, can't use scroll on wrogn job
