### ISSUE TITLE
Severed Gigas Collar

### ISSUE THREAD

**Issue by zeos101** [LegionDark/Issues#1373]
**Date & Time**:  2/17/17

**FFXI Client Version (use `/ver`)**:  30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30161227_1

**Character Name**:  Klang

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  Thf 99 / Dnc 49

**NPC or Monster or item Name**:  Severed Gigas Collar

**Zone name**:  Abyssea La Theine

**Coordinates (use `$where`)**: x-397 y-0 z-320

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  Yes, Yes, Have tried solo as well.

**Steps To Reproduce / any other info**: 
Just want to make sure the Severed Gigas Collar is dropped by Grandgousier I am well over 30 kills in 

Thank you

**Comment by R3P0FFXI** [comment]
It does
