### ISSUE TITLE
Quicksand Caves door used in ZM12, not opening with Pouch of weighted stones

### ISSUE THREAD

**Issue by AableLD** [LegionDark/Issues#1374]
**Date & Time**: 
2/18/2017, 11:45 AM EST

**FFXI Client Version (use `/ver`)**: 
30161206_3

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
no (30161227_1)

**Character Name**: 
Aable

**Nation**: 
Bastok 

**Job(level)/Sub Job(level)**: 
PLD99/WAR49

**NPC or Monster or item Name**: 
Ornate Door?

**Zone name**: 
Quicksand Caves

**Coordinates (use `$where`)**: 
X:-579 Y:0 Z:-419 (815).

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Working on ZM12, all doors in Quicksand
![img_20170218_113413](https://cloud.githubusercontent.com/assets/25867809/23094985/77f6380a-f5d0-11e6-93a8-0db21040db58.png)
![img_20170218_113444](https://cloud.githubusercontent.com/assets/25867809/23094986/8125bc3e-f5d0-11e6-84a2-4d3c367742f2.png)

 Caves have opened with the "Pouch of weighted stones" KI, but the door at the above coordinates is non-responsive.

**Comment by TeoTwawki** [comment]
You have the wrong KeyItem. Weighted stones are not used here, [Loadstone](http://ffxiclopedia.wikia.com/wiki/Loadstone) is.
