### ISSUE TITLE
Craft import request - Rinuko

### ISSUE THREAD

**Issue by joso33** [LegionDark/Issues#1375]
**Date & Time**: 2017-02-19

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**:  Rinuko

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

I'm making this request upon instructions from Server transfer thread. I don't know if I get to keep all, but if you only allow 1; I want to keep Smithing 100.

http://legiondark.com/forums/viewtopic.php?f=37&t=1968 

If you require any additional information, let me know.

**Comment by Heepster03** [comment]
Been looking for you. Haven't seen you on lately.

**Comment by joso33** [comment]
Sorry busy week at work. Didn't realise you needed me online.  

I'll logon in 3 hours when get home 

⁣Skickat från BlueMail ​

Den 22 feb. 2017 16:30, kI 16:30, Randall Heep <notifications@github.com> skrev:

**Comment by joso33** [comment]
Been online couple times but I havn't seen you online. Do you need me online for transfer cause i think we might miss eachother due to timezones?

**Comment by Heepster03** [comment]
I'm sorry was in and out today. I'm around the house now, if you can pop on that'll be good. If not, just give me a window of when you can get on again and I'll handle it. Unfortunately, you do have to be online. Again, I apologize for the missing of each other.

**Comment by joso33** [comment]
I'll logon now then :)

**Comment by Heepster03** [comment]
Transfer completed.
