### ISSUE TITLE
Craft Import Request

### ISSUE THREAD

**Issue by Coden32112** [LegionDark/Issues#1376]
**Date & Time**:  2/19/2017

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Coden

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Im looking for crafts to be added to my new transfer over

The link to the Screen Shot is http://legiondark.com/forums/viewtopic.php?f=37&t=1973. 
I also lost 2 items when i came over 1 was the thief af2 hands but thats probb because i upgraded them years ago when i played for a month and the other was Justice Torque, that one was random but i figured id see if i could get it or them back some how.

**Comment by Heepster03** [comment]
Thf hands would be excluded from the xfer being that the upgraded ones are higher than 75. Justice torque should have transferred. If you left it stored on the moogle then it would be excluded. Other than that, no reason it shouldn't move over.

**Comment by Coden32112** [comment]
Yea I figured I'd just have to get them again I don't know why the other one didn't come over because it was with everything else that came over. It was really weird 

Denis Thompson

**Comment by Heepster03** [comment]
Crafts xferred,
