### ISSUE TITLE
Cirein-Croin does not use any TP moves.

### ISSUE THREAD

**Issue by ghost** [LegionDark/Issues#1377]
**Date & Time**: 
02/21/2017 0323

**FFXI Client Version (use `/ver`)**: 
30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Imortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99Pld/Rdm

**NPC or Monster or item Name**: 
Cirein-Croin

**Zone name**: 
Aby - Misareaux

**Coordinates (use `$where`)**: 
-25 -18 586

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
N/a

**Steps To Reproduce / any other info**: 
Cirein-Croin does not use any TP moves.

**Comment by tb1** [comment]
This was true for Nuhn (Arrapago Reef), and I think other Orobon-type mobs.

**Comment by TeoTwawki** [comment]
@R3P0FFXI see huge block of commented out things in mob skill lists custom file nobody ever finished before starting more projects.. ***COUGH COUGH***

**Comment by TeoTwawki** [comment]
@JessLand86 this and like 50 other Mobs

**Comment by R3P0FFXI** [comment]
@tb1 issue resolved in todays update
