### ISSUE TITLE
Gustav Tunnel Merit Mobs Checking Too Weak at 99

### ISSUE THREAD

**Issue by Madmaxion** [LegionDark/Issues#1379]
**Date & Time**:  2/22/2017

**FFXI Client Version (use `/ver`)**:  30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**:  Maxion

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  99BLM/49RDM

**NPC or Monster or item Name**: Boulder Eater 

**Zone name**:  Gustav Tunnel

**Coordinates (use `$where`)**:  X:31 Y:0 Z:151 (25).

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**:  No

**Steps To Reproduce / any other info**:  Check mob, cons "Too weak to be worthwhile" at 99. Mob level supposed to be 100-105 and for Grounds Tome Book Page 8 in Gustav Tunnel. Target Level says 100~103.

**Comment by TeoTwawki** [comment]
Stupid dev mistakes confirmed.

**Comment by TeoTwawki** [comment]
The next time the map server restarts they'll match what the book says level wise.

**Comment by Madmaxion** [comment]
Thanks Teo :)
