### ISSUE TITLE
Gu'Dha Effigy "key item"

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#138]
Date & Time: 6/7/2015 00.49
Frequency:Always
FFXI Client Version: 30150629_2
Character Name: Thranduil
Race: Hume
Main Job: RDM
Sub Job: THF
Area & Coordinates: Dynamis-Bastok (H-9)
Party or Solo:Party
NPC Name: NA
Monster Name:Gu'Dha Effigy
Steps To Reproduce The Issue: the boss didn't drop the "???" one needs to check to get the key item as a proof of beating the zone (Hydra Corps Eyeglass)

**Comment by R3P0FFXI** [comment]
Not sure how to respond to this as we stated numerous times the boss does not drop the ??? the KI drops directly from the boss now 100%

**Comment by simthra** [comment]
I'll try to express myself t a little better: when me and Daedrik killed the boss neither the new "???"  spawned on the floor (@ the boss death position), nor I received the Key Item.
