### ISSUE TITLE
Foppish Tunica synth

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#1380]
**Date & Time**: 2/23/2017

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30161227_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: blu99/rdm49

**NPC or Monster or item Name**: Foppish Tunica

**Zone name**: na

**Coordinates (use `$where`)**: na

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: Before the last update the Foppish Tunica item had 2 ways you could synth it.  The 115 version with cloth 115 and goldcraft 60 like it currently shows, as well as cloth 113 and leathercraft 60, the items were slightly different, I'm going off memory here but I believe it was 2 scarves, 1 caleano's cloth, 1 watzka rostrum (sp), block of animal glue, and one or two types of low/mid range cloth items.  Anyway I'm not sure if it was removed by mistake or on purpose so I opened up a report.

**Comment by R3P0FFXI** [comment]
Per BG

Main Craft: Clothcraft - (115) 
Sub Craft(s): Goldsmithing - (??)
