### ISSUE TITLE
Dual Boxing Dynamis

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1381]
**Date & Time**: 
2/23/17

**FFXI Client Version (use `/ver`)**: 
n/a

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
n/a

**Character Name**: 
Raelious

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
n/a

**NPC or Monster or item Name**: 
n/a

**Zone name**: 
Dynamis*

**Coordinates (use `$where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
With the recent fixes and additions to Dynamis in the last update, was wondering if its okay to now be able to Dual Box Dynamis/Limbus now?
Thanks

**Comment by TeoTwawki** [comment]
Sorry no, the multibox crash still hasn't been fixed in DSP. When it is believe me you guys will know because I won't shut up about it when it finally happens.

**Comment by Raelious** [comment]
I did have a question about the multibox crash in there, is that a unique thing to DSP recently? Because when I was on Nasomi there wasnt a multibox crashing during Limbus or Dynamis, or did he somehow someway figure out how to fix that himself? *unlikely*

**Comment by TeoTwawki** [comment]
The bug is universal to DSP and has been since multiple map servers became a thing. We can discuss this further in IRC or Discord if you want, issues are a bad place to have discussions. Nasomi thinks he has it fixed but he doesn't. He's just making a different bad thing happen.
