### ISSUE TITLE
Telchine Braconi missing MATT mod.

### ISSUE THREAD

**Issue by ghost** [LegionDark/Issues#1382]
**Date & Time**: 
02/24/2017 0553

**FFXI Client Version (use `/ver`)**: 
30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99PLD/RDM

**NPC or Monster or item Name**: 
Telchine Braconi 

**Zone name**: 
n/a

**Coordinates (use `$where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/27235/telchine-braconi

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
Telchine Braconi is missing mod MATT = 28, // Magic Attack, it should have 15 MATT.

**Comment by PikaFox** [comment]
Added to list i just did; needs to be sent to darkstar

**Comment by R3P0FFXI** [comment]
@PikaFox issue resolved in todays update
