### ISSUE TITLE
Havestman - NM non existant?

### ISSUE THREAD

**Issue by SledgeCalamy** [LegionDark/Issues#1386]
**Date & Time**: 1:12, 25 Feb 2017

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: y 

**Character Name**:  Sledge

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: Blm99/Rdm49 

**NPC or Monster or item Name**:  Harvestman

**Zone name**: Bhaflau Thickets

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 
NM drops aptant as per legiondark Wiki
however on tracker I'm getting error, and doesn't seem to appear in game

**Comment by TeoTwawki** [comment]
DSp changed its family ID, LegionDark didn't get the memo, will be handled next time there is maintenance.
