### ISSUE TITLE
Stuck on CoP 8-3

### ISSUE THREAD

**Issue by Sookram** [LegionDark/Issues#1387]
**Date & Time**: 
02/26/17 1:15 PM EST

**FFXI Client Version (use `/ver`)**: 
30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Esquelax

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
WAR99/DNC49
**NPC or Monster or item Name**: 
Light of Dem/Mea Key item

**Zone name**: 
 The Garden of Ru'Hmet

**Coordinates (use `$where`)**: 
Warped out. L-7 on map 3

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
In this mission, you must climb a tower that is specific to your race. As an Elvaan, I climb the tower for Elvaan. At the top, I click on the Ebon panel twice. The first time I got a CS, the second time I got another CS. The wiki says after the second CS, I will get a Key item. Because I'm Elvaan, I should get the key item _Light of Mea_, however I received _Light of Dem_ (Mithra). I check my key item list and it shows that I have the key item for every race. The wiki also says that my title will be _Warrior of the Crystal._ I got the title. It seems like this should be the end of this mission. I check under my missions and it says I'm still on _When Angels Fall_ (8-3). I should be on _Dawn_ (8-4) after that second CS. I try to get the first CS for the mission _Dawn_ but does not work.

I also tried to re-log and unload all my plugins and climb the tower again. I even tried the Mithra tower and click on the Ebon panel there.

**Comment by TeoTwawki** [comment]
@LegionDark/gm find out what his `PromathiaStatus` is set to and what the script expects it to be to clear the mission. Once he's taken care of I need somebody to make a a new Elvaan test character, force that character mission to the beginning of 8-3, drag it around using their GM, and see if they can replicate this while checking that variable at each step. IF you can, report to DSP.

**Comment by TeoTwawki** [comment]
@Sookram A GM will get with you in game as soon as one is available. I expect testing/replicating and then actually fixing any actual bug will take significantly more time after they are done with you, so the issue will probably remain open for some time after you are already fixed. Labeling issue accordingly.

**Comment by TeoTwawki** [comment]
Was just told by GM staff you missed getting the brands.

**Comment by Sookram** [comment]
Yeah I miss read the wiki. I should be good.
