### ISSUE TITLE
Yetshila Wrong synth

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#1388]
**Date & Time**: 2/26/2017

**FFXI Client Version (use `/ver`)**: 30161227_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: blu99/rdm49

**NPC or Monster or item Name**: Yetshila

**Zone name**: na

**Coordinates (use `$where`)**: na

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: This is what you need to synth the items according to bg https://www.bg-wiki.com/bg/Yetshila       
Main Craft: Clothcraft - (113)
Sub Craft(s): Bonecraft - (60) 
Wind Crystal
Animal Glue
Waktza Rostrum
Waktza Crest

the legion website shows this synth (Which is what the 2nd Foppish recipe used to be.  When I used to make foppish before the last update, this is the recipe I'd use) http://legiondark.com/db/items/21378/yetshila

Clothcraft (113), Bonecraft (60) 
Square Of Silk Cloth x1
Block Of Animal Glue x1
Celaenos Cloth x1
Square Of Penelopes Cloth x1
Waktza Rostrum x1
Defiant Scarf x2

**Comment by R3P0FFXI** [comment]
@spectre99 issue resolved in todays update
