### ISSUE TITLE
Dual Maat Augmented Krousis Ring

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1389]
**Date & Time**: 
March 1, 2017
8:27 PM (MST)

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 
Tbone

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 
Krousis Ring

**Zone name**: 
Jeuno

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/15849/krousis-ring

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 

1. Do limit break quests, get Krousis Ring with augment.
2. Obtain another un-augmented Krousis Ring, give it to Maat.
3. Take over the world with 2 augmented Krousis Rings

This is a pretty rare case, but I managed to pick up one on AH and now I have 2 augmented rings.

Maybe test if an augment already exists on the ring when it's traded, or set the rare/ex flag on Krousis Ring.

**Comment by TeoTwawki** [comment]
I had this checking for that when I created it. something went wrong. sigh.

**Comment by TeoTwawki** [comment]
Won't have the fix in tonight's update, but the next one will. For anyone stumbling across this: I can in fact see in your inventory if you abuse this. Dun dunn dunnnnn. Accidental augments will be stripped. Intentional misuse will lead to item deletion.

**Comment by TeoTwawki** [comment]
Changed my mind. no longer a bug, it's a feature.
