### ISSUE TITLE
Qirmiz Tathlum & Kadraeth the Hatespawn

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#139]
**Date & Time**: 7/5/2015 8:43pm
**Frequency**: Always
**FFXI Client Version**:30150629_2
**Character Name**:Baucant
**Race**:Evann
**Main Job**:Thf
**Sub Job**:Nin
**Area & Coordinates**:Abyssea-Vunkerl
**Party or Solo**:Both
**NPC Name**:???
**Monster Name**:Kadraeth the Hatespawn
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**:

I was looking for this Item:
http://ffxiclopedia.wikia.com/wiki/Qirmiz_Tathlum
I found the item listed on our Website but no mob listed on drop tool

Drops off this mob in retail
http://ffxiclopedia.wikia.com/wiki/Kadraeth_the_Hatespawn
I found that all this mobs drops are "zeroed out"

**Comment by TeoTwawki** [comment]
I don't think that mob is implemented, and he has no drops at all in legions DB. That item has yet to be placed with any mob on legion, and legion often doesn't have things drop from where it would on retail.

@R3P0FFXI / @ Loki79 could one of you go through and find+bump up drops that are less than 1 full percent that obviously shouldn't be ridiculously rare like that? I'm guessing these are old sql lines where the person adding it did not realize that drops rates were expressed in thousandths not hundredths. I don't think there are very many but R3 found a few a couple days ago.

@Thilion you still around? Was hoping you might be interested in helping compile a list of things that exist in item basic, but currently are not obtainable anywhere.

@atom0s could you maybe add the decimal place for drops that are less than 1 full percent, just in case?

**Comment by TeoTwawki** [comment]
@R3P0FFXI / @Loki79 If that NM should be working and have drops already, remove the not-a-bug label. Right now he's got none at all.

**Comment by R3P0FFXI** [comment]
This is the same issue that Gnawtooth had but his drops should be as following

Qirmiz Tathlum (???%)
Aoidos' Seal: Feet (BRD) (???%)
Creed Seal: Feet (PLD) (???%) (Can drop x2)
Mavi Seal: Feet (BLU) (???%)
Sylvan Seal: Feet (RNG) (???%)
Pulsating Soulflayer BeardKeyItem Weakness Red (???%)

**Comment by Baucant** [comment]
the KI is droping from This NM as it is needed to pop the NM for atma MM (refresh) which I know has been farmed a little over a week ago with no issues on the KI from this mob

**Comment by Loki79** [comment]
@R3P0FFXI  go ahead and add the drops and close this out when done.

**Comment by Loki79** [comment]
@R3P0FFXI where you at on this?  thought you were adding most of this a while back.

**Comment by TeoTwawki** [comment]
-*Slaps @R3P0FFXI with a large fishbot*-

**Comment by R3P0FFXI** [comment]
Fixed will be in Tuesday
