### ISSUE TITLE
friend's password of char forgoten, please help him get his char back

### ISSUE THREAD

**Issue by arkooqymoya** [LegionDark/Issues#1390]
**Date & Time**: 2017/3/3

**FFXI Client Version (use `/ver`)**: 30170204_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: susu

**Nation**:  San d'Oria

**Job(level)/Sub Job(level)**: whm blm rdm thf blu brd sch all 99

**NPC or Monster or item Name**: no

**Zone name**: no

**Coordinates (use `$where`)**: no

**ffxiah.com link (for items issues only)**: http://www.legiondark.com/db/characters/24534/Susu

**Multi-boxing? (multiple clients on same connection)**: ehhh ,guess he will if acc back

**Steps To Reproduce / any other info**:  hes acc:  ygs09876   his mail is : 1： 609872388@qq.com

                                                                                                                 2: 860499616@qq.com
please see if those match, and get back to me ok?   want

**Comment by R3P0FFXI** [comment]
@arkooqymoya Please see me on Discord for the new password

**Comment by Arrytha** [comment]
I am in need of the same thing. Returning after over a year hiatus and hoping to check out the game again.

**Comment by PikaFox** [comment]
@Arrytha if you need the same thing, open your own ticket so it is easier to track your issue and let us get to you.

**Comment by Arrytha** [comment]
I sent R3PO a discord message as he commented above to do for the other guy. Just waiting on a response. Thanks!
