### ISSUE TITLE
~ToAU mission 6 Easterly winds ~

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#1391]
**Date & Time**: 4-3-17 19.37 gmt+1

**FFXI Client Version (use `/ver`)**: 30170204_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: thranduil

**Nation**: bastok

**Job(level)/Sub Job(level)**: nin 99/dnc 49

**NPC or Monster or item Name**: non3

**Zone name**: ru'lude gardens

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Halver gave me the mission and it's flagged as current; CS to proceed into the mission won't trigger; I've already tried walking slowly up and down the stairs (as suggested in an oleder bug report) in ru lude, but nothing happens. Thank you.

**Comment by TeoTwawki** [comment]
KI Raillefal's Letter get removed? Does Halver repeat the CS? Does the mission appear in both current and completed at the same time?


@LegionDark/gm check this player's `AhtUrganStatus` variable and also run `checkmission 4 <t>` on them.

**Comment by alannor** [comment]
Hi, Im stuck on the same part.
Tried zoning, waiting earth day..etc

**Comment by simthra** [comment]
Just checked: "raillefal's letter" is missing from temporary key items. 
Halver does not repeat the cs, the mission is just flagged as current.

**Comment by Heepster03** [comment]
> player:addMission(TOAU,EASTERLY_WINDS);

> player:delKeyItem(RAILLEFALS_LETTER);

So your KI should be removed. I'll check your variables when either of you get online.

**Comment by TeoTwawki** [comment]
This https://github.com/DarkstarProject/darkstar/commit/b11fc78c04a08560d392a31ef292d855c77a7291 is probably how this has been happening to people. Anyone who's var is "2" and can't get this cs, set the var back to "1".

**Comment by TeoTwawki** [comment]
A secondary cause for this been found and fixed and will be live in the next maintenance.

**Comment by TeoTwawki** [comment]
Catch me on discord if you still have this problem.
