### ISSUE TITLE
Summon Spirits no longer casting spells

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1392]
**Date & Time**: 
Sat, March 4
~1:00 AM

**FFXI Client Version (use `/ver`)**: 
30170204_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30170204_1

**Character Name**: 
Girlieman

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
SMN82/RDM

**Zone name**: 
Any

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 

Prior to ~1:00 AM, March 4 summoned spirits were casting spells

Server was restarted (or crashed) around that time.  After it came back up, they no longer cast spells.

I tried various conditions and zones, and they still won't cast.

**Comment by TeoTwawki** [comment]
Now that maint is over, check it again.

**Comment by tb1** [comment]
Yeah, looks to be some wierd crash thing.  It's working now.

**Comment by tb1** [comment]
After a restart it stopped working again, might be something to look into as it doesn't seem fluke anymore.

**Comment by Raelious** [comment]
@TeoTwawki just tested spirits out in South Gustaberg on bees, they are casting like normal, they seem to work now.
