### ISSUE TITLE
Ironclad Pulveriser

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1394]
**Date & Time**: 
3/6/2017

**FFXI Client Version (use `/ver`)**: 
30170204_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30170204_1

**Character Name**: 
Raelious

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
BLU99/RDM49

**NPC or Monster or item Name**: 
Ironclad Pulveriser

**Zone name**: 
Abyssea-Miseraux

**Coordinates (use `$where`)**: 
Close to X:-274, Y:-32, Z:111 (185)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Went to abyssea to help a friend get an atma and Ironclad Pulveriser was up without requiring to pop him, there were 4 copies of him. Killed 2 of them to see what was up and they seem to have less then 20k hp or so.

**Comment by R3P0FFXI** [comment]
@Raelious issue resolved in todays update
