### ISSUE TITLE
crafting level restoration

### ISSUE THREAD

**Issue by lonleyhero** [LegionDark/Issues#1397]
**Date & Time**: 
3/7/2017 6:56pm

**FFXI Client Version (use `/ver`)**: 
n/a

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
n/a

**Character Name**: 
Lonehero

**Nation**: 
bastok

**Job(level)/Sub Job(level)**: 
99thf/49dnc

**NPC or Monster or item Name**: 
n/a

**Zone name**: 
n/a

**Coordinates (use `$where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
i was asked to file a ticket about having a crafting level restored i have added a screenshot of my crafting levels if im only able to have one restored i would like to have my bonecraft level restored 

thank you guys
![craft skills](https://cloud.githubusercontent.com/assets/26263080/23683687/5f4db616-0368-11e7-808d-88b585585c57.PNG)

**Comment by Heepster03** [comment]
Crafts imported!
