### ISSUE TITLE
avatars are not despawning when entering capped BCNM

### ISSUE THREAD

**Issue by Nemesisx** [LegionDark/Issues#1398]
**Date & Time**: 1030 P.M

**FFXI Client Version (use `/ver`)**: current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: current

**Character Name**: Nemesisx

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99 SMN/RDM

**NPC or Monster or item Name**: Fenrir

**Zone name**: BCNM

**Coordinates (use `$where`)**: Fenrir Fight

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)**: n/a

**Steps To Reproduce / any other info**:  Flaming crush doing way too much dmg not scaling down to lvl cap in lvl 80 fight I was told to report it.

**Comment by R3P0FFXI** [comment]
Whats to much dmg?

**Comment by Nemesisx** [comment]
Dont know  GM in helping hunters I was helping with Fenrir fight said I was doing way too much dmg with flaming crush and that I better report it immediately to you or there would be consequences i think it was round 10~12k but i have filters turned on.

**Comment by spectre99** [comment]
Basically it seems like if you have an ilevel weapon with smn and go into a battlefield your avatar will be doing some crazy damage, bloodpacts along the lines of 20-30k damage.  Yesterday we did the fenrir fight which is a level 80 or 90 cap fight and the ifrit in the pt pretty much killed fenrir with 2 bp moves.

**Comment by R3P0FFXI** [comment]
Ok @TeoTwawki will need to look into this I will contact him.

**Comment by R3P0FFXI** [comment]
@Nemesisx @spectre99 if Pets do  not despawn while entering the BCNM instances it is a darkstar bug please report it to darkstar see me for server revision

**Comment by R3P0FFXI** [comment]
Issue has been reported to DSP

https://github.com/DarkstarProject/darkstar/issues/3792
