### ISSUE TITLE
Dynamis - Jeuno/Bastok not awarding win

### ISSUE THREAD

**Issue by Strafeous** [LegionDark/Issues#140]
**Date & Time**:  Multiple times, most recent 2am 7/6/2015
**Frequency**: 6 times now
**FFXI Client Version**: 30150619_2
**Character Name**: Strafeous
**Race**: Elvaan
**Main Job**: WAR
**Sub Job**: SAM
**Area & Coordinates**: Dynamis Jeuno and bastok
**Party or Solo**: Party
**NPC Name**: 
**Monster Name**: Dynamis Jeuno/Bastok megaboss
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**: Killed Jeuno Megaboss 5 times, then clicked the ??? and recieved no key item.Went to Bastok, killed Megaboss, clicked the ???... No key item.

**Comment by R3P0FFXI** [comment]
https://github.com/LegionDark/Issues/issues/134

Already implemented if the solution is not auto dropping the KI let us know

**Comment by Strafeous** [comment]
Thanks
