### ISSUE TITLE
Emnity Douse (Blm Job Ability)

### ISSUE THREAD

**Issue by SledgeCalamy** [LegionDark/Issues#1402]
**Date & Time**: 
09/03/17

**FFXI Client Version (use `/ver`)**: 
30170204_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Sledge

**Nation**: 

**Job(level)/Sub Job(level)**: 
Blm99/Rdm49

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
JA to remove all emnity gained 
 I understand it might be a DSP issue just wanted to post it, in case there is any possible improvement

**Comment by R3P0FFXI** [comment]
Please report to DSP
