### ISSUE TITLE
Blurred Scythe Incorrect Model

### ISSUE THREAD

**Issue by SolisFFXI** [LegionDark/Issues#1403]
**Date & Time**: 
03/09/2017 - 1900 EST

**FFXI Client Version (use `/ver`)**: 
30170204_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Solis

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99 DRK / 49 SAM

**NPC or Monster or item Name**: 
Blurred Scythe

**Zone name**: 
NA

**Coordinates (use `$where`)**: 
NA

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/20896/blurred-scythe

**Multi-boxing? (multiple clients on same connection)**: 
NA

**Steps To Reproduce / any other info**: 
Equipped item model shows basic non blurred model

**Comment by R3P0FFXI** [comment]
https://github.com/LegionDark/Issues/issues/1102

Duplicate ticket
