### ISSUE TITLE
NPC Shop item list Susu - Lower Jueno

### ISSUE THREAD

**Issue by SolisFFXI** [LegionDark/Issues#1404]
**Date & Time**: 
1900 ET 03/09/2017

**FFXI Client Version (use `/ver`)**: 
30170204_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Solis

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
DRK 99 SAM 49

**NPC or Monster or item Name**: 
Stonega II

**Zone name**: 
NA

**Coordinates (use `$where`)**: 
NA

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/4798/stonega-ii

**Multi-boxing? (multiple clients on same connection)**: 
NA

**Steps To Reproduce / any other info**: 
NPC Susu does not have correct items for sale.

**Comment by R3P0FFXI** [comment]
Please report to Darkstar
