### ISSUE TITLE
King Arthro doesnt spawn after killing knights

### ISSUE THREAD

**Issue by Fildur** [LegionDark/Issues#1407]
**Date & Time**:  March 10 2017 , 17:05:49

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Fildur

**Nation**:  Bastok

**Job(level)/Sub Job(level)**: Nin 76/thf 38

**NPC or Monster or item Name**: King Arthro

**Zone name**: Jugner Forest

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
 I was camping King Arthro after 3 hours waiting knigts crabs spawn i kill all 10 but king never apear, i was alone on the Zone some mithra log in and out seconds before the knight spawns, thats all the info i have, i save pictures of the logs in case they r needed.. i dont know if tomorrow will appear or not...

**Comment by R3P0FFXI** [comment]
@Fildur we have confirmed this to be a Darkstar issue and have reported this to DSP. Sadly this is probably not something they will fix anytime soon as it appears to be related to the same issue causing Doom not to work correctly.

**Comment by Raelious** [comment]
Tested this is working now, he does spawn after killing all 10 crabs.

**Comment by Heepster03** [comment]
I also just tested this again since the crabs were up. After killing all of them, King Arthro spawned. It appears to be working as intended now, going to close ticket.
