### ISSUE TITLE
Umagrhk [No TP moves]

### ISSUE THREAD

**Issue by Heepster03** [LegionDark/Issues#1408]
**Date & Time**: 3/10/17 at 2353

**FFXI Client Version (use `/ver`)**: 30170204_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: [GM] Halkuras

**Nation**: N/A

**Job(level)/Sub Job(level)**: N/A

**NPC or Monster or item Name**: Umagrhk [99 High Kindred Crest NM]

**Zone name**: Beaucidine Glacier

**Coordinates (use `$where`)**: -280 -80 -81

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: Umagrhk is not performing any TP moves as it should. Therefore people are able to fight this NM with much ease.

**Comment by R3P0FFXI** [comment]
@Heepster03 issue resolved in next update

**Comment by R3P0FFXI** [comment]
issue resolved in todays update
