### ISSUE TITLE
Animated Longsword did not drop anything

### ISSUE THREAD

**Issue by NononoA** [LegionDark/Issues#141]
Date & Time: 6/29/2015 - 7/3/2015
Frequency: about 3 times
FFXI Client Version: 30150619_2
Character Name: Nonono
Race: Taru
Main Job: BLU
Sub Job: THF
Area & Coordinates: 
Party or Solo: Party
NPC Name: 
Monster Name: Animated Longsword
Steps To Reproduce The Issue: Killed Animated Longsword but did not drop Holy Fragment. Tried kill others about 5 animates also no drop anything. Checked on monster tool is 100% drop.

**Comment by PikaFox** [comment]
Need to kill pop mobs to release the trapped souls before killing the animated weapons, else you will get 0 drops. The pop mobs are all the NMs ontop of the short stairs scattered through the central area on the way to the castle, before going down into the chasm area.

**Comment by itachioax** [comment]
yeah just take care, dont kill so fast the eye, if u instakill it eye wont spawn the kindred NM and u wont get ur fragment

**Comment by NononoA** [comment]
I got other fragments before and without kill any spawn kindred NM. Anyway, i will try again to kill all those NM spawn on the stair then do the animate. I will report the result later. Thank you for your information.

**Comment by NononoA** [comment]
Tried again before server maintenance around 12:30. Killed 4 status/icon then killed 14 or 15 NMs spawn on the stair. (Except one KO by 1 hit by my friend). Then we go to kill animated longsword,  Great Axe & Knuckles but  all drop nothing. Is anyone can get any fragment in Dynamis Xarcabard during the last 2 weeks?

**Comment by Rohelius** [comment]
If you miss even one NM like the one you friend killed with one hit then all fragments wont drop. you have to kill ALL the NM. its better if you pull with weak range attack then to hit them. just a tip!

**Comment by NononoA** [comment]
The holy fragment was dropped after I killed all NM on the stair. Thank you everyone.
