### ISSUE TITLE
aegis stage 5 CS not working

### ISSUE THREAD

**Issue by popaul86** [LegionDark/Issues#1410]
received my alcina but cant get the cs after

**Date & Time**: 
march 12th 2017

**FFXI Client Version (use `/ver`)**: 

/ver
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

$ecv
**Character Name**: 

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 
switchstix

**Zone name**: 

castle vahzl baliley
**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:

**Comment by PikaFox** [comment]
Please fill out the template.

**Comment by popaul86** [comment]
im sey im bad with computers and my english is bad><

**Comment by popaul86** [comment]
sry*
