### ISSUE TITLE
Kutharei Not spawning

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#1411]
**Date & Time**: 3/11/2017

**FFXI Client Version (use `/ver`)**: 30170204_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: 99pld/49dnc

**NPC or Monster or item Name**: Kutharei

**Zone name**: Abyssea-Misareaux 

**Coordinates (use `$where`)**: @ X: -146.279, Y: -31.324, Z: -316.425  (F-11)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: Kutharei is supposed to spawn every 15 mins.  I went out there with a party but it never spawned.  I stayed behind in the area for a good hour and 30 minutes, still no pop.

**Comment by JessLand86** [comment]
Seems to be fixed now. Killed and then repopped 15 min later as per the tooltip on the website. Might have just needed a reset.
