### ISSUE TITLE
aegis stage 5 bugged

### ISSUE THREAD

**Issue by popaul86** [LegionDark/Issues#1412]
i got acine shield , got the dialog what to get next. farmed what i needed in dyna xarc. went to carpenters landing to H-10 at the target near the water. the target saying there nothing out of the ordinary here and wont accept my stuff. went back to swtichstix gobbbie npc, hes asking me a fee of 20x 100's of each. so idk if its switchstix that is bugged ot the target at h-10

**Date & Time**: 
march 12 2017

**FFXI Client Version (use `/ver`)**: 
30170204_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

yes
**Character Name**: 
Walax

**Nation**: 
sandoria

**Job(level)/Sub Job(level)**: 

pld/dnc
**NPC or Monster or item Name**: 

switchstix
**Zone name**: 
castle vahzl baileys

**Coordinates (use `$where`)**: 

j-8
**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:

**Comment by popaul86** [comment]
i hope this one is better

**Comment by R3P0FFXI** [comment]
@popaul86 there is no issue with Aegis Stage 5 it is working correctly you are missing a step
