### ISSUE TITLE
Battlefield Status Doesnt Wear off On Completion

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1415]
**Date & Time**: 3/14/17

**FFXI Client Version (use `/ver`)**: 
30170204_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Tarot

**Nation**: 
San

**Job(level)/Sub Job(level)**: 
99 BST

**NPC or Monster or item Name**: 
Wings of Fury BCNM

**Zone name**: 
Ghelsba Outpost

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
On completion of wings of fury and clicking on the chest, players are ejected from the BCNM as normal, but it doesnt remove battlefield status.

**Comment by PikaFox** [comment]
Looking inside the BCNM, it seems the chest is still there and one of the bat trios didnt despawn on death.

**Comment by PikaFox** [comment]
![tarot_2017 03 14_022641](https://cloud.githubusercontent.com/assets/12601727/23888312/bbb281da-085d-11e7-84fb-7d9576330978.png)

**Comment by TeoTwawki** [comment]
well..this'll be a fun one to figure out.

**Comment by Jessland86** [comment]
This was fixed in a previous maintenance.
