### ISSUE TITLE
Mythic Aftermath doesn't work during Trials

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1419]
**Date & Time**: 
March 16, 2017
11:39 AM (MST)

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30170304_1

**Character Name**: 
Tbone et. al

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
PLD

**NPC or Monster or item Name**: 
I believe it applies to all mythic weapons, although I haven't tried all of them

http://ffxiclopedia.wikia.com/wiki/Category:Mythic_Weapons
http://www.ffxiah.com/search/item?q=Burtgang (as the example)

**Zone name**: 
Any

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 
http://ffxiclopedia.wikia.com/wiki/Category:Mythic_Weapons
http://www.ffxiah.com/search/item?q=Burtgang

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Intermediate mythic weapons (80,85,95 and I believe 99) do not give aftermath when using mythic weaponskill.

1. Get Burtgang (80,85,95)
2. Build TP
3. Use Atonement
4. See no aftermath effect

**Comment by JessLand86** [comment]
Pretty sure aftermaths are not coded on anything currently save for relic weapons. The level 75 Mythics give you the icon, but that seems to be it. As another related issue to Aftermaths, you can have three levels of the aftermath active at one time currently.

**Comment by Heepster03** [comment]
Already referenced here: https://github.com/DarkstarProject/darkstar/issues/3673

Closing ticket.
