### ISSUE TITLE
Dynamis - Jeuno / Cannot get KI for clear

### ISSUE THREAD

**Issue by skeye1** [LegionDark/Issues#142]
7/6/15 - 4:58pm EST
Always
30150619_2
Skeye
Mithra
Thief
Dancer
Dynamis - Jeuno (H-10) / x:0 Y:0 Z:-82 (178)
Solo
Goblin Golem
**Multi-boxing? = no
Repeated Dynamis with same results

**Comment by TeoTwawki** [comment]
The hell.

**Comment by R3P0FFXI** [comment]
https://github.com/LegionDark/Issues/issues/134

**Comment by TeoTwawki** [comment]
"Repeated Dynamis with same results" tells me nothing about what the problem is, so if its not the same friggin issue I already handled, you need to actually explain what is happening. Same results as what?

**Comment by R3P0FFXI** [comment]
User killed boss, KI did not Drop ??? did not pop

**Comment by TeoTwawki** [comment]
Fixed
