### ISSUE TITLE
Windurst 9-2 Moon Reading

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#1421]
**Date & Time**: 3/17/2017

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: thf99/dnc49

**NPC or Monster or item Name**: na

**Zone name**: Heaven's Tower in Windurst Walls 

**Coordinates (use `$where`)**: X:0 Y:-49 Z:37 (192)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: Once you get the mission from the gate guard you're supposed to go to Star Sibyl's chamber in Heavens Tower for a cutscene.  I was able to pick up the mission, it's showing up in my mission log, however it's not giving me the cutscene at the Vestal Chamber door which prevents me from doing the mission.  I even tried the next step in the mission to get the KI in Ro'Mave, thinking that maybe you could just skip the cs, but it looks like without the cs you really can't progress.

**Comment by Heepster03** [comment]
The steps to this are not currently implemented.

**Comment by Heepster03** [comment]
Currently already a report in DSP for it,.

https://github.com/DarkstarProject/darkstar/issues/2486

**Comment by Heepster03** [comment]
One more thing, going to reference something @TeoTwawki said in a previous ticket of the same issue.

> Sorry but. you are S.O.L. till someone code sit in DSP.

Also a word of advice: when it does show up in DSP, don't be a rush to get it done immediately, they have a nasty habit of leaving them in a broken state for months. Let someone else discover the bugs in the untested trash code they are likely to get from an idiot who uses MS word or wordpad as a code editor.

Closing this ticket like the other one.
