### ISSUE TITLE
Revealer's Mitts and Pants Do Not Enhance Stats, When Equipped

### ISSUE THREAD

**Issue by Daruvan** [LegionDark/Issues#1422]
**Date & Time**: 3/17/2017

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Alcina

**Nation**: Windurst

**Job(level)/Sub Job(level)**: RDM99 / WHM49

**NPC or Monster or item Name**: Revealer's Mitts & Revealer's Pants

**Zone name**: Any (tested in Ro'Maeve and Tahrongi)

**Coordinates (use `$where`)**: Tahrongi: X:97 Y:40 Z:358 (169)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/27991/revealers-mitts & http://www.ffxiah.com/item/27228/revealers-pants 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Equipping these items do not increase stats listed.

**Comment by PikaFox** [comment]
Finished these two items; will need to be added to server and to DSP

**Comment by R3P0FFXI** [comment]
@PikaFox issue resolved in todays update
