### ISSUE TITLE
Scroll of Frazzle - Cannot attack that target

### ISSUE THREAD

**Issue by redx3** [LegionDark/Issues#1423]
**Date & Time**: 
3/18/2017 6:50pm

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Redxsteals

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
74rdm/37blm

**NPC or Monster or item Name**: 
Scroll of Frazzle

**Zone name**: 
Any

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/4914/frazzle

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
When using item you get message "Cannot attack that target"

**Comment by R3P0FFXI** [comment]
@redx3 Frazzle is not coded in DSP

**Comment by JessLand86** [comment]
@R3P0FFXI While DSP doesn't have Frazzle coded, Legion does. I'll look into getting this scroll made useable.

**Comment by JessLand86** [comment]
These 2 lines need to be added to item_useable.sql
`INSERT INTO `item_usable` VALUES (4914,'scroll_of_frazzle',1,1,12,5,0,0,0,0);

INSERT INTO `item_usable` VALUES (4915,'scroll_of_frazzle_ii',1,1,12,5,0,0,0,0);`

and the following need to be added to \scripts\globals\items
[Frazzle1&2.zip](https://github.com/LegionDark/Issues/files/907668/Frazzle1.2.zip)

**Comment by TeoTwawki** [comment]
@JessLand86 fork DSP: https://github.com/DarkstarProject/darkstar/tree/155308e1370596ad4071ad1421fac1398f0fc0ec#fork-destination-box

make a branch to do the work in ![branch](https://cloud.githubusercontent.com/assets/6871475/24831966/ff52719c-1c72-11e7-9398-ad0d277337b3.jpg)

Clone it (get url from big green "clone" button on github) with [toirtoisgit](https://tortoisegit.org/download/) : 
![clone](https://cloud.githubusercontent.com/assets/6871475/24831973/356b80a2-1c73-11e7-9678-e635cf6b3feb.jpg)

Note: tortoise requires [git4windows](https://git-for-windows.github.io/)

Make the changes in your fork's sql file, right click it and "commit" followed by "push", then come back to github and click the "new pull request" button. Its next to the branch selector.

**Comment by JessLand86** [comment]
I might have possible done it. I have no idea. 
https://github.com/DarkstarProject/darkstar/pull/3849

**Comment by TeoTwawki** [comment]
![it is good, we are saved!](https://i.imgur.com/x4Fq95u.jpg)

**Comment by R3P0FFXI** [comment]
@redx3 issue resolved in todays update
