### ISSUE TITLE
Password Recovery for Character Login

### ISSUE THREAD

**Issue by Arrytha** [LegionDark/Issues#1425]
**Date & Time**: 
3/22/17

**FFXI Client Version (use `/ver`)**: 
Current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 
Arrytha

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
THF99

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**:

**Comment by R3P0FFXI** [comment]
@Arrytha you are missing critical information please provide login name and email address used on the account

**Comment by Arrytha** [comment]
Sorry, character is same as my forum name, Arrytha. Email will be PM'd to you on Discord.

**Comment by Arrytha** [comment]
Sent all the info you requested on Discord. Let me know if you need anything else to reset my password.

**Comment by atom0s** [comment]
This has been handled.

**Comment by Arrytha** [comment]
atom0s hooked me up. this can be closed. thanks!

**Comment by Arrytha** [comment]
woops just updated
