### ISSUE TITLE
Ladycapulet Crafting skills

### ISSUE THREAD

**Issue by Juiliet** [LegionDark/Issues#1428]
**Date & Time**: 12:05a CST

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Ladycapulet

**Nation**: Bastok

**Job(level)/Sub Job(level)**:RDM 99

**NPC or Monster or item Name**: Crafting Skills

**Zone name**: Bastok Moghouse

**Coordinates (use `$where`)**: X69 Y:0 Z:-70

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/player/Sylph/Juiliet (Crafting skills of the transfer character) http://legiondark.com/forums/viewtopic.php?f=37&t=1701 (Original Post)

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: From a Transfer

**Comment by JessLand86** [comment]
Crafts Imported!
