### ISSUE TITLE
unable to get voidstone/stratum abyssite

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#143]
**Date & Time**: 15/07/05 1:03pm CST
**Frequency**: once
**FFXI Client Version**:30150619_2
**Character Name**: Sakuraoax
**Race**: Hume
**Main Job**:WHM
**Sub Job**:RDM
**Area & Coordinates**:South sandoria
**Party or Solo**: party
**NPC Name**:voidwatcher officer
**Monster Name**: none
**Multi-boxing? yes
**Steps To Reproduce The Issue**:
already finished quest Steamed ram, and i got bronze medal for campaing, then i come to the present to get my abyssite/voidstone and i didnt get anythig, well.. i tried to change nation, talking with Mainchelite, but did get the option to give up so, what can i do?

**Comment by R3P0FFXI** [comment]
You need to join a nation in the past once you do that then you can begin accruing stones

**Comment by itachioax** [comment]
i did with both, i got ki from npc in garlaige citadel s, the first quest work with itachioax, but not with saku, with both i finished it

**Comment by TeoTwawki** [comment]
> i just got a dialogue about skillchains elements from voidwatch officer

the text ID is wrong then

**Comment by TeoTwawki** [comment]
You prolly got the stone (check your currencies menu) and just didn't see a message about it.

**Comment by TeoTwawki** [comment]
@R3P0FFXI / @Loki79 
I'll check and correct teh text IDs for voidwatch craps later tomorrow prolly.

**Comment by TeoTwawki** [comment]
p.s.
Don't assign me unless for sure thats all this was...

**Comment by NononoA** [comment]
Did u buy a clear abysite from any abyssea zone?

**Comment by itachioax** [comment]
![img_20150708_125741](https://cloud.githubusercontent.com/assets/12620527/8577877/1709d398-2571-11e5-9d56-f6607ade3f0e.png)
![Uploading img_20150708_125749.png…]()
![Uploading img_20150708_125759
=(

**Comment by itachioax** [comment]
![img_20150708_125741](https://cloud.githubusercontent.com/assets/12620527/8577943/54adadc8-2571-11e5-991f-66555bbbd7b9.png)
![img_20150708_125749](https://cloud.githubusercontent.com/assets/12620527/8577944/54b4948a-2571-11e5-8ce5-7d4dc884487a.png)
![Uploading img_20150708_125759.png…]()
 there're the pics =/

**Comment by itachioax** [comment]
![img_20150708_125759](https://cloud.githubusercontent.com/assets/12620527/8577975/7be02f88-2571-11e5-922b-bd56530363c3.png)

**Comment by TeoTwawki** [comment]
@NononoA 
> Did u buy a clear abysite from any abyssea zone?

100% irrelevant. That Voidwatch Officer only checks for the players level, the players adventurer certificate, the players campaign nation, and the presence of the correct stratum abyssite (which if all other conditions are met, he gives out said stratum abyssite).

@itachioax 
I've just fixed the text alignments for Southern San d'Oria's Voidwatch Officer, he should properly tell you what you are missing now.

**Comment by itachioax** [comment]
ty so much it works now =D
