### ISSUE TITLE
bcnm 30 bird of  a feather no mobs crat paid out a few times.

### ISSUE THREAD

**Issue by LonelyVillain** [LegionDark/Issues#1430]
**Date & Time**: monday march 27 roughly 3:00am EST

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Lonelyvillain

**Nation**: bastok

**Job(level)/Sub Job(level)**:  32Bst/dnc16

**NPC or Monster or item Name**:  bcnm 30 birds of a feather

**Zone name**: Waughroon shrine

**Coordinates (use `$where`)**: X:-353 Y:104 Z:-260 (130)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  no

**Steps To Reproduce / any other info**: 
Entered bcnm 30 Birds of a feather.  mobs weren't there  loot crate was. i clicked it a few times nothing happened  then i got hit with waves of loot. put everything in my storage and waiting for further instructions

**Comment by LonelyVillain** [comment]
i've since gone back and wasted a sky orb (meaning i didn't loot the crate) the glitch is still going on just seems like the bcnm itself is glitched

**Comment by JessLand86** [comment]
Please see http://wiki.legiondark.com/BCNM/KSNM_Status for the current list of working BCNM's. Birds of a feather is a BCNM that is not currently coded.

**Comment by TeoTwawki** [comment]
@R3P0FFXI non implemented bcnm handing out loot needs brought up (vehemently) with dsp. This is a situation that never should have been created, any code that could have done this should have been commented out until the bcnm actually worked. (the lines to stop that loot would be in the sql table for battlefield loot)

**Comment by LonelyVillain** [comment]
yikes my bad! i'm new to private servers. should i delete the loot?

**Comment by TeoTwawki** [comment]
@R3P0FFXI what do you want done with this? *not it!*

**Comment by LonelyVillain** [comment]
i'll just clear then from my inventory by dropping them if it makes it easier
