### ISSUE TITLE
Ovni (Drops empy harp) won't agro

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1433]
**Date & Time**: 
April 1, 2017
10:00 PM (MST)

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30170304_1

**Character Name**: 
Tbone

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
PLD99/THF

**NPC or Monster or item Name**: 
Ovni
http://ffxiclopedia.wikia.com/wiki/Ovni
https://www.bg-wiki.com/bg/Ovni

**Zone name**: 
Abyssea La Theine

**Coordinates (use `$where`)**: 
X:520 Y:40 Z:479 (149)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
The NM Ovni (Yovra-type mob) will not agro, and cannot be targeted because of it.

Drops empy harp, so empy harp is unattainable until he starts agroing again.

This whole area where is roams seems to have some navigation issues and pulling other mobs nearby will sometimes result in "out of range" or "unable to see" messages, even if you are ~2 yalms from the mob.  Sometimes they de-agro randomly too.

**Comment by spectre99** [comment]
I believe you have to /heal underneath it and it will come down.

**Comment by Darkara** [comment]
Standing under it and using voke/flouish/flash/dia ect. also works.

**Comment by JessLand86** [comment]
Just verified, /healing underneath it will not cause it to agro. It's busted... Again.... This mob is turning into the new Halver.

**Comment by TeoTwawki** [comment]
*someone* used a replace line and wiped out what I did over in dsp, basically.

**Comment by tb1** [comment]
It's working now.

**Comment by R3P0FFXI** [comment]
@tb1 issue resolved in todays update
