### ISSUE TITLE
Cannot cancel relic trial

### ISSUE THREAD

**Issue by Acedffxi** [LegionDark/Issues#1434]
**Date & Time**: 
04/02/2017

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Freelot

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
PLD99/RDM49

**NPC or Monster or item Name**: 
Magian Mog_TJ

**Zone name**: 
RuLude Gardens

**Coordinates (use `$where`)**: 
X:1 Y:3 Z:144 (255)

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
N/A

**Steps To Reproduce / any other info**: 
I picked up Aegis 99 trial for 50 tanz jewels but decided against using my 50 on it and tried cancelling but the moogle will not accept my imperial bronze piece. It just keeps repeating what the price to cancel it is.

**Comment by TeoTwawki** [comment]
I'll sort out the cause tomorrow afternoon

**Comment by Acedffxi** [comment]
Thank you, no rush.

**Comment by Acedffxi** [comment]
Just checking in :)

**Comment by TeoTwawki** [comment]
had a busy evening, logging in now to replicate on GM character.

**Comment by Acedffxi** [comment]
No worries, appreciate it.

**Comment by TeoTwawki** [comment]
Hotfixed!
