### ISSUE TITLE
Fomor's not there.

### ISSUE THREAD

**Issue by DirtyAE** [LegionDark/Issues#1435]
**Date & Time**: 
4/5/17 6pm ish

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Dirty

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99blu/49rdm

**NPC or Monster or item Name**: 
Fomor Beastmaster and other Fomor

**Zone name**: 
Wajaom Woodlands & Bhaflou Thickets

**Coordinates (use `$where`)**: 
just outside zones from whitegate

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
go to mobs spawn

**Comment by R3P0FFXI** [comment]
@DirtyAE what time of day was it Formers only show in those areas at night

**Comment by JessLand86** [comment]
Probably because fomor's pet's don't despawn at all people thing they are supposed to be up all the time.

**Comment by DirtyAE** [comment]
i dont remember the time tbh :(
it could been wrong time

**Comment by DirtyAE** [comment]
that was it..
putting dunce hat on.. lol
