### ISSUE TITLE
ark angel ev broken

### ISSUE THREAD

**Issue by lonleyhero** [LegionDark/Issues#1437]
**Date & Time**: 

4/7/17  7:02 pm
**FFXI Client Version (use `/ver`)**: 

30170304_1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 
lonehero

**Nation**: 
bastok

**Job(level)/Sub Job(level)**: 
99thf/49dnc

**NPC or Monster or item Name**: 
arkangel ev

**Zone name**: 
la loff amphitheater

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

was doing ark angel fights and when i got to the elvaan pld he used spirits within the second he saw me for over 16k dmg so i went back used perfect dodge and he ignored me untill he hit 1% he used benediction then i got him to 10% and the exact moment perfect dodge wore he used spirits within for 14k damage  one shotting me once again

**Comment by TeoTwawki** [comment]
no customization on this, so its a DSP thing and needs to be argued with them about their supposedly retail-like implementation.

```lua
    -- Should produce 1000 - 3750 @ full HP using the player formula, assuming 8k HP for AA EV.
    -- dmg * 2.5, as wiki claims ~2500 at 100% HP, until a better formula comes along.
    if tp <= 2000 then -- 1000 - 2000
        dmg = math.floor(hp * (math.floor(0.16 * tp) + 16) / 256);
    else -- 2001 - 3000
        dmg = math.floor(hp * (math.floor(0.72 * tp) - 96) / 256);
    end

    dmg = dmg * 2.5;

    -- Believe it or not, it's been proven to be breath damage.
    dmg = target:breathDmgTaken(dmg);
```
16k is an awful lot more than ~2500..

**Comment by TeoTwawki** [comment]
Sorry EV cheated you. Happen to have a screencap of that damage?

**Comment by lonleyhero** [comment]
no after dying twice and having a Divine Might clear not advance the quest i got angry and logged out didnt think to take a screenshot

**Comment by TeoTwawki** [comment]
Understandable. For any future rematches, you should be aware she can probably one shot you even without the extra power on her spirits within, and there's also the chance to nail you with PD up since its breath damage. Looks like only _phalanx_ and _breath damage taken_ provide any defense against it.

**Comment by TeoTwawki** [comment]
https://git.io/vSrFx
legion would get that through normal updates, but I have also hotfixed it live. See a GM for a replacement entry item, I've told them you are due one.

**Comment by JessLand86** [comment]
Ark Pentasphere (1550) added to player Lonehero in game.
