### ISSUE TITLE
I LOST MANY KEY ITEMS AFTER LOGGING TODAY

### ISSUE THREAD

**Issue by CeliaSalas** [LegionDark/Issues#1439]
**Date & Time**: 
April 10  time 11:40 am 2017

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
no

**Character Name**: 
Natalia

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
Dark night lv 90 sub nin lv 49

**NPC or Monster or item Name**: 

**Zone name**: 
art urgant white gate

**Coordinates (use `$where`)**: 
K-9

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
I lost many key items today, after having entered and I can not retrieve them, I need help, please: 
some key items i lost: PSC Wildcat Badge / Dvucca Isle Staging Point /Halvung Staging Point
Ilrusi Atoll Staging Point / Mamool Ja Staging Point / board permit / air ship pass obtained by done rank 4 /  limit breaker / and  many others.  I cant get them back i need help with this unusual issue please asap

im waiting respond in white gate thks for ur time and attencion

**Comment by TeoTwawki** [comment]
Do you know that last login you had where KI's were for sure normal/undamaged?

**Comment by TeoTwawki** [comment]
(our best bet is to roll back the KI portion of your character from as recent a backup as possible)

**Comment by CeliaSalas** [comment]
my last logging today was around 9:00 am and 10:00 am and first i lost perm key items like:
chocobo license / board permit / airship pass / limit breaker / psd wild cat package / staggin points / ducal permit / all magical maps.  I did relog but i just got back maps

**Comment by TeoTwawki** [comment]
ok but what I am looking for is the last time you were on ***before*** the problem began.

**Comment by CeliaSalas** [comment]
around 9:00 am central time

**Comment by CeliaSalas** [comment]
ok Teo just let me know when i can log in again

**Comment by TeoTwawki** [comment]
check now, I rolled your keyitems back to before the damage.

**Comment by CeliaSalas** [comment]
ok

**Comment by CeliaSalas** [comment]
thank you a lot TEO ty very much i got back all my perm and temporal key items   

god bless u man thank you

**Comment by TeoTwawki** [comment]
Glad I could get you squared away 😃
