### ISSUE TITLE
Force popped NMs that do not spawn claimed that should

### ISSUE THREAD

**Issue by TeoTwawki** [LegionDark/Issues#144]
@R3P0FFXI @Loki79 
`updateEmnity()` needs changed to `updateClaim()` to fix these.
Who wants to volunteer? Its mostly Abyssea. Teo not doin it.

**Comment by TeoTwawki** [comment]
In before "Teo didn't use the template"! :laughing:

**Comment by Loki79** [comment]
ill do this after i wrap up the VW shit this week.

**Comment by Loki79** [comment]
Done

**Comment by TeoTwawki** [comment]
Thanks man.
