### ISSUE TITLE
Ash Dragon gave trial credit

### ISSUE THREAD

**Issue by twisted419** [LegionDark/Issues#1440]
**Date & Time**: 
4/11/17 12:53

**FFXI Client Version (use `/ver`)**: 

30170304_1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

yes
**Character Name**: 
Twisted

**Nation**: 

**Job(level)/Sub Job(level)**: 
99PLD/49THF

**NPC or Monster or item Name**: 
Ash Dragon

**Zone name**: 
Ifrit's Cauldron

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Killed Ash Dragon and it gave relic trial credit as if it was HQ kings. King Behemoth or Aspid or Nidhogg

**Comment by TeoTwawki** [comment]
Fixed already. Won't happen again, can keep the credit it already gave. Thx for reporting though.
