### ISSUE TITLE
Total loss of key items

### ISSUE THREAD

**Issue by stevomatic** [LegionDark/Issues#1441]
**Date & Time**: 4/13/2017 Not entirely sure but I think it was roughly noon-1pm EST Monday the 10th event occurred

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Agnes

**Nation**: Bastok

**Job(level)/Sub Job(level)**: nin99/war49

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes I was dualboxing my rdm Gurgitator and we were otw from Mamook after having killed Gulool, to Caedarva Mire to get to Khimaira, when running through Undersea Ruins I checked map and that was when I noticed I had no map. I thought nothing of it and went AFK after the fight. It was when I returned I saw the extent of what had happened. RDM mule still has all KI's. I've also noticed that my list of maps is repopulated, not sure when this happened, although literally everything else is still gone, Missions, Voidwatch, Abyssea, Dynamis. All that I have now is what I've been able to reaquire

**Steps To Reproduce / any other info**: I can't think of anything remarkable

**Comment by Heepster03** [comment]
You should fill this out to the best of your ability, which means, what did you do right before losing your keyitems?

**Comment by R3P0FFXI** [comment]
@stevomatic when was the last time you had them what were you doing etc etc

**Comment by TeoTwawki** [comment]
I need a date/time of a login prior to this happening. see: https://github.com/LegionDark/Issues/issues/1439#issuecomment-293032011

**Comment by stevomatic** [comment]
Date time prior, Saturday April 8th would be safe if that's enough, I have no clue what time I would login or out

**Comment by stevomatic** [comment]
I'll stay logged out of Agnes in hopes you have everything you need and keep an eye out

**Comment by TeoTwawki** [comment]
Check and see if you are all fixed.

**Comment by stevomatic** [comment]
It looks all good to me, thank you this is huge relief
