### ISSUE TITLE
Iratham not doing any tp moves or casting spells.

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#1443]
**Date & Time**: 4/17/1017

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: pld99/war49

**NPC or Monster or item Name**: Iratham

**Zone name**: Aby Tarongi

**Coordinates (use `$where`)**: X:28 Y:0 Z:-28 (204

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: Fought Iratham 5 times between yesterday and today, each time he simply auto attacks, doesn't cast, doesn't perform any TP moves.

**Comment by TeoTwawki** [comment]
@R3P0FFXI this is what happens when you move skills into darkstar, wipe the skill list out of legions custom, but leave the replaceline in custom pools pointing at the now non existent skill list. you are lucky anyone reported any at all.

**Comment by TeoTwawki** [comment]
@spectre99 thanks for the report, turns out its liek a third of everything in abyssea not just this NM..trying to make sure this gets fixed in the next maint.

**Comment by R3P0FFXI** [comment]
@spectre99 issue resolved in todays update
