### ISSUE TITLE
Ziphius NM

### ISSUE THREAD

**Issue by DirtyAE** [LegionDark/Issues#1444]
**Date & Time**: 
4/18/17

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Dirty

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99thf/49dnc

**NPC or Monster or item Name**: 
Ziphius

**Zone name**: 
Misareaux Coast

**Coordinates (use `$where`)**: 
h-5

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
there are suppose to be 5 sets of ??? that spawn between 22:00-4:00 then a 6th ??? far to east. none of the ??? spawned and not sure what to do from here

**Comment by R3P0FFXI** [comment]
This is not programmed in DSP and would need to be reported to them
