### ISSUE TITLE
Makara in Toraimarai Canal droping Aptants

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1445]
**Date & Time**: 
April 19, 2017

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Tbone

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
THF

**NPC or Monster or item Name**: 
Makara

**Zone name**: 
Toraimarai Canal

**Coordinates (use `$where`)**: 
-211, 20, -17 (6)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Makara in Toraimarai Canal droping Aptants

http://legiondark.com/db/items/2820/aptant_of_geoc
http://legiondark.com/db/items/2817/aptant_of_pera

**Comment by JessLand86** [comment]
https://github.com/LegionDark/Issues/issues/1371
