### ISSUE TITLE
Cannot Place Warp Cudgel on AH

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1446]
**Date & Time**: 
4/20 0301 

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
N/A

**NPC or Monster or item Name**: 
Warp Cudgel

**Zone name**: 
North Sandy

**Coordinates (use `$where`)**: 
N/A

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/17040/warp-cudgel

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Cannot place a fully charged warp cudgel on the AH as it thinks it is a used one.

**Comment by TeoTwawki** [comment]
Known DSP issue https://github.com/DarkstarProject/darkstar/issues/534
I'll see if someone just got teh check bass ackwards though since https://github.com/DarkstarProject/darkstar/issues/2372 also exists..

**Comment by TeoTwawki** [comment]
Damn, they don't even have it checked at all, which means this is a side effect of never having implemented that byte of the packet.
