### ISSUE TITLE
COP mission

### ISSUE THREAD

**Issue by Ami116** [LegionDark/Issues#1447]
**Date & Time**: 2017/4/23

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Ami

**Nation**: bastok

**Job(level)/Sub Job(level)**: 99THF/49DNC

**NPC or Monster or item Name**: Chebukkis - A Meteoric Reunion :Shikarees - In the Name of Justice

**Zone name**: Rulude Gardens

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: Chebukkis - A Meteoric Reunion :Shikarees - In the Name of Justice,  
i got wrong oder, 
1.Enter Mhaura for a cutscene. 
2.Head to Bibiki Bay - Purgonorgo Isle and check the ??? Warmachine at (H-11) for a cutscene and a Colored Drop. The color appears to be random, at least the current Vana'diel day does not seem to affect it.
3.Head to Ru'Lude Gardens (Home Point #1) and approach the palace for a cutscene.   (NO CS!)

**Comment by JessLand86** [comment]
Have you also done the following per : http://ffxiclopedia.wikia.com/wiki/Dawn

Tenzen - Head to Metalworks and talk to Cid on the second floor, at (H-8) for a cutscene.

Jabbos - Visit Oldton Movalpolos for a cutscene.

Louverance:
Head to Southern San d'Oria and talk to Hinaree in Count Caffaule's Manor at (B-6) for a cutscene.
Travel to Uleguerand Range for a cutscene. 
Return to Count Caffaule's Manor for a cutscene.

**Comment by Ami116** [comment]
I have done all steps before "Head to Ru'Lude Gardens ",just got wrong order about( Enter Mhaura for a cutscene Head to Bibiki Bay). 
Then .Head to Ru'Lude Gardens  did not got cutscene.

**Comment by Heepster03** [comment]
So, I just pulled up the quest. It's not go to Mhaura and then Bibiki Bay.

**Chebukkis - A Meteoric Reunion**

    _**## Head to (C-8) of Port Windurst (Home Point #1) and talk to Chipmy-Popmy at the Fishing Guild for a cutscene.** 

        May require more than one attempt to receive the proper cutscene. Be sure your cutscene involves "a trio of wandering comedians." 

    Head to Bibiki Bay - Purgonorgo Isle and check the ??? Warmachine at (H-11) for a cutscene and a Colored Drop. The color appears to be random, at least the current Vana'diel day does not seem to affect it._ 

Another cutscene from the Dawn ending is to goto Mhaura but not related to the Bibiki Bay one.

**Comment by Jessland86** [comment]
If you are still having this issue please re-open the ticket.
