### ISSUE TITLE
SMN Empy Reforge +1 Not giving any bonuses

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1448]
**Date & Time**: 
4/24/17 - 8:04pm PST

**FFXI Client Version (use `/ver`)**: 
version 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30170304_1

**Character Name**: 
Meokazi

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
SMN99/RDM49

**NPC or Monster or item Name**: 
Beckoners Bracers +1, Beckoners Spats +1, Beckoners Pigaches +1

**Zone name**: 
All zones

**Coordinates (use `$where`)**: 
All coordinates

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/27081/beck-bracers-1
http://www.ffxiah.com/item/27440/beck-pigaches-1
http://www.ffxiah.com/item/27266/beck-spats-1

**Multi-boxing? (multiple clients on same connection)**: 
At the time no, reporting issue for roommate.

**Steps To Reproduce / any other info**: 
I was messing around on his SMN and noticed that his DEF was super low for a full i119 SMN, and then checked each piece seperately and none of them were giving any kind of stats via those pieces of gear.

**Comment by R3P0FFXI** [comment]
@Raelious  issue resolved in todays update
