### ISSUE TITLE
Missing  craftin recipe Hajduk Ring

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#145]
**Date & Time**: 7/8/2015 2:01am
**Frequency**:Always
**FFXI Client Version**:30150629_2
**Character Name**:Baucant
**Race**:Elvaan
**Main Job**:THF
**Sub Job**:NIN
**Area & Coordinates**: all areas
**Party or Solo**: solo
**NPC Name**:n/a
**Monster Name**n/a:
**Multi-boxing? (multiple clients on same connection)**:no
**Steps To Reproduce The Issue**:

i attempt the craft for final bonecraft exam and recieve message "Synthesis canceled. That Combonation of materials cannot be synthesized"
I have attempted with both the cyclone crystal (HQ wind) and wind crystal neither work.
http://ffxiclopedia.wikia.com/wiki/Hajduk_Ring

**Comment by Loki79** [comment]
@R3P0FFXI this coming in your next batch of crafting items?  if no plans to implement soon need to just close this out.  No sense in letting ppl fill shit up with "wish list" type shit.  My OCD kicking in at the length of our bug report page.

**Comment by TeoTwawki** [comment]
-* slaps @R3P0FFXI with a large wet trout*- 
Its been 8 days, reply to the man.

**Comment by R3P0FFXI** [comment]
This has been added tot he custom recipes and will be in Tuesday
