### ISSUE TITLE
Dynamis Re-Entry wait time?

### ISSUE THREAD

**Issue by Darkara** [LegionDark/Issues#1450]
**Date & Time**: April 25th  10:58 AM CST

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170304_1

**Character Name**: Darkara

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: Blu99/Rdm49

**NPC or Monster or item Name**: 

**Zone name**: Dynamis - Qufim

**Coordinates (use `$where`)**: X:15 Y:-20 Z:163 (148)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
Had done a run in Dynamis - Tavnazia and exited to help someone else get clears in order for them to enter Tav. When I attempted to enter Dynamis - Qufim it gave me a message saying "You cannot enter Dynamis - Buburimu for 23 days (Vana'diel Time)"

Last time i remember this happening was about a month about when dynamis was reworked (fixed).

![darkara_2017 04 25_110420](https://cloud.githubusercontent.com/assets/25020062/25396080/ddf73152-29a8-11e7-9625-af29a423978a.png)

**Comment by Darkara** [comment]
Update: Was able to enter Dynamis - Buburimu after and then tried again to enter Dynamis - Qufim with the same result.

**Comment by TeoTwawki** [comment]
my hack was probably undone in some of the scripts while I was away..will check when I have time.

**Comment by Raelious** [comment]
You can enter any dynamis zone unlimited times, but the minute you enter Dynamis-qufim and leave that zone to enter another zone you get the lock out message.

**Comment by TeoTwawki** [comment]
Hotfixed. Repository already had it fixed pending next maint, so closing this.
