### ISSUE TITLE
SMN - I Can Hear A Rainbow Quest

### ISSUE THREAD

**Issue by xrocksterx** [LegionDark/Issues#1451]
**Date & Time**: Tuesday April 25, 2017 5pm pst

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Rock

**Nation**: Windurst

**Job(level)/Sub Job(level)**: SMN/RDM 99

**NPC or Monster or item Name**: House of the Hero, Carbuncle Avatar

**Zone name**: Windurst Walls

**Coordinates (use `$where`)**: Windurst Walls, X:-25 Y:-13 Z:261 (186)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Wasn't able to obtain Carbuncle Avatar. Previous ticket https://github.com/LegionDark/Issues/issues/815

**Comment by TeoTwawki** [comment]
You available around tomorrow 7pm-8pm eastern?

**Comment by xrocksterx** [comment]
Yes i'll be online

**Comment by TeoTwawki** [comment]
fixed player, cause is priority order of quests in dsp. IS avoidable, but looking to see if I can eliminate the situation dsp.
