### ISSUE TITLE
forgot username

### ISSUE THREAD

**Issue by fgebony** [LegionDark/Issues#1453]
**Date & Time**:  4/27/17

**FFXI Client Version (use `/ver`)**: 30170329_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: no

**Character Name**:  Pallom

**Nation**:  Windurst

**Job(level)/Sub Job(level)**: 70blm/35rdm

**NPC or Monster or item Name**:  n/a

**Zone name**:  n/a

**Coordinates (use `$where`)**:  n/a

**ffxiah.com link (for items issues only)**: n/a 

**Multi-boxing? (multiple clients on same connection)**:  n/a

**Steps To Reproduce / any other info**:  went on break forgot username to log in with. Used master password so that isn't an issue I just made a non standard username that somehow isn't coming to mind, and took break before email reset was implemented. would like to see if it is possible to fish the username attached to character so that i can log back into it. Thanks!

**Comment by TeoTwawki** [comment]
contact a in discord or irc (lately I'm the only one around on irc, so go ahead and PM me directly. I'm available most afternoons). I've queried the name and left a message for the other GMs.

**Comment by fgebony** [comment]
Thanks a lot. I just stepped out to get food down the street I will get on discord as soon as I get back it's not dire so if you're not on when I get there I'll catch you again some other time.

**Comment by TeoTwawki** [comment]
resolved
