### ISSUE TITLE
Craft Import Request 

### ISSUE THREAD

**Issue by climswar** [LegionDark/Issues#1454]
**Date & Time**: 
4/29/2017 6:15P.M

**FFXI Client Version (use `/ver`)**: 
30170329_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 
Climjr

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
THF75/DNC37

**NPC or Monster or item Name**: 

**Zone name**: 
Upper Jeuno

**Coordinates (use `$where`)**: 
X:-98, Y:0, Z:165 (165)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Server craft transfer please and thank you http://legiondark.com/forums/viewtopic.php?f=37&t=2053

**Comment by JessLand86** [comment]
Handled by GM in game.
