### ISSUE TITLE
Dardrine crafting skills

### ISSUE THREAD

**Issue by dardrine** [LegionDark/Issues#1455]
**Date & Time**: 
638pm cst 4/29/17

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 
Dardrine

**Nation**: 

Windhurst
**Job(level)/Sub Job(level)**: 

99drg
**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

restoring crafting skills
![dardrine_2017 04 27_210857](https://cloud.githubusercontent.com/assets/28207283/25559910/81fa9022-2d0b-11e7-9dd3-e75139b19635.png)

**Comment by dardrine** [comment]
character transfer request link is http://legiondark.com/forums/viewtopic.php?f=37&t=2057&sid=98c5b0f164c52f9d67ccdbbd1932fa5b

**Comment by Heepster03** [comment]
Been looking for you to finish this,

**Comment by dardrine** [comment]
didn't realize i had to be logged in i've been staying off to make sure i didn't interupt anything
i dunno if you're still on atm but i logged in just in case

**Comment by Heepster03** [comment]
Crafts Imported.
