### ISSUE TITLE
Unable to Re-obtain White Stratum Abyssite

### ISSUE THREAD

**Issue by Xenriv** [LegionDark/Issues#1456]
**Date & Time**:  5/1/2017  9:15 AM EST

**FFXI Client Version (use `/ver`)**:  30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  Yes

 
**Character Name**:  Xenriv

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  99THF/49DNC

**NPC or Monster or item Name**:  Voidwatch Officer

**Zone name**:  Bastok Markets/Southern San D'oria/Windurst Waters

**Coordinates (use `$where`)**:  X:-350 Y:-10 Z-164

**ffxiah.com link (for items issues only)**:  N/A

**Multi-boxing? (multiple clients on same connection)**:  N/A

**Steps To Reproduce / any other info**:  Unable to trigger cutscenes to re-obtain White Stratum Abyssite.  I've cleared all of VW including Bismark/Morta, have cleared all Crimson/Indigo/Jade (City VW), Ashen III, Hyacinth II, Amber II, spoken to all Voidwatch Officer NPCs in cities, Audience Chamber in Ru'Lude Gardens, and the Veridical Conflux in Pashhow Marshlands [S] only  to get the message:  

Conditions not met.

Variable 'VW_3_NATIONS' value is: 0
Quest 'GUARDIAN_OF_THE_VOID' Status is: 2
Quest 'A_CAIT_CALLS' Status is: 2

I have already redone all 3 city paths. Does the VW_3_NATIONS value of 0 above mean I gotta redo them again? Is there an NPC I can speak to? Any help is greatly appreciated.  Thanks in advance.

**Comment by R3P0FFXI** [comment]
Yes you have to redo them again that is how Voidwatch was setup

**Comment by TeoTwawki** [comment]
@xenriv I haven't redone all the VW lines to stop cycling key items yet, so most still make you redo them

**Comment by TeoTwawki** [comment]
You both seem to have grossly misunderstood what exactly has to be repeated. You don't normally get the cut scene events more than once. After clearing a line (abyssite color) it simply loops you back to the bottom tier.

**Comment by TeoTwawki** [comment]
As in just go kill, at the t1 rift no

**Comment by Xenriv** [comment]
Thanks for the reply.  I understand that each tier should revert back to T1 upon completion of the last tier but in this case, the White Stratum Abyssite simply did not revert back to T1, it disappeared and not in my KI list.  I have KIs for every other VW tier including cities, ashen, hyacinth, amber.   Do I redo the 3 city lines > re-obtain white automatically or through quest CS's at pashhow conflux > ru'lude?  Thx in advance.

**Comment by R3P0FFXI** [comment]
@Xenriv yes start from the beginning and do each teir upgrading etc then turn it in for the white stratum same as you did before

**Comment by TeoTwawki** [comment]
@R3P0FFXI wrong. GM him the WHITE_STRATUM_ABYSSITE

**Comment by TeoTwawki** [comment]
@LegionDark/gm I put out a hotfix so this doesn't happen anymore.  affected players still need the GM command run on them. see also #1353

**Comment by JessLand86** [comment]
Taken care of in game.
