### ISSUE TITLE
Alchemy guild NPC Titus causing game crash error

### ISSUE THREAD

**Issue by alannor** [LegionDark/Issues#1457]
**Date & Time**: 
2017/5/2

**FFXI Client Version (use `/ver`)**: 
Current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Ryeso, Meisu

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
Various 

**NPC or Monster or item Name**: 
Titus

**Zone name**: 
Bastok Mines

**Coordinates (use `$where`)**: 
L7, sorry not in game cant provide coordinates

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Logged on behalf of Ryeso, Susu, Meisu

Spoke to Titus in alchemy guild. After gamed crashed and when Ryeso tried to log on again recoed error FFXI-2003, failed to read data. Moved Meisu into area, did not speak to NPC and the same bug appeared. 

Able to log on using the same client to log onto Susu, works fine.

Unsure what is causing the bug. And doesnt seem like an install issue since able to log on with Susu?!

**Comment by alannor** [comment]
Could you please contact Susu in game. He didnt know how to raise ticket so did it on his behalf

**Comment by Vaneticorum** [comment]
When I get an error FFXI-2003, I close Windower/Ashita. Next, I open the application again, get to the character selection screen and close Windower/Ashita (without logging into the game). Afterwards, I can usually log in normally again.

Not sure this will work for you, but, I hope it does. I have no idea how to help with NPC causing the crash.

**Comment by Heepster03** [comment]
I have tried to duplicate this issue and I can't. Titus is working as intended for me.
