### ISSUE TITLE
Sam Flag

### ISSUE THREAD

**Issue by Vorpel** [LegionDark/Issues#1458]
**Date & Time**: 
05/02/2017 ~03:00PM EST

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Vorpel

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
65BLM/32RDM

**NPC or Monster or item Name**: 
Forger (Mob) / Bomb Steel (item)

**Zone name**: 
Konschtat Highlands

**Coordinates (use `$where`)**: 
X:-707 Y:2 Z: 103 (116)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
Kill forger...
Apparently only happens in groups??

**Comment by R3P0FFXI** [comment]
Apparently only what happens In groups details are your friend

**Comment by Vorpel** [comment]
When killing the Forger in groups it seems one player is chosen for the loot while the other gets the flag but no loot. That was what happened to us anyway. 1 other player. Upon removing the party member i received the loot correctly.

**Comment by TeoTwawki** [comment]
It is *normal*  to have to it once for each person

**Comment by Vorpel** [comment]
Correct however the loot directed to the same person on both occasions regardless of who activated the fight. We even tried last hitting to see if that would trigger the loot. It did not.

**Comment by TeoTwawki** [comment]
multiboxing at any point in the players session can gum up the variables involved.

**Comment by TeoTwawki** [comment]
as in if they had an alt on several hours ago..it'll still effect them

**Comment by TeoTwawki** [comment]
one sec, checking the npc/mob script

**Comment by TeoTwawki** [comment]
ok yeah, this is handled entirely via normal loot pools: person who popped it should cast lots. in the same party you should see the same loot pool, it doesn't drop to any specific person...

**Comment by Vorpel** [comment]
ah ok so it drops as a treasure then?

**Comment by TeoTwawki** [comment]
yep, and due to dsp not handling the treasure pool correctly this means the person who spawned needs to make sure they have room (and sort because of invisible item the sort bug!) and cast lots, and everyone else needs to pass. if someone doesn't pass it can still auto fall to wrong person.

**Comment by TeoTwawki** [comment]
dsp bugs. dsp bugs everywhere.

**Comment by Vorpel** [comment]
Thank you :)
