### ISSUE TITLE
Craft Import Request for Neonracer

### ISSUE THREAD

**Issue by neonracer** [LegionDark/Issues#1459]
**Date & Time**:  May 2, 2017 @ 5:10 p.m

**FFXI Client Version (use `/ver`)**:  ver 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Neonracer

**Nation**: Bastok

**Job(level)/Sub Job(level)**: THF75/DNC37

**NPC or Monster or item Name**: 

**Zone name**:  South Gusterberg 

**Coordinates (use `$where`)**:  X-353 Y30 Z-440 (96)

![neonracer_2017 04 26_222235](https://cloud.githubusercontent.com/assets/28202863/25640066/259e8498-2f5c-11e7-8394-afa381fc6c95.png)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: Server craft transfer please and thank you Picture of crafts are included in this file ticket report. One picture was included on the legiondark forumsite inside .zip file. hopefully this .png file got loaded here. again thank you for your support.

**Comment by Heepster03** [comment]
Crafts transferred~
