### ISSUE TITLE
Unable to get voidstones.

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1460]
**Date & Time**: 
5/3/2017 05:52

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99Rdm/whm

**NPC or Monster or item Name**: 
Voidwatch officer

**Zone name**: 
South Sandy

**Coordinates (use `$where`)**: 
-106, 2, -18

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Have 22 voidstones, went and talked to the Voidwatch officer in south Sandy, still have 22 after, Keeps repeating the Debug: Voidstone Check each time they are talked to. Tried this on multiple toons, checking stones before and after talking to the VW officer.

**Comment by TeoTwawki** [comment]
Besides the debug print what is the npc dialog?

**Comment by Darkara** [comment]
I'm currently having the same issue. Debug dialog still appears but no message saying you were given a voidstone, and none added to current count.
![darkara_2017 05 03_144109](https://cloud.githubusercontent.com/assets/25020062/25678301/e23b8940-300e-11e7-8bb3-79a769480964.png)

**Comment by TeoTwawki** [comment]
Please hold off on the "me too!"s. Fact is most ppl who report this are simply effing WRONG about what is happening form 2 factors entirely out of my control and DID in fact get their voidstones without knowing it: the packet that handles the currency menu is BROKEN in darkstar, and the message offsets change constantly. tl:dr don't echo things already said, unless asnwering a question sit back and wait till we know more.

**Comment by TeoTwawki** [comment]
Added additional info messaging, appears to work just fine barring "key item obtained" message getting screwed by updates, and currency menu packets being trashed 9/10 times I look. Both are darkstar problems. The new message will display the total voidstone a player has regardless of the timer state.

Unless you see the EXACT message *"Voidstones are issued once per Earth day."* you did in fact get your voidstone.
