### ISSUE TITLE
Bihu Jstcorps +1 not have Accuracy+27 Attack+27

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1461]
**Date & Time**: 3/05/17

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Rukitsu

**Nation**: sandy

**Job(level)/Sub Job(level)**: brd

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/26819/bihu-jstcorps-1

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: Bihu Jstcorps +1 not have Accuracy+27 Attack+27 maybe need other stats

**Comment by R3P0FFXI** [comment]
@Aurelcassy issue resolved in todays update
