### ISSUE TITLE
AH Issue

### ISSUE THREAD

**Issue by Bombacloud** [LegionDark/Issues#1462]
**Date & Time**: 5/3/17 7 pm

**FFXI Client Version (use `/ver`)**:  Current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: bombacloud

**Nation**: sandoria

**Job(level)/Sub Job(level)**: Blu99/rdm49

**NPC or Monster or item Name**: n/a

**Zone name**: AH

**Coordinates (use `$where`)**: n/a

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: I placed my blurred knife on the ah for 11.1 mil and someone purchased it for 100k. I think someone may have hacked the ah to make this happen. Thank you for looking into this.

**Comment by TeoTwawki** [comment]
Nope, that didn't happen. Sorry to tell you but you goofed your listing. The AH record is made from separate entries that nobody has access to making hacking your listing impossible. I can see what you listed at, *and* what the buyer actually bid.
Listed: 11,100
Payed: 100,000
