### ISSUE TITLE
Help please :Immortal Sentries

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1463]
**Date & Time**: 6/5/2017

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Myeva

**Nation**: sandy

**Job(level)/Sub Job(level)**: rdm

**NPC or Monster or item Name**: Naja Salaheem

**Zone name**: Aht Urhgan Whitegate (I-10)

**Coordinates (use `$where`)**: X:26 Y:-7 Z:-45 (247)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: Supplies Package seems to have disappeared from my key item list (the item Naja asks you to deliver to one of the staging points). Attempted to bring to Caedarva Mire Staging area and Halvung. The NPC's in those respective areas were unresponsive. Attempted to return to Naja and she also was unresponsive.

**Comment by Heepster03** [comment]
Just verified online:

- Current Treasures of Aht Urhgan Mission ID is: '1' !

- Player 'Myeva' variable 'AhtUrhganStatus' : 0

**Comment by TeoTwawki** [comment]
Status zero should be triggering the CS event ***outside*** **the sentinels office before they reach Naja..**

**Comment by TeoTwawki** [comment]
Chalking it up to multiboxing bug yet again. Would you mind GM'ing him the KI for me @Heepster03 ?

**Comment by Heepster03** [comment]
Alright, keyitem has been added to Myeva.

**Comment by Heepster03** [comment]
@Aurelcassy Try the mission again and see if it works now, thanks.

**Comment by Aurelcassy** [comment]
THANKS , now work fine
