### ISSUE TITLE
Refresh Potency on Leth. Fuseau non-functional

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1464]
**Date & Time**: 
Mat 7, 2017, 1:31 AM

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Tbone

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
RDM99

**NPC or Monster or item Name**: 
Leth. Fuseau
Leth. Fuseau +1

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/27245/leth-fuseau
http://www.ffxiah.com/item/27246/leth-fuseau-1

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
 The "Refresh Potency +1/+2" do not increase the potency of refresh.

As a work around until it is implemented in DSP, should at least have Refresh+1/+2 on the pants :-)

**Comment by tb1** [comment]
Looks like Teo already added this to DSP months ago.

**Comment by tb1** [comment]
https://github.com/DarkstarProject/darkstar/commit/6e7484c9eb5f2520634a51137cc8584e63325caf

**Comment by TeoTwawki** [comment]
> As a work around until it is implemented in DSP

I smite co-devs and contributors who make substitutions. Just puttin that out there >.>

**Comment by Heepster03** [comment]
Believe it or not, it's not the mod that's the issue, the gear is missing the modifier altogether.

> ENHANCES_REFRESH = 529, // "Enhances Refresh" adds +1 per modifier to spell's tick result.

**Comment by Heepster03** [comment]
I'll fix this and add it to my next Abyssea PR that I've been working on.

**Comment by Heepster03** [comment]
@tb1 , I added the missing mods to NQ/HQ pants, sent to DSP.
