### ISSUE TITLE
Dracons Craft Restore ticket

### ISSUE THREAD

**Issue by Smurb7** [LegionDark/Issues#1466]
**Date & Time**: 
0955 07MAY2017

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
y

**Character Name**: 
Dracons

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
99THF/49DNC

**NPC or Monster or item Name**: 

**Zone name**: 
Lower Jueno

**Coordinates (use `$where`)**: 
AH

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Respectfully requesting restoration of craft skills
![img_20170501_203902](https://cloud.githubusercontent.com/assets/28492054/25781735/4ecca464-330b-11e7-8160-2e907f5178db.png)
Character renamed Dracons on legiondark server.
Thank you.

**Comment by Heepster03** [comment]
Crafts Transferred~
