### ISSUE TITLE
tricolor emblem not working 

### ISSUE THREAD

**Issue by salazer** [LegionDark/Issues#1467]
**Date & Time**: 5/8/17 4:10 pm est

**FFXI Client Version (use `/ver`)**: 30170329_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Emel

**Nation**: bastok

**Job(level)/Sub Job(level)**: bluemage/rdm

**NPC or Monster or item Name**: voidwatch planar rift

**Zone name**: South Gustaberg

**Coordinates (use `$where`)**: L-9

**ffxiah.com link (for items issues only)**: voidstone

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: i fin jeuno teir 6 nm's got tricolor emblem i should be able to pop any completed VW planar rift nm's  i tried to pop a nm but nothing happened went to talk to void officer nothing went to pashhow marshlands [s] Veridical Conflux no cs went to Ru'lade Gardens Audience Chamber no cs went to Bulwark Gate in Saurmague[S] no cs talk to npc Owian nothing i can't advance or pop old nm's i already fin  i have voidwatcher's emblem: jeuno ,qufim and tricolor

**Comment by R3P0FFXI** [comment]
@salazer this is working as intended, as we have said many times we have it said to remove your KI at the end of the chapter you need to start over again

**Comment by TeoTwawki** [comment]
This will work more like you were expecting after a future update. For now this is expected behavior
