### ISSUE TITLE
Ranger TP

### ISSUE THREAD

**Issue by Vorpel** [LegionDark/Issues#1468]
**Date & Time**: 
Always

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30170304_1

**Character Name**: 
Vorpel

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
RNG 16/RDM 8

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 
anywhere

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Upon using a TP skill if the mob moves out of range or is not in range to begin with it will still reset RNG TP to 0

**Comment by Heepster03** [comment]
This is how melee has always been, if you're out of range and use the WS, you lose the TP, the only stipulation to being able to WS is being engaged.

**Comment by TeoTwawki** [comment]
This is. Normal, was range isn't the same as ranged attack range - can very by ws. That said dap may have the distances off from retail I dunno. There are some incoming distance calc changes related to mob size which may also effect this. If after maintenance you still think there is a problem, contact darkstar about it.
