### ISSUE TITLE
Hvergelmir  119 need check 

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1469]
**Date & Time**: 9 -5-2017

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Aurel

**Nation**: sandy

**Job(level)/Sub Job(level)**: sch -blm

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/21144/hvergelmir

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 

This staff, have 0 magic damage, versus similar staff  ,I use aero and magic damage  is  500 other staff similar the magic damage is 1400   
No have bonus critical damage and damage critical x4

**Comment by R3P0FFXI** [comment]
MOD_MAGIC_DAMAGE          = 311 --  Magic damage added directly to the spell's base damage

current mod is (28): Magic Attack +100 needs to be removed

**Comment by TeoTwawki** [comment]
multiple items have the same substitution, to be corrected during/after reorg so as to not totally break what semblance of balance we have form mobs that were built *with* such insanity already in place. (just reminding y'all)

**Comment by Heepster03** [comment]
I added the missing Magic Damage, sent to DSP.
