### ISSUE TITLE
BLM Nuking for 0

### ISSUE THREAD

**Issue by Alesaye** [LegionDark/Issues#147]
**Date & Time**:   7-8-15   5:02am CST
**Frequency**:  appears to be after 75 i think
**FFXI Client Version**:  30150619_2
**Character Name**:  Alesaye
**Race**:   Mithra
**Main Job**:   BLM99
**Sub Job**:   RDM49
**Area & Coordinates**:   Valkurm Dunes (just outside of Selbina gate)
**Party or Solo**: Solo
**NPC Name**:  n/a
**Monster Name**:  Damsel Fly
**Multi-boxing? (multiple clients on same connection)**:  yes, Alessa & Aisha
**Steps To Reproduce The Issue**:
 I changed to BLM after someone had stated numerous times they were nuking for 0.
 went to valk and grabbed a fly to kill.
 casted blizzard4. it hit for 0.
 casted blizzard 5. it hit for 0.
casted thunder2. it hit for 0.
noticed a lvl 60 blm in the zone and asked them to cast some elemental magic.
their spells did appropiate dmg.
also tested on Alessa's 99sch and her spells are fine as well.
was told that rdm's spells are fine as well.
it appears to be only blm above 75 or so since the maint.

**Comment by R3P0FFXI** [comment]
This is a DSP issue they have just issued a pull request for it we will need to pull it and go into maint mode again to fix the issue

https://github.com/DarkstarProject/darkstar/pull/1678

**Comment by R3P0FFXI** [comment]
Issue completed in hotfix
