### ISSUE TITLE
Terpsichore 119 not granting additional finishing move for steps

### ISSUE THREAD

**Issue by daronis17** [LegionDark/Issues#1470]
**Date & Time**: 5/19/17 10:00PM

**FFXI Client Version (use `/ver`)**: 30170329_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: no (30170304_1)

**Character Name**: Jordia

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: Dnc(99)/Nin(49)

**NPC or Monster or item Name**: Terpsichore ilvl 119

**Zone name**: everywhere (currently in Abyssea Misareaux)

**Coordinates (use `$where`)**: X:-82 Y:-32 Z:-322 (121)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/20558/terpsichore

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: No additional finishing moves are granted for doing steps.  I still get 2 finishing moves per step until getting 5 stacks of the debuff on the mob, then I get 1 finishing move per step.  That dagger is supposed to grant one additional finishing move per step so it should be getting 3 per step until 5 stacks and then 2 per step after.  I've tried in offhand, mainhand, and mainhand not dual wielded but the results are the same.  Per bg-wiki it should give +60 to Step Accuracy (hard to test if that is implemented but my steps still do miss some) and it also increases the damage of the weapon skill Pyrrhic Kleos by 30% as well [https://www.bg-wiki.com/bg/Terpsichore_(Level_119) ].  Not sure if that stuff is on it or not but thought I would point that out since the step finishing move part of the weapon isn't working.

**Comment by Jessland86** [comment]
https://www.bg-wiki.com/bg/Terpsichore_(Level_119_II), but same buffs.

**Comment by Heepster03** [comment]
https://github.com/LegionDark/Issues/issues/270

Same problem with lvl 75 version. It's the mod.

**Comment by Jessland86** [comment]
Condensing to just the one open issue since it's the same issue.
