### ISSUE TITLE
Jaguarundi don't agro

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1472]
**Date & Time**: 
May 11, 2017 - 10:58 PM (post-update)

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Tbone

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
NIN/DNC

**NPC or Monster or item Name**: 
Jaguarundi

**Zone name**: 
Abby - Tahrongi Canyon

**Coordinates (use `$where`)**: 
X:-126 Y:15 Z:241 (129)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
No sneak or invisible up, Jaguarundo are not agroing like they should be.

**Comment by tb1** [comment]
Looks like the beholder's and cocktrices don't agro either.

**Comment by tb1** [comment]
Add scorpions to the list.  Looks like most of these mobs need to be double checked.

**Comment by tb1** [comment]
The agro on tons of mobs in various abby zones are off, some mobs that should agro don't, others that shouldn't agro do.  I don't have an exhaustive list however.

**Comment by TeoTwawki** [comment]
@tb1 r3 left out the agro/link flagging when he submitted legions mobs to dsp. he's going back through that to get it in.

**Comment by tb1** [comment]
I noticed a bunch are out of whack, some stuff that should agro doesn't, stuff that shouldn't agro does, some are right, other aren't.  I found a ton in various abby zones, didn't list them since I figured you guys were going through them anyway.

**Comment by R3P0FFXI** [comment]
@tb1 @TeoTwawki fixes submitted to DSP
