### ISSUE TITLE
Leviathan's Barracuda Dive Ability Is Non-Functional

### ISSUE THREAD

**Issue by Daruvan** [LegionDark/Issues#1475]
**Date & Time**: May 12th, 11:45 AM EDT

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Daru

**Nation**: Windurst

**Job(level)/Sub Job(level)**: SMN20 / RDM 10

**NPC or Monster or item Name**: Leviathan

**Zone name**: Konschtat Highlands

**Coordinates (use `$where`)**: X-188 Y:64 Z:529 (4)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Able to select and send command for Barracuda Dive, both in menu and in macro, but nothing else happens.  Blood Pact: Rage charge is used, as well.

**Comment by Raelious** [comment]
There are a handful of Bloodpact Wards/Rages that do not work. I can give you a list of them later on.

**Comment by TeoTwawki** [comment]
probably related:
https://github.com/DarkstarProject/darkstar/issues/2729
https://github.com/DarkstarProject/darkstar/issues/3709

**Comment by Raelious** [comment]
@TeoTwawki just tested this works correctly now. Can close if you want.
