### ISSUE TITLE
Qutrub Mob Animation Bug

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1476]
**Date & Time**: 
May 12, 2017 - 9:43 PM MST

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Tbone

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
RDM99

**NPC or Monster or item Name**: 
Qutrub

**Zone name**: 
Arrapago Reef

**Coordinates (use `$where`)**: 
176 -3 193 (80)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
When the Qutrub mobs move, they blink and you lose target.  I noticed an NM in Abby Tahogri doing something similar yesterday, but didn't investigate (thought it was something different).

**Comment by TeoTwawki** [comment]
its because @R3P0FFXI accidentally undid my fix in spite of my big neon sign comment in the file, so I get to redo that..
