### ISSUE TITLE
AU NPC Wahraga selling Relic Staff instead of Wind Fan

### ISSUE THREAD

**Issue by EpicTaru** [LegionDark/Issues#1477]
**Date & Time**: 
05/13/2017 @ 1815 PST

**FFXI Client Version (use `/ver`)**: 
30170427_0 <- Teo is aware of my current client version.  My client version is not the cause of this issue.

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30170304_1

**Character Name**: 
EpicTaru

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
THF99/DNC49

**NPC or Monster or item Name**: 
Wahraga

**Zone name**: 
Aht Urhgan Whitegate

**Coordinates (use `$where`)**: 
X:- 76 Y: -6 Z: 137 (192)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/18326/relic-staff
http://www.ffxiah.com/item/18236/wind-fan

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
/check Wahraga (at Alchemists' Guild).
Observe there is no Wind Fan in the list of items buyable from the NPC.
Observe there is a Relic Staff in the list of items buyable from the NPC.

FFXIAH was used to identify the Item IDs for both of the above items. Appears that the 2 and the 3 in the Item ID were transposed in place of each other, causing the Relic Staff to be a buyable item in place of a Wind Fan.

I did confirm that you can buy a Relic Staff from this NPC. Thanks for all you do!

EpicTaru

![capture](https://cloud.githubusercontent.com/assets/26195580/26029661/a23db76c-37ef-11e7-9f74-41ccbcb8407c.PNG)

**Comment by Heepster03** [comment]
Teo fixed this for future maint/update~
