### ISSUE TITLE
Attempting to learn magic via Scroll while level synced causes client crash.

### ISSUE THREAD

**Issue by Acedffxi** [LegionDark/Issues#1479]
**Date & Time**: 
5-14-17

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Fabbri

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
BLM99/RDM49 (Was BLM82/RDM41 when it occured)

**NPC or Monster or item Name**: 
Frazzel Scroll

**Zone name**: 
Korroloka Tunnel

**Coordinates (use `$where`)**: 
X:-346 Y:-10 Z:266 (61)

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
I used a scroll of Frazzel while under level sync. The scroll is RDM42 and my subjob was RDM41 at the time. Obviously couldn't have learned it anyways but still shouldn't cause a crash I guess?

**Comment by TeoTwawki** [comment]
Forwarding to DSP

**Comment by TeoTwawki** [comment]
https://git.io/v9FQd
