### ISSUE TITLE
unable to break pearls if ls is equipped as ls2.

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#1482]
**Date & Time**: 5/16/2017

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: pld99/war49

**NPC or Monster or item Name**: na

**Zone name**: na

**Coordinates (use `$where`)**: na

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: This is something that I've come across in the past but I figured I'd finally make a report on it since I searched and there wasn't one already.  Basically whatever linkshell is equipped as linkshell 2, that pearl can't be broken/kicked, even by the owner of the ls.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/2569

**Comment by Jessland86** [comment]
Fixed in the last maintenance.
