### ISSUE TITLE
Unable to pop Sedna in Abyssea-Vunkerl after 05/11/17 update

### ISSUE THREAD

**Issue by EpicTaru** [LegionDark/Issues#1483]
**Date & Time**: 
05/18/2017 @ 0233 PST

**FFXI Client Version (use `/ver`)**: 
03072407_0 - Teo is aware of the reason for my client version not matching the server version.  This mismatch is not the cause of this issue (as player Ripz also verified this).

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
03170304_1

**Character Name**: 
EpicTaru

**Nation**: 
Sand'Oria

**Job(level)/Sub Job(level)**: 
THF99/DNC49

**NPC or Monster or item Name**: 
Sedna

**Zone name**: 
Abyssea-Vunkerl

**Coordinates (use `$where`)**: 
??? at X:403, Y:-31, Z:391 or ??? at X:402, Y:-31, Z:405 - Retail spawn points

??? at X:-201, Y:-39, Z:265 - Buhkis island, where the ??? used to spawn Sedna was located prior to 
the 05/11/17 update.  After the 05/11/17 update, neither ??? responds when examined.

??? at X:-201, Y:-40, Z:-280 - Buhkis island, this ??? is used to pop Buhkis and responds correctly for KIs needed to pop Buhkis

??? at X:-201, Y:-39, Z:-295 - This ??? does not respond at all when examined.

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
BG-Wiki shows that the retail location of the ??? used to pop Sedna (if you are in possession of the necessary KIs, of course) is in gridsquare K-6 of Abyssea-Vunkerl (2 ??? were found in that gridsquare; they are listed in the Coordinates section above)

Prior to the 05/11/17 update, 1 of the 3 ??? on Buhkis island were used to pop Sedna.  Another ??? on Buhkis island is used to pop Buhkis.  Another ??? on Buhkis island doesn't respond.

After the 05/11/17 update, neither of the retail locations of the ??? respond.  The ??? on Buhkis island that was used to pop Sedna now also doesn't respond.

An exhaustive scan of the entire map, performed by player Ripz and myself, could not locate a ??? that responds with the KIs needed to pop Sedna.

Thank you for your time and assistance with this issue.

EpicTaru

**Comment by Heepster03** [comment]
I just fixed this and tested it myself to see that it was working as intended. I will look to see what happened.

**Comment by Heepster03** [comment]
Okay @EpicTaru , I found the issue, this will have to be pulled into the next maint/update after I submit the fix to DSP.

**Comment by EpicTaru** [comment]
Copy copy good sir, thanks very much for the speedy response! :D
