### ISSUE TITLE
Entozoon in Aby Attohwa missing model

### ISSUE THREAD

**Issue by daronis17** [LegionDark/Issues#1484]
**Date & Time**: 5/18/17 7:43AM est

**FFXI Client Version (use `/ver`)**: 30170329_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170304_1

**Character Name**: Jordia

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: Dnc (99)/Nin(49)

**NPC or Monster or item Name**: Entozoon

**Zone name**: Abyssea Attohwa

**Coordinates (use `$where`)**: X:308 Y:20 Z:236 (217)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: I know that some worms in other Aby zones were already reported to not have models.  I just wanted to confirm that these worms do not as well (I didn't see them mentioned in the other ticket about worm models).  These are the burrowing type of worms and not the ones that look like Glavoid so I don't know if these type of worms in other zones are missing models as well, haven't had the chance to check.  They show up in widescan.  They fill the chat log with 'Entozoon starts casting Stoneskin' ....followed by 'casting is interrupted'.

**Comment by daronis17** [comment]
I went into Abyssea La Theine and both the Rock Grinders and Megamaw Mikey have models and appear fine.  They should be the same or similar models to the Entozoons in Abyssea Attohwa so maybe it's just those worms that lost their model.

**Comment by TeoTwawki** [comment]
known issue, being handled

**Comment by TeoTwawki** [comment]
Should be fixed after maint
