### ISSUE TITLE
Promethia mission PM8-1 for both characters

### ISSUE THREAD

**Issue by gori123** [LegionDark/Issues#1485]
**Date & Time**: 18/05/17

**FFXI Client Version (use `/ver`)**: 30170329_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170304_1

**Character Name**: Sabutay  & Tonton

**Nation**:  Sandoria

**Job(level)/Sub Job(level)**: 99 war/49thf 99 rdm/49blm

**NPC or Monster or item Name**:  PM8-1  repeating cs 
check the Gate of the Gods (H-8) for a final cutscene and your reward cs is broken. 

**Zone name**: Grand palace of Hu'xzoi

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: You can not posses more than one of that item error appers when i try to get CS of mission PM8-1

**Comment by Jessland86** [comment]
Player already has item Tavnazian ring, Drop the item then recheck the gate of the gods to receive a new one. This is not a bug.

**Comment by Jessland86** [comment]
![image](https://cloud.githubusercontent.com/assets/28382433/26207287/1a8cf1a6-3bb5-11e7-8e8c-5359157b3d7f.png)

**Comment by Jessland86** [comment]
![image](https://cloud.githubusercontent.com/assets/28382433/26207343/407b4a3e-3bb5-11e7-84e9-81aeb68bbeec.png)

**Comment by gori123** [comment]
Many thanks for solving my issue so fast
