### ISSUE TITLE
Character showing twice in party list

### ISSUE THREAD

**Issue by Devilotte** [LegionDark/Issues#1486]
**Date & Time**: 
5/18/2017 1:05PM PST

**FFXI Client Version (use `/ver`)**: 
30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Darcia

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
99BLU/49BLM

**NPC or Monster or item Name**: 

**Zone name**: 
White Gate

**Coordinates (use `$where`)**: 
X-135 Y2 Z10 (84)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
I logged in another character while multiboxing and their name showed twice in the party list on their client while not in a party. When I invited them and they accepted my invite, this also happened
![darcia_2017 05 18_130204](https://cloud.githubusercontent.com/assets/24705936/26221369/1186053c-3bcb-11e7-96ad-8895afce2518.png)
When I had them disband group, Darcia no longer shows twice in the party list on Darcia's client. but their character still shows in my party's group on my other character's client.

**Comment by Heepster03** [comment]
This happened to me once before, I believe it was linked to something with Ashita. I unloaded all of my addons/plugins, zoned, and left party.

**Comment by Heepster03** [comment]
Did it fix it?

**Comment by TeoTwawki** [comment]
no reply after 20 days, closing
