### ISSUE TITLE
Voidwatch Ordelles 

### ISSUE THREAD

**Issue by stevomatic** [LegionDark/Issues#1487]
**Date & Time**: 6:28pm est 5/19/2017

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: 
Agnes

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 
pld99/war49

**NPC or Monster or item Name**: krabimanjaro

**Zone name**: 
ordelle's cave

**Coordinates (use `$where`)**: 
x-112 y31 z230 (40)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

yes
**Steps To Reproduce / any other info**: planar rift model isn't displayed correctly and untargetable. I popped Krabimanjaro from another rift and ran over, the mob appears on widescan but is invisible, untargetable and doesn't aggro, then despawns from widescan.

**Comment by Jessland86** [comment]
I just spawned this no problem, make sure you are spawning this at the correct planar rift.

**Comment by Jessland86** [comment]
This is where the correct planar rift is.
![image](https://cloud.githubusercontent.com/assets/28382433/26272381/aa5726f0-3ce4-11e7-8342-67b290890a02.png)

**Comment by Jessland86** [comment]
You were also seeing the bleed thru from the correct planar rift that was straight up on the floor/map above.

**Comment by TeoTwawki** [comment]
retail ones sometimes bleed through the floors and ceilings like that to.
