### ISSUE TITLE
2k and 4k needles are single target

### ISSUE THREAD

**Issue by Acedffxi** [LegionDark/Issues#1489]
**Date & Time**: 
5-21-17 10:35 PM CST

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Freelot

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
PLD99/WAR49

**NPC or Monster or item Name**: 
Sabotender Campeador |  Emperador de Altepa

**Zone name**: 
Western Altepa Desert | Abyssea - Altepa

**Coordinates (use `$where`)**: 
(Western - X:573 Y:0 Z:234 (64))

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
When they use 2k and 4k needles they are hitting single targets rather than AOE spread damage. Only 1K needles is aoe. Clearly outside of Abyssea 4k needles is basically death no matter what.

**Comment by TeoTwawki** [comment]
woopsie!

**Comment by Acedffxi** [comment]
<3

**Comment by TeoTwawki** [comment]
@R3P0FFXI wasn't you

**Comment by TeoTwawki** [comment]
I missed this in todays maint, but it has been fixed and the server will notice next time the map reloads..Sorry about that

**Comment by Acedffxi** [comment]
No problem, thank you. So after a crash?

**Comment by TeoTwawki** [comment]
Any kind of restart, crash or not.

Hopefully we just nail next client update immediate instead of crashing before then.

**Comment by Acedffxi** [comment]
Okay cool. Was just something unexpected I came across when farming blu
seals lol. Thanks for the info
