### ISSUE TITLE
Level sync option available when level sync is wearing off

### ISSUE THREAD

**Issue by Roamin** [LegionDark/Issues#149]
**Date & Time**: 2015 July 8th , 12:30 pm EST
**Frequency**: All the time
**FFXI Client Version**: 30150619_2
**Character Name**: Roamin
**Race**: Taru
**Main Job**: Warrior
**Sub Job**: Samurai 
**Area & Coordinates**: Anywhere
**Party or Solo**: Party
**NPC Name**: Not applicable
**Monster Name**: Not applicable
**Multi-boxing? (multiple clients on same connection)**: Not applicable
**Steps To Reproduce The Issue**:

Level sync to someone.  Have that person leave the zone. As the party leader , go in party menu , and now the option to "Level Sync" is already available. Choose it, and select anyone in the party that is not leaving and you will now sync to that person, at the same level as the original synced character who just left. This will remain until the new person with the sync levels.

So Level Sync option should be blocked until level sync has worn off , it should let me know when I try to sync to a character that it will not allow that until level sync has worn off.

**Comment by R3P0FFXI** [comment]
Per DSP same issue as https://github.com/DarkstarProject/darkstar/issues/1680
