### ISSUE TITLE
Aht Urhgan Mission 2: Immortal Sentries Key Item missing.

### ISSUE THREAD

**Issue by Stealthsoft** [LegionDark/Issues#1490]
**Date & Time**: 2:00pm CST 5/22/2017

**FFXI Client Version (use `/ver`)**: 30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170304_1

**Character Name**: Stealth 

**Nation**: Bastok

**Job(level)/Sub Job(level)**: THF99/RDM49

**NPC or Monster or item Name**: KI "Supplies Package"

**Zone name**: Aht Uhrgan Whitegate

**Coordinates (use `$where`)**: X: 25 Y: -7 Z: -44 (71)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No 

**Steps To Reproduce / any other info**: Aht Urhgan Mission 2: Immortal Sentries
I am unable to progress in this mission because the Supplies Package (Temporary Key Item) is missing. Naja Salaheem (quest giver) repeats dialogue, cannot speak to Immortals at staging point, or use Runic Portal to return. Tried twice, NPC at staging point doesn't interact. Noticed while filling out report that I'm running an unexpected version, I recently re-joined after a 7 month break and re-updated.

**Comment by Stealthsoft** [comment]
I noticed while searching the forums that there was a mention of a wiki page about the Ah Uhrgan Missions, but was unable to locate it.

http://legiondark.com/forums/viewtopic.php?f=68&t=1438&p=4786&hilit=Staging+Point#p4786

**Comment by TeoTwawki** [comment]
> I recently re-joined after a 7 month break and re-updated.

yeeeap we fixed that while you were going but you need a GM to fix you in game because you were on mission before it was fixed 😃 

@LegionDark/gm `$addkeyitem` the man.

**Comment by Jessland86** [comment]
Added KI supplies package to Stealth in game.
