### ISSUE TITLE
Orthrus not using Dread Spikes

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1492]
**Date & Time**: 
May 23, 2017 - 2:48 AM (MST)

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Tbone

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
PLD/WAR

**NPC or Monster or item Name**: 
Orthrus

**Zone name**: 
Abby - Altepa

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Asside from the broken agro and ??? all messed up again (which I believe has already been fixed and scheduled for next maintenance), after 6 kills, I haven't seen Orthrus use Dread Spikes even once.

He has been using Magma Hoplon (Stoneskin+Blaze Spikes) and I believe he's been casting Blaze Spikes too.  Unsure if this is related to recent bugs or has been addressed already for an upcoming update.

I much prefer this nicer Orthrus to the mean Dread Spikes one because I can't suicide on his spikes anymore.

**Comment by R3P0FFXI** [comment]
@tb1 do not report any mobskill issues for now, It is a current project for me I am going through line by line to verify all is correct

**Comment by TeoTwawki** [comment]
@tb1 theres been some removing of non retail spells and skills from abyssea. this will continue in the reorg as we move custom content onto non retail mobs instead of never being sure who did what to the retail ones
