### ISSUE TITLE
New Transfer Ticket For Craft Adjustment

### ISSUE THREAD

**Issue by Kimon0** [LegionDark/Issues#1493]
**Date & Time**: 
5/24/2017 12:34PM PST

**FFXI Client Version (use `/ver`)**: 
0170329_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Kiwa

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
99THF/--

**NPC or Monster or item Name**: 
N/a?

**Zone name**: 
Northern San d'Oria

**Coordinates (use `$where`)**: 
M-10

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Submitting Ticket for adjustment of crafts after server transfer
Added Picture for reference

![craft](https://cloud.githubusercontent.com/assets/28934517/26422560/3f39788e-407f-11e7-9d2e-2a4e5865662f.JPG)

**Comment by Jessland86** [comment]
Crafts imported.
