### ISSUE TITLE
Bennu is currently Unspawnable.

### ISSUE THREAD

**Issue by Darkara** [LegionDark/Issues#1494]
**Date & Time**: 10:21

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170304_1

**Character Name**: Darkara

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 99blu/49rdm

**NPC or Monster or item Name**: Bennu

**Zone name**: Abyssea - Altepa

**Coordinates (use `$where`)**: x:79 y:0 z:-129 (205)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: The ??? at the above cordinate (I-8) does not ask for a key item, this is where he was popped prior to the last software update. There is also not another ??? in I-8 that asks for his keyitem either.

**Comment by Heepster03** [comment]
This will be fixed in the next update.
