### ISSUE TITLE
Arimaspi is unpopable now

### ISSUE THREAD

**Issue by arkooqymoya** [LegionDark/Issues#1495]
**Date & Time**: 2017/5/26

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: arkoo

**Nation**: bastok

**Job(level)/Sub Job(level)**: 99thf/49dnc

**NPC or Monster or item Name**: Arimaspi (the flying eyeball nm which is used to pop kukulkan)

**Zone name**: abyssea-kon

**Coordinates (use `$where`)**: X:438 Y:32 Z:357(126)

**ffxiah.com link (for items issues only)**:  http://ffxiclopedia.wikia.com/wiki/Arimaspi

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**:  no respones to the pop item "Clouded Lens" , its one of the 3 pop site for kukulkan,i will go check the other 2 site.

**Comment by arkooqymoya** [comment]
Keratyrannos (the other one for kukulkan poping mob )is not responding too,and pop message is wrong.
$where: X:-135 Y:47 Z:417 (32)

kukulkan 's pop mark is responed a wrong message, the $where is X:-26 Y:69 Z:559(252)
and at the kukulkan's pop site where is the EE(Eccentric Eve)'s pop mark there
,the $where is X:-39 Y:71 Z:559(196)

**Comment by TeoTwawki** [comment]
https://github.com/LegionDark/Issues/issues/1478

**Comment by Heepster03** [comment]
This will be fixed next update.
