### ISSUE TITLE
Lost Voidwatch Abyssite KIs

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1498]
**Date & Time**: 
May 29, 2018 8:35 PM

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30170304_1  (yes)

**Character Name**: 
Tbone
Pockethealer
Girlieman
One
Two
Three
Four

**Nation**: 
Various 

**Job(level)/Sub Job(level)**: 
PLD99/NIN (and others)

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
After killing Belphoebe (Crimson Stratum III, San d'Oria leg, chapter 1), expected all characters to upgrade to Crimson Stratum IV.

Tbone and Pockethealer (who've previously completed chapter 1) upgraded.

Girlieman, One, Two, Three, Four all lost their Crimson and Indigo Stratum Abyssite.  This prevents me from even trying from tier 1 again.

Likely multibox related, but I've never seen this issue before so I can not say for certain.

**Comment by TeoTwawki** [comment]
hm. any other VWNMs around that time? I can see this happening to their crimson by way of multibox shenanigans, but the indigo wouldn't have been touched by that NM.

**Comment by tb1** [comment]
I hadn't touched the bastok (indigo) lag on them at all, so they should have had tier 1 still.

They all had (and still have) Jade stratum III (was stuck on soloing lord asag due to charm).

Nobody else was in zone at the time.

I figured maybe it just fucked up on upgrade and I'd have to do the sandy lag again (which although annoying, wasn't a big deal), so I came back to do Sarimanok (east ronfaure) and I can't pop it on my mains (Tbone & Pockethealer) since they are all statum 4, and I can't pop them on the mules since they don't even have the abbysite anymore.

**Comment by tb1** [comment]
If you are checking logs, I don't have the exact time, I'd estimate maybe an hour before I opened the ticket (figured I just had to redo Tier 1,2,3 so I didn't open it immediately.)

**Comment by TeoTwawki** [comment]
k, will see if I can discover why your indogo's got eaten

**Comment by tb1** [comment]
Tonite I am going to talk to the VW officers again and see if they'll give me the KIs again and go from there, maybe it was some one-off multibox issue.  I'll let you know and close ticket if I clear cities

**Comment by tb1** [comment]
Haven't had any issues when doing it again, so closing ticket.
