### ISSUE TITLE
Inanna/Entropy/souleater

### ISSUE THREAD

**Issue by nidhogg1** [LegionDark/Issues#15]
**Date & Time**: 05/27/15, 1AM
**Frequency**: high
**FFXi Client Version**: 20110829_E
**Character Name**: Coso
**Race**: Hume
**Main Job**: DRK99
**Sub Job**: SAM49
**Area & Coordinates (Type @where to get this info.)**: gustav tunnel x:48 y:0 z:181 (199
**Party or Solo**: Both
**NPC Name**:
**Monster Name**: Boulder Eaters & Pygmytoises
**Steps To Reproduce The Issue**: 
i have been testing drk alot for the pass few days and with the same gear as war and better weapon seen to be weaker by a lot but Inanna occ double dmg and white dmg is working as intended the issue could be souleater and entropy
1. stacked 3000TP entropy with better weapon as war with the same gear as war, berely 8k (war would do 12k+) 
2. stacked 3000TP souleater entropy with better weapon as war with the same gear as war, still berely 8k
3. stacked 3000TP entropy no gear, berely 7k
4. thanks! :dancers:

**Comment by Loki79** [comment]
i have actually boosted Entropy's WS script so i know it, and souleater work correctly.  What you seeing is more than likely WAR's native dbl atk proc'ing.

**Comment by nidhogg1** [comment]
just did 1 entropy with /war last resort, souleater and berserk + gear to boost  double attack to total of 22% and entropy got up to 10k i still think is way under warrior, but good call about the double attack

**Comment by Loki79** [comment]
more than likely was is proc'ing dbl atk on multiple swings.  As someone who plays DRK a good bit i can confirm its working correctly.  Closing this issue.
