### ISSUE TITLE
no ki from boss in dynamis bastok

### ISSUE THREAD

**Issue by puffer1221** [LegionDark/Issues#150]
**Date & Time**: 08/07/2015, 22:53 pm Gmt
**Frequency**: constant
**FFXI Client Version**: 30150619_2
**Character Name**: Anofreixx
**Race**: Hume
**Main Job**: Sch
**Sub Job**: Rdm
**Area & Coordinates**: Dynamis bastok, X: -13, Y: -1, Z: -130 (65)
**Party or Solo**: Party
**NPC Name**: Not applicable 
**Monster Name**: Ghu'Dha Effigy
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: Squaller and i spawned the zone boss for bastok, we killed him but no ki drop as shown in screen shot below, we both died once if that effects it dropping at all but the boss never went unclaimed.

[img]http://i.imgur.com/q14QzuR.png[/img]

**Comment by TeoTwawki** [comment]
This was already fixed today

**Comment by TeoTwawki** [comment]
(was a typo in script, yes, a simple typo, for those wondering)
