### ISSUE TITLE
Ashen Stratum Abyssite III upgrading error

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1501]
**Date & Time**: 
6/1/17

**FFXI Client Version (use `/ver`)**: 
30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30170304_1

**Character Name**: 
Raelious

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99PLD/49WAR

**NPC or Monster or item Name**: 
Aello, Qilin, Uptala

**Zone name**: 
Ru'Aun Gardens, The Shrine of Ru'Avita, or Ve'Lugganon Palace

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
First go around no, second go around yes.

**Steps To Reproduce / any other info**: 
I have killed all of the Ashen Abyssite NMs over twice now from T1-2, and upon getting to the T3s it automatically resets back to T1 abyssite after killing ANY of the t3s not after you kill all 3. So its impossible to keep a t3 ashen at the moment. Ran through these twice now and first time I killed Aello first and it reset, ran through a second time and killed Uptala first and it reset. Not really urgent I suppose just reporting so its known.

**Comment by TeoTwawki** [comment]
Have I mentioned lately how much I detest voidwatch? this is going to be the I don't know how many times fixing the exact same retarded error that will somehow have been undone

**Comment by Raelious** [comment]
Was just told to have it reported here. I personally dont care for this issue to be fixed for myself.

**Comment by TeoTwawki** [comment]
and? I don't why you are telling me that. I am just disgusted with the entire quest line because its been buggy from day one

**Comment by Raelious** [comment]
I know you are in the process of redoing vw with how it upgrades you, so no need to do extra work right now that isnt really required atm.

**Comment by TeoTwawki** [comment]
like a running gag: teo fixes voidwatch, declares hatred, voidwatch rebreaks

**Comment by TeoTwawki** [comment]
did any of the NMs involved fail to hand out its exp bonus on death?

**Comment by Raelious** [comment]
Nope they give the normal 9750 per kill, along with the drops.

**Comment by gori123** [comment]
try passhow crystal then run between jeuno door and guards

**Comment by arkooqymoya** [comment]
theirs a way to deal with this problem, my KI was disupdated sevele days ago also, but my friend find this way and its working , you just pop it and quit the team, and your ki saved .

**Comment by Raelious** [comment]
Yes that works normally, but... this is my third runthrough on Ashen tier, and both times prior ot reset back to t1 after killing any of the 3 tier3 nms. Where its only suppsed to revert back to t1 after you kill all nms in the tier. Same thing just recently happened with my T6 Jeuno abyssite.
Only logical reasoning I can come up with is my vw vars show them all as cleared/killed so killing any of them in a specific tier would cause it to revert back to the starting tier.

**Comment by TeoTwawki** [comment]
I basically need a GM with you to check the variable for it every step through, or to find time to do this myself

**Comment by TeoTwawki** [comment]
hotfixed

**Comment by Raelious** [comment]
Was White Stratum VI hotfixed too? ...and if so could I get that returned (figured id try asking since jueno is a pita!)

**Comment by TeoTwawki** [comment]
@Raelious does that line do the same behavior?

**Comment by Raelious** [comment]
Yes. Just went through Jeuno last weekend. Killed the Mantis for T6 then automatically lost my T6 abyssite on Raelious and Melious. It was Gathins first time through and he maintained it after killing the Mantis.

**Comment by TeoTwawki** [comment]
@LegionDark/gm if one of you has time, pls hand out the relevant stratum key items to effected players. the bug is already fixed server side.

**Comment by Jessland86** [comment]
Added KI's in game to Rae, and Mel.
