### ISSUE TITLE
Murgleis trial 95 does not count

### ISSUE THREAD

**Issue by gori123** [LegionDark/Issues#1502]
**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 30170329_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: no

**Character Name**:  Tonton

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 99rdm/49blm

**NPC or Monster or item Name**:  	Murgleis

**Zone name**: any

**Coordinates (use `$where`)**: multiple

**ffxiah.com link (for items issues only)**: http://ffxiclopedia.wikia.com/wiki/Murgleis_(95)

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: killing any of the necessary mobs (cerberus etc) with Murgleis_(95) does not count as trial, it is always 0/9 (i only cast healing/ enfeebling spells, i dont engage)

**Comment by R3P0FFXI** [comment]
@gori123 did you have the weapon equipped it works for everyone ele

**Comment by gori123** [comment]
if you say it is working i will cancel and retry the buff of the magian moogle. Also if i get the chance i will not multibox.

**Comment by gori123** [comment]
works after reset
