### ISSUE TITLE
San d'Oria Mission 6-1 Leaute's Last Wishes

### ISSUE THREAD

**Issue by xrocksterx** [LegionDark/Issues#1503]
**Date & Time**: June 2, 2017 3am pst

**FFXI Client Version (use `/ver`)**: 30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Rock and Fenom

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: Rock pld99/rdm49 -- Fenom whm99/rdm49

**NPC or Monster or item Name**: Halver

**Zone name**: Chateau d'Oraguille

**Coordinates (use `$where`)**: X:1 Y:0 Z:0 (233)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: Started quest at gate guard as usual. Zoned into Chateau d'Oraguille and talked to Halver for mission. Below are the series of events in order.

1. For Rock he immediately skipped both the log dialog and CS sequence about the Dreamrose. Halver went right to his dialog telling me to speak with Chalvatot to turn the Dreamrose in, I never got to the point of killing the nm nor obtaining the Dreamrose.
2. For Fenom Halver was totally unresponsive.
3. My 3rd toon Sylvie had gotten all the correct dialog and cs's.

We went to kill the mission nm, Sylvie got her KI, the Dreamrose. Rock and Fenom were not able to obtain.

Tried logging out all toons to log in one at a time. Still nothing happening with Halver.

**Comment by R3P0FFXI** [comment]
@xrocksterx 

Multi-boxing? (multiple clients on same connection): yes

YOu need to log off every character shut ffxi down completely and ONLY login 1. Multiboxing with missions is a known issue. You will probably also need to start from the beginning of the mission for each character individually to see where its screwed up.

**Comment by R3P0FFXI** [comment]
@LegionDark/gm can you please run a /Checkvar on the player as well see what you can see

**Comment by Heepster03** [comment]
![halkuras_2017 06 03_213824](https://cloud.githubusercontent.com/assets/8421725/26758505/769d8c74-48a5-11e7-9315-60462456a446.png)

**Comment by Heepster03** [comment]
`elseif (currentMission == LEAUTE_S_LAST_WISHES and MissionStatus == 0) then
player:startEvent(25);`
I already changed their MissionStatus to 0 and asked them to speak to Halver, this should allow them to start the quest as it wasn't letting them do beforehand.

**Comment by TeoTwawki** [comment]
Chalvatot is the only NPC that looks for status of 4 on that mission, and he expects the KI to be present. So seems one character advanced and its variable update was sent to the other 2 characters via the multibox bug in DSP.

**Comment by Heepster03** [comment]
Issue resolved. :)
