### ISSUE TITLE
BRD unlock quest

### ISSUE THREAD

**Issue by Valknut4** [LegionDark/Issues#1504]
**Date & Time**: 7:15pm PST 6/2/17

**FFXI Client Version (use `/ver`)**: 30170427_7

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Giers

**Nation**: Bastock

**Job(level)/Sub Job(level)**: 99sam/49war

**NPC or Monster or item Name**:  Song Stone

**Zone name**: buburimu peninsula 

**Coordinates (use `$where`)**: X-245 Y 16 z -279 (143)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/917/parchment?stack=1

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Not 100% sure, but I warped away from the stone after the CS played with  Lewenhart. Used a Black drop to warp. Then went and talked with the quest NPC's and was very confused. Went back traded item, and got nothing

**Comment by Valknut4** [comment]
Fixed by changing jobs main and sub, talking to both npc's in jeuno again. Reactivated the CS at song stone and let me trade parchment to song stone.

**Comment by TeoTwawki** [comment]
> Multi-boxing? (multiple clients on same connection): Yes

.

> Reactivated the CS at song stone and let me trade parchment to song stone.

sounds like it just didn't set the var the 1st time
