### ISSUE TITLE
Multiple NM's in Aby. Mis. are not spawning correctly.

### ISSUE THREAD

**Issue by Jessland86** [LegionDark/Issues#1505]
**Date & Time**: 
0121 06/04/2017

**FFXI Client Version (use `/ver`)**: 
30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
n/a

**Job(level)/Sub Job(level)**: 
n/a

**NPC or Monster or item Name**: 
http://legiondark.com/db/monsters/17662467/Manohra
http://legiondark.com/db/monsters/17662471/Avalerion
http://legiondark.com/db/monsters/17662485/Ironclad_Pulverizer
http://legiondark.com/db/monsters/17662484/Ironclad_Pulverizer
http://legiondark.com/db/monsters/17662489/Ironclad_Pulverizer
http://legiondark.com/db/monsters/17662490/Ironclad_Pulverizer
http://legiondark.com/db/monsters/17662472/Karkatakam
http://legiondark.com/db/monsters/17662464/Minax_Bugard
http://legiondark.com/db/monsters/17662473/Nonno
http://legiondark.com/db/monsters/17662469/Ironclad_Observer

**Zone name**: 
Aby-Mis

**Coordinates (use `$where`)**: 
Varies

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
Many mobs in this zone are on a super short 1 minute repop and have extremely low HP.
They *can* be still force popped, but it is still a watered down version of what it should be,
The 4 Ironcads are all also just up at the same time when there should only be one that is force popped.

**Comment by R3P0FFXI** [comment]
@Jessland86 the mob groups in custom for this zone are really just broken. Many have duplicate entries for god knows why and this is just broken as all hell from what im seeing. Can you get me the actual true repop times of the NMs that should be repopping automatically. I will fix this in the ReOrg branch not going to worry to  much about these NM now as they are just card NM.

**Comment by Jessland86** [comment]
Those should all be force pop nms. They currently are all poppable, but there is no reason to as they are just up.

**Comment by TeoTwawki** [comment]
> the mob groups in custom for this zone are really just broken. When originally concived Abyssea was to be 60 second repops. Many have duplicate entries for god knows why and this is just broken as all hell from what im seeing. Can you get me the actual true repop times of the NMs that should be repopping automatically. I will fix this in the ReOrg branch not going to worry to much about these NM now as they are just card NM and mobs.

you need to stop posting things like this before we've looked. Tag it with the right label move on instead of putting confusion out

**Comment by R3P0FFXI** [comment]
@Jessland86, @TeoTwawki In Current SQL

At work need to verify Nonno, anything with 128 bolded is currently set to force pop, anything with 60 bolded is 60 second repop

`REPLACE INTO `mob_groups` VALUES (10285,2553,216,0,**128**,9237,70000,10000,118,120,0); -- Manohra`

`REPLACE INTO `mob_groups` VALUES (10249,293,216,0,**128**,9229,60000,20999,118,120,0); -- Avalerion`

`REPLACE INTO `mob_groups` VALUES (10279,2094,216,0,**128**,2498,90000,200000,118,120,0); -- Ironclad Pulverizor`

`REPLACE INTO `mob_groups` VALUES (10282,2195,216,0,128,9236,70000,20999,118,120,0); -- Karkatakam`

`REPLACE INTO `mob_groups` VALUES (10287,2666,216,0,128,9238,70000,20999,118,120,0); -- Minax Bugard`

`REPLACE INTO `mob_groups` VALUES (10291,2905,216,**60**,0,2484,**10000,10000**,114,117,0); -- Nonno`

`REPLACE INTO `mob_groups` VALUES (10278,2093,216,0,**128**,9232,70000,10000,118,120,0); -- Ironclad Observer`

PS Fuck this file

P. PS. No Really fuck this fucking fucked up file

**Comment by TeoTwawki** [comment]
This fixed now?

**Comment by Raelious** [comment]
Yes they are all fixed, just ran through the zone none of them are forced up. Didnt check them with the appropriate pop items/key items.

**Comment by TeoTwawki** [comment]
dammit github! F you and your laggy label system too!
