### ISSUE TITLE
Cannot use Maat's Cap

### ISSUE THREAD

**Issue by Jessland86** [LegionDark/Issues#1507]
**Date & Time**: 
6/5/2017 0551

**FFXI Client Version (use `/ver`)**: 
30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99pld/rdm

**NPC or Monster or item Name**: 
Maat's Cap

**Zone name**: 
n/a

**Coordinates (use `$where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/15194/maats-cap

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Maat's cap ticks down in time to 0 when equipped, but will not let you use it when the timer reaches 0.

**Comment by TeoTwawki** [comment]
wierd, works on dsp and nothing custom happened to it. wonder if item packet is wrong in dsp again--Sent from Yandex.Mail and for mobile05.06.2017, 05:53, "Jessland86" <notifications@github.com>:
Date & Time:
6/5/2017 0551
FFXI Client Version (use /ver):
30170427_0
Server's Expected Client Version matches, yes/no? (use $ecv):
yes
Character Name:
Immortality
Nation:
Sandy
Job(level)/Sub Job(level):
99pld/rdm
NPC or Monster or item Name:
Maat's Cap
Zone name:
n/a
Coordinates (use $where):
n/a
ffxiah.com link (for items issues only):
http://www.ffxiah.com/item/15194/maats-cap
Multi-boxing? (multiple clients on same connection):
yes
Steps To Reproduce / any other info:
Maat's cap ticks down in time to 0 when equipped, but will not let you use it when the timer reaches 0.

**Comment by Heepster03** [comment]
It was missing something important to make it work, but it's been taken care of. Should be in the next update.

**Comment by TeoTwawki** [comment]
Additionally hotfixed live
