### ISSUE TITLE
Iriz Ima went unclaimable

### ISSUE THREAD

**Issue by Kearick** [LegionDark/Issues#1508]
So, Nonny here and went off to go help some other players with Iriz Ima.  We got him to about 20%, set up a skillchain bringing him to 3%, but just as my Atonement went off, Iriz Ima charmed me, which then caused the entire party to lose claim to the NM, that we thought, maybe we can just try killing it with spikes or something to get loot.  Which didn't work, which we aren't bummed about or anything, Iriz Ima is just annoying.  But, we thought it would be best to bring to the attention that it still happened.

**Comment by Jessland86** [comment]
What caused it to charm? I'm not seeing any move this is *supposed* to do that has charm.

**Comment by TeoTwawki** [comment]
@Jessland86 that same bug existed in the past when its skill list got mangled and mixed with another mob's

..A lot of past mob pool and mob group related bugs have resurfaced lately, could be one of them.

**Comment by Raelious** [comment]
A few mobs are doing moves that they never have before, I witnessed it on the Crab NPC in Bibiki Bay yesterday doing Petro Eyes which it never has before ever. As well as a couple Aptant mobs doing ws's not typically used in their family class, I don't remember the names, but I will go fight them again and report names.

**Comment by R3P0FFXI** [comment]
@Kearick DSP has Frog Chorus listed for this mob by mistake, we have corrected this on our end and next maint this will resolve the issue

**Comment by TeoTwawki** [comment]
@Kearick the actual claim issue with charm, that will have to be done by DSP. But this mob won't charm anymore.

**Comment by Heepster03** [comment]
@Kearick , next time use the proper format please, and thanks.

**Comment by TeoTwawki** [comment]
@R3P0FFXI this can be closed whenever the charm screwing up the ability to claim after charm has worn off is in a DSP issue.

**Comment by TeoTwawki** [comment]
Yet again nobody effin forwards the claim/charm issue to DSP. Doing it my damn self so I can close this.

> @R3P0FFXI this can be closed whenever the charm screwing up the ability to claim after charm has worn off is in a DSP issue.
