### ISSUE TITLE
Fenrir Blood Pact: Rage/Ward not working

### ISSUE THREAD

**Issue by Booey99** [LegionDark/Issues#1509]
**Date & Time**: 
6/06/2017 - 9:00am est

**FFXI Client Version (use `/ver`)**: 
30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Booey

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
72SMN/36SCH

**NPC or Monster or item Name**: 
Avatar- Fenrir

**Zone name**: 
N/a

**Coordinates (use `$where`)**: 
N/a

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
After the most recent client update, the previously working abilities of Fenrir do not appear to activate or function anymore. Prior to the update, all Fenrir abilities (that I had access to) were working. 
Currently, Only Eclipse Bite (Rage) and Lunar Cry (Ward) activate as usual. Moonlit Charge (Rage) and Crescent Fang (Rage) as well as Lunar Roar (Ward), Ecliptic Howl (Ward) and Ecliptic Growl (Ward) do not activate.

**Comment by TeoTwawki** [comment]
prolly my fault..will look when I can

**Comment by TeoTwawki** [comment]
I think I fixed it but we won't know till maint.

**Comment by R3P0FFXI** [comment]
@Booey99 please retest and check for us that this is now working

**Comment by Raelious** [comment]
@TeoTwawki @R3P0FFXI Just tested this on Meo's character and all of these bloodpact rages/wards are working correctly now. Ticket can be closed.
