### ISSUE TITLE
Dynamis Bastok - no Key item drop

### ISSUE THREAD

**Issue by SquallerSnake** [LegionDark/Issues#151]
Date & Time: 2015 July 9th , 00:30 am Rome, Europa timezone
Frequency: First time
FFXI Client Version: 30150619_2
Character Name: Squaller
Race: Hume
Main Job: Paladin
Sub Job: Warrior
Area & Coordinates: Dynamis Bastok
Party or Solo: Party
NPC Name: 
Monster Name: Arch Gu'Dha Effigy
Multi-boxing? (multiple clients on same connection): No
Steps To Reproduce The Issue: I have defeat the megaboss Arch Gu'Dha Effigy but when it died, there was no the ??? where it died. I also tried to check every ??? of Dynamis but without success.

**Comment by TeoTwawki** [comment]
The NPC spawn without issue I have checked this myself in game, however do to being frustrated with people not understanding that the NCP spawns EXACTLY where the NPC dies, I have made all city dyna NMs simply hand out KI on death. Go kill it it again, and you will get your clear.

**Comment by TeoTwawki** [comment]
PS: there is no "arch" version currently.

**Comment by SquallerSnake** [comment]
Thks for the response i will kill it again, i know that the NCP spawns
EXACTLY where the NPC dies but where it died there was no the KI....

2015-07-09 19:07 GMT+02:00 TeoTwawki <notifications@github.com>:

> The NPC spawn without issue I have checked this myself in game, however do
> to being frustrated with people not understanding that the NCP spawns
> EXACTLY where the NPC dies, I have made all city dyna NMs simply hand out
> KI on death. Go kill it it again, and you will get your clear.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LegionDark/Issues/issues/151#issuecomment-120072984>.
>



-- 
Daniele Roggeri

**Comment by TeoTwawki** [comment]
I had like 8 ppl tell me that about dyna jeuno, and another dozen+ say it about dyna sandy, I zone in killed both boss if there was the ??? exactly as expected ¯\_o.O_/¯ I check ID for all (inc bastok) and they all correct. I zone to dyna bastok  wallop boss and ?? spawn for me  ¯\_o.O_/¯  anyway, they all give on death now even if for some reason the ??? can't be found.

Dyn sandy's case was sort of understandable..it landed right on top other target, so nobody could select unless I moved it with GM command (pulling boss a little bit away from spawn site will prevent that).
