### ISSUE TITLE
Forgot my Alt password

### ISSUE THREAD

**Issue by climswar** [LegionDark/Issues#1511]
**Date & Time**: 

6/7/2017 2:24a.m
**FFXI Client Version (use `/ver`)**: 
Current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: 
Borracho

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
WAR99/DNC49

**NPC or Monster or item Name**: 
N/A

**Zone name**: 
i dont remember sorry

**Coordinates (use `$where`)**: 
i'm not sure ...again sorry 

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: 
trying to log into my Alt Borracho the email linked to him is just so you know i have another character under same email i think.

**Comment by TeoTwawki** [comment]
If you have the email linked you should be able to reset it via the website already. 

Also just to let you know by openly posting your email you are enabling uncountable numbers of spambots to harvest it.

**Comment by climswar** [comment]
via website? to log into the actual game?

**Comment by climswar** [comment]
awesome i see it now thank you

**Comment by climswar** [comment]
oh wait... thats just your reply to this post ;(

**Comment by TeoTwawki** [comment]
I thought we had a self serve reset feature but I can't find it so I guess not. If I can't find it I can't expect you too... Catch either me or @R3P0FFXI on discord, and we'll set a new one and private message it to you.

**Comment by atom0s** [comment]
No self-serve reset button since Loki/R3P0 never setup the email server that it would require.

**Comment by R3P0FFXI** [comment]
@climswar is this still and issue please respond and send me a message on forums

**Comment by climswar** [comment]
I just gave up on it... currently at work so any replies might be after I get out @6pm central

**Comment by Jessland86** [comment]
If this is still an issue please reopen and @ R3
