### ISSUE TITLE
Atrophy-boots + Lethargy Armor Set (Rdm Empy) is not obtainable

### ISSUE THREAD

**Issue by gori123** [LegionDark/Issues#1512]
**Date & Time**:  --

**FFXI Client Version (use `/ver`)**: 30170427_0 (it happened in an erlier version)

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: --

**Character Name**: Tonton

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 99rdm/49blm

**NPC or Monster or item Name**: Artifact Moogle in Tavnazia

**Zone name**:  Tavnazia

**Coordinates (use `$where`)**:  7 -9 -6

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/28227/atrophy-boots

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**:
-- Warlock's Boots +1 	Aptant: Ishis x20  gives  Vitivation boots

-- it should give Atrophy Boots

-- Whole RDM empy trade by Prishe seems to be also broken

**Comment by R3P0FFXI** [comment]
@LegionDark/gm Please give player correct item once confirmed that Vivitation boots have been dropped.

@gori123 This issue is resolved in our next update.

**Comment by gori123** [comment]
i dropped vivitation boots, prishe still did not talk to me. 
is it possible the complete Lethargy Armor Set trade by prishe is broken after update ?

**Comment by R3P0FFXI** [comment]
... reread my comments please

**Comment by gori123** [comment]
thank you i was making sure to notify 
artifact trade boots + all empy trade are broken in the same ticket.

**Comment by gori123** [comment]
i accept it was my fault Lethargy Armor Set  trade is indeed working 
but is athrophy boots problem solved
