### ISSUE TITLE
Missing TP Moves?

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1513]
**Date & Time**: 
June 7, 2015, 3:53 AM MST

**FFXI Client Version (use `/ver`)**: 
30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Tbone

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
PLD99/WAR49

**NPC or Monster or item Name**: 
Hahava
Celaeno
Melancholic Moira
... maybe others

**Zone name**: 
Various

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
- Hahava used no TP moves
- Celaeno used no TP moves, and I don't even recall her auto-attacking (just some light nuking)
- Melancholic Moira only used bad breath (and not the charm breath).
- Kholomodumo seems to be missing TP moves, but I can't recall which ones. (he was easier than he was previously)

Unsure if this is part of the upcoming rebalance/reorg, or a an actual bug.

On a side note:
- Lord Asag does charm and nuke really hard (and is still a bitch to kill because of it).

So either Hahava, Calaeno, and others are missing TP moves, or Lord Asag wasn't rebalanced with the rest.

**Comment by R3P0FFXI** [comment]
@tb1 There was no re-balancing done we just turned NM moves on that were incorrectly listed in our SQL

@LegionDark/gm can you please verify these skills are being used

The following NM below appear to be fine according to our files and what was done previously.

`INSERT INTO `mob_skill_lists` VALUES ('Lord_Asag',5047,2106); -- Bloodrake
INSERT INTO `mob_skill_lists` VALUES ('Lord_Asag',5047,2108); -- Nosferatus_kiss
INSERT INTO `mob_skill_lists` VALUES ('Lord_Asag',5047,2110); -- Wings_of_Gehenna
INSERT INTO `mob_skill_lists` VALUES ('Lord_Asag',5047,2112); -- Nocturnal_Servitude`

`INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2714); -- Yaksha_stance
INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2715); -- Yaksha_damnation
INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2716); -- Yaksha_oblivion
INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2717); -- Yaksha_bliss
INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2718); -- Raksha_stance
INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2719); -- Raksha_Judgment
INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2720); -- Raksha_illusion
INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2721); -- `Raksha_vengeance`

`INSERT INTO `mob_skill_lists` VALUES ('Kholomodumo',5046,628); -- Wild_Horn
INSERT INTO `mob_skill_lists` VALUES ('Kholomodumo',5046,629); -- Thunderbolt
INSERT INTO `mob_skill_lists` VALUES ('Kholomodumo',5046,633); -- Howlacc
INSERT INTO `mob_skill_lists` VALUES ('Kholomodumo',5046,2390); -- Accursed_Armor
INSERT INTO `mob_skill_lists` VALUES ('Kholomodumo',5046,2391); -- Amnesic_Blast
INSERT INTO `mob_skill_lists` VALUES ('Kholomodumo',5046,2586); -- Ecliptic_Meteor`

`INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2714); -- Yaksha_stance
INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2715); -- Yaksha_damnation
INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2716); -- Yaksha_oblivion
INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2717); -- Yaksha_bliss
INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2718); -- Raksha_stance
INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2719); -- Raksha_Judgment
INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2720); -- Raksha_illusion
INSERT INTO `mob_skill_lists` VALUES ('Hahava',5050,2721); -- Raksha_vengeance`

Celano seems to have no TP moves in the system so I will work on that.

**Comment by tb1** [comment]
Add Cherufe to the list
- No TP moves used
- Seems to have a endispel additional effect which works.

I'll keep adding VWNMs that seem to be missing TP moves as I go through jeuno T1/T2.

**Comment by tb1** [comment]
Add Agathos to the list
- No TP moves used
- Does nuke

He normally uses a knock back move and a TP reset move if I recall correctly.

**Comment by R3P0FFXI** [comment]
@tb1 

Both are correct in the SQL

INSERT INTO `mob_skill_lists` VALUES ('Agathos',5055,2430); -- Warped_Wail
INSERT INTO `mob_skill_lists` VALUES ('Agathos',5055,2431); -- Reaving_Wind
INSERT INTO `mob_skill_lists` VALUES ('Agathos',5055,2433); -- Calamitous_Wind
INSERT INTO `mob_skill_lists` VALUES ('Agathos',5055,2642); -- Custom_Vermilion_Wind

INSERT INTO `mob_skill_lists` VALUES ('Cherufe',5056,2099); -- Batterhorn
INSERT INTO `mob_skill_lists` VALUES ('Cherufe',5056,2100); -- Clobber
INSERT INTO `mob_skill_lists` VALUES ('Cherufe',5056,2101); -- Demoralizing_Roar
INSERT INTO `mob_skill_lists` VALUES ('Cherufe',5056,2103); -- Granite_Skin
INSERT INTO `mob_skill_lists` VALUES ('Cherufe',5056,2104); -- Crippling_Slam

**Comment by tb1** [comment]
Then I must be on the luckiest run I have ever been on, Gugalanna is only using Mow, and not his 1-shot Max HP Down move that he always use to use.

**Comment by R3P0FFXI** [comment]
INSERT INTO `mob_skill_lists` VALUES ('Gugalanna',5053,500); -- Mow
INSERT INTO `mob_skill_lists` VALUES ('Gugalanna',5053,1360); -- Apocalyptic_Ray
INSERT INTO `mob_skill_lists` VALUES ('Gugalanna',5053,2389); -- Lethal_Triclip
INSERT INTO `mob_skill_lists` VALUES ('Gugalanna',5053,2533); -- Lithic_Ray
INSERT INTO `mob_skill_lists` VALUES ('Gugalanna',5053,2640); -- Ruinous_Scythe

**Comment by TeoTwawki** [comment]
You know call me crazy but I don't think any reasonable player cares that the code looks right, or needs to see all of it. Some of our less reasonable people are likely to take it as telling them its their imagination and why report things then? It doesn't solve anything. And if a doubt did exist we'd just have a GM check the mob in game to verify. If we dunno why its broke we dunno, that's life. We've been doing a lot of things that look bad, and yes I am aware of the irony of posting this at you on github. Lord knows I have TRIED to have this conversation with you in private often enough ya thick headed *git*.

**Comment by atom0s** [comment]
Rather than just pasting sql inserts to someone and telling them 'nope' why not go in-game and actually test for yourself? Just because you have sql inserts for something does not mean another part of the SQL/Scripts/etc. are not broken or incorrect causing the mob to not work properly.

**Comment by atom0s** [comment]
**Havana**
 - Confirmed only casts, no TP moves. (This mob was working fine recently.)
 - Force giving it 3000 TP does nothing. Still only casts.
 - 1 of its spawn points are wrong and do not work. (It's off the map..)

_Like the rest of the Voidwatch still, only one spawn location works, the rest spawn the mob at the one specific location. Meaning you can use the "wrong" rift and cause the target to spawn across the map instead. Players at this point have to learn what rift is the "correct" one and avoid losing their keyitems/stones by using the wrong one._

**Comment by TeoTwawki** [comment]
> Meaning you can use the "wrong" rift and cause the target to spawn across the map instead

there actually was code checking their position to determine the "correct" rift but that appears to have broken/been mangled somewhere along the way, and i think the best solution is to *just make all the alternate rifts functional with the alternate copies of the mob*. It'll be awhile though, higher priority is getting rid of the key item cycling and then fixing everyones busted KI lists.

**Comment by Jessland86** [comment]
Add Kaggen to the list. Just tested and confirmed that it does no TP moves at all.

**Comment by Acedffxi** [comment]
Add Pil to the list. Only casted spells.

**Comment by Acedffxi** [comment]
Add Ig-Alima same thing.

**Comment by Acedffxi** [comment]
Tsui-Goab~

**Comment by Acedffxi** [comment]
Voidwrought

**Comment by TeoTwawki** [comment]
We will be performing emergency maintenance shortly, these will need rechecking after (I have them working on my local copy of the server right now).

**Comment by TeoTwawki** [comment]
emergency maint finished.

**Comment by atom0s** [comment]
Hahava is using TP moves again.

**Comment by TeoTwawki** [comment]
Thanks atom0s

**Comment by R3P0FFXI** [comment]
Also note Celeano was fixed with this fix
