### ISSUE TITLE
AH tax has no cap

### ISSUE THREAD

**Issue by Jessland86** [LegionDark/Issues#1515]
**Date & Time**: 
6/7/2017

**FFXI Client Version (use `/ver`)**: 
30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99THF/DNC

**NPC or Monster or item Name**: 
n/a

**Zone name**: 
n/a

**Coordinates (use `$where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Placed item on AH for 750m AH fee was supposed to be capped at 25k went to buy it back and I had lost approx 15m in AH fees.

**Comment by atom0s** [comment]
Tested and confirmed. 750mil item takes 15,000,050 gil to post on the AH even though it states the cap is 25k.

**Comment by TeoTwawki** [comment]
missing line of code in dsp's packet system. Fix'd! will take effect next maint.

**Comment by TeoTwawki** [comment]
scratch that, ima hotfix the search server - nobpdy will notice a 5 second interruption

**Comment by TeoTwawki** [comment]
nvm me I can't think straight..prob is in map server
