### ISSUE TITLE
Entozoon  in  Abyssea - Attohwa is missing .

### ISSUE THREAD

**Issue by arkooqymoya** [LegionDark/Issues#1517]
**Date & Time**: 2017/6/8

**FFXI Client Version (use `/ver`)**: 30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**:arkoo 

**Nation**: bastok

**Job(level)/Sub Job(level)**: 99thf/49dnc

**NPC or Monster or item Name**: Entozoon  

**Zone name**: Abyssea - Attohwa

**Coordinates (use `$where`)**: X:288 Y:20 Z:215(1)

**ffxiah.com link (for items issues only)**: http://ffxiclopedia.wikia.com/wiki/Entozoon

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**:  i saw somone already reported it 21days ago and that was a reported issue also, but last dsp update didnt fix this worm, i guess i have to report this again? "The entozoon starts casting ...."
"The entozoon's casting is interrupted"
i only do this because i need the "the belanced silver " to pop Ulhuadish for my war's and my whm's empy head.

**Comment by R3P0FFXI** [comment]
https://github.com/LegionDark/Issues/issues/1484
