### ISSUE TITLE
Fantod unlearnable (Hippogryph mobs won't use it)

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1518]
**Date & Time**: 
Jun 8, 2017

**FFXI Client Version (use `/ver`)**: 
30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30170427_0 yes

**Character Name**: 
Tbone
One, Two, Three, Four, Pockethealer, Girlieman

**Nation**: 
Windy (and others)

**Job(level)/Sub Job(level)**: 
PLD99/RDM
BLU99/RDM

**NPC or Monster or item Name**: 
Hippogryph
Cloud Hippogryph
Nimbus Hippogryph
Strato Hippogryph

**Zone name**: 
Riverne - Site A01
Riverne - Site B01

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
- Cast dia over and over watching the hippogryphs use Jettatura, Nihility Song and Back Heel, but never Fantod.

Tested on ~15 mobs, a few from each of the ones listed about.  After 10+ moves each, never saw fantod.

**Comment by tb1** [comment]
Ohh, also worth noting that the blu spell tool doesn't show it:
http://legiondark.com/db/bluespells/674/fantod

**Comment by R3P0FFXI** [comment]
@LegionDark/gm please ensure mob uses this skill this is active on our server if skill is used but is unable to be learned this is a different issue.

**Comment by tb1** [comment]
I have the spell on T, and was trying to get it in One,Two,Three and Four.  So it normally is obtainable and usable (and is a very useful spell)

**Comment by TeoTwawki** [comment]
this needs rechecked after emergency maintenance finishes, I believe that #1513 also effected the hippogryphs

**Comment by TeoTwawki** [comment]
emergency maint finished.

**Comment by atom0s** [comment]
Fantod was always a rare move to be used from these. When I learned it on my alt BLU, it took a while to get them to finally use it.

Just tested again and they are definitely using it:
http://i.imgur.com/TX1erRc.png

**Comment by TeoTwawki** [comment]
sweet closing.
