### ISSUE TITLE
A party member using @return removes level sync.

### ISSUE THREAD

**Issue by Roamin** [LegionDark/Issues#152]
**Date & Time**: 2015 July 09th
**Frequency**: All the time
**FFXI Client Version**: 301506_19
**Character Name**: Roamin
**Race**: Tarutaru
**Main Job**: Warrior
**Sub Job**: Samurai
**Area & Coordinates**: Everywhere
**Party or Solo**: Party
**NPC Name**: Not applicable
**Monster Name**: Not applicable
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**: Not sure if this happens only while 2 boxing, but It takes a party of 3 people.  Leader , syncer , returner.  The leader syncs to a low level , and the third member , not the leader or the sync uses the server command @return will permanently remove the red dot for level sync and block level to the current synced level.

**Comment by TeoTwawki** [comment]
Did the recent updates fix this @Roamin ?
