### ISSUE TITLE
Mug recast time is incorrect.

### ISSUE THREAD

**Issue by Jessland86** [LegionDark/Issues#1520]
**Date & Time**: 
06/08/2017 2135 EDT

**FFXI Client Version (use `/ver`)**: 
30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99THF/DNC

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Use mug, it's recast is 15 minutes, it is supposed to be a 5 minute recast.
https://www.bg-wiki.com/bg/Mug
http://ffxiclopedia.wikia.com/wiki/Mug

**Comment by TeoTwawki** [comment]
Used to be 15 back when I played retail.
http://ffxiclopedia.wikia.com/index.php?title=Mug&action=historysubmit&diff=1495803&oldid=1123903
DSP didn't get the memo yet.
