### ISSUE TITLE
Certain stackable items aren't stacking

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1521]
**Date & Time**: 6/09/17

**FFXI Client Version (use `/ver`)**: 30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**: Melious

**Nation**: Bastok

**Job(level)/Sub Job(level)**:  99BLU/49RDM

**NPC or Monster or item Name**: Sif's Lock / Cehuetzi Claw

**Zone name**: Bastok Mines

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/8727/sifs-lock
http://www.ffxiah.com/item/8752/cehuetzi-claw

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: 
Those 2 items are supposed to stack but they are not stacking.

**Comment by Raelious** [comment]
@TeoTwawki Found the error, DSP has these 2 items along with a handful of others set to stack in 12s, but in the custom file where it is overwriting them to not stack.

**Comment by TeoTwawki** [comment]
Fixing in pup-test branch, since that should be when thats done should be when next maint hits

**Comment by TeoTwawki** [comment]
Forgot to push the fix..will be in next time we restart
