### ISSUE TITLE
palid percy untargetable/invisible

### ISSUE THREAD

**Issue by fgebony** [LegionDark/Issues#1524]
**Date & Time**: 6/10/17 11:55 PST

**FFXI Client Version (use `/ver`)**: 30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Ebony

**Nation**: Windurst

**Job(level)/Sub Job(level)**:99PLD/49WAR 

**NPC or Monster or item Name**:  Palid Percy

**Zone name**: abyssea-attowa

**Coordinates (use `$where`)**: (logged before i got it but his ??? spot

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: traded pop item multiple times, untargetable unless you /assist who gains aggro and go from there does not appear physically

**Comment by arkooqymoya** [comment]
entozoon showed up today,but the NM is not coming out by using the pop item

**Comment by TeoTwawki** [comment]
@arkooqymoya 
![1](https://user-images.githubusercontent.com/6871475/27055099-4ae307f6-4f91-11e7-8120-05ae0d497976.jpg)

Come on dude.
