### ISSUE TITLE
Mobs de-aggroing mid fight?

### ISSUE THREAD

**Issue by DanieC89** [LegionDark/Issues#1526]
**Date & Time**:  13/06/17 12:23pm

**FFXI Client Version (use `/ver`)**:  30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**: Danie

**Nation**: San d'Orian

**Job(level)/Sub Job(level)**:  99WHM/49SCH

**NPC or Monster or item Name**:  Slime Eater 

**Zone name**: Aydeewa Subterrane

**Coordinates (use `$where`)**:  

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:  While fighting slime eaters today they have been randomly de-aggroing mid fight while both party members were engaged. They would then instantly depop under the ground (they are worm mobs) and by the time they popped up again they would have regained a portion of their health. It also happened several times during the Dea NM fight the other day whereby the mob would randomly become unclaimed (despite all party members being engaged and fighting) and would start regening before we could claim again.

**Comment by TeoTwawki** [comment]
For future reference: Github sees the at sign `@` as a mention, so a user names 12 will get notifications for every post to this issue now.

**Comment by Raelious** [comment]
I have witnessed mobs randomly going unclaimed and regain ~10% hp, but that is because I occasionally use stuns. When I fight the mob(s) without using any form of stuns it does not occur. 

Also if you spam stun (any form of a stun) it has a chance to make the mob react weirdly and regain hp, though Teo can confirm. Just putting in my two cents.

**Comment by DanieC89** [comment]
I can understand the mob having issues with stun being used regularly, but we were fighting worms and neither of us were on jobs where we could use a stun move. Glad it's not just me though :)

**Comment by DanieC89** [comment]
Sorry about the at sign. I never realised till now what you meant, apologies!

**Comment by Heepster03** [comment]
I just deleted the sign, not sure if it matters.

**Comment by Valknut4** [comment]
I have had this happen while AoE'ing large packs of mobs in many zones. 

Example: If I pull a large pack of mobs with 300 TP banked, use Aeolian Edge, then panicked realising  I had pulled too much and started single target fighting. This will occur pretty often, especially if I have have pulled the pack of mobs a long distance from their native spawn/path.

**Comment by Jessland86** [comment]
Condensing this into https://github.com/LegionDark/Issues/issues/1208 Same thing seems to be causing it.
