### ISSUE TITLE
Windurst Quest "To Bee or Not To Bee"

### ISSUE THREAD

**Issue by starblazr** [LegionDark/Issues#1527]
Date & Time: 
6/13/17 11:03 CST

FFXI Client Version (use /ver):
30170601_0
Server's Expected Client Version matches, yes/no? (use $ecv):
No.  Server 30170427_0

Character Name:
Starblazer
Nation:
Windurst
Job(level)/Sub Job(level):
BLM57/WHM284
NPC or Monster or item Name:
Raamimi

Zone name:
Windurst Walls 

Coordinates (use $where):
x:-82 y:-9 z:106 (46)

ffxiah.com link (for items issues only):

Multi-boxing? (multiple clients on same connection):
No

Steps To Reproduce / any other info:
Doing the quest "To Bee or Not To Bee", when Raamimi gives you an item, it kicks back a weird message instead of the Item received.  First time you should receive honey, second time Mulsim.  You do get the item, it just doesn't appear correctly in the chat window.
![starblazer_2017 06 13_225438](https://user-images.githubusercontent.com/7802036/27114997-4ad33a54-508d-11e7-8d5a-7e3104b5e549.png)
![starblazer_2017 06 13_230137](https://user-images.githubusercontent.com/7802036/27115002-519f2fa0-508d-11e7-8ee5-c4ac067855bf.png)

**Comment by TeoTwawki** [comment]
Looks like bad textID

**Comment by TeoTwawki** [comment]
```
FFXI Client Version (use /ver):
30170601_0
Server's Expected Client Version matches, yes/no? (use $ecv):
No. Server 30170427_0
```
this will cause text IDs to not match like that, displaying the wrong string. common client error.

**Comment by TeoTwawki** [comment]
Closed as just a version mismatch: when darkstar gets updated to match teh client this is automatically fixed, 99% of the time
