### ISSUE TITLE
Mythic Trial Stuck

### ISSUE THREAD

**Issue by Devilotte** [LegionDark/Issues#1528]
**Date & Time**: 6/15/2017 6:53PM

**FFXI Client Version (use `/ver`)**: 30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Demresinaux

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**:BRD99/BLM49 

**NPC or Monster or item Name**: Carnwenhan

**Zone name**: Ru'Lude Gardens

**Coordinates (use `$where`)**: X:2 Y:3 Z:113 (3)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/19000/carnwenhan

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: I canceled my SCH Mythic with an imperial bronze piece, and then was unable to trade Carnwenhan BRD Mythic to NPC. Even if I try to restart my SCH Mythic, it won't start the trial as well. When I use $trial, it says there's no trials active

**Comment by Heepster03** [comment]
Issue has been resolved~
