### ISSUE TITLE
Ildebrann doesn't spawn helpers.

### ISSUE THREAD

**Issue by Jessland86** [LegionDark/Issues#1529]
**Date & Time**: 
06/10/2017 0838EDT

**FFXI Client Version (use `/ver`)**: 
30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99pld/rdm

**NPC or Monster or item Name**: 
http://legiondark.com/db/monsters/17617166/Ildebrann
http://legiondark.com/db/monsters/17617173/Hraun_Dragon
http://legiondark.com/db/monsters/17617174/Hraun_Dragon

**Zone name**: 
Ifrits cauldron

**Coordinates (use `$where`)**: 
-269 3.141 -169

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Ildebrann is supposed to spawn two helper mobs, Hraun Dragon, it does not.

**Comment by TeoTwawki** [comment]
@R3P0FFXI ya forgot they had custom mob spawn point entries when you moved them to DSP's group and pool ID stuffs

**Comment by Raelious** [comment]
You can add the following to this list as well: (Assuming you use the rifts listed on wiki)
Aello - they do spawn they just don;t spawn at the correct rift.
Modron - do not initially spawn, they have to run to you from another rift.
Neith - same as above.

**Comment by TeoTwawki** [comment]
@Raelious I'm going to be going through and making the alternate rifts and alternate copies of NMs work, and will end this insanity of "wrong rift".
