### ISSUE TITLE
San d'Oria - The Rescue Drill NPCS in La Theine not starting.

### ISSUE THREAD

**Issue by Lineaus** [LegionDark/Issues#153]
**Date & Time**: 7-9-2015
**Frequency**:All the time.
**FFXI Client Version**:ver. 30150619_2
**Character Name**: Avatarofhope
**Race**: Elvaan
**Main Job**: BLU
**Sub Job**: NIN
**Area & Coordinates**: La Theine Plateau
**Party or Solo**: Solo and Party
**NPC Name**:Galaihaurat (since he starts it) and the rest of the NPC in the line.
**Monster Name**: N/A
**Multi-boxing? (multiple clients on same connection)**: N/A
**Steps To Reproduce The Issue**: Accept 2-1 Mission, head to npc and get told Drill is ongoing. 

It won't let me start the drill. "All of them keep saying Rescue drill in progress. Try to stay out of the way." I head into Ordellle caves and the npc there just tells me it's dangerous. There is no way I can finish the mission and am stuck. I can't get the KI at the end of this to finish.

**Comment by LegionTiger** [comment]
I just did this mission a few days ago, so it should work. Try to retrace all steps from the beginning using http://ffxiclopedia.wikia.com/wiki/The_Rescue_Drill, this worked for me.

**Comment by Lineaus** [comment]
There isn't anything to retrace though. The gate guard says to come out to La Theine and take party in the rescue drill.  I head out to La Theine and talk to Galaihaurat. Instead of him starting the quest, I get told the drill is in progress and I should stay out of the way I head out to each of the npc and they pretty much say the same thing.

**Comment by TeoTwawki** [comment]
Somehow you had an invalid mission status leftover from a  previous mission. Did you do any mission repeats prior to starting this one? in any case it should proceed now.

**Comment by TeoTwawki** [comment]
I really need to track down which previous mission is borking this.

**Comment by TeoTwawki** [comment]
@Lineaus I forgot to mention, even after me fixing your variable you may need to talk to 1 of the NPC's twice in a row to proceed coz the dsp code here is funky. I've been meaning to rewrite this mission but haven't had time.

**Comment by Lineaus** [comment]
Thanks so much! Everything is working now. I didn't do any repeat missions though.

**Comment by TeoTwawki** [comment]
Hmm. something left a var behind, or else a moron on DSP's end changed the variables again on me. I reverted it last time they did that.
