### ISSUE TITLE
Ironclad Pulverizer incorrect loot table.

### ISSUE THREAD

**Issue by Darkara** [LegionDark/Issues#1530]
**Date & Time**: Was just after 3:00 PM CST Thursday. Sorry about the late post.

**FFXI Client Version (use `/ver`)**: 30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Darkara

**Nation**: Sandy

**Job(level)/Sub Job(level)**: 99PLD/49WAR

**NPC or Monster or item Name**: Ironclad Pulverizer

**Zone name**: Abyssea - Misareaux Coast

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: Same loot tables.
http://www.legiondark.com/db/monsters/17662479/Ironclad_Pulverizer
Warning: This monster appears to be invalid or not implemented.
http://www.legiondark.com/db/monsters/17662288/Observer

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

![darkara_2017 06 15_150432](https://user-images.githubusercontent.com/25020062/27255605-c37c97d0-5366-11e7-87d4-700e7a39152f.png)

**Comment by TeoTwawki** [comment]
@R3P0FFXI oh gee look what got UN-fixed..AGAIN.

**Comment by TeoTwawki** [comment]
https://github.com/LegionDark/Issues/issues/1394
