### ISSUE TITLE
Incorrect Item Mods & Incorrect Item Display

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1533]
**Date & Time**: 6/20/17  - 10:24am PST

**FFXI Client Version (use `/ver`)**: 30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**: Ancillam

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99RDM/49WHM

**NPC or Monster or item Name**: 

**Zone name**: Windurst Woods

**Coordinates (use `$where`)**: X:-37, Y:-1, Z:-116 (251)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/27228/revealers-pants
http://www.ffxiah.com/item/27400/revealers-pumps

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: 
The Revealer's Pumps have no stat mods to them.
The Revealer's Pants are displaying as "Byakko's Haidate" when equiped, item mods are present though.

**Comment by Jessland86** [comment]
the +1 is the same with no mods
http://legiondark.com/db/items/27401/revealers_pumps_+1

**Comment by Raelious** [comment]
Updated client, checked and Revealer Pants still have the display of Byakkos Haidate. 
Also Revealers Feet still have no mods on them.

**Comment by Jessland86** [comment]
PR'd for item mods for the feet.
