### ISSUE TITLE
Missing loot

### ISSUE THREAD

**Issue by Rokus29** [LegionDark/Issues#1535]
**Date & Time**: 10.56 21/06/17

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Eleanor

**Nation**: Windurst

**Job(level)/Sub Job(level)**: 70/35 Smn/whm

**NPC or Monster or item Name**: Carbuncle Mitts/Light spirit pact (Crimson-toothed Pawberry NM drops)

**Zone name**: Temple of Uggalepih

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  No

**Steps To Reproduce / any other info**: 
![eleanor_2017 06 21_225111](https://user-images.githubusercontent.com/29549939/27408563-33ec86c6-56d5-11e7-97d8-ab2561fdcbfa.png)

**Comment by atom0s** [comment]
Items restored for player due to DSP bug.

**Comment by TeoTwawki** [comment]
```be detailed on your ticket as to how it fell,```
would have been nice to know which dsp bug was being tripped. But I am glad you were taken care of fast and got your items you are due (I am not concerned there was ever any possibility of shenanigans in this particular case)

**Comment by TeoTwawki** [comment]
p.s. We have made dsp aware of their loot pol probs several times over, so tagging it.
