### ISSUE TITLE
Carbuncle in BCNM LB 70 area after a SMN finishes fight.

### ISSUE THREAD

**Issue by Narpt** [LegionDark/Issues#1536]
**Date & Time**: 520 PM 6/22/2017

**FFXI Client Version (use `/ver`)**: 
3.0.0.4 Ashita

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Zoomy

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
Whm70/Blm10

**NPC or Monster or item Name**: 
Maat

**Zone name**: 
~~AHEM. The staff doesn't memorize the game here. Maat is in multiple zones, now I have to go wiki the Mob to even check.~~ **BALGA'S FLIPPIN DIAS**

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Went into the fight as WHM using WHM Testimoney and Carbuncle was in the area with maat.  Did not work out so well for me as I had to heal through both.

Go into area as SMN, win the fight, go into area as WHM and see if carbuncle is still their.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/3919

**Comment by Jessland86** [comment]
Fixed in a the last maintenance. If it becomes an issue again please open a new ticket.
