### ISSUE TITLE
Missing levels

### ISSUE THREAD

**Issue by Narpt** [LegionDark/Issues#1537]
**Date & Time**: 
6/22/2017

**FFXI Client Version (use `/ver`)**: 
ver.30170601_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
No

**Character Name**: 
Zoomy

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
Zoomhealz (Level 9 thief/4blm)
Zoomy was (Level 9 Rdm/4blm) now (level 1rdm/1blm)
 
**NPC or Monster or item Name**: 
N/a

**Zone name**: 
West Ronfaure

**Coordinates (use `$where`)**: 
N/a

**ffxiah.com link (for items issues only)**: 
N/a

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Logged into both accounts to level up a sub class. got them both to 9 really quick, logged off. Logged in today, only to show one account(Zoomhealz) at level 9(Thief) while the second account(Zoomy) is back to level 1(Red Mage). Obviously I could care less about 9 levels, takes 4 minutes to get back. But this looks like a major bug.

**Comment by TeoTwawki** [comment]
logged into game or logged into website?

**Comment by TeoTwawki** [comment]
```
FFXI Client Version (use /ver):
Ashita v3
```
That isn't valid

**Comment by Narpt** [comment]
Fixed FFXI version

**Comment by TeoTwawki** [comment]
About what time (I want timezone as well) was the logout when you were level 9 ?

**Comment by Narpt** [comment]
1026pm EST

**Comment by TeoTwawki** [comment]
may take quite some time to determine what happened/if anything really happened.

If three is a major bug causing levels to go unrecorded/roll back, I expect to gets more reports of it happening.

**Comment by TeoTwawki** [comment]
I was unable to find:

- Any bug that could cause this

- Any other players experiencing the same issue on any DarksstarProject based server let alone LegionDark

- Any evidense that this actually happened

Sorry, can't do anything about it for now, will keep an eye out and keep this issue report in mind if any similar reports occur either in Legions's tracker or Darkstars (issues reports are searchable even when not open, so I will not lose this one).
