### ISSUE TITLE
Gungir 99>119 received wrong final weapon

### ISSUE THREAD

**Issue by Jessland86** [LegionDark/Issues#1539]
**Date & Time**: 
1746EDt 6/24/2017

**FFXI Client Version (use `/ver`)**: 
30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99RNG/NIN

**NPC or Monster or item Name**: 
Magian Mog TJ

**Zone name**: 
Rulude Gardens

**Coordinates (use `$where`)**: 
2 3 113

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Trade item 19752 to Mog TJ to start trial, trade 50 item 3925 (Tanz Jewels) mog TJ. Trade item 19752 to mog and currently you receive 20962/forefront_lance instead of 20926/gungnir.

**Comment by Jessland86** [comment]
![image](https://user-images.githubusercontent.com/28382433/27512204-15d79232-5907-11e7-8255-f427eb4b0d77.png)

**Comment by Jessland86** [comment]
Also it appears he incorrectly refers to himself a Cool James. But that's super minor.

**Comment by TeoTwawki** [comment]
looks like I may have flipped TJ and CJ's scripts at some point. meh.

**Comment by Jessland86** [comment]
I mean he could be trying to talk up CJ and be a good wingman!

**Comment by TeoTwawki** [comment]
Fixed in trunk, hotfixed in live server.
