### ISSUE TITLE
Chains of Promathia 8-2 Quasilumin not working

### ISSUE THREAD

**Issue by LegionTiger** [LegionDark/Issues#154]
**Date & Time**: July 10, 2015
**Frequency**: Always
**FFXI Client Version**: 30150629_2
**Character Name**: Tiger
**Race**: Hume
**Main Job**: BLM
**Sub Job**: WHM
**Area & Coordinates**:  Grand Palace of Hu'Xzoi (tested two different Quasilumin in Galka and Elvaan Tower)
**Party or Solo**: Solo
**NPC Name**: Quasilumin
**Monster Name**: N/A
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: The Quasilumin doesn't react, while it should following the starting CS of CoP 8-2 "A Fate Decided"

**Comment by goferffxi** [comment]
I was going to post this myself. Only just a few moments ago I found a guide online stating there are 5 towers. 1 for each race. I followed a guide on wiki which lead me to a pre spawned quasilumin which also failed to react when clicked. I'm a taru 99 tried with thf and war.

**Comment by Squall-Bibi** [comment]
The Quasilumin doesn't react, yes is right but not affect mission.

you need to follow exactly the correct path and mission work.

**Comment by goferffxi** [comment]
The quasilumin I clicked on was found following a path that was found on
ffxiwiki. If I took a wrong turn I apologise but I'm sure I followed it to
the letter.

**Comment by LegionTiger** [comment]
Not to mix things up, the "race" paths are CoP Mission 8-3 in "The Garde of Ru*Hmet" / "When Angels Fall". I'm having issues with the Quasilumin in "The Grand Palace of Hu'Xzoi" / "A Fate Decided". As far as i remember from retail the start for all chars was in Galka tower (J-12). Or am I wrong?

**Comment by Squall-Bibi** [comment]
yes sure 8-2 is ok path is galka to elvaan > zone > elvaan to taru > zone > taru to hume > zone and go to H8 for nm pop on the ???

**Comment by goferffxi** [comment]
This is the furthest I've ever been on cop. The quasilumin I'm trying to
activate is the first door on the right ad you zone into the area.

**Comment by Squall-Bibi** [comment]
just for info for me this mission is work but is on version of may FFXI not the june update, i dont confirm is ok on this actualy version

**Comment by LegionTiger** [comment]
OK, found out that the Cernet Doors work without Quasilumim, so no need for them. Could finish 8-2 fine. Now on end fight 8-4.
