### ISSUE TITLE
Jueno T6 Abyssites re-lost

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1540]
**Date & Time**: 6/24/17 - 4:05p PST

**FFXI Client Version (use `/ver`)**: ver 30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Raelious/Melious

**Nation**: Bastok x2

**Job(level)/Sub Job(level)**: BLU99/RDM49 x2

**NPC or Monster or item Name**: White Stratum Abyssite VI

**Zone name**: n/a

**Coordinates (use `$where`)**: n/a

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Same error as in #1501, lost the Jueno T6 one again after Astraea gave it back to me went to test it on Ig-Alima and lost it after the kill on both chars. (No other Jueno t6's were killed on those 2 chars for t6 credit) The Ashen one is working since the fix though!

**Comment by TeoTwawki** [comment]
```lua
    if (player:hasKeyItem(WHITE_STRATUM_ABYSSITE_VI)) then -- Ig-Alima Kill
        if (player:getMaskBit(player:getVar("JEUNO_VW"), 3) == false) then
            player:setMaskBit(player:getVar("JEUNO_VW"),"JEUNO_VW",3,true);
        end
        if (player:isMaskFull(player:getVar("JEUNO_VW"),5) == true) then
            player:delKeyItem(WHITE_STRATUM_ABYSSITE_VI);
            player:addKeyItem(WHITE_STRATUM_ABYSSITE);
            player:setVar("JEUNO_VW", 0);
            player:messageSpecial(KEYITEM_OBTAINED, WHITE_STRATUM_ABYSSITE);
        end
    end
```

😠

**Comment by Raelious** [comment]
Did I pick the 1 that wasn't fixed to test it on? ;;

**Comment by TeoTwawki** [comment]
:man_facepalming: 

no

**Comment by Raelious** [comment]
Not sure how it reset again then. After Immo gave me the KI back, just went and killed Ig-Alima, few days later, for a friend and it reset upon killing it.

**Comment by TeoTwawki** [comment]
`Multi-boxing? (multiple clients on same connection): Yes`

the multibox bug makes the code pply to character sit should or fail to apply things on chars it should. so you wind up with the code thinking it should do things but half of it fails..like leaving a variable behind after taking the KI, when that var should be zeroed anytime the KI is taken.

For example..
