### ISSUE TITLE
Treasure hunter overriding

### ISSUE THREAD

**Issue by gori123** [LegionDark/Issues#1543]
**Date & Time**: 28.06.2017

**FFXI Client Version (use `/ver`)**: 30170601

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Ulubey

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 99thf/49dnc

**NPC or Monster or item Name**: 

**Zone name**: any

**Coordinates (use `$where`)**: any

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**:  Have 2 thieves in party one low TH skill, one 
high TH skill whoever hits last gives real TH to the mob. High TH shall not be overridden.  it also works with TH equipment or thief subjob. 
PS: I have no real way to test this since it is so random so close ticket if i am wrong

**Comment by TeoTwawki** [comment]
wrong, there is a detailed forum post explaining how TH works, it is accurate. the only bug ever foudn with it has already been fixed. we've also printed the TH level in testing to ensure eh situation you describe does not happen. 

Note: any drop grouping where there is a 100% drop (like how king behemoth on retail will ALWAYS drop one of either pixies earring our a defending ring) will be unaffected entirely by any TH effect and this is normal. TH increases the likely hood of ***a*** drop, and you can't get higher than 100%

The same is true for legion custom drops that have been scripted to do either/or like that. It's the same thing retail does. :)

I hope this gives you piece of mind on Your Placebo Hunter Effect. :)

**Comment by Jessland86** [comment]
http://legiondark.com/forums/viewtopic.php?f=71&t=1781&p=6039&hilit=treasure+hunter#p6039 for reference.
