### ISSUE TITLE
Windurst Mission 6-2 "Saintly Invitation"

### ISSUE THREAD

**Issue by Stealthsoft** [LegionDark/Issues#1544]
**Date & Time**: Wednesday June 28 2017 8:42PM CST

**FFXI Client Version (use `/ver`)**: 30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Veridia

**Nation**: Windurst

**Job(level)/Sub Job(level)**: RDM99/WHM49 

**NPC or Monster or item Name**: Holy One's Oath (Temporary KI)

**Zone name**: Heavens Tower

**Coordinates (use `$where`)**: X: 0 Y: -49 Z: 37 (65)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: Yes (2) different zones. 

**Steps To Reproduce / any other info**: I have the Key Item to trigger the CS to end Mission 6-2 but cannot do so. Returned to Castle Oztroja to try to talk to NPC there again, but can't access that part of Mission either.

(I am aware that you cannot get to Rank 10 as Windurst National, but didn't see this particular bug in the tracker)

![pol 2017-06-28 20-40-24-61](https://user-images.githubusercontent.com/13657496/27667920-9740379a-5c43-11e7-893c-cd41b9eaaa22.jpg)

**Comment by Acedffxi** [comment]
I believe you skipped the bcnm part in balga's ?

Key item needed to click the door in castle is

**Comment by Acedffxi** [comment]
Balga's champion certificate. (Sorry I'm on my phone and hit enter button too soon. )

**Comment by Acedffxi** [comment]
Disregard ^ I read over it all too fast. My apologies.

**Comment by TeoTwawki** [comment]
prolly variable borked from multiboxing, a GM will have to check where it thinks your characters are in progression then you'll have to repeat whatever steps it didn't apply to get them caught up/fixed. longtime known thing  in darkstar, occurs semi randomly only to people with multiple logged in characters on same connection.

**Comment by Stealthsoft** [comment]
Good to know, Thanks.

Log in THF for farming key, log out before using.

**Comment by Heepster03** [comment]
MissionStatus was still on 2, even though they received the KI from the Yagudo NPC that should've set their MissionStatus to 3.

Therefore, I set the MissionStatus to 3 and having them test it.

**Comment by Heepster03** [comment]
Working as intended now~
