### ISSUE TITLE
T1 VWNM Shallow Seymour using Minotaur TP moves

### ISSUE THREAD

**Issue by EpicTaru** [LegionDark/Issues#1545]
**Date & Time**: 
06/27/2017 at 1340 EDT

**FFXI Client Version (use `/ver`)**: 
30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
EpicTaru

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
THF99/DNC49

**NPC or Monster or item Name**: 
T1 VWNM Shallow Seymour

**Zone name**: 
South Gustaberg

**Coordinates (use `$where`)**: 
X:797  Y:0  Z:440 (0)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Spawn T1 VWNM Shallow Seymour.
Mob uses Minotaur TP moves (e.g. Lethal Triclip)

**Comment by R3P0FFXI** [comment]
@EpicTaru This is not possible, I have re-verified again the mob is on  a custom skilllist and none of these are Minotaur TP moves the only 3 TP Moves this can do are Sandspin, Tremors, and Mudspin which are all worm TP moves.

**Comment by EpicTaru** [comment]
I failed to screenshot the mob doing the Lethal  Triclip TP move,  Both @Raelious and @Skenton also witnessed the mob performing this move.  I would have thought it was normal but Rae stated that the move was doing Minotaur TP moves so I took it upon myself to go ahead and submit a ticket regarding it.  After the mob was finally killed, my stratum abyssite upgraded to Chapter II so I am now unable to re-pop this mob and SS it doing the incorrect TP move.  I'm sure that if you popped it you'd be able to see it do it.

**Comment by Heepster03** [comment]
[19:32:23] Halkuras is drawn in!
[19:32:23] Unable to see the Sallow Seymour.
[19:32:24] The Sallow Seymour readies Lethal Triclip.

I personally verified it myself, current investigation underway.

**Comment by TeoTwawki** [comment]
@R3P0FFXI it was a scripted trigger for draw in, happens whenever draw in happens.

@EpicTaru has been hotfixed in live server

**Comment by EpicTaru** [comment]
Thank you all for your assistance/resolution of this matter. :+1: :)

**Comment by w3genesis** [comment]
Mimic King began using Double Kick ws after draw in. Probably same error as above.

**Comment by EpicTaru** [comment]
@w3genesis  - Not sure if you need to but you probably should open a separate ticket regarding your issue.

**Comment by w3genesis** [comment]
Laziness says no :D

**Comment by TeoTwawki** [comment]
already know the why. its not changing the set. the wrong move is called in the draw trigger. in the future separate reports (or better yet a new report listing multiple ones where you see the same problem) is better simply because this issue was basically over so I was less likely to notice any new ones here.

Except mimic king doesn't have the same issue at all - he doesn't even use a draw in trigger (where a move is activated *because of* draw in, like Seymour was doing).
