### ISSUE TITLE
Grounds Tome Counted with 0 exp gained on Monster kill.

### ISSUE THREAD

**Issue by T3RT1UM** [LegionDark/Issues#1550]
**Date & Time**:  7/4/2017  2:12 AM cst

**FFXI Client Version (use `/ver`)**: 30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Nanashi

**Nation**: Bastok

**Job(level)/Sub Job(level)**: COR(74)

**NPC or Monster or item Name**: 

**Zone name**: Zeruhn Mines

**Coordinates (use `$where`)**: X:-25 Y:0 Z:4

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 
Party leader 74 corsair and a 99 redmage (no level sync).  Kills from corsair(72) counts toward the Grounds tome (page 4) when there is a 99 redmage on party and 0 exp is gained.  However, kills or extra damage from 99 Redmage does not seem to count toward the Grounds tome (page 4).

![nanashi_2017 07 04_022932](https://user-images.githubusercontent.com/22230953/27819698-0f0e19c4-6061-11e7-9ac9-461df3b9a207.png)

**Comment by Jessland86** [comment]
Taken care of in today's maintainance.
