### ISSUE TITLE
Magic barrier resisting death

### ISSUE THREAD

**Issue by Valknut4** [LegionDark/Issues#1552]
**Date & Time**: 3:14pm

**FFXI Client Version (use `/ver`)**: 30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Shale

**Nation**: Bastock

**Job(level)/Sub Job(level)**: 99THF/49DNC

**NPC or Monster or item Name**:Overlord tombstone

**Zone name**: Dynamis Sandoria

**Coordinates (use `$where`)**: 0.027 -2 42.099 185

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Magic barrier(BLU) is resisting death and other forms of CC, I'm not 100% sure that this is not intended, but I cannot find any info of retail having this quality. Multiple pages suggest the only way of avoiding death is the specific barriers granted by the fools items, and that the only sure fire way to not die to death is stunning the cast. Which also seems to be a very small window. I'm not sure what my ping to the server is though.

**Comment by TeoTwawki** [comment]
Were you wearing the augmented ring we gave out awhile back? because the ring can resist *anything* even death.

**Comment by Heepster03** [comment]
Shadow Ring also "Resists Death" if it's coded correctly. It's rare but it exists.

**Comment by Heepster03** [comment]
Couldn't help but notice that you're reporting a Blu spell while you were thf and not dualboxing (huge no-no anyways). Got me curious now.

**Comment by Valknut4** [comment]
I'll test and make sure that this wasn't the case, I'll try and have it tested by later tonight.

**Comment by Valknut4** [comment]
Wasn't my BLU mage tanking it was Rocks

**Comment by gori123** [comment]
his death thing really bugs me. if it acts like in retail it shall stay if not please modify it as retail.

**Comment by TeoTwawki** [comment]
@Valknut4 @Heepster03  I found the reason for it 

@gori123 yes it casting death is retail

**Comment by TeoTwawki** [comment]
Hotfix applied to live server.

**Comment by Valknut4** [comment]
Nice, it did seem odd that Magic Barrier ( I assume ) was the only thing that could stop the spell.
