### ISSUE TITLE
Part III - When Angels Fall - Chains of Promathia

### ISSUE THREAD

**Issue by xendral** [LegionDark/Issues#1554]
**Date & Time**:  5:55pm PST 7/8/17

**FFXI Client Version (use `/ver`)**:  30170601_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: no 30170427_0

**Character Name**: Bozidar

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99thf/49dnc

**NPC or Monster or item Name**: Particle Gate

**Zone name**: The Garden of Ru'Hmet (third floor)

**Coordinates (use `$where`)**: X:419 Y:0 Z:399 (196).

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Completing part 2 of the CoP mission and porting up to the third floor. Particle gate won't give CS Therefore can't initiate the Fight for the mission. When I click the gate, nothing happens.

I found this bug report from what appears to be another private server.
https://github.com/DarkstarProject/darkstar/issues/1825

**Comment by xendral** [comment]
Also, I see my issue is 1554..  Wonderful beer in case anyone likes to try dark beers.

http://www.newbelgium.com/beer/1554

**Comment by Heepster03** [comment]
Player didn't do the climb up Hume tower to double click on the 'Ebon Panel' yet, therefore can't enter fight.
