### ISSUE TITLE
Can't start 3-1

### ISSUE THREAD

**Issue by Mezurashi** [LegionDark/Issues#1555]
**Date & Time**: Sunday, July 9th, 2017  12:16am

**FFXI Client Version (use `/ver`)**:  30170601_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  30170427_0

**Character Name**:  Priscilla

**Nation**: San D'Oria

**Job(level)/Sub Job(level)**: SAM63/DNC31

**NPC or Monster or item Name**: Perfaumand

**Zone name**: Chateau d'Oraguille

**Coordinates (use `$where`)**: X:-37 Y:-3 Z:68 (176)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: Starting mission 3-1 after speaking to the gateguard I was instructed to go speak with Prince Trion. The guard simply won't let me into his room despite having the quest. The guard simply states. "This is Prince Trion's Chambers. No entry." Clicking the door or the guard gives the same results. The guard name is Perfaumand.

**Comment by Heepster03** [comment]
```
[00:14:24]` Halkuras : $checkmission 0 Priscilla
[00:14:24] ----== SystemMessage ==----
Current San d'Oria Mission ID is: '4' !
```
San d'Oria Mission 4 is "The Davoi Report" which is Mission 2-2 not to be confused with "Infiltrate Davoi" which is mission 3-1.

**Comment by Mezurashi** [comment]
http://ffxiclopedia.wikia.com/wiki/Infiltrate_Davoi

**Comment by Heepster03** [comment]
Was just a simple mistake of accidentally repeating a previous mission instead of selecting the next one in line. Good luck~
