### ISSUE TITLE
Isarukitsck TP move Whiteout crashes client

### ISSUE THREAD

**Issue by w3genesis** [LegionDark/Issues#1556]
**Date & Time**: 2017/07/03

**FFXI Client Version (use `/ver`)**: 30170427

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170707

**Character Name**: Gouken

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99 Sam/Dnc

**NPC or Monster or item Name**: Isarukitsck

**Zone name**: Uleguerand Range

**Coordinates (use `$where`)**: G-10

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: 
Multiboxing 6 clients for the fight, whenever Isarukitsck uses Whiteout TP move, has high chance 1-2 clients will crash out. Fought the mob 12 times for 6 earrings, probably crashed 30 times combined.
The model for the mob gets twisted badly when the tp move is performed, so probably wrong or no animation setting has been used for that tp move.

**Comment by Heepster03** [comment]
Missing literally everything in the ticket.

**Comment by w3genesis** [comment]
Well if you hit enter when entering title it submits automatically...

**Comment by TeoTwawki** [comment]
If this mobskill were the source of those crashes, and not something else like generic interruption or action overlap or the dozens of other things that can cause them, it would happen every single time. not sometimes. I will try to see if I can locate a client crash source at this mob beyond the _usual generic crashes\*_ that result from action packet flubs in darkstar 

_(interrupt mobskill, or overlap action packets, or a dozen other things..ugh)_

**Comment by TeoTwawki** [comment]
oh, do you remember what jobs were in your party and what your strategy was? it'll help me

**Comment by w3genesis** [comment]
Went as Pld/sam, Sam/dnc, Whm/rdm, Whm/rdm, Rdm/blm, Thf/dnc. No stuns were used at all, just standard meleeing and WS.
Isarukitsck's Whiteout will crash client randomly, seeming to be about 30% chance for 1 client to crash whenever the move is used.
Had 2 clients crash together maybe three times in the 12 fights, but no more than 2 crashes per move. Crashes happen a split second after the mob readies the move, and might be due to graphic glitch as each client tries to draw the mob twisting itself into a strange shape when performing the move.

**Comment by TeoTwawki** [comment]
its prolly the animation packets for the borked animation when combined with multiboxing (since DSP handled these wrong, you get extra packets you should not across all your characters). I'll try to do the same setup.

> No stuns were used at all, just standard meleeing and WS.

I like how everyone says that before I ask now. :) Just so you know stun isn't the only way to trigger that particular glitch, just the most common because of the overpopulation of blu's on the server :)

**Comment by w3genesis** [comment]
Is it possible to change the animation for Whiteout to that of Beak Lunge or Yawn? Will do a fight a few more times to see if that fixes the crashes.

**Comment by TeoTwawki** [comment]
it won't update while the server is running, so stuck with what it is till fixed in maint

**Comment by Heepster03** [comment]
![2017-08-08](https://user-images.githubusercontent.com/8421725/29057302-01946166-7bcf-11e7-9b83-04454353c76d.png)
This just happened tonight while it did Whiteout and it instantly crashed my client.

**Comment by TeoTwawki** [comment]
Gee heep, thanks for waiting for me to actually have time to  change the move to repeat what we already knew and bringing up the stun thing again

**Comment by TeoTwawki** [comment]
I've been busy with having things you know I can't discuss here plus not having access to my repository to actually do the deed while having to help family emergency move.

**Comment by R3P0FFXI** [comment]
@TeoTwawki I believe you and I determined the Whiteout script to be ok

`INSERT INTO `mob_skills` VALUES (2819,2563,'whiteout_custom',1,20.0,2000,1500,4,0,0,0,0,0,0); -- fix me`

Please catch up with me this week to show me how to browse through the animations

**Comment by TeoTwawki** [comment]
Completely reworked as of next maint, if issue still occurs after that then new issue or reopen.
