### ISSUE TITLE
Stuck in loading when exiting airship.

### ISSUE THREAD

**Issue by AleksandarFFXI** [LegionDark/Issues#1557]
**Date & Time**:  07/10/2017

**FFXI Client Version (use `/ver`)**:  Latest

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  Yes

**Character Name**:  Aleksandar

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  60THF/30WAR

**NPC or Monster or item Name**:  None

**Zone name**: Jeuno to Kazham Airship

**Coordinates (use `$where`)**:  None

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  No

**Steps To Reproduce / any other info**:  Take Airship

**Comment by TeoTwawki** [comment]
Well known intermittent DSP issue. Sometimes if you wait a long time (next airship cycle) the game will catch it. Doesn't happen every trip, its a timing bug.

**Comment by TeoTwawki** [comment]
I will be adding a workaround. I will close this issue at that time, as nothing more can be done about it.

**Comment by TeoTwawki** [comment]
update: workaround coded and tested, and will be in with LegionDarks next maintenance

**Comment by TeoTwawki** [comment]
Workaround added will have wiki page with details shortly.
