### ISSUE TITLE
Bibiki Bay to Purongo Isle Boat Double Ticket Ride

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1558]
**Date & Time**: 6/7/17

**FFXI Client Version (use `/ver`)**: The previous version number prior to this latest update.

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: At the time yes.

**Character Name**: Raelious

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99PLD/49WAR

**NPC or Monster or item Name**: 

**Zone name**: Bibiki Bay

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
This has happened a couple times where if you have 1 ticket left when boarding the boat, it will often times charge the player twice for the ride. If will allow you passage onto the Manaclipper but when the boat reaches this destination it will kick you off at the start of Bibiki Bay/Buburimu. Often seems to happen more often when the boat is claiming to take you to a different isle, and since all rides always take you to Puronogro Isle may be causing this issue? @Heepster03 has seen this happen first hand me. Has happened a total of about 3 times in the last couple months. Also if you only have 1 ticket, there is no way to cancel you tickets and rebuy 10 tickets, so if you board with 1 ticket and it charges double youre kinda SOL.

**Comment by TeoTwawki** [comment]
@LegionDark/gm needs sent to DSP and then labeled as forwarded to them

**Comment by Raelious** [comment]
Think you temp fixed this by adding the 5k boat rides. Ill close it out for now.

**Comment by TeoTwawki** [comment]
did this ever go to DSP though?
