### ISSUE TITLE
Sandoria Mission 6-1, Halver won't talk

### ISSUE THREAD

**Issue by kairoffxi** [LegionDark/Issues#1559]
**Date & Time**: 
8:29PM PST

**FFXI Client Version (use `/ver`)**: 
30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30170707_0

**Character Name**: 
Kairo

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
BLU99

**NPC or Monster or item Name**: 
Halver

**Zone name**: 
Chateau d'Oraguille

**Coordinates (use `$where`)**: 
X:0 Y:0 Z:0 (225)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Probably yes

**Steps To Reproduce / any other info**: 
Gate guard says finish current mission first.
Halver doesnt respond.
Dreamrose in West Altepa doesn't spawn Cactaur
Do not have Dreamrose KI.

Most likely the same issue as https://github.com/LegionDark/Issues/issues/1503

Did not realize multiboxing and missions can cause issues. Will be more careful to get missions solo going forward.

**Comment by TeoTwawki** [comment]
Looks like I've been volunteered by the lack of *anyone else responding*.

######  *@LegionDark/gm ya buncha fawkers*

**Comment by TeoTwawki** [comment]
Will catch up with you sometime tomorrow or day after

**Comment by TeoTwawki** [comment]
You either dc'd or logged without telling me if yer next mission worked after I force completed that

**Comment by kairoffxi** [comment]
Sorry about that, I had to step out suddenly. This is working great now! I was able to start Sandoria Mission 6-2 Ranperre's Final Rest right away at the gate guard then continue to chat with the mission next NPCs.

I can finally progress my rank, thank you for the effort so soon after maintenance. Cheers! -Kairo

**Comment by TeoTwawki** [comment]
k. when you get a chance I need this bugged mission [reported to darkstar](https://github.com/DarkstarProject/darkstar/issues). I don't think its just multiboxing. Your MissionStatus was at 9. This mission doesn't even go that far. 
```lua
    -- LEAUTE'S LAST WISHES (San d'Oria 6-1)
    elseif (currentMission == LEAUTE_S_LAST_WISHES and MissionStatus == 4 and player:hasKeyItem(DREAMROSE)) then
        player:startEvent(0x006f);
```
```lua
    if (csid == 0x022c or csid == 0x006f) then
        finishMissionTimeline(player,3,csid,option);
```lua
16,{0,0},      {0,0},     {0x006f,0},{0,0},{{14,0},{9,268},{10,270},{12}},                                 -- MISSION 6-1 (Finish (Chalvatot))
```
mission should have ended when you talked to Chalvatot with status of 4. He'd then set it to zero and set that mission completed but instead of just having him do it the script calls that global with a ton of crap in a table nobody sane is going to step through unless *forced to at gunpoint* to see wtf happened. Luckily all us devs are nuts but I want a  night off from crazytown so *"not it"*.

**Comment by kairoffxi** [comment]
I'd be happy to report the issue to DSP. My experience was similar to this https://github.com/DarkstarProject/darkstar/issues/3018 issue too where I started 6-1 at the gate guard but then Halver just never advanced the mission.

The crazy town table is part of DSP or something internal to LegionDark? The event code above looks understandable so if theres another LUA file to wade through I can take a look and see if I can find anything to include when reporting to DSP.

**Comment by TeoTwawki** [comment]
its part of darkstar

and def needs new issue that person mission status was failing to reach 1 from zero..yours was 9. they need to know your status went to abnormal values and at which step.
