### ISSUE TITLE
Ukudyoni  - Great Sword Missing stats~

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#156]
**Date & Time**: 7/10/2015
**Frequency**: Constant.
**FFXI Client Version**: Both me and Aurel are on latest Version. Loged out already but ill edit it later.
**Character Name**: Daedrik
**Race**:Elvaan
**Main Job**:DRK99
**Sub Job**:SAM49
**Area & Coordinates**:
**Party or Solo**:
**NPC Name**:     Ukudyoni  - Great Sword
**Monster Name**:
**Multi-boxing? (multiple clients on same connection)**:No
**Steps To Reproduce The Issue**: Equip GS and check the Refresh effect not work. The Crit+7% also is not registering in @stats but that could be there just not registering in list. Also Aurel tested the Thunder: attack +25 and says it doesn't affect it

**Comment by TeoTwawki** [comment]
if the +attack isn't there the item is likely 100% not coded yet

**Comment by Loki79** [comment]
fixed.  be in next maint/crash/restart
