### ISSUE TITLE
VWNM Jeuno abyssite went from 5 to 6 without cut scene done

### ISSUE THREAD

**Issue by w3genesis** [LegionDark/Issues#1560]
**Date & Time**: 2017/7/10

**FFXI Client Version (use `/ver`)**: 30170427

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170707

**Character Name**: Gouken

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99 Sam/dnc

**NPC or Monster or item Name**: Gwynn Ap Nudd

**Zone name**: Konschtat Highlands

**Coordinates (use `$where`)**: G-4

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: 
Killed Tier 5 Jeuno NM Smierc, Stachysaurus, Gwynn Ap Nudd in that order, when Gwynn Ap Nudd dies, the White Stratum Abyssite upgraded from V to VI automatically. 

According to wiki, I would have needed to talk to Voidwatch Officer and head to Ru'Lude Gardens and talk to the Audience Chamber door before the Abyssite would go to 6.

Current Abyssite is at 6 and works fine (spawned tier 6 Botulus Rex without problem), but I did not receive Starlight Voidwatcher's Emblem that should come with Tier 6 Abyssite.

Not sure if this is a feature working correctly or a bug and should have happened like the wiki.

**Comment by Raelious** [comment]
Pretty sure that is intended. Ive progressed about 5 characters through VW and always got T6 right away after killing the Jeuno T5's. And none of my characters have that KI that you are referring too.

**Comment by TeoTwawki** [comment]
that was where we left off on implementation see, so we left the mobs upgrading you till the rest gets done. and then the guys decided to give you outlands and toau vwnm's early..The remaining cs stuff won't be in till the next quests for VW are ready.
