### ISSUE TITLE
Dragon Tank is not a usable item.

### ISSUE THREAD

**Issue by Jessland86** [LegionDark/Issues#1561]
**Date & Time**: 
07/13/171106 EDT

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99PLD

**NPC or Monster or item Name**: 
Dragon Tank

**Zone name**: 
n/a

**Coordinates (use `$where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
http://legiondark.com/db/items/11002/
http://www.ffxiah.com/item/11002/dragon-tank

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
Dragon tank cannot be used to dispense D. Fruit au Lait. Item shows no charges etc. 
![untitled](https://user-images.githubusercontent.com/28382433/28173281-f800ac26-67bb-11e7-9d73-a94acf675156.jpg)
![dragon_tank](https://user-images.githubusercontent.com/28382433/28173349-2d77ab48-67bc-11e7-953a-cc17a6ca243e.png)

**Comment by TeoTwawki** [comment]
https://git.io/vQQQ2
