### ISSUE TITLE
Sozu Sarberry no THF Knife drop

### ISSUE THREAD

**Issue by Garvaunt** [LegionDark/Issues#1562]
**Date & Time**: July 14, 2017 @ 4:45pm PST.

**FFXI Client Version (use `/ver`)**: 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170707_0, Yes

**Character Name**: Garvaunt

**Nation**: San'doria

**Job(level)/Sub Job(level)**: BLM99/RDM49

**NPC or Monster or item Name**: Sozu Sarberry

**Zone name**: Temple of Ugglephia

**Coordinates (use `$where`)**: X:59 Y:0 Z:7 (67)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/16480/thiefs-knife

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Kill NM? i dont know how to reproduce this.

https://gyazo.com/3e345716cd7948c6562008431c8867e0

According to the Item Database the Knife is suppose to be a 100% drop.

**Comment by kairoffxi** [comment]
Wrong NM, Sozu Rogberry drops Thief's Knife. http://legiondark.com/db/monsters/17428751/Sozu%20Rogberry

**Comment by Heepster03** [comment]
@Garvaunt:

Just as @kairoffxi said, **Sozu Rogberry** not _Sozu Sarbarry_ is who you are looking for. 

Closing ticket. If you kill **Sozu Rogberry** and it doesn't drop the knife then write another ticket.
