### ISSUE TITLE
Can't progress in Sandoria mission 6-2

### ISSUE THREAD

**Issue by hadouken420** [LegionDark/Issues#1563]
**Date & Time**: 7/15/2017 3:10ish AM EST

**FFXI Client Version (use `/ver`)**: 30170427_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170427_0

**Character Name**: Kula and Kerrigan

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 99BLU/49RDM and  99WHM/49RDM

**NPC or Monster or item Name**: Grilau

**Zone name**: Southern Sandoria

**Coordinates (use `$where`)**: X:-240 Y:8 Z:58 (102)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: Turned in book to Grilau for deciphering, zoned and waited many hours but cant progress. Suppose to tell me to talk to Prince Trion but doesnt.

**Comment by Jessland86** [comment]
It's a server midnight wait for this mission.

**Comment by Jessland86** [comment]
You should be able to progress further in approx 27 more minutes.

**Comment by hadouken420** [comment]
It's working now. Sorry for wasting your time.

**Comment by Jessland86** [comment]
You're fine, Just one of those many ways that retail wait times on the wiki don't match up to what DSP has.
