### ISSUE TITLE
Incorrect Login and Timing Out

### ISSUE THREAD

**Issue by aidai7310** [LegionDark/Issues#1564]
**Date & Time**: 
07/16/17 9:01 AM EST

**FFXI Client Version (use `/ver`)**: 
not sure

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Aidai
Aidaitaru

**Nation**: 
n/a

**Job(level)/Sub Job(level)**: 
n/a

**NPC or Monster or item Name**: 
n/a

**Zone name**: 
n/a

**Coordinates (use `$where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes, but not always. 

**Steps To Reproduce / any other info**: 
I am getting incorrect login for Aidaitaru (I use this char for my bazaar). Aidai times out after login when loading files. Restarted my pc and Aidai logged in but won't now (haven't tried restarting again) yet. I am sure I'm putting in right login info and haven't had issues until yesterday. I use same password for both logins - not sure if that's part of the issue but again...no issues previously. I use Windower but also tried Ashita 3 and same thing.

**Comment by w3genesis** [comment]
Reset your internet modem and restart computer. Sometimes login gets stuck if you did not log out properly the last time due to crash/R0/power off.

**Comment by aidai7310** [comment]
Restarting does work for Aidai...so i will say that one is okay. I still get invalid username/password for Aidaitaru. I have tried through Windower, Ashita 3, and on a different internet source with same result. I have had this char maybe a week now and just use it for my bazaar. I can't login even when I'm not on Aidai char. I haven't run into any issues thus far until Friday. Same password for both chars.

**Comment by TeoTwawki** [comment]
This report was kinda confusing to read. 

Invalid username/password message in xiloader can *only* mean that you actually used either the wrong name or password. That error message would be *entirely separate* form any other issues like connection loss/timeouts that happen, and nothing to do with what happens to your other character (unless you are trying to login both *at the same time* in which case you need to *slow down* and let one be fully in game before even starting the next, but presumably you already know this).

Please come see me on discord PM, we don't want to be discussing your login credentials in public.

**Comment by aidai7310** [comment]
Sorry for the confusion! I was having problems with both logins; but now just one - Aidaitaru. That is the one I am getting incorrect login for. I'm still learning how to use Discord and can't figure out how to PM you. I'm Aidai#6224

**Comment by TeoTwawki** [comment]
was actually wrong username, resolved in discord. user was using char name for account name.
