### ISSUE TITLE
Casting Escape in a zone not escapeable causes you to be invisible. 

### ISSUE THREAD

**Issue by starblazr** [LegionDark/Issues#1565]
**Date & Time**: 
10:16AM CST

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Starblazer / Stretch

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
WHM/BLM, BLM/THF (respectively)

**NPC or Monster or item Name**: 
Escape

**Zone name**: 
Heavens Tower

**Coordinates (use `$where`)**: 
Didn't get, will update and try again in the zone.

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Was next to  Zubaba doing Windurst 3-2 and was being lazy and attempted to 'escape' out of the tower instead of having to /servo send /ma warp to the chars.. I escaped, spell casted, but char models went blank.  I could move but all pt members were invisible.  see attached screenshot.  I will update the tkt with a POS next time I'm in the tower (which will be about an hour or two)
![stretch_2017 07 16_101406](https://user-images.githubusercontent.com/7802036/28248820-79a16152-6a10-11e7-9141-ae9bc0decdbd.png)

**Comment by starblazr** [comment]
it seems to be anywhere in heavens tower.  I casted escape in a different part and it did the same thing.  POS was x:2 y:-49 z:29 (67)
![stretch_2017 07 16_113432](https://user-images.githubusercontent.com/7802036/28249417-d96a2f4c-6a1a-11e7-8cad-483d59c6c6c4.png)

**Comment by Jessland86** [comment]
I'm not entirely sure escape should be able to be cast in the zone, and thus leading to this result. A very similar thing happens when trying to warp to abby maws when you aren't past that point in the abby story line. The warp animation goes off, makes you invisible, and you stay there still able to do everything like normal. 

If this is the case, this same result should happen when you cast escape in any zone that is not escape-able.

**Comment by Jessland86** [comment]
Yup, this is what it is. If you cast escape in a zone that you can't escape from it does this.

**Comment by Jessland86** [comment]
https://github.com/DarkstarProject/darkstar/issues/3940

**Comment by Jessland86** [comment]
Was fixed in the last maintenance.
