### ISSUE TITLE
Windurst Mission 3-2 weirdness.

### ISSUE THREAD

**Issue by starblazr** [LegionDark/Issues#1566]
**Date & Time**: 
7/16/2017, 10:58 CST

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Starblazer

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
WHM70/BLM35

**NPC or Monster or item Name**: 
Zubaba

**Zone name**: 
Heavens Tower

**Coordinates (use `$where`)**: 
at Zubaba.

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
I was doing Windurst 3-2 with Star and Stretch.  We had Elinor help us with the Portal charm.  I took them both to the door, touched it, went thru the cutscene.  When I went back to Heavens Tower, Star traded Kupipi a Rollenberry to do that quest which also gives you a portal charm after the mission.  She accepted the rollenberry and then when Star went up to talk to Zubaba to finish the quest, she talks to me like I didn't touch the door.  Attached are the screenshots of Star actually touching the door and the resulting weirdness.

Stretch was able to complete the mission normally, which leads me to believe it has something to do with the side quest.

![starblazer_2017 07 16_105243](https://user-images.githubusercontent.com/7802036/28249168-4b9017da-6a16-11e7-91a3-758444c7599f.png)
![starblazer_2017 07 16_110319](https://user-images.githubusercontent.com/7802036/28249171-63ead72a-6a16-11e7-8275-0ad6895d05e6.png)

**Comment by starblazr** [comment]
I don't know if the KI disappears when you touch the door or when you end the mission.  I'll find out and update when I touch the door again.

**Comment by starblazr** [comment]
so, updating the ticket.  The Light Charm went away right after touching the door to trigger the cutscene.  As soon as I went back into town the second time, mission finished just fine.

**Comment by Jessland86** [comment]
Issue worked itself out after retracing steps.
