### ISSUE TITLE
NM tp moves Abyssea-Misereaux crashing xiloader

### ISSUE THREAD

**Issue by stevomatic** [LegionDark/Issues#1567]
**Date & Time**: 
7/16/2017

**FFXI Client Version (use `/ver`)**: 

30170707_0
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Agnes Annebonnie Gunt Langridge Gurgitator

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 

blm/rdm brd/whm blm/rdm blm/rdm rdm/whm 99/49
**NPC or Monster or item Name**: 

Cirein-Croin and Heqet
**Zone name**: 

Abyssea-Misereaux
**Coordinates (use `$where`)**: 
Cirein fighting at spawn ???
Heqet 282 -24 310 (165)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Basic manaburn setup, rdm is simply there holding an extra pop set. pop cirein, lullaby timed nuke lullaby except if he manages to get off a tp move it's crashing party members, not 100% but it seems like a cumulative effect, eventually they'll reddot. With heqet if he gets off a waterbomb its pretty much instacrash. I used almost identical setup for Isegebind and didn't have any problems at all in Uleguerand. Right now basically to beat my way through it I have to not screw up my lullaby cast and relog everyone in every step of the process, crash or no crash. Cep relog >heqet relog >cirein relog rinse, not to mention they abysmal drop rates on KI's ^^

**Comment by TeoTwawki** [comment]
I'm sorry but I am just so sick of re-explaining how this works 😭 not even gonna do it this time, all ya get is links. it took us forever to trace and even after all that it just gets re-posted to a new issue every week,

https://github.com/DarkstarProject/darkstar/issues/3393
https://github.com/DarkstarProject/darkstar/issues/1618
https://github.com/LegionDark/Issues/issues/1115
https://github.com/LegionDark/Issues/issues/219
https://github.com/LegionDark/Issues/issues/928

**Comment by TeoTwawki** [comment]
We can't fix it, DSP has to. Its a packets thing.
