### ISSUE TITLE
Boartrap have no drops/No pop item available for Tuskertrap

### ISSUE THREAD

**Issue by Jessland86** [LegionDark/Issues#1568]
**Date & Time**: 
7/17/2017

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
n/a

**Nation**: 
n/a

**Job(level)/Sub Job(level)**: 
n/a

**NPC or Monster or item Name**: 
http://legiondark.com/db/monsters/17662183/Boartrap

**Zone name**: 
byssea-Misareaux 

**Coordinates (use `$where`)**: 
varies

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
No drops from Boartraps making Tuskertratp un-poppable.

**Comment by R3P0FFXI** [comment]
@LegionDark/gm 

`INSERT INTO `mob_groups` VALUES (10252,481,216,0,0,0,0,0,0,0,0);`

Drop ID of 0 in DSP please assign a drop pool in DSP with retail drops

**Comment by Raelious** [comment]
Fix Submitted
