### ISSUE TITLE
Relic trial bugged

### ISSUE THREAD

**Issue by Skett** [LegionDark/Issues#157]
Date & Time: 7-11-2015
Frequency:N/A
FFXI Client Version:ver. 30150619_2
Character Name: Skett
Race: Elvaan
Main Job: THF
Sub Job: NIN
Area & Coordinates: N/A
Party or Solo: N/A
NPC Name: Vanessa?
Monster Name: N/A
Multi-boxing? (multiple clients on same connection): NA
Steps To Reproduce The Issue: Completed trial for Mandau 85-95, completion status stuck at 0.

Needs updating manually, cheers guys. SS below

**Comment by Skett** [comment]
![skett_2015 07 11_160524](https://cloud.githubusercontent.com/assets/12629708/8634193/01306032-27e7-11e5-9ec8-a80b16304316.png)

**Comment by TeoTwawki** [comment]
using the command while the weapon is equipped will recheck the kill counts and update the status automatically.

**Comment by Skett** [comment]
Might be worth adding that to the thread just so ppl know, to prevent further reports.
Ta

Date: Sat, 11 Jul 2015 09:08:18 -0700

**Comment by TeoTwawki** [comment]
Would have, but rewriting whole system to not be nutty instead
