### ISSUE TITLE
Ix'aern (DRK) not spawning

### ISSUE THREAD

**Issue by w3genesis** [LegionDark/Issues#1570]
**Date & Time**: 2017/7/18

**FFXI Client Version (use `/ver`)**: 30170707

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Gouken

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99 Sam/dnc

**NPC or Monster or item Name**: Ix'aern (DRK)

**Zone name**: The Garden of Ru'Hmet

**Coordinates (use `$where`)**: X:-559 Y:5 Z:239

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 
The ??? for spawning Ix'aern (DRK) at F-10 does not spawn the mob after trading 48 aern organs to it. Also tried trading 1, 12, 24, 36, 60 etc with no result. ??? just says "You sense some unknown presence..."
The ??? has also been moving among the 4 square rooms, tried trading organs at those places as well but didn't do anything either.

**Comment by benfolka** [comment]
it spawns like retail, i did same mistake. throw away your organs, you may request that forum topic deleted. And you will have to kill it like 15-20 times, it reraises that is normal.

**Comment by TeoTwawki** [comment]
the custom trade thing was accidentally removed that day @R3P0FFXI had to do maint without me. Since DSP has the bleeping spawn fixed though the work around is no longer needed, I'll see to it the old info gets cleaned up.

**Comment by w3genesis** [comment]
Thanks for clearing that up. Good thing I only farmed 60 aern organs lol.
The animosity thingy seems to be hard to get though, tried for an hour and nothing yet.

**Comment by benfolka** [comment]
it can be on any of your chars, manually try to pop it with all.

**Comment by Heepster03** [comment]
Yeaa...... on retail, you could be farming for that "Animosity" for awhile if that's how it plays out. I remember doing it way back when and it taking like 12 hours sometimes to farm the animosity to pop it. It's purely random.

**Comment by Jessland86** [comment]
I verified this...(for like the 40th time since it got changed to animosity.) It pops as intended.

**Comment by w3genesis** [comment]
@TeoTwawki Spawned Ix'aern (DRK) today with animosity without problem. But when killing the mob, it reraised for a straight 3 hours. Was using 3 empy weapons for the fight so each kill took only 90 seconds, but the reraise happened almost 100 times.
Not sure if this is intended, but is there any possibility to make this mob slightly more friendly? ^^; Was late for work from the reeeeeeeally long fight.

**Comment by TeoTwawki** [comment]
intended is totally retail it reraises completely randomly this is how its coded in dsp we didn't do it

**Comment by TeoTwawki** [comment]
retail really can reraise hundreds of times..but we'll perform some addition checking to be sure something isn't broken on dsp;s end (we haven't touched this, the core projects code is whats in use and I've seen no bugs reported in their tracker about this yet)
