### ISSUE TITLE
Flee Glitch

### ISSUE THREAD

**Issue by AleksandarFFXI** [LegionDark/Issues#1572]
**Date & Time**:  4:45pm PST

**FFXI Client Version (use `/ver`)**:  Current 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  Yes

**Character Name**:  Aleksandar

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  THF60/NIN30

**NPC or Monster or item Name**:  None

**Zone name**:  Konschatch Highlands

**Coordinates (use `$where`)**:  Crag of Dem

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  No

**Steps To Reproduce / any other info**:  Use "Flee" in any zone. When it is about to expire, use "$tele dem". It gave me Permanent Flee while I was in the Zone. Ended when I switched zones to Valkrum Dunes. May work with other $tele commands.

**Comment by Jessland86** [comment]
It's not just a tele command, it's any form of zoning when it's about to expire.

**Comment by TeoTwawki** [comment]
@LegionDark/gm @LegionDark/thebosses needs to go to dsp immediately this is serious

**Comment by w3genesis** [comment]
This might be same problem that causes zoning to sometimes "eat" linkshell messages received in the gap between zones. Some buffs carry over between zones, and the zone gap just happens to "eat" the end command for buff.

The linkshell message problem has happened in retail as well so not sure if a fix is possible at all.

One possible method is to create a feedback like /tell messages, if you /tell someone who is zoning, you get the message they did not receive it. So same thing for skills ending, send the end flag, if the effect is not received, resend it 5 seconds later etc. Not sure what other bugs might happen from such a method though lol.

**Comment by TeoTwawki** [comment]
losing messages between zones is fairly normal - happens in retail as well depending on the exact timing and how long the black screen loading was. but also on retail, status effect timers keep ticking during said loading..on darkstar your entire character is disassembled and rebuilt in the other zone when you cross.20.07.2017, 04:30, "w3genesis" <notifications@github.com>:This might be same problem that causes zoning to sometimes "eat" linkshell messages received in the gap between zones. Some buffs carry over between zones, and the zone gap just happens to "eat" the end command for buff.
The linkshell message problem has happened in retail as well so not sure if a fix is possible at all.
One possible method is to create a feedback like /tell messages, if you /tell someone who is zoning, you get the message they did not receive it. So same thing for skills ending, send the end flag, if the effect is not received, resend it 5 seconds later etc. Not sure what other bugs might happen from such a method though lol.

**Comment by Rihyuh** [comment]
Just experienced the same flee glitch tonight. 7-21-17
9:41pm AZ time (MST) 
Had THF AF feet on, hit flee from T,Canyon to get to the maze faster and it stuck upon zoning into the maze. 
Did not see a bug had been reported, but confirming it happened.
I will refrain myself from running around in circles at lightning speeds, even if its hilarious! ^.^

**Comment by TeoTwawki** [comment]
@LegionDark/gm @LegionDark/thebosses @R3P0FFXI 

So about that whole "immediately" thing because you know, "this is serious"..

_- taps foot -_

😠

**Comment by R3P0FFXI** [comment]
https://github.com/DarkstarProject/darkstar/issues/3944

**Comment by TeoTwawki** [comment]
Fix'd by DSP
