### ISSUE TITLE
Akaso Cloth synthesis with Earth Crystal could not be combined

### ISSUE THREAD

**Issue by kairoffxi** [LegionDark/Issues#1578]
**Date & Time**:  1:00AM PST

**FFXI Client Version (use `/ver`)**: 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  30170707_0

**Character Name**: Kairo

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: THF99/DNC49

**NPC or Monster or item Name**: Akaso Thread x3 + Earth Crystal

**Zone name**: Windurst Woods

**Coordinates (use `$where`)**: X: -33, Y: -1, Z: -117 (227)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: None

**Steps To Reproduce / any other info**: 
Synthesize 3 Akaso Thread with Earth Crystal. Per Raelious, the working recipe uses a Lightning Crystal. 

Filing issue for consideration to update it to match Wiki recipes. https://www.bg-wiki.com/bg/Akaso_Cloth

![kairo_2017 07 22_005550](https://user-images.githubusercontent.com/17520467/28489656-6ff12a3c-6e7c-11e7-9ce8-9370494d2ec9.png)
![kairo_2017 07 22_005558](https://user-images.githubusercontent.com/17520467/28489657-6ff4270a-6e7c-11e7-805e-1f278b5f48c1.png)

**Comment by Raelious** [comment]
`INSERT INTO `synth_recipes` VALUES (3606,1,0,0,0,97,0,0,0,0,0,4099,4242,4027,4027,4027,0,0,0,0,0,4028,4028,4028,4028,1,1,1,1); -- Akaso Cloth (cloth 97) https://www.bg-wiki.com/bg/Akaso_Cloth
`
@R3P0FFXI Fixed. Line 1316
