### ISSUE TITLE
Relic bow animation attack doesnt show xD

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#158]
Date & Time: 7-11-2015
Frequency:All the time.
FFXI Client Version:ver. 30150619_2
Character Name: Itachioax
Race: Hume
Main Job: RNG
Sub Job: SAM
Area & Coordinates:RAWRR?
Party or Solo: party
NPC Name:none
Monster Name: N/A
Multi-boxing? yes
Steps To Reproduce:
1. when im attacking with ra relic bow just move the hands without bow =D

**Comment by TeoTwawki** [comment]
@LegionDark/owners  if it actually does the firing animation but the bow itself is invisible, thats likely a model issue. If it just doesn't act like a bow being fired, then its most likely the type flags.

**Comment by Loki79** [comment]
ill look at this tonight.

**Comment by Loki79** [comment]
What lv relic bow?

**Comment by Loki79** [comment]
fixed the model, assuming its the 99-4 your talking about.  Will go in next restart, if the 99-4 wasnt the one your having an issue with re-open the ticket and specify what lv bow.
