### ISSUE TITLE
Glitched Nation Mission 5-1

### ISSUE THREAD

**Issue by Shortee1** [LegionDark/Issues#1580]
**Date & Time**:  7/22/17  approx 5:45pm EST

**FFXI Client Version (use `/ver`)**:    30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**:  Shortee

**Nation**:  Sandoria

**Job(level)/Sub Job(level)**:  78MNK/38WAR

**NPC or Monster or item Name**:   Archlich Taber'quoan

**Zone name**:  Qu'Bia Arena

**Coordinates (use `$where`)**:  none

**ffxiah.com link (for items issues only)**:  none

**Multi-boxing? (multiple clients on same connection)**:   no

**Steps To Reproduce / any other info**:  We just finsihed Sandy Mission 5-1 and just before the main skele died, I died to aeroga II.  My party killed it and I was unable to raise up and get the cutscene and the key item (burnt seal).  I attempted to try again, couldnt go inside. Talked to all the NPCs over again to make sure. There is no key item in my bag. I relogged, re-invited the partry and still could not start the fight. Now I cannot access the fight for some reason.

**Comment by TeoTwawki** [comment]
So what happened with this, did someone help and not post to the issue report, or did you fine some way to progress in game?
