### ISSUE TITLE
WW Guild Points - HQ Flutes Not Accepted

### ISSUE THREAD

**Issue by aidai7310** [LegionDark/Issues#1581]
**Date & Time**: 
7/23/2017 3:30pm

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Aidai

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
n/a

**NPC or Monster or item Name**: 
Andreas, ww guild

**Zone name**: 
Northern San d'Oria

**Coordinates (use `$where`)**: 
X:-188 Y:11 Z:263 (94)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/17372/flute-1

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
I'm working on woodworking guild points. Andreas asks for a flute. He will accept nq flute but when I trade flute +1 or flute+2, nothing happens. This has happened to me twice but only with the flute. He has accepted other hq items from me.

**Comment by Jessland86** [comment]
Added this to https://github.com/LegionDark/Issues/issues/1608
