### ISSUE TITLE
Expermental Lamia, Did not Recieve Mythic Trial credit

### ISSUE THREAD

**Issue by Garvaunt** [LegionDark/Issues#1582]
**Date & Time**: 2:30pm pst - 5:30pm pst July 23, 2017

**FFXI Client Version (use `/ver`)**: 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170707_0

**Character Name**: Garvaunt

**Nation**: Sandy

**Job(level)/Sub Job(level)**: PLD99/WAR49

**NPC or Monster or item Name**: Experimental Lamia

**Zone name**: Caedarva Mire

**Coordinates (use `$where`)**: Hard to say took awhile to get to the ???

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: N/A. Got my T2 trial for my Burtgang and logged off. Got back on today to start it and did x11 Vellonis then did x11 Verderal's (i think is the NM) then finished with x11 Experimental Lamia's. then when we were finished went to Turn it in and the Moogle gave me the Trial again. wasted 7 hours. Immo looked into it and killed 1 getting me Credit for 1/9. I have no idea as to why i didnt get credit for the others when we were there.

**Comment by TeoTwawki** [comment]
I saw what you said in game. Teo is all seeing.

When you say things like "but nothing will get done anyway" / "even though nothing will get done" it makes me not care. If I hadn't already been talking with another GM looking into this, I wouldn't have even looked. The code for this works perfectly fine, I ***watched*** it increment just like its supposed to. I **do** know the only 2 reasons why it wouldn't count: 

**A)** Multibox variable bug courtesy of DSP's garbage session handling
_or_ 
**B)** User error.

Some additional logging is being added to the trial system to root out future multibox errors and red flag people who didn't remember to clear previous tier at the moogle. Right now the only trial logging was for errors in the code..Which we don't have here causing this issue at this time.

**Comment by TeoTwawki** [comment]
The additional logging will be in the next maintenance,

**Comment by Heepster03** [comment]
So I just read this again and there is something that I'd like to point out. You said that when you did the 11 Experimental Lamia you then traded it and it started the trial over. What actually sound like happened is that you never started the Lamia stage to begin with and then when you thought you finished it and then you officially started it. Alot of people do it. Have to double trade before continuing.

**Comment by Heepster03** [comment]
It's an easy mistake and it happens alot. Just have to make sure that you start the trial or all is for not.
