### ISSUE TITLE
ZM15 The Sealed Shrine

### ISSUE THREAD

**Issue by Zikk420** [LegionDark/Issues#1583]
**Date & Time**:  23/07/2017

**FFXI Client Version (use `/ver`)**:  30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes?

**Character Name**:  Bloodlust

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  PLD?

**NPC or Monster or item Name**:  Gilgamesh?

**Zone name**:  Norg

**Coordinates (use `$where`)**:  x:119 y:-8 z:-11 (255)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**:  Did these 2-3 years ago, may have done divine might as LS event...  Mission log says The sealed shrine  but Gilgamesh not saying anything, no CS in sky and nothing at The Celestial Nexus. I have Shard of Apathy, Arrogance, Cowardice, Envy and Rage KI's.

**Comment by TeoTwawki** [comment]
Solved: CS in norg will fail if player has more Divine Might earrings than expected (Maximum is set in settings.lua)

Apparently at some point in the past a terrible mistake was made enabling players to get unlimited earrings until it was changed.
