### ISSUE TITLE
Aura Steal not absorbing/ dispelling buffs

### ISSUE THREAD

**Issue by Vaneticorum** [LegionDark/Issues#1587]
**Date & Time**: 07/28/17 - 2137 cst 

**FFXI Client Version (use `/ver`)**: 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Vaneticorum

**Nation**: Windurst

**Job(level)/Sub Job(level)**: THF99/DNC49

**NPC or Monster or item Name**: N/A

**Zone name**: Gustav Tunnel

**Coordinates (use `$where`)**: Not sure

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**:  Merit Aura Steal 5/5; Find Bune (because it always has Protect or Shell); Use Steal; Acquire no item because there is not one to steal, yet you will not take any of the buffs either; Repeat every time Steal comes up but you will not ever absorb buffs. Not sure this trait is working because I have tried it in various other situations and have yet to even dispel anything.

**Comment by Jessland86** [comment]
Aura steal is not coded in DSP.

**Comment by EpicTaru** [comment]
https://wiki.dspt.info/index.php/What_Works#Thief - Aura Steal is colored black, meaning that it isn't confirmed to work...but Immo already explained it too.

**Comment by Jessland86** [comment]
For any job if you are unsure if it works or not I have gone thru every single job and removed the job abilities that don't work from our Wiki. http://wiki.legiondark.com/Thief. You can look up every job to see what works and what doesn't.

**Comment by TeoTwawki** [comment]
@Jessland86 old label is deprecated and only exists till we get existing issues onto one or both of the other 2 where appropriate.

![](https://user-images.githubusercontent.com/6871475/28742509-ca99e720-73ff-11e7-96a1-431c5dec4be4.gif)

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/3601
&
https://github.com/DarkstarProject/darkstar/issues/3755

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/411
&
https://github.com/DarkstarProject/darkstar/issues/3755

Edit: linked wrong issue

**Comment by nfaletra** [comment]
```
lua_getglobal(L, CLuaStatusEffect::className);
        lua_pushstring(L, "new");
        lua_gettable(L, -2);
        lua_insert(L, -2);
        lua_pushlightuserdata(L, (void*)PStatusEffect);
        lua_pcall(L, 2, 1, 0);

        delete PStatusEffect;
    }
```
Seems like that delete is getting hit before the data actually processes on the lua side. Trying to use this function and use the return value to add the status effect to a different entity crashes or the data is garbage and fails to work anyway.
