### ISSUE TITLE
Error 3305

### ISSUE THREAD

**Issue by Vaneticorum** [LegionDark/Issues#1589]
**Date & Time**: 7/29/17 - 0829 cst

**FFXI Client Version (use `/ver`)**: 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Vaneticorum

**Nation**: Windurst

**Job(level)/Sub Job(level)**: NIN99/DNC49

**NPC or Monster or item Name**: N/A

**Zone name**: Selbina

**Coordinates (use `$where`)**: Not sure

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: My character has been logged in since I got disconnected last night around 2130 cst.. I was notified by a GM that one of the server admins needs to "unstuck" me. Please assist.

**Comment by Jessland86** [comment]
@TeoTwawki Stuck session.

**Comment by TeoTwawki** [comment]
session nuked
