### ISSUE TITLE
missing stats on reforged relic

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#159]
**Date & Time**: 7/12/2015 1:30pm
**Frequency**: always
**FFXI Client Version**:30150629_2
**Character Name**:Baucant
**Race**: Elvaan
**Main Job**: Thf
**Sub Job**: Dnc
**Area & Coordinates**: all areas
**Party or Solo**: both
**NPC Name**:NA
**Monster Name**: N/A
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**:
all reforge relic armor are missing the "augment stats". Examples that I currently have are hands and feet. The hands are missing the enhance perfect dodge effect where the feet are missing ehanceing assassin's charge effect. I have looked at other peices on people and noticed they to are missing the "augment stats"

https://www.bg-wiki.com/bg/Category:Reforged_Relic_Armor

**Comment by TeoTwawki** [comment]
Because they don't exist yet so we can't place them on the armor yet..
