### ISSUE TITLE
cancel

### ISSUE THREAD

**Issue by benfolka** [LegionDark/Issues#1592]
**Date & Time**: 30/07/17

**FFXI Client Version (use `/ver`)**: current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Sabutay

**Nation**: 

**Job(level)/Sub Job(level)**: 99war/49dnc

**NPC or Monster or item Name**: 

**Zone name**: all

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: Altough i think it is a known issue, Cancel addon still cancels alot of debuffs including charm etc.

**Comment by TeoTwawki** [comment]
yep.

**Comment by Heepster03** [comment]
Cancel is just used to cancel shadows, stoneskin, magic barrier, etc. The stuff that you'd NORMALLY cancel on your own.

**Comment by TeoTwawki** [comment]
have seen how to cancel buffs normally not cancel-able even on retail, long standing known thing

**Comment by benfolka** [comment]
it was a well known old bug but forgotten, i revealed it long time ago on another free server ,had been fixed partially then but not completely.

**Comment by R3P0FFXI** [comment]
@benfolka fix has been submitted to DSP and this will be resolved in forthcoming maint.
