### ISSUE TITLE
Zilart Mission 8 Battlefield

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1594]
**Date & Time**: 07/30/2017 at ~1:40p PST

**FFXI Client Version (use `/ver`)**: 3017070_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Raelious/Melious

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99NIN/49WAR

**NPC or Monster or item Name**: 

**Zone name**: Stellar Fulcrum

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes :(

**Steps To Reproduce / any other info**: 
I went to help a guy with ZM8 mission, and when we went in it capped us at 75(working as intended) BUT also removed all of our SJ's(not intended). Also upon clearing the BC the BC status was removed for this fight.

**Comment by TeoTwawki** [comment]
Fix in DSP already, will have in next maint.

**Comment by Jessland86** [comment]
Issue was taken care of in today's maintenance.
