### ISSUE TITLE
Magian Trial 95>99 not recording 2/3 kills

### ISSUE THREAD

**Issue by Rihyuh** [LegionDark/Issues#1596]
**Date & Time**: 
8-1-2017 7:44pm MST

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Furrow

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
THF99/DNC49

**NPC or Monster or item Name**: 
Hydra & Cerberus
(Both did not record kills, but Medusa did, currently 1/9)

**Zone name**: 
Mount Zhayolm & Wajaom Woodlands

**Coordinates (use `$where`)**: 
 X: 316, Y: -23, Z: -84 cerberus
 X: -282, Y: -24, Z: -1 hydra

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Kill Hydra/Cerberus
Medusa kill credited 1/9, but Cerberus/Hydra did not count
Garvaunt also killed Medusa/Cerberus/Hydra with me, did count 3/9
***8-1-2017 8:55pm MST killed Medusa, recorded kill 2/9 now***

**Comment by Heepster03** [comment]
Was your weapon equipped? It's so easy to forget to equip weapon for the killshot.

**Comment by Rihyuh** [comment]
I hit the mobs once with TK, then hit my macro immed. to build tp for the rest of the fight with the Vajra in the offhand. Worked for Medusa twice, but not the other 2. It did record for Garv on his Burtang

**Comment by R3P0FFXI** [comment]
@Rihyuh the weapon needs to be equipped for the kill, you cannot hit 1x then unequip the weapon needs to be there for the final killshot.

**Comment by TeoTwawki** [comment]
@Rihyuh from discord, I guess you were gone by the time I asked:
```[1:08 AM] Teo/[GM]Sarda: 2 modems?! #ffxihardcoremode
[1:08 AM] Teo/[GM]Sarda: am out atm will look into recent tickets when i get home
[1:09 AM] Teo/[GM]Sarda: you had weapon on when it died yeah? it works by at time of death not by registering being hit by it
```

**Comment by Rihyuh** [comment]
Teo, i found my own answer. /lockstyle on. Even though it appears the mythic is equipped visually, it was another dagger, b/c i can find no other reason for it. 
Can i delete this ticket so you dont go on a witch hunt and think the code is broken?

**Comment by TeoTwawki** [comment]
TY for letting me know! I'm going to later see if I check for and warn the player of locked style in these situations
