### ISSUE TITLE
problems popping Khalkotaur abyss vunker

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#1597]
Date & Time: 02/08/2017

FFXI Client Version (use /ver): 30170707_0

Server's Expected Client Version matches, yes

Character Name: Itachioax

Nation: Sandoria

Job(level)/Sub Job(level): THF/DNC

NPC or Monster or item Name: Khalkotaur

Zone name: Abyssea Vunkerl inlet

Coordinates (use $where): X:-243 Y:-40 Z:-114(29)

ffxiah.com link (for items issues only):

Multi-boxing? Yes

Steps To Reproduce / any other info:

signals (???) doesnt show up near of bush, i found another signals and tried trade there the pop item, but doesnt work

**Comment by Heepster03** [comment]
??? Aren't near the bush cause that's not how it's supposed to be. It's around the mountain towards the bats. Once you click on the ??? If it's the right one then it'll tell you what item to trade.

**Comment by Jessland86** [comment]
??? is in the spot described by Heep. Spawned Khalk via ??? and pop item, confirmed working. This is where the ??? is located at.
![untitled](https://user-images.githubusercontent.com/28382433/28888107-64f6af5c-778d-11e7-8184-f25e6a5a2aff.png)
