### ISSUE TITLE
Mog House Moogle unresponsive

### ISSUE THREAD

**Issue by stevomatic** [LegionDark/Issues#1598]
**Date & Time**: 4:46pm 8/2/17

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

yes
**Character Name**: 

Agnes
**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
rng/war

**NPC or Monster or item Name**: 

Moogle
**Zone name**: 

Mog House , any of them I've tried
**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
Can't interact with moogle, can access mog house tasks if I menu up mog house with keyboard. The other day I did some stuff with Prishe and Renik, while I was in upper jeuno I did some rearranging of inventory and the moogle there i recall was giving me homepoint crystal type messages.  Happens to my other characters as well now

**Comment by Jessland86** [comment]
The mog house functions through the menu do work correctly at this time. It is only the moogle that is not working.

**Comment by Jessland86** [comment]
https://github.com/DarkstarProject/darkstar/issues/3956

**Comment by Jessland86** [comment]
Issue was taken care of in today's maintenance.
