### ISSUE TITLE
Bastock 2-3 Windurst to Sandy

### ISSUE THREAD

**Issue by Valknut4** [LegionDark/Issues#160]
**Date & Time**:  3:52 pm MST 7/12/2015
**Frequency**: N/A
**FFXI Client Version**:9576fe706eb79f11e5fd851242469028ea8ea17d
**Character Name**: Agni
**Race**: Elvaan
**Main Job**: Paladin
**Sub Job**: Warrior
**Area & Coordinates**: X: 37 Y: -2 Z :-4
**Party or Solo**: Party
**NPC Name**: Baraka
**Monster Name**: N/A
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**: Finish Windurst side of the chain, and instead of talking to Helaku, talk to Baraka,. It will trigger a CS with Lion which I assume is the first CS of the Sandoria to Windurst side of Bastock 2-3. Talking to Halver Helaku or Meleka (Windurst) does nothing.

**Comment by TeoTwawki** [comment]
Related DSP issue : https://github.com/DarkstarProject/darkstar/issues/285

**Comment by TeoTwawki** [comment]
@Loki79 when you get a chance can you find the next NPC he should visit and set his `MissionStatus` variable to what that NPC expects?

**Comment by Valknut4** [comment]
Apologies, I had heard about the 2-3 mission bug. Followed peoples advice the best I could, but still bugger'd it up. Thanks for in advance for the help guys.

**Comment by Loki79** [comment]
This still going on or has it been resolved?

**Comment by Valknut4** [comment]
Still going on Helaku still won't prompt the next stage of the quest ^^;

**Comment by TeoTwawki** [comment]
> when you get a chance can you find the next NPC he should visit and set his MissionStatus variable to what that NPC expects?

@Loki79 I assume he stills needs that done and I can't get on game to do it and thus far every time I ask R3 to do these things he winds up doing something other than look up what the NPC actually expects..

**Comment by Loki79** [comment]
I'm NEVER on the server, I cannot monitor when players are or are not on.  If this still needs to be addressed I can be found in IRC most days.  I will say however i see no reason 3p0 cant get off his ass and actually do something, anything to help.  I have about reached my limit of accepting laziness and excuses.

**Comment by TeoTwawki** [comment]
> Character Name: Agni

@Valknut4 R3P0FFXI just informed me no character named "Agni" exists in the database..Can you tell me WTF is wrong here?

**Comment by R3P0FFXI** [comment]
Character Name: Agni does not exist on server according to Server tools on website or database, please contact with correct info

**Comment by TeoTwawki** [comment]
@Loki79  @R3P0FFXI I like, need to keep you two away from each other for awhile. And we need more GM's that we can trust with FULL GM command access.

**Comment by Loki79** [comment]
Working with both Sami and Strafeous on item based stuff and both want to learn more.   I know Sami has had GM exp on FW.  Strafeous wants to learn and help out as much as possible.  I just need to block out the time to talk to them and teach them.

**Comment by Valknut4** [comment]
Deleted character, fell to far behind and multiboxing is causing me DC's and quest issues so I'm cutting back this account.
