### ISSUE TITLE
Mission 2-3 won't progress, i have the key item.

### ISSUE THREAD

**Issue by Sifrid** [LegionDark/Issues#1600]
**Date & Time**: 
12:35 AM EST 8/4/2017

**FFXI Client Version (use `/ver`)**: 
301707o7_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes.

**Character Name**: 
Sifrid

**Nation**: 
San d'Oria, Bastok

**Job(level)/Sub Job(level)**: 
50RDM/25WAR

**NPC or Monster or item Name**: 
Savae E Paleade, Halver, Grilau

**Zone name**: 
Bastok, San d'oria

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
    *Talked to the gate guard named "Grilau" to obtain this mission. 
    *Spoke to the NPC  Halver in Chateau d'Oraguille to receive a KeyItemLetter to the Consuls.
    * i went to the Consulate of San d'Oria in the Metalworks at (I-9) on the second floor and speak to Savae E Paleade for a cutscene, but there was no cutscene.

**Comment by Heepster03** [comment]
Were you dualboxing?

**Comment by Sifrid** [comment]
Negitive.

**Comment by Jessland86** [comment]
Handled by GM in game.
