### ISSUE TITLE
ZM8 - "Return to Delkfutt's Tower" Fight

### ISSUE THREAD

**Issue by kyokofu** [LegionDark/Issues#1601]
**Date & Time**: 
8/3/2017 10:44 pdt

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
YES

**Character Name**: 
Kyoko Fukada

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99THF/49BLM

**NPC or Monster or item Name**: 
Stellar Fulcrum Fight for mission ZM8

**Zone name**: 
Stellar Fulcrum

**Coordinates (use `$where`)**: 
X: -519 Y: -4 Z: 18 (51)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
YES

**Steps To Reproduce / any other info**: 
Inserted the fragments and then went to talk to Aldo for cs. When touching the Qe'lov Gate in Stellar Fulcrum, nothing happens.

**Comment by Raelious** [comment]
Go attempt to try and reenter the fight, multiboxing may have caused an issue. If you cant re-enter ZM8 report back here.

**Comment by kyokofu** [comment]
was following the gide on bg. It said nothing about a cs in lower delkfutt but it seems that it was needed.
