### ISSUE TITLE
items didnt drop in inventory in bcnm

### ISSUE THREAD

**Issue by hadouken420** [LegionDark/Issues#1602]
**Date & Time**: 8/4/2017 4:20 pm est

**FFXI Client Version (use `/ver`)**: 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170707_0

**Character Name**: Kula

**Nation**: Sandoria

**Job(level)/Sub Job(level)**40 blu/nin

**NPC or Monster or item Name**: Compound eyes

**Zone name**: Horlais peak

**Coordinates (use `$where`)**: x;-503 y;158 z;212 (9)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: completed Under Observation
 but items didnt drop in my inventory! 

![1](https://user-images.githubusercontent.com/30205630/28985996-1f810574-7933-11e7-8c1c-29e17f2c1362.png)

Edit by Teo: converted link to in post image type

**Comment by Jessland86** [comment]
According to your Screenshot you zoned. Items drop to the treasure pool, not your inventory.

**Comment by TeoTwawki** [comment]
Ouch, that sucks, but you zoned before items could exit pool and reach inventory.
