### ISSUE TITLE
sandy mission jerney abrourd, bastok part 1

### ISSUE THREAD

**Issue by greysongrey** [LegionDark/Issues#1604]
**Date & Time**: 
sunday 6th aug, 2017

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 
Greyson

**Nation**: 
sandy

**Job(level)/Sub Job(level)**: 
red 12/monk 6
monk27/red12
**NPC or Monster or item Name**: 
savae e Paleade

**Zone name**: 
bastock

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
i have spent 10 hours retracing step's of this mission spoke to all npc i should do he will not exept my trade

 Trying to trade mytral sands to savae e paleade have been over and over mission for hours now respoke to every 1 i should and that give's me infomation on quest but still cant trade the sands please help

**Comment by greysongrey** [comment]
I'll be logging on at 6.30pm UK time tonight hopefully we can sort this with a Gm then.

**Comment by Raelious** [comment]
I went through every step twice with Greyson. He is stuck on the following this, all of the other NPCs are giving him the appropriate dialog till then.

```Return to Metalworks and trade the Mythril Sand to Savae E Paleade to complete this portion of the mission.```

I had him skip that step and see if he somehow completed it without knowing, and the Windust branch wont have anything to do with him. Then had him try Halver again to try and restart the mission somehow, and Halver is nonresponsive.

He does have the Mythril Sand (ID: 599) in his inventory as well.

**Comment by greysongrey** [comment]
Solve by raina in game retraced all stepped restarted  mission and now all sorted thank you so much ☺
