### ISSUE TITLE
Unable to start BLU artifact armor quest (Omens)

### ISSUE THREAD

**Issue by mikeffxi** [LegionDark/Issues#1605]
**Date & Time**: 
8/6/2017, 6:38PM Eastern Time

**FFXI Client Version (use `/ver`)**: 
version 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Miike (with 2 i's)

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
Blue mage (70)/Dancer (35)

**NPC or Monster or item Name**: 
Waoud

**Zone name**: 
Aht Urhgan Whitegate

**Coordinates (use `$where`)**: 
X:66 Y:-6 Z:-77 (101)

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
I have a 2nd account, but I was not using it at the time

**Steps To Reproduce / any other info**: 
Finish BLU artifact weapon quest (Beginnings), zone, wait one game-day, zone back, try to start the armor quest (Omens), quest will not start. NPC says he is pondering the mysteries of the universe, but will not give quest. Double checked to make sure the previous quest (Beginnings) was marked as complete, and it was. Also checked to make sure that I had the artifact weapon in my inventory, and I do. According to the FFXI wiki (http://ffxiclopedia.wikia.com/wiki/Omens) the only requirements are to be over level 50, and to have completed the prior quest (Beginnings) and I have both of those requirements but the quest will not start. Not sure if this is a bug or if I just missed something, but any help would be appreciated. Thanks!

![miike_2017 08 06_183524](https://user-images.githubusercontent.com/30783579/29007781-c341d02a-7ad8-11e7-8b26-21da2ae8807e.png)
![miike_2017 08 06_183546](https://user-images.githubusercontent.com/30783579/29007784-c8c3feba-7ad8-11e7-9133-5d51b395dcce.png)

**Comment by TeoTwawki** [comment]
https://wiki.dspt.info/index.php/What_Works#Blue_Mage
doesn't even exist yet in DSP.

**Comment by Raelious** [comment]
You can pick up all of the AF gear from an NPC near the Mog House in Lower Jueno for 500g.

**Comment by mikeffxi** [comment]
Oh, I didnt know that! I saw other people wearing it so I assumed they had done the quest for it. Ill go do that, thanks for your responses

**Comment by TeoTwawki** [comment]
np :)

**Comment by Jessland86** [comment]
http://wiki.legiondark.com/AF_storage_NPC for future reference. It's not just the one in Jeuno @Raelious

**Comment by TeoTwawki** [comment]
Ya know, the existence of that page would make a lot more sense if it described the customization done to those NPC's instead of giving the same info that's on retail. 😞
