### ISSUE TITLE
Gjallarhorn 18840 Missing stats

### ISSUE THREAD

**Issue by Jessland86** [LegionDark/Issues#1607]
**Date & Time**: 
08/06/2017 2210

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99BRD

**NPC or Monster or item Name**: 
Gjallarhorn

**Zone name**: 
n/a

**Coordinates (use `$where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
http://legiondark.com/db/items/18840

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
Item 18840 Missing the following mods:
(14): CHR +10
(119): Singing Magic Skill +25
(121): Wind Magic Skill +25

**Comment by Raelious** [comment]
Will be fixed in tomorrows maint
