### ISSUE TITLE
Unable to connect to World Server

### ISSUE THREAD

**Issue by Vashelstampede** [LegionDark/Issues#161]
**Date & Time**: 7/12/2015 11:57PM EST
**Frequency**: First time
**FFXI Client Version**: 30150629_2
**Character Name**: Vashel
**Race**: Hume
**Main Job**: BLU
**Sub Job**: DNC
**Area & Coordinates**: Lower Delkfutt's Tower, Second Floor (H-10)
**Party or Solo**: Solo
**NPC Name**: n/a
**Monster Name**: n/a
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Website says server is up and people are logged on. I was kicked out of the game and every time I try to log back in I get "Error code: FFXI-3305 Unable to connect to world server. Specified operation failed."

**Comment by NononoA** [comment]
Same here. Current online player is showing me up but I already got kick and could not login again with could not connect server (time out).

**Comment by itachioax** [comment]
same here,

**Comment by TeoTwawki** [comment]
restarted it, should work in about 3-5 min..Heap got corrupted which prevented the auto restart form happening so I had to remote in.

**Comment by NononoA** [comment]
Can't login again.

**Comment by TeoTwawki** [comment]
@NononoA  Over the last 24hrs we had a crash type the auto restart was unable to handle (the server code was calling invalid stuff in the C++ library) this is now resolved

**Comment by TeoTwawki** [comment]
Anyone still unable to log in should create a new issue or contact us on IRC.
