### ISSUE TITLE
Lost x2 Seiryu seals Due to Server Crash

### ISSUE THREAD

**Issue by Garvaunt** [LegionDark/Issues#1611]
**Date & Time**: 8/13/2017 2:55pm PST

**FFXI Client Version (use `/ver`)**: 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170707_0

**Character Name**: Garvaunt

**Nation**:  Sandy

**Job(level)/Sub Job(level)**: PLD99/WAR49

**NPC or Monster or item Name**: Seiryu

**Zone name**: Ru'uan Gardens

**Coordinates (use `$where`)**: X566 Y-70 Z-76

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: None.

Killed seiryu and Server crashed, lost our drops and 2 Seals. heres the Screenshot.
https://gyazo.com/980778c5f9b642f0fb13338e6122fa56

**Comment by R3P0FFXI** [comment]
@Garvaunt we do not replace drops due to server crash. This has been a long standing policy on the server,
