### ISSUE TITLE
Leaden Salute missing From COR Mythic LVL99 Death Penalty

### ISSUE THREAD

**Issue by xrocksterx** [LegionDark/Issues#1613]
**Date & Time**: 8/17/2017 6pm

**FFXI Client Version (use `/ver`)**: 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Iroha

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: 99cor/49dnc

**NPC or Monster or item Name**: Lvl 99 Death Penalty

**Zone name**: North Sandy

**Coordinates (use `$where`)**: X67 Y:0 Z:9 (252)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/19835/death-penalty

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: Upgraded from 95 to 99 Death Penalty and it's missing the weapon skill Leaden Salute. Re-equipped, zoned, no change. Leaden Salute is not usable via /leadensalute nor is it in the ws list. Lvl 95 had it.

**Comment by Raelious** [comment]
Will be fixed in tomorows update
