### ISSUE TITLE
Prishe not taking reforge trade

### ISSUE THREAD

**Issue by stevomatic** [LegionDark/Issues#1615]
**Date & Time**: 
8/18/17

**FFXI Client Version (use `/ver`)**: 30170707_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:
yes

**Character Name**: Gunt

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99blm/rdm

**NPC or Monster or item Name**: 
prishe

**Zone name**:Abyssea Empyreal Paradox

**Coordinates (use `$where`)**: 538 -500 -591 (129)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
With prerequisites met, 3 lunars 9 bosses and shinryu, no response from prishe trading goetia petaos +2 and 30 itzpaplotl scales to get reforge wicce petasos. no sort of error message either

**Comment by Jessland86** [comment]
Gave myself the items and tested, without the requirements it gives the error of needing the titles/lunars. With the titles and lunars it gives no error and does not accept the trade.

**Comment by TeoTwawki** [comment]
@R3P0FFXI https://github.com/LegionDark/Issues/search?q=Prishe+&type=Issues&utf8=%E2%9C%93

**Comment by Jessland86** [comment]
https://github.com/LegionDark/Issues/issues/719

**Comment by Jessland86** [comment]
https://github.com/LegionDark/Issues/issues/1319

**Comment by stevomatic** [comment]
Would it be possible to find out if Prishe will take the remaining pieces of the Goetia set while this issue i open?

**Comment by Jessland86** [comment]
@stevomatic the remaining BLM Empy is fine with Prishe. I will catch up with you in game to get this hat taken care of as a temporary work around.

**Comment by stevomatic** [comment]
![gunt](https://user-images.githubusercontent.com/26309049/30230150-102bb678-94b3-11e7-97f6-6cf53f12092e.jpg)

**Comment by Jessland86** [comment]
Gunt taken care of by GM in game. The base issue of it looking for the wrong items still needs to be addressed.
