### ISSUE TITLE
Level Sync lost immediately after 1 Kill while Multiboxing in Alliance

### ISSUE THREAD

**Issue by kairoffxi** [LegionDark/Issues#1616]
**Date & Time**: 
08/18/2017 6:54 PST

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30170707_0

**Character Name**: 
Kairo

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
RDM77/WHM39

**NPC or Monster or item Name**: 
Bloodsucker

**Zone name**: 
Bostaunieux Oubliette

**Coordinates (use `$where`)**: 
Left area already but by grounds tome and Bloodsuckers down stairs

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Multiboxing with 5 alts (total 6). 
Also in Alliance with one other level synced party.
Level syncing to certain alts reproduced the problem. 
Some alts didn't lose sync but two alts in a row caused sync to be lost immediately after 1st kill.
Selecting a 3rd alt didnt lose the sync.

![sync1](https://user-images.githubusercontent.com/17520467/29482638-1bf63010-844a-11e7-9e9a-a45277ab25da.png)
Kind of hard to tell from screenshots but if you see the timestamps, level sync was set here at 18:46:01.

![sync2](https://user-images.githubusercontent.com/17520467/29482639-1bf6707a-844a-11e7-9820-fb2d9df5c3b4.png)
Level sync is lost at 18:46:37, 37 seconds later on the first kill after level sync was set.

**Comment by Raelious** [comment]
I see you sync'd to level 70, has that character beaten Maat and broken the level70 cap?

**Comment by kairoffxi** [comment]
You are right, the synced players have all not beaten Maat and broken their level 70 cap.

**Comment by Raelious** [comment]
No problem, sorry for the confusion. :)

**Comment by kairoffxi** [comment]
Thank you for recognizing what the problem was. I've updated the [New Player Guide](http://wiki.legiondark.com/New_Player_Guide#Why_did_my_party_lose_level_sync.3F) in case any other players come across this.

**Comment by TeoTwawki** [comment]
In retail if you sync with a person at their max level (need to clear limit break quest) this happens to.
