### ISSUE TITLE
Af3 upgrade mog won't take item

### ISSUE THREAD

**Issue by salazer** [LegionDark/Issues#1618]
**Date & Time**: 8/24/17 10:40 est

**FFXI Client Version (use `/ver`)**: 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: soap

**Nation**: Bastok

**Job(level)/Sub Job(level)**: blue99/rdm49

**NPC or Monster or item Name**: af3 upgrade mog

**Zone name**: port Jeuno

**Coordinates (use `$where`)**: H-8

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: I tried to trade my Mavi Buzuband +1 and 6 coin's of wieldance to mog nothing happens logged off logged in tried again nothin i zoned and rezoned still nothing

**Comment by Heepster03** [comment]
That moogle is for reforging. You need to use the moogle in Port Jeuno by the Abyssea NPCs.

**Comment by EpicTaru** [comment]
Which moogle exactly were you trading to?  The one near the stairwell down to the AH in Port Jeuno or the one next to Jaochim?
