### ISSUE TITLE
The alliance server crashing glitch

### ISSUE THREAD

**Issue by Strafeous** [LegionDark/Issues#162]
**Date & Time**:  4:30 7/13/2015
**Frequency**: Only when we try to form an alliance at the same time
**FFXI Client Version**: Current
**Character Name**: Strafeous
**Race**: Elvaan
**Main Job**: WAR
**Sub Job**: SAM
**Area & Coordinates**: Whitegare
**Party or Solo**: Alliance
**NPC Name**: N/A
**Monster Name**: N/a
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**:
The problem is when someone forms an alliance at the same time, then both parties accept. It's as easy as that.
We would accidentally alliance each other at the same time and we'd both accept accept. It would break the alliance, and we'd try to dissolve it and fix it and it would crash.

**Comment by TeoTwawki** [comment]
@R3P0FFXI forward to DSP

**Comment by TeoTwawki** [comment]
@Strafeous Is this likely what caused #161 ?

**Comment by R3P0FFXI** [comment]
@Strafeous in the future you need to put the actual client version as shown by /ver in the client

https://github.com/DarkstarProject/darkstar/issues/1720

**Comment by Strafeous** [comment]
Sorry I wasn't able to log on at the time, the version is 30150619_2

**Comment by Strafeous** [comment]
I wasn't online during #161, so it's possible but it wasn't me

**Comment by TeoTwawki** [comment]
Will create new issue if we can reproduce this again after legion server update is done.
