### ISSUE TITLE
Ironclad Pulverizer same loot as observer

### ISSUE THREAD

**Issue by crazcracker** [LegionDark/Issues#1620]
**Date & Time**: 8/27/2017

**FFXI Client Version (use `/ver`)**: 30170728_2

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170707_0

**Character Name**: Cbolt

**Nation**: San d oria

**Job(level)/Sub Job(level)**:  Blu99/Thf49

**NPC or Monster or item Name**: Ironclad Pulverizer

**Zone name**: aby-mis

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: Popped multiple times same issue. It was dropping same items as observers there.

**Comment by Jessland86** [comment]
https://github.com/LegionDark/Issues/issues/1530
