### ISSUE TITLE
Unable to Launch Game; Failed to Initialize Instance of IPOLCoreCom

### ISSUE THREAD

**Issue by pacpac1997** [LegionDark/Issues#1621]
**Date & Time**: 8/28/17

**FFXI Client Version (use `/ver`)**: Fresh Install

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Not Sure

**Character Name**: N/A

**Nation**:  N/A

**Job(level)/Sub Job(level)**:  N/A

**NPC or Monster or item Name**:  N/A

**Zone name**: N/A

**Coordinates (use `$where`)**: N/A 

**ffxiah.com link (for items issues only)**: N/A 

**Multi-boxing? (multiple clients on same connection)**: No 

**Steps To Reproduce / any other info**: Not sure how to reproduce this
![ipolcorecom](https://user-images.githubusercontent.com/31407783/29772801-3364db36-8baf-11e7-889a-f9ce9237c3ba.png)

**Comment by R3P0FFXI** [comment]
@pacpac1997 this is not a legion issue this is something on your end not setup correctly
