### ISSUE TITLE
Ouryu Fight (CoP - The Savage)

### ISSUE THREAD

**Issue by Celticyheti** [LegionDark/Issues#1623]
**Date & Time**: 9-2-17@ 2209 hrs EST

**FFXI Client Version (use `/ver`)**: 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Andromida and Hornswoggle

**Nation**: Bastok

**Job(level)/Sub Job(level)**: WHM/RDM and BRD/DNC

**NPC or Monster or item Name**: Ouryu Fight (CoP - The Savage)

**Zone name**: Monarch Linn

**Coordinates (use `$where`)**: X:-34 Y:-1 Z-538 (238)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**:  Entered the Fight with Main and alts. Defeated Ouryu and my Main (Mike) got a CS. The CS was skipped for both my alts. My alts got credit for the fight and got the title but skipped the CS and now can't progress. I have attempted to re-enter the Spatial Displacement to do the fight over to get the CS but I am getting text that reads, "A glowing mist of ever-changing proportions floats before you..." I have tried to retrace all my steps leading up to the fight and all three toons did everything. Attempts to get the following CS from Justinius are futile. Need to find away to reset the Mission or redo the fight to progress further.

**Comment by Celticyheti** [comment]
Has anyone had a chance to look into this yet? I know you are busy but I can not progress into CoP missions unless Mission is reset or I have access to the CS. Any help would be appreciated, Thanks.

**Comment by TeoTwawki** [comment]
Sorry no, someone will post here when there is an update for you.

**Comment by Raelious** [comment]
@Celticyheti I checked yours vars for these missions and they are set to 0, you will need to log off each character and go get them separately (more then likely). Message me in game, can help sort it out more.

**Comment by Raelious** [comment]
Issue was resolved.
