### ISSUE TITLE
Iga Kyahan +2 shadow overwriting issue.

### ISSUE THREAD

**Issue by Stealthsoft** [LegionDark/Issues#1624]
**Date & Time**:  1:28AM CST 9/5/2017

**FFXI Client Version (use `/ver`)**: 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 30170707_0

**Character Name**: Graice

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99NIN/WAR

**NPC or Monster or item Name**: Iga Kyahan +2

**Zone name**: Korroloka Tunnel

**Coordinates (use `$where`)**: X-300 Y-9 Z-190 (72)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/11156/iga-kyahan-2

**Multi-boxing? (multiple clients on same connection)**: Yes (also tried while not multi-boxing)

**Steps To Reproduce / any other info**: Iga Kyahan give an extra Utsusemi shadow, but while they're equipped Utsusemi: Ni can no longer override other Utsusemi: Ni shadows. It gives a response as if you were attempting to override Utsusemi: Ni shadows with Utsusemi: Ichi (i.e. Graice's Utsusemi: Ni had no effect on Graice).

I unequipped the boots and it went back to functioning normally.

**Comment by TeoTwawki** [comment]
#1586

**Comment by Stealthsoft** [comment]
Ah searched the wrong keywords. Sorry.
