### ISSUE TITLE
Bismuth Sheet disappeared, now cannot craft Shabti Cuisses

### ISSUE THREAD

**Issue by kairoffxi** [LegionDark/Issues#1625]
**Date & Time**: 
9/6/2017

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
30170707_0

**Character Name**: 
Kairo

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
THF99/DNC49

**NPC or Monster or item Name**: 
none

**Zone name**: 

**Coordinates (use `$where`)**: 
X _104 Y 2 Z 21

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/4095/bismuth-sheet

**Multi-boxing? (multiple clients on same connection)**: 
crafting at the time but yes alts were loaded

**Steps To Reproduce / any other info**: 
I was crafting Shabti Cuisses for Stealth.
First craft successfully crafted Shabti Cuisses.
Then I noticed the 2nd Bismuth sheet I had crafted was missing??
Weird but ok. I pull 2 Bismuth ores from mog house and make a new ingot, then Bismuth sheet.
Try to craft Shabti Cuisses, cannot combine these materials.
Try to trade these items back to Stealth, no can do.
Try other items and gil, these work. I can trade other items or gil to Stealth.
Cannot trade the 1 gold ingot, 1 ram leather or 1 bismuth sheet to Stealth.
Cannot craft Shabti Cuisses.
{I dont understand}! /help!

Moved gold ingot, ram leather and bismuth sheet into mog safe.

**Comment by Jessland86** [comment]
You need to zone to unlock the crafting materials.

**Comment by Jessland86** [comment]
https://github.com/LegionDark/Issues/issues/1143

**Comment by Jessland86** [comment]
I just tested and confirmed that you can craft these. using
```
Fire Crystal
Gold Ingot x1
Ram Leather x1
Bismuth Sheet x2
```

**Comment by kairoffxi** [comment]
Okay tried to zone and logout to see if the recipe would work. Still seems to be failing.

![kairo_2017 09 07_232009](https://user-images.githubusercontent.com/17520467/30198578-48957f02-9423-11e7-8df0-5a67da1b66e1.png)

![kairo_2017 09 07_232014](https://user-images.githubusercontent.com/17520467/30198577-489070a2-9423-11e7-91d8-7a365c99580c.png)

**Comment by TeoTwawki** [comment]
Your screenshot show 1 sheet. Jessland86's last post indicated 2 are required per synth.

**Comment by kairoffxi** [comment]
Ohh jeez, that explains everything including my "disappearing" sheet. Feeling foolish comment the other day really resonating now. Sorry to waste your time. I'm sure that's what the issue was now.

**Comment by TeoTwawki** [comment]
no prob glad its sorted
