### ISSUE TITLE
Croque-mitaine wrong model ID and not a NM.

### ISSUE THREAD

**Issue by Jessland86** [LegionDark/Issues#1627]
**Date & Time**: 
09/08/2017 1537EDT

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
n/a

**Job(level)/Sub Job(level)**: 
n/a

**NPC or Monster or item Name**: 
Croque-mitaine

**Zone name**: 
Passhow Marshlands [s]

**Coordinates (use `$where`)**: 
253.724, 24.558, -25.205

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
Mob /checks as Incredibly Tough, and has the model of a Piestie when it should be a Goubbue. Uses the correct Gobbue TP moves.

**Comment by TeoTwawki** [comment]
The heck. I know I already did this.  #1177 how is it wrong again! 😠

**Comment by TeoTwawki** [comment]
@R3P0FFXI check the custom stuff, compare with the darkstar stuff

**Comment by Jessland86** [comment]
Well it has the right TP moves this time, but now the other stuff with it is wrong lol.

**Comment by R3P0FFXI** [comment]
@TeoTwawki Croque-Mitaine is commented out of the custom mob pools list.

Custom commented out
`-- REPLACE INTO `mob_pools` VALUES (4681,'Croque-Mitaine','Croque-Mitaine',136,0x0000280100000000000000000000000000000000,6,1,7,240,100,0,1,0,0,2,23,0,1,131,0,0,0,1,0,136);`

DSP Currently in
`INSERT INTO `mob_pools` VALUES (4681,'Croque-Mitaine','Croque-Mitaine',136,0x0000DF0700000000000000000000000000000000,1,1,7,240,100,0,1,0,0,0,0,0,1,131,0,0,0,1,0,136);`

**Comment by TeoTwawki** [comment]
@R3P0FFXI 
THREE backticks, nto 1, and a language identifier.
