### ISSUE TITLE
Muq Shabeel not spawning

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#1629]
Date & Time: 9/8/2017

FFXI Client Version (use /ver): 30170707_0

Server's Expected Client Version matches, no

Character Name: Itachioax

Nation: Sandy

Job(level)/Sub Job(level): thf99/dnc49

NPC or Monster or item Name: Muq Shabeel

Zone name: Meriphataud Mountains (S)

Coordinates (use $where): X:582 Y:-31 Z:593(238)

ffxiah.com link (for items issues only):

Multi-boxing? (multiple clients on same connection): yes

Steps To Reproduce / any other info: 

it just not spawn, its an aptant NM, i already camped him for 7 days and never seen him up

**Comment by Jessland86** [comment]
https://github.com/LegionDark/Issues/issues/1497
