### ISSUE TITLE
San'Doria mission 5-1 Fei'yin not granting title

### ISSUE THREAD

**Issue by Scarier** [LegionDark/Issues#163]
**Date & Time**:   7/14/2015 - 7:30AM PST
**Frequency**:  2x 
**FFXI Client Version**: current
**Character Name**: Scary
**Race**: Galka
**Main Job**: PLD
**Sub Job**: WAR
**Area & Coordinates**: Qu'Bia arena BCNM mission 5-1
**Party or Solo**: Party
**NPC Name**: 
**Monster Name**:
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**:  Fought mission bcnm 2x, cannot get burnt seal and Archmage Assassin title.

Everyone in the party received title, but I'm without one and it won't let me complete the mission nor advance to The Shadow Lord.

**Comment by R3P0FFXI** [comment]
Are you dual boxing?

**Comment by Scarier** [comment]
Yes, if that is the issue

**Comment by R3P0FFXI** [comment]
Yes dual boxing causes issues from time to time. Try it again with no dual boxing and see if it resolves your issue.

**Comment by Scarier** [comment]
I'll do that thanks

**Comment by TeoTwawki** [comment]
> Character Name: Scary
> Race: Galka

**SCARY GALKA!**  -*runs away*-

**Comment by Scarier** [comment]
Hi guys,

I've tried this again and no luck. Halver won't talk to me, I have the new
feiyin seal to enter bcnm, but after the Zeid cutscene, i'm not awarded
with burnt seal.

**Comment by Scarier** [comment]
ok it took 5 fights but i finally got it, thanks!
