### ISSUE TITLE
Character Stuck

### ISSUE THREAD

**Issue by Lavrik83** [LegionDark/Issues#1630]
**Date & Time**: 
9/9/17  3:07pm EST

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Lav

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
99WHM/49RDM

**NPC or Monster or item Name**: 

**Zone name**: 
Northern San d'Oria

**Coordinates (use `$where`)**: 
~ X:67 Y:0 Z:23 (231)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Got stuck when server crashed a few nights ago.  Says she is logged in but not physically there and I cannot log into that account.

**Comment by Jessland86** [comment]
@TeoTwawki will unstuck your session when he gets back online.

**Comment by Lavrik83** [comment]
Thanks for fixing!
