### ISSUE TITLE
Can't enter Darkness Named BC

### ISSUE THREAD

**Issue by crazcracker** [LegionDark/Issues#1631]
**Date & Time**: 9-13-17

**FFXI Client Version (use `/ver`)**: 30170728_2

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: no 

**Character Name**: Cbolt and Zewski

**Nation**: Sandy

**Job(level)/Sub Job(level)**: 99blu/49war and 99rdm/49whm

**NPC or Monster or item Name**: http://ffxiclopedia.wikia.com/wiki/Darkness_Named

**Zone name**: The Shrouded Maw

**Coordinates (use `$where`)**:  X:-300 Y:-2 Z:-259

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**:  Clicking on memento circle to enter BC does nothing. Mission log shows correct mission, talked to npc's again, have pso'xja pass, and logged in/out.

**Comment by Raelious** [comment]
Was a Multibox issue, taken care of ingame. If anything else persists just let me know.
