### ISSUE TITLE
Three NMs that do not check as NMs.

### ISSUE THREAD

**Issue by Jessland86** [LegionDark/Issues#1632]
**Date & Time**: 
09/13/2017 0100 EDT

**FFXI Client Version (use `/ver`)**: 
30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99SomethingOrtheOther/49ProbablySomethingElse

**NPC or Monster or item Name**: 
Garhorlur the Brutal
Garfurlar the Rabid
Garharlor the Unruly

**Zone name**: 
Mount Zayolm

**Coordinates (use `$where`)**: 
99, -13, 1

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
Mobs do not check as NM's. Only supposed to be up during beseiged, but that's a whole other issue as it's lolbeseiged. But they should still be nm's.

http://ffxiclopedia.wikia.com/wiki/Garhorlur_the_Brutal

**Comment by Jessland86** [comment]
Add Medusa to the list.

**Comment by R3P0FFXI** [comment]
@LegionDark/gm 

Current DSP 
`INSERT INTO `mob_pools` VALUES (2606,'Medusa','Medusa',171,0x0000490700000000000000000000000000000000,11,11,9,240,125,0,1,1,1,32,259,32,6983,541,0,0,0,1,0,725);`

Commented out Legion Code
`-- REPLACE INTO `mob_pools` VALUES (2606,'Medusa','Medusa',171,0x0000490700000000000000000000000000000000,11,11,9,240,125,0,1,0,1,23,0,32,6983,541,0,0,0,1,0,171);`

**Comment by TeoTwawki** [comment]
@R3P0FFXI 
Bad:
```
`code`
```

Good (ignore the slashes here):
```
\```language
   code
\```
```

**Comment by Raelious** [comment]
PR sent in.
