### ISSUE TITLE
cant login today

### ISSUE THREAD

**Issue by Peijieguo** [LegionDark/Issues#1634]
**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:

**Comment by TeoTwawki** [comment]
There is a big fat maintenance notice on the front page of the website. Also you have an empty template.

**Comment by TeoTwawki** [comment]
保养

**Comment by Peijieguo** [comment]
how long time？

**Comment by Peijieguo** [comment]
需要下载更新文件吗？

**Comment by TeoTwawki** [comment]
未知。
我们会发布更新 [website] 和 [discord] 完成后

**Comment by Peijieguo** [comment]
好的，谢谢

**Comment by TeoTwawki** [comment]
作品现
