### ISSUE TITLE
Skeletor - Craft Skills added after Transfer

### ISSUE THREAD

**Issue by Skeletor4424** [LegionDark/Issues#1635]
**Date & Time**: 
9/19/2017 8:06PM CST

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 
Skeletor
can contact Cleavage
**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99PLD

**NPC or Monster or item Name**: 
Craft skill Levels

**Zone name**: 
South Sandy

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

Just need to get in touch with a GM about uploading Skeletor's craft info to the newly transfered character^^. I have both Skeletor and Cleavage online, can contact either!

**Comment by Heepster03** [comment]
Crafts imported.
