### ISSUE TITLE
Pg Stuck

### ISSUE THREAD

**Issue by Lithien87** [LegionDark/Issues#1636]
**Date & Time**: 22/09/2017

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Melissandro

**Nation**:  San d'oria

**Job(level)/Sub Job(level)**: whm 34/1 blm

**NPC or Monster or item Name**: 

**Zone name**:  Ghelsba Outpost F-10

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**:

**Comment by R3P0FFXI** [comment]
@Lithien87 this tells us nothing
