### ISSUE TITLE
Item restoration - Laevateinn 119-II

### ISSUE THREAD

**Issue by Zikk420** [LegionDark/Issues#1637]
**Date & Time**: 22/09/2017

**FFXI Client Version (use `/ver`)**: 30170707_0

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: Bloodlust

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BLM

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/21139/laevateinn http://www.ffxiah.com/item/21140/laevateinn

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: I have the 21139 ver  were it should be the 21140 ver.

**Comment by Heepster03** [comment]
you're saying after trading the 50 tanz jewels correct?

**Comment by Zikk420** [comment]
Yes and no....   I did the trials and tanz, but didnt like the afterglow so i gave myself the none ver....  which at the time was the same as the other. This was 2-3 years ago  btw

**Comment by EpicTaru** [comment]
so you did this to yourself?

**Comment by EpicTaru** [comment]
and now when you are trying to redo it it isn't giving you the correct 119?

**Comment by EpicTaru** [comment]
Title changed after discord conversation.  Player had both 119 versions years ago but tossed the 119-II version back then as he didn't like the glow effect but has found that the two versions now have different stats (besides one glowing and one not).

**Comment by Zikk420** [comment]
I did the trials i did the tanz had the 119 II ver  didnt like the afterglow so i droped and gave myself the reg 119 ver again which at the time was the same. Yes i was a GM and no i dont have the 119 II anymore.

**Comment by R3P0FFXI** [comment]
@Zikk420 I'm sorry but you know my policy here. You admitted you had both versions, you admitted you tossed 1 of them. I will not refund you for tossing your items. You will need to redo the trial.
