### ISSUE TITLE
Multiple Blu Mage Spells Causing Lag

### ISSUE THREAD

**Issue by Raelious** [LegionDark/Issues#1640]
**Date & Time**: 9/28/17 starting at like uh 1:45pm to the time of this ticket

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**: Raelious

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BLU99/RDM49

**NPC or Monster or item Name**: Apademak

**Zone name**: Abyssea-Uleg

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Go pop Apademak, within like 30 seconds to 1 minute of fighting him the server lags pretty badly. I didn't think much of it, just assumed it was my connection. But upon fighting it more and more in the evening the server kept lagging and more and more people started complaining of the lag. Waited for the lag to clear up, then popped it another time and yup lag. Killed it eventually somehow? Then lag went away.... popped it again for science and yupp you guessed it lag! Did it a third time for science and yup... so Heepy wanted this report put in to disable mah baby Apademak...

**Comment by Heepster03** [comment]
Apademak is currently disabled.

**Comment by R3P0FFXI** [comment]
Main HV Host had uptime of 60 days. Rebooted HV Host, and all VM's, Reenabled Apademak.
