### ISSUE TITLE
the game stops while doing The Rescue Drill

### ISSUE THREAD

**Issue by Pespinoza78** [LegionDark/Issues#1642]
**Date & Time**: 
12:06pm MST 09/30/2017

**FFXI Client Version (use `/ver`)**: 
30170905_5

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
no, expected 3017070

**Character Name**: 
pulk

**Nation**: 
Sand'oria

**Job(level)/Sub Job(level)**: 
war/thf

**NPC or Monster or item Name**: 
tayula/Narvecaint

**Zone name**: 
La Theine Plateu

**Coordinates (use `$where`)**: 
X-293, Y29, Z144

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
whas doing The Rescue Drill, when talkin to Tayula, the game stops when the NPC Narvecaint should appear, can only move the camera and nothing else, I waited for like 20 mins so the game could react and nothing happened

**Comment by R3P0FFXI** [comment]
@Pespinoza78 this is a client mismatch issue until DSP updates to the latest version this will continue to happen

**Comment by Pespinoza78** [comment]
ok, thx, then ill wait to do this missions, til the update comes

**Comment by Pespinoza78** [comment]
i have a friend with a version that can do the mission for me, would there be a problem if he logs with my account, so he can finish the mission for me?

**Comment by TeoTwawki** [comment]
> i have a friend with a version that can do the mission for me, would there be a problem if he logs with my account, so he can finish the mission for me?

would cause any future checking to show you as having shared account, but you should be able to get the mission done now without doing that
