### ISSUE TITLE
Incorrect drop off mob

### ISSUE THREAD

**Issue by Moonlegend88** [LegionDark/Issues#1643]
**Date & Time**:  9:32pm

**FFXI Client Version (use `/ver`)**: 30170728_2

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  Yes

**Character Name**:  Moonlegend

**Nation**:  San d'Oria

**Job(level)/Sub Job(level)**: THF99/DNC49

**NPC or Monster or item Name**:  Fomor Paladin

**Zone name**: Sacrarium

**Coordinates (use `$where`)**:  X:60 Y:- 2 Z:- 106

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  Yes, 3 characters

**Steps To Reproduce / any other info**:   The Fomor Paladin dropped a Grotto Coffer Key, nothing too major but I figured id let you know its off. I'll list a screenshot below.
![moonlegend_2017 10 01_212600](https://user-images.githubusercontent.com/32443513/31061563-b75b21e6-a6f0-11e7-8efc-858f2522387a.png)

**Comment by R3P0FFXI** [comment]
@LegionDark/gm Former Paladin in DSP Group id 577 currently has droplist ID of 0 assign a drop ID and submit corrections to DSP

`INSERT INTO `mob_groups` VALUES (577,1387,24,330,1,**0**,0,0,80,82,0);`

**Comment by Raelious** [comment]
Fix submitted
