### ISSUE TITLE
Rescue Drill NPCs wont continue mission

### ISSUE THREAD

**Issue by xurpn1986** [LegionDark/Issues#1645]
**Date & Time**: 
10/03/2017  @10:16am

**FFXI Client Version (use `/ver`)**: 
30170905_5

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
3017070

**Character Name**: 
Xuron

**Nation**: 
San d'oria

**Job(level)/Sub Job(level)**: 
RDM70/BLM35

**NPC or Monster or item Name**: 

**Zone name**: 
La Theine Plateau

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
I was trying to do missions as to unlock Dyna, however this mission won't continue.  I was then told to swap to Bastok to have an easier time, however I can't change allegiance while on a mission.  Would prefer to stay Sandy as I have always been a Sandy player, however if the missions are bugged for Sandy and not Bastok I will swap.

**Comment by R3P0FFXI** [comment]
@xurpn1986 This is a version mismatch issue, because you are not on the current version of the server IDs don't match up. At this point you need to wait until we finish the update.

**Comment by xurpn1986** [comment]
Would it be possible to cancel the mission?  I would happily switch to Bastok to progress. :)

**Comment by EpicTaru** [comment]
Negative, you can't change nations mid-mission.  You have to wait until the version update files are finished being prepared by the admins.  At that time, a version update maintenance of the server will occur.
