### ISSUE TITLE
Paladin Maat Fight- I think i broke him.....

### ISSUE THREAD

**Issue by Skeletor4424** [LegionDark/Issues#1646]
**Date & Time**: 
10-2-2017 5:41PM CST

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 
Skeletor

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99PLD/49WAR

**NPC or Monster or item Name**: 
Maat

**Zone name**: 
Qu'Bia Arena

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes, but not in the fight

**Steps To Reproduce / any other info**: 
Trade Maat a pld test and then hit him with a 2k Atonement.

![skeletor_2017 10 03_172248](https://user-images.githubusercontent.com/29960533/31152634-9d70763c-a862-11e7-92fa-cfb0570c1f14.png)

**Comment by TeoTwawki** [comment]
what exactly is the problem you think you triggered? it doesn't say

**Comment by Skeletor4424** [comment]
oh duh, I didn't win the fight. It made me w8 in the zone until time ran out and I didn't get clearance.

**Comment by Jessland86** [comment]
Testing.

**Comment by Jessland86** [comment]
Killed with Atonement, got clear and win. Killed with Holy II and got clear and win.

**Comment by Jessland86** [comment]
Might have to do with being in a party. Will test that next.

**Comment by TeoTwawki** [comment]
aah, the old man just refused to acknowledge the badassery and end the bcnm. will look into.

before beginning  the bcnm, did you relogin with only this char ?

**Comment by Skeletor4424** [comment]
No

**Comment by TeoTwawki** [comment]
likely bad seasion and thats why then - have to log off all chars and relog just pne to avoid any chamce of DSPs lovely multibox bug

**Comment by Skeletor4424** [comment]
gotcha, ive run into it before with being dead at the end of BCNMs as well. Do I need to farm another test then?

**Comment by TeoTwawki** [comment]
probably yeah. I assume maat in ru'lude already snubbed ya? if jess's test reveals a diff bug I can fix but elae its just the known issue since forever and hafta refight

**Comment by TeoTwawki** [comment]
typin on mobile sucks bbl

**Comment by Skeletor4424** [comment]
np np, tests are easy enough.

**Comment by Jessland86** [comment]
I wasn't able to find anything or able to replicate it in party or out. Killed and got clear 3 times using auto-attack, magic and WS.

**Comment by Skeletor4424** [comment]
Ok thats fine, thx for looking into it^^

**Comment by Jessland86** [comment]
Lemme know if it does it again.

**Comment by TeoTwawki** [comment]
@Skeletor4424 if you keep running into it and can't get him to clear let me know (posting here again is fine)

but sounds like should be fine if redone with clean session untainted by any alts
