### ISSUE TITLE
can't enter Al Zahbi it says i dont have the expansion

### ISSUE THREAD

**Issue by Pespinoza78** [LegionDark/Issues#1647]
**Date & Time**: 
2017/10/03  9:39pm MST

**FFXI Client Version (use `/ver`)**: 
30170905_5

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
no 3017070

**Character Name**: 
pulk

**Nation**: 
San d'oria

**Job(level)/Sub Job(level)**: 
war 45/ thf 22

**NPC or Monster or item Name**: 
Ferri to Al Zahbi

**Zone name**: 
Mahura

**Coordinates (use `$where`)**: 
X:8. Y:-1 Z:2 (70)

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
i was tryng to take the ferri to al zahbi, and when the ferri i aborded and when it departed i was droped from the ferri, and it said to me "Unable to enter the next area. Expansion pack not installed", but i did installed all the expansions and did the quest in jeuno; and this happens, the ferri is not on the supposed position
![pulk_2017 10 03_214529](https://user-images.githubusercontent.com/32419708/31159196-abd3f790-a884-11e7-87da-dac1ef816dd4.png)

**Comment by TeoTwawki** [comment]
Do you have the keyitem given by the NPC in the Tenshodo? Sounds like you do not.

**Comment by Pespinoza78** [comment]
white invitation card?

**Comment by TeoTwawki** [comment]
Nope. boarding permit.

No permit, no boat ride.

**Comment by Pespinoza78** [comment]
ohh yeah, just read that, i was sure was missing something, but is been 6 years since i left the game, thx, gona check that

**Comment by TeoTwawki** [comment]
https://www.bg-wiki.com/bg/The_Road_to_Aht_Urhgan
http://ffxiclopedia.wikia.com/wiki/The_Road_to_Aht_Urhgan
The rhapsodies method doesn't exist yet, and I dunno if all 3 paths work. The subjob items path def works.

**Comment by TeoTwawki** [comment]
will leave issue up either until you close it or am told you successfully reached al zahbi, just in case ^^

**Comment by Pespinoza78** [comment]
ohh yeah, just read that, i was sure was missing something, but is been 6 years since i left the game, thx, gona check that

**Comment by Pespinoza78** [comment]
thx, it was that, sorry to bother, on my way to al zahbi right now

**Comment by TeoTwawki** [comment]
cool :)
