### ISSUE TITLE
Bummer +1 HQ result for Ogapepo Cape recipe

### ISSUE THREAD

**Issue by kairoffxi** [LegionDark/Issues#1648]
**Date & Time**:  n/a

**FFXI Client Version (use `/ver`)**:  n/a

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  n/a

**Character Name**: n/a

**Nation**: n/a

**Job(level)/Sub Job(level)**: n/a

**NPC or Monster or item Name**: n/a

**Zone name**: n/a

**Coordinates (use `$where`)**: n/a

**ffxiah.com link (for items issues only)**: 

http://www.ffxiah.com/item/28644/ogapepo-cape
http://www.ffxiah.com/item/28645/ogapepo-cape-1

**Multi-boxing? (multiple clients on same connection)**: n/a

**Steps To Reproduce / any other info**: 

Legion recipe for Ogapepo Cape shows Slime Shield for HQ +1 result. Should be Ogapepo Cape +1 result.

http://legiondark.com/db/items/28644/ogapepo_cape

http://legiondark.com/db/items/28645/ogapepo_cape_+1

**Comment by Raelious** [comment]
Fix submited, will be fixed in an upcoming maint.

**Comment by bc-kentaro** [comment]
Right on, thanks @Raelious .
