### ISSUE TITLE
Lvl 76 earring recipes needs HQ synths adjusted 

### ISSUE THREAD

**Issue by Jessland86** [LegionDark/Issues#1649]
**Date & Time**: 
2am 10/7/2017

**FFXI Client Version (use `/ver`)**: 
Not what the server is using

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
No

**Character Name**: 
N/a

**Nation**: 
N/a

**Job(level)/Sub Job(level)**: 

N/a
**NPC or Monster or item Name**: 
Flame Earring/Vulcan Earring

**Zone name**: 
N/a

**Coordinates (use `$where`)**: 
N/a

**ffxiah.com link (for items issues only)**: 
http://legiondark.com/db/items/11678/
http://legiondark.com/db/items/11681/
http://legiondark.com/db/items/11679/
http://legiondark.com/db/items/11683/
http://legiondark.com/db/items/11680/
http://legiondark.com/db/items/11682/
http://legiondark.com/db/items/11684/
http://legiondark.com/db/items/11685/

**Multi-boxing? (multiple clients on same connection)**: 
N/a

**Steps To Reproduce / any other info**: 
HQ1 is a NQ result. HQ1 needs to be edited on all of these.

Edit: Just checked it looks to be this entire series of earrings.

**Comment by Raelious** [comment]
Ill fix and PR it tomorrow morning/afternoon

**Comment by TeoTwawki** [comment]
@R3P0FFXI were you trying to requires HQ2 or better to HQ these at all or something, or just a mistake?

Verify preeze.

**Comment by R3P0FFXI** [comment]
@LegionDark/gm this is working as intended

**Comment by TeoTwawki** [comment]
k..so..how its intended is just a liiiiiittle confusing then, and we should consider using the base level instead of the hq tier in future adjustments to these hq item rarities.
