### ISSUE TITLE
Phorcys Salade not working

### ISSUE THREAD

**Issue by Strafeous** [LegionDark/Issues#165]
**Date & Time**: 9:17pm 7/15/2015
**Frequency**: Always
**FFXI Client Version**: 30150619_2
**Character Name**: Strafeous
**Race**: Elvaan
**Main Job**: WAR
**Sub Job**: SAM
**Area & Coordinates**: Everywhere
**Party or Solo**: Party
**NPC Name**:
**Monster Name**:
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**:
Equip it, doesn't give any stats at all. 
Spoke to Loki and he said it's bugged and doesn't have stats :P

**Comment by Loki79** [comment]
These were all in already.  Please remove all gear but the head and try again.  If the stats dont show please send me a SS.

INSERT INTO `item_mods` VALUES (10901, 1, 36); -- DEF:36
INSERT INTO `item_mods` VALUES (10901, 25, 10); -- Accuracy+10
INSERT INTO `item_mods` VALUES (10901, 23, 10); -- ATTACK+10
INSERT INTO `item_mods` VALUES (10901, 73, 5); -- "Store TP"+5
INSERT INTO `item_mods` VALUES (10901, 384, 7); -- "Haste+7%
INSERT INTO `item_mods` VALUES (10901, 289, 5); -- "Subtle Blow"+5

**Comment by Loki79** [comment]
Tested in game, this is working correctly.

**Comment by Strafeous** [comment]
@stats is broken :))

**Comment by TeoTwawki** [comment]
> @stats is broken
USE /CHECKPARAM :angry:

**Comment by TeoTwawki** [comment]
> @stats is broken

USE /CHECKPARAM :angry:

**Comment by TeoTwawki** [comment]
also, you tagged this guy https://github.com/stats
@ on github is a mention unless you surround it in back-tricks: `@` (not the same as the 'apostrophe'  btw)

**Comment by Strafeous** [comment]
Well, I surely hope stats is okay.
From now on I'll checkparam

**Comment by stats** [comment]
Wish I wasn't broken. But stuff happens. All good now.

**Comment by Loki79** [comment]
sorry stats :/

On a side note i want to talk to all the admins, and take a vote on removing the cmd..... you all know how much i despise it....

**Comment by TeoTwawki** [comment]
@Loki79 The command actually works as intended, but people keep expecting it to do things it doesn't. And its pissing me off so its about to become GM onry.
