### ISSUE TITLE
Ix'Aern DRK cannot pop?

### ISSUE THREAD

**Issue by alannor** [LegionDark/Issues#1651]
**Date & Time**: 
10/13

**FFXI Client Version (use `/ver`)**: 
Current

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Alannor

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
Various

**NPC or Monster or item Name**: 
Ix'Aern DRK

**Zone name**: 
Garden of Ruhmet

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Sometimes

**Steps To Reproduce / any other info**: 
So read in another ticket that Ix'Aern os now popped through sheer animosity method. 
Followed instructions to find ??? in one of the 4 rooms, kill all Aw'Aerns until (ffxiwiki says next room but I also killing all of the ones on the map) until you get sheer animosity message. Been close to 2 hours, havent seen this yet. LS mate also tried for a few hours the other night and no luck, can we confirm if this is the correct method. Trading organs (48 aerm organs) dont seem to work either.
Thanks!

**Comment by R3P0FFXI** [comment]
@alannor what version of the client are you on current is not a valid version number

**Comment by Raelious** [comment]
This isn't a predetermined pop item, I have been here for over 4 hours before without a single message, and as little as 15 minutes. It is pure luck getting that message. Just did it the other day and it took about an hour and a half to receive the message. You are just getting a bad string of luck here, bud.
