### ISSUE TITLE
Dark Adaman Bolt Heads

### ISSUE THREAD

**Issue by Blackenx1** [LegionDark/Issues#1655]
**Date & Time**: 10/17/2017 1:15pm Est

**FFXI Client Version (use `/ver`)**: 
30170728_2

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
3017070

**Character Name**: 
Blacken

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99/49 Thf/dnc

**NPC or Monster or item Name**: 
Dark Adaman Bolt Heads

**Zone name**: 
Metal Works

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/3306/d-a-bolt-heads

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Synth doesn't work 
Dark Adaman Ingot and a Wind Crystal

**Comment by Heepster03** [comment]
Cause the synthesis doesn't exist.

**Comment by R3P0FFXI** [comment]
@LegionDark/gm please add the synth recipe to DSP

**Comment by Raelious** [comment]
Fixed
