### ISSUE TITLE
Reforge BLU body >109

### ISSUE THREAD

**Issue by Rihyuh** [LegionDark/Issues#1658]
**Date & Time**: 
10/23/2017 8:50pm MST

**FFXI Client Version (use `/ver`)**: 
30171004_1 or 30170905_5

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
No

**Character Name**: 
Rihyuh

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
99 BLU / 49 RDM

**NPC or Monster or item Name**: 

Prishe
**Zone name**: 
Empyreal Paradox

**Coordinates (use `$where`)**: 

X:537 Y: -500 Z: -591 (101)
**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

yes
**Steps To Reproduce / any other info**: 
![rihyuh_2017 10 23_204205](https://user-images.githubusercontent.com/24214123/31924243-b5c40d34-b834-11e7-807d-9293484db7ba.png)
![rihyuh_2017 10 23_204226](https://user-images.githubusercontent.com/24214123/31924246-ba60abc2-b834-11e7-8a0b-885d20b2ffca.png)
![rihyuh_2017 10 23_204229](https://user-images.githubusercontent.com/24214123/31924249-be97a858-b834-11e7-8287-77015b30a84a.png)
![rihyuh_2017 10 23_204301](https://user-images.githubusercontent.com/24214123/31924252-c290abbc-b834-11e7-9d31-f1a14a124fef.png)

**Comment by Heepster03** [comment]
Found that you are **NOT** a Reseph Eradicator just yet.

I'll leave it open to make sure that Prishe is being nicer after this.

**Comment by Rihyuh** [comment]
It is done. Megadiremite killed, reforge complete!
