### ISSUE TITLE
Username retrieval?

### ISSUE THREAD

**Issue by Tsnuna** [LegionDark/Issues#1660]
**Date & Time**: 10/26/2017

**FFXI Client Version (use `/ver`)**: 30170905_5

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: no

**Character Name**: Koraynge

**Nation**: Bastok

**Job(level)/Sub Job(level)**: WAR20

**NPC or Monster or item Name**: 

**Zone name**: Valkurm Dunes

**Coordinates (use `$where`)**: Not sure where my alt-character is, but I remeber her being (near the entrance gates to Selbina)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: Currently a new player here,I  was trying to make 2 other accts in total of 4 accts to quad box, (3dd,1 healer) and was in the process of editing  the windower settings via notepad to add more profiles. After making my edits, I put my pc to sleep. When I came back and turned it on, windower had no profiles listed and when I checked the settings again, it was wiped. At the moment,  I do not remember my username for that account and can only provide my character name, location, and my other account name?)

**Comment by Heepster03** [comment]
Your first mistake was using windower.

**Comment by Tsnuna** [comment]
Is there a difference between Ashita and Windower? Like in terms of being easier to use or so?

**Comment by TeoTwawki** [comment]
ashita is set up for private servers "out of the box" where windower needs to improve handling it. alegedly happening in windower 5.

**Comment by Tsnuna** [comment]
I guess I should've stuck with ashita, but my uncle wanted me to use windower for its addons and plugins lol

**Comment by TeoTwawki** [comment]
tell your uncle theres plugins&addons both both for almost all the same things. :)

**Comment by Tsnuna** [comment]
If I remember, he used to play retail way back when it started, so I just follow along with what he says. I think he quit in 2014 though.

**Comment by Tsnuna** [comment]
My name on discord is Tsnuna btw.

**Comment by R3P0FFXI** [comment]
@Tsnuna PLease contact me on Discord

**Comment by R3P0FFXI** [comment]
User did not have correct information
