### ISSUE TITLE
Renik NPC not producing Acro Breeches

### ISSUE THREAD

**Issue by Mandefresh** [LegionDark/Issues#1661]
Date & Time: 11/1/2017, 12:30pm

FFXI Client Version (use /ver): 3010905_5

Server's Expected Client Version matches, yes/no? (use $ecv): no ,  30170707_0

Character Name: Xcaliber

Nation: Sandoria

Job(level)/Sub Job(level): Dark Knight (99)/Samurai (49)

NPC or Monster or item Name: Renik

Zone name:  Upper Jeuno

Coordinates (use $where):  X:-17, Y:0, Z:39 (216)

ffxiah.com link (for items issues only): http://www.ffxiah.com/item/27233/acro-breeches

Multi-boxing? (multiple clients on same connection): no

Steps To Reproduce / any other info: Trade Renik NPC Royal Squire's Breeches and 5 Rusted Coins. She is supposed to give Acro Breeches in return. Nothing happens.

**Comment by EpicTaru** [comment]
Verified in game that player was attempting to trade all correct needed items and had sufficient Bayld.

**Comment by R3P0FFXI** [comment]
@EpicTaru Horos Tights  item 27188 and 5 Rusted coins not Royal Squire's Breeches thats an AH item these items are incorrect

**Comment by TeoTwawki** [comment]
old forum posts that never got updated get transferred to wiki, wheeeeee! /headdesk

**Comment by EpicTaru** [comment]
Joins Teo in the /headdesk

**Comment by Mandefresh** [comment]
Horos Tights are Aug/Rare/Ex. Not sellable on ah. http://ffxiclopedia.wikia.com/wiki/Horos_Tights

**Comment by R3P0FFXI** [comment]
@Mandefresh you'll need to wait until this is fixed we are working on it there is no ETA

**Comment by EpicTaru** [comment]
shoves a desk over to @Mandefresh so he can /headdesk alongside Teo and I.

**Comment by TeoTwawki** [comment]
> Horos Tights are Aug/Rare/Ex. Not sellable on ah. http://ffxiclopedia.wikia.com/wiki/Horos_Tights 

he was saying Royal Squire's Breeches, not Horos Tights were

**Comment by EpicTaru** [comment]
¯\_(ツ)_/¯

**Comment by EpicTaru** [comment]
Ever since I started playing, the wiki page and items listed there all worked fine and performed as expected....of course the arco breeches weren't one of them, lol

**Comment by EpicTaru** [comment]
@Raelious attempted using the Royal Squire's Mufflers and Royal Squire's Sollerettes. Both produced the stated Arco hands and feet items, respectively.

**Comment by TeoTwawki** [comment]
**All I am saying: Code sitting there now is exactly the same as it was the day it came out. The item ids for this trade in that script have never changed.**

**Comment by TeoTwawki** [comment]
Do not close issue yet: I have to perform some NPC hotfixing, didn't finish in time for maint
