### ISSUE TITLE
Atropos Stuck

### ISSUE THREAD

**Issue by o0Persefone0o** [LegionDark/Issues#1662]
**Date & Time**: 
November 5 2017, 14:36 

**FFXI Client Version (use `/ver`)**: 
30170728:2

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
3017070

**Character Name**: 
Atropos

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99SMN/49RDM

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yeah i do, my chars are Persefone, Atropos, Clotho and Lachesis

**Steps To Reproduce / any other info**: 

I think i can write it here, well the issue its Atropos its not loged in and she appears to be online, i can see it using /sea all atropos, i get stuck on the limbo when i use warp ring... i try to use the unstuck tool from the legiondark page as Rae told us yesterday, but i cant because the main page says atropos its online... i need someone to kick out atropos or something like that. thank you

**Comment by TeoTwawki** [comment]
try now

**Comment by o0Persefone0o** [comment]
its stiil "online" and i can use the unstuck buttom, i use /sea all atropos and its on bastok mines but im not logged in

**Comment by TeoTwawki** [comment]
hmm

**Comment by o0Persefone0o** [comment]
i cant use the unstuck b uttom, srry my english sucks

**Comment by TeoTwawki** [comment]
noticed search shows Atropos  in party. log off all your chars, I'm going to reset any party data that may be forcing Atropos to stay around in the database there.

**Comment by TeoTwawki** [comment]
noticed search shows Atropos  in party. log off all your chars, I'm going to reset any party data that may be forcing Atropos to stay around in the database there.

**also please make sure you have closed all open windows related to the game.**

**Comment by o0Persefone0o** [comment]
ok logging out

**Comment by o0Persefone0o** [comment]
done

**Comment by TeoTwawki** [comment]
verified you are off in game list now, try once more :)

**Comment by o0Persefone0o** [comment]
thank you

**Comment by o0Persefone0o** [comment]
yaaaaaaaaaaaaay it works :D!!

**Comment by TeoTwawki** [comment]
😄
