### ISSUE TITLE
$Tele Denied after Jail

### ISSUE THREAD

**Issue by o0Persefone0o** [LegionDark/Issues#1664]
**Date & Time**: 
08 November 2017

**FFXI Client Version (use `/ver`)**: 
30170728_2

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes   3017070

**Character Name**: 
Myeva

**Nation**: 
San d´Oria

*+Job(level)/Sub Job(level)**: 
RDM99/SCH49

NPC or Monster or item Name: 
Zone name: 
Coordinates (use `$where`): 
ffxiah.com link (for items issues only): 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 

**Hello**

After Myeva was on Jail the **$tele** service was unactive to her, the other charsthey do not present the problem.

![23468248_301041300397155_1417121191_o](https://user-images.githubusercontent.com/30010790/32571357-c58464b2-c48c-11e7-8ced-7ede4d54a161.png)

**Comment by EpicTaru** [comment]
@o0Persefone0o Your client version DOES NOT match the server version.  No idea if that would have caused this issue but pointing that out to you.

**Comment by EpicTaru** [comment]
@o0Persefone0o Try using the !tele command again

**Comment by R3P0FFXI** [comment]
@EpicTaru how was Myeva removed from jail?

**Comment by EpicTaru** [comment]
@R3P0FFXI Looking into that

**Comment by TeoTwawki** [comment]
I bet rerunning release fixes - prolly multi box situation with the jail cell variable (in non zero teleports fail)

**Comment by EpicTaru** [comment]
An additional pardoning appears to have resolved the issue. I'm still digging into the original release.

**Comment by o0Persefone0o** [comment]
sorry i was asking Aurel to log Myeva and try again, he told me Myeva's $tele its now working.

Myeva get out of jail doing home point because she was dead when she get into jail, Aurel wait until the releasing date and do home point, like 2hrs before his other chars get release

**Comment by TeoTwawki** [comment]
home pointing should work from jail.

@r3p0ffxi dsp issue stat

**Comment by TeoTwawki** [comment]
@o0Persefone0o thanks for letting us know

**Comment by o0Persefone0o** [comment]
:) thank you so much for the fast answer. sorry Aurel do not talk here, but his english its worst than mine xD

**Comment by o0Persefone0o** [comment]
actually he was sending me pictures about what you told him on ffxi

**Comment by R3P0FFXI** [comment]
@TeoTwawki remind me tonight when I am home from work or send me a txt on phone and I will be sure to do it

**Comment by o0Persefone0o** [comment]
ok, i dunno what is DSP but i remember you this night. :)

**Comment by TeoTwawki** [comment]
DSP = DarkStar Project
just telling R3 to report a bug for us is all 🙂
