### ISSUE TITLE
Exporting tool

### ISSUE THREAD

**Issue by Dwingvatt** [LegionDark/Issues#1666]
**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 30171103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Dwingvatt

**Nation**: Sandy

**Job(level)/Sub Job(level)**: DNC39/NIN19

**NPC or Monster or item Name**: Exporting Tool

**Zone name**: NA

**Coordinates (use `$where`)**: Not online atm

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes I do have multiple accounts.

**Steps To Reproduce / any other info**: 
I have issue with the exporting tool, I followed the wiki have everything that is needed. When I log on retail and run exporting tool, it will close and not do anything. No error will come up; I have update everything that was mention on wiki. Disable dimming screen, I just clueless now. So I am here for help.

**Comment by Dwingvatt** [comment]
What other info do you need? First time using this.

**Comment by Dwingvatt** [comment]
Just giving an update, I have reinstall everything followed wiki to the T. When I am on Ashita on retail. I will right click on Legionexporter, the command prompt will come up, but then closes without any error code or anything. Am I pulling the .dll in the right file or where it needs to be placed? I checked to make sure my boot loader was pol.exe it was. I waited 45 mins on retail before using the exporter it did not work still. I do not know if it could be a problem with my Ashita as well. Could from time to time I have to redownload Ashita to even log on Legion because of error messages. If you need anymore information just let me know.
Thanks

**Comment by TeoTwawki** [comment]
Note: user helped by atom0s on discord
