### ISSUE TITLE
Windy 2-1 broke

### ISSUE THREAD

**Issue by Nabrut** [LegionDark/Issues#1667]
**Date & Time**: 11/11/2017 4pm est

**FFXI Client Version (use `/ver`)**: 30171103_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 3017070

**Character Name**: Turban

**Nation**: Windy

**Job(level)/Sub Job(level)**: 75thf/37dnc

**NPC or Monster or item Name**: Nanaa Mihgo

**Zone name**: Windurst Woods

**Coordinates (use `$where`)**: x63 y-4 z239

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Windurst Mission 2-1 Had issue where Fossil rocks were unclickable contacted GM. GM attempted to resolve by giving me the KI. Nanaa Mihgo wont take the fake KI... so still cant click rocks used to be unclickable now they give me this message (You must visit Aht Urhgan Whitegate in order to progress in the Rhapsodies of Vana'diel missions.) so yea they are still broke... and now I have a KI that she wont accept.

**Comment by Heepster03** [comment]
That is what we call a **Version Mismatch**. You are stuck until the server does the next update. Time to go find something else to do.
