### ISSUE TITLE
Choco digging not working you find things and says inventory is full when it is not. 

### ISSUE THREAD

**Issue by Dionuss** [LegionDark/Issues#1668]
**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 

**Character Name**: 

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:

**Comment by Heepster03** [comment]
Missing all the infos.
