### ISSUE TITLE
Moogle in rolanberry

### ISSUE THREAD

**Issue by goferffxi** [LegionDark/Issues#167]
**Date & Time**: 
**Frequency**:
**FFXI Client Version**:
**Character Name**:Gofer
**Race**:Taru
**Main Job**: WAR
**Sub Job**:SAM
**Area & Coordinates** Rolanberry fields:    X:243 Y:24 Z:480
**Party or Solo**:solo
**NPC Name**:Moogle
**Monster Name**:na
**Multi-boxing? (multiple clients on same connection)** single box:
**Steps To Reproduce The Issue**:Talk to the moogle and POL completely shuts down. tried twice and same thing happened.

**Comment by Loki79** [comment]
My fault!  I had adjusted the spoof msg in preparation for some new trials.  All good to go now,
