### ISSUE TITLE
Cant complete CoP 8-4

### ISSUE THREAD

**Issue by Kielbasa** [LegionDark/Issues#1670]
**Date & Time**:  11/14/2017

**FFXI Client Version (use `/ver`)**: 30170905_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: no

**Character Name**: Kielbasa

**Nation**: Sandy

**Job(level)/Sub Job(level)**: Theif 99 dancer 99

**NPC or Monster or item Name**: CoP 8-4

**Zone name**: 

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:  After the last fight it wont let me do the finishing cutscenes to say goodbye to any of the npc's waited over 24hours and have the last KI.

**Comment by Kielbasa** [comment]
not sure if its the client version or not making problem

**Comment by Raelious** [comment]
Can you go "re-attempt" the Promithia fight? Or is that not an option?

**Comment by TeoTwawki** [comment]
probably either an item check (cop rings) or missing npc in client due to version mismatch. but if an imported char has mission reward the mission gets stuck.

**Comment by Heepster03** [comment]
For some reason, his PromathiaStatus was set to 1. I see that he has the Tears of Altana KI which means he should have been changed from 1 to 2 and 2 to 3 and then he can talk to Cid.

I changed his PromathiaStatus variable to 3 where it should've been.

**Comment by Kielbasa** [comment]
Thank you to whom the GM was he/she fixed it cid gave me the first CS now to finish it. Very much appreciated

**Comment by Heepster03** [comment]
No problem. Early congratulations.
