### ISSUE TITLE
Import Crafting

### ISSUE THREAD

**Issue by Dwingvatt** [LegionDark/Issues#1672]
**Date & Time**: 10:55am est

**FFXI Client Version (use `/ver`)**: 30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: No

**Character Name**: Evildwingvatt

**Nation**: Sandy

**Job(level)/Sub Job(level)**: 75 THF/ 0 Subjob

**NPC or Monster or item Name**: NA

**Zone name**: Selbina

**Coordinates (use `!where`)**: X:17 Y:-14 Z:76 (84)

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Just making ticket for crafting import.
Thanks

**Comment by Heepster03** [comment]
Crafts imported.

**Comment by Dwingvatt** [comment]
Thanks again
