### ISSUE TITLE
Craft import

### ISSUE THREAD

**Issue by Sinnersslayer** [LegionDark/Issues#1673]
**Date & Time**: 19.11.17

**FFXI Client Version (use `/ver`)**: 30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: no

**Character Name**: Glizdus

**Nation**: Bastok

**Job(level)/Sub Job(level)**: WHM99/no sub

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

Just a request for crafting level import

**Comment by Heepster03** [comment]
Can't see what to import. Usually there is a screenshot to prove this.

**Comment by Sinnersslayer** [comment]
Oh I have included a screenshot in my transfer app :)
I can't post it here.
How can I send it to You?

**Comment by Sinnersslayer** [comment]
`
![glizdus_craft_info](https://user-images.githubusercontent.com/33654112/32996353-d1cc60dc-cd81-11e7-8f0f-7ac1fceabb90.png)
`

**Comment by Sinnersslayer** [comment]
This screenshot suffice?

**Comment by Heepster03** [comment]
Went looking for you tonight and couldn't find you. I'll try again tomorrow.

**Comment by Heepster03** [comment]
Crafts xferred.
