### ISSUE TITLE
Crafting import

### ISSUE THREAD

**Issue by Skanless** [LegionDark/Issues#1674]
**Date & Time**: 
11/19/17 3pm

**FFXI Client Version (use `/ver`)**: 
30171004_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
3017070

**Character Name**: 
Doruk

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
thf99/war47

**NPC or Monster or item Name**: 
null

**Zone name**: 
null

**Coordinates (use `!where`)**: 
null

**ffxiah.com link (for items issues only)**: 
null

**Multi-boxing? (multiple clients on same connection)**: 
null

**Steps To Reproduce / any other info**: 
null
![img_20171114_082748](https://user-images.githubusercontent.com/31179096/32996064-f1c995f4-cd3a-11e7-9454-43c50e41a6df.png)

**Comment by Skanless** [comment]
Do I need stay logged off Doruk or is it ok for to play him in the mean time?

**Comment by Heepster03** [comment]
You can play him. I've just been busy with working and holidays.

**Comment by Skanless** [comment]
ok just wanted to make sure it ok to play him.

**Comment by Heepster03** [comment]
Crafts xferred.
