### ISSUE TITLE
Moogle house In N.Sandy

### ISSUE THREAD

**Issue by Dwingvatt** [LegionDark/Issues#1675]
**Date & Time**: 5:30 pm est

**FFXI Client Version (use `/ver`)**: 30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: No

**Character Name**: Evildwingvatt

**Nation**: Sandy

**Job(level)/Sub Job(level)**: 99 MNK/49 DNC

**NPC or Monster or item Name**: Moogle

**Zone name**: North Sandy

**Coordinates (use `!where`)**: X:0 Y:0 Z:0 (192)

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Okay, I talk to moogle in N.Sandy and it would crashed my bootloader. So I was told to Check in South then North and try again. It crashed again. I went and did it backwards. North to South and talk to moogle in South and it worked. Went back to North and it Crashed again. I was told on discord to just open the menu and do it that way. I did that however, it crashed when I open menu in North Sandy Mog house.

**Comment by Jessland86** [comment]
This should be fixed since pupdate.
