### ISSUE TITLE
Vulpangue (White Wind)

### ISSUE THREAD

**Issue by drizzitalgul** [LegionDark/Issues#1677]
**Date & Time**: 
 11/ 27/2017
 15:04:03
**FFXI Client Version (use `/ver`)**: 
/ver 301709005_5

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
3017070
**Character Name**: 
Thetank

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
PLD99/WAR49

**NPC or Monster or item Name**: 
Vulpangue

**Zone name**: 
Wajaom Woodlands

**Coordinates (use `!where`)**: 
X:-694 Y:-8 Z:-138 (55)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
feed tp
![white wind](https://user-images.githubusercontent.com/34041055/33287273-2e633082-d386-11e7-858a-cbbc553b31a1.png)

**Comment by R3P0FFXI** [comment]
Since its not descriptive white wind is attacking mob instead of healing it

**Comment by TeoTwawki** [comment]
this is because the custom script used for it was a total copy and paste of crosswind. jeez.
