### ISSUE TITLE
Wamoura Family(Erratic Flutter)+Achamoth

### ISSUE THREAD

**Issue by drizzitalgul** [LegionDark/Issues#1678]
**Date & Time**: 
11/27/17
16:31:26
**FFXI Client Version (use `/ver`)**: 
ver: 30170905_5

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
no

**Character Name**: 
Thetank

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
(PLD99/WAR49)

**NPC or Monster or item Name**: 
Wamoura family including T3 ZNM Achamoth

**Zone name**: 
Halvung/Mount Zhayolm

**Coordinates (use `!where`)**: 
X:-30 Y:10 Z:344 (246)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Feed Tp
![image](https://user-images.githubusercontent.com/34041055/33292012-c02728ca-d395-11e7-8807-1fb863a3de89.png)
![image](https://user-images.githubusercontent.com/34041055/33292023-c8b18bd4-d395-11e7-8c42-86b47843eaf7.png)

**Comment by TeoTwawki** [comment]
```
Notes

    Blue magic version is 30% haste (equivalent to Haste II) for 5 minutes.
    Self-cast only.
    Compatible with Diffusion.
    Wamoura version also deals Fire damage to targets around the wamoura. 
```
http://ffxiclopedia.wikia.com/wiki/Erratic_Flutter

If I hadn't read discord chat I would know wtf I was supposed to see in your screenshots. Next time, please be elaborate.

**Comment by TeoTwawki** [comment]
Did find other problems and fixed (wrong dmg type, wrong haste amount)
