### ISSUE TITLE
Windy Mission 2-1

### ISSUE THREAD

**Issue by Nabrut** [LegionDark/Issues#1683]
**Date & Time**: 
10:15 AM 12/03/17

**FFXI Client Version (use `/ver`)**: 
30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
30171110

**Character Name**: 
Turban

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
96THF/48BLM

**NPC or Monster or item Name**: 
NPC : Nanaa Mihgo 
KIs : Lapis Monocle and Lapis Coral

**Zone name**: 
Windurst Woods

**Coordinates (use `!where`)**: 
X:64 Y:-4 Z:239 (37)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Normally yes but not while trying to get off this mission

**Steps To Reproduce / any other info**: 
Ok...
When I first came to this server back in Oct I started in San d'Oria but I was informed 2-1 was broken due to a version mismatch. So I switched to Windurst because I was told it was safe. (All Lies =) ) While on Windurst 2-1 I ran into issues when I got to the where I have to examine Fossil Rocks in the Maze of Shakhrami while in possession of the KI Lapis Monocle to get the KI Lapis Coral. 4/6 of the Fossil Rocks gave me random nonsense messages and 2/6 were unclickable. I logged, reloaded zone, tried everything on my end checked several times that I was progressed correctly in the mission. I proceeded to contact a GM (can't remember which one) explained the situation they attempted to remedy the situation for me on the spot and gave me the KI Lapis Coral. Unfortunately Nanaa Mihgo doesn't like cheating and won't accept the Lapis Coral that was given to me. Now with the Pupdate out and the version mismatch not as bad I attempted it again. She still wont take the KI that was given to me. I went back to the Maze of Shakhrami and clicked the Fossil Rocks to make the game think it gave me the KI and went back to Nanaa but still no luck. Please Halp =)

**Comment by Heepster03** [comment]
Quickfix'd.

**Comment by TeoTwawki** [comment]
```
Server's Expected Client Version matches, yes/no? (use !ecv):
30171110
```
this is a yes or no question, for future reference
