### ISSUE TITLE
Voidwatch: Rigorous Grip +1 fails to drop 

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#169]
**Date & Time**: 7/10/2015
**Frequency**: happened once to me
**FFXI Client Version**: 30150619_2
**Character Name**: Daedrik
**Race**:Elvaan
**Main Job**: PLD
**Sub Job**: RDM
**Area & Coordinates**:East Ronfaure(S) Voidwatch NM
**Party or Solo**: Party
**NPC Name**: 
**Monster Name**:
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**:  it dropped as soon as Lot went, inventory was free and i was using Ashitacast and Ashita so no weird gear thing happening~

![daedrik_2015 07 14_173255](https://cloud.githubusercontent.com/assets/12631024/8760080/7a567ffc-2cbd-11e5-9ea2-cdaa78b2db5c.png)

**Comment by Loki79** [comment]
All 3 items we found are fixed, will need a restart for them to go in.  Please grab me after next restart and ill get you the item.
