### ISSUE TITLE
Unable to use the Dice Items to learn the Rolls

### ISSUE THREAD

**Issue by AleksandarFFXI** [LegionDark/Issues#1696]
**Date & Time**: 
12/4/2017

**FFXI Client Version (use `/ver`)**: 

30171103_1
**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 

30171103
**Character Name**: 
Aleksandar

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
COR99/DNC49

**NPC or Monster or item Name**: 
Multiple Dice

**Zone name**: 
Bastok Mines (Anywhere)

**Coordinates (use `!where`)**: 
Anywhere

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/5497/bolters-die
http://www.ffxiah.com/item/5498/casters-die
http://www.ffxiah.com/item/5499/coursers-die
And more

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Can't use the item. It will act like it is used giving you the delay bar as if you were using it, but will not use the item or grant the Phantom Roll ability.

**Comment by R3P0FFXI** [comment]
@AleksandarFFXI And more? If there are more not working and it is not in this post then this is an incomplete report

**Comment by tb1** [comment]
Can add to the list:
http://www.ffxiah.com/item/5501/tacticians-die
http://www.ffxiah.com/item/5500/blitzers-die

**Comment by AleksandarFFXI** [comment]
Any die after level 70.

**Comment by R3P0FFXI** [comment]
@AleksandarFFXI No offense but im not going to look at every die after level 70 please submit a complete list

**Comment by TeoTwawki** [comment]
Don't make me go all 3 stooges head bang on you.

There aren't that many die and they'll have near identical scripts. **Or** you know, just check the ones reported and consider it done til more get reported later.

**Comment by TeoTwawki** [comment]
all i did was search _\Scripts\globals\items_ for the word "die".

**Comment by AleksandarFFXI** [comment]
Die is the plural for Dice

**Comment by AleksandarFFXI** [comment]
Die is the singular of Dice.

**Comment by TeoTwawki** [comment]
Listen here, the item name uses the word "die". so STUFU instead of incorrectly "correcting" the person arguing in your favor.

**Comment by EpicTaru** [comment]
Meeses is the plural of mice

**Comment by TeoTwawki** [comment]
hate them meeses to pieces!

**Comment by Jessland86** [comment]
Condensing with an existing open ticket for the same issue. https://github.com/LegionDark/Issues/issues/1289
