### ISSUE TITLE
Bukhis Apocalyptic Ray gives 2 second doom

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1698]
**Date & Time**: 
Dec 5, 2017
10:13 AM MST

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 

**Character Name**: 
Tbone

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
THF99

**NPC or Monster or item Name**: 
Bukhis

**Zone name**: 
Abyssea - Vunkerl

**Coordinates (use `!where`)**: 
-178 -40 -278

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Have Bukhis use Apocalyptic Ray on you, wait 2 seconds, die.

![tbone_2017 12 05_101127](https://user-images.githubusercontent.com/3310503/33620513-44087ba2-d9a5-11e7-9504-c5914f7cfc7c.png)

10:07:55 Bukhis readies Apocalyptic Ray
...
10:07:58 Uzi's doom counter hits 2
10:07:09 Bukhis uses Apocalyptic Ray
...
10:08:02 Uzi explodes into a pink shower of giblets
...
10:08:04 Tbone lulz

**Comment by Sinnersslayer** [comment]
If I may add.
It applies to the skill overall.
The Taur NM which drops KI to spawn Bukhis also uses Apo. Ray with same resultat.

**Comment by EpicTaru** [comment]
Ludicrous gibs!

**Comment by R3P0FFXI** [comment]
Issue has been forwarded to DSP

**Comment by R3P0FFXI** [comment]
Issue taken care of in next maint

**Comment by TeoTwawki** [comment]
Issue hotfixed right now
