### ISSUE TITLE
ToAU Naja Salaheem 1st CS Loop

### ISSUE THREAD

**Issue by Skett** [LegionDark/Issues#17]
**Date & Time**: 27.05.15 17:12 GMT
**Frequency**: Repeated
**FFXi Client Version**: 30150508_5
**Character Name**: Skett
**Race**: Elvaan
**Main Job**: NIN
**Sub Job**: WAR
**Area & Coordinates (Type @where to get this info.)**: Salaheems Sentinels, Aht Urghan (Unsure zoned)
**Party or Solo**: Solo
**NPC Name**: Naja Salaheem
**Monster Name**: N/A
**Steps To Reproduce The Issue**: Walk by Salaheems Sentinels puts you into the first CS with them. As you go to leave the room after the CS, you are put back in to the CS. Infinite loop.

**Comment by R3P0FFXI** [comment]
As a workaround after you get the first CS use @homepoint

**Comment by Loki79** [comment]
the majority of ToAU missions do not work and probably wont for some time.

**Comment by TeoTwawki** [comment]
Will check on this during the week, this was not happening before while ToAU is mostly non existent, the first few missions (which are nothing but cs) were working.

**Comment by TeoTwawki** [comment]
Confirmed bug, as Legions code matches DarkStar 100% here I have sent the details on to them.

**Comment by TeoTwawki** [comment]
It seems the game doe snot notice you have already completed this mission until you have zoned, once you have it stops triggering this event. But that traps you in the room until you have used (at)return or (at)homepoint to get out.


@R3P0FFXI be careful of using @ in github posts, if there were a user named homepoint it would have sent him a message which was not your intention. I've cause Mr. Goto and Mr Zone to receive some unwanted messages in the past. :cry:

**Comment by SomeGlenn** [comment]
Mr Where is going to get loads of messages from Legiondark then 

Area & Coordinates (Type @where to get this info.)

**Comment by TeoTwawki** [comment]
That account apparently belongs to PayPal, Inc or one of its employees..lol

**Comment by helixhamin** [comment]
This worked for me yesterday. The issue before is you weren't getting the key item, so it kept checking for that, not finding it, and redoing the scene. Now, I have the key item.

**Comment by TeoTwawki** [comment]
I received the keyitem first try when I tested this, and the cut scene looped anyways.

**Comment by TeoTwawki** [comment]
Juts so its known here, this issue was also reported to DarkStar. Waiting to see what they make of it.
