### ISSUE TITLE
Ginsen bug

### ISSUE THREAD

**Issue by Strafeous** [LegionDark/Issues#170]
**Date & Time**:  10:07pm 7/17/2015
**Frequency**: Constant
**FFXI Client Version**: 30150619_2
**Character Name**: Strafeous
**Race**: Elvaan
**Main Job**: WAR
**Sub Job**: SAM
**Area & Coordinates**: Ordelles caves/Pashhow [s]
**Party or Solo**: Party
**NPC Name**: - 
**Monster Name**: Melancholic Moira
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**: Dropped from the VWNM, I rolled, won, couldn't obtain. Loki gives it to me, never appears in my inventory, he does it a second time and it still doesn't.

**Comment by Strafeous** [comment]
Also this belt
http://i.imgur.com/uckR5Cu.jpg

**Comment by Loki79** [comment]
Ok all 3 items are fixed now.  Will take a restart before they go in though.  Get with me after retart and ill get you guys the items.  @Strafeous let me know if you come across anymore of these.
