### ISSUE TITLE
Atma of the Voracious Violet regain 200 tp

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1701]
**Date & Time**: 06/12/17

**FFXI Client Version (use `/ver`)**: 30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 

**Character Name**: 
Aurel

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
Sam

**NPC or Monster or item Name**: 
30171103_1

**Zone name**: 
Abyssea

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

no
**Steps To Reproduce / any other info**: 

Atma of the Voracious Violet regain 200 tp for tic    other Atma of the Would-Be King =Regain 100 tp/tic

**Comment by R3P0FFXI** [comment]
HUh? @Aurelcassy explain

**Comment by Aurelcassy** [comment]
the gain of TP is  200tp/tic   and Atma of the Would-Be King is 100 tp/tic , normal is Atma of the Voracious Violet  20tp/tic and Atma of the Would-Be King is 10tp/tic

**Comment by R3P0FFXI** [comment]
@Aurelcassy this might actually be correct remember TP went from 100/200/300 to 1000/2000/3000

**Comment by R3P0FFXI** [comment]
This is correct

**Comment by TeoTwawki** [comment]
#1721 
Honest mistake on @R3P0FFXI's part, he knew I had fixed multiple atma that had one zero less than it should, I just fixed one wrong though.
