### ISSUE TITLE
Atma of the Omnipotent no add haste +10%

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#1702]
**Date & Time**: 

06/12/17
**FFXI Client Version (use `/ver`)**: 
 30171103_1
**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 

**Character Name**: 
aurel
**Nation**: 
sandy

**Job(level)/Sub Job(level)**: 
drk

**NPC or Monster or item Name**: 

Atma of the Omnipotent 
**Zone name**: 
abyssea

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 

Atma of the Omnipotent  not work haste more 10%

**Comment by R3P0FFXI** [comment]
@Aurelcassy The correct mod is added to the atma, its haste gear not haste cap so most likely you are hitting the gear cap already of +25% haste

**Comment by R3P0FFXI** [comment]
Leave a comment

**Comment by Aurelcassy** [comment]
i check using cero equip
