### ISSUE TITLE
Titan Battlefield Missing

### ISSUE THREAD

**Issue by Kittycatt** [LegionDark/Issues#1703]
**Date & Time**: 
06/12/2017 
18:00 +1 GMT

**FFXI Client Version (use `/ver`)**: 
30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
no

**Character Name**: 
Kittycat

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
RNG99/DNC49

**NPC or Monster or item Name**: 
Earth Protocrystal

**Zone name**: 
Cloister of Tremors

**Coordinates (use `!where`)**: 
X:-540 Y:1 Z:-495 (186).

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No.

**Steps To Reproduce / any other info**: 
![kittycat_2017 12 06_190822](https://user-images.githubusercontent.com/34315444/33680163-053bfbe8-dac1-11e7-8f5f-5cb181cbfd49.png)
![kittycat_2017 12 06_191006](https://user-images.githubusercontent.com/34315444/33680164-0767d590-dac1-11e7-8f59-8869ae5c9a63.png)

**Comment by Larikun** [comment]
Just thought I should mention that this is literally the only Protocrystal not functioning. Have gone through and successfully completed all the others save for this one. Only mention this in hopes it'll help track down the problem for this and other BCNMs.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/4343

>[5:29 PM] Teo:  hows that bcnm branch doing? coz bcnms are all kindsa f$%^&d and I dunno what I should bother reporting now
[5:29 PM] demolish: once dyna and limbus work again it can be merged in
[5:29 PM] demolish: and i'll fix anything else in future pr
