### ISSUE TITLE
Lag in Guivre spawn room

### ISSUE THREAD

**Issue by mcduff89** [LegionDark/Issues#1705]
**Date & Time**: 
12/6/2017 2:10 pm PST/ but been since update on multiple test dates

**FFXI Client Version (use `/ver`)**: 
30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
Yes

**Character Name**: 
Asurus

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
PLD(99)/WAR(49)

**NPC or Monster or item Name**: 
Guivre

**Zone name**: 
Kuftal Tunnel

**Coordinates (use `!where`)**: 
X: 119, Y: -0.01, Z: 38

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Not at the time, occurs during single or multibox though 

**Steps To Reproduce / any other info**: 
Zone into kuftal from terrigan, lag starts to become present, head into the guivre room and lag so bad can’t perform any actions without 1min+ delay, then everything catches back up and you’re dead. Had Uzi test for me as well to verify it wasn’t just a local issue

**Comment by Uzi904** [comment]
Wasn’t even just room for guivre for me, as soon as I zoned from cape to kuftal, instant 1.7k+ R spike, zoned out from kuftal back to cape, no lag.

**Comment by TeoTwawki** [comment]
lag is happening in random places at random times since the last maintenance..We aren't sure what exactly the cause is yet, but we're hoping we can resolve it when we rebuild to get the next (and so far only remaining) major crash fix in.

**Comment by mcduff89** [comment]
Yeah, noticed the kuftal seems to be constant, figured we’d make a ticket since I hadn’t seen one mentioning kuftal
