### ISSUE TITLE
Anniversary events wants me to be transgender

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1713]
**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 

**Character Name**: 
Tbone

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
Whatever

**NPC or Monster or item Name**: 
http://www.ffxiah.com/item/15416/hume-shorts-1
http://www.ffxiah.com/item/13821/lords-yukata

**Zone name**: 

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
I already got mithra shorts +1, so http://www.ffxiah.com/item/14462/mithra-top-1 would be optimal for an exchange for the hume shorts +1, othewise I'll just toss the hume shorts.

http://www.ffxiah.com/item/13822/ladys-yukata is the obvious exchange for the Lord's Yukata.

**Comment by Jessland86** [comment]
Issue resolved by GM in game.
