### ISSUE TITLE
Craft transfer apply

### ISSUE THREAD

**Issue by myrialeen** [LegionDark/Issues#1716]
**Date & Time**: 
10 december 2017

**FFXI Client Version (use `/ver`)**: 
30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
3017110

**Character Name**: 
Nimueh

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
WHM75, any other 99
picture attached:   [Job](https://image.ibb.co/gJhVpb/img_20171210_163818.png)

**NPC or Monster or item Name**: 
NA

**Zone name**: 
NA

**Coordinates (use `!where`)**: 
NA

**ffxiah.com link (for items issues only)**: 
NA

**Multi-boxing? (multiple clients on same connection)**: 
NA

**Steps To Reproduce / any other info**: 

Ticket sent for Crafting Skill

[My Skill](https://image.ibb.co/ktNrvG/img_20171210_163832.png)
Thank you

**Comment by Heepster03** [comment]
Crafts imported.
