### ISSUE TITLE
Flanhat

### ISSUE THREAD

**Issue by ilyzia** [LegionDark/Issues#1719]
**Date & Time**: 
12/11/17 1:41pm

**FFXI Client Version (use `/ver`)**: 
30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
yes?

**Character Name**: 
Lyzia

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
Blu 86/ rdm 43

**NPC or Monster or item Name**: 
Flan Masque +1

**Zone name**: 
n/a

**Coordinates (use `!where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/26708/flan-masque-1

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
equiped and waited for 30seconds to several minutes til trying to push the use button in items. it still doesnt highlight or let me use

**Comment by TeoTwawki** [comment]
@LegionDark/gm so uh, a few items that weren't yet implemented in darkstar slipped by me when I was putting in the event items. Woops. At least this is an easy to add one. Goldfish scooping and drovers mantle, not so much..

**Comment by ilyzia** [comment]
cool. tyvm
