### ISSUE TITLE
Fey Yin 5-1, not dropping Key Item for Shale

### ISSUE THREAD

**Issue by Valknut4** [LegionDark/Issues#172]
**Date & Time**:  7/18/2015 1:48pm
**Frequency**: 2/2
**FFXI Client Version** 5e679bo267da7133b2b2f39f0d11756fd0e2d67d:
**Character Name**: Shale
**Race**: Elvaan
**Main Job**: Ninja
**Sub Job**: Dancer
**Area & Coordinates**: Qu bia Arena
**Party or Solo**: Party Tunk BLK/WHM got Key item Valknut BRD/WHM Got key item
**NPC Name**: Zeid /// N/A
**Monster Name**:  Archlich Taber'quoan
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**: I'm not sure, the only thing I can think of that is different about Shale, over Tunk and Valknut is that they frequently died and re-raised over the course of the fight. I try'd to test this method 3rd attempt but Shale is tanking and DDing so its hard to manage.

**Comment by R3P0FFXI** [comment]
I assume you are dual boxing this is a common bug when dual boxing. Dont Dual box and the KI will drop

**Comment by TeoTwawki** [comment]
@R3P0FFXI 
> Multi-boxing? (multiple clients on same connection): Yes

Thats why i added it to the template :smiley:

**Comment by R3P0FFXI** [comment]
Die Teo lol :)

**Comment by R3P0FFXI** [comment]
is this still an issue?

**Comment by R3P0FFXI** [comment]
Last chance before this is closed is this still an issue?

**Comment by Valknut4** [comment]
I tried with other players, nothing changed.

**Comment by TeoTwawki** [comment]
@LegionDark/owners  I say just hand multi-boxers any KI and variable needed to move them to next step, its faster and you can check variables with that `@checkvar` command I wrote. KI's no harm is done if you `@addkeyitem` one they already had, so just look for what the script expects to do when they win that BCNM.

**Comment by TeoTwawki** [comment]
@LegionDark/owners that way these multibox issues get closed out instead of sitting here waiting to see if repeating the fight cleared the problem for them.

**Comment by TeoTwawki** [comment]
-*nudge nudge*-

**Comment by Valknut4** [comment]
Yep tried a few more times still nothing, I'll mention it the next time I see a GM on. It's all good dudes :dudes :dancer:

**Comment by TeoTwawki** [comment]
My nudge was at the Legion devs.

**Comment by R3P0FFXI** [comment]
Ok see me in game today and I will check your variables in between some database work

**Comment by Strafeous** [comment]
Ticket resolved, fixed variable and added Key item. 
Successfully obtained 5-2.
Closed
