### ISSUE TITLE
Event moogle not responding

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#1720]
**Date & Time**: 12/11/2017

**FFXI Client Version (use `/ver`)**: 30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: yes

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**:pld99/rdm49 

**NPC or Monster or item Name**: event NPC moogle

**Zone name**: windurst waters/bastok markets

**Coordinates (use `!where`)**: X-50 y-5 z219 (225)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: Talking to the npc moogle for hourly buffs but it doesn't respond, also tried with characters who haven't talked to it for over 24 hrs for buffs/item, still nothing. Also tried the ones in other cities.

**Comment by EpicTaru** [comment]
Talking to the South Sandy Moogle gives me a buff and a random item.  Do you have screenshots of the Moogle not giving you anything?

**Comment by TeoTwawki** [comment]
a little while ago there was an error in the server log about a missing comma that I hotfixed, this was probably right before then

**Comment by TeoTwawki** [comment]
if issue happens again before the 20th of this month (this years event end then) we'll reopen.
