### ISSUE TITLE
Atma of the voracious violet

### ISSUE THREAD

**Issue by kyokofu** [LegionDark/Issues#1721]
**Date & Time**: 
12/11/2017 5:00pm pdt

**FFXI Client Version (use `/ver`)**: 
30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
yes

**Character Name**: 
kyokofukada

**Nation**: 
sandy

**Job(level)/Sub Job(level)**: 
99thf/49blm

**NPC or Monster or item Name**: 
n/a

**Zone name**: 
Abyssea-Attohwa

**Coordinates (use `!where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Atma of the Voracious Violet gives incorrect TP regain. It gives 200TP/tick instead of 20TP/tick.

**Comment by TeoTwawki** [comment]
retail added a zero onto all the tp values (basically the decimal over that you couldn't see before,) so stuff like 20.3 became 203 and for a long time stuff in darkstar wasn't fully up to date. And apparently ffxiclopedia got updated but BG didn't, which is super unusual! so it got an extra zero it shouldn't have when I updated those last. 

https://www.bg-wiki.com/bg/Atma_of_the_Voracious_Violet

http://ffxiclopedia.wikia.com/wiki/Atma_of_the_Voracious_Violet
