### ISSUE TITLE
guild master not taking items

### ISSUE THREAD

**Issue by byfuglien** [LegionDark/Issues#1722]
**Date & Time**: 
12/11/2017  9:14pm est

**FFXI Client Version (use `/ver`)**: 
30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
yes

**Character Name**: 
byfuglien

**Nation**: 
bastok

**Job(level)/Sub Job(level)**: 
blu52/blm26

**NPC or Monster or item Name**: 
npc Faulpie

**Zone name**: 
south san doria

**Coordinates (use `!where`)**: 
x: -192 y:0  z:9

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
trying to get leather to expert lvl 100 beyond, npc wont ask for item to pass the test,also any npc that ask for guild point items wont take item and wont award points

**Comment by TeoTwawki** [comment]
try now, applied a hotfix

**Comment by byfuglien** [comment]
thanks :)
