### ISSUE TITLE
Frame Rate Issue in Caedarva Mire

### ISSUE THREAD

**Issue by AleksandarFFXI** [LegionDark/Issues#1723]
**Date & Time**: 
12/12/2017

**FFXI Client Version (use `/ver`)**: 
30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
3017110

**Character Name**: 
Aleksander

**Nation**: 
Bastok 

**Job(level)/Sub Job(level)**: 
85BLU/42DNC

**NPC or Monster or item Name**: 

**Zone name**: 
Caedarva Mire

**Coordinates (use `!where`)**: 
X:239 Y:-2 Z:-666 (136)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Just be in the zone. Anywhere. Battle, Idle, Walking. Frame Rate drops in the zone and only this zone so far.

**Comment by R3P0FFXI** [comment]
This is not a legion issue
