### ISSUE TITLE
Bastok Mission 3-1 - unable to complet

### ISSUE THREAD

**Issue by Sinnersslayer** [LegionDark/Issues#1724]
**Date & Time**: 12.12.17

**FFXI Client Version (use `/ver`)**: 30171103

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: yes

**Character Name**: Glizdus

**Nation**: Bastok

**Job(level)/Sub Job(level)**: RDM99

**NPC or Monster or item Name**: 

**Zone name**: Beadeaux

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 
Killed more then 20 Copper Quadaves and still getting CS telling me that I have not killed 20.

**Comment by R3P0FFXI** [comment]
@Sinnersslayer  Multi-boxing? (multiple clients on same connection): you are missing info

**Comment by Sinnersslayer** [comment]
Yep, logged off both like You told, loging on the one on which I want to clear the mission

**Comment by Sinnersslayer** [comment]
Nope. After 23 kills still receiving same CS.

**Comment by TeoTwawki** [comment]
MissionStatus zero, needs to be one before beginning to kill Quadav for the mission.

**Comment by TeoTwawki** [comment]
You are missing the cut scene event from Iron Eater in Bastok Metalworks. A bug in Darkstar displays the cs event in pashow anyways even though you are too early for it.

**Comment by Sinnersslayer** [comment]
Ah.... that seems about right
I have missed that talking and now I have received CS while entering Beadeaux.
Thanks Teo and sorry for and for the confusion :wink:
