### ISSUE TITLE
minor: "no item id" talking to the gift moogle

### ISSUE THREAD

**Issue by ediww** [LegionDark/Issues#1726]
**Date & Time**: 2017/12/12 21:26 GMT+2

**FFXI Client Version (use `/ver`)**: 30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: yes

**Character Name**: Tate

**Nation**: Windurst

**Job(level)/Sub Job(level)**: THF/BLM

**NPC or Monster or item Name**: NPC moogle gift giver af F5 (windurst waters at the gate)

**Zone name**: Windurst Waters

**Coordinates (use `!where`)**: x:-5O y:-5 z:216 (122)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: talked to the moogle to get the prize and got "An error occured, could not find the item ID. Please bug report".
![tate_2017 12 12_213104](https://user-images.githubusercontent.com/30444503/33904329-ee042118-df83-11e7-8acb-b1c4efb0c00b.png)

**Comment by TeoTwawki** [comment]
darnit, I forgot to include the random number rolled in that debug print. talking to him a 2nd time got you an item though right?

**Comment by ediww** [comment]
yes, second talk gave me an item.

**Comment by TeoTwawki** [comment]
good. I put thta catch there looking for a broken one but messed up my print so I'll have to live edit that in a few min

**Comment by TeoTwawki** [comment]
It that print triggers again, let me know. There should be other information with it now.

**Comment by ediww** [comment]
Item no 119

**Comment by TeoTwawki** [comment]
thank you, found and fixed source of error
