### ISSUE TITLE
Shinryu BC cannot be initiated

### ISSUE THREAD

**Issue by neoffxi** [LegionDark/Issues#1728]
**Date & Time**: 
12/13/2017 4:56PM EST

**FFXI Client Version (use `/ver`)**: 
30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
yes

**Character Name**: 
Neomorpheus

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
Blu99/Rdm49

**NPC or Monster or item Name**: 
n/a

**Zone name**: 
Abyssea-EmperealParadox

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
Yes (4 characters total)

**Steps To Reproduce / any other info**: 
We tried trading a scholar's stone to initiate the Shinryu BC, but the trade doesn't go thru and can't start the BC. Several players tried (Neomorpheus, Emel, Meyrink, and Epictaru), but same result. We tried zoning a few times, and even reformed the alliance, but still cannot initialize it. 
There are no one else doing the Shinryu BC fight because we are the only ones in the zone.
Edit:
Forgot to mention that we did this BC 2 days ago 20 times, and had no issue initializing and killing Shinryu.

**Comment by EpicTaru** [comment]
Personally verified the above as well.
Also personally verified that other normal BCs work.  I used 20 BS to enter BCNM20 Charming Trio, mobs loaded correctly.  Then left BC successfully as well.

**Comment by spectre99** [comment]
Similar problems with Shin the other day.  The first time it let the person using the stone enter, everyone else saw the battlefield symbol for a second before it disappeared, rest of the party couldn't enter.  Next attempt the person trying to enter blackscreened, rest of the party once again couldn't enter.

**Comment by TeoTwawki** [comment]
problem fixed, tested myself shin can be fought again
