### ISSUE TITLE
Elvaan Gilet in a hume Moghouse Inventory

### ISSUE THREAD

**Issue by neonracer** [LegionDark/Issues#1732]
**Date & Time**: December 14, 2017 @ 1:20 pm

**FFXI Client Version (use `/ver`)**: legion dark latest server ver.

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 

**Character Name**: Neonracer

**Nation**: Bastok

**Job(level)/Sub Job(level)**: Thf 99

**NPC or Monster or item Name**: 

**Zone name**: Batok Mines Moghouse

**Coordinates (use `!where`)**: X0 Y0 Z0 (192) Moghouse inside
![neonracer_2017 12 14_132800](https://user-images.githubusercontent.com/28202863/34008288-cd6e2386-e0d2-11e7-97c0-d81a42b9e079.png)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:  Just hoping it can be swtiched for a Hume Gilet. as I dont know how I got an Elvaan one??? LOL Thank you.

**Comment by Jessland86** [comment]
Taken care of in game by GM.
