### ISSUE TITLE
PUP TP Gain Insanity

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1734]
**Date & Time**: 
Dec 15, 2017

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 

**Character Name**: 
Tbone

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
PUP70-91

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Sometimes

**Steps To Reproduce / any other info**: 

The TP gain automatons get per WS, per hit and per getting hit increases over time.  The longer the pup is out, the higher it increases.  I was able to get it up to 67% TP per hit after a fairly long XP session.  This means the pup can WS, hit once and WS again, or WS, get hit once and WS again.

- This was test Valoredge frame and head.
- I was always level sync'd down.  Unsure if this is important.
- Seems to increase with the number of hits or WSes, not purely based on time.
- Heavy use of fire maneuvers.
- Key attachments include
  - Inhibitor
  - Tension Spring
  - Tension Spring II
  - Strobe
  - Auto Repair
  - Auto Repair II
  - ... others

I think this *might* be related the Inhibitor's Store TP implementation, as I've seen other attachments with behaviors that are abnormal.

**Comment by TeoTwawki** [comment]
lmao... can you open this one on dsp's tracker?

**Comment by tb1** [comment]
Check the Auto-Regen/Refresh one too, as I think they are related.

**Comment by TeoTwawki** [comment]
revision for dsp is f99e83d

**Comment by tb1** [comment]
See https://github.com/LegionDark/Issues/issues/1736
