### ISSUE TITLE
Ix'Aern MNK ??? missing.

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1737]
**Date & Time**: 
Dec 18, 2017

**FFXI Client Version (use `/ver`)**: 
30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
No
3017110

**Character Name**: 
Tbone

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
PLD99

**NPC or Monster or item Name**: 
Ix'Aern MNK
https://www.bg-wiki.com/bg/Ix%27aern#Ix.27aern_.28MNK.29

**Zone name**: 
Grand Palace of Hu'Xzoi

**Coordinates (use `!where`)**: 
-451 0 545 184

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 

The ??? where you are suppose to trade HQ Aern Organs is missing.  Checked both sides, before and after multiple server restarts.  It just fails to spawn.

**Comment by Jessland86** [comment]
Ix'MNK ??? is in the Mithra tower at (D-8). Just confirmed it is spawnable.

**Comment by tb1** [comment]
That's new!  MNK isn't suppose to spawn in the towers, but the hallways (G-7) and (I-7).

I'll try the towers out.

**Comment by tb1** [comment]
Ohh, my bad, I see what I did, I'd dumb.

**Comment by TeoTwawki** [comment]
DSP may have farked up the pos's. if they did feel free to tell'em Ima afkmy day away >.>
