### ISSUE TITLE
Puppet (Soulsoother and Sprirtreaver quest inoperable)

### ISSUE THREAD

**Issue by Celticyheti** [LegionDark/Issues#1738]
**Date & Time**: 12-19-2017@1345 hrs

**FFXI Client Version (use `/ver`)**: 30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: yes

**Character Name**: Geppetto

**Nation**: Windurst

**Job(level)/Sub Job(level)**: PUP 72/DNC 36

**NPC or Monster or item Name**: NPC: Ghatsad

**Zone name**: Aht Urhgan Whitegate

**Coordinates (use `!where`)**: X:33 Y:-7 Z:54 (197)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
Attempted to accept the quest for the Soulsoother or Spiritreaver heads. Completed all previous frame quests. Spoke with Ghatsad and received the dialog to choose which head I wanted, chose the soulsoother head and received dialog of the materials needed to make the item, however at this point the dialog just repeats itself and will not allow you to confirm your choice. Attempted to trade items to Ghatsad with negative results. Tried again, all the steps repeated with the Spiritreaver head and the same thing occurs. Zoned and redid everything again with same results.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/new

**Comment by TeoTwawki** [comment]
*runs and hides*

**Comment by kairoffxi** [comment]
nice deflection!

**Comment by Heepster03** [comment]
```lua
elseif (attachments == 3 and attachmentStatus == 11) then
        if (trade:getSlotCount() == 3) then
            if (trade:getItemQty(2186) == 7) then -- 7x Imperial Mythril Pieces
if (trade:getItemQty(2502) == 1) then -- White Puppet Turban
```
```lua
elseif (trade:getItemQty(4610) == 1) then -- Scroll of Cure II
                        player:tradeComplete();
                        player:setVar("PUP_AttachmentStatus", 12)
                        player:setVar("PUP_AttachmentReady",getMidnight());
                        player:setVar("PUP_AttachmentWait",4);
                        player:startEvent(902);
end
```
I just want to ask if you actually have all 7 of the Imperial Mythril Pieces. I already verified that you have the other items. Your current PUP_AttachmentStatus is 11, and your current PUP_Attachments is 3. So you should be able to theoretically continue.

**Comment by Jessland86** [comment]
I actually completed both of these quests already on LD. No idea if something got changed or not since I did it like a week ago.

**Comment by Heepster03** [comment]
Issue resolved. Was trading incorrect number of items.
