### ISSUE TITLE
Items from VW chapter 1/2 not working (reminding Loki)

### ISSUE THREAD

**Issue by Strafeous** [LegionDark/Issues#174]
So far we've figured out the Influx Earring and Upsurge Earring can't equip at all,
Manibohzo set can't be equipped.
Will continue updating as we figure out what has problems and doesn't.

**Comment by Strafeous** [comment]
Hippomenes socks +1

**Comment by Strafeous** [comment]
Uk'uxkaj cap doesn't work on monk

**Comment by Loki79** [comment]
All set.
