### ISSUE TITLE
Crafting Import

### ISSUE THREAD

**Issue by CaptSparklez** [LegionDark/Issues#1740]
**Date & Time**: 20th Dec 2017

**FFXI Client Version (use `/ver`)**: 30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 3017110

**Character Name**: Hakubai

**Nation**: San D'Oria

**Job(level)/Sub Job(level)**: THF99/DNC49 

**NPC or Monster or item Name**: N/A

**Zone name**: N/A

**Coordinates (use `!where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: Ticket for crafting import. 

[Crafting Screenshot](https://ibb.co/in7k0R)

Thanks a lot, guys!

**Comment by Jessland86** [comment]
Crafts imported.
