### ISSUE TITLE
Item 114 Not Found message when trying to get daily item from Anniversary Moogle

### ISSUE THREAD

**Issue by EpicTaru** [LegionDark/Issues#1741]
**Date & Time**: 
12/15/2017 @ 1655

**FFXI Client Version (use `/ver`)**: 
30171103

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
30171103_1

**Character Name**: 
EpicTaru

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
99THF/49DNC

**NPC or Monster or item Name**: 
Anniversary Moogle (Christmas Event)

**Zone name**: 
South Sandoria

**Coordinates (use `!where`)**: 
X: 57 Y: 2 Z: -26

**ffxiah.com link (for items issues only)**: 
N/A unless Item 114 helps...which it probably won't since the Item Tool and FFXIAH both list Item ID as belonging to My First Magic Kit (http://www.ffxiah.com/item/114/my-first-magic-kit)

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Talk to the Anniversary Moogle, if you are nice (and he's not), the Moogle will try to give you w/e Item 114 should have been, but he doesn't give it to you; instead, he tells you this:
 
![item 114 not found](https://user-images.githubusercontent.com/26195580/34229912-a3527a66-e59b-11e7-9c26-9a1a49d9d887.JPG)

I respectfully request to receive the Wonder Maillot +1 (Item ID: 11277; http://www.ffxiah.com/item/11277/wonder-maillot-1).

**Comment by TeoTwawki** [comment]
when this trips it isn't using your once a day item, talking to it again will re-roll.

And item data 114 should have been a **Korrigan Pricket**

**Comment by EpicTaru** [comment]
Ah, kk and no worries, Teo. Thanks for the explanation!

**Comment by TeoTwawki** [comment]
What day was this when that happened btw? I forgot to ask. I know this would have happened before my last edit but that was awhile ago and shouldn't be possible anymore.

**Comment by EpicTaru** [comment]
12/15/2017 @ 1655

**Comment by TeoTwawki** [comment]
k. prolly right before I got in to hotfix then
