### ISSUE TITLE
Relic Trial NM not counting towards trial credit

### ISSUE THREAD

**Issue by neoffxi** [LegionDark/Issues#1743]
**Date & Time**: 
12/21/2017 1:06PM EST

**FFXI Client Version (use `/ver`)**: 
30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
yes

**Character Name**: 
Neotwo

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
Brd99/Whm49

**NPC or Monster or item Name**: 
Mischievous Micholas (ID: 125)

**Zone name**: 
Yuhtunga Jungle

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
Yes (5 characters)

**Steps To Reproduce / any other info**: 
I killed the NM for relic trial stage 1, and it just didn't give me the kill credit. I attached a screenshot below. Also, I made sure to disable Ashitacast so I do not accidentally swap gear.

Edit:
I forgot to mention that the other trial NMs are working as intended (giving credit).

![neotwo_2017 12 21_131700](https://user-images.githubusercontent.com/34224364/34269479-74f20828-e652-11e7-9356-f9cba89fb95f.png)

**Comment by TeoTwawki** [comment]
have actually seen a related error as of a few days ago and been trying to track it down

**Comment by TeoTwawki** [comment]
might have taken me longer if not for that screenshot  and this report <3

**Comment by TeoTwawki** [comment]
Hotfixed!
@LegionDark/gm please credit player and then we can close this.
```
cTrialCount["relic]"
```
Is the variable name.

**Comment by Jessland86** [comment]
Taken care of by GM in game.
