### ISSUE TITLE
Lumbering Lambert and Bloodtear Baldurf in La Theine Plateau.

### ISSUE THREAD

**Issue by brobrobro187** [LegionDark/Issues#1745]
**Date & Time**: 
12/18/17 thru 12/21/17

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 

**Character Name**: 
Bro

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
74thf/37dnc

**NPC or Monster or item Name**: 

Lumbering Lambert or Bloodtear Baldurf 
**Zone name**: 

La Theine Plateau.
**Coordinates (use `!where`)**: 
East Ram H-9 ish

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Have been killing the East Battering Ram placeholder for 4 days. Have tallied up 0/43 kills on the placeholder to spawn the above NMs. The respawn timer is working correctly for the Battering Rams (4:20) but the NMs will not spawn(10min). I have tested for days because i heard rumor of a 24 hour respawn but i have disproven that aswell. I used my alt in Konschtat Highlands with the same strategy and the NM Rams there are working on the correct 10min pop system. Im not sure what else to try, i will continue drinking while killing Rams to lessen the pain. I need the the item for Silence the Rams quest to further proceed to my Black Belt. Thank you for taking time to read the Ramblings of someone who has gone crazy killing Rams... Pun

**Comment by brobrobro187** [comment]
Unless there is some little Elf on the Shelf mother****er following me around killing it after i log.... Nah im probably just drunk again...

**Comment by R3P0FFXI** [comment]
@brobrobro187 I wont give you the window but I can assure there timer is in the script it is not 10 minutes. It looks like the slot is shared between the pair of them.

**Comment by brobrobro187** [comment]
My bad in the post the 4:20 is 10min irl for the nms its 1 hour not 10min(Lathene). But with the info below... Wtf? Lol its been 4 days and 43 kills... The ones in Lathene are 1 hour pop and Konscant are 8 hours. But i have sighted 6 in Konscant compared to 0 in Lathene. Can you compare the scripts? They might be backwards, i bought my purple belt so i know they exist but i dont know if something got thrown off in an update?

There are two Battering Rams in the area. If you split the pop area into two zones, east and west; the true placeholder always pops in the east. Both Rams have a 10 minute respawn timer.

Minimum respawn time is 1 Hour from last Time of Death.

Can take up to 12 hours to spawn.

**Comment by R3P0FFXI** [comment]
@brobrobro187 this works as intended it is a scripted spawn not a SQL spawn it has window when it opens not a guaranteed pop time.

@TeoTwawki can better verify the math

From what I am seeing if it rolls less then a certain number once the window opens the NM wont pop, If it rolls greater then the NM will Pop. From there depending on how long it has been the HQ will roll for its chance to pop if that window is open.

**Comment by brobrobro187** [comment]
Ok thought it was worth a peek before i gave up. Thanks for your time and keep up the good work

**Comment by brobrobro187** [comment]
LUMBERING LAMBERT SPAWNED! 1/92
