### ISSUE TITLE
Lantern Door will not open in COP mission 

### ISSUE THREAD

**Issue by Cowmanthethird** [LegionDark/Issues#1746]
**Date & Time**: 
12/22 11:30 

**FFXI Client Version (use `/ver`)**: 
30171205_0 (I know it's a version mismatch, I was told to submit anyway though)

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
No

**Character Name**: 
Dantheblue

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
RDM99/DNC99

**NPC or Monster or item Name**: 

N/A
**Zone name**: 
Phomiuna Aqueducts

**Coordinates (use `!where`)**: 
x:98 y:-23 z:59 (122)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Door will not open to complete COP mission 2-3
Tested on two characters on the same version (not by dual boxing, by calling my cousin), one who currently had the mission, and one who had already completed it previously. The door doesn't open no matter what combination of lamps you press, and when another player with the correct version came to help, the door opened, but the CS inside the door did not trigger.
There was also no expected message from the lamps that indicates their element when pressed.

**Comment by R3P0FFXI** [comment]
@Cowmanthethird your version is 6 months old please update and try again

**Comment by Cowmanthethird** [comment]
I updated and no change.
Edited the ticket to have the new version number.

**Comment by EpicTaru** [comment]
Cowmanthethird is not showing on COP mission 2-3.  Cowmanthethird is showing on COP mission 5-3.

**Comment by EpicTaru** [comment]
Thank you for wasting time listing a character in this ticket that wasn't even on the mission stated they are having the issue on.  Thank you for now actually telling us which character is the one with the issue regarding COP 2-3.

**Comment by EpicTaru** [comment]
@Cowmanthethird Was it CMTT or Dan that wasn't getting the CS past the 2 ornate gates?

**Comment by Heepster03** [comment]
It's Dan, since CMTT is already on 5-3.

**Comment by Heepster03** [comment]
Issue has been resolved.
