### ISSUE TITLE
Locked in Mordion

### ISSUE THREAD

**Issue by Beatrix-of-Windurst** [LegionDark/Issues#1748]
**Date & Time**: 2017.12.25

**FFXI Client Version (use /ver)**: 30171103_1

**Server's Expected Client Version matches, yes/no? (use !ecv)**: yes

**Character Name**: Beatrix

**Nation**: The Federation of Windurst

**Job(level)/Sub Job(level)**: RDM27/WHM13

**NPC or Monster or item Name**: N/A

**Zone name**: Mordion Gaol

**Coordinates (use !where)**: X: 700 Y: -400 Z; -620 (65)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: I was auto-jailed for using the command "/debuff 1" after incurring the weakened status while leveling. I was not aware this was off limits. This is the first time I have played in more than a year. Not making excuses. I take full responsibility for my actions and I apologize for my ignorance wholeheartedly. I have since uninstalled the associated addon. I request to be released from Mordion on the grounds that I will never ever do it again. Thank you for your time. ^^;

**Comment by EpicTaru** [comment]
@Beatrix-of-Windurst, welcome back to the server.  Please ensure that you familiarize yourself with the rules of the server, located on our wiki at http://wiki.legiondark.com/Server_Rules.

I'll be online in a minute to release you from jail.

**Comment by EpicTaru** [comment]
Released 12/26/2017
