### ISSUE TITLE
Fomor Paladin in Sacrarium drops wrong key

### ISSUE THREAD

**Issue by Roamin** [LegionDark/Issues#175]
**Date & Time**: July 20th 2015
**Frequency**: Everytime
**FFXI Client Version**: 30150619_2
**Character Name**: Roamin
**Race**: Tarutaru
**Main Job**: Warrior
**Sub Job**: Samurai
**Area & Coordinates**: Sacrarium H-9 
**Party or Solo**: Party
**NPC Name**:  Not applicable
**Monster Name**: Fomor Paladin
**Multi-boxing? (multiple clients on same connection)**: YES , same connection same pc
**Steps To Reproduce The Issue**: Kill Fomor Paladin in Sacrarium

The Fomor Paladins drop item id 1059 Grotto chest key while they should drop item id 1659 Coral Crest key like the other Fomors nearby.

Typo in the item id.

**Comment by TeoTwawki** [comment]
@R3P0FFXI /reminder
Do something with this or link where DSP knows about it/doing something with this.

**Comment by R3P0FFXI** [comment]
Straf can you send this fix to DSP with your next batch

**Comment by Strafeous** [comment]
Yeah, I'll fix the droplist and push it to dsp once I push the new vw stuff and the fixed vw stuff
