### ISSUE TITLE
Crafting Import - Autkastx

### ISSUE THREAD

**Issue by nfaletra** [LegionDark/Issues#1751]
**Date & Time**: 12/25/17 10:25pm MST

**FFXI Client Version (use `/ver`)**: N/A

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: N/A

**Character Name**: Autkastx

**Nation**: N/A

**Job(level)/Sub Job(level)**: N/A

**NPC or Monster or item Name**: N/A

**Zone name**: N/A

**Coordinates (use `!where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: N/A

Crafts Screenshot:
![autkastxcrafts](https://user-images.githubusercontent.com/11480851/34347681-8c294966-e9c2-11e7-84c8-70a40f3805f6.JPG)

Thank you!

**Comment by Jessland86** [comment]
Taken care of by GM in game.
