### ISSUE TITLE
Divine sap HQ results incorrect

### ISSUE THREAD

**Issue by Rihyuh** [LegionDark/Issues#1753]
**Date & Time**: 
12/26/17

**FFXI Client Version (use `/ver`)**: 
30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
yes

**Character Name**: 
Furrow

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
THF 99 / DNC 49

**NPC or Monster or item Name**: 
n/a

**Zone name**: 
Windurst waters (north)

**Coordinates (use `!where`)**: 
X: -184 Y: 11 Z: 267
![screenshot 1](https://user-images.githubusercontent.com/24214123/34367324-9773c4d2-ea66-11e7-9d75-88fdaf05fe64.png)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
HQ a divine sap through sythesis
![furrow_2017 12 26_165550](https://user-images.githubusercontent.com/24214123/34366949-6c285ac8-ea60-11e7-8448-9aedf8a7ce21.png)

**Comment by Raelious** [comment]
PR sent to DSP
