### ISSUE TITLE
Masamune 119 need to check

### ISSUE THREAD

**Issue by o0Persefone0o** [LegionDark/Issues#1756]
Date & Time: 27 -12-2017

FFXI Client Version (use /ver): 30171103_1

Server's Expected Client Version matches, yes/no? (use $ecv):

Character Name: Aurel

Nation: Sandoria

Job(level)/Sub Job(level): sam/drk

NPC or Monster or item Name:

Zone name:

Coordinates (use $where):

ffxiah.com link (for items issues only): http://www.ffxiah.com/item/21019/masamune

Multi-boxing? (multiple clients on same connection): yes

Steps To Reproduce / any other info:

This Great Katana (Masamune 119),  have no empy bonus critical damage and damage critical

**Comment by o0Persefone0o** [comment]
do i do something wrong? with the issue report?

**Comment by EpicTaru** [comment]
No, you're fine, @o0Persefone0o. Just labels we use.

**Comment by o0Persefone0o** [comment]
done :) thank you

**Comment by EpicTaru** [comment]
Already referenced here: DarkstarProject/darkstar#3673

Closing ticket.

**Comment by o0Persefone0o** [comment]
thank you ET
