### ISSUE TITLE
Avatars not able to be summoned in some Aby's areas

### ISSUE THREAD

**Issue by Picklepuss** [LegionDark/Issues#1757]
**Date & Time**:  12/27/17

**FFXI Client Version (use `/ver`)**: 
ver: 30170728_2

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
Says version does not match when I login.

**Character Name**: 
Gucci

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
SMN99/RDM49

**NPC or Monster or item Name**: 

**Zone name**: 
Aby Konchact 

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes 3 accounts.

**Steps To Reproduce / any other info**: 
Zoned my SMN job (Gucci) into Aby-Kon and upon trying to summong avatar I got the message : You can not use (Insert Avatar Name) in this area. I tried ALL avatars.

**Comment by Jessland86** [comment]
30170728_2 That's July's update btw, I would recommend updating. Still doesn't affect the issue, but It might help other things.

**Comment by TeoTwawki** [comment]
will fix soon: its just 3 of the 9 area lost their flags somehow in the last update merge

**Comment by TeoTwawki** [comment]
Corrected values in database for those 2 zones, but it won't take effect till next time the map server reloads.
