### ISSUE TITLE
King Ranpere's tomb grounds tome not functioning

### ISSUE THREAD

**Issue by a404notfound** [LegionDark/Issues#176]
**0443**: 
**Constant**:
**FFXI Client Version**:
**Fourohsix**:
**Hume**:
**Sam**:
**Dan**:
**Area & Coordinates**:
**Party AND Solo**:
**Any**:
**All**:
**No**:
**Pages 1-3 confirmed not working tested by Sami and Fourohsix**:

**Comment by R3P0FFXI** [comment]
Grounds tombs are handled by DSP if a specific tomb is not working this would be an issue they would need to fix. This is usually handled when they update IDs.

**Comment by TeoTwawki** [comment]
Takes more info than "not working" to even look into this. 

Sort of thing i expect:
If book doesn't bring up menu: "book doesn't respond" / "GoV book doesn't bring up menu"
If a mob kill doesn't ever count for a page: "<mobname> doesn't count for <page number>"

Also, your template is filled out kinda crappy/not at all for most fields. If someone doesn't care enough to provide info I don't care enough to try and fix things, ya dig?

**Comment by a404notfound** [comment]
No mobs trigger the count

**Comment by TeoTwawki** [comment]
@R3P0FFXI could be couple mobs having a missing line in `onMobDeath` or a missing global require, or even a typo in the GoV check..

@a404notfound @R3P0FFXI In any case any fixing of this has to be done in DSP directly then pulled into legion after merge.

**Comment by TeoTwawki** [comment]
> No mobs trigger the count

@a404notfound  which mobs are "no mobs"

you are still basically saying nothing but "doesn't work".

**Comment by R3P0FFXI** [comment]
please tell us specifically which pages and which mobs do not work so we can look at this properly failure to do so will result in the closing of this ticket because without the proper info this is a waste of everyone's time

**Comment by R3P0FFXI** [comment]
Last chance to reply before this ticket is closed out, if I do not see a response from you by tomorrow I am closing this ticket as more information is required.

**Comment by TeoTwawki** [comment]
Fixing in DSP.

**Comment by TeoTwawki** [comment]
These will be working after next maint.
