### ISSUE TITLE
Wrong Gender/Race Items from xmas super cool awesome event

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1760]
**Date & Time**: 
Dec 29, 2017

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
Pretty close

**Character Name**: 
Girlieman

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
RUN99

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/11854/novennial-dress
http://www.ffxiah.com/item/11279/savage-top-1

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

Got:
http://www.ffxiah.com/item/11854/novennial-dress
http://www.ffxiah.com/item/11279/savage-top-1

Should be:
http://www.ffxiah.com/item/11853/novennial-coat
http://www.ffxiah.com/item/11280/elder-gilet-1

 Or optionally:
http://www.ffxiah.com/item/26534/arke-corazza-1
http://www.ffxiah.com/item/25898/arke-cosc-1

**Comment by EpicTaru** [comment]
No, you ain't getting what optional items you listed! Lol.

**Comment by TeoTwawki** [comment]
> Character Name:
Girlieman


Moogle thought he was funny see.

**Comment by Jessland86** [comment]
Taken care of by GM in game.
