### ISSUE TITLE
Atma of the Impregnable Tower Incorrect

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1761]
**Date & Time**: 
Dec 30, 2017

**FFXI Client Version (use `/ver`)**: 

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 

**Character Name**: 
Girlieman
Tbone
Treasurehunter

**Nation**: 
Sandy
Windy
Sandy

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

https://www.bg-wiki.com/bg/Atma_of_the_Impregnable_Tower
http://ffxiclopedia.wikia.com/wiki/Atma_of_the_Impregnable_Tower

This should give 30% HPs, instead it gives 50 HPs.

https://github.com/DarkstarProject/darkstar/blob/fb9e67d9edf309bded79935c502c1404d4f97deb/scripts/globals/atma.lua#L132

target:addMod(MOD_HP, 50);

should be

target:addMod(MOD_HPP, 30);

**Comment by Raelious** [comment]
PR sent to DSP
