### ISSUE TITLE
Unable to flag for San d'Oria Mission 4-1: Magicite

### ISSUE THREAD

**Issue by jormundr8** [LegionDark/Issues#1763]
**Date & Time**: 12/30/2017 11:20am

**FFXI Client Version (use `/ver`)**: 30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 3017110

**Character Name**: Rodigen, Aufuren, Oniongarde

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: San d'Oria Mission 3-3 completed. Rank 4 attained. Rank points bar is full and unable to trade crystals any further. Unable to flag for the mission Magicite. I was multiboxing when I completed San d'Oria Mission 3-3: Appointment to Jeuno. Currently no mission is accepted. Tried completing mission 1-1 in hopes that it would reset something and allow flagging for 4-1 without success.

**Comment by R3P0FFXI** [comment]
Once again im going to chalk this up to a possible multiboxing issue. When you are doing missions make sure every character but the one you are doing the mission on is logged off. At this point you probably have screwed up your variables. Log off all characters and shut down ffxi. Login only 1 character and run through your previous mission again do this for all characters 1 at a time.

**Comment by jormundr8** [comment]
Logged all characters out. Logged 1 character in. Previous mission is unrepeatable. Tried another mission. Completed it without a problem. Still unable to flag the next mission.

**Comment by Raelious** [comment]
Are you talking to the NPC in Ru'Lude Gardens to flag the quest, you cant get it from the Gate Guards?

**Comment by Raelious** [comment]
Talked with Player in game, issue is resolved.

**Comment by TeoTwawki** [comment]
![wisdom_of_the_ancients](https://user-images.githubusercontent.com/6871475/34456379-6591bbe6-ed62-11e7-84ed-7bc3f854fe43.png)
