### ISSUE TITLE
Crafting Skill setup Post-Transfer

### ISSUE THREAD

**Issue by zarvlad** [LegionDark/Issues#1768]
**Date & Time**:  Jan 1st 18h20

**FFXI Client Version  
(use `/ver` to see your version)**: N/A

**Server's Expected Client Version matches?  
(use `!ecv` to see expected version)  
(THIS IS A YES OR NO QUESTION!)**: N/A

**Character Name**: Zarv

**Nation**:  Bastok

**Job(level)/Sub Job(level)**: N/A

**NPC or Monster or item Name**: N/A

**Zone name**: N/A

**Coordinates (use `!where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**:  N/A

**Steps To Reproduce / any other info**: 
Set crafting skills as per screenshot. Thank you! :):
http://legiondark.com/forums/download/file.php?id=1229

**Comment by Jessland86** [comment]
Taken care of by GM in game.
