### ISSUE TITLE
setskill gm command

### ISSUE THREAD

**Issue by Jessland86** [LegionDark/Issues#1769]
**Date & Time**: 
1/1/18 

**FFXI Client Version  
(use `/ver` to see your version)**: 
What the ECV is.

**Server's Expected Client Version matches?  
(use `!ecv` to see expected version)  
(THIS IS A YES OR NO QUESTION!)**: 
Yes

**Character Name**: 
GM

**Nation**: 
The best one of course, Sandy.

**Job(level)/Sub Job(level)**: 
n/a

**NPC or Monster or item Name**: 
n/a

**Zone name**: 
n/a

**Coordinates (use `!where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
setskill command seems to be using a range of 1000 now. "!setskill <skill> 100 <target>" will equal 10 instead of 100.  "!setskill <skill> 50 <target>" will be 5.  "!setskill <skill> 1000 <target>" will be 100.

**Comment by TeoTwawki** [comment]
I'll update soon to reflect whatever the \<expletive deleted\> changed in dsp.

**Comment by Jessland86** [comment]
<3 you Teo.
