### ISSUE TITLE
Unable to enter Dynamis.

### ISSUE THREAD

**Issue by Lineaus** [LegionDark/Issues#177]
**Date & Time**: 7-22-2015
**Frequency**:All the time.
**FFXI Client Version**: ver. 30150619_2
**Character Name**: Mittenz and Avatarofhope
**Race**: Mithra and Elvaan
**Main Job**: WHM and RNG
**Sub Job**: RDM and NIN
**Area & Coordinates**: X:35 Y:9 Z:-51 (141)
**Party or Solo**: Party and Solo
**NPC Name**: Trail Markings
**Monster Name**: N/A
**Multi-boxing? (multiple clients on same connection)**: Yes and No. (Mittenz is whmule/Avatarofhope is another player)
**Steps To Reproduce The Issue**: Toggling the trail markings.
The markings only say things like "an unusual arrangement of leaves on the ground" or "the strands of grass here have been tied together."  Two other people in the party are able to enter. Mittenz and Avatarofhope have both gotten the CS for dynamis. They even won Dynamis - Valkrum. But they can't enter the original RoZ dynamis areas, but can enter CoP Dynamis areas.

**Comment by Loki79** [comment]
You meet the requirements?  Rank, Level, etc..

**Comment by Lineaus** [comment]
Yep. We're rank 6, level 99 and got the CS by zoning into Xarcabard. We were able to do Dynamis Valkrum the day before. All of a sudden we can't do RoZ Dynamis zones.

**Comment by TeoTwawki** [comment]
DSP seems to have a bug where if you enter CoP dyna before doing any of the city Dyna, it screws it up and then the cities won't trigger. Is this the case? If so I'll need to manually fix you.

**Comment by Lineaus** [comment]
Yep! That is the case for both Mittenz and Avatarofhope. They did Dynamis Valkrum before any other.

**Comment by TeoTwawki** [comment]
Alright, I will try to catch you when I can be in game to fix you up. And I'd like to track down weather its the variable or the KI part that breaks from that, because I want to fix it in DSP in addition to fixing your character.

**Comment by TeoTwawki** [comment]
https://github.com/LegionDark/Issues/issues/186
Forwarded issue to DSP. Patched Mittenz variable, need to catch Avatarofhope still.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/1813
Forwarded issue to DSP. Patched Mittenz variable, need to catch Avatarofhope still.

**Comment by TeoTwawki** [comment]
Fix both chars now, closing our issue here, DSP knows so hopefully underlying cause gets fixed soon.
