### ISSUE TITLE
WoodWorking Guild points

### ISSUE THREAD

**Issue by Uzi904** [LegionDark/Issues#1778]
**Date & Time**:  1/11/18 12:00pm

**FFXI Client Version  
(use `/ver` to see your version)**: 30171103_1

**Server's Expected Client Version matches?  
(use `!ecv` to see expected version)  
(THIS IS A YES OR NO QUESTION!)**: no

**Character Name**: Uzi

**Nation**: Bastok

**Job(level)/Sub Job(level)**: RNG99/DNC49

**NPC or Monster or item Name**:  Ebony Wand/Ebony Wand+1, Round Shield/around Shield+1

**Zone name**: N. Sandoria

**Coordinates (use `!where`)**: WoodWorking Guild 

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: When I first started crafting, the first guild item (Composite Bow) was excepted for GP. Now that I’ve lvled and ranked up, through out my leveling I’ve been trying to do guild items for points, none of the items are excepted NQ or HQ. I’m aware that there is a bug in the system where you can continuously trade for points, But that’s not my intention or mission, I’m only trying to do it by the proper trade in times and I’m not able to. Has this been disabled cause people were taking advantage or an I just having a strange issue? Any help or insight is greatly appreciated. Thank you

**Comment by ghost** [comment]
If you rank up in the turn in period you are not allowed to earn GP for that day. So if you are around level 11, and you get to 18 and turn in your rank up item you will not be able to do turn ins for that day.

**Comment by Uzi904** [comment]
Ok cool thanks for the insight Rae, crafting is all new to me. I will give it sometime and see if it lets me before ranking up again. Appreciate it

**Comment by ghost** [comment]
No problem. Just be sure to do your GP turn ins before you rank up. The tier of items changes with each rank that's why it locks you out. If anything else arises just PM me.
