### ISSUE TITLE
merits borked

### ISSUE THREAD

**Issue by puffer1221** [LegionDark/Issues#178]
**Date & Time**:  23/07/2015, 07:30am (gmt)
**Frequency**: Constant
**FFXI Client Version**: 30150619_2
**Character Name**: Anofreixx
**Race**: Hume
**Main Job**: Sch
**Sub Job**: Rdm
**Area & Coordinates**: irrelevant
**Party or Solo**: Party or solo
**NPC Name**: Irrelevant
**Monster Name**: Irrelevant
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: Unknown how this occurred, checked merits as soon as i logged on to the game and all my merits have been changed, like my enhancing had been merited but i merited enfeebling, also seems like all job merits have been changed as well. Also it seems its not just myself but all other players in the ls.

**Comment by goferffxi** [comment]
Same issue here and judging by the LS convo everyone has the same problem

**Comment by R3P0FFXI** [comment]
This is a DSP bug side effect of the new update
https://github.com/DarkstarProject/darkstar/issues/1784

**Comment by R3P0FFXI** [comment]
DSP New ticket fix is 

https://github.com/DarkstarProject/darkstar/issues/1788

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/1788

**Comment by goferffxi** [comment]
Will they be reset or will players need to reapply merits?

**Comment by TeoTwawki** [comment]
We dunno wtf DSP is doing about it yet. Even if they say "to bad you are screwed" I'll likely be able to do something to get things back in order so long as people don't try and fix it themselves by wasting merits.

**Comment by TeoTwawki** [comment]
http://legiondark.com/forums/viewtopic.php?f=21&t=901&p=2749#p2749
