### ISSUE TITLE
Jailed; Process of Getting out. 

### ISSUE THREAD

**Issue by e4rthintruder** [LegionDark/Issues#1781]
**Date & Time**: 
12:44 pm

**FFXI Client Version  
(use `/ver` to see your version)**: 
30171205_0

**Server's Expected Client Version matches?  
(use `!ecv` to see expected version)  
(THIS IS A YES OR NO QUESTION!)**: 
no

**Character Name**: 
Earthintruder

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 

BRD63/WHM30

**NPC or Monster or item Name**: 

**Zone name**: 
Mordion Gaol

**Coordinates (use `!where`)**: 
X: -182 Y:11 Z:663

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**:

**Comment by ghost** [comment]
You will have a 48 hour ban from the server, after this time please respond to this issue and/or PM a GM on discord for your release.

Release Time: 1/16/18

**Comment by e4rthintruder** [comment]
Thanks for the reply. Is there anyway to gain a understanding for the ban? I haven't really logged in this week except last night for a moment to grab AH gil. So, I am unsure of the infraction beyond possibly listing too many crystals? If this is better suited for PM, I understand.

**Comment by TeoTwawki** [comment]
From jail reports GMs files, looks like association with a character caught using easyfarm to automate gameplay. So if that wasn't *you* its someone you know who had access to your character at some point, or a friends house to played the game at etc.

**Comment by e4rthintruder** [comment]
Ah, thank you for the info, Teo!
Yeah, I've never heard of Easyframe, so was not me. Must be a classic case of guilty by association.

**Comment by TeoTwawki** [comment]
That's the risk with connected/shared account into. similar situations happen on retail.

**Comment by TeoTwawki** [comment]
This is also why legion doesn't often have harsher punishments.

**Comment by e4rthintruder** [comment]
It's 1/16, so here is my request to be removed from jail on my character. Let me know what steps I need to take. 

Thanks!

**Comment by TeoTwawki** [comment]
1. get a hold of a GM on discord
2. be logged into game when GM shows up to release you.

:)

**Comment by PikaFox** [comment]
Player has been released.
