### ISSUE TITLE
Jailed

### ISSUE THREAD

**Issue by jormundr8** [LegionDark/Issues#1782]
**Date & Time**: 
1/13/2018

**FFXI Client Version  
(use `/ver` to see your version)**: 
version 30171223_0

**Server's Expected Client Version matches?  
(use `!ecv` to see expected version)  
(THIS IS A YES OR NO QUESTION!)**: 
no

**Character Name**: 
Rodigen, Aufuren, Oniongarde, Malleon

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
Rodigen THF99/DNC49
Aufuren WHM99/RDM49
Oniongarde PLD99/WAR49
Malleon THF99/DNC49

**NPC or Monster or item Name**: 

**Zone name**: 
Mordion Gaol

**Coordinates (use `!where`)**: 
x:-620 y:12 z:661

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**:

**Comment by ghost** [comment]
You will have a 72 hour ban from the server, after this time please respond to this issue and/or PM a GM on discord for your release.

Release Time: 1/16/18

**Comment by jormundr8** [comment]
Am I eligible for release?

**Comment by Jessland86** [comment]
@jormundr8 Please log in your characters.

**Comment by jormundr8** [comment]
Logging them in now.

**Comment by Jessland86** [comment]
Please log back in Malleon if you are available to do so.

**Comment by jormundr8** [comment]
Sorry I had to run. Malleon has been deleted.
