### ISSUE TITLE
BRD unlock quest CS freeze

### ISSUE THREAD

**Issue by Terkel2** [LegionDark/Issues#1787]
**Date & Time**: 
17. Jan. 2018

**FFXI Client Version  
(use `/ver` to see your version)**: 
30171205_0

**Server's Expected Client Version matches?  
(use `!ecv` to see expected version)  
(THIS IS A YES OR NO QUESTION!)**: 
No

**Character Name**: 
Bromance

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
BLM56/--

**NPC or Monster or item Name**: 

**Zone name**: 
Buburimu

**Coordinates (use `!where`)**: 
X: -245 Y: 16 Z: -279 (143)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Clicking the runes on the beach, to start CS / the runes are called Five of Spades on my screen.

The CS starts up but the NPC don't show and the CS stop after the second line of text

**Comment by R3P0FFXI** [comment]
@Terkel2 you have a version mismatch which is why the CS is locking you are on version 30171205_0 the server is on 30171103_1 you will need to wait until we update.
