### ISSUE TITLE
I forgot account Information and was wondering if It could be reset.

### ISSUE THREAD

**Issue by Dionuss** [LegionDark/Issues#1789]
**Date & Time**: 

**FFXI Client Version  
(use `/ver` to see your version)**: 

**Server's Expected Client Version matches?  
(use `!ecv` to see expected version)  
(THIS IS A YES OR NO QUESTION!)**: 

**Character Name**: Domant

**Nation**: 
San'doria

**Job(level)/Sub Job(level)**: 
25 rdm

**NPC or Monster or item Name**: 

**Zone name**: 

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**:

**Comment by R3P0FFXI** [comment]
@Dionuss please contact me on Discord so we can discuss this

**Comment by R3P0FFXI** [comment]
PLayer could not verify all required information password/account unable to be reset
