### ISSUE TITLE
Pets Unavailable in Elshimo Lowlands Region

### ISSUE THREAD

**Issue by brobrobro187** [LegionDark/Issues#1791]
**Date & Time**: 
1/19/18

**FFXI Client Version  
(use `/ver` to see your version)**: 

**Server's Expected Client Version matches?  
(use `!ecv` to see expected version)  
(THIS IS A YES OR NO QUESTION!)**: 

**Character Name**: 
Bro

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
Bst / Drg

**NPC or Monster or item Name**: 

**Zone name**: 
Elshimo Lowlands Region

**Coordinates (use `!where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Unable to Summon Jug Pets or use Call Wyvern in this zone. I havnt tested Summoner but Bst & Drg Call Pets do not work.

**Comment by EpicTaru** [comment]
What zones specifically, please.

**Comment by brobrobro187** [comment]
Sorry forgot about that:
Yuhtunga Jungle at G-11
To be specific

**Comment by brobrobro187** [comment]
Thanks
