### ISSUE TITLE
Purchasing Teal Slops gives me Teal Pigaches

### ISSUE THREAD

**Issue by Elana1** [LegionDark/Issues#1792]
**Date & Time**: 
1/20/2018 13:50 est

**FFXI Client Version  
(use `/ver` to see your version)**: 

30171103_1

**Server's Expected Client Version matches?  
(use `!ecv` to see expected version)  
(THIS IS A YES OR NO QUESTION!)**: 

Yes

**Character Name**: 

Roko

**Nation**: 

Bastok

**Job(level)/Sub Job(level)**: 

99WHM/99RDM

**NPC or Monster or item Name**: 

Cruor Prospector

**Zone name**: 

Abyssea - Konschtat

**Coordinates (use `!where`)**: 

132.000, -72.851, -822.00

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

Yes

**Steps To Reproduce / any other info**: 

![image](https://user-images.githubusercontent.com/34110701/35186882-826caa4a-fde9-11e7-9ea8-9d154610465b.png)

**Comment by Elana1** [comment]
It does it in all three zones

**Comment by EpicTaru** [comment]
https://github.com/LegionDark/Issues/issues/1758
