### ISSUE TITLE
Orcish Overlord & Overlord Bakgodek both spawned at once (should be mutually exclusive spawns)

### ISSUE THREAD

**Issue by technicolour24k** [LegionDark/Issues#1793]
**Date & Time**:
20/01/18 - 18:52GMT

**FFXI Client Version  
(use `/ver` to see your version)**:
30171103_1

**Server's Expected Client Version matches?  
(use `!ecv` to see expected version)  
(THIS IS A YES OR NO QUESTION!)**:
Yes

**Character Name**:
Hit

**Nation**:
San d'Orian R5

**Job(level)/Sub Job(level)**:
BLM67/WHM33

**NPC or Monster or item Name**:
Orcish Overlord & Overlord Bakgodek

**Zone name**:
Monastic Cavern

**Coordinates (use `!where`)**:
X:202 Y:0 Z:-77 (17)

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**:
No

**Steps To Reproduce / any other info**:
Unknown. I entered Monastic Cavern via the entrance in Davoi requiring the Crimson Orb on the upper level. Based on my understanding of retail (both from Wiki and my own camping of Overlord Bakgodek), Orcish Overlord and Overlord Bakgodek are a shared spawn and should not be able to exist at the same time. Not sure if this is an issue, or if it is something that has been updated for this server.

**Comment by ghost** [comment]
This is the same with all of the old beastking NMs.

**Comment by Jessland86** [comment]
The 3 beastmen kings are custom here.
