### ISSUE TITLE
Rakshas Incorrect Model.

### ISSUE THREAD

**Issue by Larikun** [LegionDark/Issues#1798]
**Date & Time**: 1/25/2018

**FFXI Client Version  
(use `/ver` to see your version)**:  30171103_1

**Server's Expected Client Version matches?  
(use `!ecv` to see expected version)  
(THIS IS A YES OR NO QUESTION!)**:  Yes

**Character Name**:  Plaxis

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  PLD99/THF49

**NPC or Monster or item Name**: Rakshas

**Zone name**:  Abyssea: Vunkerl

**Coordinates (use `!where`)**:  X: -203 Y: -39 Z: -28 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  Yes

**Steps To Reproduce / any other info**: 
Note: The Coordinates above are to the pop location.
I haven't played retail, but I can assume at the very least that the model is entirely incorrect given the guides I've used to get the pop items to pop this NM. In an old closed issue (#1364) apparently this was fixed, but right now the current model is similar to Quasimodo in the same zone. This NM should be a tiger I believe. I'm also assuming his move set is entirely wrong, but I honestly don't know what his abilities should even be.

Small edit: Even Rakshas's drop table is copied from Quasimodo, the only difference between the two is the name as far as I can tell.

**Comment by TeoTwawki** [comment]
@R3P0FFXI sounds like pool ID overlap
