### ISSUE TITLE
crash every time

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#18]
**Date & Time** 26/05/2015
**Frequency**: always
**FFXi Client Version**: 
**Character Name**: Itachioax
**Race**: Hume
**Main Job**: THF
**Sub Job**: NIN
**Area & Coordinates (Type @where to get this info.)**: Port Ejuno
**Party or Solo**: solo
**NPC Name**: none
**Monster Name**: none
**Steps To Reproduce The Issue**:
1. im trying to log, but every time i got crashed, i can select my char, then it load, when im in, it load for a bit then i got the crash

**Comment by R3P0FFXI** [comment]
Please try reupdating FFXI if you can move and crash when going from 1 area to another it sounds like corrupted dat files

**Comment by itachioax** [comment]
Please try reupdating FFXI if you can move and crash when going from 1 area to another it sounds like corrupted dat files


—


actually i cant move from 1 area, just keep loading for 3 seconds then i crash, already reupdate my ffxi, but not im getting pol-0033 i dont know what to do =(, before this happen, batman try to fix my ki

**Comment by atom0s** [comment]
Can you do something for us to validate your FFXi install:
 * Open PlayOnline viewer. 
 * Go to Check Files.
 * In the drop down, you should see Final Fantasy XI and a version number.

Please post that version number for Final Fantasy XI here.

**Comment by R3P0FFXI** [comment]
Forwarded off to atom0s to verify this is not a packet issue. Character is crashing for me as well when I login with it on Ashita

**Comment by R3P0FFXI** [comment]
User confirmed issue is resolved and he is now in game

**Comment by TeoTwawki** [comment]
This turned out to be related to legions server message. The big question is why it didn't hit any other players.
