### ISSUE TITLE
Armillaria cannot be spawned by trading a Shockshroom in abyssea Vunkerl

### ISSUE THREAD

**Issue by Roamin** [LegionDark/Issues#181]
**Date & Time**: July 23 2015
**Frequency**: Everytime
**FFXI Client Version**: 30150619-2
**Character Name**: Roamin
**Race**: Tarutaru
**Main Job**: Warrior
**Sub Job**: Samurai
**Area & Coordinates**: Abyssea Vunkerl ??? at F-7
**Party or Solo**: Party
**NPC Name**: ???
**Monster Name**: Armalliaria
**Multi-boxing? (multiple clients on same connection)**: Yes, same pc
**Steps To Reproduce The Issue**: Trade a shockshroom to the ??? and Armalliaria will not spawn at all.

**Comment by Loki79** [comment]
Fixed.
