### ISSUE TITLE
R0 > DC > 3305

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#182]
Date & Time: 7/24/2015 10.50 AM GMT+1
Frequency: First time
FFXI Client Version: 30150629_2
Character Name: Thranduil
Race: Hume
Main Job: THF
Sub Job: DNC
Area & Coordinates: Rolanberry fields (D-11)
Party or Solo: Solo
NPC Name: n/a
Monster Name: n/a
Multi-boxing? (multiple clients on same connection): No
Steps To Reproduce The Issue: I've got a R0 and then DC; I try to log back in and I still get "Error code: FFXI-3305 Unable to connect to world server. Specified operation failed." The website says server is up and people are logged on.

**Comment by R3P0FFXI** [comment]
Duplicate issue 

https://github.com/LegionDark/Issues/issues/180
