### ISSUE TITLE
Heka's kalasiris all stats doesn't work

### ISSUE THREAD

**Issue by army19832** [LegionDark/Issues#183]
Heka's kalasiris body doenst give any stats
Should give: DEF 51 MND +17 Cure potency +15% Adds refresh effect sphere:enhances fast cast effect set: adds refresh effect

**Comment by R3P0FFXI** [comment]
Please resubmit with the required troubleshooting template

**Comment by Loki79** [comment]
Fixed.  Will be in next maint
