### ISSUE TITLE
Treasure pool vanished!

### ISSUE THREAD

**Issue by goferffxi** [LegionDark/Issues#184]
In Legionhall Mul with Galego, galegobr Sadfahdina, Hickss Castortroy Takeno. had items in treasure pool 4 x lvl 100 body pieces and sp,e tanzanite jewels, Treasure pool vanished with all items.
![img_20150726_000036](https://cloud.githubusercontent.com/assets/12684459/8891624/fcd743fe-3329-11e5-85ac-60658d5c7646.png)
![img_20150726_000043](https://cloud.githubusercontent.com/assets/12684459/8891623/fcd5fd50-3329-11e5-8783-207534625153.png)

**Comment by Strafeous** [comment]
Ticket resolved
Re-killed boss for Gofer
Worked on trying to recreate the alliance bug but no-go. 
Used terminate while party leader and didn't break the loot pool. I'll work on this some more.
