### ISSUE TITLE
Karieyh Armor Set Moogle Wont Upgrade to 109

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#185]
**Date & Time**: 7/26/15
**Frequency**:Repeatedly
**FFXI Client Version**:30150619_2
**Character Name**: Takeno
**Race**: Hume
**Nation**:SanDoria
**Main Job**:WAR99
**Sub Job**:DNC49
**Area & Coordinates**: (J-5) Rolanberry Fields 
**Party or Solo**: Solo
**NPC Name**: Moogle
**Monster Name**:
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Takeno Traded Karieyh NQ piece +10 Tanzanite Jewel  (Legion Points@ 5800)  Tried Head and Body both did not work :(  

This is Daedrik posting for him because he only speaks Portuguese ^^;

**Comment by Loki79** [comment]
I'll look at this when I get home later tonight.

**Comment by Loki79** [comment]
Fixed.
