### ISSUE TITLE
Rank mission 5-1 Burnt Seal key item

### ISSUE THREAD

**Issue by kermit69** [LegionDark/Issues#187]
**Date & Time**:  7/27/2015,  Around 4:00 pm PST
**Frequency**: 
**FFXI Client Version**: 30150629_4
**Character Name**: Kermit
**Race**: Tarutaru
**Nation**: Windurst
**Main Job**: Samurai 99
**Sub Job**: Warrior 49
**Area & Coordinates**: Fei Yin @ Qu'Bia arena(posted after i was done so no exact coordinates sorry)
**Party or Solo**: Party
**NPC Name**:  
**Monster Name**: Archlich Taber'Quaon (Rank mission 5-1 boss for Burnt Seal Key Item)
**Multi-boxing? (multiple clients on same connection)**: Had another dsp server open during fight.
**Steps To Reproduce The Issue**: Didnt redo fight, GM fixed the issue for me.

**Comment by Strafeous** [comment]
Fixed Variable and KI
Ticket resolved
