### ISSUE TITLE
BLU spell lv 56 "feather barrier"

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#188]
Date & Time: July 28th 2015
Frequency: Everytime
FFXI Client Version: 30150619_2
Character Name: Thranduil
Race: Hume
Main Job: BLU
Sub Job: DNC
Area & Coordinates: Misareaux Coast (G-5)
Party or Solo: solo
NPC Name: n/a
Monster Name: Dyatrima
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue: I seem to be unable to learn this spell from greater birds ( blu 57, skill capped; tried for hours). The "blu spell tool" on the website flags this spell "Invalid spell id given." Are these two things related? Thank you.

**Comment by Kaoriasada** [comment]
I did test thing for about an hour and I couldn't learn the spell off Dyatrimas either.

**Comment by Rigsta** [comment]
Gonna throw in a "ditto" here.  Note also that it says "invalid spell ID given" when checking it on the website:  http://legiondark.com/?p=blue&id=574

**Date & Time**: 16/08/2015 ~22:00 UTV
**Frequency**: Constant
**FFXI Client Version**: 30150730_1
**Character Name**: Rigsta
**Race**: Hume
**Nation**: Bastok
**Main Job**: BLU 61
**Sub Job**: WAR 30
**Area & Coordinates**: Blue spots here : http://www.ffxidb.com/zones/114/diatryma
**Party or Solo**: Solo
**NPC Name**: N/A
**Monster Name**: Diatryma
**Item ID Number -- Obtained from FFXIAH** N/A
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Stab with onion sword until it casts feather barrier, then 3,000TP spirits within and blue magic spam for great justice.

I witnessed the ability being used at least 20 times, never learned.

**Comment by TeoTwawki** [comment]
Loki or myself will look into it in DB soonish.

**Comment by Rigsta** [comment]
Just learned it from a Diatryma, and I see it's not displaying an error message when I view it on the website any more.  Thanks for the fix.
