### ISSUE TITLE
Equipment/AH: Plastron

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#19]
**Date & Time**: 5/27/2015
**Frequency**: Constant
**FFXi Client Version**:30150508_8
**Character Name**: Daedrik
**Race**:Elvaan
**Main Job**:PLD
**Sub Job**:RDM
**Area & Coordinates (Type @where to get this info.)**:
**Party or Solo**: both
**NPC Name**: AH
**Monster Name**:
**Steps To Reproduce The Issue**: Try to sell Plastron lvl 71 DRK Body armor for listed amount (500.000g).  AH takes the item it list's it on sale but after the week has passed returns it to your inbox as unsold.

**Comment by R3P0FFXI** [comment]
Plastron is no longer 500k in the system the price was adjusted to 250k, +1 300k
