### ISSUE TITLE
Myochin Kabuto +1 + 20 Aptant ishis not work

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#190]
Date & Time: 28/07/2015, 15:00pm
Frequency: Constant
FFXI Client Version: 30150619_2
Character Name: Aurel
Race: Hume
Main Job: Sam
Sub Job: Drk
Area & Coordinates: Tavnazian Safehold
Party or Solo: Party or solo
NPC Name: moogle 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:moogle Tavnazian Safehold, moogle not receive the materials for the af Wakido Kabuto. . You can not make reforge Myochin Kabuto +1 + 20 Aptant ishis

**Comment by Loki79** [comment]
Was a typo in the script, all fixed.
