### ISSUE TITLE
My character is stuck

### ISSUE THREAD

**Issue by army19832** [LegionDark/Issues#191]
**Date & Time**: 28 july 2015 
**Frequency**: everytime
**FFXI Client Version**:30150629_2
**Character Name**: Arnon
**Race**: mithra
**Nation**: sandoria
**Main Job**: sam 90
**Sub Job**: war 45
**Area & Coordinates**: i dont know because i found error after maint but i was in aby atthowa
**Party or Solo**: party
**NPC Name**: none
**Monster Name**: none
**Multi-boxing? (multiple clients on same connection)**: nope
**Steps To Reproduce The Issue**: Hi all my character Arnon is stuck in abyssea Atthowa. I left her there afk for 1h and after i found server off because maint started. now after maint is finished i can't login and i get error 3305 on login. stuck tool doesnt works. plz help me, thank you

**Comment by TeoTwawki** [comment]
i fixed this earlier, didn't realize there was an open issue for it but I saw that entire party including you out in Abyssea Attohwa so I cleared the account sessions and parties table data when we rebooted today.
