### ISSUE TITLE
Academic's mortarboard not restored + mp 

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#192]
Date & Time: 29/07/2015, 10:00am
Frequency: Always
FFXI Client Version: 30150619_2
Character Name: Aurel
Race: Hume
Main Job: Sch
Sub Job: Rdm
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name: moogle 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:Academic's mortarboard , not restored more mp, only drains 2hp / tick.......Scholar's Mortarboard not restored more mp, only drains 1hp / tick...>>>>>>>>>>>>>>>> ....and    WikiiBG          Academic's Mortarboard - Enhances "Sublimation" effect
Level 99 Scholar, no equipment (lose 2 HP/tick)
986 HP -> 964 HP (22 HP lost, 96 MP gained)
964 HP -> 944 HP (20 HP lost, 88 MP gained)
944 HP -> 924 HP (20 HP lost, 88 MP gained)
924 HP -> 870 HP (54 HP lost, 224 MP gained)

There is supposed to be 8 MP gained for every 2 HP lost, so it seems there is an extra 8 MP to go along with the MP gained from all ticks. (Ex: 54 HP lost in 27 ticks. (27 ticks)(8 MP/tick) = 216 MP. 216 MP + 8 MP = 224 MP)

Academic's Mortarboard (lose 4 HP/tick)
870 HP -> 770 HP (100 HP lost, 260 MP gained)
1003 HP -> 959 HP (44 HP lost, 120 MP gained)

Looks like 10 MP gained for every 4 HP lost, and that there is an extra 10 MP to go along with the MP gained from all ticks. (Ex: 100 HP lost in 25 ticks. (25 ticks)(10 MP/tick) = 250 MP. 250 MP + 10 MP = 260 MP.)

**Comment by R3P0FFXI** [comment]
Unfortunately the MODS for this  have not been created in DSP yet so this is not possible

**Comment by nekrol** [comment]
they can me back 20 ''haelan''?for another use or block the drain 2hp

**Comment by R3P0FFXI** [comment]
Huh? Sorry im not sure what you are asking but no we wil not refund any purchases as eventually  the MODS will be added
