### ISSUE TITLE
Lost All KI's

### ISSUE THREAD

**Issue by Athomik** [LegionDark/Issues#193]
**Date & Time**: 29July 2015  17:30
**Frequency**:Well i just joined yesterday so 1st time this happen
**FFXI Client Version**:Ver.30150619_2
**Character Name**:Athomik
**Race**:galka
**Nation**:bastok
**Main Job**:mnk37
**Sub Job**:dnc15
**Area & Coordinates**:well 1st time i saw no ki's was at bastok after trying do the tele command and wasn't working so i check ki's and none was there besides portal charm
**Party or Solo**:solo
**NPC Name**:....
**Monster Name**:....
**Multi-boxing? (multiple clients on same connection)**:no only play solo
**Steps To Reproduce The Issue**:well 1st time i saw no ki's was at bastok after trying do the tele command and wasn't working so i check ki's and none was there besides portal charm even all maps gone

**Comment by R3P0FFXI** [comment]
Please get on IRC we will need more details

**Comment by Athomik** [comment]
where is the irc?

**Comment by Kaoriasada** [comment]
http://rizon.net/
Our channel is #legionFFXI.

**Comment by TeoTwawki** [comment]
For Legion GMs:
`@addallmaps <t>`
`@addkeyitem <KeyItem ID> <t>`
While targetting the player.

**Comment by TeoTwawki** [comment]
Also for Legion GMs:
The list of KeyItem IDs can be found here: https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/keyitems.lua

**Comment by Kaoriasada** [comment]
I have no problem with giving him back his KI's, but I need someone to clear for me what KIs are OK to give him.

**Comment by TeoTwawki** [comment]
@Kaoriasada will discuss that in IRC admin channel

**Comment by Kaoriasada** [comment]
Athomik has all his KIs back now.
