### ISSUE TITLE
AH/SEA/LS "Search Failed"

### ISSUE THREAD

**Issue by iroofpez** [LegionDark/Issues#195]
I apologize for asking this here, but I wasn't sure where else to go. When I try to view the AH, /sea all, or LS list, I get a "Search Failed" message. Someone in the LS said I might have an older version of polboot and that I should try Ashita. Ashita just crashes and says "polboot" stopped working. Any advice on what I can do to fix this?

Thanks!

**Date & Time**: 7/29/15, 5:16 PM
**Frequency**: Persistent
**FFXI Client Version**: 
**Character Name**: Bear
**Race**: Galka
**Nation**: San d'Oria
**Main Job**: Warrior
**Sub Job**:
**Area & Coordinates**: N/A
**Party or Solo**: N/A
**NPC Name**: N/A
**Monster Name**: N/A
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Attempting to view AH.

**Comment by Kaoriasada** [comment]
Can you type /ver in-game and get me your FFXI client version?  Thanks.

**Comment by Kaoriasada** [comment]
Spoke to Bear/Valefor in-game.  Their issue is resolved.
