### ISSUE TITLE
Rugiette

### ISSUE THREAD

**Issue by Kaoriasada** [LegionDark/Issues#196]
7/29/2015, 9:58PM
Consistent
30150629_4
Halsey
Mithra
San d'Oria
Red Mage
Ninja
Port San d'Oria
X 67 Y -8 Z -75
Party
Rugiette
N/A
Not multiboxing

Rugiette gives the option to buy magic, but when you choose a category (White or Black magic) all communication with the NPC cancels and she doesn't give you a buy/sell menu.  The NPC next to her (Regine) works properly and sells magic, you have to go through the same process to buy magic.

Notes: I'm 99.9% sure that on retail you're not suppose to be able to talk to Rugiette to get that dialogue/menu, only Regine.

**Comment by TeoTwawki** [comment]
You are correct, somebody in DSP derped. In retail she just has some generic dialog. I'll see about correcting it when I have time.

**Comment by TeoTwawki** [comment]
Thanks for reporting.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/1843

**Comment by R3P0FFXI** [comment]
This has been merged into DSP and has been pulled into Legion as of last maint and should now be working
