### ISSUE TITLE
Octave club stats not working

### ISSUE THREAD

**Issue by maikuru23** [LegionDark/Issues#197]
**Date & Time**:  4:30 PM PST
**Frequency**:  Constantly
**FFXI Client Version**:  30150619_2
**Character Name**:  Maiku  (posting for others having issue but I troubleshot on maiku too)
**Race**:  Taru
**Nation**:  Bastok
**Main Job**:  Ninja
**Sub Job**:  Warrior
**Area & Coordinates**:  X:-159   T:-40   Z:419   (184)
**Party or Solo**:  Solo
**NPC Name**: N/A
**Monster Name**:  Light Elemental
**Multi-boxing? (multiple clients on same connection)**:  Only 1 client
**Steps To Reproduce The Issue**:  Change to NIN/BLM/WAR/RDM/PLD, equip octave club and go to Ru'Aun Gardens at said location, attack a light elemental(or any mob anywhere) and see multi hit on weapon does not activate.  At lvl99 octave club stats are broken.

**Comment by Kaoriasada** [comment]
I just tested this myself, it's not working.  On top of that, not sure if this is intentional or not, but I couldn't equip the club unless I was level 99.  Any job undre 99 it would show up as equipable, but it wouldn't equip if you tried to put it on.

**Comment by Loki79** [comment]
Fixed. Be in next maint.
