### ISSUE TITLE
Mog safe showing xx/50

### ISSUE THREAD

**Issue by jhalim83** [LegionDark/Issues#198]
**Date & Time**: 07/31/2015
**Frequency**: Just trfed from retail so first time
**FFXI Client Version**: 30150629_4
**Character Name**: Hijikata
**Race**: Hume
**Nation**: Sandoria
**Main Job**: War 
**Sub Job**: Nin
**Area & Coordinates**: Sandoria Mog House x:0 y:0 z:0 (194)
**Party or Solo**: Solo
**NPC Name**: Moogle
**Monster Name**:
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Mog safe is showing 50/50 on original retail server it was 80/80

**Comment by TeoTwawki** [comment]
@jhalim83 was your character imported form another server or did you start as a new character here on Legion?

**Comment by TeoTwawki** [comment]
oh ima dumbass you had that info in your templated report.

**Comment by TeoTwawki** [comment]
Just fixed about 100 players storage info having been set incorrectly, I will see to it the import process sets them correctly in the future.
