### ISSUE TITLE
Blue Mage Relic Armor cannot get in dynamis.

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#199]
When i was in dynamis farming Mirage Jubbah it drop but i cannot get because it saying i has allready in inventory/storage, but when i check it i can't see any body from blue mage. GM was trying to gimme another item but it say, "You cannot get some item when you has one some item" LOLs

**Comment by TeoTwawki** [comment]
https://github.com/LegionDark/Issues/commit/f827c0ae75fcfb947f3c11a0d7dd373c79b1cec4 /HallOfShame

**Comment by TeoTwawki** [comment]
Next time, remember to fill out the template properly when reporting.

**Comment by TeoTwawki** [comment]
-*sticks R3 with it*-

**Comment by R3P0FFXI** [comment]
Gave user 28630
