### ISSUE TITLE
Equipment/Ammo: Fracas Grenade

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#20]
**Date & Time**: 5/27/2015
**Frequency**:Constant
**FFXi Client Version**: 30150508_8
**Character Name**: Daedrik
**Race**: Elvaan
**Main Job**: PLD
**Sub Job**:RDM
**Area & Coordinates (Type @where to get this info.)**:
**Party or Solo**:both
**NPC Name**: Ammo slot: Fracas Grenade
**Monster Name**:
**Steps To Reproduce The Issue**: Equip and see the +5 STR and the -50 Fire resist Not register.

**Comment by Loki79** [comment]
done.  be in next maint.
