### ISSUE TITLE
ZMN Tier 2 Wrong Mob Skills 

### ISSUE THREAD

**Issue by Lineaus** [LegionDark/Issues#200]
**Date & Time**:  July 30, 2015
**Frequency**: A lot
**FFXI Client Version**:
**Character Name**: Lineaus
**Race**: Elvaan
**Nation**: Sandoria
**Main Job**: Thief
**Sub Job**: War
**Area & Coordinates**: Woajam Woodlands and Mamook
**Party or Solo**: Party
**NPC Name**:N/A
**Monster Name**:Iriz Ima and Iriri Samariri
**Multi-boxing? (multiple clients on same connection)**:Yes
**Steps To Reproduce The Issue**:
Iriz Ima is a Marid but it keeps spamming Frog Chorus skill which charms. Don't know if it's supposed to or not. Iriri Samariri, a ZNM of the same tier, is a frog but doesn't even use the skill at all. Just wondering if maybe somehow it was moved over or put into the wrong one?

**Comment by Kaoriasada** [comment]
Tested for Loki.  Does use Frog Chorus.

**Comment by TeoTwawki** [comment]
double issue: another mob had wrong mobFamily ID in one of its skills, which gave it to this mob (I believe this is now fixed in Legions code base and server won't notice till next maint) and mob despawn time set improperly/not at all (should be some time before it depops, not right away).

**Comment by TeoTwawki** [comment]
...Must have been funny to see that elephant sing!

**Comment by Loki79** [comment]
Despawn is set to 3 min.  A lot of retail mobs work the same way though, if all players are charmed mob goes poof.  Example:  If all players are charmed, Yalungur will despawn.

**Comment by TeoTwawki** [comment]
That's strange, if they are all charmed they should have that 3 min to hope charm wore and re-engage it. Something is wrong in DSP there.
