### ISSUE TITLE
2-3 Journey abroad

### ISSUE THREAD

**Issue by Nightsking** [LegionDark/Issues#201]
**Date & Time**:  8/02/15
**Frequency**: first time 
**FFXI Client Version**: 30150619_2
**Character Name**: Nightsking
**Race**: elvaan
**Nation**: sandy
**Main Job**: monk 
**Sub Job**: dancer
**Area & Coordinates**: bcnm 2-3  Journey abroad was trying to do the dragon in bastok
**Party or Solo**: solo
**NPC Name**: halver
**Monster Name**: Burning circle/black dragon 
**Multi-boxing? (multiple clients on same connection)**: nope
**Steps To Reproduce The Issue**:didn't get KI to go into the dragon fight "no idea first time it happened to me"

**Comment by Kaoriasada** [comment]
Talk to the last NPC you got a CS from, sometimes they don't take.

**Comment by Nightsking** [comment]
Ok I just tried to talk to the last person like you told me to do then check all the NPC's in the quest and it still didn't progress or give me a KI

**Comment by Kaoriasada** [comment]
His var was set to 0.  I corrected it and he got the CS, and then got into the dragon fight with no issue.  Closed.  :)
