### ISSUE TITLE
Auction House malfunction

### ISSUE THREAD

**Issue by Kaoriasada** [LegionDark/Issues#202]
The "crystal" category doesn't display items, it shows as it would if the search server were down.  "Alchemy 2" and "Misc. 2" don't work either (I don't think they ever have though) and every other category is working properly.  
The "buyback" feature isn't functioning (That's off the word of players).

You can't cancel an item you've put up for sale because none of the items you have for sale will show.

**Date & Time**: 8/3/2015, 18:00:03
**Frequency**: Consistent
**FFXI Client Version**: 30150629_4
**Character Name**: Halsey
**Race**: Mithra
**Nation**: San d'Orian
**Main Job**: BLU99
**Sub Job**: NIN49
**Area & Coordinates**: Metalworks (With @ah command), -38, -10, -15
**Party or Solo**: Solo-da
**NPC Name**: @ah 
**Monster Name**: N/A
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Every single player I've spoken to is having the exact same issue.  :-)

**Comment by Kaoriasada** [comment]
Working now.

**Comment by TeoTwawki** [comment]
I guess this was caused by the bad table @atom0s fixed.
