### ISSUE TITLE
Umbani cap,you can not equip monk

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#203]
Date & Time: 03/08/2015, 10:00am
Frequency: Always
FFXI Client Version: 30150619_2
Character Name: Cassy
Race: Hume
Main Job: MNK
Sub Job: DNC
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name: none
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:you can not equip monk , but if provided in THF

**Comment by nekrol** [comment]
hello

**Comment by Strafeous** [comment]
Incorrect job mask.
Correct one is 2593826.
Thanks for the report. We'll get this taken care of as soon as possible.

**Comment by Loki79** [comment]
Fixed, be in next maint / crash.
