### ISSUE TITLE
Taeon job mask

### ISSUE THREAD

**Issue by Kaoriasada** [LegionDark/Issues#205]
Cannot equipt Taeon armor on RDM, can on THF

**Date & Time**: 8/3/2015 20:32:25
**Frequency**: Consistent
**FFXI Client Version**: 30150629_4
**Character Name**: Halsey
**Race**: Mithra
**Nation**: San d'Orian
**Main Job**: RDM99
**Sub Job**: NIN49 
**Area & Coordinates**: Labyrinth of Onzozo -32 13 -58
**Party or Solo**: Solo
**NPC Name**: N/A
**Monster Name**: N/A
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Re-equipt many times on RDM

**Comment by Kaoriasada** [comment]
Going to start rioting #NOLOVEFORRDM :) jk

**Comment by Strafeous** [comment]
Correct submask is 2602290 
I'll leave this open for loke to fix the submask

**Comment by Strafeous** [comment]
@Loki79

**Comment by Loki79** [comment]
Fixed, be in next maint / crash.
