### ISSUE TITLE
Yukitsugu +1 shows no weapon skills

### ISSUE THREAD

**Issue by slaggyt** [LegionDark/Issues#206]
Date & Time: Aug 3, 2015 aprox 11:00pm est
Frequency: continuous
FFXI Client Version: Ver 20150629_4
Character Name: Lionpaw
Race: taru
Nation:Bastok
Main Job:80 sam
Sub Job: war
Area & Coordinates: bastok , zerhun mines 
Party or Solo:both
NPC Name: 
Monster Name: NA
Multi-boxing? (multiple clients on same connection): Yes. 
Steps To Reproduce The Issue: relogged -changed zones -changed wep -chaged sub job- changed main job- couldnt fix

**Comment by slaggyt** [comment]
For some reason it was the weapon that is not registering...put back on the hagun all skills weapon skills showed up Yukitsugu +1 shows no weapon skills. Great katanna

**Comment by Strafeous** [comment]
It's because that GKT isn't coded, I'll code it and give it to @Loki79 to fix.

**Comment by Loki79** [comment]
Fixed, be in next maint / crash.
