### ISSUE TITLE
Sanction NPC not giving sanction in Nashmau

### ISSUE THREAD

**Issue by Roamin** [LegionDark/Issues#207]
**Date & Time**: August 4th 2015
**Frequency**: Everytime
**FFXI Client Version**: 30150619_2
**Character Name**: Roamin
**Race**: Tarutaru
**Nation**: Windurst
**Main Job**: Warrior
**Sub Job**: Samurai
**Area & Coordinates**: Nashmau - H-6
**Party or Solo**: Party
**NPC Name**: Nabihwah
**Monster Name**: not applicable
**Multi-boxing? (multiple clients on same connection)**: yes 3 box same pc
**Steps To Reproduce The Issue**: Talk to NPC.

Everytime you talk to Nabihwah in Nashmau, he will offer sanction (even if you dont have missoin 1 of ToAH complete , (it is active right now, omw to a staging point) but sanction does not appear. It will also not work on other characters who have completed the mission, while the npc in Aht urgan is working fine.

It will also not offer the refresh/ regen buffs, simply cast the sanction motion, with no results. It doesnt say "signet wore off".

I do have signet ON at the moment of testing.

**Comment by TeoTwawki** [comment]
I think its likely that particular NPC was never made to work at all. I had to fix up the ones elsewhere, guess I missed a few. Will take a look at him when I have time.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
