### ISSUE TITLE
Cannot log into specific Character

### ISSUE THREAD

**Issue by BlackHaloRose** [LegionDark/Issues#208]
**Date & Time**: August 4th 2015
**Frequency**: Every time
**FFXI Client Version**: Ver 20150629_4
**Character Name**: Atca
**Race**: Hume Female
**Nation**: San d'Oria
**Main Job**: Red Mage
**Sub Job**:
**Area & Coordinates**: Kazham, unsure of coordinates at this time
**Party or Solo**: Solo
**NPC Name**: None
**Monster Name**: None
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Trying to play the character.

I cannot log into this specific character, all of my others remain unaffected. When I attempt to log in, I get the POL-0001 error. I was told to restart my PC and did this but it had no effect. It does not appear to be connection or personally related as a GM tried logging in for me to move me, but encountered the same error. I tried using the Stuck Tool, that did nothing either.

**Comment by BlackHaloRose** [comment]
Issue appears to have resolved itself after I deleted a few extra characters.

**Comment by Kaoriasada** [comment]
Oh!  I know exactly what your issue was, I didn't know you had made/deleted characters.  Basically if you delete a character and it gets moved from the slot it was originally in, that can bug it up a lot and even make it completely unplayable.  Seen it a few times in the past.

**Comment by TeoTwawki** [comment]
As I've said repeatedly, its a bad idea to try and put more than 2-3 characters per account. Known DSP bug. https://github.com/DarkstarProject/darkstar/issues/497

**Comment by TeoTwawki** [comment]
Feel free to go remind DSP they have this bug.
