### ISSUE TITLE
Octave Club no longer has hidden stats at 99

### ISSUE THREAD

**Issue by Roamin** [LegionDark/Issues#209]
**Date & Time**:  August 4th 2015
**Frequency**: All the time
**FFXI Client Version**:  
**Character Name**:
**Race**:
**Nation**:
**Main Job**:
**Sub Job**:
**Area & Coordinates**:
**Party or Solo**:
**NPC Name**:
**Monster Name**:
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**:

**Comment by R3P0FFXI** [comment]
Incomplete template closing ticket

**Comment by Roamin** [comment]
I clicked post by accident, but then found out it was also fixed in last update so.  Was coming back to remove it myself.
