### ISSUE TITLE
No KI after 5-1 BCNM

### ISSUE THREAD

**Issue by Skett** [LegionDark/Issues#21]
**Date & Time**: 27/05/15 19:18:41 GMT
**Frequency**: Twice
**FFXi Client Version**: 30150508_5
**Character Name**: Skett
**Race**: Elvaan
**Main Job**: NIN
**Sub Job**: WAR
**Area & Coordinates (Type @where to get this info.)**: X:-37 Y:-28 Z:-63 (86)
**Party or Solo**: PArty
**NPC Name**: N/A
**Monster Name**: N/A
**Steps To Reproduce The Issue**: Finish 5-1 BCNM, dont get the key item for completion.
Both other ppl in my party got the KI, so we tried again thinking maybe I HP too soon, same result.

**Comment by R3P0FFXI** [comment]
Tried to look for you tonight did not see you please hit me up on IRC when you are around

**Comment by Skett** [comment]
Issues of being in gmt! Will be on later

**Comment by R3P0FFXI** [comment]
@delkeyitem 72
@addkeyitem 73
@completemission 0 14
@addmission 0 15

**Comment by R3P0FFXI** [comment]
Teo please look at this my fix did not work may be a HALVER issue Fucking Halver

**Comment by TeoTwawki** [comment]
Its not Halver, is you did totally wrong thing - you needed to look at variable, and also not skip the mission.

**Comment by Skett** [comment]
Let me know when to be on if I need to be guyz

**Comment by Skett** [comment]
minus the z

**Comment by TeoTwawki** [comment]
Fixed Skett and verified mission behaves as intended now. Closing.
