### ISSUE TITLE
Dring Lost

### ISSUE THREAD

**Issue by Superman78** [LegionDark/Issues#211]
**8/5/2015 1:22am**: 
**once**:
**Ashita**:
**Valentine**:
**Hume**:
**Sand'oria**:
**THF**:
**DNC**:
**Behemoth's Dominion.  X:-257 Y:-19 Z:63 (60)**:
**Party**:
**King Behemoth**:
**King Behemoth**:
**Multi-boxing? Yes**:
**Defending Ring dropped saying, "I do not meet the requirements to obtain item." I had 5 open spots in inventory. I did have a defending ring on retail(not sure that matters)
![valentine_2015 08 05_010946](https://cloud.githubusercontent.com/assets/13654358/9078795/10297bf4-3b11-11e5-9790-d51e74f40b36.png)
![valentine_2015 08 05_011027](https://cloud.githubusercontent.com/assets/13654358/9078797/12e2b1b2-3b11-11e5-9654-d62a2febc0ea.png)

**:

**Comment by R3P0FFXI** [comment]
Valentine see me on IRC and I will give you Dring

**Comment by Superman78** [comment]
Ok thank you. 

Date: Wed, 5 Aug 2015 06:18:33 -0700

**Comment by R3P0FFXI** [comment]
Valentine please pm me your login info on the forums I need to check some stuff

**Comment by TeoTwawki** [comment]
@valentien to be clear don't post it here! give it to him in PM!

**Comment by TeoTwawki** [comment]
@Superman78 to be clear don't post it here, PM it to him!

**Comment by Superman78** [comment]
says i cant pm you because I am too new to this server. 

Date: Thu, 6 Aug 2015 18:44:59 -0700

**Comment by TeoTwawki** [comment]
@Superman78 try and catch him on IRC tomorrow

**Comment by Superman78** [comment]
Ok thank you Teo

Date: Thu, 6 Aug 2015 21:37:35 -0700

**Comment by R3P0FFXI** [comment]
DSP Autosort bug user now has item 13566

**Comment by TeoTwawki** [comment]
This was your bug https://github.com/DarkstarProject/darkstar/issues/607 its a very old one that DSP doesn't know how to deliberately trigger or fix yet.

**Comment by Superman78** [comment]
Thank you guys for your help! 

Date: Sat, 8 Aug 2015 17:45:08 -0700
