### ISSUE TITLE
Summoner not showing Carbuncle on Magic list

### ISSUE THREAD

**Issue by jhalim83** [LegionDark/Issues#213]
**Date & Time**: 5:50 PM (GMT+7) & August 5 2015
**Frequency**: First time as just recently transfer from retail
**FFXI Client Version**:  30150619_2
**Character Name**: Hijikata
**Race**: Hume
**Nation**: Sandoria
**Main Job**: SMN 75
**Sub Job**: RDM 50
**Area & Coordinates**: Lower Jeuno outside mog house
**Party or Solo**: Solo
**NPC Name**: N/A
**Monster Name**: N/A
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**: Switch job to SMN, open Magic list page no Carby or other summon available (I assume other summon not transferred from Retail?)

**Comment by R3P0FFXI** [comment]
You need to redo the quest to re obtain carbuncle as no spells migrate over during the migration process
