### ISSUE TITLE
Radennotachi not showing WS list

### ISSUE THREAD

**Issue by jhalim83** [LegionDark/Issues#214]
**Date & Time**: August 5 2015
**Frequency**: First time as just recently transfer from retail
**FFXI Client Version**:  30150619_2
**Character Name**: Hijikata
**Race**: Hume
**Nation**: Sandoria
**Main Job**: SAM 75
**Sub Job**: WAR 80
**Area & Coordinates**: Lower Jeuno outside mog house
**Party or Solo**: Solo
**NPC Name**: N/A
**Monster Name**: N/A
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**: Switch to SAM, equip Radennotachi, no WS shown. Equip other GKT, the WS appear.

**Comment by Strafeous** [comment]
Confirmed. I'll code this and get it in once I get a bit of time.

**Comment by jhalim83** [comment]
Ok thx again

**Comment by Loki79** [comment]
Fixed, be in next maint / crash.
