### ISSUE TITLE
Incorrect jobmask on Bokwus Gloves

### ISSUE THREAD

**Issue by Kaoriasada** [LegionDark/Issues#215]
**Date & Time**: 12:49:41 8/5/2015
**Frequency**: Consistent 
**FFXI Client Version**: 30150629_4
**Character Name**: Sami
**Race**: Mithra
**Nation**: Bastok
**Main Job**: SCH99
**Sub Job**: RDM49
**Area & Coordinates**: 93 0 -71 (129) 
**Party or Solo**: party
**NPC Name**: n/a
**Monster Name**: n/a
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: I tried both last night and this morning when I woke up.  SCH is listed but cannot equip Bokwus Gloves, probably due to an incorrect job mask.  :>

**Comment by Strafeous** [comment]
Correct jobmask is 1589788
Leave this open for Loke to fix the changes. @Loki79 
Might be all the Bokwus, can you try it all on SCH and let me know if they all need to be changed?

**Comment by Loki79** [comment]
Fixed be in next maint / crash.
