### ISSUE TITLE
Voidwatch item coded incorrectly

### ISSUE THREAD

**Issue by Kaoriasada** [LegionDark/Issues#216]
**Date & Time**: 8/5/2015
**Frequency**: Once
**FFXI Client Version**: 30150629_4
**Character Name**: Sami
**Race**: Mithra
**Nation**: Bastok
**Main Job**: RDM99
**Sub Job**: BLM49
**Area & Coordinates**:-271 16 589 (111)
**Party or Solo**:party
**NPC Name**: N/A
**Monster Name**: Lord Asag
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: didn't

Inventory not full, reference SS below:
http://i60.tinypic.com/10fc7x0.png

**Comment by Strafeous** [comment]
Type the name of the item here, Sami.
The tinypic won't load for me and I'll fix it and give it to loke

**Comment by R3P0FFXI** [comment]
Shetal Stone

**Comment by Strafeous** [comment]
Thanks 3p0, coded and sent to loki.
