### ISSUE TITLE
Missing spells

### ISSUE THREAD

**Issue by jazzy00** [LegionDark/Issues#217]
So I bought 90% my Whm skills (which is 99). I didn't buy any bar spells but all my main skills and now over half my white magic is missing. You can see I bought them on Ah and when I check Ah they show that they are available to me to buy/use as if I never learned them.  Every Blm spell is gone as well, and all my Summon's are gone as well.. I only have the scrolls I just bought for Brd. (unless something else happens). I don't have the gil to rebuy all of these skills. I had them yesterday but now their gone. 

Character name Jazzy
Date 8-5-15 8:35pm
Ver 30150629_4
Freq no clue
Race Hume
Whm 
Smn
Solo and party
No multiboxing
Steps to reproduce ? No clue.. Whm, Blm, Rdm, Smn Spells Missing (whm is 50% missing spells)

**Comment by Kaoriasada** [comment]
Incomplete report....

Please fill out the form:
**Date & Time**: 
**Frequency**:
**FFXI Client Version**:
**Character Name**:
**Race**:
**Nation**:
**Main Job**:
**Sub Job**:
**Area & Coordinates**:
**Party or Solo**:
**NPC Name**:
**Monster Name**:
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**:

**Comment by jazzy00** [comment]
yes I hit the enter by accident and had to walk away to do something at my house. I updated it.

**Comment by Kaoriasada** [comment]
Thanks for filling it out! :)

**Comment by Strafeous** [comment]
You transferred from retail correct?

**Comment by R3P0FFXI** [comment]
When migrating from other servers spells and missions do not transfer over this is normal and explained on the app, you will need to rebuy them all this is normal and fully explained before migration.

**Comment by jazzy00** [comment]
Sorry I was sleeping when you answered this. I checked all her Temp and Perm key items I still have them. Maps as well. Still have all my brd songs. Moon Bauble still shows as well in key items. Yes I transfered from retail. I have not touched retail since I came here so After I installed what was needed here I have not updated anything. Yes I still have the Adoulin KI as well.

**Comment by Strafeous** [comment]
Okay, I added a bunch of spells. If you're missing anything whenever you log on, let me know.
