### ISSUE TITLE
To loki

### ISSUE THREAD

**Issue by Strafeous** [LegionDark/Issues#218]
Check your PMs on the legion fourms, sent you a list of items i finished
Need to check all the drops from vw chapter 2 and see what items thillion coded incorrectly because there's a ton; The last ring I coded was another broken VW one; Merirvosvo ring

**Comment by Loki79** [comment]
Straf, please pull a fresh copy of DSP and see whats in and what isn't.  They are almost caught up with us after the latest shareback.  Anything on the excel sheet for VW that's missing or wrong please coordinate with Sami and get knocked out.  The sooner we can put VW and these damn items too bed the sooner we can move on to bigger and better things.

**Comment by Loki79** [comment]
All the items you PM's me are in.

**Comment by Strafeous** [comment]
Loki, I'll be honest, I can't download a latest copy of dsp on this internet lollll

**Comment by Strafeous** [comment]
Items are fixed and In. 
Closed
