### ISSUE TITLE
POL XIloader crash

### ISSUE THREAD

**Issue by goferffxi** [LegionDark/Issues#219]
**Date & Time**: 6/8/15     14:25
**Frequency**: Cinsistent
**FFXI Client Version**:  30150629_2
**Character Name**: Gofer
**Race**: Taru
**Nation**: Bastok
**Main Job**:BLU
**Sub Job**:RDM
**Area & Coordinates**: Promivyan Vahzl map 3
**Party or Solo**: Party
**NPC Name**: N/A
**Monster Name**: Seether
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Head into zone and fight seethers to gain BLU spell Occultation

**Comment by goferffxi** [comment]
Just noticed that on the seethe mob all of the TP moves have the same visual effects. Mob jumps into the air and spits a fireball. When monsters occultation is used it claims it has given the target the effect of blink

**Comment by Strafeous** [comment]
So, It's XILoader that's crashing? I'd think that would be for @atom0s

**Comment by goferffxi** [comment]
It's Xiloader AND PoL

**Comment by Strafeous** [comment]
That sounds like a dsp issue

**Comment by puffer1221** [comment]
Its not just ashita, windower also died at the same time gofers client went down, also he was fighting Thinkers at the sametime i was fighting seethers when the crashes happened, but when we fought them 1 at a time nothing happened.

**Comment by R3P0FFXI** [comment]
Try launching FFXI without ashita and windower and see if you still crash also make sure you reset your character on the main page.

**Comment by goferffxi** [comment]
I'll give that a go when I can and head to the same place to test it.

**Comment by atom0s** [comment]
This is not an issue with Ashita or xiloader. It is an issue with DSP and mishandling certain packets. It is the same/similar issue that is causing random crashes in Abyssea zones as well.
