### ISSUE TITLE
Website error's

### ISSUE THREAD

**Issue by RunAwayDSP** [LegionDark/Issues#22]
Good work with the website A++ I did find a few issues 

1) http://www.legiondark.com/?p=character&id=21832 - Character is offline but "This user is currently online and anon."

2) Monster drops, item shows 0% drop rate when its an item that is stolen only (IE Thief's Testimony)

Everything else look wonderful, great work!

**Comment by Genesis-Legion** [comment]
According to teo an item with 0% still has a chance to drop, albeit extremely low chance.

**Comment by TeoTwawki** [comment]
That *should* still be a bug, because there really should not be any database entries set to exactly zero..But someone will have to check that to find out. Also unsure why DSP allows zero rate items to drop/be stolen. Pretty sure that's unintended but does happen anyway.
