### ISSUE TITLE
Bale Burgeonet +2 ,''Bale Burgeonet +1, and 6 Vision Coin not work

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#220]
Date & Time: 06/08/2015, 19:00pm
Frequency: Always
FFXI Client Version: 30150619_2
Character Name: Aurel
Race: Hume
Main Job: DRK
Sub Job: Sam
Area & Coordinates: Port jeuno
Party or Solo: Party or solo
NPC Name: moogle 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:moogle Port jeuno ,:;moogle not receive the items to upgrade to +2------''Bale Burgeonet +1, and 6 Vision

**Comment by Loki79** [comment]
Typo in the script, will be good to go here as soon as i pull the changes in.

**Comment by nekrol** [comment]
Thanks , it worked with 6 jewel vision
