### ISSUE TITLE
stuck in a cutszene COP 2-3 last cutszene

### ISSUE THREAD

**Issue by Antaroh** [LegionDark/Issues#221]
the part where the green haired taru starts running in it stops, i can still write or use @homepoint.
then i go back and try to talk to Justinius on the upper level, at (J-6), CS starts, and im stuck again.

So i cannot progess there.**Date & Time**: August 7th 15, 1:36 GMT
**Frequency**: always
**FFXI Client Version**: 30150629_4
**Character Name**: Anty
**Race**: Taru
**Nation**: Windy 
**Main Job**: Blm
**Sub Job**: Whm
**Area & Coordinates**: J-6 Tavnazian SH - @Justinius NPC
**Party or Solo**: SOLO
**NPC Name**: Justinius
**Monster Name**:  - 
**Multi-boxing? (multiple clients on same connection)**: nope
**Steps To Reproduce The Issue**: i did it again, and im stuck , tried now for the first time, i did a restart. And its haning again, same CS, same taru :dancer:

**Comment by TeoTwawki** [comment]
Have a lot of people run into this problem. Its usually a plugin interfering, or a bad file in their FFXI installation (typically people who all downloaded the same torrent of the installer..). The filecheck will ***not*** find and fix said file either, annoyingly forcing a reinstall form a known good source just to eliminate the possibility.

Try running the game with no add-ons/plugins and see if it can progress. If it still gets stuck a GM can alter your mission progress to get past this but in several CS down the mission line you will run into the same issue again if its the bad file problem.

**Comment by Antaroh** [comment]
thanks a lot, i just disabled all extra stuff in windower and i could continue. - cant tell which pulgin it was though but thanks :D
