### ISSUE TITLE
VW chapter 2 missing drops~ Mikinaak Breastplate 

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#223]
**Date & Time**:  8/9/15
**Frequency**: Constantly
**FFXI Client Version**: 30150619_2
**Character Name**: Xoe
**Race**:Hume
**Nation**:Bastok
**Main Job**:WHM
**Sub Job**:RDM
**Area & Coordinates**:
**Party or Solo**:
**NPC Name**:    
**Monster Name**: Voidwrought
**Item ID Number -- Obtained from FFXIAH**:  27917 (taken from website tool)
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: try to equip item.

**Comment by Kaoriasada** [comment]
Are you saying that you can't equip the item, or that it isn't dropping...?

**Comment by R3P0FFXI** [comment]
LV 99 WAR PLD DRK BST SAM DRG

Your Main job is WHM according to this so yes you cannot equip this.

**Comment by Loki79** [comment]
@Strafeous  can you peek at the mask for this, if wrong lets get it fixed for maint tomorrow.

**Comment by Strafeous** [comment]
Dae, you can't lockstyle an item if you dont have a job that can wear it.
I think Megamoo already explained this to you, not sure if you posted this before or after, the job mask is correct

**Comment by Rohelius** [comment]
I posted this before  Mega explained it thanks!  

It was odd to me because I can lockstyle thf empy head armor on drk, so i figured any armor is fair game in Lockstyle mode since you can edit sets that way.
