### ISSUE TITLE
O-Club Broken after Last update~

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#224]
**Date & Time**: 8/9/15
**Frequency**: constant
**FFXI Client Version**:30150619_2
**Character Name**:Daedrik
**Race**:Elvaan
**Nation**:Bastok
**Main Job**:PLD
**Sub Job**:RDM
**Area & Coordinates**:
**Party or Solo**:
**NPC Name**:  Octave Club
**Monster Name**:
**Item ID Number -- Obtained from FFXIAH**  18852
**Multi-boxing? (multiple clients on same connection)**:  no
**Steps To Reproduce The Issue**: Equip the item and auto attack. Only hits one per attack round.

**Comment by R3P0FFXI** [comment]
This will be resolved after maint. Fix is already in place just needs to be pulled down.
