### ISSUE TITLE
ToAU Mission2 KI issue

### ISSUE THREAD

**Issue by Crimson-Neko** [LegionDark/Issues#227]
**Date & Time**: 08/10/15 11:30am est
**Frequency**: 1
**FFXI Client Version**: 
**Character Name**: Suzukun
**Race**: Mithra
**Nation**: Windurst
**Main Job**: Redmage
**Sub Job**: Blackmage
**Area & Coordinates**: Halvung Staging Point X:674 Y:-24 Z:360 (165)
**Party or Solo**: solo
**NPC Name**: Waudeen
**Monster Name**: -
**Item ID Number -- Obtained from FFXIAH** Key item: Supplies Package
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Accept Mission 2 of ToAU

The Key Item was not given to my character upon CS from Mission 1

**Comment by R3P0FFXI** [comment]
This is a DSP issue and has previously been reported to them

**Comment by Kaoriasada** [comment]
Send me a tell in-game and I'll check your variable and give you the KI after talking to you if it deems necessary.  

-Halsey

**Comment by Kaoriasada** [comment]
Fixed.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
