### ISSUE TITLE
Mechanical Menace model displaying wrong mob.

### ISSUE THREAD

**Issue by Roamin** [LegionDark/Issues#228]
**Date & Time**:  August 10th 2015
**Frequency**: All the time
**FFXI Client Version**: 30150619_2
**Character Name**: Thievan
**Race**: Elvan
**Nation**: Windurst
**Main Job**: Thief
**Sub Job**: White Mage
**Area & Coordinates**: Abyssea Uleguerand Range - G-8
**Party or Solo**: Party & Solo
**NPC Name**: Not applicable
**Monster Name**: Mechanical Menace
**Item ID Number -- Obtained from FFXIAH** : Not applicable
**Multi-boxing? (multiple clients on same connection)**: Yes 3 clients same pc
**Steps To Reproduce The Issue**: Walk to G-8 of Abyssea Uleguerand Range and see the mob that is incorrect. Included screenshot
![img_20150810_190457](https://cloud.githubusercontent.com/assets/398228/9186476/242c0172-3f93-11e5-9903-58e415f2e85c.png)

**Comment by Loki79** [comment]
Fixed, will go in next maint.
