### ISSUE TITLE
VW Drops-Limbo Trousers

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#229]
**Date & Time**: 8/10/2015
**Frequency**: Constant
**FFXI Client Version**:30150619_2   
**Character Name**: Daedrik
**Race**:Elvaan
**Nation**:Bastok
**Main Job**:THF
**Sub Job**:DNC
**Area & Coordinates**: 
**Party or Solo**:
**NPC Name**:   Limbo Trousers
**Monster Name**:  Gaunab  (Drops it)
**Item ID Number -- Obtained from FFXIAH**  27222
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Try to equip item.

**Comment by Strafeous** [comment]
Thanks for the report, sounds like an incorrect job mask! 
I'll get right on that and we'll place it into the database asap! 
Thanks for the report!

**Comment by Loki79** [comment]
will be in after maint tonight.
