### ISSUE TITLE
Maat Augmented Belt: waltz delay -5 not working

### ISSUE THREAD

**Issue by excenmille** [LegionDark/Issues#230]
Date & Time: 8/11/2015
Frequency: Constant
FFXI Client Version:30150619_2

Character Name: Syl
Race: Mithra
Nation: Bastok
Main Job: DNC
Sub Job: BLM
Area & Coordinates: Xarcabard
Party or Solo: Solo
NPC Name: Maat?
Monster Name: 
Item ID Number -- 15931
Item Name: Goblin Cest (1 agi, 2 mnd, 2 chr, waltz delay -5)
Multi-boxing? (multiple clients on same connection): Yes

Steps To Reproduce The Issue: 
Finished Limit Break 2 quest ("Atop the Highest Mountain") and turned it in to Maat as DNC job. Received Goblin Cest belt with Dancer augments. Equipped the belt and tried Healing Waltz and various tiers of Curing Waltz but my Waltz recast in seconds is not reduced at all.

**Comment by TeoTwawki** [comment]
Many augment effects never got fully implemented because all my time gets sucked up dealing with crap that apparently nobody else can handle like actually reporting DSP bugs back to DSP after players reported them to Legion. And often I have to fix the damn bug in DSP too or it stays broken.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update

**Comment by TeoTwawki** [comment]
Hi I'm Teo, and this will actually work after maintenance..
