### ISSUE TITLE
Dynamis Xarcabard:  Dynamis Lord is not spawning.

### ISSUE THREAD

**Issue by BGwill30** [LegionDark/Issues#231]
**Date & Time**:  Latest 8/11/2015 19:24 CST
**Frequency**:  Last 4 attempts on 8/5/2015, 8/6/2015, 8/7/2015 and 8/9/2015
**FFXI Client Version**: current
**Character Name**: Aaroon
**Race**: Hume
**Nation**: Bastok
**Main Job**: Blue Mage
**Sub Job**: Red Mage
**Area & Coordinates**: Dynamis Xarcabard
**Party or Solo**: Solo
**NPC Name**: Dynamis Lord
**Monster Name**: Dynamis Lord
**Item ID Number -- Obtained from FFXIAH** n/a
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: same thing every attempt.

On each attempt I have killed all of the stair NMs and spawned Yin and Yang.  I have killed Yin and Yang both on and near the spot where Dyna Lord spawns.  I have also ensured they died at the exact same time.  On every attempt, the dynamis lord does not spawn.  

Please look into the issue, or at least tell me what im doing wrong, no one in game has been able to help.  Thank you for your time.

**Comment by TeoTwawki** [comment]
Broke some code relating to a time limit for getting Dyna Lord. Normally, you have to get to and kill him before then or no Dyna Lord. This will be resolved next server maint.

**Comment by TeoTwawki** [comment]
Someone broke some code relating to a time limit for getting Dyna Lord. Normally, you have to get to and kill him before then or no Dyna Lord. This will be resolved next server maint.

**Comment by BGwill30** [comment]
thank you for your response.  I will attempt again after maintenance.

**Comment by TeoTwawki** [comment]
I fixed it in DSP too. https://github.com/DarkstarProject/darkstar/pull/1915
