### ISSUE TITLE
Sandy 9-2 Final Mission CS Issue

### ISSUE THREAD

**Issue by Superman78** [LegionDark/Issues#232]
8/11/2015:
once:
*30150629_4:
Valentine:
Hume:
Sandy:
Paladin:
Dancer:
Feiyin BCNM:
Solo:
Sandy 9-2 mission fight:
Multiple:
n/a
single character login:
Not getting cs while zoning into North Sandy. Also tried the connected NPC's to the story line.

**Comment by R3P0FFXI** [comment]
DSP issue and has already been reported
