### ISSUE TITLE
Tablilla NM not correct model or is wrong mob.

### ISSUE THREAD

**Issue by Roamin** [LegionDark/Issues#233]
**Date & Time**:  August 11th 2015
**Frequency**: Every time
**FFXI Client Version**: 30150619_2
**Character Name**: Roamin
**Race**: Tarutaru
**Nation**: Windurst
**Main Job**: Warrior
**Sub Job**: Samurai
**Area & Coordinates**: Abyssea Altepa C-11
**Party or Solo**: Party
**NPC Name**: not applicable
**Monster Name**: Tablilla
**Item ID Number -- Obtained from FFXIAH** : not applicable
**Multi-boxing? (multiple clients on same connection)**: Yes 3 client same pc
**Steps To Reproduce The Issue**: Use a sandy shard to spawn NM Tablilla.  The model should be a golem statue but a Scorpion is shown instead.  Uses scorpion TP moves. 

![img_20150811_184559](https://cloud.githubusercontent.com/assets/398228/9236622/ebdb1ae2-4113-11e5-81de-73e7b6422f5a.png)

**Comment by Loki79** [comment]
@LegionDark/owners I fought this no too long ago.  WTF is going on with abyssea models??  this is the second one in a week that is now somehow different.

**Comment by Kaoriasada** [comment]
@Loki79 I've been doing a lot of Abyssea lately.  Once I get back into the game I'll make documentation of any incorrect models.  A huge one that I noticed was that all the Mechanical Menaces are supposed to be Acroliths but they're orcs.  A lot of timed NMs are spawning on 60 second timers opposed to 10-15 minutes as well (Sisyphus is an example of one.) I've got a notepad full of monsters with incorrect models, I'll be sure to send it over to you next time I have access to my laptop.

**Comment by TeoTwawki** [comment]
If its actually using scorpion moves odds are its more basic than a model issue. Likely mobID moved or is wrong pool or group (I forget which) causing wrong data to be loaded, in this specific mobs case.

**Comment by Loki79** [comment]
I'm guessing someone in dsp has been messing with abyssea shit, and they fucking suck.  All this including spawn times were all correct.  So we must have pulled in some crap from them.  I'm so tired or having to fix things that were already working I could puke.  Makes me want to burn the entire project to the ground.

**Comment by Loki79** [comment]
This will be in for maint.
