### ISSUE TITLE
Bastok Mission 5-1

### ISSUE THREAD

**Issue by Athomik** [LegionDark/Issues#234]
**Date & Time**: 12 August 2015 between 15:00 and 17:00
**Frequency**:    2 Times
**FFXI Client Version**:  Ver.30150730_1
**Character Name**: Athomik
**Race**: Galka
**Nation**: Bastok
**Main Job**: MNK99
**Sub Job**: NIN49
**Area & Coordinates**: Qubi arena in feiyin
**Party or Solo**: Party i was there with Miudo serginho and Dimma
**NPC Name**:
**Monster Name**: SKele mission 5-1
**Item ID Number -- Obtained from FFXIAH**
**Multi-boxing? (multiple clients on same connection)**: Nope
**Steps To Reproduce The Issue**: First time i beat the BC the cs freezed cause i died and when i was about to RR the cs blocked it and never again advanced had to close client. Seconde time we win again no problem during fight or cs but at end i didn't got the Burnt Seal KI i should of got.

**Comment by Kaoriasada** [comment]
This is a huge re-occurring issue going on right now.  I just fixed this for Faloo, but unfortunately I'm not going to be able to log on and deal with this for a few days.  @Strafeous is going to have to deal with it.  Yay for responding to bug reports via mobile.

**Comment by Strafeous** [comment]
Try and redo the mission and see if you get the KI, if not I'll have to mess with variables and such. Comment on here what the results are after doing it again.

**Comment by Athomik** [comment]
OK i'm at work i will try redo later when i log and after do it i'll leave here a reply ty

**Comment by excenmille** [comment]
Date & Time: some time last week, forgot
Frequency: 2 Times
FFXI Client Version: Ver.30150730_1
Character Name: Syl
Race: Mithra
Nation: Bastok
Main Job: MNK 75
Sub Job: WAR 37
Area & Coordinates: Qubia arena in feiyin
Party or Solo: Party
Monster Name: SKele mission 5-1
Multi-boxing? (multiple clients on same connection): Nope
Steps To Reproduce The Issue:

I encountered the same thing.

1st attempt: I was dead when party beat the skelly boss. Everyone else in PT received cutscene while I alone froze and had to relog.

2nd attempt: this time alive when killed the boss. Received cutscene but no key item. Naji in Metalworks wouldn't acknowledge my win.

3rd attempt: alive, killed boss, got CS, got KI. Mission finally completed.

**Comment by Athomik** [comment]
OK got The KI at 3rd time . Problem solved ty
