### ISSUE TITLE
WHM Staff WS's

### ISSUE THREAD

**Issue by Jewell12** [LegionDark/Issues#236]
**Date & Time**: 8-8-2015
**Frequency**:Once
**FFXI Client Version**:Ver.30150629_4
**Character Name**:Burrito
**Race**:TaruTaru
**Nation**:San d'oria
**Main Job**:Whitemage
**Sub Job**:Scholar
**Area & Coordinates**:Abyssea-La Thiene
**Party or Solo**:Party
**NPC Name**:n/a
**Monster Name**:Worm
**Item ID Number -- Obtained from FFXIAH**
**Multi-boxing? (multiple clients on same connection)**:Yes
**Steps To Reproduce The Issue**:n/a

My Whitemage hit 300 staff skill and unlocked Mrykr and Vidohunir. When I switched to club and capped it's skill I switched back to Staff and those WS's were gone. I changed weapons back and forth and I also skilled staff up some more to no avail. I do not have any weaponskills past Retribution. I don't think WHM naturally gets these WS's but just curious. Please let me know if this was submitted in the wrong way.

**Comment by Kaoriasada** [comment]
Have you tried using a different staff?  The one you're using may be bugged.

**Comment by Jewell12** [comment]
I've just tried multiple staves and nothing. It's very possible I wasn't supposed to have the WS's in the first place. WHM isn't a Staff mage.

**Comment by Strafeous** [comment]
http://ffxiclopedia.wikia.com/wiki/Hvergelmir_(85)
It might have been a visual bug because those are BLM weaponskills :P
Thank you for the report though Burrito.
