### ISSUE TITLE
Cannot Equip Supay Weskit

### ISSUE THREAD

**Issue by slaggyt** [LegionDark/Issues#237]
**Date & Time**: Aug 14 2015
**Frequency**:100%
**FFXI Client Version**:a137e3f0075cce9336bc5b929829ace9acf0c58c
**Character Name**: Lionpaw
**Race**:Taru
**Nation**: Bastok
**Main Job**: BLM
**Sub Job**: RDM
**Area & Coordinates**: Everywhere
**Party or Solo**: Both
**NPC Name**: N/A
**Monster Name**: Dropped in V W
**Item ID Number -- Obtained from FFXIAH** ... 26874
**Multi-boxing? (multiple clients on same connection)**: Both
**Steps To Reproduce The Issue**: Zone , Relog , Change job change back

This item was obtained the same way as Limbo pants in a prior Bug report (VW) so it might not be coded yet.

**Comment by R3P0FFXI** [comment]
Item ID Number -- Obtained from FFXIAH ... so whats the ID number?

**Comment by Kaoriasada** [comment]
26874 is the item ID.

Not sure how recent this item was put into the game, but @Loki79 sent me all the item SQLs on August 6th and I skimmed over them with /find (It was a huge bitch to open on mobile, ugh.) but there's no line for supay weskit in anything but Item_basic.sql which means unless this item was coded and added to the database after Loki sent me those files, it's not coded.

**Comment by slaggyt** [comment]
Thank you

**Comment by Strafeous** [comment]
I have a large list of stuff I'm going to do in the car today. 
This and the pants should be working post-maintenance.

**Comment by Loki79** [comment]
Fixed.  Will be in after maint tonight.
