### ISSUE TITLE
1 ten thousand byne bill

### ISSUE THREAD

**Issue by unknownwolf** [LegionDark/Issues#238]
Date & Time: 15-08-15 / 21:30
**Frequency**: 1 time
**FFXI Client Version**:30150619_2
**Character Name**: Volks
**Race**: Elvaan
**Nation**: san d'oria
**Main Job**: Thf
**Sub Job**:Dnc
**Area & Coordinates**:castle zvahl baileys J-8
**Party or Solo**:solo
**NPC Name**: Switchstix
**Monster Name**:none
**Item ID Number -- Obtained from FFXIAH**: http://www.ffxiah.com/item/1457/10000-byne-bill
**Multi-boxing? (multiple clients on same connection)**:no
**Steps To Reproduce The Issue**: switchstix ask for 1 ten thousand byne bill. traded it without trading batardeau.npc accept the currency then say "You can leave batardeau with me" traded it the batardeau but message from npc says "you wanna cancel order? have you lost your little adventurer mind?, do you want to canel your order?" I choose no, then talk to npc again and ask again for 1 ten thousand byne bill. Lost 1 ten thousand byne bill at the end for nothing
suppose to be only 1 according to wiki.
http://ffxiclopedia.wikia.com/wiki/Category:Relic_Weapons

they are some other requirements which i didnt have at the moment

**Comment by Strafeous** [comment]
Go to the place where you recieve the cutscene and trade all of it to the spot where you'd obtain the relic on retail.

**Comment by Strafeous** [comment]
If you're missing some items, you're going to need all 4 before this will work.

**Comment by Strafeous** [comment]
If it still doesn't work with my suggestions, then you can re-ticket but not meeting the requirements and then posting a bug report because it doesn't work doesn't make sense to me.
