### ISSUE TITLE
Academic's pants ,not work ,Enhances "Light Arts"

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#242]
Date & Time: 17/08/2015, 10:00am
Frequency: Always
FFXI Client Version: 30150619_2
Character Name: Aurel
Race: Hume
Main Job: Sch
Sub Job: Rdm
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name: moogle 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:to equip not add 18 Divine, Enfeebling, Enhancing, and Healing magic skill when Light Arts is active.

**Comment by Loki79** [comment]
@LegionDark/gm this is coded but but I'm guessing the mod doesn't actually work.  Will need to add to the list of mods to make.
INSERT INTO `item_mods` VALUES (28110,334,18);
@nekrol We will investigate and add to the list, but this will more than likely not be resolved very quickly as there are a ton of needed mods and this is at the bottom of the list.

**Comment by TeoTwawki** [comment]
@LegionDark/gm @Loki79 someone was telling me DSP does the SCH light/dark arts effects wrong, and that the skill doesn't always show up in the menu because of it. I don't have the details handy.

**Comment by TeoTwawki** [comment]
@Loki79 there is also a def a mod or 3 that were (very recently) added DSP's lists that didn't actually get used any any places that should check fro them resulting in the mod doing nothing at all.

**Comment by nekrol** [comment]
Scholar's Pants +1 It works well

**Comment by Loki79** [comment]
Same mod on both items so its what teo said, and it doesnt always show.
