### ISSUE TITLE
Arbatel gown,not work ,White and Addendum: Black enhancements

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#243]
Date & Time: 17/08/2015, 10:00am
Frequency: Always
FFXI Client Version: 30150619_2
Character Name: Aurel
Race: Hume
Main Job: Sch
Sub Job: Rdm
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name: moogle 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:A known issue on this item is that the Addendum: White and Addendum: Black enhancements are not working correctly.,,,,not add Divine, Enfeebling, Enhancing, and Healing magic skill when Light Arts is active.---not add Adds  elemental skill,  enfeebling skill, and Dark skill when Dark Arts is in effect.

**Comment by Loki79** [comment]
These mods do not exist in dsp yet.

**Comment by nekrol** [comment]
Savant's Gown +2 It works well
