### ISSUE TITLE
Heka's Kalasiris Set refresh doesnt work.

### ISSUE THREAD

**Issue by Pyrowe** [LegionDark/Issues#244]
Date & Time: 8/17/2015
Frequency: Constant
FFXI Client Version:30150730_1

Character Name: Yoloswaggins
Race:Tarutaru
Nation:San d'oria
Main Job:WHM
Sub Job:RDM
Area & Coordinates:
Party or Solo:Party
NPC Name: Nefer Khat +1
Monster Name: 
Item ID Number -- 10868(FFXIAH)
Multi-boxing? (multiple clients on same connection): Yes
Steps To Reproduce The Issue: Try to equip item.

Body works fine gives the +1 refresh it's intended to but the head doesn't add the +2.

**Comment by Loki79** [comment]
will add the set bonus in and push it through DSP when i get a chance.

**Comment by Strafeous** [comment]
Pushed to DSP with Hekas and head combos along with Nefer NQ and HQ body/head combos

**Comment by Loki79** [comment]
@Strafeous good shit man :D  this will be in next maint closing it out.
