### ISSUE TITLE
CoP 8-3

### ISSUE THREAD

**Issue by Pyrowe** [LegionDark/Issues#245]
Date & Time: 8/17/2015
Frequency: Constant
FFXI Client Version:30150730_1

Character Name: Pyrowe
Race:Hume
Nation:San d'oria
Main Job:SAM
Sub Job:WAR
Area & Coordinates:Grand Palace of Hu'Xzoi
Party or Solo:Party
NPC Name: Telepads for the Lights(Hume for sure doesn't work.. havent tested other races.)
Monster Name: 
Item ID Number 
Multi-boxing? (multiple clients on same connection): Yes
Steps To Reproduce The Issue: Step on the telepads, nothing happens.

**Comment by TeoTwawki** [comment]
The server is still on version 30150619_2 and won't be on 30150730_1 until after maintenance happens. 

This is why you are having issues. If it happens after server and client match, then we have a bug to look into.
