### ISSUE TITLE
Maat Augmented Ring: Waltz TP Cost -40 not working

### ISSUE THREAD

**Issue by excenmille** [LegionDark/Issues#246]
Date & Time: 8/17/2015
Frequency: Constant
FFXI Client Version:30150619_2

Character Name: Syl
Race: Mithra
Nation: Bastok
Main Job: DNC
Sub Job: WAR
Area & Coordinates: Xarcabard
Party or Solo: Solo
NPC Name:
Monster Name:
Item ID Number -- 15849
Item Name: Krousis Ring (Haste+2%, "Waltz" TP Cost -40)
Multi-boxing? (multiple clients on same connection): No

Steps To Reproduce The Issue: 
Just like Maat's augmented belt, the Dancer augment on this ring does not seem to work. Waltz TP cost is unchanged when equipping this ring. No idea if the 2% Haste works too.

Also, what does the augment "Enhances meikyo shisui effect" on Samurai's Iwatsubute do? Item ID: 19219. The duration is still 30 seconds like retail.

**Comment by TeoTwawki** [comment]
*all* the "enhances <job ability>" are not yet coded.

**Comment by TeoTwawki** [comment]
For augment system in general in DSP (which these items make use of):
Haste works. Basic stats work. "pet: thing" stats work. 
"Avatar: thing" and "Automaton: thing" and specialty stuff like casting time for specific spell times (aside fro cure, that works) don't yet.

**Comment by TeoTwawki** [comment]
I'll try and finish these off soon

**Comment by excenmille** [comment]
thx for the good work. Looking forward to the waltz augments since they'll greatly help dnc mainheal a party.

**Comment by R3P0FFXI** [comment]
And I live in a van down by the river
