### ISSUE TITLE
Yagrush-Mythic Club Trial

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#247]
**Date & Time**: 8/17/2015
**Frequency**:Constant
**FFXI Client Version**:30150619_2
**Character Name**: Xoe
**Race**: Hume
**Nation**: Bastok
**Main Job**: WHM
**Sub Job**: RDM
**Area & Coordinates**: Ru'Lude Gardens 
**Party or Solo**:Party and solo
**NPC or Monster Name**: Akta
**ffxiah.com link (for inventory items only): * 18973
**Multi-boxing? (multiple clients on same connection)**:  yes
**Steps To Reproduce The Issue**:  Trade Club to Akta and nothing happens...  :'(

**Comment by TeoTwawki** [comment]
Handled already when I took care of #61 just won't be effective till next maint.
