### ISSUE TITLE
Level Sync randomly syncs party member in different area

### ISSUE THREAD

**Issue by maeinit** [LegionDark/Issues#25]
**Date & Time**: 5/27/2015 Around 3-5pm PST
**Frequency**: Appeared to have happened after every level sync adjustment(leveling up/resyncing)
**FFXi Client Version**: 30150508_8
**Character Name**: Aishii
**Race**: Mithra
**Main Job**: DRK
**Sub Job**: WAR
**Area & Coordinates (Type @where to get this info.)**: Valkrum Dunes around E?-7, Lizard hill and around the outpost (Sorry was yesterday)
**Party or Solo**: Party
**NPC Name**: Level Sync
**Monster Name**: 
**Steps To Reproduce The Issue**: Me(DRK/WAR), my alt (BLM/WHM), and Kyorokudo(DNC/SAM) were in valkrum while Razaroic(BLU/NIN) was in bhafula thickets fighting to learn spells on BLU. I level synced me, my alt, and kyo to my level and we proceeded to kill stuff for book pages. When I leveled up not long after Razaroic mentions dieing to a troll randomly, when he checks his level he was also level synced ALTHOUGH the icon was not next to his name, while being in a whole different zone(whole different game continent). 
1. Level Sync 
2. Kill stuffs 
3. Level up, the person in different area's level was then also adjusted to the sync level. 
4. He would have to zone to remove link 
5. Level sync target would level up then reapply AGAIN to the person in different area.

**Comment by TeoTwawki** [comment]
@R3P0FFXI recommend opening an issue in darkstars tracker for this after verifying it is reproducible.

**Comment by R3P0FFXI** [comment]
We have been unable to reproduce this issue, if you are able to reproduce it please give us instructions on how to do so.

**Comment by R3P0FFXI** [comment]
Opened DSP issue for this bug

https://github.com/DarkstarProject/darkstar/issues/1586

**Comment by R3P0FFXI** [comment]
DSP Bug closed issue should be resolved next Maint

https://github.com/DarkstarProject/darkstar/commit/2600647fa4429c00c439ee551a9dee776c8b2d91
