### ISSUE TITLE
Puk not using Zephyr Mantle

### ISSUE THREAD

**Issue by jhalim83** [LegionDark/Issues#250]
Date & Time: 8/18/2015
Frequency: Constant
FFXI Client Version:30150619_2

Character Name: Hijikata
Race: Hume
Nation: Sandoria
Main Job: Blu
Sub Job: Nin
Area & Coordinates: Wajaom, Mamook
Party or Solo: Solo
NPC Name:
Monster Name: Puk
Item ID Number -- 
Item Name: 
Multi-boxing? (multiple clients on same connection): No

Puk not using Zephyr Mantle at all even after feeding lot of TP.

**Comment by R3P0FFXI** [comment]
I am showing Zepheyr Mantle as being obtainable from a Puk we have no control over when and where a mob uses a move
