### ISSUE TITLE
Katana Uguisu not dropping from  Aqrabuamelu in Crawlers Nest 

### ISSUE THREAD

**Issue by Roamin** [LegionDark/Issues#251]
**Date & Time**: August 18th 2015
**Frequency**: All the time
**FFXI Client Version**: 30150619_2
**Character Name**: Roamin
**Race**: Tarutaru
**Nation**: Windurst
**Main Job**: Warrior
**Sub Job**: Samurai
**Area & Coordinates**: Crawler's nest 2nd map E-7
**Party or Solo**: Party
**NPC or Monster Name**:  Aqrabuamelu 
**ffxiah.com link (for inventory items only): *  http://www.ffxiah.com/item/19302/uguisu
**Multi-boxing? (multiple clients on same connection)**: Yes 3 clients same pc
**Steps To Reproduce The Issue**: 
Killed twice and no drop, but looking up Uguisu on items tool says it drops from no mob in Crawler's nest , and looking up Aqrabuamelu it is not in the drop list, only 2 aptants.

The conquest NM forums post shows Uguisu as a drop from Aqrabuamelu.  I discussed this on irc with straf and proposed I should report it.

**Comment by Loki79** [comment]
yeah when i reworked this mob for aptants i probably didn't mover the katana to a new home.  I'll find somewhere to drop it.  Just a heads up though if it were me i would reach out to Tarot and go help him with Glavoid, it drops the +54 skill katana.

**Comment by Loki79** [comment]
INSERT INTO `mob_droplist` VALUES (4516,0,19302,330);

This still drops from scrorp.
