### ISSUE TITLE
 PoL.exe Crash On Nation New Nation Mission

### ISSUE THREAD

**Issue by Ramenuzumki** [LegionDark/Issues#252]
**Date & Time**:  August. 17/2015 (Multiple times) 
**Frequency**: Every time
**FFXI Client Version**: version 30150730_1
**Character Name**: Ramenuzumaki
**Race**: Elvaan
**Nation**: San d'Oria
**Main Job**: NIN99
**Sub Job**: DNC49
**Area & Coordinates**: Southern San d'Oria 
**Party or Solo**: Solo
**NPC or Monster Name**: 
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Nope. I only run the one client.
**Steps To Reproduce The Issue**: After I finished a mission I grabbed a new one.

My signet wasn't lasting very long, so I figured I'd get my nation rank up. Not sure if it works the same here as it does on retail, but worth a shot, and I really do like San d'Oria's story. Literally each and every time I grabbed a mission (1-1 1-2 1-3 2-1 2-3 3-1 3-3 4-1) my PoL.exe would crash, and I'd have to relaunch the game. I had mentioned it in the Legion LS, and Manthra said he had the same issue.

**Comment by R3P0FFXI** [comment]
If you were doing this before we updated with that version number try it after maint. There is a good chance your IDs were off due to the updated client.

**Comment by Ramenuzumki** [comment]
Alright. Gunna be a pain to do 4-1 though, haha. I'll get an update asap! :)

**Comment by R3P0FFXI** [comment]
Please advise if you have tested this or not.

**Comment by R3P0FFXI** [comment]
Last chance if no reply by tomorrow I am closing this

**Comment by R3P0FFXI** [comment]
no player response closing ticket
