### ISSUE TITLE
Convert

### ISSUE THREAD

**Issue by Kaoriasada** [LegionDark/Issues#253]
**Date & Time**: 8/19/2015 1:47AM
**Frequency**: Consistent
**FFXI Client Version**: Latest (Am not logged in, but I'm updated.)
**Character Name**: Halsey
**Race**: Mithra
**Nation**: San d'Oria
**Main Job**: RDM
**Sub Job**: NIN
**Area & Coordinates**: Legion -170 11 -140 (128)
**Party or Solo**: Both
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: No.
**Steps To Reproduce The Issue**: Tarot, Darkcompany, and I all crashed the server by using convert.  It's consistent and happens everytime.

Convert is crashing the server.  ._.  Both the main server and legion server, it happens immediately.

**Comment by Kaoriasada** [comment]
According to Teo:
"Someone derped a getmod."

**Comment by TeoTwawki** [comment]
Fixed, starting back up. Turns out the code was fine just github wasn't showing me all the commit. The real cause was a derp during main not updating one file, which convert happened to depend on now that Murgleis works properly.

**Comment by Kaoriasada** [comment]
MUUUURGLEIS WORKS PROPERLY?  YAAAAAAAAAAS

**Comment by TeoTwawki** [comment]
:rage:
