### ISSUE TITLE
Bug with losing spells I just learned in town before zoneing. 

### ISSUE THREAD

**Issue by kermit69** [LegionDark/Issues#254]
**Date & Time**: 8/19/2015,   2:40 a.m., 2:48 a.m. and 3:00 a.m. PDT 
**Frequency**:
**FFXI Client Version**: 30150730_1
**Character Name**: Kaalyn
**Race**: Mithra
**Nation**: Bastok
**Main Job**: Bard 1
**Sub Job**: White Mage 1
**Area & Coordinates**: X:544 Y:0 Z:-320 (106). 
**Party or Solo**: Party(Kaalyn and my main Kermit)
**NPC or Monster Name**: n/a
**ffxiah.com link (for inventory items only)** : 
**Multi-boxing? (multiple clients on same connection)** Yes:
**Steps To Reproduce The Issue**: I did this process twice with Knight's Minne song, I used the scroll inside Bastok Mines and had the spell just fine, upon zoning into South Gustaberg my spell i had just learned vanished, did this process twice to just make sure it didnt bug out on me. Changed job to BLM10 and used an aero scroll to see if the problem was just bard songs or spells in general, Upon doing the same exact process of zoning i lost Aero as well.

**Comment by Roamin** [comment]
Same thing just happened to me (Thievan) and Exorial on red mage.  All learned spells work until zoning , then they vanish and must be learned again.

**Comment by R3P0FFXI** [comment]
Confirmed DSP bug we will have to pull from DSP to fix

**Comment by R3P0FFXI** [comment]
This issue should now be fixed after todays maint
