### ISSUE TITLE
The Garden of Ru'Hmet 2/F Galka, Taru & Central elevator not work

### ISSUE THREAD

**Issue by NononoA** [LegionDark/Issues#255]
Date & Time: 8/20/2015
Frequency: Constant
FFXI Client Version:30150730_1

Character Name: Nonono
Race:Taru
Nation:San d'oria
Main Job:BLU
Sub Job:NIN
Area & Coordinates: The Garden of Ru'Hmet 2/F
Party or Solo:Party
NPC Name: The teleporter from 2/F to 3/F (Galka & Taru tower) wouldn't work. Elevator in the central room (2/F) wouldn't work.
Monster Name: 
Item ID Number 
Multi-boxing? (multiple clients on same connection): No
Steps To Reproduce The Issue: Step on the telepads, nothing happens.

**Comment by LegionTiger** [comment]
It seems like all the elevators on 2F are broken. Checked Hume, Taru and Central - none work.

**Comment by LegionTiger** [comment]
Update: after some testing I found the following:
- after using one elevator from 1F to 2F (whichever) the 2F elevator wont work
- if u @return into 2F u CAN use the 2F elevator to 3F, but then u again can't use the 3F elevator

So it seems like the zoning after using an elevator induces an error somehow.

**Comment by LegionTiger** [comment]
Workaround (this works only with one account logged in / not multiboxing!):
- after u have used an elevator, log out
- log back in, now u can use the next elevator
- rinse repeat for every elevator

This way I was able to advance the mission.

**Comment by TeoTwawki** [comment]
@LegionDark/gm @LegionDark/owners needs reported to DSP, might possibly already be in their tracker not sure, but need to be sure they know the elevators are farked up unless one of you thinks you can fix and pull request it yourselves.

**Comment by TeoTwawki** [comment]
@LegionTiger @NononoA thanks for the info and the report, we'll try and get this cleared up soon.

**Comment by R3P0FFXI** [comment]
Is this still an issue?

**Comment by PikaFox** [comment]
It seems to be still an issue; i took an elevator in the grand palace, and a 2nd elevator wouldnt respond when i ran over it.

**Comment by bathuka** [comment]
log off / log on and that work at all teleport you use log off / log on 
i know that is annoying

**Comment by R3P0FFXI** [comment]
K im reporting this to DSP then

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
