### ISSUE TITLE
Estoqueur's Fuseau +2:not work,Enhances "Refresh" potency

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#256]
Date & Time: 20/08/2015, 18:00pm
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: Rukitsu
Race: Hume
Main Job: Rdm
Sub Job: whm
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name: moogle 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:Enhances "Refresh" potency
Refresh spells give an extra 1 MP per tick.,,,not work

**Comment by Loki79** [comment]
Modifier doesn't exist yet.

**Comment by TeoTwawki** [comment]
I created it in DSP tonight, and added mod to item and the check relevant scripts.
