### ISSUE TITLE
Quatz Thatlum + 1 VWNM bugged drop

### ISSUE THREAD

**Issue by goferffxi** [LegionDark/Issues#257]
**Date & Time**: 21/08/2015  17:56 GMT
**Frequency**: not sure
**FFXI Client Version**:30150730_1
**Character Name**:Gofertwo
**Race**:Hume
**Nation**:Bastok
**Main Job**:WHM
**Sub Job**:RDM
**Area & Coordinates**:X528 Y25 Z484
**Party or Solo**:party
**NPC or Monster Name**:Murk Veined Banberry
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/21359/quartz-tathlum-1
**Multi-boxing? (multiple clients on same connection)**:Yes
**Steps To Reproduce The Issue**:Lotted on Item treasure pool dropped stating that player did not meet requirements for item
![gofer_2015 08 21_175150](https://cloud.githubusercontent.com/assets/12684459/9414177/6467a66c-482e-11e5-8f9c-bdbacfeaa036.png)

**Comment by Roamin** [comment]
I just want to confirm with my own screenshot that this really happened. Gofertwo was allowed to lot, but drop failed.

![img_20150821_125555](https://cloud.githubusercontent.com/assets/398228/9414482/bb7a7344-4806-11e5-9b96-f85009c5f576.png)

**Comment by TeoTwawki** [comment]
In both screencaps I see all loot falling at once.

If 1 person of the group doesn't pass, even though someone lotted, it can hit dirt unlike retail: known dsp bug that they need to nagged senseless about in their tracker.

**Comment by Loki79** [comment]
looks like its missing a item_basic entry

**Comment by Loki79** [comment]
ill get to it before next maint.

**Comment by TeoTwawki** [comment]
@Loki79 if you are 100% sure, and this was also an item Legion added, remove the not our bug label. Screenshot looked like what ~~usually~~ always happens on DSP when someone expects it to auto fall to them though, and that is still a known DSP bug.

**Comment by goferffxi** [comment]
Gofer two had lotted on the item. His lot wad am abysmal 96 but he
deffinately lotted . The odd part was that it stated he didn't meet the
requirements.

**Comment by TeoTwawki** [comment]
@goferffxi you aren't reading what i actually wrote. Nobody disputed that you lotted.

**Comment by TeoTwawki** [comment]
@goferffxi > In both screencaps I see all loot falling at once.
>
> If 1 person of the group doesn't pass, even though someone lotted, it can hit dirt unlike retail: known dsp bug that they need to nagged senseless about in their tracker.

And Loki already said its missing from item basic.

**Comment by TeoTwawki** [comment]
@goferffxi 
> In both screencaps I see all loot falling at once.
>
> If 1 person of the group doesn't pass, even though someone lotted, it can hit dirt unlike retail: known dsp bug that they need to nagged senseless about in their tracker.

And Loki already said its missing from item basic.

**Comment by Loki79** [comment]
will be in with the rest of the VW stuff for next maint.
