### ISSUE TITLE
Current and Future Voidwatch drops.

### ISSUE THREAD

**Issue by Loki79** [LegionDark/Issues#258]
@Strafeous and @Kaoriasada -  I need you guys to go through EVERY drop in EVERY chapter on the VW drop spreadsheet and control + F through each one of the tables and make sure each item has and entry in every table.  So each item will need an entry in item_basic (normal or custom version), item_armor (normal or custom version), item_mods (normal or custom version), and if the item is a weapon then also item_weapon.  If you need copies of the tables again let me know and ill send them again, if you still have the ones I sent your good to go nothing there has changed.  If any entries are missing or incorrect please make or correct them an dsend to me via email so I can get them in.  This takes priority over anything else atm we are getting too many of these damn reports so need to put this to bed.  If you have any questions grab me in IRC.  Thanks!

**Comment by Strafeous** [comment]
I finished all of them last night and i'm pushing them to push in about 30 mins whenever i fix my .mod problem

**Comment by Strafeous** [comment]
Added 252 new items

**Comment by Loki79** [comment]
kk cool.  Make sure to run it through Travis and get the all clear.

**Comment by Strafeous** [comment]
That name is offlimits

**Comment by Strafeous** [comment]
@Teotwawki and I are just having the time of our lives over here trying to fix the End of line error I got on the new items ;:..:;

**Comment by Kaoriasada** [comment]
@Loki79 @Strafeous 
Did Strafeous do this or do I need to do it?

**Comment by TeoTwawki** [comment]
Straf has the lines he's just going to have to reinsert them to a fresh copy of the file to because his working copy of the repository gave him the finger

**Comment by Kaoriasada** [comment]
So...what do I need to do?

**Comment by Loki79** [comment]
@Kaoriasada nothing if he has it done then move forward to going through all the Abyssea zones.

**Comment by Kaoriasada** [comment]
@Loki79 OK.  I'm going to begin working on that then.  :)

**Comment by Strafeous** [comment]
If you've decided to release the chpt 3 on the date you told 3p0 in the irc, that would be much better, going through 5000+ lines of item_mod has made me very unhappy

**Comment by TeoTwawki** [comment]
The NPC (for the required stratum abyssite) and RL also gave this a hearty FU, I keep waking up and going back to bed and waking up, killing my productivity.

**Comment by Loki79** [comment]
yeah we will shoot for 9/1 release.  you don't need to go through mods like that, these are all new items crtrl f through mods, if it has an entry assume its correct.

**Comment by Loki79** [comment]
@LegionDark/gm where we at with this?  Did these item ever get pushed through?  If so let me know and lets close this out.

**Comment by Loki79** [comment]
Again, any clue what happened to this?

**Comment by TeoTwawki** [comment]
I think his net went out, I left Straf a message and he hasn't gotten back to me.

**Comment by Kaoriasada** [comment]
@TeoTwawki @Loki79 I talked to someone who knew Strafeous irl via phone and they said he was in jail.  They didn't give me any specifications, but they said he was in jail.

**Comment by TeoTwawki** [comment]
I don't think he'd appreciate that being said in public (which github basically is).

**Comment by Kaoriasada** [comment]
@Loki79 if he never finished/sent in the voidwatch drops, send me a full list and I'll finish the items before starting on the crafting items for Repo

**Comment by Loki79** [comment]
@Kaoriasada the rest should be in but could you check the ones listed below.  if not in please make them :D  Thanks!

Etiolation Earring	
Wingcutter +1	
Ternion Dagger +1	
Enervating Earring
Eosuchus Club
Pulfanxa
Cryptic Earring
Kumalo
Emxgha
Deviant Necklace	
Jugo Kukri +1	
Lekboza	
Lugra Cloak			
Miasmaic Pants			
Hygieia Clogs

**Comment by Kaoriasada** [comment]
Just sent in the remaining items to Loki.

**Comment by Strafeous** [comment]
Wasn't your place to tell anyone about my situation.
Do not mention me again.
