### ISSUE TITLE
Mission 5-1: No Burnt Seal Post Fight

### ISSUE THREAD

**Issue by Talen2** [LegionDark/Issues#259]
**Date & Time**: 8/22/15 & 12pm
**Frequency**:1
**FFXI Client Version**:
**Character Name**: Talen
**Race**:Elf
**Nation**:Sandy
**Main Job**:MNK
**Sub Job**:BLU
**Area & Coordinates**:Fei'Yin, Qu'Bia Arena
**Party or Solo**:Solo
**NPC or Monster Name**: Archlich Taber'quoan
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:No
**Steps To Reproduce The Issue**:Solo 5-1

**Comment by Talen2** [comment]
Re-attempted fight @ 4:55 pm est with 3 others. Everyone got the KI, but me.

**Comment by Kaoriasada** [comment]
Logging on to check your variable now.  Was having computer issues.  @Talen2

**Comment by Kaoriasada** [comment]
Fixed.
