### ISSUE TITLE
Koghatu the unpoppable

### ISSUE THREAD

**Issue by maikuru23** [LegionDark/Issues#26]
Date & Time: 5/28/2015 2PM PST
Frequency: always
FFXi Client Version: 30150508_8
Character Name: Maiku
Race: Taru
Main Job: PLD
Sub Job: NIN
Area & Coordinates: x: -127  y:-177  z:11  (77)  abyssea ule
Party or Solo: both
NPC Name: ???
Monster Name: Koghatu
Steps To Reproduce The Issue: 
1. Go to abyssea Ule at stated coords
2. turn camera so facing wall, or use widescan for ???'s nearby
3. Target the ??? inside the wall and below floor
4. The ??? is for Koghatu a pre pop for the giant who is a pre pop for Pantokrator.
5. This is unpoppable without using teleport hacks.
6. ???

https://www.bg-wiki.com/bg/Koghatu

**Comment by Loki79** [comment]
fixed.  be in next maint.
