### ISSUE TITLE
Unable to travel to the past

### ISSUE THREAD

**Issue by beardd** [LegionDark/Issues#260]
Please close this issue. It seems I went in the maw in saur. sorry about this.

**August 22, 2015  @ 3:16 PM EST*: 
**100% of the time**:
**FFXI Client Version**:
**Pso/Mor**:
**Tarutaru/Hume**:
**San d'Orian**:
**BLM**:
**WHM**:
**Rolanberry fields / Batalia Downs**:
**Party**:
**Cavernous Maw**:
**No**:
**I click on the Cavernous Maw in Batalia Downs or in Rolanberry Fields and it says "Nothing Happens..." instead of moving the character in to the past area. I have collected the pure white feather and have been into the past successfully for the DNC quest. I am unable to enter the past again.**:

**Comment by TeoTwawki** [comment]
You have to actually fill in the template..

**Comment by TeoTwawki** [comment]
At the very least, i want a client version here when reporting an NPC (the maw is an NPC) nto behaving as expected.

**Comment by TeoTwawki** [comment]
p.s.
if when you went into the past before, if you did not return to the present through those maws, its normal for them to not function, white feather or not. Each maw has to be unlocked from the past side, and if your original landing sight saw Sauramogue that's where you'll have to re-enter the past at.

**Comment by R3P0FFXI** [comment]
Please advise if you were able to return to the past using one of the 3 maws, Saru, Rolan or batilla

**Comment by R3P0FFXI** [comment]
2nd contact attempt Please advise if you were able to return to the past using one of the 3 maws, Saru, Rolan or batilla, if we do not hear from you by Wednesday I will be closing the ticket

**Comment by beardd** [comment]
Sorry, I edited the issue instead of commented. I found I had to go through sauramogue I didn't realize. You can close this issue.
