### ISSUE TITLE
Chcoboleech not working.

### ISSUE THREAD

**Issue by Lordstrife** [LegionDark/Issues#261]
Area: Dangruf Wadi
Notorious Monster: Chocoboleech
Item needed: Vial of Fresh Blood
Problem: I went to the locations Wiki has listed, i get to correct area and use the correct item to pop the NM and it does not take item. I click the ??? and says small hole in ground meaning right location but does not seem to work.

**Comment by R3P0FFXI** [comment]
Please resubmit with the proper template

**Comment by Loki79** [comment]
This is a pretty new NM and is not coded, nor is the drop.  No plans to get to it anytime soon so closing this out.
