### ISSUE TITLE
Rank 5-1 BCNM fight not giving key item Burnt Seal. *update!!! killed 3rd time and got the item :D

### ISSUE THREAD

**Issue by luxurywagon** [LegionDark/Issues#262]
**Date & Time**: 8/23/2015  6:00~7:00PM
**Frequency**: two times in a row.
**FFXI Client Version**: 30150730_1
**Character Name**: Manthra
**Race**: Mithra
**Nation**: San D' Oria
**Main Job**: Samurai
**Sub Job**: Warrior
**Area & Coordinates**: Qu'Bia Arena
**Party or Solo**: Party
**NPC or Monster Name** : Archlich Taber'quoan
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: click on bcnm to do the fight, but after killing archlich, can't get key item Burnt Seal.

**Comment by R3P0FFXI** [comment]
Issue resolved user received KI
