### ISSUE TITLE
Rubeus Jacket doesn't drop from Alkyoneus?

### ISSUE THREAD

**Issue by excenmille** [LegionDark/Issues#263]
Date & Time: 8/24/2015
Frequency: 
FFXI Client Version: 30150730_1
Item Name: Rubeus Jacket
ITEM ID: 10452
Monster Name: Alkyoneus 
Steps To Reproduce The Issue:

Rubeus Jacket is listed to drop from Alkyoneus in upper delkfutt tower according to this forum thread "Conquest NM, Custom drops": http://legiondark.com/forums/viewtopic.php?f=27&t=80

But the website's drop tool gives "The item(s) found appear to not drop from any monster in the world." Is it dropped by Alkyoneus?

**Comment by Loki79** [comment]
Be in next maint.
