### ISSUE TITLE
VNM Nosferatu (Mythic trial) Depopped in the middle of of fight (multiple times)

### ISSUE THREAD

**Issue by slaggyt** [LegionDark/Issues#264]
**Date & Time**: August 24 2015
**Frequency**: 2 times
**FFXI Client Version**:30150730_1
**Character Name**: Lionpaw
**Race**:Taru
**Nation**:Bastok
**Main Job**: BLM
**Sub Job**: RDM
**Area & Coordinates**: E-9 Adeywa subterrane
**Party or Solo**: Party
**NPC or Monster Name**: Nosferatu
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Multi 
**Steps To Reproduce The Issue**: Fought him again.  First fight he depopped when the toon that traded the r/ex item died.  PT was still alive.  Second Fight I bound him went to rest mp when he was unbound and ran to me he did a TP move Nocturnal Servitude, chat said I was charmed then he depopped. PT was till alive.  (In a previous fight)  When I use whm mule to pop him he goes after the mule the entire fight even when I nuke 90% of his HP. If I stun him at the start and bind nuke so whm never uses cure he goes after the WHM the entire fight and never after me who is attacking him 100%

**Comment by Loki79** [comment]
I just tested this and it works correctly, or as correctly as it can.  ENM is fucked on DSP servers, always has been and more than likely always will be.  If all members of a party are charmed the mob will depop, it should stay up the 5 min but currently does not.  This issue has already been brought to DSP.

**Comment by TeoTwawki** [comment]
Solution: make sure a party member is out of charm range
