### ISSUE TITLE
Bug Report Abyssea 

### ISSUE THREAD

**Issue by Az1r** [LegionDark/Issues#265]
**Date & Time**: 
**Frequency**: Always
**FFXI Client Version**: 
**Character Name**: Unisei Wargasmic Redsanchez
**Race**: Mitha Hume Hume
**Nation**: n/a
**Main Job**: THF WHM PLD
**Sub Job**: n/a
**Area & Coordinates**: Aby La theine
**Party or Solo**: Party
**NPC or Monster Name**: Dozing Dorian
**ffxiah.com link (for inventory items only)**:  
**Multi-boxing? (multiple clients on same connection)**: Yes x3
**Steps To Reproduce The Issue**: Trying to trade the pop item (Dried Chigoe) to the L-6 ??? (Dozing Dorian force pop location) , and it doesn't work. It asks for some other item completely which I am sure we don't have access to (Pair of Maze Monger Cuffs +1).

**Comment by Kaoriasada** [comment]
Thanks for reporting!  I'm actually compiling a huge list of Abyssea bugs to be fixed right now, so if you know of any more, please let me know!!  <3

**Comment by Kaoriasada** [comment]
Looks like someone typo'd when coding him.  

The ??? does ask for "Pair of Maze Monger Cuffs +1" which has an item ID of 2981, and it does pop when traded the cuffs.  The correct pop item is a "Dried Chigoe", which has an item ID of 2891.

**Comment by TeoTwawki** [comment]
@Loki79 you typo'd :smiley: lol

**Comment by Az1r** [comment]
Lol thanks for the quick fix you guys

**Comment by Loki79** [comment]
Resolved.
