### ISSUE TITLE
CoP 7-5 The Warrior's Path / Tenzen Fight

### ISSUE THREAD

**Issue by LegionTiger** [LegionDark/Issues#266]
Date & Time: August 25th 2015
Frequency: Everytime
FFXI Client Version: 30150730_1
Character Name: Tigercub
Race: Tarutaru
Main Job: Black Mage
Sub Job: White Mage
Area & Coordinates: Sealion's Den
Party or Solo: Party
NPC Name: Not applicable
Monster Name: Not applicable
Multi-boxing? (multiple clients on same connection): YES , same connection same pc
Steps To Reproduce The Issue: Enter battlefield "The Warrior's Path"

Upon entering the battlefield you get 3250 EXP and cannot enter the fight. You can advance to 8-1 after this. But no fight.

**Comment by Kaoriasada** [comment]
Although we're already aware of this, thank you for reporting!  (-:

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
