### ISSUE TITLE
AF+1 trouble

### ISSUE THREAD

**Issue by LegionTiger** [LegionDark/Issues#267]
Date & Time: August 23th 2015
Frequency: Two times tried with different gear
FFXI Client Version: 30150730_1
Character Name: Tiger
Race: Hume
Main Job: Black Mage
Sub Job: Red Mage
Area & Coordinates: Port Jeuno (J-8)
Party or Solo: Party
NPC Name: Sagheera
Monster Name: Not applicable
Multi-boxing? (multiple clients on same connection): YES , same connection same pc
Steps To Reproduce The Issue: 

Tried to trade the following to her:

1st try:
- Magus Jubbah
- Luminian Thread
- Flameshun Cloth
- Wamoura Cloth
- 30 Ancient Beastcoins

2nd try:
- Fighter's Calligae
- Ecarlate Cloth
- Argyro Rivet
- Drk. Brz. Sheet
- 25 Ancient Beastcoins

No response.

**Comment by Loki79** [comment]
May be an NPC ID shift ill check it out next time I'm in game.

**Comment by Kaoriasada** [comment]
Do you have the sufficient mission progress to do these upgrades?

**Comment by LegionTiger** [comment]
Hmm, I thought so:
CoP 8-4 Dawn
ZM 17 Awakening
Rank 10 Nation

**Comment by Loki79** [comment]
@Kaoriasada can you check this NPC for me?  Just see if you get any action at all and if any trades work.

**Comment by Kaoriasada** [comment]
@Loki79 I can check on Sami, Halsey doesn't have the sufficient mission progress.

**Comment by TeoTwawki** [comment]
@Kaoriasada its usually best to just use a character we don't actually play on and use the GM commands to alter that characters data as needed: `@addmission` `@completemission` etc. I often create spare Testdummy Taru's and delete them when I am done while testing things in DarkStar.

**Comment by Kaoriasada** [comment]
@TeoTwawki  I had no clue about those commands

**Comment by Kaoriasada** [comment]
@TeoTwawki or how they work, so if you could give me a rundown, that'd be great, and then I can check

**Comment by TeoTwawki** [comment]
@Kaoriasada 
https://github.com/DarkstarProject/darkstar/blob/master/scripts/commands/addmission.lua#L12
and
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/missions.lua

See where in the command script it says
`function onTrigger(player, logId, missionId, target)`
That line says what the arguments for the command are. In the global script, the 1st thing you see are the Log IDs (area ID it calls them) and then the Mission ID lists for each one.

`@addmission 0 1 Timmy`
would add San d'Oria (logID 0) mission "BAT_HUNT" (MissionID 1) to a target player named Timmy. 

And if you omit the target player like so: 
`@addmission 0 1`
then sandy mission 1 would be set on the user (you), not Timmy.

**Comment by Kaoriasada** [comment]
@TeoTwawki but it adds these as current missions, not completed.  So is it going to work for me if I don't have the rest of the progress and variables?

**Comment by Kaoriasada** [comment]
@Loki79 I tested it.  I got no response.

**Comment by LegionTiger** [comment]
Update on this:

1) I traded her 30 Ancient Beastcoins
2) I traded her the other items

Now it worked! So the ACs must be traded separately and she must have enough for the upgrade.
