### ISSUE TITLE
Shinryu

### ISSUE THREAD

**Issue by ronnymp** [LegionDark/Issues#268]
Date & Time: August 25th 2015
Frequency: one run
FFXI Client Version: 30150730_1
Character Name: Miudo
Race: Galka
Main Job:warrior
Sub Job: samurai
Area & Coordinates: Aby Empyreal paradox
Party or Solo: Alliance
NPC Name: Shinryu
Monster Name: Shinryu
Multi-boxing? (multiple clients on same connection): YES , Serjoca.

Me and qigang and aurel was the tank of the run , and then we died and Auto HP  ... when we type @return and shinryu draws in we cant do nothing just watch ... also with his drawn in is getting alot ppls out of area and cant do nothing ... thats is it ^^ , sorry for tyt and for my bad english!

**Comment by Dimmabr** [comment]
Many bugs in Shinryu fight, i was with it and 15 more ppls, impossível to hits shinryu and i think it is hard to drop lunar abyssite, i think it can be bugged...

**Comment by R3P0FFXI** [comment]
This is not a bug it is working as intended Shinryu is a BCNM you cannot leave a BCNM and then return once you are out of the fight you are out. Unfortunately if hit by Auto HP bug there is nothing we can do to fix this until DSP fixes it.
