### ISSUE TITLE
Abyssea glitches/bugs

### ISSUE THREAD

**Issue by Kaoriasada** [LegionDark/Issues#269]
Abyssea glitches
* Cannot trade "Dried Chigoe" to the ??? at (L-6) of Abyssea - La Theine Plateau to spawn Dozing Dorian.  Asks for a "Pair of Maze Monger Cuffs +1" which has an item ID of 2981, and does spawn if traded this item.  Looks like someone typo'd when coding his spawn, correct spawn item is "Dried Chigoes" and has an item ID of 2891.  He's working properly outside of his spawn being messed up.
* Sirrush is on a timed spawn of 15 minutes, he's supposed to be force spawned by trading "Molt Scraps", which have an item ID of 3086, to a ??? at (I-J/11) in Abyssea - Misareaux Coast.
* Sisyphus is respawning 60 seconds after death, supposed to be on a 10~15 minute respawn.
* Mechanical Menaces are not spawning in (G/H-8).  Further more, there were reports of them showing up as orcs instead of Acroliths.

I'll continue to add to this list as I find more issues.  I had to leave for today.

**Comment by Kaoriasada** [comment]
Added more.

**Comment by Loki79** [comment]
ok all of this should be good after next maint.

**Comment by Loki79** [comment]
going to leave it open until then though incase something else pops up.

**Comment by Roamin** [comment]
The ??? for spawning a  "La Theine Liege" in abyssea la theine N-W of I-7 is called "Achieve Master" instead of ??? . Trading the transparent insect wing still spawns the NM though.

**Comment by TeoTwawki** [comment]
ID shifted so client and server mismatch screwed up NPC names in zone. Gonna have to fix in a PR to DSP.
