### ISSUE TITLE
Chariots and Unicorns (Model mismatch)

### ISSUE THREAD

**Issue by maikuru23** [LegionDark/Issues#27]
Date & Time: 5/28/2015 2PM PST
Frequency: always
FFXi Client Version: 30150508_8
Character Name: Maiku
Race: Taru
Main Job: PLD
Sub Job: NIN
Area & Coordinates: x: -307   y:-175    z:-10 (90) abyssea ule
Party or Solo: both
NPC Name: N/A
Monster Name: Impervious Chariot
Steps To Reproduce The Issue:
1. Go to abyssea Ule at stated coords
2. Find Impervious Chariot at stated coords
3. Visually inspect Impervious Chariot
4. Chariot ≠ Monoceros/Ixion
5. KI drops/Drops are correct but model does not reflect retail and mobs TP moves and junk do not reflect actual mob either.
6. ???
https://www.bg-wiki.com/bg/Impervious_Chariot

**Comment by Loki79** [comment]
Fixed.  Be in next maint.
