### ISSUE TITLE
Relic trial 75-85 problema

### ISSUE THREAD

**Issue by SquallerSnake** [LegionDark/Issues#271]
Date & Time: 8/27/15
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: Squaller
Race: Hume
Nation: Bastok
Main Job: 99 PLD
Sub Job: WAR
Area & Coordinates: NA
Party or Solo: NA
NPC or Monster Name: Seww the Squidlimbed
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): No
Steps To Reproduce The Issue:

I'm on relic trial 75-85 with Aegis, i have killed Seww the Squidlimbed 5 time now, all with Aegis equipped but the counter is stopped at 3/4. When i defeat him the Row "you completed a trial objective" appears but the counter remains at 3.  I link the Stamp.

![squaller_2015 08 27_140738](https://cloud.githubusercontent.com/assets/13245127/9521236/f2992660-4ccd-11e5-81f8-70590d33e9ac.png)

**Comment by TeoTwawki** [comment]
Found and fixed error.

**Comment by SquallerSnake** [comment]
Thank you, now it works!
