### ISSUE TITLE
Heka's kalasiris & Nefer Khat: Set bonus doesn't work

### ISSUE THREAD

**Issue by excenmille** [LegionDark/Issues#273]
Date & Time: 8/27/15
Frequency: always
FFXI Client Version: 30150730_1
Character Name: orangeorange
Race: Hume
Nation: Bas
Main Job: WHM
Sub Job: SCH
Area & Coordinates: NA
Party or Solo: solo
NPC or Monster Name: 
Item IDs: 11867 and 10868
Multi-boxing? (multiple clients on same connection): Yes
Steps To Reproduce The Issue:

The body piece is supposed to give 1 mp/tick and this does work properly. However, when equipped together with the head piece there should be another extra set bonus of 2 mp/tick. But this set bonus does not work. Killed Bonnacon today, wore the pairing set and got only 1mp/tick.

http://ffxiclopedia.wikia.com/wiki/Heka's_Kalasiris

**Comment by Kaoriasada** [comment]
We already have a closed report for this.  It's going to be implemented in the next maintenance.

**Comment by TeoTwawki** [comment]
#244

**Comment by TeoTwawki** [comment]
p.s.
@LegionDark/owners this is why I was leave the issues open till after maint before.
