### ISSUE TITLE
Relic Trial Bug

### ISSUE THREAD

**Issue by SquallerSnake** [LegionDark/Issues#274]
Date & Time: 8/27/15
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: Squaller
Race: Hume
Nation: Bastok
Main Job: 99 PLD
Sub Job: WAR
Area & Coordinates: NA
Party or Solo: NA
NPC or Monster Name: Venessa / Moogle
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): No
Steps To Reproduce The Issue:

I have killed all the nm of relic trial 75-85, all counter are full but the status completition is 0.
I saw another post on this problem but i don' t understand.
Whitch is the command to update the completition counter?

![squaller_2015 08 27_211229](https://cloud.githubusercontent.com/assets/13245127/9530521/a54a642c-4d00-11e5-84fd-c8007c830845.png)

**Comment by TeoTwawki** [comment]
Was there any error message during any of the NM kills? When I rewrote the system I made it print errors if a step failed. Somehow it died at the end of an NM kill.

**Comment by Kaoriasada** [comment]
Trading it to the moogle doesn't work?

**Comment by TeoTwawki** [comment]
@Kaoriasada his completion var isn't set yet. I need to find WHERE it failed to set before correcting it for him. He can't trade to moogle yet.

**Comment by TeoTwawki** [comment]
@Kaoriasada entire reason complete var sets when the other vars reach the proper amounts is so I don't have to check trial conditions + 6 vars states every time I want to see if they are ready for the next upgrade..This is a critical step.

**Comment by SquallerSnake** [comment]
No, I didn't see any error message after the kills, and I never died on these fights.
The only problem was with Seww the Squidlimbed when the counter was not incrementing (Bug #271 )
You fixed this problem yesterday and after I kill the NM and the counter incremented to 4/4.

**Comment by TeoTwawki** [comment]
When I say "it died" I mean my script, sorry. Trying to determine where code stopped execution. Can you tell me which NM was your final kill?

**Comment by TeoTwawki** [comment]
@SquallerSnake if you have time I can get in game with you right now to fix your trial.

**Comment by SquallerSnake** [comment]
Ok i Will look for a Gm when i Will be online, my final nm was dune widow.

**Comment by simthra** [comment]
The same thing just happened to me too; I've killed all the NMs for the excalibur trial and completion status is still " 0 ". I've never received any error messages during the process.
![thranduil_2015 08 28_185131](https://cloud.githubusercontent.com/assets/12772770/9552327/6c9b6420-4db7-11e5-833b-a3e8c8cf205e.jpg)

**Comment by TeoTwawki** [comment]
@simthra I'm working on it. I only just found the bug.

**Comment by TeoTwawki** [comment]
@simthra whats your in game name? You basically added a me2 without info, I don't see character with your github name in the database.

**Comment by TeoTwawki** [comment]
@SquallerSnake Its now corrected and I have manually edited the database for you since nobody seems to have caught you online (that is more difficult than running simple GM command, was hoping to avoid it).

**Comment by TeoTwawki** [comment]
@simthra I'm so tired (lack of sleep) that it didn't even occur to me to look in screenshot to get your player name.

**Comment by TeoTwawki** [comment]
Now you are both fixed.

Internally I got 2 of the NM's variable counters backwards with what was display, so it was looking for that 4 dune windows by mistake, and 3 of something else. Its now corrected and I have manually edited the database now for both of you. @simthra @SquallerSnake

**Comment by simthra** [comment]
Thank you very much Teo.

**Comment by SquallerSnake** [comment]
Thank you very much
