### ISSUE TITLE
Everything i know about the abyssea - attohwa eruca crash

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#275]
**Date & Time**: 8/28/15
**Frequency**: Randomly
**FFXI Client Version**: 30150730_1
**Character Name**: Tarot
**Race**: Hume
**Nation**: San
**Main Job**: NA
**Sub Job**: NA
**Area & Coordinates**: Abyssea Attohwa by erucas
**Party or Solo**: All
**NPC or Monster Name**: Blazing Eruca + Ignis Eruca
**ffxiah.com link (for inventory items only)**: NA
**Multi-boxing? (multiple clients on same connection)**: Either
**Steps To Reproduce The Issue**:

Unknown what exactly triggers it, as it doesnt seem to always happen. It also can affect only a small group of people within the vicinity of the Blazing Eruca area. As far as i can tell, it happens when fighting either Blazing Eruca or Ignis Eruca. Some speculation that it is their TP move Incinerate that causes it. The exact cause is hard to pin because it doesnt seem to be repeatable on command, although a group farmiing Erucas will quickly rack up a couple PoL crashes over the course of its farming.

**Comment by Loki79** [comment]
Its a zone crash and unrelated to the mob itself.  We have yet to determine the cause and it doubtful DSP will pay any attention to anything abyssea related for some time.  Sadly atm just kind of stuck dealing with it.

**Comment by TeoTwawki** [comment]
I spent several hours on this, could not get it to happen for me under any circumstances. **Will reward first person to give me a definite trigger that makes it happen for my test character with known clean and  undamaged client files with actual consistency (**"*random*" **isn't reproducible)**

**Comment by TeoTwawki** [comment]
ignore me I misread
this is a duplicate issue

**Comment by TeoTwawki** [comment]
#85

**Comment by TeoTwawki** [comment]
@PikaFox its the actual packets in the area.

**Comment by Kaoriasada** [comment]
Raptors in Misareaux do the same bullshit

**Comment by TeoTwawki** [comment]
@Kaoriasada its not the mob, its the area. I can trip it just running through Abyssea-Attowha fighting nothing. Damned fixed value packet nonsense.
