### ISSUE TITLE
Caladbolg----Masamune---- ws way too low 

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#276]
Date & Time: 28/08/2015, 08:00am
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: Aurel
Race: Hume
Main Job: Sam and Drk
Sub Job: Sam/Drk
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name: moogle 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue: ws way too low  vs NM, full merit attributes .----- ws deflate. ------- I do not like war, war ws 10k vs sam 2k - 2k GS drk dmg -------- all weapons xd 119 equals the GM who use them do great harm was the reason empy weapon to do 2

**Comment by TeoTwawki** [comment]
Legion server is using the pre SoA WS maths. Not gonna see huge numbers like on current retail.

**Comment by nekrol** [comment]
It is LegionDark  ,very good .very best vs retail.

**Comment by R3P0FFXI** [comment]
All WS are working as intended
