### ISSUE TITLE
Veridical Conflux in Pashhow Marshlands (S) not giving CS for voidwatch Chapter 2.

### ISSUE THREAD

**Issue by Roamin** [LegionDark/Issues#277]
**Date & Time**:  August 31st 2015
**Frequency**: All the time
**FFXI Client Version**: 30150730_2
**Character Name**: Dimma
**Race**: Hume
**Nation**: Sandy
**Main Job**: BLU
**Sub Job**: RDM
**Area & Coordinates**: Pashow Marshlands [S] , J-9  , x: 345 y:25 z:-160 
**Party or Solo**: Party
**NPC or Monster Name**: Veridical Conflux
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Yes , same PC (I assume)
**Steps To Reproduce The Issue**:
I'm writing this on behalf of Dimma to make it cleared because his english is not perfect.

He has cleared the 3 nation bosses of VW chapter 1  ( Celaeno 	Hahava 	Voidwrought ) , and he has the 3 stratum abyssites Indigo, Crimson and Jade at level IV but when he talks to the Veridical Conflux in Pashhow Marshlands [S] it says :

Conditions not met.
Variable 'VW_3_NATIONS' value is : 0 ..and must be 7
Quest GUARDIAN_OF_THE_VOID' Status is: 0 ..and must be 0

According to the forum post on VW Chapter 2 , after killing the 3 Nation bosses you should be able to trigger a CS at the veridical conflux in Pashhow.  No CS was triggered and no key item (White stratum abyssite) was received.

Is it a missing requirement, or a bug that is preventing us from going further?

Sorry if its a requirement (from retail maybe) that we have missed somewhere.

Dimma is Rank 6.

**Comment by Loki79** [comment]
i will be in game in a moment to fix Dimma's Variable.  He will need to follow the steps from this link after getting the CS in pash [s].
https://www.bg-wiki.com/bg/Drafted_by_the_Duchy

**Comment by Roamin** [comment]
After the variables were fixed , it was possible to follow the link's directions to acquire both Emblem and White stratum Key items. We used the Rulude gardens CS .

Thank you.
