### ISSUE TITLE
10000 byne bill "swallowed" by Switchstix!

### ISSUE THREAD

**Issue by LegionTiger** [LegionDark/Issues#278]
Date & Time: August 31st 2015
Frequency: Once
FFXI Client Version: 30150730_1
Character Name: Tiger
Race: Hume
Main Job: Thief
Sub Job: Dancer
Area & Coordinates: Castle Zvahl Baileys, (I-8) Map 1
Party or Solo: Solo
NPC Name: Switchstix
Monster Name: Not applicable
Multi-boxing? (multiple clients on same connection): YES , same connection same pc
Steps To Reproduce The Issue: 

By failure traded Switchstix my 10000 byne bill. He took it and will not return it. Is this supposed to be like that?

**Comment by R3P0FFXI** [comment]
This is actually normal don't ask me why SE wrote it this way. This should not be happening again as it was fixed in DSP

**Comment by Kaoriasada** [comment]
@LegionTiger contact me in-game the next time you're online and I'll help you sort it out.  :)

**Comment by Kaoriasada** [comment]
Sorted out!
