### ISSUE TITLE
Voidwatch Officer ,not work for me

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#279]
Date & Time: 02/09/2015, 08:00am
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: Aurel
Race: Hume
Main Job: Sam and Drk
Sub Job: Sam/Drk
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name: moogle 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue: I have the key items Voidwatcher's emblem: Jeuno and White stratum abyssite ,so speak with a Voidwatch Officer in one of the three nations (past or present) and not receive the voidstone

**Comment by nekrol** [comment]
![aurel_2015 09 02_142628](https://cloud.githubusercontent.com/assets/13084662/9638770/b8a4dca0-517e-11e5-8214-2552456cafc8.png)
all ki

**Comment by Kaoriasada** [comment]
Your voidstones show up as a currency under your status menu, not as a KI.

**Comment by nekrol** [comment]
Voidwatch Officer not responding ,
![aurel_2015 09 02_174430](https://cloud.githubusercontent.com/assets/13084662/9643812/6c6b35a2-519a-11e5-8d34-6c6e992edc61.png) I and waited more than 48 hours

**Comment by R3P0FFXI** [comment]
Which NPC give us the zone and POS of the NPC you are attempting to goto with voidwatch

**Comment by nekrol** [comment]
1Pashhow Marshlands (S) and check the Veridical Conflux at  for a cutscene ...2 Speak with Voidwatch Officers in either Southern San d'Oria  ---3Travel to Ru'Lude Gardens and examine the Door:Audience Chamber for a cutscene --4Speak with Voidwatch Officers in either Southern San d'Oria

**Comment by Loki79** [comment]
SS is from Jeuno... if I ask Teo to get involved and your doing something retarded again like trying to go to VW NPC in Jeuno I'm going to flip shit.  Just FYI make sure your ducks are in a row.

**Comment by nekrol** [comment]
that is not the case, ---Voidwatch Officers Delivery not me Voidstone

**Comment by nekrol** [comment]
Pashhow Marshlands (S)  Veridical Conflux  cutscene ,not work on Hiya ,recently we killed the last NM Celano, Voidwrought and Hahava

**Comment by nekrol** [comment]
Voidwatch Officers Delivery not  Voidstone ,

**Comment by nekrol** [comment]
Voidwatch Officers Delivery not  Voidstone ,in aurel and char cassy

**Comment by Loki79** [comment]
then you have an open quest preventing it.  Need to go back through and follow the quest progression and make sure you have fully completed the one your on, then go back to the VW officer.

**Comment by TeoTwawki** [comment]
@nekrol this has been a real pain to trace, but is now fixed.

**Comment by nekrol** [comment]
thank work fine now
