### ISSUE TITLE
Signet Staff Does not give signet (Bastok)

### ISSUE THREAD

**Issue by maikuru23** [LegionDark/Issues#28]
Date & Time: 5/28/2015 9PM PST
Frequency: always
FFXi Client Version: 30150508_8
Character Name: Maiku
Race: Taru
Main Job: PLD
Sub Job: NIN
Area & Coordinates: all areas
Party or Solo: both
NPC Name: N/A
Monster Name: N/A

Steps To Reproduce The Issue:
1. Get bastok Rank 10
2. Buy Republic Signet Staff from Gate Guard
3. Wait for Signet to wear off
4. Use Signet Staff
5. Do not obtain Signet
6. ???

https://www.bg-wiki.com/bg/Rep._Signet_Staff

**Comment by TeoTwawki** [comment]
Worked fine when I trued it just now.

**Comment by R3P0FFXI** [comment]
https://github.com/DarkstarProject/darkstar/issues/1491

Showing a Github issue on DSP for signet staffs

**Comment by TeoTwawki** [comment]
@R3P0FFXI If you read the issue there (which I opened) nothing in it is related to what was reported here. And per my post here, I could not find the issue that was reporter: the staff gave me signet. I simply found other issues when checking it.
