### ISSUE TITLE
Lost Attestation of Vigor

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#280]
Date & Time: 02/09/2015, 08:00am
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: Aurel
Race: Hume
Main Job: Sam and Drk
Sub Job: Sam/Drk
Area & Coordinates: none
Party or Solo: Party or solo 
NPC Name: moogle 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue: I do not understand why you lose 
![aurel_2015 09 02_141211](https://cloud.githubusercontent.com/assets/13084662/9639021/378fc61e-5180-11e5-8a9d-d0a28bbe0c2c.png)

**Comment by Kaoriasada** [comment]
Your fucking inventory was full.

[img]http://i62.tinypic.com/35d0nsl.png[/img]

**Comment by nekrol** [comment]
I do not and I entered as dual player, do not break the rules

**Comment by nekrol** [comment]
I'll do it again tomorrow
