### ISSUE TITLE
cop 4.4

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#281]
Date & Time: 02/09/2015
Frequency:
FFXI Client Version: 30150730_2
Character Name: zaya
Race: hume
Main Job:rdm
Sub Job:whm
Area & Coordinates:sealion den
Party or Solo:
NPC Name: iron gate
the cs iron gate do not work
https://www.bg-wiki.com/bg/Promathia_Mission_4-4

http://img15.hostingpics.net/pics/286320Zaya20150902222334.png

**Comment by Kaoriasada** [comment]
it me

**Comment by TeoTwawki** [comment]
Elaborate on "not work". Does the gate not respond at all, does the cs start but hang,,,,I need something to go on to even check it.

**Comment by bathuka** [comment]
cs does not start :)

**Comment by Kaoriasada** [comment]
Try repeating the steps prior to that CS.

**Comment by bathuka** [comment]
i have repeat 4 time despachaire cs 
and miudo have tell me log off all acoount and test again and this time that work :) 
( resolved ) now i know all account log on bug CS :)

**Comment by TeoTwawki** [comment]
This is why I added the multi boxing question to the template.

**Comment by bathuka** [comment]
ah ok sry for the temp I is makes you lose i slap zaya on the buttocks for you :)
