### ISSUE TITLE
Aht Urgan mission 2 missing KI

### ISSUE THREAD

**Issue by thirroxin** [LegionDark/Issues#282]
**Date & Time**: 9/3/2015 around 10AM 
**Frequency**: 2 (happened with original character on account as well)
**FFXI Client Version**:30150730_2
**Character Name**: Zontu
**Race**: Hume M
**Nation**: Sandoria
**Main Job**: Dancer
**Sub Job**: not unlocked
**Area & Coordinates**: custcene started autmatically
**Party or Solo**: solo
**NPC or Monster Name**: Naja saleem
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: nope
**Steps To Reproduce The Issue**: The mission started via a cutscene upon entering aht urgan, and i was told to deliver a KI to an immortal at a staging point of my choosing. Went to the Azouph ISle point and attempted to speak to the BLU (immortal), npc faced my way as if to speek with no text nor triggered events. I returned to Naja after noticing the temporary KI is not in my inventory and the same thing happened. Faced me, as if to speek, with no results. Now i cannot unlock my mog locker in which much of my gear upon retail server transfer lies. Any help would be great ^^

**Comment by Kaoriasada** [comment]
Gave him the KI.
