### ISSUE TITLE
Unable to receive Supplies Package 

### ISSUE THREAD

**Issue by Topace1** [LegionDark/Issues#283]
**Date & Time**: 09/02/15 at 10:30 am
**Frequency**: High
**FFXI Client Version**:
**Character Name**:Topace
**Race**:Tarutaru
**Nation**: Windurst
**Main Job**:Black Mage
**Sub Job**:Red Mage
**Area & Coordinates**: Aht Urgan Whitegate I-10
**Party or Solo**:Solo
**NPC or Monster Name**: Naja Salaheem
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Keep talking to her she won't give it to me.

**Comment by Kaoriasada** [comment]
I already fixed this Teo

**Comment by Kaoriasada** [comment]
like as soon as he reported it lol i just forgot to close it

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
