### ISSUE TITLE
Heka's kalasiris not working right

### ISSUE THREAD

**Issue by puffer1221** [LegionDark/Issues#284]
**Date & Time**: 14:40 pm gmt, 4/9/2015
**Frequency**: constant
**FFXI Client Version**: 30150730_1
**Character Name**: Anofrei
**Race**: Taru
**Nation**: Bastock
**Main Job**: Whm
**Sub Job**: Rdm
**Area & Coordinates**: Irrelevant
**Party or Solo**: solo or party
**NPC or Monster Name**: irrelevant
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/11867/hekas-kalasiris , http://www.ffxiah.com/item/10865/nefer-khat
**Multi-boxing? (multiple clients on same connection)**: irrelevant
**Steps To Reproduce The Issue**: Equip the heka and nefer khat and the set bonus of refresh doesnt activate, same result from equipping the nefer khat +1.

**Comment by R3P0FFXI** [comment]
Set bonuses are being worked on in DSP this will be added whenever DSP gets around to adding it

**Comment by TeoTwawki** [comment]
This looks like a duplicate of #273

**Comment by TeoTwawki** [comment]
And #244

**Comment by TeoTwawki** [comment]
Leaving open till after maint so people stop posting it.

**Comment by TeoTwawki** [comment]
And if the maint doesn't fix it, then there is a bug to report to DSP.

**Comment by excenmille** [comment]
The Refresh set bonus has been working since the Sept maintenance that required us to update our client.

**Comment by R3P0FFXI** [comment]
What client update there was no Legion Client update???

**Comment by TeoTwawki** [comment]
its fixed since last maint in any case, closing
