### ISSUE TITLE
t4 jeuno voidwatch

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#285]
**Date & Time**: 5/09/2015
**Frequency**: 
**FFXI Client Version**: 30150730_2
**Character Name**: bathuka and zaya
**Race**: elvaan / hume
**Nation**: sandy
**Main Job**: pld/nin rdm/whm
**Sub Job**:
**Area & Coordinates**:
**Party or Solo**: pty
**NPC or Monster Name**: akvan kaggen pil
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: yes 
**Steps To Reproduce The Issue**
After few kill akvan kaggen and pil that possibl you up me manualy my kill t4 jeuno i stay afk few hours IG today 
or i need waiting fix during the next maint ?

http://img11.hostingpics.net/pics/790783Bathuka20150905145250.png
http://img11.hostingpics.net/pics/528835Zaya20150905145302.png

**Comment by TeoTwawki** [comment]
Soem work in prgress related to this, I need to get with @Loki79 before I can sort out the probs

**Comment by bathuka** [comment]
kk teo tks :)

**Comment by bathuka** [comment]
done i have t4 KI ( resolved ) tks for help
