### ISSUE TITLE
Ix'aern (Dark Knight)

### ISSUE THREAD

**Issue by Avalonshadow** [LegionDark/Issues#286]
**Date & Time**: Sept 6, 2015
**Frequency**: everytime
**FFXI Client Version**: 30150730_1
**Character Name**: Digweed
**Race**: Galka
**Nation**: Bastok
**Main Job**: THF
**Sub Job**: NIN
**Area & Coordinates**: The Garden of Ru'Hmet (F-12)
**Party or Solo**: Party
**NPC or Monster Name**: Ix'aern (Dark Knight)
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Yes, all other characters are in Grand Palace of Hu'Xzoi
**Steps To Reproduce The Issue**: I purposely placed all other characters in the Grand Palace of Hu'Xzoi so I won't miss the message.  After 3 hours killing all the aerns in F-10, F-8, J-8, and J-10, I haven't seen the message "PLAYER is enveloped in sheer animosity".

I just want to know if this NM is functional.

**Comment by TeoTwawki** [comment]
Right now, no. Should work after maint, leaving this open till we're sure.

**Comment by R3P0FFXI** [comment]
Can you please test this and let us know if it is still broken

**Comment by Avalonshadow** [comment]
oh for sure, Teo.  
But it will probably on weekend if you don't mind since that is the only time i play :) 


     On Thursday, September 10, 2015 1:15 PM, R3P0FFXI <notifications@github.com> wrote:
   

 Can you please test this and let us know if it is still broken—

**Comment by bathuka** [comment]
i test it and atm i do not obtain the aura for pop it i continue :8ball:

**Comment by Avalonshadow** [comment]
I tested late last night from 8:30pm - 11:30pm PST, didn't get it either.
cheers, 


     On Friday, September 11, 2015 7:28 AM, bathuka <notifications@github.com> wrote:
   

 i test it and atm i do not obtain the aura for pop it i continue  —

**Comment by bathuka** [comment]
after several hours and 200 AERN death I think it does not work :)
I even AERN kill all of the area without ever having animosity

**Comment by TeoTwawki** [comment]
k, I'll see if I can spot what step of the script sit broke down at and then fix in DSP if I can. Might be a long while.

**Comment by bathuka** [comment]
deed of moderation obtain by other means ? buy this object could be possible, we can not pop AV - ;

**Comment by R3P0FFXI** [comment]
No it will only be obtained via Ix Drk

**Comment by TeoTwawki** [comment]
Might set him force pop via trade as a temp measure. We'll see. I'll eventually wind up fixing DSP's mess there.

**Comment by bathuka** [comment]
kk tks i wait :)

**Comment by Avalonshadow** [comment]
Sounds good!  Thanks for the hard work Teo.

**Comment by TeoTwawki** [comment]
For now he can be spawned by trading 5 stacks of Aern Organs. The Aerns can be massed killed and Organs have decent drop rate (varies by which Aerns you farm).

**Comment by bathuka** [comment]
tks tks tks*
