### ISSUE TITLE
Dancer Curing Waltz V animation wrong

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#287]
Date & Time: Sept 7, 2015
Frequency: everytime
FFXI Client Version: 30150730_2
Character Name: Dimma
Race: Hume
Nation: San'doria
Main Job: DNC
Sub Job: NIN
Area & Coordinates: All Area
Party or Solo: Party and Solo
NPC or Monster Name:
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): Yes,but it don't when solo too
Steps To Reproduce The Issue: Curing Waltz in lergion Worth like flee of the thief and it need to be like curing waltz IV from dnc.

**Comment by TeoTwawki** [comment]
clarify: the animation is wrong or the ability targets wrong? Animates like self target but aside from this works properly?

**Comment by Dimmabr** [comment]
Animation is wrong, in legion it work like flee from thf...that is wrong need to bee like curing waltz iv.

**Comment by TeoTwawki** [comment]
Saying the same thing twice is not clarification.

**Comment by TeoTwawki** [comment]
@Kaoriasada dumping on you to figure out wtf he means.

**Comment by TeoTwawki** [comment]
@Kaoriasada Once I know, I'll maybe fix it.

**Comment by Dimmabr** [comment]
Animation is wrong dont ablity target.

**Comment by Kaoriasada** [comment]
@TeoTwawki It's essentially what he said.  Curing Waltz V has the flee animation instead of the curing waltz animation.  So does Divine Waltz II.

**Comment by TeoTwawki** [comment]
Except what he said was too effing ambiguous to be sure thats what he meant.

**Comment by Kaoriasada** [comment]
I just explained to you

**Comment by TeoTwawki** [comment]
You are being dense. read IRC chat.

**Comment by TeoTwawki** [comment]
go tell darkstar about it, I don't even care now

**Comment by TeoTwawki** [comment]
@LegionDark/owners I'm done dealing with this SH. Finishing code like I said I would, and then removing myself from any and all positions within all repositories and groups. I've told you this before and then stalled out. This time the decision is final. If some things I planned to do don't get finished so be it. I do not want to stay on with ANY server, or even offer to help any servers anymore.
