### ISSUE TITLE
Kulkukan crashing when farming it ..

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#289]
**Date & Time**: Sep.07.2015 
**Frequency**: Everytime
**FFXI Client Version**: 30150730_2
**Character Name**: Dimma
**Race**: Hume
**Nation**: San'doria
**Main Job**: BLU
**Sub Job**: RDM
**Area & Coordinates**: Abyssea Konschat
**Party or Solo**: Solo and Party
**NPC or Monster Name**: Kulkukan
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Yes, my mule but it crash in solo too
**Steps To Reproduce The Issue**: Always trying get my fangs to do AF3 feet blue mage but in 10 times i got 8 crashing...solo and party (mule)

**Comment by Kaoriasada** [comment]
@Dimmabr Is an ability crashing you?  Because I just fought Kulkukan and he used every ability he has with no induced crash nor packet crash.  We're on the same FFXI version as well.  It sounds like a dualbox issue.

**Comment by Dimmabr** [comment]
I dunno, when i am fighting it crashed..

**Comment by TeoTwawki** [comment]
purely guessing: blue mage spell related

**Comment by Loki79** [comment]
I just fought twice and no issues at all.  closing this out.
