### ISSUE TITLE
  Incorrect or Missing stats on equipment (placeholder issue for previously reported items)

### ISSUE THREAD

**Issue by TeoTwawki** [LegionDark/Issues#29]
### Needed investigation that may not have happened:
> Yukitsugu / Yukitsugu  +1 :: skill type in database...
> All darts :: delay ratings and skill types in database...

### Reported items that may or may not have had work done already:
> Pavor Gauntlets - Stats added - need mod created for the Absorb bonus
> Magma Gauntlets LVL93 (missing modifiers/stats) -FIXED
> Paguroidea ring LVL92 (missing modifiers/stats) -FIXED
> Affronter cuisses LVL92 (missing modifiers/stats) -FIXED
> berserker's torque (needs latent coded)
> dragonkin earring - FIXED
> Tlamiztli Collar - FIXED
> Shneddick Chapeau (could not equip) -- FIXED
> Chidori (swinging 1 handed under dual wield) -- FIXED
> Jinx Discus (not able to be thrown)
> Metasoma Katars (not using both fists with hand2hand)
> Eyra Baghnakhs +1 (not using both fists with hand2hand)
> clarus stone (no info given..likely missing stats)
> quartz tathlum - FIXED
> kaikias' cape (wind elemental MAB bonus does not work - needs mod created)
> grapevine cape (does not extend refresh - needs mod created)
> tontiah ax (wrong model and swings 1 handed during dual wield)
> Isador (dual wield issue when main handed)
> Oneiros pebble (missing stats) - FIXED

**Comment by Loki79** [comment]
ill look through  some of this today.

**Comment by Loki79** [comment]
pretty sure this is all done.
