### ISSUE TITLE
Dancer dagger skill low then thf, why?

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#290]
Date & Time: Sept 7, 2015
 Frequency: everytime
 FFXI Client Version: 30150730_2
 Character Name: Dimma
 Race: Hume
 Nation: San'doria
 Main Job: DNC
 Sub Job: NIN
 Area & Coordinates: All Area
 Party or Solo: Party and Solo
 NPC or Monster Name:
 ffxiah.com link (for inventory items only): 
 Multi-boxing? (multiple clients on same connection): 
 Steps To Reproduce The Issue: Dancer  Why dancer is dagger skill 404 and thf is 416? in retail server say dnc and thf get priority on dagger weapon but in legion server dnc got low skill on dagger lol.

**Comment by TeoTwawki** [comment]
DarkStar is still using old pre adoulin time period skill caps, hasn't been updated and likely will not be until someone makes a pull request for that.

Legion uses DarkStar's skillcaps so when DarkStar gets an update, so will Legion.

**Comment by Dimmabr** [comment]
thank you Teo ^^
