### ISSUE TITLE
Dancer job abilities Flourishes III don't work.

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#291]
Date & Time: Sept 7, 2015
 Frequency: everytime
 FFXI Client Version: 30150730_2
 Character Name: Dimma
 Race: Hume
 Nation: San'doria
 Main Job: DNC
 Sub Job: NIN
 Area & Coordinates: All Area
 Party or Solo: Party and Solo
 NPC or Monster Name:
 ffxiah.com link (for inventory items only): 
 Multi-boxing? (multiple clients on same connection): 
 Steps To Reproduce The Issue: Job Ability "Flourishes III" don't work "Climactic, Striking and Ternary Flourich" folowing Presto, pls guys fix it because Flourishes III work to dancer so how sneak attack work to thfs.

**Comment by TeoTwawki** [comment]
@dimma there are a lot of things that simply don't exist in darkstar yet. Please don't report them all here in a single day, for the most part implementing missing retail features has to happen in darkstar itself.

**Comment by TeoTwawki** [comment]
Btw if there is anything you'd like to report directly to them (missing job features for example) you can do that here, optionally: https://github.com/DarkstarProject/darkstar/issues

Liable to get closed later weather we try and add it or not. I don't mind asking here or pointing out something missing here, just don't bury me, ok?  :smiley:

**Comment by Dimma** [comment]
Maybe, you have to answer to Dimmabr, not to me? :)

**Comment by TeoTwawki** [comment]
@Dimma very sorry, his *character* name, was Dimma, and I confused the too.

**Comment by TeoTwawki** [comment]
I am not having a good day. Just erased teh **ing text I meant to resend directly to him.

**Comment by TeoTwawki** [comment]
@Dimmabr I hope you get email notifications on this. I accidentally did an `@` mention intended for you with the wrong username, then wrecked the original post I made before making sure you had read it..

**Comment by TeoTwawki** [comment]
@Dimma the really part about this issue tracker is the parent project uses a command structure I'm not able to change where commands start with the `@`symbol so the users manage to send mentions to random people frequently and I am always telling them to stop doing that, and now I did it myself, albeit in a different way.

**Comment by Dimmabr** [comment]
I'm getting e-mails...

**Comment by PikaFox** [comment]
I made a full list of the abilities that dont work for dancer already that can be forwarded to DSP if wanted. It includes fourish IIIs on it.

https://github.com/LegionDark/Issues/issues/272

This thread is technically a duplicate Teo, and mine might be if you have a set list for it still from the old bug report JA section.

**Comment by TeoTwawki** [comment]
@PikaFox Wound up with drama and wasted time yesterday so I was heavily distracted. 
My main concern here was conveying I don't want to see a flood of multiple issue reports for each unimplemented thing. Closing this so the guy I mistakenly tagged doesn't get more notifications, any further discussion can happen in issue 272.
