### ISSUE TITLE
cant got bayld VWNM IV is 0 bayld

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#292]
**Date & Time**: spet 8.2015
**Frequency**:everytime
**FFXI Client Version**:30150730_2
**Character Name**:qigang and Hiya
**Nation**:San'doria
**Main Job**:SAM
**Sub Job**:THF
**Area & Coordinates**:All Area
**Party or Solo**:Party and solo
**NPC or Monster Name**:Hahava and all VW   IV store NM
**Multi-boxing? (multiple clients on same connection)**:yes

**Comment by nekrol** [comment]
Date & Time: 02/09/2015, 08:00am
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: hiya
Race: Hume
Main Job: Sam and Drk
Sub Job: Sam/Drk
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name: moogle 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:  HERE report

**Comment by Loki79** [comment]
check your currencies.  If its not there you are doing something wrong.  This WORKS for everyone else and is not something that can just break for one person.

**Comment by qiganggang** [comment]
Our entire guild is the same, is not Bayld, what is the problem?

**Comment by Loki79** [comment]
Please post a Screen Shot of your currency showing Bayld at 0.  I just tested this and I get it.

**Comment by Roamin** [comment]
Hahava does not give the correct EXP amount.  I killed it 3 times 3 days ago, and it only gave about 400 exp points.  I did not check the amount of baylds that dropped.

**Comment by TeoTwawki** [comment]
```lua
    killer:addCurrency("bayld", 125);
    killer:addExp(10000);
```
is whats in the script. its not physically possible for anyone to be getting other amounts.

**Comment by TeoTwawki** [comment]
I wanna see before and after pics proving that somebody didn't get what they should have, or one of us will be closing this within the week. The only theoretical way I can think of for those amounts not be obtained would be if the mob's claim was lost a split second before it died.

p.s.
If anyone was wondering, the amounts in the script are **not** divided by party members, and the servers exp rate setting influences the exp to be even more than what Loki scripted it as.

**Comment by TeoTwawki** [comment]
**Also, there is no message about the scripted bonus amounts in your log.**

You have to actually check your menu's to see what you got after the fact.

**Comment by PikaFox** [comment]
Killed Hahava today, did not get bonus xp nor bayld.

http://imgur.com/a/9TsHW

**Comment by PikaFox** [comment]
Celano seems to have the issue as well

http://imgur.com/a/NxHHT

**Comment by PikaFox** [comment]
Voidwrought same issue.

http://imgur.com/a/2XzUT

**Comment by TeoTwawki** [comment]
Thank you @PikaFox

**Comment by TeoTwawki** [comment]
With @PikaFox's help I have now found and fixed 3 VWNM's scripts including Hahava's that all failed to execute. 

I have added some Voidstones and Bayd to both Qigang and Hiya for your trouble.
(Don't get used to that - we don't usualy do compensation)
