### ISSUE TITLE
Lebeche ring not work

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#293]
Date & Time: 07/09/2015, 08:00am
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: Myeva
Race: Hume
Main Job: Rdm
Sub Job: Whm
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name: 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue: Lebeche ring not add mp not work cure +3%

**Comment by Loki79** [comment]
Fixed.  Be in after Maint today.
