### ISSUE TITLE
 Inquisitor bead necklace you can not equip in job Rdm

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#294]
Date & Time: 07/09/2015, 08:00am
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: Myeva
Race: Hume
Main Job: Rdm
Sub Job: Whm
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name: 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:Inquisitor bead necklace you can not equip in job Rdm

**Comment by Loki79** [comment]
Fixed, be in after maint today.

**Comment by TeoTwawki** [comment]
@Loki79 well yer quick today ain'tcha?
