### ISSUE TITLE
Dancer Emperyan Artifict Armor Maculele Tights.

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#295]
Date & Time: 09/08/2015 (09:30am)
 Frequency: Everytime
 FFXI Client Version: 30150730_2
 Character Name: Dimma
 Race: Hume
 Main Job: DNC
 Sub Job: NIN
 Area & Coordinates: none
 Party or Solo: Party or solo
 NPC Name: 
 Monster Name: 
 Multi-boxing? (multiple clients on same connection): 
 Steps To Reproduce The Issue: Dancer Emperyan Artific Armor Maculele tights:

Isn't add status from: 
DEF:81 HP+23 STR+18 VIT+10 AGI+12 INT+19 MND+11 CHR+7 = OK
Evasion+37 Magic Evasion+51 = X
"Magic Def. Bonus"+2 = dunno
Dagger skill +18 = add skill +7 only
Haste+6% = nothing
"Critical Parry"+17 = nothing
Set: Augments "Samba" = Dunno

**Comment by Loki79** [comment]
Fixed the dagger skill the other stats were all in.

**Comment by Dimmabr** [comment]
Test it now and still isn't working.. :P

**Comment by R3P0FFXI** [comment]
Dimma wait until after maint lots of our fixes go in after maint is run
