### ISSUE TITLE
Dancer Emperyan Artifict Armor Maculele bangles.

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#296]
Date & Time: 09/08/2015 (09:43am)
 Frequency: Everytime
 FFXI Client Version: 30150730_2
 Character Name: Dimma
 Race: Hume
 Main Job: DNC
 Sub Job: NIN
 Area & Coordinates: none
 Party or Solo: Party or solo
 NPC Name: 
 Monster Name: 
 Multi-boxing? (multiple clients on same connection): 
 Steps To Reproduce The Issue: Dancer Emperyan Artific Armor Maculele bangles:

DEF:64 HP+12 STR+9 DEX+25 VIT+19 AGI+10 INT+9 MND+20 CHR+12 = Ok
Accuracy+16 Evasion+16 = dunno
Magic Evasion+29 "Magic Def. Bonus"+1 = dunno
Haste+4% = X
"Skillchain Bonus"+10 "Reverse Flourish"+10 = X
Set: Augments "Samba" = Dunno

**Comment by TeoTwawki** [comment]
please just make 1 issue for multiple equipment you are reporting, in the future.

**Comment by Loki79** [comment]
Everything that can work on these is working.
