### ISSUE TITLE
 atzintli-necklace unable to be equipped 

### ISSUE THREAD

**Issue by jhalim83** [LegionDark/Issues#297]
Earlier I accidentally posted this under issues on darkstar #2047
Just in case I posted it here again.

Date & Time: Sept 8, 2015
Frequency: everytime
FFXI Client Version: 30150730_2
Character Name: Hijikata
Race: Hume
Nation: San'doria
Main Job: BLU
Sub Job: RDM
Area & Coordinates: All Area
Party or Solo: Party and Solo
NPC or Monster Name:
ffxiah.com link (for inventory items only): http://www.ffxiah.com/item/28385/atzintli-necklace
Multi-boxing? (multiple clients on same connection): No

Cannot be equipped

**Comment by Loki79** [comment]
Fixed, will be in next maint.
