### ISSUE TITLE
Job Abilities and traits over level 75

### ISSUE THREAD

**Issue by R3P0FFXI** [LegionDark/Issues#298]
Do not open ANY tickets for job abilities and traits and skills (especially those over level 75) we are aware most are not fully working or have issues. We are currently compiling a list of what does not work and will be putting it on our wiki so that we do not get multiple reports. Failure to follow this notice will result in your ticket being promptly closed with no resolution or response. The only exception will be those that were known to be working previously, that suddenly get broken.

**Being on this list does not mean we will be implementing it, because these need to happen in DarkStar. This is just to both player and dev alike to easily see what isn't there yet without a mass of clutter filling up the issue reports.**

**Comment by TeoTwawki** [comment]
**NOTE:** Being on this list does not mean we will be implementing it, because these need to happen in DarkStar. This is just to both player and dev alike to easily see what does isn't there yet without a mass of clutter filling up the issue reports.

**Comment by benfolka** [comment]
hello i have a char named "Clay"
i need to pass sandoria mission 2-3
i am told it is GM pushed
please help.

**Comment by TeoTwawki** [comment]
Can you read?

**Comment by benfolka** [comment]
yes

**Comment by TeoTwawki** [comment]
Then read this issue. And then go make your own issue and fill in the template.

**Comment by TeoTwawki** [comment]
Modus Veritas
Perfect Counter

Ppl not even reading the ReadMe..

**Comment by TeoTwawki** [comment]
Assimilation on Blue Mage

**Comment by SledgeCalamy** [comment]
Emnity Douse (Blm)
Mana Wall (Blm)

**Comment by TeoTwawki** [comment]
Closing in favor of wiki page. This issue report intended to be a catch all went largely unnoticed by the player base.

http://wiki.legiondark.com/Category:Jobs
Every jobs page on LegionDarks wiki has a currently up to date list now.

DSP also has a wiki of its own with a "what works" page:
https://wiki.dspt.info/index.php/What_Works#
