### ISSUE TITLE
Not Working as Intended!!

### ISSUE THREAD

**Issue by nidhogg1** [LegionDark/Issues#3]
Date & Time: 5/24/2015 7:25pm PST
Frequency: none
FFXi Client Version:
Character Name: Coso
Race: Hume
Main Job: Nin99
Sub Job: War49
Area & Coordinates (Type @where to get this info.): Inside MogHouse x;0 y:0 z:-3 (60)
Party or Solo: Solo
NPC Name: none
Monster Name: none
Steps To Reproduce The Issue: 
https://www.bg-wiki.com/bg/Thur._Boots_%2B1
1. typed @stats no gear on
2. equiped Thurandaut boots +1
3. typed @stats again with the item on
4. everything worked but the following bonus of the item:
    a. HP
    b. Magic Eva
    c. Magic Def
    d. Evasion (it adds the eva from the agi not the +eva)

**Comment by R3P0FFXI** [comment]
Fixed will be in next maint
