### ISSUE TITLE
Ro issue

### ISSUE THREAD

**Issue by zeos101** [LegionDark/Issues#30]
**5-29-15 11:35 am**: 
**twice**:
**FFXI Client Version 30150508_8**:
**Klang**:
**Elven**:
**MNK**:
**Nin**:
**North Sandy Smith Guild**:
**Solo**:
**Pinok-Morok**:

**talk to that NPC**:

**Comment by TeoTwawki** [comment]
I just fixed in darkstar itself, will get that into legion asap.

**Comment by R3P0FFXI** [comment]
Thanks for the report Klang you found a pretty big issue in Darkstar

**Comment by zeos101** [comment]
Glad to help I will keep an eye out for any other issues

**Comment by R3P0FFXI** [comment]
Issue was resolved in DSP last maint by Teo
