### ISSUE TITLE
ToA 2 «Immortal sentries» Key item/supplies package

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#300]
Date & Time: 09/09/15 at 10:30 am
Frequency: High
FFXI Client Version:
Character Name:Thranduil
Race:Hume
Nation: Bastok
Main Job:RDM
Sub Job:DNC
Area & Coordinates: Aht Urgan Whitegate I-10
Party or Solo:Solo
NPC or Monster Name: Naja Salaheem
Multi-boxing? (multiple clients on same connection): No
Steps To Reproduce The Issue: Naja Salaheem doesn't give me the key item I need to deliver to immortal sentries at the staging point.

**Comment by R3P0FFXI** [comment]
Tried to catch you after we talked a second you had already logged needs KI 775

**Comment by R3P0FFXI** [comment]
Gave player KI 775

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
