### ISSUE TITLE
Chat failing inside Maquette Abdhaljs-Legion

### ISSUE THREAD

**Issue by goferffxi** [LegionDark/Issues#302]
**Date & Time**:  11/09/2015   13:28 GMT+0
**Frequency**: Always
**FFXI Client Version** : 30150730_1
**Character Name**: Gofer
**Race**: Taru
**Nation**: Bastok
**Main Job**: BLU
**Sub Job**: DNC
**Area & Coordinates**: `@legionlaunch` and other areas of legion
**Party or Solo**: party/solo
**NPC or Monster Name**:n/a
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: Enter legionhall and try to communicate with players outside of legionhall. The comms don't go cross server. Might be to reduce needless chatter, but figured id report it just in case.

**Comment by TeoTwawki** [comment]
Known issue in DarkStars multi map server thing, and they have basically said its never going to be fixed..Its a real pain the rear for the GMs.

**Comment by TeoTwawki** [comment]
If basic /tell and linkshell chatter are failing, thats new and we'll need to inform DSP. When I first read it I though the new command @Loki79 added was failing if you were in a specific place.

**Comment by goferffxi** [comment]
Its every form of communication inside. /tell /party /yell /shout /ls /linkshell you name it it fails. it shows in the log but no one can see it unless they are in the area with you.

**Comment by TeoTwawki** [comment]
hmm. Logging in to go check this out..

**Comment by TeoTwawki** [comment]
@LegionDark/gm confirmed, cross server chat messages seem to have broken completely...

**Comment by TeoTwawki** [comment]
@LegionDark/gm since message server is the same executable as the lobby server, but the packets are generated in the map server, this is going to be a pain to trace which update in DSP did it.

**Comment by TeoTwawki** [comment]
@goferffxi The map server that zone is on was empty aside from GM Batman, so I went ahead and restarted it..And that seems to have fixed it.
