### ISSUE TITLE
Carabosse fight causes POL to crash

### ISSUE THREAD

**Issue by goferffxi** [LegionDark/Issues#303]
Date & Time: 11/09/2015 16:31 GMT+0
Frequency: Always
FFXI Client Version : 30150730_1
Character Name: Gofer
Race: Taru
Nation: Bastok
Main Job: BLU
Sub Job: THF
Area & Coordinates:  Abyssea La Thiene Plateau   spawn @ X36 Y20 Z142  pulled and fought @ x81 y20 z142
Party or Solo: party
NPC or Monster Carabosse
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): yes 2 box
Steps To Reproduce The Issue: fight carabosse long enough and the clients crash. was advised by GM Roamin to try to remove both Linkshells, crash still took place.

**Comment by TeoTwawki** [comment]
Its more like: a blue mage is in the part and we're in an abyssea zone = random crashes, random crashes at random times, WHEEEEEEEEEE

**Comment by TeoTwawki** [comment]
Serious we've had like 30 people say that soem mob in some zone crashes them, and we test it and nothing is wrong. Only common factors are blue mages involved and its in abyssea, every time.

And just walking around in Abyssea causes a random crash, sometimes..

**Comment by TeoTwawki** [comment]
See #85 if you weren't aware of that 2nd one.
