### ISSUE TITLE
Crusher's Gauntles

### ISSUE THREAD

**Issue by ronnymp** [LegionDark/Issues#304]
*Date & Time**: 12/09 18:41
**Frequency**:
**FFXI Client Version**:
**Character Name**:Miudo
**Race**:Galka
**Nation**:Sandy
**Main Job**:WAR
**Sub Job**:SAM
**Area & Coordinates**:
**Party or Solo**:SOLO
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:Serjoca
**Steps To Reproduce The Issue**:

I get those gloves like two days ago in Zitah , cant equip them as war...war/pld/drk/bst/sam/drg can use it ^^

**Comment by Az1r** [comment]
Confirmed instead of WAR a MNK is able to equip them, which isn't right. 

FFXI AH: WAR PLD DRK BST SAM DRG

**Comment by ronnymp** [comment]
thank you ^^

**Comment by R3P0FFXI** [comment]
Whats the item ID your missing the id off ffxiah

**Comment by PikaFox** [comment]
http://www.ffxiah.com/item/27044/crusher-gauntlets

**Comment by Loki79** [comment]
Fixed.  Be in next maint.
