### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#305]
**Date & Time**:  9/12/2015 11:00
**Frequency**: Randomly
**FFXI Client Version**: 30150730_2
**Character Name**: Baucant
**Race**: Elv
**Nation**: Sandy
**Main Job**: Nin
**Sub Job**: Dnc
**Area & Coordinates**: Gustave Tunnel x:37 y:0 z:159 (0)
**Party or Solo**: Both
**NPC or Monster Name**: IDK
**ffxiah.com link (for inventory items only)**: N/A 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: log in stand still server crashes at random intervales

**Comment by R3P0FFXI** [comment]
Confirmed Pygmytoise is causing the server to crash when attempting to use TP moves no TP  move is listed in log.

**Comment by R3P0FFXI** [comment]
Issue has been resolved server has been up all night and into today with 0 crashes
