### ISSUE TITLE
VWNM Jeuno Tier IV Bhishani does not grant added xp/bayld on death

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#306]
**Date & Time**: 9/14/15
**Frequency**: 3 times
**FFXI Client Version**: 30150730_1
**Character Name**: Tarot
**Race**: Hume
**Nation**: San
**Main Job**: Mnk
**Sub Job**: War
**Area & Coordinates**: South Gustaburg
**Party or Solo**: Aliance
**NPC or Monster Name**: Bhishani
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**:

On death the VWNM did not grant the additional xp/bayld on kill. Of note, the first two times i locked up mid fight and had to log back in, the third i died and had to come back.

Before and after screenshots: http://imgur.com/a/B0qnJ

**Comment by TeoTwawki** [comment]
Name was typo'd in sql table.  Will be fixed in next maint.

**Comment by Loki79** [comment]
this has been temp fixed so you can re-do the kill and get credit now.

**Comment by TeoTwawki** [comment]
Closing since won't be a problem anymore.
