### ISSUE TITLE
Bard Songs(spells) not working 

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#307]
**Date & Time**: 9/15/2015
**Frequency**:Always
**FFXI Client Version**:30150730_2
**Character Name**:Jukebox
**Race**:Mithra
**Nation**:Sandy
**Main Job**:Brd
**Sub Job**:Whm
**Area & Coordinates**: North Sandy x:70 y:0 z:11 (138)
**Party or Solo**: Both
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)** n/a: 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**:tried in multipul zones after loging of and back on my Brd is lvl 99

The scroll of Light Carol II and Scroll of Pining Nocturne are not activating. I get the message "Can Not use the scroll of Light Carol II/Pining Noturne on Jukebox." When I try to use them.

**Comment by Loki79** [comment]
They aren't coded yet.
