### ISSUE TITLE
~Excalibur~ Can't complete the final trial

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#308]
Date & Time: 9/15/2015
Frequency:Always
FFXI Client Version:30150730_2
Character Name:Thranduil
Race:Hume
Nation:Bastok
Main Job:Rdm
Sub Job:Dnc
Area & Coordinates: Ru'Lude Gardens x:70 y:0 z:11 (138)
Party or Solo: solo
NPC or Monster Name: Ru'Lude Garden custom trials Moogle (X5 Y0 Z-76)
ffxiah.com link (for inventory items only) n/a:
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue: the counter for my Tanzanites seems to be stuck at 5/50; when I try to trade another T.jewel to the moogle, he  just talks about the trial cancelling procedure and its cost.
![thranduil_2015 09 15_092816](https://cloud.githubusercontent.com/assets/12772770/9870556/4925d7b2-5b8d-11e5-882b-2fd284bed223.png)

**Comment by TeoTwawki** [comment]
I dunno how you got to 5 - its currently set up to require all 50 in a single trade!

**Comment by simthra** [comment]
I guess I'll restart the trial then. Thank you.
