### ISSUE TITLE
~Caruvinda / LJ armor storage NPC~ 

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#309]
Date & Time: 9/15/2015
Frequency:Always
FFXI Client Version:30150730_2
Character Name:Thranduil
Race:Hume
Nation:Bastok
Main Job:Rdm
Sub Job:Dnc
Area & Coordinates: Lower Jeuno (x:23 y:-1 z:79)
Party or Solo: solo
NPC or Monster Name: Caruvinda
ffxiah.com link (for inventory items only) n/a:
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue: He won't take back the BLU AF Magus set; I've tried to change to blu, zone, logout-in, trade the pieces in ascending-descending-random order but still no deal. I've had no problems in retrieving and storing other AF armors.

**Comment by R3P0FFXI** [comment]
no just toss it and get a new claim slip that npc is handled by dsp
