### ISSUE TITLE
Dynamis - San d'Oria Issue

### ISSUE THREAD

**Issue by Skett** [LegionDark/Issues#31]
**Date & Time**: 29/05/15
**Frequency**: Unknown
**FFXI Client Version**: 30150508_5
**Character Name**: Skett/Chrystina/Pray
**Race**: Elvaan/Hume/Taru
**Main Job**: THF/BLM/WHM
**Sub Job**: NIN/RDM/RDM
**Area & Coordinates**: Dynamis San d'Oria
**Party or Solo**: Party
**NPC Name**: N/A
**Monster Name**: N/A
**Steps To Reproduce The Issue**:
1. Enter Dynamis and kill all mobs, only 1 NM spawned.
2.. No other NMs spawned so no boss pop either, waited 30 mins no respawns.
3. Not able to complete Dynamis San d'Oria

**Comment by R3P0FFXI** [comment]
Common DSP issue Neo Dynamis is not coded we will look for a work around

**Comment by Skett** [comment]
Any update on this? Will be need to try again to get the win? looking to progress on to beaucedine etc

**Comment by R3P0FFXI** [comment]
We are currently in the middle of a massive update this will not be addressed until after, in the meantime continue to try and complete as normal as sometimes NM pops others it does not.

**Comment by Skett** [comment]
Sorted it today. Do NOT 1shot the mm statues as they won't spawn their NMs and you won't be able to finish.

Sent from my HTC

----- Reply message -----

**Comment by R3P0FFXI** [comment]
Per user issue resolved do not 1 shot statues
