### ISSUE TITLE
T5 upgrade jeuno

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#310]
Date & Time: 15/09/2015
Frequency:
FFXI Client Version: 30150730_2
Character Name: bathuka and zaya
Race: elvaan / hume
Nation: sandy
Main Job: pld/nin rdm/whm
Sub Job:
Area & Coordinates:
Party or Solo: pty
NPC or Monster Name: lancing lamarok  Bhishani  RW 
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue

http://ffxiclopedia.wikia.com/wiki/White_Stratum_Abyssite_IV

the atmacite rafiner do not upgrade abyssite :)

**Comment by TeoTwawki** [comment]
Just an FYI: This server never used the refiners at all. Always gets handled in either a cs or an NM kill. I'd have to look at scrips to see where/if this one happens at.

**Comment by PikaFox** [comment]
Bath; we need to kill the pixie again. It wasnt giving kill credit before, it should now.

**Comment by bathuka** [comment]
kk :)
