### ISSUE TITLE
Elevators in "The Garden of Ru'Hmet" only working 1 time before zoning

### ISSUE THREAD

**Issue by Roamin** [LegionDark/Issues#311]
**Date & Time**: September 15, 2015
**Frequency**: All the time
**FFXI Client Version**: 30150730_2
**Character Name**: Xiaoxiao / Maomao
**Race**: Mithra / Tarutaru
**Nation**: San d'Oria
**Main Job**: Whm  (xiao) Sam (mao)
**Sub Job**: Rdm (xiao) nin (mao)
**Area & Coordinates**: All elevators,   example : D-9  The Garden of Ru'Hmet
**Party or Solo**: Party
**NPC or Monster Name**:  None , "Use device?" should appear when walking on elevator
**ffxiah.com link (for inventory items only)**:  None
**Multi-boxing? (multiple clients on same connection)**:  Yes , same pc (i assume)
**Steps To Reproduce The Issue**: 

I wrote this ticket for XiaoXiao because his english is not good enough.
It seems that all the elevators in "The Garden of Ru'Hmet" will only let you trigger them once.  Using the @bring command  to bring Maomao and xiaoxiao back to me in front the elevators , will allow them to use them again,  until he has crossed one.  Once one elevator has been crossed, the others will not ask you to "Use the device?".   
Either logging off, and relog , or using the @bring GM command will fix this issue until the next teleport.

So , zoning fixes the teleport statuses.

**Comment by R3P0FFXI** [comment]
duplicate ticket DSP issue opened and DSP is working on it
