### ISSUE TITLE
Aegis do not work 

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#312]
Date & Time: 16/09/2015
Frequency:
FFXI Client Version: 30150730_2
Character Name: bathuka 
Race: elvaan
Nation: sandy
Main Job: pld
Sub Job:
Area & Coordinates:
Party or Solo: pty
NPC or Monster Name: 
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue

i take the same dmg when i use or not aegis 99-4
( quake 2 )
not equiped 1125
http://img11.hostingpics.net/pics/824697Bathuka20150916023118.png
with 1125
http://img11.hostingpics.net/pics/327551Bathuka20150916023148.png

same for stone 5 and stonega IV

http://ffxiclopedia.wikia.com/wiki/Aegis_%2899%29
Magic Damage Taken -50%:
Independent of the natural 50% cap for magic damage.

**Comment by R3P0FFXI** [comment]
Bathuka the mod is on the item so it does appear to be working as intended

INSERT INTO `item_mods` VALUES (16200,163,-128);

**Comment by TeoTwawki** [comment]
Except if one of his 2 screenshots had it equipped and the other not, it -can't- be working right.

I wanna see a comparison between Aegis 75 and aegis 99-4. Might help me see whats going on/not going on.

**Comment by bathuka** [comment]
i have screen with stone 5
with
http://img11.hostingpics.net/pics/727813Bathuka20150916022140.png
not equiped
http://img11.hostingpics.net/pics/726059Bathuka20150916022929.png

**Comment by bathuka** [comment]
i do not have aegis 75 :)

**Comment by TeoTwawki** [comment]
@bathuka what other magic damage taken gear you have on at the time? And I know you can't do the compare for me, that comment was for staff. :) It would be crazy to expect you to do that.

**Comment by bathuka** [comment]
set MDT-
http://img11.hostingpics.net/pics/873361Bathuka20150916030657.png
http://img11.hostingpics.net/pics/237794Bathuka20150916030703.png
http://img11.hostingpics.net/pics/463979Bathuka20150916030707.png
http://img11.hostingpics.net/pics/964427Bathuka20150916030708.png
http://img11.hostingpics.net/pics/859584Bathuka20150916030710.png
http://img11.hostingpics.net/pics/373744Bathuka20150916030712.png
http://img11.hostingpics.net/pics/558856Bathuka20150916030717.png
http://img11.hostingpics.net/pics/972822Bathuka20150916030718.png
http://img11.hostingpics.net/pics/862595Bathuka20150916030720.png
http://img11.hostingpics.net/pics/881130Bathuka20150916030724.png
http://img11.hostingpics.net/pics/576311Bathuka20150916030728.png
http://img11.hostingpics.net/pics/132412Bathuka20150916030750.png

**Comment by TeoTwawki** [comment]
Ok, that shoots down 1 theory I had. 
For future reference, "magic defense" and "magic damage taken" are two different things. :)

**Comment by bathuka** [comment]
yeah i know teo magic defense is different magic damage taken :)
my problem is only the aegis -50% :) that impossibl i take the same dmg when i use it

**Comment by R3P0FFXI** [comment]
Aegis is actually 50% Bathuka at 99-4. What were looking at is the hidden trait that allows Aegis to bypass the 50% MDT as that the entire purpose of Aegis.

**Comment by bathuka** [comment]
ahhhhhh ok ok super

**Comment by SquallerSnake** [comment]
Hello, I also have problems with aegis 99-1. (with Aegis 95 no problems)

When  I have Aegis equipped, it seems to take +50% dmg physical and magical.

As u can see in image adamantoise hit me for 30-40 with normal shield equipped, with aegis i take +100 dmg.

![aegis](https://cloud.githubusercontent.com/assets/13245127/9975721/f84cc69c-5ec6-11e5-99fd-d9b5ccb02466.jpg)
![normal](https://cloud.githubusercontent.com/assets/13245127/9975722/f84f0f56-5ec6-11e5-94c9-c957c1728770.jpg)

**Comment by SquallerSnake** [comment]
Any news on Aegis bug fix?
I worked so hard to take it to lvl 99 and now i can't use it...

**Comment by TeoTwawki** [comment]
I'll post when there is news. Limited amount of time to work on these things.

**Comment by TeoTwawki** [comment]
Finally had to time to get what I needed done myself. the fix I just did will take effect next server restart.

**Comment by TeoTwawki** [comment]
Just so everyone is aware, the part where it is supposed to go beyond the normal 50% cap is a DSP problem, and I won't be coding that. When they make theirs do it, all tiers of Aegis can be updated.

**Comment by SquallerSnake** [comment]
Thank you!
