### ISSUE TITLE
Aoidos' Calot +1

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#313]
**Date & Time**:9/16/2015 12:26 am 
**Frequency**: Never
**FFXI Client Version**:30150730_2
**Character Name**:Jukebox
**Race**:Mithra
**Nation**:Sandy
**Main Job**:Brd
**Sub Job**:Whm
**Area & Coordinates**: Port Jeuno x:-48 y:0 z:-9 (52)
**Party or Solo**: Both
**NPC or Monster Name**: Moogle
**ffxiah.com link (for inventory items only)**: http://ffxiclopedia.wikia.com/wiki/Aoidos%27_Calot_%2B1 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: Loged off and on, zoned in and out

I get no results when trading Aoid. Seal:Hd x8 and Aoidos' Calot

**Comment by Loki79** [comment]
I looked at the trade for this and its 100% correct so my assumption is its an inventory issue.  If you do not have a free slot, or even if the game thinks you do not have a free slot it wont execute anything.  Please sort your inventory and then talk to the NPC again and let me know.

**Comment by TeoTwawki** [comment]
@Loki79 we don't have a messageSpecial() call telling them they can't obtain itemWhatever?

**Comment by Baucant** [comment]
I thought I had space available but I'll try it again and report back

**Comment by Baucant** [comment]
Tried again today work

**Comment by R3P0FFXI** [comment]
Closing ticket issue resolved
