### ISSUE TITLE
Mnk cannot equip Focal Orb

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#314]
**Date & Time**: 9/16/15
**Frequency**: NA
**FFXI Client Version**:30150730_1
**Character Name**: Tarot
**Race**: Hume
**Nation**:  San
**Main Job**: Mnk
**Sub Job**: War
**Area & Coordinates**: NA
**Party or Solo**: NA
**NPC or Monster Name**: NA
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/21345/focal-orb
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: Try to equip, will not let me. Mnk is a job that can use it. Unknown if other jobs have this issue.

**Comment by PikaFox** [comment]
Would not equip on war either, so more than one job has the issue.

**Comment by Loki79** [comment]
Fixed, will be in next maint.
