### ISSUE TITLE
Able to see and lot loot in an entirely different area

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#315]
**Date & Time**: 9/17/15
**Frequency**: Once 
**FFXI Client Version**: 30150730_1
**Character Name**: Tarot
**Race**: Hume
**Nation**: San
**Main Job**: Mnk
**Sub Job**: War
**Area & Coordinates**: Ordelles Caves (them)/Port Jeuno (me)
**Party or Solo**: Party
**NPC or Monster Name**: According to screenshot, .
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: Was in alliance, aliance dissolved. I was in Port Jeuno for a loooong while afk. I looked over, and i was able to see the treasure pool of the person who was solo farming a couple tanzanites. This has happened before, and ive been able to afk get book credit from gustav tunnel long ago purely by accident while i was in north sandoria. 

http://imgur.com/rgHyA7m

As you can see, i was in Port Jeuno the entire time. And yes, the slime oil did go into my inventory.

Probably a DSP issue.

**Comment by TeoTwawki** [comment]
> Probably a DSP issue.

Ya, and all that info plus screencap needs shown to them.

**Comment by R3P0FFXI** [comment]
Reported to DSP
