### ISSUE TITLE
Ocythoe NM t6 jeuno "planar rift" not work

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#316]
Date & Time: 17/09/2015
Frequency:
FFXI Client Version: 30150730_2
Character Name: bathuka
Race: elvaan
Nation: sandy
Main Job: pld
Sub Job: nin
Area & Coordinates: Grauberg (S) 
Party or Solo: pty
NPC or Monster Name: Ocythoe
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue

the 3 planar rift in "gauberg s" do not work nothing "message" 
Spawned by examining a Planar Rift at (D-14), (G-7), or (G-11) in Grauberg (S) 
http://ffxiclopedia.wikia.com/wiki/Ocythoe

**Comment by Roamin** [comment]
Bathuka, answer me in game. I just popped that nm with no issues..

**Comment by PikaFox** [comment]
Loki fixed this last night

**Comment by bathuka** [comment]
ah ok cool :) tks :)
