### ISSUE TITLE
Ix Aern Drk pop not taking pop

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#318]
**Date & Time**: 9/18/15
**Frequency**: Always
**FFXI Client Version**: 30150730_1
**Character Name**: Tarot
**Race**: Hume
**Nation**:San
**Main Job**:NA
**Sub Job**: NA
**Area & Coordinates**: Garden of Ru'hmet
**Party or Solo**: Part
**NPC or Monster Name**: ??? - ID 16921028
**ffxiah.com link (for inventory items only)**:  NA
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**:

Reported issue that it wasnt taking pop items on pop, issue was fixed and was changed to 4 stacks to pop. Will not pop with 1-5 stacks traded to ??? now.

**Comment by TeoTwawki** [comment]
Fixed
