### ISSUE TITLE
Dynamis -  Jeuno won't allow entry

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#32]
**Date & Time**: 5/29/2015 5:00pm
**Frequency**: everytime i click the Trial Markings
**FFXI Client Version**:30150508_8
**Character Name**: Baucant and Dapunted
**Race**: Elvaan and taru
**Main Job**: Thf and whm
**Sub Job**: Dnc and Rdm
**Area & Coordinates**: Ru'lude Gardens x:37 y:9 Z:-49 (243)
**Party or Solo**: both
**NPC Name**: Trail Markings
**Monster Name**: N/A
**Steps To Reproduce The Issue**: 
When I click on the trial marking it responce in chat. "Even Captain Woldgang has been looking disturbed since he received that envelop. What ever could be going on?" This happened yesterday and someone in Ls said I had to beat all the nation dynamises first.I needed windy win so did that yesterday. I now have the 3 KIs from all 3 Nation dynamis and still I am not granted access.

**Comment by Baucant** [comment]
IDK if anyone worked on this. didn't get a tell or anything. I was able to enter Dynamis Jeuno.

**Comment by R3P0FFXI** [comment]
Your timer was most likley not up but thanks for the update

**Comment by Baucant** [comment]
your probably right about the time but that is a very unussual message

**Comment by TeoTwawki** [comment]
Stuff doesn't always happen same day (or even same week)

**Comment by TeoTwawki** [comment]
It sounds like a textID is off so the current client/server don't match up with the message you should have received about not being able to enter at the time.
