### ISSUE TITLE
Voidwatch officers won't give stratum abyssite/voidstone

### ISSUE THREAD

**Issue by excenmille** [LegionDark/Issues#320]
Date & Time: 9/19/15
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: Orangeorange
Race: Hume
Nation: Bas
Main Job: WHM
Sub Job: RDM
Area & Coordinates: bastok market
Party or Solo: Solo
Multi-boxing? (multiple clients on same connection): Solo
Steps To Reproduce The Issue:

I joined bastok(s), finished its first quest, my quest completed log displays 'The Fighting Fourth' and I've received sprinter boots. But when I visit both present Bastok and Sandoria their voidwatch officers just output this: 
48 5
48 6

Voidstones under Currency tab is 0, and I have nothing on Voidwatch KI tab. When I completed The Fighting Fourth quest I was dualboxing with a character who's already completed it a few days ago, but today I tried talking to VW Officer solo and still cant get KI.

**Comment by Loki79** [comment]
Are you visiting the VW officers in past or present?  Only the ones in the present are scripted.  The ones in the present will print text if they fail please post what they print.

**Comment by excenmille** [comment]
![vw](https://cloud.githubusercontent.com/assets/13755300/9976228/4cde471e-5f10-11e5-816f-47bc706fbd24.png)

I talked to the VW officer in present bastok market. He just keeps repeating this:

DEBUG: Initial Abysite check started.
Voidwatch Officer: 48 5
Voidwatch Officer: 48 6

**Comment by TeoTwawki** [comment]
And this is why I left those debug prints in! No applause necessary, I know I am awesome, thanks.

**Comment by TeoTwawki** [comment]
Your character is missing 1 or more of the requirement for obtaining the first Stratum Abyssite from the Bastok NPC. You said you were dual boxing

> The Fighting Fourth quest I was dualboxing with a character who's already completed it a few days ago, but today I tried talking to VW Officer solo and still cant get KI.

So there is a chance that messed up your completion of that quest, or its possible you simply didn't meet one of the other requirements: On lv75+ jobclass, adventurer certificate. Those are required also.

**Comment by excenmille** [comment]
Ahh, it's the adventurer cert that I'm missing. This character's a whm mule and still rank 1. Thanks for the help.

**Comment by TeoTwawki** [comment]
Ok cool, glad its not broken quest! We'll get the messages fixed soon so he'll actually tell people that again, they keep breaking during client updates and very few people actually tell us about it or even notice (the average player hammers the enter key till the NPC stops talking).
