### ISSUE TITLE
Tsurumaru's "Save TP" working?

### ISSUE THREAD

**Issue by excenmille** [LegionDark/Issues#321]
Date & Time: 9/19/15
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: Orangeorange
Race: Mit
Nation: Bas
Main Job: sam
Sub Job: war
Party or Solo: Solo
Multi-boxing? (multiple clients on same connection): Solo
Steps To Reproduce The Issue:

Does tsurumaru's Save TP+250 work? When I use any WS and regardless of gear I always get back less than 250 TP.

**Comment by Loki79** [comment]
No, that mod does not currently exist in DSP servers, so we have substituted STP for to compensate.

**Comment by TeoTwawki** [comment]
Changing label: thats not an augment.
