### ISSUE TITLE
Help´please no drop Spool Of Ruby Silk Thread

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#322]
Date & Time: 19/09/2015, 1100 am
![myeva_2015 09 19_112113](https://cloud.githubusercontent.com/assets/13084662/9976862/dc807638-5ec7-11e5-96f2-5b1dd7a8048e.png)

Frequency: Always
FFXI Client Version: 30150730_2
Character Name: Myeva
Race: Hume
Main Job: Rdm
Sub Job: Whm
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name: 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue:item no drop ,please help......everything falls, and the wait is 24 hours for other hunts of mobs

**Comment by TeoTwawki** [comment]
> everything fails

Works fine for me. If by "fails" you mean that all items are saying you can't hold them then are probably experiencing the sort bug. The item definitely drops and I was able to obtain several without issue.

**Comment by nekrol** [comment]
ok keep trying tomorrow

**Comment by TeoTwawki** [comment]
Its all luck as to which item is the bonus drop btw. Is why I set it to such a high rate. You probably have every job except rdm done if you are having bad luck..This happened to me on retail. Except was cloth. I could never get that cardinal cloth x_X

**Comment by nekrol** [comment]
an NPC who sells the item is needed

**Comment by TeoTwawki** [comment]
Will never sell for gil. Ancient Beastcoin possibly.

**Comment by nekrol** [comment]
good idea

**Comment by TeoTwawki** [comment]
Discussing with devs, another possibility is trade several of wrong job to get current job item.

**Comment by nekrol** [comment]
cardinal cloth only fallen one

**Comment by TeoTwawki** [comment]
http://legiondark.com/forums/viewtopic.php?f=10&t=1022
