### ISSUE TITLE
Other players and I are chocobos

### ISSUE THREAD

**Issue by Zejx** [LegionDark/Issues#323]
**Date & Time**: 9/19/2015 12:50PM CST
**Frequency**: Always
**FFXI Client Version**: 30150910_3
**Character Name**: Zejx
**Race**: Hume M
**Nation**: Bastok
**Main Job**: Warrior
**Sub Job**: none
**Area & Coordinates**: Anywhere
**Party or Solo**: Both
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**:

Whenever I have Signet cast on me I turn into a chocobo until I zone. Also so far all the other players are chocobos. Also whenever I or someone is a chocobo, I can't see their names at all. The signet on myself happens no matter where I get it from. So far I have only seen other players in Valkrum Dunes. Not sure it if happens anywhere else yet.

**Comment by TeoTwawki** [comment]
This is because you are on a later game version than the server is.

**Comment by TeoTwawki** [comment]
Game will be normal for you after teh server is caught up, I can't say when that will be, no ETA.


@LegionDark/owners leaving open so duplicate issues don't get created by people that either just installed or updated when they should not have.

**Comment by Zejx** [comment]
Okay. Thank you.

**Comment by R3P0FFXI** [comment]
Issue now resolved as server has been updated
