### ISSUE TITLE
T2cant up KI to T3

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#324]
Date & Time:20/09/2015, 08:00am
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: hiya
Race: Hume
Main Job: BLU
Sub Job: RDM
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name:Voidwatch Officer
Monster Name:
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue: 
![qq 20150920072955](https://cloud.githubusercontent.com/assets/13742980/9978578/97574cdc-5f6a-11e5-9f2c-f3251092d79f.jpg)

I T2 6 NM have all hit, but to find Officer Voidwatch no response, please repair the BUG, thank you

**Comment by qiganggang** [comment]
and cant equip this head 
![qq 20150920074548](https://cloud.githubusercontent.com/assets/13742980/9978596/b2b3e0fc-5f6b-11e5-8a23-3610ec758c9c.jpg)

**Comment by TeoTwawki** [comment]
separate issues = separate reports.

**Comment by qiganggang** [comment]
OK

**Comment by TeoTwawki** [comment]
According to the variable, you are missing 1 NM kill: Laidly Laurence

**Comment by PikaFox** [comment]
Screenshot your bayld before and after the fight. If you dont get bayld for Laidly Laurence, post screenshots here. If you have killed the VWNM before, might be the same issue as a few other VWNMs.

**Comment by qiganggang** [comment]
ok let me check

**Comment by TeoTwawki** [comment]
Keep in mind multi-boxing will randomly cause things like variables to not get set, causes you to have to repeat things sometimes.

**Comment by qiganggang** [comment]
![qq 20150920112044](https://cloud.githubusercontent.com/assets/13742980/9979177/92c8c800-5f90-11e5-920b-c6cbd75567fa.jpg)
![qq 20150920112105](https://cloud.githubusercontent.com/assets/13742980/9979178/93038e68-5f90-11e5-8407-c8154fbbec0b.jpg)
![qq 20150920120856](https://cloud.githubusercontent.com/assets/13742980/9979179/931822ce-5f90-11e5-9959-2c45a5a0cd4c.jpg)
![qq 20150920120924](https://cloud.githubusercontent.com/assets/13742980/9979180/9333e3e2-5f90-11e5-8f6d-76b1eeec7250.jpg)

**Comment by qiganggang** [comment]
not have CS

**Comment by qiganggang** [comment]
ok KI UP to III thanks

**Comment by Loki79** [comment]
Fixed.
