### ISSUE TITLE
cant Equip 119 head

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#325]
Date & Time:20/09/2015, 08:00am
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: hiya
Race: Hume
Main Job: BLU
Sub Job: RDM
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name:
Monster Name:
Multi-boxing? (multiple clients on same connection): yes

my LS friend all cant equip this head 

![qq 20150920075235](https://cloud.githubusercontent.com/assets/13742980/9978614/8b403e48-5f6c-11e5-9124-1ae80e1e8ca6.jpg)

**Comment by R3P0FFXI** [comment]
Yes Blu cannot equip that it is correct 

Main Job: BLU

**Comment by Loki79** [comment]
just wow....

**Comment by TeoTwawki** [comment]
wait wait wait...The guy isn't English native, and I don't think he intended to say he was trying to equip it on blue, or I wouldn't have left it open in the first place guys.

**Comment by TeoTwawki** [comment]
He always just puts whatever his current job is, so I gave him benefit of the doubt.
