### ISSUE TITLE
Jailer of Faith's ??? spawns outside of player reachable area

### ISSUE THREAD

**Issue by Roamin** [LegionDark/Issues#327]
**Date & Time**: September 20th 2015
**Frequency**: Depends on the respawn
**FFXI Client Version**: 30150730_1
**Character Name**: Roamin 
**Race**: Taru
**Nation**: Windy
**Main Job**: War
**Sub Job**: Sam 
**Area & Coordinates**: The Garden of Ru'Hmet  possibly at : -412 0 -698
**Party or Solo**: Both
**NPC or Monster Name**:  ??? NPC ID : 16921029
**ffxiah.com link (for inventory items only)**: not applicable
**Multi-boxing? (multiple clients on same connection)**: Yes, same pc
**Steps To Reproduce The Issue**:

Since last update a few things broke in sea.  The ??? that should spawn in one of the 5 towers on floor 2 of Garden of Ru'het willl sometimes span on floor 1 in between the 2 southern most towers, completely out of map , and unreachable to any players.

I used @npchere 16921029 and placed it in the room where it teleports you after you spawn it, and we popped him properly. The next 2 spawns were at correct location.  1 day passed, the server crashed last night and now today the ??? returned to that same location off screen location.  Possibly it hangs there when it is suppose to jump from one room to the other every 15-30 minutes.

**Comment by TeoTwawki** [comment]
wtf. I disabled the code that moves it around 3 days ago because 1 pos was in a wall when I checked. I set the database pos to a valid position, and pulled to server, so it should not be moving anymore and the pos that was in a wall shouldn't exist anymore. Talk to you in game in a minute, I need to see where its landing. I want you to show me.

**Comment by TeoTwawki** [comment]
Effing crap code in DSP. They had the onMobDeath of the mob it spawns planting it in the middle of gd nowhere.
