### ISSUE TITLE
Dancer job: Izhiikoh high damage occasionally hits.

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#329]
Date & Time: 09/21/2015 (09:54am)
 Frequency: Everytime
 FFXI Client Version: 30150730_2
 Character Name: Dimma
 Race: Hume
 Main Job: DNC
 Sub Job: NIN
 Area & Coordinates: none
 Party or Solo: Party or solo
 NPC Name: 
 Monster Name: 
 Multi-boxing? (multiple clients on same connection): 
 Steps To Reproduce The Issue: 

Izhiikoh has a hidden effect that causes high damage when occasionally hits a monster and seems to work with thief job but not with a dancer job , this could be a game bug or something?

**Comment by R3P0FFXI** [comment]
Enhances "Triple Attack" Effect 2

This has the correct mod on it you are just unlucky please stop opening Dancer job related tickets Dimma we have no intention of working on dancer any time soon

**Comment by Dimmabr** [comment]
Thank you
