### ISSUE TITLE
Nyzul Isle 99 Sets NPC doesn't work

### ISSUE THREAD

**Issue by SomeGlenn** [LegionDark/Issues#33]
**Date & Time**: 29th May
**Frequency**: Always
**FFXI Client Version**: 30150508_8
**Character Name**: Glenn
**Race**: Hume
**Main Job**: BLU
**Sub Job**: NIN
**Area & Coordinates**: X22 Y0 Z-86
**Party or Solo**: Solo
**NPC Name**: Mrohk Sahjuuli
**Monster Name**: N/A
**Steps To Reproduce The Issue**:
1) Farm many hours for Snowsteel Ores
2) Trade items as http://www.legiondark.com/forums/viewtopic.php?f=27&t=115
3) Nothing happens
4) Talk to the NPC, and it tries to give you a whole bunch of designs, so no help there

**Comment by atom0s** [comment]
'Latest' is not a valid client version.  Please use the value from the game.

**Comment by SomeGlenn** [comment]
Updated.

**Comment by Loki79** [comment]
Need more info,  like the specific items you are trading.  This npc also handles other things so just talking may trigger one of those events.  Trade all the required items at once and report back what happens.

**Comment by SomeGlenn** [comment]
I traded Denali Jacket + 12 Snowsteel Ores + 5 imperial gold pieces
