### ISSUE TITLE
MNK WEP Fists of Fury +1 do not attack(WS and counter attack only)

### ISSUE THREAD

**Issue by slaggyt** [LegionDark/Issues#330]
**Date & Time**: Sept 20th and 21st 2015
**Frequency* Never auto attack
**FFXI Client Version**: 30150730_1
**Character Name**:Lionpaw
**Race**:Taru
**Nation**:Bastok
**Main Job**:MNK
**Sub Job**:WAR
**Area & Coordinates**: Abby Altep E-9
**Party or Solo**: Party and solo
**NPC or Monster Name**:  Fear Dearg
**ffxiah.com link (for inventory items only)**:  http://www.ffxiah.com/item/20528/fists-of-fury-1
**Multi-boxing? (multiple clients on same connection)**: Tried w/o and with multi boxing
**Steps To Reproduce The Issue**: Took off wep tried outside of Abby

**Comment by slaggyt** [comment]
Just tried Eminent Baghnakhs the are attacking but they are showing dagged weapon skills.http://www.ffxiah.com/item/20540/em-baghnakhs. Tried everything I did for Fist of Fury weapon.(inc Removing them)

**Comment by Loki79** [comment]
Both items are fixed, be in next maint.
