### ISSUE TITLE
Disconnect into unable to log in

### ISSUE THREAD

**Issue by AlixeT** [LegionDark/Issues#331]
**Date & Time**:  9/22/2015 0130
**Frequency**: On all characters and accounts I have
**FFXI Client Version**: 30150910_3
**Character Name**: Alixe/ Swordeni
**Race**:Taru/Hume
**Nation**:Jeuno/Sandy
**Main Job**: Rdm/War
**Sub Job**:Nin/None
**Area & Coordinates**:Residential area
**Party or Solo**: solo
**NPC or Monster Name**: None
**ffxiah.com link (for inventory items only)**: None
**Multi-boxing? (multiple clients on same connection)**: Not at the time of this event. My husband plays on the same connection on occasion.
**Steps To Reproduce The Issue**: I was just putting rdm gear on and it DC'd me. Gave error 3305 so I left it for a while to see if my character would disconnect. As of this ticket Character is still logged into the server on the list. Also made a new character and tried again but same issue occurred on that character.

**Comment by NononoA** [comment]
Same here. My friends with me fighting Resheph in Abyssea - Uleguerand at 42% HP left got DCed and can't login again. We turn off the computer over few hours but our characters still show as online.

**Comment by PikaFox** [comment]
Unfortunately nothing can be done until someone who can restart the server wakes up, sorry for the inconvenience

**Comment by R3P0FFXI** [comment]
Sadly this was one of those issues Auto restarter was unable to handle. Server has been restarted and is back up and running
