### ISSUE TITLE
Mytic trial not registering

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#332]
**Date & Time**:  9/22/2015 12:35pm
**Frequency**: Always
**FFXI Client Version**: 30150730_2
**Character Name**: Baucant, Dapunted and Jukebox
**Race**: Elvan Taru mithra
**Nation**: Sandy
**Main Job**: Thf, Whm, Brd
**Sub Job**: Nin, Rdm, dnc
**Area & Coordinates**: Mount Zhayoln x:403 y:-27 z:121 (126)
**Party or Solo**: Party
**NPC or Monster Name**: Brass Borer
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**: Killed 3 time, checked that weapon was equiped in main hand. disabled gearswap to ensure it did change out anything. checked @trial after every kill trail read 0/5 after every kill.

**Comment by TeoTwawki** [comment]
Fixed broken mob script, looking for you in game now..
