### ISSUE TITLE
Aht Urhgan - Immortal sentries

### ISSUE THREAD

**Issue by whitemistita** [LegionDark/Issues#333]
**Date & Time**: 21-09-2015 16.oo GMT +1
**Frequency**: once
**FFXI Client Version**: 30150730_2
**Character Name**: Boccola
**Race**: Taru
**Nation**: Sandy
**Main Job**: WHM
**Sub Job**: RDM
**Area & Coordinates**: Azouph Isle Staging Point
**Party or Solo**: party
**NPC or Monster Name**: 
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: got mission from Naja, then we went to Nashmau by boat and then entered in Azouph Isle Staging Point. I tried to talk to NPC but no CS started. I check key items and I had no item. Used runic portal to come back to Aht Urhgan and talked to Naja. Nothing happens. I still have mission activated but I cannot speack with anyone to get/finish the mission

**Comment by TeoTwawki** [comment]
Feel free to remind DSP they broke pretty much all of ToAUI that was once working here https://github.com/DarkstarProject/darkstar/issues
**please do not copy Legion's template to them, they will think you are confused about which tracker you are using.**

**Comment by TeoTwawki** [comment]
@LegionDark/gm might be somewhat fixable using GM commands. Next misison following it will most likely be just as broken.

**Comment by whitemistita** [comment]
Thx for your replay,
I know ToAU missions are not implemented yet, but i should be able to do them till "Immortal Sentries" the one that allow to get signet and use the runic portals (i did it with my main char). Can it be fixed?

**Comment by TeoTwawki** [comment]
@whitemistita the 1st few were, and an update from DSP that was supposed to add more broke the existing ones instead. A Legiondark GM will have to get with you and see if GM commands can make your mission progress correctly. `@addkeyitem` / `@setplayervar` w/e..

**Comment by TeoTwawki** [comment]
@LegionDark/gm  `@addkeyitem` / `@setplayervar` w/e..See what you can find in the scripts on DSP's repository to point you at correct part (`scripts/zones/ZoneHere/npc/NameHere.lua`)

**Comment by whitemistita** [comment]
got KI from a GM and successfully completed the mission.
Thanks

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
