### ISSUE TITLE
Manibozho beret no stats shown on status screen

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#334]
**Date & Time**: 22/09/2015, 10:00am
**Frequency**: Always
**FFXI Client Version**: 30150619_2
**Character Name**: Rukitsu
**Race**: mithra
**Main Job**: THF
**Sub Job**: dnc
**Area & Coordinates**: Irrelevant
**Party or Solo**: Irrelevant
**NPC Name**: none
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/27777/manibozho-beret
**Monster Name**: Irrelevant
**Multi-boxing? (multiple clients on same connection)**: Irrelevant
**Steps To Reproduce The Issue**: ~~not work~~ No stats, see screenshot.
 
![rukitsu_2015 09 22_194642](https://cloud.githubusercontent.com/assets/13084662/10034026/46e678ac-615b-11e5-993e-b49afc416acc.png)

**Comment by TeoTwawki** [comment]
Please take note of the changes I just made to your post.

**Comment by nekrol** [comment]
ok

**Comment by TeoTwawki** [comment]
May be awhile before this gets looked into.

**Comment by Loki79** [comment]
fixed, be in next maint.
