### ISSUE TITLE
Iriz Ima uses Frog Chorus, TP move not from his family

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#335]
**Date & Time**: 9/22/15
**Frequency**: Always
**FFXI Client Version**: 30150730_1
**Character Name**: Tarot
**Race**: Hume
**Nation**: San
**Main Job**: Thf
**Sub Job**: Nin
**Area & Coordinates**: Wajaom Woodlands
**Party or Solo**:party
**NPC or Monster Name**: Iriz Ima ID 16986429
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: Mob uses incorrect TP skill Frog Chorus, causes AoE charm.

**Comment by TeoTwawki** [comment]
Huh. Thought @Loki79 fixed that before closing #200 
Theres a whole change to how mobskills are done coming up (dsp already has it, Legion hasn't caught up yet), and it'll be fixed then if not sooner.

**Comment by PikaFox** [comment]
Updated to fix Taort.

**Comment by Loki79** [comment]
fixed, be in next maint.
