### ISSUE TITLE
"Nahtirah Hat" and "Regal Pumps +1" currently cannot be equipped as White Mage

### ISSUE THREAD

**Issue by Roamin** [LegionDark/Issues#336]
**Date & Time**:  September 23rd 2015
**Frequency**: All the time
**FFXI Client Version**: 30150730_1
**Character Name**: Redroam
**Race**: Taru
**Nation**: Windurst
**Main Job**: Whm
**Sub Job**: Rdm
**Area & Coordinates**: not applicable
**Party or Solo**: Solo
**NPC or Monster Name**: not applicable
**ffxiah.com link (for inventory items only)**:  27775 (Nahtirah Hat) and item 28274 (Regal Pumps +1)
**Multi-boxing? (multiple clients on same connection)**: Yes 3 box same pc
**Steps To Reproduce The Issue**:
The following 2 items are unable to be equipped as a White Mage , although they are labeled as whm gear:

27775 Nahtirah Hat
28274 Regal Pumps +1

**Comment by Roamin** [comment]
I posted these 2 because I have been receiving a few tells about them, being good gear , and they both dropped from VW.  There are a few more items i have noticed that either drop directly to floor (floestone is another popular item) or cannot be equipped. (Mostly drop to floor) But i'm pretty sure Strafeous had already went through a whole bunch of these items , so this might be double work for nothing.

**Comment by qiganggang** [comment]
this BUG what time fixed?

**Comment by TeoTwawki** [comment]
It'll get fixed when it gets fixed. And then this gets closed and thats how you'll know.

**Comment by Loki79** [comment]
Both items are fixed.  Will be in next maint,.
