### ISSUE TITLE
Mythic trial 2: Brass Borer gives credit as Achamoth

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#337]
**Date & Time**: 9/23/15
**Frequency**: Once
**FFXI Client Version**: 30150730_1
**Character Name**: Tarot
**Race**: Hume
**Nation**: San
**Main Job**: Thf
**Sub Job**: Nin
**Area & Coordinates**: Mount Zhayolm
**Party or Solo**: Party
**NPC or Monster Name**: Brass Borer/Achamoth
**ffxiah.com link (for inventory items only)**:  NA
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: 4/4 on all mobs but Achamoth, needed another Achamoth pop so we went to start down the Achamoth line, killed Brass Borer and got the last credit off him. 4 people got the credit.

http://imgur.com/FyCcrw0

**Comment by TeoTwawki** [comment]
Fixed a bug that would enable certain objectives to count towards the wrong tier. As a side effect objective counts can exceed their maximum, but this is purely cosmetic and the trial will still complete properly cone all objectives are met or exceeded. Cosmetic bug will last until all requirements are moved into an array.
