### ISSUE TITLE
Character Wulfstadt cannot recieve gil/gil not updating

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#338]
**Date & Time**: 9/23/15
**Frequency**: Always 
**FFXI Client Version**: 30150730_1
**Character Name**: Wulfstadt
**Race**: Hume
**Nation**: Bastok
**Main Job**: 53 Thf
**Sub Job**: None
**Area & Coordinates**: Valkurm Dunes
**Party or Solo**: NA
**NPC or Monster Name**: NA
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Character is a recent server transfer character. Gil was stuck at 1 and would not update. Was able to trade the gil away, but any gil traded back would not be updated on the character.

Bug report was filled out by Tarot while Wulfstadt was making a github account.

**Comment by R3P0FFXI** [comment]
Hes going to need to reimport his character once we update the server, We are not on the latest client so the tooll appears to not be functioning correctly

**Comment by R3P0FFXI** [comment]
As your character has been reimported please let me now if you are still experiencing issues

**Comment by R3P0FFXI** [comment]
No response from player
