### ISSUE TITLE
Ashen Stratum Abyssite to a KeyItemAshen Stratum Abyssite II 

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#339]
Date & Time: 24/09/2015, 1100am
Frequency: Always
FFXI Client Version: 30150730_2
Character Name: Aurel -Cassy
Race: Hume
Main Job: Blu-Thf
Sub Job: Rdm-dnc
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name: Kieran
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:after killing every mob, no NPC Kieran scene.

**Comment by qiganggang** [comment]
we need UP ki no CS cant up ki

**Comment by TeoTwawki** [comment]
I'll check and see whats up with this soon

**Comment by Loki79** [comment]
Thought we had this sorted out.  Go back and make sure you have followed every step in the quest.

**Comment by nekrol** [comment]
Search is simple, but no more stones to kill again the NM

**Comment by TeoTwawki** [comment]
Ok, I checked using `@checkquest Aurel 80` to see what status of "Guardian of the Void" was, and it show the quest active and not completed. So that Aurel ever got the 1st Ashen Stratum Abyssite is a mystery. This NPC is supposed to snub you until that quest is completed. Upgrading to the 2nd tier requires 3 more quests: 

VOIDWATCH_OPS_BORDER_CROSSING
VW_OP_054_ELSHIMO_LIST
VW_OP_101_DETOUR_TO_ZEPWELL

After several cs later and all 3 are done, and you are finally given tier 2.

**Comment by TeoTwawki** [comment]
GDI..Nevermind previous comment, command error at fault

**Comment by TeoTwawki** [comment]
Ok, I checked using 
`@checkquest` 5 100 Aurel`
`@checkquest` 5 101 Aurel`
`@checkquest` 5 102 Aurel`
to see what quest status's were.
Upgrading to the 2nd tier requires 3 more quests: 

VOIDWATCH_OPS_BORDER_CROSSING
VW_OP_054_ELSHIMO_LIST
VW_OP_101_DETOUR_TO_ZEPWELL

After several cs later and all 3 are done, and you are finally given tier 2.

All 3 of these quests show they are still active, not completed. You need to speak with the NPC's in Rabao and Kazham to finish them after killing all involved NMs.

**Comment by TeoTwawki** [comment]
Ok, I checked using
`@checkquest 5 100 Aurel`
`@checkquest 5 101 Aurel`
`@checkquest 5 102 Aurel`
to see what quest status's were.
Upgrading to the 2nd tier requires 3 more quests: 

VOIDWATCH_OPS_BORDER_CROSSING
VW_OP_054_ELSHIMO_LIST
VW_OP_101_DETOUR_TO_ZEPWELL

After several cs later and all 3 are done, and you are finally given tier 2.

All 3 of these quests show they are still active, not completed. You need to speak with the NPC's in Rabao and Kazham to finish them after killing all involved NMs.

**Comment by TeoTwawki** [comment]
**Reminder:** as long as you multi box, random things will break that work for pretty much everyone else, at random. You seem to be extra unlucky.

**Comment by nekrol** [comment]
It would be nice not needing another specialized char in THF, and all have an item with TH +12, because I think it is annoying THF walk with mules and other whm .. It's just an opinion

**Comment by TeoTwawki** [comment]
@nekrol what? wtf are you even talking about?? What relation to this issue does anything you just said, actually have??

**Comment by nekrol** [comment]
is for use 3 mules passing bug me ,-.thf -rdm -sam

**Comment by Loki79** [comment]
Just reading this makes me want to slap someone.....

**Comment by nekrol** [comment]
hello we kill all NM, and not up KI

**Comment by nekrol** [comment]
Ashen Stratum Abyssite to a KeyItemAshen Stratum Abyssite I
