### ISSUE TITLE
Forgot my alt's login credentials

### ISSUE THREAD

**Issue by Tanild** [LegionDark/Issues#340]
My main is Splinter but I can't remember the alt's information. I really would like it because it's a ~78BRD and a ~70WHM...that' a good amount of time I lost. I know this is totally my fault but any help would make me really happy.

Thank you for your consideration
-Splinter

**Comment by R3P0FFXI** [comment]
Please PM me on the forums what your alts login ID and character name were and I will look into resetting the password if this information is correct.

**Comment by Tanild** [comment]
Hey I can't PM on the website, insufficient privileges. I don't remember my credentials, I made them abnormal and I have no idea why. My username could be a number of things:
TanildErollAltHealerBard
I believe the character's name is Eroll, I'm not even sure on that lol
Thank you for helping,-Splinter 


     On Friday, September 25, 2015 5:29 AM, R3P0FFXI <notifications@github.com> wrote:
   
 

 Please PM me on the forums what your alts login ID and character name were and I will look into resetting the password if this information is correct.—

**Comment by TeoTwawki** [comment]
@Tanild Suggest trying to PM him on IRC isnetad.

@R3P0FFXI fix your forum stuffs so people can actually PM you before telling them to PM you :frowning:
