### ISSUE TITLE
4-12 aern organ cant  pop Ix'aern (DRK) 

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#341]
Date & Time: 9/25/15
Frequency: Always
FFXI Client Version: 30150730_1
Character Name: Hiya
Race: Hume
Main Job: BLU
Sub Job: RDM
Area & Coordinates: 
Party or Solo:party solo
NPC or Monster Name:  Ix'aern (DRK) 
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): yes

 i have 12 aern organ but cant pop  Ix'aern (DRK)  is  no work?

**Comment by PikaFox** [comment]
4 stacks of 12. I popped him, he works.
