### ISSUE TITLE
Gasha jeuno t2 problem 0hp

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#342]
Date & Time: 25/09/2015
Frequency:
FFXI Client Version: 30150730_2
Character Name: bathuka
Race: elvaan
Nation: sandy
Main Job: pld
Sub Job:
Area & Coordinates: Eldiemne necropole
Party or Solo: alliance
NPC or Monster Name: GASHA
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue

THE nm do not die
http://img15.hostingpics.net/pics/978119Bathuka20150925001013.png

Can you this is that we exceed the temp available to kill him ?
we had a really great difficulty killing 
((IT REALLY DraiN MANY OF LIFE WITH BLOOD SABER)) (for loki) lol

**Comment by Loki79** [comment]
Blood saber I'll look at when I get back in town.  The not dying I'm going to have to assume is do to some recent changes to his script for testing.

Teo looks like actuonque stuff may have s side effect.

**Comment by bathuka** [comment]
kk cool

**Comment by TeoTwawki** [comment]
@Loki79 I put in the action check thing after this happened, as a response to it. The timer ran out and that happened when it tried to depop. Now it *shouldn't actually try to depop if its middle of doing something* and instead finish its previous action then immediately try to depop. I hope.

**Comment by Loki79** [comment]
@LegionDark/gm please test this.

**Comment by PikaFox** [comment]
We killed this NM yesterday and were able to kill it. How conclusive that is as to whether the problem is solved or not i dont know.

**Comment by TeoTwawki** [comment]
@PikaFox since the issue was with the code for it despawning from time running out for the fight, being able to kill it really isn't relevant. To test it somebody would need to deliberate;y hold it and see if it despawns properly or gets stuck again now.

**Comment by TeoTwawki** [comment]
@Loki79 pisses me off that nobody ever got back to me on the results of this. If later someone tells me its broken, my response is going to start with 4 letter words.
