### ISSUE TITLE
Laidly Laurence t2 jeuno

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#343]
Date & Time: 25/09/2015
Frequency:
FFXI Client Version: 30150730_2
Character Name: bathuka
Race: elvaan
Nation: sandy
Main Job: pld
Sub Job:
Area & Coordinates: citadel garlaige ( s )
Party or Solo: alliance
NPC or Monster Name: laidly laurence
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue

compare it to other t2 nm is really an ordeal even sound easier t4
http://img15.hostingpics.net/pics/946689Bathuka20150925021408.png

**Comment by Loki79** [comment]
The move works like 10,000 needles.  Need more ppl to absorb the dmg.

**Comment by bathuka** [comment]
ahhhhhhhhhhhhhhhhhh

**Comment by bathuka** [comment]
ok close this lol sry
