### ISSUE TITLE
Bard's AF3 Low drop rate per NM in abyssea.

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#344]
Date & Time: 09/25/2015 (09:35am)
 Frequency: Everytime
 FFXI Client Version: 30150730_2
 Character Name: Dimma
 Race: Hume
 Main Job: DNC
 Sub Job: NIN
 Area & Coordinates: none
 Party or Solo: Party or solo
 NPC Name: 
 Monster Name: 
 Multi-boxing? (multiple clients on same connection): 
 Steps To Reproduce The Issue: 

Aoidos Seal Hands (Item ID: 3159) - Total Drops: 4

Mob Name

Zone

Drop Rate

Spawn Location

Vadleany Abyssea-Altepa 10.00% X: -58.000, Y: 0.001, Z: 119.000 
Upas-Kamuy Abyssea-Uleguerand 10.00% X: -212.000, Y: -184.000, Z: 449.000 
Teekesselchen Abyssea-Grauberg 10.00% X: 460.507, Y: 56.975, Z: 679.438 
Teekesselchen Abyssea-Grauberg 5.00% X: 460.507, Y: 56.975, Z: 679.438 

Why brd's get so low drop rate per drops? 

I have farming in Abyssea for bard's seal's but I have encountered many difficulties because many NMs drop only 1 label while drop 3-4 other jobs, please tell me you are going to adjust this ...

**Comment by R3P0FFXI** [comment]
... this is not a bug please stop reporting things that are not bugs

**Comment by Dimmabr** [comment]
I know that this is not a bug but something's wrong and you know it.

**Comment by TeoTwawki** [comment]
> I know that this is not a bug but something's wrong and you know it.

Saying "and you know" is makes me not care, and I expect other staff to feel same way. You had bad luck. 

The bug tracker is for BUGS not whining about poor drop rates on the item you want. If you want to **POLITELY** suggest a drop or drop rate should be changed, using the forum *would have* been a good choice so other would see it and share their experiences for staff to see.

**Comment by R3P0FFXI** [comment]
Nothing is wrong this is how it was set this is what was chosen you had bad luck
