### ISSUE TITLE
Saotome Kote +2: Meditate duration

### ISSUE THREAD

**Issue by excenmille** [LegionDark/Issues#345]
Date & Time: 9/26/15
Frequency: Always
FFXI Client Version: 30150730_1
Main Job: sam
Sub Job: war
Party or Solo: Solo
Multi-boxing? (multiple clients on same connection): no
FFXIAH Link: http://www.ffxiah.com/item/10701/sao-kote-2
Item ID: 10701
Steps To Reproduce The Issue:

I just got my saotome kote +2 but its meditate duration isn't longer than the base NQ version. Other players from ffxiah say they're getting 1800-2000 TP when used together with sam AF1 head. But I'm never getting any higher than 1600. 

I also tested equipping the kote without the AF1 helm and sometimes I ended up with as low as 1200 TP only.

**Comment by excenmille** [comment]
If this is a DSP issue that you can't change, can I also check if BLU's Mirage Jubbah +2 (item ID 10685) work properly before I start farming for it? According to ffxiah the +2 piece should give 2 MP/tic refresh whereas the base armor only gives 1/tic.

**Comment by Loki79** [comment]
Fixed.  Be in next maint.
