### ISSUE TITLE
Regal Pumps Not equiping

### ISSUE THREAD

**Issue by Topace1** [LegionDark/Issues#346]
**Date & Time**: 09/26/2015 5:40PM
**Frequency**:Keep trying won't work
**FFXI Client Version**:
**Character Name**: Topace
**Race**: Tarutaru
**Nation**: Windurst
**Main Job**: Black Mage
**Sub Job**: Red Mage
**Area & Coordinates**: Aht Arghan 
**Party or Solo**: Party/Solo
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**:

**Comment by Loki79** [comment]
Just fixed this, will be in next maint.
