### ISSUE TITLE
renik af+1 reforged rdm legs error

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#347]
Date & Time: 27/09/2015
Frequency:
FFXI Client Version: 30150730_2
Character Name: zaya
Race: hume 
Nation: sandy
Main Job: rdm
Sub Job:
Area & Coordinates: upper jeuno
Party or Solo: alliance
NPC or Monster Name: renik
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue

i have trade atrophy leg (rdm) + 5rem chap 2 
and i obtain blm leg af1 reforged lol
http://img15.hostingpics.net/pics/411880Zaya20150927001320.png

that possibl you return me the atrophy leg +1 http://www.ffxiah.com/item/28115/atrophy-tights-1
tks :)
http://img15.hostingpics.net/pics/429987Zaya20150927001950.png

**Comment by nekrol** [comment]
work??'??'?

**Comment by Loki79** [comment]
I'll get to this tonight or tomorrow

**Comment by Kaoriasada** [comment]
Same issue as #351. 
I went ahead and gave the item to Zaya and Myeva. 

Issue seems to be that the ID was typo'd when coding it, the RDM legs are 28115 and the BLM legs are 28114.  Closing the other report and leaving this one open since this one is more detailed.

**Comment by Loki79** [comment]
Script is corrected.  If you haven't gotten your correct item pls see a GM in game or ping one of us in IRC.  closing this out, changes are lua so will take effect tonight when I pull it into the server.
