### ISSUE TITLE
Iriz Ima doesnt give mythic trial credit

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#349]
**Date & Time**: 9/28/15
**Frequency**: Once
**FFXI Client Version**: 30150730_1
**Character Name**: Tarot
**Race**: Hume
**Nation**: San
**Main Job**: Dnc
**Sub Job**: Nin
**Area & Coordinates**: Wajoam Woodlands
**Party or Solo**: Party
**NPC or Monster Name**: Iriz Irma
**ffxiah.com link (for inventory items only)**:  NA
**Multi-boxing? (multiple clients on same connection)**: NA
**Steps To Reproduce The Issue**: Killed mob, didnt get credit. (at)Trial says his name is Iriz Irma, in game name is Iriz Ima

Also bitch still uses frog chorus :c gdi frog chorus! Cant wait for the maint that fixes that xD

**Comment by Loki79** [comment]
Frog chorus won't change until after maint.

**Comment by PikaFox** [comment]
I know, was just an added comment on him still being a dick :s main thing was the lack of trial credit with weapon equipped when he was working a couple days ago, which is really odd.

**Comment by TeoTwawki** [comment]
Script and database both match the in game name, `@trial` text is simply typo (and fixed just now). Don't see a reason for it to not give credit..Hm.

**Comment by TeoTwawki** [comment]
I tossed some Debug prints into Iriz's script to see if its executing the code it should.

**Comment by synafey** [comment]
It happend also to whitemist and I yesterday, we got the debug message, but no credits for the kill

**Comment by TeoTwawki** [comment]
Need to know which messages, so I know which block of code it stopped at.

**Comment by Roamin** [comment]
Same thing happening with hickss, he sent me his SS , here's the debug message

![hickss_2015 09 30_122923](https://cloud.githubusercontent.com/assets/398228/10199814/c2a5b686-6770-11e5-9c79-3a763be365a4.png)

**Comment by TeoTwawki** [comment]
Well wtf, it passed the check, that should have incremented.

**Comment by TeoTwawki** [comment]
Found, fixed tested. Its working now. Found same bug with Hydra. Added new conditional debug checks to prevent future mysteries like this (if it ever happens again, then the debug info will print).

**Comment by TeoTwawki** [comment]
@LegionDark/gm @LegionDark/owners 
`@setplayervar <name> C_TRIAL_OBJ_2 <number>`
 will adjust the kill counts of those who were effected by this bug prior to the fix.
