### ISSUE TITLE
NM Pallid Percy failed to spwn

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#35]
**Date & Time**: 5/30/2015 10:53 am
**Frequency**: once so far
**FFXI Client Version**:30150508_8
**Character Name**: Baucant
**Race**:Elvaan
**Main Job**: Thf
**Sub Job**: Dnc
**Area & Coordinates**: Aby Attohwa Chasm X:280 y:20 z:172 (0)
**Party or Solo**: Party
**NPC Name**: ???
**Monster Name**: Pallid Percy
**Steps To Reproduce The Issue**: will continue to attempt to pop
http://ffxiclopedia.wikia.com/wiki/Pallid_Percy
Traded  Blanched Silver to ??? to pop NM. Item was removed when traded but NM did not spawn.

**Comment by Baucant** [comment]
found the NM, the location that NM spawns after trading the item is incorrect.

**Comment by R3P0FFXI** [comment]
Can you give the correct coordinates so we can check?

**Comment by Baucant** [comment]
X:280 y:20 z:172 (0) appox is the location of the ???

**Comment by bathuka** [comment]
use wide scan he pop just has another position

**Comment by Baucant** [comment]
@bathuka Finding the mob is not the point, the point is to have it work correctly

**Comment by TeoTwawki** [comment]
Could have sworn @Loki79 moved this NM before because of this exact issue.

**Comment by Loki79** [comment]
I have... but ill look again, when i have time.
