### ISSUE TITLE
Bad scripts (mainly in Abyssea)

### ISSUE THREAD

**Issue by TeoTwawki** [LegionDark/Issues#350]
@LegionDark/owners all mob scritps in all abyssea zones need to be reviewed. **Not it, bro.**

If you use a text ID, as when using `messageSpecial()`, you have to not only require the TextIDs file you also have to package null it first.

The reason the TextIDs.lua package gets nulled out at the top of each header between the header info and its requires is: every zone uses that same filename. If we don't null then reload it, a player can zone in and the server will use the ID values from the TextIDs.lua of the zone they came from instead of the zone they are now in. Often that ID will be an invalid or null ID for the current zone, and cause a client crash. this is what happened with the voidwatch guy in Norg. You have upwards of 500 crashes waiting to happen anytime a mob dies that gives a key item.

**Comment by TeoTwawki** [comment]
l;dr
if you use a text ID, you have to not only require the TextIDs file you also have to package null it first.

**Comment by TeoTwawki** [comment]
p.s.
Also saw magic numbers in place of text IDs, which will cause client crashes when ID shifts happen because those don't update themselves (that's the number I removed from BabaYaga.lua and replaced with a valid TextID...)

**Comment by Loki79** [comment]
I wont have time for this until SAT but ill dig into it then and get it sorted out.

**Comment by TeoTwawki** [comment]
@Loki79 I'm sticking @R3P0FFXI with the textIDs in the update branch so we can have fewer crashes in abyssea (theres over 500 scripts that will crash clients on monster death, and it just gave me a migraine updating the branch..) I'll let you take care of the static IDs that remain when we are done updating, because getting through this update takes priority and you are having an extended away time.

**Comment by R3P0FFXI** [comment]
@TeoTwawki I want to work on this today I ma over my cold what was the require that needed changing again I lost the PM window in my IRC client from a few days ago

**Comment by TeoTwawki** [comment]
````lua
-----------------------------------
package.loaded["scripts/zones/Abyssea-Altepa/TextIDs"] = nil;
-----------------------------------
require("scripts/zones/Abyssea-Altepa/textIDs");
```

Those must always be together, in that order.

**Comment by TeoTwawki** [comment]
````lua
-----------------------------------
package.loaded["scripts/zones/zoneName/TextIDs"] = nil;
-----------------------------------
require("scripts/zones/zoneName/TextIDs");
```

Those must always be together, in that order.

And its case sensitive.

**Comment by R3P0FFXI** [comment]
Pushed fix to Massive Update Branch, issue resolved in update
