### ISSUE TITLE
 OH renik af+1 reforged rdm legs error

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#351]
Date & Time: 28/09/2015
Frequency:
FFXI Client Version: 30150730_2
Character Name: myeva
Race: hume 
Nation: sandy
Main Job: rdm
Sub Job:
Area & Coordinates: upper jeuno
Party or Solo: alliance
NPC or Monster Name: renik
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue

i have trade atrophy leg (rdm) + 5rem chap 2 
and i obtain blm leg af1 reforged lol

**Comment by nekrol** [comment]
sorry I thought it worked well and the NPC, and pass objects 
![myeva_2015 09 28_154504](https://cloud.githubusercontent.com/assets/13084662/10145188/a36b6c3e-65ef-11e5-8aeb-e5aaa0df09bb.png)

**Comment by Kaoriasada** [comment]
I traded the NPC the same thing, got the same result.  Gave Myeva the Atrophy Tights +1, leaving the ticket open because it still needs fixed.  Seems like someone typo'd the ID, RDM tights are 28115 and the BLM tonbans are 28114.

**Comment by Kaoriasada** [comment]
Same issue as #347, closinbg because other report is more detailed
