### ISSUE TITLE
ischemia chasuble no stat

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#353]
Date & Time: 29/09/2015
Frequency:
FFXI Client Version: 30150730_2
Character Name: zaya
Race: hume
Nation: sandy
Main Job: rdm
Sub Job:
Area & Coordinates:
Party or Solo: 
NPC or Monster Name: 
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue
 ischemia chasuble  have no stat :)
http://img11.hostingpics.net/pics/123040Zaya20150929014512.png

**Comment by Kaoriasada** [comment]
Coded and emailed to @Loki79

**Comment by Loki79** [comment]
added, thanks Sami! will go in next maint.
