### ISSUE TITLE
Claidheamh soluis skill+ not script and hidden idk 

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#354]
Date & Time: 29/09/2015
Frequency:
FFXI Client Version: 30150730_2
Character Name: bathuka
Race: elvaan
Nation: sandy
Main Job: pld
Sub Job:
Area & Coordinates: 
Party or Solo: 
NPC or Monster Name: 
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue
https://www.bg-wiki.com/bg/Claidheamh_Soluis
the sword do not have the skill+ and hidden idk

New loot pools:
(all the weapons below have hidden effects: Occasionally does double damage & TP Bonus +1000) They are not as good as Empy/Mythic/Relic but are by far the best weapons you can get that don't need to be built through trials.

sry i know i report all time do not kill me ;-;

**Comment by PikaFox** [comment]
Skill+ on weapons dont show up when you equip them anymore, they are handled in a different calculation since DSP actually coded ilvl stuff now. Unless i am misunderstanding you, all of your 119 weapons should show this.

**Comment by bathuka** [comment]
when i equip burtgang or almace i have 855 attack and when i equip this i down to 600

**Comment by PikaFox** [comment]
Alright then, thats a little more descriptive :3

**Comment by Kaoriasada** [comment]
The sword is definitely coded and working properly.  I think you're getting more attack because our REMs are custom, and this weapon is just coded to retail.

**Comment by Kaoriasada** [comment]
Just a guess though

**Comment by Loki79** [comment]
Skill was not added.  I have it corrected but wont go in until maint.
