### ISSUE TITLE
unable to equip Regal Pumps +1

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#355]
**Date & Time**: 9/29/2015 2:18am
**Frequency**: Always
**FFXI Client Version**:30150730_2
**Character Name**:Dapunted
**Race**:Taru
**Nation**:Sandy
**Main Job**:whm
**Sub Job**:rdm
**Area & Coordinates**: any area all locations
**Party or Solo**:both
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**:http://www.ffxiah.com/item/28274/regal-pumps-1 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: attempted reloging, zoning, inside and outside MH

**Comment by PikaFox** [comment]
https://github.com/LegionDark/Issues/issues/336

**Comment by PikaFox** [comment]
Issue has already been addressed in another closed report as linked above
