### ISSUE TITLE
Plunderer's Armlets +1 Eva not working in checkperm

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#356]
**Date & Time**: 9/29/2015 2:05pm
**Frequency**: Always
**FFXI Client Version**:30150730_2
**Character Name**:Baucant
**Race**:Elvaan
**Nation**:Sandy
**Main Job**:Thf
**Sub Job**:Nin
**Area & Coordinates**: all areas all coordinates
**Party or Solo**: both
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**:http://www.ffxiah.com/item/26987/plun-armlets-1 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: Zoneing, loging, inside MH and outside.

When placing the armlets on and doing /checkperm <me> I notice my eva is the same as when I have no gloves on, I also compared this to Skulker's Armlets. I found that when I put the Skulker's armlets on my eva goes up. The Skulker's amlets have +16 eva where the Plunderer's Armlets +1 have +39 eva.

**Comment by Baucant** [comment]
this also brings a concern about the TH on these could we look at that also?

**Comment by Loki79** [comment]
Glad you pointed this out, although you just totally screwed yourself.  They were getting EVAP (eva%) which means you had tons more EVA than you should have,  That is now corrected on all these items.  TH is fine.

**Comment by Baucant** [comment]
well if thats how you intended them to work please by all means just correct me and keep the higher eva

**Comment by R3P0FFXI** [comment]
EHHHH WRONG ANSWER MCYFLY!

**Comment by TeoTwawki** [comment]
Lol
