### ISSUE TITLE
Manibozho Brais no stats added

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#358]
Date & Time: 9/29/2015 2:05pm
Frequency: Always
FFXI Client Version:30150730_2
Character Name:Baucant
Race:Elvaan
Nation:Sandy
Main Job:Thf
Sub Job:Nin
Area & Coordinates: all areas all coordinates
Party or Solo: both
NPC or Monster Name: N/A
ffxiah.com link (for inventory items only): http://www.ffxiah.com/item/28199/manibozho-brais
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue: Zoning, loging, inside MH and outside.

**Comment by Kaoriasada** [comment]
I coded and e-mailed these to @Loki79

**Comment by Loki79** [comment]
added, thanks Sami! will go in next maint.
