### ISSUE TITLE
Food not working Coconut Rusk

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#36]
Date & Time: 5/30/2015 2:07 Pm
Frequency: anytime i try to use
FFXI Client Version:30150508_8
Character Name: Baucant
Race:Elvaan
Main Job: Thf
Sub Job: Dnc
Area & Coordinates: anywhere
Party or Solo: both
NPC Name: N/A
Monster Name: N/A
Steps To Reproduce The Issue: will continue to attempt to pop
Attempted to use food Coconut Rusk. food was not consumed no food effect given

**Comment by TeoTwawki** [comment]
its an unimplemented item (no script for it yet)

**Comment by Loki79** [comment]
Ok.. looking at what this food does i can tell you that the mods for it dont even exist, and therefore will not be implemented for quite some time.  If a time comes when these mods do get made we will let you know.  Closing this out.
