### ISSUE TITLE
Can't complete Immortal Sentries, didn't get KI Supplies Package

### ISSUE THREAD

**Issue by Psyllia** [LegionDark/Issues#361]
**Date & Time**: 9/30/2015 12 PM PST estimated
**Frequency**:Once
**FFXI Client Version**: 30150730_1
**Character Name**: Bildo
**Race**: Galka
**Nation**: Bastok
**Main Job**: Thf
**Sub Job**: Dnc
**Area & Coordinates**:Aht Urghan Whitegate I-10
**Party or Solo**: Party with Psyllia and Holiday
**NPC or Monster Name**: Naja Salaheem
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Yes, with Holiday
**Steps To Reproduce The Issue**: Tried zoning in and out, and logging off and on again, I talk to her and she doesn't say anything. First time she said her script but didn't give the KI Supplies Package

**Comment by TeoTwawki** [comment]
Known DSP bug, a GM will have to assist you in game. One should contact you as soon as they are able.

@LegionDark/gm `@addkeyitem` to the rescue yet again..

**Comment by Kaoriasada** [comment]
@Psyllia Message me when you're online if I don't catch you

**Comment by Kaoriasada** [comment]
Gave Bildo the KI.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
