### ISSUE TITLE
Unable to go to the past through Maw, cutscene loops.

### ISSUE THREAD

**Issue by Reaps989** [LegionDark/Issues#362]
Date & Time: 10/3/15
Frequency: Always
FFXI Client Version: Will find out the version in a bit.
Character Name: Nysek
Race: Hume
Main Job: WHM - Does not effect this bug.
Sub Job: BLM - Does not effect this bug.
Area & Coordinates:
1) Batallia Downs (H-5)
2) Rolanberry Fields (H-6)
3) Sauromugue Champaign (K-9) - Need to confirm if this also causes it.
Party or Solo: Solo
NPC Name: N/A
Monster Name: N/A
Steps To Reproduce The Issue: Seen below

I had this issue on live long ago, but forgot how exactly I fixed it.

When I go into a Carnivorous Maw (B. Down, Rol. Field, etc) to unlock the ability to go to the past. The cutscene plays like normal up until the cat-like creature appears. It will not continue the dialog past this point making it impossible to finish the trigger which will let me continue.

Restarting the client does not help :(

![nysek_2015 10 03_033116](https://cloud.githubusercontent.com/assets/14950947/10261918/30ff0b54-697f-11e5-9898-e951637b7afd.png)

**Comment by PikaFox** [comment]
This needs your /ver

**Comment by R3P0FFXI** [comment]
Need client version on this type /ver in game

**Comment by TeoTwawki** [comment]
I a, betting its a newer version than the server so the IDs for objects called by the CS event are mismatched.

**Comment by R3P0FFXI** [comment]
Issue should now be resolved with updated clients as server has been updated
