### ISSUE TITLE
Wayfarer Clogs  Wrong ID

### ISSUE THREAD

**Issue by Az1r** [LegionDark/Issues#363]
**Date & Time**: 
**Frequency**:
**FFXI Client Version**:
**Character Name**: Unisei
**Race**: na
**Nation**: na
**Main Job**: drk
**Sub Job**: sam
**Area & Coordinates**: 
**Party or Solo**: solo
**NPC or Monster Name**: na
**ffxiah.com link (for inventory items only)**:  http://www.ffxiah.com/item/28308/wayfarer-clogs / http://legiondark.com/?p=items&id=28303
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**:

**Comment by R3P0FFXI** [comment]
Fixed should be in next time we pull a maint
