### ISSUE TITLE
Switchstix in Castle Z breaks Aegis acquisition, gives wrong dialogs, and other relic related problems

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#365]
Date & Time:04/10/2015
Frequency:
FFXI Client Version: 30150730_2
Character Name: qigang
Race: elvaan
Nation: sandy
Main Job: pld
Sub Job:THF
Area & Coordinates: Caprnters' Landing H-10 ??? 
Party or Solo: 
NPC or Monster Name:
ffxiah.com link (for inventory items only): Ancile
Multi-boxing? (multiple clients on same connection): yes

i have pop trade the this NPC noting   no CS
![qq 20151004213935](https://cloud.githubusercontent.com/assets/13742980/10268101/76a08b80-6ae0-11e5-96d3-89494ecd15cb.png)
![qq 20151004213945](https://cloud.githubusercontent.com/assets/13742980/10268103/7c8b90a8-6ae0-11e5-8492-4d28818b41b8.png)
![qq 20151004213922](https://cloud.githubusercontent.com/assets/13742980/10268104/7fa65412-6ae0-11e5-9936-e03533f2f767.png)

**Comment by TeoTwawki** [comment]
From retail's wiki:
> **Stage 4 > Stage 5**
>
>    This last step requires two Rare/Ex drops from Dynamis: Xarcabard: a Shard of Necropsyche and a Fragment (which may prove difficult to obtain) specific to your Relic Weapon, **as well as a single 10,000-unit Ancient Currency of a specific type.** 
> 
>    Once you have all these items, pay a visit to Switchstix yet again. **Upon talking to him, you will get a cutscene in which your Relic Weapon will speak to you.** Now head out to the appropriate location for your specific weapon to find a blank NPC target. Trade your Relic Weapon and the required items **(including the Ancient Currency)** to the blank ???. After a cutscene, you will receive your 5th stage, and completely upgraded, Relic Weapon!
> 

Were you also trading the correct currency?

**Comment by qiganggang** [comment]
![qq 20151005130245](https://cloud.githubusercontent.com/assets/13742980/10273324/6476743e-6b61-11e5-88b2-e0c9010cb75e.png)
![qq 20151005125639](https://cloud.githubusercontent.com/assets/13742980/10273325/655e6884-6b61-11e5-86a8-a8e86b73193a.png)
no CS cant trade

**Comment by simthra** [comment]
Date & Time:05/10/2015
Frequency:
FFXI Client Version: 30150910_3
Character Name: thranduil
Race: hume
Nation: bastok
Main Job: sam
Sub Job: dnc
Area & Coordinates: Horlais Peak
Party or Solo: solo
NPC or Monster Name:
ffxiah.com link (for inventory items only): Totsukanotsurugi
Multi-boxing? (multiple clients on same connection): no

Also my character is stuck at this point: it can't get the CS at Zvahl Baileys and trading the items  (totsukanotsutugi+R. goldpiece+divine fragment+necropsyche) to the hot spring in Horlais'peak isn't working.
I'm aware I'm on a wrong client version; thank you.

**Comment by TeoTwawki** [comment]
I'll see if I can find what went wrong sometime tonight guys

**Comment by TeoTwawki** [comment]
you two have 2 diff client versions, 1 old one new, so I don't think it was an ID shift

**Comment by qiganggang** [comment]
![qq 20151006092237](https://cloud.githubusercontent.com/assets/13742980/10297946/d0fd3b92-6c0b-11e5-8ec0-666a5ae083cc.jpg)

**Comment by TeoTwawki** [comment]
@qiganggang @simthra @LegionDark/owners @LegionDark/gm the array the relic goblin uses is broken, reporting to DSP and looking into replacing his script with my own till DSP redoes him..This isn't going to fixed right away.

**Comment by TeoTwawki** [comment]
Has been reported to DSP

**Comment by nekrol** [comment]
hi now work  ,thanks        
![captura](https://cloud.githubusercontent.com/assets/13084662/11252327/5f8d4a76-8e14-11e5-9fb9-6d7f7e3a66f4.PNG)

**Comment by TeoTwawki** [comment]
Weird, because nothing has changed at all. And I know the bug was real, tripped it myself in testing and then reported it to DarkStar's tracker..
