### ISSUE TITLE
caballarius coronet do not enhance rampart duration 

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#366]
Date & Time: 05/10/2015
Frequency: 
FFXI Client Version: 30150730_2
Character Name: bathuka
Race: elvaan
Nation: sandy
Main Job: pld
Sub Job: nin
Area & Coordinates:
Party or Solo: party
NPC or Monster Name:
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue
the caballarius coronet do not enhance the rampart duration :)
https://www.bg-wiki.com/bg/Cab._Coronet

**Comment by R3P0FFXI** [comment]
Bathuka No mod for this exists and until one is created there is nothing we can do.

**Comment by bathuka** [comment]
ahhhhhh kk God
