### ISSUE TITLE
Scathacha, a gk, is acting like single handed weapon

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#367]
**Date & Time**: 10/6/15 noon
**Frequency**: when equiped
**FFXI Client Version**:30150730_2
**Character Name**: Ritonami
**Race**: Mithra
**Nation**: Windurst
**Main Job**:Samurai
**Sub Job**:Dancer
**Area & Coordinates**: 0,0,0, (192)
**Party or Solo**:Solo
**NPC or Monster Name**: none
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/17808/scathacha
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: equip it

**Comment by Kaoriasada** [comment]
This isn't happening.  Used same job and subjob.  Simplying not acting as a single handed weapon.
