### ISSUE TITLE
Sylvan Reforge Feet Wrong Item Reward

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#368]
**Date & Time**:  10/8/15
**Frequency**: Always
**FFXI Client Version**: 30150730_1
**Character Name**: Tarot
**Race**: Hume
**Nation**: San
**Main Job**: Rng
**Sub Job**: NA
**Area & Coordinates**: Abys Paradox
**Party or Solo**: Alliance 
**NPC or Monster Name**: Prishe
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/27431/amini-bottillons
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: Trade Sylvan +2 feet to NPC with 30 Carabosse Gems, get wrong item reward.
![tarot_2015 10 08_111912](https://cloud.githubusercontent.com/assets/12601727/10370975/409a9b1c-6daf-11e5-8c83-3ee6d237928b.png)
![tarot_2015 10 08_112412](https://cloud.githubusercontent.com/assets/12601727/10370981/44fa0fd0-6daf-11e5-9bc8-2ec0bcb3072c.png)

**Comment by Kaoriasada** [comment]
Amini Bottillons have an item ID of 27341.  The Caballarius Leggings +1 have an item ID of 27431.  It's just a typo.  I'll log on and give you the Amini Bottillons since you've dropped the feet.

@Loki79 IDs need switched

**Comment by PikaFox** [comment]
Got feet from halsey

**Comment by Loki79** [comment]
Fixed.  Be in next maint.
