### ISSUE TITLE
Renik doesnt accept Amini Bottillons trade

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#369]
**Date & Time**: 10/8/15
**Frequency**: Always
**FFXI Client Version**: 30150730_1
**Character Name**: Tarot
**Race**: Hume
**Nation**: San
**Main Job**: Rng
**Sub Job**: Sam
**Area & Coordinates**: Upper Jeuno
**Party or Solo**: Solo
**NPC or Monster Name**: Renik 
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/27432/amini-bottillons-1
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: Trade Rem's Tales ch1 x5 and Amini Bottillons to Renik, does not accept trade and give Amini Bottillons +1. I have 5,000 Bayld
![tarot_2015 10 08_161021](https://cloud.githubusercontent.com/assets/12601727/10378598/c5801e7e-6dd7-11e5-81b5-8005bf800176.png)
![tarot_2015 10 08_161029](https://cloud.githubusercontent.com/assets/12601727/10378604/cc33557e-6dd7-11e5-9705-38fde2c8ff93.png)
![tarot_2015 10 08_161044](https://cloud.githubusercontent.com/assets/12601727/10378607/cf790abc-6dd7-11e5-89b0-a85b9391f618.png)

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
