### ISSUE TITLE
Unable to learn Horde Lullaby II

### ISSUE THREAD

**Issue by sumthingwong** [LegionDark/Issues#37]
Date & Time: 27.05.15 
Frequency: Repeated
FFXi Client Version: 30150508_5
Character Name: Sumthingwong
Race: Mithra
Main Job: BRD
Sub Job: DNC
Area & Coordinates Everywhere
Party or Solo: Solo
NPC Name: N/A
Monster Name: N/A
Steps To Reproduce The Issue:  Cant use the Song scroll Horde Lullaby II.
The archived bug showed this was Completed  a while back. But bug seem to be back.

http://www.legiondark.com/forums/viewtopic.php?f=32&t=304

**Comment by TeoTwawki** [comment]
Strange, I'll see wtf is up.

**Comment by TeoTwawki** [comment]
Corrected level requirement in database, spell is supposed to be lv92, was set lv99. This change will take effect during Legion's next maintenance.
