### ISSUE TITLE
Toau KI missing

### ISSUE THREAD

**Issue by adfasdaf** [LegionDark/Issues#370]
**Date & Time**: Oct 6 3PM
**Frequency**:1
**FFXI Client Version**:current
**Character Name**:Tron
**Race**:Elvaan
**Nation**:San d'Oria
**Main Job**:Nin
**Sub Job**:War
**Area & Coordinates**:Al Zahbi/Caedarva Mire
**Party or Solo**:solo
**NPC or Monster Name**:Naja Salaheem/Nareema
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:no
**Steps To Reproduce The Issue**:Toau Key item "Supplies Package" disappeared during mission.

**Comment by PikaFox** [comment]
Known issue and DSP issue, they borked ToAU missions substantially.

I have issued the KI in game to Tron.

**Comment by adfasdaf** [comment]
It is fixed. Thank you!

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
