### ISSUE TITLE
Turul Spawns in a non attackable state

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#371]
Date & Time: 10/10/2015, 03:00am
Frequency: Always
FFXI Client Version: 30150730_2 
Character Name: Aurel
Race: Hume
Main Job: Sam and Drk
Sub Job: Sam/Drk
Area & Coordinates: Abyssea - Konschtat
Party or Solo: Party or solo 
NPC Name:Turul
Monster Name: Turul
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:i need Redemption,NM Turul not work,...I just need  Redemption

**Comment by R3P0FFXI** [comment]
What?

**Comment by nekrol** [comment]
NM, Turul not appear, there is no way of attacking, there is a Turul but can not attack

**Comment by PikaFox** [comment]
Turul spawns in a state that he cannot be targetted/attacked on initial start of the server. Im assuming it thinks that he is in a flying state, thus not attackable, but since he doesnt agro he doesnt become targetable. Atm, despawning and spawning him via GM commands fixes him, i shall do that shortly, but the overall issue will need to be looked into by someone else.

**Comment by PikaFox** [comment]
Resolved Nekrol's issue; Turul spawning untargettable at server start is all thats left of this.

**Comment by nekrol** [comment]
thanks

**Comment by R3P0FFXI** [comment]
This may be do to Navmesh enabling as it did work prior to Navmesh escalating to Teo

**Comment by TeoTwawki** [comment]
@R3P0FFXI is form darkstar not resetting the animationSub state back to whats in the database on respawns, so whatever the value was when it was up last gets used, which doesn't match its actual state..and he gets stuck. I can fix it pretty fast when I get a chance.

**Comment by TeoTwawki** [comment]
ok so, I was working on this and kept getting sidetracked with voidwatch bugs and never fixed him. Since then, DSP fixed their end to reset the animationSub on repop proper, so whenever we finally catch up with them he should be already fixed.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
