### ISSUE TITLE
Terra Crystals not signing Truelove Chocolate / Love Chocolate

### ISSUE THREAD

**Issue by justaminigalka** [LegionDark/Issues#372]
**10/10/2015 9:03am PDT - 9:11am PDT**: 
**12 out of 12 tries**:
**Retail update with Version Fix**:
**Hikuzo**:
**Tarutaru**:
**San d'Oria**:
**Thief**:
**Dancer**:
**Lower Jeuno (h-9) & Lower Jeuno Mog House**:
**Party & Solo**:
**Love Chocolate / Truelove Chocolate**:
**http://www.ffxiah.com/item/5231/truelove-choco**: 
**Single Boxing. Wife plays on same server different computer. **:
**Synth multiple time in and out of mog house.  Even logged out and back in.**:

**Comment by justaminigalka** [comment]
So does anyone look into this, and if so do you ever let us know you are looking into this. an acknowledgement of investigation would be greatly appreciated.

**Comment by TeoTwawki** [comment]
asked r3 to check other recipes/signing xtal to see if its global dsp thing, and he hasn't had time yet + forgot to update issue with a label. He has a new kid and a dayjob, I been away sick + f'up my knee. rl happens

**Comment by TeoTwawki** [comment]
just fyi this likely will need corrected in dsp, not legion. gonna be a long while unless its just a db entry.

**Comment by justaminigalka** [comment]
alrighty. Im currently signing Ceremonial gear with no issues. and I signed lvl 1 copper ring no issues.  just that chocolate would not sign. 

Also, what is DSP? lol

**Comment by TeoTwawki** [comment]
DarkStar Project. https://github.com/DarkstarProject

they make teh server software legion run (with some modifications)

**Comment by justaminigalka** [comment]
aaaaaaaaaaaaah. :) thanks

**Comment by Kaoriasada** [comment]
I'm going to check if it's flagged inscribable in the database

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
