### ISSUE TITLE
Naja Salaheem

### ISSUE THREAD

**Issue by goferffxi** [LegionDark/Issues#373]
**Date & Time**:11/10/2015  @06:50 am GMT +0
**Frequency**:Constant
**FFXI Client Version**:30150730_1
**Character Name**:gofertwo
**Race**:hume
**Nation**:bastok
**Main Job**:whm
**Sub Job**:rdm
**Area & Coordinates**:aht urghan whitegate x 25 y -6 z -56 (116)
**Party or Solo**:solo or party
**NPC or Monster Name**:naja salaheem
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**:speak to naja to get quest/mission toau1 KI suppies order Cut scene plays and and KI mentioned in game text but no KI received or "received key item: supplies" dialogue

**Comment by PikaFox** [comment]
Known DSP issue, KI given to player in game.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
