### ISSUE TITLE
Unable to equip DNC af

### ISSUE THREAD

**Issue by adfasdaf** [LegionDark/Issues#374]
**Date & Time**: Mon 1am EST
**Frequency**:multiple
**FFXI Client Version**:Current
**Character Name**:Tron
**Race**:Elvaan
**Nation**:San d'Oria
**Main Job**:Dnc66
**Sub Job**:war33
**Area & Coordinates**:lower jeuno MH
**Party or Solo**:solo
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**:I received wrong gender equipment.

**Comment by PikaFox** [comment]
Assuming you figured this out; dancer is an odd case, and since all AF is unlocked, you can receive AF for both genders as two separate dancer categories.
