### ISSUE TITLE
missing mobs    

### ISSUE THREAD

**Issue by goferffxi** [LegionDark/Issues#375]
**Date & Time**: 
**Frequency**: constant
**FFXI Client Version**:30150730_1
**Character Name**:Gofer
**Race**:taru
**Nation**:bastok
**Main Job**:BLU
**Sub Job**:THF
**Area & Coordinates**:Abyessa Ulegurand Range   X: -77.482, Y: -176.000, Z: -2.609
**Party or Solo**:solo
**NPC or Monster Name**: Mechanical Menace
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:Yes Gofertwo WHM/RDM Hume
**Steps To Reproduce The Issue**:Enter area. All mechanical menace mobs are missing. Only Leviathan looking mob is in the area.

**Comment by Loki79** [comment]
Son of a bitch!  I have fixed this exact issue at least 3 times....

**Comment by Loki79** [comment]
These are correct in SQL.
