### ISSUE TITLE
Crafting: Argent gear

### ISSUE THREAD

**Issue by MissMaki** [LegionDark/Issues#376]
**Date & Time**: 1:43AM PST
**Frequency**: twice
**FFXI Client Version**: Retail
**Character Name**: Makira
**Race**: Hume
**Nation**: Sandy
**Main Job**: White Mage
**Sub Job**:Black Mage
**Area & Coordinates**:  Bastok Mines - K-7
**Party or Solo**: Solo
**NPC or Monster Name**: Irrelevent
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/16365/argent-hose
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Tried items to craft again, says combo of items can't be synthed

**Comment by MissMaki** [comment]
http://www.ffxiah.com/item/11310/argent-coat

Argent Coat is also not able to be synthed.

**Comment by R3P0FFXI** [comment]
I can confirm these are not coded, due to how busy we are this is not something that will be added anytime soon, for now you can buy the item off the AH

**Comment by MissMaki** [comment]
I wanted to sign them, haha. But that's okay =x thank you for responding.
