### ISSUE TITLE
~ Jailer of Fortitude ~ broken ?

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#377]
Date & Time:14/10/2015 ~23.00 GMT+1
Frequency: everytime
FFXI Client Version: 30150910_3
Character Name: thranduil
Race: hume
Nation: bastok
Main Job: rdm
Sub Job: whm
Area & Coordinates: The Garden of Ru'Hmet X: -434.100, Y: -0.500, Z: 697.849
Party or Solo: 2 pt alliance
NPC or Monster Name: Jailer of Fortitude
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): not me; others were multi-boxing.

Fought JoFort three times yesterday and noticed a wrong behavior: it's spawned and stayed in spheroid form all fight long, spamming Actinic Burst and occasionally Holy II, Prot&Shell V.
According to wiki it should be in humanoid form only and (à-la-colibrì) bounce back any spell cast on him until the 2 ghrahs minions are dead. 
Couldn't test if ranged atks were working; physical resistance and regen were as supposed to be.

**Comment by R3P0FFXI** [comment]
Assigning to Loki he is aware of the issue

**Comment by TeoTwawki** [comment]
@Loki79 @R3P0FFXI its the animation persisting between respawns. We can fix live with 1 line in `onMobSpawn()` in the mob script but once we catch up with DarkStar updates that shouldn't be needed anymore.

**Comment by R3P0FFXI** [comment]
Please reopen if issues persist after update
