### ISSUE TITLE
San D'Oria mission 3-1

### ISSUE THREAD

**Issue by adfasdaf** [LegionDark/Issues#378]
**Date & Time**: 10/15 3pm est
**Frequency**:multiple
**FFXI Client Version**:current
**Character Name**:Tron
**Race**:Elvaan
**Nation**:Sandy
**Main Job**:Samurai
**Sub Job**:Warrior
**Area & Coordinates**:Chateau d'Orihoweveryouspell it
**Party or Solo**:solo
**NPC or Monster Name**:Prince Trion
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:no
**Steps To Reproduce The Issue**:Accepted rank mission 3-1 from gate guard. Unable to get cutscene with Trion to progress the mission.

**Comment by PikaFox** [comment]
He still cannot complete the mission at all due to the prince also requiring a CS there again after the mission ends. That CS also appears to not be working for them.

**Comment by PikaFox** [comment]
Ended up being on Davoi Report and not Infiltrate Davoi. afaeatgeawh
