### ISSUE TITLE
NPC eats Amber-colored seal if you have Myrrh already

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#379]
**Date & Time**: 10/15/15
**Frequency**: Once
**FFXI Client Version**: 30150730_1
**Character Name**: Tarot
**Race**: Hume
**Nation**: San
**Main Job**: Drg
**Sub Job**: Sam
**Area & Coordinates**: Aht Urgan Whitegate
**Party or Solo**: Alliance
**NPC or Monster Name**: Sanraku (ID 16982564)
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/2595/myrrh
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: Have Myrrh in inventory, get KI again (Amber colored seal), get Myrrh from NPC again, it will eat the KI (and im assuming the zenni as well), even though it shouldnt complete the transaction. 

(Might happen to more ZNM pops with this NPC, not sure)

**Comment by TeoTwawki** [comment]
Welcome to the part Teo wasn't the dude who coded! :cry: 

May be some time before I can look at how to fix it in DSP.

**Comment by TeoTwawki** [comment]
actually..may have a live test with you shortly.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2270/files?w=1
