### ISSUE TITLE
Quivering Eft Egg does not drop

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#38]
**Date & Time**: 5/31/15
**Frequency**: Always
**FFXI Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: NA
**Main Job**: NA
**Sub Job**: NA
**Area & Coordinates**: Abys Tahrongi
**Party or Solo**: NA
**NPC Name**: NA
**Monster Name**: NA
**Steps To Reproduce The Issue**: Legiondark Mob tool doesnt list Quivering Eft Egg as a drop, egg is needed to pop an NM that eventually leads up to zone boss.

According to ffxiclopedia, egg is 100% drop rate. 

http://ffxiclopedia.wikia.com/wiki/Quivering_Eft_Egg

**Comment by Loki79** [comment]
be in next maint restart.
