### ISSUE TITLE
Case of the Missing Knife!

### ISSUE THREAD

**Issue by vashzx1** [LegionDark/Issues#381]
**Date & Time**: 10:32PM
**Frequency**: All the time!
**FFXI Client Version**: 30150910_3
**Character Name**: Hisoka
**Race**: Mithra
**Nation**: Bastok
**Main Job**: Blu
**Sub Job**: dnc
**Area & Coordinates**: mog house in bastok mines x0 y0 z0 (192)
**Party or Solo**:solo
**NPC or Monster Name**:Thief's knife?
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:no
**Steps To Reproduce The Issue**:its gone using the /find addon from ashita it says its in my mog wardrobe and its in my case... which is impossible to have 2 and my case has 0 items in it my wardrobe has 15

**Comment by TeoTwawki** [comment]
@LegionDark/owners I had him open the ticket and planned to nuke both knives and just give him a knew one, but the database claims its in location 8 slot zero, and that there is only one of it. But damned if I know wtf location 8 even is!

**Comment by TeoTwawki** [comment]
@R3P0FFXI back at you - I have no idea what more I can do about this. Without a demonstration to make it happen on purpose, I have no idea what is happening or how to prove it.

**Comment by TeoTwawki** [comment]
DarkStar says the location value should reflect the actual container ID.
https://github.com/DarkstarProject/darkstar/blob/acc412775a127c4e1f84d8f50908d23a491a37dc/src/map/item_container.h#L38

**Comment by Kaoriasada** [comment]
@TeoTwawki Do I need to try and give this to him?

**Comment by TeoTwawki** [comment]
Nope, database says he already has it so doing the GM command will fail.

**Comment by Kaoriasada** [comment]
@TeoTwawki it's not possible that once the server is up to date with his client that it will reappear?

**Comment by TeoTwawki** [comment]
@Kaoriasada  Inventory related packets didn't change that I am aware of, so not a version thing.

**Comment by Kaoriasada** [comment]
@TeoTwawki ok, just let me know if there's anything I can do.

**Comment by vashzx1** [comment]
So basically am i screwed?

**Comment by TeoTwawki** [comment]
@vashzx1 get with me in IRC

**Comment by TeoTwawki** [comment]
Got him fixed, and I think I figured out how it turned invisible. Closing issue and will talk in admin channel on irc when ppl are around.
