### ISSUE TITLE
CoP 3-3 the Road forks Initail CS not starting

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#383]
**Date & Time**: 10/17/2015 10:03
**Frequency**: Always
**FFXI Client Version**:30150730_2
**Character Name**: Jukebox
**Race**: Mithra
**Nation**: Sandy
**Main Job**: Brd
**Sub Job**: Dnc
**Area & Coordinates**: North sandy X:0 Y:0 Z-30 (200)
**Party or Solo**: Both
**NPC or Monster Name**: N/a
**ffxiah.com link (for inventory items only)**: N/a 
**Multi-boxing? (multiple clients on same connection)**: Yes & No
**Steps To Reproduce The Issue**: At first I thought this was the dual-box bug so Logged off all character and only logged in Juke, Still CS will no start. the prvious CS 3-2 on the stairs to the Audience Chamber will repeat.

**Comment by Baucant** [comment]
You guys either worked very fast on this or something finally stuck with the last CS cause it's working now and I'm closeing the ticket

**Comment by TeoTwawki** [comment]
DSP code being random with you. /shrug
