### ISSUE TITLE
PM8-3 not initializing CS for access to battle field

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#384]
**Date & Time**: 10/18/2015 11:40
**Frequency**: ALways
**FFXI Client Version**:30150730_2
**Character Name**:Jukebox
**Race**:Mithra
**Nation**:Sandy
**Main Job**:BRD
**Sub Job**:DNC
**Area & Coordinates**: The Garden of Ru'Hmet X:419 Y:0 Z:398 (191)
**Party or Solo**: Both
**NPC or Monster Name**:Partical Gate
**ffxiah.com link (for inventory items only)**:N/A
**Multi-boxing? (multiple clients on same connection)**: yes and no
**Steps To Reproduce The Issue**: I have aquired both "Brand of Dawn" and "Brand of Dusk" KIs, Game confirmed on elevatore ride to the 3rd floor. I tried loging out, zoning, re-aquiring both brands withought my alts on. I have tried accessing the door with and without my alts.

**Comment by PikaFox** [comment]
DId you get the light for your race? (climb the race tower)

**Comment by Baucant** [comment]
Thats something that must have been fixed I know when I took my other 2 char through I didn't have to go to the 2 differnt towers
