### ISSUE TITLE
Supplies package problem

### ISSUE THREAD

**Issue by Bruce101** [LegionDark/Issues#386]
**Date & Time**:  October 12 2015
**Frequency**:  Once
**FFXI Client Version**:  30150730.1
**Character Name**:  Bruce
**Race**: Elvaan
**Nation**: Bastok
**Main Job**:Blm
**Sub Job**: mnk
**Area & Coordinates**: Whitegate I-10
**Party or Solo**: Solo
**NPC or Monster Name**: Naja Salaheem
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Tried zoning and logging, she doesn't talk to me anymore after saying to take the package to a guard. Didn't get the KI Supplies Package for ToAU 1

**Comment by PikaFox** [comment]
Gave player KI, should be able to complete this mission now. Other than that, confirmed DSP bug with our current version as the label states.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
