### ISSUE TITLE
Bastok 2-3

### ISSUE THREAD

**Issue by Bruce101** [LegionDark/Issues#387]
**Date & Time**:  Oct 12 2015
**Frequency**:  Once
**FFXI Client Version**:  30150730.1
**Character Name**: Bruce
**Race**: Elvaan
**Nation**: Bastok
**Main Job**: Blm
**Sub Job**: Mnk
**Area & Coordinates**:  Chateau d'Oraguille I-9
**Party or Solo**: Solo
**NPC or Monster Name**: Halver
 **ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Tried loging/zoning to get him to talk but no luck. I got the Windy part done just fine, went to embassy in Sandy, got the CS with Lion, NPC Melek no longer says anything, and Halver didn't talk to continue the mission. Touching the burning circle in Horlais Peak does nothing.

**Comment by PikaFox** [comment]
Got him to progress.
