### ISSUE TITLE
Duelwielding but not attacking with offhand!

### ISSUE THREAD

**Issue by vashzx1** [LegionDark/Issues#389]
Date & Time: 10-19 12:17am
Frequency:often
FFXI Client Version:30150910_3
Character Name:Hisoka
Race:mithra
Nation:bastok
Main Job:blu
Sub Job:dnc
Area & Coordinates: pashhow mashlands (s)
Party or Solo:solo
NPC or Monster Name:peiste
ffxiah.com link (for inventory items only): MainHand:http://www.ffxiah.com/item/21125/tamaxchi
Offhand:http://www.ffxiah.com/item/16630/striker-sword
Multi-boxing? (multiple clients on same connection):No
Steps To Reproduce The Issue:
Tamaxchi was mainhand and striker is offhand for some reason both weapons are out but the offhand wont attack.

**Comment by Kaoriasada** [comment]
These SHOULD be fixed...if they aren't when Loki includes the stuff I sent him next maintenance, I'll look further into it.
