### ISSUE TITLE
Mission 5-1

### ISSUE THREAD

**Issue by melman429** [LegionDark/Issues#39]
**Date & Time**: 5/30 1am est
**Frequency**: n.a.
**FFXI Client Version**: _8
**Character Name**: melman
**Race**:hume
**Main Job**:blm
**Sub Job**:rdm
**Area & Coordinates**: 5-1 bcnm fight
**Party or Solo**:solo
**Monster Name**: Archlich Taber'quoan
**Steps To Reproduce The Issue**:
entered fight and although its supposed to be capped at 99 i was unable to use my spells. like the level wasn't capped but my spell list was. and when i died it had a funny transition and gave me the cs with zied and gave me the burnt seal like i beat the bcnm.

**Comment by R3P0FFXI** [comment]
This fight is capped at 50 its old school, Wiki is a guide not the exact settings on the server

**Comment by R3P0FFXI** [comment]
Please advise if this is still an issue or if you have advanced past 5-1

**Comment by R3P0FFXI** [comment]
Last Chance will give 24 hours for a response if no response in 24 hours I am closing this ticket

**Comment by R3P0FFXI** [comment]
No response from user closing issue.
