### ISSUE TITLE
Animated great axe not dropping seraphic fragment, this seems to happen to the longbow one too.

### ISSUE THREAD

**Issue by southmonk** [LegionDark/Issues#390]
**Date & Time**: 20/10/2015   12:03am
**Frequency**:  twiece so far
**FFXI Client Version**:  30150730_1
**Character Name**: southmonk
**Race**: galka
**Nation**: bastok
**Main Job**: war
**Sub Job**: dnc
**Area & Coordinates**: dynamix xarcabard i7 animated great axe location
**Party or Solo**: party once solo once
**NPC or Monster Name**: Animated great axe
**ffxiah.com link (for inventory items only)**:  http://ffxiclopedia.wikia.com/wiki/Seraphic_Fragment
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: kill animated gaxe
![southmonk_2015 10 19_235848](https://cloud.githubusercontent.com/assets/15199995/10584820/5ca2c47a-76be-11e5-92af-dd16de438a3c.png)

**Comment by PikaFox** [comment]
Did you kill all the eyes/NMs on the steps?

All fragments have a 0% chance (which equates to a 1% chance or something like that because of coding) to drop if you havnt cleared out all the proper NMs to release the souls in dynamis.

**Comment by southmonk** [comment]
oops i didnt kill the nms and eyes on steps, will try this later

**Comment by R3P0FFXI** [comment]
Please advise when retested properly

**Comment by PikaFox** [comment]
Make sure you dont 1shot the eyes before they spawn the NMs as well.

**Comment by simthra** [comment]
I'll add some info: did a xarc-fragments run yesterday; got the drops from every animated weapon after having killed the 15 NMs.

**Comment by R3P0FFXI** [comment]
Closing issue
