### ISSUE TITLE
Magus Keffiyeh +1 Sagheera won't return gear

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#391]
**Date & Time**: 10/21/2015 7:17 am
**Frequency**:everytime I talk to her
**FFXI Client Version**:30150730_2
**Character Name**: Baucant
**Race**: Elvaan
**Nation**: Sandy
**Main Job**: Blu
**Sub Job**: Rdm
**Area & Coordinates**: Port Jeuno
**Party or Solo**: Solo
**NPC or Monster Name**: Sagheera
**ffxiah.com link (for inventory items only)**: http://ffxiclopedia.wikia.com/wiki/Magus_Keffiyeh_%2B1 
**Multi-boxing? (multiple clients on same connection)**: not at this time
**Steps To Reproduce The Issue**: Trade the ABC first then the 4items to Upgrade Artifate from NQ to +1 came back next game day. Sagheera say nothing about my gear. I tried zone, relogging with no results

**Comment by R3P0FFXI** [comment]
This is most likely going to be a DSP issue as they maintain the limbus NPC's

**Comment by Baucant** [comment]
So am I just screwed out my AF+1 and reforged Artifact on blu or is there a work around?

**Comment by R3P0FFXI** [comment]
We will have to look into it further

**Comment by Baucant** [comment]
ok that's wierd I came back a few hours later and she gave me the item

**Comment by PikaFox** [comment]
DSP likely has this set to JP midnight or so still.
