### ISSUE TITLE
Key item : Supplies package from Mission ToAU

### ISSUE THREAD

**Issue by djaffa** [LegionDark/Issues#392]
Hello, 

Doing Mission for ToAU and didn't received the KI Supplies package with my 2 char
LS told me to do a bug report to fix it

http://ffxiclopedia.wikia.com/wiki/Supplies_Package

Character Name : Djaffa
Character Name : Arutai

Thanks a lot for your help and your great job :)

**Comment by PikaFox** [comment]
For future reference please use this bug template:

**Date & Time**: 
**Frequency**:
**FFXI Client Version**:
**Character Name**:
**Race**:
**Nation**:
**Main Job**:
**Sub Job**:
**Area & Coordinates**:
**Party or Solo**:
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**:

It can be found here: https://github.com/LegionDark/Issues/

**Comment by PikaFox** [comment]
Gave both chars the KI, known issue with our current build off DSP, just use the bug template in the future.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
