### ISSUE TITLE
ashen KI cant UP to ashen II 

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#394]
Date & Time: 10/22/2015
Frequency: constantly
FFXI Client Version: 30150730_2
Character Name:Qigang
Race: Elv
Nation: Sand
Main Job: BLU
Sub Job: RDM
Area & Coordinates:No
Party or Solo: party
NPC or Monster Name: Kieran
ffxiah.com link (for inventory items only): n/a
Multi-boxing? (multiple clients on same connection): yes 

Kill 6nms talked Norg Kieran  noting 
We both played a couple of times, and we didn't react to 6NM.

**Comment by qiganggang** [comment]
can you log in check my quest ? need kill what nm? I think it's the monster that has no record.

**Comment by nekrol** [comment]
Date & Time: 26/10/2015, 1100am
Frequency: Always
FFXI Client Version: 30150730_2
Character Name: Aurel -Cassy
Race: Hume
Main Job: Blu-Thf
Sub Job: Rdm-dnc
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name: Kieran
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:after hi, 2 times and killed all NM , Kieran CS not not up KI ASHEN

**Comment by qiganggang** [comment]
![Uploading QQ图片20151026210356.png…]()
![Uploading QQ图片20151026210402.jpg…]()

**Comment by qiganggang** [comment]
Quicksand caves  VWNM  Malleator Maurok   NO byld and exp  this bug@!!!!!!!!!!!!!!!! please check it

**Comment by TeoTwawki** [comment]
Needs more exclamation marks.

**Comment by TeoTwawki** [comment]
@nekrol you never flagged the quests you were supposed to, same problem you had last time. ACTUALLY SPEAK TO THE NPCs. Its not just Keiran. There are THREE.

@qiganggang I fixed Malleator Maurok but have not had a chance to check your quest status and variables yet.

**Comment by TeoTwawki** [comment]
@PikaFox when He's on next do this: 
`@checkquest 5 102  Qigang` 
`@checkvar Qigang VW_OP_101` 
`@checkvar Qigang ASHEN_STRATUM`
And tell me results of each.

**Comment by nekrol** [comment]
Hello , I followed the steps and all the quest WIKI and is sure to talk to the NPC , they are now doing the same thing twice , -----Speak to Kieran in Norg (I-8) to receive a cutscene and the key item Ashen stratum abyssite.
Speak with the following NPCs to begin their respective quests:
Hildegard in Kazham (F-9) to begin VW Op. 054: Elshimo List
Gushing Spring in Rabao (G-8) to begin VW Op. 101: Detour to Zepwell
Complete both of these quests and return to Kieran to complete the quest.

**Comment by nekrol** [comment]
Important: Before you start any Tier I fights, speak with Gushing Spring in Rabao and Hildegard in Kazham first and """""select to participate in Voidwatch! ------->>>>this option does not appear cn me the NPC

**Comment by TeoTwawki** [comment]
@nekrol tried to talk to you in game but got no response. Go see Gushing Spring again. Your bugged characters should get a cs with him now.

**Comment by TeoTwawki** [comment]
@qiganggang manually fixed you in database

**Comment by TeoTwawki** [comment]
@qiganggang there was a server crash shortly after I did this, and now I don't know your status. If you have any more issue please let me know when a good time to catch you in game is.
