### ISSUE TITLE
Missing Woodworking Recipe: Vermihumus

### ISSUE THREAD

**Issue by neuromancerxi** [LegionDark/Issues#395]
**Date & Time**: 2015-10-22 ~12:45 PM Pacific
**Frequency**: Repeatable
**FFXI Client Version**: 30150910_3
**Character Name**: Neuromancer
**Race**: Taru
**Nation**: Sando
**Main Job**: WAR
**Sub Job**: MNK
**Area & Coordinates**: N/A
**Party or Solo**: Solo
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/17894/vermihumus
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: 

Woodworking recipe for Vermihumus appears to be missing / unusable. Tried Dark Crystal + 2x Humus, "Synthesis canceled. That combination of materials cannot be synthesized."

**Comment by Kaoriasada** [comment]
@R3P0FFXI add this into the crafting overhaul and I'll make sure the item is coded

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
