### ISSUE TITLE
Bard Relic Horn (Gjallarhorn) Valey Sorrow Blank target.

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#396]
Date & Time: 10/23/2015
 Frequency: constantly
 FFXI Client Version: 30150910_3
 Character Name:Dimasp
 Race: Tarutaru
 Nation: Sand'Oria
 Main Job: BRD
 Sub Job: WHM
 Area & Coordinates:No
 Party or Solo: 
 NPC or Monster Name: Blank target (Valey Sorrow)
 ffxiah.com link (for inventory items only): n/a
 Multi-boxing? (multiple clients on same connection): no

I got last starge from Relic weapon (Gjallarhorn) done items, but i can follow because i can't see the blank target in some spot talked, so i need some help...

I am in posses follow items: 1 Millennium horn, 1 Shard os necropsyche, 1 Mysterial Fragment and 1 Rimilala stripeshell.

**Comment by Kaoriasada** [comment]
If I log on and it's there, I'm having Loki link your HP to VE.  >:(

In all seriousness I'll log on and check this in a few hours.

**Comment by R3P0FFXI** [comment]
You updated your FFXI client FFXI Client Version: 30150910_3 the current version the server is running on is 30150730_1

**Comment by R3P0FFXI** [comment]
Issue resolved with last maint
