### ISSUE TITLE
Ab`xzomit Perma Hundred fist

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#397]
**Date & Time**: 10/23/2015 8:38 am
**Frequency**: always
**FFXI Client Version**: 30150730_2
**Character Name**: Baucant
**Race**: Elvaan
**Nation**: Sandy
**Main Job**: Blu
**Sub Job**: nin
**Area & Coordinates**: Abyssea- Konschtat X:-430 Y:15 Z: 182 (30)
**Party or Solo**: Party
**NPC or Monster Name**: Ab`xzomit
**ffxiah.com link (for inventory items only)**: n/a
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**: Fought many of the mobs all seem to have a perma Hundred fist or attack delay of 0

**Comment by R3P0FFXI** [comment]
Please retest and see if issue is still occuring

**Comment by TeoTwawki** [comment]
@R3P0FFXI remember that big ol list of mobs that needed a delay value set in the database? This is one of them. Its not gonna be effected by version update. I'm pushing the fix for this 1 mob right now and closing this.

**Comment by TeoTwawki** [comment]
Change will take effect next time map server reloads

**Comment by Baucant** [comment]
Checled this mob today after server crash. ...still has perma hundredred fist / 0 delay

**Comment by TeoTwawki** [comment]
Fixed my typo that caused my 1st fix to fail. >.>
