### ISSUE TITLE
Hoary Ragwort perma Hundred fist

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#398]
**Date & Time**: 10/23/2015 8:38 am
**Frequency**: always
**FFXI Client Version**: 30150730_2
**Character Name**: Baucant
**Race**: Elvaan
**Nation**: Sandy
**Main Job**: Blu
**Sub Job**: nin
**Area & Coordinates**: Abyssea- Konschtat X:-458 Y:7 Z:-56 (124)
**Party or Solo**: Party
**NPC or Monster Name**: Hoary Ragwort
**ffxiah.com link (for inventory items only)**: n/a
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**: Fought many of the mobs all seem to have a perma Hundred fist or attack delay of 0

**Comment by R3P0FFXI** [comment]
Please retest and see if issue is still occuring

**Comment by TeoTwawki** [comment]
Will be fixed next time map server loads

**Comment by Baucant** [comment]
checked this mob after server crash today...all seems well
