### ISSUE TITLE
Anchorite's Crown not Enhances "Focus" effect potency to +35 Accuracy.

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#399]
Date & Time: 24/10/2015, 03:00am
Frequency: Always
FFXI Client Version: 30150730_2 
Character Name: Aurel
Race: Hume
Main Job: monk
Sub Job: dnc
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name:
Monster Name: 
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:Anchorite's Crown not Enhances "Focus" effect potency to +35 Accuracy.

**Comment by nekrol** [comment]
Chakra in monk not work properly ,i have 129 vit +99 vit and Anchorite's Cyclas AF +  Hesychast's gloves AF and recovery 464 hp

**Comment by R3P0FFXI** [comment]
Mod for Enhance Chakra does not exist nothing we can do about this right now

**Comment by TeoTwawki** [comment]
Thats not an augment, wrong label. This isn't a todo - has to be coded in dsp.
