### ISSUE TITLE
Fistule 20% 10% 5%   

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#40]
**Date & Time**:  31/05/2015
**Frequency**:  
**FFXi Client Version**: 30150508_5
**Character Name**: bathuka
**Race**:
**Main Job**:
**Sub Job**:
**Area & Coordinates abyssea konchtat
**Party or Solo**:
**NPC Name**: 
**Monster Name**: FISTULE 
**Steps To Reproduce The Issue**:  HE DO NOT DROPP ONe FISTUDE DISCHARGE 100%

**Comment by Loki79** [comment]
Fixed be in with Maint Tuesday.
