### ISSUE TITLE
Player Morgoth unable to learn Barbed Crescent

### ISSUE THREAD

**Issue by iMorgoth** [LegionDark/Issues#400]
**Date & Time**: 10/24/15   0800 EST-1600 EST
**Frequency**:  30-40 kills when mobs used move and increasing
**FFXI Client Version**: 30150730_2
**Character Name**: Morgoth
**Race**: Hume
**Nation**: Bastok
**Main Job**: BLU 99
**Sub Job**: NIN 49
**Area & Coordinates**: Wajoam Woodlands K-7
**Party or Solo**: Solo
**NPC or Monster Name**: Fomors
**ffxiah.com link (for inventory items only)**: NA
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Tried other mobs listed with BLU tool with no success. Other players having same difficulty.

**Comment by PikaFox** [comment]
Only available off of the shadow NMs in Fei'Yin. Learned on mob death at a % chance.

**Comment by PikaFox** [comment]
Reply back stating if you obtained the spell from the mobs specified. It is a % chance still, so might take a few kills, but this should still be the case.

**Comment by TeoTwawki** [comment]
Dev note: there is an adjustment in the pipes that will allow it to be learned normally, but that is a ways off.

**Comment by iMorgoth** [comment]
Thank you for the response. It worked, and I was able to learn the spell.
