### ISSUE TITLE
all Tier4 voidwatch bugged

### ISSUE THREAD

**Issue by maikuru23** [LegionDark/Issues#401]
**Date & Time**:  10/24/2015 8:30PM PST
**Frequency**:  Always
**FFXI Client Version**:  30150730_2
**Character Name**:  Maiku
**Race**:  Taru
**Nation**:  Bastok
**Main Job**: WAR
**Sub Job**:  SAM
**Area & Coordinates**:  Dangruf Wadi (H-4)
**Party or Solo**: Party
**NPC or Monster Name**: Planar Rift/Celaeno
**ffxiah.com link (for inventory items only)**:  n/a
**Multi-boxing? (multiple clients on same connection)**: yes, but not a multibox issue.  Others on server having same issue
**Steps To Reproduce The Issue**:
1. go to dangruf wadi H-4
2. click planar rift and commence voidwatch operation for T4 bastok
3. use stone
4. pop celaeno
5. mob goes invisible but you can still attack. 
6. we get its HP to 60% and it despawns
7. lost 2 stones and mob will not stay there long enough to kill.
8. all Tier4 VW bugged (confirmed by multiple groups this happens on all T4 city)

**Comment by TeoTwawki** [comment]
variable was set wrong at mob spawn..
