### ISSUE TITLE
Can't Equip Nahtirah Trousers

### ISSUE THREAD

**Issue by swlong82** [LegionDark/Issues#402]
**Date & Time**: 25 October 2015
**Frequency**: Tried a few times after relogging as well
**FFXI Client Version**: 30150730_1
**Character Name**: Lockie
**Race**: Taru
**Nation**: Bastok
**Main Job**: Thief or Ranger
**Sub Job**: Dancer
**Area & Coordinates**: Mog House
**Party or Solo**: Solo / Party
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/28197/nahtirah-trousers
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Tried to Equip on Thief or Ranger. It doesn't equip, and just maintains existing piece (doesn't actually unequip).

1. Attempting To Equip
![lockie_2015 10 25_224102](https://cloud.githubusercontent.com/assets/15011219/10716128/85d70bbc-7b69-11e5-833f-b8f76dc46b3f.png)

2. Nothing Changes
![lockie_2015 10 25_224128](https://cloud.githubusercontent.com/assets/15011219/10716131/9364413c-7b69-11e5-851c-43f833b0290c.png)

**Comment by Kaoriasada** [comment]
It's equip-able on COR, PUP, and DNC.  Guessing that this is a job mask issue.  I'll look into it.

**Comment by Kaoriasada** [comment]
Job mask was set as 5187652, correct value is 496674 without Rune Fencer, 2593826 with Rune Fencer.  I'll send this into Loki with the rest of my stuff.

**Comment by R3P0FFXI** [comment]
Send it with Run in the event Run actually ever gets coded

**Comment by Kaoriasada** [comment]
Sent to Loki, should be in next update, closing issue.  I did add the Rune Fencer.  I added RUN and GEO into all the job masks I fixed.
