### ISSUE TITLE
Regal Pumps +1 (VW boots can;'t put them on)

### ISSUE THREAD

**Issue by slaggyt** [LegionDark/Issues#403]
**Date & Time**: October 1 2015
**Frequency**: All the time
**FFXI Client Version**: 30150730_1
**Character Name**:Imalion
**Race**:Mithra
**Nation**:Bastok
**Main Job**:WHM
**Sub Job**:RDM
**Area & Coordinates**:All
**Party or Solo**: Both
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**:  http://www.ffxiah.com/item/28274/regal-pumps-1
**Multi-boxing? (multiple clients on same connection)**: Both
**Steps To Reproduce The Issue**: Tried equipping in different zones

**Comment by R3P0FFXI** [comment]
https://github.com/LegionDark/Issues/issues/336 Dusplicate ticket will be fixed next maint
