### ISSUE TITLE
shadow ring

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#405]
Date & Time: 26/10/2015
Frequency:
FFXI Client Version: 30150730_2
Character Name: bathuka
Race: elvaan
Nation: sandy
Main Job: pld
Sub Job: nin
Area & Coordinates:
Party or Solo: party
NPC or Monster Name:
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): 
**i want know if the shadow ring is script i have test it and i have never occassionnaly annul magic dmg taken** tks

for info dynamislord pop
http://img11.hostingpics.net/pics/212071Bathuka20151025234423.png

**Comment by Kaoriasada** [comment]
INSERT INTO `item_mods` VALUES (14646,255,5); Shadow Ring, MOD_DEATHRES, +5

The nullify magic damage taken and magic defense bonus on Darksday is not coded.

**Comment by bathuka** [comment]
ok super tks

**Comment by R3P0FFXI** [comment]
This is working as intended the missing mods are NOT coded

**Comment by TeoTwawki** [comment]
MOD_MAGIC_NULL = 476
right in status.lua.

**Comment by Kaoriasada** [comment]
Next time I send items into Loki I will add this to the ring then :-)

**Comment by bathuka** [comment]
ohhh perfect

**Comment by R3P0FFXI** [comment]
Teo thats not correct the Mod Magic Null = 476 is 100% the Shadow Ring is Darksday only .. On Darksdays: "Magic Def. Bonus"

**Comment by TeoTwawki** [comment]
Latents aren't mods.

I read "nullify magic damag" which is what that modifier does.

**Comment by TeoTwawki** [comment]
`Occasionally annuls magic damage taken` <- ok, R3 is right that mod won't do because it'd be every time
`Enhances resistance against "Death"` <- we got that
`On Darksdays: "Magic Def. Bonus"` <- needs to be latent, thought it'd be in but don't see it in DSPs file https://github.com/DarkstarProject/darkstar/blob/master/sql/item_latents.sql and doubt we did it in a custom file

**Comment by TeoTwawki** [comment]
-*mumble*s-  y'all making me actually research thinsg n' stuff.  -*mutters*-

**Comment by TeoTwawki** [comment]
GAH! no, I was right the first time guys. That IS the right mod for nulling magic damage, the value is used as the proc rate. MOD_MAGIC_NULL at 10 = 10% chance of nulling.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/blob/0e302c2f2977258fe4ac77a558065df4386f46f0/src/map/utils/battleutils.cpp#L4330

**Comment by TeoTwawki** [comment]
So both this and the mantle can in fact be fully coded. Lets get them into DSP so we don't have to maintain it after it works.

**Comment by R3P0FFXI** [comment]
Please reopen if issues persist after update
