### ISSUE TITLE
shadow mantle

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#406]
Date & Time: 26/10/2015
Frequency:
FFXI Client Version: 30150730_2
Character Name: bathuka
Race: elvaan
Nation: sandy
Main Job: pld
Sub Job: nin
Area & Coordinates:
Party or Solo: party
NPC or Monster Name:
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): 
**i want know if the shadow mantle is script i have test it and i have never occassionnaly annul physical dmg taken** tks 
**the vit+20 on darkdays do not work**

for info dynamislord pop
http://img11.hostingpics.net/pics/212071Bathuka20151025234423.png

**Comment by Kaoriasada** [comment]
INSERT INTO `item_mods` VALUES (13658,1,15);  --  Shadow Mantle, MOD_DEF, +15
INSERT INTO `item_mods` VALUES (13658,416,15);  --  SHADOW MANTLE, MOD_NULL_PHYSICAL_DAMAGE, +15

**Comment by bathuka** [comment]
very nice :)

**Comment by R3P0FFXI** [comment]
This is working as intended the missing mods are NOT coded

**Comment by TeoTwawki** [comment]
Note: that'd be in item Latents, not item Mods. Latent for dakrsday does exist.

**Comment by bathuka** [comment]
+20 vit all time np XD

**Comment by R3P0FFXI** [comment]
Please reopen if issues persist after update
