### ISSUE TITLE
Password reset request

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#407]
Date & Time: 10/23/2015
 Frequency: constantly
 FFXI Client Version: 30150910_3
 Character Name:Dimma
 Race: Hume
 Nation: Sand'Oria
 Main Job: BLU
 Sub Job: RDM
 Area & Coordinates:No
 Party or Solo: 
 NPC or Monster Name: Qullin
 ffxiah.com link (for inventory items only): n/a
 Multi-boxing? (multiple clients on same connection): no

I lent my acc to a friend play, but he used my account to pop Qullin and I lost my key item, please I ask them to reset my password charaters of Dimma and Dimasp.

Thank you

**Comment by R3P0FFXI** [comment]
Per discussion with user only a Password reset will be performed, we will not reimburse the lost KI user will need to clear NM again.

**Comment by R3P0FFXI** [comment]
Password has been reset to requested variables
