### ISSUE TITLE
ashen KI cant UP to ashen II

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#408]
Date & Time: 27/10/2015, 1100am
Frequency: Always
FFXI Client Version: 30150730_2
Character Name: Aurel -Cassy
Race: Hume
Main Job: Blu-Thf
Sub Job: Rdm-dnc
Area & Coordinates: Kazham (F-9)--Rabao---Norg
Party or Solo: Party or solo
NPC Name: Kieran-Hildegard-Gushing Spring
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:after ,3 cs and got the 3 NPCs ---- but not working my key item----ashen KI cant UP to ashen II---Issue Closed #394 for more information

**Comment by nekrol** [comment]
Date & Time: 10/22/2015
Frequency: constantly
FFXI Client Version: 30150730_2
Character Name:Qigang
Race: Elv
Nation: Sand
Main Job: BLU
Sub Job: RDM
Area & Coordinates:No
Party or Solo: party
NPC or Monster Name: Kieran
ffxiah.com link (for inventory items only): n/a
Multi-boxing? (multiple clients on same connection): yes

Kill 6nms talked Norg Kieran noting 
We both played a couple of times, and we didn't react to 6NM.

**Comment by TeoTwawki** [comment]
There is no reason you couldn't reply on the closed issue.

**Comment by TeoTwawki** [comment]
I'm in game right now looking for you -_-

**Comment by nekrol** [comment]
login

**Comment by TeoTwawki** [comment]
Effing crashed out
