### ISSUE TITLE
~ Artifact/Relic armor reforge ~ TRADE isn't working

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#410]
Date & Time: 10/27/2015 19.00 GMT+1
Frequency: everytime
FFXI Client Version: 30150910_3
Character Name: Thranduil
Race: Hume
Nation: Bastok
Main Job: rdm
Sub Job: dnc
Area & Coordinates: Port Jeuno (H-8) X:-52 Y:0 Z:-8
Party or Solo: solo
NPC or Monster Name: armor reforge Custom Moogle
ffxiah.com link : http://www.ffxiah.com/item/26632/vitivation-chapeau
Multi-boxing?: no

"20 Aptants of Durus  & Duelist chapeau +2" > Vitivation Chapeau 
The trade isn't working; CoP and Zilart done. Thank you.

**Comment by simthra** [comment]
Date & Time: 10/27/2015 19.00 GMT+1
Frequency: everytime
FFXI Client Version: 30150910_3
Character Name: Thranduil
Race: Hume
Nation: Bastok
Main Job: rdm
Sub Job: dnc
Area & Coordinates: Port Jeuno (H-8) X:-52 Y:0 Z:-8
Party or Solo: solo
NPC or Monster Name: armor reforge Custom Moogle
ffxiah.com link : http://www.ffxiah.com/item/27811/atrophy-tabard
Multi-boxing?: no

"25 Aptants of fyrsy & Warlock's tabard+1 " > Atrophy Tabard
The trade isn't working; CoP and Zilart done. Thank you.

**Comment by simthra** [comment]
Date & Time: 10/27/2015 19.00 GMT+1
Frequency: everytime
FFXI Client Version: 30150910_3
Character Name: Thranduil
Race: Hume
Nation: Bastok
Main Job: rdm
Sub Job: dnc
Area & Coordinates: Port Jeuno (H-8) X:-52 Y:0 Z:-8
Party or Solo: solo
NPC or Monster Name: armor reforge Custom Moogle
ffxiah.com link : http://www.ffxiah.com/item/27947/atrophy-gloves
Multi-boxing?: no

"20 Aptants of geoc & Warlock's gloves+1 " > Atrophy gloves
The trade isn't working; CoP and Zilart done. Thank you.

**Comment by simthra** [comment]
Date & Time: 10/27/2015 19.00 GMT+1
Frequency: everytime
FFXI Client Version: 30150910_3
Character Name: Thranduil
Race: Hume
Nation: Bastok
Main Job: rdm
Sub Job: dnc
Area & Coordinates: Port Jeuno (H-8) X:-52 Y:0 Z:-8
Party or Solo: solo
NPC or Monster Name: armor reforge Custom Moogle
ffxiah.com link : http://www.ffxiah.com/item/27160/vitivation-tights
Multi-boxing?: no

"20 Aptants of haelan & Duelist's tights +2 " > Vitivation tights
The trade isn't working; CoP and Zilart done. Thank you.

**Comment by simthra** [comment]
Date & Time: 10/27/2015 19.00 GMT+1
Frequency: everytime
FFXI Client Version: 30150910_3
Character Name: Thranduil
Race: Hume
Nation: Bastok
Main Job: rdm
Sub Job: dnc
Area & Coordinates: Port Jeuno (H-8) X:-52 Y:0 Z:-8
Party or Solo: solo
NPC or Monster Name: armor reforge Custom Moogle
ffxiah.com link : http://www.ffxiah.com/item/27336/vitivation-boots
Multi-boxing?: no

"20 Aptants of ishis & Duelist's boots +2 " > Vitivation boots
The trade isn't working; CoP and Zilart done. Thank you.

**Comment by PikaFox** [comment]
Iirc aptants are traded to moogles in tavnasian safehold, bottom floor, try there.

**Comment by TeoTwawki** [comment]
Also please use edit instead of making a ton of posts when you are listing off more items. No need to duplicate template or cause me to get 50 xmpp messages from github..

**Comment by R3P0FFXI** [comment]
What the fuck my email

**Comment by simthra** [comment]
Shame on me. Tavnazian moogles did it just fine. My apologies.
