### ISSUE TITLE
BLU spell Sudden Lunge possibly causes clients to crash

### ISSUE THREAD

**Issue by Flamebuilt** [LegionDark/Issues#411]
**Date & Time**: 10/27/2015 2:00PM
**Frequency**: 100% reproducable. Doesn't happen every single stun, but seems to have a chance to do so each time the monster is stunned.
**FFXI Client Version**:30150910_3
**Character Name**: Kabri
**Race**: Hume F
**Nation**: San d'Oria
**Main Job**: MNK
**Sub Job**: WAR
**Area & Coordinates**: Confirmed Locations--Abyssea - Tahrongi, Abyssea - La Theine, Abyssea - Misareaux, Jugner Forest
**Party or Solo**: Party
**NPC or Monster Name**: Confirmed Monsters to cause crash--Adze, Glavoid, Carabosse, Gukumatz, Belphoebe
**Multi-boxing? (multiple clients on same connection)**: Happens both when multi-boxing, and when not. 
**Steps To Reproduce The Issue**: Stun any of these monsters via Sudden Lunge

**Comment by R3P0FFXI** [comment]
Will test at some point

**Comment by puffer1221** [comment]
I have noticed that sudden lunge will crash the players client as well and also anyone else close by in aby, also seems to result in the same effect in legion, but it only seems to occur if i spam it and keep the mob or nm stun locked or if someone else does the same thing.

**Comment by Flamebuilt** [comment]
I've noticed it even when stunning only a specific spell, as well as when stun locking. The specific spell instance was against Belphoebe. Stunned Death one time, instantly crashed.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
