### ISSUE TITLE
Horos casaque (NQ) incorrect model!

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#412]
Date & Time:14/10/2015 ~23.00 GMT+1
 Frequency: everytime
 FFXI Client Version: 30150910_3
 Character Name: Dimma
 Race: Hume
 Nation: San'Odia
 Main Job: DNC
 Sub Job: NIN
 Area & Coordinates: 
 Party or Solo: 
 NPC or Monster Name: 
 ffxiah.com link (for inventory items only):
 Multi-boxing? (multiple clients on same connection): 

Horos casaque (NQ) has incorret model, so i neeg to see the correto model pls...
![dimma_2015 10 29_145815](https://cloud.githubusercontent.com/assets/13370670/10825903/3aca1924-7e4e-11e5-8955-5de113ced9a2.png)

**Comment by R3P0FFXI** [comment]
needs correct mID, item can be equipped and appears to function.

**Comment by Dimmabr** [comment]
How i cane help?

**Comment by Kaoriasada** [comment]
Dimma, you've been bugging me about this for 4 days EVERYTIME I log on.  I fixed it already and sent it to Loki, I fixed it the day you told me, and I sent it the day you told me.  It'll be in whenever Loki pushes the stuff I coded.  If you bring it up to me again in-game, I'm jailing you in-game for a day harassing staff.

**Comment by Dimmabr** [comment]
WTF!




I went up to you to fix it and you said you did not know how , then said Loki do that , you are too arrogant to tell me these things ... I just humbly asked to fix my item , I'm not here to fight .

**Comment by Kaoriasada** [comment]
No, I didn't.  I said that I had already fixed it and had sent it to Loki.  I told you that changing passwords wasn't anything I could do.  Please stop bugging me about this.  I understand you're foreign, but I FIXED IT ALREADY is pretty clear.

Thanks for your patience.
