### ISSUE TITLE
annealed mantle 

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#413]
Date & Time: 29/10/2015
Frequency:
FFXI Client Version: 30150910_3
Character Name: bathuka
Race: elvaan
Nation: sandy
Main Job: pld
Sub Job: nin
Area & Coordinates:
Party or Solo: party
NPC or Monster Name:
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): 

the def +13 is not script :)
https://www.bg-wiki.com/bg/Annealed_Mantle

**Comment by Kaoriasada** [comment]
Please only give FFXIAH links.  It asks specifically in the report template for an FFXIAH link.

Added the line and sent to Loki.  It'll be in when he pushes the stuff I've coded.
