### ISSUE TITLE
ashen KI ll cant UP to ashen IIl

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#414]
Date & Time: 29/10/2015, 1100am
Frequency: Always
FFXI Client Version: 30150730_3
Character Name: Aurel -Cassy 
Race: Hume
Main Job: Blu-Thf
Sub Job: Rdm-dnc
Area & Coordinates: Norg
Party or Solo: Party or solo
NPC Name: Kieran
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:NPCs Kieran is broken no up ki to ashen lll ,i kill Cath Palug in The Sanctuary of Zi'Tah
Modron in The Boyahda Tree
Mimic King in Ro'Maeve,,,,,,,,,,,LS  Qigang ,,NO up ashen ki ll ......Please help me , only uploaded the Ashen ki ll, the char Qigang -Hiya -Aurel -Cassy , with the work of GM Batman ...

**Comment by TeoTwawki** [comment]
Are you fucking kidding me!

**Comment by nekrol** [comment]
nop

**Comment by R3P0FFXI** [comment]
Stop quad boxing and see if that solves your issues

**Comment by TeoTwawki** [comment]
I Hate voidwatch. I really do. It makes me wanna burn the entire server to ash.

**Comment by TeoTwawki** [comment]
Incoming fix

**Comment by TeoTwawki** [comment]
Try it now. Should be a new CS.

**Comment by nekrol** [comment]
ok

**Comment by TeoTwawki** [comment]
player verified working in game while I watched
