### ISSUE TITLE
AHbot not buying certain items

### ISSUE THREAD

**Issue by Setsuai** [LegionDark/Issues#415]
**Date & Time**: 10/29/2015, 6:40 pm CST
**Frequency**:
**FFXI Client Version**: 30150910_3
**Character Name**: Setsuai
**Race**: Mithra
**Nation**: Bastok
**Main Job**: THF
**Sub Job**: DNC
**Area & Coordinates**: Mog House
**Party or Solo**: Solo
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**:

Steel Ingot(Single), Iron Sheet (Stack), and Adaman Chain (Single) are not being bought off AH.

**Comment by TeoTwawki** [comment]
likely pricing issue. some prices were changed, and the AH history does not retroactively reflect this.

Stacks and singles are relative to each other, in the ballpark of stack price being 9 to 12 times the price of a single (it varies). Its likely the price for stack or single or both was adjusted. There was no easy method of adjusting history (requires direct database edits) at the times these adjustments would have been made (still isn't).

**Comment by TeoTwawki** [comment]
The only known way it would get "stuck" would be if literally hundred of the item were stocked at once. The Darkstar based AH and search server itself wigs out and starts telling the bot these items don't exist. Known issue for 3 years without anybody on their end caring to investigate.

**Comment by Setsuai** [comment]
Ahh okay. I was kinda wondering if that might be the case. Thank you for responding!

**Comment by TeoTwawki** [comment]
I'll leave it for you to close this if you think its just pricing, else someone take a look when we have time.

**Comment by Setsuai** [comment]
I'll go ahead and close it. Thank you again!
