### ISSUE TITLE
Sinister Seidel lvl 0 mob

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#416]
**Date & Time**: 10/29/2015 7:50pm
**Frequency**: always
**FFXI Client Version**:30150910_3
**Character Name**: Baucant
**Race**: Elvaan
**Nation**: Sandy
**Main Job**: Blu
**Sub Job**: Nin
**Area & Coordinates**: Abyssea - Grauberg X:528 Y:46 Z:630 (215)
**Party or Solo**: party
**NPC or Monster Name**: Sinister Seidel
**ffxiah.com link (for inventory items only)**: N/A 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: fought many 1-shotted all

**Comment by Kaoriasada** [comment]
Are you getting EXP off them or is it simply getting one shot?

**Comment by Baucant** [comment]
I don't recall if I got EXP but I was one shooting them with low lvl blu spells...I'll go after them real quick and get more details

**Comment by Loki79** [comment]
Fixed be in next maint.
