### ISSUE TITLE
Missing mob group in Abby- Ulegurerand

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#417]
**Date & Time**: 10/29/2015 9:03pm
**Frequency**: always
**FFXI Client Version**:30150910_3
**Character Name**: Baucant
**Race**: Elvaan
**Nation**: Sandy
**Main Job**: Blu
**Sub Job**: Nin
**Area & Coordinates**: Abyssea - Ulegurerand X:-140 Y:-176 Z:65 (167)
**Party or Solo**: party
**NPC or Monster Name**: Mechanical Menace
**ffxiah.com link (for inventory items only)**: N/A 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: N/A

**Comment by Kaoriasada** [comment]
@Loki79  did this break again?  This was one of the issues in the big list of Abyssea bugs.  :<
