### ISSUE TITLE
99 RDM + Scroll of raise 2 = fail

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#418]
**Date & Time**: 10/30/2015 8:56am
**Frequency**: Always
**FFXI Client Version**:30150910_3
**Character Name**:Jukebox
**Race**:Mithra
**Nation**:Sandy
**Main Job**:Rdm
**Sub Job**:Whm
**Area & Coordinates**:Norther Sandy  X:129 Y:0 Z:-2 (148)
**Party or Solo**: both
**NPC or Monster Name**:N/A
**ffxiah.com link (for inventory items only)**:http://ffxiclopedia.wikia.com/wiki/Raise_II  (image is old but discription shows 95 rdm can learn) 
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**: tried useing scroll multipul times

**Comment by Loki79** [comment]
fixed.
