### ISSUE TITLE
Dvalinn uses no TP moves

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#419]
**Date & Time**: 10/30/2015 11:09 am
**Frequency**: Every time
**FFXI Client Version**:30150910_3
**Character Name**:Baucant
**Race**:Elvaan
**Nation**:Sandy
**Main Job**:BLu
**Sub Job**:Nin
**Area & Coordinates**:abyssea - Vunkerl
**Party or Solo**: Party
**NPC or Monster Name**: Dvalinn  http://ffxiclopedia.wikia.com/wiki/Dvalinn
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: Fought mob multipul time never did any TP moves

**Comment by Kaoriasada** [comment]
@Loki79 ???

**Comment by Loki79** [comment]
Fixed next maint.
