### ISSUE TITLE
CoP 1-2 Below the Arks

### ISSUE THREAD

**Issue by Tatako** [LegionDark/Issues#42]
Date & Time: 5/31/15 / 5:00pm EST
Frequency: Every time
FFXI Client Version: 30150508_8
Character Name: Tatako
Race: Mithra
Main Job: SAM
Sub Job:DNC
Area & Coordinates: x:0 y:-2 z: -252 (196) Spire of Holla
Party or Solo: Solo
NPC Name: n/a
Monster Name: n/a
Steps To Reproduce The Issue: As Baucant and Kinori also have the same issue.

Followed the walkthrough, spoke with Pherimociel and recieved CS, I spoke with Harith and mentions the emptyness. I do have mysterious amulet as temp key item.
I did not recieve CS when entering Shatered telepoint
Zoned into Hall of Transferance, I used the Large Apparatus (on left) to enter Dem and Holla. 
I climbed the promy for both Holla and Dem with the same result reaching the top and getting
the message: "You can hear a faint scraping sound from within, but the way is barred by some strange membrane..."

You can zone back into Promy and fight things if needed.

**Comment by TeoTwawki** [comment]
#14
