### ISSUE TITLE
Pol  crashes

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#420]
Date & Time: 30/10/2015, 1100am
Frequency: Always
FFXI Client Version: 30150730_3
Character Name: Aurel -Cassy 
Race: Hume
Main Job: war-Thf
Sub Job: Rdm-dnc
Area & Coordinates: Abyssea - Attohwa
Party or Solo: Party or solo
NPC Name: Ignis Eruca and Blazing Eruca,all time
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:My client crashes to make agriculture in Ignis Eruca and Blazing Eruca,all time

**Comment by nekrol** [comment]
Octave Club VS  Ignis Eruca and Blazing Eruca,client crashes

**Comment by TeoTwawki** [comment]
#85

>Seems to just be a random occurrence on:
* moving away form a mob as it is in its death animation
* killing multiple mobs very quickly
* fighting mobs at specific spots, like the NM pop site.
For no damn reason I can see.

>pretty much gonna be an issue till someone in DSP gives a f*** about it.

**Comment by TeoTwawki** [comment]
Its very random, and I can't fix it.
