### ISSUE TITLE
promyvion with rikiki not acces

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#421]
Date & Time: 30/10/2015
Frequency:
FFXI Client Version: 30150910_3
Character Name: rikiki
Race: tarutaru
Nation: sandy
Main Job: nin
Sub Job: war
Area & Coordinates: konchtat highlands x139 y19 z217 (237) 
Party or Solo: solo
NPC or Monster Name:s hattered cristal
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): 
I did all the cs and I can not go into PROMY (dem) (holla) (mea) (**i do not have the choice yes or no**)
Mission : http://img15.hostingpics.net/pics/496801Rikiki20151030233114.png
shattered cristal : http://img15.hostingpics.net/pics/865041Rikiki20151030233305.png

**Comment by bathuka** [comment]
would it be possible to reset the missions of promothia rikiki ?
at the first cs delkfut tower ?

**Comment by TeoTwawki** [comment]
Rikki one of your alts Bath?

**Comment by PikaFox** [comment]
You mignt need to redo a CS that was required before entering promy. CoP is finicky like that.

**Comment by bathuka** [comment]
I know pika I try several times that is why I am asking him to reset the Mission

**Comment by TeoTwawki** [comment]
I can fix or reset if need be

**Comment by TeoTwawki** [comment]
Just need to be on at same time

**Comment by Kaoriasada** [comment]
@bathuka has this been fixed or do we need to schedule a time online where we can get this done?

**Comment by Loki79** [comment]
Pretty sure this was resolved.  If not let us know.

**Comment by TeoTwawki** [comment]
It wasn't but it is now. char had started missions before dsp changed them, so all vars were broke.

**Comment by bathuka** [comment]
yes this is resolved sry tks teo for help
