### ISSUE TITLE
Jute boots floored

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#422]
**Date & Time**: 10/30/2015 8:51 pm
**Frequency**: atleast this one time
**FFXI Client Version**:30150910_3
**Character Name**:Baucant
**Race**:Elvaan
**Nation**: Sandy
**Main Job**: Thf
**Sub Job**: nin
**Area & Coordinates**:Fort Karugo-Narugo (s) X:-643 Y:-27 Z:-423 (246)
**Party or Solo**: Party
**NPC or Monster Name**:Kalasutrax
**ffxiah.com link (for inventory items only)**: https://www.bg-wiki.com/bg/Jute_Boots 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: n/a

Inv 74-80 and boots floored after winning lot

**Comment by Baucant** [comment]
just happened again

**Comment by TeoTwawki** [comment]
http://www.ffxiah.com/item/28275/jute-boots

Thats what we want, next time you have to report an item. I'm checkin into it.

**Comment by TeoTwawki** [comment]
@LegionDark/gm missing a table entry for these boots, can't even `@additem` them to myself.

**Comment by TeoTwawki** [comment]
@LegionDark/gm ye who would volunteer, assign self at the right.

**Comment by Kaoriasada** [comment]
@TeoTwawki Didn't see this.  On it

**Comment by Kaoriasada** [comment]
These weren't coded at all.  No entry in anything.  Sending them to @Loki79.

**Comment by Baucant** [comment]
@TeoTwawki , @Samikana, @R3P0FFXI Did this get Fixed? looking over the comments it seems like it was just passed around, nothing done and closed.

**Comment by Samikana** [comment]
@Baucant In my last comment, I said that I sent them to @Loki79.  Which means I coded them.  :)

Let me know if you experience any further issues with the item and I'll take a second look at it, or talk to Loki.  I'm not sure all of what I've coded and sent him has been implemented.

**Comment by Baucant** [comment]
@Samikana  my bad I misunderstood that last comment. When you put "Sending them to loki" I interpreted that as you sent the task to loki to be done. Sorry for the confusion.

**Comment by Samikana** [comment]
No problem!
