### ISSUE TITLE
incorrect mob lvl Savage Ruszor

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#423]
**Date & Time**: 10/31/2015 4:27 pm
**Frequency**: always
**FFXI Client Version**:30150910_3
**Character Name**:Baucant
**Race**:Elvaan
**Nation**: Sandy
**Main Job**: Blu
**Sub Job**: nin
**Area & Coordinates**:Xarcabard [S] X: 425.674, Y: -3.054, Z: 54 (998)
**Party or Solo**:both
**NPC or Monster Name**: Savage Ruszor
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: fought multipul mobs
All mobs of this type are lvl 1 this can not be correct

**Comment by Loki79** [comment]
nothing works in the past.  dont report it.
