### ISSUE TITLE
incorrect mob lvl Ruszor

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#424]
**Date & Time**: 10/31/2015 4:27 pm
**Frequency**: always
**FFXI Client Version**:30150910_3
**Character Name**:Baucant
**Race**:Elvaan
**Nation**: Sandy
**Main Job**: Blu
**Sub Job**: nin
**Area & Coordinates**:Beaucedine Glacier [S] X: 214.735, Y: -0.255, Z: 95 (627)
**Party or Solo**:both
**NPC or Monster Name**: Ruszor
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: fought multipul mobs
All mobs of this type are lvl 1 this con not be correct

**Comment by PikaFox** [comment]
Yes, they are the wrong level, many mobs in the past are. DSP has barely touched the past areas.
