### ISSUE TITLE
Nahtirah Trousers not equipping on 99 THF

### ISSUE THREAD

**Issue by TwIzTiD2469** [LegionDark/Issues#426]
**Date & Time**: 11/1/2015 1:00AM EST~
**Frequency**:Always
**FFXI Client Version**: Current to retail.
**Character Name**:Boombastic
**Race**:Taru
**Nation**:Sandy
**Main Job**:THF
**Sub Job**:DNC
**Area & Coordinates**:Anywhere
**Party or Solo**:Both
**NPC or Monster Name**:N/A
**ffxiah.com link (for inventory items only)**:  http://www.ffxiah.com/item/28197/nahtirah-trousers
**Multi-boxing? (multiple clients on same connection)**:N/A
**Steps To Reproduce The Issue**:Equipment menu, Manual typing of /equip "legs" "Nahtirah Trousers" and even using equipset.

**Comment by Kaoriasada** [comment]
I already fixed this/sent it to @Loki79.  Whenever he pushes in my stuff, the job mask will be fixed.  :)
