### ISSUE TITLE
npc selling item crash server 

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#427]
Date & Time: 3/11/2015
Frequency:
FFXI Client Version: 30150910_3
Character Name: hysteria
Race: elvaan
Nation: sandy
Main Job: thf
Sub Job: nin
Area & Coordinates:  port jeuno     x21 y0 z-7 (74)
Party or Solo: solo
NPC or Monster Name: garridan NPC
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): 
he selling item halloween when you buy flan masque +1 you crash the server i do not have test all head  
http://img11.hostingpics.net/pics/122370Hysteria20151103030345.png

**Comment by TeoTwawki** [comment]
Temp disabling flan masks till item_basic table fix is in. 
Sadly with the timing, the Event NPC is due to change its stock soon, which will close out its Halloween stock until next year. :frowning: 

As a reward for reporting it, I'll offer you the item after its fixed.

**Comment by Kaoriasada** [comment]
I sent this item to Loki and he said all of my stuff is live, so this should be in.  Closing the issue.
