### ISSUE TITLE
ix aern drk (broken is back)

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#429]
Date & Time: 4/11/2015
Frequency:
FFXI Client Version: 30150910_3
Character Name: bathuka
Race: elvaan
Nation: sandy
Main Job: pld
Sub Job: nin
Area & Coordinates: x-559 y5 z240 (75) garden of ruhmet
Party or Solo: pty
NPC or Monster Name: garridan NPC ix aern drk
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): 

is again broken the 48 AERN organ trade no longer allows pop

**Comment by TeoTwawki** [comment]
Spawned just fine for me just now.
