### ISSUE TITLE
Ramuite

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#43]
**Date & Time**: 5/31/2015 8:00pm
**Frequency**: Always
**FFXI Client Version**: 30150508_8
**Character Name**: Baucant
**Race**: Elvaan
**Main Job**: THF
**Sub Job**: DNC
**Area & Coordinates**: any AH
**Party or Solo**: either or
**NPC Name**: Auction house
**Monster Name**:N/A
**Steps To Reproduce The Issue**:
Asked GM God today if there was any logic to why single Ramuites sell on AH-BOT for 2k but the stacks of 99 sell for 4 million. GM God said it was a bug and needed to be reported I would assume this is the same for the other "avatar stones".

**Comment by TeoTwawki** [comment]
I already fixed this a few days ago but teh AH history still reflects the old pricing until some ppl sell some. Going to try and create a set of queries for changing the entries where the bot created the initial history, without effecting player sales.

**Comment by TeoTwawki** [comment]
And yes it was all of them crazy priced. :(

**Comment by Baucant** [comment]
I tried to purchase the stack of 99 for 200k, 250k, 300k, 350k, 400k,. Can you say what the price is set to so I can test that it it correct. I don't see people saveing these at all. except me of course.

**Comment by TeoTwawki** [comment]
stack prices should always come close to 10x or 12x single. In this case 12 singles is identical to the stack price. 

These were introduced for content Legion hasn't released yet. Some crafting recipes already have them, but later augments and/or custom trial stuff will call for the avatarite and/or items synthed from them.

**Comment by Baucant** [comment]
nice to hear this will have other uses. my Plan is to use them to make Avatar-rings NQ when they get coded.now you mentioned stacks of these should come out basicly the same cost if I bought indiidually. as these stack to 99 I would assume that 200kish would be the right price.  Still can not buy for 200k , 250k, 300k, did not keep trying after that.

**Comment by TeoTwawki** [comment]
oh crap
I thought they stacked to 12...Adjusting >.>

**Comment by Baucant** [comment]
yeaht was 12 I would just buy the 9 that AH-bot puts up and call it a day.

**Comment by TeoTwawki** [comment]
stack of 99 will be 195000, singles will remain 2k (99x 2k would be 198000, I don't foresee anyone wasting time breaking it up to profit a measly 3k).

**Comment by Baucant** [comment]
unable to buy for 195k do I need to wait for AH bot to cycle?

**Comment by TeoTwawki** [comment]
I have to get it to dump its extant stock, gonna be a few min while I work on the queries to adjust it

**Comment by TeoTwawki** [comment]
Gave the AH tool a restart, did some surgery AH history and pricing of current stock. See if you can buy them at the new price now.

**Comment by Baucant** [comment]
works as expected

**Comment by TeoTwawki** [comment]
Cool beans, closing issue now.

**Comment by TeoTwawki** [comment]
Oddly, retail really does have them regularly selling in millions for stacks, and singles for pocket change. Usually that sort of price discrepancy is because either the single or the stack is rarely listed, but they have fairly recent sales for both o.O; still, in a private server environment that's a problem, and I'd rather have cheap stacks than expensive singles in this particular case.

**Comment by Baucant** [comment]
yes in retail these are used to upgrade old weapons(no-one does that anymore though) but they make the "avatar-rings". The reason the "avatar rings" are so expensive is cause you have to get an HQ3 craft on these just to get 1 of the items you need to make the "avatar rings". Also with the lower Synth skill on this server (compared to retail) you are going to need more luck to craft HQ3 on a lvl 81 craft recipe. So you might get 1 out of the 99 to HQ3. if you would like i can follow up with the results. Oh and i never asked but is Ramutear's coded. would hate to try to make when the item isn't even coded

**Comment by TeoTwawki** [comment]
I honestly don't know if its in yet.
