### ISSUE TITLE
BRD cannot equip Nares Trews

### ISSUE THREAD

**Issue by Flamebuilt** [LegionDark/Issues#430]
Date & Time: 11/4/2015 4:00AM
Frequency: constant
FFXI Client Version: 30150910_3
Character Name: Nabri
Race: Tarutaru
Nation: San d'Oria
Main Job: BRD
Sub Job: WHM
Area & Coordinates: Anywhere
Party or Solo: Both
NPC or Monster Name: N/A
ffxiah.com link (for inventory items only): http://www.ffxiah.com/item/10564/nares-trews
Multi-boxing? (multiple clients on same connection): Yes
Steps To Reproduce The Issue: Tried changing jobs etc, BRD can't equip them no matter what. Hope this isn't a repost, searched for duplicates but didn't find any.

**Comment by Kaoriasada** [comment]
Jobmask was 1622044.  Changed to Supposed to be 1589788.  

Fixed the entire Nares set and sent to @Loki79
