### ISSUE TITLE
Fafnir-Adamantose-Behemoth-not reappear in 5 hours

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#431]
Date & Time: 29/10/2015, 1100am
Frequency: Always
FFXI Client Version: 30150730_3
Character Name: Aurel -Cassy 
Race: Hume
Main Job: Blu-Thf
Sub Job: Rdm-dnc
Area & Coordinates: 
Party or Solo: Party or solo
NPC Name: Fafnir
Adamantose
![captura](https://cloud.githubusercontent.com/assets/13084662/10987328/0f9282be-8411-11e5-8890-4a9d4742e344.PNG)

Behemoth
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:hello ,the NM not reappear took 10 hours waiting. I like so much fun doing things but expected no sense

**Comment by TeoTwawki** [comment]
You are wrong, and they are respawning correctly.

**Comment by nekrol** [comment]
I'm waiting for hours and nobody killed a stay on my record
if someone killed

**Comment by R3P0FFXI** [comment]
First off stop wasting our time with this crap land kings repop according to how I have them scripted 5 hours is not eh confirmed repop time

**Comment by TeoTwawki** [comment]
I was just in game checking them. Their timer is fine, and they are repopping fine.

**Comment by TeoTwawki** [comment]
I was just in game checking them. Their timer is fine, and they are repopping fine.

**Comment by nekrol** [comment]
We boring killed three Nidhogg

**Comment by TeoTwawki** [comment]
If anyone kills HQ, it resets NQs timer as well. They share timer and only 1 will spawn at a time unless force popped.

**Comment by TeoTwawki** [comment]
This has always been this way.

**Comment by TeoTwawki** [comment]
...About ready to remove mob tool from website..
