### ISSUE TITLE
Beastmaster pet causing 0 xp gain

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#432]
**Date & Time**: 11/6/15
**Frequency**: Always
**FFXI Client Version**: 30150910_3
**Character Name**: Tarot
**Race**: Hume
**Nation**: San
**Main Job**: 76/77 bst
**Sub Job**: NA
**Area & Coordinates**: Zeruhn Mines
**Party or Solo**: Party
**NPC or Monster Name**: NA
**ffxiah.com link (for inventory items only)**: NA
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Summoning a beastmaster pet causes party to get 0 xp credit. Happened with multiple lvl 76 pets, and of note, i did max the merit ability that upgrades pet level.

With Pet
![tarot_2015 11 06_005531](https://cloud.githubusercontent.com/assets/12601727/10990524/0bc221ec-8422-11e5-9866-8d1e3003a686.png)

Without Pet
![tarot_2015 11 06_005641](https://cloud.githubusercontent.com/assets/12601727/10990527/11dce936-8422-11e5-9eaa-5b3662e0ecc7.png)

Merits
![tarot_2015 11 06_005743](https://cloud.githubusercontent.com/assets/12601727/10990528/185b1c1a-8422-11e5-8a8c-e593aeeab8c8.png)

**Comment by TeoTwawki** [comment]
DSP bug that happens because they have the exp calc done entirely wrong and including your pets. I saw Hozu talking about how he's attempting to fix it in their IRC channel. Has to do with the level the pet is.

**Comment by TeoTwawki** [comment]
Basically anytime you pets level is above yours its gonna hurt your exp, till the fix happens.

**Comment by PikaFox** [comment]
I assumed as much.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
