### ISSUE TITLE
Dynamis Sandoria Crashed on Entry then Kicked

### ISSUE THREAD

**Issue by nemesisx101** [LegionDark/Issues#433]
**Date & Time**: 8:53 AM
**Frequency**: NA
**FFXI Client Version**:30150910_3
**Character Name**:Nemesisx
**Race**:Hume
**Nation**:Bastok
**Main Job**:Thief
**Sub Job**:Dancer
**Area & Coordinates**:Dynamis Sandoria
**Party or Solo**:solo
**NPC or Monster Name**:NA
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:NO
**Steps To Reproduce The Issue**:NA

**Comment by R3P0FFXI** [comment]
Server did not crash this was a client based crash
