### ISSUE TITLE
Anch. Gloves +1 boost not work

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#434]
Date & Time: 16/11/2015, 03:00am
Frequency: Always
FFXI Client Version: 30150730_3
Character Name: Aurel
Race: Hume
Main Job: Sam - Drk -Monk -Blu-War
Sub Job: Sam/Drk
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name:
Monster Name:
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:Hello ,Increases Boost attack boost to 20%. +68 not work ,I have 47 pieces the reforge AF and 20 not work ,Please for what all reforge AF not work fine The game need save a list the AF work or not work AF ,,,sorry for my stupid report yesterday

**Comment by Loki79** [comment]
Some mods do not exist in DSP and more than likely never will.  We are aware of the ones that do not not work.  It is not a priority for anyone to add them.

**Comment by nekrol** [comment]
thank i have other issue please check #440
