### ISSUE TITLE
faust has an incorrect repop timer

### ISSUE THREAD

**Issue by puffer1221** [LegionDark/Issues#436]
**Date & Time**: 10/11/2015, 06:39 am
**Frequency**: Constant
**FFXI Client Version**: 30150910_3
**Character Name**: Anofreixx, Anofrei
**Race**: Hume
**Nation**: Bastok
**Main Job**: War
**Sub Job**: Sam
**Area & Coordinates**: The Shrine of RuAvitau, X: 740.000, Y: -0.463, Z: -99.000
**Party or Solo**: Irrelevant
**NPC or Monster Name**: Faust
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Yes but irrelevant
**Steps To Reproduce The Issue**: Faust's repop timer is set to 17hrs 6 mins and 40secs, seems to be the only one at that repop timer in sky the others seem to be between 2-6hrs.

**Comment by R3P0FFXI** [comment]
Faust repop timer is correct its controlled by script not by SQL, the tool on the website cant read the script
