### ISSUE TITLE
Bravura Lv 85

### ISSUE THREAD

**Issue by Niobiritzu** [LegionDark/Issues#437]
**Date & Time**: 11/10/2015 7:37 AM EST
**Frequency**: Any time item is equipped, even after zoning and changing items. Logging out also has no effect (full shutdown not just /logout).
**FFXI Client Version**: 30150910_3
**Character Name**: Niobirizu
**Race**: Hume
**Nation**: San d'Oria
**Main Job**: Warrior
**Sub Job**: Samurai
**Area & Coordinates**: Any
**Party or Solo**: Either
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/18642/bravura
**Multi-boxing? (multiple clients on same connection)**: Yes, 2
**Steps To Reproduce The Issue**: Complete first trial and obtain Bravura 85

The problem is that Bravura model will not show up. It appears as a H2H weapon (only 1).
![bravura 85 model issue](https://cloud.githubusercontent.com/assets/15780681/11062832/42e78804-8780-11e5-9eee-63879cc7845e.png)

**Comment by TeoTwawki** [comment]
Today we have learned that Niobirizu is secretly *one punch man*! >.>

**Comment by Niobiritzu** [comment]
NOOOO HOW DID YOU KNOW! Too bad I'm not bald O.o

**Comment by Kaoriasada** [comment]
I'll look into this when I get home

**Comment by Kaoriasada** [comment]
I honestly skipped over this report because I didn't think it applied to anything I could do!  Thought it was something relating to trials.

**Comment by TeoTwawki** [comment]
Just a model ID I think (I don't see the axe on his back in the screenshot but I do see h2h weapon at his hip). Till the model is corrected he has one helluva punch? lol

**Comment by Kaoriasada** [comment]
Yeah, I'll correct the model.  I figured that's what it was, too...  I'll check through everything else just to make sure it's all coded correctly, though.  It was probably a typo, or laziness.  Who knows.

**Comment by Niobiritzu** [comment]
Upheaval and Metatron Torment looks hilarious with the H2H weapons for sure.

**Comment by Kaoriasada** [comment]
Fixed and sent to Loki.
