### ISSUE TITLE
White Stratum Abyssite III cant UP to White Stratum Abyssite IV

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#438]
Date & Time: 10/11/2015, 18:00pm
Frequency: Always
FFXI Client Version: 30150730_3
Character Name: Aurel -Cassy
Race: Hume
Main Job: Sam - Drk -Monk -Blu-War
Sub Job: Sam/Drk
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name:
Monster Name:
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:Hello,i kill all NM and not have Voidwatcher's Emblem: Qufim. ----talk to all NPCs, and killed about 10 times the NM
![captura](https://cloud.githubusercontent.com/assets/13084662/11076790/6c8643fc-87db-11e5-80c9-e767b788b1b2.PNG)
![catura](https://cloud.githubusercontent.com/assets/13084662/11076802/7e8c19a0-87db-11e5-9075-a844c499b676.PNG)

**Comment by TeoTwawki** [comment]
Will be fixed soon as server can pull in changes.

**Comment by Kaoriasada** [comment]
Teo do I need to log in and give anyone KIs?

**Comment by TeoTwawki** [comment]
No.

**Comment by Loki79** [comment]
This shit works for EVERYONE but this idiot

**Comment by nekrol** [comment]
thank i have other issue please check #440
