### ISSUE TITLE
I lost Ki Indigo Stratum Abyssite IV

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#439]
![captura](https://cloud.githubusercontent.com/assets/13084662/11077128/3257b088-87dd-11e5-9fde-3ed3a1f808ea.PNG)
Date & Time: 10/11/2015, 18:00pm
Frequency: Always
FFXI Client Version: 30150730_3
Character Name: Rukitsu
Race: Mithra
Main Job: Rdm
Sub Job: Whm
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name:
Monster Name:
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:Hello,i kill Celaeno in Dangruf Wadi and ki low

**Comment by TeoTwawki** [comment]
This is supposed to happen, sort of. The T4 3 nations voidwatch NMs cycle your T4 abyssite back to the 1st tier. An adjustment is being considered of making this only happen to the person who spawned NM.

**Comment by TeoTwawki** [comment]
(Right now it happens to anybody present who is in possession of a T4)

**Comment by nekrol** [comment]
ok thanks

**Comment by nekrol** [comment]
I lost my starting oprtunidad Quest Guardian of the Void

**Comment by nekrol** [comment]
thank i have other issue please check #440

**Comment by TeoTwawki** [comment]
> I lost my chance to start Quest Guardian of the Void

No, you didn't. The keyitem has nothing to do with that. A variable is set separately.

> thank i have other issue please check #440

Don't do that. these issues are not related.
