### ISSUE TITLE
NPC in Jueno caused RO to most of the server

### ISSUE THREAD

**Issue by ditchfly** [LegionDark/Issues#44]
**Date & Time**: May 31, 2015 9:00 pm
**Frequency**: 1
**FFXI Client Version**: 30150508_8
**Character Name**: Klang
**Race**: Elvaan
**Main Job**:BLM
**Sub Job**:WHM
**Area & Coordinates**:Low Jueno  X:-121 Y:0 Z:- 196 (199). 
**Party or Solo**:PARTY
**NPC Name**:Don't remember. Had never seen it. Mithra in PLD gear right at gate. She said "the best we can do is try" then party RO'd as well as several in LS
**Monster Name**:None
**Steps To Reproduce The Issue**:Can't reproduce because she isn't there anymore

**Comment by Baucant** [comment]
thats the NPC who turns on the street lamps if no-one is doing that quest

**Comment by R3P0FFXI** [comment]
Vhana Ehgaklywha is the Mithra PLD at the gate No problem found with her. I clicked and did not DC, nor did anyone else.
