### ISSUE TITLE
Feast Hose currently cannot be equipped

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#440]
Date & Time: 11/11/2015, 18:00pm
Frequency: Always
FFXI Client Version: 30150730_3
Character Name: Aurel 
Race: Hume
Main Job:  - Monk
Sub Job: Sam/Drk
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name:
Monster Name:
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:Hello,Feast Hose currently cannot be equipped         
![captura](https://cloud.githubusercontent.com/assets/13084662/11094399/6c02aa18-886e-11e5-97dd-03ecac20cb75.PNG)
http://www.ffxiah.com/item/27223/feast-hose

**Comment by R3P0FFXI** [comment]
OK so wheres the FFXIAHh Link that's required in ALL bug reports? Your missing lines in your template that are on the main page

**Comment by nekrol** [comment]
http://www.ffxiah.com/item/27223/feast-hose

**Comment by nekrol** [comment]
that's ? because they understand that more needed

**Comment by Kaoriasada** [comment]
Missing an entry in item_armor.  Coded in item_mod and item_basic.  Sent to Loki.

**Comment by Kaoriasada** [comment]
@R3P0FFXI he has it underneath the screenshot.

**Comment by Loki79** [comment]
I don't give a fuck about your issue how about that??!  I'm so sick of seeing you file bug reports I could puke.  Go play retail.

**Comment by PikaFox** [comment]
Kaori stated that it was coded and sent to loki. It will be fixed when it gets fixed.

**Comment by TeoTwawki** [comment]
> 
I lost Ki Indigo Stratum Abyssite IV #439 
Anch. Gloves +1 boost not work #434
White Stratum Abyssite III cant UP to White Stratum Abyssite IV #438
Miasmic Pants currently cannot be equipped #442

WTF is wrong with you.

**Comment by nekrol** [comment]
I'm sorry, I did not think that report is an annoyance

**Comment by TeoTwawki** [comment]
The report is, YOU are.

**Comment by TeoTwawki** [comment]
The report is not, YOU are.

**Comment by TeoTwawki** [comment]
You linked all your issues for no reason, as if we ignore you. That impatience is irritating.

**Comment by PikaFox** [comment]
In all seriousness, it pings and floods our notice system for every comment left per every report opened. It basically ties down the system so we have to go through 5 different threads to find nothing of relevance.

If you wanted an update, it would have been better to simply ask here. Even if it would have annoyed people, since kaori stated that it would be resolved before closing it, it would have annoyed people less and been more efficient.

**Comment by TeoTwawki** [comment]
Are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet are we there yet ?

**Comment by nekrol** [comment]
ok bye understood
