### ISSUE TITLE
Hattori Hakama +1 giving absolutely no stats

### ISSUE THREAD

**Issue by Flamebuilt** [LegionDark/Issues#441]
**Date & Time**: 11/14/2015 12:00PM
**Frequency**: constant
**FFXI Client Version**:30150910_3
**Character Name**: Kabri
**Race**: Hume F
**Nation**: San d'Oria
**Main Job**: NIN
**Sub Job**: WAR
**Area & Coordinates**: N/A
**Party or Solo**: Both
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/27262/hattori-hakama-1
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**: Not a single stat from the hattori hakama +1 are being given. Checked constantly from equipping/reequipping. Tried changing jobs, zoning etc. No DEF/HP/attributes/katana skill, and the haste also seems inactive. Tested the haste with Utsusemi. The 109s worked perfectly fine.

**Comment by Flamebuilt** [comment]
Would it be possible to have the 109s returned to me for now? Literally have no other option for my NIN atm, basically running around pantsless lol

**Comment by Kaoriasada** [comment]
Sorry, no.  I'll get the 119s coded and in to Loki.

**Comment by Loki79** [comment]
Fixed be in next maint.
