### ISSUE TITLE
Miasmic Pants currently cannot be equipped

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#442]
Date & Time: 16/11/2015, 18:00pm
Frequency: Always
FFXI Client Version: 30150910_3
Character Name: Rukitsu
Race: Mithra
Main Job: Rdm
Sub Job: Whm
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name:
Monster Name:
Multi-boxing? (multiple clients on same connection): yes
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/27220/miasmic-pants
Steps To Reproduce The Issue:Miasmic Pants currently cannot be equipped

**Comment by Loki79** [comment]
Fixed in next maint.

**Comment by nekrol** [comment]
thank i have other issue please check #440
