### ISSUE TITLE
Some H2H weapons not using both fists

### ISSUE THREAD

**Issue by neuromancerxi** [LegionDark/Issues#443]
**Date & Time**: N/A
**Frequency**: Repeatable
**FFXI Client Version**: 30150910_3
**Character Name**: Neojin
**Race**: Hume
**Nation**: Bastok
**Main Job**: MNK
**Sub Job**: WAR
**Area & Coordinates**: N/A
**Party or Solo**: Solo
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**:  
http://www.ffxiah.com/item/18784/
http://www.ffxiah.com/item/18783/

**Multi-boxing? (multiple clients on same connection)**: NO
**Steps To Reproduce The Issue**: Equip H2H, punch things.

https://github.com/LegionDark/Issues/issues/29
Does not appear to be resolved.

Metasoma Katars (not using both fists with hand2hand)
Eyra Baghnakhs +1 (not using both fists with hand2hand)

**Comment by TeoTwawki** [comment]
TY for report, we'll look into it soon as we can

**Comment by Kaoriasada** [comment]
Did not intend to self assign

**Comment by Loki79** [comment]
These items are not coded yet and to be honest there are plenty of options so not going to worry about it.  If these are on the aH they need to be remved/
