### ISSUE TITLE
Can't get Caballarius Gauntlets from moogle

### ISSUE THREAD

**Issue by SquallerSnake** [LegionDark/Issues#444]
Date & Time: 11/17/2015 22:30 pm
Frequency: Always
FFXI Client Version:30150910_3
Character Name:Squaller
Race:Hume
Nation: Bastok
Main Job: Paladin
Sub Job: Ninja
Area & Coordinates:Tavnazian Safehold
Party or Solo: solo
NPC or Monster Name: Moogle
ffxiah.com link (for inventory items only): N/A
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue: I have trade to the Moogle (Relic armor moogle): Valor gautlets +2, 12 Aptant Pera + 8 Aptant Pera but he don't give me the Caballarius Gauntlets. I tried several times.
![squaller_2015 11 17_224159](https://cloud.githubusercontent.com/assets/13245127/11226214/d1c8095a-8d7e-11e5-8f1d-d107b6f68e9a.png)

**Comment by Kaoriasada** [comment]
@TeoTwawki

**Comment by TeoTwawki** [comment]
Not it!
@Loki79

**Comment by SquallerSnake** [comment]
The other four pieces, head, body, legs, feet is being exchanged without problems.

Only hand trade is not working

**Comment by Loki79** [comment]
Fixed.

**Comment by SquallerSnake** [comment]
thank You!
