### ISSUE TITLE
ranperres final rest

### ISSUE THREAD

**Issue by XXXLBUCK** [LegionDark/Issues#446]
*Date & Time**: 11/19/15 10pm
**Frequency**: constant 
**FFXI Client Version**:30150910_3
**Character Name**:death
**Race**:elv
**Nation**:sandy
**Main Job**:pld
**Sub Job**:war
**Area & Coordinates**: 
**Party or Solo**:solo
**NPC or Monster Name**: trion
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: yes/no/both tried
**Steps To Reproduce The Issue**:n/a

ranperres final rest wont proc, i try to talk to trion, the guard at his door just says no admittance.

went to the heavy stone door, it just lets me through with no nm spawned, no idea what the issue is.

i thought maybe i already talked to trion, but then the heavy stone door at h-8 just says "leave through this door?"

halp

**Comment by PikaFox** [comment]
Ill see what i can do when you log in if im awake.

**Comment by XXXLBUCK** [comment]
when are you usually on?

**Comment by PikaFox** [comment]
Usually afternoonsish.

**Comment by XXXLBUCK** [comment]
est?

**Comment by PikaFox** [comment]
Yes

**Comment by PikaFox** [comment]
Player was able to receive CS to progress. Reopen if any issues in the future occur.
