### ISSUE TITLE
Tancho +1 no stats shown on status screen

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#447]
Date & Time: 20/11/2015, 14:00pm
Frequency: Always
FFXI Client Version: 30150910_3
Character Name: Aurel -Cassy
Race: Hume
Main Job: Sam - Drk -Monk -Blu-War-nin
Sub Job: Sam/Drk
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name:
Monster Name:
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/20988/tancho-1
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:
![captura](https://cloud.githubusercontent.com/assets/13084662/11309203/32410786-8fa1-11e5-97bf-da3e545175d8.PNG)

**Comment by Loki79** [comment]
Fixed be in next maint.
