### ISSUE TITLE
Ildebrann the invincible

### ISSUE THREAD

**Issue by maikuru23** [LegionDark/Issues#448]
**Date & Time**: 1:31 AM PST
**Frequency**: popped 3/3 times and was same each time
**FFXI Client Version**: 30150910_3
**Character Name**: Maiku
**Race**: Taru
**Nation**: Bastok
**Main Job**: PLD
**Sub Job**: NIN
**Area & Coordinates**: Ifrits Cauldron I-6
**Party or Solo**: Party
**NPC or Monster Name**: Ildebrann/Planar Rift  ZM voidwatch NM
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: yes but not the issue
**Steps To Reproduce The Issue**:
Ildebrann spawns magic eva buffed/magic immune and does not land.  Always flies even after killing adds separate or at same time.  Mages cannot even out damage regen.  We took rangers but damage from rangers is super pathetic also.  ***Does not land*** so this makes 99% of all DD's worthless on this NM.  Held on pld for over 30min, does not depop either due to rage timer or depop after its been spawned for that matter.  Pretty sure this NM is bugged on several levels.  Even with 10 rngs this wouldn't be feasible

**Comment by PikaFox** [comment]
The NM worked a while ago, and while i wont say its impossible that its broke since, i can state that he is always supposed to be flying unless you kill all of his adds at the same time. He flies again whenever any of his adds are repopped.

**Comment by maikuru23** [comment]
adds instantly repop after they die, and even if adds die exact same time they do not force land Ilde.  I see no issue with it always flying... but making it magic immune and melee not being able to hit it...?  How does one even begin to fight that...?  RNG army i guess?

**Comment by PikaFox** [comment]
Respawn on the adds is incredibly short for some reason, making this mob unkillable

**Comment by Loki79** [comment]
upping the spawn timer on the adds.  @TeoTwawki  this has not changed since we launched it months ago.  I noticed the same thing with Bismarck though, any thing change that would effect how these functions behave?

**Comment by TeoTwawki** [comment]
@Loki79 its partly from us having not pulel din DSP update syet - until we do, subsequent repops  of any mob will keep whatever animation state instead of resetting to normal, which screws up things like the flight modes of Wyrms and Amphiptiers. There may be other issues but I need to look at the mob script some more first.

**Comment by Kaoriasada** [comment]
We're updated to the latest vers.  Should this be closed @TeoTwawki?

**Comment by TeoTwawki** [comment]
The update was to allow newer client, but did not get caught up on DSP updates yet. Annoyingly doing a client update patch like that makes getting caught up take even longer.

**Comment by TeoTwawki** [comment]
p.s.
I did manually fix things except until we DSP update he may still possibly spawn in the flying state, which will much up his AI some. The flying NM in Abyssea-Konschtat has the same problem.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
