### ISSUE TITLE
ashen KI cant UP to ashen II 

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#449]
**Date & Time**: 11/22/2015
**Frequency**:always
**FFXI Client Version**:30150910_3
**Character Name**:Hiya
**Race**:hume
**Nation**:san
**Main Job**:BLU
**Sub Job**:RDM
**Party or Solo**:party
**NPC or Monster Name**:Kieran
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**:
We go through your repair in the repeat to do this task, after your repair has been less than the solution, we have played a few times NM ashen1, but do not have the last step, the problem has been plagued by us, why not always get it?

**Comment by qiganggang** [comment]
![Uploading QQ图片20151122235748.jpg…]()

**Comment by R3P0FFXI** [comment]
Fine at this point we will reset your VW back to 0 this is the only solution we have not tried

**Comment by TeoTwawki** [comment]
no, that will just enable even more glitches in the character

**Comment by qiganggang** [comment]
We are always in accordance with the tips above requirements do, but every time there is an in the upgrading of the problem above repeated the same problem several times not to repair, we a guild friends a didn't upgrade up, these problems has filed a good several times.

**Comment by qiganggang** [comment]
We have already mentioned this problem several times, and we have been following the tips in your repair process, but we can't get a valid solution to the problem. I hope you can handle this problem this time, thank you.

**Comment by qiganggang** [comment]
This is our entire line the same problem. L don't go up,

**Comment by TeoTwawki** [comment]
The problem is largely language barrier and timezone difference. The code IS correct. There is no bug in the code to actually fix. The problem is one of: 
a) character is screwed up from before the fix
b) character has missed a step from after the fix
I've been dealing with Nekrol repeatedly. Its the same gd problem. You and I are never on at same time when i look for you to check your status and correct any issue. I am almost never on in fact, and for someone else to help you I wind up just hand holding them through every effing GM command anyway. you have no idea how much I would like to just delete voidwatch right off the goddamn server.

**Comment by qiganggang** [comment]
you what time in here i call you? help the this bug

**Comment by qiganggang** [comment]
When are you online? I'm waiting for you to deal with the problem.

**Comment by TeoTwawki** [comment]
I'm standing next to you in game right now...I should be in bed asleep but trying to help you and you are afk. I logged in instantly after seeing you post after being notified within 5 seconds of the new post. This always happens when I try to help somebody.

**Comment by TeoTwawki** [comment]
Go finish VW OP 054 Elshimo List....quest status show you never finished it by going to the NPC in Kazham.

**Comment by TeoTwawki** [comment]
I waited in game more than 30 min to walk you through what you were missing. I'm going to bed.

**Comment by qiganggang** [comment]
i'm sorry boss call me work

**Comment by qiganggang** [comment]
When did I have you online?

**Comment by TeoTwawki** [comment]
YOU HAVE BEEN GOING TO WRONG GODAMN NPC YOU NEVER FINISHED QUEST KEIRAN CANNOT HELP YOU

I CANNOT BE ANY FUCKING CLEARER THAN THIS
