### ISSUE TITLE
void watch crimson abbysite

### ISSUE THREAD

**Issue by BlessedXxX** [LegionDark/Issues#450]
ok i did the New begging and steamed ram ... got my sprinter boots and ribbon but no voidwatch officer will give me stone/crimson abbysite... and its really making me mad.

**Comment by PikaFox** [comment]
**Date & Time**: 
**Frequency**:
**FFXI Client Version**:
**Character Name**:
**Race**:
**Nation**:
**Main Job**:
**Sub Job**:
**Area & Coordinates**:
**Party or Solo**:
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**:

Please fill out the template.

**Comment by R3P0FFXI** [comment]
No template closing
