### ISSUE TITLE
Relic H2H Stage 5 not taking Items for Spharai

### ISSUE THREAD

**Issue by nemesisx101** [LegionDark/Issues#451]
**Date & Time**: 11/22/2015 10:56 P.M.
**Frequency**:n/a
**FFXI Client Version**:30150910_3
**Character Name**:Nemesisx
**Race**:Hume
**Nation**:Bastok
**Main Job**:BLU
**Sub Job**:RDM
**Area & Coordinates**:Castle Oztroja (Court Yard) H-6
**Party or Solo**:Solo
**NPC or Monster Name**: ??? 
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:No
**Steps To Reproduce The Issue**: Exited Castle  went back talked to Goblin came back tried again.

**Comment by nemesisx101** [comment]
I have tried again to trade items after update still nothing could it be items are coded wrong ?

**Comment by Samikana** [comment]
Did it get fixed?
