### ISSUE TITLE
Ashen stratum abyssite I -> II

### ISSUE THREAD

**Issue by ronnymp** [LegionDark/Issues#452]
**Date & Time**: 9:46pm (gmt-3)
**Frequency**:often
**FFXI Client Version**:
**Character Name**:Miudo
**Race**:Glka
**Nation**:Sand
**Main Job**:WAR
**Sub Job**:SAM
**Area & Coordinates**:Norg
**Party or Solo**:Party (me aurel & our bots)
**NPC or Monster Name**: Last NM to ashen stratum II > tangaroa
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Yes , X1 (serjoca)
**Steps To Reproduce The Issue**:

After all NMS killed , i talked to NPCs in order like it says in ffxiwikia ... "Travel to Norg and speak to 
Kieran (H-8) for a cutscene.
Talk to Gilgamesh (L-8) for another cutscene.
Speak to Kieran again for a cutscene that upgrades your KeyItemAshen Stratum Abyssite to a KeyItemAshen Stratum Abyssite II (the quest is flagged at this point)." 
When i talk to kieran he dont wanna give me CS , and i killed all NMs already lol...

**Comment by TeoTwawki** [comment]
Re-kill'em because there is no way in hell that there is any bugged code here (my eyes will bleed if I look at it any more than I already have man). And multiboxing is KNOWN to cause variables to randomly not update. :(

**Comment by ronnymp** [comment]
i forgot to say , after  kiilled scorpion in Quicksand caves , server crashed...

**Comment by TeoTwawki** [comment]
...the crash prolly ate your variable change then. :(

**Comment by ronnymp** [comment]
ok , thanks teo

**Comment by TeoTwawki** [comment]
p.s. remember to get quest completions in rabao and kazham, or Keiran will intentionally ignore you! I got so many non-bug reports from that, that I have added system messages berating peoepl who will waste my time on it.

**Comment by ronnymp** [comment]
i did talk to them... xD

**Comment by TeoTwawki** [comment]
Just have to make sure x_X so many..reports...wasn't..broken... -*twitches*-

**Comment by ronnymp** [comment]
im gonna redo scorpion and see whats gonna happen

**Comment by TeoTwawki** [comment]
If it turns out not to be the scorpion, a change I made late last night can help me determine which you are missing. Gushing Spring in Rabao now system messages your variable to you (7 = got credit for all 3 mobs) and I can tell which one is missing form what the number is.

**Comment by TeoTwawki** [comment]
if you haven't already ran to quicksand caves you may wanna just check that 1st

**Comment by ronnymp** [comment]
"this menu doesnt work yet" for Gushing 
Hildegard , "quest variable :0 and needs to be 7!"
 weird.. i did all Nms and lldebran took me forever to kill but we did it :(

**Comment by TeoTwawki** [comment]
1 sec meeting you in game. thought you have kaz part done already and just needed rabao's finish

**Comment by ronnymp** [comment]
hehe ok ... i tough i did too xD

**Comment by TeoTwawki** [comment]
got players requirements sorted out in game and they were able to progress.

**Comment by ronnymp** [comment]
Thank you teo for patiente
