### ISSUE TITLE
Arendsi fleuret - wrong model ?

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#453]
Date & Time: 24/11/2015 10:14 P.M.
Frequency: everytime
FFXI Client Version:30150910_3
Character Name:Thranduil
Race:Hume
Nation:Bastok
Main Job:rdm
Sub Job:thf
Area & Coordinates: bastok mines
Party or Solo:Solo
NPC or Monster Name: -
ffxiah.com link (for inventory items only): http://www.ffxiah.com/item/20717/arendsi-fleuret
Multi-boxing? (multiple clients on same connection):No

Weapon model seems to be wrong: it should be a grey fleuret, but is appears as a longsword.
![thranduil_2015 10 28_142704 - copia](https://cloud.githubusercontent.com/assets/12772770/11380912/3c58dd92-92f9-11e5-8012-af197d1a0592.jpg)

**Comment by Kaoriasada** [comment]
I'll fix this on Friday!  Today is Turkey Day.  :)

**Comment by Kaoriasada** [comment]
I've fixed this, it'll be sent in with the crafting update

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
