### ISSUE TITLE
wait you help me  5hr wait you

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#456]
Date & Time: 11/22/2015
Frequency:always
FFXI Client Version:30150910_3
Character Name:Hiya
Race:hume
Nation:san
Main Job:BLU
Sub Job:RDM
Party or Solo:party
NPC or Monster Name:Kieran
Multi-boxing? (multiple clients on same connection):yes
Steps To Reproduce The Issue:

**Comment by TeoTwawki** [comment]
I'm gonna kick your fucking ass into next Tuesday if you keep pulling this shit. I told you EXACTLY wtf was wrong. and its NOT on teh servers end

**Comment by R3P0FFXI** [comment]
Dont ever open a ticket like this again, Teo has told you whats wrong numerous times. Stop wasting our time.
