### ISSUE TITLE
Unable to progress in Aht Urghan Mission "Immortal Sentries"

### ISSUE THREAD

**Issue by neuromancerxi** [LegionDark/Issues#457]
**Date & Time**: 2015-11-25
**Frequency**: Repeatable
**FFXI Client Version**: 30150910_3
**Character Name**: Hotai
**Race**: Taru
**Nation**: Sando
**Main Job**: WHM
**Sub Job**: RDM
**Area & Coordinates**: Mount Z, 674.144, 365.427, -24.000
**Party or Solo**: Party and Solo
**NPC or Monster Name**: Waudeen
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**:

1. Activate quest in Aht Urghan (Naja Salaheem)
2. Travel to Cadavera Mire Homepoint crystal
3. `@homepoint`
4. `@return`
5. Zone into Alzadaal Undersea
6. Take porter on right
7. Zone out to Mount Z
8. Walk to Waudeen
9. Waudeen does not produce dialog
10. Returned to Naja to see if I missed a touch, Naja does not produce Dialog
11. Returned to Waudeen, still does not produce dialog

I took my main and my mule (hotai) at the same time while doing this quest. My main completed without issue. Hotai, however, does not have the Supplies Key Item in any of the KI menus. Probably a quirk of multi-boxing during the quest. Can we reset the mission flag for Hotai? Thanks in advance.

**Comment by TeoTwawki** [comment]
Its mroe a quirk of DSp broek early ToAU missions on us. GM will have to fix you up in game whiel both online.

Tip: github uses the at symbol for mentions, so when you need to use one when talking about a GM command surround it in back ticks (above tabkey, looks like an apostrophe) like this `@return` so some guy named return doesn't wonder why we're tagging him.

@PikaFox can you hook this guy up next time you are on? Prolly the supplies package thing again

**Comment by neuromancerxi** [comment]
Thanks @TeoTwawki . I'll use backticks next time. 

@PikaFox Let me know when you have time available, and I'll try to get the twerps logged in.

**Comment by PikaFox** [comment]
Im logged in atm

**Comment by PikaFox** [comment]
Key item "Supplies Package" added to Hotai.

**Comment by neuromancerxi** [comment]
@PikaFox Received, and was able to progress with mission. TYVM.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
