### ISSUE TITLE
Can't unlock Blu, Pol.exe keeps crashing during cutscene

### ISSUE THREAD

**Issue by GeoLobava** [LegionDark/Issues#458]
**Date & Time**: 12/1/2015 @ 9:48pst
**Frequency**: Everytime
**FFXI Client Version**: Version 30151103_3
**Character Name**: Geo
**Race**: Taru
**Nation**: Windurst
**Main Job**: Drk
**Sub Job**: Rdm
**Area & Coordinates**: Aydeewa Subterrane | (H-9) | x:379  y:0  z:347  (103)
**Party or Solo**: Solo
**NPC or Monster Name**: n/a
**ffxiah.com link (for inventory items only)**: n/a
**Multi-boxing? (multiple clients on same connection)**: Nope
**Steps To Reproduce The Issue**: I can't seem to get passed the cutscene where you step into the well in Aydeewa and reply "yes" 2 times. Pol.exe always crashes right after my 2 responses, forcing me to relog. When I log back in, I'm at the entrance to the zone, but without Blu unlocked. I've tried numerous times on my comp, but I haven't had a chance to try on another. I also haven't abandoned the quest yet to see if that'll help, I wanted to pick your brain first. Any help is greatly appreciated! Thanks! :)

**Comment by TeoTwawki** [comment]
Oh goody, DSP has the NPC IDs in Aydeewa slightly off. Being worked on.

**Comment by GeoLobava** [comment]
Awesome! Thanks for the quick reply!!

**Comment by TeoTwawki** [comment]
I just happened to be awake still, saw the ding (github instant messages me) and saw them talk about it in DSP's IRC, so I knew what was up. :)

**Comment by TeoTwawki** [comment]
Seems some new mobs were added there, and SE likes to add new stuff smack in the middle of old stuff.

**Comment by Kaoriasada** [comment]
@TeoTwawki is this something I can adjust his variable for, or is he stuck until DSP fixes it?

**Comment by TeoTwawki** [comment]
@Kaoriasada its more than a variable, but you could look at the zone script in dsp and manually do all the things it does when that cs normally finishes. https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Aydeewa_Subterrane/Zone.lua#L71

**Comment by TeoTwawki** [comment]
@Kaoriasada Oh..correction..I don't think you have a command for unlocking a job (yet!) I'll fix that soon!

**Comment by neuromancerxi** [comment]
@TeoTwawki West Ron is offset as well.

**Comment by TeoTwawki** [comment]
@Kaoriasada `@batfix BLU targetName` should fix him up. The command will zone him at the end so you'll know it worked. Bad things will happen if used on somebody that didn't need it.

**Comment by LuckyBane** [comment]
I'm facing the same problem; is there a process to follow while in game as a fix or should we sit tight until DSP fixes it?

**Comment by TeoTwawki** [comment]
Theres no real fix till DSp updates NPC list again and Legion pulls said fix from them.Sami can try the same workaround for you but it bypasses the cs event.

**Comment by Kaoriasada** [comment]
I'm offering the fix to everyone who asks for it.  I also told them if they ask for it before they're at the final cutscene, it's their fault and I won't be helping them fix their character, and none of the staff will either.  

Fletcher and Kuroanu have been fixed.

**Comment by Kaoriasada** [comment]
Wacko has been pushed past the final cutscene for Blue Mage.

**Comment by GeoLobava** [comment]
Is it possible to push my char into Blu as well? I'm at the cut scene in the quest line, but I'm not physically at aydeewa with my char

**Comment by Samikana** [comment]
You need to be online for me to push you past

**Comment by Samikana** [comment]
Dasciaz has been pushed past.

@GeoLobava I still need to catch you in-game?

**Comment by GeoLobava** [comment]
Hi Sami, sorry about the massive AFK I've had, I'll be on all evening and if I dont catch you tonight, I'll leave Geo on while I sleep, thanks in advance!

**Comment by Samikana** [comment]
I believe the issue is that your "evening" is 1AM for me.  I won't be home until roughly 3:00~3:30EST, I'm not sure what time zone you're in, but that's about 8 hours from now.

**Comment by GeoLobava** [comment]
Yes, lol, that does see to be an issue, I'm in PST, but I'll leave my comp on while I'm at work, thanks again! I've been dying to play Blu :)

**Comment by Samikana** [comment]
@GeoLobava you are not online unfortunately.  .-.

**Comment by Samikana** [comment]
Just kidding /sea all looks for the god damn job GEO not the person

**Comment by Samikana** [comment]
Geo has been pushed past for the BLU mission

**Comment by Samikana** [comment]
Omegazprime and Preacher have been pushed past the final CS.  Also someone else whose name I forgot because derp

**Comment by Skadau** [comment]
Hello, i just ran into the same problem on the final cut scene.  had a buddy of mine tell me about this forum.  if you could push through Agrias and Skadaru i'd be most appreciative.  i'm on mst but should be on all day or whenever i need to be.  tyvm ^^y

**Comment by Samikana** [comment]
Both fixed

**Comment by Samikana** [comment]
If anyone else experiences this issue, PM Halsey in-game

**Comment by PikaFox** [comment]
Pushed Nikkilai through.

**Comment by adveque** [comment]
Hello I have been having the same issue wondering if you could push Zio through. Thanks

**Comment by Gn3x0n** [comment]
**Date & Time**:  01/07/2016 at 12:03am est
**Frequency**: Everytime.
**FFXI Client Version**: Version 30151103_3 (most current available)
**Character Name**: Caramon
**Race**: Elvaan
**Nation**: San d'Oria
**Main Job**: Ninja
**Sub Job**:  Monk
**Area & Coordinates**: Aydeewa Subterrane,  X: 380, Y: 0, Z:330 (61)
**Party or Solo**: Solo
**NPC or Monster Name**: 
**ffxiah.com link (for inventory items only)**:  None
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**: Once in the Aydeewa Subterrane zone, walk to the area to start the final cut scene. Cut scene rolls out (although sometimes the client will crash before hand) and when it reaches the segment where the ???? says "he's waking up" the game crashes.

**Comment by Samikana** [comment]
@Gn3x0n you're supposed to make a seperate bug report.  I'll fix you in-game tomorrow, as I'm going to bed now.  Didn't realize this was a BLU issue.

**Comment by Gn3x0n** [comment]
Oh! Sorry, I didn't to create a new issue that was similar :X

**Comment by Samikana** [comment]
That's fine.  I'll be on today after school for a short time before work.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
