### ISSUE TITLE
Rank Mission 2-3 Giddius

### ISSUE THREAD

**Issue by Rion1984** [LegionDark/Issues#459]
**Date & Time**: dec 4 2015
**Frequency**:tryed 5 time
**FFXI Client Version**: 30151103_3
**Character Name**: Rion,
**Race**: Hume, 
**Nation**: Bastok
**Main Job**: thief
**Sub Job**: black mage
**Area & Coordinates**: x:313 y:-123 z:380 (127)
**Party or Solo**: party and solo
**NPC or Monster Name**: stuck in CS, fight timer is on.
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: tried with or with out same results
**Steps To Reproduce The Issue**: start rank mission 2-3

**Comment by Gryphus9** [comment]
Just tried to attempt this fight with 3 other people. Experienced the same bug repeatedly.

**Comment by TeoTwawki** [comment]
Will be tracking down cause and posting new info when I can.

**Comment by TeoTwawki** [comment]
CS stick-age is usually caused by bad plugin or client file problems, but can be bad NPC ID from recent updates as well. I have a character than can test it though when I get a few hrs to myself.

**Comment by Samikana** [comment]
@Rion1984 Catch up with me (Halsey) in-game and I'll push you past 2-3.  :)

**Comment by Samikana** [comment]
@Gryphus9 you too as well!

**Comment by TeoTwawki** [comment]
@Rion1984 @Gryphus9 guys, because mission 2-3 has multiple paths I need to know which nation you went to 1st and which one you went to second for debugging purposes, on the characters who got stuck

**Comment by Samikana** [comment]
I fixed them already

**Comment by TeoTwawki** [comment]
@Samikana @#$%^

I KNOW. I'm trying to locate the BUG -_-

**Comment by Samikana** [comment]
They were both in Bastok, on the path San d'Oria to Windurst.

**Comment by TeoTwawki** [comment]
And now I know which path to run down the code in, but in the future I'd appreciate just letting the people I am actually talking to answer.

**Comment by Samikana** [comment]
I apologize, I didn't think they'd answer as they didn't answer me and many players don't offer responses on here.  I will not interfere
