### ISSUE TITLE
Guild point NPC

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#46]
**Date & Time**: 6/1/2015 11:05am (est)
**Frequency**: once so far
**FFXI Client Version**:30150508_8
**Character Name**: Baucant
**Race**: Elvaan
**Main Job**: THF
**Sub Job**: Dnc
**Area & Coordinates**: Bastok Markets X:-213 Y:-6 Z:-63 (112)
**Party or Solo**: party
**NPC Name**:Ellard
**Monster Name**:N/A
**Steps To Reproduce The Issue**:
Guild Point NPC on wind day said "You have 1 more days (vana1diel time) to provide us with the requested item." (brass hairs)
"You are not eligible to receiver giuld pointat this time." which I understood cause I turned in brass hair pins about 6 hours prior. I waiting in Bastok Market for day to change and to start the new guild point requested item
to my surprise when I return to the guild point NPC (Ellard) he said  "You have 25 more days (vana1diel time) to provide us with the requested item." (brass hairs)
"You are not eligible to receiver giuld pointat this time."

**Comment by TeoTwawki** [comment]
This is related to bug fixes that will be in Tuesdays maint. Will need to recheck it after that to see if there is one that got missed.

**Comment by Baucant** [comment]
Ok I'll hold offf till after maintance.

**Comment by Baucant** [comment]
Still doing the same thing this morning at about 8 am est the requested item was jeweled collars, and I had 4 vanadiel days to complete. I completed the request left to do some other things. I came back after 1pm (5hours later), the requested item is still jeweled collar I have 23 (vana`diel days to complete but I can not earn anymore points

**Comment by TeoTwawki** [comment]
This may possibly be related to the server time offset and the client being hardcoded for Japanese time. But maint hasn't actually happened yet either. Itw as supposed to be today and I just got up and I see its been announced for tomorrow instead, guess everyone was busy offline today.

**Comment by R3P0FFXI** [comment]
Issue was resolved by DSP last maint
