### ISSUE TITLE
renik jeuno wrong af+1

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#460]
Date & Time: 6/12/2015
Frequency:
FFXI Client Version: 3015113_3
Character Name: bathuka
Race: elvaan
Nation: sandy
Main Job: pld
Sub Job: nin
Area & Coordinates: upper jeuno
Party or Solo: pty
NPC or Monster Name: renik 
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): yes
i have trading 5 rem4 for obtain http://www.ffxiah.com/item/27690/rev-coronet-1
and i have obtain thf head http://www.ffxiah.com/item/27689/pill-bonnet-1

i throw the pillager bonnet+1
http://img11.hostingpics.net/pics/439210Bathuka20151206055011.png

**Comment by Samikana** [comment]
Looks like someone accidentally added one to the item ID.  This should be an easy fix.

@R3P0FFXI

**Comment by Samikana** [comment]
Oops.  @R3P0FFXI, add this to what needs to be included in the Dec. update

**Comment by bathuka** [comment]
Can you 'll get item when a gm will be online?

**Comment by Samikana** [comment]
I had to go to Renik and test the trade because there was no proof of you getting that item in the screenshot, only that you traded it.

I've verified that this is not working properly and have given @bathuka the item.

**Comment by bathuka** [comment]
tks the next time i screen all step

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
