### ISSUE TITLE
SMN quest + Chocobo refuses to load map

### ISSUE THREAD

**Issue by Shyrtle** [LegionDark/Issues#462]
Hello,
This is my first bug report. 
Basically, if you are doing the SMN quest, and you zone into an area with a new weather while riding a Chocobo, the map will not load. It will go into a black screen and stay black until you @homepoint or @return. 

**Date & Time**: 12/9/15 & 1:02 AM (PST)
**Frequency**: It's happened to me 3 times. But I think it would happen every time. 
**FFXI Client Version**: 30151103_3
**Character Name**: Shyrtle and Sidaithe
**Race**: Taru
**Nation**: Bastok
**Main Job**: WHM and RDM
**Sub Job**: THF and BLM
**Area & Coordinates**:X: -586, Y:0, Z:631 (91)
**Party or Solo**: Party
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: Yes. It happened on both characters. All 3 times.
**Steps To Reproduce The Issue**: Accept the quest to unlock summoner. Purchase a Chocobo. Ride Chocobo into a map with a weather you have not discovered yet. The game will not load the CS, which keeps you stuck in a black screen. You have to @return or @homepoint to get out of it.

**Comment by Samikana** [comment]
Can you try without dualboxing?  Generally, we don't investigate bug reports unless it's tested without dualboxing, because it can cause so many issues.

**Comment by TeoTwawki** [comment]
@LegionDark/gm @LegionDark/owners needs forwarded to DSP if reproducible. There used to be a known bug where chocobo would interfere but my understanding was it just wouldn't trigger at all, not leave you stuck.

**Comment by Samikana** [comment]
I have some questions.
1.) Does any text appear, like the cutscene is happening, just with a black screen?
2.) Do you get credit for the weather?

**Comment by Samikana** [comment]
As you can see, I forced thunder weather in Batallia Downs and then zoned out and back in with a chocobo.  It happened, so I'd say the situation has been reproduced.  
![halsey_2015 12 14_155027](https://cloud.githubusercontent.com/assets/12781975/11793579/70c4dab4-a27a-11e5-94a2-9f4b1980f339.png)

**Comment by TeoTwawki** [comment]
Its like it was trying to load, but got stuck somehow.

**Comment by Shyrtle** [comment]
I think all the questions posted have been asnwered so far. But yeah, I did it without duel boxing and it still happened. And you do get credit for the weather. Because I have finished the smn quest, and I never got CS's for Wind/Dust/Normal/Lightning

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
