### ISSUE TITLE
Dancer Emperyan Artifict Armor Maculele bangles +1 (Effects)

### ISSUE THREAD

**Issue by Dimmabr** [LegionDark/Issues#464]
Date & Time: December, 10th ,2015
Frequency:Always
FFXI Client Version:30151103_3
Character Name: Dimma
Race:Hume
Nation:Sand'Oria
Main Job:DNC
Sub Job:THF
Area & Coordinates:Always
Party or Solo: both
NPC or Monster Name:NA
ffxiah.com link (for inventory items only) http://www.ffxiah.com/item/27089/macu-bangles-1
Multi-boxing? (multiple clients on same connection):NA

 I have checking and tested to work this effects but don't work at all "Skillchain Bonus"+11 "Reverse Flourish"+12

**Comment by R3P0FFXI** [comment]
Once again Dimma mods dont exist

**Comment by Dimmabr** [comment]
What is version neeeded?

**Comment by Samikana** [comment]
Mod doesn't exist.  No version is needed.  Needs coded for the armor to be coded.
