### ISSUE TITLE
Assimilator's keffiyeh +1renik jeuno wrong af+1

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#466]
Date & Time: 12/12/2015, 14:00pm
Frequency: Always
FFXI Client Version: 30151103_3
Character Name: Aurel 
Race: Hume
Main Job: -Blu-
Sub Job: Sam
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name:
Monster Name:
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/27699/assim-keffiyeh-1
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:i have trading 5 rem4 for obtain http://www.ffxiah.com/item/27699/assim-keffiyeh-1
and i have obtain SMN head http://www.ffxiah.com/item/27698/con-horn-1

**Comment by Samikana** [comment]
Someone needs to go through these because this is happening so often it's annoying

**Comment by nekrol** [comment]
hi some solution

**Comment by Samikana** [comment]
I can give you the item, but this NPC spits out all the wrong items.  The code needs to be checked and fixed.

**Comment by nekrol** [comment]
ok tell me when ,i  online now

**Comment by Samikana** [comment]
I'll be online today at 3:30PM EST.  Exactly how long I'll be on is undetermined, but it should be a few hours.

**Comment by Samikana** [comment]
@TeoTwawki if someone sends me the code for this stuff, I can double check all the items that it spits out, unless someone else is already on it

**Comment by nekrol** [comment]
mmm what is you name? in the game i play all day

**Comment by nekrol** [comment]
![captura](https://cloud.githubusercontent.com/assets/13084662/11793294/78e1f3da-a289-11e5-8eba-52d7d90f0473.PNG)

**Comment by Samikana** [comment]
I'm Halsey.  Gave Aurel the Assimilator's Keffiyeh.  This bug still needs fixed though.

**Comment by nekrol** [comment]
thanks for you help

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update

**Comment by TeoTwawki** [comment]
@Samikana somehow I never got the notification for all these issues with renik when you tagged me.
