### ISSUE TITLE
Prishe do not accept the item for reforge Arbatel bracers

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#467]
Date & Time: 15/12/2015, 14:00pm
Frequency: Always
FFXI Client Version: 30151103_3
Character Name: cassy
Race: Hume
Main Job: -sch
Sub Job: Sam
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name:Prishe
Monster Name:
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/27090/arbatel-bracers
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The IssuePrishe do not accept the item for reforge Arbatel bracers
![captura](https://cloud.githubusercontent.com/assets/13084662/11809768/e397dafe-a307-11e5-897e-1fa6403496a1.PNG)

**Comment by Samikana** [comment]
Do you get a server message when you trade it?

**Comment by nekrol** [comment]
nop

**Comment by Samikana** [comment]
I'll test this when I get home if I have time to get online.

**Comment by Samikana** [comment]
Make sure to try without dualboxing @nekrol

**Comment by nekrol** [comment]
ok

**Comment by nekrol** [comment]
I reforge head -body -legs -feet and hands does not work

**Comment by Samikana** [comment]
This is SCH empyrean?

**Comment by nekrol** [comment]
yes sch empy

**Comment by Samikana** [comment]
Ok.  I get home in 4~5 hours.  I'll test it then.  Thanks for the info.  :)

**Comment by Samikana** [comment]
I just tested this and @nekrol is correct, the hands are not working.  I also tried to trade the +1 version of the hands and it didn't work.

**Comment by Samikana** [comment]
@R3P0FFXI do you want me to test the rest of the Empyrean 109 reforged to make sure it's all functional and so it can all be in for the update in case it's not all working

**Comment by nekrol** [comment]
you change all item for Arbatel bracers +1 ,i have all item 30 itz +Savant's bracers +2+ 5 rems 3 and 5000bayd??please

**Comment by Samikana** [comment]
no

**Comment by R3P0FFXI** [comment]
@Samikana Yes go ahead and test lets find out whats not working

**Comment by nekrol** [comment]
all work , I now have head , body , legs , and feet Legs and feet ,,,,, +1,,,,,so hand not work trade

**Comment by Samikana** [comment]
I understand but I'm testing ALL 109 reforged, not just SCH.  It will be fixed in the update.

**Comment by Baucant** [comment]
@nekrol has Cassy defeated all 9 zone bosses and acquired all 3 lunar abyssites?

**Comment by Samikana** [comment]
@Baucant this was already taken care of.

**Comment by Samikana** [comment]
If you read the comments above, it was an issue with the coding, not human error on Nekrol's part

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
