### ISSUE TITLE
Mindmelter MID

### ISSUE THREAD

**Issue by Samikana** [LegionDark/Issues#468]
**Date & Time**: 15/12/15 15:27
**Frequency**: Consistent
**FFXI Client Version**: 30151103_3
**Character Name**: Ezra
**Race**: Mithra
**Nation**: Bastok
**Main Job**: SCH
**Sub Job**: BLM
**Area & Coordinates**: 579 0 -305
**Party or Solo**: Solo
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/21161/mindmelter
**Multi-boxing? (multiple clients on same connection)**: /
**Steps To Reproduce The Issue**: Wearing it ???

MID wrong for Mindmelter.  Appears and attacks as a sword.  Just writing this to remind myself to fix it.
![ezra_2015 12 15_153114](https://cloud.githubusercontent.com/assets/12781975/11823221/e9ff92b8-a340-11e5-84dc-1f82832b4150.png)

**Comment by PikaFox** [comment]
Well, according to the FFXIAH comments, it uses the nirvana model, so should be an easy swap

**Comment by Samikana** [comment]
It's not identical to Nirvana, apparently it has the same picture but not the same actual model in-game.  But I'm not spending hours looking for that model, so I'm just going to make it have the same model as the photo.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
