### ISSUE TITLE
Testing Reforged Gears

### ISSUE THREAD

**Issue by ghost** [LegionDark/Issues#469]
To make it quick and painless, this is where I'm going to log my results while collecting data for the correct/incorrect reforged gears.

**109 Empyrean Reforged**
THF 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

WHM 109 Empyrean 
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

WAR 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

MNK 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

BLM 109 Empyrean
Head - CODED INCORRECTLY.  Traded Goetia Petasos +2 and 30 Itzapapalotl's scales to Prishe.  No reponse.
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

RDM 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

PLD 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

DRK 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

BST 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

BRD 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

RNG 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

SAM 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

NIN 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

DRG 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly,

SMN 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

BLU 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

COR 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

DNC 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

SCH 109 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - CODED INCORRECTLY.  Traded Savant's Braces +2 and 30 Itzapapalotl's scales to Prishe.  No reponse.
Legs - Coded Correctly
Feet - Coded Correctly

109 Empyrean trial testing is completed.

**Comment by Samikana** [comment]
@R3P0FFXI i am going to finish the items tonight and then finish testing all 109 and 119 reforged for the sake of being absolute and not having to return to the issue

**Comment by Samikana** [comment]
I don't know if the testing will be done by tonight but I will finish the items tonight and the reforged trials sometime this weekend

**Comment by R3P0FFXI** [comment]
@Samikana that's fine i appreciate the work being put in here, its the holiday were in no rush

**Comment by Samikana** [comment]
THF 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

WHM 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

WAR 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

MNK 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

BLM 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

RDM 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

PLD 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

DRK 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

BST 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

BRD 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

RNG 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - CODED INCORRECTLY.  Traded Amini Bottillons and 5 copies of Rem's Tale, Chapter 1s to Renik.  No response.

SAM 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

NIN 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

DRG 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

SMN 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

BLU 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

COR 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

DNC 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

SCH 119 Empyrean
Head - Coded Correctly
Body - Coded Correctly
Hands - Coded Correctly
Legs - Coded Correctly
Feet - Coded Correctly

**Comment by Samikana** [comment]
Just got the final requirement for the relic and artifact reforged, as I was a few missions off.  

I'll be testing the Artifact Armor and Relic Armor soon.

**Comment by R3P0FFXI** [comment]
issue resolved in MUP2
