### ISSUE TITLE
sors shield  strange 

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#47]
Date & Time: 1/06/2015
Frequency:
FFXI Client Version: 30150508_5
Character Name: sepultura
Race: 
Main Job:
Sub Job:
Area & Coordinates: action house
Party or Solo:PARTY
NPC Name:
Monster Name: 

i have buy sors shield @ah 
problem this shield do not work he is unequipable and he is not droppable in this server !!
i have using "dropp tool"
question when people obtain it 
item >> http://img15.hostingpics.net/pics/635970Sepultura20150601192450.png
action house >> http://img15.hostingpics.net/pics/928121Sepultura20150601192345.png

**Comment by Loki79** [comment]
not in game more than likely... sounds like someone ran the ah grab item shit which will suck if they did.

**Comment by Loki79** [comment]
You were sold an item that was imported from retail that we have yet to make.  It was sold from a player not the AH-Bot.  This shouldn't be an issue much longer as it wont be possible.
