### ISSUE TITLE
Configuration Issues

### ISSUE THREAD

**Issue by oormis** [LegionDark/Issues#470]
Date & Time: 12/1/2015 @ 6:32gmt
Frequency: Everytime
FFXI Client Version: Version 30151204_2
Character Name: Kailix
Race: Mithra
Nation: Bastok
Main Job: Whm
Sub Job: 
Area & Coordinates:
Party or Solo: Party and Solo
NPC or Monster Name:
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): No
Steps To Reproduce The Issue: Every time I change zones and login/out all configurations reset "volume, resolution, macros, etc."

**Comment by TeoTwawki** [comment]
Many settings in the client aren't actually used at all in xiloader currently but..Macros? You lose macro's when you zone, not when you dc'd or something but just crossing a zoneline? 
Are you using "run as admin" ?

 ![run as admin](https://www.blackvpn.com/content/uploads/run_as_admin_03.png)

In any case no specific private server really has anything to do with this, and your best bet for help is either the darkstar forums or their irc channel. I've never lost macro's just by crossing a zoneline ever but I have lost my changes on being dc'd and had my macro's overwritten by testing on a different server.

**Comment by TeoTwawki** [comment]
https://forums.dspt.info/viewforum.php?f=12&sid=6717d6818d883e2d6abdfeb291c6cdc9
or
`#darkstarproject` on  `irc.rizon.net`

**Comment by Samikana** [comment]
She's on the latest ver.  Could that make it bug up..?

**Comment by TeoTwawki** [comment]
Unlikely but possible. If its a version thing I'd see a ton of ppl in DSP's irc saying it pretty fast.

**Comment by Samikana** [comment]
Hm, when she /telled me in-game and I asked her her /ver, I figured it was a version thing and told her to file a bug report.  We should make a "we don't know" tag lol

**Comment by TeoTwawki** [comment]
well I know enough to know enough to confidently say its not a legion specific bug :)

**Comment by Samikana** [comment]
@oormis if DSP has nothing to say about it, I'd try reinstalling and then going back to them if the issue persists.

**Comment by Samikana** [comment]
@TeoTwawki I'm fairly certain now that this is an issue caused by a later client.  I've met 3 different (notably new) players experiencing this issue, all on the latest December client.

**Comment by R3P0FFXI** [comment]
@Samikana im updating to the latest retail client on a PC now I will test this

**Comment by Samikana** [comment]
@R3P0FFXI OK let me know if you need any help.

**Comment by Samikana** [comment]
This is not a client issue.  Please uninstall your game and try to reinstall from a different source.  

You can find the install here: http://www.playonline.com/ff11us/download/media/install_win.html

**Comment by Samikana** [comment]
The official install*

**Comment by R3P0FFXI** [comment]
@Samikana @TeoTwawki @oormis I have just tested this with no issues, I updated to the latest retail client and all macros and settings stayed with no issues. Logged in/Out Zoned etc. I am firmly convinced this is 100% a client based issue with the source of the client that some are using. Download   and update direct from SE not a 3rd party source.
