### ISSUE TITLE
Help me unlock blu please!

### ISSUE THREAD

**Issue by Shyrtle** [LegionDark/Issues#471]
Date & Time: 12/17/2015 @ 1:00pst
Frequency: Everytime
FFXI Client Version: Version 30151103_3
Character Name: Shyrtle
Race: Taru
Nation: Bastok
Main Job: RDM
Sub Job: BLM
Area & Coordinates: Aydeewa Subterrane | (H-9) | x:379 y:0 z:347 (103)
Party or Solo: Solo
NPC or Monster Name: n/a
ffxiah.com link (for inventory items only): n/a
Multi-boxing? (multiple clients on same connection): No
Steps To Reproduce The Issue: I can't get passed the cutscene where you step into the well in Aydeewa and reply "yes" 2 times. Pol.exe always crashes right after my 2 responses, forcing me to relog. When I log back in, I'm at the entrance to the zone, but without Blu unlocked. 

I know this is a known bug, I was told to post here by a GM and work out a time I can be on to meet with a GM. So they can unlock the class for me :) 

I'm in PST Timezone, and I can log on more frequently now that school is over. Lemme know!
Ideally, now would work, or tomorrow around this time. Basically, from 11pm-2am pst works really good, but I can make something else work. 

Thanks!

I'll close this as soon as I unlock blu lol :D

**Comment by Samikana** [comment]
I won't be online until 3:30PM EST and if my character is online it's because I fell asleep coding last night.  >.>

**Comment by Samikana** [comment]
Also which GM told you to bug report it?  Afaik every GM has the command and they should have been capable of pushing you past.  If you can't be online when I am, please leave your character on.

**Comment by R3P0FFXI** [comment]
@Samikana when he pops into the room at 3am for a week and a half straight and everyone is asleep and we keep missing the player when we do login yes he was told to bug report it by not only myself but Teo as well due to us being busy or not logged in.

**Comment by Samikana** [comment]
Ah, okay.  I didn't think about IRC, I just assumed a GM in-game said it to her.  I'll fix it up for you tonight.  :)

**Comment by Shyrtle** [comment]
K I will leave my character logged in from now til late tonight.

**Comment by Shyrtle** [comment]
and I'm PST so 3am is really only midnight for me, and that is just the time I'm able to play lol. Because school and stuff.

**Comment by Shyrtle** [comment]
I'm guna leave the character on all night and into the morning, and maybe all of tomorrow.

**Comment by Samikana** [comment]
Unfortunately almost every GM/admin is asleep or at school/work at that time so it's a bit tough to get help.

I can be on that time on Saturday and Sunday, otherwise, I'll fix you tonight as long as your character is on.  :)

**Comment by Shyrtle** [comment]
Yeah, that's what I figured. I'll leave my character on all day today. As long as the server stays up. I'm not too worried about it, I understand that the time I can play isn't really convenient for any of the GM's lol. Thanks for helping though.

**Comment by PikaFox** [comment]
Used command on Shyrtle, reopen if issue is not resolved.

**Comment by R3P0FFXI** [comment]
@PikaFox took care of this @Samikana he was able to catch the user while I was updating my work PC to get into FFXI

**Comment by Samikana** [comment]
Sounds great.  Thanks @PikaFox.

**Comment by Shyrtle** [comment]
Awesome! I have blu unlocked now! Thank you guys!!
