### ISSUE TITLE
CoP Mission 6-4 Server crash

### ISSUE THREAD

**Issue by Quillarts** [LegionDark/Issues#473]
Date & Time: 12/18/15 
*Frequency: N/A
*FFXI Client Version: Version 30151103_2
*Character Name: Hakushi, Jonelol
*Race: Taru
*Nation: Sandoria
*Main Job: BLU, SCH
*Sub Job: RDM, RDM
*Area & Coordinates: Sealion's Den x: 612, y: 132
*Party or Solo: Party of 2
*NPC or Monster Name: N/A
*Multi-boxing?: Yes
*Steps To Reproduce The Issue: Enter Battlefield

@TeoTwawki 

Teo, Neuromancer told me to send you a ticket when I got to CoP 6-4 so I would not crash the server. I have myself "Hakushi" and my cure-bot "Jonelol" right before the fight. Thanks!

**Comment by Samikana** [comment]
I need to verify with someone that this is actually crashing the server and if it is, for the time being, I will push you past the fight so you can progress.

**Comment by Samikana** [comment]
@TeoTwawki are all BCNM fights causing issues or is this just a coincidence?

**Comment by TeoTwawki** [comment]
@Samikana I'm still investigating the exact cause, but it looks the same as the dynamis crash even though no crossing of zoneserver takes place. I think there's a DSP bug in the BCNM handling for Sealions den BCNMs. Haven't had a chance but need to do some testing in person myself. 

I pushed a few people past **who had already done the actual fights** but crashed out, and gave them the titles and what have you, I don't want us to have to do that for everyone that hits that mission nor watch server repeatedly crash as they try to clear it so I need to find the cause soon.

**Comment by Quillarts** [comment]
I was at work all day. Thanks for the quick response on this. Can I ask that if you do not find a solution soon that you could still push me and my curebot through? I am trying to catch up to my LS mates so so we can progress in Sea. Thanks!

**Comment by TeoTwawki** [comment]
yeah If I can't take of it soon I'll push you past

**Comment by Samikana** [comment]
@Quillarts just asked me in-game if I could push him past and I told him no because of what you previously stated about not wanting to push everyone past.

**Comment by TeoTwawki** [comment]
I will prolly be in on tonight to have a look at wtf that BCNm is doing

**Comment by Quillarts** [comment]
Ok, thanks guys. I just found out that my god daughter will be staying with us tonight so I probably will not be online. But I can check in here occasionally if you need me. Would I have to be online to be pushed through?

**Comment by PikaFox** [comment]
Yes, youd need to be online and most likely responsive. Generally makes it easier on the devs.

**Comment by Samikana** [comment]
@Quillarts I can fix you past, but I need @TeoTwaki to explain exactly HOW to use the commands he wants me to use to send you past.

**Comment by teotwaki** [comment]
I believe @Samikana wanted to ping @TeoTwawki, and not me :).

**Comment by Samikana** [comment]
@TeoTwaki, sorry dawg!

@TeoTwawki I need explained how to use these commands.  I can see their coding and it gives a small howto, but I have no idea where to find IDs for titles or some of the other stuff the @completemission was asking for.

**Comment by TeoTwawki** [comment]
@Samikana Like I said last night, in the globals in darkstars trunk. 
https://github.com/DarkstarProject/darkstar/tree/master/scripts/globals
There's one for keyitems, one for quests, one for missions, another for titles..Pretty much anything that is a mysterious number is listed in one of them.

**Comment by TeoTwawki** [comment]
If you aren't sure, just wait and I'll get it taken care of tonight.

**Comment by Samikana** [comment]
I'll look at it when I get off school.  I might be coming home early as I feel like I'm about to throw up, lol.  We'll see.  I'll give it a gander though and let you know.  I'd rather be taught how to do it so I have the knowledge later on if something similiar comes up again.

**Comment by neuromancerxi** [comment]
@TeoTwawki It's likely we'll have a few more bodies from my LS coming up on this fight in the next few days/weeks. I'll refer them to this thread to check status before requesting assistance. Thanks again for looking into this.

**Comment by Samikana** [comment]
Perhaps Teo thinks otherwise, but I think a plethora of people is too much to push past.  Unless Teo states otherwise, you're going to need to wait until it's fixed.

**Comment by TeoTwawki** [comment]
Yeah I do not wanna have a lot of people just totally skipping a battlefield+cs altogether.

**Comment by TeoTwawki** [comment]
Some folks gonna have to wait while I fix it.

**Comment by TeoTwawki** [comment]
Github is being retarded and eating my comments here.

**Comment by Quillarts** [comment]
Ok, Well, I'm around. Just let me know. Thanks

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
