### ISSUE TITLE
Woodworking Recipe: Kapor Lumber (97)

### ISSUE THREAD

**Issue by Schaedelschaden** [LegionDark/Issues#474]
Kapor Lumber not listed on AH, found bug(?) while attempting to synth Kapor Log with Wind Crystal to generate Kapor Lumber.

**Comment by R3P0FFXI** [comment]
I believe this recipe is part of the refactor and crafting update

**Comment by Samikana** [comment]
@R3P0FFXI it's not.  It's part of a recipe, but it isn't one that's scheduled to get coded.  So unless you made the ingredient's recipes as well, it's not.  I would check.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
