### ISSUE TITLE
ZM9

### ISSUE THREAD

**Issue by Samikana** [LegionDark/Issues#475]
**Date & Time**: 16:59 15/20/12
**Frequency**: Happened on both characters
**FFXI Client Version**: 30151103_3
**Character Name**: Ezra
**Race**: Mithra
**Nation**: Bastok
**Main Job**: WHM99
**Sub Job**: RDM49
**Area & Coordinates**:320 0 -11 191
**Party or Solo**: Party of 2
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: N/A 
**Multi-boxing? (multiple clients on same connection)**: yas
**Steps To Reproduce The Issue**: N/A

Black screen after ZM9 fight.

**Comment by Samikana** [comment]
This may be because I had been dualboxing and dualboxed the fight as well.  No other complication so going to close.  I'll re-open if I hear anyone else having an issue with it.

**Comment by Arrytha** [comment]
Just had this problem. However, I think it's ZM8 fight against Kam'lanaut? Finished him off (not dualboxing) and stuck on black screen.
