### ISSUE TITLE
Sand'Oria Mission 2-3

### ISSUE THREAD

**Issue by BeguZoo** [LegionDark/Issues#477]
**Date & Time**: 21/12/2015
**Frequency**: always
**FFXI Client Version**: 30151103_3
**Character Name**: Bigbiggiant
**Race**: Galka
**Nation**: sand'oria
**Main Job**: WAR
**Sub Job**: NIN
**Area & Coordinates**: Burning Circle
**Party or Solo**: party/solo
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: N/A
**Steps To Reproduce The Issue**: entering the Burning Circle and receiving a cutscene then deadlocked.

**Comment by Samikana** [comment]
I'll fix your mission but this is getting closed because it's a repeat of #472
