### ISSUE TITLE
Problem with obtaining boarding permit

### ISSUE THREAD

**Issue by ruin2it3** [LegionDark/Issues#478]
**Date & Time**: 12/20-21/15
**Frequency**: Constant
**FFXI Client Version**: 30151103_3
**Character Name**: Ruhi
**Race**: Mithra
**Nation**: Bastok
**Main Job**: THF
**Sub Job**: DNC
**Area & Coordinates**: Various
**Party or Solo**: Both
**NPC or Monster Name**: Faursel
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Obtain all 6 subjob items and trade to npc Faursel in Lower Jeuno - On doing the mini-quest for boarding permit to go to Whitegate it is impossible to go to Whitegate/Al Zhabi if the quest is completed by use of the 6 Sub Job items.

With correct key item, I am unable to board the boat to Whitegate. The correct boat comes to Mhaura, docks and upon departure it leaves the passenger and the room behind. (No cutscene is triggered, and the character is not zoned)

![ruhi_2015 12 21_000143](https://cloud.githubusercontent.com/assets/8246990/11941788/bbcc78c8-a7f7-11e5-985e-b30b321b113c.png)
![ruhi_2015 12 21_000156](https://cloud.githubusercontent.com/assets/8246990/11941791/c0f881fc-a7f7-11e5-8c8a-d8608e6a19f6.png)
![ruhi_2015 12 21_000312](https://cloud.githubusercontent.com/assets/8246990/11941794/c48cec0e-a7f7-11e5-8b2a-ea8e779a3d6c.png)

I was unable to trigger the permit NPC to warp me similar to just taking the 500k gil option.

**Comment by Samikana** [comment]
Please use the template found on [url=https://github.com/LegionDark/Issues]this[/url] page

**Comment by ruin2it3** [comment]
Updated to follow the template.

**Comment by Samikana** [comment]
@TeoTwawki this is a DSP issue correct?

**Comment by TeoTwawki** [comment]
Yeah. Dunno why it happens exactly but its been reported to them before.

**Comment by TeoTwawki** [comment]
Only Bibiki bay's boat has a known cause (it has multiple routes, and 1 doesn't exist).

**Comment by ruin2it3** [comment]
IMO - we should just warn players beforehand and/or disable other methods of completing the quest till DSP gets this ironed out. I'd consider this "issue" closed.

**Comment by TeoTwawki** [comment]
the boat really has jack to do with the quest itself, the boat glitch is a separate thing. the quest should award the KI, if it does not, then there a quest bug separate from the boat glitch.
