### ISSUE TITLE
Cannot get to Yannei

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#48]
**Date & Time**:  6/1/15
**Frequency**: Always
**FFXI Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: NA
**Main Job**: NA
**Sub Job**: NA
**Area & Coordinates**: Abyssea Attohwa
**Party or Solo**: NA
**NPC Name**: NA
**Monster Name**: Yannei
**Steps To Reproduce The Issue**: The attohwa mountain does not work properly, and thus cannot be climbed. Cannot get to NM Yannei because of this.

**Comment by TeoTwawki** [comment]
Elaborate on doesn't work properly please. Like..one of those gas cloud walls stuck in an always up state, or what?

**Comment by PikaFox** [comment]
Gas clouds in abyssea on the mountain dont exist afaik, hell i dont know if they exist at all in abyssea currently (or if theyre supposed to).

**Comment by TeoTwawki** [comment]
I just need to know what exactly is stopping you from going up..Still haven't said.

**Comment by PikaFox** [comment]
Theres a crack in the ground where in the present gas would be, it just doesnt let you continue. Its hard for me to explain, its a bit easier to go there yourself and try it unfortunately. Its when you start climbing the mountain, the first gas part. I couldnt get past it.

**Comment by TeoTwawki** [comment]
So invisible wall, basically.

**Comment by PikaFox** [comment]
Yes.

**Comment by Loki79** [comment]
This ever addressed?  if not ill just move the damn NM.

**Comment by TeoTwawki** [comment]
@Loki79 I have a plan for this but haven't had a chance to actually do it yet

**Comment by R3P0FFXI** [comment]
@TeoTwawki please add this to the custom refactor I now need to place some items on this mob

**Comment by TeoTwawki** [comment]
its now fixed in the update branch, with an NPC at **J-9** in Abyssea-Attowha to teleport players past the barriers.

**Comment by R3P0FFXI** [comment]
Issue fixed in Update closing
