### ISSUE TITLE
-Missing items- miscellaneous

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#480]
Date & Time: 23/12/15
Frequency: Constant
FFXI Client Version: 30151103_3
Character Name: Thranduil
Race: hume
Nation: Bastok
Main Job: THF
Sub Job: DNC
Area & Coordinates: Various
Party or Solo: Both
NPC or Monster Name: 
ffxiah.com link (for inventory items only): 
http://www.ffxiah.com/item/10605/avant-leggings-1
http://www.ffxiah.com/item/11980/calma-hose
http://www.ffxiah.com/item/1321/eabjuration-hn
http://www.ffxiah.com/item/10441/shedir-turban
http://www.ffxiah.com/item/10370/shedir-crackows

http://www.ffxiah.com/item/19255/mavi-tathlum
http://www.ffxiah.com/item/11614/ardor-pendant
http://www.ffxiah.com/item/11465/mirage-keffiyeh

Multi-boxing? (multiple clients on same connection): no

Referring to this post: http://legiondark.com/forums/viewtopic.php?f=10&t=1159
I've found some non coded items which should be in game; nothing groundbreaking, but here they are (for completion sake).
In addition: are "augments breath damage" items supposed to be working with blu spells or not?
Thank you.

**Comment by Samikana** [comment]
I'll do my best to get these in-game before the update, but honestly, I'm struggling to find time to do the ones I have now.

**Comment by R3P0FFXI** [comment]
Huh, These items are already in game

**Comment by R3P0FFXI** [comment]
@Samikana No idea what this person is talking about these items are all coded or should be already

**Comment by simthra** [comment]
That's weird because the drop tool does not list them at all and I've been unable to obtain them, even through extensive farming.
And i've also tested the breath dmg modifier. It's not working.

**Comment by Samikana** [comment]
You mean they don't DROP or when you lot them, they floor...?

I think your luck is just shitty.  I've personally gotten some of these items, but I'll check it tonight if I have time

**Comment by Samikana** [comment]
I just looked.  All of this is coded.

**Comment by simthra** [comment]
Then drop tool is wrong.

**Comment by Samikana** [comment]
Drop tool shows it's all coded.  The items would not have a result if they weren't in the database

**Comment by R3P0FFXI** [comment]
Big difference between not dropping off a mob and not coded in the database at all, if these are coded and do not drop from a mob thats a completely different issue then what you reported
