### ISSUE TITLE
Bastok Mission : The Emissary (2-3)

### ISSUE THREAD

**Issue by Reaps989** [LegionDark/Issues#481]
Date & Time: 12/23/15
Frequency:　Everytime
FFXI Client Version: type/ver to get this　30151103_3
Character Name:　Nysek
Race:　Hume
Main Job:　WHM
Support Job:　SCH
Area and Coordinates: 305, 123, 379 (Zone in point before entering mission)
Party or Solo:　ｓｏｌｏ
NPC Name:　Searcher
Monster Name: Searcher & Black Dragon
Steps:
　　http://wiki.ffxiclopedia.org/wiki/The_Emissary
　”Go to the deepest parts of Giddeus and destroy the horrible beast terrorizing the Yagudo ”

Completed the San d'Oria one of killing the Warchief, now I cannot finish the Windurst one as the cutscene is locked only allowing me to watch a 30 minute timer.

"One who will rally the beastman hordes on a grand campaign to rid the world of you and your kind." is said by Searcher before it locks up.

So I am unable to complete the fight to rank up... I can at least zone out with @return thankfully.

**Comment by Samikana** [comment]
Repeat of #472.  Closing this because it's a known issue that is being worked on.  I'll be on today to push you past the mission tonight.

**Comment by Reaps989** [comment]
Might I need to be online for that?

**Comment by PikaFox** [comment]
If a GM is going to do anything with your character you need to be online for it unless they tell you otherwise.

**Comment by Samikana** [comment]
I fixed him

**Comment by Bushuru** [comment]
Hi there, please add me to the 2-3 push que.  I'm in no hurry, I'll catch ya online at some point. - Bushuru.   
P.S.  Do i need to open a ticket or is this post sufficient?  (/ver=30151215_0)

**Comment by PikaFox** [comment]
Its recommended you open your own ticket so we can view the open ticket queue to see whats needed still.

Also the ticket will allow us to see exactly who in game has the issue, without the template id have to assume your in game name is bushuru.

**Comment by TeoTwawki** [comment]
its kind of why its called a tracker :smiley:
