### ISSUE TITLE
Frequent FFXI client shutdown

### ISSUE THREAD

**Issue by thiefx** [LegionDark/Issues#482]
**Date & Time**: Any day, any time. Most recent was 10:47PM PST.
**Frequency**: Roughly once per hour.
**FFXI Client Version**: 30151103_3
**Character Name**: Uubu
**Race**: Mithra
**Nation**: Bastok
**Main Job**: PLD
**Sub Job**: DNC or WAR
**Area & Coordinates**: Any location, most recent was in Dynamis Beaucedine.
**Party or Solo**: Both party and solo.
**NPC or Monster Name**: Most recent was Hydra Samurai in Dynamis Beaucedine.
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No. Although I have dual-boxed a few times, it can happen on either client.
**Steps To Reproduce The Issue**: It happens every hour, I believe mostly in combat (i'm usually fighting anyways, hard to tell). When I try using an ability, could be ANY ability, magic or WS, the client has a chance to shut down completely without any warning.

**Comment by R3P0FFXI** [comment]
we need to know exactly what happens when this happens, what spell/ability you or the mob you were fighting was using etc

**Comment by Samikana** [comment]
Uubu is on the same version as I am and I don't experience these crashes and I've heard no one else speak of crashing randomly, so perhaps you should try a file repair and tell us what happens.

**Comment by R3P0FFXI** [comment]
@Samikana this can be caused by various mobs/abilities the player is fighting using or being used on the player, this is why im asking for a list first before we proceed to ask the user to run the repair.

**Comment by thiefx** [comment]
I did the check files and it repaired a couple things, seems to be working great now. Thanks yo!
