### ISSUE TITLE
Trial Moogles are Broken

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#483]
**Date & Time**: 
**Frequency**: Constantly
**FFXI Client Version**: 30151103_3
**Character Name**: Daedrik
**Race**:Elvaan
**Nation**:Bastok
**Main Job**:PLD
**Sub Job**:RDM
**Area & Coordinates**:All Trial Moogles
**Party or Solo**: both
**NPC or Monster Name**: Trial Moogles Weapons-Armor
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Trial Weapons mog dont give any dialogue while Armor mogs dont acceptt trades.

**Comment by TeoTwawki** [comment]
Did some checking, the one in RuLude seems 100% working, and the ones in port responded properly for me but I didn't thoroughly check that the mission requirements were accurate - I just set my test character to "everything 100% cleared" and then "nothing cleared".

**Comment by Samikana** [comment]
Feel free to reopen if you continue to have an issue but this is a month old and no one else is having an issue.  Please make sure you've met all of the requirements and are speaking to the correct moogle.  Thanks.
