### ISSUE TITLE
Voidwatch-NM-Bastok

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#484]
**Date & Time**: 
**Frequency**: once
**FFXI Client Version**: 30151103_3
**Character Name**:Daedrik
**Race**:Elvaan
**Nation**:Bastok
**Main Job**:PLD
**Sub Job**:RDM
**Area & Coordinates**: North Gustaberg  X:797 Y:0 Z:439 (251)
**Party or Solo**:Party
**NPC or Monster Name**: Sallow Seymour
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: Kill Sallow Seymour.  NM went to 0% HP but did not drop loot or despawned, it just stood there and did nothing. 

Also my characters voidstone was expended and i could not pop it again. Not sure if kill counted.

**Comment by Samikana** [comment]
I tried to force despawn this with commands and nothing happened.

**Comment by TeoTwawki** [comment]
Its another mob effected by the despawn bug from not checking the actionqueue before sending the command to despawn. This bug was triggered by the fight taking longer than 30 min.

**Comment by TeoTwawki** [comment]
A fix will be included in the update.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
