### ISSUE TITLE
The ferry from Mhaura to the Empire of Aht Urhgan.

### ISSUE THREAD

**Issue by Darkgiox** [LegionDark/Issues#485]
**Date & Time**: 8pm Est
**Frequency**: Once
**FFXI Client Version**: 30151103_3
**Character Name**: Giovanni
**Race**: Hume
**Nation**: San Doria
**Main Job**: Thief
**Sub Job**: Dancer
**Area & Coordinates**: Ferry from Mhaura to the Empire of Aht Urhgan.
**Party or Solo**: Solo
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Board Ferry from Mhaura to the Empire of Aht Urhgan.

The issue is it takes way to much time to get to Aht Urhgan, even when you speak to the npc he says 0 hours , it took me at least 5 mins after i speaked to the npc.

**Comment by TeoTwawki** [comment]
You only ever have to ride the boat once (and that's only if you don't want to pay gil during the quest) after that if you've done the first mission and done the quest(s) "Lure of The Wildcat" you can warp directly to whitegate. http://ffxiclopedia.wikia.com/wiki/Lure_of_the_Wildcat

**Comment by PikaFox** [comment]
The NPC does not give the correct time, theres no issue here. The ferry lasts the proper duration.
