### ISSUE TITLE
Change account password

### ISSUE THREAD

**Issue by BeguZoo** [LegionDark/Issues#486]
**Date & Time**: 27/12/2015 14:16
**Frequency**: Always
**FFXI Client Version**: 30151103_3
**Character Name**: Begu & Zoo
**Race**: Tarutaru & Mithra
**Nation**: Sand'Oria
**Main Job**: 
**Sub Job**:
**Area & Coordinates**:
**Party or Solo**:
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**: I found my these two accounts always login by others, this maybe my account password not security enough. Can i or how can i change my password to prevent this happen again. Please help.

**Comment by TeoTwawki** [comment]
Need to contact Myself, or @R3P0FFXI via private message in forums or in IRC when we're around, and we can get that changed for you.

**Comment by BeguZoo** [comment]
Please help change these two accounts password, 1.(Begu) username: 1234567
2.(Zoo) username: 12345678
Someone still login these two accounts at that time :( last time i lost all
my gil and dynamic coins.
Any information required, please let me know, thanks.

2015-12-27 15:51 GMT+08:00 TeoTwawki <notifications@github.com>:

**Comment by TeoTwawki** [comment]
sigh. You just publicly stated passwords on github. I told you what you need to do. We can't help you till we're communicating privately.

**Comment by TeoTwawki** [comment]
Also, thats the same combination on my luggage! (and a really bad idea for a password)

**Comment by TeoTwawki** [comment]
User's passwords have been changed after talking on IRC.
