### ISSUE TITLE
Mission 2-3 Disconnect on Boss

### ISSUE THREAD

**Issue by Shadowgar** [LegionDark/Issues#487]
**Date & Time**:  12/27/2015 0856
**Frequency**: Every time I zone in.
**FFXI Client Version**: 30151215_0
**Character Name**: Shadowga
**Race**:hume female
**Nation**:Bastok
**Main Job**: Warrior
**Sub Job**:none
**Area & Coordinates**: x:316 Y:-123 Z:379
**Party or Solo**:Solo
**NPC or Monster Name**: Mission 2-3 Seeker and Dragon
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:No
**Steps To Reproduce The Issue**:

Need to complete the Mission 2-3, I enter area and my account logs out.

**Comment by Shadowgar** [comment]
I am on today till noon EST and will not return from work till Monday noon. It seems I have to be online for this to be fixed. Let me know a time and date and I can attempt to get online.

**Comment by Samikana** [comment]
Another repeat of #472.  

Closing.  Contact Halsey in-game when you see me online and I'll keep an eye out for you.
