### ISSUE TITLE
Server Lag Issues

### ISSUE THREAD

**Issue by R3P0FFXI** [LegionDark/Issues#488]
**Date & Time**: Random
**Frequency**: Frequent
**FFXI Client Version**: Any
**Character Name**: God
**Race**: NA
**Nation**: NA
**Main Job**: NA
**Sub Job**: NA
**Area & Coordinates**: NA
**Party or Solo**: Party/Alliance
**NPC or Monster Name**: NA
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Multiboxing
**Steps To Reproduce The Issue**:

Form party
Kill stuff until lag occurs while logging packets
Note the exact time lag gets bad, so we can cross-reference it with the packet log
Disband after and shutdown, log back in and see if lag disappears

This ticket is for the logging of packets during testing for lag issues. DO NOT POST IN THIS THREAD IF YOU ARE NOT LOGGING PACKETS! If you post anything but packets in this thread and are not a GM expect your posts to be deleted this is for ADMIN and Packet Team tracking purposes ONLY!

**Comment by TeoTwawki** [comment]
Aaaaand zero posts were given. Its like the players version of how many ~~fu~~ er, cares, you give about stuff. :smiley:

**Comment by R3P0FFXI** [comment]
Issue resolved with DSP Commit by TEO to stop logging Navmesh Errors

**Comment by TeoTwawki** [comment]
Note: there were other lag fixes as well, done in DSP: status effects were one source, extra update packets that weren't needed were another. But it seems the bulk of LegionDarks lag was simply disc i/o from excessive logging of meaningless data that was marked as important. Before my change you couldn't avoid logging those without turning off ALL error logging.
