### ISSUE TITLE
Lightning Carol II

### ISSUE THREAD

**Issue by LuckyBane** [LegionDark/Issues#489]
**Date & Time**: 12:38pm, 29/12/2015
**Frequency**: Constant.
**FFXI Client Version**: 30151103_3
**Character Name**: Fletcher
**Race**: Galka
**Nation**: Windurst
**Main Job**: Bard
**Sub Job**: Dancer
**Area & Coordinates**: All
**Party or Solo**: Solo
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/5058/lightning-carol-ii
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Try to use Lightning Carol II scroll as Bard mainjob at level 99.

Error message states that the character is unable to learn the spell. All other Carols work.

**Comment by R3P0FFXI** [comment]
@Samikana please look at this in item tables etc

**Comment by Samikana** [comment]
It has an item_basic entry, I don't know where else you'd want me to look

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
