### ISSUE TITLE
Mission 5-1 Crash Midfight

### ISSUE THREAD

**Issue by neverendingsquad** [LegionDark/Issues#490]
Crashed during 5-1 Fei'Yin fight, logged back in, redid fight, still no credit. No post-fight KI.
 Have SS of log:

![img_20151228_205542](https://cloud.githubusercontent.com/assets/16470262/12028538/b96ae54c-ada6-11e5-9d72-395be1d6e164.png)

**Date & Time**: 12/28/15 9PM EST
**Frequency**:Once
**FFXI Client Version**:30151103_3
**Character Name**:Artax
**Race**:Hume
**Nation**:Bastok
**Main Job**:War
**Sub Job**:Sam
**Area & Coordinates**:Fei' Yin
**Party or Solo**:Party
**NPC or Monster Name**:Archlich Taber'quoan 
**ffxiah.com link (for inventory items only)**:N/A 
**Multi-boxing? (multiple clients on same connection)**:Yes
**Steps To Reproduce The Issue**:DC midfight?

**Comment by R3P0FFXI** [comment]
Whenever you multibox you run the risk of things not completing right. Please try again this time do not multibox.

**Comment by neverendingsquad** [comment]
Fought again, running only one character. worked fine. 
thank you for the response. 
i have learned something.
~Artax
