### ISSUE TITLE
Whence Blows the Wind (Limit break 3)

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#491]
**Date & Time**: 12/28/2015
**Frequency**: repeatedly tried to no avail
**FFXI Client Version**:30151103_3
**Character Name**: Daedrik
**Race**:Elvaan
**Nation**:Bastok
**Main Job**:PLD
**Sub Job**:NIN
**Area & Coordinates**: All 4 Davoi Ponds  (H-10)(L-9)(E-8)(H-6)
**Party or Solo**: Party And  Solo
**NPC or Monster Name**: Sedal-Godjal (J-8)
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**:

 -Start Limit break 3 go to Davoi.
-Touch the Wall of Banishing (J-9).
- Speak to Sedal-Godjal to start mini quest and then travel to the 4 ponds.

"White Orb" KI doesnt change color and CS in "Wailing Pond" makes the character model go crazy.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
