### ISSUE TITLE
Auction House Bug

### ISSUE THREAD

**Issue by FatePGN** [LegionDark/Issues#492]
So I think the auction house is bugged.

If you use @ah and start selling things, so long as you don't close the menu, you can sell up to 80 items (inventory limit), and it gives you all the money in the delivery box still from AH bot.

**Comment by TeoTwawki** [comment]
The part about selling more than 7 would be a brand spanking new DSP bug if true, as we haven't done the customization to allow that (there is a way to accomplish it on purpose, but it breaks if you view your sales status). Its entirely possible you were mid listing and the AH bot kicked in. In fact its very likely if you got gil right away in your delivery box as the bot does its buying in and selling in spurts at regular intervals.

**Comment by FatePGN** [comment]
Oh that's possible, I did get my gil right away, I'll try and test on an off hour from the AH bot

**Comment by Samikana** [comment]
@TeoTwawki being able to list more than 7 items has always been around on the server as long as I've been here.

**Comment by TeoTwawki** [comment]
@sami I don't recall making the change. /shrug

not really worried about it but if it was a a dsp bug I'd want them to know

**Comment by Samikana** [comment]
This isnt really being addressed and I don't think it's a "bug" but if @TeoTwawki or @R3P0FFXI  wants to fix it at some point, they're open to.  Otherwise I'm going to close it as it's not being worried about and it doesn't matter.  Feel free to open it again if we address it at a later time ofc.

**Comment by FatePGN** [comment]
Should probably not close this. I stopped playing, but I can easily make 50m with this bug per auction house bot cycle.

Not sure if you guys intend for that, but yeah, completely broken.

**Comment by TeoTwawki** [comment]
@FatePGN gil is kind of a bad joke, as long as the only thing this is allowing is using extra slots, my only concern is if there was an unreported dsp bug or a deliberate change that my swiss cheese memory forgot about us doing.

**Comment by Samikana** [comment]
People are abusing the auto sell feature

**Comment by Samikana** [comment]
It has been known for a while though

**Comment by TeoTwawki** [comment]
elaboration: legion decided early on that its desired for  (and farmers) to make tons of cash, we just limit the restock intervals and amounts and buyback rate to prevent getting multiple crafts leveled 0 to 100 in a day.

**Comment by TeoTwawki** [comment]
elaboration: legion decided early on that its desired for crafters (and farmers) to make tons of cash, we just limit the restock intervals and amounts and buyback rate to prevent getting multiple crafts leveled 0 to 100 in a day.

**Comment by TeoTwawki** [comment]
@Samikana abusing how exactly?

**Comment by Samikana** [comment]
Buying things that sell lower per stack and selling per item.  I'll talk to you abt it next time i'm on IRC

**Comment by TeoTwawki** [comment]
thats a completely different issue

**Comment by TeoTwawki** [comment]
just confirmed it as a dsp bug.
