### ISSUE TITLE
Faf + Nidhogg spawn

### ISSUE THREAD

**Issue by Fenrir001** [LegionDark/Issues#493]
They spawn at the same time! So after the request o' Hal, here it be. One bug report to report Faf and Nidhogg for cheating.

**Comment by TwIzTiD2469** [comment]
bug reports are supposed to look like this:

Nidhogg, Aspid, King Behemoth take about 5-8 days to repop.
Fafnir, Adamantoise, Behemoth take about 45min-8hours to repop.
More often than not when the HQ pops the NQ is also up along side it.

**Date & Time**: 12/29/2015 afternoon sometime for KB, 12/30/2015 3:00PM EST~ just before server reboot Fafir and Nidhogg were both up.
**Frequency**:Always
**FFXI Client Version**:30151103_3
**Character Name**:Kamikaze
**Race**:Galka
**Nation**:San d'Oria
**Main Job**:DRK
**Sub Job**:SAM
**Area & Coordinates**:Behemoth's Dominion, Dragons Aery, Valley of Sorrows
**Party or Solo**:Solo till pop
**NPC or Monster Name**:King Behemoth, Aspid, Nidhogg, Fafnir, Adamantoise, Behemoth
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:After pop yes
**Steps To Reproduce The Issue**:Stand and wait days for pop on HQ

**Comment by R3P0FFXI** [comment]
I am being told also that HQ are not popping within the designated window so its possible we are missing HQ timers somewhere

**Comment by TeoTwawki** [comment]
> They spawn at the same time! 

@R3P0FFXI I fixed this in darkstar awhile ago, but LegionDark didn't get that fix because of update delays. You can copy the scripts for the 6 land kings out of the update branch into the live server and it'll be fine.

> TwIzTiD2469 : Stand and wait days for pop on HQ
> R3P0FFXI R3 : I am being told also that HQ are not popping within the designated window

I've verified and reverified over and over, every single time its been someone not understanding how the timing reset works or plain missing an out of sight range pop+kill. Every. Single. Time.

**Comment by TeoTwawki** [comment]
p.s.
Them being up at the same time isn't rally a bug, it was intended but no longer default behavior due to the confusion it caused.

When kings were both force pop and timed at the same time, this was necessary.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/commit/3b8d4f3c3d7aeb857cd78a345ef978d57b7d5130?w=1 for reference

**Comment by R3P0FFXI** [comment]
@TeoTwawki @Samikana I ran a hotfix and dropped the massive update king files on the server since we do not need a reboot to do this, the dsp fixes Teo did a month or 2 ago should now be active on Legion

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
