### ISSUE TITLE
PM8-3

### ISSUE THREAD

**Issue by Samikana** [LegionDark/Issues#494]
**Date & Time**: 12/31/15 14:46
**Frequency**: Consistent
**FFXI Client Version**: 30151215_0
**Character Name**: Ezra
**Race**: Mithra
**Nation**: Bastok
**Main Job**: WHM
**Sub Job**: RDM
**Area & Coordinates**: 419 0 437 193
**Party or Solo**: Party and solo
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: Yes, but have tried without
**Steps To Reproduce The Issue**: Tried changing my own var, can't get it to work

I cannot get the CS/fight to trigger at the Particle Door and I have tried changing my own var but so far no luck.  need @TeoTwawki to walk me through how to fix this piece of shit

**Comment by PikaFox** [comment]
Assuming you got both brands to go up the elevator; did you get your race light as well? The fight did work before, and generally when it hasnt its been because of either not getting the brands or race light.

**Comment by Samikana** [comment]
I have them both.  It's something I have to talk to Teo about.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
