### ISSUE TITLE
Legion Upgrade Moogle

### ISSUE THREAD

**Issue by Quillarts** [LegionDark/Issues#495]
**Date & Time**: 1/2/16 4:30AM PST 
**Frequency**:  multiple attempts
**FFXI Client Version**: 30151103_3
**Character Name**: Hakushi
**Race**: Taru
**Nation**: Sandoria
**Main Job**: BLU
**Sub Job**: RDM
**Area & Coordinates**: Rolanberry Fields 243/479/24
**Party or Solo**: Solo
**NPC or Monster Name**: Moogle
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/28190/weathersp-pants
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**: Moogle does not accept trade of items to upgrade legion gear to +1. Traded moogle Weatherspoon pants + 20 Tanzanite gems, no response. Tried with boots, no response. I do have enough Legion points (6,200)

Doing this in reference to the post: http://legiondark.com/forums/viewtopic.php?f=40&t=594&p=3533&hilit=legion#p1764

**Comment by goferffxi** [comment]
Aren't the watherspoon pants ilvl106? I thought the moogle legion upgrade only worked with ilvl100. The upgrade would push them to ilvl109.

**Comment by Samikana** [comment]
It only works with the iLvl. 100 stuff.  We don't have a system implemented to upgrade iLvl 106.
