### ISSUE TITLE
Problem with MNK Maat fight

### ISSUE THREAD

**Issue by ruin2it3** [LegionDark/Issues#496]
**Date & Time**:  1/2/16 - 10:15 PM Central
**Frequency**: On first Maat fight attempt
**FFXI Client Version**:  30151103_3
**Character Name**: Misstical
**Race**: Mithra
**Nation**: Bastok
**Main Job**: MNK - 70
**Sub Job**: WAR or N/A
**Area & Coordinates**: Rulude Gardens/Balga's Dias
**Party or Solo**: Solo
**NPC or Monster Name**: Maat
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: Fight Maat for limit break as MNK - upon winning fight, under Hundred Fists (with medicated status) - Maat did not drop a warp scroll, but rather an Aqua Geode. The quest does not finish, no CS, and Maat did not offer the "after win" dialogue.

![misstical_2016 01 02_221459](https://cloud.githubusercontent.com/assets/8246990/12077559/4fe3cf50-b1a0-11e5-9682-0a874d68e226.png)
![misstical_2016 01 02_221612](https://cloud.githubusercontent.com/assets/8246990/12077560/54eaa3c0-b1a0-11e5-8b8b-282445fd0986.png)

**Comment by R3P0FFXI** [comment]
Yeah not going to lie here I talked this over with Teo and we got nothin on this one as Maat has been in DSP forever and has not been changed. By chance you dont have a warp scroll already in your inventory do you?

**Comment by Samikana** [comment]
It's worth mentioning that there was two other player (whose names escape me as they're new) who did their maat fights on MNK about an hour after Misstical and they had no issue.  

@Ruin2it did you ever get it figured out or are you still experiencing the issue?  If not and Repo's possibility doesn't solve the issue,we can figure it out tonight when I log on.

**Comment by TeoTwawki** [comment]
Having a warp scroll would stop the drop, but wouldn't stop getting credit. I don't know how this is even possible without a multi box glitch. Are other jobs clearing Maat ok?

**Comment by Samikana** [comment]
@TeoTwawki I've personally not seen any players complain about their maat fights being inconclusive.  Misstical and Ruhi play on the same network though.

**Comment by TeoTwawki** [comment]
> Misstical and Ruhi play on the same network though. 

Server would very likely treat it the same as a single player multiboxing then, and have the same glitches, which would explain their problem

**Comment by TeoTwawki** [comment]
Multi-boxing is defined in the template as **multiple clients on same connection**, and **not** as one person with multiple characters, for exactly this reason.

**Comment by Samikana** [comment]
@ruin2it3 Try doing this again without dualboxing before we investigate further.

**Comment by R3P0FFXI** [comment]
@TeoTwawki @Samikana I spoke to Ruhi and he stated that only 1 character Misstical was logged into the game when this happened. Tho i do agree for you to attempt this again @ruin2it3 as this is very perplexing and has all of us scratching our heads here.

**Comment by R3P0FFXI** [comment]
Also if you at any time when you go to retry make sure you have logged both PCs out to fully clear the system then just login Misstical and attempt again

**Comment by Samikana** [comment]
Just saw Misstical in-game, they were level 72 MNK.

**Comment by PikaFox** [comment]
They did the war maat fight.

**Comment by TeoTwawki** [comment]
There no coding for war fight thats any different from the mnk fight, so if that worked it ain't busted.

**Comment by ruin2it3** [comment]
I'll go ahead and try this again with her when I get some free time this weekend.
The difference I saw between the MNK fight and the WAR fight was the location.
WAR took place in Waghroon Shrine while the MNK fight was in Balga's Dias.
That's why I was asking if perhaps it might have been an issue relating to code for the zone.
I know that's just reaching for straws, but it would tie in with difficulty completing mission fights in the same area.

**Comment by TeoTwawki** [comment]
All Maat fight code is identical at all locations though, just so you know. The different jobs just send you to another place with identical code.
