### ISSUE TITLE
Fists of fury +1 not working.

### ISSUE THREAD

**Issue by Zeldha** [LegionDark/Issues#497]
The unity ranking isn't working...

![vida_2016 01 03_171505](https://cloud.githubusercontent.com/assets/16524259/12078065/99d8ac50-b23d-11e5-9f0c-3fcc372f61cc.png)

**Comment by PikaFox** [comment]
Afaik unity ranking mods dont exist in DSP.

**Comment by TeoTwawki** [comment]
Pika is correct.

**Comment by Zeldha** [comment]
is this mean, all unity ranking not works?

**Comment by TeoTwawki** [comment]
There's no unity rank coded into darkstar yet, nor any modifier to apply based on it, so those stats can't be done for any item. I am also steadfastly against any substituting, as that makes things much more annoying when it actually does get implemented.

**Comment by Samikana** [comment]
@TeoTwawki when Loki had me doing unity gear, he had me add the unity ranking onto any pre-existing mod or just create a new entry with the stat

**Comment by TeoTwawki** [comment]
GRRRR -_-

**Comment by Zeldha** [comment]
Did someone doing something with the weapon?
If the unity ranking not works, its just fine, but now i am unable to engage if using this weapon.

**Comment by TeoTwawki** [comment]
@R3P0FFXI Tag you're it.
