### ISSUE TITLE
Relic Trials  Not being credited

### ISSUE THREAD

**Issue by Nemesisx** [LegionDark/Issues#498]
**Date & Time**:  January 5th 2016 8:00 AM
**Frequency**: First time
**FFXI Client Version**:30151103_3
**Character Name**: Nemesisx
**Race**: Hume
**Nation**:Bastok
**Main Job**: Bard
**Sub Job**:whitemage
**Area & Coordinates**: Behemoth's Dominion
**Party or Solo**: Party
**NPC or Monster Name**: King Behemoth
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: 2nd time I have killed King Behemoth and did not get credit for the kill, and yes GHorn was equipped when it died and I was still alive Trial ID:18580

**Comment by R3P0FFXI** [comment]
Please post a picture of what G horn you actually have

**Comment by Nemesisx** [comment]
![ghorn 95](https://cloud.githubusercontent.com/assets/12467043/12134602/1589f352-b3ee-11e5-9288-e9a94c1bb7fc.png)

**Comment by Samikana** [comment]
@Nemesisx please send me a tell in-game and i will update your trial in the meantime

**Comment by Samikana** [comment]
This is fixed
