### ISSUE TITLE
Cannot equip Aeolus Arrow with Bow

### ISSUE THREAD

**Issue by bartonkt** [LegionDark/Issues#5]
**Date & Time**: 16:24:47 (Mountain Time), 5/25/15
**Frequency**: every time i try to equip
**FFXi Client Version**: 30150508_8
**Character Name**: Cyrilla
**Race**: Elvaan (dhamel)
**Main Job**: Ranger
**Sub Job**: Samurai
**Area & Coordinates (Type @where to get this info.)**: Mog house
**Party or Solo**: Solo
**NPC Name**: N/A
**Monster Name**: N/A
**Steps To Reproduce The Issue**:

1. Equip Bow
2. Equip Aeolus arrow in ammo slot
3. Equipping the arrow de-equips the bow. 

This makes it impossible to use the arrow for Unlimited Shot > WS.

**Comment by R3P0FFXI** [comment]
Will look at this after extended maint is completed

**Comment by maikuru23** [comment]
This also happens with the lvl85 relic annihilator gun and any ammo.  Equipping ammo unequips gun, equipping gun unequips ammo.

**Comment by TeoTwawki** [comment]
@maikuru23 now that we have an actual tracker issue we're no longer trying to catch every gear bug in a single place, can you open a separate issue for the l85 Annihilator for me to Todo-Tag? Thanks

**Comment by R3P0FFXI** [comment]
INSERT INTO `item_weapon` VALUES (19193,'aeolus_arrow',19,0,1,1,90,46,0);

19 is not a valid skill 25 is Archery

**Comment by Loki79** [comment]
fixed, will come in with Tuesday maint.
