### ISSUE TITLE
Unable to unlock BLU, Crash during CS

### ISSUE THREAD

**Issue by Unmaligned** [LegionDark/Issues#500]
Date & Time: 01/07/2016 at 10:00pm est
Frequency: Everytime.
FFXI Client Version: Version 30151215_0
Character Name: Unmaligned
Race: Elvaan
Nation: San d'Oria
Main Job: Beastmaster
Sub Job: Warrior
Area & Coordinates: Aydeewa Subterrane, X: 380, Y: 0, Z:330 (61)
Party or Solo: Solo
NPC or Monster Name:
ffxiah.com link (for inventory items only): None
Multi-boxing? (multiple clients on same connection): No
Steps To Reproduce The Issue: In the zone Aydeewa Subterrane, I step upon the pool of water to start the final CS to unlock blu. Client will crash right after the text ???? says "he's waking up".

**Comment by Samikana** [comment]
I told @PikaFox fix him because i'm ay school

**Comment by PikaFox** [comment]
Done
