### ISSUE TITLE
Blessed Briault synth : Cratfing Mats locked (greyed) upon failed synth

### ISSUE THREAD

**Issue by Valena07** [LegionDark/Issues#503]
**Date & Time**: 011216
**Frequency**: Always
**FFXI Client Version**: 30151204_2
**Character Name**: Valenya
**Race**: Taru
**Nation**: Windurst
**Main Job**: Whm
**Sub Job**: Rdm
**Area & Coordinates**: Windurst Woods (G-12)
**Party or Solo**: solo
**NPC or Monster Name**: none
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: Fail a Blessed Briault synth. The Galateia will be locked in grey in inventory (like a linkpearl), and not lost. Inventory resets upon zoning, and the material are available again.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/463

**Comment by TeoTwawki** [comment]
Feel free to remind them this bug exists.

**Comment by Valena07** [comment]
Thanks. Didn't think to look into DSP issues first. Well actually I didn't even know where to look at.

**Comment by TeoTwawki** [comment]
Its np, its an old one, even if you went to their tracker, good luck spotting it. I just happened to remember. We don't expect you guys to know this stuff anyhow :smile:

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update

**Comment by TeoTwawki** [comment]
> Reopen if still an issue after update

Of coarse its still gonna be n issue. It was NEVER fixed in DSP, where the bug actually lives. Where it should actually be being reported over and over till they choke on it or fix it.
