### ISSUE TITLE
Transfering Character Issues

### ISSUE THREAD

**Issue by mnevys** [LegionDark/Issues#504]
**Date & Time**: January 11 (transfer date)
**Frequency**: 100%
**FFXI Client Version**: 30151223_0
**Character Name**: Zervilhaa
**Race**: Mithra
**Nation**: Windurst
**Main Job**: MNK
**Sub Job**: WAR
**Area & Coordinates**: Starting location in windurst
**Party or Solo**: Solo
**NPC or Monster Name**: -------
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**:
After transfering my character from retail, server Sylph. My  Mog safe inventory got capped at 50.
Storage items were restored after setting up the furninshings, but all the other items in the following inventories have been deleted: 
Mog Locker; Mog Satchel; Mog Sack, Mog Case, Mog Wardrobe.

The server also a no 76 and higher item transferable policy, which i knew before-hand as well the non-existence of the mog safe 2, so in retail I put most of the items of 99 on it.
To know that also some lv. 99 (Ilvl 113) items have been transfered over albeit they are unusable by my character, such as Otronif gloves and legs, Iuitl wristbands and feet, among others.

**Comment by TeoTwawki** [comment]
It sounds like a bad import happened.

Just an FYI, currently no Darkstar based server is able to use the second mog safe. I posted a warning about this to Legions forum for their imports. the higher level item restrictions are in the pre-existing sticky. Items that slip past that rule are mostly from the items not having been implemented.

**Comment by mnevys** [comment]
I believe that some issue happened to the import as well.

Regarding the warning about the 2nd mog safe, i knew before hand, that I've put items there that wouldn't be imported anyway (mostly stuff lv. 80 and up).
The real main issue is everything else from all other inventories have been deleted as well my mog safe 1 has only 50 slots, instead of the maxed 80 which I've been told about i was supposed to do.

Best course of action should be making a new import file and import it again?

**Comment by TeoTwawki** [comment]
Yeah that whats we should try if you can re-export. Make sure you have the latest exporter and the latest dll it uses. I don't usually handle any imports so I don't actually know what the latest currently is, just fyi.

If things are messed up again it *should* be fairly visible to whoever does the import job but there's always the possibility the tool needs an update whenever a client version change hits.

**Comment by mnevys** [comment]
Yes, i'll make sure that everything is up to date and export my character again, and see how it goes.

**Comment by Samikana** [comment]
http://legiondark.com/forums/viewtopic.php?f=37&p=4042#p4042

Being continued here

**Comment by Samikana** [comment]
I just spoke to @mnevys and they said that their issue is persisting, but this time, the issue is worse, as their mog safe is also completely empty.

**Comment by mnevys** [comment]
Yes. In fact that issue is even more severe this time around.
All by my main inventory has been erased, and from the regular inventory i have a total of 35 items, which 8 of them are the starting items (Lv. 1 RSE, Adv. cuppon, LegionDS pearl and the weapon, Onion sword). 

Returning to my retail character, with the main inventory of 67/80, of which 21 of them were lv. 76 or higher, some of them are 75 or below, such as homam pieces. I've also got 3 testimonies (DRK MNK DRG) on my inventory, which only one of those was able to be transferred, so the issue is not only from regular usable gear, but items as well. 

Mog safe has been completely erased, and all the items there are supported on this server, to know some: 3 HQ elemental staves, bomb core, bugard strap +1, furnishings which on the original import, had been successfully imported (to the extention of 50 items only) have been deleted as well.

**Comment by R3P0FFXI** [comment]
Retry import after update, you need to be on the latest client for stuff to work
