### ISSUE TITLE
Legion Crash

### ISSUE THREAD

**Issue by Kynil** [LegionDark/Issues#505]
**Date & Time**: 1900 EST
**Frequency**:?
**FFXI Client Version**:30151204_2
**Character Name**:Kynil
**Race**:Hume
**Nation**:San d'Oria
**Main Job**: BLU
**Sub Job**: RDM
**Area & Coordinates**: @legionlaunch
**Party or Solo**: Party
**NPC or Monster Name**: Legion Tome
**ffxiah.com link (for inventory items only)**: ?
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: I traded a Fire Cluster to the Legion Tome as instructed to start Legion. The server then crashed. Not sure if this action was the cause, but it happened the moment of action.

**Comment by TeoTwawki** [comment]
@R3P0FFXI I did a remote in to look and there is no crashdump for this time - doesn't look like there was an actual server crash to me. The trade script you have there does look like it would cause some other unrelated issues though so I have made some edits, will talk with you about this on IRC..

**Comment by R3P0FFXI** [comment]
@TeoTwawki There was a hard memory dump crash which locked the main map server, this has been resolved ill hit you up on IRC shortly
