### ISSUE TITLE
Mission 2/3 Fight

### ISSUE THREAD

**Issue by Phantomwolfie89** [LegionDark/Issues#506]
**Date & Time**: 1/15/16
**Frequency**:
**FFXI Client Version**: 30151215_0
**Character Name**: Phantom
**Race**: Elvaan
**Nation**: Bastok
**Main Job**: Ninja
**Sub Job**: Warrior
**Area & Coordinates**: BCNM for Mission 2-3
**Party or Solo**: solo
**NPC or Monster Name**: Dark Dragon and Eye
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: get mission 2/3 turn into Burning circle no fight....

**Comment by Phantomwolfie89** [comment]
Sandy > Windy

**Comment by Samikana** [comment]
Please send Halsey a tell when you log in
