### ISSUE TITLE
Blu Job Unlock Quest

### ISSUE THREAD

**Issue by Phantomwolfie89** [LegionDark/Issues#507]
**Date & Time**: 01/15/16 11:11pm PST
**Frequency**:
**FFXI Client Version**: 30151215_0
**Character Name**: Phantom
**Race**: Elvaan
**Nation**: Bastok
**Main Job**: Ninja
**Sub Job**: Warrior
**Area & Coordinates**:  X:516 Y:-32 Z:459
**Party or Solo**: Solo
**NPC or Monster Name**: ???
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Last Cut Scene of Blue mage quest POL Error

**Comment by Samikana** [comment]
Please send Halsey a tell next time you log in
