### ISSUE TITLE
Linkshell Transfer request

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#508]
**Date & Time**: 
**Frequency**:
**FFXI Client Version**: 30151103_3
**Character Name**: Daedrik
**Race**: Elvaan
**Nation**: Bastok
**Main Job**: PLD
**Sub Job**: RDM 
**Area & Coordinates**: 
**Party or Solo**:
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**:  The issue is our LS members would like to keep our current pearls but since our LS leader is gone we cant even change our LSmes and are stuck with only me as sack holder. So my request.If it's at all possible, Is to dupe the Shell it self and have it transferred to me so that i can manage the already established forums. 
-Thank you-

**Comment by TeoTwawki** [comment]
Unless the character who was holding the shell was deleted by its owner, can't help you. To big a risk it'll screw up your shells members. You are best off making a new shell and transferring re-pearling in game.

**Comment by Rohelius** [comment]
Okay, I wasn't sure if it could be done to begin with.  thanks man.
