### ISSUE TITLE
Unknown #2

### ISSUE THREAD

**Issue by Lunarie** [LegionDark/Issues#510]
**Date & Time**: 1/16/2016
**Frequency**: Consistent
**FFXI Client Version**: 30151215_0
 **Character Name**: Lunarie
**Race**: Hume
**Nation**: Bastok
**Main Job**: RDM
**Sub Job**: DNC
**Area & Coordinates**: -310 -42 -420 (93)
**Party or Solo**: Both
**NPC or Monster Name**: --
**ffxiah.com link (for inventory items only)**: --
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**: I've spoken to it multiple times now and it shows that option every time.  

The HP points that have I registered are:
Southern San d'Oria 3 
Northern San d'Oria 2, 3 
Windurst Walls 1, 2, 3 
Port Windurst 3 
Bastok Mines 1, 2 
Bastok Markets 1, 2, 3, 4 
Port Bastok 1, 3 
Ru'Lude Gardens 1, 2, 3 
Upper Jeuno 1, 2, 3 
Lower Jeuno 2 
Port Jeuno 1, 2 
Attohwa Chasm 1 
Fei'Yin 1 
Upper Delkfutt's Tower 1 
Quicksand Caves 1 
Rabao 1 
Kazham 1 
Norg 1 
Den of Rancor 1 
Ru'Aun Gardens 1, 2, 3, 4, 5 

![lunarie_2016 01 16_113539](https://cloud.githubusercontent.com/assets/16735229/12373402/55a4a1a2-bc46-11e5-9d59-c0c3fd399364.png)

**Comment by TeoTwawki** [comment]
DSP screwed these up awhile back, and the only way to truly fix them is to wipe homepoint data, and even then every time they add new ones it can happen again. Just use common sense and don't try to transport to any place you haven't actually been.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
