### ISSUE TITLE
Bastok 2-3 Fight Freezes

### ISSUE THREAD

**Issue by Lazarus376** [LegionDark/Issues#511]
**Date & Time**: 
1/16/16 10:15pm
**Frequency**:
Twice
**FFXI Client Version**:
30151204_2
**Character Name**:
Helel
**Race**:
Hume
**Nation**:
Bastok
**Main Job**:
Monk
**Sub Job**:
Warrior
**Area & Coordinates**:
Mission final fight
**Party or Solo**:
Party
**NPC or Monster Name**:
Searcher
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**:
Enter the pre fight CS and it freezes after a couple sentences

**Comment by Samikana** [comment]
Contact me (Halsey) ig when you're online

**Comment by Samikana** [comment]
Fixed
