### ISSUE TITLE
Bastok 2-3 Mission

### ISSUE THREAD

**Issue by Chessna** [LegionDark/Issues#512]
**Date & Time**: 1/16/2016 10:30pm central
**Frequency**: Once
**FFXI Client Version**: 30151204_2
**Character Name**: Chessna
**Race**: Elvaan
**Nation**: Bastok
**Main Job**: Samurai 
**Sub Job**: Dancer
**Area & Coordinates**: Mission Cut scene
**Party or Solo**: Party
**NPC or Monster Name**: Searcher
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**: Fight cut scene freezes after a couple of sentences

**Comment by Samikana** [comment]
Contact me (halsey) ig when you are online

**Comment by Arrytha** [comment]
Same issue as Chessna except Mission 2-3 San d'Oria. Order of quest was Bastok > Windurst.

**Comment by Samikana** [comment]
Both fixed
