### ISSUE TITLE
Grounds of Valor: Gustav Tunnel

### ISSUE THREAD

**Issue by LuckyBane** [LegionDark/Issues#513]
**Date & Time**: 18.01.16, 9:22am
**Frequency**: Consistent
**FFXI Client Version**:30151103_3
**Character Name**: Fletcher
**Race**: Galka
**Nation**: Bastok
**Main Job**: COR
**Sub Job**: NIN
**Area & Coordinates**: Gustav Tunnel
**Party or Solo**: Party + Solo
**NPC or Monster Name**: Grounds of Valor
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**:
Talk to tome and select Page 8 (Turtles and Worms) << Everything normal, yes to confirm, yes to repeat
Talk to tome again, no page registered as selected
All pages listing no target monsters and for levels 0~65355
Zoning out did not resolve the issue.

**Comment by PikaFox** [comment]
This crops up every now and then. Generally talking to the book again a few times/logging solves the issue. As R3 already added, its a DSP issue.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
