### ISSUE TITLE
Item not selling on AH because it says its been used (which it hasn't)

### ISSUE THREAD

**Issue by warlord1352** [LegionDark/Issues#514]
I bought a blink band a few weeks ago but i never used it, and now I've been trying to sell it back to AH but it won't let me because it says it's lots some of its charges which it hasn't. I dont think anyone else has had this problem that I know of as I asked the LS.

**Date & Time**:  All the time
**Frequency**: All the time
**FFXI Client Version**: 30151103_3
**Character Name**: Oscar
**Race**: Tarutaru
**Nation**: Bastok
**Main Job**: Thf
**Sub Job**: Dnc
**Area & Coordinates**: Everywhere, but currently X:-300 Y:-9 Z:185 (13)
**Party or Solo**: Both
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/15170/blink-band
**Multi-boxing? (multiple clients on same connection)**: Yes, but happens when I'm not as well.
**Steps To Reproduce The Issue**: Tried to sort inventory, doesn't work.

p.s. On windower as well (if that matters)

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update

**Comment by TeoTwawki** [comment]
@R3P0FFXI I already know it isn't fixed but its a known DSP bug
