### ISSUE TITLE
Relic Reforge

### ISSUE THREAD

**Issue by Genesius1490** [LegionDark/Issues#515]
**Date & Time**: 18/91/2016
**Frequency**: always
**FFXI Client Version**: 30151204_2
**Character Name**:Jenna
**Race**:Mithra
**Nation**:Bastok
**Main Job**:WHM
**Sub Job**:RDM
**Area & Coordinates**:Tavnazia Safehold  & X:10 Y:-9 Z:0 (21)
**Party or Solo**:solo
**NPC or Monster Name**:Moogle "Relic"
**ffxiah.com link (for inventory items only)**:  --- 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**:Trade Cleric Birault +2 + 25 Aptant: Tachus to Reforge moogle in safehold >> nothing happens, no reforge 109

**Comment by Samikana** [comment]
Do you have ALL CoP and RoZ missions completed up to the requires missions as well as rank 6 (thats a given with RoZ but yeah)

**Comment by Samikana** [comment]
or if you arent rank 6 in a nation you transferred to

**Comment by Genesius1490** [comment]
yep i'm rank10 did Dawn and last ZM mission

**Comment by Baucant** [comment]
Did you visit the correct Moogle? iirc there are two moggle there one to reforge AF and one to reforge relic. if you trade relic to the AF moogle they will do nothing.

**Comment by Samikana** [comment]
I'll look into this tonight and see if anything is wrong.  If I find an issue, I'll pass it along to @TeoTwawki to get fixed

**Comment by Genesius1490** [comment]
@Baucant yeah I visited the right moogle

**Comment by Genesius1490** [comment]
any news? /blush

**Comment by Samikana** [comment]
I have had 0 time to focus on much with Legion lately, hopefully I'll get to it within the next few days.  I've only been able to log in to fix missions as of late

**Comment by Genesius1490** [comment]
Np^^ take your time and keep up the good work

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
