### ISSUE TITLE
Missing mobs in Abyssea Uleguerand

### ISSUE THREAD

**Issue by Genesius1490** [LegionDark/Issues#516]
**Date & Time**: 18/01/2016
**Frequency**:always
**FFXI Client Version**:30151204_2
**Character Name**:Genesius
**Race**:hume
**Nation**:Bastok
**Main Job**:NIN
**Sub Job**:DNC
**Area & Coordinates**:Abyssea-Uleguerand  (H-8)
**Party or Solo**:both
**NPC or Monster Name**:Mechanical Menace
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**:went to (H-8) to farm some NM Key items and pop items. needed the one from Mechanical Menace, though these mobs do not appear/pop where the mob tool from forum say they. I ran around map with Wide scan and never found them. Also tried zoning/rezoning in to reset but still the same.

**Comment by Samikana** [comment]
This is a known issue iirc Loki fixed it, so wtf is making it happen again?  @TeoTwawki

**Comment by TeoTwawki** [comment]
I'll look into it when I and r3 fix the rest of the thing we're in middle of

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
