### ISSUE TITLE
Belphoebe

### ISSUE THREAD

**Issue by Genesius1490** [LegionDark/Issues#517]
Date & Time: 18/01/2016
Frequency:always
FFXI Client Version:30151204_2
Character Name:Genesius
Race:hume
Nation:Bastok
Main Job:NIN
Sub Job:DNC
Area & Coordinates:Jugner Forest -- (I-7) planar rift
Party or Solo:both
NPC or Monster Name:Belphoebe
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection):yes
Steps To Reproduce The Issue: Poped Voidwatch NM Belphoebe, client of half the party crashed after she used Cyclonic Torment.

**Comment by TeoTwawki** [comment]
ty, investigating

**Comment by TeoTwawki** [comment]
Are you sure it wasn't "Cyclonic Turmoil"? Cyclonic Torrent looks legit, but Cyclonic Turmoil looks like it was scripted by a semi intelligent brine shrimp with no previous coding experience. I expect it to be a crasher.

**Comment by Genesius1490** [comment]
oh yeah it's prolly Turmoil. sry for the miss spell

**Comment by TeoTwawki** [comment]
k. I disabled it earlier today, because it looked like a crasher. It probably won't make a return in corrected form till sometime after the update we're working on.
