### ISSUE TITLE
ToAU Mission: Land of the Sacred Serpents (unable to obtain Key Item "Supplies Package")

### ISSUE THREAD

**Issue by JayCrusnik** [LegionDark/Issues#518]
**Date & Time**: Jan 18, 2016
**Frequency**: N/A
**FFXI Client Version**: Ver.30151103_3
**Character Name**: Jaycee
**Race**: Mithra
**Nation**: Windurst
**Main Job**: Samurai
**Sub Job**: Dancer
**Area & Coordinates**: Aht Urghan Whitegate I-10
**Party or Solo**: Solo
**NPC or Monster Name**: Naja Salaheem
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Tried speaking to Quest start NPC again, but could not get the Key Item.

**Comment by Samikana** [comment]
I'll get you when I log in this afternoon

**Comment by JayCrusnik** [comment]
Thanks Sami, but if I need to be logged on for the fix I won't be available til 7 pm PST

**Comment by Samikana** [comment]
That's fine, I'll be available :)

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
