### ISSUE TITLE
Linkshell Master

### ISSUE THREAD

**Issue by Zeldha** [LegionDark/Issues#519]
Date & Time: Jan 19, 2016
Character Name: Vida / Zeldha

Cause Strafeous no longer play in Legion.
LS Exigence lost the shell master holder.
Is it possible to duplicate the shell master?

**Comment by Samikana** [comment]
#508
No template

**Comment by TeoTwawki** [comment]
FYI, there are potential problems for LS members with doing such a thing, unless the character holding the shell has deleted themselves. If they quit but left their character undeleted, can't help you.

**Comment by Samikana** [comment]
@TeoTwawki I'm going to close the other one then

**Comment by Zeldha** [comment]
Okie, thanks.
