### ISSUE TITLE
cant reforge RNG relic+2 feets

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#52]
Date & Time: 6/2/2015 12:55pm
Frequency: 
FFXI Client Version:30150508_8
Character Name: Itachioax
Race:Hume
Main Job:Thf
Sub Job:NIN
Area & Coordinates: Port Jeuno
Party or Solo: Solo
NPC Name: Moogle
Monster Name: none
Steps:
1. i tried trade rng relic feets +2 and 20 aptant: Haelan, and doenst work.
2. already reforge one piece, so i dont have rpoblems with the missions/quests

**Comment by Loki79** [comment]
you other report states you cant get relic +2 feet.  How did you obtain them to try and reforge?

**Comment by Loki79** [comment]
Area & Coordinates: Port Jeuno  <--- incorrect.   
Reforge NPC is in Tav.  Please check the forums to make sure you are doing things correctly before you post bug reports.
