### ISSUE TITLE
Black screen upon entering North Sandy

### ISSUE THREAD

**Issue by Lunarie** [LegionDark/Issues#520]
**Date & Time**: 8:27PM 1/19/2016
**Frequency**: Consistent
**FFXI Client Version**: 30151215_0
**Character Name**: Lunarie
**Race**: Human
**Nation**: Bastok
**Main Job**: THF
**Sub Job**: DNC
**Area & Coordinates**: I moved now, but Northern Sandy
**Party or Solo**: Solo
**NPC or Monster Name**: -
**ffxiah.com link (for inventory items only)**: -
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: It happens every time I zone into Northern Sandoria

![lunarie_2016 01 19_202845](https://cloud.githubusercontent.com/assets/16735229/12437483/3defdcea-beec-11e5-9404-f70bccb05e45.png)

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
