### ISSUE TITLE
BLU CS

### ISSUE THREAD

**Issue by ruin2it3** [LegionDark/Issues#521]
**Date & Time**: 1/19/16
**Frequency**: consistent
**FFXI Client Version**: 30151103_3
**Character Name**: Ruhi
**Race**: Mithra
**Nation**: Bastok
**Main Job**: THF
**Sub Job**: DNC
**Area & Coordinates**: 
**Party or Solo**: 
**NPC or Monster Name**: 
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: Try to obtain final CS in unlocking BLU

**Comment by PikaFox** [comment]
Fixed
