### ISSUE TITLE
San d'Oria Mission 2-3

### ISSUE THREAD

**Issue by daronis17** [LegionDark/Issues#523]
Order of quest was Bastok > Windurst. Need a push through the bugged CS for the Dragon/Searcher fight at Balgas Dais. Character name Jordia.

Date & Time: 1/20/2016 7:37am EST
Frequency: Tried once
FFXI Client Version: 30151223_0
Character Name: Jordia
Race: Hume
Nation: San d'Oria
Main Job: Dancer
Sub Job: Warrior
Area & Coordinates: Mission Cut scene (Balga's Dais)
Party or Solo: Solo
NPC or Monster Name: Searcher
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue: Fight cut scene freezes after a couple of sentences

**Comment by Samikana** [comment]
fixed
