### ISSUE TITLE
two more pics for relic trial (halsey)

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#524]
Date & Time:1/20/2016
Frequency: last time
FFXI Client Version: 30151215_0
Character Name: itachioax
Race: Human
Nation: Sandy
Main Job: MNK
Sub Job: DNC
Area & Coordinates: 
Party or Solo: Solo
NPC or Monster Name: Adamantoise
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue: 
![img_20160116_204914](https://cloud.githubusercontent.com/assets/12620527/12458207/56f72392-bf6e-11e5-96a0-2b09b1a48bdf.png)

![img_20160117_172130](https://cloud.githubusercontent.com/assets/12620527/12458176/315095d8-bf6e-11e5-884b-d43f586d43bf.png)

**Comment by R3P0FFXI** [comment]
Something is not right here as Teo hotfixed this on the server weeks ago. @Samikana please do not do anything with these until i talk with @TeoTwawki

**Comment by itachioax** [comment]
i took them 1 week ago, the trial working, but i missed those 2, im 4/7+ 2 and i need kill one more =/

**Comment by TeoTwawki** [comment]
should report asap, not a week later dude. this is why you got missed when we fixed the others kill counts. I've half a mind to go make you re-kill this was exactly why I had said nobody else on the other ticket!

@Samikana go ahead and give him cred, but anybody else with week odl pics for bugs I already fixed is SOL.

**Comment by TeoTwawki** [comment]
..I'm hearing in IRC that you already got credited? I am confused.

**Comment by R3P0FFXI** [comment]
@itachioax @Samikana @TeoTwawki Itachi if these are from a week ago and you never posted we are not going to credit you now. You will need to re kill these mobs as we are not going back on something that is a week old.

**Comment by TeoTwawki** [comment]
¯\\_(ツ )_/¯
