### ISSUE TITLE
2-3 Mission Fix

### ISSUE THREAD

**Issue by mnevys** [LegionDark/Issues#527]
Date & Time: Jan 21st, 2016
Frequency: Known Issue
FFXI Client Version: 30151223_0
Character Name: Zervilhaa
Race: Mithra
Nation: Windurst
Main Job: DRK
Sub Job: SAM
Area & Coordinates: Horlais Peak
Party or Solo: 
NPC or Monster Name: Seeker and Dark Dragon
ffxiah.com link (for inventory items only): N/A
Multi-boxing? (multiple clients on same connection): No
Steps To Reproduce The Issue: 2-3 Mission from Windurst, Fight in Horlais Peak

**Comment by Samikana** [comment]
Please contact me (Halsey) in-game when you can to get pushed past this mission.  If you do not send me a tell or respond to this bug report within 3 days time it will get closed.

**Comment by mnevys** [comment]
I'm ingame right now

**Comment by Samikana** [comment]
I searched you while I was on and you didn't show up.  Sorry, I had to leave shortly after for work.  Let me know next time you're on.

**Comment by mnevys** [comment]
I'll be on most of the day today

**Comment by Samikana** [comment]
I logged in at 8:54 on 1/22/16 and you were not online.  Please send me a tell next time you're online.
