### ISSUE TITLE
Push passed mission 2-3

### ISSUE THREAD

**Issue by warlord1352** [LegionDark/Issues#528]
**Date & Time**: 3:05 p.m. pst january 21st.
**Frequency**: known issue
**FFXI Client Version**: 30151103_3
**Character Name**: Cureslave
**Race**: Taru
**Nation**: Bastok
**Main Job**: White mage
**Sub Job**: Rdm
**Area & Coordinates**: Heaven's Tower
**Party or Solo**: Solo
**NPC or Monster Name**: Seeker and Dark Dragon
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**:

**Comment by Samikana** [comment]
Please contact me (Halsey) in-game when you can to get pushed past this mission.  If you do not send me a tell or respond to this bug report within 3 days time it will get closed.

**Comment by warlord1352** [comment]
Ok, thank you. I am currently online, so if you are free today just reply on here and I'll get the email notification cuz I'm kinda doing other things on comp as well.
