### ISSUE TITLE
2-3 push request

### ISSUE THREAD

**Issue by Bushuru** [LegionDark/Issues#529]
**Date & Time**: 1\22\16 19:02
**Frequency**: always
**FFXI Client Version**: 30151215_0
**Character Name**: Bushuru 
**Race**: galka
**Nation**: bastok
**Main Job**: beastmaster
**Sub Job**:ninja
**Area & Coordinates**: gelsba bcnm
**Party or Solo**: solo
**NPC or Monster Name**: 2-3 dragon
**ffxiah.com link (for inventory items only)**: none
**Multi-boxing? (multiple clients on same connection)**:no
**Steps To Reproduce The Issue**: start bcnm for mission 2-3

**Comment by Bushuru** [comment]
Giddeous bcnm rather

**Comment by Samikana** [comment]
Msg Halsey ingame please when you are on
