### ISSUE TITLE
cant upgrade RNG relic+1 feets

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#53]
Date & Time: 6/2/2015 12:55pm
Frequency: 
FFXI Client Version:30150508_8
Character Name: Itachioax
Race:Hume
Main Job:Thf
Sub Job:NIN
Area & Coordinates: Port Jeuno
Party or Solo: Solo
NPC Name: Moogle
Monster Name: none
Steps:
1. i tried trade rng relic feets +1 and 30 forgotten steps, and doenst work.

**Comment by Loki79** [comment]
i see another report here for relic +2 feet.  If you cant get relic +2 feet how do know trade for reforge is broken?
