### ISSUE TITLE
2-3 push request

### ISSUE THREAD

**Issue by tammy7th** [LegionDark/Issues#530]
**Date & Time** 1-22-16 11:30 pm
**Frequency**: once
**FFXI Client Version** ashita:
**Character Name**: Summerrose
**Race**: hume
**Nation**: Bastok
**Main Job**: Blue Mage
**Sub Job**: Red Mage
**Area & Coordinates**: Ghelsba
**Party or Solo**: Party
**NPC or Monster Name** Dragon fight :
**ffxiah.com link (for inventory items only)**: n/a 
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: n/a

**Comment by PikaFox** [comment]
Issue should be resolved, both got CS and kindred report.
