### ISSUE TITLE
BRD songs Mage's Ballad II and Mage's Ballad

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#531]
**Date & Time**: 1/23/2016
**Frequency**: Under the effect of Troubadour & Nightingale
**FFXI Client Version**:30151223_0
**Character Name**:Jukebox
**Race**:Mithra
**Nation**:Sandy
**Main Job**:BRD
**Sub Job**:Rdm
**Area & Coordinates**: North Sandy X:63 Y:0 Z:15 (28)
**Party or Solo**:Party
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**:N/A 
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**: Continued trying with different song combo

When Stacking song (up to 4) Mage's Ballad and Mage's Ballad II are not overwriting previous songs for self or party members. It will overwrite ballad.

**Comment by TeoTwawki** [comment]
note to self: check this on dsp master branch

**Comment by R3P0FFXI** [comment]
Heres the last issue with it in DSP its closed now I assumed its fixed we just have not pulled the fix

https://github.com/DarkstarProject/darkstar/issues/2321

**Comment by TeoTwawki** [comment]
I dunno @R3P0FFXI te comments there imply nobody looked into it before it was closed.

**Comment by R3P0FFXI** [comment]
@TeoTwawki KJ said that Fio closed it so yeah good possibility noone looked into it

**Comment by Baucant** [comment]
took a look at the DSP  report R3P0 posted and this appears to be a different issue that works correctly. What I'm experiencing is only during the effect of Troubadour & Nightingale.

**Comment by R3P0FFXI** [comment]
ahh fuckoff already :)

**Comment by Baucant** [comment]
@R3P0FFXI Really?

**Comment by TeoTwawki** [comment]
Ignore him Bauc, he's a poopyhead today /3rdGradeHumor
