### ISSUE TITLE
Push past 2-3 request

### ISSUE THREAD

**Issue by Unmaligned** [LegionDark/Issues#532]
Date & Time: 1\23\16 15:08
Frequency: always
FFXI Client Version: 30151223_0
Character Name: Todai
Race: Elvaan
Nation: Sandoria
Main Job: Blu
Sub Job:Whm
Area & Coordinates: X:298 Y:-123 Z:346 (11)
Party or Solo: solo
NPC or Monster Name: 2-3 dragon
Multi-boxing? (multiple clients on same connection):no
Steps To Reproduce The Issue: start bcnm for mission 2-3

**Comment by Samikana** [comment]
I will be logging on shortly to fix all of these

**Comment by Samikana** [comment]
I logged in at 8:54 on 1/22/16 and you were not online.  Please send me a tell next time you're online.

**Comment by Unmaligned** [comment]
I apologize I has just logged out a few minutes so i could drive home.  I am back online now.

**Comment by Samikana** [comment]
I can't log on the rest of the night.  I can try to catch you Monday

**Comment by Unmaligned** [comment]
okiedokie

**Comment by Samikana** [comment]
fixed
