### ISSUE TITLE
Push past BLU quest

### ISSUE THREAD

**Issue by thiefx** [LegionDark/Issues#533]
**Date & Time**: Jan 23rd, 2016, 1:07pm PST
**Frequency**: Once
**FFXI Client Version**: 30151215_0
**Character Name**: Uubu
**Race**: Mithra
**Nation**: Bastok
**Main Job**: Currently PLD
**Sub Job**: WAR
**Area & Coordinates**: Aydeewa Subterrane (H-9)
**Party or Solo**: Solo
**NPC or Monster Name**: None
**ffxiah.com link (for inventory items only)**:  None
**Multi-boxing? (multiple clients on same connection)**: None
**Steps To Reproduce The Issue**: Umm... do the Blu quest line? heh

Got the cutscene then got the crash as expected. Please help me push through this to unlock Blu!

**Comment by Samikana** [comment]
I will be logging on shortly to fix all of these

**Comment by Samikana** [comment]
I logged in at 8:54 on 1/22/16 and you were not online.  Please send me a tell next time you're online.
