### ISSUE TITLE
Mission 2-3: Dragon fight

### ISSUE THREAD

**Issue by Gn3x0n** [LegionDark/Issues#536]
**Date & Time**: 1/24/2016
**Frequency**: Constant
**FFXI Client Version**:
**Character Name**: Caramon and Raistlin
**Race**: 2 Elvaan Male
**Nation**: San D'oria
**Main Job**: Dark Knight (lvl 61) and Red Mage (lvl 43)
**Sub Job**: Blm (lvl 30) and Blm (lvl 21)
**Area & Coordinates**:  Waughroon Shrine, Coords: X:-345 Y:104 Z:-262 (136).
**Party or Solo**: Party
**NPC or Monster Name**: Seeker and Dark Dragon
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Multi-boxing, same connection.
**Steps To Reproduce The Issue**: Enter BCNM. 
**Side bar**: This request is for both Characters: Caramon and Raistlin.

**Comment by Samikana** [comment]
Please send Halsey a tell in-game tomorrow to get pushed past

**Comment by Gn3x0n** [comment]
Thank you Halsey, appreciate it

**Comment by Samikana** [comment]
Player wasn't on at 11:11 1/25/16 when I logged on

**Comment by Samikana** [comment]
Player wasn't online at 11:30 1/26/16 when I logged on. Please comment a date and time you think you'll be online so that I can catch you.

**Comment by Gn3x0n** [comment]
I attempted to send you a /tell yesterday on both characters but there was no response. I work mon-fri 7-5 and am usually home approximately 6:00pm (EST). My apologies for missing you this morning

**Comment by Gn3x0n** [comment]
Oh and I took the San D'orian 2-3 path as follows: Windurst > Bastok.
