### ISSUE TITLE
Mission 2-3 Dragon Fight

### ISSUE THREAD

**Issue by Dalkiel81** [LegionDark/Issues#537]
Date & Time: 1/24/2016
Frequency: Constant
FFXI Client Version:
Character Name: Deaomongun, Grimnir, Rymr Sirian
Race: 2 Elvaan Male, Taru male, Taru Male, Mithra
Nation: Bastok
Main Job: 99 thf, 99 blm, 99 rdm , 99 brd
Sub Job: 49 dnc, 49 rdm, 49 whm, 49 whm
Area & Coordinates: Balga's Dais, Coords: X:299 Y:-124 Z:342 (172).
Party or Solo: Party
NPC or Monster Name: Seeker and Dark Dragon
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): Multi-boxing, same connection.
Steps To Reproduce The Issue: Enter BCNM.
Side bar: This request is for 4 Characters Deaomongun Grimnir Rymr and Sirian

**Comment by Samikana** [comment]
Please send Halsey a tell ingame when you're online

**Comment by Samikana** [comment]
Player wasn't on at 11:11 1/25/16 when I logged on

**Comment by Samikana** [comment]
Player wasn't online at 11:30 1/26/16 when I logged on.  Please comment a date and time you think you'll be online so that I can catch you.

**Comment by Dalkiel81** [comment]
I'll be online at 7:30pm est tonight 1/26/16

**Comment by Samikana** [comment]
Sounds great, I'll do my best to be online

**Comment by Dalkiel81** [comment]
i went sandy> windy
