### ISSUE TITLE
2-3 mission push

### ISSUE THREAD

**Issue by Grouchmonk** [LegionDark/Issues#538]
**Date & Time**: 1/25/2016, 2:45 am
**Frequency**:once
**FFXI Client Version**:Ashita
**Character Name**:Grouchmonk
**Race**:Hume
**Nation**:Bastok
**Main Job**:MNK
**Sub Job**:THF
**Area & Coordinates**:Giddeus
**Party or Solo**:Solo
**NPC or Monster Name**:2-3 mission battle
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**:N/A
**Steps To Reproduce The Issue*N/A

**Comment by Samikana** [comment]
You need to list what path you were on.  I'll back on in a few hrs.  like 2-3.

**Comment by PikaFox** [comment]
Player got CS from Melek.
