### ISSUE TITLE
Mission 2-3 Push Through

### ISSUE THREAD

**Issue by w3genesis** [LegionDark/Issues#539]
Date & Time: 1/25/2016
Frequency: Constant
FFXI Client Version:
Character Name: Gouken and Miniakuma
Race: Galka, Taru
Nation: Bastok
Main Job: Monk (lvl 99) and Red Mage (lvl 99)
Sub Job: Samurai (lvl 50) and Whm (lvl 50)
Area & Coordinates: Balga's Dais
Party or Solo: Party
NPC or Monster Name: Seeker and Dark Dragon
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): Multi-boxing, same connection.
Steps To Reproduce The Issue: Enter BCNM. 
Side bar: This request is for both Characters: Gouken and Miniakuma.

**Comment by Samikana** [comment]
Your bug report is incomplete.  I need to know which path you've taken.

**Comment by w3genesis** [comment]
Both toons have taken Sandy -> Windy path.

**Comment by Samikana** [comment]
Both characters have had their variables and key items updated.
