### ISSUE TITLE
Lost item (pair of buremte gloves)

### ISSUE THREAD

**Issue by Sangoten** [LegionDark/Issues#54]
**Date & Time**: 02/062015
**Frequency**: all time
**FFXI Client Version**: 30150508_5
**Character Name**: Drkdolfo
**Race**: galka
**Main Job**: pld
**Sub Job**: nin
**Area & Coordinates**: gustaberg
**Party or Solo**: solo
**NPC Name**: 
**Monster Name**:
**Steps To Reproduce The Issue**:
1 > http://img15.hostingpics.net/pics/745643Drkdolfo20150602175914.png
2 > can you bring me a new gloves plz tyvm...

**Comment by R3P0FFXI** [comment]
We do not replace items you threw out sorry
