### ISSUE TITLE
Blue Mage Unlock Cutscene

### ISSUE THREAD

**Issue by Thotless** [LegionDark/Issues#540]
**Date & Time**: 4:30 AM mst
**Frequency**: 1
**FFXI Client Version**: 30151215
**Character Name**: Thotless
**Race**: Tarutaru
**Nation**: Bastok
**Main Job**:Black Mage
**Sub Job**:Red Mage
**Area & Coordinates**:Aydeewa Subterrane
**Party or Solo**: Party
**NPC or Monster Name**: 
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:Yes
**Steps To Reproduce The Issue**:Final Blue Mage Unlock Cutscene

**Comment by Samikana** [comment]
Please PM me (Halsey) in-game when you are online!
