### ISSUE TITLE
Atma of the Gnarled Horn

### ISSUE THREAD

**Issue by neojinx** [LegionDark/Issues#541]
**Date & Time**: 1-27-16
**Frequency**: Consistent
**FFXI Client Version**: 30151215_0
**Character Name**: Neojin
**Race**: Hume
**Nation**: Bastok
**Main Job**: Thief
**Sub Job**: Dancer
**Area & Coordinates**: Abyssea - Misareaux 578.381 433.949 2.426
**Party or Solo**: Party
**NPC or Monster Name**: Sobek
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**: Pop Sobek with required key items and defeat Sobek. No atma gained. Killed Sobek over 20 times with everyone else including 2nd character obtaining atma. Have tried logging 2nd character out completely, booting him out of party, relogging main before pop still no atma.

**Comment by R3P0FFXI** [comment]
Your just having bad luck the atma is the same as any other drop you either get it or you dont.
