### ISSUE TITLE
Relic Reforge 109

### ISSUE THREAD

**Issue by Zeldha** [LegionDark/Issues#542]
**Date & Time:** Jan 27, 2016
**Frequency:** Always
**FFXI Client Version:** 30151204_2
**Character Name:** Vida
**Race:** Mithra
**Nation:** San d'Oria
**Main Job:** PLD
**Sub Job:** WAR
**Area & Coordinates:**
**Party or Solo:** Solo
**NPC or Monster Name:** Moogle  Reforge Port Jeuno
**ffxiah.com link (for inventory items only):** --- 
**Multi-boxing? (multiple clients on same connection):** Yes
**Steps To Reproduce The Issue:** Trade Valor Surcoat +2 + 25 Aptant: Ishis to reforge moogle in Port Jeuno >> Nothing happens.

Rank 6 in Nation.
Some SS that might give more info about mission:

![vida_2016 01 27_222343](https://cloud.githubusercontent.com/assets/16524259/12616211/de4f73cc-c544-11e5-9fb1-426124e82952.png)
![vida_2016 01 27_222402](https://cloud.githubusercontent.com/assets/16524259/12616217/e7f8fa6a-c544-11e5-9902-073941c52637.png)
![vida_2016 01 27_222410](https://cloud.githubusercontent.com/assets/16524259/12616221/f3a63e7c-c544-11e5-9843-731d488b64cd.png)
![vida_2016 01 27_222423](https://cloud.githubusercontent.com/assets/16524259/12616223/f4bfebc8-c544-11e5-98fa-8146887a8682.png)

**Comment by Zeldha** [comment]
Ref page:
http://www.legiondark.com/forums/viewtopic.php?f=40&t=596
http://www.legiondark.com/forums/viewtopic.php?f=27&t=281

**Comment by PikaFox** [comment]
Wrong NPC, the NPC you are looking for is in the bottom floor of Tavnasian Safehold

**Comment by Zeldha** [comment]
Thanks, going to put more info on resources thread in forum about Tav Moogle.
