### ISSUE TITLE
Maat

### ISSUE THREAD

**Issue by Sarge3009** [LegionDark/Issues#543]
1/27/16
Constanr:
**FFXI Client Version**:
Sarge
Hume
Sandoria
samurai:
warrior
burning circle where you trade the testimony to fight maat after he teleports you to quicksand cave
solo
Its quest
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:
When I trade the samurai testimony to the circle it tells me unable to use item. My friend told me to make a ticket cause my quest may need to be reset.

**Comment by Samikana** [comment]
You can only use the testimony once.  If you've used it twice, it won't be useable.

**Comment by Samikana** [comment]
If anything, farm another testimony and get back to me then if it doesn't work

**Comment by Sarge3009** [comment]
worked ty
