### ISSUE TITLE
San D'Orian Mission: 2-3

### ISSUE THREAD

**Issue by Gn3x0n** [LegionDark/Issues#544]
**Date & Time**: 01/27/2016, 2:37 pm est
**Frequency**: Constant
**FFXI Client Version**:
**Character Name**: Caramon And Raistlin
**Race**: Elvaan Male (Both Characters)
**Nation**: San D'Orian
**Main Job**: Caramon - lvl 61 Monk, Raistlin - lvl 70 White Mage
**Sub Job**: Caramon - lvl 30 Warrior, Raistlin - lvl 35 Black Mage
**Area & Coordinates**: Waughroon Shrine (inside the BCNM)
**Party or Solo**: Party 
**NPC or Monster Name**: Seeker 
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Multi-Boxing on Same connection/Device
**Steps To Reproduce The Issue**: Simply beat the BCNM.

After GM Halsey Administered the 2-3 Push, the NPC Halver (nor gate guards or any NPC that might recognize the Mission is on going) Did no award the next rank. Went back to the BCNM, fought and won the fight, got to the CS and game became "stuck" again, attempted to try and talk to NPC's again and still nothing.

**Comment by Samikana** [comment]
This is now the second person who has had issues with being pushed past even though it was working prior to this.  @TeoTwawki any insight?

**Comment by Samikana** [comment]
There was no issue.
