### ISSUE TITLE
Mission 2-3 Dragon Fight

### ISSUE THREAD

**Issue by Darth12189** [LegionDark/Issues#545]
**Date & Time**: 1/27/16 7PM
**Frequency**: Constant
**FFXI Client Version**:
**Character Name**:Darth
**Race**:Tarutaru
**Nation**:San D'Oria
**Main Job**:BLM
**Sub Job**: WHM
**Area & Coordinates**:
**Party or Solo**: Solo
**NPC or Monster Name**:
**Steps To Reproduce The Issue**: mission 2-3

Requesting a push through this fight.

**Comment by Samikana** [comment]
Pm halsey ingame when you are online next

**Comment by Samikana** [comment]
No PM nor update on bug report.  Getting closed.  Please re-open or submit a new report if you'd like to get pushed past.
