### ISSUE TITLE
Throwing and crossbow give signing annimation

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#546]
**Date & Time**: 1/28/2016 9:00am
**Frequency**:Always
**FFXI Client Version**:30151223_0
**Character Name**:Baucant
**Race**:Elvaan
**Nation**:Sandy
**Main Job**:THF
**Sub Job**:NIN
**Area & Coordinates**: all area all coordinates
**Party or Solo**:Either
**NPC or Monster Name**:N/A
**ffxiah.com link (for inventory items only)**:http://www.ffxiah.com/item/21479/tsoa-crossbow#adv
                                                                     http://www.ffxiah.com/item/19260/raiders-bmrng 
**Multi-boxing? (multiple clients on same connection)**:rather I'm multi-boxing or not
**Steps To Reproduce The Issue**: Tried many different zones.

**Comment by Gn3x0n** [comment]
Same, whenever I try to throw the rising sun +1

**Comment by TeoTwawki** [comment]
"singing"?

**Comment by Samikana** [comment]
I've seen this before, can verify it happens.  They make the animation of a song being casted with no instrument.

**Comment by Zeldha** [comment]
Its probably because of  /lockstyle?
I got this "singing" animation, when i /lockstyle using ammo only equiped.
If I lock the style, with range weapon equiped, everything just fine.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update

**Comment by kcilslio** [comment]
I still get this issue. I was on ninja around lv 20ish throwing darts in Qufim. I was getting the singing animation.

**Comment by TeoTwawki** [comment]
@LegionDark/gm some GM reproduce this, screenshot it or video record it, open a DSP issue and do some show and tell. If you find you cannot reproduce this, label this issue as such.

**Comment by kcilslio** [comment]
Okay, you got it. I'll try to get a video of it tomorrow.

**Comment by TeoTwawki** [comment]
That was directed at the GMs but if you got time and want to, sure!

**Comment by kcilslio** [comment]
Oh! I was going to get the video and link you guys to it. I'm not familiar with the DSP issue tracker submission, but I can probably figure it out.

**Comment by TeoTwawki** [comment]
Anything you wanna contribute is fine, we'll pass it along where it needs to go.

**Comment by Heepster03** [comment]
I recorded a video and sent it to DSP.

**Comment by Baucant** [comment]
Since putting in this bug report. I've learned that if you use lockstyle without a range weapon equip it'll always do the singing animation
