### ISSUE TITLE
Aht Urhgan Mission: Immortal Sentries

### ISSUE THREAD

**Issue by Gn3x0n** [LegionDark/Issues#547]
Date & Time**:  1/28/2016, 12:23pm est 
**Frequency**: Constant
**FFXI Client Version**:
**Character Name**: Raistlin
**Race**: Elvaan Male
**Nation**: San D'Oria
**Main Job**: White Mage lvl 76
**Sub Job**: Black Mage lvl 38
**Area & Coordinates**: Halvung
**Party or Solo**: Party and solo
**NPC or Monster Name**: 
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Multiboxing on same connection 
**Steps To Reproduce The Issue**: Supplies Package seems to have disappeared from my key item list (the item Naja asks you to deliver to one of the staging points). Attempted to bring to Caedarva Mire Staging area and Halvung. The NPC's in those respective areas were unresponsive. Attempted to return to Naja and she also was unresponsive.

**Comment by PikaFox** [comment]
Known DSP issue with current revision, youll have to be online when either Halsey or I am to get the KI to continue.

**Comment by Samikana** [comment]
Player has not reached out to a GM nor commented on bug report in more than 3 days.  This issue is getting closed.

Please re-open your report or submit a new one if you'd like to get fixed.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
