### ISSUE TITLE
Kumhau randomly does 2.2x unshown damage.

### ISSUE THREAD

**Issue by Kynil** [LegionDark/Issues#548]
**Date & Time**: 28 JAN 2016, 22:37:35
**Frequency**:Once

**Frequency**
**FFXI Client Version**: 30151223_0
**Character Name**:Kynil
**Race**:Hume
**Nation**: San d'Oria
**Main Job**: BLU
**Sub Job**: RDM
**Area & Coordinates**: x:-49 y:-175 z:1
**Party or Solo**: Party
**NPC or Monster Name**: NPC (Kumhau)
**ffxiah.com link (for inventory items only)**: Don't have one I think
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: It randomly happened.

The issue was that, if you can possibly go back through the chat lag, I had full hp, I was hit for 0 while fighting Kumhau. Then,  I was hit for 132 (stoneskin breaks.) My Max hp is close to  1900. I then get hit for 792 and drop to about 250 hp. Which then in turn, Kumhau hits me for 320 and I "fall to the ground." My issue is why Kumhau seems to have a random damage increase of 2.2x on his 790ish hit. Thanks. :)

**Comment by Samikana** [comment]
He is coded that way.
