### ISSUE TITLE
Aht Urhgan - An Empty Vessel - Blu

### ISSUE THREAD

**Issue by Raishin86** [LegionDark/Issues#549]
Date & Time: 1/29/2016, 08.42 pm 
**Frequency: Constant
FFXI Client Version:
Character Name: Raishin
Race: Tarutaru Male
Nation: San D'Oria
Main Job: DRK lvl 99
Sub Job: SAM lvl 49
Area & Coordinates: Aydeewa Subterrane
Party or Solo: Party and solo
NPC or Monster Name: 
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): nope
Steps To Reproduce The Issue: i need complete Blu mage quest but pol crash

**Comment by PikaFox** [comment]
Fixed
