### ISSUE TITLE
Curaga Earring + AH = fail

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#55]
**Date & Time**: 6/3/2015 1:40pm (est)
**Frequency**: anytime I try to Sell Curaga earring on AH 
**FFXI Client Version**:30150508_8
**Character Name**:Dapunted
**Race**:Taru
**Main Job**:Whm
**Sub Job**:rdm
**Area & Coordinates**:Rabao X:128 Y:8 Z:53 (42)
**Party or Solo**: Party
**NPC Name**:Hyesun (auction house)
**Monster Name**:n/a
**Steps To Reproduce The Issue**:
Attempted to place item on AH recived message "Partially depleted items cannot be put up for auction." charges are 50/50 in face the ring has never been worn

**Comment by TeoTwawki** [comment]
Known bug in DarkStar they've have for multiple years, and nothing Legion can do about.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/534
