### ISSUE TITLE
Mission 2-3 Dragon Fight

### ISSUE THREAD

**Issue by Malagan** [LegionDark/Issues#550]
#Date & Time: 1/30/16 0:30PM
Frequency: Constant
FFXI Client Version:
Character Name:Malagan
Race:Tarutaru
Nation:Bastok
Main Job:RDM
Sub Job:BLM
Area & Coordinates:
Party or Solo: Solo
NPC or Monster Name:
Steps To Reproduce The Issue: mission 2-3. Road Sandoria to Windurst.

Thank you! :

**Comment by PikaFox** [comment]
Fixed.
