### ISSUE TITLE
Body Armor for Feet

### ISSUE THREAD

**Issue by thiefx** [LegionDark/Issues#551]
Quick bug, sorry for lazy reporting.

New chest armor items "Sombra Harness" and "Sombra harness +1" show up under the wrong category AH > Armor > Feet

**Comment by thiefx** [comment]
**Date & Time**: Jan 30, 2016
**Frequency**: Now
**FFXI Client Version**: 30151215_0
**Character Name**: Uubu
**Race**: Mithra
**Nation**: Bastok
**Main Job**: PLD
**Sub Job**: DNC
**Area & Coordinates**: Anywhere
**Party or Solo**: Party
**NPC or Monster Name**: None
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Nay
**Steps To Reproduce The Issue**:

AH items showing up incorrectly on AH

SHIELDS:
Eminemnt Flute (rare/ex) (instrument)

BODY:
Mes'yohi haubergeon (rare/ex)

HANDS:
Gorney mouflet's +1 (rare/ex)

LEGS:
Mes'yohi Slacks (rare/ex)
Aetosaur Ledelsens (feet)
Aetosaur Ledelsens +1 (feet)

FEET:
Sombra harness (body)
Sombra harness +1 (body)

HAND-TO-HAND:
Eminent baghnakhs (rare/ex)

DAGGER:
Eminent dagger (rare/ex)

SWORDS:
Eminent Scimitar (rare/ex)
Mimesis (rare/ex)
Arendsi Fleuret (rare/ex)

G.SWORD:
Eminent Sword (rare/ex)

AXES:
Eminent Axe (rare/ex)

G.AXES:
Minos (rare/ex)
Eminent Voulge (rare/ex)

SCYTHES:
Cronus (rare/ex)
Sminent Sickle (rare/ex)

POLEARMS:
Eminent Lance (rare/ex)
Eminent Crossbow (rare/ex) (Crossbow)
Eminent Crossbow +1 (rare/ex) (Crossbow)

KATANA:
Shigi (rare/ex)
Kaitsuburi (rare/ex)

G.KATANA:
Senkuto (rare/ex)
Ichimonji-Yofusa (rare/ex)

CLUBS:
Eminent Wand (rare/ex)
Bolelabunga (rare/ex)

STAVES:
Kaladanda (rare/ex)
Eminent Pole (rare/ex)
Eminent Staff (rare/ex)

RANGED:
Mekosuchus Blade (rare/ex) (Great Sword)
Macbain (rare/ex) (Great Sword)
Kbiroj (Great Sword)
Ipetam (Dagger)
Eminent Shield (rare/ex) (Shield)

**Comment by Samikana** [comment]
@TeoTwawki a lot of the items I coded have been screwing up even though I double checked a lot of them and they were coded correctly.  Idk what's happening but I won't have time to fix them at all likely this entire month so @R3P0FFXI may have to look at them as like I told Repo, I wouldnt be able to be as active due to school and now an upcoming surgery.

**Comment by Samikana** [comment]
This is why I wanted a third GM, these reports are stacking up and I have no tim to fix them neither the ingame ones nor scripting related ones.  I can only log in and do my best when a moment comes up

**Comment by TeoTwawki** [comment]
@Samikana If they file up they pile up, let them if need be. Don't try to get them all yourself. We're ina  rough patch right now, people need to be understanding and if they aren't to bad for them.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
