### ISSUE TITLE
CoP Mission 6-4

### ISSUE THREAD

**Issue by Unmaligned** [LegionDark/Issues#552]
Date & Time: 1/30/16
*Frequency: N/A
*FFXI Client Version: Version 30151223_0
*Character Name:Todai
*Race: Elvaan
*Nation: Sandoria
*Main Job: BLU
*Sub Job: NIN
*Area & Coordinates: Sealion's Den x: 610, y: 132
*Party or Solo: Solo
*NPC or Monster Name: N/A
*Multi-boxing?: No
*Steps To Reproduce The Issue: Enter Battlefield

I saw that there was a pending issue for the CoP 6-4 fight and didn't want to crash the server.  Would it be possible to be pushed past this mission?  Thank you!

**Comment by TeoTwawki** [comment]
no but the fix will be along "soon"(tm)

**Comment by Unmaligned** [comment]
Lot of people from the main linkshell advised me they never had an issue.  I completed this without a problem.  Issue resolved.  Thank you!

**Comment by Arrytha** [comment]
Date & Time: 1/30/16
*Frequency: N/A
*FFXI Client Version: Version 30151223_0
*Character Name:Arrytha
*Race: Mithra
*Nation: Sandoria
*Main Job: THF
*Sub Job: DNC
*Area & Coordinates: Sealion's Den - Iron Gate CS
*Party or Solo: Party, but only one present
*NPC or Monster Name: N/A
*Multi-boxing?: No
*Steps To Reproduce The Issue: Clicked on gate to initiate CS and game crashed upon beginning of CS

**Comment by Arrytha** [comment]
The crash report remains, but after logging back in, it resumed the CS and had no further problems.
