### ISSUE TITLE
Mob Seether TP attack "Wanion" crashes xiloader "pol"

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#553]
**Date & Time**: 1/30/2016 5:00pm
**Frequency**: anytime mob uses Wanion
**FFXI Client Version**:30151223_0
**Character Name**:Baucant & Dapunted
**Race**:Elvaan & Taru
**Nation**:Sandy
**Main Job**:Blu & Whm
**Sub Job**:Rdm & Rdm
**Area & Coordinates**:Promyvion - Vahzl X:53 Y:0 Z:229 (200)
**Party or Solo**:Party
**NPC or Monster Name**: Seether
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**:multipul times similar results

**Comment by Zeldha** [comment]
Tested on Ashita, 1st TP moves POL client OK, 2ns TP moves POL client crash.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
