### ISSUE TITLE
Maat lvl 70 cap quest fail

### ISSUE THREAD

**Issue by Bushuru** [LegionDark/Issues#554]
**Date & Time**: 1-30-16
**Frequency**:constant since failure
**FFXI Client Version**: 30151215
**Character Name**:Bushuru
**Race**: Galka
**Nation**:Bastok
**Main Job**: DRK
**Sub Job**:WAR
**Area & Coordinates**: Ru'Lude Gardens
**Party or Solo**:solo
**NPC or Monster Name**: Maat
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: True, I had one active at the time
**Steps To Reproduce The Issue**: It is apparently unique to me

I started Shattering Stars, the lvl 70 Maat Cap quest, used my drk testimony, fought and defeated him.  Returned to ru'lude to speak with him to finish the quest, instead he started an earlier cap quest requiring me to find exoray mold, ancient papyrus, and bomb core fragment.  I asked the global LS and they said this is normal, but I'm still capped at lvl 70.  I am at 39,999\34,000 exp and cannot progress any further until this is resolved.

**Comment by TeoTwawki** [comment]
gm will have to set the var so maat will notice your clear, you got random multibox glitched.

**Comment by Bushuru** [comment]
I beat him a second time with drk, still no joy.  I then raised bst to 68, challenged him, beat him, and got the cap cleared.  If you want to leave the bug open to find out what went wrong, by all means, but I'll bet you'd rather get this off your plate.  From my perspective, this is now closed.

**Comment by TeoTwawki** [comment]
I think one of your clears on drk failed to count towards the total because of previously mentioned known glitch causing in invalid set of conditions, so closing.
