### ISSUE TITLE
Stuck on Bastok mission 2-3

### ISSUE THREAD

**Issue by Bushuru** [LegionDark/Issues#555]
**Date & Time**: 1-30-16
**Frequency**: Always
**FFXI Client Version**: 30151215
**Character Name**: Bushuru
**Race**: Galka
**Nation**: Bastok
**Main Job**: DRK
**Sub Job**: WAR
**Area & Coordinates**: Giddeous BCNM
**Party or Solo**: solo
**NPC or Monster Name**: Rank 2-3 dragon
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**: Start BCNM fight

This is the 2nd report I am entering on this.  Spoke with Halsey in game and was told my client was updated so I could move past it, however it still crashes for failing to load the NPC during CS.  I don't know if this helps, but I've heard this fight is no longer capped, yet my level still drops down to lvl 30ish (based on my hp after I @tele dem out of there).

**Comment by PikaFox** [comment]
Player was able to progress.
