### ISSUE TITLE
Sandoria 2-3 Dragon fight(@Giddeus)

### ISSUE THREAD

**Issue by jnuz777** [LegionDark/Issues#556]
**Date & Time**: 1/31/2016 10PM
**Frequency**: First Attempt
**FFXI Client Version**: 30151223_0
**Character Name**: Victer
**Race**: Hume
**Nation**: Sandoria
**Main Job**: Black Mage 89
**Sub Job**: Red Mage
**Area & Coordinates**: Balga's Dais
**Party or Solo**: Solo
**NPC or Monster Name**: Searcher
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Attempt Dragon Fight Again

**Comment by TeoTwawki** [comment]
Protip: Avoid using the at symbol, github uses those for mentions meaning if there is a user named `@Giddeus` and I hadn't surrounded that in code notation just now, they'd be wondering why I'm talking about him/her.

**Comment by PikaFox** [comment]
Player has been able to progress.
