### ISSUE TITLE
Dancer Combat Skill Ratings are Wrong...For Me At Least

### ISSUE THREAD

**Issue by daronis17** [LegionDark/Issues#557]
Dancer should have an A+ rating in dagger skill, B+ rating in evasion skill, and B rating in parrying. I am level 70 and my combat sheet is saying my Dagger and Evasion skills are capped at 233 and my Parrying skill is capped at 244. Either the ratings aren't right, my character has an issue, or there is something else that effects these numbers that I'm not remembering? This is my highest level job so I haven't done merits or anything if you can merit any of these skills and it show up in the combat skills log. According to this (http://ffxiclopedia.wikia.com/wiki/Category:Combat_Skills) which I assume is right, at level 70 and A+ skill should cap at 251, a B+ skill should cap at 233, and a B skill should cap at 228.

**Date & Time**: All the time but I noticed 2/1/16 around 3PM EST
**Frequency**:  All the time
**FFXI Client Version**: 30151223_0
**Character Name**: Jordia
**Race**: Hume
**Nation**: San 'd Oria
**Main Job**: Dancer
**Sub Job**:  Warrior
**Area & Coordinates**: Everywhere
**Party or Solo**:  Both
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: Log in a look at my character combat skills page

**Comment by TeoTwawki** [comment]
I swear to god this comes up every ffing month like clockwork.

**Comment by TeoTwawki** [comment]
DSP's skill shit, is not current with retail.

**Comment by TeoTwawki** [comment]
see also #290
