### ISSUE TITLE
Animated horn - Mystical Fragment

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#558]
**Date & Time**: 2/2/2016 9:00am
**Frequency**:when Animated horn is killed
**FFXI Client Version**:30151223_0
**Character Name**:Jukebox
**Race**:Mithra
**Nation**: Sandy
**Main Job**: Brd
**Sub Job**: Rdm
**Area & Coordinates**: Dynamis - Xacabar  X: 395.764, Y: -8.013, Z: 40.003
**Party or Solo**:Solo
**NPC or Monster Name**:Animated Horn
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/1571/mystic-fragment
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**:Fought mob didn't drop item. Server tool indicates this is a 100% drop.

**Comment by PikaFox** [comment]
Kill all the NMs on the steps, it will give a message that says the souls or whatever have been released.

If this issue continues after this message, open a new ticket. As far as i can tell, you didnt do this step.
