### ISSUE TITLE
Animated Dagger - Ornate Fragment 

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#559]
**Date & Time**: 2/2/2016 9:00am
**Frequency**:when Animated Dagger killed
**FFXI Client Version**:30151223_0
**Character Name**:Jukebox
**Race**:Mithra
**Nation**: Sandy
**Main Job**: Brd
**Sub Job**: Rdm
**Area & Coordinates**: Dynamis - Xacabard  X: 153.690, Y: -24.117, Z: -234.320
**Party or Solo**:Solo
**NPC or Monster Name**:Animated Dagger
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/1572/ornate-fragment
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**:Fought mob didn't drop item. Server tool indicates this is a 100% drop.

**Comment by itachioax** [comment]
u killed all kindreds NM? cuz u have to kill them all before farm fragment

**Comment by PikaFox** [comment]
Kill all the NMs on the steps, it will give a message that says the souls or whatever have been released.

If this issue continues after this message, open a new ticket. As far as i can tell, you didnt do this step.
