### ISSUE TITLE
Blu Spells unavailable that should be (Loki's Request)

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#56]
**Date & Time**: 6/3/15
**Frequency**:  NA
**FFXI Client Version**: 30150508_8
**Character Name**: NA
**Race**: NA
**Main Job**: Blu
**Sub Job**: NA
**Area & Coordinates**: NA
**Party or Solo**: NA
**NPC Name**: NA
**Monster Name**: NA
**Steps To Reproduce The Issue**:

Mobs do not use/do not let you learn any of these spells, listed by Glenn. These are the ones from the list that we should be able to get but cant;

Orcish Counterstance  - https://www.bg-wiki.com/bg/O._Counterstance

Sudden Lunge - https://www.bg-wiki.com/bg/Sudden_Lunge

Crashing Thunder - https://www.bg-wiki.com/bg/Crashing_Thunder

Sub-Zero Smash - https://www.bg-wiki.com/bg/Sub-zero_Smash

**Comment by Loki79** [comment]
Sub-Zero Smash added to Sedna.
Sudden Lunge added to Xan.
I'll deal with the other two later.

**Comment by Loki79** [comment]
Moved to my personal to do board.
