### ISSUE TITLE
something is wrong with the server

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#560]
**Date & Time**: 
**Frequency**:
**FFXI Client Version**:
**Character Name**: Itachioax
**Race**: Hume
**Nation**: Sandy
**Main Job**: BLU
**Sub Job**: RDM
**Area & Coordinates**:
**Party or Solo**: both
**NPC or Monster Name**: none
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**:
for some reason, all in the server cant use linkshell chat, linkshell2, tell and pty not working neither.
another thing, we can send pty invite, but the pty is bugged

**Comment by TeoTwawki** [comment]
taken care of
