### ISSUE TITLE
2-3 Dragon Fight

### ISSUE THREAD

**Issue by SarahEG** [LegionDark/Issues#561]
**Date & Time**: 2/2/2016 7:27 PM
**Frequency**:
**FFXI Client Version**:
**Character Name**: Sarah
**Race**: Hume
**Nation**: Sandy Oreo
**Main Job**:
**Sub Job**:
**Area & Coordinates**:
**Party or Solo**:
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**: I'm requesting to be pushed through on the 2-3 Dragon fight. Path taken was Windy -> Bastok

**Comment by Samikana** [comment]
Player was not online at 9:40PM 2016 7 February when I logged on.  Please let me know when I can catch you online, my schedule is tight right now and I don't have the time to stay logged on and wait for players.

I'll be available the next two days to log on for a few seconds and fix it.

**Comment by SarahEG** [comment]
Kk, going to be online all of today.

**Comment by R3P0FFXI** [comment]
I'll be online Sunday in the am EST time zone

**Comment by PikaFox** [comment]
Player was able to progress.
