### ISSUE TITLE
2-3 mission push, From Windhurst to San 'doria to Bastok

### ISSUE THREAD

**Issue by Grouchmonk** [LegionDark/Issues#562]
**Date & Time**:  02/02/2016 22:00
**Frequency**: N/A
**FFXI Client Version**: Ashita 
**Character Name**: Wukie
**Race**: Taru
**Nation**: Windhurst
**Main Job**: BLM
**Sub Job**: WHM
**Area & Coordinates**: Palabourgh Mines
**Party or Solo**: solo
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**:  N/A
**Multi-boxing? (multiple clients on same connection)**: N/A
**Steps To Reproduce The Issue** N/A

**Comment by PikaFox** [comment]
Player was able to progress.
