### ISSUE TITLE
Moogle storage slip 21

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#564]
**Date & Time**: 2/3/2015 8:30am
**Frequency**:always
**FFXI Client Version**:30151223_0
**Character Name**:Baucant
**Race**:Elvaan
**Nation**:Sandy
**Main Job**:Thf
**Sub Job**:Nin
**Area & Coordinates**: Lower Jeuno X:-17 Y:0 Z:12 (159)
**Party or Solo**:Solo
**NPC or Monster Name**: Porter Moogle
**ffxiah.com link (for inventory items only)**:http://www.ffxiah.com/item/29331/storage-slip-21 
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**:attempted to purchase slip nothing appeared in inventory. Tried sorting inventory, tried zoning

**Comment by R3P0FFXI** [comment]
Not even programmed wont even be looked at until after the update is done

**Comment by R3P0FFXI** [comment]
Are you fucking serious, just dont care, will be done by DSP if ever
