### ISSUE TITLE
2-3 Dragon Fight

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#565]
Date & Time: 02/03/2016 12:47pm
Frequency: N/A
FFXI Client Version: Ashita
Character Name: Spectre
Race: Taru
Nation: Windhurst
Main Job: RDM
Sub Job: WHM
(Path taken San d'oria --> Bastok)
Area & Coordinates: Palabourgh Mines
Party or Solo: solo
NPC or Monster Name: N/A
ffxiah.com link (for inventory items only): N/A
Multi-boxing? (multiple clients on same connection): N/A
Steps To Reproduce The Issue N/A

**Comment by PikaFox** [comment]
Player was able to proceed.
