### ISSUE TITLE
Dagger WS "Mercy Stroke" not available on BRD.

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#568]
**Date & Time**: 2/4/2016 8:50am
**Frequency**:always
**FFXI Client Version**:30151223_0
**Character Name**:Jukebox
**Race**:Mithra
**Nation**:Sandy
**Main Job**:Brd
**Sub Job**:Rdm
**Area & Coordinates**:all areas all coordinates
**Party or Solo**: both
**NPC or Monster Name**:N/A
**ffxiah.com link (for inventory items only)**:N/A 
**Multi-boxing? (multiple clients on same connection)**. both
**Steps To Reproduce The Issue**: zoned, sorted Weapon Skills.

**Comment by R3P0FFXI** [comment]
What weapon are you using?

75 	THF, BRD, or RDM via Batardeau or Mandau
85 	RDM, BRD, DNC, or THF via Clement Skean

**Comment by Baucant** [comment]
Does the weapon matter? I know we used to have all weapon skills that the job could do regardless of weapon. IE mythic, relic, empy, and quested WS. I looked through all the server maintance threads and found nothing that mentions that the WS were changed. I know I have Rudra storm without having a Twashtar.

**Comment by PikaFox** [comment]
All relic WSs were changed in DSP to only be available with the relic weapons.
