### ISSUE TITLE
Mission 2-3 Push From Bastok to San doria to Windhurst

### ISSUE THREAD

**Issue by bjoern74legion** [LegionDark/Issues#569]
Date & Time: 02/04/2016 10:00
Frequency: N/A
FFXI Client Version: Ashita
Character Name: Bjoern
Race: Hume
Nation: Bastok
Main Job: RDM
Sub Job: BLM
Area & Coordinates: Giddious
Party or Solo: solo
NPC or Monster Name: N/A
ffxiah.com link (for inventory items only): N/A
Multi-boxing? (multiple clients on same connection): N/A
Steps To Reproduce The Issue N/A

**Comment by Samikana** [comment]
Player was not online at 9:40PM 2016 7 February when I logged on.  Please let me know when I can catch you online, my schedule is tight right now and I don't have the time to stay logged on and wait for players.

I'll be available the next two days to log on for a few seconds and fix it.

**Comment by R3P0FFXI** [comment]
I'll be online Sunday est 10am February 14

**Comment by R3P0FFXI** [comment]
@bjoern74legion was not online when I ran fixes still an open issue

**Comment by PikaFox** [comment]
Set var and gave KI, player should be able to progress.

**Comment by TeoTwawki** [comment]
If there is still an issue, open new ticket. Assuming this is handled since player hasn't said otherwise in last 4 days after pika's post.
