### ISSUE TITLE
ZM8 Upper Delffut tower cs not working

### ISSUE THREAD

**Issue by Alizoutim** [LegionDark/Issues#57]
**Date & Time**: 6/03/2015 16:30 EST
**Frequency**:Always
**FFXI Client Version**:Ver.30150508_5
**Character Name**:Alizoutim
**Race**:TaruTaru
**Main Job**:Thief
**Sub Job**:Ninja
**Area & Coordinates**:Upper Delkfutt's Tower F-10 on mab  Stellar Fulcrum
**Party or Solo**:Solo
**NPC Name**:none
**Monster Name**:none
**Steps To Reproduce The Issue**:
1-enter Delkfutt tower via the teleport crystal
2- step on the  Stellar Fulcrum 
3- Answer Yes  to the Go trough door
4-Room is black  i can do everything normaly  room seem very small and there is 1 cermet door
5- use the only option and clic the cermet door
6- Back at lower delkfutt tower
7- try again
8- when in dark room use @return twice to maby fix it but it is not working

**Comment by TeoTwawki** [comment]
My gut says likely same as the prob with zm4, will need to test after maint.

**Comment by Alizoutim** [comment]
ok thank you

**Comment by Alizoutim** [comment]
it is fixed

**Comment by TeoTwawki** [comment]
Cause by DSP bug https://github.com/DarkstarProject/darkstar/issues/1425
Fixed by commenting out the offending code.
