### ISSUE TITLE
Mission 2-3 Sandy > Windy > bast

### ISSUE THREAD

**Issue by Eyeles** [LegionDark/Issues#570]
Date & Time                                               02/04/2016
Frequency                                                  NA
FFXI Client Version                                     Ashita
Character Name                                          Vladros
Race                                                             Elvaan 
Nation                                                           Sandoria 
Main Job                                                       Warrior
Sub Job                                                         Dancer
Area & Coordinates                                       Giddius
Party or Solo                                                  Solo
NPC or Monster Name                                   Uu Zhoumo
ffxiah.com link (for inventory items only)        NA
Multi-boxing? (multiple clients on same connection)      NA
Steps To Reproduce The Issue                                     NA

Uu Zhoumo not taking my shield offering (piranha shield)

**Comment by PikaFox** [comment]
He takes a KI from you when you talk to him, he doesnt take the Piranha shield(s) that you are supposed to bring back to your nation.

**Comment by PikaFox** [comment]
After entering Giddeus, you must defeat Zhuu Buxu the Silent twice to obtain 2 Parana Shields.
To get to Zhuu Buxu the Silent, head to the path at (I-8) on the first map and go down the tunnels. Then, make your way to (H-7) on the second map.
Zhuu Buxu the Silent can aggro and link with the surrounding Yagudo.
After defeating him, a Parana Shield drops.
The respawn time for Zhuu Buxu the Silent is 5 minutes. You must wait until he appears again to obtain the second Parana Shield.
Make your way to (F-7) on the second map and speak to Uu Zhoumo to give the KeyItemShield Offering. You can do this while waiting for Zhuu Buxu the Silent to respawn.

**Comment by Eyeles** [comment]
Ok i will try taking the shield back to dandy consulate after work and inform you on progress thank you



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by Eyeles** [comment]
ok i had to trade 2 shields to guy at sandy wouldnt take 1 
at final fight now got in killed seeker and died but still got final cs but froze mid cs think that is point where i need to be pushed ?

**Comment by Samikana** [comment]
Yes, you need to get pushed past the final battlefield with the seeker and dragon.  Please submit a new template to get that done.
