### ISSUE TITLE
Mission 2-3 Sandy > Windy > Bastok

### ISSUE THREAD

**Issue by Eyeles** [LegionDark/Issues#573]
Date & Time 02/04/2016
Frequency NA
FFXI Client Version       Ashita
Character Name            Vladros
Race                              Elvaan 
Nation                            Sandoria 
Main Job                        Warrior
Sub Job                         Dancer
Area & Coordinates       Waughroon Shrine burning circle
Party or Solo                  Solo
NPC or Monster             Burning circel
ffxiah.com link (for inventory items only) NA
Multi-boxing? (multiple clients on same connection) NA
Steps To Reproduce      The Issue enter burning circle defeat boss and cs freezes

**Comment by Samikana** [comment]
Player was not online at 9:40PM 2016 7 February when I logged on. Please let me know when I can catch you online, my schedule is tight right now and I don't have the time to stay logged on and wait for players.

I'll be available the next two days to log on for a few seconds and fix it.

**Comment by Eyeles** [comment]
Thnk you for response. I am on the CAT time zone comparable to UCT +2 or GMT+2
Depending on my work obligations i should be online during 5pm up to 10pm CAT. If you coul let me know when you would be availeble i can try be there at that time.

**Comment by Eyeles** [comment]
Thnk you for response. I am on the CAT time zone comparable to UCT +2 or GMT+2
Depending on my work obligations i should be online during 5pm up to 10pm CAT. If you coul let me know when you would be availeble i can try be there at that time.

**Comment by Samikana** [comment]
I wont be home until 6PM est.  leave your chr afk if you can't be on.

**Comment by Eyeles** [comment]
Will do thnx



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by R3P0FFXI** [comment]
I'll be online Sunday feb 14 10am est

**Comment by Eyeles** [comment]
Thnx not shure what my gf has planned but will make shure my char is online at that time



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by R3P0FFXI** [comment]
@Eyeles Issue resolved per our discussion
