### ISSUE TITLE
BLU quest An Empty Vessel push through

### ISSUE THREAD

**Issue by w3genesis** [LegionDark/Issues#574]
**Date & Time**: 2/7/2016
**Frequency**: Constant
**FFXI Client Version**: Newest
**Character Name**: Gouken, Miniakuma, Minibaal, Minidiablo, Catburglar 
**Race**: Galka Taru Taru Taru Mithra
**Nation**: Bastok all
**Main Job**: 99pld, 99whm, 99rdm, 99rdm, 99thf
**Sub Job**:war, rdm, blm, blm, war
**Area & Coordinates**: Aydeewa Subterrane
**Party or Solo**: solo on all
**NPC or Monster Name**: none
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: 
At last cut scene for BLU quest inside the pool, pol crashes on every character, unable to proceed.

**Comment by Samikana** [comment]
=]
