### ISSUE TITLE
[Mission 2-3] - [Nation : San d'Oria] - [Walkthrough : Bastok > Windurst] 

### ISSUE THREAD

**Issue by adamviano** [LegionDark/Issues#575]
Hello troubleshooters, here's my template for the issue:

**Date & Time**: 2/5/2016
**Frequency**: NA
**FFXI Client Version**: NA
**Character Name**: Minervah
**Race**: Mithra
**Nation**: San d'Oria
**Main Job**: NA
**Sub Job**: NA
**Area & Coordinates**: Giddeous
**Party or Solo**: Solo
**NPC or Monster Name**: 	
Requesting to be pushed through on the 2-3 Dragon fight. 
Nation : San d'Oria
Path taken was Bastok to Windy						
**ffxiah.com link (for inventory items only)**: NA
**Multi-boxing? (multiple clients on same connection)**: NA
**Steps To Reproduce The Issue**: NA

Thanks for your help, well appreciated

**Comment by PikaFox** [comment]
Player has been fixed and should be able to progress.
