### ISSUE TITLE
mission 2-3 

### ISSUE THREAD

**Issue by Sarge3009** [LegionDark/Issues#576]
**Date & Time**:  2/6/2016  8:43pm EST
**Frequency**: constant
**FFXI Client Version**: 
**Character Name**: Sarge
**Race**: Hume
**Nation**: sandoria
**Main Job**:Sam
**Sub Job**:Warrior
**Area & Coordinates**: Giddeus mission 2-3
**Party or Solo**: Solo
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**:

I need to get passed the sandy 2-3 mission, ive done all steps and got stuck in the 30 minutes cutscene where u fight boss.

**Comment by Samikana** [comment]
Player was not online at 9:40PM 2016 7 February when I logged on.  Please let me know when I can catch you online, my schedule is tight right now and I don't have the time to stay logged on and wait for players.

I'll be available the next two days to log on for a few seconds and fix it.

**Comment by Sarge3009** [comment]
Im online now.

**Comment by Samikana** [comment]
Should be fixed =]  Feel free to re-open or write a new bug report if the problem persists.
