### ISSUE TITLE
Pillager's Poulaines +1 does not extend Flee effect

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#577]
**Date & Time**: 2/7/2016 9:45am
**Frequency**: under the ability of flee
**FFXI Client Version**:30151223_0
**Character Name**:Baucant
**Race**:Elvaan
**Nation**:San d`Oria
**Main Job**:Thf
**Sub Job**:War
**Area & Coordinates**: All areas all coordinates
**Party or Solo**:either
**NPC or Monster Name**:N/A
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/28249/pill-poulaines-1 & possibly http://www.ffxiah.com/item/28228/pillagers-poulaines
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**: confirmed item was equipped before, during and after Flee was executed. No change to flee duration (30sec). According to Wiki boots only need to be equipped when the ability is activated. I can not confirm or deny if this also happened with the Pillager's Poulaines.

**Comment by Baucant** [comment]
Also it doesn't appear that my movement speed has increased.

**Comment by Samikana** [comment]
INSERT INTO `item_mods` VALUES (28248,1,63);  --  DEFENSE +63
INSERT INTO `item_mods` VALUES (28248,2,21);  --  HIT POINTS +21
INSERT INTO `item_mods` VALUES (28248,5,22);  --  MANA POINTS +22
INSERT INTO `item_mods` VALUES (28248,8,10);  --  STRENGTH +10
INSERT INTO `item_mods` VALUES (28248,9,11);  --  DEXTERITY +11
INSERT INTO `item_mods` VALUES (28248,10,10);  --  VITALITY +10
INSERT INTO `item_mods` VALUES (28248,11,33);  --  AGILITY +33
INSERT INTO `item_mods` VALUES (28248,12,22);  --  INTELLIGENCE +22
INSERT INTO `item_mods` VALUES (28248,13,19);  --  MIND +19
INSERT INTO `item_mods` VALUES (28248,14,34);  --  CHARISMA +34
INSERT INTO `item_mods` VALUES (28248,28,16);  --  MAGIC ATTACK BONUS +16
INSERT INTO `item_mods` VALUES (28248,29,5);  --  MAGIC DEFENSE BONUS +5
INSERT INTO `item_mods` VALUES (28248,30,16);  --  MAGIC ACCURACY +16
INSERT INTO `item_mods` VALUES (28248,31,107);  --  MAGIC EVASION +107
INSERT INTO `item_mods` VALUES (28248,65,55);  --  EVASION +55%
INSERT INTO `item_mods` VALUES (28248,384,31);  --  HASTE +3.1%

These are coded all kinds of wrong.  This is for the +1.

**Comment by Baucant** [comment]
could you please provide the HQ stats so at least I could make use of this item until the fix is put in?

**Comment by TeoTwawki** [comment]
@Baucant everything is one hold till update the update is finished. item stats are not something we can do without taking entire server down anyway. what'll happen is teh fix will get put into the update branch and will ride on in with it.

**Comment by Samikana** [comment]
All stats are visible on beta website

**Comment by Baucant** [comment]
@TeoTwawki   I wasn't expecting that this be handled right now or even relatively soon. I completely understand that the update is the #1 priority. But if I don't create the bug report when it is in my mind I will forget about it when the update comes. Then no one knows that there is a bug and nothing gets fixed

@Samikana  maybe for you as you are an admin, but us common folk don't get to see shit if it not on the picture. As you have demonstrated with this NQ version of the item the picture means nothing.

**Comment by TeoTwawki** [comment]
@Baucant I was responding specifically to:

> could you please provide the HQ stats so at least I could make use of this item until the fix is put in?

Only. I have no prob with you reporting things before the update, just letting you know we can't do anything for a bit. In fact I *need* those, or I will forget a thing exists. :)

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
