### ISSUE TITLE
San d'Oria Mission 2-3

### ISSUE THREAD

**Issue by MishaHiroki** [LegionDark/Issues#578]
Date & Time: 2/7/2017 11:08 AM MST
Frequency: constant
FFXI Client Version: 
Character Name: Misha
Race: Mithra
Nation: San d'Oria
Main Job: PLD
Sub Job: DNC
Area & Coordinates: Waughroon Shrine BC
Party or Solo: Solo
NPC or Monster Name: N/A
ffxiah.com link (for inventory items only): N/A
Multi-boxing? (multiple clients on same connection): No
Steps To Reproduce The Issue: Path taken: San d'Oria > Windurst > Bastok

**Comment by Samikana** [comment]
Player was not online at 9:40PM 2016 7 February when I logged on.  Please let me know when I can catch you online, my schedule is tight right now and I don't have the time to stay logged on and wait for players.

I'll be available the next two days to log on for a few seconds and fix it.

**Comment by MishaHiroki** [comment]
I can log in right now if you like.
