### ISSUE TITLE
Quest - It's Raining Mannequins

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#579]
**Date & Time**: 2/7/2016 2:30 pm
**Frequency**: always
**FFXI Client Version**30151223_0:
**Character Name**:Baucant
**Race**:Elvaan
**Nation**:San d`Oria
**Main Job**:Thf
**Sub Job**:Dnc
**Area & Coordinates**:Mhaura X:-37, Y:-16, Z:69(217)
**Party or Solo**: Solo
**NPC or Monster Name**:Fyi Chalmwoh
**ffxiah.com link (for inventory items only)**: N/A 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**:Checked and confirmed Fame Lvl, zoned multipul times.  NPC still will not respond.

FFXI wiki quest page : http://ffxiclopedia.wikia.com/wiki/It%27s_Raining_Mannequins!

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update, and I just dont care
