### ISSUE TITLE
Blu Spells unavailable because of lack of access to mobs (Loki's Request)

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#58]
**Date & Time**:  6/3/15
**Frequency**: NA
**FFXI Client Version**: 30150508_8
**Character Name**: NA
**Race**: NA
**Main Job**: Blu
**Sub Job**: NA
**Area & Coordinates**: NA
**Party or Solo**: NA
**NPC Name**: NA
**Monster Name**: NA
**Steps To Reproduce The Issue**: This is the list of spells for blue mage for spells where there is no mob implemented that uses these TP moves as of yet. I separated the two because this one is moreso for future reference.

Embalming Earth - https://www.bg-wiki.com/bg/Embalming_Earth

Foul Waters - https://www.bg-wiki.com/bg/Foul_Waters

Glutinous Dart - https://www.bg-wiki.com/bg/Glutinous_Dart

Molting Plumage - https://www.bg-wiki.com/bg/Molting_Plumage

Nature's Meditation - https://www.bg-wiki.com/bg/Nature%27s_Meditation

Nectarous Deluge - http://ffxiclopedia.wikia.com/wiki/Nectarous_Deluge

Paralyzing Triad - https://www.bg-wiki.com/bg/Paralyzing_Triad

Retinal Glare - https://www.bg-wiki.com/bg/Retinal_Glare

Subduction - https://www.bg-wiki.com/bg/Subduction

Sweeping Gouge - http://ffxiclopedia.wikia.com/wiki/Sweeping_Gouge

Tempestuous Upheaval - https://www.bg-wiki.com/bg/Tempest_Upheaval

Thrashing Assault - https://www.bg-wiki.com/bg/Thrashing_Assault

Uproot - https://www.bg-wiki.com/bg/Uproot

**Comment by PikaFox** [comment]
Fix'd Upheaval > Uproot. Woops.

**Comment by Loki79** [comment]
Moved to my personal to do board,
