### ISSUE TITLE
Supplies package Key item

### ISSUE THREAD

**Issue by ronnymp** [LegionDark/Issues#580]
Date & Time: 2/7/2016 8:12 pm
Frequency: always
FFXI Client Version30151223_0:
Character Name: Serjoca
Race:Taru taru
Nation:Bastok
Main Job:whm
Sub Job:rdm
Area & Coordinates:white gate (I-10)
Party or Solo: Solo
NPC or Monster Name Naja Salaheem
ffxiah.com link (for inventory items only): N/A 
Multi-boxing? (multiple clients on same connection): No

 In my mission log it showing "Immortal Sentries"... After mission 1 she didnt give me the Key item...So i tried talk to the immortals at stagin points but they dont talk to me...no cs , nothing .
I try talk to naja too , but nothing happens...

**Comment by Samikana** [comment]
Player was not online at 9:40PM 2016 7 February when I logged on.  Please let me know when I can catch you online, my schedule is tight right now and I don't have the time to stay logged on and wait for players.

I'll be available the next two days to log on for a few seconds and fix it.

**Comment by ronnymp** [comment]
Ok , im On already if u want ^^

**Comment by Samikana** [comment]
I'm at the school atm

**Comment by R3P0FFXI** [comment]
I'll be online Sunday 10am est feb 14

**Comment by R3P0FFXI** [comment]
@ronnymp Not logged in when trying to perform fixes

**Comment by TeoTwawki** [comment]
@ronnymp please post some times you are available to meet up with a GM. Our availability in game doesn't always line up with when we are posting comments on github.

**Comment by TeoTwawki** [comment]
I'f I'm not mistaken I handled this person yesterday, a lot was going on so I forgot to post here right away. If I am wrong reply here and I will reopen the ticket.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
