### ISSUE TITLE
Shattering stars / Maat Fight RDM / LB5

### ISSUE THREAD

**Issue by Malagan** [LegionDark/Issues#581]
Maat is imune to any tier 3 spells. Tried Aero, Water and Stone. All spells do 0 damage. All tier 2 work.

**Date & Time**:  Feb. 7 2016
**Frequency**: Everytime
**FFXI Client Version**: ver.30151215_0
**Character Name**: Malagan
**Race**: Tarutaru
**Nation**: Bastok
**Main Job**: RDM
**Sub Job**: BLM
**Area & Coordinates**: Waughroon Shrine / RDM Maat Fight
**Party or Solo**: Solo
**NPC or Monster Name**: Maat
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Cast any tier III spells to Maat.

**Comment by Samikana** [comment]
I just tested this.  Maat took damage from tier III spells with no issue.  Try upgrading your gear or capping your skill if you haven't already.

**Comment by Malagan** [comment]
As info: All skills caped. AF1 set with Merveilleuse sword. Died the first fight cause of enfeebling too low Caped for second fight. That'S where I realize that alll my tier 3 spells do 0 damage. I have Whence Blows the Wind quest active when I tried the fight. I also took a cream puff from the MogDonald shop and Maat activated "Oh Snap" ability when i used it... what is this ability?

**Comment by TeoTwawki** [comment]
> activated "Oh Snap" ability when i used it... what is this ability?

Its not an ability, its an effect.

> "Maat eats the same food you did!
 Maat gains the effect of **Oh snap!*"

He's getting the exact same food effect bonus as you.

**Comment by Samikana** [comment]
Use elemental staves of the element of the spell

**Comment by TeoTwawki** [comment]
protip: don't trigger oh snap
