### ISSUE TITLE
TOAU 2

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#582]
Date & Time: 2/7/2016 8:20 pm
Frequency: always
FFXI Client Version30151223_0:
Character Name: Serjoca
Race:Mithra
Nation:Windurst
Main Job: pld
Sub Job:war
Area & Coordinates:white gate (I-10)
Party or Solo: Solo
NPC or Monster Name Naja Salaheem
ffxiah.com link (for inventory items only): N/A 
Multi-boxing? (multiple clients on same connection): No

In my mission log it showing "Immortal Sentries"... After mission 1 she didnt give me the Key item...

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
