### ISSUE TITLE
Windhurst Mission 2-3: Sandy to Bastok - Need push through

### ISSUE THREAD

**Issue by Xtian75** [LegionDark/Issues#583]
**Date & Time**: 02/08/2016 - 10:53AM PST
**Frequency**: n/a
**FFXI Client Version**: 30151233_0
**Character Name**: Xtian
**Race**: Tarutaru
**Nation**: Windhurst
**Main Job**: White Mage
**Sub Job**: Red Mage
**Area & Coordinates**: Palborough Mines Waughroon Shrine (H-10)
**Party or Solo**: Solo
**NPC or Monster Name**: n/a
**ffxiah.com link (for inventory items only)**: n/a
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: I am at the part before entering the waughroon shrine BCNM dragon fight. I need a push through. I went Sandy then to Bastok's Waughroon Shrine. Please let me know if I actually need to enter the BCNM fight first before I get pushed through. I got the HP crystal outside the BCNM. Thanks!

**Comment by Samikana** [comment]
I'll be on at 6pm est (in 3 hr 20 min) please either be online or leave your chr online so i can get uou when i hop oj

**Comment by Samikana** [comment]
Stuff came up for me irl.  I can't log on...sorry!  Try & catch me tmrw.

**Comment by Xtian75** [comment]
No worries, Sami! I get off work at 6pm EST so I won't get home until at least 6:30PM EST. So i'll try to get on about 7PM EST. Real life is important, no worries at all :)

**Comment by R3P0FFXI** [comment]
I'll be online Sunday 10am on February 14

**Comment by Xtian75** [comment]
Ok cool. Are you EST or PST time zone? If its EST, I can just leave my character online for you. Please let me know. Thanks!

**Comment by R3P0FFXI** [comment]
Varible looked right added Key item for you let me know if it does not work @Xtian75

**Comment by Xtian75** [comment]
Hello R3POFFXI! Even with the key item the kindred crest added, it still does not let me to proceed to get the last key item, the Kindred Report. Patt-pott npc in Bastok metalworks, does not give me the Kindred Report key item to take back to Windhurst to complete the quest.

**Comment by Xtian75** [comment]
GM Tarot got this corrected for me and fix. Thank you so much! Closing now.
