### ISSUE TITLE
Bastok Mission 2-3 Sandy to Windy Need Push

### ISSUE THREAD

**Issue by Raziel-IX** [LegionDark/Issues#584]
Date & Time: 02/08/2016 - 9:57PM EST
Frequency: n/a
FFXI Client Version: 30151233_0
Character Name: Raziel
Race: Elvaan
Nation: Bastok
Main Job: Samurai
Sub Job: Dancer
Area & Coordinates: X:300 Y:-134 Z:343 (103).
Party or Solo: Solo
NPC or Monster Name: n/a
ffxiah.com link (for inventory items only): n/a
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue: Standing in front of burning circle. Would like to get past this mission. Thank you.

**Comment by R3P0FFXI** [comment]
I'll be online Sunday 10am est February  14

**Comment by Raziel-IX** [comment]
Do I need to be on as well?


Sent from Outlook Mobile






On Fri, Feb 12, 2016 at 9:12 AM -0800, "R3P0FFXI" <notifications@github.com> wrote:





I'll be online Sunday 10am est February  14

---

**Comment by R3P0FFXI** [comment]
Yes either you or your character logged in

**Comment by Raziel-IX** [comment]
OK

Sent from my Sony Xperia® Z1ˢ on T-Mobile’s 4G LTE Network

---- R3P0FFXI wrote ----

Yes either you or your character logged in

---

**Comment by Raziel-IX** [comment]
Thank you for fixing it!

**Comment by PikaFox** [comment]
Player was able to progress.
