### ISSUE TITLE
San D'Oria mission 2-3 - Windurst 1st, Waughroon Shrine BCNM

### ISSUE THREAD

**Issue by shabazz** [LegionDark/Issues#585]
**Date & Time**: 10:24 PM EST, Feb 08/16
**Frequency**: N/A
**FFXI Client Version**: 
**Character Name**: Shabazz and Tikenzie
**Race**: Hume M and Taru F
**Nation**: San D'Oria
**Main Job**: 
**Sub Job**:
**Area & Coordinates**: Waughroon Shrine
**Party or Solo**: N/A
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: Yes, Shabazz and Tikenzie
**Steps To Reproduce The Issue**:

Need bump on both characters to achieve rank 3 in San D'Oria. All CS's done up until entry into burning circle in Waughroon Shrine

**Comment by R3P0FFXI** [comment]
I'll be online Sunday fen 14 10am

**Comment by shabazz** [comment]
Issue resolved, Tarot pushed me through
