### ISSUE TITLE
renik af+1 reforged blm feet error

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#587]
Date & Time: 09/02/2016, 23:00pm --01/03/16
Frequency: Always
FFXI Client Version: 30151233_0
Character Name: Aurel
Race: Hume
Main Job: blm
Sub Job: Sam
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name:Renik
Monster Name:
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/27335/arch-sabots-1
http://www.ffxiah.com/item/27688/atro-chapeau-1
http://www.ffxiah.com/item/27695/wakido-kabuto-1
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:
i have trade 
http://www.ffxiah.com/item/27334/arch-sabots + 5 rems chap 1 ,and i obtain rdm feet af1 reforged lol 
http://www.ffxiah.com/item/28248/atrophy-boots-1
i have trade
http://www.ffxiah.com/item/27674/wakido-kabuto +5 rems chap 4,and i obtain
http://www.ffxiah.com/item/27694/orion-beret-1
i have trade
http://www.ffxiah.com/item/27667/atrophy-chapeau +5 rems chap 4,and i obtain
http://www.ffxiah.com/item/27687/spae-petasos-1
![captura](https://cloud.githubusercontent.com/assets/13084662/12907321/9bbe856a-cec8-11e5-8767-7395b0258a68.PNG)
![ra](https://cloud.githubusercontent.com/assets/13084662/13528160/a71d58f2-e1ea-11e5-8843-cab6c62b0693.PNG)

**Comment by nekrol** [comment]
ooo sorry not sure where is issue

**Comment by Samikana** [comment]
@TeoTwawki

**Comment by nekrol** [comment]
Hello i need you help i lost 2 af reforge
![captura png rdm](https://cloud.githubusercontent.com/assets/13084662/13434637/f1d395ea-dfac-11e5-8bbb-cbfa3aa3a0c6.PNG)
![captura png rdm](https://cloud.githubusercontent.com/assets/13084662/13434651/fbe0bf04-dfac-11e5-9634-8102af945442.PNG)
![caura](https://cloud.githubusercontent.com/assets/13084662/13434659/04a353cc-dfad-11e5-9ac7-613d9e6cfe89.PNG)
![ptura](https://cloud.githubusercontent.com/assets/13084662/13434671/115b84fe-dfad-11e5-8bcc-487443012fc8.PNG)

**Comment by nekrol** [comment]
GM can give me some item? AF 119 reforge

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update

**Comment by TeoTwawki** [comment]
@R3P0FFXI I don't think loki's trial NPC's ever got fixed all the way.

@Loki79 still not it! 
###### _\*hides\*_

**Comment by nekrol** [comment]
How reopen i lost + equip 109 i lost rems chapter and lost bayld ,..i need GM deliver the AF 119

**Comment by Samikana** [comment]
Write another bug report.

**Comment by Samikana** [comment]
I hit wrong button, you still need to write a new bug report.
