### ISSUE TITLE
Chelona Trousers does not show up on AH when put up for sale

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#588]
**Date & Time**: 2/9/2016 10:00 am
**Frequency**: Anytime Item is placed on AH
**FFXI Client Version**:30151223_0
**Character Name**:Baucant
**Race**:Elvaan
**Nation**:San d`Oria
**Main Job**:Thf
**Sub Job**:Dnc
**Area & Coordinates**: All areas all Corridinates
**Party or Solo**:Solo
**NPC or Monster Name**:Auction House
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/10348/chelona-trousers
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**:Check AH with command and physically visted Auction houses Item does not show on AH but was removed from inventory for sale.

**Comment by Samikana** [comment]
Yeah because you guys aren't meant to be crafting that shit yet.  It's not done being coded.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
