### ISSUE TITLE
BLU quest push

### ISSUE THREAD

**Issue by KavelNg** [LegionDark/Issues#589]
**Date & Time**: 2/9*2016
**Frequency**:Always
**FFXI Client Version**:30151223_0
**Character Name**:Kavel
**Race**:Hume
**Nation**:Sandori'a
**Main Job**:NIN
**Sub Job**:DNC
**Area & Coordinates**:N/A
**Party or Solo**:Solo
**NPC or Monster Name**:N/A
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**:N/A
**Steps To Reproduce The Issue**: I need a push for BLU quest, did everything correctly

**Comment by R3P0FFXI** [comment]
I'll be on,one Sunday February  14 10am

**Comment by KavelNg** [comment]
thanks, ill be waiting.

**Comment by R3P0FFXI** [comment]
@KavelNg Ran blu fix your all set
