### ISSUE TITLE
Missing Weapon Skills (SAM)

### ISSUE THREAD

**Issue by Tatako** [LegionDark/Issues#59]
Date & Time: 6/3/15
Frequency: Always
FFXI Client Version: 30150508_8
Character Name: Tatako
Race: Mithra
Main Job: SAM
Sub Job: Any
Area & Coordinates: Anywhere
Party or Solo: Any
NPC Name: NA
Monster Name: NA
Steps To Reproduce The Issue: I have had a fix applied to my character to fix CoP 1-2.
That is working, I am unsure if this caused the issue.  However, I noticed that before maintenance and after if I equip a GKatana specifiically:  Yukitsugu +1,  I lose all weapon skills.  It states "No abilities available".  If i change the weapon to a Hagun I receive all of them back.

I have logged out, shutdown the client, changed jobs nothing seems to fix this.
Thanks!

**Comment by TeoTwawki** [comment]
Sounds like a regression in our item table info, meaning we lost a few of our changes for reason I won't go into. Its likely the skill isn't set correctly for weapon to be recognized as a "Great Katana" type and will have to be re-added.

**Comment by TeoTwawki** [comment]
@Loki79 reminder: changes to make this fixed either have to go in custom file or done via pull req, then pulled into Legion via merge with DSP.

**Comment by Loki79** [comment]
its a lv 77 random ah weapon the bot prolly picked up.  not going to be fixed in 12 minutes you would actually use it before leveling into something better but ill fix for an upcoming maint.
