### ISSUE TITLE
Bastok 2-3 Mission - Path Windy to Sandy 

### ISSUE THREAD

**Issue by Kylar82** [LegionDark/Issues#590]
**Date & Time**: 09/02/16 22:55 GMT
**Frequency**:
**FFXI Client Version**: 30151223_0
**Character Name**: Kylar
**Race**: Mithra
**Nation**: Bastok
**Main Job**: BST
**Sub Job**: DNC
**Area & Coordinates**:  Holaris Peak X-506 Y158 Z-212 (3)
**Party or Solo**: Solo
**NPC or Monster Name**: n/a
**ffxiah.com link (for inventory items only)**: n/a 
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: Dont want to enter BC and cause CS crash

**Comment by R3P0FFXI** [comment]
I'll be online Sunday February 14 at 10am est

**Comment by Kylar82** [comment]
That'll be 3pm GMT I'll be in work I can log my character in before I go work if that is OK with you

**Comment by R3P0FFXI** [comment]
if its logged in should be fine

**Comment by R3P0FFXI** [comment]
@Kylar82 Should be all set gave you the KI and gave you the proper varviable

**Comment by Kylar82** [comment]
Awesome thanks so much

**Comment by Kylar82** [comment]
is there a way to reset mission as now no longer able to speak to 1 npc and no longer able to click the BC?

**Comment by PikaFox** [comment]
Assuming it was done correctly; "Return to Helaku to receive the KeyItemKindred Report." is the step you should be on. If you are unable to get the kindred report from them, then one of the GMs will need to revisit you to fix it is all. Resetting the mission entirely is.... a little more complicated that fixing it usually.

**Comment by Kylar82** [comment]
Yes <GM>God helped yesterday and he gave me the crest and told me to check FFXIBG to make sure I done everything correct but I mustof missed something from the sandy side as the NPC halver won't respond to tell me to go to the BC

**Comment by PikaFox** [comment]
You should be at the part where you return to Helaku, not halver. If Helaku doesnt respond then we will need to check your var again.

**Comment by Kylar82** [comment]
Helaku only tells me to return to Naji as if he has already given me the Report but I still just have a Crest is it possible to change the Var on Helaku to the point where he tells me to speak to Halver who in turn tells to go to the BC as thats the only thing i cant recheck from FFXIBG to do (as helaku only responds with above)

**Comment by PikaFox** [comment]
The point is to push you past the BC fight because the BC fight will make you crash and wont let you progress currently. If Naji doesnt do anything, then we will need to look at your var again is all.

**Comment by Kylar82** [comment]
I agree I mean may need to set Helaku to the first point of contact where I would go from him to Halver (who states BC fight, but skip going to BC) then back to Helaku to swap crest for Report?  as this is the only part i cant recheck i done correctly
FYI I am sorry to be taking so much time from you 2 for such a little thing

**Comment by PikaFox** [comment]
Well when youre in game when i, or another GM, am then i can help you.

**Comment by Kylar82** [comment]
Well I'm on pretty much every night GMT time from 9ish to about 12 either leveling or exploring

**Comment by Samikana** [comment]
@Kylar82 please let me know a time you can be online so that I can fix your mission for you.

**Comment by Kylar82** [comment]
I will be on at 9-12ish GMT time most night

**Comment by Samikana** [comment]
@Kylar82 sorry that I couldn't be on, it's hard for me to get time in right now.  Doing my best, in the mean time let's try and figure out a time we can get you fixed.  Sorry that you've had to wait nearly a month to get fixed.

**Comment by Kylar82** [comment]
Don't worry I have been having fun leveling up my jobs and unlocking others, I know there are other things that GM's are working on that are more important than getting me past a mission so I don't mind waiting

**Comment by frank2212** [comment]
stuck on  bastok mission 2-3  sandy windy path  game freezes wen i enter  dragon eye fight  3/10  franky hume  bastok blm/rdm  balgias dias solo

**Comment by Samikana** [comment]
@frank2212 you need to write your own bug report, but I'm pretty sure I fixed you in-game.

@Kylar82 any time you can get on tomorrow

**Comment by Kylar82** [comment]
@Samikana i will be on game from about 8pm gmt til 12ish

**Comment by frank2212** [comment]
ya its been fixed alrdy thx

**Comment by Kylar82** [comment]
Tarot Fixed Thank you ^^

**Comment by PikaFox** [comment]
I have no idea why this wasnt working for Kylar, and ended up having to set the var to 11 and giving kindred report to get it to work, bypassing the kindred crest step.

**Comment by Samikana** [comment]
@PikaFox this route needs to be taken for every mission that is 2-3 Bartok to Sandy.  I forgot to write it on our master post I'm sorry.

**Comment by Samikana** [comment]
I will do that now
