### ISSUE TITLE
San d'Oria Mission 2-3

### ISSUE THREAD

**Issue by daronis17** [LegionDark/Issues#591]
Did the Bastok part first, now I need the push past the Windurst part and the Balga's Dais bugged fight.  Thank you.

**Date & Time**: 2/10/16  7AM
**Frequency**:  once (known issue)
**FFXI Client Version**: 30151223_0
**Character Name**:  Jojo
**Race**: Tarutaru
**Nation**:  San d'Oria
**Main Job**:  White Mage
**Sub Job**:  Red Mage
**Area & Coordinates**:  Balga's Dais (x:298 y:-123 z:345 (68))
**Party or Solo**:  Solo
**NPC or Monster Name**:  mission 2-3 Balga's Dais fight
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**:  attempt to start the fight, it hangs during the cutscene before the fight starts.

**Comment by R3P0FFXI** [comment]
I'll be online Sunday February 14 10am est

**Comment by R3P0FFXI** [comment]
@daronis17 Jojo should be set added the Kindred Crest KI and set your variable.

**Comment by Samikana** [comment]
No response in WAAAAY more than 3 days.  Closing.

**Comment by daronis17** [comment]
I guess this was never closed but I was online two weeks ago when R3P0 said to be online and got my KI then.  Sorry you have been trying to take care of something that was already done.
