### ISSUE TITLE
Soaring Naraka despawned before engaged

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#593]
**Date & Time**: 2/10/2016 10:00 am
**Frequency**: once
**FFXI Client Version**:30151223_0
**Character Name**:Baucant
**Race**:Elvaan
**Nation**:San d`Oria
**Main Job**:Thf
**Sub Job**:Dnc
**Area & Coordinates**: Maquette Abdhaljs-Legion X:174 Y:12 Z:239(248)
**Party or Solo**:Party
**NPC or Monster Name**:Soaring Naraka
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:yes
**Steps To Reproduce The Issue**:None. Fought and clear ever mob on Floor. Allowed those who had died time to recover from weakness. Floor boss despawned without being engaged.

**Comment by Baucant** [comment]
this just happened with Lofty Harpeia as well

**Comment by Baucant** [comment]
this mob too Veiled Sanguiptere

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
