### ISSUE TITLE
2-3 push request

### ISSUE THREAD

**Issue by Grouchmonk** [LegionDark/Issues#594]
**Date & Time**:  02/10/2016
**Frequency**: N/A
**FFXI Client Version**: Ashita
**Character Name**: Nightsong
**Race**: Elvan
**Nation**: San 'Doria
**Main Job**: RDM
**Sub Job**: WAR
**Area & Coordinates**: Giddeus
**Party or Solo**: Solo
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**:  N/A
**Multi-boxing? (multiple clients on same connection)**: N/A
**Steps To Reproduce The Issue**: N/A

**Comment by PikaFox** [comment]
Player was able to proceed.
