### ISSUE TITLE
stuck

### ISSUE THREAD

**Issue by ronnymp** [LegionDark/Issues#595]
Date & Time: 02/10/2016
Frequency: N/A
FFXI Client Version: windower
Character Name: Miudo
Race: galka
Nation: San 'Doria
Main Job: war
Sub Job: sam
Area & Coordinates: white gate
Party or Solo: Solo
NPC or Monster Name: N/A
ffxiah.com link (for inventory items only): N/A
Multi-boxing? (multiple clients on same connection): yes , serjoca
Steps To Reproduce The Issue: N/A

they are both stuck in white gate , when i try log i get blackscreen...weird i can see them online all the time , they dont got DC or something...i've relogged my computer , but still nothing

**Comment by PikaFox** [comment]
Theres an unstuck tool on the website for something like this if needed. http://legiondark.com/?p=stuck

**Comment by TeoTwawki** [comment]
> Date & **_Time_**: 02/10/201

Without the **_time_** I can't look in log to see any server side error that may be associated with your account or character.

**Comment by ronnymp** [comment]
They are still on , u can see them on list on website, miúdo , serjoca and ermess...it was around 5h and 45 mins from now, thx

**Comment by TeoTwawki** [comment]
so what your saying is, you want me to have to stop and do when you open tickets :disappointed: i see how ya are :cry: 

...logging in to see if I can knock you offline

**Comment by TeoTwawki** [comment]
@ronnymp what was the last thing you were doing before the character got stuck?

**Comment by TeoTwawki** [comment]
I just manually axed your session..see if you can log in, report back here, and answer my previous question when you do.

**Comment by ronnymp** [comment]
ok teo ... i was doing legion before zone to white gate... ill try log on right now, thanks alot :)

**Comment by ronnymp** [comment]
yay , got it! no more black screen

**Comment by TeoTwawki** [comment]
I dunno how, but the session was jammed. normally times out after 60 seconds of no login attempts.

**Comment by TeoTwawki** [comment]
Glad clearing the session fixed it, was not looking forward to further diagnosing.

**Comment by ronnymp** [comment]
xD thx alot teo
