### ISSUE TITLE
windurst 9-1 doll of the dead

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#596]
**Date & Time**: 2/11/2015 3:00 pm
**Frequency**: everytime
**FFXI Client Version**: 30151215_0
**Character Name**:Ritonami
**Race**:Mithra
**Nation**:Windurst
**Main Job**: DRG
**Sub Job**:WAR
**Area & Coordinates**: Sanctuary of Zi'Tah
**Party or Solo**: Solo
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/1181/goobbue-humus
**Multi-boxing? (multiple clients on same connection)**:sometimes
**Steps To Reproduce The Issue**: Needed for windurst 9-1 but according to the server tools nothing drops this

**Comment by R3P0FFXI** [comment]
INSERT INTO `mob_droplist` VALUES (1526,0,1181,80);

@ritonami this is fixed in update

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
