### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by LAWNPARTY** [LegionDark/Issues#598]
My e-mail address is taken meaning I have an account. Unable to guess it myself. I cannot email the board administrator because that's been disabled. No one has been able to help in IRC. I cannot join teamspeak because it is passworded.

Can a friend get some friends here or what!!??

**Comment by R3P0FFXI** [comment]
You need to use the template especially because this tells us nothing, ill give you 24 hours to reply with the correct template or we will close this ticket

**Comment by LAWNPARTY** [comment]
**February 2, 2011 10:09 PM CST**: 
**Once instance**:
**Current**:
**None on this server yet**:
**N/a**:
**N/a**:
**N/a**:
**Sub Job**:
**N/a**:
**N/a**:
**N/a**:
**N/a**: 
**N/a**:
**I have tried to contact all of the moderators in IRC**:

**Comment by atom0s** [comment]
Assisted via IRC, account was recovered.
