### ISSUE TITLE
2-3 Windy Fight

### ISSUE THREAD

**Issue by neonovas** [LegionDark/Issues#599]
Date & Time: 2/11/16 
Frequency: Known Issue
FFXI Client Version: 
Character Name: Anna
Race: Mithra
Nation: Windurst
Main Job: Samurai
Sub Job: War
Area & Coordinates:  Waughroon Shrine 
Party or Solo: 
NPC or Monster Name: mission 2-3 Dragon fight
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue: 2-3 Mission for Windurst nation. Did San'dora->Bastok.

I also need the Characters Serale and Arlia pushed through as well. All 3 are the same nation. I have finished San'doria and talked with everyone in Bastok and need to go into the mine to kill the dragon. Just want to make sure I don't need to actually do anything in the mine zone.

**Comment by R3P0FFXI** [comment]
I'll be online Sunday February 14 at 10am est

**Comment by neonovas** [comment]
I'll be at work but I'll try to leave my characters logged in when I leave in the morning.

**Comment by neonovas** [comment]
Tarot happened to be around and pushed me through on all 3 characters so the issue is resolved. Thank you.
