### ISSUE TITLE
Cannot upgrade BRD Empy.

### ISSUE THREAD

**Issue by KinoriGareth** [LegionDark/Issues#6]
**Date & Time**: 5/25/15 - 9:58 PM EST
**Frequency**: Every try.
**FFXi Client Version**: 30150508_8
**Character Name**: Kinori
**Race**: Mithra
**Main Job**: BRD
**Sub Job**: RDM
**Area & Coordinates (Type @where to get this info.)**: X:-51 Y:0 Z:-8 (23)
**Party or Solo**: Party
**NPC Name**: Moogle
**Monster Name**: -
**Steps To Reproduce The Issue**:
-Killed Ovni, obtained Daurdabla
-Killed Briareus, obtained 50 helms.
-Went back to Port Jeuno, tried trading the Empy along with 50 Briareus helms to the Moogle (one closest to Joachim), but no response.
-Tried trading just the Empy itself, but no response either.

**Comment by Loki79** [comment]
Ok this is fixed and will be pulled in with maint today.  Please note the changes to the trial info as well :) it will progress Briarius > Apademak > tanz jewles.
