### ISSUE TITLE
Treasures of Aht Urghan Mission 2 Immortal Sentries Bugged Staging Ground/Can't progress

### ISSUE THREAD

**Issue by Arrytha** [LegionDark/Issues#600]
**Date & Time**: 1AM Est
**Frequency**: Tried twice
**FFXI Client Version**: Current
**Character Name**:  Arrytha
**Race**:  Mithra
**Nation**:  San d'Oria
**Main Job**: Thief
**Sub Job**: Dancer
**Area & Coordinates**: Halvung Staging Point or Mamool Ja Staging Point
**Party or Solo**: Tried both party and solo
**NPC or Monster Name**: Immortal npc in either respective staging ground
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Tried doing the supplies run to two different areas. Apparently upon the first attempt a major lag spike hit and couldn't open the "Heavy Iron Door" and when I finally could, the door was named "Moogle" and all the name labels were messed up inside the Halvung staging ground. Checked Key Items for "Supplies Package" and it's not there anymore. Tried talking to the npc to start mission and she won't even talk to me now. Need a mission reset if possible.

**Comment by R3P0FFXI** [comment]
I'll be online Sunday 10am est February 14

**Comment by Arrytha** [comment]
If I leave my character logged in will that work? I won't be able to be
online and at my computer at that time. Would be home around 12:30-1pm

On Fri, Feb 12, 2016 at 12:17 PM, R3P0FFXI <notifications@github.com> wrote:

> I'll be online Sunday 10am est February 14
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LegionDark/Issues/issues/600#issuecomment-183418569>.
>



-- 
Joe Driver
Survey Party Chief
Terra Engineering and Land Solutions, PC
540-337-4591
http://www.terraengineering.net/

**Comment by R3P0FFXI** [comment]
Yes that would work

**Comment by R3P0FFXI** [comment]
@Arrytha Supplies Package added

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
