### ISSUE TITLE
Hvergelmir 99-4 not have with Crit +25% and Crits doing about 4x dmg 

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#602]
Date & Time: 12/02/2016, 23:00pm
Frequency: Always
FFXI Client Version: 30151233_0
Character Name: Aurel
Race: Hume
Main Job: blm
Sub Job: Sam
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name:Renik
Monster Name:
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/21144/hvergelmir
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:this weapon does not have any kind of buff   ,,,although for a BLM should have fast attack and casting magic buff

**Comment by Baucant** [comment]
Based on you ScreenShot you are hitting for crits 3 out of 5 times that is 60% so that part does seem to be working. IDK about the crit damage calulations though.

**Comment by Samikana** [comment]
@nekrol is correct that it's not coded to be custom like the rest of the Empyrean weapons.  I'll do this when I get a chance, but it may not be for a week or more.

**Comment by R3P0FFXI** [comment]
Sorry we cant fix stupid
