### ISSUE TITLE
USer name and Password help

### ISSUE THREAD

**Issue by Mizrabel** [LegionDark/Issues#603]
**Date & Time**: 2/12/2016 10:11
**Frequency**:MY fault
**FFXI Client Version**: can't log in to tell you
**Character Name**:Mizrabel
**Race**:Taru
**Nation**:Sandy
**Main Job**:Blm
**Sub Job**:N/A
**Area & Coordinates**:Maze of Shakhrami
**Party or Solo**:Solo
**NPC or Monster Name**:N/A
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**:N/A
**Steps To Reproduce The Issue**: attempted to log in with what I thought was my user name and password.

**Comment by Baucant** [comment]
Atomos help me:)

**Comment by atom0s** [comment]
Handled via IRC.
