### ISSUE TITLE
San D'orian 2-3 Mission help

### ISSUE THREAD

**Issue by geahlen** [LegionDark/Issues#604]
Did the Bastok part first, now I need the push past the Windurst part and the Balga's Dais bugged fight. Thank you.

Date & Time: 2/13/16 2AM
Frequency: once (known issue)
FFXI Client Version: 30151223_0
Character Name: Geahlen
Race: Hume
Nation: San d'Oria
Main Job: Ninja
Sub Job: Warrior
Area & Coordinates: Balga's Dais
Party or Solo: Solo
NPC or Monster Name: mission 2-3 Balga's Dais fight
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue: attempt to start the fight, it hangs during the cutscene before the fight starts.

**Comment by geahlen** [comment]
I am ready for this again.  Thanks so much for the help!!

Geahlen

**Comment by PikaFox** [comment]
Set payer's var and added KI, player was afk at time of post. Will leave this open to see if players issue has been resolved or not.

**Comment by geahlen** [comment]
Success!  Thank you!
