### ISSUE TITLE
Server Xfer

### ISSUE THREAD

**Issue by geahlen** [LegionDark/Issues#605]
Hello!

Don't know if this is an issue or not.  My server xfer was completed successfully.

None of my stored items on "Porter Moogle" are present.  Not even the Level 75 gear.

Also none of my items in my safe, storage, locker, satchel, sack, case were imported, only some items from my wardrobe came in.

If it's not possible to bring in items stored on porter moogle, would it be possible for me to get those items into my safe, storage, locker, etc and have my char re-imported?

Thanks so much for all you do.  If none of this is possible, i understand and will put in my due diligence on this server to regain what could not be imported.

Thanks again!

Thom

**Comment by TeoTwawki** [comment]
Its normal for porter moogle'd items to not be transferred, as there is no method to scan the slips and determine what was stored. However your other items being missing is an indication something went wrong on import, so we'll have to re-import you. post to the server transfer forum again and link this issue page for reference.

**Comment by R3P0FFXI** [comment]
Reimported
