### ISSUE TITLE
Possible server Crash

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#606]
**Date & Time**: 2/13/2016 5:20pm
**Frequency**: Just now
**FFXI Client Version**: not able to log in to aquire
**Character Name**:Baucant
**Race**:Elvaan
**Nation**:Sandy
**Main Job**:Blm
**Sub Job**:Rdm
**Area & Coordinates**: all areas all corrdinates
**Party or Solo**:Party
**NPC or Monster Name**:N/A
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**:continues to try to log in after waiting 20 mins with no success

**Comment by Arrytha** [comment]
Same problem (maybe they are patching in the massive update....! *shows optimism* )

**Comment by Baucant** [comment]
No Atomos just fixed it....all if fine now
