### ISSUE TITLE
Spool Of Light Filament (how to get)?

### ISSUE THREAD

**Issue by Zeldha** [LegionDark/Issues#607]
**Date & Time**: February 15, 2016
**Frequency**: Always
**FFXI Client Version**: 30121504_2
**Character Name**: Vida
**Race**: Mithra
**Nation**: Sa d'Oria
**Main Job**: THF
**Sub Job**: NIN
**Area & Coordinates**: -
**Party or Solo**: Solo
**NPC or Monster Name**: -
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/1941/light-filament
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: Cant find where to get this item using drop info in LegionDS website.

**Comment by R3P0FFXI** [comment]
@Zeldha This item drops from Apollyon at random as it does in retail
