### ISSUE TITLE
Bastok 2-3 Mission (Sandy to Windy)

### ISSUE THREAD

**Issue by Onemonsterkitty** [LegionDark/Issues#608]
Date & Time: 09/14/16 15:36 PST
Frequency:
FFXI Client Version: 30151223_0
Character Name: Muvant
Race: Elvaan
Nation: Bastok
Main Job: DRK
Sub Job: BLM
Area & Coordinates: Bastok Mines
Party or Solo: Solo
NPC or Monster Name: n/a
ffxiah.com link (for inventory items only): n/a 
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue: Dont want to enter BC and cause CS crash

**Comment by PikaFox** [comment]
Set players Var and gave them the proper KI. Player was afk but online, ill leave this open for them to close to confirm the issue is resolved.

**Comment by Onemonsterkitty** [comment]
Thanks fam
