### ISSUE TITLE
legiondark login information

### ISSUE THREAD

**Issue by Arrytha** [LegionDark/Issues#609]
I have forgotten my login info for the legiondark website for forums and stuff. Any way to retrieve it again? (securely, no public replies/posts) :P 

Date & Time: N/A
Frequency: Login
FFXI Client Version: 30151223_0
Character Name: Arrytha
Race: Mithra
Nation: San d'Oria
Main Job: Thief
Sub Job: Dancer
Area & Coordinates: N/A
Party or Solo: N/A
NPC or Monster Name: N/A
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): N/A
Steps To Reproduce The Issue: Multiple failed login attempts

**Comment by R3P0FFXI** [comment]
If its forums create a new login
