### ISSUE TITLE
Vajra (75) trial wont start

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#61]
**Date & Time**:  6/5/15
**Frequency**: Always
**FFXI Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: Hume
**Main Job**: Pld
**Sub Job**: Nin
**Area & Coordinates**: Rulude
**Party or Solo**: Alliance
**NPC Name**: Akta
**Monster Name**: NA
**Steps To Reproduce The Issue**: Trade Vajra 75 to him, he does nothing and says nothing. No movement or response at all.

**Comment by Loki79** [comment]
i know @TeoTwawki  is currently sorting these out.

**Comment by itachioax** [comment]
yep same bug happen to me, i cant start the same trial

**Comment by TeoTwawki** [comment]
Somehow this weapon (and all of its upgrades) are 100% missing form all trial related scripts. Will get it incorporated into the new version

**Comment by R3P0FFXI** [comment]
75 18996
85 19085
95 19715
99-1 19824
99-4 20560

**Comment by TeoTwawki** [comment]
I haven't finished the rewrite just yet but vagra should be trial-able now

**Comment by TeoTwawki** [comment]
small update: I forgot Omni used static `if id == number then` checks in all those npc's, so the trials for this (also yagrush) won't work till the trial update is live after next maint. Blarg.

It'll all be golden after that next maint though.

**Comment by Strafeous** [comment]
Did you end up coding Yagrush after all? I'm pretty sure Mega pushed his stuff last night and he did all of Yagrush. If he didn't, he will have today before maintenance.

**Comment by TeoTwawki** [comment]
@Strafeous I'm only talking about the trials, not the item stats etc, which is an entirely separate issue that I know nothing about.

**Comment by TeoTwawki** [comment]
(and wasn't even reported here so I dunno why this issue had that label)

**Comment by Strafeous** [comment]
Gotcha, I'll send you the info to fix it once Mega pushes it, he decided to wait since maintenance was pushed back
