### ISSUE TITLE
5.1 San D'orian Mission CS Stuck entering Fei'Yin

### ISSUE THREAD

**Issue by geahlen** [LegionDark/Issues#610]
**Date & Time**:  2/16/16  1:45pm
**Frequency**: seems to be every time
**FFXI Client Version**: 30160203_0
**Character Name**:  Geahlen
**Race**:  Hume
**Nation**:  San D'oria
**Main Job**:  Ninja
**Sub Job**:  Dancer
**Area & Coordinates**:  Fei'Yin entrance
**Party or Solo**: Solo
**NPC or Monster Name**: 5.1 Mission San D'oria
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**: used server stuck tool, ran back to Fei'Yin, re-entered Fei'Yin.

This happened with both Windower 4 and AshitaV2
Character Geahlen freezes up on entry into Fei'Yin and the CS triggers.  Screen stays black and only hear CS music.

**Comment by Samikana** [comment]
No one is going to help you until you have your FFXI client version listed.  You can access this by typing /ver in-game.

**Comment by geahlen** [comment]
Sorry for the late response.  It's version 30160203_0

**Comment by Samikana** [comment]
@TeoTwawki is there any specific reason for this?

**Comment by geahlen** [comment]
I remember this being a windower issue in retail... the way to get past it
was to login using only the POL- Viewer... there were a few CS that locked
like this one.  The only way to get past it was to login w/o using a Third
Party Program.

**Comment by TeoTwawki** [comment]
Likely NPC ID /client version  causing it. When a CS calls for an NPC the server can't find, it does exactly this. The coming update will fix it.

**Comment by TeoTwawki** [comment]
When a cs actually loads but then freezes after the black screen is gone, then it could be same NPC ID issue but is more likely a plugin or addon. Freezing on a black screen has always been NPC probs when I have looked, or mro erarely bugs with DSP's daisy chained cs's (lookin at you ZIlart 4 !).

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
