### ISSUE TITLE
Aht Urhgan M2 no Supplies Package

### ISSUE THREAD

**Issue by w3genesis** [LegionDark/Issues#611]
**Date & Time**: 2016/02/17
**Frequency**: Once
**FFXI Client Version**: Newest
**Character Name**: Sworddemon
**Race**: Galka
**Nation**: Bastok
**Main Job**: Sam 99
**Sub Job**: Thf 49
**Area & Coordinates**: Aht Urhgan Whitegate (I-10)
**Party or Solo**: Solo
**NPC or Monster Name**: Naja Salaheem
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce The Issue**:
Talked to Naja Salaheem to start Aht Urhgan Mission 2: Immortal Sentries, but at end of cut scene, did not receive Supplies Package in key item. Cannot proceed with mission.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2960
