### ISSUE TITLE
Key Items Gone. Maps Gone.

### ISSUE THREAD

**Issue by monicawebmage** [LegionDark/Issues#612]
Hello,

Is there any chance that you can restore my key items please?

**Date & Time**:  18th February 2016
**Frequency**: All the time
**FFXI Client Version**: 30160203_0
**Character Name**: Zoralyn
**Race**: Female Elvaan
**Nation**: Bastok
**Main Job**: BLM
**Sub Job**: WHM
**Area & Coordinates**: 
**Party or Solo**: Solo
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**: I tried to use the @tele dem command but today it did not work. I checked my key items and they are all gone. Including the pure white feather obtained by going through a Cavenous maw to get to the past to unlock SCH. The key items I remember getting are:

Tele dem
Tele mea
Tele la thiene
Kahzam airship pass
Tele Yhoat
Tele Jugner 
Pure white feather
Chocobo license

In regards to the maps. They all stopped displaying even after a reinstall of Ashita. I decided to purchase maps from a vendor so that sort of solved the issue - although I wish I could have bought them at a low price to compensate having this bug :(

Let me know if there's any more information you need from me.

Thanks,
Monica.

**Comment by Samikana** [comment]
@TeoTwawki is this adoulin anti-cheat?

**Comment by monicawebmage** [comment]
Hi Teo,

I'm quite new to this server I don't know what the adoulin anti-cheat is. What does that mean?

**Comment by TeoTwawki** [comment]
@Samikana no, adoulin thing only wipes homepoints

**Comment by monicawebmage** [comment]
Hello,

Thanks so much for looking into this. The items I mentioned above I'm sure are the only ones I lost - luckily I haven't played the game too much yet so had not obtained many key items.

The main problematic key item for me is the chocobo license due to the fact that I have already completed the quest so am unable to re - obtain a license. The maps at least I can buy those and the Teleport Crystals I can get those too. I'm not sure about the pure white feather - I have not tried to re obtain it.

Let me know if you need any more information from me. 

Many thanks!
Monica.

**Comment by TeoTwawki** [comment]
@monicawebmage thank you for further info and clarification, those being the only ones makes it much easier to fix you up - we'll just re add them. Have all your missions quests and spells stayed normal? They are stored in a similar manner. In the coming update some of that will change and will help prevent data corruption. 

If you can, I'd appreciate checking your KI lists for any unusual key items you should not actually have. We had the previous 2 players hit by this bug not only lose their keyitems but get strange random keyitems for no reason.

**Comment by monicawebmage** [comment]
Hello,

There are no unusual Key Items and all my quests seem fine thanks.
I did buy a few maps because I was totally lost without them xD Do you need the list of maps I bought? Today I also went to re-get Tele mea, dem and holla. I have a total of 3 Key items now.

Many thanks,
Monica.

**Comment by Samikana** [comment]
@monicawebmage please let me know when you can get in-game so that I can add your maps back.  My in-game name is Halsey.

**Comment by monicawebmage** [comment]
Hello,

Thanks ok I will log in now.

**Comment by monicawebmage** [comment]
Hello,

Is there any update please on applying my fix? I'd really appreciate this. I really don't want to start my character from the beginning (how can I be sure the error wont happen again?) but please let me know if this is the only option.

I look forward to hearing from you.

**Comment by TeoTwawki** [comment]
@Samikana I happened to be on at same time and squared them away.
