### ISSUE TITLE
Windurst Mission 2-3 & BLU Quest CS's

### ISSUE THREAD

**Issue by Schaedelschaden** [LegionDark/Issues#613]
**Date & Time**: 02/18/16 - 4:03 PM MST
**Frequency**: Once (known issue)
**FFXI Client Version**: 30151103_3
**Character Name**: Aeria, Naria, Khalum
**Race**: Mithra, Mithra, Galka
**Nation**: Windurst (All 3)
**Main Job**: BLM, BLM, BLM
**Sub Job**: WHM, WHM, DNC
**Area & Coordinates**:  Waughroon Shrine (X: -338 Y: 104 Z: -260 (7)) & Aydeewa Subterrane (X: 379 Y: 0 Z: 348 (64))
**Party or Solo**: Party
**NPC or Monster Name**: Mission 2-3 - Waughroon Shrine BCNM
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**: Bugged CS for Rank Mission 2-3 & Bugged CS for BLU unlock

All three characters are currently at the CS portion of the Rank mission and BLU quest.

**Comment by PikaFox** [comment]
All 3 got Blu CS and all 3 should be able to progress now.
