### ISSUE TITLE
Blu Unlock

### ISSUE THREAD

**Issue by jonvito** [LegionDark/Issues#618]
Date & Time: 2/20/16 @ 5:15 Pm EST
Frequency: Everytime
FFXI Client Version: Version30160203_0
Character Name: Brogg
Race: Galka
Nation: Sandoria
Main Job: MNK
Sub Job: DNC
Area & Coordinates: Aydeewa Subterrane | (H-9) | x:379 y:0 z:347 (103)
Party or Solo: Solo
NPC or Monster Name: n/a
ffxiah.com link (for inventory items only): n/a
Multi-boxing? (multiple clients on same connection): Nope
Steps To Reproduce The Issue:It's a known issue, crashes at beginning of cs.

**Comment by Azurerite** [comment]
**Date & Time**: 
2/20/2016 8:45 pm pst
**Frequency**:
everytime
**FFXI Client Version**:
30160203_0
**Character Name**
Azurerite:
**Race**:
Tarutaru
**Nation**
Windurst:
**Main Job**
Red Mage
**Sub Job**:
None
**Area & Coordinates**:
Aydeewa Subterrane x514 y-32 z459
**Party or Solo**:
solo
**NPC or Monster Name**
None:
**ffxiah.com link (for inventory items only)**:
none 
**Multi-boxing? (multiple clients on same connection)**:
no
**Steps To Reproduce The Issue**:
Happens everytime

**Comment by Samikana** [comment]
@Azurerite create your own bug report, don't add onto another person's

**Comment by Samikana** [comment]
@jonvito need to know what time you can get online

**Comment by jonvito** [comment]
I am online for the rest of the day and can be online anytime this weekend.

**Comment by jonvito** [comment]
@Samikana If you are unable to get to me during the weekend i can do any day during the week after 5:00 p.m. EST.
