### ISSUE TITLE
Mandau 85 doesn't give Aftermath effect

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#62]
**Date & Time**:  6/5/2015 12:27 pm (est)
**Frequency**: anytime I use mercy Stroke
**FFXI Client Version**:30150508_8
**Character Name**: Baucant
**Race**: Elvaan
**Main Job**: Thf
**Sub Job**: Dnc
**Area & Coordinates**: all areas
**Party or Solo**: both
**NPC Name**: N/A
**Monster Name**: all mobs
**Steps To Reproduce The Issue**:did numberous WSs with mandau in main hand. I was recieving the aftermath effect when mandua was 75 now that it's upgraded to 85 I no longer recieve aftermath effect

**Comment by itachioax** [comment]
aftermath is not coded, it wont work

**Comment by R3P0FFXI** [comment]
Aftermath itself is not coded, as explained Occ does dmg effects added, found Poison script was not connected to relics, it has been added to all relics that have scripts between 75-99-4 and will go in at Tuesdays maint.
