### ISSUE TITLE
Sandy 2-3 Mission

### ISSUE THREAD

**Issue by jonvito** [LegionDark/Issues#620]
Did the bastok to windy path.
Date & Time: 2/20/16 @ 5:15 Pm EST
Frequency: Everytime
FFXI Client Version: Version 30160203_0
Character Name: Brogg
Race: Galka
Nation: Sandoria
Main Job: MNK
Sub Job: DNC
Area & Coordinates: Balga's Dais (x:298 y:-123 z:345 (68))
Party or Solo: Solo
NPC or Monster Name: n/a
ffxiah.com link (for inventory items only): n/a
Multi-boxing? (multiple clients on same connection): Nope
Steps To Reproduce The Issue:It's a known issue.

**Comment by Samikana** [comment]
Please contact me (Halsey) or @PikaFox (Tarot) in-game when you see us or let us know what date/time you can be on so we can fix you up.

**Comment by jonvito** [comment]
I am online for the rest of the day and can be online anytime this weekend.

**Comment by jonvito** [comment]
If you are unable to get to me during the weekend i can do any day during the week after 5:00 p.m. EST.

**Comment by Samikana** [comment]
@jonvito Can you log on now?

**Comment by jonvito** [comment]
@Samikana sorry missed this, but I'm on for few more hours from now, and be on from 5 EST. till late tomorrow.
