### ISSUE TITLE
Mobs spawning behind walls Dynamis Qufim

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#621]
**Date & Time**: 2/20/2016 6:30pm
**Frequency**: after defeating the Zone Boss
**FFXI Client Version**:30151223_0
**Character Name**:Baucant
**Race**:Elvaan
**Nation**:Sandy
**Main Job**:Thf
**Sub Job**:Dnc
**Area & Coordinates**:Dynamis Quifim Mob is inside of a wall can not acquire coordinates Found via wide scan
**Party or Solo**: Solo
**NPC or Monster Name**:Nightmare Diremite & Nightmare Tiger
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**:Not at this time
**Steps To Reproduce The Issue**: Was unable to target. Tracked them via wide scan.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
