### ISSUE TITLE
BCNM/KSNM working list

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#622]
BCNMs
Name       -                                                   Zone          -                              Status

Level 20    Cloudy Orb
(20 Beastmen's Seals)

Charming Trio                          -                 Balga's Dais          -                  Works
Crustacean Conundrum            -                Waughroon Shrine -  Trade not accepted
Shooting Fish                            -               Horlais Peak -  Trade not accepted
Wings of Fury                             -              Ghelsba Outpost- Works

Level 30    Sky Orb
(30 Beastmen's Seals)

Birds of a Feather                     -             Waughroon Shrine - No mobs just chest; doesn't exit upon opening chest
Carapace Combatants             -            Horlais Peak- No option given
Creeping Doom                        -           Balga's Dais-Trade not accepted
Die by the Sword                          -          Qu'Bia Arena-Trade not accepted
Petrifying Pair                                -         Ghelsba Outpost-works

Dropping Like Flies                         -        Horlais Peak   - Works
Grove Guardians                          -       Waughroon Shrine - No option given
Harem Scarem                              -      Balga's Dais-Trade not accepted
Let Sleeping Dogs Die                      -     Qu'Bia Arena-Trade not accepted
Toadal Recall                                       -    Ghelsba Outpost -No option given

Level 40    Star Orb
(40 Beastmen's Seals)

Under Observation              -                     Horlais Peak-Trade not accepted
Undying Promise             -                    Qu'Bia Arena-Trade not accepted
Royal Jelly                      -                   Waughroon Shrine-Trade not accepted
Royal Succession                  -                  Balga's Dais-Trade not accepted

Factory Rejects      -                           Qu'Bia Arena-Trade not accepted
Steamed Sprouts       -                          Balga's Dais-Trade not accepted
Tails of Woe                   -                         Horlais Peak-Trade not accepted
The Worm's Turn         -                        Waughroon Shrine-Trade not accepted

Level 50    Comet Orb
(50 Beastmen's Seals)

The Final Bout              -                           Waughroon Shrine-Trade not accepted

An Awful Autopsy         -                          Qu'Bia Arena-Trade not accepted
Eye of the Tiger          -                         Horlais Peak-No option given
Rapid Raptors                  -                        Balga's Dais-Trade not accepted
Hostile Herbivores          -                       Horlais Peak- Works

3, 2, 1...                        -                        Waughroon Shrine-Trade not accepted
Idol Thoughts                  -                       Qu'Bia Arena-Trade not accepted
Treasure and Tribulations   -              Balga's Dais-Trade not accepted

Level 60    Moon Orb
(60 Beastmen's Seals)

Celery                       -                         Qu'Bia Arena-Trade not accepted
Shots in the Dark         -                        Horlais Peak-Trade not accepted
Up in Arms                 -                       Waughroon Shrine-Works
Wild Wild Whiskers          -                      Balga's Dais-Trade not accepted

Amphibian Assault       -                          Sacrificial Chamber-No option given
Brothers D'Aurphe        -                         Qu'Bia Arena-Trade not accepted
Demolition Squad          -                        Qu'Bia Arena-Trade not accepted
Dismemberment Brigade-                      Horlais Peak-Trade not accepted
Divine Punishers             -                     Balga's Dais-Trade not accepted
Grimshell Shocktroopers   -                    Waughroon Shrine-No option given
Jungle Boogymen           -                    Sacrificial Chamber-Works
Kindred Spirits                    -                   Throne Room-Trade not accepted
Legion XI Comitatensis      -                  Chamber of Oracles-Trade not accepted

Atropos Orb
(30 Kindred's Seals)

Contaminated Colosseum  -                Horlais Peak-Works
Infernal Swarm                   -               Qu'Bia Arena-Trade not accepted
Moa Constrictors                      -              Balga's Dais-Trade not accepted
Prehistoric Pigeons                    -             Waughroon Shrine- Works
The Scarlet King                        -           Chamber of Oracles-Trade not accepted

Clotho Orb
(30 Kindred's Seals)

Cactuar Suave                                -        Chamber of Oracles-Trade not accepted
Come Into My Parlor               -       Qu'Bia Arena-Trade not accepted
Copycat                                        -      Waughroon Shrine-Trade not accepted
Double Dragonian                            -     Horlais Peak-Works
Seasons Greetings                            -    Balga's Dais- Trade not accepted

Lachesis Orb
(30 Kindred's Seals)

E-vase-ive Action         -                       Qu'Bia Arena-Trade not accepted
Eye of the Storm           -                      Chamber of Oracles-Trade not accepted
Operation Desert Swarm  -                     Waughroon Shrine-Works
Royale Ramble            -                    Balga's Dais-Trade not accepted
Today's Horoscope             -                   Horlais Peak-Trade not accepted

Themis Orb
(99 Kindred's Seals)

Early Bird Catches the Wyrm   -           Balga's Dais-Works
Horns of War                               -          Horlais Peak-Works
The Hills Are Alive                     -         Waughroon Shrine-Works

**Comment by R3P0FFXI** [comment]
@Baucant All these BCNM/KSNM work with no issues? Hello new content!

**Comment by Arrytha** [comment]
Good to know! I was wondering if any of these fights were coded in. :)

**Comment by Heepster03** [comment]
This has been relocated to the wiki at: http://wiki.legiondark.com/BCNM/KSNM_Status
