### ISSUE TITLE
Bastok Mission 2-3

### ISSUE THREAD

**Issue by Xenriv** [LegionDark/Issues#623]
**Date & Time**:  2/20/2016
**Frequency**: Once 10:40 PM EST
**FFXI Client Version**:  30151223_0
**Character Name**: Xenriv
**Race**: Hume
**Nation**:  Bastok
**Main Job**:  Thief
**Sub Job**: Dancer
**Area & Coordinates**:  Balga's Dais (x:298 y:-123 z:345 (68))
**Party or Solo**: Solo
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**:  Re-enter the Mission BCNM

Thank you

**Comment by genesis3951** [comment]
i also have the same issue

**Comment by Samikana** [comment]
@genesis3951 you need to write your own bug report if you haven't already.

@Xenriv's issue is fixed.  You can proceed by following the steps that are after the fight
