### ISSUE TITLE
Blue Mage Quest.

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#626]
Frequency: Everytime
Character Name: Spectre
Race: Tarutaru
Nation: Windurst
Main Job: RDM
Sub Job: DNC
Area & Coordinates: Aydeewa Subterrane | (H-9) | x:379 y:0 z:347 (103)
Party or Solo: Solo
NPC or Monster Name: n/a
ffxiah.com link (for inventory items only): n/a
Multi-boxing? (multiple clients on same connection): Nope
Steps To Reproduce The Issue:It's a known issue, crashes at beginning of cs.

**Comment by Samikana** [comment]
Fixed
