### ISSUE TITLE
No Werebats in Bostaunieux Oubliette

### ISSUE THREAD

**Issue by psyops78** [LegionDark/Issues#627]
**Date & Time**: 21st February @ 12:00pm GMT
**Frequency**: Constant as far as I can tell. 
**FFXI Client Version**:30151223_0
**Character Name**: Magpie
**Race**: Mithra
**Nation**: Sand'oria
**Main Job**: 69THF 
**Sub Job**: 34DNC 
**Area & Coordinates**:Bostaunieux Oubliette
**Party or Solo**: Solo
**NPC or Monster Name**: Werebat
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Visited again 8 hours later and still no spaws of this mob.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
