### ISSUE TITLE
CoP three path (tenzen path)

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#628]
**Date & Time**: 
**Frequency**:
**FFXI Client Version**:
**Character Name**: Sakuraoax
**Race**: Hume
**Nation**: Sandy
**Main Job**: WHM
**Sub Job**:RDM
**Area & Coordinates**:
**Party or Solo**: Party dual box D=
**NPC or Monster Name**: noone
**ffxiah.com link 
**Multi-boxing? (one more client
**Steps To Reproduce The Issue**:
1. Click the ??? at (G-6) in La Theine Plateau where you met Carbuncle in I Can Hear a Rainbow if you unlocked Summoner. Teleport-Holla, 
2.Enter Pso'Xja from the tower at (J-8) in Beaucedine Glacier
3.Check the Avatar Gate (H-8) for a cutscene. 
5-3T2: Branded 
1.Talk to Monberaux in the Infirmary Monberaux at Upper Jeuno (G-10) (Home Point #3). Obtain: KeyItemEnvelope from Monberaux
2. Talk to Pherimociel in the Guard Post of the Ducal Palace, Ru'Lude Gardens (G-6) (Home Point #1) to get a cutscene involving Wolfgang.
3. Talk to Monberaux again.
5-3T3: Pride and Honor
1.  Walk out of Upper Jeuno into Batallia Downs and out through the gate in the wall. Turn left and examine the ??? at (K-8) once for a cutscene and then a second time for a KeyItem Delkfutt Recognition Device.
at this point, i didnt touch ??? so never get the ki, then i gone to delkfut tower with my dual box, and kill that NM cuz my dual could get the ki, i never noticed it D=.... when i came back to try get the KI i couldn't get it T_T, probably i broke it with that ki and i wont get it again, plz help me sry, cuz my english is bad hehe but i tried.
P.D. already try relog char, and tried get start cs at la theine with carby and tenzen, but nothing happen, same tried talk with monberaux and nothing happen =(

    Be sure to examine it twice!!

**Comment by itachioax** [comment]
already tried, checked ??? twice, and not getting the ki =(

**Comment by Samikana** [comment]
It looks like they were dualboxing and the client got confused, because their variable was updated, they just don't have the KI.  Went ahead and gave @itachioax the KI.
