### ISSUE TITLE
San D'orian 2-3 Unable to trade Onz of Mythril Sand 

### ISSUE THREAD

**Issue by geahlen** [LegionDark/Issues#629]
Did the bastok to windy path.
Date & Time: 2/22/16 @ 19:35 MST
Frequency: Everytime
FFXI Client Version: Version 30160203_0
Character Name: Giselda
Race: Hume
Nation: San d'oria
Main Job: WHM
Sub Job: RDM
Area & Coordinates: Bastok Markets (I-9) NPC Savae E Paleade
Party or Solo: Solo
NPC or Monster Name: Savae E Paleade
ffxiah.com link (for inventory items only): n/a
Multi-boxing? (multiple clients on same connection): Nope
Steps To Reproduce Repeated attempts to trade "Onz of Mythril Sand"

**Comment by Samikana** [comment]
This stupid fucking NPC gives me nothing but trouble.

I can't help you without you being online for me to check your variable.  Let me know when you'll be online as I'm not really logging in bc i'm still in recovery

**Comment by geahlen** [comment]
Cant say for sure when i'll be online next.  Family always comes first for
playtime.  I am almost always online saturday mornings from around 9am -
noon MST.

what is your name online so that I know who to look for when I am online
next.  Getting past this is not an urgent issue for me.

Thanks for your help!

**Comment by Samikana** [comment]
@geahlen you weren't online when I was, so I'm still going to need you to let me know when you can get online and it also depends if I can get online.  My name is Halsey in-game

**Comment by geahlen** [comment]
I have my character Giselda online right now, can stay online for the next
3-4 hours

**Comment by TeoTwawki** [comment]
@geahlen without looking at wiki, can you tell me all steps you did prior to attempting the trade, from the very beginning of the mission? Its not that I don't believe you, its that I want to track down which step failed to behave properly so this doesn't happen anymore so @Samikana doesn't go nuts from this NPC. :smiley: She'll still fix you up.

**Comment by geahlen** [comment]
i followed the steps at ffxiwiki.

basically accepted the mission, spoke with the npc's i needed to... chose
the sandy - bastok - windy path.  went to caves, mined the gravel?  w/e
it's called.  traded it to the grinder thing clicked the lever to the
right, dropped to the bottom got the sand.  warped back to hp, used crystal
to get to metalworks by the embassy, clicked on NPC, attempted trade,
nothing happened after completing the trade.

I hope this helps.

**Comment by geahlen** [comment]
This is no longer an issue, apparently i missed a cutscene prior to
gathering the onz of mythril sand.  I have successfully traded and now have
the KI Dark Key for the 2-3 fight.

**Comment by Samikana** [comment]
*slams head on desk repeatedly*
