### ISSUE TITLE
annihilator animation

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#63]
**Date & Time**: 05/06/2015
**Frequency**: always
**FFXI Client Version**:
**Character Name**: Itachioax
**Race**: Humen
**Main Job**: RNG
**Sub Job**: SAM
**Area & Coordinates**: any
**Party or Solo**: party
**NPC Name**: none
**Monster Name**: none
**Steps: just  animation of attack from annihilator 99-4 doesnt look, can u fix it =D

**Comment by Loki79** [comment]
Fix will be in Tuesday maint.
