### ISSUE TITLE
Blu mage quest

### ISSUE THREAD

**Issue by Azurerite** [LegionDark/Issues#631]
**Date & Time:** 2/20/2016 8:45 pm pst
**Frequency:** everytime
**FFXI Client Version:** 30160203_0
**Character Name:** Azurerite:
**Race:** Tarutaru
**Nation:** Windurst
**Main Job:** Red Mage
**Sub Job:** None
**Area & Coordinates:** Aydeewa Subterrane x514 y-32 z459
**Party or Solo:** solo
**NPC or Monster Name:** None
**ffxiah.com link (for inventory items only):** none 
**Multi-boxing? (multiple clients on same connection):** no
**Steps To Reproduce The Issue:** Happens everytime

_Eddied by GM for readability._

**Comment by Azurerite** [comment]
Sorry about commenting on the other one i wasnt sure how it was supposed to be done

**Comment by Samikana** [comment]
@Azurerite please send me (halsey) a tell in-game when you are online.

**Comment by Samikana** [comment]
No response after 3+ days.  Closing.
