### ISSUE TITLE
The Emissary (Windurst)

### ISSUE THREAD

**Issue by Akuma9** [LegionDark/Issues#632]
ï**Date & Time**: 2/25/2016
**Frequency**: 
**FFXI Client Version**: 30151223_0
**Character Name**: Akuma
**Race**: Elvaan
**Nation**: Bastok
**Main Job**: Red Mage
**Sub Job**: None
**Area & Coordinates**: X:509 Y:0 Z:-439 (97)
**Party or Solo**: Solo
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**:
I am on mission 2-3. I went to San d'Oria and completed the quest there. When I go to Windurst I can not complete the quest. I am trying to get passed this mission, but game keeps on freezing when I enter the circle thing.
Please help me get passed the mission. Thank you.

**Comment by R3P0FFXI** [comment]
@Akuma9 This really does not tell us anything I hope this is what you need is not the issue at hand what exactly is the problem

**Comment by Akuma9** [comment]
How do you need me to word it? 

I need assistance on moving passed that mission. I was told that it was a known issue. 


Sent from Outlook Mobile






On Fri, Feb 26, 2016 at 3:46 AM -0800, "R3P0FFXI" <notifications@github.com> wrote:












@Akuma9 This really does not tell us anything I hope this is what you need is not the issue at hand what exactly is the problem

**Comment by Samikana** [comment]
@R3P0FFXI they're experiencing the same 2-3 issue as everyone else.  @Akuma9 please send me (Halsey) a tell in-game when you get a chance.

**Comment by Akuma9** [comment]
I'm in game now.  When do you usually get on? Maybe we can sync our game times 

    On Monday, February 29, 2016 6:28 PM, Sami <notifications@github.com> wrote:
 

 @R3P0FFXI they're experiencing the same 2-3 issue as everyone else. @Akuma9 please send me (Halsey) a tell in-game when you get a chance.—

**Comment by Samikana** [comment]
All fixed :)
