### ISSUE TITLE
Current/completed CoP Dawn in mission log. No ring.

### ISSUE THREAD

**Issue by neojinx** [LegionDark/Issues#633]
**Date & Time:** February 26th, 1016
**Frequency:** All the time
**FFXI Client Version:**30151215_0
**Character Name:** Neojin and Caffine
**Race:** Hume and Taru
**Nation:** Bastok
**Main Job:** 99 THF and 99 WHM 
**Sub Job: **49 DNC and 49 RDM 
**Area & Coordinates:** Ru'lude Gardens and Upper Jeuno
**Party or Solo:** Party
**NPC or Monster Name:** N/A
**ffxiah.com link (for inventory items only):** N/A
**Multi-boxing? (multiple clients on same connection):** Yes
**Steps To Reproduce The Issue:** Completed all the CoP cutscenes for Dawn until the one in Ru'lude Gardens on both characters. Unable to activate cutscene in Ru'lude gardens or Upper Jeuno for CoP ring. Checked mission log on both characters and Dawn is shown as current and completed but did not get ring. Same thing happened to another person at: [http://legiondark.com/forums/viewtopic.php?f=28&t=476&p=1387&hilit=dawn#p1387]

**Comment by TeoTwawki** [comment]
I fixed variable issue for Neojin and Caffine
