### ISSUE TITLE
Mission 2-3 basok stuck

### ISSUE THREAD

**Issue by genesis3951** [LegionDark/Issues#634]
Date & Time: 2/20/2016
Frequency: Once 10:40 PM EST
FFXI Client Version: 30151223_0
Character Name: archenemy
Race: Hume
Nation: Bastok
Main Job: ranger
Sub Job: Dancer
Area & Coordinates: Balga's Dais (x:298 y:-123 z:345 (68))
Party or Solo: Solo
NPC or Monster Name: N/A
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): No
Steps To Reproduce The Issue: Re-enter the Mission BCNM

Thank you

**Comment by Samikana** [comment]
Player was not online when I was, please message me (Halsey) in-game when you are online.

**Comment by genesis3951** [comment]
I am online now
