### ISSUE TITLE
Supply package KI

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#635]
**Date & Time**: 2/27/2016 10:30am
**Frequency**: Always
**FFXI Client Version**:30151223_0
**Character Name**:Mizrabel
**Race**:Taru
**Nation**:Sandy
**Main Job**:Blm
**Sub Job**:Rdm
**Area & Coordinates**:Aht Urhgan Whitegate X:26 Y:-7  Z:-45 (136)
**Party or Solo**:Both
**NPC or Monster Name**:Naja Salaheem
**ffxiah.com link (for inventory items only)**:N/A 
**Multi-boxing? (multiple clients on same connection)**:Yes
**Steps To Reproduce The Issue**: attempted to re get CS to no avail. Ki was not giving

**Comment by TeoTwawki** [comment]
Gave player missing KI.
