### ISSUE TITLE
Spotted Flyfrond doesn't drop off Boartrap

### ISSUE THREAD

**Issue by neojinx** [LegionDark/Issues#636]
**Date & Time:** February 27th, 1016
**Frequency:** All the time
**FFXI Client Version:**30151215_0
**Character Name:** Neojin and Caffine
**Race:** Hume and Taru
**Nation:** Bastok
**Main Job:** 99 THF and 99 WHM 
**Sub Job: **49 DNC and 49 RDM 
**Area & Coordinates:** Abyssea - Misareaux
**Party or Solo:** Party
**NPC or Monster Name:** Boartrap
**ffxiah.com link (for inventory items only):** N/A
**Multi-boxing? (multiple clients on same connection):** Yes
**Steps To Reproduce The Issue:** Boartrap doesn't seem to drop Spotted Flyfrond **http://www.ffxiah.com/item/3096/spotted-flyfrond** to spawn Tuskertrap NM. Was trying for over an hour with a decent amount of TH.

**Comment by TeoTwawki** [comment]
Dev note: item appears to be in a drop ID, but that drop ID isn't attached to the correct monster.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
