### ISSUE TITLE
Iriri Samariri Charm causing despawn

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#638]
**Date & Time**: 2/28/2016 9:14 am
**Frequency**: charmed
**FFXI Client Version**: 30151223_0
**Character Name**: Baucant
**Race**: Elvaan
**Nation**: Sandy
**Main Job**: Pld
**Sub Job**: DNC
**Area & Coordinates**:Mamook 
**Party or Solo**: Party
**NPC or Monster Name**:Iriri Samariri 
**ffxiah.com link (for inventory items only)**:N/A 
**Multi-boxing? (multiple clients on same connection)**:Yes 
**Steps To Reproduce The Issue**: If entire party is charmed the mob despawns.

**Comment by TeoTwawki** [comment]
All ZNM are fixed in the coming update.
