### ISSUE TITLE
No White Stratum Abyssite after CS at Pashhow Marshland [S]

### ISSUE THREAD

**Issue by Zeldha** [LegionDark/Issues#639]
**Date & Time**:  Feb 28, 2015
**Frequency**: Once
**FFXI Client Version**:30151204_2 
**Character Name**: Vida & Zeldha
**Race**:  MIthra & Taru-mustdie
**Nation**: Sandy
**Main Job**: THF & BLU
**Sub Job**: NIN & RDM
**Area & Coordinates**: 
**Party or Solo**: Both
**NPC or Monster Name**: Veridical Conflux
**ffxiah.com link (for inventory items only)**: ~ 
**Multi-boxing? (multiple clients on same connection)**: Yes
**Steps To Reproduce The Issue**:  Defeated all 3 City T4 VW > Get CS when checking Veridical Conflux on Pashhow Marshland [S], after CS, both char didnt get White Stratum Abyssite KI.

Thanks.

**Comment by TeoTwawki** [comment]
Whats the conflux say after this when clicked?

**Comment by Zeldha** [comment]
@TeoTwawki 
Issue **SOLVED**. After few times searching in LD Issues list, i found the guide here:
https://github.com/LegionDark/Issues/issues/279

1. Pashhow Marshlands (S) and check the Veridical Conflux at for a cutscene
2. Speak with Voidwatch Officers in either Southern San d'Oria 
3. Travel to Ru'Lude Gardens and examine the Door:Audience Chamber for a cutscene
4. Speak with Voidwatch Officers in  Southern San d'Oria.

I cant find these guide in Forum. I will post this steps on VW Jeuno Guide in Forum.
Thanks.
