### ISSUE TITLE
BST EMPY REFORGE

### ISSUE THREAD

**Issue by Thotless** [LegionDark/Issues#641]
**Date & Time**: 
**Frequency**: always
**FFXI Client Version**: 
**Character Name**: Thotless
**Race**: Tarutaru
**Nation**: Bastok
**Main Job**: Beastmaster
**Sub Job**: Dancer
**Area & Coordinates**: anywhere
**Party or Solo**: both
**NPC or Monster Name**: any
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: The set bonus on the Empy Reforge ILVL 109 gear doesn't work.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
