### ISSUE TITLE
Bastok Mission 4 (Magicite) Unable to finish

### ISSUE THREAD

**Issue by Hallabaloo4** [LegionDark/Issues#642]
**Date & Time**: 2/29/2016  4:20AM PST
**Frequency**: Consistant, unable to proceed 
**FFXI Client Version**: 30160203_0
**Character Name**: Halabaloo
**Race**: Hume
**Nation**: Bastok
**Main Job**: Red Mage
**Sub Job**: Black Mage
**Area & Coordinates**: Ru'lude Gardens (H-10)
**Party or Solo**: Solo
**NPC or Monster Name**:  Goggehn
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:  No
**Steps To Reproduce The Issue**: Obtained the Airship pass from the final cutscene of Bastok rank 4 mission "Magicite", run to San'dorian embassy in Ru'lude Gardens, they'll give you a cutscene and give you the Archducal audience permit (despite having already finished the quest as well as not having it in my inventory afterwards and getting the cutscene over and over) then talk to Goggehn to turn in quest to continue but be unable to.

**Comment by TeoTwawki** [comment]
@LegionDark/gm set players MissionStatus to 6 and have them speak with the NPC Nelcabrit

**Comment by TeoTwawki** [comment]
Once CS at Nelcabrit is finished next step is in San d'Oria, clicking same NPC again my result in mission recycling itself because derped code in DSP.

**Comment by Hallabaloo4** [comment]
I apologize if asking this is unnecessary but i am unsure if the second reply is an anwer on what to do. what should i do in order to progress to 5-1 seeing as Goggehn is unable to finish the quest for me and rank up, and the sandoria embassy just repeats the cutscene? I already have an airpass so i just need to do whatever is necessary to hit rank 5 and begin the next quest

**Comment by TeoTwawki** [comment]
dammit, how'd I give you wrong nation.

**Comment by TeoTwawki** [comment]
brb edditing

**Comment by TeoTwawki** [comment]
OK: the 1st post is instructions for the GM to assist you, the 2nd is warning you of a gotcha afterward. Both posts are now edited to reflect the correct NPC name and Nation. You might see messages saying you recieved thinsg you already have - ignore them. But once the scene is over, head Hoem to bastok.

**Comment by Hallabaloo4** [comment]
Thank you for the swift replies. Currently at this time (3:03PM PST) I am still not receiving a cutscene from Goggehn at this step as said per the instructions.
* Return to your embassy's receptionist to complete the mission. You will receive Rank 5, KeyItem "Message to Jeuno", and 10,000 gil. 
but receive the prompt: "We believe in you Halabaloo. Now, seek audience with the Archduke!"
as before, despite having finished the prior cutscene and obtaining the Airship Pass.
I am assuming this is because the process of the pushing or whatever needed to be done hasn't happened yet and i need to await a GM to do so?

**Comment by TeoTwawki** [comment]
Unless a GM contacted you to set that variable in game there has been no change and until then expecting it to work would be silly.

**Comment by Hallabaloo4** [comment]
That's what i thought. Wasn't sure though. Thank you for the confirmation

**Comment by Samikana** [comment]
@Hallabaloo4 you should be able to progress in your mission.  Please let me know otherwise if you come upon any further issue.  My name is Halsey in-game.

I'm leaving this issue open and assigning myself so players know that I can fix it.  

Also @ any players who have this issue, please don't comment on this thread.  Make another bug report just like you would for the 2-3 mission or BLU quest.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
