### ISSUE TITLE
Windurst 2-3 The Three Kingdoms

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#643]
**Date & Time**: 2/28/2016 7:55
**Frequency**: 
**FFXI Client Version**: 30151215_0
**Character Name**: Clone
**Race**: Mithra
**Nation**: Windurst
**Main Job**: Whm
**Sub Job**: RDM
**Area & Coordinates**: -36, -10, -2
**Party or Solo**: solo
**NPC or Monster Name**: 
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: 
Finish the BCNM fight in waughroon shrine, and the cs starts but doesnt progress. no dialogue comes up. Doesnt crash or anything, can teleport outta cs, but doesnt count towards mission.

**Comment by Samikana** [comment]
Ya'll need to start saying what path you're on or I'm closing these without any warning.  That counts as an incomplete report and it's annoying to go through hoops to figure it out.

You've been pushed past the fight.  Speak to your nation's consultant and open another report if you find yourself not being able to progress.
