### ISSUE TITLE
Bastok Mission 5-1 Fei'yin Zone/CS Black Screen

### ISSUE THREAD

**Issue by Hallabaloo4** [LegionDark/Issues#646]
**Date & Time**: 2/29/16 3:56PM PST
**Frequency**: Consistant
**FFXI Client Version**: 30160203_0
**Character Name**: Halabaloo and Facepalmsundae
**Race**: Hume
**Nation**: Bastok
**Main Job**: RDM
**Sub Job**:  BLM
**Area & Coordinates**: Fei'yin (coordinates unknown, havent been able to zone in)
**Party or Solo**: Party and solo
**NPC or Monster Name**: 
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: 1. Be on Bastok Mission 5-1 up to the point where you're told to go to Fei'yin.
2. Zone inside Fei'yin

-Happened twice. Now both Facepalmsundae and I are unable to unstuck, or log in, or move passed this cutscene

**Comment by TeoTwawki** [comment]
Likely NPC ID /client version causing it. When a CS calls for an NPC the server can't find, it does exactly this. The coming update will fix it.

**Comment by Hallabaloo4** [comment]
Any way for us to progress passed this point so we can reach rank 6 and start Dynamis? Or is it just the patience game then?

**Comment by Samikana** [comment]
Pushed htem past CS

**Comment by Samikana** [comment]
Closed because we only need one issue open and we have 3.  Issue will be coming in the big update.
