### ISSUE TITLE
CS Black Screen

### ISSUE THREAD

**Issue by Facepalmsundae** [LegionDark/Issues#647]
**Date & Time**:  2/29/16 3:56PM PST
**Frequency**: Consistant
**FFXI Client Version**: 30160203_0
**Character Name**: Facepalmsundae
**Race**: Mithra
**Nation**: Bastok
**Main Job**: Thief
**Sub Job**: Dancer
**Area & Coordinates**: Fei'yin
**Party or Solo**: Party
**NPC or Monster Name**: 
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: 1. Be on Bastok Mission 5-1 up to the point where you're told to go to Fei'yin.
2. Zone inside Fei'yin

**Comment by TeoTwawki** [comment]
Liekly NPC ID /client version  causing it. When a CS calls for an NPC the server can't find, it does exactly this. The coming update will fix it.

**Comment by Samikana** [comment]
#646 
#682

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
