### ISSUE TITLE
Windurst Mission 6-2 (Saintly Invitation) CS Freeze

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#648]
Date & Time: 02/29/2016 - 16:10 PST (latest attempt)
Frequency: Every time I’ve tried (numerous times over past week, just to be sure it wasn't a fluke)
FFXI Client Version: 30151215_0
Character Name: Kaiju
Race: Tarutaru
Nation: Windurst
Main Job: NIN
Sub Job: DNC
Area & Coordinates: Balga’s Dais (Giddeus)
Party or Solo: Solo
NPC or Monster Name: 
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): No
Steps To Reproduce The Issue: Activate Balga’s Dais (labelled "NPC") for BCNM fight. Cutscene begins and freezes as the camera rotates down to the battlefield. The fight countdown timer begins and continues to tick down to zero. Cannot interact with anything at this point, and must force-quit the game. 

I did not find a reference to the mission in a preliminary search of the DSP issues list. 
Thanks for reading.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
