### ISSUE TITLE
San d'Oria Mission 2-3 BC Fight CS Freeze

### ISSUE THREAD

**Issue by kairoffxi** [LegionDark/Issues#649]
**Date & Time**: 2/29 12:00pm
**Frequency**: 1
**FFXI Client Version**: Current
**Character Name**: Kairo
**Race**: Mithra
**Nation**: San d'Oria
**Main Job**: THF99
**Sub Job**: NIN49
**Area & Coordinates**: Giddeus, Balga Dais
**Party or Solo**: Solo
**NPC or Monster Name**: Black Dragon
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Start Mission 2-3, Complete Bastok portion, Complete Windurst portion, Start final BC fight in Giddeus.

**Comment by Samikana** [comment]
Player wasn't online when I was, please let me know when I can catch you, or contact Tarot in-game as well if you see him!

**Comment by kairoffxi** [comment]
@Samikana thanks for looking into my mission issue. I am in game now as Kairo.
