### ISSUE TITLE
Inventory Problem

### ISSUE THREAD

**Issue by Deeedee** [LegionDark/Issues#65]
**Date & Time**: 6/6/2015
**Frequency**:every loot
**FFXI Client Version**:
**Character Name**:Lafir
**Race**:Hume
**Main Job**:WHM
**Sub Job**:SMN
**Area & Coordinates**:everyzone
**Party or Solo**:solo
**NPC Name**:
**Monster Name**:
**Steps To Reproduce The Issue**: Issue 1 : after Character transfer my mog safe is 50 only.
                                                        Issue 2: after I claim AF for Slip guy I did sort to see the equipment ever since then everyitem I get from monster I need to do 'Sort' to see them.

**Comment by R3P0FFXI** [comment]
Mog Safe shows 80 available slots in your database entry. Please check again and make sure you are /80.

As for the sorting issue we are aware it is a DSP bug and until DSP fixes the sorting bug there is nothing we can do.

**Comment by atom0s** [comment]
Please add you client version to this report.  This could be due to your client being outdated.

**Comment by Deeedee** [comment]
ok. it's shows 80 now

**Comment by R3P0FFXI** [comment]
K Closing issue
