### ISSUE TITLE
BLU Job trail Fast cast (Erratic Flutter)

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#650]
**Date & Time**: 2/29/2016 9:03pm
**Frequency**: always
**FFXI Client Version**:30151223_0 
**Character Name**: Baucant
**Race**: Elvaan
**Nation**: Sandy
**Main Job**: Blu
**Sub Job**: War
**Area & Coordinates**:North San  d'Oria (MH) X:0 Y:0 Z:0 (192)
**Party or Solo**: Both
**NPC or Monster Name**: N/A
**ffxiah.com link (for inventory items only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: yes and no
**Steps To Reproduce The Issue**: Set spell erratic flutter is suppose to give 8points towards Fast Cast Job trait. Does not give Job trait. attempted to pair with other still not recieving Job triat fast cast

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
