### ISSUE TITLE
Bastok Mission 2-3

### ISSUE THREAD

**Issue by Breogan7** [LegionDark/Issues#652]
**Date & Time**: 3/1/2016
**Frequency**: 1
**FFXI Client Version**: 30160203_3
**Character Name**: Breogan
**Race**: Hume
**Nation**: Bastok
**Main Job**: Warrior
**Sub Job**: Samurai
**Area & Coordinates**: Bastok Mines (H-10)
**Party or Solo**: Solo
**NPC or Monster Name**: Black Dragon
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: Starting Bastok Mission 2-3, was informed I need to submit a ticket to be pushed past it.

**Comment by Samikana** [comment]
I fixed it
