### ISSUE TITLE
Hyacinth Stratum Abyssite not up to Hyacinth Stratum Abyssite II.

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#653]
**Date & Time:** 23:00pm --01/03/16
**Frequency:** Always
**FFXI Client Version:** 30151233_0
**Character Name:** Aurel -Cassy
**Race:** Hume
**Main Job:** blm
**Sub Job:** Sam
**Area & Coordinates:** Tavnazian Safehold X:-16 Y:-25 Z:125 (201)
**Party or Solo:** Party or solo 
**NPC Name:** Owain
**Monster Name:**
**ffxiah.com link (for inventory items only):**
**Multi-boxing? (multiple clients on same connection):** yes
**Steps To Reproduce The Issue:**
-- Aurel ,Cassy  Defeat the 4 monsters:
Fjalar in Attohwa Chasm
Abununnu in Lufaise Meadows
Tsui-Goab in Misareaux Coast
Isarukitsck in Uleguerand Range
Return to Owain to finish this quest and not work CS no up KI Hyacinth Stratum Abyssite II.

![caura](https://cloud.githubusercontent.com/assets/13084662/13435861/cabc5770-dfb2-11e5-9cca-ce032a487405.PNG)
![tura](https://cloud.githubusercontent.com/assets/13084662/13435887/ec7d7fc4-dfb2-11e5-8b7b-0a667b011619.PNG)

**Comment by TeoTwawki** [comment]
> **Area** & Coordinates: X:-16 Y:-25 Z:125 (201)

You put coordinates but no area. Took me several min to figure out this was the Tavnazia VW line. I've edited your post so when I come back to this I'll know. Its going to be awhile, many other things have my attention and priority.

**Comment by qiganggang** [comment]
we lost KI bug not refix

**Comment by nekrol** [comment]
talk Owain up ki again Hyacinth I

**Comment by TeoTwawki** [comment]
> we lost KI bug not refix

@qiganggang I dunno what you were trying to say, or why, since I haven't done anything about this yet

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
