### ISSUE TITLE
Ashen Stratum Abyssite II not up Ashen Stratum Abyssite III.again VW is broken or me

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#654]
Date & Time: 23:00pm --01/03/16
Frequency: Always
FFXI Client Version: 30151233_0
Character Name: Aurel -Cassy
Race: Hume
Main Job: blm
Sub Job: Sam
Area & Coordinates: Norg
Party or Solo: Party or solo 
NPC Name:Kieran
Monster Name:
ffxiah.com link (for inventory items only):1
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:
--Aurel Defeat all of the Tier II Zilart NMs.
Cath Palug in The Sanctuary of Zi'Tah. Rifts are located at (E-9), (F-8), and (G-10).
Modron in The Boyahda Tree. Rifts are located on Map 1 (G-5), (K-8), and on Map 2 at (F-7).
Mimic King in Ro'Maeve. Rifts are located at (E-7), (I-9), and (K-7).
Return to Norg and speak to Kieran (H-8) NOT receive your KeyItemAshen Stratum Abyssite III.
![ca](https://cloud.githubusercontent.com/assets/13084662/13436346/21fa0e22-dfb5-11e5-96a1-0f876e95b3bc.PNG)
![ra](https://cloud.githubusercontent.com/assets/13084662/13436378/4fbc5428-dfb5-11e5-9e14-d70557c68351.PNG)

**Comment by TeoTwawki** [comment]
Check again when you get a chance and then tell me results.

**Comment by nekrol** [comment]
thank you
![captura](https://cloud.githubusercontent.com/assets/13084662/13448971/7bac2caa-dffd-11e5-8e30-ae4f27f0f9f2.PNG)
