### ISSUE TITLE
password assist

### ISSUE THREAD

**Issue by karnas0891** [LegionDark/Issues#655]
**Date & Time**: 3/1
**Frequency**: 
**FFXI Client Version**: 
**Character Name** Karnas: 
**Race**: Hume
**Nation**: Bastok
**Main Job**: THF
**Sub Job**: war
**Area & Coordinates**: 
**Party or Solo**: Solo
**NPC or Monster Name**: 
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: 

I need to have my password changed for my main account. I can not log into it. My wife Yenny is online most of the time if anyone can assist me.

**Comment by karnas0891** [comment]
I need to have my password changed for my main account.  I can not log into it.  My wife Yenny is online most of the time if anyone can assist me.

**Comment by R3P0FFXI** [comment]
@karnas0891 See me on IRC to get this resolved

**Comment by karnas0891** [comment]
Ok l get home around 8:30 pst is that ok ?

**Comment by R3P0FFXI** [comment]
@karnas0891 done as per the password you gave on IRC
