### ISSUE TITLE
Witful belt

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#656]
**Date & Time**: 3/2/2016 12:45pm
**Frequency**: Currently
**FFXI Client Version**: 30151223_0
**Character Name**: Merlin, Mizrabel, Belltrix
**Race**: Taru
**Nation**: Sandy
**Main Job**: Blm
**Sub Job**: Rdm
**Area & Coordinates**: All AH locations 
**Party or Solo**: either
**NPC or Monster Name**: N/A 
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/10826/witful-belt
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: With the AH stripped of all items this is now unobtainable.

per -request https://www.bg-wiki.com/bg/Witful_Belt

**Comment by R3P0FFXI** [comment]
@Baucant Thanks man keep em coming ill find a place for this

**Comment by R3P0FFXI** [comment]
Added drop to Mob

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
