### ISSUE TITLE
Sandy 2-3 Windurst Fight

### ISSUE THREAD

**Issue by ibanez802** [LegionDark/Issues#657]
**Date & Time**: 3/2/16

**FFXI Client Version (use `/ver`)**: 30151103_3

**Character Name**: Arielle

**Nation**: Sandy

**Job(level)/Sub Job(level)**:  74 Bluemage / 37 Redmage

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**:  Balga Dais

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce The Issue**:  2-3 Dragon Fight, CS freezes up. Would like some help :)

**Comment by Samikana** [comment]
Hey there, you weren't online when I got on. If you could please either log on now or tell me a time that either @PikaFox or I can catch you online, that'd be great.

Thanks, 
Halsey

**Comment by Samikana** [comment]
No response in 3 days, closing.
