### ISSUE TITLE
Melee Hose

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#659]
Date & Time: 23:00pm --04/03/16
Frequency: Always
FFXI Client Version: 30151233_0
Character Name: Aurel -
Race: Hume
Main Job: blm
Sub Job: Sam
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name: 
Monster Name:
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/15118/melee-hose
Multi-boxing? (multiple clients on same connection): solo
Steps To Reproduce The Issue:hello I have the same problem  issue #360 .-i have space in me inventary ,I check everything and not have Melee Hose
![captura](https://cloud.githubusercontent.com/assets/13084662/13527482/91ea1b1e-e1e5-11e5-8bc6-880bd6b38078.PNG)
![tura](https://cloud.githubusercontent.com/assets/13084662/13527499/b5c3427c-e1e5-11e5-946f-c3a157cc564f.PNG)

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
