### ISSUE TITLE
Wingcutter +1  (Voidwatch drop not Equipable nin/thf)

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#660]
**Date & Time**: 3/4/16

**FFXI Client Version (use `/ver`)**: 30151103_3

**Character Name**: Daedrik

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BLU99/RDM49

**NPC or Monster or item Name**:  Wingcutter+1 ( Item Id: 21350 )

**Zone name & Coordinates (use `@where`)**:  Uleguerand Range:   Isarukitsck    G-10

**ffxiah.com link (for items issues only)**:  http://www.ffxiah.com/item/21350/wingcutter-1

**Multi-boxing? (multiple clients on same connection)**:  Yes

**Steps To Reproduce The Issue**:  Item is equip-able by only NIN/THF, however it does not seem to want to do so when tried by either job.

**Comment by Samikana** [comment]
#567
