### ISSUE TITLE
San D'orian 2-3 Mission help

### ISSUE THREAD

**Issue by geahlen** [LegionDark/Issues#661]
**Date & Time**:  3/5/2016  12:50pm MST

**FFXI Client Version (use `/ver`)**:  30160203_0

**Character Name**:  Giselda

**Nation**:  San D'oria

**Job(level)/Sub Job(level)**:  BLM75/RDM37

**NPC or Monster or item Name**:  Burning Circle NPC

**Zone name & Coordinates (use `@where`)**:  X:299  Y:-124  Z:342 (63)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  no

**Steps To Reproduce The Issue**:  attempt to enter burning circle in Balga's Dais for mission fight.

**Comment by Samikana** [comment]
Hey there, you weren't online when I got on. If you could please either log on now or tell me a time that either @PikaFox or I can catch you online, that'd be great.

Thanks, 
Halsey

**Comment by geahlen** [comment]
I can logon later tonight.  Between 7-9pm MST.

**Comment by Samikana** [comment]
I logged on and you weren't on.  It's unrealistic for me to get on in your time frame because I have to sleep for school, so try leaving your character on over night if you can't be on earlier and I'll catch you tomorrow.

Also I need to know which path you took.

**Comment by geahlen** [comment]
i'm logged in now.  bastok - windy

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
