### ISSUE TITLE
Isgebind Heart drop rate

### ISSUE THREAD

**Issue by w3genesis** [LegionDark/Issues#662]
**Date & Time**: 03/06/2016

**FFXI Client Version (use `/ver`)**: Newest

**Character Name**: Gouken

**Nation**: Bastok

**Job(level)/Sub Job(level)**: Sam99/War49

**NPC or Monster or item Name**: Isgebind

**Zone name & Coordinates (use `@where`)**: Abyssea-Uleguerand

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce The Issue**: 

Am planning to build Masamune, but when checking the monster tool in database, noticed that Isgebind's Heart drop rate seems significantly lower than other boss trial items. Most boss trial item have 3 drop slots 100% 20% 10%, but Isgebind's Heart only has 2 drop slots of 20% and 10%, with the 100% drop slot missing.

Am reporting this since I might need to kill Isgebind more than 50 times to get 50 hearts, which will be hugely painful. Not sure if this drop rate is intended or not ^^;

**Comment by itachioax** [comment]
we all kill it like 30 times just to reforge one piece man D=

**Comment by Samikana** [comment]
@R3P0FFXI is this a result of your RNG?

**Comment by R3P0FFXI** [comment]
This issue is a known issue and is confirmed resolved in the Massive Update on the 15th @Samikana  and @w3genesis

**Comment by w3genesis** [comment]
Woot, can't thank you enough for fixing this! ^^

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update

**Comment by nekrol** [comment]
now after update drop is good very good so isgebind now use all time 
Absolute Terror  , magic evasion on AF not work ,good luck
