### ISSUE TITLE
Blue Mage Job Quest

### ISSUE THREAD

**Issue by RandomStuffed** [LegionDark/Issues#663]
Date & Time:3/5/2016 2342
Frequency: everytime
FFXI Client Version: 30160203_0
Character Name: Random
Race: Mithra
Nation: Windurst
Main Job: Red Mage
Sub Job: Black Mage
Area & Coordinates: Aydeewa Subterrane x514 y-32 z459
Party or Solo: solo
NPC or Monster Name: None
ffxiah.com link (for inventory items only): none
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue: Happens everytime

**Comment by Samikana** [comment]
Hey there, you weren't online when I got on.  If you could please either log on now or tell me a time that either @PikaFox or I can catch you online, that'd be great. 

Thanks, 
Halsey

**Comment by RandomStuffed** [comment]
Issue was resolved.
