### ISSUE TITLE
Sandy 2-3 bastok -> windy

### ISSUE THREAD

**Issue by heldia** [LegionDark/Issues#664]
**Date & Time**: 3/6/16 10:33 pm EST

**FFXI Client Version (use `/ver`)**: 30151103_3

**Character Name**: Heldia

**Nation**: Sandy

**Job(level)/Sub Job(level)**: 99blu/49rdm

**NPC or Monster or item Name**: burning circle

**Zone name & Coordinates (use `@where`)**: x298 y-124 z343

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce The Issue**: zoned in and out multiple times doesn't work

**Comment by Samikana** [comment]
Hey there, you weren't online when I got on.  If you can get online now or tell me or @PikaFox a time we can catch you online, that'd be great.  

Thanks, 
Halsey

**Comment by heldia** [comment]
I'm online now and should be until 11 or so pm est.  I am normal on between 7-11 weekdays.
