### ISSUE TITLE
Dynamis-Beaucedine Entry Not showing/no CS

### ISSUE THREAD

**Issue by Hallabaloo4** [LegionDark/Issues#665]
**Date & Time**: 3/7/16 12:07 AM PST

**FFXI Client Version (use `/ver`)**:  30160203_0

**Character Name**: Halabaloo

**Nation**: Bastok

**Job(level)/Sub Job(level)**: SAM(99)/DNC(49)

**NPC or Monster or item Name**: Trail Markings

**Zone name & Coordinates (use `@where`)**: Beaucedine Glacier x: -279, y: -39, z: -417

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce The Issue**: Have all 4 required KI's as well as watch all 4 required cutscenes from Dynamis-Jeuno, Bastok, Sandoria and Windurst. Run to the Trail Markings in Beaucedine Glacier. Click on the markings and receive no prompt and no CS, just a short text saying "Thirty Years ago i came in contact.. blah blah"

-I'm unsure as whether the glitch is that we aren't receiving the cutscene/prompt or if the problem is that it shares the 24 vanadiel day re-entry timer with the other 4 previous dynamis, but the text telling us that just isn't showing up so we aren't able to know.

**Comment by TeoTwawki** [comment]
yes the timer is shared, and you get the wrong message because your client version is ahead of the server so the text ID for it doesn't match. Soon as we get updated that'll stop happening.
