### ISSUE TITLE
Crafting Advancement after character transfer

### ISSUE THREAD

**Issue by kupoknights** [LegionDark/Issues#666]
**Date & Time**: 3/7/2016   11:29am pst

**FFXI Client Version (use `/ver`)**: 30151223_0

**Character Name**: Kyomizu

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 75blu/37dnc

I had my character transfer over about 2month ago and was not able to get my crafting advance and was wondering if it is possible to do so?

![kyomizu](https://cloud.githubusercontent.com/assets/17695658/13580697/34174780-e458-11e5-8eee-1076732547a1.jpg)

**Comment by Samikana** [comment]
Hey there, you weren't online when I got on. If you could please either log on now or tell me a time that either @PikaFox or I can catch you online, that'd be great.

Thanks, 
Halsey

**Comment by Samikana** [comment]
Player logged in.  :)  All of his credits have been boosted.
