### ISSUE TITLE
Auction House sales

### ISSUE THREAD

**Issue by Xtian75** [LegionDark/Issues#667]
**Date & Time**: 03/07/2016

**FFXI Client Version (use `/ver`)**:  30160203_0

**Character Name**: Xtian

**Nation**: Windhurst

**Job(level)/Sub Job(level)**: BLM 99 / RDM 49

**NPC or Monster or item Name**: n/a

**Zone name & Coordinates (use `@where`)**: Auction House

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce The Issue**: I see items I put on the AH have sold via the website, but when I login to the game to check the delivery box, I see no money has been sent from the AH sales.

**Comment by TeoTwawki** [comment]
Need the item IDs in order to check on this. For each item. We can get the item IDs from the items ffxiah.com url.

**Comment by Xtian75** [comment]
Enhancing Sword  ID - 16605
Earth Crystals ID - 4099
Wind Crystals ID - 4098

Unfortunately, the website only list the last 10 transactions and these were the only ones I saw that sold on my history. Item ID I pulled from legion website since it listed them. Please let me know if those are not correct on the Legion site. I couldn't find the item ID listed on ffxiah :(

**Comment by TeoTwawki** [comment]
Item IDs were fine, it let me look up the history of your AH transactions and delivery box queue. I was able to see the sales record of the items and the gil sent to the delivery box. I checked against the previous database backups as well (which is what took so long) and records indicates the money from that transaction already passed out of the delivery system and into inventory (delivery box data says it was already clicked/removed). 100k enhancing sword and you've had another hundred other items sales.

I see you have multiple alts, did you possibly forget after handing money to an alt?

**Comment by Xtian75** [comment]
So I checked my sales to see if any items sold today and the website shows I sold 5 stacks of Earth Crystals and 2 stacks of ice crystal today (03/08/16). I just login (3:33PM PST) to my game and check the delivery box and the money is not listed from the AH sales of the crystals in the delivery box :(

Has anyone else reported having issue from their AH sales?

**Comment by TeoTwawki** [comment]
Not recently no. There was a bug in the past where the delivery system would freeze up and we know how to check for that bug, so if somethings wrong this is new. Checking you data again for your new sales..

**Comment by TeoTwawki** [comment]
Ok this is really strange. I'm seeing no new changes to your delivery box data at all. This may take some time to investigate, and nobody else has yet reported an issue.

**Comment by TeoTwawki** [comment]
Weeeeell the good news is I found the error. The bad news is I still do not know how it happened and its [going to take awhile to fix](http://legiondark.com/forums/viewtopic.php?f=21&t=1347).

**Comment by Xtian75** [comment]
That's awesome that you found the error! No worries, i'm sure these things take time to fix. Is this issue affecting the entire AH or is it just isolated to my character?

**Comment by TeoTwawki** [comment]
Turns out effected the entire delivery box table - all characters. Are you able to meet me in game tonight?

**Comment by Xtian75** [comment]
Yup. I'm currently on now, will be on for about an hour before I have to go to bed for work.
