### ISSUE TITLE
Sandoria Mission 2-3

### ISSUE THREAD

**Issue by benfolka** [LegionDark/Issues#668]
**Date & Time**:  04:31 (GMT +2)

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Clay

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 99/49 war/dnc

**NPC or Monster or item Name**: black dragon & searcher

**Zone name & Coordinates (use `@where`)**:  Balga's Dais Battlefield entry

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  no

**Steps To Reproduce The Issue**:  Zoned in cs does not happen

**Comment by benfolka** [comment]
please push

**Comment by Samikana** [comment]
Done.  Also, never demand something from the GMs.  If this was @TeoTwawki he would have added a 0 fucks given tag and closed your issue.
