### ISSUE TITLE
Celestial Nexus

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#669]
Date & Time: 3/7/2016
Frequency: 
FFXI Client Version: 30151215_0
Character Name: Ritonami
Race: Mithra
Nation: Windurst
Main Job: thf
Sub Job: nin
Area & Coordinates: -36, -10, -2
Party or Solo: solo
NPC or Monster Name: 
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): no/yes
Steps To Reproduce The Issue:  Got up to the bcnm for ZM16 Celestial Nexus, cleared first phase timed out on second phase. only one client on connection at time. got mule up to same mission, went to go duo it, Ritonami couldnt activate fight, could participate, checked mission log sealed shrine is current mission and as a completed mission. Tried to get cs for sealed shrine again didn't work. Cleared the fight, mule got cs in norg main didn't

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
