### ISSUE TITLE
On Sabbatical (Klimaform)

### ISSUE THREAD

**Issue by Kaoriasada** [LegionDark/Issues#67]
Date/Time:  June 7th, 2015 02:32:00
Frequency:  Every time
FFXi Client Vers.:  version 30150508_8
Character Name: Sami
Race: Mithra
Main Job: SCH65
Sub Job: RDM30
Area & Coordinates: The Eldieme Necropolis [S], X:378 Y:-40 Z:18 (117)
Party/Solo: Tried with both party and solo, same result.
NPC Name: Erlene
Monster Name: N/A
Steps to Reproduce issue: Talk to her as SCH 40+.  Over and over and over again.  Same result.

**Comment by Kaoriasada** [comment]
Can't start the quest "On Sabbatical" for SCH (Considered AF1), which rewards Klimaform, a R/EX scroll that can't be otherwised obtained and is pretty essential for someone playing main SCH.

**Comment by TeoTwawki** [comment]
You can't start it because neither the quest nor the spell itself exist at all in DarkStar yet.

**Comment by TeoTwawki** [comment]
I will leave this open, and when compiling my grand list of stuff jobs need, will add this to that and then close this at that time.
