### ISSUE TITLE
2-3 Bastok (windy to sandy)

### ISSUE THREAD

**Issue by sirus628** [LegionDark/Issues#670]
**Date & Time**:  8 mar 2016

**FFXI Client Version (use `/ver`)**: Ashita, 30160203_0

**Character Name**: Nugwa

**Nation**: Bastok

**Job(level)/Sub Job(level)**: drk99/rdm49

**NPC or Monster or item Name**: any 2-3 bastok

**Zone name & Coordinates (use `@where`)**: multiple

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes. w/ sirus

**Steps To Reproduce The Issue**: 
OK so my KI was updated then it sent my mission to part 1 (talk to peeps in star tower blah)
None of the NPCs associated will update/complete/progress the mission.
It is effectively frozen from regular play.

Not sure what would be easiest for you. I dont mind doing it again if you have to reset my rank to 1.

**Comment by Samikana** [comment]
Player variable updated
