### ISSUE TITLE
"Glitch" on mission bastok 7-2

### ISSUE THREAD

**Issue by warlord1352** [LegionDark/Issues#672]
**Date & Time**: 3/8/16; 1:20p.m. pst

**FFXI Client Version (use `/ver`)**: 3015110_3

**Character Name**: Erinyes

**Nation**:  Bastok

**Job(level)/Sub Job(level)**: 99 thf/49dnc

**NPC or Monster or item Name**: Karst

**Zone name & Coordinates (use `@where`)**: X:104 Y:-20 Z:0 (255)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  Yes; Oscar, and cureslave as well

**Steps To Reproduce The Issue**: Tried to relog, wait for another game day. Still not working. I already talked to Gumbah and fought the BCNM and just needed to talk to Karst but now nothing is happening.

**Comment by warlord1352** [comment]
Not trying to complain or anything but just curious because I see other posts that have been "attended to" and mine is older but still has had anything done to it. Not telling you guys to fix this right now but I just want the piece of mind that you know about it. Sorry like I said not trying to complain.

**Comment by TeoTwawki** [comment]
scheduling and hands full and randomness.  ¯\_(ツ)_/¯  

Except for the most generic issues GMs can quick fix LegionDark is trying to just get the server updated first and see which issues are still happening after that.

**Comment by warlord1352** [comment]
Ah ok. Thank you for the quick reply. Take your time. Like I said I just wanted to make sure you guys at least saw this (which I was pretty sure you did). Again thanks for all the hard work and effort guys, really do appreciate all this! Keep it up!

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update

**Comment by TeoTwawki** [comment]
>> ~~Reopen if still an issue after update~~ reply here after the update and Teo will reopen if its still broke 

_cough_ :smiley:
