### ISSUE TITLE
AH missing Gil

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#674]
**Date & Time**: 3/8/2016 10:47pm

**FFXI Client Version (use `/ver`)**:30151223_0 

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:Thf99/Dnc49 

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**:MH X:0 Y:0 Z:0 

**ffxiah.com link (for items issues only)**: See below

**Multi-boxing? (multiple clients on same connection)**: No 

**Steps To Reproduce The Issue**: tried to collect gil for DB for items sold on AH list of items and amont of gil missing below.

Toolbag (shihei) [Stack] - 5314 - 3mil
Shihei [Stack] - 1179 - 830k (possible more)
Fire Crystals [Stack] -4096 - 20k
Fire Cluster [Stack] - 4104 - 100k
Ice cluster [Stack] - 4105 -  300k
Wild onion - 4387 - 4k
Spool of silk Thread [Stack] - 816 - 70k
Karakul skin [Stack} - 878 - 40k
Lizard Skin - 852 - 4k
Sheet of Parchment [Stack] - 917 - 50k
Scroll of auspice - 30k
Scroll of reraise - 50k

As of 10:44pm 3/8/2016 
Total 4,498,000

**Comment by Baucant** [comment]
#667 simalar issue

**Comment by Samikana** [comment]
None of this is in the SQL dump.  I've given you back what is logged.

**Comment by TeoTwawki** [comment]
@Samikana escalate for AH sales not in the dump. And I stuck r3 with this one for a reason. Did he PM you to handle it? I have a feeling he did.

@R3P0FFXI you sneaky f\*er

**Comment by TeoTwawki** [comment]
Found sales record and time-stamp correlates with the period this mess happened. Wish I had an easy way to make these particular records available to regular GMs like I did the delivery box but I don't (yet).

**Comment by Baucant** [comment]
Thanks Teo for finding it for me
