### ISSUE TITLE
Delivery box missing bunch of items

### ISSUE THREAD

**Issue by password100** [LegionDark/Issues#675]
**Date & Time**: 
3/8/16 after emergency maint. possibly before but I just logged in to check after reading website.
**FFXI Client Version (use `/ver`)**: 
30160203_0
**Character Name**: 
Krakenclub
**Nation**: 
Sandoria
**Job(level)/Sub Job(level)**: 
BLM10 no SJ
**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 
Mog House Sandy X:0 Y:0 Z:-7
**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/17440/kraken-club
**Multi-boxing? (multiple clients on same connection)**: 
no
**Steps To Reproduce The Issue**: 
missing a bunch of items but i don't remember and only really concerned about the kraken clubs i sent to myself so i could hold more. Some were pending and some were already in DB.

**Comment by TeoTwawki** [comment]
pls be a joke pls be a joke pls be a joke pls be a joke pls be a joke pls be a joke :cry:

**Comment by TeoTwawki** [comment]
Omg its real. how and why did you have so many. :scream:

**Comment by TeoTwawki** [comment]
Restored players **eight** kraken clubs, 2 vulcan's pearls, and 2 Tati earning +1 ...

**Comment by password100** [comment]
Lol sometimes he pops after 1-2 kills, sometimes its 10 hours. But it's not that annoying when your doing homework/studying and just checking every 20 minutes. Thanks for responding so fast.
