### ISSUE TITLE
Delivery Box missing items

### ISSUE THREAD

**Issue by Hallabaloo4** [LegionDark/Issues#676]
**Date & Time**:  9:06PM PST

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Halabaloo

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 81SCH/40RDM

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce The Issue**: Server Crash with delivery box issues.

Here's the thing, i had been using it as a sort of storage for maybe 15-20 items and do not remember what they were and their worth. For all i knew it could be some valuable stuff or a bunch of junk not including what may have been sent to me or any money made from the AH. IF you have records and any way to look and wouldn't mind i'd really, really appreciate it and will be very patient. If there is no way to do this or this is an absurd amount of work i'll just have to take the loss but if its at all possible i'd love to check because i most certainly lost everything.

**Comment by TeoTwawki** [comment]
>  i had been using it as a sort of storage

Don't do that. Seriously.

**Comment by TeoTwawki** [comment]
Restored crafter's treasure hoard :eyes:
