### ISSUE TITLE
Craft Marid Leather = Fail

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#678]
**Date & Time**: 3/9/2016 8:38pm

**FFXI Client Version (use `/ver`)**:30151223_0 

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:THF99/DNC49 

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**:All areas all coordinates 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/2152/marid-leather

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce The Issue**: Tried to craft, double checked recipe does not work.

**Comment by R3P0FFXI** [comment]
@Baucant  Item is not in list I will get to this later

**Comment by R3P0FFXI** [comment]
@Baucant Fixed in DSP when we update the recipe will get pulled
