### ISSUE TITLE
Sandoria Rank 5-1 fei'yin cs broken cant obtain when entering

### ISSUE THREAD

**Issue by Fayth0987** [LegionDark/Issues#679]
**Date & Time**: 3-9-2016
**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Fayth

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: Pld99/Dnc49

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: Entry to Fei'yin

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce The Issue**: I am trying to get Mission 5-1 cs so i can do the fight but when i zone in to Fei'yin the screen goes black like its going to load but then it just stays black and i can do nothing except @tele out or go to website to unstuck i have done this 3-4 times now from different arrival points and nothing changes and i cant move on.

**Comment by Fayth0987** [comment]
I did not read previous posting like i probably should have i would love to be pushed past but i can wait for update if i have too :)

**Comment by Fayth0987** [comment]
understand thank you

**Comment by Samikana** [comment]
#647
#646
#682

**Comment by Fayth0987** [comment]
thank you
