### ISSUE TITLE
CoP 1-2 Below the Arks [not resolved for Bibi]

### ISSUE THREAD

**Issue by Squall-Bibi** [LegionDark/Issues#68]
Date & Time: 07/06/15
Frequency: Every time
FFXI Client Version: 30150508_8
Character Name: Bibi
Race: Taru
Main Job: RDM
Sub Job: WHM
Area & Coordinates: Spire of Holla / Dem / Mea
Party or Solo: Solo and Party
NPC Name: n/a
Monster Name: n/a

Steps To Reproduce The Issue: As Baucant and Kinori also have the same issue.

Followed the walkthrough, spoke with Pherimociel and recieved CS, I spoke with Harith and mentions the emptyness. I do have mysterious amulet as temp key item.
I did not recieve CS when entering Shatered telepoint but have a CS afer used the Large Apparatus and always this cs after re enter. 
I climbed the promy for both Holla and Dem and Mea with the same result reaching the top and getting the message: "You can hear a faint scraping sound from within, but the way is barred by some strange membrane..."

You can zone back into Promy and fight things if needed.

**Comment by TeoTwawki** [comment]
I fixed'em.
