### ISSUE TITLE
5-1 bastok Mission CS entry to Fei'Yin failed to start.

### ISSUE THREAD

**Issue by djmanofsteel** [LegionDark/Issues#682]
**Date & Time**: 3/9/2016 10pm

**FFXI Client Version (use `/ver`)**: ver. 30160203_0

**Character Name**: Rollout and Kara

**Nation**: Bastok

**Job(level)/Sub Job(level)**: Cor99/Nin49      Rdm99/Whm49

**NPC or Monster or item Name**: NA

**Zone name & Coordinates (use `@where`)**: Fei'Yin entry

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce The Issue**: Atempt to entry Fei'Yin Yielded Black screen and 
Pol crash(on Rollout)
entry to Fei'Yin Yielded black screen and no crash but CS failed to start.(on Kara)
Atempted to login on only 1 char. and see if it was a duel boxing issues got same results.

Thank you 
Mano

**Comment by Samikana** [comment]
#646 

Catch me online and I'll push you past the mission.

**Comment by Samikana** [comment]
Closed because we only need one issue open and we have 3.  You know to contact me in-game.
