### ISSUE TITLE
NPC Victoire (standard merchant) no reasonse

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#683]
**Date & Time**: 3/10/2016 8:24 

**FFXI Client Version (use `/ver`)**: 30151223_0 

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**: Thf99/Dnc49

**NPC or Monster or item Name**: Victorie http://ffxiclopedia.wikia.com/wiki/Victoire

**Zone name & Coordinates (use `@where`)**: Southern San d`Oria X:70 Y:0 Z:38 (87)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**:N/A 

**Steps To Reproduce The Issue**: Talked to NPC numerous times

**Comment by TeoTwawki** [comment]
If you find more vendors not working, enough to make a list, we'll get them all into dsp as soon as we have time to make it happen or pass that list along if we do not (like we did with BCNM).

**Comment by TeoTwawki** [comment]
If this one turns out to be the only one, he won't take long to fix.

**Comment by Baucant** [comment]
she just happened to be one I needed something from but if I come across more I'll start a list.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
