### ISSUE TITLE
My mission broke.

### ISSUE THREAD

**Issue by Samikana** [LegionDark/Issues#685]
If you're on a mission that's not 2-3, **_please do NOT send GMs tells for help_**.  These missions will not be addressed until the server is updated due to a majority of them being a result of version mismatches.

After the update, any mission that can still not be progressed on will be addressed accordingly.

Thank you,
**Halsey.**

**Comment by benfolka** [comment]
altough i am replying someone else's ticket
thanks alot did not realize that

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
