### ISSUE TITLE
Anchorite's cyclas (mnk AF reforge body)

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#686]
**Date & Time**: 10/03/2016

**FFXI Client Version (use `/ver`)**: 30151215_0

**Character Name**:  Itachioax

**Nation**:  Sandy

**Job(level)/Sub Job(level)**: MNK99/WAR49

**NPC or Monster or item Name**:  noone

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/27808/anchorites-cyclas

**Multi-boxing? (multiple clients on same connection)**:  dual

**Steps To Reproduce The Issue**:  chakra effect is not working, and plz check for piece +1 anchorites cyclas +1 http://www.ffxiah.com/item/27829/anch-cyclas-1

**Comment by Samikana** [comment]
Chakra mod does not exist in DSP.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
