### ISSUE TITLE
Hesychats's gloves (relic mnk reforge hands)

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#687]
**Date & Time**: 10/03/2016

**FFXI Client Version (use `/ver`)**: 30151215_0

**Character Name**:  Itachioax

**Nation**:  Sandy

**Job(level)/Sub Job(level)**: MNK99/WAR49

**NPC or Monster or item Name**:  noone

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/26978/hes-gloves

**Multi-boxing? (multiple clients on same connection)**:  dual

**Steps To Reproduce The Issue**:  chakra effect is not working same as the body i report before, and plz check for piece +1 http://www.ffxiah.com/item/26979/hes-gloves-1
 i dont have piece +1 or should i make them and then in case of.. report it? just asking

**Comment by Samikana** [comment]
Chakra mod does not exist.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
