### ISSUE TITLE
Lost Item after monster is defeated

### ISSUE THREAD

**Issue by Minikay** [LegionDark/Issues#688]
**Date & Time**: 3/10/16 11:40pm pst

**FFXI Client Version (use `/ver`)**: 30151215_0

**Character Name**: Minikay

**Nation**: Sandy

**Job(level)/Sub Job(level)**: 99thf/49war

**NPC or Monster or item Name**: Iztaasu +1

**Zone name & Coordinates (use `@where`)**: 30, -9, -33

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/20736/iztaasu-1

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce The Issue**: Only happened once. Were were trying to get i113 sword for me from amhuluk and when it did drop, for some reason it got lost right away. Same goes for Kanagi. Our inventory wasn't full. Here is the screenshot.
![lootdropped](https://cloud.githubusercontent.com/assets/17779024/13697307/788ce21e-e721-11e5-86c6-2dd8c4502d87.png)

**Comment by Samikana** [comment]
@LegionDark/gm Isn't this in the big update?

**Comment by Samikana** [comment]
You likely already had something in your treasure pool when it happened and when Amhuluk dropped those items, it pushed them out automatically.

![halsey_2016 03 11_170732](https://cloud.githubusercontent.com/assets/12781975/13716882/d3025384-e7ab-11e5-94c8-63b837789127.png)

**Comment by Minikay** [comment]
Yes, he already had the item but it wasn't for him, my inventory wasn't full though. We didn't have anything in the treasure pool either. After the NM was defeated, there wasn't a chance to lot. The item went straight to the ground. This is the first time this has happened to me.

**Comment by TeoTwawki** [comment]
In retail when an item "falls" it will go to a randomly selected person out of those who don't already have one. In darkstar though, it will go to a randomly selected _anybody present_ and if they already have one, it'll be lost. So don't let anything important fall - have everyone lot/pass, and make sure the treasure pool is emptied before tackling another mob.

**Comment by TeoTwawki** [comment]
Additionally, if an item is borked in the database (missing info) it will auto fall. We'll check for that.

**Comment by TeoTwawki** [comment]
Also to many items in a single loot pool, but that screenshot doesn't show that.

**Comment by TeoTwawki** [comment]
Most likely scenario : invis items / the sort bug.
