### ISSUE TITLE
Telchine Gloves currently cannot be equipped

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#689]
Date & Time: 23:00pm --11/03/16
Frequency: Always
FFXI Client Version: 30151233_0
Character Name: Aurel -
Race: Hume
Main Job: blm
Sub Job: Sam
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name: 
Monster Name:
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/27048/telchine-gloves
Multi-boxing? (multiple clients on same connection): solo
Steps To Reproduce The Issue:Telchine Gloves currently cannot be equipped

**Comment by Samikana** [comment]
Incorrect job mask

**Comment by R3P0FFXI** [comment]
@Samikana this is an issue where the item does not appear in Item Armor

**Comment by R3P0FFXI** [comment]
@Samikana @nekrol Issue has been resolved and next time we reimport SQL the gloves will work
