### ISSUE TITLE
Sub Zero Smash Crash

### ISSUE THREAD

**Issue by ffxi007** [LegionDark/Issues#69]
Date & Time**:  6/6-7/2015
**Frequency**: always 
**FFXI Client Version**: 30150508_8
**Character Name**: Katiebelle
**Race**: Hume 
**Main Job**: BLU
**Sub Job**: RDM
**Area & Coordinates**: kamihr drifts 
**Party or Solo**: solo
**NPC Name**:  Slobbering Ruszor 
**Monster Name**: Slobbering Ruszor
**Steps To Reproduce The Issue**: melee the mob until it gets tp and decides to use Sub Zero Smash
entire server R0s

all of its other tp moves work fine being used, same type of issue as the subzero gears for rail cannon awhile back

**Comment by SomeGlenn** [comment]
Eh? How did you even get there?
I had the same experience with the lvl 1 Ruzsors in Xacabard[S] (i think, or Bead[S]). I let them hit me for 40 mins and they TP move. Some times, it would R0, but I was never able to confirm the source of that.

There was 1 time when I actually recovered from the r0, but 4 of the mobs despawned, while 2 remained attacking. Extremely puzzling.

**Comment by R3P0FFXI** [comment]
Da FuQ SOA We dont have SOA Areas open closing
