### ISSUE TITLE
Chasseur's Frac +1 no have haste +4

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#690]
Date & Time: 23:00pm --11/03/16
Frequency: Always
FFXI Client Version: 30151233_0
Character Name: Aurel -
Race: Hume
Main Job: blm
Sub Job: Sam
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name: 
Monster Name:
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/26931/chasseurs-frac-1
Multi-boxing? (multiple clients on same connection): solo
Steps To Reproduce The Issue:Chasseur's Frac +1 no have haste +4

**Comment by Samikana** [comment]
No haste, will check other mods when I fix the item

**Comment by R3P0FFXI** [comment]
@nekrol Fixed in DSP not sure when itll make it into Legion
