### ISSUE TITLE
Sailfi Belt +1 no have haste +9 

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#691]
Date & Time: 23:00pm --11/03/16
Frequency: Always
FFXI Client Version: 30151233_0
Character Name: Aurel -
Race: Hume
Main Job: blm
Sub Job: Sam
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name: 
Monster Name:
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/28428/sailfi-belt-1
Multi-boxing? (multiple clients on same connection): solo
Steps To Reproduce Sailfi Belt +1 no have haste +9,no work unity ,"Triple Attack"+2% not idea

**Comment by Samikana** [comment]
Item mods are not coded.

**Comment by R3P0FFXI** [comment]
@nekrol Fixed in Legion should be active next time we update, @Samikana added mods to custom file
