### ISSUE TITLE
Haste doesn't spread with SCH's Accession ability

### ISSUE THREAD

**Issue by Hallabaloo4** [LegionDark/Issues#692]
**Date & Time**: 5:35 PM PST

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Halabaloo

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 96 SCh / 48 RDM

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce The Issue**: Use Light Arts -> Accession (Spreads next healing or enhancing magic to party) -> Cast Haste

**Comment by Baucant** [comment]
it never has even in retail

**Comment by PikaFox** [comment]
Grants 15% Magic haste (150/1024).
Does not stack with Accession

https://www.bg-wiki.com/bg/Haste

I dont get it either, SE went full retard on this imo.
