### ISSUE TITLE
Avatara Slops

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#693]
**Date & Time**: 10:04 3/12/16
Frequency: 
FFXI Client Version: 30151215_0
Character Name: Ritonami
Race: Mithra
Nation: Windurst
Main Job: smn
Sub Job: rdm
Area & Coordinates: -36, -10, -2
Party or Solo: solo
NPC or Monster Name: 
ffxiah.com link (for inventory items only): http://www.ffxiah.com/item/27221/avatara-slops
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue: smn can't equip avatara slops

**Comment by R3P0FFXI** [comment]
@Samikana Missing Item_Armor in DSP master files

**Comment by R3P0FFXI** [comment]
@ritonami is now fixed in DSP no idea when this will get pulled into Legion
