### ISSUE TITLE
Nahtirah Hat

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#694]
**Date & Time**: 10:04 3/12/16
Frequency: 
FFXI Client Version: 30151215_0
Character Name: Ritonami
Race: Mithra
Nation: Windurst
Main Job: smn
Sub Job: rdm
Area & Coordinates: -36, -10, -2
Party or Solo: solo
NPC or Monster Name: 
ffxiah.com link (for inventory items only): http://www.ffxiah.com/item/27775/nahtirah-hat
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue: smn can't equip Nahtirah hat

**Comment by R3P0FFXI** [comment]
@Samikana needs DSP fix should be 1622556 not 3179576 for the job mask in item_armor.sql

**Comment by R3P0FFXI** [comment]
@ritonami Fixed in DSP no idea when this will get pulled into Legion,
