### ISSUE TITLE
Ternion dagger +1

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#695]
Date & Time: 10:04 3/12/16
Frequency: 
FFXI Client Version: 30151215_0
Character Name: Ritonami
Race: Mithra
Nation: Windurst
Main Job: dnc
Sub Job: rdm
Area & Coordinates: -36, -10, -2
Party or Solo: solo
NPC or Monster Name: 
ffxiah.com link (for inventory items only): http://www.ffxiah.com/item/20604/ternion-dagger-1
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue: dnc cant equip Ternion dagger+1

**Comment by R3P0FFXI** [comment]
@Samikana Job entry needs to be 1867769 in DSP currently listed as 1605625, needs to be fixed and sent to DSP

**Comment by R3P0FFXI** [comment]
@ritonami Fixed in DSP no idea when this will get pulled down into legion
