### ISSUE TITLE
Eminent Dagger

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#696]
Date & Time: 10:04 3/12/16
Frequency: 
FFXI Client Version: 30151215_0
Character Name: Ritonami
Race: Mithra
Nation: Windurst
Main Job: dnc
Sub Job: rdm
Area & Coordinates: -36, -10, -2
Party or Solo: solo
NPC or Monster Name: 
ffxiah.com link (for inventory items only): http://www.ffxiah.com/item/20624/eminent-dagger
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue: dnc cant equip eminent dagger

**Comment by R3P0FFXI** [comment]
Fixed in Item_Armor Custom 1867769 is correct mask for jobs @Samikana , this should work next time we update @ritonami
