### ISSUE TITLE
eminent Scimitar

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#697]
Date & Time: 10:04 3/12/16
Frequency: 
FFXI Client Version: 30151215_0
Character Name: Ritonami
Race: Mithra
Nation: Windurst
Main Job: drk
Sub Job: rdm
Area & Coordinates: -36, -10, -2
Party or Solo: solo
NPC or Monster Name: 
ffxiah.com link (for inventory items only): http://www.ffxiah.com/item/20726/eminent-scimitar
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue: pld and rdm cant equip eminent scimitar

**Comment by R3P0FFXI** [comment]
@ritonami this is fixed in Legion now, @Samikana incorrect job mask in item_armor should be 2195665

**Comment by TeoTwawki** [comment]
I really don't need the flood of single item issues clogging my notifications. I you have a lit of items, make ONE list.
