### ISSUE TITLE
Quest - Arts and Crafts not completable

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#698]
**Date & Time**: 3/13/2016 11:56

**FFXI Client Version (use `/ver`)**: 30151223_0

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:Thf99/DNC49 

**NPC or Monster or item Name**: Starting NPC  Hadahda - NPC not working ass expected-  Zabahf, Ekhu Pesshyadha & Qutiba

**Zone name & Coordinates (use `@where`)**: Aht Urhgan Whitegate X:-89 Y:0 Z:12 (65) , X:-13 Y:2  Z:100 (187) & X:91 Y:-6 Z:-128 (41)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No 

**Steps To Reproduce The Issue**: Attempted to speak with the NPC multiple times. tried zoneing and speaking to them again no results

**Comment by TeoTwawki** [comment]
###### _I am Teo's complete lack of surprise._

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
