### ISSUE TITLE
Wayfarer Clogs not stats shown on status screen

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#699]
Date & Time: 23:00pm --13/03/16
Frequency: Always
FFXI Client Version: 30151233_0
Character Name: Aurel -
Race: Hume
Main Job: blm
Sub Job: Sam
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name: 
Monster Name:
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/28308/wayfarer-clogs
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce:
![captura](https://cloud.githubusercontent.com/assets/13084662/13732000/ba84882e-e94d-11e5-9f86-19fe57812a26.PNG)

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
