### ISSUE TITLE
Delivery Box Item Recovery

### ISSUE THREAD

**Issue by Xenres** [LegionDark/Issues#700]
**Date & Time**: 3/14/16, 1856 JST

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Zenephret

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: MNK99/WAR49

**NPC or Monster or item Name**: Juogi +1

**Zone name & Coordinates (use `@where`)**: Mog House

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/12622/juogi-1

**Multi-boxing? (multiple clients on same connection)**: Yep

**Steps To Reproduce The Issue**: Pretty sure that was the only thing in DB. Very low priority so absolutely no rush to get this done so feel free to push til after update stuff is done. Thanks!

**Comment by Samikana** [comment]
Will you be on between 3-10pm est.  I can't give an exact time I'll be on but sometime in between there.

**Comment by Xenres** [comment]
I'm at work now, but I logged the character in so hopefully it stays up

**Comment by Samikana** [comment]
I actually couldn't get online today.  I got called into work and I was only home twice when I stopped in to get my textbooks for class and when I ran (literally ran) home to feed my pets and then when I got home.  I deeply apologize and I'll get to you ASAP.

**Comment by Xenres** [comment]
Appreciate the update, but no need to apologize for anything. Like I said no rush at all and real life comes first. I'll try to just leave the char logged in when I can

**Comment by R3P0FFXI** [comment]
@Xenres Closing due to lack of responses, if this issue has not been resolved please contact a GM and open a new bug report
