### ISSUE TITLE
AH, LS list and search fail to function

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#701]
**Date & Time**: 3/14/2016 7:17pm

**FFXI Client Version (use `/ver`)**: 30151223_0

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:THF99/DNC49 

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**:All Zones all Coordinates 

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**:N/A 

**Steps To Reproduce The Issue**: Tried from multiple zones. relogging, numerous people stating same issue

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
