### ISSUE TITLE
Vadleany

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#702]
Date & Time: 9:19 3/14/16
Frequency: 
FFXI Client Version: 30151215_0
Character Name: Ritonami
Race: Mithra
Nation: Windurst
Main Job: thf
Sub Job: dnc
Area & Coordinates: abyssea altepa -62 0 103
Party or Solo: solo
NPC or Monster Name: Vadleany
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue: Vadleany is supposed to be a ladybug, it spawns as a scorpion, its named vadleany but it's shaula.
Here's a link to his info: https://www.bg-wiki.com/bg/Vadleany

**Comment by TeoTwawki** [comment]
Monster and NPC names, IDs, and models get mixed up by client and server versions not matching. If its still screwed up after the update then someone will check into it. Chances are the IDs there need re-synced for that zone. This could be wrong in several different ways that would all fit your issue description, and without actually checking it after the update with a client matching the server, I can't know for sure.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
