### ISSUE TITLE
Upas-Kamuy snow god core

### ISSUE THREAD

**Issue by Thotless** [LegionDark/Issues#703]
**Date & Time**:  3/14/2016  8:30 PM MST

**FFXI Client Version (use `/ver`)**: 30151215_0

**Character Name**: Thotless

**Nation**: Bastok

**Job(level)/Sub Job(level)**: Ninja 99/ Warrior 49

**NPC or Monster or item Name**: Upas-Kamuy

**Zone name & Coordinates (use `@where`)**: Abyssea-Uleguerand @ X: -212, Y: -184, Z: 449 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/3246/snow-god-core

**Multi-boxing? (multiple clients on same connection)**:

**Steps To Reproduce The Issue**: Killed 15+ times with TH8 and never dropped the snow god core.  Doesn't seem right

**Comment by Samikana** [comment]
Drop rate is 10%.  @TeoTwawki I think this fell to Repo's RNG.  Drop rate is around 45ish% on retail.

**Comment by R3P0FFXI** [comment]
Reopen if still an issue after update
