### ISSUE TITLE
Limbus item Sheet Of Kurogane not dropping

### ISSUE THREAD

**Issue by w3genesis** [LegionDark/Issues#704]
**Date & Time**: 3/14/2016

**FFXI Client Version (use `/ver`)**: newest

**Character Name**: Gouken

**Nation**: Bastok

**Job(level)/Sub Job(level)**: sam99/war49

**NPC or Monster or item Name**: Limbus mobs

**Zone name & Coordinates (use `@where`)**: NE Apollyon

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/1953/kurogane

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce The Issue**: This item is used to upgrade Sam af1. 
In db lookup no mob currently drops this item http://legiondark.com/db/items/1953/sheet_of_kurogane

**Comment by TeoTwawki** [comment]
It won't show in the db lookup because I hacked it in via script: I made all mobs in all limbus zones able to drop all jobs upgrade items, as a temp measure till limbus and its drops can be fixed properly.

**Comment by w3genesis** [comment]
Had gotten a ton of other job items but no kurogane ^^; must be my luck then, will keep trying.
Thanks Teo for the reply!

**Comment by TeoTwawki** [comment]
Yeah its kind of a sucky system atm. The rate is set high, but there's a lot of possible items. This is why I don't consider it anything but temporary - I **hate** luck based things like this, as I myself am not a lucky guy, so I know how it feels.

**Comment by w3genesis** [comment]
Got it on third run in NE ^^
Cronos is bane of my existence though, never seen final level thanks to physical immune...
