### ISSUE TITLE
Incorrect Mob Drops

### ISSUE THREAD

**Issue by Xenres** [LegionDark/Issues#706]
**Date & Time**: 3/18/2016 / 2033 JST

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Zenephret

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: SAM99/WAR49

**NPC or Monster or item Name**: Cobraclaw Buchzvotch

**Zone name & Coordinates (use `@where`)**: Jugner Forest [S] @ X: 2.195, Y: -0.066, Z: -293.161

**ffxiah.com link (for items issues only)**: http://legiondark.com/db/monsters/17113464/CobraclawBuchz

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce The Issue**: Killed this NM as part of a story line quest and it dropped several pieces of it's future self's dynamis gear. Mob also spawns in Dynamis - Beaucedine so it's Jugner Forest [S] equivalent appears to have the same drop table loaded, but shouldn't drop anything. I'll check out the other Dyna mobs to see if they have past equivalents and update if I find anymore.

**Comment by TeoTwawki** [comment]
my apologies that nobody got back to you, this was fixed and the issue report never updated.
