### ISSUE TITLE
Gotoh Zha the Redolent popping crashing server

### ISSUE THREAD

**Issue by benfolka** [LegionDark/Issues#708]
**Date & Time**: 16.44

**FFXI Client Version (use `/ver`)**: latest

**Character Name**: Clay

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: war/dnc

**NPC or Monster or item Name**: Gotoh Zha the Redolent

**Zone name & Coordinates (use `@where`)**: Wajaom Woodlands. @pos -337 -31 676 51

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  no

**Steps To Reproduce The Issue**: trading a Sheep Botfly to the ??? at (F-5) behind the Watchtower crashes server

**Comment by benfolka** [comment]
also may be travelling inside mamook taking down the server not sure about this, have to be tested.

**Comment by R3P0FFXI** [comment]
@TeoTwawki @benfolka confirmed 

Sheep Botfly
Key Items: Apple green seal

Are causing R0 with this NM when trading and trying to pop

**Comment by TeoTwawki** [comment]
think I fixed this but forgot to close it?

**Comment by benfolka** [comment]
i will test and close it

**Comment by benfolka** [comment]
no it still crashes server.

**Comment by TeoTwawki** [comment]
:(

**Comment by TeoTwawki** [comment]
Self reminder: check family ID, spell list ID

**Comment by benfolka** [comment]
Groundburst or Warm-Up move may be breaking server. The mob is using one of these  moves soon as it pops if i remember right.

**Comment by TeoTwawki** [comment]
no its his spell list

I fixed in trunk its not in live yet

**Comment by benfolka** [comment]
thanks so much for the hard work

**Comment by TeoTwawki** [comment]
should be all workin now, forgot to close issue after maint
