### ISSUE TITLE
(Storms of fate) entering bcnm takes down the server 

### ISSUE THREAD

**Issue by benfolka** [LegionDark/Issues#709]
**Date & Time**: 18.37

**FFXI Client Version (use `/ver`)**: latest

**Character Name**: Clay

**Nation**: SAndoria

**Job(level)/Sub Job(level)**: war/dnc

**NPC or Monster or item Name**:  http://ffxiclopedia.wikia.com/wiki/Storms_of_Fate

**Zone name & Coordinates (use `@where`)**:  entering bcnm for storms of fate takes down the server it is this quest here http://ffxiclopedia.wikia.com/wiki/Storms_of_Fate

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce The Issue**:

**Comment by benfolka** [comment]
tried it second time definitely it goes down

**Comment by R3P0FFXI** [comment]
Stop trying things that NEVER worked before @benfolka this was never even part of the update notes

**Comment by benfolka** [comment]
i dont
