### ISSUE TITLE
Missing Mob group

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#71]
**Date & Time**: 6/7/2015 9:50am
**Frequency**: always
**FFXI Client Version**: 30150508_8
**Character Name**:Baucant
**Race**:Elvan
**Main Job**:thf
**Sub Job**:dnc
**Area & Coordinates**: aby misareaux coast X:-201 Y:-32 Z:79 (227) general area
**Party or Solo**: Party
**NPC Name**: n/a
**Monster Name**: Observers
**Steps To Reproduce The Issue**: This entire mob group is non exsitance. These drop an Item needed to Pop NM for KI to pop NM that give atma Razed ruines The item seems to use to be part of AH bot but none are available and last sold was 5/15/15

**Comment by Loki79** [comment]
fixed.  will be in after maint.

**Comment by Baucant** [comment]
great work placing the mobs however the item needed to pop the NM was not added to the Observers drop list. can we please add Spheroid Plate to the list of possible drops
