### ISSUE TITLE
renik af+1 reforged blm feet error-Sam head error --rdm head error

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#710]
![captura](https://cloud.githubusercontent.com/assets/13084662/13886572/c8dc522e-ed37-11e5-8587-08b5635ad7fb.PNG)
![ptura](https://cloud.githubusercontent.com/assets/13084662/13886581/d058e2b0-ed37-11e5-875d-00d1debf7222.PNG)

Date & Time: 09/02/2016, 23:00pm --01/03/16
Frequency: Always
FFXI Client Version: 30160203_0
Character Name: Aurel
Race: Hume
Main Job: blm
Sub Job: Sam
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name:Renik
Monster Name:
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/27335/arch-sabots-1
http://www.ffxiah.com/item/27688/atro-chapeau-1
http://www.ffxiah.com/item/27695/wakido-kabuto-1
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:
i have trade 
http://www.ffxiah.com/item/27334/arch-sabots + 5 rems chap 1 ,and i obtain rdm feet af1 reforged lol 
http://www.ffxiah.com/item/28248/atrophy-boots-1
i have trade
http://www.ffxiah.com/item/27674/wakido-kabuto +5 rems chap 4,and i obtain
http://www.ffxiah.com/item/27694/orion-beret-1
i have trade
http://www.ffxiah.com/item/27667/atrophy-chapeau +5 rems chap 4,and i obtain
http://www.ffxiah.com/item/27687/spae-petasos-1
captura
ra
i need GM deliver the AF 119

**Comment by nekrol** [comment]
when there is a solution to this, there's always GM online

**Comment by Samikana** [comment]
Refile your bug report and try to do it with a nicer tone and maybe I'll help you next time!  These need to be filed separately.

**Comment by R3P0FFXI** [comment]
@nekrol @Samikana @Genesis-Legion I have fixed the script for this and found BLM Head, Body, Hands, Feet were all coded incorrectly. Please see a GM In game to get your items returned to you.

**Comment by Genesis-Legion** [comment]
Aurel was taken care of.
