### ISSUE TITLE
Voay Sword -1 not reflecting on AH

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#711]
**Date & Time**: 3/18/2016

**FFXI Client Version (use `/ver`)**:30160203_0 

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:Thf99/Dnc49 

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**:all zones all Coodinates 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/20772/voay-sword-1

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce The Issue**: Placed on AH went to see if it listted was not listed

**Comment by R3P0FFXI** [comment]
@Samikana can you look into this please, this is one of the new crafting mats

**Comment by Baucant** [comment]
This also doesn't show as a crafting mat via item search tool

**Comment by R3P0FFXI** [comment]
@Samikana this is listed in DSP Item_basic but has no item_armor

INSERT INTO `item_basic` VALUES (20772,0,'voay_sword_-1','voay_sword_-1',1,2048,4,0,100);

Looks like its showing that it can be on AH as the category is 4

**Comment by Samikana** [comment]
Should be 3

**Comment by Samikana** [comment]
Actually, @R3P0FFXI, it looks like this is in the correct AH slot.  4 is for greatsword.  

I'll do the item_armor entry right now and send it to you.

**Comment by Samikana** [comment]
Fixed & sent.
