### ISSUE TITLE
Prishe do not accept the item for reforge Arbatel bracers

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#712]
Date & Time: 15/12/2015, 14:00pm Reopen 18/03-16
Frequency: Always
FFXI Client Version: 30160203_0
Character Name: cassy
Race: Hume
Main Job: -sch
Sub Job: Sam
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name:Prishe
Monster Name:
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/27090/arbatel-bracers
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The IssuePrishe do not accept the item ,30 Itzpapalotl's Scale +Savant's Bracers +2
![captura](https://cloud.githubusercontent.com/assets/13084662/13887074/2a762bf2-ed3a-11e5-9292-7ef26f759b9e.PNG)

**Comment by R3P0FFXI** [comment]
@nekrol this tells me nothing what items did you trade you need to be detailed

**Comment by nekrol** [comment]
issue is reopen to

**Comment by Samikana** [comment]
Not enough information.

**Comment by TeoTwawki** [comment]
#467

@nekrol prishe needs rewritten. to many reports of things being wrong
