### ISSUE TITLE
Hyacinth Stratum Abyssite not up to Hyacinth Stratum Abyssite II

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#713]
Date & Time: 23:00pm --18/03/16
Frequency: Always
FFXI Client Version: 30160203_0
Character Name: Aurel -Cassy
Race: Hume
Main Job: blm
Sub Job: Sam
Area & Coordinates: Tavnazian Safehold X:-16 Y:-25 Z:125 (201)
Party or Solo: Party or solo 
NPC Name: Owain
Monster Name:
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:
-- Aurel ,Cassy Defeat the 4 monsters:
Fjalar in Attohwa Chasm
Abununnu in Lufaise Meadows
Tsui-Goab in Misareaux Coast
Isarukitsck in Uleguerand Range
Return to Owain to finish this quest and not work CS no up KI Hyacinth Stratum Abyssite II.

**Comment by Samikana** [comment]
@LegionDark/gm Any verification on this?

**Comment by TeoTwawki** [comment]
reference issue that should not have been closed really. #653

**Comment by TeoTwawki** [comment]
Oh boy. This thing is so wrong.

@nekrol I still haven't got this fixed yet, but when I do I'll push you past it.

**Comment by TeoTwawki** [comment]
@Aurelcassy  Finally was able to sit down and handle this. will look for you in game soon.

**Comment by TeoTwawki** [comment]
You seemed to be AFK but should be on the next part now.

**Comment by Aurelcassy** [comment]
thank you
