### ISSUE TITLE
VW MOB

### ISSUE THREAD

**Issue by djmanofsteel** [LegionDark/Issues#714]
**Date & Time**: 1:38pm est

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Mano

**Nation**: bastok

**Job(level)/Sub Job(level)**: NIN99/WAR99

**NPC or Monster or item Name**: Kholomodumo

**Zone name & Coordinates (use `@where`)**: Jugnar Forrest(s)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce The Issue**: NM Cast Ecliptic Meteor and then there was crash

**Comment by R3P0FFXI** [comment]
@TeoTwawki Here's another one

**Comment by TeoTwawki** [comment]
"Fixed" by disabling retarded meteor
