### ISSUE TITLE
Wayfarer Clogs not stats shown on status screen

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#715]
Date & Time: 23:00pm --18/03/16
Frequency: Always
FFXI Client Version: 30160203_0
Character Name: Aurel -
Race: Hume
Main Job: blm
Sub Job: Sam
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name: 
Monster Name:
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/28308/wayfarer-clogs
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce:

**Comment by R3P0FFXI** [comment]
@Samikana Another item ticket

**Comment by R3P0FFXI** [comment]
@nekrol added mods to item next time we pull they should work, closing ticket
