### ISSUE TITLE
Hvergelmir 99-4 not haveMagic Damage+248 ,,have Magic Damage+130 +-

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#716]
Date & Time: 18/03/2016, 23:00pm
Frequency: Always
FFXI Client Version: 30160203_0
Character Name: Aurel
Race: Hume
Main Job: blm
Sub Job: Sam
Area & Coordinates: 
Party or Solo: Party or solo 
NPC Name:Renik
Monster Name:
ffxiah.com link (for inventory items only):http://www.ffxiah.com/item/21144/hvergelmir
Multi-boxing? (multiple clients on same connection): yes
Steps To Reproduce The Issue:Hvergelmir 99-4 not haveMagic Damage+248 ,,have Magic Damage+130 +- ,when use Hvergelmir dmg is = 1300 ,,,using bolelabunga dmg is = 1300 ,other staff 2400 dmg  ,is very It is frustrating to use

**Comment by Samikana** [comment]
Coded as intended to be coded.  Bolelabunga has less magic damage than Hvergelmir.

**Comment by nekrol** [comment]
Hvergelmir. 1300 dmg  = Bolelabunga 1300 dmg  not is correct.....so no longer has my interest ,thanks

**Comment by TeoTwawki** [comment]
your mouth no longer has the interest of my ears either

**Comment by Samikana** [comment]
@TeoTwawki Bolelabunga has spell damage +130, but I am standing by the idea that it's meant to and the other weapon isn't meant to.

**Comment by Samikana** [comment]
Meant to have a custom mod and the other isn't *

**Comment by TeoTwawki** [comment]
@Samikana I'm just sick of people being mouthy and thinking their problem should be the top priority

**Comment by Samikana** [comment]
I agree.
