### ISSUE TITLE
Palladian Brass Ingot (x2)+ fire crystal = Evader Earring (fail)

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#717]
**Date & Time**: 3/18/2016

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:Thf99/Dnc49 

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: All zone all coordinates

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/11060/evader-earring

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce The Issue**: chjecked item Database confimed craft. Crafted resulted in Palladian brass chain Which should be Palladian brass ingot (x2) + EARTH crystal. This also make GSM crafting impossible to exceed lvl 100

**Comment by R3P0FFXI** [comment]
@Baucant Fixed this in DSP so when we update again it will get fixed
