### ISSUE TITLE
GSM NPC doesn't state item needed to Surpass lvl 100

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#718]
**Date & Time**: 3/18/2016 2:30

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:THF99/DNC49 

**NPC or Monster or item Name**: Reinberta

**Zone name & Coordinates (use `@where`)**:Bastok Markets X:-193 Y:-6 Z:-59 (159)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**:yes 

**Steps To Reproduce The Issue**: Talked to NPC still say "Try your hand at  ." should say evader earring. Also Evader earring is uncraftable at this time.

**Comment by R3P0FFXI** [comment]
@Baucant Issue resolved today in massive Update part 2
