### ISSUE TITLE
Wicce Petasos = fail

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#719]
**Date & Time**: 3/18/2016

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Merlin, Mizrable, Bellatrix

**Nation**: Sandy

**Job(level)/Sub Job(level)**:Blm99/Rdm49 

**NPC or Monster or item Name**: Prishe

**Zone name & Coordinates (use `@where`)**:Aby Paradox  X:536 Y:-500 Z:-592 (81)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/26746/wicce-petasos

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce The Issue**: Attempted to trade 30Itza scales + Goetia Petasos +2 no responce

**Comment by Samikana** [comment]
All of this shit was included in a master report of all Relic, Empyrean, and AF trial issues.

**Comment by R3P0FFXI** [comment]
@Baucant issue has been resolved in Massive Update Pt2 will be in next maint
