### ISSUE TITLE
Bastok VW NM

### ISSUE THREAD

**Issue by djmanofsteel** [LegionDark/Issues#721]
**Date & Time**: 4:00pm

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Mano

**Nation**: Bastok

**Job(level)/Sub Job(level)**: Nin99/War49

**NPC or Monster or item Name**: Celaena

**Zone name & Coordinates (use `@where`)**: Dangruf Wadi **pos data missing**

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce The Issue**: Mob did not use benediction.
Mob also did not de-spawn after 30 min. in fact stayed up for 60+ min. before dying.
upon death did not change indigo Stratum Abyssite.

**Comment by TeoTwawki** [comment]
Did mob use chainspell? Did mob give out EXP bonus on death?
Depop stuff has been removed for now due to bugs.

**Comment by djmanofsteel** [comment]
this was a while ago Teo think it was already fixed i haven't been back to do this one again since march  when i posted this i believe. havent heard of anyone having any more issues with it.
