### ISSUE TITLE
Call Beast server crash

### ISSUE THREAD

**Issue by Thotless** [LegionDark/Issues#723]
**Date & Time**:  2:20 PM MST

**FFXI Client Version (use `/ver`)**: 

**Character Name**: Thotless

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BST99/DNC49

**NPC or Monster or item Name**: Wormy Broth

**Zone name & Coordinates (use `@where`)**: Abyssea - La' Theine

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce The Issue**: Tried to use Call Beast with wormy broth equipped.  Seems to have crashed server

**Comment by TeoTwawki** [comment]
Slippery Silas go boom.

**Comment by TeoTwawki** [comment]
Mind checking older jugs? Today is crash city anyway, so I just wanna know that any other jug at all works. Try an cheap sheep or something and later I'll gift you a jug of your choice.

**Comment by Thotless** [comment]
Sure, I'll test the few I can get a hold of.

**Comment by TeoTwawki** [comment]
If even one of the older mobs works/doesn't that gives me what I need to know. As long as its one we know worked before.

**Comment by Thotless** [comment]
Carrot broth seems fine, and I know for a fact it worked as well before the update

**Comment by TeoTwawki** [comment]
k, its likely something wrong with just the new jugs then. Some missing peace of data it needs in order to load all its stats properly. In Silas case, it didn't know how much elemental magic skill it should have.

**Comment by TeoTwawki** [comment]
@R3P0FFXI we'll need to test these in zone 49 to see if your sql edits fixed any and which ones still crash

**Comment by R3P0FFXI** [comment]
@Thotless issue resolved today in Massive update Part 2 beast pets to 99 are now working, ilvl pets are not
