### ISSUE TITLE
celestial nexus

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#725]
Date & Time: 3/18/2016
Frequency: 
FFXI Client Version: 30151215_0
Character Name: Ritonami
Race: Mithra
Nation: Windurst
Main Job: thf
Sub Job: nin
Area & Coordinates: -36, -10, -2
Party or Solo: solo
NPC or Monster Name: 
ffxiah.com link (for inventory items only): 
Multi-boxing? (multiple clients on same connection): no/yes
Steps To Reproduce The Issue: Got up to the bcnm for ZM16 Celestial Nexus, cleared first phase timed out on second phase. only one client on connection at time. got mule up to same mission, went to go duo it, Ritonami couldnt activate fight, could participate, checked mission log sealed shrine is current mission and as a completed mission. Tried to get cs for sealed shrine again didn't work. Cleared the fight, mule got cs in norg main didn't

**Comment by R3P0FFXI** [comment]
@ritonami you need to log out both characters then only login 1 and do the fight, simply logging 1 out doe snot fix the dual boxing issues that plague DSP servers.

**Comment by TeoTwawki** [comment]
@R3p0FFXi I think he's already been glitched since the one character has the same mission as both completed and current and could not even activate the battle. He's going to need all the post battle code exec'd on that character manually, or else reset variable back to start of mission with it deleted and re-added so he can do the fight.

**Comment by ritonami** [comment]
yeah it's more along the lines of what Teo said. My Mission was The Celestial Nexus, i failed the bcnm, and came back and did the bcnm again and beat it, had to have a different character actually start the bcnm. When i didnt get the cs in norg i checked mission log, and instead of the mission progressing to awakening, it had reverted to the sealed shrine. Also i tried redoing the sealed shrine, i cant retrigger the cs

**Comment by TeoTwawki** [comment]
@ritonami did this ever get taken care of? if it has close the issue.

**Comment by ritonami** [comment]
Honestly my pc haa been outta commission for awhile and i started a new job so i havent had time to check. I plan on logging in soon so i will update then but as of last log in it has not been fixed

**Comment by ritonami** [comment]
It's still broken, any chance someone could look into it

**Comment by PikaFox** [comment]
checkmission 3 -> THE_SEALED_SHRINE   = 27  player claims it is both active and complete.

**Comment by PikaFox** [comment]
Player got CS at Gilgamesh's door. Reply back if any further issues are encountered, or if you complete the mission so that the ticket may be closed.

**Comment by ritonami** [comment]
seems to have worked
