### ISSUE TITLE
Character missing

### ISSUE THREAD

**Issue by tammy7th** [LegionDark/Issues#727]
**Date & Time**: 3-18-16

**FFXI Client Version (use `/ver`)**: 

**Character Name**: Willow

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 15?

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce The Issue**: 
My character, Willow is missing.

**Comment by TeoTwawki** [comment]
Does the account still log in? Are any other characters on the same account?

**Comment by tammy7th** [comment]
I have 3 other characters still ok on my account. Autumnmoon, Tigerlily and
Summerrose. There is just the 4th one gone, Willow. But all my gear and gil
seem to be fine on the other 3 characters. 
 
 
 
 
-------Original Message-------
 
From: TeoTwawki
Date: 3/18/2016 10:28:16 PM
To: LegionDark/Issues
Cc: tammy7th
Subject: Re: [Issues] Character missing (#727)
 
Does the account still log in? Are any other characters on the same account?

**Comment by TeoTwawki** [comment]
Ok, hit the newly enforced char limit. Which you probably were too new to hear of. There are bugs with multiple characters on one account, so we need to limit to 3 per account. I f you make an additional account I can move them between accounts for you no problem.

Just post both account names and which character you want moved to which account. Sorry for the inconvenience. If Darkstar ever fixes that packet we'll be able to allow the full set of content IDs per account again.

**Comment by tammy7th** [comment]
Ok, I made a second account. So I guess you can put my missing character
Willow onto the new account. My old account name is tammy7th. The new
account I just made is tammy07. 

So, Willow would go onto the account tammy07.

And Autumnmoon, Tigerlily and Summerrose would stay on the old account where
they are currently.

Thanks for your help  
 
 
 
 
-------Original Message-------
 
From: TeoTwawki
Date: 3/18/2016 10:44:43 PM
To: LegionDark/Issues
Cc: tammy7th
Subject: Re: [Issues] Character missing (#727)
 
Ok, hit the newly enforced char limit. Which you probably were too new to
hear of. There are bugs with multiple characters on one account, so we need
to limit to 3 per account. I f you make an additional account I can move
them between accounts for you no problem.
Just post both account names and which character you want moved to which
account. Sorry for the inconvenience. If Darkstar ever fixes that packet we
ll be able to allow the full set of content IDs per account again.

**Comment by TeoTwawki** [comment]
check both accounts when you get a chance and see if everything shows correctly now.

**Comment by tammy7th** [comment]
Sorry for the delay. Yes, both accounts are working and my missing character
is back! Thank you! 
 
 
 
 
-------Original Message-------
 
From: TeoTwawki
Date: 03/19/16 19:43:52
To: LegionDark/Issues
Cc: tammy7th
Subject: Re: [Issues] Character missing (#727)
 
check both accounts when you get a chance and see if everything shows
correctly now.
