### ISSUE TITLE
annihilator animation

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#73]
**Date & Time**: 05/06/15
**Frequency**: always
**FFXI Client Version**:
**Character Name**:Itachioax
**Race**:Hume
**Main Job**: RNG
**Sub Job**: SAM
**Area & Coordinates**:
**Party or Solo**:solo
**NPC Name**: none
**Monster Name**: none
**Steps: this about the annihilator 99-4 animation, it doesnt show, just move the hands but the weapon not

**Comment by Loki79** [comment]
if i fix a an issue and say it will be resolved after maint, dont post another damn ticket until after maint.  maint is on TUESDAY so the fix will not go in until then.
