### ISSUE TITLE
Non-aggressive mob attacks as though it was linking to earlier battle

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#730]
**Date & Time**: 18 March 2016 23:45ish

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Buttons

**Nation**: Windurst

**Job(level)/Sub Job(level)**: 85BLM/42WHM

**NPC or Monster or item Name**: Targe Beetle

**Zone name & Coordinates (use `@where`)**: Ordelle Caves (x:-34, y:32, z:0)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce The Issue**: Nuke a Targe Beetle to death on one side of the cave. Run to the other side of the cave (well out of linking range) and, if there's another Targe Beetle present, it will attack as though it was linking to the earlier battle. 

For lack of a better way of putting it, it's as though a "hate variable" isn't being cleared properly after the original fight is over. 

Thanks for reading.

**Comment by TeoTwawki** [comment]
We may have to live with some strange things for a bit, but we'll look into it. I know DSP fixed something similar fairly recently.

**Comment by Midgardsormr** [comment]
Gotcha. Thanks!!

**Comment by TeoTwawki** [comment]
Open new issue if this occurs again.
