### ISSUE TITLE
(website tool display)  mobs in db are borked

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#731]
**Date & Time**:  3/19/16

**FFXI Client Version (use `/ver`)**:  30160203_0

**Character Name**:  Daedrik

**Nation**:  Bastok

**Job(level)/Sub Job(level)**: BLU99//RDM49

**NPC or Monster or item Name**:  Jormungand

**Zone name & Coordinates (use `@where`)**:  Ulegerand Range  @  X280,  Y1,  Z396

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce The Issue**:  

Just tested and Jormy is still using all its Wyrm abilities so it might just be the page that is wrong.

Also checked Tiamat in game and is not up, Page says it's not implemented so which is right.

And the Ravishing Raflesia that normally accompany Morta seem to be switched with Vrtra.
Upon engaging Vrtra it did all normal Wyrm attacks so it could just be named switched like Jormy.

![morta-1](https://cloud.githubusercontent.com/assets/12631024/13899087/424c3358-eda2-11e5-9351-ae8c7de31871.PNG)

Raflesia in King Ramperres Tomb:

![morta-2](https://cloud.githubusercontent.com/assets/12631024/13899089/501025ee-eda2-11e5-880d-70d33c2e4f17.PNG)

**Comment by TeoTwawki** [comment]
Would you mind reopening this in the website tracker, using its template?

https://github.com/LegionDark/Website/issues

```
**Bug Date & Time**:
**Bug Name**:
**Bug Page/Url**:
**Bug Information**:
**Steps To Reproduce The Bug**:
**Additional Information**:
```
Thanks.

**Comment by TeoTwawki** [comment]
ITT: website issues don't go In tracker named "website" when the cause isn't website code, isn't possible for end users to know and I don'\t even know myself. Super.

**Comment by atom0s** [comment]
The website just pulls info that is within the database. So if it is wrong on the site, it means it's wrong in the database. I assume these issues were due to a sql file not getting executed when the update happened and we had the roll back due to an incorrect query.

**Comment by TeoTwawki** [comment]
@atom0s I haven't a clue how one mob would pull up anothers data, even with bad IDs in their database. I am aware of entries with non existing family IDs, but not any overlap (example: mob has family ID 9970 but no such family exists in the family table). Similar screw ups could exist in with group and pool IDs, but nothing I know of that puts the same info on two mobs. 

Thats all I know, and I haven't time to research it so I assigned R3 and this will prolly be on the back burner for a long time, at a minimum till VW mobskills are fixed up (need skill scripts hooked up to their database name/ID).

**Comment by TeoTwawki** [comment]
@atom0s the short of it is i assumed the same thing but didn't know for sure how the tool fetches what form where, which is why I pm'd you on irc. but our schedules don't line up lately.

**Comment by R3P0FFXI** [comment]
@Rohelius thiss hould all be resolved on the back end in massive Update pt 2 as this is pulled directly from the server SQL and displayed on the webpage. Also @atom0s did a little extra coding to make things a bit more clear for you guys
