### ISSUE TITLE
Titanium Ore doesn't stack

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#732]
**Date & Time**: 3/19/2016 3:48 pm

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:Thf99/Dnc99 

**NPC or Monster or item Name**: titanium ore

**Zone name & Coordinates (use `@where`)**:All zones and Coordinates 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/4020/titanium-ore

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce The Issue**: tried sorting inventory

**Comment by R3P0FFXI** [comment]
@Baucant Fixed in DSP no idea when this will get pulled down and into Legion
