### ISSUE TITLE
4th character has disappeared from Tick account and would like to be moved to DomingoSeven2 (had enough currency to make a relic and was rank 6)

### ISSUE THREAD

**Issue by DomingoSeven** [LegionDark/Issues#733]
**Date & Time**:  Last update

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Grimace

**Nation**: San D'oria

**Job(level)/Sub Job(level)**: MNK(99)/WAR(49)

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce The Issue**:

**Comment by TeoTwawki** [comment]
I'll get this done soon, next time put all that test in the issue comment instead of the subject lol

**Comment by DomingoSeven** [comment]
Will do sir and sorry for the inconvenience

**Comment by TeoTwawki** [comment]
I need the name for that forth character

**Comment by TeoTwawki** [comment]
~~I need the name for that forth character~~
I need both account names, so I can match up that character name

**Comment by TeoTwawki** [comment]
Assuming its "Grimace" to be moved.

**Comment by TeoTwawki** [comment]
I Don't see an account named **DomingoSeven2**. Is the 2 a typo? Because I do see a **DomingoSeven**.

**Comment by DomingoSeven** [comment]
Yes, I just made DomingoSeven2 so there would be no characters on the account.

**Comment by DomingoSeven** [comment]
I mean I made it before i posted

**Comment by TeoTwawki** [comment]
> Is the 2 a typo?

> yes

>  I just made DomingoSeven2

still confused. All I know is  an no account is named **DomingoSeven2**  with the 2 in the database right as I post this.

**Comment by DomingoSeven** [comment]
do I have to make a character for it to become visible? i can log in and everything

**Comment by TeoTwawki** [comment]
no, somethings wrong during your account creation and you aren't actually creating it, or I'd see it.

**Comment by TeoTwawki** [comment]
I'm wondering if theres a max size name you are hitting and what you thought had the 2, doesn't.

**Comment by TeoTwawki** [comment]
Looks like length maxes out at 16

**Comment by TeoTwawki** [comment]
So that should fit..hmm

**Comment by DomingoSeven** [comment]
my mistake, 2 minutes

**Comment by DomingoSeven** [comment]
fixed, was directing windower to my private server like a derp

**Comment by TeoTwawki** [comment]
ok, now I saw and moved Grimace to it.

**Comment by DomingoSeven** [comment]
Thanks a billion, and sorry for the trouble

**Comment by TeoTwawki** [comment]
if all you characters can log in now, we can close this.

**Comment by DomingoSeven** [comment]
just checked and cant see him yet, but i'll give it a minute

**Comment by TeoTwawki** [comment]
relog and he should appear

**Comment by DomingoSeven** [comment]
it's all working, thank you again

**Comment by TeoTwawki** [comment]
Cool, glad all is well now

**Comment by TeoTwawki** [comment]
And you are welcome :)
