### ISSUE TITLE
blazing eruca

### ISSUE THREAD

**Issue by ritonami** [LegionDark/Issues#735]
**Date & Time**:  3:04 3/19/2016

**FFXI Client Version (use `/ver`)**: latest

**Character Name**: Ritonami

**Nation**: windurst

**Job(level)/Sub Job(level)**: thf99/dnc49

**NPC or Monster or item Name**: Blazing Eruca

**Zone name & Coordinates (use `@where`)**: Abyssea-Attohwa @ X: 233, Y: 19, Z: -243

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce The Issue**:  His incinerate is hitting for around 17,000 damage, he used it twice both times around 17,000, havent tried on multiple blazing eruca though

**Comment by thicksz** [comment]
yes i was there on mar 20th every time he did his TP move was over 9k . hes still not working right

**Comment by atom0s** [comment]
This is working correctly as according to retail / wiki standards. His incinerate is supposed to deal a massive amount of damage. You need barfira for the fight and/or shellra to help reduce the damage. Along with that other fire resist gear is recommended if you are not in a large group or under-geared. 

See: http://ffxiclopedia.wikia.com/wiki/Blazing_Eruca

Wiki reports ~12k damage which is obviously going to vary based on gear, weather, resists, buffs, foods, atmas, etc.

**Comment by TeoTwawki** [comment]
Keep in mind all fire breathing Eruca's get huge boosts during fire day/weather plus we have no control over nor an idea how accurate DSP's resistance checks are anymore. If you get slammed for over 12k with a full resist set top tier shell and barfire all at once, thats obviously gonna be a prob, but there isn't much we can do right now anyway - other more serious problems have priority over one NM

**Comment by thicksz** [comment]
ok just wanted to say i had on full buffs from whm was not fire day i also had on 100 %fire resistance ATAM on at start of fight it open with move and DOSE not do 12k dd its 17549 DD .. test it your self go fight it fully buffed up and u will see its 17k+ with all buffes and resistance u can put on in game.. so he is not working correctly ...

**Comment by TeoTwawki** [comment]
>  test it your self go fight it fully buffed up and u will see its 17k+ with all buffes and resistance u can put on in game.. 

yeah no, he's not even on my radar until the mountain of other broken mobs are handled

**Comment by R3P0FFXI** [comment]
@ritonami @thicksz mob Issues have been resolved and fix will be in next maint
