### ISSUE TITLE
Unexpected result from unstuck tool

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#736]
**Date & Time**: 3/19/2016 6:48pm

**FFXI Client Version (use `/ver`)**:30160203_0 

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:Thf99/nin49 

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**:North Sandy X:71 Y:0 Z:231 (93)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce The Issue**: Used unstuck tool place me in this location. I can not move.

**Comment by TeoTwawki** [comment]
@atom0s first time this happened, someone landed somewhere strange in port bastok, any idea why?

**Comment by atom0s** [comment]
Where is your homepoint set to? I need the zone and the specific homepoint. As in, is it the mog house or one of the crystals? If its a crystal, which one etc.

**Comment by Baucant** [comment]
my HP is Northern San d`Oria HP crystal #3

**Comment by Baucant** [comment]
Someone eles has fallen "Victum" to the unstuck tool 
Character name: Klang 
HP: Bastok Mine Mog House
Coordinates unstuck tool placed: X:116 Y:0 Z:234 (51)

**Comment by atom0s** [comment]
His info in the database reads as:
http://i.imgur.com/s8EtBcP.png

Which looks correct. (His Z is probably 234 from falling through the map etc.) However the zone looks like its not getting updated properly.

**Comment by atom0s** [comment]
This should now be fixed.
