### ISSUE TITLE
Reopening mission 7-2 "glitch"

### ISSUE THREAD

**Issue by warlord1352** [LegionDark/Issues#737]
**Date & Time**: 4p.m. 3/19/16

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Erinyes

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  THF99/DNC45

**NPC or Monster or item Name**: Karst

**Zone name & Coordinates (use `@where`)**: Bastok mines presidents office; X:104 Y:-20 Z:0 (0)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce The Issue**: Still tried talking to both gumbah and karst again and still no moving foward in this mission.

**Comment by Samikana** [comment]
Yours is probably not going to work bexause even if the mission is now functioning, your variable has still not been updated.

**Comment by TeoTwawki** [comment]
Check Iron Eater and the door (from iron eater's side) just in case, though I think we probably need to have a GM manually adjust you. Especially if you multi boxed part of the mission (you didn't fill in the template fully here)

**Comment by TeoTwawki** [comment]
Hi sami. near simultaneous post.

**Comment by Samikana** [comment]
Sup dawg :)

**Comment by warlord1352** [comment]
Oh sorry yes I did multibox when I originally did the mission and yeah I already tried talking to Iron Eater, but nothing happened.

**Comment by Samikana** [comment]
@warlord1352 can you log on now?  If not, tomorrow anywhere between 7-10PM EST?

**Comment by Samikana** [comment]
Gave player key item Letter From Werei (290).  MissionStatus variable was 1, needed to be 3.  Updated, player proceeded in the mission.
