### ISSUE TITLE
Gurfurlur the Menacing Seems to have perma hundred fist

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#738]
**Date & Time**: 3/19/2016 9:07 pm

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:Thf99/Nin49 

**NPC or Monster or item Name**: Gurgurlur The menacing

**Zone name & Coordinates (use `@where`)**: Halvung @ X: -59, Y: -23, Z: 3 (62)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**:Yes 

**Steps To Reproduce / any other info**: Fought Mob a few time either though he is a monk it seems he has 0 delay on melle attacks

**Comment by TeoTwawki** [comment]
I guess Gurf decided his missing skills was to much of a nerf and took matters into his own hands..or fists.

**Comment by Baucant** [comment]
lol. did you look at his delay though?

**Comment by TeoTwawki** [comment]
not yet but we'll get to it. its the sorta thing server has to come down to fix anyways so for now he's broke

**Comment by R3P0FFXI** [comment]
@Baucant this should be resolved in the next update

**Comment by TeoTwawki** [comment]
Along with every last mob with the same problem, and several related problems. Mass bug smackdown occurred. :rage3:
