### ISSUE TITLE
Missing Stats

### ISSUE THREAD

**Issue by piglorian** [LegionDark/Issues#74]
Date & Time: All the time
Frequency: Always
FFXI Client Version: 30150508_8
Character Name: Piglorian
Race: Taru
Main Job: BLM
Sub Job: WHM
Area & Coordinates: Anywhere
Party or Solo: Both
NPC Name: N/A
Monster Name: N/A
Steps To Reproduce The Issue

I bought a Memoria Sachet and checked @stats without any gear.  Then put the Memoria Sachet on and checked the stats again and they hadn't increased.  Probably just an item that isn't coded yet.

**Comment by R3P0FFXI** [comment]
Fixed should be pulled in Tuesday
