### ISSUE TITLE
Indrik does no TP moves

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#740]
**Date & Time**: 3/20/2016 10:11am

**FFXI Client Version (use `/ver`)**:30160203_0 

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:Thf99/Dnc49 

**NPC or Monster or item Name**: Indrik

**Zone name & Coordinates (use `@where`)**:Abyssea-Uleguerand @ X: 354.514, Y: 0.721, Z: -375.945
**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**:Yes

**Steps To Reproduce The Issue**: Fought mob multiple times and it never done a TP move

**Comment by TeoTwawki** [comment]
tons of everything is missing tp moves right now.

**Comment by R3P0FFXI** [comment]
@Baucant issue resolved in todays update
