### ISSUE TITLE
Goldsmith's Torque . Cannot be equipped.

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#741]
**Date & Time**:  3/20/16

**FFXI Client Version (use `/ver`)**: 30160203_0 

**Character Name**: Daedrik

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BLU99/RDM49

**NPC or Monster or item Name**:  Goldsmith's Torque

**Zone name & Coordinates (use `@where`)**:  Halvung @ X: -59, Y: -23, Z: 3 (62)

**ffxiah.com link (for items issues only)**:   http://www.ffxiah.com/item/10950/goldsm-torque

**Multi-boxing? (multiple clients on same connection)**:  yes

**Steps To Reproduce / any other info**:  Try and equip it.

**Comment by R3P0FFXI** [comment]
@Rohelius This is fixed in DSP and should allow to be equipped next time we pull DSP
