### ISSUE TITLE
Shinryuu BC crashed server.

### ISSUE THREAD

**Issue by Arotaka** [LegionDark/Issues#742]
**Date & Time**: 03/17/2016 - 17:28 CEST

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Akatora

**NPC or Monster or item Name**: Scholar Stone trade

**Zone name & Coordinates (use `@where`)**: Empyreal Paradox - X: 540, Y: -500, Z: -594 (71)

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Trading Scholar Stone to Transcendental Radiance in Empyreal Paradox to start the Shinryuu BC crashed the server. Did not lose pop item.

**Comment by TeoTwawki** [comment]
Fixed in trunk, won't be live till next maint.

**Comment by TeoTwawki** [comment]
P.s.
Shin's mobskills are likely all screwed up too. I haven't checked. IF they are, merry way early xmass on those lunars.
