### ISSUE TITLE
Ironclads are not attacking. Edit: All mobs with the same attack type

### ISSUE THREAD

**Issue by Arotaka** [LegionDark/Issues#743]
**Zone name**: Abyssea - Misareaux & Abyssea - Vunkerl

**Steps To Reproduce / any other info**:  Ironclad mobs do not attack/weaponskill. They just follow you around, doing nothing.

This happened on the two Ironclads in Misareaux and the one in Vunkerl. I assume it's a general family bug since the update.

**Comment by Arotaka** [comment]
The bee wonder mob does this too. Could be a general thing for mobs attacking this way.

**Comment by TeoTwawki** [comment]
@R3P0FFXI  Stumped. They are in skill list, flagged, assigned to these mobs, and the script has the command to enable them (in onMobSpawn).

**Comment by TeoTwawki** [comment]
mystery solved...was something I did in caffeine deprived near coma state..
