### ISSUE TITLE
Mage-type mobs are not going in to melee.

### ISSUE THREAD

**Issue by Arotaka** [LegionDark/Issues#744]
**NPC or Monster or item Name**: Mage-type mobs.

**Steps To Reproduce / any other info**: Mobs casting spells are staying '15~18 away, only casting spells, and not going in to melee. This is different behavior than before the update.

**Comment by TeoTwawki** [comment]
This is normal, dsp changed them to be allegedly more retail.

If this behavior is wrong, please tell them they were full of SH while I make popcorn for us so we can watch them argue it in comfort.
