### ISSUE TITLE
Observer mobs missing in Abyssea - Misareaux

### ISSUE THREAD

**Issue by Arotaka** [LegionDark/Issues#745]
**Date & Time**: 03/20/2016 - 17:50 CEST

**Character Name**: Akatora

**NPC or Monster or item Name**: Observer

**Zone name & Coordinates (use `@where`)**: Abyssea - Misareaux (X: -144, Y: -31, Z: 114 (3))

**Steps To Reproduce / any other info**: Every Observer mob (Detector type) is missing from Abyssea - Misareaux. This makes it impossible to get the pop item needed for Ironclad Observer and thus Ironclad Pulverizer.

**Comment by TeoTwawki** [comment]
@R3P0FFXI likely bad family ID in our custom group or pool table (whichever one thats in), I saw a lot of thsoe when we were converting the mobskills but didn't fix all of them because we wer eon skill list IDs at the time.

**Comment by R3P0FFXI** [comment]
Closing Duplicate ticket
