### ISSUE TITLE
shadow lord statue and xaddi gaunlets

### ISSUE THREAD

**Issue by benfolka** [LegionDark/Issues#746]
**Date & Time**: 21.02

**FFXI Client Version (use `/ver`)**: latest

**Character Name**: Clay

**Nation**: SAndoria

**Job(level)/Sub Job(level)**: 99 war/dnc

**NPC or Monster or item Name**:  shadow lord statue and xaddi gaunlets

**Zone name & Coordinates (use `@where`)**:  none

**ffxiah.com link (for items issues only)**:  http://legiondark.com/db/items/269/shadow_lord_statue
http://legiondark.com/db/items/28015/xaddi_gauntlets

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:  these  items "shadow lord statue and xaddi gaunlets" used to drop from some HNM now it is completely gone. the statue is also used as bahamut pop item.

**Comment by R3P0FFXI** [comment]
Looks like all Wyrm drops need to be readded to the wyrms we will take a care of this

**Comment by R3P0FFXI** [comment]
@benfolka fixed this should be in next maint
