### ISSUE TITLE
Auction House Rare item Issue

### ISSUE THREAD

**Issue by Baleoce** [LegionDark/Issues#747]
**Date & Time**: 18:40GMT - 20/03/16

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Baleoce

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: 62THF/31DNC

**NPC or Monster or item Name**: Peacock Charm

**Zone name & Coordinates (use `@where`)**: X:9 Y:1 Z:-30 (83). (Southern San d'Oria Auction House)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/13056/peacock-charm

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Tried to take a Peacock Charm I'd put up, off of the auction house in order to change the price. I forgot I already had one in my inventory. The in-game message stated: "You cannot possess more than one of that item". But then when I checked my sales status again, the item had been taken off, and was not in my inventory, as I can only hold one at a time. It wasn't in my received box either.

**Comment by TeoTwawki** [comment]
@R3P0FFXI @LegionDark/gm 
This needs reported to DSP, and should make a post warning the players on legion about it till a DSP fix can be pulled in. Said fix won't restore his item though, that would have to be done by GM command after mailing the existing one to himself or a mule.

**Comment by Samikana** [comment]
@Baleoce let me know a time you can log in so i can give you the item.

**Comment by Baleoce** [comment]
Thanks Sami, I'll log in now and I'll most likely be on tonight as well from 21:00GMT onwards.

**Comment by Baleoce** [comment]
Sorry to be a bother, but I think the person who was originally handling this query is no longer here. Could anyone help me out?

**Comment by Samikana** [comment]
I'm Sami.  I deleted my own Github account.

Closing issue, player got their Peacock Charm.

**Comment by TeoTwawki** [comment]
Someone make sure this is/was reported to DSP tracker with steps to reproduce it. Might already be there, I didn't look too tired about to pass out.
