### ISSUE TITLE
Transfer character: Increase craft request

### ISSUE THREAD

**Issue by voulo5** [LegionDark/Issues#748]
Was told by Halsey to report on github to request my Craft Skills to be carried over.
Sorry if this is the wrong spot, this is the only place I see I can post haha.
![img_20160314_203902](https://cloud.githubusercontent.com/assets/17954647/13911831/4bf36532-ef0c-11e5-9055-f65e65ee02d5.jpg)

**Comment by Samikana** [comment]
You need a template.
