### ISSUE TITLE
Nahtirah Hat will not equip on WHM

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#750]
**Date & Time**: 3/21/2016

**FFXI Client Version (use `/ver`)**:30160203_0 

**Character Name**: Dapunted

**Nation**: San d`Oria

**Job(level)/Sub Job(level)**:Whm99/Rdm40 

**NPC or Monster or item Name**: Nahtirah Hat  

**Zone name & Coordinates (use `@where`)**: All zones all coordinates

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/27775/nahtirah-hat

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: Attempted to equip item on whm would not equip

**Comment by R3P0FFXI** [comment]
Already fixed next update this should work
