### ISSUE TITLE
Logging in Issue

### ISSUE THREAD

**Issue by Eyeles** [LegionDark/Issues#751]
**Date & Time**:   21/03/2016 17:20 gmt+2

**FFXI Client Version (use `/ver`)**: current release

**Character Name**:  Vladmugger and Gorilla

**Nation**: Sandoria

**Job(level)/Sub Job(level)** 53bard/blm1:    99war/sam 

**NPC or Monster or item Name**: na

**Zone name & Coordinates (use `@where`)** N Sandoria : 

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)** Yes: 

**Steps To Reproduce / any other info**: NA

Since yesterday the 20th i have noticed these to characters are still logged in. could not relog after server crash and assumd this is the cause. i left it and went to bed assuming they will log out eventually. 
Now i still cant log in on legion site and on server via /sea ... command  it shows they are logged in.

**Comment by TeoTwawki** [comment]
Cleared stuck sessions from db, post back if you can now log in or not.

**Comment by Eyeles** [comment]
all sorted thanx Teo
