### ISSUE TITLE
Goldsmith's Torque Won't equip

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#752]
**Date & Time**: 3/21/2016 22:58 am 

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Baucant 

**Nation**: San d`Oria

**Job(level)/Sub Job(level)**:Thf99/Dnc49 

**NPC or Monster or item Name**: Goldsmith's Torque 

**Zone name & Coordinates (use `@where`)**: All zones All coordinates

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/10950/goldsm-torque

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Attempted to equip item. won't equip

**Comment by R3P0FFXI** [comment]
FIxed in DSP already will be fixed when we pull DSP next
