### ISSUE TITLE
Gurfurlur the menacing 15 min respawn

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#754]
**Date & Time**: 3/21/2016 3:45 PM

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:THF99/DNC49 

**NPC or Monster or item Name**: Gurfurlur the Menacing

**Zone name & Coordinates (use `@where`)**: Halvung @ X: -59, Y: -23, Z: 3

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**:yes 

**Steps To Reproduce / any other info**: Wating for 15 min and he spawned

**Comment by R3P0FFXI** [comment]
@Baucant resolved added scripted respawn timer to mob
