### ISSUE TITLE
Goldsmith's Torque~ Disapeared after 3/21/16 Maint.

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#756]
**Date & Time**:  3/21/16

**FFXI Client Version (use `/ver`)**:  30160203_0

**Character Name**: Daedrik

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  99BLU/49RDM

**NPC or Monster or item Name**:  Goldsmiths Torque

**Zone name & Coordinates (use `@where`)**:  @Gusgen~

**ffxiah.com link (for items issues only)**:  http://www.ffxiah.com/item/10950/goldsm-torque

**Multi-boxing? (multiple clients on same connection)**: yes 

**Steps To Reproduce / any other info**:   I was in Gusgen mines before server restart and upon re login the Goldsmiths Torque wasn't in my inv anymore..  

I checked to see if  I could equip before the maint/update, to check if it was going to work after it.

**Comment by R3P0FFXI** [comment]
Nothing was done to the torques with maint, it was fixed in DSP but not here yet

**Comment by TeoTwawki** [comment]
http://legiondark.com/forums/viewtopic.php?f=21&t=1394&p=4650#p4650

I just finished the maint that should fix this.
