### ISSUE TITLE
Some abyssea mobs not attacking. 

### ISSUE THREAD

**Issue by JayCrusnik** [LegionDark/Issues#757]
**Date & Time: *March 21, 2016*

**FFXI Client Version (use `/ver`): *Ver. 30160203_0*

**Character Name: *Jaycee*

**Nation: *Windurst*: 

**Job(level)/Sub Job(level): *Thief*

**NPC or Monster or item Name: *Ironclad Severer, Ironclad Cleaver*

**Zone name & Coordinates (use `@where`): *Abyssea Miseraux*

**ffxiah.com link (for items issues only): *N/A*

**Multi-boxing? (multiple clients on same connection): *Yes*

**Steps To Reproduce / any other info: *Tried Twice, mob would not fight back.*

**Comment by TeoTwawki** [comment]
Was this before http://legiondark.com/forums/viewtopic.php?t=1384&amp;sid=531d0d6baf047094ed628df33bb96a55 or after?

**Comment by Xenres** [comment]
Can confirm it's still occurring after the update. Appears to be all of the ironclads

**Comment by TeoTwawki** [comment]
Those ironclads are conspiring to make me flip tables. :goberserk: 

Those and the Gallu in Legion should have  had their melee specials working after that update. The others I expected to remain busted for now.

**Comment by JayCrusnik** [comment]
It was after

**Comment by TeoTwawki** [comment]
open new issues if any mobs still fail to melee
