### ISSUE TITLE
Absolute virtue does not spawn

### ISSUE THREAD

**Issue by benfolka** [LegionDark/Issues#759]
**Date & Time**: 08.15

**FFXI Client Version (use `/ver`)**: latest

**Character Name**: Clay

**Nation**: sandoria

**Job(level)/Sub Job(level)**:  99 war/dnc

**NPC or Monster or item Name**: Absolute virtue

**Zone name & Coordinates (use `@where`)**: 461.266, Y: -1.643, Z: -580 al'taieu

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: Absolute virtue does not spawn after jailer of love is killed

**Comment by R3P0FFXI** [comment]
AV Spawns just fine, its not 100% spawn if i remember correctly on this server

**Comment by benfolka** [comment]
altough you closed my ticket, i am guessing there is really a bug. It never spawns ...
Could you please check it.
