### ISSUE TITLE
Gulool Ja Ja Trial kill not registered.

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#76]
**Date & Time**:  6/07/2015
**Frequency**: Happened once
**FFXI Client Version**: 30150508_8
**Character Name**: Daedrik
**Race**: Elvaan
**Main Job**: PLD
**Sub Job**: RDM
**Area & Coordinates**: Mamook Gulool Ja Ja Spawn E-8
**Party or Solo**: Party
**NPC Name**:  ~~
**Monster Name**: Gulool Ja Ja
**Steps To Reproduce The Issue**: Kill Gulool Ja Ja while active trial Burtgang 95-99/1  Screeshots~
![daedrik_2015 06 07_200449](https://cloud.githubusercontent.com/assets/12631024/8027774/28cd6efe-0d53-11e5-8117-232c9635cbeb.png)
![daedrik_2015 06 07_200506](https://cloud.githubusercontent.com/assets/12631024/8027775/2f54b070-0d53-11e5-865b-84079feb3332.png)

**Comment by Loki79** [comment]
@TeoTwawki is working on un-fucking these trials currently.  On a side note i do want to say if you killed in Besieged it will no count for the trials.

**Comment by itachioax** [comment]
it was in mamook, i was with him

**Comment by Rohelius** [comment]
yep, was in Mamook past the gate. i only checked trial after i @homepointed.

**Comment by TeoTwawki** [comment]
Did you have the weapon equipped when the killing blow was delivered?

**Comment by Rohelius** [comment]
Sorry for late response. Hardly had time to play this week.  I equipped  the weapon at 10% and Itachi can attest for that.

I had another go at it Yesterday around 7PM and it did it again this time i took a pic of me holding Burtgang while fighting it to make sure there isn't a doubt about anything, And it did not register again.
![daedrik_2015 06 14_192624](https://cloud.githubusercontent.com/assets/12631024/8170849/684067ec-1368-11e5-8fe9-ffa417727aca.png)
Thats before it died (clearly holding weapon)
This is after.  
![daedrik_2015 06 14_192735](https://cloud.githubusercontent.com/assets/12631024/8170874/9bbf6b54-1368-11e5-9de3-1b81b14448a9.png)

**Comment by Rohelius** [comment]
Also if i may add it on here. The mobs (Hydra & Gulool) felt more buffed then last time i killed them.

Took me and Ita almost an hour to get it to under 40%% then after people joined,  they had to go TP on other mobs because they just couldn't Hit the thing at all. 
I was hitting decently enough when i had full ilvl100 and 119 sword. but accuracy for Hydra and Gulool fell if i removed some of those 100 pieces for -PDT gear. 

I Dont know if it got the King Behemot treatment and just got buffed by mistake but it was a noticeable difference for me and Itachi( Whos ranged attacks also where missing quite a bit~)

**Comment by TeoTwawki** [comment]
Found and fixed the problem. Please send me a message on IRC or in game (normally prefer not to get tells for bugs, making an exception) to get your kills credited.

**Comment by TeoTwawki** [comment]
As for the others mobs being stronger, to my knowledge they haven't been touched.

**Comment by TeoTwawki** [comment]
Player credited, and bug squashed, so closing.

**Comment by TeoTwawki** [comment]
@Rohelius so you know loki's been looking into the issue with the other mobs already, says looks like they did get changed and weren't supposed to be. No need to open another issue for them he's already dealing with it.
