### ISSUE TITLE
Something wrong with my inventory

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#761]
**Date & Time**: 3/22/2016 9:16am

**FFXI Client Version (use `/ver`)**:30160203_0 

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:Thf99/Dnc49 

**NPC or Monster or item Name**: Numerous items Soil geode and Kindred crest was most recent

**Zone name & Coordinates (use `@where`)**: Uleguerand range X:-24 Y:-175 Z:39 (82)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**:Yes 

**Steps To Reproduce / any other info**: Got items to fall off mob when I win the lot they hit the floor inv space is 59/80

**Comment by Rohelius** [comment]
I lost two items already one disappeared after update(GS Torque) the other during a trade with mule yesterday, Most of my members wont play until shit is fixed and I'm starting to feel the same way specially if my inventory starts losing not easy to get shit...

I really don't think the Troll king will just hand me another one when I give him R3po's explanation..

**Comment by TeoTwawki** [comment]
http://legiondark.com/forums/viewtopic.php?f=21&t=1394&p=4650#p4650

I just finished the maint that should fix this.

**Comment by Baucant** [comment]
Everything seems to be in order now. TY
