### ISSUE TITLE
No Shinryu spawn in bc fight

### ISSUE THREAD

**Issue by w3genesis** [LegionDark/Issues#762]
**Date & Time**: 3/22/2016 10:30 a.m. PST

**FFXI Client Version (use `/ver`)**: newest

**Character Name**: Gouken

**Nation**: Bastok

**Job(level)/Sub Job(level)**: Sam 99/ War 49

**NPC or Monster or item Name**: Shinryu

**Zone name & Coordinates (use `@where`)**: Abyssea Empyreal Paradox

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Traded Scholar Stone to enter Shinryu fight, but no Shinryu in BC. Scholar Stone was spent as normal. This is after the update on 21st.

**Comment by TeoTwawki** [comment]
@R3P0FFXI haha..hahahahaha _rips hair out_ hahahahahahaah!

(@LegionDark/gm  Give him back his stone while I comment out the part in the npc on live)

**Comment by w3genesis** [comment]
Thanks Teo ^^;

**Comment by R3P0FFXI** [comment]
@TeoTwawki ... /banghead

**Comment by TeoTwawki** [comment]
@w3genesis did you get your stone back already? assuming you did since you closed this. I have altered the NPC object to not steal any more stones till we fix shin.

**Comment by w3genesis** [comment]
Didn't get stone yet, but am in no hurry about it ^^ Will wait till a gm gets on.

**Comment by TeoTwawki** [comment]
Issue stays open till someone gets to you then

**Comment by w3genesis** [comment]
Okie~ Thanks Teo :D

**Comment by PikaFox** [comment]
Stone given to Catburglar, a mule of the poster.

**Comment by w3genesis** [comment]
Got stone. Thanks Tarot ^^
