### ISSUE TITLE
Bugged item drops from Voidwatch

### ISSUE THREAD

**Issue by Arotaka** [LegionDark/Issues#763]
**Zanhi Ring** http://legiondark.com/db/monsters/17568142/Krabimanjaro
**Benthos Grip** http://legiondark.com/db/monsters/17568142/Krabimanjaro
**Floestone** http://legiondark.com/db/monsters/17555901/Hahava
**Quartz Tathlum +1** http://legiondark.com/db/monsters/17224185/Murk-veined_Baneberry
**Damani Horn +1** http://legiondark.com/db/monsters/17167113/Pancimanci + http://legiondark.com/db/monsters/17281497/Holy_Moly

**Comment by TeoTwawki** [comment]
1: we know voidwatch is all manner of busted, have mentioned this multiple times
2: drops were changed, hell if I know which ones and to what
3: that template wasn't there just to make you waste time deleting it.
4. your punishment for the template is have r3 sicked on you. Have a nice day.

**Comment by Arotaka** [comment]
This is just an extension of what I did the other day for Abyssea. It hardly needs a template as it has nothing to do with anything I did ingame. I found drops listed as unknown, so they can be fixed. This was for R3 in the first place.

**Comment by TeoTwawki** [comment]
he's the one so insistent about that template though..and nothing was said to me about it. If he wanted this that would have been good info to include in the original post.

**Comment by TeoTwawki** [comment]
Its his prob - he can reopen.

**Comment by Arotaka** [comment]
Yeah, my bad, should have included more info to not cause extra work. I'll remember that next time.
