### ISSUE TITLE
my character transfer

### ISSUE THREAD

**Issue by macdaddy78** [LegionDark/Issues#764]
**Date & Time**:  3/23/2016 5:45 pm

**FFXI Client Version (use `/ver`)**:  30160203_0

**Character Name**:  mact

**Nation**:  bastok

**Job(level)/Sub Job(level)**:  99thf/49dnc

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:  when i read the transfer info i thought it said merits would transfer, and locker,satchel,sack,case.wardrobe all of those inv were totally empty.. im wondering if i was suppossed to get those things or not cause i thought for sure it said that i would..

**Comment by Samikana** [comment]
@R3P0FFXI please look into this when you have a moment to.  I spoke to the player and they're aware of all the items that transfer and don't transfer, and after speaking with them, I'm pretty certain this is a case of a corrupted transfer file.


@macdaddy78 If he does re-transfer your character, your current character will need to be deleted and level 1.  Your crafts will be back to 0 when re-transferred, and I'll have to set your crafts again.  Just a heads up in the event he does re-transfer you.

**Comment by macdaddy78** [comment]
ok, so i was spossed to get merits and those 75 or lower gear? and to fix it just have to transfer again

**Comment by macdaddy78** [comment]
so i submitted another transfer if you guys dont mind to redo that it hink i got all the info needed there even SS of crafts
