### ISSUE TITLE
Character transfer crafting levels

### ISSUE THREAD

**Issue by PresidentNixon** [LegionDark/Issues#767]
**Date & Time**: March 23, 2016 9:12PM EST

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Nixon

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BLU85/DNC75

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: Zeruhn Mines roaming atm

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Link to thread that contains my screenshot of crafts: http://legiondark.com/forums/viewtopic.php?f=37&t=1374

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
