### ISSUE TITLE
mact crafts

### ISSUE THREAD

**Issue by macdaddy78** [LegionDark/Issues#768]
**Date & Time**: 
3/23/2016

**FFXI Client Version (use `/ver`)**: 

**Character Name**:  mact

**Nation**:  bastok

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

http://i67.tinypic.com/hwbcs9.jpg

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
