### ISSUE TITLE
Khromasoul Bhurborlor- Loot Table duplicates/Missing items

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#769]
**Date & Time**: 3/23/16

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Daedrik

**Nation**: Bastok

**Job(level)/Sub Job(level)**:  BLU99/RDM49

**NPC or Monster or item Name **: Khromasoul Bhurborlor

**Zone name & Coordinates (use `@where`  **:  Mount Zhayolm @ X: 88, Y: -22.029, Z: 70

**ffxiah.com link (for items issues only)**:  

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 
Kill NM. 3 sets of oracles gloves, and some other items. 
No Tizona on Loot table.
Pages drop Tool reflects this.

**Comment by R3P0FFXI** [comment]
@Rohelius thanks ill look at this tonight

**Comment by R3P0FFXI** [comment]
@Rohelius fixed will take effect next maint
