### ISSUE TITLE
Crafting levels transfer

### ISSUE THREAD

**Issue by Bovice1** [LegionDark/Issues#770]
**Date & Time**: 6:00 PM EST

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Bovice

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: N/A

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: N/A

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Not sure if this is the proper place to post this but filing ticket to transfer crafting levels. It says expert next to all crafts, that's only because on ERA it defaults all crafts to that upon leveling them. 

![bovice_2016 03 20_015142](https://cloud.githubusercontent.com/assets/17997739/14032719/3d541dd2-f1eb-11e5-90da-31a2c0498930.png)

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
