### ISSUE TITLE
Trading shadow lord statues to pop Bahamut crashes server.

### ISSUE THREAD

**Issue by neojinx** [LegionDark/Issues#771]
**Date & Time**:  

03/24/2015 1527

**FFXI Client Version (use `/ver`)**: 

Version 30160203_0

**Character Name**:  

Neojin/Caffine

**Nation**: 

Bastok

**Job(level)/Sub Job(level)**: 

THF99/DNC49
WHM99/RDM49

**NPC or Monster or item Name**: 

Bahamut 
Shadow lord statue I
Shadow lord statue II
Shadow lord statue III

**Zone name & Coordinates (use `@where`)**:  

Riverne-Site B01 @ X: -114, Y: 0, Z: -632

**ffxiah.com link (for items issues only)**: 

http://www.ffxiah.com/item/269/s-lord-statue
http://www.ffxiah.com/item/279/s-lord-statue-ii
http://www.ffxiah.com/item/280/s-lord-statue-iii

**Multi-boxing? (multiple clients on same connection)**: 

Yes

**Steps To Reproduce / any other info**: 

Trade 3 shadow lord statues to bahamut pop and server crashed.

**Comment by TeoTwawki** [comment]
@Loki79 bahamut in general is busted on legion for now. this includes the quest fights with him as well as your custom version. they got added sooner than you expected.

**Comment by TeoTwawki** [comment]
@R3P0FFXI can you comment out the spawn npc's code real fast for now?

**Comment by R3P0FFXI** [comment]
@TeoTwawki this has been commented out can hotfix on my next commit

**Comment by TeoTwawki** [comment]
Custom version of Bahamut was disabled, and may make a future come return but many changes are coming - all new high level mobs on the way soon. In the meantime, the Darkstar version of Bahamut should at least work now. We'll open an issue with DSP if it doesn't.
