### ISSUE TITLE
Clothcraft Item to pass lvl 100 unobtainable

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#772]
**Date & Time**: 3/24/2016

**FFXI Client Version (use `/ver`)**:30160203_0 

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:THF(99)/DNC(49) 

**NPC or Monster or item Name**: sparkstrand

**Zone name & Coordinates (use `@where`)**: All zones all coordinates

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/2199/sparkstrand

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: According to Item Tool this item is not avaiable nor is the item it is crafted from. Without this item the swiftcape can not be crafted.

**Comment by Samikana** [comment]
This was meant to be implemented into a drop.  @R3P0FFXI tag you're it

**Comment by TeoTwawki** [comment]
Should also be craft-able from _Water Spider's Web_ but that's probably missing too.

**Comment by Baucant** [comment]
yes it should be craftable from water spider web but those aren't obtainable either

**Comment by R3P0FFXI** [comment]
Water Spider Web itemid 2198 to be added to Aqueduct Spider GroupID : 10849/10850

Looks like it should also drop from Legion mobs

Recipe to be added to DSP direct

NQ: Sparkstrand Thread
Main Craft: Clothcraft - (74)

Lightning Crystal
Water Spider's Web x2
NQ: Sparkstrand Thread x3

Main Craft: Clothcraft - (74) 
Key Item: Spinning

Lightning Crystal
Water Spider's Web x6
Spindle

**Comment by R3P0FFXI** [comment]
@Baucant  Added recipe to DSP, Added water spider web to Aqueduct Spiders will take effect next time we pull dsp. Drops will begin next maint.
