### ISSUE TITLE
Lower Delkfutt's Tower, Grounds Tome, Page 1 broken

### ISSUE THREAD

**Issue by Pharisee** [LegionDark/Issues#773]
**Date & Time**: 20160325 / 10:20AM JST

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Mik

**Nation**: Windurst

**Job(level)/Sub Job(level)**: PLD30/WAR15

**NPC or Monster or item Name**: Grounds Tome

**Zone name & Coordinates (use `@where`)**: X:456 Y:0 Z:-50 (146)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: 2

**Steps To Reproduce / any other info**: Lower Delkfutt's Tower, Grounds Tome, Page 1 is broken
Reads:
0 members of the bat family
0 members of the Goblin family
Target level range: 0~0

You can accept the page, but killing bats or goblins doesn't register towards the progress. When you interact with the Grounds Tome after accepting, you can select "Review current training regime", but it then just reverts you back to the "What will you do?" menu.

**Comment by Samikana** [comment]
Abandon the page and re-accept it.  This happens occasionally, and is a DSP issue.  If the problem continues please let me know as that will need to be reported to DSP separately if it broke.

**Comment by TeoTwawki** [comment]
Present me apologized for past me implementing tomes by copying the shit code DSP has in field manuals. present me would not have even touched it and it woudl still not exist at all, had I realized just how god awful it was written.

![Maybe I haven't been to Iceland because I'm busy dealing with YOUR crummy code.](http://imgs.xkcd.com/comics/future_self.png)

> _Maybe I haven't been to Iceland because I'm busy dealing with YOUR crummy code!_

**Comment by Pharisee** [comment]
@ghost It seems completely broken to me. I abandoned the page and re-accepted it multiple times with the same result.

@TeoTwawki No worries man. We appreciate the work you guys put in. Just reporting it, so yall know.

**Comment by R3P0FFXI** [comment]
@Pharisee this has changed multiple times with DSP revisions please report to DSP if there are still issues with books
