### ISSUE TITLE
Smithing Can't surpass lvl 100

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#774]
**Date & Time**: 3/24/2016 11:14pm

**FFXI Client Version (use `/ver`)**:30160203_0 

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:Thf(99)/Dnc(49) 

**NPC or Monster or item Name**: Ghemp & Gorkhali Kukri

**Zone name & Coordinates (use `@where`)**: Metalworks X:-112 Y:2 Z:27 (124)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/19788/gorkhali-kukri

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Attempted to trade item to NPC to surpass lvl 100 no responce. NPC does not say item need but since every previous items matched retail I assumed this on would too.

**Comment by Samikana** [comment]
Tag, you're it @R3P0FFXI

**Comment by R3P0FFXI** [comment]
@Baucant  Issue resolved in MUP2
