### ISSUE TITLE
Chelona Gloves Not showing on AH (Re-opened)

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#776]
**Date & Time:** 3/24/2016 11:39pm

**Frequency:** Anytime Item is placed on AH

**FFXI Client Version:**30160203_0

**Character Name:**Baucant

**Race:**Elvaan

**Nation:**San d`Oria

**Job(level)/Sub Job(level):**Thf(99)/Dnc(49)

**Area & Coordinates:** All areas all Corridinates

**NPC or Monster Name:**Auction House

**ffxiah.com link (for inventory items only):** http://www.ffxiah.com/item/10318/chelona-gloves

**Multi-boxing? (multiple clients on same connection):**yes

**Steps To Reproduce The Issue:**Check AH with command and physically visted Auction houses Item does not show on AH but was removed from inventory for sale.

**Comment by Samikana** [comment]
aH value is incorrect.  Should be 19.

**Comment by R3P0FFXI** [comment]
@Baucant Fixed will be in next time we update
