### ISSUE TITLE
Kitron Macarons (food) don't activate

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#777]
**Date & Time**: 3/24/2016 - 20:44

**FFXI Client Version (use `/ver`)**: 30160203

**Character Name**: Buttons

**Nation**: Windurst

**Job(level)/Sub Job(level)**: BLM(99)/WHM(49)

**NPC or Monster or item Name**: Kitron Macaron

**Zone name & Coordinates (use `@where`)**: Bastok Markets X:-203, Y:-6, Z:-59

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/5781/kitron-macaron

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Select item in inventory and try to activate it. No crafting buff is applied, and item remains in inventory.

Thanks for reading.

**Comment by TeoTwawki** [comment]
can't apply what doesn't exist yet

**Comment by Samikana** [comment]
Yeah, I told him to write a bug report.  @Midgardsormr you may want to submit it to DSP, not Legion.  Sorry if I was unspecific.

**Comment by Midgardsormr** [comment]
gotcha. thanks!!
