### ISSUE TITLE
Shofar/Behemoth Horn Unobtainable (Gjallarhorn) / Lootblox gives Moko Grass instead of B.Horn for x25 M.Silver

### ISSUE THREAD

**Issue by Hallabaloo4** [LegionDark/Issues#778]
**Date & Time**: 3/24/2016 9:29PM PST

**FFXI Client Version (use `/ver`)**: 30160302_0

**Character Name**: Halabaloo

**Nation**: Bastok

**Job(level)/Sub Job(level)**: All

**NPC or Monster or item Name**: Lootblox

**Zone name & Coordinates (use `@where`)**: All

**ffxiah.com link (for items issues only)**: 883

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Behemoth Horn doesn't drop from King Behemoth here, and the Lootblox will not give you a Behemoth Horn for x25 M.Silver's and instead gives you Moko Grass. Shofar also isn't stocked by the AH. Trying to make Gjallarhorn :[

Lootblox glitch: Trade Lootblox x25 M. Silver's and he'll give you a Moko Grass instead of a Behemoth horn.

**Comment by Baucant** [comment]
so what you saying is that it is obtainable but you don't want to do the work....i understand

**Comment by Hallabaloo4** [comment]
It was my understanding that using currency to purchase these items was to be a last resort. This item for the Gjallarhorn is the only item in the series of relics in which that last resort is the only option for purchasing it and i posted this because i wasn't sure if that was intended or not. Of course if you'd rather ridicule me for being active in posting things here on what i assume aren't intended instead of being helpful or a useful source of information, that's up to you. I'm going to entirely disregard what you said though and continue to hope an answer lands on this post instead of things like that.

**Comment by Hallabaloo4** [comment]
-Reposting a comment as trading 25 M.Silverpieces to Lootblox in Davoi gives you a Moko grass despite it even saying under "Trading Montiant Silverpieces" It says he'll give you a horn for x25. Goodbye my sweet 25 M.Silverpieces... *sheds tears*

**Comment by TeoTwawki** [comment]
@R3P0FFXI Gave player their horn that Lootblox conned them out of. Forward the moko grass thing to DSP, and then let me know what we're doing about those behemoth horns later.

**Comment by R3P0FFXI** [comment]
@TeoTwawki  Behemoth Horns have been added to drop pool and will go in on the next maint.
