### ISSUE TITLE
Adze's Cimine Discharge crashing clients

### ISSUE THREAD

**Issue by Arotaka** [LegionDark/Issues#779]
**Date & Time**: 08:20 CEST

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Akatora

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: MNK99/WAR49

**NPC or Monster or item Name**: Adze

**Zone name & Coordinates (use `@where`)**: Abyssea - Tahrongi (X-60, Y374, Z29, (105))

**Multi-boxing? (multiple clients on same connection)**:  Yes.

**Steps To Reproduce / any other info**:  Adze's WS move Cimine Discharge made 3 out of the 4 characters in the party crash. Broken move.

**Comment by TeoTwawki** [comment]
checking script..

**Comment by TeoTwawki** [comment]
I think its gotta be a non script issue. Nothing special in that script, just applying slow to you guys. Does it animate correctly to those of you not getting crashed, and do they actually crash or just r0? I want the error code if POL is actually crashing.

**Comment by Arotaka** [comment]
It froze the screens. Crashed both mine so I didn't see if it fired the animation normally. Will go check.

**Comment by TeoTwawki** [comment]
@LegionDark/gm Arotaka and I test for awhile lats night, experienced no crash from the skill. Something else present during the fight must have been the cause.

**Comment by TeoTwawki** [comment]
will reopen if I get new info

**Comment by TeoTwawki** [comment]
Determined to have most likely been caused by a player action that will be fixed in next maint.
