### ISSUE TITLE
Auroral Drape possibly crashing server

### ISSUE THREAD

**Issue by PresidentNixon** [LegionDark/Issues#780]
**Date & Time**: 3/25/2016 5:30AM EST

**FFXI Client Version (use `/ver`)**: 

**Character Name**: Nixon

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BLU99/WHM49

**NPC or Monster or item Name**: Taxim (only one tried on)

**Zone name & Coordinates (use `@where`)**: Gustav Tunnel

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Was fighting Taxim with some friends, tried to cast Auroral Drape on it and right as the spell was finishing the server crashed. I didn't realize it was me, but when I did the same thing on the next attempt it crashed at the same time. I don't want to try it any more to confirm so I am letting you know.

**Comment by TeoTwawki** [comment]
ARG! I swear to god I really did fix that before. re-disabling it..

**Comment by TeoTwawki** [comment]
and rerererefixed
