### ISSUE TITLE
Merchant not selling items he should

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#781]
**Date & Time**: 3/25/2016 10:40 AM

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Baucant

**Nation**: San d`Oria

**Job(level)/Sub Job(level)**:Thf(99)/Dnc(49) 

**NPC or Monster or item Name**: Denvihr

**Zone name & Coordinates (use `@where`)**:Port Bastok X:-51 Y:2 Z:-12 (26) 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/644/mythril-ore

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Checked NPC while Bastok is currently in first place Vendor does not sell

**Comment by R3P0FFXI** [comment]
@Baucant We are aware the merchants may not be selling correct items this is a DSP issue its why these items were added to the AH-Bot

**Comment by R3P0FFXI** [comment]
@Baucant Guild Shops have been replaced by standard NPC and have been verified correct, all NPC are selling correct items now
