### ISSUE TITLE
acution house

### ISSUE THREAD

**Issue by macdaddy78** [LegionDark/Issues#783]
**Date & Time**:  3/5/2016 12:40

**FFXI Client Version (use `/ver`)**: 

**Character Name**:  macd

**Nation**: 
bastok

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

just noticed aetosaur ledelsens (feet) are on the ah under legs just thought id let you all know..

**Comment by R3P0FFXI** [comment]
@macdaddy78 you need to fill out the full template your missing the FFXIah link so this really does nothing for us

**Comment by macdaddy78** [comment]
i dont really know the link i dont use ffxiah...
