### ISSUE TITLE
Unable to access Uriel Blade

### ISSUE THREAD

**Issue by neojinx** [LegionDark/Issues#784]
**Date** & Time:**

03/25/2015 1515

**FFXI Client Version (use /ver):**

Version 30160203_0

**Character Name:**

Neojin/Caffine

**Nation:**

Bastok

**Job(level)/Sub Job(level):**

BLU99/RDM49
WHM99/RDM49

**NPC or Monster or item Name:**

**Zone name & Coordinates (use @where):**

Bastok Mines X:0 Y:0 Z:2 (180) 

**ffxiah.com link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

Yes

**Steps To Reproduce / any other info:**

Have 440 sword skill and no access to uriel blade.

**Comment by TeoTwawki** [comment]
Fix incoming, some customization were accidentally lost in the update, due to it being crazy difficult to keep track of them in their previous form.

**Comment by TeoTwawki** [comment]
fix'd
