### ISSUE TITLE
Unable to access Unbridled Learning.

### ISSUE THREAD

**Issue by neojinx** [LegionDark/Issues#786]
**Date** & Time:**

03/25/2015 1650

**FFXI Client Version (use /ver):**

Version 30160203_0

**Character Name:**

Neojin/Caffine

**Nation:**

Bastok

**Job(level)/Sub Job(level):**

BLU99/RDM49
WHM99/RDM49

**NPC or Monster or item Name:**

**Zone name & Coordinates (use @where):**

Bastok Mines X:0 Y:0 Z:2 (180) 

**ffxiah.com link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

Yes

**Steps To Reproduce / any other info:**

Unable to access unbridled learning.

**Comment by TeoTwawki** [comment]
from same bug as #784 will be fixed soon

**Comment by TeoTwawki** [comment]
fix'd
