### ISSUE TITLE
Aetosaur Jerkin (NQ) not showing on AH

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#787]
**Date & Time**: 3/25/2016 11:37pm

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Baucant

**Nation**: San d`Oria

**Job(level)/Sub Job(level)**:Thf(99)/Dnc(49) 

**NPC or Monster or item Name**: Aetosaur Jerkin

**Zone name & Coordinates (use `@where`)**:All areas all coordinates 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/27889/aetosaur-jerkin

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Put item on AH search for I tem on AH item not showing on AH

**Comment by R3P0FFXI** [comment]
@Baucant Fixed will be in next time we update
