### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by Eyeles** [LegionDark/Issues#789]
Date & Time: 3/26/2016

FFXI Client Version (use /ver): current version

Character Name: Vladros 

Nation: Sandoria 

Job(level)/Sub Job(level): 99Blu/rdm 

NPC or Monster or item Name: NA

Zone name & Coordinates (use @where): aquaducts

ffxiah.com link (for items issues only): NA

Multi-boxing? (multiple clients on same connection): No

Steps To Reproduce / any other info: Server crashed and charracter remained logged on can not reconnect second time in a row it happens not sure if it is a bug

**Comment by R3P0FFXI** [comment]
@Eyeles Issue should be resolved
