### ISSUE TITLE
Can't sign up for goldsmithing or alchemy guilds.

### ISSUE THREAD

**Issue by RWBjr** [LegionDark/Issues#79]
**Date & Time**: 6/9/15 4:13 am
**Frequency**:
**FFXI Client Version**:30150508_8
**Character Name**:RWBjr
**Race**:Hume
**Main Job**:Monk
**Sub Job**:Dancer
**Area & Coordinates**: Bastok mines L-7 & Bastok market H-8
**Party or Solo**: Solo
**NPC Name**: Reinberta (Goldsmithing Guildmaster) Abd-al-Raziq (Alchemy Guildmaster)
**Monster Name**:
**Steps To Reproduce The Issue**:

**Comment by TeoTwawki** [comment]
Need more details on what exactly happens when you try- wrong dialogs, client crash, says you signed up but then after the same dialog repeats as if you never did, etc..Need to know exactly whats happens in order to help you.

**Comment by RWBjr** [comment]
With goldsmith in it repeats dialog on would you like to sign up for goldsmith in after choosing yes and it will give me  a crystal every time, with alchemy it never asks me if I want to sign up for alchemy and just repeats dialog

Sent from Yahoo Mail on Android

**Comment by RWBjr** [comment]
with goldsmithing it asks me if i want to join the guild and i accept joining the guild and then it asks me again as if i never accepted before giving me a crystal everytime, with alchemy it never gives me the choice to join the guild it just repeats "To master alchemy is to know the universe, and to know the universe requires time"
 


     On Tuesday, June 9, 2015 6:46 AM, TeoTwawki <notifications@github.com> wrote:
   

 Need more details on what exactly happens when you try- wrong dialogs, client crash, says you signed up but then after the same dialog repeats as if you never did, etc..Need to know exactly whats happens in order to help you.—

**Comment by RWBjr** [comment]
sorry didn't know if first post went thru cus i was on phone and thought i hit wrong button, sorry for repeats post.

**Comment by TeoTwawki** [comment]
I think I found and fixed the prob now, should working after next maint.

**Comment by RWBjr** [comment]
I joined the goldsmithing guild and alchemy guild, they seems to be working after the server maint.

**Comment by TeoTwawki** [comment]
Cool, closing issue then.
