### ISSUE TITLE
Aetosaur set

### ISSUE THREAD

**Issue by password100** [LegionDark/Issues#791]
**Date & Time**: 
11:00 AM PST

**FFXI Client Version (use `/ver`)**: 

30160203
**Character Name**: 
Monday

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99BLU/49NIN

**NPC or Monster or item Name**: 
Aetosaur Helm and Aetosaur Gloves

**Zone name & Coordinates (use `@where`)**: 
Sandoria X:120 Y:0 Z:-3

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/27746/aetosaur-helm and http://www.ffxiah.com/item/28036/aetosaur-gloves

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
crafted the headpiece and the hands last night and realized that stats weren't actually active and I'm assuming the whole set isn't. Not sure if intentionally not programmed or what but maybe i missed something. Just wanted to let ya know.

**Comment by Baucant** [comment]
I can confirm that feet don't work with this set item #28314 
http://www.ffxiah.com/item/28314/aeto-ledelsens

**Comment by Samikana** [comment]
@PikaFox this is you.

**Comment by Samikana** [comment]
Coded & given to @TeoTwawki.  Please re-open if the issue persists after the upcoming maintenance.

**Comment by Baucant** [comment]
@Samikana  I know this bug report was specific to feet head and gloves did you by chance check the body and legs too?

**Comment by Samikana** [comment]
@Baucant I re-did the entire set.
