### ISSUE TITLE
Urja Trousers Craft for Leatherworking lvl 100+ test fail

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#792]
**Date & Time**: 3/26/2016

**FFXI Client Version (use `/ver`)**:30160203_0 

**Character Name**: Baucant

**Nation**: San d`Oria

**Job(level)/Sub Job(level)**:THF(99)/DNC(49) 

**NPC or Monster or item Name**: Urja Trousers

**Zone name & Coordinates (use `@where`)**: All zones all coordinates

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/10577/urja-trousers

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Attempted craft with Terra Crystal as lvl 100 test items must be signed. Game states. Synthesisi Canceled. That combination of Materials cannot be synthesized. 
recipe used is Terra Crystal + Square Of Buffalo Leather x2 + Squamous Hide x2

**Comment by Samikana** [comment]
Coded & given to @TeoTwawki.  Please re-open if the issue persists after the upcoming maintenance.
