### ISSUE TITLE
BLU Job trail Fast cast (Erratic Flutter) [RE-opened]

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#793]
**Date & Time:** 2/29/2016 9:03pm

**Frequency:** always

**FFXI Client Version:**30160203_0

**Character Name:** Baucant

**Race:** Elvaan

**Nation:** Sandy

**Job:** Blu(99)War(49)

**Area & Coordinates:**All areas all coordinates

**NPC or Monster Name:** N/A

**ffxiah.com link (for inventory items only):** N/A

**Multi-boxing? (multiple clients on same connection):** yes and no

**Steps To Reproduce The Issue:** Set spell erratic flutter is suppose to give 8points towards Fast Cast Job trait. Does not give Job trait. attempted to pair with other still not recieving Job triat fast cast

**Comment by Raelious** [comment]
@TeoTwawki  Erractic Flutter now gives the job trait "Fast Cast" and is now working.
