### ISSUE TITLE
mact transfer and craft levels

### ISSUE THREAD

**Issue by macdaddy78** [LegionDark/Issues#794]
first i wanted to say thank you so much for redoing my transfer, but for some reason my storage isnt showing up i did put out furninshings and logged out and back in but didnt help.. also ive added a link for my crafts if anyone could do that..  
http://i67.tinypic.com/hwbcs9.jpg

**Date & Time**: 
3/27/2016 12:08

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**:  mact

**Nation**: bastok

**Job(level)/Sub Job(level)**: 
99thf/dnc

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:

**Comment by Samikana** [comment]
Can you log in within the next hour and a half?

**Comment by macdaddy78** [comment]
Sorry ive just now seen this..

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
