### ISSUE TITLE
Character: Croexi | Craft Skills | Import

### ISSUE THREAD

**Issue by lwrand** [LegionDark/Issues#795]
Hello,
 could you please add my "Craft Skills" as shown in the following screenshot ?

Character: **Croexi**
![croexi](https://cloud.githubusercontent.com/assets/8465871/14064888/d0a1ea40-f413-11e5-81c2-e0298b02503a.jpg)

Many thanks for your time,

**Comment by PikaFox** [comment]
Restored cooking to 100.
