### ISSUE TITLE
Character: Mensolai | Craft Skills | Import

### ISSUE THREAD

**Issue by lwrand** [LegionDark/Issues#796]
Hello,
could you please add my "Craft Skills" as shown in the following screenshot ?

Character: **Mensolai**
![mensolai](https://cloud.githubusercontent.com/assets/8465871/14064896/2447d0b0-f414-11e5-8299-be55e69c60c7.jpg)

Many thanks for your time,

**Comment by PikaFox** [comment]
Bonecraft restored to 100.
