### ISSUE TITLE
Character: Laf | Craft Skills | Import 

### ISSUE THREAD

**Issue by Lafarga** [LegionDark/Issues#797]
Hello,
could you please add my "Craft Skills" as shown in the following screenshot ?

Character: **Laf** (Renamed from Lafarga) **~ Please apply to the imported character Laf**
![lafarga_2016 03 27_234206](https://cloud.githubusercontent.com/assets/18100677/14065669/641ea86e-f476-11e5-9a27-2479b6c7524f.png)

Thank you

**Comment by Samikana** [comment]
Please fill out the template available [https://github.com/LegionDark/Issues](here).
