### ISSUE TITLE
Carver's Torque

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#798]
**Date & Time**: 3/27/2016 10:48am

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Baucant

**Nation**: San d`Oria

**Job(level)/Sub Job(level)**:Thf(99)/Dnc(49) 

**NPC or Monster or item Name**: Carver's Torque

**Zone name & Coordinates (use `@where`)**: Ifrit's Cauldron X:-284 Y:39 Z:124(172) 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/10948/carvers-torque

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Got the Item to drop from Mob invtory space was 62/80 won lot and item hit the floor

<img src="http://s18.postimg.org/xn2k8rjd5/img_20160327_104621.png">
http://s18.postimg.org/xn2k8rjd5/img_20160327_104621.png

**Comment by Samikana** [comment]
Most, if not all, of the torques are missing entries from DSP's database.  I coded these in the overhaul but all of the items coded have been acting weird and will likely need to be recoded and submitted to DSP directly.

**Comment by TeoTwawki** [comment]
@Samikana just to let you know r3 did this but we haven't pulled the change in yet (we're still playing catch up)

**Comment by R3P0FFXI** [comment]
So yeah @TeoTwawki was drunk when he adjusted the item basic file and totally missed the torque so ive now fixed his drunkeness, will be in next maint.

**Comment by TeoTwawki** [comment]
Don't listen to the addict guys, its all because of the coke @R3P0FFXI r3 is snorting and acid he's doing, he can't keep anything straight anymore he's so messed up.
