### ISSUE TITLE
Character: Zaraki | Craft Skills | Import

### ISSUE THREAD

**Issue by yogocoso** [LegionDark/Issues#799]
Hello,
could you please add my "Craft Skills" as shown in the following screenshot ?
please import woodworking

Character: Zaraki

![craft skill](https://cloud.githubusercontent.com/assets/18103937/14067251/01542296-f461-11e5-9969-dc2706b76f0a.png)

**Comment by Samikana** [comment]
Please fill out the template available [here](https://github.com/LegionDark/Issues) and resubmit your issue with it completed.
