### ISSUE TITLE
Perm Flee

### ISSUE THREAD

**Issue by daworstest** [LegionDark/Issues#8]
**Date & Time**:  1:30am est  5/26/2015
**Frequency**:once
**FFXi Client Version**:Unsure
**Character Name**:Yodokodo
**Race**:Mithra
**Main Job**:thf
**Sub Job**:nin
**Area & Coordinates (Type @where to get this info.)**: x-164 y-11 z77 Ghelsba outpost
**Party or Solo**:solo
**NPC Name**:none
**Monster Name**:3 orc type
**Steps To Reproduce The Issue**:Can not get flee off to try

**Comment by Genesis-Legion** [comment]
Is this perma flee for you you're asking about? or the monsters?

**Comment by TeoTwawki** [comment]
This will be fixed in next maint. Its a generic but rare timing bug, the server saved your status effects right when that one should have wrong off resulting in a zero duration flee.

**Comment by TeoTwawki** [comment]
Er..if you meant the mobs...They are coded to match your speed once they agro, its near impossible to outrun them and they don't give up easily. 

Sorry, I'm tired and should have waited till after I slept to respond to this.

**Comment by TeoTwawki** [comment]
@daworstest If you can clarify and there is a bug, I'll reopen this. Closing for now.
