### ISSUE TITLE
Homepoints opening for SOA areas by mistake

### ISSUE THREAD

**Issue by ffxi007** [LegionDark/Issues#80]
i have the kamihr drifts homepoint, no idea how i got it. 

may have been CoP or ZM messing up, or Sky hps.

also subzero smash crashes server when used by mobs. all the past zone ruczors are 1 hits and just die, however with some people having access to kamihr drifts the ruczor in there use it and it crashes the server.

User: Katiebelle

Add your damn template

**Comment by ffxi007** [comment]
tested the homepoints in ruaun gardens i got all of them 1-5

**Comment by R3P0FFXI** [comment]
Not using a proper template please apply the proper template the only reason I am not closing this directly is because you and I spoke earlier

**Comment by Loki79** [comment]
those mobs are not coded and if ppl continue to go there i will jail them.  Sub-Zero smash can be learned from SEDNA.  stay the hell out of areas we dont have opened.

**Comment by R3P0FFXI** [comment]
Bug Report opened with DSP to prevent this in the future

https://github.com/DarkstarProject/darkstar/issues/1589

**Comment by Loki79** [comment]
Teo resolved this.
