### ISSUE TITLE
Fight 3. 2

### ISSUE THREAD

**Issue by sakuraknight** [LegionDark/Issues#800]
**Date & Time**:  27/0316 21:31GMT

**FFXI Client Version (use `/ver`)**:  IDK

**Character Name**:  sakuraknight

**Nation**:  Bastoc

**Job(level)/Sub Job(level)**:  THF 100 / DNC 49

**NPC or Monster or item Name**: Boss fight 2.3  Nation

**Zone name & Coordinates (use `@where`)**: Blagas dias?

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  mp

**Steps To Reproduce / any other info**:  just need the push past please. Thank you

**Comment by R3P0FFXI** [comment]
@sakuraknight this template is filled out improperly we dont just push ppl past a fight for no reason
