### ISSUE TITLE
Friar Rush / Lord of Onzozo seemingly not popping

### ISSUE THREAD

**Issue by PresidentNixon** [LegionDark/Issues#801]
**Date & Time**: 10:11PM 3/27/2016

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Nixon

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BLU99/WHM49

**NPC or Monster or item Name**: Friar Rush, Lord of Onzozo

**Zone name & Coordinates (use `@where`)**: Den of Rancor  X: -86, Y: 16, Z: 2
Labyrinth of Onzozo  X: -44, Y: 14, Z: -58 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: We've been killing placeholders for the last several days and neither NM is popping, including for hours in a row after server restarts. Been told that they aren't even lottery here and they used to be up a lot, so I think their spawns may be broken.

**Comment by R3P0FFXI** [comment]
@PresidentNixon spawns are not broken they are lottery once the window opens
