### ISSUE TITLE
status on transfer

### ISSUE THREAD

**Issue by orangezag** [LegionDark/Issues#803]
**Date & Time**: 
Sun March 27  8:04pm (pst)

**FFXI Client Version (use `/ver`)**: 

30160203_0
**Character Name**: 

Anigavyllems

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
RDM1

**NPC or Monster or item Name**: 

none
**Zone name & Coordinates (use `@where`)**: 
Windurst Walls X-0 Y-0 Z-0 (201) Mog House

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
no made account for transfer but do not multi-box.

**Steps To Reproduce / any other info**: 

i noticed many accounts were transferred and i was curious if the delay was cause my files were corrupted or i did not do something correctly, if so please let me know what i need to do so i can correct the issue.

**Comment by Samikana** [comment]
Some got overlooked by accident.  I made repo aware and he'll look over them soon to see if they're a viable transfer or not.  Sorry for your wait.

**Comment by Samikana** [comment]
Closing this because your transfer is now being taken care of on the forums.
