### ISSUE TITLE
Character: Saga | Craft Skills |

### ISSUE THREAD

**Issue by yogocoso** [LegionDark/Issues#804]
Hello,
could you please add my "Craft Skills" as shown in the following screenshot ?
please import Smithing

Character: Saga

![craft skill saga](https://cloud.githubusercontent.com/assets/18103937/14086290/af8b6130-f524-11e5-9f3f-a13d3c0766e7.png)

kind regards

**Comment by Samikana** [comment]
Please fill out the template available [here](https://github.com/LegionDark/Issues) and resubmit your issue with it completed.
