### ISSUE TITLE
Craft skill import plz :)

### ISSUE THREAD

**Issue by Alilyamoon** [LegionDark/Issues#805]
March 28, 2016
Alilyamoon
Please import my cooking skill as shown in this screenshot :)
Thank you

![alilyamoon crafting skills](https://cloud.githubusercontent.com/assets/18125267/14088873/dfed9c00-f4ff-11e5-9084-cdd27740f161.jpg)

**Comment by Samikana** [comment]
Please fill out the template available [here](https://github.com/LegionDark/Issues) and resubmit your issue with it completed.
