### ISSUE TITLE
Unable to switch guilds to level up/trade craft item

### ISSUE THREAD

**Issue by Xenriv** [LegionDark/Issues#806]
**Date & Time**:  3/28/2015 19:00

**FFXI Client Version (use `/ver`)**:   30160203_0

**Character Name**:  Xenriv

**Nation**:  Bastok

**Job(level)/Sub Job(level)**:  BRD/WHM

**NPC or Monster or item Name**:  Woodworking Guild

**Zone name & Coordinates (use `@where`)**:  

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**:  N/A

**Comment by Baucant** [comment]
Which NPC are you talking to? the NPC  to join the guide (lvl up) and to join the guide union (trade craft items for guild points) are two different NPCs. Also the Guild union rep will not talk to you if you if your not a member.

**Comment by TeoTwawki** [comment]
There is also a known DSP bug where there is a cooldown at the wrong time/shouldn't exist if I remember right. Don't think anyone has reported exactly how to reproduce it for them. I could be wrong on either count but I don't see it in their tracker.

**Comment by R3P0FFXI** [comment]
@Xenriv this is handled in todays update
