### ISSUE TITLE
Chunk of Bismuth Ore  Not Obtainable.

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#807]
**Date & Time**:  3/28/16

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Daedrik

**Nation**: bastok

**Job(level)/Sub Job(level)**: 99blu/49rdm

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: N/A

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/4058/bismuth-ore

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**:  Looked at the Item Tool and while it does appear on the list, there isn't a mob that drops it like the other High lvl Mats. 

The retail Wiki points to Adoulin areas to mine it.

**Comment by R3P0FFXI** [comment]
@Rohelius Added to mobs will go in next maint
