### ISSUE TITLE
Craft skill import plz :)

### ISSUE THREAD

**Issue by Alilyamoon** [LegionDark/Issues#808]
**Date & Time**:   Mar 28/16  10:55pm est

**FFXI Client Version (use `/ver`)**:   30160203_0

**Character Name**:   Alilyamoon

**Nation**:   Sandoria

**Job(level)/Sub Job(level)**:   75thf/37dnc

**NPC or Monster or item Name**:   N/A

**Zone name & Coordinates (use `@where`)**:   N/A

**ffxiah.com link (for items issues only)**:   N/A

**Multi-boxing? (multiple clients on same connection)**:   No

**Steps To Reproduce / any other info**:   Import crafting skills please as per attached screenshot

Thanks 

![alilyamoon crafting skills](https://cloud.githubusercontent.com/assets/18125267/14096577/f2609d64-f537-11e5-8890-661582c88fd4.jpg)

**Comment by Samikana** [comment]
Can you be online between 6PM and 10PM EST?

**Comment by Alilyamoon** [comment]
yes

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
