### ISSUE TITLE
Character: Zaraki | Craft Skills | Import

### ISSUE THREAD

**Issue by yogocoso** [LegionDark/Issues#809]
Date & Time: Mar 29/16 

FFXI Client Version (use /ver): 30160203_0

Character Name: Zaraki

Nation: Bastok

Job(level)/Sub Job(level): 99Sam/49dnc

NPC or Monster or item Name: N/A

Zone name & Coordinates (use @where): N/A

ffxiah.com link (for items issues only): N/A

Multi-boxing? (multiple clients on same connection): yes

Steps To Reproduce / any other info: Import crafting skills woodworking please as per attached screenshot

**Steps To Reproduce / any other info**: 
![craft skill](https://cloud.githubusercontent.com/assets/18103937/14103878/70ce0de8-f5a2-11e5-9dcd-6a61972808c3.png)

**Comment by Samikana** [comment]
Can you be online between 6PM EST?

**Comment by yogocoso** [comment]
i can leave pg up, but i'm not at PC it's ok ?

**Comment by Samikana** [comment]
Yes, that's fine.

Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
