### ISSUE TITLE
Buffs disappearing when changing zones.

### ISSUE THREAD

**Issue by Vashelstampede** [LegionDark/Issues#81]
**Date & Time**:  6/9/2015 1:55PM EST
**Frequency**: First time
**FFXI Client Version**: 30150508_8
**Character Name**: Vashel
**Race**: Hume
**Main Job**: Scholar
**Sub Job**: Black Mage
**Area & Coordinates**: Zoning from Konschtat Highlands into Valkurm Dunes
**Party or Solo**: Solo
**NPC Name**: n/a
**Monster Name**: n/a
**Steps To Reproduce The Issue**: I had on a few buffs, most notable was an EXP buff from an Empress band. Zoned into Valkurm and all buffs were gone except Aquaveil. (Had Protect, Shell, Aquaveil, EXP buff and @regen)

**Comment by R3P0FFXI** [comment]
Known DSP issue is a byproduct of the ZMQ server split, sadly you will just have to reapply buffs
