### ISSUE TITLE
Character: Saga | Craft Skills |

### ISSUE THREAD

**Issue by yogocoso** [LegionDark/Issues#810]
Date & Time: Mar 29/16

FFXI Client Version (use /ver): 30160203_0

Character Name: Saga

Nation: Bastok

Job(level)/Sub Job(level): 46WHM

NPC or Monster or item Name: N/A

Zone name & Coordinates (use @where): N/A

ffxiah.com link (for items issues only): N/A

Multi-boxing? (multiple clients on same connection): yes

Steps To Reproduce / any other info: Import crafting skills Smithing please as per attached screenshot
![craft skill saga](https://cloud.githubusercontent.com/assets/18103937/14104059/65b09c4a-f5a3-11e5-85fd-b311749f61c0.png)
Steps To Reproduce / any other info:

**Comment by Samikana** [comment]
Can you be online between 6PM and 10PM est?

**Comment by yogocoso** [comment]
i can leave pg up, but i'm not at PC it's ok ?

**Comment by Samikana** [comment]
Yes

**Comment by yogocoso** [comment]
ok i'm leavig pg up, if you need is up now

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
