### ISSUE TITLE
ToAU 1 key item supplies package

### ISSUE THREAD

**Issue by gori123** [LegionDark/Issues#811]
**Date & Time**: 08:43 AM

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**:  Oggy

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: sam99/dnc49

**NPC or Monster or item Name**:  Naja Salaheem

**Zone name & Coordinates (use `@where`)**: i-10

**ffxiah.com link (for items issues only)**: SUPPLIES PACKAGE 	key item id 775 
https://wiki.dspt.info/index.php/Key_Item_IDs

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: server connection was slow, something went wrong with cutscene i could not get SUPPLIES PACKAGE key item. tried to talk again nothing happened also guards at staging points dont talk to me. i am missing SUPPLIES PACKAGE key item

**Comment by Samikana** [comment]
Can you be online between 6PM and 10PM EST?

**Comment by gori123** [comment]
sure i will just leave my character online. Thanks alot.

**Comment by Samikana** [comment]
The key item has been added to your character.  Please open another bug report if the problem persists.

**Comment by TeoTwawki** [comment]
It was not your connection it was the bug in DSP thats been in existence since June of last year. https://github.com/DarkstarProject/darkstar/pull/2960
