### ISSUE TITLE
Rock - Crafts Import

### ISSUE THREAD

**Issue by xrocksterx** [LegionDark/Issues#812]
**Date & Time**: 03-29-2016 06:00 AM PDT

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Rock

**Nation**: Windurst

**Job(level)/Sub Job(level)**: 99smn/49rdm

**NPC or Monster or item Name**: n/a

**Zone name & Coordinates (use `@where`)**: n/a

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)**: n/a

**Steps To Reproduce / any other info**: Crafts Import - (If limited to one: fishing)

![rock_crafts](https://cloud.githubusercontent.com/assets/18143653/14109220/df585be2-f575-11e5-9217-9d8bf4c860b6.jpg)

**Comment by Samikana** [comment]
Can you be online between 6PM and 10PM EST?

**Comment by xrocksterx** [comment]
Yeah, i will be online at 6 onwards

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
