### ISSUE TITLE
can i change  password?

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#813]
**Date & Time**: 3/29/2016

**FFXI Client Version (use `/ver`)**: 30160203

**Character Name**: Qigang

**Nation**: sand

**Job(level)/Sub Job(level)**: 99WAR/49SAM

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 
i want change qigang password plz

**Comment by Samikana** [comment]
You should be able to do this on the legiondark.com website by signing in
and choosing "change password".

**Comment by qiganggang** [comment]
Can you give me a link?

**Comment by Samikana** [comment]
Bruh.
I just did.
http://www.legiondark.com/
Log in and choose "change password".

**Comment by qiganggang** [comment]
is login play ID password?

**Comment by R3P0FFXI** [comment]
@qiganggang the login is what you use to login to the Legiondark FFXI server to play the game

**Comment by qiganggang** [comment]
is ok
