### ISSUE TITLE
Character: Cytra | Craft Skills | Import

### ISSUE THREAD

**Issue by Clent1986** [LegionDark/Issues#814]
Hello,
could you please add my "Craft Skills" as shown in the following screenshot ?

Character: Cytra
![clent](https://cloud.githubusercontent.com/assets/18147836/14115892/55a3f9b6-f5dd-11e5-96b6-ac32290c31b0.jpg)
Many thanks for your time,

**Comment by Samikana** [comment]
Please fill out the template available [here](https://github.com/LegionDark/Issues) and resubmit your issue with it completed.
