### ISSUE TITLE
SMN - I Can Hear A Rainbow quest

### ISSUE THREAD

**Issue by xrocksterx** [LegionDark/Issues#815]
**Date & Time**: 03-29-2016 17:00 PST

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Rock

**Nation**: Windurst

**Job(level)/Sub Job(level)**: 99smn/49rdm

**NPC or Monster or item Name**: House of the Hero, Carbuncle

**Zone name & Coordinates (use `@where`)**: Windurst Walls, X:-25 Y:-13 Z:261 (186)

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)**: yes. logged out alt. zoned rock. tried clicking the door again.

**Steps To Reproduce / any other info**: So basically I need the Carbuncle Avatar. To start off, I ported into Legion as 99smn. Walked up to the door as 99smn/49rdm with Carbuncle's Ruby in inventory to start the 'I Can Hear a Rainbow' quest. Clicked the door and received the questline for 'The Puppet Master'. This is the quest after completion of 'I Can Hear a Rainbow'. I then switched jobs to 75nin/37dnc and tried again. After that I logged out my alt, zoned Rock, still not the right quest.

**Comment by Samikana** [comment]
AFAIK you have to either go speak to the ??? or re-do the quest completely to get the summon.

**Comment by xrocksterx** [comment]
I tried speaking and trading the ruby to the ??? and nothing happens. My quest log shows the puppet master. Can you null that that quest so i can start over fresh?

**Comment by TeoTwawki** [comment]
@xrocksterx whats a good time of day for me to catch up with you in game? (in general - I'm not available in game atm)

**Comment by xrocksterx** [comment]
I'm usually in the game from 4pm - 1am PST

**Comment by TeoTwawki** [comment]
Really sorry I either never got back to you on this or forgot to come back and close the issue. I will look for you this week.

**Comment by TeoTwawki** [comment]
Have been unable to get in touch with player for months, closing.

If you come back and still need assistance, please open a new issue.
