### ISSUE TITLE
Crafting skills After transfer also Storage items issus

### ISSUE THREAD

**Issue by RenCross01** [LegionDark/Issues#816]
**Date & Time**: 2:23AM 3/30/2016
**FFXI Client Version (use `/ver`)**: 
**Character Name**: Snoww 
**Nation**: Windurst 
**Job(level)/Sub Job(level)**: 99 THF
**NPC or Monster or item Name**: N/A
**Zone name & Coordinates (use `@where`)**: N/A
**ffxiah.com link (for items issues only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: N/A
**Steps To Reproduce / any other info**: 
Just got my account transfer just need my crafting skill applied also i notice after the transfer none of the stuff in Storage was place because it was 0/0 so none of the items that was in there are there i added my Furnishing items was layout is there a way to get that fixed?
![craft skill cooking 85 fishing 34](https://cloud.githubusercontent.com/assets/18160259/14133612/a4800584-f61e-11e5-88dc-22b7489b3469.jpg)

**Comment by Samikana** [comment]
It's an issue with all transfers atm.

**Comment by Samikana** [comment]
Please log in within the next 2 hours or tell me what day you can log in within 6-10PM EST.

**Comment by TeoTwawki** [comment]
Next time use the bottom template field instead of jamming info at the top. Chances were against my even scrolling down before thinking it just wasn't filled in, and had that happened I might have closed it before you got help. And that would suck.

**Comment by TeoTwawki** [comment]
btw, usually just placing your furniture will increase the storage amount allowing you access to the items (they should still be there, just invisible). Anything _actually_ missing once storage levels are restored would have to either be a restricted/too high lv piece of gear, or doesn't exist in DSP or legion yet. Mass item loss would likely be some sort of a bug with the import if non of those things were  factor.

**Comment by RenCross01** [comment]
Saturday 4/2 7PM EST is the best day i can log in

**Comment by Samikana** [comment]
Sounds good @RenCross01 i'll try to be on.  If I can't be, just leave your chr on when you log off and I'll do it.

**Comment by Samikana** [comment]
@TeoTwawki I just editted their report and put the information at the bottom, because everytime I open their report, my first reaction is to close it.

**Comment by Samikana** [comment]
No reponse in more than 3 days.  Closing.
