### ISSUE TITLE
Character: Cytra | Craft Skills | Import

### ISSUE THREAD

**Issue by Clent1986** [LegionDark/Issues#817]
Date & Time: Mar 30/16

FFXI Client Version (use /ver): 30160203_0

Character Name: Cytra

Nation: Windurst

Job(level)/Sub Job(level): 99Rdm/49whm

NPC or Monster or item Name: N/A

Zone name & Coordinates (use @where): N/A

ffxiah.com link (for items issues only): N/A

Multi-boxing? (multiple clients on same connection): yes

Steps To Reproduce / any other info: Import crafting skills alchemy please as per attached screenshot

Steps To Reproduce / any other info: 

![55a3f9b6-f5dd-11e5-96b6-ac32290c31b0](https://cloud.githubusercontent.com/assets/18147836/14151152/d987f316-f6ac-11e5-87bf-28ab4e7b0555.jpg)

**Comment by Samikana** [comment]
Please log in within the next 2 hours, or otherwise let me know what day you can get on between 6-10PM

**Comment by Clent1986** [comment]
I can leave my pg up friday or saturday from 6 to 8 pm if it's ok for you ^^

**Comment by Samikana** [comment]
@LegionDark/gm The bug reports formatted like this need to be discussed on IRC.  I've labeled all open ones as "Escalation Needed".

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
