### ISSUE TITLE
Character: Zefiro | Craft Skills | Import

### ISSUE THREAD

**Issue by zefri88** [LegionDark/Issues#818]
Hello,
could you please import my Goldsmithing Skill ?

Character: Zefiro

![zefri](https://cloud.githubusercontent.com/assets/18176171/14156129/1a915fb0-f6c5-11e5-8ce7-be4880d4b51c.jpg)

Thanks a lot for your help.

**Comment by Samikana** [comment]
Please fill out the template available [here](https://github.com/LegionDark/Issues) and resubmit your issue with it completed.
