### ISSUE TITLE
Armor not working. Please fix

### ISSUE THREAD

**Issue by Raziel-IX** [LegionDark/Issues#819]
**Date & Time**: 3/30/2016 & 9:13pm

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Raziel

**Bastok**: 

**THF(99)/DNC(42)**: 

**NPC or Monster or item Name**: Aetosaur Gloves    and    Aetosaur ledelsens  not working. Can you please fix.  Thank you

**Zone name & Coordinates (use `@where`)**:  N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: N/A

**Comment by R3P0FFXI** [comment]
@Raziel-IX your missing the FFXI-AH info plus this is a duplicate ticket
