### ISSUE TITLE
Unable to spawn Chloris; Items needed to pop do not drop

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#82]
**Date & Time**:  6/10/15
**Frequency**: Always
**FFXI Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: NA
**Main Job**: NA
**Sub Job**: NA
**Area & Coordinates**: Abys Tahrongi
**Party or Solo**: NA
**NPC Name**: NA
**Monster Name**: Vetehinen/Halimede
**Steps To Reproduce The Issue**:

Neither of these NMs drop their pop items. Vet supposed to drop Tarnished Pincer, Hali Shriveled Wing. Both are supposed to be 100% drops.

http://ffxiclopedia.wikia.com/wiki/Vetehinen

http://ffxiclopedia.wikia.com/wiki/Halimede

**Comment by R3P0FFXI** [comment]
Will look at this tonight when I get home

**Comment by Loki79** [comment]
Fixed will be in next restart.

**Comment by Loki79** [comment]
update.  this is in your good to go.  was nobody in abyssea so bounced the server.
