### ISSUE TITLE
Server Transfer Craft Skills - Sansah

### ISSUE THREAD

**Issue by biancatechinc** [LegionDark/Issues#820]
**Date & Time**: March 31, 9:02 p.m.

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**:  Sansah

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: THF 75/ NIN37

Craft SKills 

![ffxi_2016 03 22_20 18 15](https://cloud.githubusercontent.com/assets/12072344/14177240/ef99e732-f787-11e5-933e-869fb776f09b.png)

**Comment by Samikana** [comment]
Incomplete template.
