### ISSUE TITLE
Character Import: Storage items missing. 

### ISSUE THREAD

**Issue by monicawebmage** [LegionDark/Issues#821]
**Date & Time**:  31st March 2016

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Zora

**Nation**: Windurst

**Job(level)/Sub Job(level)**: SCH95/

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: Port Sandoria X:80 Y:-16 z:-135 (165)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
I recently had my character imported from Retail - many thanks for this. After checking to see if the import was successful I noticed that none of the items that are in my Storage had been imported - it was 80/80 on Retail, now it is 0/0 on Legiondark. If it is possible to fix this issue, what is the best way for me to help you? If you need me to re do the export file I can do this by resubscribing to Retail FFXI. I assume I will need to delete the affected character? Or will you overwrite it? Let me know what the next steps should be.

Thanks,
Monica.

**Comment by R3P0FFXI** [comment]
Reseat your furniture it restores your sotrage

**Comment by monicawebmage** [comment]
Brilliant! Thanks so much! Was a bit worried when the game booted me off after I placed all furniture items, but after relogging all my items were restored.

Thanks,
Monica.
