### ISSUE TITLE
Character: Laf | Craft Skills | Import

### ISSUE THREAD

**Issue by Lafarga** [LegionDark/Issues#822]
**Date & Time**: 1/04/16 7:03AM

**FFXI Client Version (use `/ver`)**: n/a

**Character Name**: Laf

**Nation**: Bastok

**Job(level)/Sub Job(level)**: DRG 75/ WHM 37

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**:  Please import Craft skills
Woodworking 59
Goldsmithing 11
Clothcraft 53
Leathercraft 7
Bonecraft 45
Cooking 15

![lafarga_2016 03 27_234206](https://cloud.githubusercontent.com/assets/18100677/14190881/4e40c486-f7d8-11e5-851e-66488219b55a.png)

**Comment by PikaFox** [comment]
Restored players clothcraft to 53
