### ISSUE TITLE
Character: Zora | Craft Skills | Import

### ISSUE THREAD

**Issue by monicawebmage** [LegionDark/Issues#823]
**Date & Time**: 31st March 2016

**FFXI Client Version (use `/ver`)**: NA

**Character Name**: Zora

**Nation**: Windurst

**Job(level)/Sub Job(level)**: SCH95/

**NPC or Monster or item Name**: NA

**Zone name & Coordinates (use `@where`)**: NA

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: NA

**Steps To Reproduce / any other info**: 
Can you restore my cooking skill to 100 please?

![ffxi_2016 03 28_17 34 49](https://cloud.githubusercontent.com/assets/17324096/14192211/18e42af6-f794-11e5-853e-759b080c6b92.png)

**Comment by Samikana** [comment]
@LegionDark/gm The bug reports formatted like this need to be discussed on IRC.

**Comment by monicawebmage** [comment]
Hello,

Does this escalation affect the implementation of my skills being restored. Would you prefer to to submit my request somewhere else? Please let me know.

Thanks,
Monica.

**Comment by Samikana** [comment]
Yes, it does.  No, you don't need to submit your request anymore else.  Just wait.

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.

**Comment by monicawebmage** [comment]
Thanks for getting online to sort it.
