### ISSUE TITLE
New transfer craft import Plz

### ISSUE THREAD

**Issue by duggg** [LegionDark/Issues#824]
**Date & Time**:   Mar 31/16  6:20 EST

**FFXI Client Version (use `/ver`)**:   Ver. 30160203_0

**Character Name**:    Dugg

**Nation**:   Bastok

**Job(level)/Sub Job(level)**:   99 Nin

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**:   N/A

**ffxiah.com link (for items issues only)**:    N/A

**Multi-boxing? (multiple clients on same connection)**:    No

**Steps To Reproduce / any other info**:  

Requesting craft skill import to new transfer  Thank you 

![dugg craft skill](https://cloud.githubusercontent.com/assets/18199417/14192681/2a88edea-f76d-11e5-8b02-de3abc4e63fe.png)

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
