### ISSUE TITLE
Stormstrife craft transfer

### ISSUE THREAD

**Issue by Mizenkupa** [LegionDark/Issues#825]
**Date & Time**: 
3/31/2016

**FFXI Client Version (use `/ver`)**: 
30160203_0

**Character Name**: 
Stormstrife

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
75rd/37nin

**NPC or Monster or item Name**: 
n/a

**Zone name & Coordinates (use `@where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
not yet

**Steps To Reproduce / any other info**: 
Hello there, I'm a little unclear if this is the correct place to put this, sorry if it isn't. I had my character transfered yesterday and a friend told me to post a ticket to have my crafts transfered. So here's a link to my transfer thread with included screenshot: http://legiondark.com/forums/viewtopic.php?f=37&t=1435&sid=0fba85ed672adccf089213280b06acaa

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
