### ISSUE TITLE
Eddy crafts transfer

### ISSUE THREAD

**Issue by Eddy7** [LegionDark/Issues#826]
**Date & Time** 01/04/2016

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Eddy

**Nation**: Bastok

**Job(level)/Sub Job(level)**: THF75/DNC37

**NPC or Monster or item Name**: n/a

**Zone name & Coordinates (use `@where`)**: n/a

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Crafts skills transfer
![crafts](https://cloud.githubusercontent.com/assets/18200606/14194407/1d6088ce-f7a6-11e5-95ed-6ec66bb182a1.png)

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
