### ISSUE TITLE
Stormstrife 2-3 mission

### ISSUE THREAD

**Issue by Mizenkupa** [LegionDark/Issues#827]
2-3 Mission Fix Request Form
In-game name:Stormstrife
Issue: 2-3 Dragon fight
Nation affiliated with:Sandoria
Path taken:Bastok>Windurst

**Comment by Mizenkupa** [comment]
I copied the template from this topic:

http://legiondark.com/forums/viewtopic.php?f=67&t=1225

**Comment by TeoTwawki** [comment]
The fields and format are pre created here to help you, and you deleted what we here instead of filling them out..

**Comment by TeoTwawki** [comment]
That was for a post in the forums, which the staff then argued over and didn't update the post I guess -_-

@R3P0FFXI @Samikana YOU TWO DEAL WITH IT
