### ISSUE TITLE
Character Creation Bug?

### ISSUE THREAD

**Issue by Xenres** [LegionDark/Issues#828]
**Date & Time**: 4/1/16 1608 JST

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: N/A

**Nation**: N/A

**Job(level)/Sub Job(level)**: N/A

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: So I'm not sure if this is a bug or not, but I was trying to get a friend on here and when trying to create a character with the letters "noc" anywhere in the name together it'll just error out (3322). Clients are up to date and tested making characters with different names (without "noc" anywhere in the name) and those worked fine. Is it that this is just a blocked string of characters for some reason? If all else I'll just tell them to pick a new name, but was just curious. Thanks!

**Comment by TeoTwawki** [comment]
Square-Enix blocks certain names in the client like that, we dunno which ones or why, and nothing we can do about it during character creation.

**Comment by TeoTwawki** [comment]
p.s. My nephew tried to make an Elvaan named Monkeyboy and got same problem.

**Comment by Xenres** [comment]
Yeah I figured it was going to be something outside of what could probably reasonably be looked at, but I just wanted to see if anyone else had weird issues like that. What's even more strange is there's already 2 characters on the server with names containing "noc" (Sabnocke & Xenocide), but even the random ones we tried if those were in sequence like that none would go through.

**Comment by Xenres** [comment]
Thanks for the reply though Teo. Gonna go ahead and close this out.

**Comment by TeoTwawki** [comment]
Poke me on IRC if you can.

**Comment by Xenres** [comment]
On IRC now, but haven't used any of the functions so I have no idea what I'm doing haha
