### ISSUE TITLE
Stormstrife 2-3 mission

### ISSUE THREAD

**Issue by Mizenkupa** [LegionDark/Issues#829]
2-3 Mission Fix Request Form
In-game name:Stormstrife
Issue: 2-3 Dragon fight
Nation affiliated with:Sandoria
Path taken:Bastok>Windurst

This was closed for having no template, but the template is copied from: http://legiondark.com/forums/viewtopic.php?f=67&t=1225

**Comment by TeoTwawki** [comment]
Can you meet me in game in say, 5 min? I wanna test something.

**Comment by Mizenkupa** [comment]
I'm in game just send me a msg.

**Comment by TeoTwawki** [comment]
Handled

**Comment by TeoTwawki** [comment]
and old ass forum post sent to recycle bin
