### ISSUE TITLE
can not back to the past

### ISSUE THREAD

**Issue by zeos101** [LegionDark/Issues#83]
entered the maw in ron fields to do the dnc quest got the key item then romed around a bit and @homepoint now i can not get back please help if possible 

Thank you
Klang

**6-10-15 9:45pm EST**: 
**once**:
**20150508_8**:
**Klang**:
**Elvaan**:
**BLM**:
**RDM**:
**Ron Fields**:
**Solo**:
**NPC Name NA**:
**Monster Name NA**:
**went to both mas just says nothing happened**:

**Comment by Genesis-Legion** [comment]
You get teleported to a random past gate (batallia/rolanberry/Sauromugue) and to get back to the past you have to go back through the one you got teleported to. 
And to unlock gates in the present to go to the past you have to go through the one in the past first.

**Comment by zeos101** [comment]
i have tried the ones I can get to in the present and get nothing happens how do i get back to the past again to go threw the portal if it was my fist time there and did not get any telepoints?

**Comment by Genesis-Legion** [comment]
Have you tried to get to the one in Sauromuge Campaign? (through Garlaige Citadel) You should be able to get past the banishing gates with the weighted stones key item.

**Comment by TeoTwawki** [comment]
One of Battalia, Sauromuge, or Rollanberry, should always work.

**Comment by R3P0FFXI** [comment]
Have you attempted to go to the past using all 3 of these points?

**Comment by R3P0FFXI** [comment]
Is this still an issue please respond

**Comment by zeos101** [comment]
Sorry for the slow reply the issue is solved with help from the LS thank you again very much
