### ISSUE TITLE
Boyadha Tree Grounds Tome errors 

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#831]
**Date & Time**: 4/1/2016 - 09:38

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Buttons

**Nation**: Windurst

**Job(level)/Sub Job(level)**: BLU(68)/WHM(34)

**NPC or Monster or item Name**: Robber Crab

**Zone name & Coordinates (use `@where`)**: The Boyadha Tree

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Boyadha Tree Grounds Tome pages 2 & 3 are duplicates (save for the level descriptions). Also, regardless of which is picked, Robber Crabs do not count towards number of kills. 

Note: I don't recall whether pages were duplicated before, but i *do* recall being able to complete a "Mourioche & Robber Crab" page before successfully on other jobs... which were all prior to the last update. 

Thanks for reading.

**Comment by TeoTwawki** [comment]
pls spread the word to : tell all FoV/GoV issues to darkstar.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues

**Comment by R3P0FFXI** [comment]
@Midgardsormr New Darkstar updates pulled into server with massive Update Part 2 issues should be resolved
