### ISSUE TITLE
Luceiia crafting skill transfer

### ISSUE THREAD

**Issue by sasquatch32** [LegionDark/Issues#832]
**Date & Time**: 
04/01/2016 -- 12:16 pm

**FFXI Client Version (use `/ver`)**: 
30160203_0

**Character Name**: 
Luceiia

**Nation**: 
bastok

**Job(level)/Sub Job(level)**: 
rng99/nin49

**NPC or Monster or item Name**: 
none

**Zone name & Coordinates (use `@where`)**: 
current: bastok mines  90,0,-66

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
rarely, not currently

**Steps To Reproduce / any other info**: 
could i please get crafting skills transferred whenever there is time?
tyvm

luc
![luceiia_2016 03 27_195436](https://cloud.githubusercontent.com/assets/18217689/14214709/2dd6c4c6-f804-11e5-8e22-3f36ab74ebb3.png)

**Comment by Samikana** [comment]
Let me know what time you can get on within the next two days.

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
