### ISSUE TITLE
Black Curry Bun (NQ/+1) | Unable to craft | Cooking 100

### ISSUE THREAD

**Issue by lwrand** [LegionDark/Issues#833]
**Date & Time**: 04/02/2016 7:15 PM GMT+2

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Croexi

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 99(PLD)/49(DNC)

**NPC or Monster or item Name**: Black Curry Bun/Black Curry Bun +1

**Zone name & Coordinates (use `@where`)**: X:-15 Y:-3 Z:-61 (128)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/5764/b-curry-bun-1

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
Trying to craft "Black Curry Bun/Black Curry Bun +1" (http://www.ffxiah.com/item/5764/b-curry-bun-1) you get the message: "Synthesis canceled. That combination of materials cannot be synthesized". I have Cooking Skill to 100. 

Many Thanks,
Croex.

**Comment by Baucant** [comment]
I was told recently by R3 that with some recipes you have to add the ingredients in order based on their item ID. Which would be Fire crystal + San d`oria Flour, Flask of Olive oil, Black curry and bird egg. in that specific order. Have you tried that?

**Comment by lwrand** [comment]
Hi Baucant,
 I tried with the specific order but I still get the same message: 
![screen1](https://cloud.githubusercontent.com/assets/8465871/14231578/17672c54-f989-11e5-981f-d4ea5d64f468.jpg)

Croex,

**Comment by TeoTwawki** [comment]
The ingredients only have to be in order in the SQL table, not in game. Sounds like someone misunderstood something and passed it along in corrupted form.

**Comment by Baucant** [comment]
I checked the item via the Item database tool and the recipe is not listed.

**Comment by lwrand** [comment]
Let me know if I can help in any way ;)

**Comment by R3P0FFXI** [comment]
Added to custom file for now @TeoTwawki I will move to DSP later, will be fixed next maint in legion

**Comment by lwrand** [comment]
The recipe is now craftable but it "seems" that HQ2 (Black Curry Bun+1 x 6) and HQ3 (Black Curry Bun+1 x 8) can't be popped. I keep getting NQ (Black Curry Bun x 6) and HQ1 (Black Curry Bun x 8).

Thanks,
/Croex.
