### ISSUE TITLE
Sansah - Craft Transfer

### ISSUE THREAD

**Issue by biancatechinc** [LegionDark/Issues#834]
**Date & Time**: April 3, 2016 1:34am hongkong time

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Sansah

**Nation**: Sandy

**Job(level)/Sub Job(level)**: THF88 / DNC44

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: WINDY WOODS (G-11)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: NO

**Steps To Reproduce / any other info**: N/A
![ffxi_2016 03 22_20 18 15](https://cloud.githubusercontent.com/assets/12072344/14228015/7ecb2640-f93c-11e5-8074-619af5844f72.png)

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
