### ISSUE TITLE
this item low drop

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#835]
**Date & Time**: 04/03/2016

**FFXI Client Version (use `/ver`)**: 

**Character Name**: 
qigang

**Nation**: 

**Job(level)/Sub Job(level)**: war/sam

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
![qq 20160403135145](https://cloud.githubusercontent.com/assets/13742980/14230995/3ff56798-f9a3-11e5-9e5f-cd2623eeca42.jpg)
need Up drop

**Comment by R3P0FFXI** [comment]
@qiganggang No im not upping the drop rate at all
