### ISSUE TITLE
Haruspex Hat and Pigaches error

### ISSUE THREAD

**Issue by LegionTiger** [LegionDark/Issues#836]
**Date & Time**: 
2015/04/03

**FFXI Client Version (use `/ver`)**: 
30160203_0

**Character Name**: 
Tiger
Tigercub

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
THF99/DNC49
WHM99/RDM49

**NPC or Monster or item Name**: 
Haruspex Hat
Haruspex Pigaches

**Zone name & Coordinates (use `@where`)**: 
Windurst Woods
X:-35 Y:-1 Z:-117 (61)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/27750/haruspex-hat
http://www.ffxiah.com/item/28318/haru-pigaches

**Multi-boxing? (multiple clients on same connection)**: 
YES

**Steps To Reproduce / any other info**: 
Haruspex Hat can be synthed, but does not show in inventory. Tried the synth successfully twice, but no item obtained.

Haruspex Pigaches can be synthed, and also obtained. Yet, they cannot be equipped. Tried this on both listed Chars and Jobs (THF and WHM).

**Comment by LegionTiger** [comment]
Same goes for the Slops. Seems to be error with the complete set.

**Comment by Samikana** [comment]
Fixed.  Should be in next maint.
