### ISSUE TITLE
Steadfast shield

### ISSUE THREAD

**Issue by Minikay** [LegionDark/Issues#837]
**Date & Time**: 
4/3/2016 1:30pdt

**FFXI Client Version (use `/ver`)**: 
most recent one

**Character Name**: 
minikay

**Nation**: 
sandy

**Job(level)/Sub Job(level)**: 
99drk/49war

**NPC or Monster or item Name**: 
Steadfast shield

**Zone name & Coordinates (use `@where`)**: 
Gustav Tunnel
x: 36 y: 0 z: 185 (175)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/28663/steadfast-shield

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Shield could not be equipped. You still lose tp when attempting to equip it but it will not give any stats nor will it stay in the sub slot..

**Comment by Samikana** [comment]
Sounds like no MID

**Comment by Samikana** [comment]
Just equipped this shield without any issue.  Closing.

**Comment by Minikay** [comment]
Did you try it on drk? my pld can use the shield but drk cant

**Comment by Samikana** [comment]
I'll check in a bit
