### ISSUE TITLE
Sandorian Mission 8-2 Broken

### ISSUE THREAD

**Issue by jefferyrlc** [LegionDark/Issues#838]
**Date & Time**: April 4, 2016 10:00 AM EDT

**FFXI Client Version (use `/ver`)**: 30161203_0

**Character Name**: Jefferyrlc

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: WAR99/DNC49

**NPC or Monster or item Name**: ???

**Zone name & Coordinates (use `@where`)**: Temple of Uggalepih X:-13 Y:-17 Z:-151, X:-32 Y:-17 Z:-153, X:-66 Y:-17 Z:-153

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Start the sandy mission Lightbringer (8-2) and get past the prelate key doors. Upon examining the three ??? no key items are issued, making it impossible to spawn the NMs and complete the mission.

**Comment by jefferyrlc** [comment]
Bug report issued in error

**Comment by R3P0FFXI** [comment]
@jefferyrlc next time please close the issue as well then
