### ISSUE TITLE
Observers in Aby Mis not spawning. 

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#839]
**Date & Time**: Wednesday April 6th 2016

**FFXI Client Version (use `/ver`)**: (Don't remember exactly, updated client with the last server update)

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/rdm49

**NPC or Monster or item Name**: observers

**Zone name & Coordinates (use `@where`)**: Aby Miseraux x:-191 Y:-31 Z:123 (59).

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: Observers aren't spawning, the area is just empty around ironclad Severer

**Comment by R3P0FFXI** [comment]
@spectre99 this will be resolved next maint, fix has been pushed to DSP

**Comment by TeoTwawki** [comment]
@R3P0FFXI nope, not fixed, and its gonna hold up maint. You've got 2 of everything in the custom groups...Get with me on IRC

**Comment by R3P0FFXI** [comment]
This should be fixed next maint

**Comment by R3P0FFXI** [comment]
Fixed
