### ISSUE TITLE
Blu Merit Assimilation dont work here but in Darstar Team is seem ok

### ISSUE THREAD

**Issue by Squall-Bibi** [LegionDark/Issues#84]
**Date & Time**: 10/06/2015
**Frequency**: always
**FFXI Client Version**: 
**Character Name**: Squall
**Race**: Hume
**Main Job**: BLU
**Sub Job**: NIN
**Area & Coordinates**: all
**Party or Solo**: all
**NPC Name**:
**Monster Name**:
**Steps To Reproduce The Issue**:

On darkstar team have assimillation merit Blu works why not here ?

you can put in forum, merit work or dont work please ? is the same darkstar team or not ?

**Comment by TeoTwawki** [comment]
This server has nothing different than the DarkStar trunk for that job trait. At all.

**Comment by Squall-Bibi** [comment]
job trait ok but is merit for add point in blu magic spell dont works i take one assimilation and not have point added

**Comment by TeoTwawki** [comment]
And I'm telling you if its broke here its broke on DarkStar, because nobody has touched it.

**Comment by R3P0FFXI** [comment]
As Teo said this does not work in DSP it will not work here, this should be reported to DSP not to us.

**Comment by R3P0FFXI** [comment]
Testing and confirmed Assimilation does not increase the amount of points above 55 for Blue Mage this is a DSP bug and needs to be directed to DSP.

**Comment by R3P0FFXI** [comment]
Opened DSP Bug for issue

https://github.com/DarkstarProject/darkstar/issues/1587
