### ISSUE TITLE
Chateau de'Oraguille zoning problem.

### ISSUE THREAD

**Issue by Genesis-Legion** [LegionDark/Issues#840]
**Date & Time**: 3:50pm (cst)

**FFXI Client Version (use `/ver`)**: 3016203_0 

**Character Name**: Arielle

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: WHM70/RDM35

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: North Sandoria X:-2 Y:-2  Z:117 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Attempt to zone into Chateau de'Oraguille (Am on mission 6-1, Leaute's last wishes) and the screen goes black without ever actually zoning me, I can zone in on Genesis no problem.

**Comment by Samikana** [comment]
Fixed the issue by pushing them into Chateau d'Oraguille, they triggered a CS with Halver and then spoke to the door for the King and then had no issue zoning back in.

@TeoTwawki not sure if you want to explore this and see if anything is broken.  To me, it seems like a broken CS was trying to trigger and it fixed itself when his variable updated as he spoke to Halver/the door.

**Comment by TeoTwawki** [comment]
Its extremely like to have been a one off multibox glitch rather than an actual programming problem, or it'd be much more common. I occasionally have difficulties zoning if my nephew is on, its usually timing related.

**Comment by TeoTwawki** [comment]
Elaboration: packet gets lost/mangled, character times out while between zones, I wind up having to reset my session and force move character. its fairly rare.

**Comment by Samikana** [comment]
@TeoTwawki even if it's consistent?  I HP'd him and he tried again and it got him stuck.  He couldn't zone on Arielle until I sent him to Chateau d'Oraguille.

**Comment by TeoTwawki** [comment]
I literally just explained how that happens

**Comment by Samikana** [comment]
Re-open if issue persists later on.

**Comment by TeoTwawki** [comment]
If anyone gets it to happen without multi boxing, escalate and tag me.
