### ISSUE TITLE
Aetosaur Jerkin not recognized/unequipable

### ISSUE THREAD

**Issue by Xenriv** [LegionDark/Issues#842]
**Date & Time**:  4/6/2016

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**:  Xenriv

**Nation**: Bastok

**Job(level)/Sub Job(level)**:  THF/DNC

**NPC or Monster or item Name**:  None

**Zone name & Coordinates (use `@where`)**:  N/A

**ffxiah.com link (for items issues only)**:  http://www.ffxiah.com/item/27889/aetosaur-jerkin

**Multi-boxing? (multiple clients on same connection)**:  N/A

**Steps To Reproduce / any other info**:  Crafted Aetosaur Jerkin, Leathercraft skill 109, unable to equip it with appropriate job, no message saying I cannot. Also, when placed on AH, it is not listed anywhere to retrieve it or have potential buyers see it.  Thank you.

**Comment by Samikana** [comment]
@PikaFox I fixed the other one, this one is yours

**Comment by Samikana** [comment]
Fixed.
