### ISSUE TITLE
Werebats not spawning in Bostaunieux Oubliette

### ISSUE THREAD

**Issue by Samikana** [LegionDark/Issues#843]
**Date & Time**: 16/7/4

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Halsey

**Nation**: Bastok

**Job(level)/Sub Job(level)**: RDM/WHM

**NPC or Monster or item Name**: Werebat

**Zone name & Coordinates (use `@where`)**: -82 0 -58 (169)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: 

The Werebats in Bostaunieux Oubliette are not spawning on their own.  These monsters are a part of a page and currently, none of them spawn.  I've checked each spawn spot of the 10 that spawn in the zone.  They spawn fine with <code>@spawnmob</code> and function normally but they will not spawn on their own.  On the monster search on the main website, there is a notice at the top that says "this monster appears to be invalid or not implemented."  Killing the monster after being spawned with GM commands also counts for the page.  There are also supposed to be 48 in the zone, not 10.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/2860/commits/fa9023f4fd50728fa8bb597db56fb7b1fc3adf2c

**Comment by atom0s** [comment]
This appears to be fixed now. Werebats are appearing as they should.
