### ISSUE TITLE
Self casting (and Job ability) problem.

### ISSUE THREAD

**Issue by Genesis-Legion** [LegionDark/Issues#844]
**Date & Time**: 8:35AM cst

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Genesis, and Arielle

**Nation**: Bastok

**Job(level)/Sub Job(level)**: DRG99/SAM49, WHM93/RDM46

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: All

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Solo and Dualboxed

**Steps To Reproduce / any other info**: 

Talk to an NPC (tested on bastok mines NPC to the right of MH entrance, Also worked with the homepoint)
Attempt to use an ability or spell on yourself (ex: /ja Hasso Genesis) and it'll fail throwing an error as if you mistyped it. But if you were to replace your name with < me > it'll work fine.
The first command works with no problems until you talk to an NPC, after which is breaks then continues to work after you zone. 
This causes problems when you need to talk to an npc for buffs like in abyssea and your alt can't cast on themselves due to the way cureplease targets players.
Tested on windower and ashita with 0 plugins turned on

**Comment by Samikana** [comment]
Submit this to @DarkstarProject/Darkstar/issues.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/3009
