### ISSUE TITLE
Pandemonium_Warden taking down server

### ISSUE THREAD

**Issue by benfolka** [LegionDark/Issues#845]
**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 30160203

**Character Name**: Clay

**Nation**: sandoria

**Job(level)/Sub Job(level)**: 99rdm/49whm

**NPC or Monster or item Name**:  Pandemonium_Warden

**Zone name & Coordinates (use `@where`)**: Aydeewa Subterrane

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  yes

**Steps To Reproduce / any other info**: i was not there but i heard Pandemonium_Warden took down the server 4 times at GM event. This is just a reminder

**Comment by TeoTwawki** [comment]
Disabled last night so can't happen again while it waits to be repaired.
**Dev note:** one of the mobskills it uses places an invalid / corrupted status effect on players.

**Comment by TeoTwawki** [comment]
Closing this issue but pandy warden will be making a comeback after the reorganization of drops and high level targets is completed if not during it.
