### ISSUE TITLE
Abyssea La Theine Plateau 2 - Electric boogaloo

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#847]
**Date & Time**: Sunday April 10th 2016

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/Rdm49

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: Abyssea La Theine Plateau

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 

Mob name: Psychopomp
Family: Cropslights
problem: Wiki lists only 2 abilities Corpsle breath and Louring skies.  Mob however does different tp moves such as necrobane, hellsnap, hellclap.

mob name: Great wasp
Family: Bee
problem: not doing Frenzy pollen

Mob name: Luison
Family: Gnole
Problem: only does 2 tp moves Fevered pitch and Asuran claws.  Fought around 10, never did the following moves, call of the moon, plenilune embrace, nox blast, cacophony.

Mob Name: Crepuscule Puk
Family: Puk
Problem: 1. Doesn't do Crosswind 2. Does III Wind,  according to bg III Wind should only happen in Mamook and Besieged.

Mob Name: Poroggo Seducteur
Family: Poroggo
Problem: Only does water bomb and magic hammer.  Listed moves that it doesn't do are Frog cheer, Frog song, and Providence. 

Mob name: Crapaudy
Family: Frog
Problem: BG lists it as having no abilities,  yet it does water bomb and magic hammer.

Mob name: Irate Sheep
Family: Sheep
Problem: Didn't see the following abilities: Feeble bleat & sleep bleat.

Mob Name: Black Merino
Family: Sheep
Problem: Whenever they do Feeble bleat they hover in the air.

**Comment by R3P0FFXI** [comment]
@spectre99 if this is still an issue please let me know

**Comment by R3P0FFXI** [comment]
Lack of player response closing issue
