### ISSUE TITLE
Vadleany model wrong/family type

### ISSUE THREAD

**Issue by Samikana** [LegionDark/Issues#848]
**Date & Time**: 16/4/10 19:00

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Halsey

**Nation**: Bastok

**Job(level)/Sub Job(level)**: RDM DNC

**NPC or Monster or item Name**: Vadleany

**Zone name & Coordinates (use `@where`)**: -55 0 121 91

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Vadleany has Shaula's model.  Also using Scorpion TP moves when it's a Ladybug.

**Comment by TeoTwawki** [comment]
This should be fixed now. If its not, new issue..
