### ISSUE TITLE
Orison ft. Seals incorrect drop

### ISSUE THREAD

**Issue by Samikana** [LegionDark/Issues#849]
**Date & Time**: 16/10/4 20:53

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Halsey

**Nation**: Bastok

**Job(level)/Sub Job(level)**: RDM DNC

**NPC or Monster or item Name**: Quadav Guard, Quadav Transporter

**Zone name & Coordinates (use `@where`)**: NA

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/3192/orison-seal-ft

**Multi-boxing? (multiple clients on same connection)**: yep

**Steps To Reproduce / any other info**: Orison feet seals dropping off Quadav Guard/Transporters in the past.

**Comment by R3P0FFXI** [comment]
@Samikana resolved in massive update pt 2
