### ISSUE TITLE
Warp Spell quest error - Mean Machine

### ISSUE THREAD

**Issue by monicawebmage** [LegionDark/Issues#850]
**Date & Time**: 11th April 2016

**FFXI Client Version (use `/ver`)**: 30160203-0

**Character Name**: Zora

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: THF75/NIN37

**NPC or Monster or item Name**: Unlucky Rat

**Zone name & Coordinates (use `@where`)**: Bastok Metalworks(G-7)  X:-58 Y:2 Z:28 (71)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes and No. Have tried both.

**Steps To Reproduce / any other info**: 

Hello, I would like the option of completing this quest to obtain a Scroll of Warp for my Black Mage especially as there is none on the AH and I enjoy doing quests :) After executing the following, the quest did not complete:

1. Flagged the quest with the NPC
2. Obtained the required item (Slime Oil) by farming in Korroloka Tunnel
3. Returned to the NPC to trade in the item
4. The NPC does no accept the item to finish the quest and the quest is still flagged in my quest list.

Are you able to help with this?

Thanks,
Monica.

**Comment by Samikana** [comment]
This needs to be reported to DSP.

**Comment by monicawebmage** [comment]
Hello,

Just to let you know that I have just tried the quest again and it has worked.

**Comment by TeoTwawki** [comment]
Nothing changed on the servers end.

**Comment by Samikana** [comment]
Sounds like you were dual boxing and didn't log out and in the main
character before trying again.  That can cause issues.

**Comment by TeoTwawki** [comment]
Or had a full inventory and didn't notice. The way its coded in dsp fails to run the event, rather than running it but then not clearing quest and trying to give reward. I'll go fix that I guess so next time ppl realize whats wrong.

**Comment by TeoTwawki** [comment]
Oh nope, I'm wrong - there still would be a log message saying you can't obtain <item here> the way DSP has it. So zero way to say anything in code was involved here. ¯\\\_(ツ)\_/¯

**Comment by monicawebmage** [comment]
Ah OK, this must have happened then. Thanks for looking into it. I'm still
getting used to the interesting quirks of the server :)

**Comment by monicawebmage** [comment]
It sounds like it was the dual boxing thing. I did try getting the spell last night and it didn't work work so I thought I'd try again today when I'm less tired. It still didn't work at first but I think there was a quirk with the dual boxing like you mentioned.

Thanks for the assistance!
