### ISSUE TITLE
Post-Transfer Crafts Update

### ISSUE THREAD

**Issue by Noctis-LD** [LegionDark/Issues#851]
**Date & Time**: 4/11/16, 9:02AM EST 

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Noctis

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: 99 NIN

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: 
New transfer to the server and need crafting skills applied to character:
![image](https://cloud.githubusercontent.com/assets/18396158/14428161/da240eec-0032-11e6-9808-adba0b1cb427.png)

I'll try to leave the character online so you can do what you need to. Thanks in advance!

(Not sure how legible that screenshot will be judging from the preview.. looks clearer on the transfer thread on the LD forums: http://legiondark.com/forums/viewtopic.php?f=39&p=4938#p4938)

**Comment by Samikana** [comment]
Should be on between six and ten pm. Est.

**Comment by Noctis-LD** [comment]
Character should be online whenever you're able to get to him. Thanks again!

**Comment by Samikana** [comment]
Sorry, I'll need you to be present so you can verify that the crafts are the correct levels.

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
