### ISSUE TITLE
Empousa HP/MP pool

### ISSUE THREAD

**Issue by Samikana** [LegionDark/Issues#853]
**Date & Time**: 24:02

**FFXI Client Version (use `/ver`)**: 301060203_0

**Character Name**: Halsey

**Nation**: B

**Job(level)/Sub Job(level)**: RDM99DNC

**NPC or Monster or item Name**: Empousa

**Zone name & Coordinates (use `@where`)**: -619 -39 -13 40

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: y

**Steps To Reproduce / any other info**: 

Empousa has about 9~10k HP even though it's meant to be around ilvl 120ish iirc.  spawned it a bit and it seems to be doing normal DMG to a 119 player and using all its TP moves.  Seems like the only thing screwed up is it's HP and possibly its MP depending on what thats meant to be.  Respawn times seems to be normal too.

**Comment by R3P0FFXI** [comment]
Fixed in Update
