### ISSUE TITLE
i got my transfer and requesting craft skill, also my storage did not transfer

### ISSUE THREAD

**Issue by orangezag** [LegionDark/Issues#854]
**Date & Time**: 
1:30am PST 4/12/16

**FFXI Client Version (use `/ver`)**: 
Ver 30160203_0

**Character Name**: 
Nairas

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
99 (WHM) / --(SubJob)
**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 
Bastok Mines X:-8 Y:-3 Z:-51 (0)
**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

Nope no dual boxing
**Steps To Reproduce / any other info**: 
i am putting in request for craft skills and also i saw you were having issues with all transfers storage, i had this issue as well. just let me know what i need to do to help you correct this or if there is something i am doing wrong for my storage to not show up, thank you again for the time to help me.
![nairas_2016 03 31_134306](https://cloud.githubusercontent.com/assets/18108173/14454332/d161bdc4-004e-11e6-8029-794091ad77e7.png)

**Comment by Noctis-LD** [comment]
Have you zoned after placing your furnishings? That's what I had to do and then my items that were in storage appeared again.

**Comment by orangezag** [comment]
Ok I didn't zone.... thank you! It's there awesome possum!

**Comment by TeoTwawki** [comment]
If your items are now showing, please close your ticket

**Comment by orangezag** [comment]
Ok what about craft skills? Will they be applied if I close the ticket? I wasn't sure that's why I kept the ticket open. Or is there another place I need to go to post to get them? I was referred here to do that, thank you.

**Comment by TeoTwawki** [comment]
sorry didn't realize you had 2 things in one ticket. I wish ppl would stop doing the (you aren't the first, nor will you be the last).

**Comment by orangezag** [comment]
I'm sorry yea I wasn't sure about that either I didn't want to make 2 tickets and seem like I was overwealming you guys with tickets. But now I know in the future to do so if I ever come across an issue like this again. Would you like me to close this and make a new one for the crafts?

**Comment by TeoTwawki** [comment]
The irony is, we do get overwhelmed with dozens of reports for the same bug on multiple items when those get reported individually instead of 1 big list. :cry: 

You can keep this open. In the future rule of thumb: 
- 1 bug = 1 ticket each. 
- same basic bug (you have a list of object exhibiting same problem) = condense to a single ticket.

**Comment by orangezag** [comment]
Ok will do 😊 Again sorry and thank you for letting me know.

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
