### ISSUE TITLE
Unable to do Uriel blade and Glory slash in Jeuno Dynamis

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#855]
**Date & Time**: Tuesday April 12th, 2016

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/Rdm49

**NPC or Monster or item Name**: na

**Zone name & Coordinates (use `@where`)**: Dynamis Jeuno

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: While in Jeuno Dynamis the weaponskills Uriel blade and Glory Slash do not show up.

**Comment by R3P0FFXI** [comment]
@spectre99 if this is still an issue please let me know

**Comment by R3P0FFXI** [comment]
Lack of player response closing issue
