### ISSUE TITLE
i cant login

### ISSUE THREAD

**Issue by macdaddy78** [LegionDark/Issues#856]
fgf
**Date & Time**: 4/12/2016 7:35

**FFXI Client Version (use `/ver`)**: 3 something cant check cause i cant log on

**Character Name**: mact

**Nation**:  bastok

**Job(level)/Sub Job(level)**:  75drk

**NPC or Monster or item Name**: n/a

**Zone name & Coordinates (use `@where`)**: abt attowa 

**ffxiah.com link (for items issues only)**: n/a

**Multi-boxing? (multiple clients on same connection)** no: 

**Steps To Reproduce / any other info**:  cant log in

for some reason i cant type my password in when trying to login.using ashita it lets me type username but the password wont move at all..

**Comment by atom0s** [comment]
For anyone wondering about this with Ashita, the new boot loader I pushed hides the password. No characters are shown while typing it, but rest assure you are actually typing them. I can adjust it to show a * or something in the future.

**Comment by atom0s** [comment]
Just pushed another new version of the boot loader. This version's changelog is:

- Updated boot loader.
 - Passwords will now display * for each input letter/number.
 - Passwords will now restrict to only alpha numeric passwords for proper compatibility with DarkStars limitations.
