### ISSUE TITLE
Khromasoul Bhurborlor Bracelet

### ISSUE THREAD

**Issue by Goodjuice** [LegionDark/Issues#857]
**Date & Time**: 5:51AM GMT

**FFXI Client Version (use `/ver`)**: 30160203_0

**Character Name**: Goodjuice

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: PLD99/WAR49

**NPC or Monster or item Name**: Khromasoul Bhurborlor

**Zone name & Coordinates (use `@where`)**:  Mount Zhayolm -   X:86 Y:-22 Z:72 (46)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/2621/bblrs-vambrace

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Dropping two pop items for sarameya instead of its usual 1 pop 
![img_20160413_054640](https://cloud.githubusercontent.com/assets/18429106/14483181/28e273fc-013c-11e6-847c-3ce4c8a2f301.png)
item.

**Comment by Samikana** [comment]
As far as I'm concerned, the hands and legs dropping two times off him are intentional and have always been like that.  You'll have to confirm with @Loki79 as he was the one who coded these, but the pop item should not drop twice.

**Comment by R3P0FFXI** [comment]
Pop Item should not drop twice @Samikana I will deal with this

**Comment by Samikana** [comment]
That's what I said and ok

**Comment by R3P0FFXI** [comment]
@Goodjuice @Samikana No idea how this happened both Teo and myself looked at droplist all is fine

**Comment by TeoTwawki** [comment]
@Goodjuice @Samikana @R3P0FFXI if we find this happening on more mobs, with similar screenshot proof, let me know

**Comment by Goodjuice** [comment]
After update looks fine but before it wasn't dropping tizona and was dropped double pop item / enkidu legs and double oracle hands. Looks okay now however
