### ISSUE TITLE
Hippogryphs not using Fantod skill

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#858]
**Date & Time**: 
13 April 2016 - 17:20

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**: 
Buttons

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
BLU(99)/WHM(49)

**NPC or Monster or item Name**: 
Hippogryph family

**Zone name & Coordinates (use `@where`)**: 
Various (Riverne - Site B01 --X: 684 / Y: 0 / Z: -711)

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Build up a Hippogryph's TP so it uses special attacks. It uses Nihility Song, Jettatura, and Back Heel... but never Fantod. 

(I thought I was told the special attack would be fixed with the second part of the massive update, but I could be mistaken)

Thanks for reading.

**Comment by Samikana** [comment]
@TeoTwawki started a new rule that we only accept bug reports in Italian or Spanish.  :P

**Comment by Midgardsormr** [comment]
puedo escribir esto en español si así lo desea ^^

**Comment by TeoTwawki** [comment]
We haven't gotten Massive Update part 2 yet. Its been kind of getting broken into more frequent smaller pieces, but eventually you'll see me shove a big update out and call it that >.>

**Comment by TeoTwawki** [comment]
Will have this corrected very soon.

**Comment by TeoTwawki** [comment]
Some hippo's now use Fantod.It will be added to all of the rest of them next time the server restarts, so closing this out now.
