### ISSUE TITLE
shark wonder not using normal attacks

### ISSUE THREAD

**Issue by macdaddy78** [LegionDark/Issues#859]
**Date & Time**: 
4/13/16   11:55pm
**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**: 
mact

**Nation**: 
bastok

**Job(level)/Sub Job(level)**: 
99thf/dnc

**NPC or Monster or item Name**: 
NPC

**Zone name & Coordinates (use `@where`)**: 
valrum dunes, secret beach  x:-767 y:-4 z:161 (125)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 

mob used no normal attacks, only tp moves and one tp move "forgot the name" seemed to hit itself didnt seem normal to me.

**Comment by TeoTwawki** [comment]
@R3P0FFXI I totally called it this. "_Watch it hits itself in the face or some nonsense_".

@macdaddy78 we'll have a mini maint during the week to correct this.

**Comment by Samikana** [comment]
@TeoTwawki Can we make Shark chase its own tail?  Err...fin?

**Comment by TeoTwawki** [comment]
@macdaddy78 is he still hitting himself now that I fixed his melee?

**Comment by Samikana** [comment]
@TeoTwawki I'll check when I get home.
