### ISSUE TITLE
Hahava drop's 

### ISSUE THREAD

**Issue by djmanofsteel** [LegionDark/Issues#860]
**Date & Time**:4/14/2016 9:05am 

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Mano

**Nation**: BAstok

**Job(level)/Sub Job(level)**: War99/Sam49

**NPC or Monster or item Name**: Hahava

**Zone name & Coordinates (use `@where`)**: King Ranperre's Tomb  X:-58 Y:8 Z:155 (64)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/21366/floestone

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**:FloeStone [ammo] all races 
would drop into treasure pool with correct visual looks as it should. lot on it and it drops to the floor.
used monster tool: it is listed as [Unknown] on mob drop list.
used item search tool: it does not exsist under its name.

other item is.
Sailfi Belt +1[waist] all races
Item Id: 28428

only issue i see is it has unity ranking Attack +10~15 <-- this does not add anything to your stats.
i have other unity items with same stats and they add stats. 
this was not a major issue just wanted it check if possible.

**Comment by Samikana** [comment]
Repo I'll fix these items.

**Comment by R3P0FFXI** [comment]
Fixed will be in system during mini maint shortly
