### ISSUE TITLE
Unknown Items

### ISSUE THREAD

**Issue by djmanofsteel** [LegionDark/Issues#862]
**Date & Time**: 9/14/2016 11:21am

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Mano

**Nation**: Bastok

**Job(level)/Sub Job(level)**: War99/Sam49

**NPC or Monster or item Name**: multiple 

**Zone name & Coordinates (use `@where`)**:several

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/21359/quartz-tathlum-1

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 

Murk-Viened Baneberry
Pashow Marshlands X:552 Y:24 Z:491
Quartz Tathlum +1 [ammo] all races
shows up in monster tool as [Unknown] under NM's drop list 
used item tool: does not exsist under its name.
BAstok VW T3 NM

Pancimanci
West Sarutabaruta [S] @ X: 120, Y: -3.5, Z: -440
Damani Horn +1 [range] all races
shows up in monster tool as [Unknown] under NM's drop list 
used item tool: does not exsist under its name.
Windy VW T1 NM

Krabimanjaro
Ordelles Caves @ X: -112, Y: 0, Z: 230
Zanhi ring[finger] all races
shows up in monster tool as [Unknown] under NM's drop list 
used item tool: does not exsist under its name.

same mob

Benthos Grip[sub] all races
shows up in monster tool as [Unknown] under NM's drop list 
used item tool: does not exsist under its name.
Sandy VW  T2 NM

Ogbunabali
Maze of Shakhrami (D-8)
NM does not show up in Monster tool.
checked item name of drops thru Item tool.

Domesticator's Earring
used item tool: does not exsist under its name.
assume it is labeled as [Unknown] under mob drop list but could not find mob in Monster Tool.
Windy T2 VW NM

**Comment by R3P0FFXI** [comment]
Thanks @djmanofsteel Ill get this fixed tonight

**Comment by R3P0FFXI** [comment]
Item Basic done, @Samikana  please verify these items are fully coded what I did was to stop server crashes

**Comment by R3P0FFXI** [comment]
@Samikana Issue resolved
