### ISSUE TITLE
Too many rare/ex items drop and treasure pool auto sorts Itzp Scales

### ISSUE THREAD

**Issue by neojinx** [LegionDark/Issues#863]
**Date** & Time:**

04/14/2016 1600

**FFXI Client Version (use /ver):**

30160329_1

**Character Name:**

Neojin/Caffine

**Nation:**

Bastok

**Job(level)/Sub Job(level):**

THF99/DNC49
WHM99/RDM49

**NPC or Monster or item Name:**

Itzpapalotl

**Zone name & Coordinates (use @where):**

Abyssea - Attowha 436 20 -184 215

**ffxiah.com link (for items issues only):**

http://www.ffxiah.com/item/2962/itzpapa-scale

**Multi-boxing? (multiple clients on same connection):**

Yes

**Steps To Reproduce / any other info:**

With just enough luck (misfortune?) and high treasure hunter too many rare/ex items drop off Itzpapalotl and causes the scales to auto sort. I've lost 6 or more scales from this happening. Is there any way to bind the abyssea NMs empy weapons upgrade items in the treasure pool so they'll cause the other rare/ex items to auto sort instead? Or at least redistribute a couple of the weapons to other abyssea NMs? Thanks.

**Comment by R3P0FFXI** [comment]
@neojinx Unfortunately no, this is one of those rare instances there is just not much we can do, the weapons are not supposed to drop 3 at a time you should randomly get 1 weapon or none. The functionality in the script is not working like we had expected.
