### ISSUE TITLE
Sentinels Scherzo

### ISSUE THREAD

**Issue by Goodjuice** [LegionDark/Issues#864]
**Date & Time**: 6:15am GMT

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Bardjuice

**Nation**: Sand'Oria

**Job(level)/Sub Job(level)**: BRD99/WHM49

**NPC or Monster or item Name**: Sentinels Scherzo

**Zone name & Coordinates (use `@where`)**: All Dungeons

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/5078/sentinels-scherzo

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: 

Sentinel's scherzo seems to be acting like a mazurka style spell and will result in a "Can't cast in this area" Message when you attempt to use it in dungeons, it works in towns and outside area's fine however.
![img_20160415_061100](https://cloud.githubusercontent.com/assets/18429106/14552015/e8658da4-02d1-11e6-9998-8bcc658afcb8.png)
![img_20160415_061533](https://cloud.githubusercontent.com/assets/18429106/14552017/ec799804-02d1-11e6-9af8-d325353531cf.png)

**Comment by TeoTwawki** [comment]
Ok after investigating, it wouldn't matter if I correct the usability flag because the effect itself doesn't exist yet. Whoever implements it in Darkstar will have to fix that to test it, so I'm not bothering.
