### ISSUE TITLE
Grandgousier Health

### ISSUE THREAD

**Issue by Goodjuice** [LegionDark/Issues#865]
**Date & Time**: 9:23AM GMT

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Goodjuice

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: WAR99/SAM49

**NPC or Monster or item Name**: Grandgouiser

**Zone name & Coordinates (use `@where`)**: Abyssea-La'thiene: X:-396 Y:0 Z:-321

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: 

Grandgousier HP is way too low, is set to 10,000.

http://www.legiondark.com/db/monsters/17318439/Grandgousier
![img_20160415_092325](https://cloud.githubusercontent.com/assets/18429106/14555731/fb23e624-02eb-11e6-95bb-9e2a69ea0068.png)

**Comment by TeoTwawki** [comment]
Everything else in his ballpark has 60-90k HP :fearful:

**Comment by Samikana** [comment]
@TeoTwawki same with #853

**Comment by R3P0FFXI** [comment]
Fixed in update
