### ISSUE TITLE
April Fools Event

### ISSUE THREAD

**Issue by Genesis-Legion** [LegionDark/Issues#866]
**Date & Time**: 3:20 cst

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Genesis

**Nation**: Bastok

**Job(level)/Sub Job(level)**: WAR99/SAM49

**NPC or Monster or item Name**: blank

**Zone name & Coordinates (use `@where`)**: x7 y0 z-72 Ru Lude Gardens

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Nope

**Steps To Reproduce / any other info**: 
Was told to post here regarding april fools event, mistakenly did the screenshot on my alt character (Azezel)  and haven't picked it up on it, wanting to know if I can get it on my main (Genesis)

**Comment by TeoTwawki** [comment]
As discussed in game, this went by the name visible in the screenshots and is non transferable.
