### ISSUE TITLE
Pig event: Goodjuice

### ISSUE THREAD

**Issue by Goodjuice** [LegionDark/Issues#867]
**Date & Time**: 9:34 GMT

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Goodjuice

**Nation**: S

**Job(level)/Sub Job(level)**: BLM99/RDM49

**NPC or Monster or item Name**: Magian Mog_CJ

**Zone name & Coordinates (use `@where`)**: Ru'Lude Gardens X:3 Y:0 Z:-74 (250)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 
Feel pretty dumb writing a ticket out for this, but i didnt get my prize :cake: for the goblin event.
was told to post a ticket here regardless

**Comment by TeoTwawki** [comment]
I typo'd your name, so sorry. Next year this will be more automated, remove human error. Should be fixed now.

**Comment by Goodjuice** [comment]
fixed :+1:
