### ISSUE TITLE
Bastok Mission Bugged

### ISSUE THREAD

**Issue by luizsephsama** [LegionDark/Issues#869]
**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 

**Character Name**: 
Seph

**Nation**: 

**Job(level)/Sub Job(level)**: 
RDM/BLM

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
I was doing 2-3 mission from Bastok, I did the way Wind > Sand, finish the Wind and Talk to embassor in Sand to in the Chateau, I going inside Chateau talk to Halver but he said nothing to me, I leave the Chateau and try in again the Guard dont let me in again, my mission menu goes empty and can't do any mission now

[http://imgur.com/sbenZqo](url)

[http://imgur.com/zQYSHf3](url)

**Comment by Samikana** [comment]
@TeoTwawki this happened with another player, so this confirms that it's consistent.  I'm not going to update any variables since maintenances are happening frequently now, so this player will have to wait.

**Comment by TeoTwawki** [comment]
I wanna know the very last mission related NPC you spoke with was before it progression went off the rails.

**Comment by TeoTwawki** [comment]
I wanna know the very last mission related NPC you spoke with was before it progression went off the rails.

**Comment by TeoTwawki** [comment]
I wanna know the very last mission related NPC you spoke with was before it progression went off the rails.

Also bunch of template info missing: were you multi-boxing?

**Comment by TeoTwawki** [comment]
I wanna know the very last mission related NPC you spoke with was before it progression went off the rails.

Also bunch of template info missing: were you multi-boxing?

**Comment by TeoTwawki** [comment]
fucking github

**Comment by luizsephsama** [comment]
The Last NPC I talk was Halver, then I leave The Chateau and my mission menu bugged, never use multi-box, I dont even know how to use.

**Comment by luizsephsama** [comment]
I also try to get The 2-1 mission again and can't trade The Crystal with Cid, nothing happens

**Comment by luizsephsama** [comment]
all my missions reset, I try to in in Lower Delfkut Tower and CoP cs appear again -_-

**Comment by TeoTwawki** [comment]
sounds like you were hit with blob corruption, rather than an actual mission bug at that point. Going to have to restore it from backup.

**Comment by TeoTwawki** [comment]
Players missions now working normally.
