### ISSUE TITLE
Chains of Promathia 3-3 The Road forks.

### ISSUE THREAD

**Issue by Ryos1** [LegionDark/Issues#87]
**Date & Time**: 6/6/15-6/12/15
**Frequency**: Constant
**FFXI Client Version**:30150508_8
**Character Name**: Ryos
**Race**: Mithra
**Main Job**: THF
**Sub Job**: NIN
**Area & Coordinates**: Metalworks X: -12 Y: -10 Z: 0 (192)
**Party or Solo**:Solo
**NPC Name**: Cid
**Monster Name**: None
**Steps To Reproduce The Issue**:
1. Complete all cutscenes from Chains of Promathia Mission 3-3 (The Road Forks)
2. Follow up with the final cutscene at Cid. This is where i got stuck. Cid is not giving me the final Cutscene to complete the missions.
3. I have went back to all the NPC's in 3-3 the road forks to receive any missed cutscenes, though I am sure I didn't miss any of them. I also brought my Taru mule along for CoP as well and Taru didn't recieve any issues with these cut scenes.

**Comment by Loki79** [comment]
So the Taru got the completion and your main did not?

**Comment by Ryos1** [comment]
Correct

**Comment by Ryos1** [comment]
I noticed it when my main didn't get the cutscene for the next quest zoning into jueno, but my Taru did.

**Comment by R3P0FFXI** [comment]
See a GM in game will will complete the mission for you and give you any required KI

**Comment by TeoTwawki** [comment]
This is likely the dua-lboxing variable glitch again. Anytime multiple characters share the same socket, there is a chance one of them will have the code that changes/sets variables or add keyitem fails on that character while the other has everything work without issue. Its totally random whenever the server needs to act on multiple characters from same connection like that. Old timey DSP bug that isn't a high priority for them.

**Comment by R3P0FFXI** [comment]
Added Key Item:Mimeo Jewel to your character try again and see if it resolves your issue

**Comment by Ryos1** [comment]
Cid still does not complete my mission. I will go back and do the cutscenes in windy when i get home tonight

**Comment by Ryos1** [comment]
Okay, so after noticing that Mimeo Jewel was for the mountain climb. I went back to attowah Chasm clicked on the loose sand got my mimeo feather and the other KI needed to redo the cutscenes in windurst. 
Mimeo Feather
Second Mimeo Feather
Third Mimeo Feather

Return to Windurst Walls and talk to Yoran-Oran.
Go to Port Windurst and talk to Yujuju (M-6). You may need to speak with her twice. (after getting this cutscene finished client crashed. I logged back in and the key items i had gotten from the mountain climb vanished into mid air.)
Go to Windurst Waters at (G-8, Northern Map) and talk to Tosuka-Porika, inside the Right (East) Optistery.
Return to Windurst Walls and talk to Yoran-Oran again. You may need to speak with him twice.

I received all the cutscenes as intended after relogging even after the KI's vanished.

The Windurstian leg of the mission is now complete.
In order to complete the mission, talk to Cid in Bastok Metalworks. You may have to talk to him twice.
All cid says for me here is : Ah, its you. You remember what I asked you to do, right?

**Comment by R3P0FFXI** [comment]
Issue resolved per user

**Comment by Loki79** [comment]
@R3P0FFXI whats up with this?  Close if its done please or complete it.
