### ISSUE TITLE
Sirrush

### ISSUE THREAD

**Issue by Samikana** [LegionDark/Issues#870]
**Date & Time**: 23:19

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Halsey

**Nation**: B

**Job(level)/Sub Job(level)**: RDMDNC

**NPC or Monster or item Name**: Sirrush

**Zone name & Coordinates (use `@where`)**: @pos 404 16 -437 216

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yep

**Steps To Reproduce / any other info**: Sirrush has no ??? to trade the moltened skin to.  He used to be a timed spawn to avoid this but it looks like he doesn't do that either.

**Comment by Baucant** [comment]
his spawn is where sobek is in retail

**Comment by TeoTwawki** [comment]
All the IDs in abyssea have shifted, I gotta fix them in DSP

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
