### ISSUE TITLE
Keraunos

### ISSUE THREAD

**Issue by Goodjuice** [LegionDark/Issues#871]
**Date & Time**: 00:18 GMT

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Goodjuice

**Nation**: San'doria

**Job(level)/Sub Job(level)**: BLM99/RDM49

**NPC or Monster or item Name**: Keraunos

**Zone name & Coordinates (use `@where`)**: West Ronfaure X-71 Y:-50 Z:167 (69)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/21169/keraunos

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 
Stat's appear to be wrong on the staff unless Ngqoqwanb has some hidden augment i don't know about.

Initial testing done in West Ronfaure on level 0 Wild rabbits on Thundersday using fire spells. using the exact same nuking gear minus weapon changes.

Nqqoqwanb---------------------- Keraunos-----------------------No weapon
Fire 1275--------------------------Fire 935------------------------Fire 95
Fire II 2212-----------------------Fire II 1605--------------------Fire II 970
Fire III 3246----------------------Fire III 2344-------------------Fire III 1595
Fire IV 4715----------------------Fire IV 3395-------------------Fire IV 2494
Fire V 6191----------------------Fire V 4415--------------------Fire V 3398

**Comment by Samikana** [comment]
Keranous has better state than ngq so idk where you're getting this information from and I can't see your chart there for absolute shit it'd formatted weird

**Comment by Samikana** [comment]
![tmp_9846-screenshot_2016-04-18-09-28-111274347943](https://cloud.githubusercontent.com/assets/18128996/14605791/4c4f4314-0548-11e6-898a-0fd7af277b70.png)
![tmp_9846-screenshot_2016-04-18-09-27-45287238335](https://cloud.githubusercontent.com/assets/18128996/14605798/5182b4f6-0548-11e6-8649-11ffb352b516.png)

**Comment by Samikana** [comment]
I can check the actual sql when I get home as sometimes these don't show up right but other than that it's likely whatever fix I make is going to gimp them not make them better so I would take what you can yet but I will check.

**Comment by Goodjuice** [comment]
as you can see keraunos has the wrong values for magic attack at 28 and not 128.

**Comment by TeoTwawki** [comment]
> Keranous has better state than ngq so idk where you're getting this information from and I can't see your chart there for absolute shit it'd formatted weird

@Samikana his entire point was that the staff supposedly weaker was doing more damage, those were his raw damage numbers. And I just noticed in your screenshots one of them has magic attack stat listed twice, which shouldn't be causing this but is -_very_- odd...

**Comment by Samikana** [comment]
Teo I'll recode the staff mods from scratch when I get home and make sure
it doesn't have an entry in both legion and the regular files

**Comment by Samikana** [comment]
I didn't code this item, but when I saw that, I figured that it would stack
the magic attack not choose one over the other.  Regardless I'll look at it
and come to you if it doesn't fix it

**Comment by Goodjuice** [comment]
Its because ngqoq has magic attack+120 and it should be +18 so technically theres probably nothing wrong with karaunos, its just the nqoq is OP because it has way too much mab

**Comment by Samikana** [comment]
Legion uses custom stats on certain gear so it's hard to determine what is
intentional and what is not

**Comment by Genesis-Legion** [comment]
Recoded the staves, hopefully that fixes the problem.
