### ISSUE TITLE
Incorrect Loot Table On Ramponneau

### ISSUE THREAD

**Issue by Danyeul** [LegionDark/Issues#872]
**Date & Time**: 
April 17, 2016 -- 11:35PM PST

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**: 
Orange // Juice

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
THF99/WAR49, WHM99/RDM99

**NPC or Monster or item Name**: 
Ramponneau

**Zone name & Coordinates (use `@where`)**: 
West Sarutabaruta [S] @ X: 93.736, Y: -1.104, Z: -204.736 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yeeee

**Steps To Reproduce / any other info**: 
Ramponneau (lottery NM) has identical loot table to Abyssea-Tahrongi mob, Mictlantecuhtli, as well as his typical Summoning Belt drop.  Also, Mictlantecuhtli, is not supposed to drop Summoning Belt.

Ramponneau link -- http://www.legiondark.com/db/monsters/17166705/Ramponneau
Mictlantecuhtli link -- http://www.legiondark.com/db/monsters/16961933/Mictlantecuhtli

**Comment by R3P0FFXI** [comment]
@Danyeul mobs in the past are not coded, we will just be 0 out this loot pool

**Comment by R3P0FFXI** [comment]
@Danyeul this has been resolved in massive update pt 2 and will go in next maint
