### ISSUE TITLE
Pamun has Incorrect Crafting Ingredients

### ISSUE THREAD

**Issue by Danyeul** [LegionDark/Issues#873]
**Date & Time**: 
April 17, 2016 -- 11:35PM PST

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**: 
Orange // Juice

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
THF99/WAR49, WHM99/RDM99

**NPC or Monster or item Name**: 
Pamun -- http://www.legiondark.com/db/items/21006/pamun

**Zone name & Coordinates (use `@where`)**: 
N/A

**ffxiah.com link (for items issues only)**: 
https://www.bg-wiki.com/bg/Pamun

**Multi-boxing? (multiple clients on same connection)**: 
Yeeeeeeeeeeeeeeeezzir

**Steps To Reproduce / any other info**: 
Pamun in the database has the incorrect recipe, requiring a Scarletite Ingot instead of the Ormulu Ingot.

**Comment by Samikana** [comment]
i don't even know what to tag this.

 @R3P0FFXI was this intentional?  In the crafting master document the mats are what is listed on Bg-wiki, not what is listed for our server.

**Comment by R3P0FFXI** [comment]
@Samikana @Danyeul issue resolved in DSP when we pull updated DSP files this should eventually resolve itself, may or may not be included in Massive update Pt2
