### ISSUE TITLE
Relaxing Earring

### ISSUE THREAD

**Issue by Goodjuice** [LegionDark/Issues#874]
**Date & Time**: 11:50PM GMT

**FFXI Client Version (use `/ver`)**:  30160329_1

**Character Name**: Goodjuice

**Nation**: San'doria

**Job(level)/Sub Job(level)**: WAR99/THF49

**NPC or Monster or item Name**: Yurim

**Zone name & Coordinates (use `@where`)**: Tavnazian Safehold X82 Y-25 Z3 (254)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/14792/relaxing-earring

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: 
Upon triggering the quest and trading the required items to Yurim, a black chip and silver earring she will not accept them.
![img_20160418_115245](https://cloud.githubusercontent.com/assets/18429106/14601832/5c69f410-055c-11e6-9132-d4249174d9fc.png)

**Comment by R3P0FFXI** [comment]
@Goodjuice 

Quest
In the Name of Science
Needed:
Silver Earring
Black Chip
Luminian Tissue x5
Euvhi Organ x5

your missing things :)

**Comment by Samikana** [comment]
It looks like he has those items?  Idk, human error...

**Comment by R3P0FFXI** [comment]
@Samikana he was only trading 2 of the items not all 4
