### ISSUE TITLE
Need help recovering account!

### ISSUE THREAD

**Issue by Ascheriit00** [LegionDark/Issues#875]
**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 

**Character Name**: 
Gutzz

**Nation**: 
San'doria

**Job(level)/Sub Job(level)**: 
THF72/NIN36

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Trying to recover my account

**Comment by R3P0FFXI** [comment]
If you wish to request a password reset, 
or have lost login information:

Contact staff privately either in the forum or in IRC (not publicly in the IRC channel, a forum post, or on github) with your account name and the replacement password. 

If nobody is available when you look, open a ticket to remind us you need password help and we'll try to contact you, but do not post your old or new account info on github.

**Comment by Samikana** [comment]
No player response in 3 days or more.
