### ISSUE TITLE
Moongate Pass

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#876]
**Date & Time**: 3:08pm Tuesday, April 19th

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/rdm49

**NPC or Monster or item Name**: na

**Zone name & Coordinates (use `@where`)**: Ro'Maeve x:-278 y:-3 Z:-17 (243)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: Went through the moon gate during a full moon during 1-3am when the gate was open, found and touched the ??? for Moongate Pass key item, and nothing happened. Not sure if its glitched/bugged, or just not enabled.

**Comment by R3P0FFXI** [comment]
@spectre99 DSP issue not ours

**Comment by R3P0FFXI** [comment]
Issue resolved in previous maint
