### ISSUE TITLE
Aetosaur Evasion

### ISSUE THREAD

**Issue by Fizzld** [LegionDark/Issues#877]
**Date & Time**: 
April 19, 2016

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**: 
In Hiding

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
n/a

**NPC or Monster or item Name**: 
Aetosaur Helm/Jerkin/gloves/trousers/ledelsens

**Zone name & Coordinates (use `@where`)**: 
n/a

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/search/item?q=aetosaur

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
The aetosaur gear has its evasion+ coded as evasion skill, noticed the other day when I was comparing equipment.

**Comment by R3P0FFXI** [comment]
Working as Intended this is how Evasion works on DSP

**Comment by Samikana** [comment]
Repo I talked to Teo last night and this is coded using skill mod 108 not
68 which is the intended mod.
