### ISSUE TITLE
Revealer's Tunic - Crafted but cannot equip due to Su1

### ISSUE THREAD

**Issue by Xenriv** [LegionDark/Issues#878]
**Date & Time**:  Tuesday, April 19, 2016 11:50 PM EST

**FFXI Client Version (use `/ver`)**:  Current

**Character Name**:  Xenriv

**Nation**: Bastok

**Job(level)/Sub Job(level)**:  White Mage/Scholar

**NPC or Monster or item Name**:  Revealer's Tunic

**Zone name & Coordinates (use `@where`)**:  Winhurst Woods

**ffxiah.com link (for items issues only)**:  http://www.ffxiah.com/item/26885/revealers-tunic

**Multi-boxing? (multiple clients on same connection)**:  No

**Steps To Reproduce / any other info**:  Crafted 4x Revealer's Tunics, but I was unable to equip any of them on my 99WHM due to the Su1 (Superior Level 1) Job Point designation as the item name remained grayed out within the menu. 

Since we don't have job points on DSP, is this correctable/removable? There are other iLVL armor pieces and weapons (Blurred weapons/Sombra set...etc.)  that have the Su1/Su2 tag on them that may also need to be addressed, especially since we can make some of them or if the new crafting materials will be introduced in the next update. 

 I ended up placing all 4 on AH for sale.  Thanks in advance for your help.

**Comment by Samikana** [comment]
@TeoTwawki this is the issue I was running into and needed Lokis help

**Comment by R3P0FFXI** [comment]
@Samikana this makes 0 sense as Su1/2 isnt even coded in DSP these items should work as is

**Comment by Samikana** [comment]
K, you figure it out then and when you can't figure out what's wrong
because the items are coded correctly get back to me then

**Comment by R3P0FFXI** [comment]
@Samikana @TeoTwawki Talked to Max today he thinks this may be a client side limitation forcing su0/1/2 if the packets are known he thinks a really easy fix will be to hack the packet structure to make it work. @TeoTwawki thoughts?

**Comment by TeoTwawki** [comment]
My thoughts: 
¯\\\_(o_O)_/¯ 
"pls save me, @maxtherabbit!"

**Comment by maxtherabbit** [comment]
I may have made some progress, possibly have something tonight.

**Comment by R3P0FFXI** [comment]
@maxtherabbit thank you for the help

**Comment by maxtherabbit** [comment]
sorry guys I'm stuck

spoofing the 0x05 variant of the 0x63 packet was easy enough (this 
allows the use of the job point menu and shows maxed out job and 
capacity points) but unfortunately this was not enough to get the client 
to recognize a superiority level

once the client gets a 0x63 0x05 packet it sends the server a 0xC0 
packet which expects a series of 11 bitpacked 0x8D packets in response 
(another new packet not in DSP) - these packets tell the client which 
job points specifically have been purchased and I can only assume that's 
how the client evaluates superiority

spoofing those without some valid retail packets to go off is going to 
be pretty difficult

**Comment by maxtherabbit** [comment]
@xenriv did you attempt to make the tunic part of an equipment set and then equip the set? that may possibly bypass the limitation

another super hacky workaround would be to create a @ command that all players can use to equip items bypassing the client limitation

**Comment by R3P0FFXI** [comment]
@maxtherabbit I think were going to have to wait until the next free weekend to circle back to this. The Job Points menu also opens up T6 spells and such which would be a nice option in the future. I assume the 4 packets you mentioned in your post are the 4 which will need to be captured from retail for SP?

**Comment by maxtherabbit** [comment]
add this line to your char_stats.cpp before the }

 ref<uint8>(0x52) = PChar->GetMLevel() == 99 ? 2 : 0;

**Comment by R3P0FFXI** [comment]
@Xenriv SU1/2 Fix is live today with Massive Update part 2 and confirmed working.
