### ISSUE TITLE
Login Server Unavailable

### ISSUE THREAD

**Issue by neuromancerxi** [LegionDark/Issues#879]
**Date & Time**: 2016-04-20 0600
**FFXI Client Version (use `/ver`)**: N/A
**Character Name**: N/A
**Nation**: N/A
**Job(level)/Sub Job(level)**: N/A
**NPC or Monster or item Name**: N/A
**Zone name & Coordinates (use `@where`)**: N/A
**ffxiah.com link (for items issues only)**: N/A
**Multi-boxing? (multiple clients on same connection)**: N/A
**Steps To Reproduce / any other info**: Attempt to login using current client.

**Comment by R3P0FFXI** [comment]
hard crash issue resolved
