### ISSUE TITLE
Unable to spawn Wherwetrice

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#88]
**Date & Time**: 6/12/2015 6:00pm
**Frequency**: always
**FFXI Client Version**: 30150508_8
**Character Name**:Baucant
**Race**:Elvaan
**Main Job**: THF
**Sub Job**: DNC
**Area & Coordinates**: Abyssea - Attohwa X: 195 Y:20 Z:138 (36)
**Party or Solo**: Party
**NPC Name**: ???
**Monster Name**: Wherwetrice
**Steps To Reproduce The Issue**: Fought Amuckatrice hoping for Mangled Cockatrice Skin to dropped. I notice things dropping that normally don't drop from Cocktrices. reviiewed Server tools to find that  Mangled Cockatrice Skin does not drop from any mob. can we please adjust the drops of Amuckatrices accordingly

**Comment by R3P0FFXI** [comment]
Correct items are in SQL this should be resolved next maint. Id this does not work will need to check the mobs are linked to the correct Drop ID of 82

Info DB
GroupID : 10173 	PoolID : 115
DropID : 82

**Comment by Loki79** [comment]
if fixed the drop ID so if you add the item to dropID 82 you will be good to go 3p0

**Comment by R3P0FFXI** [comment]
Issue will be fixed in Tuesday Maint
