### ISSUE TITLE
Problems with communication

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#880]
**Date & Time**: Wednesday April 20th, 2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: blu99/rdm49

**NPC or Monster or item Name**: na

**Zone name & Coordinates (use `@where`)**: everywhere

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: Can not join parties, can not see ls chat, can not send other users tells.  Only way to currently communicate is being in close proximity and just typing.  Can't send tells so can't confirm if this is happening with other users or not, but myself, Hickss, and goodjuice have not been able to join parties, or send tells, or see ls chat.

**Comment by R3P0FFXI** [comment]
Fixed
