### ISSUE TITLE
Gefechtbrust / Gefechtschuhs craftable but cannot be equipped

### ISSUE THREAD

**Issue by PresidentNixon** [LegionDark/Issues#882]
**Date & Time**: 4:00 PM EST 4/20/2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Nixon

**Nation**: Bastok

**Job(level)/Sub Job(level)**: WAR99/SAM49

**NPC or Monster or item Name**: Gefechtbrust and Gefechtschuh

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/26881/gefechtbrust
http://www.ffxiah.com/item/27396/gefechtschuhs

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Just crafted these today only to find out they can't be equipped. It seems likely the other pieces of the set and the HQ versions are the same, but I only have these two pieces.
Screenshot of it grayed out not being able to be equipped by WAR99: http://i.imgur.com/lSioTle.jpg?1

**Comment by Samikana** [comment]
@R3P0FFXI I have fixes for all of the broken items from the crafting update that were sent to you 2ish months ago.  Do you want them resent, as it looks like they never got in game??

**Comment by Samikana** [comment]
It's B/C of the Su1 & is being worked on

**Comment by PresidentNixon** [comment]
It doesn't have Su1 tag it's just regular 119 armor, but thanks for working on it either way.

**Comment by R3P0FFXI** [comment]
Su1/2 issue https://github.com/LegionDark/Issues/issues/878
