### ISSUE TITLE
Crafting Skill Import Please

### ISSUE THREAD

**Issue by KrispeyK** [LegionDark/Issues#883]
**Date & Time**: 4/20/16

**FFXI Client Version (use `/ver`)**: NA

**Character Name**: Krispey

**Nation**: Bastok

**Job(level)/Sub Job(level)**: NA

**NPC or Monster or item Name**: NA

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Crafting Import needed, thank you for your time. 

http://imgur.com/PkIonAy

**Comment by Samikana** [comment]
I'll do it tonight.   I forgot yesterday.

**Comment by Samikana** [comment]
Player not online when I was.  Send a tell for your crafts.

**Comment by Samikana** [comment]
Please be aware that Synergy and Fishing will not be included in your skill transfer.  Additionally, any crafts that exceed 100 will not surpass that level.  

Your crafts have been risen.  If any mistakes were made, please open another bug report to have any issues resolved.
