### ISSUE TITLE
Unable to get CS to finish Nation Mission 2-3

### ISSUE THREAD

**Issue by DanieC89** [LegionDark/Issues#884]
**Date & Time**: 21/04/2016 - 19:21pm

**FFXI Client Version (use `/ver`)**:  30160329_1

**Character Name**: Danie

**Nation**:  San d'Oria

**Job(level)/Sub Job(level)**:  99BLM/49WHM

**NPC or Monster or item Name**: Halver

**Zone name & Coordinates (use `@where`)**: Chateau d'Oraguille  X:1 Y:0 Z:0 (202)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: I'm trying to get the CS to finish nation mission 2-3 by speaking to Halver, and when I do it's activating Aht Urhgan Mission 5: Confessions of Royalty. This mission requires me to speak to Halver, hand him a letter and head to Ru''Lude Gardens and walk into the Palace for a CS, which I do so that I can then speak to Halver about mission 2-3, and the CS in the Palace won't activate. I go back to speak to Halver again and it's a repeat of the mission 5 CS asking me to go to the palace.

**Comment by TeoTwawki** [comment]
The TOAU mission is taking priority and mistakenly repeats if the ToAU mission isn't fully completed first. I'm fixing the repeat part in darkstar, but you will be able to get your correct cs if you fully finish the ToAU missions that are checked before the nation missions in Halvers script (CONFESSIONS_OF_ROYALTY and EASTERLY_WINDS both take priority).

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/3078

**Comment by TeoTwawki** [comment]
Legion server will get that after updating later

**Comment by TeoTwawki** [comment]
Thanks for the report!
