### ISSUE TITLE
Voidwatch Windurst T3 upgrade problem.

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#886]
**Date & Time**: 4:30pm April 21st 2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/rdm49

**NPC or Monster or item Name**: Akupara

**Zone name & Coordinates (use `@where`)**: Meriph mountains

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: This has happened to us a few times now, not really a serious issue but an issue regardless.  T3 mobs are Lord Asag and Akupara.  Whenever you fight Akupara first, then Lord Asag the abysite won't upgrade even though you've killed both.  For some reason you have to kill Akupara second or the abyssite won't upgrade to 4 and stays at 3.

**Comment by TeoTwawki** [comment]
Not seeing how that is physically possible. They each are coded identically save for which mask bit they flip. When both bits are flipped, the mask fills, and the next step fires the exact same code on both.

**Comment by TeoTwawki** [comment]
If this still occurs, open new issue.
