### ISSUE TITLE
Voidwatch Windurst t3 Akupara  PoL Crash

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#887]
**Date & Time**: April 21st, 2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: blu99/rdm49

**NPC or Monster or item Name**: Akupara

**Zone name & Coordinates (use `@where`)**: Meriphataud Mountains (S) (E-4)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: Myself and about 3 other players had their PoL.  Took a screencap the moment it happened and it LOOKS like the ability Testudo Tremor caused PoL to lock up

http://i.imgur.com/kfWbzvy.jpg

**Comment by R3P0FFXI** [comment]
@spectre99 No if you see the ability go off its not the cause of the crash if there even is one. Most likely you or one of the 3 others are a Blu mage and one of those spells is causing your issue. It is not VWNM.

**Comment by TeoTwawki** [comment]
Determined to have most likely been caused by a player action that will be fixed in next maint.
