### ISSUE TITLE
Voidwatch Windurst T2 Ogbunabali issues

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#888]
**Date & Time**: 6:30pm April 21st 2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/rdm49

**NPC or Monster or item Name**: Ogbunabali

**Zone name & Coordinates (use `@where`)**: Maze of Shakhrami (D-8)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: A few issues were noticed.  First when the nm spawns it is invisible at first, you can only see the name hovering in the air. You can target and attack, but it takes a moment for the NM to become visible.  When I died I got sent to homepoint, I came back out during the fight and he was invisible, could target and attack, and he could inflict damage to me, but remained invisible.  The Abyssite also didn't upgrade the first time, we fought it again, and the second time it crashed PoL for about 3 or so players, it looked as if it was during the ability Mandibular Bite.  Didn't manage to catch a screenshot like the others

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/3025

The crash was not the mobs fault, but a player action which should be fixed in the next maint. Antlions are in general borked until the server catches up with darkstar again.

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
