### ISSUE TITLE
Mourioche TP move causing wrong status effect

### ISSUE THREAD

**Issue by Genesis-Legion** [LegionDark/Issues#889]
**Date & Time**: 2:23 AM (CST)

**FFXI Client Version (use `/ver`)**:  30160329_1

**Character Name**: Genesis

**Nation**: Bastok

**Job(level)/Sub Job(level)**: DRK63/SAM31

**NPC or Monster or item Name**: Mourioche

**Zone name & Coordinates (use `@where`)**: Boyahda Tree X:46 Y:8 Z:130

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: 

Make any mourioche use the TP move Scream. The effect should be mind down but is causing terror instead.

http://ffxiclopedia.wikia.com/wiki/Category:Mandragora

http://i.imgur.com/kfJ9eIK.png

**Comment by TeoTwawki** [comment]
it was running an NM's version of the script..will be fixed in next maint.
