### ISSUE TITLE
Elshimo pachira fruit

### ISSUE THREAD

**Issue by Goodjuice** [LegionDark/Issues#890]
**Date & Time**: 9:38am GMT

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Goodjuice

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: WAR99/SAM49

**NPC or Monster or item Name**: Elshimo Pachira Fruit

**Zone name & Coordinates (use `@where`)**: All

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/5604/el-pachira-fruit

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 

Elshimo pachira fruit gives a food effect however it is only supposed to be a medicine its not a food.
![img_20160422_093806](https://cloud.githubusercontent.com/assets/18429106/14736300/2e30a5de-086e-11e6-8e89-e80b65c6273b.png)

**Comment by TeoTwawki** [comment]
Covered up what you were trying to screenshot with your chatlog, lol. But its actually supposed to be neither - on retail this just does poison effect and nothing else.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/3079
