### ISSUE TITLE
Blu Spell Sudden lunge cant be learned/ not used by mobs

### ISSUE THREAD

**Issue by maberrychief** [LegionDark/Issues#892]
Date & Time: 4/22/2016 2:00 pm - 2:35pm CST

FFXI Client Version (use /ver): playonline 1.18.15e

Character Name: maberrychief

Nation: Bastok

Job(level)/Sub Job(level):Blu99/rdm49

NPC or Monster or item Name:Biddybug

Zone name & Coordinates (use @where):x:300 y:-1 z:485
 (132)
ffxiah.com link (for items issues only):

Multi-boxing? (multiple clients on same connection): no

Steps To Reproduce / any other info: fight biddybugs in jugner forest (s)

**Comment by TeoTwawki** [comment]
Will be fixed in next maint.
