### ISSUE TITLE
Su1 and su2 list work in progress

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#893]
Gefechtschaller (Su1?) item # 26722
Gefechtbrust (Su1?) item # 26881
Gefechtdiechlings (Su1?) item # 27224
Gefechtschuhs (Su1?) item # 27396
Gefechthentzes (Su1?) item# 27987

Wildheitschaller (Su1?) item # 26723
Wildheitbrust (Su1?) item # 26882
Wildheitdiechlings (Su1?) item# 27225
Wildheitschuhs (Su1?) item# 27397
Wildheithentzes (Su1?) item# 27988

Sombra Tiara (Su1?) item # 26724
Sombra Harness (Su1?) item # 26883
Sombra Tights (Su1?) item # 27226
Sombra Leggings (Su1?) item # 27398
Sombra Mittens (Su1?) item # 27989

Sombra Tiara +1 (Su1?) item # 26725
Sombra Harn. +1 (Su1?) item # 26883
Sombra Tights +1 (Su1?) item # 27227
Sombra Leg. +1 (Su1?) item # 27399
Sombra Mit. +1 (Su1?) item# 27990

Revealer's Crown (Su1?) item # 26726
Revealer's Tunic (Su1?) item # 26885
Revealer's Pants (Su1?) item # 27228
Revealer's Pumps (Su1?) item # 27400
Revealer's Mitts (Su1?) item #27991

Reveal. Crown +1 (Su1?) item # 26727
Reveal. Tunic +1 (Su1?) item # 26886
Reveal. Pants +1 (Su1?) item # 27229
Reveal. Pumps +1 (Su1?) item # 27401
Reveal. Mitts +1 (Su1?) item # 27992

**Comment by TeoTwawki** [comment]
All Su1 and Su2 items can now be equipped as of today's update. For now the unlock requirement doesn't exist, so its not being enforced - everyone is Su2 stat'd for free.
