### ISSUE TITLE
Shark TP moves

### ISSUE THREAD

**Issue by Samikana** [LegionDark/Issues#894]
**Date & Time**: 16/4/23

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Ezra

**Nation**: Bastok

**Job(level)/Sub Job(level)**: WHM(99)/RDM(49)

**NPC or Monster or item Name**: Tchakka

**Zone name & Coordinates (use `@where`)**: -766 -4 154 (138)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes.

**Steps To Reproduce / any other info**: Shark 7 wonder's TP moves are going crazy.  Verve is buffing players instead of shark and he's using TP moves off of Colkhab (the Bee 7 wonder) that are causing random (but not consistent) client crashes.  The TP moves I've seen him use and people crash on are both off of Colkhabb, Incicive Apotheosis and Incicive Denouement as well.

**Comment by TeoTwawki** [comment]
Had wrong IDs on his melee attacks somehow. This can't be adjusted in live without a maint. The target flags on a shitton of skills still need adjusted though.

**Comment by TeoTwawki** [comment]
I somehow forgot to close this during maint I guess
