### ISSUE TITLE
Unobtainable Spell (Can't be bought off AH from Bot, can't be farmed, no NPC)

### ISSUE THREAD

**Issue by Samikana** [LegionDark/Issues#895]
**Date & Time**: 16/4/23

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Ezra

**Nation**: Bastok

**Job(level)/Sub Job(level)**: SCH(99)/BLM(49)

**NPC or Monster or item Name**: Regen V

**Zone name & Coordinates (use `@where`)**: N/A

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/5086/regen-v

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: 
Regen V can't be bought off AH, no quest for it, doesn't drop off anything, and it's not sold off any NPC (It's a WoE drop on retail.)

**Comment by R3P0FFXI** [comment]
Added in Maint
