### ISSUE TITLE
Sudden Lunge possibly causing client crashes.

### ISSUE THREAD

**Issue by Genesis-Legion** [LegionDark/Issues#897]
**Date & Time**: 5:30 cst

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Azazel

**Nation**: Bastok

**Job(level)/Sub Job(level)**: RDM99/BLM49

**NPC or Monster or item Name**:  Sallow Seymour and Ushumgal

**Zone name & Coordinates (use `@where`)**: X: 798, Y: 0, Z: 439 (North Gustaburg and North Gustaburg [S]

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
Not entirely sure if this is enough to go on but it might be something. My windower logging file shows that Sudden Lunge as well as Tremors and Aqua fortis were used immediately as a few people, myself included POL crashed

Azazel's bind effect wears off.
Sallow Seymour's stun effect wears off.
[Sallow Seymour] Tremors ¨ Mano
[Minikay] 10 Sudden Lunge ¨ Sallow Seymour
=== Area: North Gustaberg ===     <---Me logging back in after crash
Azazel's petrification effect wears off.
Azazel's bind effect wears off.
<<< Welcome to LegionDS! >>>
Our IRC channel on Rizon: #Legionffxi 

Ushumgal's stun effect wears off.
[Minikay] Sudden Lunge ¨ Ushumgal
[Ushumgal] Aqua Fortis ¨ Mano
[Minikay] 93 Sudden Lunge ¨ Ushumgal
=== Area: North Gustaberg [S] ===   <---Also logging back in after crash
Style lock mode disabled.
<<< Welcome to LegionDS! >>>
Our IRC channel on Rizon: #Legionffxi

**Comment by TeoTwawki** [comment]
Closing in favor of  #904
