### ISSUE TITLE
Elemental Rings makes me cry

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#898]
**Date & Time**: 4/23/2016 8:57pm

**FFXI Client Version (use `/ver`)**:30160329_1 

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:Thf(99)/War(49) 

**NPC or Monster or item Name**: Shiva Ring

**Zone name & Coordinates (use `@where`)**:all zones all coordinates 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/27574/shiva-ring

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Can't put Elemental rings on AH.

**Comment by Samikana** [comment]
You've gotta do better than that.  You should have photoshopped a screenshot of ~~Buttcunt~~ Buttcant.

**Comment by Samikana** [comment]
@Genesis-Legion try and see if you can look through and tell me what is wrong with this and if you can't figure it out I'll take over

**Comment by Samikana** [comment]
Just tested the other rings and no others can be put on AH.

**Comment by Genesis-Legion** [comment]
All the elemental rings were fixed and send to to @Samikana.

**Comment by R3P0FFXI** [comment]
Please don't close until I get the lists and can add them in
