### ISSUE TITLE
Problem with the Burning Circle in Waughroon Shrine for Windy M2-3

### ISSUE THREAD

**Issue by Rentaro01** [LegionDark/Issues#899]
**Date & Time**: April 23, 2015 18:00

**FFXI Client Version (use `/ver`)**: 

**Character Name**: Rentaro

**Nation**:  Windurst

**Job(level)/Sub Job(level)**: Red Mage / Warrior

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**:  Waughroon Shrine, @ the Burning Circle

**ffxiah.com link (for items issues only)**: No

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
I was in Waughroon Shrine for my Windurst Rank Mission 2-3 at the Burning Circle platform and click on it. and no action.

**Comment by TeoTwawki** [comment]
@LegionDark/gm get me their current mission ID via `@checkmission` and the value of their `MissionStatus` variable via `@checkvar`

**Comment by Samikana** [comment]
Their variable was originally 4.  I set it to 10 manually to try and push them past their issue with it, as Grohm never updated his variable (it seems).

His mission ID is 6.  @TeoTwawki

**Comment by TeoTwawki** [comment]
it being 4 means player most definitely has missed steps before reaching Grohm
