### ISSUE TITLE
Monster Tool gets a 500 Internal Server Error

### ISSUE THREAD

**Issue by SomeGlenn** [LegionDark/Issues#9]
**Date & Time**: 26th May
**Frequency**: Always
**FFXi Client Version**: N/A
**Character Name**: N/A
**Race**: N/A
**Main Job**: N/A
**Sub Job**: N/A
**Area & Coordinates (Type @where to get this info.)**: On the INTERNETS!
**Party or Solo**: Solo
**NPC Name**: http://legiondark.com/?p=mobs
**Monster Name**: Legiondark
**Steps To Reproduce The Issue**:
1. Head over to http://legiondark.com/?p=mobs
2. Type in any mob name
3. Internal error 500

**Comment by atom0s** [comment]
This should be fixed now.
