### ISSUE TITLE
Horst npc teleport issue

### ISSUE THREAD

**Issue by Greyhulk** [LegionDark/Issues#90]
**Date & Time**: 6/12/15
**Frequency**: Always
**FFXI Client Version**: 30150508_8
**Character Name**: Zallen
**Race**: Elvaan M
**Main Job**: Monk
**Sub Job**: Dancer
**Area & Coordinates**: X -55 Y 0 Z -9 (13)
**Party or Solo**: solo
**NPC Name**: Horst
**Monster Name**: none
**Steps To Reproduce The Issue**: attempting to teleport to a maw

I did the quest to unlock aby, got my stone, went to several abyssea maws with cutscenes, returned to joachiim and got the final required cs, then attempt to tele with Horst, and when he casts the tele, my character just turns invisible until i interact with something.

**Comment by Loki79** [comment]
you missed a step then, please review the progression and make sure you have completed everything.
