### ISSUE TITLE
Shabti Sabatons Does Not Have Any Crafting Information/Recipe

### ISSUE THREAD

**Issue by Danyeul** [LegionDark/Issues#900]
April 24, 2016 -- 1:22AM PST

FFXI Client Version (use /ver):
30160329_1

Character Name:
Orange // Juice

Nation:
Bastok

Job(level)/Sub Job(level):
THF99/WAR49, WHM99/RDM99

**NPC or Monster or item Name**: 
Shabti Sabatons

**Zone name & Coordinates (use `@where`)**: 
N/A

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/28178/shabti-cuisses

**Multi-boxing? (multiple clients on same connection)**: 
Sure~

**Steps To Reproduce / any other info**: 
Currently no crafting recipe is available for this Feet piece, where as the other 4 pieces included in this set are available/craftable.

**Comment by Samikana** [comment]
@Genesis-Legion take a shot at them.  I'll proofread your work and if you can't code them, let me know and I will.

**Comment by R3P0FFXI** [comment]
This has been submitted to DSP and should be corrected shortly, it was previously mixed in with blurred gear

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
