### ISSUE TITLE
Ix 'aern (dragoon) Possibly Not Spawnable Right Now

### ISSUE THREAD

**Issue by Danyeul** [LegionDark/Issues#901]
**Date & Time**: 
April 24, 2016 -- 1:22AM PST

FFXI Client Version (use /ver):
30160329_1

Character Name:
Orange // Juice

Nation:
Bastok

Job(level)/Sub Job(level):
THF99/WAR49, WHM99/RDM99

NPC or Monster or item Name:
Ix' Aern (dragoon) ix' drG

**Zone name & Coordinates (use `@where`)**: 
The Garden of Ru'Hmet

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Been about 3 days on/off killing aw'aern any chance we get in hopes of popping ix'aern (dragoon), but have had absolutely no luck, so, beginning to wonder if it's even coded to spawn.  Browsed forum prior to camping/opening ticket, but it appears the only information available is that it's a lottery.

**Comment by TeoTwawki** [comment]
@R3P0FFXI good chance it is busted, since the other Ix is. I haven't had time to check wtf is wrong yet.

**Comment by benfolka** [comment]
it is broken, i also had same problem long ago.

**Comment by TeoTwawki** [comment]
@benfolka your issue was with Ix'dr**k**, not Ix'dr**g**. 2 diff mobs. I haven't had time to work on that yet either.

**Comment by benfolka** [comment]
i was shy to open another ticket for drg

**Comment by TeoTwawki** [comment]
:weary:

**Comment by TeoTwawki** [comment]
Ix 'aern (dragoon) is now spawning (forgot to update issue, a comment over at the Ix'drk issue just reminded me) with additional fixes for some of its behavior coming in next update. The comment by  alannor says Ix'mnk spawns as well so only drk needs fixed now.
