### ISSUE TITLE
Unable to complete ToAU mission 5 to access nation mission 2-3 CS

### ISSUE THREAD

**Issue by DanieC89** [LegionDark/Issues#902]
**Date & Time**: 24/04/2016 10:41am

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Danie

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: 99BLM/49RDM

**NPC or Monster or item Name**: Halver

**Zone name & Coordinates (use `@where`)**: Ru'Lude Gardens X:0 Y:2 Z:40 (180)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: I previously submitted a ticket as my nation mission 2-3 cutscene wasn't activating as a ToAU mission (Confessions of Royalty) was taking precedence. I was told to complete the ToAU mission, however, this doesn't seem to be working, either. I'm asked to report to Halver and show him a letter, which I do and get the cutscene for that, then i'm told to make my way to the palace in Ru'Lude Gardens for the next cutscene but this won't activate anywhere in the palace. On my missions lists i'm still on Confessions of Royalty but no matter how many times I speak to Halver I just repeat showing him the letter and being told to go to Jeuno in an endless loop. Any help would be appreciated, thanks! :)

**Comment by TeoTwawki** [comment]
I've tested that cs and it does activate near the bottom of the stairs leading to the dukes chambers as in retail. Any enhanced movement or lag will screw it up requiring you to walk away and re-enter "the area" (generally, go back outside that room, walk back in slowly). I know this works and I did my own ToAU missions all the way to the black coffin fight.

**Comment by DanieC89** [comment]
I've literally stuck my character on walk and slow walked from upper jeuno all the way to the palace with no cutscene. Exited and went back in again several times with nothing, all the way up the stairs in the palace and out the back still nothing. Just sat through the CS with Halver 10times+ to see if he would offer me a different CS but he's still telling me to go to Jeuno. My mission log doesn't update to say that I'm on Easterly Winds but Halvers CS wont change and I can't activate the CS in jeuno still. I have no idea what to do next or what to try to make this work :< Sorry to be a bother with this but I literally do not know what to do to fix it!

**Comment by TeoTwawki** [comment]
I'll be looking for you in game when I can.

**Comment by TeoTwawki** [comment]
Fixed in dsp and in legions live server.
