### ISSUE TITLE
quartz tathlum +1

### ISSUE THREAD

**Issue by benfolka** [LegionDark/Issues#905]
**Date & Time**: 16.05

**FFXI Client Version (use `/ver`)**: 30160929_1

**Character Name**: Clay

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 99sch/49rdm

**NPC or Monster or item Name**: quartz tathlum +1

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/21359/quartz-tathlum-1

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**:  quartz tathlum +1 cant be worn to ammo slot

**Comment by Samikana** [comment]
Getting sick of items I've fixed getting bug reported still.

@PikaFox this is all you

**Comment by R3P0FFXI** [comment]
@Samikana latest round of fixes are in but not on live

**Comment by Samikana** [comment]
This was not in those fixes I sent it before that @R3P0FFXI

**Comment by PikaFox** [comment]
Sent halsey fix for review.

**Comment by R3P0FFXI** [comment]
Fixed in Maint
