### ISSUE TITLE
renik af+1 reforged SAM head error

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#906]
Date & Time: 26/04/2016, 23:00pm --01/03/16

Frequency: 

FFXI Client Version: 30151233_0

Character Name: Aurel

Race: Hume

Main Job: blm

Sub Job: Sam

Area & Coordinates: 

Party or Solo: Party or solo 

NPC Name:Renik

Monster Name:

ffxiah.com link (for inventory items only):
http://www.ffxiah.com/item/27695/wakido-kabuto-1

Multi-boxing? (multiple clients on same connection): yes

Steps To Reproduce The Issue:i have trade
http://www.ffxiah.com/item/27674/wakido-kabuto +5 rems chap 4,and i obtain
http://www.ffxiah.com/item/27694/orion-beret-1

**Comment by Samikana** [comment]
@Nekrol I will not be fixing this via GM commands until the fix for it in general is live, so don't harass me about it.
