### ISSUE TITLE
Archery skill not properly capped

### ISSUE THREAD

**Issue by maberrychief** [LegionDark/Issues#907]
**Date & Time**: 4/26/16

**FFXI Client Version (use `/ver`)**: 1.18.15e

**Character Name**: maberrychief

**Nation**: bastok

**Job(level)/Sub Job(level)**:  sam99/rng49

**NPC or Monster or item Name**: archery skill

**Zone name & Coordinates (use `@where`)**:  crawlersnest  X:97 Y:0 Z:-228 (87)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: archery skill capped at 336 when should be 378 also archery weapon skills that should be available with rng sub are not all available reference 
http://ffxiclopedia.wikia.com/wiki/Category:Archery

**Comment by TeoTwawki** [comment]
See every skill cap related issue ever.

The Legion Server has no control over this, its been reported to darkstar and whenever they fix it we'll be able to get that fix here.

**Comment by TeoTwawki** [comment]
There are multiple related bugs, 1 of which can be solved be re-equiping your weaponry.
