### ISSUE TITLE
Hi-Potion missing from vendors. 

### ISSUE THREAD

**Issue by KrispeyK** [LegionDark/Issues#908]
**Date & Time**: Wed. April 27 

**FFXI Client Version (use `/ver`)**: 

**Character Name**: Krispey

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: Alchemy Guild

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/4116/hi-potion

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Alchemy Guild NPC In Bastok Should (Per wiki) Sell Hi-Potions. Link below. 
http://ffxiclopedia.wikia.com/wiki/Hi-Potion

Thank you for your time.

**Comment by R3P0FFXI** [comment]
@KrispeyK Guild shops were replaced today by standard NPC all are selling the correct items
