### ISSUE TITLE
Synergy Items to convert to crafting synths

### ISSUE THREAD

**Issue by KrispeyK** [LegionDark/Issues#909]
Per R3PO here is a list I compiled of all synergy items that may be of use to players of varying levels from 75 - 99. I combed through the list twice, but it's possible I missed something noteworthy. 

- -  https://www.bg-wiki.com/bg/Vivid_Strap 
http://www.ffxiah.com/item/19049/vivid-strap
- https://www.bg-wiki.com/bg/Nefer_Khat
http://www.ffxiah.com/item/10865/nefer-khat
- -  https://www.bg-wiki.com/bg/Flame_Pearl (and all the assorted other earrings +3/4)
http://www.ffxiah.com/item/11014/flame-pearl
- -  https://www.bg-wiki.com/bg/Beir_Belt
http://www.ffxiah.com/search/item?name=Beir_Belt
- -  https://www.bg-wiki.com/bg/Grim_Cuirass
http://www.ffxiah.com/item/13792/grim-cuirass
- -  https://www.bg-wiki.com/bg/Juogi
http://www.ffxiah.com/item/14336/juogi
- -  https://www.bg-wiki.com/bg/Yhel_Jacket
http://www.ffxiah.com/item/14364/yhel-jacket
- - https://www.bg-wiki.com/bg/Pyrosoul_Ring (And all the assorted other rings for stats)
http://www.ffxiah.com/item/11656/pyrosoul-ring (and other rings for other stats)
- -  https://www.bg-wiki.com/bg/Hachirin-no-Obi
http://www.ffxiah.com/item/28419/hachirin-no-obi
- -  https://www.bg-wiki.com/bg/Combatant%27s_Torque
http://www.ffxiah.com/item/26015/combatants-torque
- - https://www.bg-wiki.com/bg/Incanter%27s_Torque
http://www.ffxiah.com/item/26016/incanters-torque
- -  https://www.bg-wiki.com/bg/Fotia_Belt
http://www.ffxiah.com/item/28420/fotia-belt
- - https://www.bg-wiki.com/bg/Fylgja_Torque
http://www.ffxiah.com/item/11579/fylgja-torque
- - https://www.bg-wiki.com/bg/Ire_Torque
http://www.ffxiah.com/item/11581/ire-torque
https://www.bg-wiki.com/bg/Ocelo._Headpiece
http://www.ffxiah.com/item/10864/ocelo-headpiece

**Comment by Baucant** [comment]
could I throw this item for consideration http://www.ffxiah.com/item/18633/chatoyant-staff https://www.bg-wiki.com/bg/Chatoyant_Staff

and the NQ version
http://www.ffxiah.com/item/18632/iridal-staff https://www.bg-wiki.com/bg/Iridal_Staff

**Comment by Baucant** [comment]
2 more items that could be useful
http://www.ffxiah.com/item/28420/fotia-belt
http://www.ffxiah.com/item/27510/fotia-gorget

**Comment by R3P0FFXI** [comment]
@KrispeyK Issue resolved in MUP2 which is now live
