### ISSUE TITLE
Assassin's Bonnet +2 (moogle won't accept trade)

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#91]
**Date & Time**: 6/13/2015 2:30 pm
**Frequency**: everytime
**FFXI Client Version**:30150508_8
**Character Name**: Baucant
**Race**: Elvaan
**Main Job**: Thf
**Sub Job**: Dnc
**Area & Coordinates**: Port Jeuno X:-50 Y:0 Z:-9 (47)
**Party or Solo**: Both
**NPC Name**: Moogle
**Monster Name**: n/a
**Steps To Reproduce The Issue**: attempted to trade 50 forgotten thoughts with assassin's bonnet multipul times, tried zoning and trading again, tried changing order of item place on the trade. I have done the other 4 pices of relic in the THF set just this one the moggle isn't reconizing.

**Comment by Loki79** [comment]
Fixed.  This wont require a restart so you will be good to go as soon as i pull it into the server here in a few.

**Comment by Baucant** [comment]
Thanks you so much for a quick resolution I was able to aquire the relic +2
