### ISSUE TITLE
Crafting - Kalina

### ISSUE THREAD

**Issue by KalinaERA** [LegionDark/Issues#910]
**Date & Time**: 04/28/2016 10:24am

**FFXI Client Version (use `/ver`)**: NA

**Character Name**: Kalina

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: NA

**NPC or Monster or item Name**: NA

**Zone name & Coordinates (use `@where`)**: NA

**ffxiah.com link (for items issues only)**: NA

**Multi-boxing? (multiple clients on same connection)**: NA

**Steps To Reproduce / any other info**: Please update/import my crafting skills. Character ported over in early April but I failed to log a request/issue to update my crafting skills until now. I ave attached the screenshot which was posted on my import request. Thank you.
![kalina_crafting](https://cloud.githubusercontent.com/assets/17536962/14889217/df2145ee-0d2b-11e6-9b9e-2c91dc3fd126.png)

**Comment by Samikana** [comment]
I will do it when I get home.  I don't want @genesis-legion doing it until I can explain it and all the rules

**Comment by Samikana** [comment]
Rather I will show him how if he's online

**Comment by Samikana** [comment]
No response from the player in more than 3 days.
