### ISSUE TITLE
KI missing

### ISSUE THREAD

**Issue by Ascheriit00** [LegionDark/Issues#911]
**Date & Time**: 28/04/2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Ascheriit

**Nation**: Sand'oria

**Job(level)/Sub Job(level)**: THF97/DNC38

**NPC or Monster or item Name**: Supplies package

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
I have mission 1.2 of Aht Urgan active but dont have the Key Item on my inventory and can't go on with the mission.

**Comment by R3P0FFXI** [comment]
@Ascheriit00 were you multiboxing? If so restart your PC log your character missing the KI in and restart the mission. Multiboxing causes issues you guys need to stop having multiple characters on the same connection logged in.

@Samikana @Genesis-Legion if this is not his issue please run a @checkvar on this character and get Teo the variables so we can see what is going on.

DO NOT PUSH HIM FORWARD until Teo says to do so.

**Comment by Ascheriit00** [comment]
i have restarted my character alone and tried restarting the mission and got all the dialogs but no key item for it, dont think is my issue because i've gotten all the key items for the all the others missions/quests while having my mule logged too except this one, thank you for your time

**Comment by TeoTwawki** [comment]
I'm betting you started the mission forever ago, and only recently tried to complete it.

@LegionDark/gm @R3P0FFXI  I'm I'm right he's carrying bugged data, needs the KI or else a mission reset so he can see the CS that gives it.

**Comment by Ascheriit00** [comment]
Yes iirc i started the mission a time ago and is probably that the why i dont have the KI

**Comment by Samikana** [comment]
Not online both times I've logged on.

**Comment by Samikana** [comment]
@Ascheriit00 your bug report is going to be closed in 1 day if you don't respond.

If you can't make it online leave your character on and I wil get to it.

**Comment by Ascheriit00** [comment]
Hi sorry i was working the weekend now i am online

**Comment by Samikana** [comment]
You should have your KI.
