### ISSUE TITLE
Smierc(skeleton) using mantis WS/TP attacks

### ISSUE THREAD

**Issue by Genesis-Legion** [LegionDark/Issues#914]
**Date & Time**: 4/28/16 7:50 pm (cst)

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Genesis

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BLU99/RDM49

**NPC or Monster or item Name**: Smierc

**Zone name & Coordinates (use `@where`)**: X:198 Y:16 Z:-659 Tahrongi Canyon

**ffxiah.com link (for items issues only)**:

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: 

Fight Smierc (Jeuno VW Tier 5) and the skeleton uses multiple Mantis TP moves including
Macerating Bile, Preying Posture, Phelegm Explosion, Slicing Sickle etc.
Unsure if this is intentional so I put it here anyways.

**Comment by TeoTwawki** [comment]
ell oh ell

**Comment by TeoTwawki** [comment]
ell oh ell

**Comment by TeoTwawki** [comment]
fixed in trunk, won't take effect till next maint/crash happen.
