### ISSUE TITLE
Immortal Sentries

### ISSUE THREAD

**Issue by bonez69** [LegionDark/Issues#916]
**Date & Time**: 4/29/2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Gollum

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: THF(99)/DNC(49)

**NPC or Monster or item Name**: Naja Salaheem

**Zone name & Coordinates (use `@where`)**: Whitegate X:25 Y:-7 Z:-45 (114)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: got CS but no KI (supplies package)

**Comment by TeoTwawki** [comment]
how long ago did you get the cs?

**Comment by bonez69** [comment]
i'm not sure using this char from a friend but he has the mission but no ki  prob a few month im guessin when he last played.

**Comment by TeoTwawki** [comment]
Same as #911 most likely.

I only recently fixed this stuff in darkstar, so probably going to be quite a few ppl who started this mission before that.

**Comment by Genesis-Legion** [comment]
Gollum was given the KI and should be able to complete the mission.
