### ISSUE TITLE
Saruta Cotton unusable

### ISSUE THREAD

**Issue by Angie1984** [LegionDark/Issues#917]
**Date & Time**: 
4/29/16 7:38pm

**FFXI Client Version (use `/ver`)**: 

**Character Name**: 
Angie

**Nation**: 
San D'oria

**Job(level)/Sub Job(level)**: 
40 Blm / 38 Whm

**NPC or Monster or item Name**: 
Saruta Cotton stack switches to dark/unusable during synth, crashing synth, resulting in mass loss of expensive materials.

**Zone name & Coordinates (use `@where`)**: 
Anywhere

**ffxiah.com link (for items issues only)**: 
???

**Multi-boxing? (multiple clients on same connection)**: 
none

**Steps To Reproduce / any other info**: 
When I go to craft anything using a stack of Saruta Cotton, the stack goes dark like its unusable crashing my synth making me loose expensive materials, namely trying to make Linen Doublets. I have tried zoning, it does come back, but the results are the same when I retry the synth. When I shut down and reboot, that does nothing.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/2373
https://github.com/DarkstarProject/darkstar/issues/463

From their tracker:
> "It happens when you break and the stack exists after the synth. I am not certain if it happens when you crystal break and/or lose items break."

If you have additional info to add, please tell them about it. When it gets fixed there Legion will be able to pull in that fix, and there is nothing else that can be done about it.
