### ISSUE TITLE
ZM14 Ark Angel TT Fight Doesn't Activate

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#918]
**Date & Time**: 
4/29/2016 - 21:56

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**: 
Buttons

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
BLU(99)/RDM(49)

**NPC or Monster or item Name**: 
Ark Angel TT

**Zone name & Coordinates (use `@where`)**: 
La'Loff Amphitheatre - X:-261, Y:-137, Z:375 (126)

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Click on Ark Angel TT's Shimmering Circle. Nothing happens.

All of the other Ark Angel battles worked as expected.

I don't think it's a DSP issue, unless it was recently broken, as I was able to complete all of the battles on my previous private server. 

Thanks for reading.

**Comment by Midgardsormr** [comment]
An additional note: I am at a loss to explain it, but even though I did not complete the Ark Angel TT fight, I noticed that I have advanced to ZM15 and have the KI. Wondering if someone pushed me through, or...? 

Guess I'll go ahead and close this out.

**Comment by TeoTwawki** [comment]
Its possible it glitched and gave you clear when you tried to enter. We'll try and reproduce later. You didn't do Divine Might right, just the individual Arks? Coz DM will insta clear all 5 of them.

**Comment by Midgardsormr** [comment]
It was the individual Ark fights. 

Weird. Guess it was just a fluke. Thanks.
