### ISSUE TITLE
Homepointing to Toraimarai Canal Takes Me to Qufim Island

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#919]
Date & Time: 
4/29/2016 - 23:05

FFXI Client Version (use /ver): 
30160329_1

Character Name: 
Buttons

Nation: 
Windurst

Job(level)/Sub Job(level): 
BLU(99)/RDM(49)

NPC or Monster or item Name: 
N/A

Zone name & Coordinates (use @where): 
Qufim Island - X:-210, Y:-20, Z:91 (33)

ffxiah.com link (for items issues only): 
N/A

Multi-boxing? (multiple clients on same connection): 
No

Steps To Reproduce / any other info: 
Try to homepoint to Toraimarai Canal from any crystal. I end up going to Qufim Island homepoint. 

It appears that the Qufim crystal is actually registering as the Toraimarai Canal crystal because the option to homepoint to Toraimarai Canal is not available at the Qufim crystal.

Additionally, there's no Qufim Island homepoint available in the homepoint menus.

Thanks for reading.

**Comment by Genesis-Legion** [comment]
This is a dsp problem, I'd suggest posting this over at the dsp bug tracker.
https://github.com/DarkstarProject/darkstar/issues
Teo mentioned that the server version shouldn't matter (for the dsp bug report)

**Comment by Samikana** [comment]
@Genesis-Legion don't close DSP bug reports so that players don't re-report.

**Comment by TeoTwawki** [comment]
@samikana I told him to. I've been closing all the homepoint warp issues, telling ppl "tell it to darkstar". Because these nee dot go there, not here. I would frankly like to see Darkstar _DROWN_ in homepoint reports till they do something about it.

**Comment by Samikana** [comment]
OK NP
