### ISSUE TITLE
kukulkan dropp 20% 10% 5%

### ISSUE THREAD

**Issue by bathuka** [LegionDark/Issues#92]
Date & Time: 13/06/2015
Frequency:
FFXI Client Version: 30150508_5
Character Name: Bathuka
Race: Elvaan
Main Job:pld
Sub Job:nin
Area & Coordinates:abyssea konchtat
Party or Solo:PARTY
NPC Name:
Monster Name: kukulkan do not dropp one kukulkan fang item 100% tks :)

**Comment by Loki79** [comment]
Be in Tuesday, or next crash/restart.
