### ISSUE TITLE
Slendix Spindlethumb Has Wrong Skin

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#920]
**Date & Time**: 
4/30/2016 - 00:01

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**: 
Buttons

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
BLU(99)/RDM(49)

**NPC or Monster or item Name**: 
Slendix Spindlethumb

**Zone name & Coordinates (use `@where`)**: 
Inner Horutoto Ruins - X: -238, Y: -0.5, Z: -167

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
I happened upon an Orc NM (Slendix Spindlethumb) in Inner Horutoto Ruins, which didn't seem right, so I looked him up online. He's supposed to be a Goblin NM. His job seemed to be correct (casted WHM spells on me) when I engaged. 

Not something major, obviously, but I thought I'd mention it.

Thanks for reading.

**Comment by TeoTwawki** [comment]
@R3P0FFXI This basically means whoever set him to actually be spawned never gave him a model at all (default = orc placeholder in client)
