### ISSUE TITLE
Reforged Relic/AF+1 for WHM still not working

### ISSUE THREAD

**Issue by Genesius1490** [LegionDark/Issues#921]
**Date & Time**: April 29 -- 9:30 A.M GMT+1

**FFXI Client Version (use `/ver`)**: 30160329_0

**Character Name**: Jenna

**Nation**: Bastok

**Job(level)/Sub Job(level)**: WHM99/RDM49

**NPC or Monster or item Name**: Moogle (moogle in tavnazian safehold)

**Zone name & Coordinates (use `@where`)**: Tavnazian safehold -- X:12 Y:-9 Z:0 (29)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/10672/clr-briault-2

**Multi-boxing? (multiple clients on same connection)**: yes and no, tried both

**Steps To Reproduce / any other info**: Trade Cleric Briault+2 with 25 Aptant:Tachus to moogle, nothing happens, no Reforged relic109 granted, same happens with Artifact+1 body.

PS: And yes I have all the Pre-requirement to do these items

**Comment by Genesis-Legion** [comment]
This is an extension of bug report #515 that was closed months ago.

**Comment by Genesis-Legion** [comment]
This is on the to-do list along with the other broken reforges.
