### ISSUE TITLE
Windurst Mission 9-2 Not Functioning

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#922]
**Date & Time**: 
04/30/2016 - 01:20

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**: 
Buttons

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
BLU(99)/RDM(49)

**NPC or Monster or item Name**: 
N/A

**Zone name & Coordinates (use `@where`)**: 
Heavens Tower - X:0, Y:-49, Z:38 (192)

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
After accepting Windurst mission 9-2, click on Vestal Chamber door in Heaven's Tower. Cutscene fails to activate. Can't complete the mission. 

I saw the DSP issue report at https://github.com/DarkstarProject/darkstar/issues/2486 about this not being scripted, but Genesis suggested in IRC that I post a report on our own github issue tracker as well.

Thanks for reading.

**Comment by TeoTwawki** [comment]
Sorry but. you are S.O.L. till someone code sit in DSP.

Also a word of advice: when it does show up in DSP, don't be a rush to get it done immediately, they have a nasty habit of leaving them in a broken state for months. Let someone else discover the bugs in the untested trash code they are likely to get from an idiot who uses MS word or wordpad as a code editor.

**Comment by Midgardsormr** [comment]
Okee-doke. Thanks.
