### ISSUE TITLE
Titanium Ore only stacks in singles

### ISSUE THREAD

**Issue by Genesis-Legion** [LegionDark/Issues#925]
Date & Time: 
5/2/2016 1AM cst

FFXI Client Version (use /ver): 
30160329_1

Character Name: 
Azazel

Nation: 
Bastok

Job(level)/Sub Job(level): 
RDM99/DNC49

NPC or Monster or item Name: 
Titanium Ore

Zone name & Coordinates (use @where): 
Anywhere

ffxiah.com link (for items issues only): 
http://ffxiclopedia.wikia.com/wiki/Titanium_Ore
(Stackable: 12)

Multi-boxing? (multiple clients on same connection): 
No

Steps To Reproduce / any other info: 
Get Titanium Ore to drop, only stacks in singles.

**Comment by R3P0FFXI** [comment]
@Genesis-Legion 

Per BG Wiki
https://www.bg-wiki.com/bg/Titanium_Ore

Stack SIze 1, this would need to be confirmed on retail before being changed as we now have a conflict of information

**Comment by Samikana** [comment]
Retail is 1, can confirm.

**Comment by Samikana** [comment]
Jk I just goofed.  I was thinking about something else. 

Stop github-ing and driving Sami! 

They stack to 12.

**Comment by R3P0FFXI** [comment]
@Samikana This needs retail verification

**Comment by Samikana** [comment]
It's listed as 12 on ffxiah.

**Comment by Genesis-Legion** [comment]
I looked at DSP's item_basic and it was fixed there, looks like it'll get pulled in eventually.

**Comment by R3P0FFXI** [comment]
@Samikana @Genesis-Legion Should be fixed in MUP2 now
