### ISSUE TITLE
Jeuno VW T6 upgrade displays wrong message.

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#927]
**Date & Time**: 5/2/2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/rdm49

**NPC or Monster or item Name**: Smierc (though I think it might happen with any t5 nm that is the last one fought before upgrade)

**Zone name & Coordinates (use `@where`)**: Tarongi Canyon X:204 y:15 Z:-679 (16)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: After fighting the last Jeuno T5 NM we fought and killed, the message said White Startum Abbysite V attained, which initially caused some confusion, making a few people think that we'd have to do t5 again.  I looked under Voidwatch Key items and saw that the abyssite did actually upgrade and showed as VI, but the message in the log shows V. Took a screencap

http://i.imgur.com/bk5eJl1.png

**Comment by TeoTwawki** [comment]
Which NM...

**Comment by TeoTwawki** [comment]
Smierc. you should just said smierc.

**Comment by TeoTwawki** [comment]
Hotfixed on server
