### ISSUE TITLE
Carabosse locking PoL

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#928]
**Date & Time**: 5/2/2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/rdm49

**NPC or Monster or item Name**: Carabosse

**Zone name & Coordinates (use `@where`)**: Fought him away from spawn, exact location - X:-125 Y:6 Z:72 (90)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: There was a guy farming carabosse and I went to help,he said PoL kept crashing, I went down and we popped about 5 times while I was there, I froze twice, when I did it seemed 2 or 3 other people would as well.  The party before I joined was a whm, sam, and war I believe, so it doesn't seem like a problem that is related to BLU, though I was blu when I joined pt, but the PoL crash was apparently happening even before I joined.

**Comment by TeoTwawki** [comment]
Nothing at all in this mob or its skills is capable of causing this.

**Comment by kelvenar** [comment]
Just a Short notice, i fought carabosse several times yesterday (multiboxing) and Never had any issues or crashes
