### ISSUE TITLE
Flying pig event ring (Tellluric Ring)

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#929]
**Date & Time**: 5/2/2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/rdm49

**NPC or Monster or item Name**: fought few nms in various places, carabosse for about 5 or 6 pops, as well as some Jeuno vw nms varying from t3-t6

**Zone name & Coordinates (use `@where`)**: Stayed longest at carabosse so I'll just give that location X:-125 Y:6 Z:72 (90)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: Teo said that the ring didn't work properly and after the last maintenance the potency would be increased.  I've had the ring on for most fights yesterday as well as today, I haven't seen the ring proc and resist any adverse effects.  No messages in chat log either.  Most notable fight was carabosse as it spams various negative status effects, didn't seem like any were being resisted.

**Comment by TeoTwawki** [comment]
this probably has to do with loki giving that bleeping pixie absurd amount of macc, combined with dsp not using resist traits correctly.

**Comment by TeoTwawki** [comment]
they seem to be treating the resistance entirely as part of the magic evasion calculation, instead of a % proc rate

**Comment by TeoTwawki** [comment]
p.s. :

When I beefed up the ring to compensate for it not proc'ing the resist, I also beefed up its multitude of other effects. Just so you know.

**Comment by TeoTwawki** [comment]
Fixed with today's update
