### ISSUE TITLE
Red Mage doesn't get Sanguine Blade

### ISSUE THREAD

**Issue by Genesis-Legion** [LegionDark/Issues#930]
Date & Time: 
5/2/2016 7:30 PM cst

FFXI Client Version (use /ver): 
30160329_1

Character Name: 
Azazel

Nation: 
Bastok

Job(level)/Sub Job(level): 
RDM99/DNC49

NPC or Monster or item Name: 

Zone name & Coordinates (use @where): 
Anywhere

ffxiah.com link (for items issues only): 

Multi-boxing? (multiple clients on same connection): 
No

Steps To Reproduce / any other info: 
Check WS list on RDM, missing WS Sanguine Blade. 
According to https://www.bg-wiki.com/bg/Sanguine_Blade RDM should have access to it. (my blu has access to it)
"Can only be used if you have Red Mage, Paladin, Blue Mage, Rune Fencer, Warrior, or Dark Knight as your main job or sub job."

**Comment by TeoTwawki** [comment]
I'll go over the WS list for next maint.

**Comment by TeoTwawki** [comment]
Haven't forgotten, giving the entire list of all ws's a check for any other misisng jobs like this.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/3386
