### ISSUE TITLE
Atma Infusionist in Aby Grauberg not giving atma buffs

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#931]
**Date & Time**: 5/2/2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: blu99/rdm49

**NPC or Monster or item Name**: Atma Infusionist 

**Zone name & Coordinates (use `@where`)**: Aby Grauberg X:-532 Y:26 Z:-774 (105)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: When you talk to the npc the only message you get is "Well met, wayfarer.  I am an Atma Infusionsit, and from my ltitle I do trust you can glean my field of expertise.  Those who possess a lunar abyssite may come to me to have atma infused"  Same message over and over. The box asks How may I serve you, the only two options are 'You may not' and 'Tell me about atma'

**Comment by TeoTwawki** [comment]
Fix'd
