### ISSUE TITLE
HP crystals in Ru'Aun Gardens

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#932]
**Date & Time**: 5/3/2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/rdm49

**NPC or Monster or item Name**: na

**Zone name & Coordinates (use `@where`)**: Ru'Aun Gardens HP crystal #2 X;-498 Y:-42 Z:164 (132)  HP crystal #3 X:312 Y:-42 Z:-421 (214)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: In Ru'Aun Gardens when you try teleporting using HP cyrstal 2, it takes you to HP cyrstal 3, and when you try warping to HP crystal 3 it wraps you to HP crystal 2.

**Comment by TeoTwawki** [comment]
see every other hp warp issue on this tracker: same anser
