### ISSUE TITLE
Abby NMS dropping more then 2 empy upgrade items

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Issues#936]
**Date & Time**: 5/9/2016 

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Baucant

**Nation**: Sandy

**Job(level)/Sub Job(level)**:Thf(99)/War(49) 

**NPC or Monster or item Name**: Apademak & Glavoid

**Zone name & Coordinates (use `@where`)**: Abyssea-Uleguerand @ X: -332.73, Y: -156.074, Z: 346.739 & Abyssea-Tahrongi @ X: 196, Y: 34, Z: 413

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/3289/apademak-horn & http://www.ffxiah.com/item/2927/glavoid-shell

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: Kill mob and occ. will get 3 drops

**Comment by R3P0FFXI** [comment]
@Baucant will be fixed in next update
