### ISSUE TITLE
Blazing Eruca's Incinerate TP move damage

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#937]
**Date & Time**: 
5/10/2016 - 06:04

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**: 
Buttons

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
BLU99/RDM49

**NPC or Monster or item Name**: 
Blazing Eruca

**Zone name & Coordinates (use `@where`)**: 
Abyssea - Attowha -  X: 233, Y: 19, Z: -243  (215)

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
No. 

**Steps To Reproduce / any other info**: 
First off, I want to say that I am not whining. ^^  

That said, it seems that Blazing Eruca's damage output has gone to an insane level since the last time my friends and I engaged it. The "Incinerate" TP move is doing 15K+ damage on each toon, wiping out entire party. I do not recall this being the case before. If I am mistaken, my apologies for the bug report.

Thanks for reading.

**Comment by R3P0FFXI** [comment]
@Midgardsormr https://github.com/LegionDark/Issues/issues/735 Duplicate ticket closing your issue

**Comment by Midgardsormr** [comment]
sorry 'bout that. thanks.
