### ISSUE TITLE
Black Curry Bun +1 | Unable to craft | Cooking 100

### ISSUE THREAD

**Issue by lwrand** [LegionDark/Issues#939]
**Date & Time**: 10/05/2016, 22:46 PM GMT+2

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Croexi

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BLU(99)/DNC(49)

**NPC or Monster or item Name**: Black Curry Bun +1

**Zone name & Coordinates (use `@where`)**: X:0 Y:0 Z:0 (192) - (MogHouse - Bastok Mines)

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/5764/b-curry-bun-1

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
Following the issue: https://github.com/LegionDark/Issues/issues/833, the NQ "Black Curry Bun" is now craftable but you can't pop the "+1 version". I keep getting "6x Black Curry Bun" (NQ) and "8x Black Curry Bun" (HQ1) but no HQ2 or HQ3.

Many thanks,
/Croex.

**Comment by R3P0FFXI** [comment]
@lwrand this is craftable with no issues it is a HQ 2/3 so just bad luck for you im afraid
