### ISSUE TITLE
Can not equip ammo with Annihilator 75 

### ISSUE THREAD

**Issue by rekcahniZe** [LegionDark/Issues#94]
Date & Time: 6/13/15
Frequency: Always
FFXI Client Version: 30150508_8
Character Name: Rekcah
Race: Hume
Main Job: Rng
Sub Job: Sam
Area & Coordinates: NA
Party or Solo: Any
NPC Name: NA
Monster Name: NA
Steps To Reproduce The Issue:

1) Equip Annihilator
2) Equip ammo (Tested Titanium, Steel, and silver bullet)

Note: Cannon Shells work

**Comment by Loki79** [comment]
fixed.  will be in Tuesday or next crash / restart
