### ISSUE TITLE
I lost my password on Hiya

### ISSUE THREAD

**Issue by qiganggang** [LegionDark/Issues#940]
**Date & Time**: 5/9/2016

**FFXI Client Version (use `/ver`)**: 30160329-1

**Character Name**: Hiya

**Nation**: sandy

**Job(level)/Sub Job(level)**: blu99/rdm49

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 
I want to find the Hiya code, can you help me find it?

**Comment by TeoTwawki** [comment]
@R3P0FFXI password reset, aisle seven.

**Comment by qiganggang** [comment]
How do I get it?

**Comment by TeoTwawki** [comment]
如果你不明白我在说什么，[ 为什么这么问？ R3P0FFXI 配来帮助你。](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/)

**Comment by qiganggang** [comment]
ok i waiting

**Comment by R3P0FFXI** [comment]
@qiganggang there are some serious questions regarding this account as this is not the first time we have recovered this for you. Not to mention a banned player was telling everyone he had purchased this account from you when he first started on this server. We are going to go back through the IP logs and if ANYONE but you has logged into this account I am not going to recover it.

**Comment by qiganggang** [comment]
When did you recover? Our account password here are playing together, my friend he has no play, so I want to find you to restore this ID, you can check to, has been nearly 1 months.

**Comment by qiganggang** [comment]
XD

**Comment by R3P0FFXI** [comment]
@qiganggang if its your friends account im not going to recover it for you im sorry but its his account not yours. You are sharing the account with your friend and these things take time to perform. Your friend wouldnt happen to be Fly would it as his accounts are all banned for the spam he did on the server. We will perform an investigation but if the IP do not match IE your IP and Hiya IP im not restoring the account for you.

**Comment by qiganggang** [comment]
You can check my original IP account registered a year ago

**Comment by qiganggang** [comment]
I'll wait for you to help me with this event.

**Comment by R3P0FFXI** [comment]
@qiganggang you need to PM me the account login and the new password on the forums and we will go ahead and reset this one last time for you

**Comment by qiganggang** [comment]
Change password for4892131

**Comment by R3P0FFXI** [comment]
@qiganggang you need to listen man PM ME your new password not post it here for the world to see, pick a new password and PM IT TO ME ON THE FORUMS. I will not use the password you placed here.

**Comment by qiganggang** [comment]
I will go to change, forum I will not send a post

**Comment by qiganggang** [comment]
Changed my own can go to the site to change the password.

**Comment by qiganggang** [comment]
I have been online, you help me to re set, I go to the site to change the password, because the forum I can not send the theme and news, looking for a long time did not find.

**Comment by qiganggang** [comment]
plz

**Comment by TeoTwawki** [comment]
> Change password for4892131

oh for fuck sake.

http://legiondark.com/forums/ucp.php?i=pm&mode=compose&u=48

or you could have left it with me this morning and I'd have passed it to him.

**Comment by R3P0FFXI** [comment]
@qiganggang STOP saying please and READ the instructions failure to follow them and just sitting here begging is NOT going to resolve your situation.

**Comment by qiganggang** [comment]
![qq 20160515093700](https://cloud.githubusercontent.com/assets/13742980/15271507/a95828b2-1a80-11e6-8b62-84a295440c6e.png)

**Comment by TeoTwawki** [comment]
张志贤掴网站管理员
brb..

**Comment by TeoTwawki** [comment]
@qiganggang try now


phpBB是垃圾

**Comment by qiganggang** [comment]
ok thanks

**Comment by R3P0FFXI** [comment]
@qiganggang All set Password has been reset
