### ISSUE TITLE
gorney moufles +1 legion gear upgrade

### ISSUE THREAD

**Issue by benfolka** [LegionDark/Issues#941]
**Date & Time**: 11/05/2016 - 07.18

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Clay

**Nation**: Sandy

**Job(level)/Sub Job(level)**: 99war/49dnc

**NPC or Monster or item Name**: Gorney muffles +1

**Zone name & Coordinates (use `@where`)**: Rolanberry fields

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/28010/gorney-moufles-1

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: http://legiondark.com/forums/viewtopic.php?f=40&t=594#p3462
it has been mentioned above you need gorney moufles + 5000 legion points + 20 tanzanite jewels
traded to moogle outside rolanberry fields.
i did them all and no response. Is the information wrong, is it not working? also traded 10 tanzanite jewels not working.

**Comment by R3P0FFXI** [comment]
@benfolka what NPC are you trying to trade this to? Whats its name?

**Comment by benfolka** [comment]
@where 243,24,480  (20)
its name is moogle

**Comment by TeoTwawki** [comment]
its 25 jewels and 2500 legion points
I guess someone changed things way way way long ago and never had the posts updated.

**Comment by benfolka** [comment]
you guys are great
