### ISSUE TITLE
Moongate pass Quest

### ISSUE THREAD

**Issue by djaffa** [LegionDark/Issues#942]
**Date & Time**: 13 May 2016 - 12h33 (GMT+1)

**FFXI Client Version (use `/ver`)**:  Ver 301603_29

**Character Name**: Djaffa & Arutai

**Nation**: Bastok & Sandoria

**Job(level)/Sub Job(level)**: Thf(99)/Dnc - Whm(99)/Rdm

**NPC or Monster or item Name**: Moongate pass quest

**Zone name & Coordinates (use `@where`)**: Ro'Maeve X:-179 Y:-5 Z:12 (12)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: unable to open Moongate on Full Moon between 00:00 - 03:00 Vanadiel time. in order to get the permanent Key Item "Moongate Pass" according to 

http://ffxiclopedia.wikia.com/wiki/Moongate_Pass_Quest

So impossible to pass door to kill NM Nargun who drop Aptant for reforged Armor

**Comment by TeoTwawki** [comment]
The gate is a darkstar issue.

when legion updates next I will bypass the problem.

**Comment by TeoTwawki** [comment]
Forgot to assign self and lost track of this. will get it taken care of soon, unless I already did and forgot >.>

**Comment by TeoTwawki** [comment]
Fix'd
