### ISSUE TITLE
Server transfer help

### ISSUE THREAD

**Issue by starkffxi** [LegionDark/Issues#943]
**Date & Time**: 3:39 5/13/2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Kensei

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: DRK75/WAR37

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

Cant seem to get the transfer exporter to work.  It says it fails to initialize required api for information collection. I downloaded the latest eliteapi file but dont know why it doesnt work

**Comment by Genesis-Legion** [comment]
Did you replace the eliteapi.dll that came with the exporter with the new one?

**Comment by starkffxi** [comment]
Yes

**Comment by atom0s** [comment]
http://legiondark.com/forums/viewtopic.php?f=37&t=398 explains everything you need to do before using the export tool.

**Comment by starkffxi** [comment]
Yeah I followed all the steps still can't get it to work

**Comment by R3P0FFXI** [comment]
@starkffxi did you actually extract the tool to its own directory or did you try to run it from within the zip file. The tool needs ot be extracted and run as admin on the latest version of FFXI not an old one with the newest eliteapi.dll. Based on the sheer number of migrations we are doing now with the free week you are doing something wrong.

**Comment by starkffxi** [comment]
Yeah I extracted but I'm trying to transfer from another private server so I don't know if its the latest version but I can log into your server should I try to update ffxi?

**Comment by starkffxi** [comment]
I just checked in the other private server with /ver and its 30160329_1

**Comment by atom0s** [comment]
"fails to initialize required api" means you failed to do one of a few things:
  * You didn't install the required runtime files.
  * You didn't run the tool as an Administrator.
  * Your boot loader is not named pol.exe (Usually a Windower issue since they use the boot loader wrong.)

**Comment by starkffxi** [comment]
ill just start from scratch
