### ISSUE TITLE
Need Password Reset

### ISSUE THREAD

**Issue by Kri77777** [LegionDark/Issues#944]
I need a password reset. After reaching out on IRC, TeoTwawki told me to reach out to R3P0FFXI who in turn told me to file a ticket. (Note: I tried to do via forum PM but am told I don't have enough posts).

Account: Kri77777
Forum Name: Kri77777
Main Character: Landon
Main Character: Should be BLM (been very long time)

**Comment by R3P0FFXI** [comment]
@Kri77777 Please PM me a new password on the forums so i can reset this for you.

**Comment by R3P0FFXI** [comment]
@Kri77777 all set have fun
