### ISSUE TITLE
Password reset incorrectly

### ISSUE THREAD

**Issue by Rennie-Boy** [LegionDark/Issues#945]
**Date & Time**:  15/05/2016 11:35

**FFXI Client Version (use `/ver`)**: 30160329-1

**Character Name**: Rennie

**Nation**: Sandy

**Job(level)/Sub Job(level)**: 10War

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: La Theine

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: Hi guys R3P0FFXI was kind enough to reset my password for me as I kept forgetting it but I don't think it's been changed correctly. I can no longer sign into the game or the site using the new or even the old password. Any chance it can be reset again? Thanks.

**Comment by R3P0FFXI** [comment]
@Rennie-Boy All set check PM on forums
