### ISSUE TITLE
Bloodheart Imported character crafts

### ISSUE THREAD

**Issue by BL00DHEART** [LegionDark/Issues#946]
**Date & Time**:
 05-15-16 10:10pm PST

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**:
 Bloodheart

**Nation**:
 Bastok

**Job(level)/Sub Job(level)**: 
THF55

**NPC or Monster or item Name**: 
N/A

**Zone name & Coordinates (use `@where`)**: 
Port Bastok X:112 Y:8 Z:-22 (131)

**ffxiah.com link (for items issues only)**:
 N/A

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Just imported my character from another server and would like crafting imported. If only 1 can be selected i would choose Smithing as it is the highest. Thank you.

![bloodheart_craft](https://cloud.githubusercontent.com/assets/19382329/15280946/3c252068-1aeb-11e6-814d-19e3052c1153.png)

**Comment by Genesis-Legion** [comment]
I took care of importing his smithing skill as he requested.
