### ISSUE TITLE
Magicked Astrolabe not available from Churano-Shurano

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#948]
**Date & Time**: 
05/17/2016

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**: 
Buttons

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
BLU99/RDM49

**NPC or Monster or item Name**: 
Churano-Shurano

**Zone name & Coordinates (use `@where`)**: 
Windurst Waters / X:-59, Y:-10, Z:100 (175)

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Churano-Shurano is supposed to sell a Magicked Astrolabe (for solo access to Eldieme Necropolis gates) for 10,000 gil. He doesn't sell it. When you talk to him, he only gives you a line of dialogue. I also tried just trading 10,000 gil to him. 

I searched for a reference to this in the LegionDark and Darkstar issues, but didn't find one. 

Thanks for reading.

**Comment by R3P0FFXI** [comment]
@Midgardsormr this needs to be PR to DSP this would not be something we code wait until the update drops and if it still does not work report it to DSP

**Comment by Midgardsormr** [comment]
10-4. 

Just curious... if you know... is it the item that's broken (and therefore sale is not implemented) or is the sale just not implemented?

**Comment by R3P0FFXI** [comment]
@Midgardsormr no idea as this is content we consider handled by DSP this is not something we would implement or work on with our time.

**Comment by R3P0FFXI** [comment]
@Midgardsormr ticket submitted to DSP for issue this has still not been fixed 

https://github.com/DarkstarProject/darkstar/issues/3825

**Comment by Barftarr** [comment]
Hello!  I ran into this today and noticed it sounds like a fix is possibly ready.  Was just curious if another maintenance cycle had to take place in order for it to be implemented. I tried looking around for that and couldn't find it, so apologies if I'm being a noob.

Also just want to say I really like what you guys have going here, been great hopping back into the game :).

Thanks for any info you can provide!

**Comment by TeoTwawki** [comment]
yeah it won't be in until maint happens

**Comment by Barftarr** [comment]
Awesome!  Appreciate the update and info :).

**Comment by R3P0FFXI** [comment]
@Midgardsormr issue resolved in todays update
