### ISSUE TITLE
~ The tigress strikes ~ NPC not giving quest 

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#949]
**Date & Time**: 19/05/2016
**FFXI Client Version

**: 30160329_1
**Character Name**: nanatuttatana
**Nation**: windurst
**Job(level)/Sub Job(level)**: 99 whm/ 49rdm
**NPC or Monster or item Name**:  Dhea Prandoleh
**Zone name & Coordinates**: windurst waters (S) X2; Y-1; Z15; (254)
**Multi-boxing? (multiple clients on same connection)**: no
**Steps To Reproduce / any other info**: the NPC isn't giving the quest "The tigress strikes" (had no problem with the previous quest from the same npc), needed to complete the WotG mission 2 "Back to the beginning" (VW pre-req).
She says her dialogue (see ss) but the quest doesn't appear under the "active quests" tab.
Thank you.
![nanatuttatana_2016 05 19_160221](https://cloud.githubusercontent.com/assets/12772770/15396190/37e62d56-1ddb-11e6-9dc5-bd51b5beacf4.jpg)

**Comment by R3P0FFXI** [comment]
@simthra Just go join a city in the past No WOTG is coded past Mission 1

**Comment by TeoTwawki** [comment]
VW pre-req is to have joined one of the armies only, don't have to go beyond "snake on the plains" if joining windurst.

**Comment by TeoTwawki** [comment]
which btw is a quest, not a mission. any probs with these are dsp bugs anyway, so closing
