### ISSUE TITLE
Gancanagh (Aby Tahrongi NM) missing item from loot pool.

### ISSUE THREAD

**Issue by Genesis-Legion** [LegionDark/Issues#95]
Date & Time: 6/14/15 2:05 am cst
Frequency: Always
FFXI Client Version: 30150508_8
Character Name: Genesis
Race: Hume
Main Job: War
Sub Job: Sam
Area & Coordinates: Abyssea - Tahrongi
Party or Solo: Party
NPC Name: NA
Monster Name: Gancanagh
Steps To Reproduce The Issue:

Killed Gancanagh trying to get a Chloris pop, checked mob tool and the item "Acidic Humus" is not in it's loot pool therefore unable to progress.

**Comment by Loki79** [comment]
Fixed.  Be in tuesday or next crash/restart.
