### ISSUE TITLE
Sununu Crafting Skill

### ISSUE THREAD

**Issue by Nususu** [LegionDark/Issues#950]
**Date & Time**: 5/19/16 6PM MST

**FFXI Client Version (use `/ver`)**: 30160427_0

**Character Name**: Sununu

**Nation**: Bastok

**Job(level)/Sub Job(level)**: 90BRD/45WHM

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: X:5 Y:3 Z:118 (79)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: just need crafting skills restored from Retail Server transfer. skills included in attached photo.
<img width="866" alt="screen shot 2016-05-19 at 6 03 43 pm" src="https://cloud.githubusercontent.com/assets/19480479/15413303/12d6ae94-1dec-11e6-9a9b-87fe33417305.png">

**Comment by Genesis-Legion** [comment]
Tried to get in touch with you ingame but you were afk.
I should be on tomorrow sometime and I'll check again.

**Comment by Nususu** [comment]
Hi, sorry I was afk when you tried. Is there some info I can provide to you via email? I'm at work right now and am not sure when I will be online tomorrow. 

Thank you for taking care of this!

Sent from my iPhone

On May 20, 2016, at 3:38 PM, Genesis <notifications@github.com> wrote:

Tried to get in touch with you ingame but you were afk.
I should be on tomorrow sometime and I'll check again.

**Comment by Genesis-Legion** [comment]
I'll hop back on rq and take care of it

**Comment by Genesis-Legion** [comment]
I'll take care of it right now since you're online.

**Comment by Genesis-Legion** [comment]
All your crafts have been updated besides synergy, should be good to go.

**Comment by Nususu** [comment]
Thank you for taking care of that!

On Fri, May 20, 2016 at 3:54 PM, Genesis <notifications@github.com> wrote:

> All your crafts have been updated besides synergy, should be good to go.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/LegionDark/Issues/issues/950#issuecomment-220727592>
>



-- 
Dylan Shearer
Marriott School of Management | Brigham Young University
mobile: (508) 314-9892 | sdshearer26@gmail.com
LinkedIn: www.linkedin.com/in/shearerdylan
