### ISSUE TITLE
Ragnarok Crafting Transfer

### ISSUE THREAD

**Issue by ragnarokLD** [LegionDark/Issues#951]
**Date & Time**:  22May16, 0724
**FFXI Client Version (use `/ver`)**: Latest Patch
**Character Name**: Ragnarok
**Nation**: San d'Oria
**Job(level)/Sub Job(level)**: 99WAR
**NPC or Monster or item Name**: NA
**Zone name & Coordinates (use `@where`)**: Southern San d'Oria
**ffxiah.com link (for items issues only)**: NA
**Multi-boxing? (multiple clients on same connection)**: NA
**Steps To Reproduce / any other info**: Submitting ticket for crafting level to be restored after transfer.

![liam_2016 05 19_073223](https://cloud.githubusercontent.com/assets/19517560/15454487/9b20f698-1fee-11e6-8f1d-6252ac7eb069.png)

**Comment by ragnarokLD** [comment]
Also do merits transfer over or just merits points?

**Comment by Samikana** [comment]
> Your limit and merit points will be imported.

This is a quote directly from the info guide on the forums.  You will need to re-do your merits.

Player was not online at 14:55 EST 16/5/22.

**Comment by ragnarokLD** [comment]
I saw that, wasn't sure since I saw my 16 GK merits then it vanished.  Thank you.

**Comment by ragnarokLD** [comment]
currently online for craft transfer.

**Comment by PikaFox** [comment]
Gave player goldsmithing 100 as per server transfer craft.
