### ISSUE TITLE
Homepoint Teleport Providing Teleport Destinations Not Open to User

### ISSUE THREAD

**Issue by Kri77777** [LegionDark/Issues#953]
Date & Time: 
2016-05-22

FFXI Client Version (use /ver): 
30160329_1

Character Name: 
Landon

Nation: 
San d'Oria

Job(level)/Sub Job(level): 
N/A

NPC or Monster or item Name: 
N/A

Zone name & Coordinates (use @where): 
All HomePoints

ffxiah.com link (for items issues only): 
N/A

Multi-boxing? (multiple clients on same connection): 
No

Steps To Reproduce / any other info: 
I did a character import from Retail. When I was imported, my Mog House had all jobs unlocked.

1. Go to a homepoint
2. When asked where to teleport, select "Favorites"
3. From list of favorites, select an item and remove it
4. Go back to list of favorites

Expected result: Same favorites list (minus the one removed)
Actual result: Seeing all different home points, including to places a user may not have visited

**Comment by R3P0FFXI** [comment]
@Kri77777 we don't import everything possible from retail or the other servers and favorites or anything you had stored are going to be gone. 

Also homepoint issues are a DSP problem not ours we have done nothing to the homepoint system so if things are incorrect on it then its a DSP issue.

**Comment by smokey56** [comment]
Thanks for the quick response.  Guess I'll dust off the traveling boots and start getting them back.

**Comment by TeoTwawki** [comment]
Aim for the ones you can't live without for now, I'll try and not leave you folks hanging to long on that replacement.
