### ISSUE TITLE
Wikyo Cloak lets you wear a head piece

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#954]
**Date & Time**: 
May 25, 2016
4:00 PM (MST)

**FFXI Client Version (use `/ver`)**: 
N/A

**Character Name**: 
tbone
pockethealer

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
N/A

**NPC or Monster or item Name**: 
Hurkan

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/10292/wikyo-cloak

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 

Wikyo Cloak lets you wear a head piece, even tho it says cannot equip head gear.

**Comment by Samikana** [comment]
It's because there's no value in rslot other than maybe 0.

**Comment by R3P0FFXI** [comment]
@tb1 issue resolved
