### ISSUE TITLE
Carabosse & Baba Yaga | Abyssea - La Theine | Freezing video (Audio keep playing)

### ISSUE THREAD

**Issue by lwrand** [LegionDark/Issues#955]
**Date & Time**: 
28/05/2016 at 7.38 PM GMT+2

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**: 
Croexi

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
BLU(99)/DNC(49)

**NPC or Monster or item Name**: 
Carabosse and Baba Yaga

**Zone name & Coordinates (use `@where`)**: 
Abyssea - La Theine | X:-35 Y:16 Z:44 (41)

**Multi-boxing? (multiple clients on same connection)**: 
Both solo and multiboxing

**Steps To Reproduce / any other info**: 
Both "Baba Yaga" and "Carabosse" seem to have some sort of bug which freezes my video, while I keep hearing the audio in the background. It started this morning with "Baba Yaga" then I think that the server was restarted so I tried again, and  I was finally able to kill it without any issue. Moving on with "Carabosse" I have the same issue, freezing my screen (I tried multiple times, first multiboxing, then solo as I did the day before with "Baba Yaga"). The issue seems totally random with no connection with ability and/or spells (it can start in the early fight or after "Carabosse" does Benediction). I have modded icons and maps, and the following addons: "Distance" and "TParty" and plugins: "Config" and "Timers".

Many thanks,
/Croex.

**Comment by R3P0FFXI** [comment]
@lwrand This is not a server issue but a client one, check your drivers and settings try reupdatng FFXI

**Comment by lwrand** [comment]
@R3P0FFXI I retried this morning with a friend and he freezes at the same time with me.
