### ISSUE TITLE
Can't complete San d'Oria Mission 2-3 "Journey Abroad"

### ISSUE THREAD

**Issue by v4gr4nt** [LegionDark/Issues#956]
**Date & Time**: 
May 29, 2016
2:00 PM (EST)

**FFXI Client Version (use `/ver`)**: 
30160427_0

**Character Name**: 
Vagrant

**Nation**: 
San d'Oria

**Job(level)/Sub Job(level)**: 
73 RDM / 36 BML

**NPC or Monster or item Name**: 
Item: Mythril Sand 
NPC: Savae E Paleade

**Zone name & Coordinates (use `@where`)**: 
Metalworks - Consulate of San d'Oria
X:21 Y:-16 Z:-39 (49)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/599/mythril-sand

**Multi-boxing? (multiple clients on same connection)**: 
Nop

**Steps To Reproduce / any other info**: 
I'm doing San d'Oria Mission 2-3 "Journey Abroad" - Bastok first
I already talked to Pius and Grohm, and double checked that I followed all the steps, but when I trade the "Mythril Sand " to "Savae E Paleade" nothing happens and I can't continue the mission.
I already tried to zone out and log out, but nothing works.
I don't know If it is related, but when I finished the mission 2-1 I was offered 2-2 and 2-3, I just accepted 2-3 without completing 2-2 first.
It seems another linkshell member completed this mission without any problem a few days ago. 
I hope it is possible to fix the bug or at least let me start 3-1 please.
Thank you

**Comment by TeoTwawki** [comment]
possibly from client being newer than server and would resolve itself once legion catches up

**Comment by Samikana** [comment]
No response from player after 3 days.  Closing.
