### ISSUE TITLE
To cure a cough Quest

### ISSUE THREAD

**Issue by sucidaldeathtar** [LegionDark/Issues#957]
**Date & Time**: 
May 29, 2016 19:30pm est

**FFXI Client Version (use `/ver`)**: 

**Character Name**: 
sucidaldeath

**Nation**: 
sandy

**Job(level)/Sub Job(level)**: 
34thf/17rdm

**NPC or Monster or item Name**: 
NPC Nenne 

**Zone name & Coordinates (use `@where`)**: 
Southern San d'Oria (F-6)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
Started To Cure a Cough and went to cutsence and it just stopped when a npc was going to come through door

**Comment by TeoTwawki** [comment]
incomplete template, and this is extremely likely to be version related

**Comment by R3P0FFXI** [comment]
@sucidaldeathtar what ffxi version are you on type /ver in game

**Comment by sucidaldeathtar** [comment]
30160427_0

**Comment by TeoTwawki** [comment]
yeah client newer than server, it'll be normal once legion catches up

**Comment by sucidaldeathtar** [comment]
Ok thank you :)
