### ISSUE TITLE
Warding Vampires Quest

### ISSUE THREAD

**Issue by sucidaldeathtar** [LegionDark/Issues#958]
**Date & Time**: 
May 29, 2016 12pm est

**FFXI Client Version (use `/ver`)**: 
30160427-0

**Character Name**: 
sucidaldeath

**Nation**: 
sandy

**Job(level)/Sub Job(level)**: 
33thf/16rdm

**NPC or Monster or item Name**: 
Orcish Cursemakers

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/1018/shaman-garlic

**Multi-boxing? (multiple clients on same connection)**: 
no

**Steps To Reproduce / any other info**: 
Mob doesn't drop the item

**Comment by R3P0FFXI** [comment]
@sucidaldeathtar  Bulb Of Shaman Garlic (Item Id: 1018) confirmed this does not drop

**Comment by Jessland86** [comment]
This was handled some time ago, the mobs drop the item currently. http://legiondark.com/db/items/1018/bulb_of_shaman_garlic
