### ISSUE TITLE
BRD quest

### ISSUE THREAD

**Issue by kyokofu** [LegionDark/Issues#959]
**Date & Time**: 
6/1/2016
3pm pdt

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**: 
Kyokofukada

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
99blu/49rdm

**NPC or Monster or item Name**: 
Poetic Parchment

**Zone name & Coordinates (use `@where`)**: 
Lower Jeuno
X:-17 Y:0 Z:-61 (209)

**ffxiah.com link (for items issues only)**: 
http://www.ffxiah.com/item/634/poetic-parchment

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
I was doing the quest to get bard job. After trading a parchment to obtain the poetic parchment needed to start and complete the next quest, I headed to Jeuno to trade the Mertaire the item but it was nowhere to be found. No, I didn't throw anything away and checked the log to make sure it did say I obtain the poetic parchment and it does. The Old Monument quest is also completed thus confirming I should have gotten the poetic parchment. I tried going back to trade another parchment to the song rune but nothing happens. I tried talking to Mertaire and Bki Tbujhja again but nothing happens. Now I can't complete the bard job quest.

**Comment by R3P0FFXI** [comment]
@kyokofu This is most likely due to an ID shift in the client. As we have not updated for the new client yet this is why it does not work. Once we update the issue will resolve itself.

**Comment by Samikana** [comment]
Please re-submit your bug report if the problem persists after the update.  There is currently no ETA on when the maintenance will be.  There will be an announcement both in-game and on our homepage when we have more information.
