### ISSUE TITLE
COP 1-3: The Mothercrystals

### ISSUE THREAD

**Issue by helixhamin** [LegionDark/Issues#96]
So, I had to have the mission fixed, but did not complete it immediately. Now, when I check the shattered telepoint, I get the "The telepoint has been shattered into a thousand pieces..." message, no matter which craig I try it at. I do not enter the staging area, do not enter the promy, just get the message and nothing. I do get the proper message from Harith in Jeuno.

**6/14/2015 4:50 PM**: 
**Always**:
**30150508_5**:
**Weijun/Delaide/Yuehan**:
**Hume/Hume/Mithra**:
**PLD/WHM/MNK**:
**WAR/SCH/WAR**:
**Every shattered crystal**:
**Party**:
**Shattered Telepoint**:
**N/A**:
**Go click the telepoint, and nothing but the message happens**:

**Comment by R3P0FFXI** [comment]
You are on the incorrect version of the client 30150808_8 is the current version update and try again

**Comment by helixhamin** [comment]
Trying now, will close if successful

**Comment by helixhamin** [comment]
Nope, still same error

**Comment by helixhamin** [comment]
Just a note, it was originally fixed during this bug: https://github.com/LegionDark/Issues/issues/14
Could it be that?

**Comment by R3P0FFXI** [comment]
added KI 590 light of holla for user now able to enter

**Comment by helixhamin** [comment]
All good.
