### ISSUE TITLE
Unable to boot 

### ISSUE THREAD

**Issue by fgebony** [LegionDark/Issues#960]
-edit- after doing some playing around I fixed it please close sorry for the wasted time :(

**Date & Time**:  6/5/16 3:18 AM

**FFXI Client Version (use `/ver`)**: Fresh Install

**Character Name**: N/a

**Nation**: N/a

**Job(level)/Sub Job(level)**:  N/a

**NPC or Monster or item Name**: N/a

**Zone name & Coordinates (use `@where`)**: N/a

**ffxiah.com link (for items issues only)**: N/a

**Multi-boxing? (multiple clients on same connection)**: N/a 

**Steps To Reproduce / any other info**: Fresh install of game and followed the guide precisely but when I open through Ashita, after logging in the dos window closes but nothing loads. I looked all over forums and Q&A sections, cannot figure out what I am doing wrong. if you had any I'd be super thankful.

![screenshot 2016-06-05 02 52 27](https://cloud.githubusercontent.com/assets/19757826/15804130/6c0a7800-2acc-11e6-9e36-74b6cc0cf6e8.png)

**Comment by R3P0FFXI** [comment]
Closing
