### ISSUE TITLE
Cannot put Avant Cuisses +1 on Auction House

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#961]
Date & Time: 
06/05/2016 - 06:53

FFXI Client Version (use /ver): 
30160329_1

Character Name: 
Buttons

Nation: 
Windurst

Job(level)/Sub Job(level): 
BLU99/RDM49

NPC or Monster or item Name: 
Avant Cuisses +1 

Zone name & Coordinates (use @where): 
Any

ffxiah.com link (for items issues only): 
http://www.ffxiah.com/item/11975/avant-cuisses-1

Multi-boxing? (multiple clients on same connection): 
No

Steps To Reproduce / any other info: 
Try putting "Avant Cuisses +1" on the Auction House. It lets you set price, but fails to progress beyond the "Sell/Cancel" dialog box. I did notice them mistakenly flagged as "No Auction" in the database tool, and you can still bazaar them. 

I searched for a reference to this in the LegionDark and Darkstar issues, but didn't find one. I'm assuming it's a DSP thing rather than a LegionDark thing. 

Thanks for reading.

**Comment by R3P0FFXI** [comment]
@Midgardsormr this issue should now be corrected in DSP and Legion
