### ISSUE TITLE
CoP 8-3 not working

### ISSUE THREAD

**Issue by Greyhulk** [LegionDark/Issues#962]
**Date & Time**: 6/6/2016

**FFXI Client Version (use `/ver`)**: 30160427_0

**Character Name**: Zallen

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 99thf/49dnc

**NPC or Monster or item Name**: N/A

**Zone name & Coordinates (use `@where`)**: Garden of ru'hmet X:420 Y:0 Z:397 (158)

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: N/A

**Steps To Reproduce / any other info**: Got the brand and mark of dawn went up elevator to initate cutscene and battlefield but it just clicks off the door tried relogging and rezoning still messes up.

**Comment by TeoTwawki** [comment]
most likely because of version issues (client and server not matching)

**Comment by Samikana** [comment]
File another bug report after server is updated if the problem still persists.  At this point there is no ETA for the maintenance and you will need to hold tight.
