### ISSUE TITLE
Crafting skill

### ISSUE THREAD

**Issue by rimtice** [LegionDark/Issues#963]
![piglorian_2016 05 17_222230](https://cloud.githubusercontent.com/assets/11727709/15833575/0bf0b71e-2bed-11e6-9a07-cc645e82cb5e.png)

**Date & Time**: 

**FFXI Client Version (use `/ver`)**: 
30160427_0

**Character Name**: 
Piglorian

**Nation**: 
Windy

**Job(level)/Sub Job(level)**: 
THF99/WAR49

**NPC or Monster or item Name**: 
n/a

**Zone name & Coordinates (use `@where`)**: 
Konschtat Highlands

**ffxiah.com link (for items issues only)**: 
n/a

**Multi-boxing? (multiple clients on same connection)**: 
n/a

**Steps To Reproduce / any other info**: 
n/a

**Comment by R3P0FFXI** [comment]
@Genesis-Legion Gen can you take care of this when you have a moment

**Comment by Samikana** [comment]
Player wasn't online at 9:34 16/6/17

**Comment by Genesis-Legion** [comment]
@rimtice Leave a comment here next time you get a change to be online Pig.

**Comment by rimtice** [comment]
I'm currently online

**Comment by Genesis-Legion** [comment]
I was out at the time, I'll try and stay online tonight if you get a chance to get online.

**Comment by rimtice** [comment]
I'm on

**Comment by PikaFox** [comment]
Restored player's alchemy.

**Comment by Genesis-Legion** [comment]
@PikaFox He was transferring his retail crafts, meaning he could keep all of them and not just one as if he were transferring from another private server. I restored his cooking since that's the only one he really wanted.
