### ISSUE TITLE
Equipped Krousis Ring unsorts all inventories upon zoning

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#964]
Date & Time:
06/07/2016 - 05:06

FFXI Client Version (use /ver):
30160329_1

Character Name:
Buttons

Nation:
Windurst

Job(level)/Sub Job(level):
BLU99/RDM49

NPC or Monster or item Name:
Krousis Ring

Zone name & Coordinates (use @where):
Any

ffxiah.com link (for items issues only):
http://www.ffxiah.com/item/15849/krousis-ring
(Limit-break reward version of the ring)

Multi-boxing? (multiple clients on same connection):
No

Steps To Reproduce / any other info:
When zoning with the "Krousis Ring" (limit-break reward version) equipped in either ring slot, it unsorts your inventory and all Mog House storages. You can zone with it unequipped and there is no issue. 

If you open up the inventory quickly after zoning, you can see the ring hangs at the top for a second then everything else populates unsorted. 

I do not know if the regular version of the ring (if it exists in-game) does this. 

I searched for a reference to this in the LegionDark and Darkstar issues, but didn't find one. I did find something similar regarding the Senjuinrikio doing the same thing, though. (https://github.com/DarkstarProject/darkstar/issues/2902)

Thanks for reading.

**Comment by R3P0FFXI** [comment]
Issue should be resolved

**Comment by TeoTwawki** [comment]
> Issue should be resolved

Doubt it since that was DSP bug

But we can't do jack about it so issue can stay closed.
