### ISSUE TITLE
Broken Spawn

### ISSUE THREAD

**Issue by Danyeul** [LegionDark/Issues#965]
**Date & Time**: 
June 07, 2016 1:14PM

**FFXI Client Version (use `/ver`)**: 
30160329_1

**Character Name**: 
Orange
Juice

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
THF99/WAR49
WHM99/RDM49

**NPC or Monster or item Name**: 
Juggler Hecatomb

**Zone name & Coordinates (use `@where`)**: 
Gusgen Mines @ X: -138.821, Y: 2.603, Z: 337.125 

**ffxiah.com link (for items issues only)**: 
N/A

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Mob currently respawns immediately after death.  Was not like this, as it had at least a 21-24 hour respawn.  Game changing due to item drops available on this revised notorious monster.

![img_20160607_130102](https://cloud.githubusercontent.com/assets/18524779/15873237/7b3e8eaa-2cb2-11e6-9506-a4f30b0ee676.png)
![img_20160607_130949](https://cloud.githubusercontent.com/assets/18524779/15873239/7b3f7d7e-2cb2-11e6-85c6-00c0040fb17d.png)
![img_20160607_131222](https://cloud.githubusercontent.com/assets/18524779/15873235/7b3c504a-2cb2-11e6-99be-efcb6d8b71d1.png)
![img_20160607_131324](https://cloud.githubusercontent.com/assets/18524779/15873238/7b3e9dbe-2cb2-11e6-8761-9f79d09b5a4d.png)
![img_20160607_131913](https://cloud.githubusercontent.com/assets/18524779/15873236/7b3df1de-2cb2-11e6-9a7d-ed0e5854aec0.png)
![img_20160607_131948](https://cloud.githubusercontent.com/assets/18524779/15873243/841f65b2-2cb2-11e6-876d-a98d63619286.png)

http://imgur.com/a/W8nvA

**Comment by Danyeul** [comment]
More images of death, timestamps, etc.

http://imgur.com/a/pv2J8

**Comment by Genesis-Legion** [comment]
According to Minikay, Ash dragon has the same problem.

**Comment by TeoTwawki** [comment]
trying something now to see if I have the cause...

**Comment by TeoTwawki** [comment]
need someone to kill it and tell me if my fix works

**Comment by Genesis-Legion** [comment]
They still spawn immediately after being killed, tested both Duke Haborym, and Ash Dragon

**Comment by TeoTwawki** [comment]
I'm stumped. those are both scripted correctly

**Comment by TeoTwawki** [comment]
and duke hasn't been touched at all, no way to have broken it from its previously working state. so confused now.

**Comment by R3P0FFXI** [comment]
@Danyeul can you please confirm if this is still an issue

**Comment by Genesis-Legion** [comment]
Well I can confirm that Duke Haborym doesn't respawn immediately anymore

**Comment by TeoTwawki** [comment]
maybe the reboot we had fixed whatever derp the server was having. I couldn't find any reason for it in code..

**Comment by Genesis-Legion** [comment]
I could go kill ash dragon if you wanted me to confirm that real quick

**Comment by TeoTwawki** [comment]
check jugggler hecatomb

**Comment by Genesis-Legion** [comment]
It's not up, you're all clear Teo

**Comment by TeoTwawki** [comment]
spawn it, kill it, see if it repops

**Comment by Genesis-Legion** [comment]
Seems to be fine now, no respawn

**Comment by R3P0FFXI** [comment]
@TeoTwawki the reboot was due to the time being all off on the server. atom0s stated specifically that CPU calculations were all FUBAR so its a safe bet this was also affected. I think you and I need to setup a specific time to perform weekly/biweekly resets to avoid this in the future

**Comment by TeoTwawki** [comment]
@R3P0FFXI I'd much prefer to learn how they got fubar so that uptime didn't have to be effected by a restart.
