### ISSUE TITLE
Missing linkpearl and broken custom items

### ISSUE THREAD

**Issue by taisae** [LegionDark/Issues#967]
**Date & Time**: 
6/7/2016: 7:30pm-9:00pm mst

**FFXI Client Version (use `/ver`)**: 
30160427_0

**Character Name**: 
Taisae

**Nation**: 
Sandoria

**Job(level)/Sub Job(level)**: 
thf99/dnc49  ***edited because i put the wrong job in***

**NPC or Monster or item Name**: 
Legiondark Linkpearl (this is missing and no one can trade it to me) ***Edited to clarify this is the community pearl***

Custom Items (I think):
I think i got these from Maat in the past.
Krousis (missing the blue text stats)
Iwatsubute (missing the blue text stats)
Goblin Cest (missing the blue text stats)

**Zone name & Coordinates (use `@where`)**: 
x0 y0 z0 (192)

**ffxiah.com link (for items issues only)**: 
Custom items (I think).

**Multi-boxing? (multiple clients on same connection)**: 
No

**Steps To Reproduce / any other info**: 
Unsure. I recently returned to the game and am missing my linkpearl and the 3 items listed above are missing the blue text to them. I believe they were from Maat but could be mistaken. I checked with my wifes account (Ilsewitch) and she still has her link pearl and her items she got still have the blue stats.

**Comment by PikaFox** [comment]
Maat items should be able to be traded to maat to re obtain augments given the conditions to receive said augments are met (LB completed + job level high enough)

http://legiondark.com/forums/viewtopic.php?f=40&t=658&p=3542&hilit=maat#p3542

**Comment by taisae** [comment]
Ah okay thanks for the information! I will go check that out tonight.

for the linkpearl, I'm assuming i need to be online to receive one (for the community LS)?

**Comment by PikaFox** [comment]
Yeah; any GM can give you one, youd just need to be online when they are.

**Comment by taisae** [comment]
Awesome thanks so much for the help I appreciate it very much.

**Comment by Samikana** [comment]
Need to know if you got a pearl already, or if you still need one.

**Comment by taisae** [comment]
I received it. Thanks so much for the follow up though!
