### ISSUE TITLE
Unable to obtain Signet effect

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#968]
Date & Time:
06/08/2016 - 01:08

FFXI Client Version (use /ver):
30160329_1

Character Name:
Buttons

Nation:
Windurst

Job(level)/Sub Job(level):
BLU99/RDM49

NPC or Monster or item Name:
Any city guard

Zone name & Coordinates (use @where):
Any city

ffxiah.com link (for items issues only):
N/A

Multi-boxing? (multiple clients on same connection):
No

Steps To Reproduce / any other info:
Ask any city guard to cast Signet on my toon. They go through the motions (i.e. text and animation), but no Signet effect is applied and there's no Signet icon appearing with my other status effects.

(Note: Even though the icon never displays, I do get a "Buttons'  Signet effect wears off" message about a second or two after the casting animation)

I thought it might just be an icon display issue, but I later died in battle and wasn't given the option to be revived.

I've tried a number of guards in different cities with no luck. 

Thanks for reading.

**Comment by Midgardsormr** [comment]
FYI... other people are reporting the same issue.

**Comment by atom0s** [comment]
Confirmed this is a problem. On Atomos I cannot get signet. On an alt character I can.

**Comment by atom0s** [comment]
Some more info looking into this:
```
duration = (player:getRank() + getNationRank(player:getNation()) + 3) * 3600;
...
player:addStatusEffect(EFFECT_SIGNET,0,0,duration); -- Grant Signet
```

duration on Atomos is 50400, on my alt it's 18000. Seems like the duration is too high for normal players or something and its being killed. Anything over 18000 seems to die instantly.

**Comment by atom0s** [comment]
This should now be fixed.

**Comment by Midgardsormr** [comment]
thank you!!
