### ISSUE TITLE
Cannot activate Iron Portcullis to enter Castle Oztroja (S)

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Issues#969]
Date & Time:
06/09/2016 - 00:46 PST

FFXI Client Version (use /ver):
30160329_1

Character Name:
Buttons

Nation:
Windurst

Job(level)/Sub Job(level):
BLU99/RDM49

NPC or Monster or item Name:
N/A

Zone name & Coordinates (use @where):
Meriphataud Mountains (S) - K-8

ffxiah.com link (for items issues only):
N/A

Multi-boxing? (multiple clients on same connection):
No

Steps To Reproduce / any other info:
Try to activate the "Iron Portcullis" in Meriphataud Mountains (S) that serves as the entrance to Castle Oztroja (S). Nothing happens.

I searched for a reference to this in the LegionDark and Darkstar issues, but didn't find one. I did find references to Castle Oztroja (S) being accessible elsewhere, though. 

If this is an intentionally closed-off area, my apologies. I asked about it in-game, but no one on at the time was sure. 

Thanks for reading.

**Comment by R3P0FFXI** [comment]
We have done no work on the past areas this would be a DSP issue and need to be reported to them

**Comment by Midgardsormr** [comment]
Okay, thanks. I was just curious because I saw it was an area that could be entered on another server. Guess they fixed whatever need to be fixed to enter it on their own.
