### ISSUE TITLE
Aptant Scorpion 1shot bug

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#97]
**Date & Time**:  6/14/15
**Frequency**: Once
**FFXI Client Version**: 30150508_8
**Character Name**: Tarot
**Race**: Hume
**Main Job**: Pld
**Sub Job**: Rdm
**Area & Coordinates**: Attohwah Chasm
**Party or Solo**: Alliance
**NPC Name**: NA
**Monster Name**: Sargas
**Steps To Reproduce The Issue**: Unknown. I was engaged, and eventually the DSP animation for "Dieing to spike damage" appeared (White magic spell casting). I was at near full HP with buffs up, it would have been impossible for anything of the sort to kill me at that time.

Also of note, someone mentioned the bug happening again with another aptant scorpion, i think it was Aqrabuamelu. I told the person to bug report that when it happened, and i couldnt find it here to add sargas to it, and i cant recall if it was for sure aqra again, so im putting this little tidbit here if needed.

**Comment by Loki79** [comment]
does it show anything at all in the log?  So far we have been unable to reproduce this.

**Comment by PikaFox** [comment]
Nooope. I will say sargas only did it once to me so far. He also spams chat log with useless dribble like "STR 13 wore off" or something. Havnt fought in a while.

**Comment by TeoTwawki** [comment]
Does this still happen? I let Sargas beat on me for an hour today, didn't get the KO.

**Comment by R3P0FFXI** [comment]
No further reports of issues from these mobs in weeks unable to reproduce on several tests
