### ISSUE TITLE
Crafting skill

### ISSUE THREAD

**Issue by Trajik327** [LegionDark/Issues#972]

**Comment by Trajik327** [comment]
This will not let me post the screenshot of my crafting skills
Character Trajik 
Fishing 92
Woodworking 102
smithing 6
goldsmithing 21
clothcrafting 63
leather 10
bonecraft 2
alchemy 10
cooking 48
synergy 72
The screenshot can be seen on the transfer page I made

**Comment by atom0s** [comment]
Use the template for making bug reports or we will just ignore you.

**Comment by TeoTwawki** [comment]
https://guides.github.com/features/mastering-markdown/   <- read it, posting images ain't hard

**Comment by Trajik327** [comment]
look I am trying to do so the image wont load heres the screenshots I'm not
an idiot it just wont let me in zip jpeg png nothing

**Comment by TeoTwawki** [comment]
![pebkac](http://s33.postimg.org/u5tnfdjrj/Untitled_gif.png)

**Comment by TeoTwawki** [comment]
not working for just you only you = doinitwrongbrah
