### ISSUE TITLE
crafting for transfered char

### ISSUE THREAD

**Issue by rasta01** [LegionDark/Issues#973]
i want to transfer my craft skill from my old server to this server
my original name wiss n from era 
date & Time**: 
june 12/2016 10:48AM
![img_20160525_013417](https://cloud.githubusercontent.com/assets/19883315/15988629/e5d7bce2-308a-11e6-9cc6-a1d0b7341ba3.png)

**FFXI Client Version (use `/ver`)**: 
30160427_0

**Character Name**: 
shiro

**Nation**: 

bastok
**Job(level)/Sub Job(level)**: 

mnk75/war37
**NPC or Monster or item Name**: 

craftskill
**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:

**Comment by Genesis-Legion** [comment]
@rasta01 please leave a comment here next time you get online with the craft you want transferred
You can only pick one and it will be set to 100.

**Comment by Samikana** [comment]
No response after 3 days.
