### ISSUE TITLE
Trajik Craft skills transfer

### ISSUE THREAD

**Issue by Trajik327** [LegionDark/Issues#974]
want to transfer my craft skill from my old server to this server
 Image is here 
https://www.dropbox.com/s/qic2gjjozjc9hds/Untitled.gif.png?dl=0

 date & Time**: 
 june 12/2016 10:48AM

FFXI Client Version (use  /ver ): 
 30160427_0

Character Name: 
Trajik

Nation: 

bastok
Job(level)/Sub Job(level): 

99PLD/49BLM
NPC or Monster or item Name: 

craftskill
Zone name & Coordinates (use  @where ): 

ffxiah.com link (for items issues only): 

Multi-boxing? (multiple clients on same connection): 

Steps To Reproduce / any other info:

**Comment by R3P0FFXI** [comment]
@Trajik327  Ill let you pick 1 craft to be at 100 but im not making all of them 100 since ERA does not do this similar to retail.

**Comment by TeoTwawki** [comment]
we already had a rule about only 1 lv100 skill anyway

**Comment by Trajik327** [comment]
Ok um woodworking then please

**Comment by Genesis-Legion** [comment]
Trajik's woodworking skill has been set to 100.

**Comment by Trajik327** [comment]
Thanks
