### ISSUE TITLE
Stuck in metal works

### ISSUE THREAD

**Issue by MisonoFFXI** [LegionDark/Issues#975]
**Date & Time**: 06/13/2016

**FFXI Client Version (use `/ver`)**: 30160602_0

**Character Name**: Misono

**Nation**: Bastok

**Job(level)/Sub Job(level)**: Warrior

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: MetalWork near Elevator (G-8) , I can't provide @where Data , as the command does not work on my side.

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**:  I Entered Metalworks zone and as soon as I get close to the elevators , my game freeze , but I still have access to menu , I get a sky blue screen , From that point I only can /shutdown. When I log back in I am trapped in a loop since it will freeze about 10 seconds after I log back in.

**Comment by R3P0FFXI** [comment]
@MisonoFFXI login tot he website using your character data and reset your character that will pull you out of the loop

**Comment by TeoTwawki** [comment]
log into http://legiondark.com/account/profile and click "unstuck". This will move your character if your session has expired (which means character offline and won't show on websites roster anymore *this can take a full minute if you were recently in game*).

**Comment by MisonoFFXI** [comment]
Yes bit it rises another problem , I cannot do any of the Bastok Mission , that could mean I am forbidden to do further mission.

**Comment by TeoTwawki** [comment]
its  version problem - client is newer than server, you'll have to wait till the server gets updated.

**Comment by MisonoFFXI** [comment]
Yeah I tought that when I was asked for version. wish i had the previous version. Was really looking to redo those.
