### ISSUE TITLE
need a pw resest please!

### ISSUE THREAD

**Issue by TwIzTiD2469** [LegionDark/Issues#976]
**Date & Time**: 
6/15/2016 9:37PM EST

**FFXI Client Version (use `/ver`)**: 
Most up to date!

**Character Name**: 
Kamikaze

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
DRK/WAR99

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Need a PW reset. when I quit I gave this char away, but that person has also since quit. so if possible i'd like my garka back. please. 

Thanks guys, keep up the awesome work!

**Comment by Samikana** [comment]
If you gave the character away, it's unlikely we'll be able to recover it for you unless you have an email connected to the account.

**Comment by TwIzTiD2469** [comment]
i never added an email to the account as I'm fairly sure at the time there wasn't an option to do so. if any char has an email attached of mine its likely just boombastic that has 1. as it was my first char here and the galka was a mule.

**Comment by Samikana** [comment]
If there's no email on the account, we cannot recover the password for you.

**Comment by R3P0FFXI** [comment]
@TwIzTiD2469 As there is a valid email associated with the account and the password was set by someone not us which is different then what you remember we are not able to restore this account. By your own public admission you gave this account away. If you would like this account back the other person has to come back, restore it and give it back to you.
