### ISSUE TITLE
Missing Mobs within Ship rides

### ISSUE THREAD

**Issue by Trajik327** [LegionDark/Issues#977]
**Date & Time**: 
6/18/16

**FFXI Client Version (use `/ver`)**: 
30160427_0

**Character Name**: 
Trajik

**Nation**: 
Bastok

**Job(level)/Sub Job(level)**: 
90rdm/45sch

**NPC or Monster or item Name**: 
All Mobs in zone

**Zone name & Coordinates (use `@where`)**: 
X-0 Y--7 Z-13 (213)
Ship to and from mhaura/selbina

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
No solo account

**Steps To Reproduce / any other info**: 
Consistant problem possibly 4 times back and forth no mobs spawning at all

**Comment by TeoTwawki** [comment]
Thsi is currently normal for Darkstar - its not a bug, its unimplemented content.

**Comment by TeoTwawki** [comment]
(I'm especially sad about no Sea Horror and no Pirates)

**Comment by Trajik327** [comment]
oh ok wasn't sure since mobs where listed on our item search ty for update I rode that for an hour or so lol

**Comment by TeoTwawki** [comment]
Sorry bout that. They exist in dsp's database so the site tools show them, even thought you can't reach them/they don't pop.

**Comment by Trajik327** [comment]
No worries
