### ISSUE TITLE
renik af+1 reforged Scholar hand error

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#978]
**Date & Time**: 6/19/16 5pm

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: aurel

**Nation**: sandoria

**Job(level)/Sub Job(level)**: sch99/RDM49

**NPC or Monster or item Name**: renik

**Zone name & Coordinates (use `@where`)**: x:-15  y:0  z.38  (244) upper jeuno

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/27984/acad-bracers-1

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 
i have trade
http://www.ffxiah.com/item/27963/acad-bracers   +5 rems chap 3,and i obtain  
http://www.ffxiah.com/item/27981/foire-dastanas-1
![img_20160619_192633](https://cloud.githubusercontent.com/assets/13084662/16180534/3fcc5f04-365e-11e6-8023-3494756a53b2.png)

![img_20160619_194357](https://cloud.githubusercontent.com/assets/13084662/16180547/b25666be-365e-11e6-94d1-f1c499556062.png)

**Comment by R3P0FFXI** [comment]
@Aurelcassy This issue is resolved in the update, @Samikana @Genesis-Legion please issue him the correct item

**Comment by Genesis-Legion** [comment]
Aurel was given his item.
