### ISSUE TITLE
Goblin Veterinarian bug

### ISSUE THREAD

**Issue by puffer1221** [LegionDark/Issues#98]
**Date & Time**:  15/06/2015, 12:42:00 pm Gmt
**Frequency**: Constant
**FFXI Client Version**: 30150508_8
**Character Name**: Anofrei
**Race**: Hume
**Main Job**: Sch 
**Sub Job**: Rdm 
**Area & Coordinates**: Pso'Xja  (H-10 tower), X: 169 Y:16 Z:-367 (179)
**Party or Solo**: Solo
**NPC Name**: Not applicable
**Monster Name**: Goblin Veterinarian
**Steps To Reproduce The Issue**: I had buffed up using, Blink/Stoneskin/Protect 3/Hailstorm/shell 2/exp band/signet/Addendem: Black and @regen. i used Cryohelix on the goblin pet then followed it up with Stone 3 and Blizzard 2 for the kill, i then took a knee to get some mp back and waited for it to resummon its pet, now when ever it tried to resummon it does the animation for call beast but nothing spawns and it just keeps repeating the same action. It does seem to summon it after about 4-5 mins though.

**Comment by TeoTwawki** [comment]
I think the IDs are off in DarkStar..Related issue on their tracker: https://github.com/DarkstarProject/darkstar/issues/1582

**Comment by TeoTwawki** [comment]
This probably will not get fixed until someone pull requests the corrections for that DarkStar issue.

**Comment by Loki79** [comment]
Been forwarded to dsp.  Closing from our Que since over 30 days old.
