### ISSUE TITLE
Pedagogy loafers +1 :not have fast cast and not have haste +3

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#980]
Date & Time: 6/21/16 5pm

FFXI Client Version (use /ver): 30160329_1

Character Name: aurel

Nation: sandoria

Job(level)/Sub Job(level): sch99/RDM49

NPC or Monster or item Name: 

Zone name & Coordinates (use @where):

ffxiah.com link (for items issues only): http://www.ffxiah.com/item/27367/peda-loafers-1

Multi-boxing? (multiple clients on same connection): yes

Steps To Reproduce / any other info:http://www.ffxiah.com/item/27367/peda-loafers-1

Steps To Reproduce / any other info: Hello, no solution to this because I have more equipment with the same problem and do not know if I report it??,,,,----,Pedagogy loafers +1 :not have fast cast and not have haste +3

**Comment by R3P0FFXI** [comment]
@Aurelcassy This is only missing haste +3 it does currently have fastcast on it. keep in mind there is a hardcap to haste built into the client/dsp.

**Comment by R3P0FFXI** [comment]
@Aurelcassy this has been resolved in DSP and is currently live
