### ISSUE TITLE
Items missing from server transfer due to stack size differences

### ISSUE THREAD

**Issue by Lurtz93** [LegionDark/Issues#981]
**Date & Time**: 1:55pm EDT

**FFXI Client Version (use `/ver`)**: 30160427_0

**Character Name**: Lurtz

**Nation**: Bastok

**Job(level)/Sub Job(level)**: MNK99/THF45

**NPC or Monster or item Name**: Orthrus's Claw

**Zone name & Coordinates (use `@where`)**: N/A

**ffxiah.com link (for items issues only)**: 

http://www.ffxiah.com/item/3287/orthruss-claw/?stack=1

**Multi-boxing? (multiple clients on same connection)**: not when I did the transfer

**Steps To Reproduce / any other info**: 

I requested a server transfer on June 1, which R3P0 completed. When I logged in, I noticed the stack of 75 Orthrus's claws I had was reduced to 12. I suspect this is because of the difference in stack sizes between here and retail. Retail can stack up to 99 (see ffxiah link) while the legiondark database tool indicates the claws can stack up to 12. 

Can you restore these for me? 

I would have included a screenshot from retail character as proof but since I created the transfer file, retail has updated and so I don't want to update the client and mess things up for my legion account. 

If you need a screenshot, I can probably figure update client and then roll back my data files to pre-update status. 

If you can't/won't, it's fine, I can think of multiple reasons why not (not worth your time, etc.) If that's the case just let me know. 

Thanks for maintaining this server!

**Comment by R3P0FFXI** [comment]
@Lurtz93 Unfortunately the server migration process is not 100% At this point in time we will not restore the mats as we have not restored them from any user previously before your request. It would be an unfair policy to begin individual item restorations at this time. You would need to farm the claws.

**Comment by Nususu** [comment]
Thanks for letting me know!

**Comment by Lurtz93** [comment]
Thanks for letting me know!
