### ISSUE TITLE
Cruor bug

### ISSUE THREAD

**Issue by fgebony** [LegionDark/Issues#983]
**Date & Time**: 6/22/16 5:13

**FFXI Client Version (use `/ver`)**: 30160427_0

**Character Name**: Ebony

**Nation**: Windurst

**Job(level)/Sub Job(level)**:99THF/49DNC 

**NPC or Monster or item Name**: Atrociraptor

**Zone name & Coordinates (use `@where`)**:abyssea-miseraux  x522 y15 z-445 (141)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**:  Aggro'd Atrociraptor, ran for my life died, reraised from signet after death as it was depopping, received cruor as if it was kill

-EDIT- mob doesn't have to depop, cruor is granted upon reraise.

**Comment by Baucant** [comment]
This has always happened I think it has to do with the exp gain (raise gives back some of exp lost to death) and cruor is give when exp is gained inside of abby

**Comment by TeoTwawki** [comment]
@Baucant thats not upposed to happen, in the same way that gaining conquest points does nto happen on raising.


@LegionDark/thebosses de-assining myself, as I unfortunatly have been unabel to give this teh attention it needs. Someone will need to confirm exactly wtf is going on (how to reliably 100% reproduce) and take it to darkstar.

**Comment by Hazed69** [comment]
Can confirm on any raise effect in which you lost exp as a result upon accepting raise from either signet or rr spell/items and recovering some exp it acts as if you have killed a mob gaining the exp and cruor as a result. I have not checked on conquest but will do so shortly for you guys

**Comment by TeoTwawki** [comment]
> I have not checked on conquest but will do so shortly for you guys

@Hazed69 soooooo about that...

**Comment by Raelious** [comment]
You do not receive any CP after dying and raising in zones for conquest points. This bug only seems present in abyysea zones.

**Comment by TeoTwawki** [comment]
https://git.io/vHytf
