### ISSUE TITLE
Voidwatch quest line not starting properly

### ISSUE THREAD

**Issue by MisonoFFXI** [LegionDark/Issues#984]
**Date & Time**: 06/23/2016 01:24am GMT+2

**FFXI Client Version (use `/ver`)**:  30160602_0

**Character Name**: Misono

**Nation**: Bastok

**Job(level)/Sub Job(level)**: SAM99/WAR49

**NPC or Monster or item Name**: Voidwatch Officer

**Zone name & Coordinates (use `@where`)**:  X-41 Y-5 Z218 (142)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: After doing Wing of the Goddess Quest , up to "Better part of valor" I still do not gain access to VW quest line. I followed religiously the wiki , Which says after competing The fighting four I should be able to start voidwatch. I spoke to voidwatch officers accross all 3 nation , I just get "DEBUG: Initial check abysite started" then nothing. No key items or any option to choose from.

**Comment by TeoTwawki** [comment]
look at your client version. this isn't going to work right for you till the server gets update.
