### ISSUE TITLE
Nagi, Terpsichore & Gastraphetes Missing

### ISSUE THREAD

**Issue by Nususu** [LegionDark/Issues#985]
**Date & Time**: 12:15pm EST

**FFXI Client Version (use `/ver`)**: 30160427_0

**Character Name**: Nususu

**Nation**: Bastok

**Job(level)/Sub Job(level)**: NIN99/DNC49

**NPC or Monster or item Name**: Nagi, Gastraphetes, Terpsichore

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

http://www.ffxiah.com/item/19003/nagi
http://www.ffxiah.com/item/18989/terpsichore
http://www.ffxiah.com/item/19001/gastraphetes

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: No ZNM drops the above mentioned items. Looks like they should drop from Nosferatu (according to forums).

**Comment by ragnarokLD** [comment]
did you check http://www.legiondark.com/db/monsters/17056157/Nosferatu ?

**Comment by Nususu** [comment]
Yes I did. Every other ZNM t3 drops lvl 75 variant of mythic. Nosfetatu, according to the database link, does not. 

http://legiondark.com/forums/viewtopic.php?f=27&t=8&p=8&hilit=Nosferatu#p8

Every other t3 ZNM on this list actually drops the mythics listed there, seems nosferatu is the exception.

**Comment by Dimmabr** [comment]
Can I farm terpsichore for now?

**Comment by R3P0FFXI** [comment]
@Nususu Issue resolved in Maint Yesterday
