### ISSUE TITLE
Shabti Cuisses gives no stats

### ISSUE THREAD

**Issue by ragnarokLD** [LegionDark/Issues#986]
**Date & Time**: 24 June 2016
**FFXI Client Version (use `/ver`)**: 30160329_1
**Character Name**: Ragnarok
**Nation**: San d'oria
**Job(level)/Sub Job(level)**: WAR99/SAM49
**NPC or Monster or item Name**: Shabti Cuisses
**Zone name & Coordinates (use `@where`)**: n/a
**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/28178/shabti-cuisses
**Multi-boxing? (multiple clients on same connection)**: n/a
**Steps To Reproduce / any other info**: Equipment gives no stats.

**Comment by R3P0FFXI** [comment]
@ragnarokLD this has been resolved and will be included in our next maint

**Comment by R3P0FFXI** [comment]
Issue resolved in todays maint
