### ISSUE TITLE
Can't eat Kitron Macaron

### ISSUE THREAD

**Issue by Luxxord** [LegionDark/Issues#987]
**Date & Time**: June 25th

**FFXI Client Version (use `/ver`)**: 30160602_0

**Character Name**: Luxxord

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: Kitron Macaron

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/5781/kitron-macaron

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: Bought it off AH once I started training Goldsmithing and I can't eat it, other food off the AH works just fine.

**Comment by TeoTwawki** [comment]
https://github.com/LegionDark/Issues/issues/777
