### ISSUE TITLE
Crafting Skill Unlockage

### ISSUE THREAD

**Issue by DanieC89** [LegionDark/Issues#988]
**Date & Time**:  25/06/2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Danie

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**:  WHM99/SCH49

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: X:-4 Y:-2 Z:14 (66)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 

I've been asked to post a ticket to get a crafting skill unlocked so here it is and here is the link to my original tranfer post~ http://legiondark.com/forums/viewtopic.php?f=39&t=1427  Looking to get Goldsmithing unlocked :) Thanks for any help~! :3

**Comment by Genesis-Legion** [comment]
Restored player's goldsmithing.
