### ISSUE TITLE
Odjin craft skills

### ISSUE THREAD

**Issue by Odjin** [LegionDark/Issues#989]
**Date & Time**: 6/25/16, 1150

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Odjin

**Nation**: San'doria

**Job(level)/Sub Job(level)**: COR75/DNC37

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: Original transfer app with crafting info, I'd like woodworking please ^^ http://legiondark.com/forums/viewtopic.php?f=39&t=1428

**Comment by Genesis-Legion** [comment]
Restored player's woodworking.
