### ISSUE TITLE
Karieyh Haubert +1

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Issues#99]
Date & Time: 6/14/2015
Frequency: 
FFXI Client Version: 30150508_8
Character Name: Daedrik
Race: Elvaan
Main Job: PLD
Sub Job: RDM
Area & Coordinates: 
Party or Solo: 
NPC Name:  
Monster Name :
Steps To Reproduce The Issue:  Upgrade Karieyh Haubert and watch it sit in your inventory :'( .

Piece is White and equip-able, it's just that nothing happens when you click it to equip.

**Comment by Loki79** [comment]
nothing happens like fireworks don't go off?  No Stats? cant equip it?

**Comment by Loki79** [comment]
fixed.  had to fix in dsp so will come in with maint,.
