### ISSUE TITLE
Renik upper Jeuno Error

### ISSUE THREAD

**Issue by yelari** [LegionDark/Issues#990]
**Date & Time**: 25/6/2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: yel

**Nation**: sandoria

**Job(level)/Sub Job(level)**: red mage

**NPC or Monster or item Name**: Renik Upper Jeuno

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: to trade Vitivation Boots (red mage) and 5 Rems Chapters 1 on renik, the reward is Spaekona's Sabots +1(feet BLM)

**Comment by R3P0FFXI** [comment]
@yelari this is fixed int eh next update, please post a pic of yourself tossing the incorrect item. @Genesis-Legion @Samikana please give user correct item.

**Comment by yelari** [comment]
ok 
![yel_2016 06 27_165758](https://cloud.githubusercontent.com/assets/20144190/16397199/8791044a-3c88-11e6-9ba3-f1f2a8b98af2.png)

**Comment by PikaFox** [comment]
Gave player proper item.

**Comment by yelari** [comment]
thank you
