### ISSUE TITLE
Reforged Relic for WHM still not reforge

### ISSUE THREAD

**Issue by Aurelcassy** [LegionDark/Issues#991]
Date & Time:25/6/16

FFXI Client Version (use /ver):  30160329_1

Character Name: Myeva

Nation: Sandy

Job(level)/Sub Job(level): WHM99/RDM49

NPC or Monster or item Name: Moogle (moogle in tavnazian safehold)

Zone name & Coordinates (use @where): Tavnazian safehold -- X:12 Y:-9 Z:0 (29)

ffxiah.com link (for items issues only): http://www.ffxiah.com/item/26804/piety-briault

Multi-boxing? (multiple clients on same connection): yes 

Steps To Reproduce / any other info: Trade Cleric Briault+2 with 25 Aptant:Tachus to moogle, nothing happens, no Reforged relic109

**Comment by R3P0FFXI** [comment]
@Aurelcassy yeah because the fix is not live yet so why do you continue to do the quests when we have not told you its fixed?

**Comment by Aurelcassy** [comment]
sorry , I wait after update for reforged
