### ISSUE TITLE
Heep Crafts to be imported

### ISSUE THREAD

**Issue by Heepster03** [LegionDark/Issues#992]
Date & Time: June 26th, 2016; 0930

FFXI Client Version (use /ver): 30160329_1

Character Name: Heep

Nation: Bastok

Job(level)/Sub Job(level): THF99/DNC49

NPC or Monster or item Name:

Zone name & Coordinates (use @where):

ffxiah.com link (for items issues only):

Multi-boxing? (multiple clients on same connection):

Steps To Reproduce / any other info:

I was told to place a ticket for my crafts to be restored. 

Here is my transfer application with my picture containing crafts: http://legiondark.com/forums/viewtopic.php?f=37&t=1601

Since I have only 1 100 craft, are the other subcrafts imported as well? Thanks!

**Comment by Halkuras** [comment]
Apparently my username is different than what I have for forums. Hope that's ok.

**Comment by Heepster03** [comment]
Heepster was taken so had to add a Lil extra

**Comment by Genesis-Legion** [comment]
Crafts transferred
