### ISSUE TITLE
Voidwatch Ashen Abyssite II wont upgrade bug

### ISSUE THREAD

**Issue by thicksz** [LegionDark/Issues#995]
**6-27-16 11:07 est**: 

**FFXI Client Version (use `/ver 30160329_1`)**: 

**Hickss**: 

**San d'Oria**: 

**Job(99)/Sub Job(49)**: 

**Kieran Vw Npc**: 

**NORG (X:0 Y:0 Z:15)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing Yes  (Kimmi & Vajayjaykiller)**: 

**i have did this full Path to and and started over on Hickss and Kimmi but now it wont give me Cs to get T3 ... so i went out 2 more times on this Path hitting all Npc in right order be4hand . Did all Nm in order as posted and still NO Cs to get T3.. started fresh on Vajayjay Step by Step New with Hickss and kimmi in Pt And vajayjaykiller Got her  Cs to T3.. BUT hickss and Kimmi DID NOT they are still stuck on T2 of this path i have been over all Npc to mach sure need help to fix bug with hickss and kimmi plz will not get Cs to upgrade to T3 and i dont want to do this path 4th time just to be stuck at T2 **: with Hickss&kimmi i did this full path with NP at all just after it reset the Tir and started over this happen

**Comment by R3P0FFXI** [comment]
@thicksz then you missed something, there are also several issues with multiboxing that can happen including the missing KI which have been an issue on every DSP server. You run the risk of not getting KI or upgrades when this happens and no we will not manually give them to you. Take a single character out after logging all of your characters off and make sure FFXI is closed. Login just Hickss and try to get the KI. Should this not work an error message is usually printed out we will need this error message to diagnose.

**Comment by thicksz** [comment]
did as u posted still not working the error im getting foe all the NPC in path is < this menu doesn't work yet> SYStemMessage.... and i have not missed anything i have done this full VW path to full and reset it this is #2 time im doing it i followed the very same steps. this is the 3rd time i did all nms over up to T2... i can send screen shot if it will help

**Comment by thicksz** [comment]
ok on kimmi im not getting error npc just telling here to go see a Vw npc hmmm maybe

**Comment by thicksz** [comment]
i think kimmis is missing kills and the both on hickss&kimmi did do something SO going to do then over on each toon one at a time and see if thats it cuz right now hickss is getting menu dosent work but on kimmi im not gettting that same Msg let ya know ... thanks

**Comment by thicksz** [comment]
OK today i just did full run Vw of Ashen T2 with on Kimmi log on to server full time NO hickss noe VajayAt all i did all the NM is order AND still up upgrade to T2 ... And u said to me u wont give me the T3 after all the work i have been dong SO im just stuck on T2 Ashen ... if u wont push me to T3 then plz reset it back to T1  ashen Plz so i can try this over again. I am NOT a GM so i cant fix it myself and i should not have be stuck on T2 if im doing quest as its posted on forums STEP by STEP with only one toon loged in server ...

**Comment by R3P0FFXI** [comment]
@thicksz were either of the characters logged on at all while Kimmi was in game. If they were and you did not log Kimmi out at all and completely close FFXI then you still have open ports as DSP does not close them. This questline works with no issues it has been tested numerous times. We will not push you to T3 because doing so causes issues and resetting is a pain in the ass so we need to see where your stuck.

Please post your exact messages.

**Comment by thicksz** [comment]
ok look at this form what i see the NPC in kaz and rebo are telling me i need to go kill Nm in T1 but yet i cant pop T1  cuz i have Ki T2 Ashen... could this be it and if sooo why did it give me a T2 if i need to still kill NMs on T1 from what NPC are telling  > come to me in game and look if u think im Bs- ing  you.. i have screen pic of it i will send in or u can log on my toon and see for your self >>

**Comment by thicksz** [comment]
ok now i think i have found out what is wrong.. Rebo NPC Gushing Spring is telling me i still need to go kill NMs in his path ... and as for KAzam path that npc i need to go Kill them 3 NM in that path ....BUT HER  IS I have AShen T2 KI i cant go back and pop them T1's to find out if this will fix it becuz there T1 and im on T 2 ??? ...how the hell did i get T2 if its saying i still need to kill T1 ... so yes maybe muitl box did this im sure it did BUT how do i fix it  with a T2 Ki in my list and cant pop the T1

**Comment by TeoTwawki** [comment]
> how the hell did i get T2 if its saying i still need to kill T1

My thoughts exactly. It is literally not possible to have upgraded with finishing the quests first, except if a GM pushed you past a spot they thought was broken (in which case I would bludgeon them to death with my crazy mind powers _waggles fingers_).

> Please post your exact messages.
Don't paraphase, post THE EXACT TEXT all all these npcs. Effing screenshot it. Show me your voidwatch key items too.

**Comment by thicksz** [comment]
hope im doing this right lol never sent Screen pix on here but just ran to each npc and took pic and took pic of Ki list ..


![hickss_2016 06 29_215651](https://cloud.githubusercontent.com/assets/17992515/16474542/bbdd41e6-3e45-11e6-80c8-7d7c54291d9f.png)
![hickss_2016 06 29_215712](https://cloud.githubusercontent.com/assets/17992515/16474548/c354be18-3e45-11e6-93d5-bc3664a8f99c.png)
![hickss_2016 06 29_215853](https://cloud.githubusercontent.com/assets/17992515/16474553/c6554420-3e45-11e6-9114-343266d94c81.png)
![hickss_2016 06 29_215915](https://cloud.githubusercontent.com/assets/17992515/16474559/ca3a9ca2-3e45-11e6-93d3-ab91526eae1a.png)

**Comment by TeoTwawki** [comment]
Thank you. Does Keiran and Gilgemesh (both in norg) behave similarly?
And sorry to ask for more but I need your quest menu showing me if the quests from these 2 also. Normally I'd make the server tell me but I can't log in for the time being.

Copy pasted form my own post in the other report:
There are a metric ton of user created possibilities to rule out and we go to the most common problem first. The shear number of times someone has not read a message that told them exactly what was wrong is staggering, as is the number of items a single kill or single dialog/cut scene event failed to "count" because of multi boxing. My hands have been fairly tied by rl lately, I will be discussing wtf needs checked with other GMs soon. Thank you for your continued patience.

**Comment by TeoTwawki** [comment]
@R3P0FFXI in his screenshots, my debug messages are not present. This tells me quite a few things, so I belive I can track down what happened to these characters and leave instructions for GMs on how to correct it. Will discus with you on irc later.

**Comment by thicksz** [comment]
awesome thank u .. no rush guys if u still want i can go get pic of Npc post in norg but yes the same 
![kimmi_2016 06 29_221817](https://cloud.githubusercontent.com/assets/17992515/16474973/cca14cb8-3e48-11e6-8472-75b645b85931.png)   that was in norg then i went to KAz 
![kimmi_2016 06 29_222046](https://cloud.githubusercontent.com/assets/17992515/16474991/e3ed1456-3e48-11e6-9115-d21f4768f6c3.png)   then 
![kimmi_2016 06 29_222105](https://cloud.githubusercontent.com/assets/17992515/16475000/ef15eff6-3e48-11e6-9c08-766996eb9094.png)       then rebo  same 
![kimmi_2016 06 29_222300](https://cloud.githubusercontent.com/assets/17992515/16475011/fc6a4ae4-3e48-11e6-806e-7d3971ec383a.png)     then 
![kimmi_2016 06 29_222315](https://cloud.githubusercontent.com/assets/17992515/16475014/06cf5b78-3e49-11e6-8e39-0eae73c2c7b3.png)

**Comment by TeoTwawki** [comment]
oh..thats showing those debug messages. Those are what I was hoping to see before. hmm

its the quest menu I need, not the KI menu.

**Comment by thicksz** [comment]
im looking but i dont see where to look in quest menu

**Comment by thicksz** [comment]
ooo think i found spot just min

**Comment by TeoTwawki** [comment]
outlands or other area's probably.

**Comment by bonez69** [comment]
i have the same txts with npcs as hickss  hope there a fix or w/e tks again

**Comment by thicksz** [comment]
![hickss_2016 06 29_224519](https://cloud.githubusercontent.com/assets/17992515/16475314/7547d57e-3e4b-11e6-9c44-84068c7dead9.png)

**Comment by thicksz** [comment]
![hickss_2016 06 29_225042](https://cloud.githubusercontent.com/assets/17992515/16475365/0c3ca716-3e4c-11e6-94e2-310fe2074ff1.png)

**Comment by TeoTwawki** [comment]
Pretty sure I know -which- of the vast number of multibox collisions you hit now. Will have 1st available GM adjust you.

**Comment by TeoTwawki** [comment]
Check gilgemesh for me first, just in case, before we proceed.

**Comment by TeoTwawki** [comment]
Gilgemesh has scenes which modify Keiran's responces.

**Comment by thicksz** [comment]
woot awesome ty when u free Np thnaks a lot ...u rock Teo .... np goign to him now for ya

**Comment by thicksz** [comment]
this is on hickss



![hickss_2016 06 29_225711](https://cloud.githubusercontent.com/assets/17992515/16475483/e9d537e6-3e4c-11e6-8580-733290c360d8.png)

**Comment by thicksz** [comment]
Kimmi  is same 


![kimmi_2016 06 29_225830](https://cloud.githubusercontent.com/assets/17992515/16475514/1addc5a6-3e4d-11e6-925d-5e42e929f55a.png)

**Comment by TeoTwawki** [comment]
kk

**Comment by TeoTwawki** [comment]
Somehow you have _Border Crossing_ completed, when completing it requires both _Zepwell Detour_ and _Elshimo list_ to be finished first. In the current codebase, this is physically impossible. It was only possible during a brief window back when someone launched voidwatch "chapters" before they were ready, and to happen after this and be where you are at requires a whole slew multi box errors ina  row. If you are a gambling man, you should definitely buy some lotto tickets. You had better chances at that then these conditions all lining up just right for you to somehow be able to flag _Skyward Ho_ and yet not done with Zepwell and Elshimo. :scream:

**Comment by TeoTwawki** [comment]
Jus' sayin'

**Comment by TeoTwawki** [comment]
okaaaaay. As I dug into this to write out the how to for the other GMs, I saw various inconsistencies and realized you gave me screenshots from multiple characters and that they don't have the same issue. You can't show me me part of it on one char and part of it on another and expect me to seriously figure out the real situation here -\_- according to the quest status and variables involved this is NOT what I thought it was. God I am so pissed off now. I just overheated my laptop trying to stay in game long enough to look up what you actually have.

**Comment by TeoTwawki** [comment]
Kimmi has zero kills credited toward quest that are flagged as in progress, rather than completed. The quests after, are not yet flagged at all.

**Comment by TeoTwawki** [comment]
Hickss and Vayjayjay both have expected vars and quest status for completed quests. Your upgrades don't come from NPCs once you've beaten the quest line, they happen form the bitmask of the variable registering as full (all binary ones, its like knocking over domino's).

**Comment by TeoTwawki** [comment]
Check your chars KI's when you are back in game. Kimmi need to do the quests. Hickss and Vajayjaykiller should be fine now.

**Comment by TeoTwawki** [comment]
@R3P0FFXI anyone else that reports this, make them re-kill any of :
Cath Palug in The Sanctuary of Zi'Tah
Modron in The Boyahda Tree
Mimic King in Ro'Maeve
..I have those checking for various forms of stupid and rechecking what tier they belong on.

**Comment by thicksz** [comment]
awesome thank soo much sorry for the headache... alll loooks fine and np with kimmi ill do it over keep ya posted ...

**Comment by thicksz** [comment]
soo i should not multi box u think when doing VW ? would be the best way for this not to happen again

**Comment by thicksz** [comment]
Teo its still not working with kimmi hicks works fine but today i just did kimmi run over to get pass T2 and NPC just keep telling we same info i need to go kill Nm's in T1 but i cant pop them Cuz ki is T2 ashen...

**Comment by R3P0FFXI** [comment]
@thicksz we have it programmed so that you need to start over to redo T1, this is normal and expected

**Comment by thicksz** [comment]
Sorry R3POFFxi let me post this better .. when Teo told me hickss was ok i when on and did him Solo and all was fixed and Teo siad i had to redo Nm in path over but i never did her over till today and she still having same thing going on to where she cant get pass Ashen T2 cuz the npc are telling me i neeed to go out and do T1 of AShen but i have  T2 ki in list ... and i found out kimmi has White stratum abyssite VI <had long time> but wont let me pop any of the T6 over again .. i have 36 stones .. and we cant end T6 cuz Npc is not working in Tavnazian safehold .. was just letting Teo know kimm is still bug from be4 but all is good ill wait till update rolls out no rush

**Comment by TeoTwawki** [comment]
kimm legitly was not bugged at all when checked before - she simply had ZERO of the requirements DONE at all because she wasn't even at the same stage as the other 2. If she's bugged now, I need new details and will have to get with you in game to check her variables.

**Comment by Samikana** [comment]
No response when requested details.  Closing.
