### ISSUE TITLE
level sync

### ISSUE THREAD

**Issue by atts2002** [LegionDark/Issues#996]
level sync deactivates on its own
also exp while under level sync is alot lower than before
**Date & Time**: 28 june 2016

**FFXI Client Version (use `/ver`)**: 

**Character Name**: 

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**:

**Comment by Genesis-Legion** [comment]
Template incomplete. Fill out the rest.
