### ISSUE TITLE
Augustas craft transfer

### ISSUE THREAD

**Issue by Aelromi** [LegionDark/Issues#997]
**Date & Time**: 6/28/16 11:12am

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Augustas

**Nation**: Sandoria

**Job(level)/Sub Job(level)**: 77Rdm/Nin

**NPC or Monster or item Name**: 

**Zone name & Coordinates (use `@where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Woulld like to have Cooking craft transferred. Here's the link to my fourm post.  Thanks
http://legiondark.com/forums/viewtopic.php?f=37&t=1607

**Comment by PikaFox** [comment]
55 cooking restored.
