### ISSUE TITLE
Serpentes Sabots unobtainable due to missing NM

### ISSUE THREAD

**Issue by Nususu** [LegionDark/Issues#998]
**Date & Time**: 1:34 EDT

**FFXI Client Version (use `/ver`)**: 30160427_0

**Character Name**: Nususu

**Nation**: Bastok

**Job(level)/Sub Job(level)**: NIN99/DNC49

**NPC or Monster or item Name**: Serpentes Sabots & Brooder (NM)

**Zone name & Coordinates (use `@where`)**: Abyssea La Theine

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/14085/serpentes-sabots

**Multi-boxing? (multiple clients on same connection)**: yes

**Steps To Reproduce / any other info**: 

Since the NMs spawned by demilune abyssite are not implemented, some items are currently unobtainable. Could these items be moved to other NMs?

**Comment by R3P0FFXI** [comment]
@Nususu At this time we have no plans to add this NM or make the items from said NM available to anyone as half the mods for the item do not even exist in DSP. All it would have would be DEF: 14
HP +13, MP +13

**Comment by TeoTwawki** [comment]
latents aren't mods. just fyi.

**Comment by Nususu** [comment]
Thanks for the response/info.
