### ISSUE TITLE
Kieran

### ISSUE THREAD

**Issue by bonez69** [LegionDark/Issues#999]
**Date & Time**: 6-28-16 10am hst

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Yin

**Nation**: Sandy

**Job(level)/Sub Job(level)**: 
blu99/rdm49

**NPC or Monster or item Name**: 
Kieran Vw npc

**Zone name & Coordinates (use `@where`)**: 
Norg (X:1 Y:0 Z:15)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes 

**Steps To Reproduce / any other info**: 
same prob as Hickss have done ashen T1~t3 no prob reset and redid and now can not upgrade past T2 on both my char Yin and Yang did what was posted logged only 1 Char on and did all 3 NM on T2 went back and talk to Kieran and i get systemMessage "this menu doesn't work yet." on both my toons.

**Comment by R3P0FFXI** [comment]
@bonez69 because you guys are at the wrong NPC or missing something there is no issues with the questline. You are multiboxing and most likely did not get a clear.

**Comment by bonez69** [comment]
i logged on only 1 char nothing else and redid all 3 nms t2  i got systemMessage **"this menu doesn't work yet."** no other char was on and then i logged off completely and logged on the other 1 and did all 3 nms t2 and got same systemMessage . and went to talk to all 3 npc in rabo and kazam and norg just incase it missed something, and same thing . tks for ur time

**Comment by thicksz** [comment]
OK here we go WE DID IT ALL OVER AGAIN AND AGAIN WITH ONLY ! TOON LOGED ON other toons booted up at all u keep saying its working but others are saying something. WE are not saying that Multi box did not do this. WE are asking 4 help to get it fixed we did as u asked up 2 times over step 4 step each NPV each VW NM .. but yet u always come back saying its working right and its us....  Just like the VW windy path is u have to kill Nm 3 times ---> to get upgrade.. the point of this is to help out not.. we can see what we are missing as u say we have been over all the CS and Nm fight ..........WE have done this the first time with NP this startyed when we reset Path and got to T2 did all 3 Nm go get CS but cant .. and again i stop muitl box i only log ONE toon on from start ONE thats all no other POL or anything like that at all running ...

**Comment by bonez69** [comment]
tks Teo for taking the time to answer ok i understand loggin in 1 char wont fix the prob so what do u recomend i do then. i have done all the T2 mobs twice to make sure i get the win on 1 char logged in only if i missing anything then im lost to what i should do next. Plz advise what u think i should try cuz the only thing i can think is missing is nm kill is not being recorded i cant be missing npc or i would not be able to pop ??. just a reminder this is the 2nd time im doin Ashen path on both toons could there be a problem with reseting the path? just putting it out there idk. Tks again for ur time.~

**Comment by TeoTwawki** [comment]
@thicksz stfu

@bonez69 resetting can do more harm than good, if there is a bug in one of the NM scripts we'd never find it if we reset and if we never got all the info about the currently effected chars. There are a metric ton of user created possibilities to rule out and we go to the most common problem first. The shear number of times someone has not read a message that told them exactly what was wrong is staggering, as is the number of items a single kill or single dialog/cut scene event failed to "count" because of multi boxing. My hands have been fairly tied by rl lately, I will be discussing wtf needs checked with other GMs soon. Thank you for your continued patience.

**Comment by bonez69** [comment]
tyvm for all u do Teo

**Comment by TeoTwawki** [comment]
Question. do you realize the NPCs don't handle the upgrades if you already cleared and are doing repeats?

**Comment by TeoTwawki** [comment]
Check your chars KI's when you are back in game.

**Comment by bonez69** [comment]
yin is on ashen T3 yang is still on ashen t2

**Comment by TeoTwawki** [comment]
check yang now

30.06.2016, 00:29, "bonez69" <notifications@github.com>:

**Comment by bonez69** [comment]
yep all good now on yang tyvm Teo
